#+TITLE: Definitions

* Overview
https://en.wikipedia.org/wiki/English_grammar
https://en.wikipedia.org/wiki/Clause
https://en.m.wikipedia.org/wiki/List_of_Latin_legal_terms
https://en.m.wikipedia.org/wiki/Kill_chain
https://wiki.haskell.org/Pointfree
https://wiring.readthedocs.io/en/latest/rationale.html
https://en.m.wikipedia.org/wiki/Glossary_of_fencing
https://zampaniosim.fandom.com/wiki/Cognitohazard
https://scp-fanon.fandom.com/wiki/Category:Cognitohazard
https://en.wikipedia.org/wiki/Information_hazard
https://docutils.sourceforge.io/docs/ref/rst/introduction.html#goals
* Main
** General
*** Modalities
Alethic     - Possibility
Deontic     - Permission
Axiological - Value (intrinsic/extrinsic)
Epistemic   - Knowledge
Doxastic    - Belief
Boulomaic   - Desire
Temporal    - Time
*** Greek
α Α   - alpha
β Β   - beta
γ Γ   - gamma
δ Δ   - delta
ε Ε   - epislon
ζ Ζ   - zeta
η Η   - eta
θ Θ   - theta
ι Ι   - iota
κ Κ   - kappa
λ Λ   - lambda
μ Μ   - mu
ν Ν   - nu
ξ Ξ   - xi
ο Ο   - omicron
π Π   - pi
ρ Ρ   - rho
σ Σ ς - sigma
τ Τ   - tau
υ Υ   - upsilon
φ Φ   - phi
ψ Ψ   - psi
ω Ω   - omega
*** Operators
⟘ - bottom / false
⟙ - Top / true

∧ - and
∨ - or

∴ - therefore, qed.
⊢ - syntactic consequence, sequent, (typing) judgement
⊨ - semantic consequence

⨂ - (linear logic) Multiplicative Conjunction
⅋ - (linear logic) Multiplicative Disjunction
& - (linear logic) Additive Conjunction
⨁ - (linear logic) Additive Disjunction

⊂ - Subset
⊃ - Superset
∪ - union
∩ - intersection
⋀ - lattice join
⋁ - lattice meet

□ - (modal logic)
◇ - (modal logic)

⨯ - cartesian product

∫ - Integral
Δ - Delta
Σ - Sum
Π - Product
μ - The Mean
σ - Standard Deviation
ρ = Correlation Coefficient

n! - factorial(n)
*** Software Methodology
**** Reproducibility Manifesto
[[https://lorenabarba.com/gallery/reproducibility-pi-manifesto/][link]]

1) teach my graduate students about reproducibility.
2) research code (and writing) is under version control.
3) always carry out verification and validation (V&V reports are posted to figshare)
4) For main results in a paper, share data, plotting script & figure under CC-BY
5) upload the preprint to arXiv at the time of submission of a paper.
6) release code at the time of submission of a paper.
7) add a "Reproducibility" declaration at the end of each paper.
8) keep an up-to-date web presence.

**** Science Code Manifesto
[[https://web.archive.org/web/20160218093215/http://sciencecodemanifesto.org/][wayback link]]

1) Code      : All source code written specifically to process data for a published paper must be available to the reviewers and readers of the paper.
2) Copyright : The copyright ownership and license of any released source code must be clearly stated.
3) Citation  : Researchers who use or adapt science source code in their research must credit the code’s creators in resulting publications.
4) Credit    : Software contributions must be included in systems of scientific assessment, credit, and recognition.
5) Curation  : Source code must remain available, linked to related materials, for the useful lifetime of the publication.

**** Research Software Manifesto
(Allen 2016)
***** Recognition of Academic Software
1) properly cite software used to produce research results
2) point out improper or missing citations to software when I am reviewing publications.
3) make explicit how to cite the software I make available.
4) recommend software experts for funding agencies to include in their review processes.
5) invite developers of software that enables research to be co-authors on papers.
6) recognize software contributions in hiring and promotion within institution.
7) recognize software contributions at conferences, e.g. dedicated sessions, and prizes.
8) support and publish in journals that recognise software contributions.
9) contribute to sustaining the software I rely on for research.
***** Academic software development processes
10) develop software as open source right from the start whenever possible.
11) document academic software for users with instructions and examples.
12) package, release and archive versions of software
13) consider and document the sustainability of research software.
14) publish how I organize and run software projects
15) match software engineering practices I recommend to the needs and resources of projects.
16) help scientists improve the quality of their software without passing judgment.
***** The intellectual content of academic software
17) acknowledge that source code is a legitimate part of the academic discourse.
18) publish the intellectual contributions of research software.
19) distinguish the intellectual contribution of software from its service contribution.
20) examine the source code of academic software contributions and encourage others to do so as well.
*** Types of Error
Type 1: False Positive
Type 2: False Negative

*** Types of Bias
https://en.wikipedia.org/wiki/Bias#Types_of_bias

**** Cognitive
***** Confirmation Bias

***** Attribution Bias

***** Gamblers Fallacy

***** Anchoring

***** Framing

***** Halo Effect / Horn Effect

***** Self-Serving Bias

***** Status quo bias

***** Availability bias

***** Survivorship bias

***** Confirmation bias

***** Base Rate Fallacy

**** Statistical

***** Forecast

***** Observer expectancy effect

***** Reporting Bias

***** Selection Bias


** Math
*** Number Systems
N - Natural Numbers.             0?, 1, 2, 3...
Z - Integers.        ... -2, -1, 0,  1, 2...
Q - Rational Numbers. Fractions of two integers. ∀x,y ∈ Z : x/y.

R - Real Numbers. Decimals.
C - Complex Numbers. x + y·i, where i = √-1
H - Quaternions. Extension of Complex numbers. a + b·i + c·j + d·k

π - pi

Peano -
*** Probability and Statistics
:Axioms:
∀x, P(X)    >= 0
P(Certainty) = 1
P(Union(X)) = ΣP(x ∈ X)

:END:
:Law_of_Total_Probability:
Summing over a partition over a variable can give the independent probability.

P(A) = P(A, B₁) + P(A, B₂) ... + P(A, B_n)

Or with explicit probabilities:
P(A) = P(A|B₁)P(B₁) + P(A|B₂)P(B₂) ... + P(A|B_n)P(B_n)
:END:
:Bayes_Theorem:
P(A | B) = (P(B | A) * P(A)) / P(B)
:END:
:General_Formulas:
Conditional Probability                 -  P(A | B) = P(A ∩ B) / P(B)
Independence                            -  P(A)     = P(A|B) = P(A ∩ B) = P(A)P(B)
Conditional Independence                -  P(A|B,C) = P(A|C)
:END:
:Expectation_μ:
Also: population mean. µ.

Discrete:
    μ = E(X) = Σ x*P(X=x)

    Where P(X) is uniform, it becomes the arithmetic mean:
    u = E(X) = 1/n * Σx

Continuous:
E(X) = ∫ x P(X) dx

Conditional Expectation
E(Y|x) = Σ y P(Y=y|x)

Linear Functions:
If Y  = a   X + b then
 E(Y) = a E(X)

:END:
:Central_Moments:
nth moment = E((X-μ)ⁿ)

Odd moments are 0 for symmetric distributions.
:END:
:Variance:
σ²(X)
Var(X) = E((X - E(X))²)

Var(X) = E(X²) - E(X)²

When Y = a + bX
Var(Y) = b² * Var(X)

or
Var(X) = Cov(X,X)
Var(X+Y) = Var(X) + Var(Y) + 2Cov(X,Y)

Product of Independent Variables:
Var(XY) = (E(X²)E(Y²)) - (E(X)²E(Y)²)
Product of Dependent Variables:
Var(XY) = E(X²Y²) - E(XY)²
:END:
:StandardDeviation:
σ = sqrt(Var(X))
σ = sqrt(Cov(X,X))

Expressed in the same units as X.
:END:
:Covariance:
σ(XY) = E( (X  - E(X)) (Y - E(Y)) )
σ(XY) = E(XY) - (E(X) * E(Y))
σ(XY) = ΣXY   - (ΣX * ΣY)

Measures association between two variables.


Properties:
Cov(aX, bY)   = a * b * Cov(X, Y)
Cov(X + c, Y) = Cov(X, Y)
Cov(X + Y, Z) = Cov(X, Z) + Cov(Y, Z)
Cov(X, X)     = Var(X)
Cov(X,Y)      = E(XY) - E(X)E(Y)

Cov(Y, X₁) = Cov(β₀ + β₁ * X₁ + β₂ * X₂, X₁) = β₁Var(X₁) + β₂Cov(X₂, X₁)
:END:
:Correlation:
Correlation_Coefficient is the normalization of covariance:
ρ(XY) = σ(XY) / (σ(X)σ(Y))
:END:
:Linear_Regression:
Linear Approximation of the line:
y = α + βx

Least Squares minimization of error:
(where y' = actual data value)
min(Σ(y_i - y'_i)²) = min(Σ(y_i - α - βx_i)²)

where β = R(YX) = σ(XY) / σ²(X)
then  α = E(Y) - β*E(X)

:END:
:Multiple_linear_regression:
Using the line:
y = α + (β₁*X₁) + (β₂*X₂)... + ε

By partially regressing on each variable, holding the others steady.
R(X₁Y.X₂) = Partial Regression Coefficient.

and minimizing the covariance between each variable and the error ε.
Cov(ε, Xᵢ)

giving:
denom = Var(X₁)Var(X₂) - Cov(X₁X₂)²
β₁ = R(YX₁.X₂) = ( Var(X₂)Cov(YX₁) - Cov(YX₂)Cov(X₂X₁) ) / denom

β₂ = R(YX₂.X₁) = ( σ²(X₂)σ(YX₂)σ(YX₂) - σ(YX₁)σ(YX₂) ) / denom

α  = E(Y)
:END:


Distribution                            -
Joint Distribution                      -
Partition                               - Exhaustive, mutually exclusive set of events

Marginalization                         - Summing all probabilities of a variable.
Conditioning                            -
Conjugate Prior                         -
Central Limit Theorem -

*** Relations, Orders and Sets
**** Binary Relations and Functions
domain                - X in f: X → Y.
codomain              - Y in f: X → Y.

Injective             - left-unique.               ∀x,z ∈ X, ∀y ∈ Y : xRy ∧ zRy ⇒ x = z
Surjective            - right-total.               ∀y ∈ Y,   ∃x ∈ X : xRy
Total                 - left-total.                ∀x ∈ X,   ∃y ∈ Y : f(x) = y
Partial               - right-unique.              ∀x ∈ X, ∀y,z ∈ Y : xRy ∧ xRz ⇒ y = z
Bijective             - A Function which is both injective and surjective.


transpose             - X, Y and R ⊆ X ⨯ Y : (R^T) = y(R^T)x ⇔ xRy.
involution            - f(f(x)) = x.

Reflexive             - ∀x ∈ X : xRx.
Irreflexive           - ∀x ∈ X : not xRx.
Symmetric             - ∀x,y ∈ X : xRy ⇒ yRx.
Asymmetric            - ∀x,y ∈ X : xRy ⇒ not yRx.
Antisymmetric         - ∀x,y ∈ X : xRy and yRx ⇒ x = y.
Transitive            - ∀x,y,z ∈ X : xRy and yRz ⇒ xRz.
Connected             - ∀x,y ∈ X : x ≠ y ⇒ xRy or yRx.
Strongly Connected    - ∀x,y ∈ X : xRy or yRx.

Associativity         - ∀x,y,z ∈ S: (xRy)Rz = xR(yRz).
Commutativity         - ∀x,y ∈ S  : xRy = yRx.
Distributivity        - ∀x,y,z ∈ S : xR(yR'z) = (xRy)R'(xRz).   eg: Multiplication, ∧, ∨.
Idempotence           - f(x) = f(f(x)) = f(...f(x)). eg: multiplication by 1.
Absorption            - xR(xR'y) = xR'(xRy) = x.
Duality               - dual((P, <)) = (P, ⧼), ∀x,y ∈ P : x < y ⇔ y ⧼ x.

Left Residual         - relations A, B : A\B = complement(A^T complement(B))
Right Residual        - relations A, B: A/B = complement(complement(A) B^T))
Symmetric Quotient    - relations A, B: syq(A, B) = complement(A^T complement(F)) ∩ complement(complement(E)^T F)
**** Orders
Pre-order             - reflexive, transitive relation.
Equivalence Relation  - reflexive, symmetric, transitive relation.

Partial Order         - reflexive,   antisymmetric, transitive relation. Not every element is comparable.
Total Order           - reflexive,   antisymmetric, transitive and connected relation. Every element is comparable.
Poset                 - a set S, relation R : (S, R).
Interval              - interval I of poset (P, <) : I ⊂ P,  ∀x,y ∈ I, ∀z ∈ P : x < z < y ⇒ z ∈ Y.

Strict Partial Order  - irreflexive, antisymmetric, transitive relation.
Strict Total Order    - irreflexive, antisymmetric, transitive and connected relation.

Reflexive Closure     - smallest reflexive relation over X containing R.
Transitive Closure    - smallest transitive relation over X containing R.
Equivalence Closure   - smallest equivalent relation over X containing R.

order-preserving      - (*monotonic*). For posets (S, <), (T, ⧼), function f(S → T) if ∀x,y ∈ S, x < y ⇒ f(x) ⧼ f(y).
order-reversing       - (*antitonic*). For posets (S, <), (T, ⧼), functiion f(S → T) if ∀x,y ∈ S, x < y ⇒ f(y) ⧼ f(x).
order-reflecting      - For posets (S, <), (T, ⧼), function f(S → T) if ∀x, y ∈ S: f(x) ⧼ f(y) ⇒ x < y.
order-embedding       - both order-preserving and order-reflecting.

infimum               - *meet*, *greatest lower bound*. inf(S) ∈ poset (P, <), S ⊂ P, ∀x ∈ S : inf(S) < x. *Single Element or nothing*.
supremum              - *join*, *least upper bound*. sup(S) ∈ poset (P, <), S ⊂ P, ∀x ∈ S : x < sup(S). *Single Element or nothing*.

Semi-lattice          - Poset X, ∀Y ⊂ X : inf(Y) != ∅
Lattice               - Poset with infimum and supremum.

**** Set Theory
Powerset - the set of all subsets of S, including empty set and itself.
union                 - X, Y : X ∪ Y = {a : ∀a : a ∈ X or  a ∈ Y}
intersection          - X, Y : X ∪ Y = {a : ∀a : a ∈ X and a ∈ Y}
*** Linear Algebra
Scalar -
Vector -
Matrix -

Cross Product -
Dot Product -
*** Geometry
Euclidean geometry -
Non-euclidean geometry -
Cartesian geometry - (analytic)
Geometric Transform -
Affine Transform - a geometric transform that preserves lines and parallelism, but not necessarily distances and angles.

scaling -
reflection -
rotation -
shear -
hyperplane -
*** Calculus
Derivative -
Definite Integral -
Indefinite Integral -

l'hopitals rule -
*** Game Theory
*** Graph Theory
** Logic
*** Classical Logic Definitions
Syntactic Entailment - P ⊢ Q : Q is derivable from P in system S by the transformation rules of S, independent of truth assignments.
Semantic Entailment  - P ⊨ Q : Q is derivable from P in system S by the transformation rules of S if there *not* a model I where P ∈ I and Q ∉ I.
Sound                - (⊢) ⇒ (⊨).
Complete             - (⊨) ⇒ (⊢).

Satisfiability       - there exists a model which is true.
Validity             - every model is true.
Consistency          - an expression that does not lead to a contradiction.
Decidability         - a procedure exists for computing the answer of an expression in finite time.

necessary            - Q only when P.
sufficient           - P therefore Q.

conditional          - material implication.   (P → Q) ⩭ ¬P ∨ Q.
biconditional        - material equivalence. P ⇔ Q ⇒ P → Q and Q → P

well formed formulas -
Term                 -
Signature            -
Hoare Triple         -
model                -
valuation            -
Bisimulation         -
Sequent              -
compactness property -
first-order correspondence language -
*** Modal Logic Definitions
Kripke Model -
□A = ~◇~A
*** Rules of Inference
Admissable                   - (redundancy). The set of theorms does not change when a rule is added to the system.

Open World Assumption        - statements whether be true even if they are not known to be true.
Closed World Assumption      - only statements known to be true are true.

modus ponens                 - Affirming the antecedent. (P → Q), P ⊢ Q.
modus tollens                - Denying the Consequent.   (P → Q), ¬Q ⊢ ¬P.
contraposition               - (modus tollens) Inverting the antecedent and consequent. P → Q becomes ¬Q → ¬P
inversion                    - P → Q becomes  ¬P → ¬Q
conversion                   - P → Q becomes   Q →  P
complement                   - P → Q becomes ¬(P → Q)

Affirming the consequent     - *Fallacy* : (P → Q), Q ⊢ P.
Denying the antecedent       - *Fallacy* : (P → Q), ¬P ⊢ ¬Q.

import-export                - P → (Q → R) ⩭ (P ∧ Q) → R
Strengthening                -

law of excluded middle       - P ∨ ¬P
double negation elimination  - ¬¬P ⇒ P.

De Morgan's Laws 1           - not (A ∨ B) = (not A) ∧ (not B).
De Morgan's Laws 1           - not (A ∧ B) = (not A) ∨ (not B).
*** Structural Rules
Weakening                           - Addition does not change the truth of the expression. (A ⊢ X) ⇒ (A, B ⊢ X), (A ⊢ X, Y)
Contraction                         - Idempotence of entailment. (A, A, A ⊢ X) ⩭ (A ⊢ X) and  (A ⊢ X, X, X) ⩭ (A ⊢ X).
Exchange                            - Permutation. (A, B ⊢ X) ⩭ (B, A ⊢ X) and (A ⊢ X, Y) ⩭ (A ⊢ Y, X)
Cut                                 - Generalisation of Modus Ponens. (Γ ⊢ A, Δ) and (Γ', A ⊢ Δ') ⩭ (Γ, Γ' ⊢ Δ, Δ')
*** Lambda Calculus
Normal Form         -
Free Variable       -
α conversion        - Renaming bound variables in an expression
β reduction         - Replacing bound variables in body of expression.
η (eta) reduction   - Converts between (λx.f x) and (f) whenever x does not appear free in f.

De Bruijin Indexing -
*** Transition System
*** Semantics
Hilbert Semantics      -
Tarski Semantics       -
Operational            -
Structural Operational -
Denotational           -
Axiomatic              -
*** Types of Logics
**** Propositional
**** First Order
**** Second Order
**** Classical
**** Constructive
**** Intuitionistic
**** Substructural
**** Input/Output Logics
**** Linear Logic
linear logic               -

Multiplicative Conjunction - ⨂
Multiplicative Disjunction - ⅋
Additive Conjunction       - &
Additive Disjunction       - ⨁
**** Temporal Logics
temporal logic                      -
alternating temporal logic          -
alternating time temporal logic     -
linear temporal logic               -
linear time temporal logic          -
metric temporal logic               -
temporal action logic               -
temporal epistemic logic            -
temporal modal defeasible logic     -
**** Modal Logics
modal logic          -
sabotage modal logic -
K                    -
K45                  -
S                    -
S5                   -
**** Description Logic
**** Misc Logics
3 valued logics                     -
BDI stit logic                      -
KLM logic                           -
Notation3 logic                     -
OO logic                            -
STIT logic                          -

abductive logic                     -
acceptance logic                    -
action logic                        -
action model logic                  -
adaptive deontic logic              -
adaptive logic                      -
adjoint logic                       -
agency logic                        -
agent organization logic            -
arabic logic                        -
axiomatic logic                     -
boolean logic                       -
c1 logic                            -
categorical logic                   -
causal logic                        -
chbdo logic                         -
choice logic                        -
coalition logic                     -
combinatory logic                   -
computation tree logic              -
computation tree logic of knowledge -
computational logic                 -
conjunctive choice logic            -
connective action logic             -
context logic                       -
contextual logic                    -
cultural logic                      -
default logic                       -
defeasible logic                    -
definite logic programs             -
delegation logic                    -
deontic logic                       -
dependence logic                    -
description logic                   -
diagnostic logic                    -
dialethic logic                     -
dialogue logic                      -
display logic                       -
doxastic logic                      -
dyadic deontic logic                -
dynamic epistemic logic             -
economic logic                      -
edinburgh logical framework         -
emerging logics                     -
epistemic logic                     -
epistemic logic of friendship       -
equilibrium logic                   -
exclusion logic                     -
extended logic programs             -
f logic                             -
failure logic                       -
fuzzy logic                         -
general awareness logic             -
generalised possibilistic logic     -
geometric logic                     -
graphical logic                     -
herbrand logic                      -
higher ordered logic                -
hoare logic                         -
hybrid logics                       -
ignorance logic                     -
imperative logic                    -
inductive logic                     -
input output logics                 -
inquisitive logic                   -
institutional logic                 -
interaction logic                   -
intuitional logic                   -
justification logic                 -
lax logic                           -
legal logic                         -
linear logic                        -
logic of agency                     -
logic of questions                  -
logic of rules                      -
mathematical logic                  -
minimal inconsistency logic         -
monadic deontic logic               -
moral logic                         -
multivalued logic                   -
neighbourhood logic                 -
non dialogical acts                 -
non monotonic logic                 -
normative logic                     -
object oriented logic               -
operational logic                   -
order sorted logic                  -
ordered choice logic                -
ordered logic                       -
organisational logic                -
paraconsistent logic                -
polarized logic                     -
predicate logic                     -
procedural logic                    -
propositional dynamic logic         -
propositional lax logic             -
propositional logic                 -
protological power                  -
provability logic                   -
public announcement logic           -
qualitative choice logic            -
radiological weapons testing        -
rational agency logic               -
relational logic                    -
separation logic                    -
service logic                       -
set based logic programming         -
social logic                        -
spatial logic                       -
specification logic                 -
strategic logic                     -
stratified logic                    -
strictly positive logic             -
substructural logic                 -
symbolic logic                      -
tensor logic                        -
tool logic                          -
transaction logic                   -
*** Logic Programming
**** Definitions
From cropper22_induc_logic_progr_at_74

- A *variable* is a string of characters starting with an uppercase letter, e.g. A, B, and C.
- A *function* symbol is a string of characters starting with a lowercase letter.
- A *predicate* symbol is a string of characters starting with a lowercase letter, e.g. job or happy. The arity n of a function or predicate symbol p is the number of arguments it takes and is denoted as p/n, e.g. happy/1, head/2, and append/3.
- A *constant* symbol is a function symbol with zero arity, e.g. alice or bob.
- A *term* is a variable, or a constant/function symbol of arity n immediately followed by a tuple of n terms.
- A term is *ground* if it contains no variables.
- An *atom* is a formula p(t1, . . . , tn), where p is a predicate symbol of arity n and each ti is a term, e.g. lego builder(alice), where lego builder is a predicate symbol of arity 1 and alice is a constant symbol.
- An atom is *ground* if all of its terms are ground, e.g. lego builder(alice) is ground but lego builder(A), where A is a variable, is not ground.
- The symbol *not* denotes negation as failure, where an atom is false if it cannot be proven true.
- A *literal* is an atom A (a positive literal) or its negation not A (a negative literal). For instance, lego builder(alice) is both an atom and a literal but not lego builder(alice) is only a literal because it includes the negation symbol not.
- A *clause* is of the form h1, ..., hn :- b1, ...,bm where each hi and bj is a literal and the symbol , denotes conjunction. The symbols hi are called the head of the clause. The symbols bi are called the body of the clause. We sometimes use the name rule instead of clause.
- A *Horn clause* is a clause with at most one positive literal.
- A *definite clause* is clause of the form h :- b1, b2, ..., bn, i.e. a clause with only one head literal, e.g. qsort(A,B):- empty(A),empty(B). Informally, a definite clause states that the head is true if the body is true, i.e. all of the body literals are proven true. For instance, the rule happy(A):- lego builder(A),enjoys lego(A) says that happy(A) is true when both lego builder(A) and enjoys lego(A) are true.
- A clause is *ground* if it contains no variables.
- A *clausal theory* is a set of clauses.
- A *goal* (also called a constraint) is a clause of the form :- b1, b2, ..., bn, i.e. a clause without a head, e.g. :- head(A,B),head(B,A).
- A *unit clause* is a clause with no body. For unit clauses, we usually omit the :- symbol, e.g. loves(alice,X).
- A *fact* is a ground unit clause loves(andrew,laura).
- A *substitution* is a clause with variables v1, . . . , vn simultaneously replaced with terms t1, . . . , tn and is denoted as θ = {v1/t1, . . . , vn/tn}. For instance, applying the substitution θ = {A/bob} to loves(alice,A) results in loves(alice,bob).
- A substitution *θ* unifies atoms A and B in the case Aθ = Bθ. Note that atoms A and B need to have a distinct set of variables, i.e., they should not have a variable with the same name, for unification to work properly.

(Procedural) Cut -
Resolution       -
Unification      -

**** Prolog
**** Answer Set Programming
Herbrand Base            -
Herbrand Universe        -
Interpretation           -

Minimal Model Semantics  -
Fixpoint                 -
Stratified Program       -
Dependency Graph         -
Stable Semantics         -
Gelfond-Lifschitz Reduct -

Brave Reasoning          -
Cautious Reasoning       -
**** Communicating Sequential Processes
**** satisfiability modulo theory
*** Category theory
[[https://en.wikipedia.org/wiki/Glossary_of_category_theory][Glossary]]
Natural Transformation -
:Morphisms:


mono       -
epi        -
bi         -
iso        -
endo       -
auto       -

retraction -
section    -
:END:

:Functors:

:END:

Adjoint -
*** Causal Models
:DAGs:
Directed Acyclic Graph.
Every Strict Partial Order is a DAG.
Every transitive closure of a DAG is a strict partial order.
:END:

:Rule_of_Product_Decomposition:
For a DAG g:
P(X₁, X₂, ... X_n) = ∏ P(x_i | parent(x_i))

eg: X -> Y -> Z
P(X, Y, Z) = P(X) P(Y|X) P(Z|Y)

:END:

:Chains:
eg: X -> Y -> Z

Z and Y are Dependent.
Y and X are Dependent.
Z and X are likely dependent.
Z and X are independent, *conditional on Y*.
:END:
:Forks:
eg: Y <- X -> Z

X and Y are Dependent.
X and Z are Dependent.
Z and Y are likely Dependent.
Y and Z are independent, *conditional on X*.
:END:
:Colliders:
eg: X -> Z <- Y

X and Z are Dependent.
Y and Z are Dependent.
X and Y are independent.
X and Y are dependent, *conditional on Z*.
:END:

:Conditional_Independence_in_Chains:
Two variables, X and Y, are conditionally independent given Z, if:
there is only one unidirectional path between X and Y
and Z is any set of variables that intercepts that path.
:END:
:Conditional_Independent_in_Forks:
If a variable X is a common cause of variables Y and Z,
and there is only one path between Y and Z,
then Y and Z are independent conditional on X.
:END:
:Conditional_Independence_in_Colliders:
If a variable Z is the collision node between two variables X and Y,
and there is only one path between X and Y,
then X and Y are unconditionally independent
but are dependent conditional on Z and any descendants of Z.

:END:

:D-Separation:
A path p is blocked by a set of nodes Z if and only if
1. p contains a chain of nodes A -> B -> C or a fork A <- B -> C
   such that the middle node B is in Z (i.e., B is conditioned on), or
2. p contains a collider A → B ← C such that the collision node B is not in Z,
   and no descendant of B is in Z.

If Z blocks every path between two nodes X and Y,
then X and Y are d-separated, conditional on Z,
and thus are independent conditional on Z.
:END:

:Adjustment_Formula:

:END:

:The_Causal_Effect_Rule:

:END:

:The_Truncated_Product_Rule:

:END:
:The_Backdoor_Criterion:

:END:
:The_Frontdoor_Criterion:

:END:

:Mediation:

:END:
:Counterfactuals:

:END:
*** Description Logic
TBox -
ABox -

EL -
ALC -
SHIQ -

:Extensions:
H -
R -
O -
I -
N -
Q -
F -
:END:





*** Computational Complexity
LogSpace -
PTime -
NP -
PSpace -
ExpTime -

** Computer Science
*** Args vs Params
params : expected, formal definition
args   : actual

*** Binary Sizes
Bit: 0 or 1
Byte: 8 bits
Word: 2 Bytes
DWord: 2 words

*** Little v Big Endian
lowest address <-------------> highest address
least sig      <little endian>        most sig
most sig       <big    endian>       least sig

little end first versus big end first


** Misc
Marxism                        - critique of capitalism, and understanding economic activity through class struggle
dialectic                      - discourse between opposing points of view (people) to arrive at the truth
hegelian dialectic/speculative - opposing conceptions, instead of people. Proceeds from abstract, to negatively rational, to positively rational.
eristic                        - argument to dispute an opponents argument, rather than arrive at truth
didactic                       - one teaching and leading others through an argument
hermeneutics                   - method of interpeting texts
legal formalism                -
legal positivism               - law as it exists, separate from its morality. "Normatively inert" (John Gardner). Law provides reasonably determinate guidance.
legal realism                  - view that jurisprudence should emulate the methods of natural science, rely on evidence, test hypotheses.
logical atomism                - Bertrand Russell, Analytic Philosophy.
logical positivism             -
logical realism                -
methodological individualism   -
methodological legalism        -
ontological neutrality         -
ontological priors             -
sociological realism           -
technological determinism      -
cognito-hazard -
historical inferentialism -
minimum viable population - https://en.m.wikipedia.org/wiki/Minimum_viable_population
quango - quasi-NGO / quasi-autonomous national goverment organisation
:Condorcet_paradox:
https://artint.info/2e/html/ArtInt2e.Ch11.S5.html

Where:
Alice : X > Y > Z
Bob   : Y > Z > X
Cory  : Z > X > Y

In pairwise voting, 2/3 for (X > Y) and (Y > Z) and (Z > X),
so preference is non-transitive.
:END:
:arrows_impossibility_theorem:
If there are three or more outcomes, the following properties cannot simultaneously hold for any social preference function(SPF):

- SPF is complete and transitive
- every individual preference that is complete and transitive is allowed
- if every individual prefers X to Y, the group prefers X to Y.
- the group preference between X and Y depends only on the individual preferences of X and Y, and not on other preferences
- no individual gets to unilaterally decide the outcome
:END:

[[https://en.wikipedia.org/wiki/Delphi_method][Delphi Method]] - Multi-Round Structured Interviews of experts with summary sharing.

ergodic - a dynamic system which will eventually visit all parts of its domain space
ergodic literature - [aaarseth97_cyber_ p1] requires nontrivial effort to allow the reader to traverse the text.

entropy - [shannon] increase in amount of probable arrangements of a system

hyperobject - [timothy morton] objects which resist knowability on a human scale

*** Rights
claim rights                 - entails obligations on others regarding the right holder.
legal rights                 - rights bestowed by a given legal system, and so modifiable.
liberty rights               - only regards the right holder.
natural rights               - rights existing independent of the state/legal system.
negative rights              - relating to protection from interference.
positive rights              - relating to protection to act.
second order rights          - power to/immunity from modification of rights
*** Stances
realism        - view of a mind-independent existence of a thing
positivism     - from David Hume, Augustus Comte, Popper. Empiricism+.
naturalism     - all beings and events in the universe are natural, so is relevant to study scientifically. Generally not metaphysical.
materialism    - reducing the universe to physical facts and processes.
legalism       - (western meaning) strict adherence to the letter of the law.
interpretivism - law exists through the interpretations and aims of lawyers actions.
pragmatism     - meaning lies in its observable practical uses and consequences.
formalism      - rigourous adherence to recognized forms.
structuralism  - understanding elements by their relationship to a broader system.
*** Politics
Liberalism       - John Locke. Replacing norms of hereditary privilege, state religion and monarchy with rights of the individual, consent of the governed.
Neoliberalism    - conservative focus on free-market capitalism. Privatization, deregulation, globalization, free trade, monetarism, austerity.
Conservatism     - seeks to preserve traditional institutions and practices. Supposedly for slow change.
Libertarianism   - seeks to maximize 'liberty', by minimising the state's encroachment on individuals.
Communitarianism - views individuals as existing and shaped within a broad community,
individualism    - emphasises the independence and importance of an individual, over their connection to a community.
Communism        - theoretical post-capitalist economic system with collective ownership of property
Socialism        - focus on social ownership
Fascism          - nationalist centralization of authority, capitalist economy with suppression of opposition, with racism.
**** Peelian Principles of Policing
(From Charles Reith, A Short History of the British Police, 1948)
https://en.m.wikipedia.org/wiki/Peelian_principles
To prevent crime and disorder, as an alternative to their repression by military force and severity of legal punishment.
To recognise always that the power of the police to fulfil their functions and duties is dependent on public approval of their existence, actions and behaviour, and on their ability to secure and maintain public respect.
To recognise always that to secure and maintain the respect and approval of the public means also the securing of the willing co-operation of the public in the task of securing observance of laws.
To recognise always that the extent to which the co-operation of the public can be secured diminishes proportionately the necessity of the use of physical force and compulsion for achieving police objectives.
To seek and preserve public favour, not by pandering to public opinion, but by constantly demonstrating absolutely impartial service to law, in complete independence of policy, and without regard to the justice or injustice of the substance of individual laws, by ready offering of individual service and friendship to all members of the public without regard to their wealth or social standing, by ready exercise of courtesy and friendly good humour, and by ready offering of individual sacrifice in protecting and preserving life.
To use physical force only when the exercise of persuasion, advice and warning is found to be insufficient to obtain public co-operation to an extent necessary to secure observance of law or to restore order, and to use only the minimum degree of physical force which is necessary on any particular occasion for achieving a police objective.
To maintain at all times a relationship with the public that gives reality to the historic tradition that the police are the public and that the public are the police, the police being only members of the public who are paid to give full-time attention to duties which are incumbent on every citizen in the interests of community welfare and existence.
To recognise always the need for strict adherence to police-executive functions, and to refrain from even seeming to usurp the powers of the judiciary of avenging individuals or the State, and of authoritatively judging guilt and punishing the guilty.
To recognise always that the test of police efficiency is the absence of crime and disorder, and not the visible evidence of police action in dealing with them.

*** Art (western)
**** Ancient
Thracian (Dacian)
Nuragic
Aegean (Cycladic Minoan Minyan ware Mycenaean)
Greek (Sub-Mycenaean Protogeometric Geometric Orientalizing Archaic Black-figure Red-figure Severe Classical Kerch)
Hellenistic ("Baroque" Neo-Attic)
Etruscan
Scythian
Iberian
Gaulish
Roman (Republican Gallo-Roman Julio-Claudian Pompeian Styles Trajanic Hadrian  Antonines  Commodus )
Severan (Gallienus)
**** Medieval
Late antique
Early Christian
Art of Diocletian and the Tetrarchy
Constantinian art
Theodosian art
Migration Period
Anglo-Saxon
Hunnic
Insular
Lombard
Visigothic
Donor portrait
Pictish
Mozarabic
Repoblación
Viking
Byzantine
Iconoclast
Macedonian
Italo-Byzantine
Frankish
Merovingian
Carolingian
Pre-Romanesque
Ottonian
Romanesque
Mosan
Norman
Norman-Sicilian
Opus Anglicanum
Gothic
International Gothic
Lucchese School
Novgorod School
Duecento
Sienese School
Mudéjar
Medieval cartography
Italian school
Majorcan school
Mappa mundi

**** Renaissance
Italian Renaissance
Trecento
Proto-Renaissance
Florentine School
Pittura infamante
Quattrocento
Ferrarese School
Forlivese School
Venetian School
Di sotto in sù
Cinquecento
High Renaissance
Bolognese School
Mannerism
Counter-Maniera
Northern Renaissance
Early Netherlandish
World landscape
Ghent-Bruges school
Northern Mannerism
German Renaissance
Cologne School
Danube school
Dutch and Flemish Renaissance
Antwerp Mannerism
Romanism
Still life
English Renaissance
Tudor court
Cretan School
Vologda School
Turquerie
Fontainebleau School

**** 17th Century
Baroque
Flemish Baroque
Caravaggisti
Utrecht
Tenebrism
Quadratura
Louis XIII style
Lutheran Baroque
Godunov School
Stroganov School
Siberian School
Guild of Romanists
Dutch Golden Age
Delft School
Capriccio
Heptanese School
Classicism
Louis XIV style
Poussinists and Rubenists
**** 18th Century
Rococo
Rocaille
Louis XV style
Frederician
Chinoiserie
Fête galante
Neoclassicism
Goût grec
Louis XVI style
Adam style
Directoire style
Picturesque


**** 19th Century
    Academic, c. 16th century–20th century
    Aesthetic Movement
    American Barbizon school
    American Impressionism
    Amsterdam Impressionism
    Art Nouveau, c. 1890–1910
    Arts and Crafts Movement, founded 1860s
    Barbizon school, c. 1830s–1870s
    Biedermeier, c. 1815–1848
    Cloisonnism, c. 1888–1900s (decade)
    Danish Golden Age c. 1800s-1850s
    Decadent movement
    Divisionism, c. 1880s–1910s
    Düsseldorf School
    Etching revival
    Expressionism, c. 1890s–1930s
    German Romanticism, c. 1790s–1850s
    Gründerzeit
    Hague School, c. 1860s–1890s
    Heidelberg School, c. 1880s–1900s (decade)
    Hoosier Group
    Hudson River School, c. 1820s–1900s (decade)
    Hurufiyya movement mid-20th-century in North Africa and the Middle East
    Impressionism, c. 1860s–1920s
    Incoherents, c. 1882-1890s
    Jugendstil
    Les Nabis, c. 1890s–1900s (decade)
    Les Vingt
    Letras y figuras, c. 1845-1900s
    Luminism
    Lyon School
    Macchiaioli c. 1850s–1900s (decade)
    Mir iskusstva, founded 1898
    Modernism, c. 1860s-ongoing
    Naturalism
    Nazarene, c. 1810s–1830
    Neo-Classicism, c. 1780s–1900s (decade)
    Neo-impressionism, c. 1880s–1910s
    Norwegian romantic nationalism, c. 1840–1867
    Norwich School, founded 1803
    Orientalism
    Peredvizhniki
    Pointillism, c. 1880s–1910s
    Pont-Aven School, c. 1850s–1890s
    Post-Impressionism, c. 1880s–1900s (decade)
    Pre-Raphaelite Brotherhood
    Realism, c. 1850s–1900s (decade)
    Realism, c. 1850s–1900s (decade)
    Romanticism, c. 1750s–1890s
    Secession groups, c. 1890s–1910s
    Society of American Artists, c. 1877–1906
    Spanish Eclecticism, c. 1845-1890s
    Symbolism
    Synthetism, c. 1877–1900s (decade)
    Tipos del País
    Tonalism, c. 1880–1915
    Vienna Secession, founded 1897
    Volcano School
    White Mountain art, c. 1820s–1870s
    Spiritualist art, c. 1870–

**** 20th Century
***** 1900-1921
    Academic, c. 1900s (decade)-ongoing
    American realism, c. 1890s–1920s
    Analytic Cubism, c. 1909–1912
    Art Deco, c. 1910–1939
    Ashcan School, c. 1890s–1920s
    Australian tonalism, c. 1910s–1930s
    Berliner Sezession, founded 1898
    Bloomsbury Group, c. 1900s (decade)–1960s
    Brandywine School
    Camden Town Group, c. 1911–1913
    Constructivism, c. 1920–1922, 1920s–1940s
    Cubism, c. 1906–1919
    Cubo-Futurism, c. 1912–1918
    Czech Cubism, c. 1910–1914
    Dada, c. 1916–1922
    Der Blaue Reiter, c. 1911–1914
    De Stijl, c. 1917–1931
    Deutscher Werkbund, founded 1907
    Die Brücke, founded 1905
    Expressionism c. 1890s–1930s
    Fauvism, c. 1900–1910
    Futurism, c. 1909–1916
    German Expressionism, c. 1913–1930
    Group of Seven (Canada), c. 1913–1930s
    Jack of Diamonds, founded 1909
    Luminism (Impressionism), c. 1900s (decade)–1930s
    Modernism, c. 1860s–ongoing
    Neo-Classicism, c. 1900s (decade)–ongoing
    Neo-primitivism, from 1913
    Neue Künstlervereinigung München
    Novembergruppe, founded 1918
    Objective Abstraction, c. 1933–1936
    Orphism, c. 1910–1913
    Photo-Secession, founded c. 1902
    Pittura Metafisica, c. 1911–1920
    Proto-Cubism, c. 1906–1908
    Purism, c. 1917–1930s
    Rayonism
    Section d'Or, c. 1912–1914
    Suprematism, formed c. 1915–1916
    Synchromism, founded 1912
    Synthetic Cubism, c. 1912–1919
    The Eight, c. 1909–1918
    The Ten, c. 1897–1920
    Vorticism, founded 1914
***** 1920-1945
American Scene painting, c. 1920s–1950s
Arbeitsrat für Kunst
Art Deco
Bauhaus, c. 1919–1933
Concrete art
Der Ring
De Stijl, c. 1917–1931
Ecole de Paris
Geometric abstraction
Gruppo 7
International Style, c. 1920s–1970s
Kapists, c. 1930s
Magic Realism
Neo-Romanticism
Neue Sachlichkeit
Novecento Italiano
Novembergruppe, founded 1918
Precisionism, c. 1918–1940s
Regionalism (art), c. 1930s–1940s
Return to order, 1918–1922
Scuola Romana, c. 1928–1945
Social Realism, c. 1920s–1960s
Socialist Realism
Surrealism, c. 1920s–1960s
Universal Constructivism, c. 1930–1970

***** 1940-1965
Abstract expressionism
Action painting
Arte Povera
Art Informel
Assemblage
Beatnik art
Chicago Imagists
CoBrA, c. 1948–1951
Color Field painting
Combine painting
De-collage
Fluxus
Happening
Hard-Edge Painting
Kinetic Art
Kitchen Sink School
Lettrism
Lyrical abstraction
Neo-Dada
New Brutalism
Northwest School
Nouveau Réalisme
Op Art
Organic abstraction
Outsider Art
Panic Movement
Pop Art
Post-painterly abstraction
Process art
Public art
Retro art
Serial art
Shaped canvas
Situationist International
Tachism
Video art

***** 1965-2000
Abstract Illusionism
Appropriation
Arte Povera
Art Photography
Body Art
Classical Realism
Conceptual Art
Dogme 95
Earth Art
Figuration Libre
Funk art
Graffiti art
Hyperrealism
Installation art
Internet Art
Land art
Late modernism
Light and Space
Lowbrow
Lyrical Abstraction
Mail art
Massurrealism
Maximalism
Minimalism
Neo-Expressionism
Neo-figurative
Neo-pop
Performance Art
Postminimalism
Postmodernism
Photorealism
Psychedelic art
Relational art
Site-specific art
Sound Art
Transavanguardia
Young British Artists

**** 21st Century
Algorithmic art
Altermodernism
Biomorphism
Computer art
Computer graphics
Craftivism
Digital art
Electronic Art
Empathism
Environmental art
Excessivism
Intentism
Internet art
Intervention art
Metamodernism
Modern European ink painting
Neo-minimalism
New Media Art
Pixel art
Post-postmodernism
Relational art
Remodernism
Social practice (art)
SoFlo Superflat
Stuckism International
Superflat
Superstroke
Transgressive art
Toyism
Unilalianism
Vaporwave
Postinternet
**** Specific Movements
***** Realism
The Attempt to represent the subject matter truthfully.

Classical  -
Literary   -
New        -
Theatrical -
Fantastic  -
Socialist  -
****** Neorealism
Italian -
Indian  -
***** Minimalism
***** Art Nouveau
***** Expressionism
***** Romanticism
***** Impressionism
***** Modernism
***** Neo-Classicism
***** Orientalism
***** Pointillism
***** Romanticism
***** Art Deco
***** Cubism
***** Dada
***** De Stijl
***** Fauvism
***** Futurism
***** Bauhaus
***** Magical Realism
***** Surrealism
***** Brutalism
***** Pop Art

*** Turns
adaptive_turn       -
computational_turn  -
historical_turn     -
institutional_turn  -

:linguistic_turn:
Focusing on relations between language, language users, and the world.
The birth of Analytic Philosophy

Rorty 1967.
:END:

methodological turn -
ontological turn    -
participatory turn  -
symbolic turn       -
*** Philosophy
Ordinary language philosophy  - where traditional philosophical problems arise from philosophers distorting words.
Rhizome                       -
Structuralism                 -
Post-Structuralism            -
Diaspora                      -

:from_quote:
Ontology is the study of beings or their being - what is.
Epistemology is the study of knowledge - how we know.
Logic is the study of valid reasoning - how to reason.
Ethics is the study of right and wrong - how we should act.
Phenomenology is the study of our experience - how we experience.
:END:


*** Ontology
*** Sociology
double hermeneutic      - relationship between lay and social science interpretation of the world.
symbolic interactionism - George Herbert Mead. Meaning constructed via communication.
Iron Cage               -
Habitus                 -
Structuration           -
Total Institution       -
Time Displacement       -
Woozle effect           -
Chicago School          -
*** Linguistics
Synonym  - words of the same language with nearly the same meaning in some or all senses
Antonym  - words with opposite meaning
Homonym  - words with similar spelling or pronounciation but with different meanings.
Hypernym - a more abstract word which includes the meaning of a specific word.
Hyponym  - a more specific word which includes the meaning of a more general word.
Troponym - a more specific verb for describing action
Metonymy - figure of speech replacing one thing with an attribute of it. eg: "the crown"
Meronym  - a word that names a part of a larger whole.

:Gerund:
Gerund - clause using a verb ending in -ing, the clause acting as a noun in the sentence.
A   Subject                   | [Eating cakes] is pleasant.
B   Extraposed subject        | It can be pleasant [eating cakes.]
C   Subject Complement        | What I'm looking forward to is [eating cakes]
D   Direct object             | I can't stop [eating cakes].
E   Prepositional object      | I dreamt of [eating cakes].
F   Adverbial                 | He walks the streets [eating cakes].
G   Part of noun phrase       | It's a picture of a man [eating cakes].
H   Part of adjective phrase  | They are all busy [eating cakes].
I   Complement of preposition | She takes pleasure in [eating cakes].
:END:

non-finite clause - dependent/embedded clause independent of verb tense.
Infinitive -

:Verb_Tenses:
Past, Present, Future
(all with continuous, perfect, and perfect-continuous modalities)

:END:

:English_Clauses:
Declarative
Interrogative
Imperative
Exclamative

:END:


**** Parts of Speech
Noun                    -
Pronoun                 -
Verb                    -
Adjective               -
Adverbs                 -
Preposition             -
Conjunction             -
Articles                -
Interjections           -

Open and Closed Classes -
*** Speech Acts
Illocutionary                   -
Perlocutionary                  -
Performative                    -
Indirect                        -

Direction of Fit                -
Components:
Illocutionary Point             -
Strength of Illocutionary Point -
Mode of Achievement             -
Content Conditions              -
Preparatory Conditions          -
Sincerity Conditions            -
Strength of Sincerity           -

Scorekeeping                    -

(Austin):
Verdictives                     -
Exercitives                     -
Commissives                     -
Behabitives                     -
Expositives                     -

(Searle):
Assertives                      -
Directives                      -
Commissives                     -
Expressives                     -
Declarations                    -

Pragmatics                      -
*** GOFAI
Of John Haugeland, described by Brian Cantwell Smith in "The Promise of Artificial Intelligence":
1) Intelligence = Rational Thought.
2) Logical Inference is an ideal model of thought.
3) Perception is lower level than thought.
4) The ontology of the world is formal, discrete well-defined objects.

* Links
