#+TITLE: List Quotes

* [[https://antichamber.fandom.com/wiki/List_of_Signs][AntiChamber]]
1) Every journey is a series of choices. The first is to being the journey.
2) Patience has its own rewards.
3) Taking the first step can be harder than the rest of the challenge.
4) Many small obstacles can make for one large problem.
5) Some choices leave us running around a lot without really getting anywhere.
6) Live on your own watch, not on someone else's.
7) Failing to succeed does not mean failing to progress.
8) Some paths are clearer than others.
9) Some paths are straight forward.
10) A choice may be as simple as going left or going right.
11) The choice doesn't matter if the outcome is the same.
12) If you don't like where you've ended up, try doing something else.
13) When you return to where you have been, things aren't always as remembered.
14) We fall down when there is nothing there to support us.
15) Building a buridge can get you over a problem.
16) Some hurdles are too high to jump over.
17) Life is full of ups and downs.
18) Connecting the pieces can solve a puzzle.
19) Life has a way of pushing us in the right direction.
20) the end may come before we were ready to get there.
21) Life isn't about getting to the end.
22) It's harder to progress if you're leaving things behind.
23) The further we get, the less help we need.
24) Moving forward may require making the most of what you've got.
25) Some tasks require a lot of care and observation.
26) Taking one path often means missing out on another.
27) A path may not be right or wrong. It may just be different.
28) Look a little harder, and you will find a way forward.
29) Venturing into the unknown can lead to great rewards.
30) If you're only focusin on right now, you won't have enough for later.
31) A dead end will only stop you if you don't try to move through it.
32) Going a certain way may require building your own path.
33) There's nothing wrong with taking shortcuts.
34) We often fall into things when we least expect.
35) What looks out of reach may only be a few steps away.
36) There are multiple ways to approach a situation.
37) When you've hit rock bottom, the only way is up.
38) Some outcomes are more favourable than others.
39) How we perceive a problem can change every time we see it.
40) The solution to a problem may just require a more thorough look at it.
41) Rushing through a problem won't always give the right results.
42) Moving through a problem slower may help find the solution.
43) If you never strop trying, you will get there eventually.
44) Raw persistence may be the only option other than giving up entirely.
45) Some problems just come down to size.
46) A Problem may only be difficult when you are missing the right tools.
47) What we've done before may impact what we can do next.
48) If you aren't paying attention, you will miss everything around you.
49) Some choices can leave us running around in circles.
50) Splitting a problem up may help you find the answer.
51) What appears impossible may have a very simple answer.
52) If you lose sight of what's important, it may not be there when you need it.
53) Too much curiosity can get the best of us.
54) Signs may be helping you more than you realize.
55) Understanding a problem requires filling in the pieces.
56) Small steps can take you great distances.
57) The path of least resistance is a valid option.
58) No matter how high you climp, there's always more to achieve.
59) Falling down teaches us how to get up and try again.
60) The world rarely changes when we watch to see it happen.
61) Half way through is half way finished.
62) The problem may not be where you're going, but how to get there.
63) New skills enable further progress.
64) Mastering a skill requires practice.
65) A little kind direction can get obstacles out of your way.
66) Solving a problem may require approaching it from a different angle.
67) Try hard enough and you will get to where you want to be.
68) Some doors will close unless we hold them open.
69) When you absorb your surroundings, you may notice things that you didn't see before.
70) Dig a little deeper and you may find something new.
71) Attention to detail can lead to very rewarding outcomes.
72) Solving a problem may require using abilities that we didn't realize we had.
73) Old skills are useful even after we have learned new ones.
74) The right answers may also be the most obvious ones.
75) Some Obstacles are more stubborn than others.
76) Some things don't have a deeper meaning.
77) The right decisions at the right time will get you where you want to go.
78) Some choices are only useful when we make them early.
79) With forethought, things have a way of just working themselves out.
80) Some challenges are far harder than they first appear.
81) To get past a problem, you may just need to keep pushing through it.
82) Getting to a solution requires cutting out what doesn't work.
83) The further we explore, the more connected everything becomes.
84) A Window of opporunity can lead to new places if you are willing to take a closer look.
85) The world looks different on the other side.
86) When you have enough resources, you can start growing more.
87) You can grow a garden anywhere.
88) The best solutions may still be the most primitive ones.
89) If you lead the way, others will follow.
90) Straightforward problems can often require roundabout solutions.
91) If you are missing information, it's easy to be misled.
92) When you look beyond the surface, there may be more to find.
93) Sometimes we only have just enough to get by.
94) When what you have is not enough, find ways to turn it into more.
95) Getting where we want may require jumping through some hoops.
96) Throwing yourself into things can take you to new heights.
97) Similar problems can have entirely different solutions.
98) Some events happen whether we want them to or not.
99) Old solutiosn can apply to new problems.
100) The consequences of the one choice can cut us off from making others.
101) At times we need to view the world from someone else's perspective.
102) Sometimes you need to be carried.
103) There comes a time when you can work your way through anything.
104) With more experience, previous challenges aren't so difficult.
105) There's no need to take apart what already works.
106) A few steps backwards may keep you moving forwards.
107) Obscure problems may require unusual solutions.
108) Getting to the end requires tying off the loose ends.
109) The world is always finding new ways to surprise us.
110) Sometimes we do things just to go along for the ride.
111) The more we complete, the harder it gets to find what we missed.
112) Some challenges exist just to test how much we know.
113) You can't do everything yourself.
114) The world is full of secrets waiting to be uncovered.
115) Peeking behind the curtains lets us see how everything works.
116) Some problems can't be solved until you're more experienced.
117) We move on when there is nothing left to learn.
118) Complicated problems are easier when solved one step at a time.
119) We can appreciate the entire journey by looking back at how far we have come.
120) Every journey comes to an end.
* Ferengi Rules of Acquisition
[[https://memory-alpha.fandom.com/wiki/Rules_of_Acquisition][Memory-Alpha List]]
[[http://www.sjtrek.com/trek/rules/][SJTrek List]]
[[https://projectsanctuary.com/the_complete_ferengi_rules_of_acquisition.htm][Project Sanctuary List]]

1. Once you have their money, never give it back

2. You can't cheat an honest customer, but it never hurts to try

3. Never spend more for an acquisition than you have to

4. Sex and profit are the two things that never last long enough

5. If you can't break a contract, bend it

6. Never let family stand in the way of opportunity

7. Always keep you ears open

8. Keep count of your change

9. Instinct plus opportunity equals profit

10. A dead customer can't buy as much as a live one

11. Latinum isn't the only thing that shines

12. Anything worth selling is worth selling twice

13. Anything worth doing is worth doing for money

14. Anything stolen is pure profit

15. Acting stupid is often smart

16. A deal is a deal ... until a better one comes along

17. A bargain usually isn't

18. A Ferengi without profit is no Ferengi at all

19. Don't lie too soon after a promotion

20. When the customer is sweating, turn up the heat

21. Never place friend ship before profit

22. Wise men can hear profit in the wind

23. Never take the last coin, but be sure to get the rest

24. Never ask when you can take

25. Fear makes a good business partner

26. The vast majority of the rich in this galaxy did not inherit their wealth; they stole it

27. The most beautiful thing about a tree is what you do with it after you cut it down

28. Morality is always defined by those in power

29. When someone says "It's not the money," they're lying

30. Talk is cheap; synthehol costs money

31. Never make fun of a Ferengi's mother

32. Be careful what you sell. It may do exactly what the customer expects

33. It never hurts to suck up to the boss

34. War is good for business

35. Peace is good for business

36. Too many Ferengi can't laugh at themselves anymore

37. You can always buy back a lost reputation

38. Free advertising is cheap

39. Praise is cheap. Heap it generously on all customers

40. If you see profit on a journey, take it

41. Money talks, but having a lots of it gets more attention

42. Only negotiate when you are certain to profit

43. Caressing an ear is often more forceful than pointing a weapon

44. Never argue with a loaded phaser

45. Profit has limits. Loss has none

46. Labor camps are full of people who trusted the wrong person

47. Never trust a man wearing a better suit than you own

48. The bigger the smile, the sharper the knife

49. Old age and greed will always overcome youth and talent

50. Never bluff a Klingon

51. Never admit a mistake if there's someone else to blame

52. Only Bugsy could have built Las Vegas

53. Sell first; ask questions later

54. Never buy anything you can't sell

55. Always sell at the highest possible profit

56. Pursue profit; women come later

57. Good customers are almost as rare as Latinum - treasure them

58. Friendship is seldom cheap

59. Fee advice is never cheap

60. Never use Latinum where your words will do

61. Never buy what can be stolen

62. The riskier the road, the greater the profit

63. Power without profit is like a ship without an engine

64. Don't talk shop; talk shopping

65. Don't talk ship; talk shipping

66. Anyone serving in a fleet who is crazy can be relieved, if they ask for it

67. Enough is never enough

68. Compassion is no substitute for a profit

69. You could afford your ship without your government - if it weren't for your government

70. Get the money first, then let the buyers worry about collecting the merchandise

71. Gamble and trade have two things in common: risk and Latinum

72. Never let the competition know, what you're thinking

73. Never trust advice from a dying Ferengi; listen but don't trust

74. A Ferengi without profit is no Ferengi at all

75. Home is where the heart is, but the stars are made of Latinum

76. Every once in a while, declare peace. It confuses the hell out of your enemies

77. Go where no Ferengi has gone before; where there is no reputation there is profit

78. Don't discriminate. The most unlikely species can create the best customers

79. Benefit from the Vulcan greed for knowledge

80. If it works, sell it. If it works well, sell it for more. If it doesn't work, quadruple the price and sell it as an antique

81. There's nothing more dangerous than an honest businessman

82. A smart customer is not a good customer

83. Revenge is profitless

84. She can touch your ears but never your Latinum

85. Death takes no bribes

86. A wife is a luxury, a smart accountant a necessity

87. Trust is the biggest liability of all

88. When the boss comes to dinner, it never hurts to have the wife wear something

89. Latinum lasts longer than lust

90. Mine is better than ours

91. He who drinks fast pays slow

92. Never confuse wisdom with luck

93. He's a fool who makes his doctor his heir

94. Beware of small expenses: a small leak will kill a ship

95. Important, more impotant, Latinum

96. Faith moves mountains - of inventory

97. If you would keep a secret from an enemy, don't tell it to a friend

98. Profit is the better part of valor

99. Never trust a wise man

100. Everything that has no owner, needs one

101. Never do something you can make someone do for you

102. Nature decays, but Latinum lasts forever

103. Sleep can interfere with opportunity

104. Money is never made. It is merely won or lost

105. Wise men don't lie, they just bend the truth

106. There is no honor in poverty

107. Win or lose, there's always Huyperian Beetle Snuff

108. A woman wearing clothes is like a man without profit

109. Dignity and an empty sack is worth the sack

110. Only a fool passes up a business opportunity

111. Treat people in your debt like family ... exploit them

112. Never sleep with the boss's wife unless you pay him first

113. Never sleep with the boss's sister

114. Small print lead to large risk

115. Greed is eternal

116. There's always a way out

117. If the profit seems too good to be true, it usually is

118. Never cheat a honest man offering a decent price

119. Buy, sell, or get out of the way

120. Even a blind man can recognize the glow of Latinum

121. Everything is for sale, even friendship

122. As the customers go, so goes the wise profiteer

123. A friend is only a friend until you sell him something. Then he is a customer

124. Friendship is temporary, profit is forever

125. A lie isn't a lie until someone else knows the truth

126. A lie isn't a lie, it's just the truth seen from a different point of view

127. Gratitude can bring on generosity

128. Ferengi are not responsible for the stupidity of other races

129. Never trust your customers

130. Never trust a beneficiary

131. If it gets you profit, sell your own mother

132. The flimsier the produce, the higher the price

133. Never judge a customer by the size of his wallet ... sometimes good things come in small packages

134. There's always a catch

135. The only value of a collectible is what you can get somebody else to pay for it

136. The sharp knife cuts quickly. Act without delay!

137. Necessity is the mother of invention. Profit is the father

138. Law makes everyone equal, but justice goes to the highest bidder

139. Wives serve; brother inherit

140. The answer to quick and easy profit is: buy for less, sell for more

141. Competition and fair play are mutually exclusive. Fair play and financial loss go hand-in-hand

142. A Ferengi waits to bid until his opponents have exhausted themselves

143. The family of Fools is ancient

144. There's nothing wrong with charity ... as long as it winds up in your pocket

145. Always ask for the costs first

146. If possible sell neither the sizzle nor the steak, but the Elphasian wheat germ

147. New customers are like razor toothed gree worms. They can be succulent, but sometimes they bite back

148. Opportunity waits for no one

149. Females and finances don't mix

150. Make your shop easy to find

151. Sometimes, what you get free costs entirely too much

152. Ask not what your profits can do for you; ask what you can do for your profits

153. You can't free a fish from water

154. The difference between manure and Latinum is commerece

155. What's mine is mine, and what's yours is mine too

156. Even in the worst of times someone turns a profit

157. You are surrounded by opportunities; you just have to know where to look

158. Don't pay until you have the goods

159. The customer is always right ... until you have their cash

160. Respect is good, Latinum is better

161. Never kill a customer, unless you make more profit out of his death than out of his life

162. His money is only your's when he can't get it back

163. A thirsty customer is good for profit, a drunk one isn't

164. Never spend your own money when you can spend someone elses

165. Never allow one's culture's law to get in the way of a universal goal: profit

166. Never give away for free what can be sold

167. If a deal is fairly and lawfully made, then seeking revenge especially unprofitable revenge, is illegal

168. Beware of relatives bearing gifts

169. If you're going to have to endure, make yourself comfortable

170. Never gamble with an empath

171. Time is Latinum. The early Ferengi get the Latinum

172. If you can sell it, don't hsitate to steal it

173. A piece of Latinum in the hand is worth two in a customer's pocket

174. Share and perish

175. When everything fails - run

176. Ferengi's don't give promotional gifts!

177. Know your enemies ... but do business with them always

178. The world is a stage - don't forget to demand admission

179. Whenever you think that things can't get worse, the FCA will be knocking on you door

180. Never offer a confession when a bribe will do

181. Even dishonesty can't tarnish the glow of Latinum

182. Whenever you're being asked if you are god, the right answer is YES

183. Genius without opportunity is like Latinum in the mine

184. There are three things you must not talk to aliens: sex, religion and taxes

185. If you want to ruin yourself there are three known ways: Gambling is the fastest, women are the sweetest, and banks are the most reliable way

186. There are two things that will catch up with you for sure: death and taxes

187. If your dancing partner wants to lead at all costs, let her have her own way and ask another one to dance

188. Never bet on a race you haven't fixed

189. Borrow on a handshake; lend in writing

190. Drive your business or it will drive you

191. Let other keep their reputation. You keep their money

192. If the flushing isn't strong enough, use your brain and try the brush

193. Klingon women don't dance tango

194. It's always good business to know about new customers before they walk in your door

195. Wounds heal, but debt is forever

196. Only give money to people you know you can steal from

197. Never trust your customers, especially if they are your relatives

198. Employees are the rungs on your ladder to success - don't hesitate to step on them

199. The secret of one person is another person's opportunity

200. A madman with Latinum means profit without return

201. The justification for profit is profit

202. a)  A friend in need is a customer in the making

203. A friend in need means three times the profit

204. A Ferengi in need, will never do anything for free

205. When the Grand Nagus arrives to offer you a business opportunity, it's time to leave town until he's gone

206. When the customer dies, the money stops a-comin'

207. Fighting with Klingons is like gambling with Cardassians - it's good to have a friend around when you lose

208. Never trust a hardworking employee

209. Give someone a fish, you feed him for one day.  Teach him how to fish, and you lose a steady customer

210. Tell them what they want to hear

211. A wife, who is able to clean, saves the cleaning lady

212. In business deals, a disruptor can be almost as important as a calculator

213. If they accept your first offer, you either asked too little or offered too much

214. Stay neutral in conflicts so that you can sell supplies to both sides

215. Never begin a business transaction on an empty stomach

216. Instinct without opportunity is useless

217. Never take hospitality from someone worse off than yourself

218. Only pay for it if you are confronted with loaded phaser

219. Always know what you're buying

220. A friend is not a friend if he asks for a discount

221. Profit is like a bed of roses - a few thorns are inevitable

222. Beware of any man who thinks with his lobes

223. Knowledge is Latinum

224. Rich men don't come to buy; they come to take

225. Never throw anything away: It may be worht a lot of Latinum some Stardate

226. Pride comes before a loss

227. Don't take your family for granted, only their Latinum

228. Loyalty can be bought ... and sold

229. All things come to those who wait, even Latinum

230. Beware the man who doesn't make time for oo-mox

231. Manipulation may be a Ferengi's greatest tool, and liability

232. If you steal it, make sure it has a warranty

233. Life's no fair (How else would you turn a profit?)

234. Every dark cloud has a Latinum lining

235. Never deal with beggars; it's bad for profits

236. Don't trust anyone who trusts you

237. You can't buy fate

238. There's a sucker born every minute.  Be sure you're the first to find each one

239. The truth will cost

240. Ambition knows no family

241. The higher you bid, the more customers you drive away

242. Never underestimate the inportance of the fist impression

243. More is good, all is better

244. If you got something nice to say, then SHOUT

245. If you can't sell it, sit on it, but never give it away

246. A warranty is valid only if they can find you

247. He that speaks ill of the wares will buy them

248. Never question luck

249. Celebrate when you are paid, not, when you are promised

250. Respect other culture's beliefs; they'll be more likely to give you money

251. A dead vendor doesn't demand money

252. Satisfaction is not guaranteed

253. Let the buyer beware

254. A contract without fine print is a fool's document

255. Anyone who can't tell a fake doesn't deserve the real thing

256. A warranty without loop-holes is a liability

257. Synthehol is the lubricant of choice for a customer's stuck purse

258. Only fools negotiate with their own money

259. A Ferengi is only as important as the amount of Latinum he carries in his pockets

260. A lie is a way to tell the truth to someone who doesn't know

261. Gambling is like the way to power: The only way to win is to cheat, but don't get caught in the process

262. A wealthy man can afford everything except a conscience

263. No lobes, no profit

264. Never let a female in clothes cloud your sense of profit

265. It's not the size of your planet, but it's income, that matters

266. The fear of loss may be your greatest enemy or your best friend - choose wisely

267. A pair of good ears will ring dry a hundred tongues

268. Wish not so much to live Long, as to live well

269.
     a) When in doubt, lie

     b) When in doubt, buy

270. When in doubt, demand more money

271. When in doubt, shoot them, take their money, run and blame someone else

272. Never purchase anything that has been promised to be valuable or go up in value

273. It's better to have gambled and lost than to never have gambled at all

274. There's many witty men whose brains can't line their pockets

275. The way to a Ferengi's heart is through his wallet

276. Always count their Latinum before selling anything

277. There is no profit in love; however, a strong heart is worth a few bars of Latinum on the open market. Keep it on ice

278. Latinum can't buy happiness, but you can sure have a blast renting it

279. If at first you don't succeed, try to acquire again

280. Diamonds may be girl's best friend, but you can only buy the girl with Latinum

281. It's better to swallow your pride than to lose your profit

282. Never close a deal too soon after a female strokes your lobes

283. An empty bag can not stand upright

284. Blood is thicker than water, but harder to sell

285. Business is like war; it's important to recognize the winner

286. Rules are always subject to change

287. Rules are always subject to interpretation

288. No good deed ever goes unpunished

289. When Morn leaves it is all over
* Chick Corea
 CHEAP BUT GOOD ADVICE FOR PLAYING MUSIC IN A GROUP
 Chick Corea

1. Play only what you hear.
2. If you don't hear anything, don't play anything.
3. Don't let your fingers and limbs just wander--place them intentionally.
4. Don't improvise on endlessly--play, something with intention, develop it or not, but then end off, take a break.
5. Leave space--create space--intentionally create places where you don't play.
6. Make your sound blend. Listen to your sound and adjust it to the rest of the band and the room.
7. If you play more than one instrument at a time--like a drum kit or multiple keyboards-make sure that they are balanced with one another.
8. Don't make any of your music mechanically or just through patterns of habit. Create each sound, phrase, and piece with choice--deliberately.
9. Guide your choice of what to play by what you like-not by what someone else will think.
10. Use contrast and balance the elements: high/low, fast/slow, loud/soft, tense/relaxed, dense/sparse.
11. Play to make the other musicians sound good. Play things that will make the overall music sound good.
12. Play with a relaxed body. Always release whatever tension you create.
13. Create space--begin, develop, and end phrases with intention.
14. Never beat or pound your instrument--play it easily and grace- fully.
15. Create space-- then place something in it.
16. Use mimicry sparsely--mostly create phrases that contrast with and develop the phrases of the other players.
* John Lambert                                    :hacking:security:threat_assessment:
    What is the most important network security spend: Sensor
    appliances? SIEM? Threat intelligence feeds? It's your analyst
    team.

    Defenders, you're not stopping attacks. You're increasing attacker
    requirements. 'Stopping' breeds a mindset ignorant of
    countermoves.

    Your network is a directed graph of credentials. Hacking is graph
    traversal. See the graph or all you'll see is exfil.

    Things go wrong right here. Admins focus on control to possess
    secrets. Hackers focus on secrets to possess control. Hackers are
    right.

    On vulns: You can argue over exposure, difficulty, and
    likelihood. Security researchers write exploits because they like
    the truth.

    Pentest is the most misused security practice. Pentest is
    diagnostic. Go from treating the bugs as output, to treating them
    as input.

    Software engrs hide reality by using architecture over
    implementation. Hackers reveal reality by using implementation
    against architecture

    Do security jobs need a degree? Remember self-taught hackers made
    most of our progress. When academia sits out, autodidacts show the
    way.

    If you shame attack research, you misjudge its
    contribution. Offense and defense aren't peers. Defense is
    offense's child.

    Biggest problem with network defense is that defenders think in
    lists. Attackers think in graphs. As long as this is true,
    attackers win
* Matthew Frederick
101 Things I learned in Architecture School

 Being process-oriented, not product driven, is the most important and difficult skill for
 a designer to develop.
 Being process-oriented means:
 1) seeking to understand a design problem before chasing after solutions;
 2) not force-fitting solutions to old problems onto new problems
 3) removing yourself from prideful investment in your projects and being slow to fall in
    love with your ideas
 4) making design investigations and decisions holistically (that address several aspects of a
    design problem at once) rather than sequentially (that finalize one aspect of a solution
    before investigating the next)
 5) making design decisions conditionally - that is, with the awareness that they may
    or may not work out as you continue toward a final solution
 6) knowing when to change and when to stick with previous decisions
 7) accepting as normal the anxiety that comes from not knowing what to do
 8) working fluidly between concept-scale and detail-scale to see how each informs the other
 9) always asking "What if...?" regardless of how satisfied you are with your solution.
* Robert Greene
** Law 1: Never Outshine the Master

   Always make those above you feel comfortably
   superior.  In your desire to please or impress
   them, do not go too far in displaying your talents
   or you might accomplish the opposite – inspire
   fear and insecurity.  Make your masters appear
   more brilliant than they are and you will attain
   the heights of power.

** Law 2: Never put too Much Trust in Friends, Learn how to
   use Enemies

   Be wary of friends-they will betray you more
   quickly, for they are easily aroused to envy.
   They also become spoiled and tyrannical. But hire
   a former enemy and he will be more loyal than a
   friend, because he has more to prove.  In fact,
   you have more to fear from friends than from
   enemies.  If you have no enemies, find a way to
   make them.

** Law 3: Conceal your Intentions

   Keep people off-balance and in the dark by never
   revealing the purpose behind your actions.  If
   they have no clue what you are up to, they cannot
   prepare a defense.  Guide them far enough down the
   wrong path, envelope them in enough smoke, and by
   the time they realize your intentions, it will be
   too late.

** Law 4: Always Say Less than Necessary

   When you are trying to impress people with words,
   the more you say, the more common you appear, and
   the less in control.  Even if you are saying
   something banal, it will seem original if you make
   it vague, open-ended, and sphinxlike.  Powerful
   people impress and intimidate by saying less.  The
   more you say, the more likely you are to say
   something foolish.

** Law 5: So Much Depends on Reputation – Guard it with your Life

   Reputation is the cornerstone of power.  Through
   reputation alone you can intimidate and win; once
   you slip, however, you are vulnerable, and will be
   attacked on all sides.  Make your reputation
   unassailable.  Always be alert to potential
   attacks and thwart them before they happen.
   Meanwhile, learn to destroy your enemies by
   opening holes in their own reputations.  Then
   stand aside and let public opinion hang them.

** Law 6: Court Attention at all Cost

   Everything is judged by its appearance; what is
   unseen counts for nothing.  Never let yourself get
   lost in the crowd, then, or buried in oblivion.
   Stand out.  Be conspicuous, at all cost.  Make
   yourself a magnet of attention by appearing
   larger, more colorful, more mysterious, than the
   bland and timid masses.

** Law 7: Get others to do the Work for you, but Always Take the Credit

   Use the wisdom, knowledge, and legwork of other
   people to further your own cause.  Not only will
   such assistance save you valuable time and energy,
   it will give you a godlike aura of efficiency and
   speed.  In the end your helpers will be forgotten
   and you will be remembered.  Never do yourself
   what others can do for you.

** Law 8: Make other People come to you – use Bait if Necessary

   When you force the other person to act, you are
   the one in control.  It is always better to make
   your opponent come to you, abandoning his own
   plans in the process.  Lure him with fabulous
   gains – then attack.  You hold the cards.

** Law 9: Win through your Actions, Never through Argument

   Any momentary triumph you think gained through
   argument is really a Pyrrhic victory: The
   resentment and ill will you stir up is stronger
   and lasts longer than any momentary change of
   opinion.  It is much more powerful to get others
   to agree with you through your actions, without
   saying a word.  Demonstrate, do not explicate.

** Law 10: Infection: Avoid the Unhappy and Unlucky

   You can die from someone else’s misery – emotional
   states are as infectious as disease.  You may feel
   you are helping the drowning man but you are only
   precipitating your own disaster.  The unfortunate
   sometimes draw misfortune on themselves; they will
   also draw it on you.  Associate with the happy and
   fortunate instead.

** Law 11: Learn to Keep People Dependent on You

   To maintain your independence you must always be
   needed and wanted.  The more you are relied on,
   the more freedom you have.  Make people depend on
   you for their happiness and prosperity and you
   have nothing to fear.  Never teach them enough so
   that they can do without you.

** Law 12: Use Selective Honesty and Generosity to Disarm your Victim

   One sincere and honest move will cover over dozens
   of dishonest ones.  Open-hearted gestures of
   honesty and generosity bring down the guard of
   even the most suspicious people.  Once your
   selective honesty opens a hole in their armor, you
   can deceive and manipulate them at will.  A timely
   gift – a Trojan horse – will serve the same
   purpose.

** Law 13: When Asking for Help, Appeal to People’s Self-Interest, Never to their Mercy or Gratitude

   If you need to turn to an ally for help, do not
   bother to remind him of your past assistance and
   good deeds.  He will find a way to ignore you.
   Instead, uncover something in your request, or in
   your alliance with him, that will benefit him, and
   emphasize it out of all proportion.  He will
   respond enthusiastically when he sees something to
   be gained for himself.

** Law 14: Pose as a Friend, Work as a Spy

   Knowing about your rival is critical.  Use spies
   to gather valuable information that will keep you
   a step ahead.  Better still: Play the spy
   yourself.  In polite social encounters, learn to
   probe.  Ask indirect questions to get people to
   reveal their weaknesses and intentions.  There is
   no occasion that is not an opportunity for artful
   spying.

** Law 15: Crush your Enemy Totally

   All great leaders since Moses have known that a
   feared enemy must be crushed completely.
   (Sometimes they have learned this the hard way.)
   If one ember is left alight, no matter how dimly
   it smolders, a fire will eventually break out.
   More is lost through stopping halfway than through
   total annihilation: The enemy will recover, and
   will seek revenge.  Crush him, not only in body
   but in spirit.

** Law 16: Use Absence to Increase Respect and Honor

   Too much circulation makes the price go down: The
   more you are seen and heard from, the more common
   you appear.  If you are already established in a
   group, temporary withdrawal from it will make you
   more talked about, even more admired.  You must
   learn when to leave.  Create value through
   scarcity.

** Law 17: Keep Others in Suspended Terror: Cultivate an Air of Unpredictability

   Humans are creatures of habit with an insatiable
   need to see familiarity in other people’s actions.
   Your predictability gives them a sense of control.
   Turn the tables: Be deliberately unpredictable.
   Behavior that seems to have no consistency or
   purpose will keep them off-balance, and they will
   wear themselves out trying to explain your moves.
   Taken to an extreme, this strategy can intimidate
   and terrorize.

** Law 18: Do Not Build Fortresses to Protect Yourself – Isolation is Dangerous

   The world is dangerous and enemies are everywhere
   – everyone has to protect themselves.  A fortress
   seems the safest. But isolation exposes you to
   more dangers than it protects you from – it cuts
   you off from valuable information, it makes you
   conspicuous and an easy target.  Better to
   circulate among people find allies, mingle.  You
   are shielded from your enemies by the crowd.

** Law 19: Know Who You’re Dealing with – Do Not Offend the Wrong Person

   There are many different kinds of people in the
   world, and you can never assume that everyone will
   react to your strategies in the same way.  Deceive
   or outmaneuver some people and they will spend the
   rest of their lives seeking revenge.  They are
   wolves in lambs’ clothing.  Choose your victims
   and opponents carefully, then – never offend or
   deceive the wrong person.

** Law 20: Do Not Commit to Anyone

   It is the fool who always rushes to take sides.
   Do not commit to any side or cause but yourself.
   By maintaining your independence, you become the
   master of others – playing people against one
   another, making them pursue you.

** Law 21: Play a Sucker to Catch a Sucker – Seem Dumber than your Mark

   No one likes feeling stupider than the next
   persons.  The trick, is to make your victims feel
   smart – and not just smart, but smarter than you
   are.  Once convinced of this, they will never
   suspect that you may have ulterior motives.

** Law 22: Use the Surrender Tactic: Transform Weakness into Power

   When you are weaker, never fight for honor’s sake;
   choose surrender instead.  Surrender gives you
   time to recover, time to torment and irritate your
   conqueror, time to wait for his power to wane.  Do
   not give him the satisfaction of fighting and
   defeating you – surrender first.  By turning the
   other check you infuriate and unsettle him.  Make
   surrender a tool of power.

** Law 23: Concentrate Your Forces

   Conserve your forces and energies by keeping them
   concentrated at their strongest point.  You gain
   more by finding a rich mine and mining it deeper,
   than by flitting from one shallow mine to another
   – intensity defeats extensity every time.  When
   looking for sources of power to elevate you, find
   the one key patron, the fat cow who will give you
   milk for a long time to come.

** Law 24: Play the Perfect Courtier

   The perfect courtier thrives in a world where
   everything revolves around power and political
   dexterity.  He has mastered the art of
   indirection; he flatters, yields to superiors, and
   asserts power over others in the mot oblique and
   graceful manner.  Learn and apply the laws of
   courtiership and there will be no limit to how far
   you can rise in the court.

** Law 25: Re-Create Yourself

   Do not accept the roles that society foists on
   you.  Re-create yourself by forging a new
   identity, one that commands attention and never
   bores the audience.  Be the master of your own
   image rather than letting others define if for
   you.  Incorporate dramatic devices into your
   public gestures and actions – your power will be
   enhanced and your character will seem larger than
   life.

** Law 26: Keep Your Hands Clean

   You must seem a paragon of civility and
   efficiency: Your hands are never soiled by
   mistakes and nasty deeds.  Maintain such a
   spotless appearance by using others as scapegoats
   and cat’s-paws to disguise your involvement.

** Law 27: Play on People’s Need to Believe to Create a Cultlike Following

   People have an overwhelming desire to believe in
   something.  Become the focal point of such desire
   by offering them a cause, a new faith to follow.
   Keep your words vague but full of promise;
   emphasize enthusiasm over rationality and clear
   thinking.  Give your new disciples rituals to
   perform, ask them to make sacrifices on your
   behalf.  In the absence of organized religion and
   grand causes, your new belief system will bring
   you untold power.

** Law 28: Enter Action with Boldness

   If you are unsure of a course of action, do not
   attempt it.  Your doubts and hesitations will
   infect your execution.  Timidity is dangerous:
   Better to enter with boldness.  Any mistakes you
   commit through audacity are easily corrected with
   more audacity.  Everyone admires the bold; no one
   honors the timid.

** Law 29: Plan All the Way to the End

   The ending is everything.  Plan all the way to it,
   taking into account all the possible consequences,
   obstacles, and twists of fortune that might
   reverse your hard work and give the glory to
   others.  By planning to the end you will not be
   overwhelmed by circumstances and you will know
   when to stop.  Gently guide fortune and help
   determine the future by thinking far ahead.

** Law 30: Make your Accomplishments Seem Effortless

   Your actions must seem natural and executed with
   ease.  All the toil and practice that go into
   them, and also all the clever tricks, must be
   concealed.  When you act, act effortlessly, as if
   you could do much more.  Avoid the temptation of
   revealing how hard you work – it only raises
   questions.  Teach no one your tricks or they will
   be used against you.

** Law 31: Control the Options: Get Others to Play with the Cards you Deal

   The best deceptions are the ones that seem to give
   the other person a choice: Your victims feel they
   are in control, but are actually your puppets.
   Give people options that come out in your favor
   whichever one they choose.  Force them to make
   choices between the lesser of two evils, both of
   which serve your purpose.  Put them on the horns
   of a dilemma: They are gored wherever they turn.

** Law 32: Play to People’s Fantasies

   The truth is often avoided because it is ugly and
   unpleasant.  Never appeal to truth and reality
   unless you are prepared for the anger that comes
   for disenchantment.  Life is so harsh and
   distressing that people who can manufacture
   romance or conjure up fantasy are like oases in
   the desert: Everyone flocks to them. There is
   great power in tapping into the fantasies of the
   masses.

** Law 33: Discover Each Man’s Thumbscrew

   Everyone has a weakness, a gap in the castle wall.
   That weakness is usual y an insecurity, an
   uncontrollable emotion or need; it can also be a
   small secret pleasure.  Either way, once found, it
   is a thumbscrew you can turn to your advantage.

** Law 34: Be Royal in your Own Fashion: Act like a King to be treated like one

   The way you carry yourself will often determine
   how you are treated; In the long run, appearing
   vulgar or common will make people disrespect you.
   For a king respects himself and inspires the same
   sentiment in others.  By acting regally and
   confident of your powers, you make yourself seem
   destined to wear a crown.

** Law 35: Master the Art of Timing

   Never seem to be in a hurry – hurrying betrays a
   lack of control over yourself, and over time.
   Always seem patient, as if you know that
   everything will come to you eventually.  Become a
   detective of the right moment; sniff out the
   spirit of the times, the trends that will carry
   you to power.  Learn to stand back when the time
   is not yet ripe, and to strike fiercely when it
   has reached fruition.

** Law 36: Disdain Things you cannot have: Ignoring them is the best Revenge

   By acknowledging a petty problem you give it
   existence and credibility.  The more attention you
   pay an enemy, the stronger you make him; and a
   small mistake is often made worse and more visible
   when you try to fix it.  It is sometimes best to
   leave things alone.  If there is something you
   want but cannot have, show contempt for it.  The
   less interest you reveal, the more superior you
   seem.

** Law 37: Create Compelling Spectacles

   Striking imagery and grand symbolic gestures
   create the aura of power – everyone responds to
   them.  Stage spectacles for those around you, then
   full of arresting visuals and radiant symbols that
   heighten your presence.  Dazzled by appearances,
   no one will notice what you are really doing.

** Law 38: Think as you like but Behave like others

   If you make a show of going against the times,
   flaunting your unconventional ideas and unorthodox
   ways, people will think that you only want
   attention and that you look down upon them.  They
   will find a way to punish you for making them feel
   inferior.  It is far safer to blend in and nurture
   the common touch. Share your originality only with
   tolerant friends and those who are sure to
   appreciate your uniqueness.

** Law 39: Stir up Waters to Catch Fish

   Anger and emotion are strategically
   counterproductive.  You must always stay calm and
   objective.  But if you can make your enemies angry
   while staying calm yourself, you gain a decided
   advantage.  Put your enemies off-balance: Find the
   chink in their vanity through which you can rattle
   them and you hold the strings.

** Law 40: Despise the Free Lunch

   What is offered for free is dangerous – it usually
   involves either a trick or a hidden obligation.
   What has worth is worth paying for.  By paying
   your own way you stay clear of gratitude, guilt,
   and deceit.  It is also often wise to pay the full
   price – there is no cutting corners with
   excellence.  Be lavish with your money and keep it
   circulating, for generosity is a sign and a magnet
   for power.

** Law 41: Avoid Stepping into a Great Man’s Shoes

   What happens first always appears better and more
   original than what comes after.  If you succeed a
   great man or have a famous parent, you will have
   to accomplish double their achievements to
   outshine them.  Do not get lost in their shadow,
   or stuck in a past not of your own making:
   Establish your own name and identity by changing
   course.  Slay the overbearing father, disparage
   his legacy, and gain power by shining in your own
   way.

** Law 42: Strike the Shepherd and the Sheep will Scatter

   Trouble can often be traced to a single strong
   individual – the stirrer, the arrogant underling,
   the poisoned of goodwill.  If you allow such
   people room to operate, others will succumb to
   their influence.  Do not wait for the troubles
   they cause to multiply, do not try to negotiate
   with them – they are irredeemable.  Neutralize
   their influence by isolating or banishing them.
   Strike at the source of the trouble and the sheep
   will scatter.

** Law 43: Work on the Hearts and Minds of Others

   Coercion creates a reaction that will eventually
   work against you.  You must seduce others into
   wanting to move in your direction.  A person you
   have seduced becomes your loyal pawn.  And the way
   to seduce others is to operate on their individual
   psychologies and weaknesses.  Soften up the
   resistant by working on their emotions, playing on
   what they hold dear and what they fear.  Ignore
   the hearts and minds of others and they will grow
   to hate you.

** Law 44: Disarm and Infuriate with the Mirror Effect

   The mirror reflects reality, but it is also the
   perfect tool for deception: When you mirror your
   enemies, doing exactly as they do, they cannot
   figure out your strategy.  The Mirror Effect mocks
   and humiliates them, making them overreact.  By
   holding up a mirror to their psyches, you seduce
   them with the illusion that you share their
   values; by holding up a mirror to their actions,
   you teach them a lesson.  Few can resist the power
   of Mirror Effect.

** Law 45: Preach the Need for Change, but Never Reform too much at Once

   Everyone understands the need for change in the
   abstract, but on the day-to-day level people are
   creatures of habit.  Too much innovation is
   traumatic, and will lead to revolt.  If you are
   new to a position of power, or an outsider trying
   to build a power base, make a show of respecting
   the old way of doing things.  If change is
   necessary, make it feel like a gentle improvement
   on the past.

** Law 46: Never appear too Perfect

   Appearing better than others is always dangerous,
   but most dangerous of all is to appear to have no
   faults or weaknesses.  Envy creates silent
   enemies.  It is smart to occasionally display
   defects, and admit to harmless vices, in order to
   deflect envy and appear more human and
   approachable.  Only gods and the dead can seem
   perfect with impunity.

** Law 47: Do not go Past the Mark you Aimed for; In Victory, Learn when to Stop

   The moment of victory is often the moment of
   greatest peril.  In the heat of victory, arrogance
   and overconfidence can push you past the goal you
   had aimed for, and by going too far, you make more
   enemies than you defeat.  Do not allow success to
   go to your head.  There is no substitute for
   strategy and careful planning.  Set a goal, and
   when you reach it, stop.

** Law 48: Assume Formlessness

   By taking a shape, by having a visible plan, you
   open yourself to attack.  Instead of taking a form
   for your enemy to grasp, keep yourself adaptable
   and on the move.  Accept the fact that nothing is
   certain and no law is fixed.  The best way to
   protect yourself is to be as fluid and formless as
   water; never bet on stability or lasting order.
   Everything changes.
