# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: local
  hooks:
    - id: dootBuild
      name: dootBuild
      description: run the pelican build
      language: system
      entry: mamba run "-n" "doot-dev" doot "pelican::build"
      always_run: true
      verbose: true
      require_serial: true
      stages: [post-commit]
