verbosity               = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
log_filters   =  ['doot', 'bkmkorg'] # <list>
log_format   =  "{levelname} : {message}" # <str>

[tool.doot.directories]
src            = "."
temp           = ".temp"
build          = "build"
docs           = "orgfiles"
data           = "resources"

bibtex         = "resources/bibliography"
bibtex_working = "/Volumes/documents/in_progress_pdfs/Current/"

bookmarks      = "resources/bookmarks"
completions    = "resources/completions"
tags           = "resources/tags"
urls           = "resources/urls"

pdfs      = "/Volumes/documents/pdflibrary"
# orgs    = "/Volumes/documents/twitterthreads"
orgs      = "orgfiles"
downloads = "~/Downloads"
desktop   = "~/Desktop"
dropbox   = "~/Dropbox/docs"
firefox   = "~/Library/ApplicationSupport/Firefox"

[tool.doot.files]
bib_stub_file   = "resources/todo.bib"
bookmarks_total = "resources/bookmarks/total.bookmarks"
