action_string_formatting = "new"
batch                    = {sleep = 5}
default_tasks            = ["locs::report"]
notify                   = {say-on-exit = false}
subtask                  = {sleep = 1}
verbosity                = 2

[logging]
stream = { level = "INFO", format  = "{levelname:<8} : {message}", filters = ["doot"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} : ({module}.{lineno}.{funcName})", filters =  ["doot", "pelican"] }

[globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[[directories]] # core
temp       = ".temp"
build      = "build"
docs       = "orgfiles"
res        = "resources"

[[directories]] # github pages / pelican
site             = "site"
codegen          = "site/_generated"
site_build       = "build/site"
pelican_settings = "pelican.toml"

[[directories]] # libraries
bibtex         = "resources/bibliography"
bookmarks      = "resources/bookmarks"
completions    = "resources/completions"
tags           = "resources/tags"
urls           = "resources/urls"
orgs           = "orgfiles"
pdfs           = "/Volumes/documents/pdf_library"
bibtex_working = "/Volumes/documents/in_progress_pdfs/Current/"

[[directories]] # Watch folders
threads   = "/Volumes/documents/twitter_threads"
downloads = "~/Downloads"
desktop   = "~/Desktop"
dropbox   = "~/Dropbox/docs"
firefox   = "~/Library/ApplicationSupport/Firefox"

[[files]]
bib_stub_file   = "resources/todo.bib"
bookmarks_total = "resources/bookmarks/total.bookmarks"

[bibtex]
clean_in_place = true
