verbosity               = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
subtask = {sleep = 1}
batch   = {sleep = 5}
notify  = {say-on-exit = false}


[tool.doot.logging]
stream = { level = "INFO", format  = "{levelname:<8} : {message}", filters = ["doot", "bkmkorg"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} : ({module}.{lineno}.{funcName})", filters =  ["doot", "bkmkorg"] }

[tool.doot.globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[[tool.doot.directories]] # core
src            = "."
temp           = ".temp"
build          = "build"
docs           = "orgfiles"
data           = "resources"

[[tool.doot.directories]] # libraries
bibtex         = "resources/bibliography"
bookmarks      = "resources/bookmarks"
completions    = "resources/completions"
tags           = "resources/tags"
urls           = "resources/urls"
pdfs           = "/Volumes/documents/pdflibrary"
orgs           = "orgfiles"
bibtex_working = "/Volumes/documents/in_progress_pdfs/Current/"

[[tool.doot.directories]] # Watch folders
# orgs    = "/Volumes/documents/twitterthreads"
downloads = "~/Downloads"
desktop   = "~/Desktop"
dropbox   = "~/Dropbox/docs"
firefox   = "~/Library/ApplicationSupport/Firefox"

[[tool.doot.files]]
bib_stub_file   = "resources/todo.bib"
bookmarks_total = "resources/bookmarks/total.bookmarks"
