verbosity               = 2

[tool.doot]

[tool.doot.directories]
src = "."
temp           = ".temp"
build          = "build"
docs           = "orgfiles"
data           = "resources"
bibtex         = "resources/bibliography"
bookmarks      = "resources/bookmarks"
completions    = "resources/completions"
tags           = "resources/tags"
urls           = "resources/urls"

pdfs           = "/Volumes/documents/pdflibrary"
orgs           = "/Volumes/documents/twitterthreads"
downloads      = "~/Downloads"
desktop        = "~/Desktop"
dropbox        = "~/Dropbox/docs"
firefox        = "~/Library/ApplicationSupport/Firefox"
bibtex_working = "/Volumes/documents/in_progress_pdfs/Current/"

[tool.doot.files]
bib_stub_file  = "resources/todo.bib"
