* Game Ideas copied from note cards
** Institution Play
American Psycho / The Office / Parks and Rec / *Suits* like office
games. Favours and grudges within bounds, reverting to working
together when dealing with outside threats.

** At Home
The variations and peculiarities that Bill Bryson highlights,
integrated into the Sims.

** Space Colonies
2312-like Terraria / Off world Colonies. The fragility of space
living, and the influence of orbiting planets for travel and trade.

** Observable Democracy
A Positech Democracy like simulation, but where actions are modelled,
possibly sims like, that *shows* the consequences of legalising drugs
/ banning firearms / increase in crime etc.

** Social Roguelike
Binding of Isaac / Dungeon of Dredmor style game. Generated maps, with
social predicaments in collections of rooms instead of violent
enemies. 
Binding of Isaac style combination of a wide variety of pickups would
be interesting. 
Queuing as an example? Very British Problems?

** Society Generator
See Red Mars / Galactica / Walking Dead / other Post-apocalyptic
stories.
A linear set of challenges which define the rules of a society as it
grows, which is then simulated afterwards.
Eg: The choices of whether to ban or allow abortion, limit military
control etc in Galactica set up a particular society. The difference
is obvious when comparing Galactica to Pegasus.

** Judiciary / Activist Judge
Generate Criminal / Civil disputes, allow the player to set binding
rulings, punishments, fines, and restrictions. Define the hierarchy of
values for a society.

See also: Graeber: Accounting in defunct Roman coinage / Slaves /
Cows / Maidens.

** "Go Down to the Shops and Buy Some Milk"
Sliders-style world variation, where the player needs to survive for a
specified amount of time. 
Alt: Institutionalized / Normalized violence against specific classes
of people. Spawn as White / Black / Male / Female, and see how
behaviours towards you change.

** Monetary - Warfare - Slavery complex

** Socially Responsive RPGs

Where players have to abide by the norms instead of looting peasants'
houses.
Downton Abbey, Upstairs/Downstairs, and Gosford Park are good
examples.
Social contracts of how a hierarcy behaves. Those upstairs have rules
to abide by just as those downstairs.

** Accidents
Games do not typically include concepts of accidents. Tripping,
falling, hitting yourself accidentally. Swallowing food badly. We
often fail at being human, or will accidentally break. Such events are
what add uncertainty and stress to our lives. 
Related: Douglas Adams pseudo fractures.

** Guild Politics
Similar to Institution Play. Think Elder Scrolls, and Discworld's
Night Watch and Wizards. 
Wizards have rules on how they can assassinate others and climb the
ranks, Night watch covers the behaviour of the police, and who
supports whom. 

Also of note: The Night Watch scene of the assassination of Lord
Winder. Birds eye view of supporters and opposition, with intended
steering of parties.

Elder Scroll's Guilds don't particularly get you to do
anything. Tithes, preferred / prohibited / obligated behaviours etc. 
See Graeber for the cycle of debt that African trader institutions
worked within.

** Elevator Conversations
Dungeon of the Endless has conversations in the elevator, that hint at
more complex modeling. Distrust, blame, optimism etc could all come
into play during those elevator rides. Characters could refer back to
events that happened in the level just gone.

** Social Leaders
Designated individuals are Institutional Entrepreneurs, leading the
way for how others should behave. Trump is an example for bringing out
blatant racism. 

** Squad Dynamics
XCom doesn't include interactions between squad members. See MGS5's
Diamond Dogs, with some soldiers getting put in the brig. MGS's
weakness however is that the conflicts are left implicit, and aren't
shown ever. 

Soldiers joke, get nervous, shell-shocked, tired, and can hold
grudges. As they get injured, they can get particular scars and
prosthetics. The is similar to Elevator Conversations. 

** Social Lemmings

** Country Differences

Stand On Zanzibar compares broad descriptions of different
countries. This could work well in a Positech Democracy style game.






