* Procedural Society Examples                                                   :examples:society:
** Streets
   The way streets look, and the composition of them.
   The width, materials, and buildings on the street. 
   Police, homeless, and pedestrian presence.
   Cleanliness, sanitation, parks. 
   Level of technology, cars, lighting.
   Climate, smog.
   Variation between night and day.
   Likeliness of terrorism and crime.
   Behaviour of police, sexual harassment, racism, class tensions.
   Children playing.
   Friendliness of strangers, styles of greeting, and clothing.
   Grouping of individuals.
   What locations are popular.
** Newspapers
   Headlines display the values, and ordering of values, of a society.
   England/America: Different scales of scandals vs normal. Small scale spending scandals vs massive and accepted 'campaign contributions'.
   What acts of violence are major vs minor. Big headlines for domestic terrorism by outsiders, minor headlines for foreign terrorism.
   Scale of reporting. America: big deal out of small terrorist attacks while Iraq has massive casualties, which are barely reported by American media.
   The statements of political candidates. The rate of police abuse, and protests. 
   Strange versus normal stories. 'Aliens did X' versus 'Tax rates to increase'
   Calls for violence and assassinations, admissions of wrong doing, micro vs macro reporting
** Violence Escalation
   The pathways and steps in which non-compliance is escalated to eventual police violence.
   Ie: Graeber's notes on accessing a school library without a student id. Library staff -> School police -> State police. 
   What is the path of escalation when you keep saying "No" to someone's demands.
** Bureaucracy  
   To do task X, how many committees, boards, and agencies must you contact, forms filled out, 
   licenses obtained, permits applied for, fees paid, studies conducted
   Officials bribed, killed, owed, 
