[project]
name = "jgrey4296-github-io"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "tox>=4.28.4",
    "tox-uv>=1.27.0",
    "pydot>=4.0.1",
]

