[project]
name = "jgrey4296-github-io"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "doot>=1.0.4",
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
