#+TITLE: Quotes
* Unverified
** Anon
 Self-Consciousness: "Why don't you wear your influenza mask?"
 "I'm afraid I might look funny."
 "Suppose you do. Wouldn't you rather introduce a little comedy into your household than subject it to a tragedy?"

 "We got a lot of phone calls and lettes, probably more than any other episode I can recall.
Interestingly, most of the phone calls were negative, while most of the letters were positive.
One that I always remember was a call that one of our PAs took.
A man said, 'You're ruining my kids by making them watch two women kiss like that.'
And our PA said, 'Let me ask you a question. Would you have been okay if one of the women had shot the other to death with a phaser and the kids watched that?'
And he said, 'Yes, of course'.
And the PA said, 'Well, maybe you'd better think about who it is that is ruining your kids'. "
 Quote regarding DS9 lesbian kiss.

"The legendary cellist Pablo Casals was asked why he continued to practice at age 90.
'Because I think I'm making progress' he replied."

"When you debate a person about something that affects them more than it affects you, remember
that it will take a much greater emotional toll on tem than you. For you it make feel like an
academic exercise. For them, it feels like revealing their pain only to have you dismiss their experience
and sometimes their humanity. The fact that you might remain more calm under these circumstances is a
consequence of your privilege, not increased objectivity on your part. Stay Humble."

"Weird hill to die on, but at least you're dead."

"In this school we are trauma-informed.
We connect before we correct.
We stay curious not furious.
We understand behaviour is communication.
We believe in co-regulation, that children regulate off the adults in their lives.
We think can't - not won't.
We empathise when someone is flipping their lid.
We believe in restoration - not punishment.
We believe that relationships buffer stress and build resilience.
All of us need one another, always.
Resilience means we see you, we hear you, we are with you."

"Mother, I've weight the risks which I prefer to living in a world dominated by Nazis."
- Bill, on his headstone.

"Computational tools aren't going to make people recognize our humanity."

"Capitalist Insanity: A Scientist prophesies that by the year 2020 the inhabitants of the world
will all be insane. Some of us are inclued to think that today the world is one huge insane asylum,
where the sane are kept in bondage by the insane."

"In 1996 racism may wear a new dress, buy a new pair of boots, but neither it nor its succubus twin
fascism is new or can make anything new. It can only reproduce the environment that supports its
own health: fear, denial and an atmosphere in which its victims have lost the will to fight.
The forces interested in fascist solutions to national problems are not to be found in
one political party or another, or in one or another wing of any single political party.
Democrats have no unsullied history of egalitarianism. Nor are liberals free of domination agendas.
Republicans have housed abolitionists and white supremacists.
Conservative, moderate, liberal; right, left, hard left, far right; religious, secular, socialist-
we must not be bliindsided by these Pepsi-Cola, Coca-Cola labels because the genius of fascism is
that any political structure can host the virus and virtually any developed country can
become a suitable home. Fascism talks ideology, but it is really just marketing -
marketing for power."

"Manifesto:
Make bad videogames
with orbs
where you can get stuck in walls
and fall through floors
that embrace the glitches and bugs
with amateurish hand draw grafix
that explore unexplored emotions
where you can pet animals
and pick flowers
and make friends
with no other goals."


"The writer, daytime insomniac.

Granted, to write is to renounce being in command of oneself or having a proper name,
and at the same time it is not to renounce, but to announce, welcoming without recognition the absent.
Or, it is to be in relation, through words in their absence, with what one cannot remember -
a withness to the unencountered, answerable not only for the void in the subject, but for the subject
as a void, it's disappearance in the imminence of a death which has already taken place,
out of place, any place at all."

"It pleases me that we may explore kindness with one another," Besarion said. "But do not mistake
my kindness for a gentle nature."

"I am not about to use literature to make this point.
Anyone who is interested can discuss it at length with actual women."

"When white folks can't defeat you they'll always find some Negro - some boot-licking, butt-licking
buck-dancing, bamboozled, half-baked, half-fried, sissified, punkified, pasteurized, homogenized nigger -
that they can trot out in front of you."

"Despite all our accomplishments we owe our existence to a six-inch layer of topsoil and the fact it rains"


"If someone says it's raining & another person says it's dry, it's not your job to quote them both.
Your job is to look out the fucking window and find out which is true."

"We weren't making a political statement. == We made a political statement unconsciously."
** Lyndon B. Johnson
If you can convince the lowest white man he's better than the best colored man,
he won't notice you're picking his pocket. Hell, give him somebody to look down on and
he'll empty his pockets for you.
** Rand Paul
Quoting @judgenap: Why do we have a second amendment? It's not to shoot deer.
It's to shoot at the government when it becomes tyrannical.
** Frank Zappa
Republicans stand for Raw, Unbridled Evil and Greed and Ignorance smothered in balloons and ribbons.

** David Dunning
An ignorant mind is precisely not a spotless, empty vessel, but one that's filled with the clutter of
irrelevant or misleading life experiences, theories, facts, intuitions, strategies,
algorithms, heuristics, metaphors and hunches that regrettably have the look and feel of
useful and accurate knowledge.
** Abdullah Zuber
Jihad will continue until all the Hindus, Christians, Buddhists, Atheists are killed.
Your secularism & tolerance can not change our ideology. Quran does not permit survival of non-muslims.
** Dr Zakir Naik
Every muslim is allowed to have sex with his female slave. If he does not have female slave and
wife is not at home then he must release his lust with sheep or goat.
** Kim Stanley Robinson
Thats libertarians for you - anarchists who want police protection from their slaves.
- Green Mars.
** Roosh
When a female gets a tattoo, she is giving a permanent oath of fealty to the oligarchs and their hired managers.
Her mind is controlled by their Satanic inversions, her body destined to be used and abused in exchange for
pleasure and power. Her tattoo is the mark of the beast.

** JFK
What do our opponents mean when they apply to us the label, "Liberal"? If by "Liberal" they mean, as they want people to believe, someone who is soft in his policies abroad, who is against local government, and who is unconcerned with the taxpayer's dollar, then the record of this party and its members demonstrate that we are not that kind of "Liberal." But, if by a "Liberal," they mean someone who looks ahead and not behind, someone who welcomes new ideas without rigid reactions, someone who cares about the welfare of the people - their health, their housing, their schools, their jobs, their civil rights, and their civil liberties - someone who believes that we can break through the stalemate and suspicions that grip us in our policies abroad, if that is what they mean by a "Liberal," then I'm proud to say that I'm a "Liberal."
- [[https://www.jfklibrary.org/archives/other-resources/john-f-kennedy-speeches/liberal-party-nomination-nyc-19600914][Accepting the Liberal Party Nomination for President, New York, New York, September 14, 1960]]
** Hitler
In this they proceeded on the sound principle that the magnitude of a lie always contains a certain factor of credibility, since the great masses of the people in the very bottom of their hearts tend to be corrupted rather than consciously and purposely evil, and that, therefore, in view of the primitive simplicity of their minds they more easily fall a victim to a big lie than to a little one, since they themselves lie in little things, but would be ashamed of lies that were too big. Such a falsehood will never enter their heads and they will not be able to believe in the possibility of such monstrous effrontery and infamous misrepresentation in others; yes, even when enlightened on the subject, they will long doubt and waver, and continue to accept at least one of these causes as true. Therefore, something of even the most insolent lie will always remain and stick – a fact which all the great lie-virtuosi and lying-clubs in this world know only too well and also make the most treacherous use of.
- Mein Kampf
** Dietrich Bonhoeffer
Silence in the face of evil is evil itself.
God will not hold us guiltless.
Not to Speak is to Speak.
Not to Act is to Act.
** K. Gibran
They deem me mad because I will not sell my days for gold and I deem them mad because they think my days have a price.
** Dr Seuss
A Person is a person no matter how small.
** Lucy Parsons
Never be decieved that the rich will allow you to vote away their wealth.
** Kofi Annan
We need to regulate drugs because they are risky.
Drugs are infinitely more dangerous when produced and sold by criminals who do not worry about any safety measures.
Legal regulation protects health.
** Max Weinreich
A Language is a dialect with an army and a navy.

** James Tiptree Jr
Being, I imagine, must be very simple.
It is Becoming which is so messy and which I am all for.
** Matthew Schultz
“You’re allowed to believe in a god. You’re allowed to believe unicorns live in your shoes for all I care. But the day you start telling me how to wear my shoes so I don’t upset the unicorns, I have a problem with you. The day you start involving the unicorns in making decisions for this country, I have a BIG problem with you.”
** Dran
We didn't set anything up knowing that at any point with no warning NPCs would materialize and blow everything up.
NPCs don't sleep, they don't get tired, they don't have to wake people up or take off work to show up for a timer.
- [[https://www.pcgamer.com/uk/eve-online-is-in-chaos-after-an-unprecedented-alien-invasion/][Eve online alien invasion]]
** Queen Kristina
There are men who are as much women as their mothers, and women who are as much men as their fathers, for
the soul has no gender.
- 1641.
** George Orwell
But if thought corrupts langugage, language can also corrupt thought.
"... putting them together again in new shapes of your own choosing."

"Until they become conscious they will never rebel,
and until after they have rebelled they cannot become conscious."
- 1984

** MC Hammer
"When you measure, include the measurer."
** Bessel van der Kolk
Beneath the surface of the protective parts of trauma survivors there exists an
undamaged essence, a self that is confident, curious, and calm, a self that has
been sheltered from destruction by the various protectors that have emerged in their efforts to ensure survival.
Once those protectors trust that it is safe to separate, the self will spontaneously emerge,
and the parts can be enlisted in the healing process.
** Tony Benn
The way a government treats refugees is very instructive because it shows you how they would treat
the rest of us if they thought they could get away with it.


I expect that the House has heard of the little document, which is circulating, about the boat race between the NHS and a Japanese crew. Both sides tried hard to do well, but the Japanese won by a mile. The NHS was very discouraged and set up a consultancy. The consultancy came to the conclusion that the Japanese had eight people rowing and one steering, whereas the NHS had eight people steering and one rowing. The NHS appointed people to look at the problem and decided to reorganise the structure of the team so that there were three steering managers, three assistant steering managers and a director of steering services, and an incentive was offered to the rower to row harder. When the NHS lost a second race, it laid off the rower for poor performance and sold the boat. It gave the money it got from selling the boat to provide higher than average pay awards for the director of steering services.
- [[https://publications.parliament.uk/pa/cm199596/cmhansrd/vo951122/debtext/51122-36.htm][Hansard Archive]]
** John Green
Let me explain why I like to pay taxes for schools even though I don't personally have a kid
in school:
I don't like living in a country with a bunch of stupid people.
** Maurice Merleau-Ponty
Each one of us knows for his own part that the world as it is, is unacceptable.
** Fred Rogers
Love isn't a state of perfect caring. It is an active noun like struggle.
To love someone is to strive to accept that person exactly the way he or she is, right here and now.

** Andrew Bolt
Why do elderly Australian men keep getting jail for raping young boys?
In this day and age it's as if no one dares disbelieve anyone claiming to be a victim, for fear they
may be accused of being cruel.
- Herald Sun, Feb 7, 2021.
** Zora Neale Hurston
If you are silent about your pain, they'll kill you and say you enjoyed it.

** The Onion
"What part of 'stand back and stand by' did these idiots not understand?"
** Anthony Bourdain
“Once you’ve been to Cambodia, you’ll never stop wanting to beat Henry Kissinger to death with your bare hands. You will never again be able to open a newspaper and read about that treacherous, prevaricating, murderous scumbag sitting down for a nice chat with Charlie Rose or attending some black-tie affair for a new glossy magazine without choking. Witness what Henry did in Cambodia – the fruits of his genius for statesmanship – and you will never understand why he’s not sitting in the dock at The Hague next to Milošević.”
- The Cook's Tour: Global Adventures in Extreme Cuisines


“If I'm an advocate for anything, it's to move. As far as you can, as much as you can. Across the ocean, or simply across the river. The extent to which you can walk in someone else's shoes or at least eat their food, it's a plus for everybody.

Open your mind, get up off the couch, move.”
** Marshall McLuhan
New technological environments are commonly cast in the molds of the preceiding technology out of the sheer
unawareness of their designers.
** Fred Hampton
I'm not going to die on no airplane.
I'm not going to die slipping on no ice.
I'm going to die for the people because
I'm going to live for the people.
I'm going to live for the people
because I love the people.
** Joe Wintergreen
Randomly started thinking about AI and started making a system where like, each type of action
(take cover/flank/shoot target/throw grenade/wander/move to target) is kept in an object with a
CanExecute function (which returns wheter i'ts a good idea to do that thing right now or not)
and then on tick the ai goes through a list of actions and executes the first one that CanExecute.
So theoretically you can have like, a Combat row on a data table that has a list of objects with the thing you
really want the AI to do at the top and fallbacks under that like this.
** Salvador Dali
It is not necessary for the public to know whether I am joking or whether I am serious,
just as it is not necessary for me to know it myself.

I am not strange. I am just not normal.

The Sole difference between myself and a madman is the fact that I am not mad!

I don't do drugs. I am drugs.
** Egon Bittner
"In recent years a good deal of the very best sociological work has been devoted to the study of organization. Although the term, organization, belongs to the category of expressions about which there is maintained an air of informed vagueness, certain special conventions exist that focus its use, with qualifications, on a delimited set of phenomena. In accordance with these conventions, the term applies correctly to stable associations of persons engaged in concerted activities directed to the attainment of specific objectives. It is thought to be a decisive characteristic of such organizations that they are deliberately instituted relative to these objectives. Because organizations, in this sense, are implementing and implemented programs of action that involve a substantial dose of comprehensive and rational planning, they are identified as instances of formal or rational organization in order to differentiate them from other forms."
- The Concept of Organization

** Michael Rosen
 "The data have landed.
First they said they needed data about the childrern to find out what they're learning.

Then they said they needed data about the children to make sure they are learning.

Then the children only learnt what could be turned into data.

Then the Children became data".
** Kwame Ture
 "The job of a revolutionary is, of course, to overthorw unjust systems and replace them with just systems
because a revolutionary understands this can only be done by the masses of the people."

"In order for non-violence to work, your opponent must have a conscience.
The United states has none, has none."

“If a white man wants to lynch me, that's his problem. If he's got the power to lynch me, that's my problem. Racism is not a question of attitude; it's a question of power. Racism gets its power from capitalism. Thus, if you're anti-racist, whether you know it or not, you must be anti-capitalist. The power for racism, the power for sexism, comes from capitalism, not an attitude.”


“This country is a nation of thieves. It stole everything it has, beginning with black people. The U.S. cannot justify its existence as the policeman of the world any longer. I do not want to be a part of the American pie. The American pie means raping South Africa, beating Vietnam, beating South America, raping the Philippines, raping every country you’ve been in. I don’t want any of your blood money. I don’t want to be part of that system. We must question whether or not we want this country to continue being the wealthiest country in the world at the price of raping everybody else.”

** Henry David Thoreau
"Disobedience is the true foundation of liberty. The obedient must be slaves"
** Ira Glass
 “Nobody tells this to people who are beginners, I wish someone told me. All of us who do creative work, we get into it because we have good taste. But there is this gap. For the first couple years you make stuff, it’s just not that good. It’s trying to be good, it has potential, but it’s not. But your taste, the thing that got you into the game, is still killer. And your taste is why your work disappoints you. A lot of people never get past this phase, they quit. Most people I know who do interesting, creative work went through years of this. We know our work doesn’t have this special thing that we want it to have. We all go through this. And if you are just starting out or you are still in this phase, you gotta know its normal and the most important thing you can do is do a lot of work. Put yourself on a deadline so that every week you will finish one story. It is only by going through a volume of work that you will close that gap, and your work will be as good as your ambitions. And I took longer to figure out how to do this than anyone I’ve ever met. It’s gonna take awhile. It’s normal to take awhile. You’ve just gotta fight your way through.”
** Anthony Robbins
"Who have you decided to become? Make this decision consciously. Make it carefully. Make it powerfully"
- Outstanding People of the World
** Charles Dickens
 "No one is useless in this world who lightens the burden of another"
** David Sedaris
"To put them in perspective, I think of being on an airplane.
The flight attendant comes down the aisle with her food cart and,
eventually, parks it beside my seat.
'Can I interest you in the chicken?' She Asks. 'Or would you prefer the
platter of shit with bits of broken glass in it?'

To be undecided in this election is to pause for a moment and then ask how the chicken is cooked."
** Terry Pratchett
“The reason that the rich were so rich, Vimes reasoned, was because they managed to spend less money.

Take boots, for example. He earned thirty-eight dollars a month plus allowances. A really good pair of leather boots cost fifty dollars. But an affordable pair of boots, which were sort of OK for a season or two and then leaked like hell when the cardboard gave out, cost about ten dollars. Those were the kind of boots Vimes always bought, and wore until the soles were so thin that he could tell where he was in Ankh-Morpork on a foggy night by the feel of the cobbles.

But the thing was that good boots lasted for years and years. A man who could afford fifty dollars had a pair of boots that'd still be keeping his feet dry in ten years' time, while the poor man who could only afford cheap boots would have spent a hundred dollars on boots in the same time and would still have wet feet.

This was the Captain Samuel Vimes 'Boots' theory of socioeconomic unfairness.”
- Men at Arms.

 “You'd like Freedom, Truth, and Justice, wouldn't you, Comrade Sergeant?' said Reg encouragingly.
'I'd like a hard-boiled egg,' said Vimes, shaking the match out.
There was some nervous laughter, but Reg looked offended.
'In the circumstances, Sergeant, I think we should set our sights a little higher--'
'Well, yes, we could,' said Vimes, coming down the steps. He glanced at the sheets of papers in front of Reg. The man cared. He really did. And he was serious. He really was. 'But...well, Reg, tomorrow the sun will come up again, and I'm pretty sure that whatever happens we won't have found Freedom, and there won't be a whole lot of Justice, and I'm damn sure we won't have found Truth. But it's just possible that I might get a hard-boiled egg.”
― Night Watch

 "It's not as simple as that. IT's not a black and white issue. There are so many shades of grey.'
'Nope'.
'Pardon?'
'There's no greys, only white that's got grubby. I'm surprised you don't know that. And sin, young man,
is when you treat people as things. Including yourself. That's what sin is.'
'It's a lot more complicated than that-'
'No. It ain't. When people say things are more complicated than that,
they means they're getting worried that they won't like the truth.
People as things, that's where it starts.'
'Oh, I'm sure there are worse crimes-'
'But they starts with thinking about people as things...'"
 - Carpe Jugulum.
** @alliebland
"Then Google Maps was like, 'turn right on Malcolm Ten Boulevard' and I knew there were no
black engineers working there".
** Carl Sagan
"We've arranged a global civilization in which most crucial elements profoundly depend on science and technology.
We have also arranged things so that almost no one understands science and technology.
This is a prescription for disaster. We might get away with it for a while, but sooner or later this
combustible mixture of ignorance and power is going to blow up in our faces."
** Tommy Douglas
 "Once more, let me remind you what fascism is. I need not wear a brown shirt or a green shirt.
Fascism begins the moment a ruling class, fearing the people may use their political democracy to gain
economic democracy, begins to destroy political democracy in order to retains its power of exploitation
and special privilege."
** Iain Banks
"I'm not arguing there are no decent people in the Tory Party, but they're like bits of sweetcorn in a turd;
technically they've kept their integrity, but they're still embedded in shit."
** Lesley Lokko
"My decision to leave Spitzer after less than a year is fairly straightforward: I was not able to build enough support to be able to deliver on either my promise of change, or my vision of it. The reasons why are more complex. Part of it has to do with COVID-19 and the rapid lockdown, which occurred after only three months in post. It's hard enough to build social capital in a new place without having to do it over Zoom. Part of it too has to do with the wider inflexibility of U.S. academic structures. In an incredibly bureaucratic and highly-regulated context, change is as much administrative as it is conceptual. The lack of meaningful support—not lip service, of which there's always a surfeit—meant my workload was absolutely crippling. No job is worth one's life and at times I genuinely feared for my own. Race is never far from the surface of any situation in the U.S. Having come directly from South Africa, I wasn't prepared for the way it manifests in the U.S. and quite simply, I lacked the tools to both process and deflect it. The lack of respect and empathy for Black people, especially Black women, caught me off guard, although it's by no means unique to Spitzer. I suppose I'd say in the end that my resignation was a profound act of self-preservation."
** Sankara
"Sankara: Yes. You cannot carry out fundamental change without a certain amount of madness.
In this case, it comes from noncomformity, the courage to turn your back on the old formulas,
the courage to invent the future. Besides, it took the madmen of yesterday for us to be able to act with
extreme clarity today. I want to be one of those madmen.
Rapp: To Invent the future?
Sankara: Yes. We must dare to invent the future."
** Bertrand Russell
"Everything is vague to a degree you do not realize till you have tried to make it precise."
** Clement Attlee
"Charity is a cold grey loveless thing.
If a rich man wants to help the poor, he should pay his taxes gladly, not dole out money at a whim."
** Talia Lavin
Vanity Fair: Do you worry about the reaction to your book?
Lavin: You mean am I worried I'm going to be murdered?
VF: Yes.
Lavin: I think anyone who engages with the far right journalistically or as an activist worries
about being murdered. But I worked on an operating principle of not letting these people steal my
right to speak out of fear, and that's how I'm continuing to operate. On the balance of things
I'd prefer not to be murdered, but if I have to go somehow, I guess standing up against Nazis in
2020 America isn't the worst reason.
** Ally Henny
It's funny how nooooobody talks about "Irish Slaves" until Black people start protesting for their
freedom. Then fragile people of whiteness resume their social media campaign of conflating
indentured servitude with slavery.

People will try to shout down Black folks' oppression by claiming that there were white folks who were
also oppressed, as if that somehow justifies oppression of any sort. I need y'all to get a
better narrative.

If you want to have a discussion about the injustices perpetuated against Irish immigrants, have at it.
But don't use it as a way to diminish the oppression of Black people that has spanned over 400 years
and covers five centuries of history.
** Tony Morrison
"And fantasy it was, for we were not strong, only aggressive;
we were not free, merely licensed;
we were not compassionate, we were polite;
not good, but well behaved.
We courted death in order to call ourselves brave, and hid like thieves from life.
We substituted good grammar for intellect; we switched habits to simulate maturity;
we arranged lies and called it truth, seeing in the new pattern of an old idea the Revelation
and the Word."
- The Bluest Eye

“The function, the very serious function of racism is distraction. It keeps you from doing your work. It keeps you explaining, over and over again, your reason for being. Somebody says you have no language and you spend twenty years proving that you do. Somebody says your head isn’t shaped properly so you have scientists working on the fact that it is. Somebody says you have no art, so you dredge that up. Somebody says you have no kingdoms, so you dredge that up. None of this is necessary. There will always be one more thing.”
** Frantz Fanon
“Sometimes people hold a core belief that is very strong. When they are
presented with evidence that works against that belief, the new
evidence cannot be accepted. It would create a feeling that is
extremely uncomfortable, called cognitive dissonance. And because it
is so important to protect the core belief, they will rationalize,
ignore and even deny anything that doesn't fit in with the core belief.”
- Black Skin, White Masks.
** Maurice Mitchell
"When you hear moderate Democrats pin their losses on 'defund' or the movement for Black lives...
it shows how little they care about police violence actually and how little they care about
Black death."
** Count Dooku
"It is an honor to stand before you, for you represent the freedom and the future of our galaxy. The once-great Republic and Jedi Order have become victims of their own ambitions, and the Supreme Chancellor is no more than a pawn of corporate monopolies. As a people you called out for change, you called out for leadership, and I humbly answered that call. Together we challenged the system. We asked for equality. And how were we met? With war! The Jedi secret army of clones was revealed, and their treachery was far greater than we could have imagined! Countless living beings—these clones the Jedi created—have been sent to their deaths, while we sacrifice mainly droids. Our soldiers of flesh and blood are willing participants! They are your fathers and sons, mothers and daughters, who fight not because they were grown and designed to do so, but because they know in their hearts that they are fighting for a just and noble cause!"
** Hannah Arendt
"You ask about the effect my work has on others.
If I may speak ironicaly, that's a masculine question.
Men always want to be influential.
Do I see myself as influential?
No, I want to understand."

"The ideal subject of totalitarian rule is not the convinced Nazi or the dedicated communist,
but people for whom the distinction between fact and fiction, true and false, no longer exists."

 “The trouble with Eichmann was precisely that so many were like him, and that the many were neither perverted nor sadistic, that they were, and still are, terribly and terrifyingly normal. From the viewpoint of our legal institutions and of our moral standards of judgment, this normality was much more terrifying than all the atrocities put together.”
** Eric Lafforgue
In the Mahalah Flower Men Market, an old man wears traditional shoes made of palm leaves.
Things started to change with their construction of a cable car track in the 1990's that allowed access
to the remote villages of the Flower Men. But traditions remain strong with the elders.
** Neil Gaiman
It is a fool's prerogative to utter truths no one else will speak.
** Charles Eliot
What is the plural of rhinoceros? Well, Liddell and Scott seem to authorize "rhinocerotes", which is
pedantic, but "rhinoceroses" is not euphonious.
- The East Africa Protectorate. 1905
** Glinner
If your civil rights movement opposes data and peer reviewed science, it's not a civil rights movement,
it's a cult.

** Martin Luther King
"Power without love is reckless and abusive, and love without power is sentimental and anemic.
Power at its best is love implementing the demands of justice, and justice at its best is
power correcting everything that stands against love."

The time is always right to do what is right.
** Lee Atwater
Atwater: Y'all don't quote me on this. You start out in 1954 by saying, "Nigger, nigger, nigger". By 1968 you can't say "nigger"—that hurts you. Backfires. So you say stuff like forced busing, states' rights and all that stuff. You're getting so abstract now [that] you're talking about cutting taxes, and all these things you're talking about are totally economic things and a byproduct of them is [that] blacks get hurt worse than whites. And subconsciously maybe that is part of it. I'm not saying that. But I'm saying that if it is getting that abstract, and that coded, that we are doing away with the racial problem one way or the other. You follow me—because obviously sitting around saying, "We want to cut this", is much more abstract than even the busing thing, and a hell of a lot more abstract than "Nigger, nigger". So, any way you look at it, race is coming on the back-burner.
- [[https://www.thenation.com/article/archive/exclusive-lee-atwaters-infamous-1981-interview-southern-strategy/][Southern Strategy interview]]

** Nancy Fraser
"The free-rider worry, incidentally, is typically defined androcentrically as a worry
about shirking paid employment.
Little attention is paid, in contrast, to a far more widespread problem, namely,
men's free riding on women's unpaid domestic labour."
** Bruno Latour
 'To exist is to differ; difference, in one sense, is the substantial side of things, what they have most in common and what makes them most different. One has to start from this difference and to abstain from trying to explain it, especially by starting with identity, as so many persons wrongly do. Because identity is a minimum and, hence, a type of difference, and a very rare type at that, in the same way as rest is a type of movement and the circle a type of ellipse. To begin with some primordial identity implies at the origin a prodigiously unlikely singularity, or else the obscure mystery of one simple being then dividing for no special reason.' (idem p. 73).
** Amine Mechaal
"He's Ibn Sina, not Avicenna.
He's Ibn Rushd, not Averroes.
He's Jabir Ibn Hayyan, not Geber.

Stop Latinizing the names of Muslim scholars to conceal the fact that they were Muslims.
You don't see us calling Shakespeares 'Sheikh Zubayr'".
** Kumail Nanjiani
He's just so stupid.

He's so breathtakingly stupid that the above statement is all it takes for every person reading this
to know exactly who I'm talking about.
** Coco Chanel
The most couragous act is still to think for yourself, aloud.
** John Brown
I believe to have interfered as I have done... on behalf of His despised poor, was not wrong,
but right. Now, if it be deemed necesssary that I should forfeit my life for the
furtherance of the ends of justice, and mingle my blood further with the blood of my children,
and with the blood of millions in this slave country whose rights are disregarded by wicked, cruel and unjust
enactments, I submit: so leet it be done.
** Frederick Douglass
“I assert most unhesitatingly, that the religion of the south is a mere covering for the most horrid crimes, - a justifier of the most appalling barbarity, - a sanctifier of the most hateful frauds, - and a dark shelter under, which the darkest, foulest, grossest, and most infernal deeds of the slaveholders find the strongest protection. Were I to be again reduced to the chains of slavery, next to enslavement, I should regard being the slave of a religious master the greatest calamity that could befall me. For of all slaveholders with whom I have ever met, religious slaveholders are the worst. I have ever found them the meanest and basest, the most cruel and cowardly, of all others.”

 “I love the pure, peaceable, and impartial Christianity of Christ; I therefore hatethe corrupt, slaveholding, women-whipping, cradle-plundering, partial, and hypocritical Christianity of this land. Indeed, I can see no reason, but the most deceitful one, for calling the religion of this land Christianity. I look upon it as the climax of all misnomers, the boldest of all frauds, and the grossest of all libels.”
** James Henry Hammond
In all social systems there must be a class to do the menial duties, to perform the drudgery of life. That is, a class requiring but a low order of intellect and but little skill. Its requisites are vigor, docility, fidelity. Such a class you must have, or you would not have that other class which leads progress, civilization, and refinement. It constitutes the very mud-sill of society and of political government; and you might as well attempt to build a house in the air, as to build either the one or the other, except on this mud-sill. Fortunately for the South, she found a race adapted to that purpose to her hand. A race inferior to her own, but eminently qualified in temper, in vigor, in docility, in capacity to stand the climate, to answer all her purposes. We use them for our purpose, and call them slaves. We found them slaves by the common "consent of mankind," which, according to Cicero, "lex naturae est." The highest proof of what is Nature's law. We are old-fashioned at the South yet; slave is a word discarded now by "ears polite;" I will not characterize that class at the North by that term; but you have it; it is there; it is everywhere; it is eternal.

The Senator from New York said yesterday that the whole world had abolished slavery. Aye, the name, but not the thing; all the powers of the earth cannot abolish that. God only can do it when he repeals the fiat, "the poor ye always have with you;" for the man who lives by daily labor, and scarcely lives at that, and who has to put out his labor in the market, and take the best he can get for it; in short, your whole hireling class of manual laborers and "operatives," as you call them, are essentially slaves. The difference between us is, that our slaves are hired for life and well compensated; there is no starvation, no begging, no want of employment among our people, and not too much employment either. Yours are hired by the day, not cared for, and scantily compensated, which may be proved in the most painful manner, at any hour in any street in any of your large towns. Why, you meet more beggars in one day, in any single street of the city of New York, than you would meet in a lifetime in the whole South. We do not think that whites should be slaves either by law or necessity. Our slaves are black, of another and inferior race. The status in which we have placed them is an elevation. They are elevated from the condition in which God first created them, by being made our slaves. None of that race on the whole face of the globe can be compared with the slaves of the South. They are happy, content, unaspiring, and utterly incapable, from intellectual weakness, ever to give us any trouble by their aspirations. Yours are white, of your own race; you are brothers of one blood. They are your equals in natural endowment of intellect, and they feel galled by their degradation. Our slaves do not vote. We give them no political power. Yours do vote, and, being the majority, they are the depositories of all your political power. If they knew the tremendous secret, that the ballot-box is stronger than "an army with banners," and could combine, where would you be? Your society would be reconstructed, your government overthrown, your property divided, not as they have mistakenly attempted to initiate such proceedings by meeting in parks, with arms in their hands, but by the quiet process of the ballot-box. You have been making war upon us to our very hearthstones. How would you like for us to send lecturers and agitators North, to teach these people this, to aid in combining, and to lead them?
- Speech to the US Senate, March 4, 1858.
** Abraham Lincoln
But another class of reasoners hold the opinion that there is no such relation between capital and labor, as assumed; and that there is no such thing as a freeman being fatally fixed for life, in the condition of a hired laborer, that both these assumptions are false, and all inferences from them groundless. They hold that labor is prior to, and independent of, capital; that, in fact, capital is the fruit of labor, and could never have existed if labor had not first existed -- that labor can exist without capital, but that capital could never have existed without labor. Hence they hold that labor is the superior -- greatly the superior -- of capital.

The prudent, penniless beginner in the world, labors for wages awhile, saves a surplus with which to buy tools or land, for himself; then labors on his own account another while, and at length hires another new beginner to help him. This, say its advocates, is free labor -- the just and generous, and prosperous system, which opens the way for all -- gives hope to all, and energy, and progress, and improvement of condition to all. If any continue through life in the condition of the hired laborer, it is not the fault of the system, but because of either a dependent nature which prefers it, or improvidence, folly, or singular misfortune. I have said this much about the elements of labor generally, as introductory to the consideration of a new phase which that element is in process of assuming. The old general rule was that educated people did not perform manual labor. They managed to eat their bread, leaving the toil of producing it to the uneducated. This was not an insupportable evil to the working bees, so long as the class of drones remained very small. But now, especially in these free States, nearly all are educated -- quite too nearly all, to leave the labor of the uneducated, in any wise adequate to the support of the whole. It follows from this that henceforth educated people must labor. Otherwise, education itself would become a positive and intolerable evil. No country can sustain, in idleness, more than a small per centage of its numbers. The great majority must labor at something productive. From these premises the problem springs, "How can labor and education be the most satisfactory combined?"
- [[http://www.abrahamlincolnonline.org/lincoln/speeches/fair.htm][Address before the Wisconsin State Agricultural Society Milwaukee, Wisconsin September 30, 1859]]
** Elon Musk
Marx was a capitalist. He even wrote a book about it.
** Anne Herb
Libraries will get you through times of no money better than money will get you through times of no libraries.
** Roland Freisler
This jurisprudence would suit us perfectly, with a single exception.
Over there they have in mind, practically speaking, only coloreds and half-coloreds, which includes
mestizos and mulattoes; but the jews, who are also of interest to us, are not reckoned among the coloreds.
- Nazi judge talking about the USA.
** Gore Vidal
There is only one party in the United States, the Property Party ... and it has two right wings: Republican and Democrat. Republicans are a bit stupider, more rigid, more doctrinaire in their laissez-faire capitalism than the Democrats, who are cuter, prettier, a bit more corrupt – until recently ... and more willing than the Republicans to make small adjustments when the poor, the black, the anti-imperialists get out of hand. But, essentially, there is no difference between the two parties.
- [[https://archive.org/details/mattersoffactoff00vida/page/265][Archive.org Matters of Fact and Fiction]]
** Roy Moore
These women have had 30 years to come forward, and the one and only reason they're speaking out now is because they
suddenly have less fear that their lives will be utterly destroyed.
** Randall Terry
"Our goal must be simple. We must have a Christian nation built on God's law, on the ten Commandments. No apologies."

"I don't think Christians should use birth control. You consummate your marriage as often as you like and if you have babies, you have babies."

"When I, or people like me, are running the country, you'd better flee, because we will find you, we will try you, and we will execute you. I mean every word of it. I will make it part of my mission to see to it that they are tried and executed... If we're going to have true reformation in America, it is because men once again, if I may use a worn out expression, have righteous testoserone flowing through their veins. They are not afraid of contempt for their contemporaries. They are not even here to get along. They are here to take over... Somebody like Susan Smith should be dead. She should be dead now. Some people will go, "Well how do you know God doesn't have a wonderful plan for her life?" He does, it's listed in the Bible. His plan for her is that she should be dead."

I want you to just let a wave of intolerance wash over you. I want you to let a wave of hatred wash over you. Yes, hate is good. … Our goal is a Christian nation. We have a Biblical duty, we are called by God, to conquer this country. We don't want equal time. We don't want pluralism.
** Barry Goldwater
“Mark my word, if and when these preachers get control of the [Republican] party, and they're sure trying to do so, it's going to be a terrible damn problem. Frankly, these people frighten me. Politics and governing demand compromise. But these Christians believe they are acting in the name of God, so they can't and won't compromise. I know, I've tried to deal with them.”

** C.S. Lewis
If we let ourselves, we shall always be waiting for some distraction or other to end before we can really get down to our work. The only people who achieve much are those who want knowledge so badly that they seek it while the conditions are still unfavorable. Favorable conditions never come.”
- Learning in War-Time.
** Alexander Stephens
Our new government is founded... upon the great turth that the negro is not equal to the white man;
that slavery subordination to the superior race is his natural and normal condition.
This, our new government, is the first, in the history of the world, based upon this great physical,
philosophical, and moral truth.
- Cornerstone speech, March 21, 1861.
** Fleur Adcock
There are worse things than having behaved foolishly in public.
There are worse things than these miniature betrayals, committed or endured or suspected;
there are worse things than not being able to sleep for thinking about them.
It is 5am. All the worse things come staking in and stand icily about the bed looking worse and
worse and worse.
** Ronald Reagan (Humourous)
The second amendment doesn't exist for hunting. It exists so undocumented immgrants can shoot ICE agents in self defense.
** Ronald Reagan
She has 80 names, 30 addresses, 12 social security cards and is collecting veteran's benefits on four non-existing deceased husbands. And she is collecting social security on her cards. She's got medicaid, getting food stamps, and she is collecting welfare under each of her names.
- 1976 on the 'welfare queen'.
** Mueller Report
"... the evidence doees indicate that a thorough FBI investigation would uncover facts about the campaign and
the president personallty that the president could have understood to be crimes or that would give rise to
personal and political concerns."
- Vol 2, page 76.
** Rosie Cappuccino
She should not apologise for the trauma that formed her.
** Malcolm X
."We, the Black masses, don't want these leaders who seek our support coming to us representing a certain political party. They must come to us today as Black Leaders representing the welfare of Black people. We won't follow any leader today who comes on the basis of political party. Both parties (Democrat and Republican) are controlled by the same people who have abused our rights, and who have deceived us with false promises every time an election rolls around."
- [[https://malcolm-x.org/quotes.htm][Malcolm X Quotes]]
** Richard Buckminster Fuller
“We should do away with the absolutely specious notion that everybody has to earn a living. It is a fact today that one in ten thousand of us can make a technological breakthrough capable of supporting all the rest. The youth of today are absolutely right in recognizing this nonsense of earning a living. We keep inventing jobs because of this false idea that everybody has to be employed at some kind of drudgery because, according to Malthusian Darwinian theory he must justify his right to exist. So we have inspectors of inspectors and people making instruments for inspectors to inspect inspectors. The true business of people should be to go back to school and think about whatever it was they were thinking about before somebody came along and told them they had to earn a living.”

It is now highly feasible to take care of everybody on Earth at a ‘higher standard of living than any have ever known.’ It no longer has to be you or me. Selfishness is unnecessary and henceforth unrationalizable as mandated by survival. Most importantly we have learned that from here on it is success for all or none, for it is experimentally proven by physics that “unity is plural and at minimum two” – the complementary but not mirror-imaged proton and neutron. You and I are inherently different and complimentary. Together we average as zero – that is, as eternity.

„We can now take care of everybody at a higher standard of living than anybody has ever known. It does not have to be “you or me,” so selfishness is unnecessary and war is obsolete. This has never been done before.“

** Theodore Roosevelt
Patriotism means to stand by the country. It does not mean to stand by the president.
