* Why Institutions are important for video-games                   :argument:

Institutions are important because they structure almost all life, action, and systems.

** Institutions are currently ignored in games

*** There has always been a bias to the physics in game systems.
Mario. Donkey Kong. Modern Warfare. Minecraft. Even games like Dragon age, where 
dialogue and party interactions are praised, still rely primarily on (physical) combat systems.
Even the Sims encodes a large amount of its word in physical smart objects.

This is changing, with games like Prom Week, and Versu, placing more of a focus on social interactions,
and social rules.

** Institutions provide structure to social rules
Currently, CiF collects rules into 'micro-theories', and Versu into 'social practices'. 
In the words of Josh McCoy, micro-theories are 'big bags of rules'. The complexity of institutions can surely
be described better than this.

** Institutions fill the structuring role of narrative and story in real life interactions.
** Institutional changes themselves can be the focus of narrative. 
See Red Mars, and Gormenghast.

** Phenomenological models and portrayals of Institutions are shallow and lacking
There has started to be some (Paper's Please, We Happy Few), but they are the exception.



