* Worked examples of institutions
In an attempt to specify particular institutions
** Annotation Structure
Fligstein - Roles, Field, Greater Interface, Social Skill, *IGU, Crisis, Resolution*
Searle: Brute and Institutional Facts
Marx/Bourdieu: Capitals
Grossi: Institution/Organization
Bicchieri: Descriptive/Prescriptive Norms, Sanctions

*** Roles

*** Facts

**** Brute

**** Institutional

*** Capitals

*** Field

*** IGU

*** Sanctions

**** Legitimate

**** Illegitimate

*** Interactions

*** Norms

*** Crises

*** Organizations

** Racist Police Violence
Roles: Police, Civilians

Brute Facts: Colour of Skin, Driving Speed, Car Colour, Items in Car, State of Car Maintenance, Gender
Institutional Facts: Desirable, Undesirable, Idealised, Neutral
Capitals: Economic, Social, Intellectual, Trust, Fear

Field: Police Observation -> Pull over -> Release / Escalate

IGU: Policy Makers, Unions, Civil Rights Groups

Legitimate Sanctions: Ticket, Warning, Arrest
Illegitimate Sanctions: Slurs, Insults, Beating, Shooting, Rape 

Interactions: Police->Desirable/Undesirable/Idealised/Neutral/Policy Makers
              Policy Makers -> Police

Norms: police stop group -> interact -> (NG/ID-> Behave according to protocol)
                                     -> (FG -> Behave leniently)
                                     -> (UG -> Behave extra judicially)

Crises: Publicised Illegitimate Sanctions. Trust and Fear

Organization: Police -> Hierarchical

** Street Experience
Roles: Police, Pedestrians, Assisted-Travellers (Motor/Device/Animal), Criminals, Entertainers, Shopkeepers, Children,
Families, Animals, Street Workers, Sex Workers, Town Criers, Soldiers

Brute Facts: Building Style, Street Size/Cleanliness, Business, Time
Institutional Facts: ?

Capitals: Economic, Social, Intellectual

Field: ?

IGU: Politicians, Guilds, Police

Legitimate Sanctions: 
Illegitimate Sanctions:

Interactions:

Norms:

Crises:

Organizations: 

** Albinos in Africa?

** Tribes?

** Libraries?

** Law-Making

** Eugenics

** Rituals

** Debt

** Slavery

