t_shirt                          : 2
tab                              : 1
tabasco                          : 1
table_top                        : 2
table_top_game                   : 1
table_top_rpg                    : 18
table_top_rpgs                   : 1   : table_top_rpg
tabled_abduction                 : 1
tablet                           : 1
tabletop_game                    : 1   : table_top_game
tabletop_gaming                  : 7   : table_top_game
tabletop_rpg                     : 5   : table_top_rpg
tabletopia                       : 1
taboo                            : 1
taboos                           : 2   : taboo
Tabqa                            : 1
tabu_search                      : 1
tacit_communication              : 1
taco_bell                        : 1
tacoma                           : 1
tactical_institutions            : 1
tactical_modes_of_practice       : 1
tactical_path_finding            : 1
tactical_pathfinding             : 1   : tactical_path_finding
tactical_tech                    : 1
tactics                          : 9
tactile                          : 2
tag                              : 5
tag_system                       : 1
tagging                          : 13
tagging_behaviour                : 1
taglines                         : 1
Tags                             : 1   : tag
tags                             : 9   : tag
tahrir_square                    : 1
taiwan                           : 3
tajikstan                        : 1
take_back_illinois               : 1
takedown                         : 3
tale_of_tales                    : 1
tale_spin                        : 2
talent                           : 1
tales                            : 1
taliban                          : 2
talismans                        : 1
talk                             : 5
talk_of_the_town                 : 1
talk_radio                       : 1
talking_about_bpd                : 1
talking_bodies                   : 1
talking_points_memo              : 3
talkingaboutbpd                  : 1   : talking_about_bpd
talkingpointsmemo                : 2   : talking_points_memo
talks                            : 1
talmud                           : 1
tamale                           : 1
tambourine                       : 1
tamil                            : 1
tampa                            : 1
tampa_bay                        : 1
tampa_bay_times                  : 2
tang_china                       : 1
tangential_learning              : 1
tangibl                          : 1   : tangible
tangible                         : 2
tanzania                         : 1
tap_water                        : 1
target                           : 1
target_trial_framework           : 1
targeted_advertising             : 1
targeted_interventions           : 1
targets                          : 1 : target
tariff                           : 2   : tariffs
tariffs                          : 4
tarot                            : 2
tarot_cards                      : 1   : tarot
taser                            : 2
task                             : 7
task_analysis                    : 1
task_artifact_cycle              : 1
task_assembly                    : 1
task_complexity                  : 1
task_delegation                  : 1
task_demand                      : 1
task_diversity                   : 1
task_log                         : 1
task_orientation                 : 1
task_scheduling                  : 1
taskmaker                        : 2
tasks                            : 16
tasmania                         : 2
taste                            : 2
tate                             : 1
tate_britain                     : 1
tattoo                           : 11
tattooed_prof                    : 1
tattoos                          : 11  : tattoo
taubes                           : 1
tavistock                        : 2
tax                              : 31
tax_avoidance                    : 2
tax_cut                          : 1
tax_cuts                         : 1
tax_evasion                      : 1
tax_fraud                        : 2
tax_haven                        : 2
tax_policy                       : 1
tax_reform                       : 4
tax_return                       : 1
taxation                         : 12
taxes                            : 6
taxi                             : 1
taxis                            : 1
taxonomic_neutrality             : 1
taxonomy                         : 256
taylor_and_francis               : 1
tea                              : 8
tea_party                        : 1
teacher                          : 2
teacher_of_the_year              : 1
teachers                         : 4
teachers_guide                   : 1
teaching                         : 15
team                             : 1
team_oriented_programming        : 1
team_structures                  : 1
teams                            : 7
teamwork                         : 2
teapot                           : 1
teapots                          : 1 : teapot
tear_gas                         : 4
teaspoons                        : 1
tech                             : 11
tech_adoption                    : 2
tech_bros                        : 4
tech_companies                   : 3
tech_crunch                      : 3
tech_culture                     : 1
tech_dangers                     : 1
tech_debt                        : 2
tech_dirt                        : 381
tech_ethics                      : 3
tech_failures                    : 1
tech_report                      : 1
tech_republic                    : 1
tech_review                      : 1
tech_specs                       : 1
tech_times                       : 1
tech_tree                        : 1
tech_workers                     : 1
tech_writing                     : 1
techcrunch                       : 3   : tech_crunch
techdirt                         : 381 : tech_dirt
technical                        : 206
technical_artifacts              : 1
technical_debt                   : 2
technical_function               : 1
technical_practice               : 1
technical_requirements           : 1
technical_standards              : 1
technical_writing                : 1
technicians                      : 1
techno_chauvinism                : 1
techno_culture                   : 1
techno_determinism               : 1
techno_economic                  : 1
techno_feminism                  : 1
techno_futurism                  : 1
techno_imperialism               : 1
techno_poetics                   : 1
techno_polis                     : 1
techno_social                    : 1
techno_spiritual                 : 1
techno_thriller                  : 1
technocracy                      : 1
technoculture                    : 1   : techno_culture
technodeterminism                : 1   : techno_determinism
technofeminism                   : 1   : techno_feminism
technological_change             : 1
Technological_Change             : 1   : technological_change
technological_determinism        : 1
technological_dystopias          : 1
technologies                     : 1   : technology
technology                       : 362
technology_failure               : 1
technology_garden                : 3
technology_review                : 1
technopoetics                    : 1   : techno_poetics
technopolis                      : 1   : techno_polis
technosocial                     : 1   : techno_social
techreports                      : 1   : tech_report
tedium                           : 1
teen                             : 1
teen_vogue                       : 15
teenagers                        : 3
teens                            : 2   : teenagers
teenvogue                        : 4   : teen_vogue
teespring                        : 2
teeth                            : 1
teflon                           : 1
tehran                           : 1
telco                            : 10
telecommunication                : 1
telegraph                        : 9
telemarketing                    : 1
telemetry                        : 1
teleo_reactive                   : 1
teleology                        : 3
teleoperation                    : 1
teleosemantics                   : 1
telepathy                        : 1
telephone                        : 2
telephone_box                    : 1
telephones                       : 1   : telephone
telepresence                     : 1
telescript                       : 1
Telescript                       : 1   : telescript
televiion                        : 1   : television
television                       : 1
television_narrative             : 1
telework                         : 1
telic                            : 1
telling_about_society            : 1
telltale                         : 5
temperament                      : 1
temperature                      : 4
temperature_variation            : 1
template                         : 7
template_haskell                 : 1
templates                        : 3   : template
templeOS                         : 1
temples                          : 1
tempo                            : 2
temporal                         : 29
temporal_bias                    : 1
temporal_context                 : 1
temporal_degradation             : 1
temporal_dependency              : 1
temporal_dimensions              : 1
temporal_earth                   : 1
temporal_experience              : 1
temporal_graph                   : 1
temporal_grounding               : 1
temporal_logic                   : 16
temporal_modal_defeasible_logic  : 1
temporal_order                   : 1
temporal_parochialism            : 1
temporal_sequence_learning       : 1
temporality                      : 3
temporality_model                : 1
temporary_email                  : 1
ten_daily                        : 1
tenacles                         : 1   : tentacles
tenants                          : 2
tendency                         : 1
tennessee                        : 7
tennis                           : 1
tennyson                         : 1
tenochtitlan                     : 1
tense                            : 1
tensegrity                       : 1
tension                          : 1
tensor_fields                    : 1
tensorboard                      : 1
tensorflow                       : 14
tensors                          : 1
tentacles                        : 1
tenure                           : 1
teratology                       : 1
term_limits                      : 2
term_rewriting                   : 1
terminal                         : 5
terminator                       : 2
terminology                      : 3
termites                         : 1
terms                            : 3
terms_of_service                 : 1
terracotta_army                  : 1
terraform                        : 2
terraforming                     : 1   : terraform
terrain                          : 7
terrain_generation               : 8
terrible_realities               : 1
territorial                      : 1
territoriality                   : 1   : territorial
territory                        : 1
terror                           : 1
terrorism                        : 151
terrorism_studies                : 1
terrorist_groups                 : 1
tesco                            : 2
tesla                            : 2
test                             : 17
test_bed                         : 1
test_driven_design               : 3
test_driven_development          : 1
test_driven_developmet           : 1   : test_driven_development
test_driven_writing              : 1
testability                      : 1
testimonies                      : 1   : testimony
testimony                        : 2
testing                          : 18
tests                            : 1   : test
tetris                           : 6
tex                              : 3
texas                            : 72
texas_monthly                    : 1
texas_observer                   : 1
texas_tribune                    : 1
text                             : 12
text_adventure                   : 7
text_analysis                    : 1
text_based_learning              : 1
text_blob                        : 1
text_book                        : 584
text_books                       : 17 : text_book
text_editor                      : 1
text_generation                  : 3
text_layout                      : 1
text_net                         : 1
text_processing                  : 1
text_segmentation                : 1
text_simplification              : 1
text_tiling                      : 2
textblob                         : 1   : text_blob
textbook                         : 585 : text_book
textbook_knowledge               : 1
textbooks                        : 2   : text_book
textile                          : 2
textile_workers                  : 1
textnet                          : 1   : text_net
TextTiling                       : 2   : text_tiling
texture                          : 1
texture_synthesis                : 2
textures                         : 3   : texture
thai                             : 1
thailand                         : 3
thanksgiving                     : 1
that_which_sleeps                : 2
the_advocate                     : 1
the_appeal                       : 5
the_appear                       : 1
the_atlantic                     : 86
the_bachelorette                 : 1
the_baffler                      : 8
the_balkans                      : 1
the_beatles                      : 2
the_bicker                       : 2
the_body_keeps_score             : 1
the_bulwark                      : 1
the_canary                       : 2
the_cave                         : 1
the_center                       : 1
the_color_of_wealth              : 1
the_commons                      : 1
the_conversation                 : 9
the_correspondent                : 2
the_crime_report                 : 1
the_cross_tab                    : 1
the_cruelty_is_the_point         : 1
the_culture                      : 1
the_cut                          : 4
the_dark_is_rising               : 1
the_depression                   : 1
the_dispossessed                 : 1
the_division                     : 3
the_economist                    : 1
the_end_of_ice                   : 1
the_enlightenment                : 1
the_escapist                     : 11
the_establishment                : 5
the_expanse                      : 2
the_exploding_metropolis         : 1
the_false_cause                  : 1
the_fed                          : 1
the_federalist                   : 4
the_flash                        : 1
the_fulcrum                      : 1
the_gamer                        : 1
the_good_place                   : 2
the_hill                         : 13
the_intercept                    : 19
the_interept                     : 1   : the_intercept
the_invisible_technician         : 1
the_irish_times                  : 1
the_isle_of_pines                : 1
the_kitchn                       : 28
the_know_it_alls                 : 1
the_last_of_us                   : 1
the_little_mermaid               : 1
the_machinist                    : 1
the_man_in_the_high_castle       : 1
the_mechanic                     : 1
the_mind_circle                  : 3
the_mint                         : 1
the_morning_paper                : 2
the_nation                       : 8
the_netherlands                  : 1
the_new_deal                     : 1
the_nib                          : 1
the_oatmeal                      : 1
the_office                       : 1
the_one_joke                     : 2
the_outlin                       : 1   : the_outline
the_outline                      : 3
the_phantom_menace               : 1
the_pill                         : 1
the_pope                         : 1
the_pudding                      : 1
the_queen                        : 1
the_raven                        : 1
the_register                     : 1
the_root                         : 3
the_sims                         : 11
the_slot                         : 1
the_south                        : 1
the_spectator                    : 1
the_squad                        : 2
the_standard                     : 1
the_star                         : 1
the_state                        : 16
the_stranger                     : 1
the_sunday_papers                : 54
the_tea                          : 1
the_tiffany_problem              : 1
the_time_of_troubles             : 1
the_times                        : 5
the_trace                        : 1
the_trove                        : 1
the_two_cosmic_eras              : 1
the_verge                        : 3
the_watch                        : 4
the_week                         : 1
the_whole_story                  : 1
the_wire                         : 2
the_witcher                      : 1
the_witness                      : 1
theano                           : 2
theater                          : 2   : theatre
theatlantic                      : 10  : the_atlantic
theatre                          : 4
theatre_memory                   : 1
theft                            : 11
theft_capitalism                 : 1
theism                           : 1
them                             : 3
them_us                          : 1
thematic_analysis                : 2
theme_hospital                   : 1
themes                           : 1
themindcircle                    : 1   : the_mind_circle
theologians                      : 1   : theology
theology                         : 2
theorem                          : 1
theorem_proving                  : 4
theoretical_coding               : 1
theoretical_frameworks           : 1
theoretical_politics             : 1
theoretical_psychology           : 1
theory                           : 70
theory_as_code                   : 1
theory_building                  : 2
theory_change                    : 1
theory_crafting                  : 1
theory_development               : 1
theory_fiction                   : 2
theory_for_the_world             : 1
theory_of_action                 : 1
theory_of_mind                   : 4
theory_of_planned_behaviour      : 1
theory_of_practice               : 1
theory_of_surplus_value          : 1
theory_of_the_growth_of_the_firm : 1
theory_revision                  : 4
therapist                        : 1
therapy                          : 13
there_and_back_again             : 1
theremin                         : 1
thermal                          : 1
thermodynamics                   : 1
thesis                           : 7
thick                            : 2
thick_description                : 1
thicker_than_blood               : 1
thief                            : 6
thing_of_value                   : 1
think_progress                   : 7
think_tank                       : 1
think_tanks                      : 1 : think_tank
thinking                         : 8
thinking_history                 : 1
thinking_styles                  : 3
thinkinghistory                  : 1   : thinking_history
thinkprogress                    : 1   : think_progress
thinktank                        : 1   : think_tank
thinktsalagi                     : 1
third_party                      : 1
third_safe_schools               : 1
third_shift                      : 1
third_way                        : 1
third_world                      : 1
this_ugly_civilization           : 1
thomas_the_tank_engine           : 2
thornton                         : 1
thought                          : 2
thought_crime                    : 1
thought_experiment               : 5
thought_experiments              : 1   : thought_experiment
thread                           : 6
thread_compilers                 : 1
threadapalooza                   : 2
threads                          : 1
threat_assessment                : 1
threat_model                     : 1
threats                          : 2
three_body_problem               : 1
three_californias                : 1
three_fifths_compromise          : 1
three_js                         : 1
three_mile_island                : 1
three_strikes                    : 6
threejs                          : 1   : three_js
threnoscope                      : 1
Threnoscope                      : 1   : threnoscope
thresholds                       : 1
thrift                           : 3
throne_room                      : 1
throttling                       : 1
thud                             : 1
thug_life                        : 1
thunderbirds                     : 2
thundercluck                     : 2
tianamen_square                  : 1 : tiananmen_square
tiananmen_square                 : 1
tiberian_sun                     : 1
tibet                            : 3
tic_tac_toe                      : 1
ticks                            : 1
tidal                            : 8
tidy_models                      : 1
tidymodels                       : 1   : tidy_models
tie_strength                     : 1
tiered                           : 1
tiffin                           : 1
tiger_woods                      : 1
tihama                           : 1
tijuana                          : 1
tiktok                           : 3
tile_algebra                     : 1
tile_model                       : 1
tiled                            : 1
tilemancer                       : 1
tiles                            : 6
tileset                          : 2
tiling                           : 1
tim                              : 1   : time
timbre                           : 1
time                             : 98
time_awareness                   : 1
time_blind                       : 1
time_keeping                     : 1
time_lapse                       : 1
time_management                  : 1
time_poverty                     : 1
time_scale                       : 1
time_scale_of_emotions           : 1
time_shift                       : 1
time_space_cube                  : 1
time_stamps                      : 1
time_stream                      : 1
time_tax                         : 1
time_travel                      : 1
time_use                         : 1
time_warner                      : 2
timed_automata                   : 1
timed_component_connectors       : 1
timekeeping                      : 1   : time_keeping
timelapse                        : 1   : time_lapse
timeline                         : 23
timelines                        : 1   : timeline
times                            : 1   : time
timescale                        : 1   : time_scale
timescale_of_emotions            : 1   : time_scale_of_emotions
timestream                       : 1   : time_stream
timing                           : 6   : time
tin                              : 1
tinkering                        : 1
tinkerpop                        : 1
tiny_bird_games                  : 1
tiny_islands                     : 2
tinybirdgames                    : 1   : tiny_bird_games
tipping                          : 5
tipping_points                   : 1
tips                             : 3   : tipping
tiredness                        : 1
tisk                             : 1
tissue_damage                    : 1
titanfall                        : 1
titans                           : 1
titles                           : 1
tkinter                          : 1
tlaxcala                         : 1
tlingit                          : 1
to_delete                        : 2
to_fix                           : 43
toasties                         : 1
tobacco                          : 2
todo_list                        : 1
togo                             : 1
toilet                           : 2   : toilets
toilet_paper                     : 1
toilet_scapes                    : 1
toilets                          : 18
toiletscapes                     : 1   : toilet_scapes
token_economy                    : 1
tokens                           : 2
tokio                            : 2   : tokyo
tokyo                            : 6
tolerance                        : 6
tomasp                           : 1
tomb                             : 1
tomb_raider                      : 3
tomorrow_corporation             : 1
tone_policing                    : 1
tool                             : 19
tool_assisted_creativity         : 1
tool_development                 : 2
tool_logic                       : 1
toolbox                          : 2
toolbox_documents                : 1
toolkit                          : 3
toolkits                         : 1   : toolkit
tools                            : 86
tools_for_thought                : 1
toolz                            : 1
top_surgery                      : 1
topic_modeling                   : 1
topic_models                     : 1
topic_sentences                  : 3
topical_hidden_markov_model      : 1
topography                       : 2
topology                         : 18
tor                              : 14
tor_books                        : 1
torah                            : 1
torbay                           : 1
torch                            : 1
torchlight                       : 1
tories                           : 2
tornillo                         : 1
toronto                          : 5
toronto_press                    : 1
torque                           : 1
torrent                          : 3
tort                             : 1
torture                          : 14
tory                             : 12
torys                            : 1   : tory
tosa_school                      : 1
total_bureaucracy                : 1
total_institution                : 1
total_order                      : 1
total_war                        : 1
totalitarian                     : 1
totalitarianism                  : 3
tottenham                        : 1
toucan                           : 1
tourism                          : 3
tourmaline                       : 1
tournament                       : 1
tournaments                      : 2
tow_center                       : 1
towel                            : 1
tower_defense                    : 1
towers                           : 1
town                             : 1
town_life                        : 1
townhall                         : 2
towns                            : 3
townville                        : 1
toxic                            : 2
toxic_culture                    : 2
toxic_dust                       : 1
toxic_masculinity                : 5
toxic_meals                      : 1
toxic_waste                      : 1
toxicity                         : 1
toxicology                       : 1
toxins                           : 1
toy                              : 2
toy_worlds                       : 1
toys                             : 7 : toy
tpy_checking                     : 1   : type_checking
trace_analysis                   : 1
trace_divergence                 : 1
tracery                          : 3
tracing                          : 1
tracker                          : 2
tracking                         : 4
trade                            : 15
trade_deficit                    : 1
trade_policy                     : 1
trade_politics                   : 1
trade_routes                     : 1
trade_unions                     : 2
trade_war                        : 4
trademark                        : 8
trademarks                       : 1 : trademark
tradeoff                         : 1
traders                          : 1
trading                          : 2 : trade
trading_cards                    : 1
tradition                        : 9
traditional_dress                : 1
traditional_knowledge            : 1
traditional_society              : 2
traditionalists                  : 1
traffic                          : 15
traffic_laundering               : 1
traffic_stops                    : 1
traffic_tickets                  : 1
traffice                         : 1 : traffick
traffick                         : 1
trafficking                      : 9
tragedy                          : 3
tragedy_of_the_commons           : 1
trailer                          : 4
train                            : 4
training                         : 10
training_costs                   : 1
training_games                   : 1
training_transfer                : 1
trains                           : 3
trait_factor                     : 1
traits                           : 3
trams                            : 1
tranparency                      : 1
trans                            : 16
trans_diagnostic                 : 1
trans_disciplinary               : 2
trans_equality                   : 1
trans_galatica                   : 1
trans_humanism                   : 2
trans_jordan                     : 1
trans_literature                 : 1
trans_man                        : 1
trans_manifesto                  : 1
trans_media                      : 3
trans_men                        : 1
trans_misogyny                   : 1
trans_national                   : 1
trans_phobia                     : 43
trans_rights                     : 1
trans_siberian                   : 1
trans_studies                    : 1
trans_women                      : 1
transaction                      : 1
transaction_costs                : 1
transaction_logic                : 1
transaction_structure            : 1
transactional_analysis           : 1
transactions                     : 1
transation_structure             : 1   : transaction_structure
transcendental_realism           : 1
transcript                       : 15
transcripts                      : 3   : transcript
transdiagnostic                  : 1   : trans_diagnostic
transdiciplinarity               : 1   : trans_disciplinary
transdisciplinary                : 1   : trans_disciplinary
transequality                    : 1   : trans_equality
transfer_learning                : 2
transform                        : 9
transform_harm                   : 2
transformation                   : 11
transformation_rules             : 1
transformations                  : 2   : transformation
transformative_justice           : 2
transformer                      : 2
transformers                     : 2   : transformer
transformharm                    : 2   : transform_harm
transforms                       : 7   : transform
transgender                      : 91
transgnder                       : 1   : transgender
transgression                    : 1
transhumanism                    : 1   : transhumanism
transient_information            : 1
transients                       : 1
transition                       : 15
transition_graph                 : 1
transition_system                : 2
transition_systems               : 4   : transition_system
Transitions                      : 1 : transition
transitions                      : 5   : transition
transjordan                      : 1   : trans_jordan
translation                      : 6
translit                         : 1   : trans_literature
transmedia                       : 3   : trans_media
transmen                         : 1   : trans_men
transmisogyny                    : 1   : trans_misogyny
transmission                     : 3
transnational                    : 1   : trans_national
transnational_corporations       : 1
transparency                     : 20
transphobi                       : 1 : trans_phobia
transphobia                      : 43  : trans_phobia
transpiler                       : 2
transport                        : 3   : transportation
transportation                   : 3
transportation_engineering       : 1
transsiberian                    : 1   : trans_siberian
transvaal                        : 1
transvaginal_ultrasound          : 1
transvestites                    : 1
transvestities                   : 1   : transvestites
trapdoor                         : 2
traps                            : 3
trash                            : 5
trashed_bathrooms                : 2
trauma                           : 43
trauma_culture                   : 1
trauma_informed_care             : 6
trauma_narrative                 : 1
travel                           : 10
traveller                        : 2
Traveller                        : 2   : traveller
travellers                       : 1   : traveller
travelogue                       : 1
treason_act                      : 1
treatise_of_human_nature         : 1
treatment                        : 1
treatment_effects                : 1
treaty                           : 9
tree                             : 22
tree_adjoining_grammar           : 1
tree_adjoining_grammars          : 1   : tree_adjoining_grammar
tree_alphabet                    : 1
tree_of_life                     : 1
tree_rewriting                   : 1
tree_search                      : 1
tree_transducers                 : 1
treemap                          : 2
treemaps                         : 1   : treemap
trees                            : 12
trello                           : 2
treloars_college                 : 1
trends                           : 4
trespasser                       : 1
tresspass                        : 1
triadic_relations                : 1
triage                           : 2
trial                            : 1
trial_and_error_learning         : 1
trial_by_tech                    : 1
trial_error                      : 1
trials                           : 1   : trial
triangle                         : 1
tribal                           : 3
tribal_epistemology              : 1
tribal_integration               : 1
tribal_politics                  : 1
tribalism                        : 2
tribe                            : 1
tribes                           : 7 : tribe
tribunal                         : 3
tribunals                        : 1 : tribunal
trickster                        : 2
tricksters                       : 1 : trickster
trie                             : 2
tries                            : 1
trig                             : 1
trigger                          : 1
trigger_warning                  : 5
trigger_warnings                 : 2
triggered                        : 1
trigonometry                     : 3
trilemma                         : 1
trincher                         : 1
trip_advisor                     : 1
tripadvisor                      : 1   : trip_advisor
trivial_dialogue_phrases         : 1
trobriand                        : 1
trojan_war                       : 1
troll                            : 19  : trolling
trolley_problem                  : 1
trolling                         : 2
trolls                           : 1   : trolling
tron                             : 1
tropes                           : 4
tropical_diseases                : 1
tropical_geometry                : 1
tropicana                        : 1
tropico                          : 2
tropics                          : 1
Tropos                           : 1
trousers                         : 1
troy                             : 1
truancy                          : 6
trucking                         : 2
truism                           : 1
trump                            : 551
trump. policy                    : 1   : trump : policy
trump_bench                      : 1
trump_care                       : 2
trump_foundation                 : 1
trump_university                 : 1
trumpcare                        : 2   : trump_care
TrumpConcentrationCamps          : 1   : trump : concentration_camps
TrumpIsAMoron                    : 1
TrumpIsATraitor                  : 1
Trust                            : 1 : trust
trust                            : 30
trust_spectrum                   : 1
truth                            : 3
truth_maintenance                : 2   : truth_maintenance_system
truth_maintenance_system         : 1
truther                          : 1
try_catch                        : 1
tsar                             : 1
tsetse_fly                       : 1
tshirt                           : 2
tshirt_cannon                    : 1
tshirts                          : 2   : tshirt
tsimshian                        : 1
tsunamis                         : 1
tsundur                          : 1
tube                             : 1
tube_stations                    : 1
tuberculosis                     : 2
tudor                            : 1
tufts                            : 1
tug_of_war                       : 1
tuition                          : 2
tujunga                          : 1
tuk_tuk                          : 1
tulip                            : 1
tulsa                            : 3
tulsa_race_massacre              : 1
tumble_town                      : 1
tumbleweeds                      : 1
tumblr                           : 74
tuning                           : 1
tunisia                          : 2
tuple                            : 1
tuple_generating_dependencies    : 1
tuple_space                      : 1
turbine                          : 1
turbulence                       : 1
turing_award                     : 1
turing_complete                  : 2
turing_machine                   : 1
turing_machines                  : 2   : turing_machine
turing_test                      : 1
turkey                           : 14
turkish                          : 1
turky                            : 1   : turkey
turn                             : 2
turn_based_combat                : 2
turn_based_strategy              : 1
turn_taking                      : 5
Turnaway                         : 1
turned_based_strategy            : 1
turning_point                    : 1
turnover                         : 2
turns                            : 1
turnstile_jumper                 : 1
turtle                           : 1
tusayan                          : 2
tuskegee                         : 2
tutorial                         : 402
tutoring                         : 1
tutoring_systems                 : 1
tv_episode                       : 4
tv_guide                         : 1
tv_news                          : 1
tv_show                          : 35
tv_shows                         : 1   : tv_show
tv_tropes                        : 3
tvguide                          : 1   : tv_guide
twee                             : 1
tweening                         : 1
tweet                            : 3
tweeting                         : 1
twig                             : 2
twilight                         : 1
twin                             : 2
twin_oaks                        : 1
twin_peaks                       : 2
twine                            : 17
twitch                           : 7
twitch_plays_pokemon             : 1
twitter                          : 114
twitter_lists                    : 1
twitter_thread_activation        : 1
two_point_hospital               : 1
two_spirit                       : 1
twocare                          : 1
twurl                            : 1
tyle                             : 1
type                             : 1   : types
type_2_fuzzy_sets                : 2
type_2_interval                  : 1
type_3_error                     : 1
type_caste                       : 1
type_checking                    : 26
type_classes                     : 2
type_classopedia                 : 1
type_errors                      : 1
type_holds                       : 1
type_inference                   : 13
type_providers                   : 1
type_safety                      : 3
type_script                      : 1
type_semantics                   : 1
type_structure                   : 1
type_system                      : 23
Type_Systems                     : 1
type_systems                     : 1
type_theory                      : 9
types                            : 62
typestate                        : 1
typewriter                       : 2
typicality                       : 1
typification                     : 1
typing                           : 2
typography                       : 13
typological_neutrality           : 1
typology                         : 27
tyranny                          : 9
tyranny_of_structurelessness     : 1
tyranny_of_the_concrete          : 1
tyson_foods                      : 2
tyt_network                      : 1
