*  My Kingdom for a Function: Modeling Misadventures of the Innumerate
  [[http://jasss.soc.surrey.ac.uk/6/3/8.html][Paper Link]]
** Tags                                                                         :netlogo:ethnography:epidemiology:drug_use:abm:
** Citation:
** YEAR : 2003
** AUTHORS
   Michael Agar
** ABSTRACT
   In this tongue-in-cheek commentary the author takes a serious look at the
   problem of translating ethnographic conclusions into simple functions as a means
   to the end of building an agent-based simulation in the Netlogo language.
   Specifically, the goal is to take the simple fact that stories about illicit
   drugs have a lot to do with whether or not they will be used and see if an
   agent-based model can produce an epidemic incidence curve under the appropriate
   conditions. This commentary has less to do with the model and more to do with
   figuring out what kinds of numbers make sense. Based on the principle that
   mathematical ignorance is bliss, the author concludes that the most important
   thing is that number construction reflects the differences that make a
   difference in the ethnographic work, where the discovery of what the significant
   differences in fact were was a major result of the research. Support by NIH/NIDA
   grant DA 10736 is gratefully acknowledged.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
