*  Using Social Simulation to Explore the Dynamics at Stake in Participatory Research
  [[http://jasss.soc.surrey.ac.uk/14/4/12.html][Paper Link]]
** Tags
** Citation:
** YEAR : 2011
** AUTHORS
   Olivier Barreteaua and Christophe Le Pageb
** ABSTRACT
   This position paper contributes to the debate on perspectives for simulating the
   social processes of science through the specific angle of participatory
   research. This new way of producing science is still in its infancy and needs
   some step back and analysis, to understand what is taking place on the
   boundaries between academic, policy and lay worlds. We argue that social
   simulation of this practice of cooperation can help in understanding further
   this new way of doing science, building on existing experience in simulation of
   knowledge flows as well as pragmatic approaches in social sciences.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
