*  Role-Playing Games, Models and Negotiation Processes
  [[http://jasss.soc.surrey.ac.uk/6/2/10.html][Paper Link]]
** Tags                                                                         :role_playing_games:participatory_simulation:companion_modelling:artificial_societies:
** Citation:
** YEAR : 2003
** AUTHORS
   Olivier Barreteau, Christophe Le Page and Patrick D'Aquino
** ABSTRACT
   This special collection of papers on Role-Playing Games, Models and Negotiation
   Processes presents a selection of papers from two thematic sessions at the
   International Society for Ecological Economics conference held in Sousse,
   Tunisia, in February 2002. The aim of these thematic sessions was to share
   experiments involving negotiation using models and role-playing games (RPG), in
   order to review the range of these experiments and the methodological
   difficulties encountered.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
