*   Typical Pitfalls of Simulation Modeling - Lessons Learned from Armed Forces and Business
  [[http://jasss.soc.surrey.ac.uk/15/2/5.html][Paper Link]]
** Tags                                                                         :simulation:pitfalls:military:methodology:management:logic_of_failure:
** Citation:
** YEAR : 2012
** AUTHORS
   Rolf Bartha, Matthias Meyerb and Jan Spitznerc
** ABSTRACT
   This paper identifies possible pitfalls of simulation modeling and suggests ways
   to prevent them. First, we specify five typical pitfalls that are associated
   with the process of applying simulation models and characterize the "logic of
   failure" (Dörner 1996) behind the pitfalls. Then, we illustrate important
   aspects of these pitfalls using examples from applying simulation modeling to
   military and managerial decision making and present possible solutions to them.
   Finally, we discuss how our suggestions for avoiding them relate to current
   methodological discussions found in the social simulation community.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
