*  A Logical Architecture of a Normative System
** Tags                                                                         :counts_as:IO_logic:permissions:obligations:
** Citation: Boella2006a
** YEAR : 2006
** AUTHORS
   Guido Boella and Leendert van der Torre
** ABSTRACT
   Logical architectures combine several logics in to a more complex logcal
   system. In this paper we study a logical architecture using input/output
   operations corresponding to the functionality of logical components. We
   illustrate how the architectural approach can be used to develop a logic of a
   normative system based on logics of counts-as conditionals, institutional
   constraints, obligations and permissions. In this example we adapt for
   counts-as conditionals and institutional constraints a proposal of Jones and
   Sergot, and for obligations and permissions we adapt the input/output logic
   framework of Makinson and van der Torre. We use our architecture to study
   logical relations among counts-as conditionals, institutional constraints,
   obligations and permissions. We show that in our logical architecture the
   combined system of counts-as conditionals and institutional constraints
   reduces to the logic of institutional constraints, which again reduces to an
   expression in the underlying base logic. Counts-as conditionals and
   institutional constraints are defined as a pre-processing step for the
   regulative norms. Permissions are defined as exceptions to obligations and
   their interaction is characterized.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
