*  Learning Dilemmas in a Social-Ecological System: An Agent-Based Modeling Exploration 
  [[http://jasss.soc.surrey.ac.uk/17/1/2.html][Paper Link]]
** Tags                                                                         :agent:water:south_africa:learning:institution:catchment:
** Citation:
** YEAR : 2014
** AUTHORS
   Erin Bohensky
** ABSTRACT
   The process of learning in social-ecological systems is an emerging area of
   research, but little attention has been given to how social and ecological
   interactions motivate or inhibit learning. This is highly relevant to the
   South African water sector, where a major policy transition is occurring that
   provides local water users and managers with new opportunities to engage in
   adaptive learning about how to balance human and ecological needs for water.
   In this paper, an agent-based model is used to explore potential 'learning
   dilemmas', or barriers to learning in the South African water sector, whereby
   human perceptions combined with social-ecological conditions affect the
   capacity, understanding, and willingness required to learn. Agents manage
   water according to different management strategies and use various indicators
   to evaluate their success. The model shows that in areas with highly variable
   hydrological regimes, agents may be less able to learn because conditions are
   too unpredictable for them to benefit from past experience. Because of these
   changing conditions, however, agents are more likely to try new water
   management strategies, promoting a greater diversity of experience in the
   system for agents to learn from in the future. In water-stressed areas, where
   agents tend to have greater difficulty fulfilling demand for water than in
   areas with abundant water supplies, they are also more apt to try new
   strategies. When learning is restricted to small areas, agents may learn more
   quickly but based on a more narrow range of experience than in larger or more
   heterogeneous areas. These results suggest a need to enhance learning so that
   it accounts for interacting hydrological, ecological, and social dynamics.
   Although the model is a highly stylised version of reality, this preliminary
   exploration may eventually help to reverse the past trend of poor
   understanding of social-ecological dynamics as they relate to water
   management.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
