*  The Origin of Institutions: socio-economic processes, choice, norms and conventions
  [[http://jasss.soc.surrey.ac.uk/2/2/1.html][Paper Link]]
** Tags                                                                         :evolutionary_algorithms:socio_economic_simulation:agent_modelling:institutional_economics:
** Citation:
** YEAR : 1999
** AUTHORS
   José Castro Caldas and Helder Coelho
** ABSTRACT
   Institutions, the way they are related to the behaviour of the agents and to the
   aggregated performance of socio-economic systems, are the topic addressed by
   this essay. The research is based on a particular concept of a bounded rational
   agent living in society and by a population based simulation model that
   describes the processes of social learning. From simple co-ordination problems,
   where conventions spontaneously emerge, to situations of choice over alternative
   constitutional rules, simulation was used as a means to test the consistency and
   extract the implications of the models. Institutions, as solutions to recurring
   problems of social interaction, are both results and preconditions for social
   life, unintended outcomes and human devised constraints. In an evolutionary
   setting no support is found for the deep rooted beliefs about the 'naturally'
   beneficial outcomes generated by 'invisible-hand' processes or by any
   alternative Hobbesian meta-agency.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
