*  Considering a Multi-Level Model as a Society of Interacting Models: Application to a Collective Motion Example 
  [[http://jasss.soc.surrey.ac.uk/18/3/7.html][Paper Link]]
** Tags                                                                         :collective_motion:mas:multi_model:multi_level:
** Citation:
** YEAR : 2015
** AUTHORS
   Benjamin Camus, Christine Bourjot and Vincent Chevrier
** ABSTRACT
   As they involve relationships between interacting individuals and groups,
   social systems can be described at different levels of resolution. In a
   number of modeling cases, only one of these levels is explicitly represented.
   In order to study phenomena where both individual and collective
   representations are needed, multi-level modeling is a good approach as it
   explicitly represents these different levels. We propose to consider a
   multi-level representation from a multi-modeling point of view. This
   perspective allows explicitly specifying the level's relationships and,
   therefore, to test hypothesis about interaction between individuals and
   groups in social systems. We define a framework to better specify the
   concepts used in multi-level modeling and their relationships. This framework
   is implemented through the AA4MM meta-model, which benefits from a middleware
   layer. This meta-model uses the multi-agent paradigm to consider a
   multi-model as a society of interacting models. We extend this meta-model to
   consider multi-level modeling, and present a proof of concept of a collective
   motion example, where we show the advantages of this approach for the study
   of social phenomena.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
