*  Normative reputation and the costs of compliance
  [[http://jasss.soc.surrey.ac.uk/1/3/3.html][Paper Link]]
** Tags                                                                         :compliance:reputation:norms:
** Citation:
** YEAR : 1998
** AUTHORS
   Cristiano Castelfranchi, Rosaria Conte and Mario Paolucci
** ABSTRACT
   In this paper, the role of normative reputation in reducing the costs of
   complying with norms will be explored. In previous simulations (Conte &
   Castelfranchi 1995), in contrast to a traditional view of norms as means for
   increasing co-ordination among agents, the effects of normative and
   non-normative strategies in the control of aggression among agents in a common
   environment was confronted. Normative strategies were found to reduce aggression
   to a much greater extent than non-normative strategies, and also to afford the
   highest average strength and the lowest polarisation of strength among the
   agents. The present study explores the effects of the interaction between
   populations following different criteria for aggression control. In such a
   situation the normative agents alone bear the cost of norms, due to their less
   aggressive behaviour, while other agents benefit from their presence. Equity is
   then restored by raising the cost of aggression through the introduction of
   agents' reputation. This allows normative agents to avoid respecting the
   cheaters' private property, and to impose a price for transgression. The
   relevance of knowledge communication is then emphasised by allowing neighbour
   normative agents to communicate. In particular, the spreading of agents'
   reputation via communication allows normative agents to co-operate without
   deliberation at the expense of non-normative agents, thereby redistributing the
   costs of normative strategies.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
