*  From Social Monitoring to Normative Influence
  [[http://jasss.soc.surrey.ac.uk/4/2/7.html][Paper Link]]
** Tags                                                                         :social_contagion:social_control:imitation:mas:norms:
** Citation:
** YEAR : 2001
** AUTHORS
   Rosaria Conte and Frank Dignum
** ABSTRACT
   This paper is intended to analyse the concepts involved in the phenomena of
   social monitoring and norm-based social influence for systems of normative
   agents. These are here defined as deliberative agents, representing norms and
   deciding upon them. Normative agents can use the norms to evaluate others'
   behaviours and, possibly, convince them to comply with norms. Normative
   agents contribute to the social dynamics of norms, and more specifically, of
   norm-based social control and influence. In fact, normative intelligence
   allows agents to

   Check the efficacy of the norms (the extent to which a norm is applied in the
   system in which it is in force), and possibly Urge their fellows to obey the
   norms.

   The following issues are addressed:

   What is norm-based control?
   Why and how do agents exercise control on one another?
   What role does it play in the spread of norms?
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
