*  Narrative Intelligence from the Bottom Up: A Computational Framework for the Study of Story-Telling in Autonomous Agents
  [[http://jasss.soc.surrey.ac.uk/4/1/1.html][Paper Link]]
** Tags                                                                         :autonomous_robots:narrative_intellignce:autobiographic_agents:
** Citation:
** YEAR : 2001
** AUTHORS
   Kerstin Dautenhahn and Steven J. Coles
** ABSTRACT
   This paper addresses Narrative Intelligence from a bottom up, Artificial Life
   perspective. First, different levels of narrative intelligence are discussed in
   the context of human and robotic story-tellers. Then, we introduce a
   computational framework which is based on minimal definitions of stories,
   story-telling and autobiographic agents. An experimental test-bed is described
   which is applied to the study of story-telling, using robotic agents as examples
   of situated, autonomous minimal agents. Experimental data are provided which
   support the working hypothesis that story-telling can be advantageous, i.e.
   increases the survival of an autonomous, autobiographic, minimal agent. We
   conclude this paper by discussing implications of this approach for
   story-telling in humans and artifacts.
** Summary
   Levels of narrative intelligence:
    0) "Grandfather Model" of Schank and Abelson. *Essentially a
       Doorbell*.
    1) Random selection of stories to tell
    2) Eliza-like contextual storytellers.
    3) Interpretive/ encode and retrieval based storyteller
    4) Human narrative intelligence.

*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
