* A Pragmatic Reading of Friedman's Methodological Essay and What It Tells Us for the Discussion of ABMs
  [[http://jasss.soc.surrey.ac.uk/12/4/6.html][Paper Link]]
** Tags                                                                         :calibration:assumptions:abm:methodology:
** Citation:
** YEAR : 2009
** AUTHORS
   Simon Deichsel
   Andreas Pyka
** ABSTRACT
   The issues of empirical calibration of parameter values and functional
   relationships describing the interactions between the various actors plays an
   important role in agent based modelling. Agent-based models range from purely
   theoretical exercises focussing on the patterns in the dynamics of
   interactions processes to modelling frameworks which are oriented closely at
   the replication of empirical cases. ABMs are classified in terms of their
   generality and their use of empirical data. In the literature the
   recommendation can be found to aim at maximizing both criteria by building
   so-called 'abductive models'. This is almost the direct opposite of Milton
   Friedman's famous and provocative methodological credo 'the more significant
   a theory, the more unrealistic the assumptions'. Most methodologists and
   philosophers of science have harshly criticised Friedman's essay as
   inconsistent, wrong and misleading. By presenting arguments for a pragmatic
   reinterpretation of Friedman's essay, we will show why most of the
   philosophical critique misses the point. We claim that good simulations have
   to rely on assumptions, which are adequate for the purpose in hand and those
   are not necessarily the descriptively accurate ones.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
