*  A Context- and Scope-Sensitive Analysis of Narrative Data to Aid the Specification of Agent Behaviour
  [[http://jasss.soc.surrey.ac.uk/18/1/17.html][Paper Link]]
** Tags                                                                         :narrative:specification:analysis:scope:context:qualitative_data:
** Citation:
** YEAR : 2015
** AUTHORS
   Bruce Edmonds
** ABSTRACT
   A structure for analysing narrative data is suggested, one that distinguishes
   three parts in sequence: context (a heuristic to identify what knowledge is
   relevant given a kind of situation), scope (what is possible within that
   situation) and narrative elements (the detailed conditional and sequential
   structure of actions and events given the context and scope). This structure is
   first motivated and then illustrated with some simple examples taken from
   Sukaina Bharwani's thesis (Bharwani 2004). It is suggested that such a structure
   might be helpful in preserving more of the natural meaning of such data, as well
   as being a good match to a context-dependent computational architecture, and
   thus facilitate the process of using narrative data to inform the specification
   of behavioural rules in an Agent-Based Simulation. This suggestion only solves
   part of the 'Narrative Data to Agent Behaviour' puzzle — this structure needs to
   be combined and improved by other methods and appropriate computational
   architectures designed to suit it.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
