*  Modelling the Emergence of Possession Norms using Memes
  [[http://jasss.soc.surrey.ac.uk/4/4/3.html][Paper Link]]
** Tags
** Citation:
** YEAR : 2001
** AUTHORS
   Felix Flentge, Daniel Polani and Thomas Uthmann
** ABSTRACT
   In this paper we study the emergence and the effects of a possession norm in
   an artificial society. We link the study of norms and the concept of memes
   as put forward by Richard Dawkins. Normative behaviour is modelled using
   memes as carriers for certain behaviours. For our simulations we extend the
   sugarscape model from Epstein and Axtell (1996) and give the agents the
   possibility to claim possession of a "plot" of land. Memes regulate the
   behaviour of the agents regarding the land claims of others. It turns out
   that the probability for the survival of the population is much higher when
   possession claims of others are respected. However, there exist short term
   disadvantages for agents respecting the possessions of others. Thus, the
   need for a possession norm arises. The introduction of sanctions provides a
   good possibility to enforce the norm as long as no costs arise for
   sanctioning agents. We also investigate different kinds of meme propagation
   and their effects on the establishment of the norm.

** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
