* Appearances Can Be Deceiving: Lessons Learned Re-Implementing Axelrod's 'Evolutionary Approach to Norms'
  [[http://jasss.soc.surrey.ac.uk/8/3/2.html][Paper Link]]
** Tags                                                                         :metanorms:norms:social_dilemmas:evo_game_theory:abm:replication:
** Citation:
** YEAR : 2005
** AUTHORS
   Jose Manuel Galan and Luis R. Izquierdo
** ABSTRACT
    In this paper we try to replicate the simulation results reported by Axelrod
    (1986) in an influential paper on the evolution of social norms. Our study
    shows that Axelrod's results are not as reliable as one would desire. We can
    obtain the opposite results by running the model for longer, by slightly
    modifying some of the parameters, or by changing some arbitrary assumptions
    in the model. This re-implementation exercise illustrates the importance of
    running stochastic simulations several times for many periods, exploring the
    parameter space adequately, complementing simulation with analytical work,
    and being aware of the scope of our simulation models.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
