*  The Multi-Agent Modelling Language and the Model Design Interface
  [[http://jasss.soc.surrey.ac.uk/2/3/8.html][Paper Link]]
** Tags                                                                         :integrated_modelling_environment:ABM:social_science_simulation:
** Citation:
** YEAR : 1999
** AUTHORS
   L치szl칩 Guly치s, Tam치s Kozsik and John B. Corliss
** ABSTRACT
   While computer models provide many advantages over traditional experimental
   methods, they also raise several problems. The process of software development
   is a complicated task with high potential for errors, especially when it is
   carried out by scientists holding their expertise in other fields than computer
   science. On the other hand, the process of creating computer simulations of
   social systems which reflect the reality of such systems requires insights
   considerably beyond expertise in computer science. The Multi-Agent Modelling
   Language (MAML) is one of the efforts to ease these difficulties.

   In its current version, MAML is a macro-language for Swarm (a freely distributed
   toolset under development at SFI), but it is also part of a larger
   Swarm-independent framework. Also, the design of MAML, while influenced by
   concepts from Swarm, is general enough to allow for later extension of the
   supported simulation kernels. This paper gives an overview of the mentioned
   larger framework, with special emphasis on MAML and its graphical CASE tool, the
   Model Design Interface.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
