* Agent-Based Modelling: The Next 15 Years
  [[http://jasss.soc.surrey.ac.uk/13/4/7.html][Paper Link]]
** Tags                                                                         :abm:policy_advice:netlogo:
** Citation:
** YEAR : 2010
** AUTHORS
   Lynne Hamill
** ABSTRACT
   This short note makes recommendations for the future direction of research in
   agent-based modelling (ABM). It is a personal view based on my experience as a
   policy adviser who has recently come to ABM. I suggest that to promote the use
   of ABM, the ABM community needs demonstrate the value of modelling to other
   social scientists by showing-by-doing and offering training projects; and to
   produce tools, guidance on good-practice and basic building blocks. Then the
   policy contexts most likely to benefit from ABM need to be identified along with
   any new data requirements, so that the usefulness of ABM can be demonstrated to
   policy analysts. This is, in my view, the challenge facing the ABM community for
   the next 15 years.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
