*  Explaining Simulations Through Self Explaining Agents
  [[http://jasss.soc.surrey.ac.uk/13/1/4.html][Paper Link]]
** Tags                                                                         :virtual_training:goal_based_behavior:agents:explaination:
** Citation:
** YEAR : 2010
** AUTHORS
   Maaike Harbersa, John-Jules Meyera and Karel van den Boschb
** ABSTRACT
   Several strategies are used to explain emergent interaction patterns in
   agent-based simulations. A distinction can be made between simulations in which
   the agents just behave in a reactive way, and simulations involving agents with
   also pro-active (goal-directed) behavior. Pro-active behavior is more variable
   and harder to predict than reactive behavior, and therefore it might be harder
   to explain. However, the approach presented in this paper tries to make
   advantage of the agents' pro-activeness by using it to explain their behavior.
   The aggregation of the agents' explanations form a basis for explaining the
   simulation as a whole. In this paper, an agent model that is able to generate
   (pro-active) behavior and explanations about that behavior is introduced, and
   the implementation of the model is discussed. Examples show how the link between
   behavior generation and explanation in the model can contribute to the
   explanation of a simulation.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
