*  Rules don't apply: Kafka's insights on Bureaucracy
** Tags                         :weber:rule_breaking:kafka:chaos:bureaucracy:
** Citation: Hodson2013
** YEAR : 2012
** AUTHORS
   Randy Hodson
   Andrew W. MartinSteven H. Lopez
   Vincent J. Roscigno
** ABSTRACT
   Weber’s ideal typical model of bureaucracy constitutes the starting point for
   most scholarship on organizations. Much organizational behaviour, however
   occurs outside this formalized model. It is thus somewhat surprising that
   behaviours outside the formal-rational model are, more often than not,
   treated as aberrations. In contrast, the emerging critical literature on
   ‘inhabited institutions’ has identified such gaps in our theoretical
   understanding as foundational, warranting a more agentic conception of
   organizational life—a conception more fully acknowledging of and sensitive to
   the dynamics of power in organizational life. In this regard, we highlight
   four prevalent (though seldom theoretically incorporated) features of
   contemporary bureaucracies—divergent goals, patrimonialism, unwritten rules
   and chaos. These features, which we contend are no less critical to
   organizational functioning than those identified by Weber, constitute an
   organizational logic more compatible with a Kafkan vision of bureaucracy than
   with a Weberian one. Theorizing such attributes allows us to explore elements
   of bureaucratic life that the formal-rational model of bureaucracy renders
   largely invisible and is conceptually and empirically ill equipped to
   incorporate. An illustrative analysis, drawing on narrative data drawn from
   the population of organizational ethnographies (n = 162) (1) demonstrates the
   prominence of such dynamics in organizational life; and (2) highlights their
   implications for rule breaking as a relatively common yet under-theorized
   occurrence. A core implication of our analysis and critique is that the
   social sciences need a fundamentally revised theory of bureaucracy capable of
   understanding bureaucracy’s power laden and often dystrophic features.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
