*  The Current State of Normative Agent-Based Systems
  [[http://jasss.soc.surrey.ac.uk/14/2/6.html][Paper Link]]
** Tags                     :simulation:jasss:agents:normative_systems:norms:
** Citation
** AUTHORS
   Christopher D. Hollander
   Annie S. Wu
** YEAR : 2011
** ABSTRACT
   Recent years have seen an increase in the application of ideas from the social
   sciences to computational systems. Nowhere has this been more pronounced than
   in the domain of multiagent systems. Because multiagent systems are composed
   of multiple individual agents interacting with each other many parallels can
   be drawn to human and animal societies. One of the main challenges currently
   faced in multiagent systems research is that of social control. In particular,
   how can open multiagent systems be configured and organized given their
   constantly changing structure? One leading solution is to employ the use of
   social norms. In human societies, social norms are essential to regulation,
   coordination, and cooperation. The current trend of thinking is that these
   same principles can be applied to agent societies, of which multiagent systems
   are one type. In this article, we provide an introduction to and present a
   holistic viewpoint of the state of normative computing (computational
   solutions that employ ideas based on social norms.) To accomplish this, we (1)
   introduce social norms and their application to agent-based systems; (2)
   identify and describe a normative process abstracted from the existing
   research; and (3) discuss future directions for research in normative
   multiagent computing. The intent of this paper is to introduce new researchers
   to the ideas that underlie normative computing and survey the existing state
   of the art, as well as provide direction for future research.
** Summary
   Always with *efficiency*: "Research on social control address the challenge
   of ensuring that a system operates *efficiently* while at the same time
   allowing individual agents maintain their freedom"

   Makes the point of following *methodological individualism*. This works from
   the individual on up. Again, consider institutional analysis, should we
   start with individuals?

   Normative agents must:
   1) satisfy the regular notions associated with artificial agents
   2) represent norms in a format that allows them to be reasoned
      over and modified during the lifetime of the agent
   3) recognise and infer the norms of other agents based on
      observations and interactions while not confusing the norms with
      individual rules and constraints
   4) transmit norms
   5) sanction otheragents who do not comply with known norms as
      required


**** What is a norm
     authoritative standard / principle of right action / typical behaviours

     an obligation / permission (boella)

     or a prohibition

     in legal theory: any behavioural rule dictated by a ruling body (verhagen)

     in social sciences: behavioural constraints that are socially enforced
     (bendor and swistak...)

     Common theme: behaviours which *ought* to be displayed by members of a
     group in a given context (boella).

     "One aspect of norms that is frequently left unaddressed in artificial
     systems is their dynamic nature and tendency to change over time (neumann
     2008)"

     norms can be *sub-optimal*

     norms can be willfully violated. There is *normative choice*

     *COIN* workshops? *EMIL* project for norm innovation COST* action OC0801
     *working group on norms

**** Key Concepts
     a norm is a behavioural rule that is considered valid by the majority of
     the population

     norms are acquired through a social learning process

     norms are social enforced

     norms spread, by active and passive transmission mechanisms

**** Means of representing norms


***** In the Social Sciences

      social function of norms: durkheim, parsons, merton social impact of
      norms: economics mechanisms leading to norms: complexity science

      in literature: norms address individual action, govern interaction between
      members of a group, dictate responses to behaviours observed in others.

      social function in terms of obligations: legal, moral, conditional.

      provides dicitions and noramlity.

      social impact: cost provided to / imposed on parties involved in a social
      interaction. can impose costs and benefits on individuals or groups.

      most recently: interest in norm emergence and creation. Two general
      methods of norm creation: (Boella, Tuomela, Verhagen)
      1) *Type 1* explicitly created and enforced by an authority structure
      2) *Type 2* emerge from regularities in behaviour


****** oughtness
       refers to the notion that there are behaviours an agent should or should
       not perform regardless of the possible consequences

****** expectation
       refers to the behaviours other agents anticipate when observing an agent.
       created when an agent displays behavioural regularity when it encounters
       specific contexts.


***** In Computer Science


****** Modal Logic
       deontic logic as a derivation. Exclusion logic / Versu too. links to
       legal theory. boella, castelfranchi, alberti, meneguzzi, sadri. illegal
       behaviour - Meyer and Wieringa.

****** condition/action pairs in rule systems
       Cif is an example. Boella. Typically offline designed.

****** binary strings
       Islanders. A more abstract representation of norms.

****** game theory
       Bicchieri. CiF. choices and payoffs


**** Norm Life Cycle
     mentions norm taxonomies and typologies of *finnemore and sikkink* and
     *savarimuthu and cranefield* and *verhagen*.

***** Patterns of norm life cycles

      enforcement -> recognition -> obedience -> sanctions internalization ->
      acceptance -> modification -> internalization emergence -> transmission ->
      enformcement -> internalization evolution -> creation -> transmission ->
      enforcement -> internalization -> forgetting


**** Categories of the norm life cycle:

***** Creation

***** Transmission

***** recognition

***** enforcement

***** acceptance

***** modification

***** internalization

***** emergence

***** forgetting

***** evolution


*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
