*  Generating Social Practices
  [[http://jasss.soc.surrey.ac.uk/17/1/17.html][Paper Link]]
** Tags                                                                         :consumption:social_practice:
** Citation:
** YEAR : 2014
** AUTHORS
   Georg Holtz
** ABSTRACT
   Changing consumer behaviour is key to reducing the environmental effects of
   industrialised societies. Social practice theories provide an integrated
   approach to understanding consumer behaviour. The mechanisms underlying the
   emergence and diffusion of social practices are however until now poorly
   understood. This paper presents a conceptual framework and an abstract
   agent-based simulation model for generating social practices which use and
   extend approaches from social practice theories. The main results are
   twofold. First, the simulation model is able to generate social practices,
   what confirms that the conceptual framework captures relevant elements and
   processes. Second, a new mechanism for behavioural lock-in is identified
   that provides additional insights into the widely acknowledged challenge of
   changing social practices and respective consumption.

** Summary
**** Results
     Simulation model able to generate social practices
     Mechanism for Behavioural lock-in identified

**** Background
***** TODO Social Practice Theory?
      " Social practices involve consumption as performing the
      respective activities requires the usage of material artefacts
      as well as resources such as energy and water. Hence social
      practices such as showering (almost) every day or doing the
      laundry according to a specific standard of cleanness
      (Shove 2004) have a large impact on a society's resource use."

      ----
      "Jackson (2005) notes that "… our understanding of the dynamics
      of social practice, of the ways in which social practices
      evolve, and of the interaction between policy and social
      practice is as yet so limited that it would be difficult to see
      how policy could make use of this position…" (p. 63). "

      JACKSON, T. (2005). Motivating Sustainable Consumption – a review of
      evidence on consumer behaviour and behavioural change. A report
      to the Sustainable Development Research Network.
      ----

      Giddens - Structuration mediates between actors and structure.
      Extended by Schatzki and Reckwitz.

      ( RECKWITZ, A. (2002). Toward a Theory of Social
      Practices. European Journal of Sociology, 5(2), 243–263. )

      "Individuals are seen as the 'carriers of practices' who do not
      freely choose between practices based on utility or similar
      individualistic concepts but are 'recruited' to practices
      according to their background and history (Reckwitz 2002)"

      ----

      SHOVE, E., & Pantzar, M. (2005). Consumers, Producers and
      Practices. Journal of Consumer Culture, 5(1),
      43–64. [doi:10.1177/1469540505049846]

      "Conceptualised the role of the material (bodily activities,
      technological artefacts) in social practices, that was mostly
      neglected in early practice theories, but which is crucial for
      analysing environmental effects of practices."

      A Practice is a configuration of three components: material, meaning and competence.

      ----

      "SPT doesn't conceptualise how the components 'glue together',
      ie. why certain elements form 'succesful' practices which diffuse
      and are maintained by a substantial part of society while other
      constellations of elements do not succeed."

**** Conceptual framework of social practices
***** Components
      Social practices as weak emergent property of the interaction of individual, compoents etc.
      Only first order convergence considered, not macro-level properties.
      Components linked by individuals when carrying out a practice.

****** Material
       Physical aspects of the performance of a practice.
****** Meaning
       understandings, beliefs, emotions
****** Competence
       skills and knowledge which are required to perform the practice.
       eg: driving skills, knowledge of public transport routes.

***** Coherence
      Coherence elaborated by Holtz.
      ( HOLTZ, G. (2012a). Coherence of social practices: the case of
      meat consumption. Unpublished working
      paper. http://www.usf.uos.de/institut/publikationen/forschungsgruppen/rem.html )
      ( HOLTZ, G. (2012b). An agent-based model of social practices. ESSA 2012 Proceedings. )

****** Cognitive consitency
       (alighning behaviours with beliefs / deontics)
       ie: meaning and material must fit.

****** habits over deliberated decisions
       ie: competence and material must fit.

***** social sharing practices

****** adapt meaning to material
       eg: learning about the environmental effects of car use may choose to go by bike

****** adapt competence to material
       eg: introduction of congestion charge in London + public
       transport investment to change transport preferences

****** habituation
       reinforced situation-goal-response connections.  Two different
       modes of behaviour:
******* deliberate choice of material
******* habitual behaviour keeping current material

****** adapt material

****** exchange meaning

**** Implementation
     Simple bitstrings.


*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
