*  Emergence and Collapse of the Norm of Resource Sharing Around Locally Abundant Resources
  [[http://jasss.soc.surrey.ac.uk/18/4/7.html][Paper Link]]
** Tags                                                                         :hawk_dove_bourgeouis_game:norms:resources:abm:
** Citation:
** YEAR : 2015
** AUTHORS
   Shiro Horiuchi
** ABSTRACT
   How do individuals resolve conflicts over resources? One way is to share
   resources, which is possible between known individuals, with the use of
   sanctions on free riders or by partner selection. Another way is for anonymous
   individuals to respect the finders' ownership of resources based on asymmetry
   and avoid conflicts over resources. This study elucidates the conditions under
   which anonymous individuals share resources with each other irrespective of
   their asymmetry with regard to resources. High resource values inhibit anonymous
   individuals from sharing resources; however, small cumulative values and local
   distributions let anonymous individuals share the resources. Punishment of the
   richest individuals also supports resource sharing. These conditions may
   represent resource sharing among anonymous individuals in periods of great
   disasters and may be the origin of the practice of exchange in prehistoric
   times.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
