*  A Play of Bodies: A Phenomenology of Videogame Experience
** Tags                                                                         :videogames:play:experience:phenomenology:
** Citation:
** YEAR : 2015
** AUTHORS
   Brendan Keogh
** ABSTRACT
   Videogames require robust yet flexible methods and vocabularies of critical analysis that appreciate both the textual and embodied pleasures of players. Such analysis cannot start with the player’s intentions as an autonomous user nor with the videogame as a stable object; rather, it must account for the dynamic interplay between videogame hardware, sensorial perception, and audiovisual and haptic representations. If it is to understand how a particular videogame is engaged as both textual artefact and embodied practice, such analysis must be concerned with not just what the player does with the videogame, but what the videogame does with the player.
   This thesis forwards a phenomenology of videogame experience to account for how
   the player and the videogame incorporate each other in reflexive cycles that
   mediate presence, attention, perception, and agency. It does not hope to
   understand videogames either ‘as narratives’ or ‘as games’ but as particular
   amalgamations of existing and nascent media and forms—it hopes to understand
   videogames as videogames. It explores videogame play as a convergence of
   eyes-on-screens, ears-at-speakers, and muscles-against-interfaces to interrogate
   the limits of current game studies approaches that often obscure rich
   commonalities between videogames and other media forms. Drawing upon
   phenomenology, posthumanism, and cyborg theory, and embedded in detailed and
   multifaceted analyses of various videogames on different platforms as played,
   this thesis develops nuanced understandings of how the player and the videogame
   come together during play to form particular modes of embodiment through which a
   videogame work is both interpreted and perceived.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
