*  A Computational Model of Worker Protest
  [[http://jasss.soc.surrey.ac.uk/14/3/1.html][Paper Link]]
** Tags                                                                         :group_identity:netlogo:trust:protest:jasss:
** Citation:
** YEAR : 2011
** AUTHORS
   Jae-Woo Kim
   Robert Hanneman
** ABSTRACT
   This paper presents an agent-based model of worker protest. Workers have
   varying degrees of grievance depending on the difference between their wage
   and the average of their neighbors. They protest with probabilities
   proportional to grievance, but are inhibited by the risk of being
   arrested—which is determined by the ratio of coercive agents to probable
   rebels in the local area. We explore the effect of similarity perception on
   the dynamics of collective behavior. If workers are surrounded by more
   in-group members, they are more risk-taking; if surrounded by more out-group
   members, more risk-averse. Individual interest and group membership jointly
   affect patterns of workers protest: rhythm, frequency, strength, and duration
   of protest outbreaks. Results indicate that when wages are more unequally
   distributed, the previous outburst tends to suppress the next one, protests
   occur more frequently, and they become more intensive and persistent. Group
   identification does not seriously influence the frequency of local uprisings.
   Both their strength and duration, however, are negatively affected by the
   ingroup-outgroup assessment. The overall findings are valid when workers
   distinguish 'us' from 'them' through simple binary categorization, as well as
   when they perceive degrees of similarity and difference from their neighbors.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
