*  The Development of Social Simulation as Reflected in the First Ten Years of JASSS: a Citation and Co-Citation Analysis
  [[http://jasss.soc.surrey.ac.uk/12/4/12.html][Paper Link]]
** Tags
** Citation:
** YEAR : 2009
** AUTHORS
   Matthias Meyer, Iris Lorscheid and Klaus G. Troitzsch
** ABSTRACT
   Social simulation is often described as a multidisciplinary and fast-moving
   field. This can make it difficult to obtain an overview of the field both for
   contributing researchers and for outsiders who are interested in social
   simulation. The Journal for Artificial Societies and Social Simulation (JASSS)
   completing its tenth year provides a good opportunity to take stock of what
   happened over this time period. First, we use citation analysis to identify the
   most influential publications and to verify characteristics of social simulation
   such as its multidisciplinary nature. Then, we perform a co-citation analysis to
   visualize the intellectual structure of social simulation and its development.
   Overall, the analysis shows social simulation both in its early stage and during
   its first steps towards becoming a more differentiated discipline.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
