* Between Replication and Docking: "Adaptive Agents, Political Institutions, and Civic Traditions" Revisited
  [[http://jasss.soc.surrey.ac.uk/13/3/1.html][Paper Link]]
** Tags                                                                         :social_capital:italy:abm:docking:replication:
** Citation:
** YEAR : 2010
** AUTHORS
   Dan Miodownika, Britt Cartriteb and Ravi Bhavnanic
** ABSTRACT
   This article has two primary objectives: (i) to replicate an agent-based model
   of social interaction by Bhavnani (2003), in which the author explicitly
   specifies mechanisms underpinning Robert Putnam's (1993) work on Civic
   Traditions in Modern Italy, bridging the gap between the study's historical
   starting point—political regimes that characterized 14th Century Italy—and
   contemporary levels of social capitalóreflected in a 'civic' North and an
   'un-civic' South; and (ii) to extend the original analysis, using a landscape of
   Italy that accounts for population density. The replication exercise is
   performed by different authors using an entirely distinct ABM toolkit (PS-I)
   with its own rule set governing agent-interaction and cultural change. The
   extension, which more closely approximates a docking exercise, utilizes equal
   area cartograms otherwise known as density-equalizing maps (Gastner and
   Newman 2004) to resize the territory according to 1993 population estimates. Our
   results indicate that: (i) using the criterion of distributional equivalence, we
   experience mixed success in replicating the original model given our inability
   to restrict the selection of partners to 'eligible' neighbors and limit the
   number of agent interactions in a timestep; (ii) increasing the number of agents
   and introducing more realistic population distributions in our extension of the
   replication model increases distributional equivalence; (iii) using the weaker
   criteria of relational alignment, both the replication model and its extension
   capture the basic relationship between institutional effectiveness and civic
   change, the effect of open boundaries, historical shocks, and path dependence;
   and (iv) that replication and docking may be usefully combined in model-to-model
   analysis, with an eye towards verification, reimplementation, and alignment.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
