*  Grounded Simulation
  [[http://jasss.soc.surrey.ac.uk/18/1/9.html][Paper Link]]
** Tags                                                                         :theoretical_coding:ontology:evidence_based_modeling:grounded_theory:
** Citation
   
** AUTHORS
   Martin Neumann
** YEAR : 2015
** ABSTRACT
   This paper investigates the contribution of evidence-based modelling to
   grounded theory (GT). It is argued that evidence-based modelling provides
   additional sources to truly arrive at a theory through the inductive process
   of a Grounded Theory approach. This is shown by two examples. One example
   concerns the development of software ontologies of criminal organisations.
   The other example is a simulation model of escalation of ethno-nationalist
   conflicts. The first example concerns early to middle stages of the research
   process. The development of an ontology provides a tool for the process of
   theoretical coding in a GT approach. The second example shows stylised facts
   resulting from a simulation model of the escalation of ethno-nationalist
   conflicts in the former Yugoslavia. These reveal mechanisms of nationalist
   radicalisation. This provides additional credibility for the claim that
   evidence-based modelling assists to inductively generate a theory in a GT
   approach.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
