*  Norm Internalisation in Human and Artificial Intelligence
  [[http://jasss.soc.surrey.ac.uk/13/1/12.html][Paper Link]]
** Tags                                                                         :theoretical_validity:socialisation_theories:norm_internalisation:normative_agent_architecture:
** Citation:
** YEAR :
** AUTHORS
   Martin Neumann
** ABSTRACT
   In this article, principles of architectures relating to normative agents are
   evaluated with regard to the question whether and to what extend results of
   empirical research are incorporated in the architecture. In the human sciences,
   internalisation is a crucial element within the concept of norms.
   Internalisation distinguishes normative behaviour regulation from mere coercion.
   The aim of this article is to begin answering the question of to what extent
   normative agent architectures represent the theoretical construct of norm
   internalisation. The relevant research in this area may be found in
   socialisation research in psychology and sociology. Evaluation of conclusions
   from the empirical sciences allows to identify drawbacks and opportunities in
   existing architectures, as well as to develop suggestions for future
   development.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
