*  Homo Socionicus: a Case Study of Simulation Models of Norms
  [[http://jasss.soc.surrey.ac.uk/11/4/6.html][Paper Link]]
** Tags                                                                         :norms:methodological_individualism:role_theory:norMAS:
** Citation:
** YEAR : 2008
** AUTHORS
   Martin Neumann
** ABSTRACT
   This paper describes a survey of normative agent-based social simulation
   models. These models are examined from the perspective of the foundations
   of social theory. Agent-based modelling contributes to the research program
   of methodological individualism. Norms are a central concept in the role
   theoretic concept of action in the tradition of Durkheim and Parsons. This
   paper investigates to what extend normative agent-based models are able to
   capture the role theoretic concept of norms. Three methodological core
   problems are identified: the question of norm transmission, normative
   transformation of agents and what kind of analysis the models contribute.
   It can be shown that initially the models appeared only to address some of
   these problems rather than all of them simultaneously. More recent
   developments, however, show progress in that direction. However, the degree
   of resolution of intra agent processes remains too low for a comprehensive
   understanding of normative behaviour regulation.

** Summary
    Neumann (2008)

**** Intro
     Mentions link between role theory (ie: Parsons), and norms.
     Action as guided by normative orientation.
     Over the past 20 years there has been criticism of Social Factor
     based explanations.
     Role theory was based on Durkheim / social factors.
     Rise of *Methodological Individualism* / 'From Factors to Actors'
     (Macy and Willer). This enables investigation into *the feedback
     loop between individual interaction and collective dynamics*

**** The original *homo sociologicus*
     Dahrendorf (1956)
     Meeting a fictional 'Mr Smith' at a cocktail party. What is there
     to find out about him?

     "Mr Smith is an adult male, circa 35 years old. He holds a PhD,
     and is an academic. Since he wears a wedding ring, we know that
     he is married. He lives in a middle-sized town in Germany and is
     a German citizen. Moreover, we discover that he is Protestant and
     that he arrived as a refugee after the 2nd World War in a town
     populated mostly by Catholics. We are told that this situation
     caused some difficulties for him. His is a Lecturer by profession
     and he has two kids. Finally, we learn that he is the third
     chairmen of the local section of a political party, Y, a
     passionate and skilful card player and a similarly passionate
     though not so good driver. This approximates to what his friends
     would tell us. "

     We find out *social facts* about him, without finding out about
     Smith's unique identity.
     Social Facts -> Social Positions -> Social Roles.
     "Roles are defined by specific attributes, behaviour and social
     relations. Demands of society determine individual behaviour"
     These demands are transmitted to the individual by *norms*.
     "Casting mould" (Durkheim 1895).

     Neumann makes the point that Dahrendorf mentions Smith is
     unlikely to use the cane on his pupils, and driving competence
     would be unlikely to be mentioned now. So *norms change*.

***** Characteristics of Norms
      1) Norms show generality
      2) Norms ahve a subjective element
         Action sets for roles can cover a wide range.
         Ends of an action have to be determined internally.
      3) Roles are functionally relevant for the reproduction of society.
         Father educates child, Lecturer socialises pupils.


***** Criticism of Classical Role Theory
      1) Norm conception of role theory has a dubious epistemological
         basis.
         Durkheim and Parsons take a functional analysis over causal.
         (See also Gellner and Archer for the *reification of
         society*)
      2) An over socialised picture of man. (Wrong, Homans, and Balog)
         Individual actors are, in Role Theory, treated as social
         automata.


***** Questions for Agent Based Models
      1) Can they provide insights into the normative regulation of
         society? (Focus of contribution)
      2) Do they allow for a causal reconstruction of the mechanisms
         that generate the functional interconnectedness on the social
         level?
      3) What transforms the agents in such a way that they factually
         follow norms? Causal mechanism at work to enable
         internalisation. (Transformation problem)
      4) By what mechanisms in the model can norm-abiding behaviour
         spread to or decay from one agent to another. (Transmission
         problem).

      Research traces back to game theory (J: ie: Bicchieri) and AI (ie:
      Boella).

***** TODO See Hegselmann for a broad range of moral dynamics.

**** Discussion of Axelrod's evolutionary norms
     Creates a norm and meta-norm game. *Does not rely on rationality*
     only on effectiveness of norms.
     Variables for meta-norm enforcement include boldness and
     vengefulness.

     Axelrod's model has flexible agents, with observable changes in
     behaviour. Is the starting point for many *normative dynamics*
     investigations.
     Is limited by the applicability to macro-level
     functionality. Decisions are purely based on calculating expected
     utility.
     "An active element of normative orientation in the choice
     relating to the ends of action cannot be found in a game
     theoretic approach". Mirrors Parson's critique of utilitarian
     theories of action.

     Agents do not act focused on norms. Norms are for interpretation
     of others behaviour. *Transformation is not identical with
     internalisation*.

**** Discussion of Castelfranchi's function of norms in social groups through simulation

     Differentiates between *norms of co-ordination* and *explicit
     prescriptive, directive and command norms*. (J: In this respect
     similar to Bicchieri).

     Simple world of agents, food, smell, attacks, and diminishing
     strength.

***** Types of Experiment
      1) Blind Aggression.
         No means to control aggression, always attack when able.
      2) Strategic aggression.
         Attacks constrained by strategic reasoning.
         Only attack weaker agents.
      3) Normative agents.
         Finder-keeper norm. Multiple possession.
         Agents do not attack agents eating their own possessed food.

      Units of analysis: *rate of aggression*, *average strength of agents*,
      *variance of individual strength*.

      "The classical scheme of a functional explanation assumes a social
      phenomena P, whereby P has a (functional) effect n for the
      society. Individual actors have reasons to practise P independently of
      the functional effect n. Moreover there is a feedback loop so that in
      the case of a decrease of P, there is a cause for an amplification of
      P. Thus, society remains in equilibrium. It is claimed that this state
      of affairs is crucial for the 'survival' of the society. "


      Norms in this model, unlike Axelrod's, are explicit action routines.

      However, transmission, transformation, and internalisation are not
      dealt with by Castelfranchi's model. The agents are normative automata
      with no personal variation in behaviour.

***** Development of normative agents.
      Section *6* of the paper describes a number of game theoretic and
      cognitive architectures for normative simulations.
      Implementations include *dynamic propensities*, *conditional
      strategies*, *dynamic updating*,*decision trees* and *dynamic
      thresholds*.

      Game theoretic tradition tends to investigate norm dynamics, while AI
      tradition tends to investigate functional aspects of norms.
      Cognitive agents have become more flexible and applicable to
      transformation problems. GT tends to use sanctions, AI uses a variety
      of means.

      Communication for transformation is more explicitly modelled in AI.

      Social learning is implemented in many game theoretic models by
      replicator dynamics. This amounts to: more successful types of
      behaviour become more frequent, without formalising the mechanism.

**** TODO Convergence example: Verhagen

**** TODO Convergence example: Savarimuthu



*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
