*  Tools of the Trade: A Survey of Various Agent Based Modeling Platforms 
  [[http://jasss.soc.surrey.ac.uk/12/2/2.html][Paper Link]]
** Tags                                                                         :survey:MAS:ABM:
** Citation:
** YEAR : 2009
** AUTHORS
   Cynthia Nikolai and Gregory Madey
** ABSTRACT
   Agent Based Modeling (ABM) toolkits are as diverse as the community of people
   who use them. With so many toolkits available, the choice of which one is
   best suited for a project is left to word of mouth, past experiences in using
   particular toolkits and toolkit publicity. This is especially troublesome for
   projects that require specialization. Rather than using toolkits that are the
   most publicized but are designed for general projects, using this paper, one
   will be able to choose a toolkit that already exists and that may be built
   especially for one's particular domain and specialized needs. In this paper,
   we examine the entire continuum of agent based toolkits. We characterize each
   based on 5 important characteristics users consider when choosing a toolkit,
   and then we categorize the characteristics into user-friendly taxonomies that
   aid in rapid indexing and easy reference.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
