*  A Logic of Delegation
** Tags                                                                         :agent_communication:responsibility:imperatives:groups:delegation:logic:
** Citation: Norman2010
** YEAR : 2010
** AUTHORS
   Timothy J. Norman
   Chris Reed
** ABSTRACT
   Delegation is a foundational concept for understanding and engineering systems
   that interact and execute tasks autonomously. By extending recent work on tensed
   action logic, it becomes possible to pin down a specific interpretation of
   responsibility with a well specified semantics and a convenient and intuitive
   logic for expression. Once descriptions of direct agent responsibility can be
   formed, there is a foundation upon which to characterise the dynamics of how
   responsibility can be acquired, transferred and discharged and, in particular,
   how delegation can be effected. The resulting logic, designed specifically to
   cater for responsibility and delegation, can then be employed to offer an
   axiological and semantic exploration of the related concepts of forbearance,
   imperatives and group communication.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
