*  Simulating Correctional Disturbances: The Application of Organization Control Theory to Correctional Organizations via Computer Simulation
  [[http://jasss.soc.surrey.ac.uk/2/1/1.html][Paper Link]]
** Tags                                                                         :general_systems_theory:deterministic_systems:organizational_control:prison_riots:prison_management:simulation:
** Citation:
** YEAR : 1999
** AUTHORS
   Steven Patrick, Patricia M. Dorman and Robert L. Marsh
** ABSTRACT
   Inmate group behavior is a complex phenomenon that many researchers have
   attempted to understand. Most of the individual theories applied to this issue
   have had limited success. This work uses computer simulation to apply a complex
   theory of organizational control to the issue of inmate group behavior that
   incorporates all the major theoretical components found in the individual
   theories. The complete theory is first presented and then basic simulation
   results are discussed. The findings show that the simulated theory produced
   results that are empirically realistic. The control processes used by prisons
   generally produce compliance from inmates but these same control processes
   result in episodic periods of negative inmate group behavior. These initial
   results point to the promise of computer simulation for understanding complex
   control issues in ways simpler theories cannot.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
