*  Extracting OWL Ontologies from Agent-Based Models: A Netlogo Extension
  [[http://jasss.soc.surrey.ac.uk/18/2/15.html][Paper Link]]
** Tags                                                                         :netlogo:OWL_API:OWL:transparency:ontology:
** Citation:
** YEAR : 2015
** AUTHORS
   Gary Polhill
** ABSTRACT
   Using OWL ontologies to represent the state and structure of a simulation at any
   one time has been argued to improve the transparency of a social simulation, on
   the basis that this information is then not embedded in the source code of the
   model, or in the computer's memory at run-time. Should transparency of such a
   form be desirable, it would be preferable to enable it by extracting the
   information automatically from a running model. However, semantic differences
   between traditional object-oriented programming languages and description logics
   pose an obstacle to this. This paper presents arguments that Netlogo does not
   have the same semantic challenges to automated ontology extraction, and
   describes an extension to Netlogo (5.0) using the OWL-API (3.1.0) that extracts
   state and structure ontologies from an existing Netlogo model. The extension is
   freely available from https://github.com/garypolhill/netlogo-owl.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
