*  How Can Social Networks Ever Become Complex? Modelling the Emergence of Complex Networks from Local Social Exchanges
  [[http://jasss.soc.surrey.ac.uk/8/4/12.html][Paper Link]]
** Tags                                                                         :structural_emergence:social_exchange_theory:abm:small_world:scale_free:power_law:complex_networks:
** Citation:
** YEAR : 2005
** AUTHORS
   Josep M. Pujol, Andreas Flache, Jordi Delgado and Ramon Sangüesa
** ABSTRACT
   Small-world and power-law network structures have been prominently proposed as
   models of large networks. However, the assumptions of these models usually lack
   sociological grounding. We present a computational model grounded in social
   exchange theory. Agents search attractive exchange partners in a diverse
   population. Agent use simple decision heuristics, based on imperfect, local
   information. Computer simulations show that the topological structure of the
   emergent social network depends heavily upon two sets of conditions, harshness
   of the exchange game and learning capacities of the agents. Further analysis
   show that a combination of these conditions affects whether star-like,
   small-world or power-law structures emerge.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
