*  Simulating Norms, Social Inequality, and Functional Change in Artificial Societies
  [[http://jasss.soc.surrey.ac.uk/2/1/2.html][Paper Link]]
** Tags                                                                         :social_inequality:functional:norms:simulation:
** Citation:
** YEAR : 1999
** AUTHORS
   Nicole J. Saam and Andreas Harrer
** ABSTRACT
   In this paper, we compare the computational and sociological study of norms, and
   resimulate previous simulations (Conte and Castelfranchi 1995a, Castelfranchi,
   Conte and Paolucci 1998) under slightly different conditions. First, we analyze
   the relation between norms, social inequality and functional change more
   closely. Due to our results, the hypothesis stating that the "finder-keeper"
   norm while controlling aggression efficaciously reduces social inequality holds
   only in quite egalitarian societies. Throughout a variety of inegalitarian
   societies, it instead increases social inequality. This argument which can be
   traced back to Marx is being investigated by use of computer simulations of
   artificial societies. Second, we remodel normative behaviour from a sociological
   point of view by implementing Haferkamp's theory of action approach to deviant
   behaviour. Following the game theoretic models, the computational study of norms
   has up to now ignored the importance of power in explaining how norms affect
   social behaviour, how norms emerge, become established and internalized, and
   change. By simulating Haferkamp and repeating the Conte and Castelfranchi
   experiments, we demonstrate that it is possible to integrate power into
   computational models of norms.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
