*  Obligation Norm Identification in Agent Societies
  [[http://jasss.soc.surrey.ac.uk/13/4/3.html][Paper Link]]
** Tags                                                                         :norMAS:artificial_societies:simulation_of_norms:agent_based_simulation:norm_identification:obligations:social_norms:norms:
** Citation:
** YEAR : 2010
** AUTHORS
   Tony Savarimuthu, Stephen Cranefield, Maryam A. Purvis and Martin K. Purvis
** ABSTRACT
   Most works on norms have investigated how norms are regulated using
   institutional mechanisms. Very few works have focused on how an agent may infer
   the norms of a society without the norm being explicitly given to the agent.
   This paper describes a mechanism for identifying one type of norm, an obligation
   norm. The Obligation Norm Inference (ONI) algorithm described in this paper
   makes use of an association rule mining approach to identify obligation norms.
   Using agent based simulation of a virtual restaurant we demonstrate how an agent
   can identify the tipping norm. The experiments that we have conducted
   demonstrate that an agent in the system is able to add, remove and modify norms
   dynamically. An agent can also flexibly modify the parameters of the system
   based on whether it is successful in identifying a norm.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
