*  Economic Performance, Inter-Firm Relations and Local Institutional Engineering in a Computational Prototype of Industrial Districts
  [[http://jasss.soc.surrey.ac.uk/5/1/1.html][Paper Link]]
** Tags                                                                         :technological_change:local_institutional_engineering:industrial_districts:abm:
** Citation:
** YEAR : 2002
** AUTHORS
   Flaminio Squazzoni and Riccardo Boero
** ABSTRACT
   Industrial districts can be conceived as complex systems characterised by a
   network of interactions amongst heterogeneous, localised, functionally
   integrated and complementary firms. In a previous paper, we have introduced an
   industrial district computational prototype, showing that the economic
   performance of an industrial district proceeds to the form through which firms
   interact and co-ordinate each others. In this paper, we use such computational
   framework to experiment different options of 'local institutional engineering',
   trying to understand how specific 'supporting institutions' could perform
   macro-collective activities, such as, i.e., technology research, transfer and
   information, improving the technological adaptation of firms. Is a district more
   than a simple aggregation of localised firms? What can explain the economic
   performance of firms localised into the same space? Could some options of 'local
   institutional engineering' improve the performance of a district? Could such
   options set aside the problem of how firms dynamically interact? These are
   questions explored in this paper.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
