* A Virtual Laboratory for the Study of History and Cultural Dynamics
  [[http://jasss.soc.surrey.ac.uk/14/4/19.html][Paper Link]]
** Tags                                                                         :virtual_lab:netlogo:MAS:cultural_complexity:cultural_dynamics:
** Citation:
** YEAR : 2011
** AUTHORS
   Juan-Luis Suáreza and Fernando Sanchob
** ABSTRACT
   This article presents a Virtual Laboratory that enables the researcher to try
   hypothesis and confirm data analysis about different historical processes and
   cultural dynamics. This Virtual Cultural Laboratory (VCL) is developed using
   agent-based modeling technology. Individuals' tendencies and preferences as well
   as the behavior of cultural objects in the transformation of cultural
   information are taken into consideration. In addition, the effect of local
   interactions at different scales over time and space is visualized through the
   VCL interface. Information repositories, cultural items, borders, population
   size, individual' tendencies and other features are determined by the user.
   Finally, the researcher can also isolate specific factors whose effect on the
   global system might be of interest to the researcher. All the code can be found
   at http://projects.cultureplex.ca/
** Summary
**** The Model
***** Agents
      Individuals - mobile, carry messages, have preferences and range of behaviours, limited storage.
      Repositories - immobile, preferences, tolerance, no learning, limited storage.
      Cultural Items - No reception, just a single message in memory.
***** Messages
***** Behaviours
      Reception, memory, learning, and emission
      Emmission : Dominant/Creative/Passive behaviours
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
