*  The Cognitive and behavioral mediation of institutions: Towards an account of institutional actions
** Tags                                                                         :power:coordination:constitutive_rules:MAS:castelfranchi:institutions:
** Citation
   Tummolini2006
** AUTHORS
   Luca Tummolini
   Cristiano Castelfranchi
** YEAR : 2006
** ABSTRACT
   The aim of this paper is to provide an analysis of institutional actions from
   the standpoint of cognitive science.

   The notion of constitutive rules have been proposed to describe the
   conceptual nature of institutions.

   In this paper it is extended to cover specific processes of ‘recognition’ that
   provide the agents with additional artificial powers.

   The power of doing an
   institutional action is considered as a special kind of artificial power.

   It is argued that institutional actions achieve their effects thanks to a
   cognitive and behavioral mediation of a collective of agents.

   Individual actions are seen and treated as (count as) institutional actions
   by the involved participants even if, in fact, institutional actions are
   collective
   actions.

   When human behavior becomes institutionalized, it acquires special
   conventional powers to bring about effects in the social world.

   A model of such conventional empowerment of an agent is proposed and is
   identified in a sort of collective permission.

   Finally it is argued that institutions are a specific kind of coordination
   artifacts.

   In particular, the importance of institutional roles as artifacts that assign
   conventional powers is investigated.

** Quotes
*** Institution Definitions and claims
    "Institutions are usually conceived as normative systems that structure
    social interactions."

   "As it is generally acknowledged, an institution is a solution to
   coordination problems of a collective, but what seems to be special in the
   case of institutions is that such coordination is obtained thanks to the
   constitution of a new level of actions that can be done. "

   "Our claim is that to institutionalize something is to assign a specific
   kind of artificial powers to it by means of a conceptualization that can be
   expressed by counts as formulas."

   "Our ontological statement is that institutional actions, like paying,
   marrying, promising, having precedence and so on and so forth, are concrete
   physical actions in the physical world. "

   "Our claim is that every individual action in the institution is actually a
   multiagent action where the collectivity unintentionally collaborate so that
   the individual agent achieves his intended results. Differently from the
   previous case, this collaborative action is not intentional. While during
   the ceremony each agent acting in the institutional role cooperates
   intentionally with the other, they are also unintentionally cooperating in
   a very different way."

   "As it is clear the notion of ‘group’ in institutional actions is local,
   context dependent and dynamic."

   "It is a platitude to argue that institutions seem to be something external
   to the agents that enact them while actually they are man made products
   evolved or designed to coordinate agents’ activities."

   "The main difference between conventions and institutions lies in the fact
   that while a convention enables a single-agent action that contributes to a
   multiagent coordination (when acting according to a convention, the agent
   has the power of acting in coordination with others), an institution provides
   individual agents with the special conventional power of doing an action
   which is a multi-agent coordinated action."

   "We have also acknowledged that to get the institutional machinery off the
   ground it is necessary that the involved participants believe that there is
   one agent in the group that has the power of doing the institutional action
   (subjective power)."

*** Mentions of Others
    "We agree with Searle that there is a 'primacy of the micro-level' where the
    individual agents constitute the institution by considering something as
    something else.'

   "Makinson (1986) has argued that ‘having the power is not the same as being
   permitted to use it’."

   "Traditional and assumed definitions of an institution as ‘‘the laws, rules
   and conventions that give a durable structure to social interactions in
   members of a population’’ (Bowles, 2004) tend to reduce institutions to
   conventions."

   "Actually there is a continuum the goes from conventions, to practices and to
   institutions (Tuomela, 2002). And more importantly, convention in Lewis’
   sense can evolve in institutions. "

*** Examples
    " Take this example from Jones and Sergot (1996): in a department the
    signature of the secretary (X term) counts as the signature of the boss (Y
    term)."

   "The function of the chairs depends on their physical features that are there
   independently of any human agreement. However, at the same time, Searle
   argues that functions are never intrinsic and always observer relative. In
   his theory, functions are always ascribed by humans to the external material
   world."

   "Something is usable as a chair even if it is not recognized as a chair,
   however this possibility of being used as a chair will never be actualized if
   somebody does not recognize it as a chair. In this recognition process, the
   agent needs to infer a possible use of the artifact. Notwithstanding its
   intrinsic function, if the agent does not acknowledge its use, the artifact
   seems to lack the status of being fully a chair."

   "Take the institutional action of ‘marrying’. If Paul, the priest, is
   marrying John and Mary such action can be exe- cuted only if there is a set of
   agents recognizing it. The involved agents see the vehicle actions of the priest
   as a token of the Cognitive Type ‘to marry’ (cognitive media- tion). While
   necessary, this condition however is not sufficient. As in the case of ‘acting
   together’ for such an action to have physical effects
   in the world (and so to exist), it is also necessary that the set of involved
   actors act accordingly to this interpretation (treat as). Because they have
   recognized that the institutional action A has already occurred, they
   consequently believe the R obtains, viz. that John and Mary are married (mutual
   belief that R is true). Either the belief that the supra-action has been accom-
   plished or simply its
   reactive interpretation (disposition to behave), trigger the agent to treat the
   vehicle action a as A and so act on this basis (behavioral mediation)."

   "There is a complex hierarchy of levels which involve both formal and
   informal authorities. The formal authority has the conventional power of
   assigning conventional powers (the lawmaker). The informal one assigns these
   powers simply by their behavioral mediation, by acting accordingly to a given
   recognition (the involved participants). The latter is actually more fundamental
   because it is the real support also for the first one. But due to the fact that
   usually the informal authority does not know of having such an objective power,
   it is not able to influence the formal one."

   "The mechanism is stable also because, as we have seen, it is a co-power of
   the involved participants not a single power of any of them. None of them
   individually by deciding not to accept the power of the priest is able to
   prevent all the other from empowering him."

*** Perception
    "It is at least since the late forties (Bruner & Goodman, 1947) that it is
    argued that perception is ‘‘necessarily the end product of a process of
    categorization [. . .] in which organisms move inferentially from cues to
    category identity’’. Such a ‘perceptual semiosis’ is something different
    from the signification process where something stands for something else."

*** Action, Function and Goal
    "An action is always a (supra-)action composed of a vehicle action and an
    external delegated event."

   "A function is ‘‘an external goal placed on a system that results in a trans-
   formation of the structural properties of the system’’. The external goal is
   usually internal to another goal-governed agent, but what is specific
   relative to weaker notions like ‘use’ and ‘destination’ is that the physical
   characteristics of the system are caused by the external goal."

   "However, we also claim that there exist external goals that are not internal
   to any agent at all. ... Finalities are selecting effects that modify an
   organism’s characteristics in a way that will render it more adaptive."

   "A goal can be defined as a sieve used to select the (morphological or
   behavioral) properties of a system such that at time t1 such properties are
   not the result of chance, but of its preceding history (t0) that consists in
   the rejections resulting from the sieve sifting the alterna- tives of a given
   property."

   "The ‘use’ of something is a weaker notion relative to the notion of
   ‘function’. We consider the ‘use’ as the simplest notion of external goal.
   Even if something does not have a function, it can still have a use."

   "We say that such a tool (and of course a proper artifact) provides the agent
   with the physical power of achieving at least one of his goals"

   "However, to effectively have the power of achieving the goal, even an
   artifact with a function needs to be recognized as usable which means that
   the agent is able to infer how the artifact is supposed to be used (rules of
   use)"

   "From this perspective, to say that ‘‘objects that are designed and used to
   be sat on by one person counts as chairs’’ is something more that a simple
   description. A sort of empowerment is present also when agents appropriately
   recognize a tool or an artifact. Conceptualization of arti- facts is a form of
   empowerment.

   "To the eyes of the agents, the tie between the artifact and the enabled
   actions is so strict the ordinary language allows expressions such ‘the goal
   of the knife is to cut’. This common conception treats the action as
   intrinsic to the artifact"

   "An agent has an objective power when, given his goals, he has the internal
   (skills, motivation, etc.), and external resources (tools and artifacts or
   what- ever) and the conditions for action are such that if he acts, he
   achieves those goals."

   "In collaborative activities, there is more than one agent executing the
   necessary vehicle actions {a, b, . . . , n} and each of these vehicles are
   part of the collective action A."

   "It is in fact a communicative action, when one is doing his share in a group
   activity is also emitting a message. "

   "Differently, it is evident that there are a number of institutional
   actions that we perform that are non-intentional. Think of the case of
   murdering. Killing a man and murdering can be two very distinct kind of
   actions. Some instances of the first, in certain conditions, are cases of the
   second. Others are not, a soldier in battle is not murdering even if he is
   killing thousands of men. There are very different collective behaviors when we
   know that a specific soldier has killed an enemy (or even an innocent civilian)
   with the respect to the case that a killer has been discovered in our block.
   However it is very common that in both cases the agents while intending to kill
   somebody do not intend to perform an institutional action that is nevertheless
   performed."

   "In other words, we identify an artifact as a kind of result of an action, as
   something which is done (is brought about) by an agent x in order to
   (intentionally or functionally) be used by another agent y."

   "Traces of actions can be the most basic kind of coordination artifacts.
   Consider the case of some people walking in a park. The unintended effect of
   their walking is to modify the shape of the grass in a way that is visible
   to others."

   " As we have seen practical and coordination uses and functions very often
   coexist. Even if we have distinguished artifacts that have practical functions
   but only coordination uses (i.e. the bottle and glass) from artifacts that
   have both practical and coordination functions (i.e. the emerged path and the
   table), it is out of the scope of this paper to offer an exhaustive typology of
   coordination artifacts."

*** Formal Definitions

       "Let x be an entity instantiated in a sequence of distinct repetitions
   (x1, ..., xn). A sequence of repetitions is defined as a set of occurrences
   of the same entity linked in such a way that each is produced by the
   preceding, and produces the following occurrences (if any) in the sequence,
   thanks to whatever mechanism of reproduction. Let Bx be the set of behaviors
   or characteristics of x, a finality or function can be defined as follows:

   (1) some items in Bx produces effects unintended by, and unknown to, x;
   (2) any item in x that produces the unintended effect is functional, if that
   effect acts through a causal feedback loop on the mechanism of reproduction,
   favoring x’s reproduction, and as a consequence, that of the item themselves.

   ... It has selected and shaped that behavior or morphology to be as it is. "

   We can consider this process as a double empowerment. By recognizing
   artifacts and tools as usable – somehow acknowledging their ‘rules of use’ –
   (1) and by using them
   (2) agents become able to produce new physical effects in the world.
   Because the former kind of empowerment is mediated by the agent itself we
   consider it a process of artificialization.
   Even if the process is individual, it is the agent that produces it by means
   of his (individual) cognitive mediation, and so in the end he acquires
   additional artificial powers."


   "In our model an action A is composed of a vehicle action a and of an
   external delegated event E on which the agent relies to achieve its intended
   results. The action A can be named supra-action to distinguish it clearly
   from the vehicle one."

   "A minimal model of action implies that the agent believes that his action A
   is necessary and sufficient to achieve R (while the vehicle action is only
   necessary) and that he can obtain R by doing A."

   "We can also define the Community C of agents as the non empty set of all the
   agents that can recognize that institutional action. Such a concept of
   community identifies all the agents that potentially can recognize the
   institutional action and that potentially can act accordingly. "

   "From this, it follows plainly that a Group is a subset of the Community
   sharing that institutional Cognitive Type."

  "We have claimed that doing an institutional action A is a co-power of the group
   G. However the involved agents in G believe that Ag1 has the power of A and for
   this reason, assume that A has been executed. From the subjective point of view,
   agents believe that one of them has such a power."

   "Since it is the group that can do the action, it is the group that has the
   co-power of preventing the single agent Ag1. The conventional/institutional
   empowerment is obtained thanks to a functional permission of the kind
   consent. The functional effect of the acting accordingly is that they pos-
   itively interfere with Ag1 reinforcing his belief of having
   the power of doing the action (Ag1 believes that he can do A, he has the power
   of A). It is not simply the belief that he has the power of doing A that
   empowers the agent but also the fact that they act on this basis."

   "Before and beyond an institutional normative system, it is the participants
   that empowers the Priest in doing the action. If the participant Ag4 does not
   act appro- priately on the basis of the belief that the priest can marry Ag2
   and Ag3 and that they are married as a result of Ag1’s action they in fact
   are not married because the priest actually lacks the power of marrying
   them."

   "All the participants believe and assume that he has such power but are
   unaware of the fact that they (as a group and a community) are empowering
   him by consenting him doing the action, by actively conforming to his
   expectations and so contributing to the achievement of the intended result."

   "Given a population P of agents, A is an artifact if and only if the
   following conditions are satisfied:

   (1) there exists at least one agent x in P such that x brings it about that A;
   (2) there exists at least one agent y in P such that A has a use U for y;
   (3) U is one of the motivating results for x to bring it about that A or y
   using A at t bring it about that x bring it about that A again at some point
   in the future."

*** Different ways in which artifacts support or constrain coordination
    "Proposition 1. There exist some artifacts such that their physical
    opportunities and constraints and the recognition of their use by an agent
    are necessary and sufficient conditions to enable a single-agent action."

    "Proposition 2. There exist some artifacts such that their physical
    opportunities and constraints are sufficient conditions to enable a
    single-agent coordinated action."

    "Proposition 3. There exist some artifacts such that their physical opportunities
    and constraints and the recognition of their use by an agent are necessary and
    sufficient conditions to enable a single-agent coordinated action."

    "Proposition 4. There exist some artifacts such that their physical opportunities
    and constraints and the recognition of their use by an agent and the set of
    ‘cognitive opportunities and constraints’ (deontic mediatiors) are necessary and
    sufficient conditions to enable a single-agent coordinated action."

    "Proposition 5. There exist some artifacts such that the set of cognitive
    opportunities and constraints (deontic mediatiors) are necessary and sufficient
    conditions to enable a single-agent coordinated action. "

*** Institutions as Coordination artifacts
    "Proposition 6. There exist some artifacts such that the recognition of
    their use by an agent and the set of cognitive opportunities and constraints
    (deontic mediators) are necessary and sufficient conditions to enable a
    multiagent coordinated action. "

** Summary
   "Institutional actions are always multi-agent actions."
*** Hypotheses
    Our working hypothesis is that such basic coordination artifact is the
    institutional role that the agent is playing (the priest, the owner) and
    that the collectivity, even if unaware of doing this, is using for
    coordinating their physical actions.

    Institutional roles enable actions that otherwise would not be possible.

    From this respect the role of ‘owner’ is an artifact similar to the ‘knife’.

    By using the knife an agent acquire the power of cutting.

    Similarly, once an agent has the role of ‘owner’, he is somehow empowered to
    exclude all the others from the use of a resource.

    It is our hypothesis the institutional roles are macro-concepts that group a
    set of institutional actions.

*** Authors key findings
    It is part of our research program the grounding of the deontic dimension in
    the physical one.

    In form of a conclusion is useful to summarize the main theses that we have
    defended:
    (1) the process of institutionalization of human behavior is a
    process of artificial empowerment;

    (2) an institutional action is a socially mediated multi-agent action;

    (3) while an institutional action is a socially mediated multi-agent action
    (viz. a collaborative activity) it is not executed on the basis of a shared
    plan;

    (4) an institutional action is regarded as a single agent action and the
    agent believes he has the power of doing the action;

    (5) an institutional action has artificial effects that are added by the
    collectivity so that the intended result is obtained;

    (6) the main result that the action is achieving is the coordination result.
    This result is not necessary intended but is the ultimate end of the action
    (function);

    (7) the institutional action can be done intentionally or not by the agent
    but it is a real action relative to the function of coordinating the
    collectivity;

    (8) the institutional role is the artifact that assign the conventional
    power to the agent. The collectivity by recognizing the role and by acting
    accordingly enable the institutional actions because they wrongly attribute
    the power of the action to the role. This is why having the role is having
    the power;

    (9) the conventional power is always a power of coordi nating a collectivity
    of agents.
*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
