*  Societies, cultures and fisheries from a modeling perspective
  [[http://jasss.soc.surrey.ac.uk/1/2/2.html][Paper Link]]
** Tags                                                                         :environment:dynamics:beliefs:institutions:learning:fisheries:
** Citation:
** YEAR : 1998
** AUTHORS
   Gérard Weisbuch and Guillemette Duchateau-Nguyen
** ABSTRACT
   Cultures can be viewed as sets of beliefs and techniques allowing societies to
   cope with their environment. We here propose simple and explicit schemes showing
   how fishermen could encode beliefs about a renewable resource, fish. We then
   discuss the dynamics of the society, represented by economic and cultural
   variables, coupled to the fishery represented by fish abundance. According to
   different coding schemes and sets of parameters, several dynamical regimes are
   observed, including one with endogenous crises.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
