*  It Pays to Be Popular: a Study of Civilian Assistance and Guerilla Warfare
  [[http://jasss.soc.surrey.ac.uk/8/4/9.html][Paper Link]]
** Tags                                                                         :abm:insurgency:peacekeeping:
** Citation:
** YEAR : 2005
** AUTHORS
   Scott Wheeler
** ABSTRACT
   This paper presents a study into the benefits imparted by friendly civilian
   populaces in assisting peacekeepers to conduct operations under the threat of
   guerrilla warfare. In this study, civilians report observed insurgent activity
   to peacekeepers with varying levels of enthusiasm depending on the reputation of
   the peacekeepers with the local populace. A simulation model is developed using
   an agent-based approach and a statistically significant number of Monte Carlo
   simulations conducted to measure the success of the peacekeeping operations and
   the benefits of civilian assistance.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
