*  Leadership in Small Societies
  [[http://jasss.soc.surrey.ac.uk/13/3/5.html][Paper Link]]
** Tags                                                                         :norms:pacific_island_societies:reciprocity:leadership:
** Citation:
** YEAR : 2010
** AUTHORS
   Stephen Younger
** ABSTRACT
   Multi-agent simulation was used to study several styles of leadership in small
   societies. Populations of 50 and100 agents inhabited a bounded landscape
   containing a fixed number of food sources. Agents moved about the landscape in
   search of food, mated, produced offspring, and died either of hunger or at a
   predetermined maximum age. Leadership models focused on the collection and
   redistribution of food. The simulations suggest that individual households were
   more effective at meeting their needs than a simple collection-redistribution
   scheme. Leadership affected the normative makeup of the population: altruistic
   leaders caused altruistic societies and demanding leaders caused aggressive
   societies. Specific leadership styles did not provide a clear advantage when two
   groups competed for the same resources. The simulation results are compared to
   ethnographic observations of leadership in Pacific island societies.
** Summary
*** Research Questions

*** Hypothesis tested

*** Methods

*** Results

*** Authors key findings

*** Contributions [Faster/Cheaper/Better]

** What kind of text is it?

** What genre is the text?

** What is the critical context?

** What is the intended audience?

** What is your purpose in reading?

** What are you meant to get out of the text?
*** Are you supposed to get the gist, or details?

*** Are you meant to close read the language of the text?

*** Are you meant to apply or relate the text to something else?

*** Are you supposed to engage with (agree, disagree, tweak, nuance) the text?

** What it says / What it does
   For each chapter/section/subsection/paragraph
*** What it Says: Stated or implied topic

*** What it Does: Function within the reading
    Evidence for claim, summarize opposing view, data, analogy etc.

** Double Entry
*** Represent the text in your own words. Restate the argument.

*** Respond to the text.
    Analyse, relate, question, believe, doubt, refute, go beyond.

** Believe / Doubt
   Read with opposing views.
*** Believing - Read generously

*** Doubting  - Read critically

** Reverse Outline
   Organise text hierarchically by function

** Freewrite argumentative response
*** Before I read this text, the author assumed I knew and believed X

*** After I Read this text, the author wanted me to think and believe that Y

*** The Author was (not) successful in changing my views. How so, and why.
