#+TITLE: Quotes
* Unverified
** @alliebland
"Then Google Maps was like, 'turn right on Malcolm Ten Boulevard' and I knew there were no
black engineers working there".
** @chouxsalax and @alt254
 The Greatest trick the videogame industry ever pulled was convincing the world that videogames were games in the first place.
 Unlike traditional games in which voluntary rules are consciously chosen to further constrain
 or interpret the physical properties of dice and cards, balls and bats, or track and field,
 videogames conflate the rulse of a game with the mechanics of the equipment.
- Metagaming
** @dril
The wise man bowed his head solemnly and spoke:
"Theres actually zero difference between good & bad things. you imbecile. you fucking moron."
** @hypervisible
Computational tools aren't going to make people recognize our humanity.
** @mathbabedotorg
A white-shoe law firm or an exclusive prep school will lean far more on recommendations
and face-to-face interviews than will a fast-food chain or a cash-strapped urban school district.
The privileged, we'll see time and again, are processed more by people, the masses by machines.
- Weapons of Math Destruction
** @skulldelacreme (@dirtbagboyfren)
You can't force people to live under capitalism which equates your worth to how
much you own, then not understand property damage as protest.
** @Vanessa_ABee
"Never too young to date, always too young to choose abortion" - ancient GOP Proverb
** Abdullah Zuber
Jihad will continue until all the Hindus, Christians, Buddhists, Atheists are killed.
Your secularism & tolerance can not change our ideology. Quran does not permit survival of non-muslims.
** Abraham Lincoln
But another class of reasoners hold the opinion that there is no such relation between capital and labor, as assumed; and that there is no such thing as a freeman being fatally fixed for life, in the condition of a hired laborer, that both these assumptions are false, and all inferences from them groundless. They hold that labor is prior to, and independent of, capital; that, in fact, capital is the fruit of labor, and could never have existed if labor had not first existed -- that labor can exist without capital, but that capital could never have existed without labor. Hence they hold that labor is the superior -- greatly the superior -- of capital.

The prudent, penniless beginner in the world, labors for wages awhile, saves a surplus with which to buy tools or land, for himself; then labors on his own account another while, and at length hires another new beginner to help him. This, say its advocates, is free labor -- the just and generous, and prosperous system, which opens the way for all -- gives hope to all, and energy, and progress, and improvement of condition to all. If any continue through life in the condition of the hired laborer, it is not the fault of the system, but because of either a dependent nature which prefers it, or improvidence, folly, or singular misfortune. I have said this much about the elements of labor generally, as introductory to the consideration of a new phase which that element is in process of assuming. The old general rule was that educated people did not perform manual labor. They managed to eat their bread, leaving the toil of producing it to the uneducated. This was not an insupportable evil to the working bees, so long as the class of drones remained very small. But now, especially in these free States, nearly all are educated -- quite too nearly all, to leave the labor of the uneducated, in any wise adequate to the support of the whole. It follows from this that henceforth educated people must labor. Otherwise, education itself would become a positive and intolerable evil. No country can sustain, in idleness, more than a small per centage of its numbers. The great majority must labor at something productive. From these premises the problem springs, "How can labor and education be the most satisfactory combined?"
- [[http://www.abrahamlincolnonline.org/lincoln/speeches/fair.htm][Address before the Wisconsin State Agricultural Society Milwaukee, Wisconsin September 30, 1859]]

We the people are the rightfuli masters of both Congress and the courts, not to
overthrow the Constitution but to overthrow the men who pervert the Constitution.

We here highly resolve... that government of the people, by the people, for the people,
shall not perish from the earth.
- Gettysburg Address, 1863
** Ada Lovelace
The more I study the more insatiable do I feel my genius for it to be.
** Adam Protextor
 "When people call you a "snowflake" just remember they're quoting Fight Club, a satire written by a gay man about how male fragility causes men to destroy themselves, resent society, and become radicalized, and that Tyler Durden isn't the hero but a personification of the main character's mental illness, and that his "snowflake" speech is a dig at how fascists use dehumanizing language to breed loyalty from insecure people.

So basically people who say "snowflake" as an insult are quoting a domestic terrorist who blows up skyscrapers because he's insecure about how good he is in bed."
- facebook
** Alan Levinovitz
"Natural: How Faith in Nature's Goodness Leads to Harmful Fads, Unjust Laws, and Flawed Science":

And then there's the problem of my own privilege. I have never walked for miles to secure drinking water, or medicine, or books.
Machines wash my clothing and my dishes. Natural light is a wonderful thing, but for nearly a billion people with no access to power,
and billions more with only intermittent access, the prospect of unnatural light is no less wonderful.
No one has told me that my sexual orientation is unnatural, or my biology is naturally inferior.
Seen differently, praise of naturalness can look like praise of the privileges that render its downsides invisible.

** Albert Einstein
I have no special talents, I am only passionately curious.
** Alexander Dumas
One thing that humbles me deeply is to see that human genius has its limits while human stupidity does not.
** Alexander Hamilton
The truth unquestionably is, that the only path to a subversion of the republican system of the Country is, by flattering the prejudices of the people, and exciting their jealousies and apprehensions, to throw affairs into confusion, and bring on civil commotion. Tired at length of anarchy, or want of government, they may take shelter in the arms of monarchy for repose and security.

Those then, who resist a confirmation of public order, are the true Artificers of monarchy—not that this is the intention of the generality47 of them. Yet it would not be difficult to lay the finger upon some of their party who may justly be suspected. When a man unprincipled in private life desperate in his fortune, bold in his temper, possessed of considerable talents, having the advantage of military habits—despotic in his ordinary demeanour—known to have scoffed in private at the principles of liberty—when such a man is seen to mount the hobby horse of popularity—to join in the cry of danger to liberty—to take every opportunity of embarrassing the General Government & bringing it under suspicion—to flatter and fall in with all the non sense of the zealots of the day—It may justly be suspected that his object is to throw things into confusion that he may “ride the storm and direct the whirlwind.”
- [[https://founders.archives.gov/documents/Hamilton/01-12-02-0184-0002#ARHN-01-12-02-0184-0002-fn-0005][Objections and Answers respecting the Administration of the Government]]
** Alexander Stephens
Our new government is founded... upon the great turth that the negro is not equal to the white man;
that slavery subordination to the superior race is his natural and normal condition.
This, our new government, is the first, in the history of the world, based upon this great physical,
philosophical, and moral truth.
- Cornerstone speech, March 21, 1861.
** Alfred Hitchcock
Interviewer: You've given a lot of audiences shock sitting in the stalls,
you've frightened me to death with Psycho. What frightens you?
Hitchcock: Policemen.
** Ally Henny
It's funny how nooooobody talks about "Irish Slaves" until Black people start protesting for their
freedom. Then fragile people of whiteness resume their social media campaign of conflating
indentured servitude with slavery.

People will try to shout down Black folks' oppression by claiming that there were white folks who were
also oppressed, as if that somehow justifies oppression of any sort. I need y'all to get a
better narrative.

If you want to have a discussion about the injustices perpetuated against Irish immigrants, have at it.
But don't use it as a way to diminish the oppression of Black people that has spanned over 400 years
and covers five centuries of history.
** Amine Mechaal
"He's Ibn Sina, not Avicenna.
He's Ibn Rushd, not Averroes.
He's Jabir Ibn Hayyan, not Geber.

Stop Latinizing the names of Muslim scholars to conceal the fact that they were Muslims.
You don't see us calling Shakespeares 'Sheikh Zubayr'".
** Andrew Bolt
Why do elderly Australian men keep getting jail for raping young boys?
In this day and age it's as if no one dares disbelieve anyone claiming to be a victim, for fear they
may be accused of being cruel.
- Herald Sun, Feb 7, 2021.
** Andrew Jackson (Facebook nobody)
I'm not religious. But I'm here to defend Bryce. He's right.
Transgenders are disgusting, revolting freaks, and are hated by most people in society
including myself. I don't even view you as human, and wouldn't care if you were wiped off
the face of the Earth. A Man's biggest fear IS that his date turns out to be transgender...
Personally I would beat the shit out of my date if that happened.
I'm happy transgender people are assaulted and murdered, and I hope it continues to happen
with more frequency.
** Anne Herb
Libraries will get you through times of no money better than money will get you through times of no libraries.
** Anne Sexton
I am a collection of dismantled almosts.
** Annie Thebaud-Mony
They didn't encourage people to get a lead concentration, they didn't close the schools,
the Health Regional Agency didn't send any alert.
** Anon
 Self-Consciousness: "Why don't you wear your influenza mask?"
 "I'm afraid I might look funny."
 "Suppose you do. Wouldn't you rather introduce a little comedy into your household than subject it to a tragedy?"

 "We got a lot of phone calls and lettes, probably more than any other episode I can recall.
Interestingly, most of the phone calls were negative, while most of the letters were positive.
One that I always remember was a call that one of our PAs took.
A man said, 'You're ruining my kids by making them watch two women kiss like that.'
And our PA said, 'Let me ask you a question. Would you have been okay if one of the women had shot the other to death with a phaser and the kids watched that?'
And he said, 'Yes, of course'.
And the PA said, 'Well, maybe you'd better think about who it is that is ruining your kids'. "
 Quote regarding DS9 lesbian kiss.

"The legendary cellist Pablo Casals was asked why he continued to practice at age 90.
'Because I think I'm making progress' he replied."

"When you debate a person about something that affects them more than it affects you, remember
that it will take a much greater emotional toll on tem than you. For you it make feel like an
academic exercise. For them, it feels like revealing their pain only to have you dismiss their experience
and sometimes their humanity. The fact that you might remain more calm under these circumstances is a
consequence of your privilege, not increased objectivity on your part. Stay Humble."

"Weird hill to die on, but at least you're dead."

"In this school we are trauma-informed.
We connect before we correct.
We stay curious not furious.
We understand behaviour is communication.
We believe in co-regulation, that children regulate off the adults in their lives.
We think can't - not won't.
We empathise when someone is flipping their lid.
We believe in restoration - not punishment.
We believe that relationships buffer stress and build resilience.
All of us need one another, always.
Resilience means we see you, we hear you, we are with you."

"Mother, I've weight the risks which I prefer to living in a world dominated by Nazis."
- Bill, on his headstone.



"Capitalist Insanity: A Scientist prophesies that by the year 2020 the inhabitants of the world
will all be insane. Some of us are inclued to think that today the world is one huge insane asylum,
where the sane are kept in bondage by the insane."

"In 1996 racism may wear a new dress, buy a new pair of boots, but neither it nor its succubus twin
fascism is new or can make anything new. It can only reproduce the environment that supports its
own health: fear, denial and an atmosphere in which its victims have lost the will to fight.
The forces interested in fascist solutions to national problems are not to be found in
one political party or another, or in one or another wing of any single political party.
Democrats have no unsullied history of egalitarianism. Nor are liberals free of domination agendas.
Republicans have housed abolitionists and white supremacists.
Conservative, moderate, liberal; right, left, hard left, far right; religious, secular, socialist-
we must not be bliindsided by these Pepsi-Cola, Coca-Cola labels because the genius of fascism is
that any political structure can host the virus and virtually any developed country can
become a suitable home. Fascism talks ideology, but it is really just marketing -
marketing for power."

"Manifesto:
Make bad videogames
with orbs
where you can get stuck in walls
and fall through floors
that embrace the glitches and bugs
with amateurish hand draw grafix
that explore unexplored emotions
where you can pet animals
and pick flowers
and make friends
with no other goals."


"The writer, daytime insomniac.

Granted, to write is to renounce being in command of oneself or having a proper name,
and at the same time it is not to renounce, but to announce, welcoming without recognition the absent.
Or, it is to be in relation, through words in their absence, with what one cannot remember -
a withness to the unencountered, answerable not only for the void in the subject, but for the subject
as a void, it's disappearance in the imminence of a death which has already taken place,
out of place, any place at all."

"It pleases me that we may explore kindness with one another," Besarion said. "But do not mistake
my kindness for a gentle nature."

"I am not about to use literature to make this point.
Anyone who is interested can discuss it at length with actual women."

"When white folks can't defeat you they'll always find some Negro - some boot-licking, butt-licking
buck-dancing, bamboozled, half-baked, half-fried, sissified, punkified, pasteurized, homogenized nigger -
that they can trot out in front of you."

"Despite all our accomplishments we owe our existence to a six-inch layer of topsoil and the fact it rains"



"We weren't making a political statement. == We made a political statement unconsciously."


When ya find out Satan ain't the one creating evil:
"I form the light and create darkness
I make peace and create evil:
I the Lord do all these things"
- Isaiah 45:7

Whats Crazier than having an imaginary friend?
Having an Imaginary Enemy.


"Conservatism is the dread fear that somewhere, somehow, someone you think is your inferior
is being treated as your equal."

"A truly extraordinary variety of alternatives to the chemical control of insects is available.
Some are already in use and have achieved brilliant success. Others are in the stage of
laboratory testing. Still others are little more than ideas in the minds of imaginative scientsts,
waiting for the opportunity to put them to the test.
All have this in common: they are biological solutions, based on understanding of the living organisms they
seek to control, and of the whole fabric of life to which these organism belong.
Specialists representing various areas of the vast field of biology are contributing-
entomologists, pathologists, geneticists, physiologists, biochemists, ecologists-
all pouring their knowledge and their creative inspirations into the formation of a new science of biotic controls."

"It irritates me to be told how things have always been done. I defy the tyranny of precedent.
I cannot afford the luxury of a closed mind."


"We investigate the methodology used in a significant genre of experimental economics, in which experiments are designed to test theoretical models by implementing them in a laboratorry.
Using two case studies, we argue that such an experiment is a test, not of what the
model says about its target domain, but of generic theoretical components used in the model.
The properties that make a model interesting as a putative explanation of phenomena in its
target domain are not necessarily appropriate for such tests."

"The Terminator films are not really about the human race getting killed off by future machines.
They're about us losing touch with our own humanity and becoming machines, which
allows us to kill and brutalise each other.
Cops think of all non-cops as less than they are, stupid, weak and evil.
They dehumanise the people they are sworn to protect and desensitise themselves in order to
do that job."

"We are what we pretend to be, so we must be careful about what we pretend to be."

"Restoration is fear of mortality, or wanting to believe that anything that's broken can return
to how it was."

"When you choose not to vote, you allow for the worst people to decide not only your future,
but the future of everyone you love."

"All human beings are born free and equal in dignity and rights".

"You cre not compelled to form a opinion about this matter before you, nor to disturb your peace of mind at all. Things in themselves have no power to extort a verdict from you."

"Until lions have their historians, tales of the hunt shall always glorify the hunter"
- African Proverb

"The vast accumulations of knowledge - or at least of information - deposited by the ninteeth century have been responsible for an equally vast ignorance.
When there is so much to be known, when there are so many fields of knowledge in which the same words
are used with different meanings, when every one knows a little about a great many things,
it becomes increasibly difficult for anyone to know whether he knows what he is talking about or not.
And when we do not know, or when we do not know enough, we tend always to substitute emotions for thoughts."

I think we like to complicate things when it is really quite simple;
find what it is that makes you happy and who it is that makes you happy and you're set.
promise.


Go to work, send your kids to school,
follow fashion, act normal,
walk on the pavement, watch TV.
Save for your old age, obey the law
Repeat after me: I am Free.


1) Never open a book with the weather.
2) Avoid Prologues
3) Never use a verb other than "said" to carry dialogue
4) Never use an adverb to modify the verb "said"
5) Keep your exclamation points under control.
6) Never use the words "suddenly" or "all hell broke loose"
7) Use dialect sparingly
8) Avoid Detailed descriptions of characters
9) Same for places and things
10) leave out the parts readers tend to skip


When nonviolence is preached as an attempt to evade the repercussions of political brutality, it betrays itself. When nonviolence begins halfway through the war with the aggressor calling time out, it
exposes itself as a ruse.
When nonviolence is preached by the representatives of the state, while the state doles out
heaps of violence to its citizens, it reveals itself to be a con.
And none of this can mean that rioting or violence is "correct" or "wise", any more than a forest
fire can be "correct" or "wise".
Wisdom isn't the point tonight. Disrespect is.
In this case, disrespect for the hollow law and failed order that so regularly disrespects the rioters
themselves.


 It’s not about giving the guests what you think they want. That’s simple. The guests don’t return for the obvious things we do, the garish things. They come back because of the subtleties, the details. They come back because they discover something they imagine no one had ever noticed before. Something they have fallen in love with. They’re not looking for a story that tells them who they are. They already know who they are. They’re here because they want a glimpse of who they could be.”
 - [[https://www.kotaku.com.au/2016/10/the-video-game-horror-of-hbos-westworld/][Westworld]]

 Theory is when you know everything but nothing works.
 Practice is when everything works but no one knows why.
 In our lab, theory and practice are combined: nothing works and nobody knows why.

 Never make fun of someone if they mispronounce a word. It means they learned it by reading.


 Being process-oriented, not product driven, is the most important and difficult skill for
 a designer to develop.
 Being process-oriented means:
 1) seeking to understand a design problem before chasing after solutions;
 2) not force-fitting solutions to old problems onto new problems
 3) removing yourself from prideful investment in your projects and being slow to fall in
    love with your ideas
 4) making design investigations and decisions holistically (that address several aspects of a
    design problem at once) rather than sequentially (that finalize one aspect of a solution
    before investigating the next)
 5) making design decisions conditionally - that is, with the awareness that they may
    or may not work out as you continue toward a final solution
 6) knowing when to change and when to stick with previous decisions
 7) accepting as normal the anxiety that comes from not knowing what to do
 8) working fluidly between concept-scale and detail-scale to see how each informs the other
 9) always asking "What if...?" regardless of how satisfied you are with your solution.


Jewish Recipe for Apple Pie
First, fry up some onions and garlic so the kitchen smells like you're cooking
** Anthony Bourdain
“Once you’ve been to Cambodia, you’ll never stop wanting to beat Henry Kissinger to death with your bare hands. You will never again be able to open a newspaper and read about that treacherous, prevaricating, murderous scumbag sitting down for a nice chat with Charlie Rose or attending some black-tie affair for a new glossy magazine without choking. Witness what Henry did in Cambodia – the fruits of his genius for statesmanship – and you will never understand why he’s not sitting in the dock at The Hague next to Milošević.”
- The Cook's Tour: Global Adventures in Extreme Cuisines


“If I'm an advocate for anything, it's to move. As far as you can, as much as you can. Across the ocean, or simply across the river. The extent to which you can walk in someone else's shoes or at least eat their food, it's a plus for everybody.

Open your mind, get up off the couch, move.”

** Anthony Robbins
"Who have you decided to become? Make this decision consciously. Make it carefully. Make it powerfully"
- Outstanding People of the World
** Antonio Gramsci
The crisis consists precisely in the fact that the old is dying and the new cannot be born;
in this interregnum a great variety of morbid symptoms appear.
** Anython Ewer
No matter how grouchy you're feeling,
You'll find the smile more or less healing.
It grows in a wreath
All around the front teeth
Thus preserving the face from congealing.
** April Rosenblum
Partly it’s that it allows Jews success. Many oppressions rely on keeping a targeted group of people poor, uneducated, designated non-white, or otherwise 'at the
the “middleman” - Rulers used Jews for “mid- dlemen” jobs that put Jews in direct contact with the
the Court Jew - History is full of unpopular kings who managed to save
bottom.’ Anti-Jewish oppression doesn’t depend on that. Although at many times it has kept Jews in poverty or designated non-white, these have been “optional” features. Because the point of anti-Jewish oppression is to keep a Jewish face in front, so that Jews, instead of ruling classes, become the target for peoples’ rage, it works even more smoothly when Jews are allowed some success, and can be perceived as the ones “in charge” by other oppressed groups.

I'ts absolutely possible to critique Israel without being antisemitic - but it's not automatic.
you keep things clear when you describe accurately and speicifcally what you oppose,
and critique actions and policy as unjust - not people or nations as evil.

- [[https://www.aprilrosenblum.com/thepast][The Past Didn't Go Anywhere]]
** Arthur C. Clarke
The goal of the future is full unemployment, so we can play.
That's why we have to destroy the present politico-economic system.

** Barry Goldwater
“Mark my word, if and when these preachers get control of the [Republican] party, and they're sure trying to do so, it's going to be a terrible damn problem. Frankly, these people frighten me. Politics and governing demand compromise. But these Christians believe they are acting in the name of God, so they can't and won't compromise. I know, I've tried to deal with them.”
** Bertrand Russell
"Everything is vague to a degree you do not realize till you have tried to make it precise."
** Bessel van der Kolk
Beneath the surface of the protective parts of trauma survivors there exists an
undamaged essence, a self that is confident, curious, and calm, a self that has
been sheltered from destruction by the various protectors that have emerged in their efforts to ensure survival.
Once those protectors trust that it is safe to separate, the self will spontaneously emerge,
and the parts can be enlisted in the healing process.
** Bruno Latour
 'To exist is to differ; difference, in one sense, is the substantial side of things, what they have most in common and what makes them most different. One has to start from this difference and to abstain from trying to explain it, especially by starting with identity, as so many persons wrongly do. Because identity is a minimum and, hence, a type of difference, and a very rare type at that, in the same way as rest is a type of movement and the circle a type of ellipse. To begin with some primordial identity implies at the origin a prodigiously unlikely singularity, or else the obscure mystery of one simple being then dividing for no special reason.' (idem p. 73).
** C.S. Lewis
If we let ourselves, we shall always be waiting for some distraction or other to end before we can really get down to our work. The only people who achieve much are those who want knowledge so badly that they seek it while the conditions are still unfavorable. Favorable conditions never come.”
- Learning in War-Time.
** Carl Sagan
"We've arranged a global civilization in which most crucial elements profoundly depend on science and technology.
We have also arranged things so that almost no one understands science and technology.
This is a prescription for disaster. We might get away with it for a while, but sooner or later this
combustible mixture of ignorance and power is going to blow up in our faces."
** Charles Darwin
One day, tearing off some old bark, I saw two rare beetles and seized one in each hand;
then I saw a third and new kind, which I could not bear to lose, so that I popped the one
which I held in my right hand into my mouth.
Alas it ejected some intensely acrid fluid, which burnt my tongue so that I was
forced to spit the beetle out, which was lost, as well as the third one.
** Charles Dickens
 "No one is useless in this world who lightens the burden of another"
** Charles Eliot
What is the plural of rhinoceros? Well, Liddell and Scott seem to authorize "rhinocerotes", which is
pedantic, but "rhinoceroses" is not euphonious.
- The East Africa Protectorate. 1905
** Chien-Shiung Wu
It is shameful that there are so few women in science in China.
There are many many women in physics.
There is a misconception in America that women scientists are all dowdy spinsters.
This is the fault of men.
In Chinese society, a woman is valued for what she is, and men encourage her to accomplishments
yet she remains eternally feminine.
** Chomsky
The effect of the concentration of wealth is to yield concentration of power.

** Christopher Walker
People who think we need "Straight Pride Parades" or a "White Hitory Month" are kinda like people
who look at handicapped parking spaces and say "Why don't I get something like that, huh?"
They don't care why it exists,
They don't care that they get the whole parking lot,
They're just mad that there's 4 spaces in front of the walmart that aren't just for them.
** Clarence Darrow
I have never killed any one, but I have read some obituary notices with great satisfaction.
** Clement Attlee
"Charity is a cold grey loveless thing.
If a rich man wants to help the poor, he should pay his taxes gladly, not dole out money at a whim."
** Cliff Bleszinski
Nice young guy asks me if we have controller support and I immediately go into my pre canned
response that we are PC first and that keyboard mouse are pretty easy to learn
at which point he holds up his lack of a hand and shrugs.
** Coco Chanel
The most couragous act is still to think for yourself, aloud.
** Count Dooku
"It is an honor to stand before you, for you represent the freedom and the future of our galaxy. The once-great Republic and Jedi Order have become victims of their own ambitions, and the Supreme Chancellor is no more than a pawn of corporate monopolies. As a people you called out for change, you called out for leadership, and I humbly answered that call. Together we challenged the system. We asked for equality. And how were we met? With war! The Jedi secret army of clones was revealed, and their treachery was far greater than we could have imagined! Countless living beings—these clones the Jedi created—have been sent to their deaths, while we sacrifice mainly droids. Our soldiers of flesh and blood are willing participants! They are your fathers and sons, mothers and daughters, who fight not because they were grown and designed to do so, but because they know in their hearts that they are fighting for a just and noble cause!"

The jedi order's problem is Yoda. No being can wield that kind of power for centuries without
becoming complacent at best or corrupt at worst. He has no idea that it's overtaken him;
he no longer sees all the little cumulative evils that the Republic tolerates and fosters,
from slavery to endless wars, and he never asks, "Why are we not acting to stop this?"
Live alongside corruption for too long, and you no longer notice the stench.
The Jedi cannot help the slaves of Tatooine, but they can help the slavemasters.
** David Cameron
For too long, we have been a passively tolerant society, saying to our citizens:
As long as you obey the law, we will leave you alone.
** David Dunning
An ignorant mind is precisely not a spotless, empty vessel, but one that's filled with the clutter of
irrelevant or misleading life experiences, theories, facts, intuitions, strategies,
algorithms, heuristics, metaphors and hunches that regrettably have the look and feel of
useful and accurate knowledge.
** David Evans
Prior to the Pell Grant, the aid went to institutions to give to students.
With the Pell Grant, the dynamic changed.

** David Sedaris
"To put them in perspective, I think of being on an airplane.
The flight attendant comes down the aisle with her food cart and,
eventually, parks it beside my seat.
'Can I interest you in the chicken?' She Asks. 'Or would you prefer the
platter of shit with bits of broken glass in it?'

To be undecided in this election is to pause for a moment and then ask how the chicken is cooked."
** Deb Chachra
Any Sufficiently advanced neglect is indistinguishable from malice.
** Dietrich Bonhoeffer
Silence in the face of evil is evil itself.
God will not hold us guiltless.
Not to Speak is to Speak.
Not to Act is to Act.
** Dinesh D'souza
The stakes could not be higher - we're talking about the fate of the greatest nation on Earth.
Who are the real fascists?
Who are the real racists?
We must learn the Truth.
- Death of a Nation
** Doris Lessing
Ideally, what should be said to every child, repeatedly, throughout his or her school life is something like this:

'You are in the process of being indoctrinated. We have not yet evolved a system of education that is not a system of indoctrination. We are sorry, but it is the best we can do. What you are being taught here is an amalgam of current prejudice and the choices of this particular culture. The slightest look at history will show how impermanent these must be. You are being taught by people who have been able to accommodate themselves to a regime of thought laid down by their predecessors. It is a self-perpetuating system. Those of you who are more robust and individual than others will be encouraged to leave and find ways of educating yourself — educating your own judgements. Those that stay must remember, always, and all the time, that they are being moulded and patterned to fit into the narrow and particular needs of this particular society.
** Douglas Adams
'The point is, you see,' said Ford, 'that there is no point driving yourself mad trying to stop
yourself going mad. You might as well give in and save your sanity for later'.
'And this is you sane again, is it?' asked Arthur. 'I ask merely for information.'

'Listen Bud', said Ford, 'if I had One Altairian dollar for every time I heard one bit of the
Universe look at another bit of the Universe and say "That's Terrible" I wouldn't be sitting here
like a lemon looking for a gin. But I haven't and I am. Anyway, what are you looking so placid
and moon-eyed for? Are you in love?'

** Dr Seuss
A Person is a person no matter how small.
** Dr Zakir Naik
Every muslim is allowed to have sex with his female slave. If he does not have female slave and
wife is not at home then he must release his lust with sheep or goat.
** Dran
We didn't set anything up knowing that at any point with no warning NPCs would materialize and blow everything up.
NPCs don't sleep, they don't get tired, they don't have to wake people up or take off work to show up for a timer.
- [[https://www.pcgamer.com/uk/eve-online-is-in-chaos-after-an-unprecedented-alien-invasion/][Eve online alien invasion]]
** Edward Abbey
Growth for the sake of growth is the ideology of the cancer cell.

** Egon Bittner
"In recent years a good deal of the very best sociological work has been devoted to the study of organization. Although the term, organization, belongs to the category of expressions about which there is maintained an air of informed vagueness, certain special conventions exist that focus its use, with qualifications, on a delimited set of phenomena. In accordance with these conventions, the term applies correctly to stable associations of persons engaged in concerted activities directed to the attainment of specific objectives. It is thought to be a decisive characteristic of such organizations that they are deliberately instituted relative to these objectives. Because organizations, in this sense, are implementing and implemented programs of action that involve a substantial dose of comprehensive and rational planning, they are identified as instances of formal or rational organization in order to differentiate them from other forms."
- The Concept of Organization

** Elanor Crumblehulme
Cutting libraries in a recession is like cutting hospitals in a plague.
** Elisabeth Kubler-Ross
The ultimate lessons is learning how to love and be loved unconditionally.
** Elle Maruska
The Places We Go When We Leave

There are worls upon worls all blooming with wonder
& numberless doorways between
& when we are done with mere skin & bone
we become travelers of shadow & dreamswe do not need form, nor breath, eyes or claws
to hunt through the brilliance & gleam
& all pain fades away, all fear falls to gray
when we go where we go when we leave
but memory persists & love still exists
& we wait close & we watch as you grieve
for we know that you can't know the places we go
when our bodies fall finally to sleep
but don't hurt for us long, nor imagine us gone
though we've slipped into beauty unseen:
we're waiting right here for when you finally appear
& we can both go where we go when we leave.
** Elon Musk
Marx was a capitalist. He even wrote a book about it.
** Emma Thompson
I think books are like people in the sense that they'll turn up in your life when you most need them.

** Eric Lafforgue
In the Mahalah Flower Men Market, an old man wears traditional shoes made of palm leaves.
Things started to change with their construction of a cable car track in the 1990's that allowed access
to the remote villages of the Flower Men. But traditions remain strong with the elders.
** Facebook
As we've said many times, the documents Six4Three gathered for their baseless case are only part
of the story and are presented in a way that is very misleading without additional context.
We stand by the platform changes we made in 2015 to stop a person from sharing their
friends' data with developers.
Like any business, we had many of internal conversations about the various ways we could build a
sustainable business model for our platform.
But the facts are clear: We've never sold people's data.
** Fleur Adcock
There are worse things than having behaved foolishly in public.
There are worse things than these miniature betrayals, committed or endured or suspected;
there are worse things than not being able to sleep for thinking about them.
It is 5am. All the worse things come staking in and stand icily about the bed looking worse and
worse and worse.
** Frank Lantz
Making games combines everything that's hard about building a bridge with everything that's hard
about composing an opera. Games are operas made out of bridges.
- Hearts and Minds, GDC 2014.
** Frank Zappa
Republicans stand for Raw, Unbridled Evil and Greed and Ignorance smothered in balloons and ribbons.

** Frantz Fanon
“Sometimes people hold a core belief that is very strong. When they are
presented with evidence that works against that belief, the new
evidence cannot be accepted. It would create a feeling that is
extremely uncomfortable, called cognitive dissonance. And because it
is so important to protect the core belief, they will rationalize,
ignore and even deny anything that doesn't fit in with the core belief.”
- Black Skin, White Masks.
** Fred Hampton
I'm not going to die on no airplane.
I'm not going to die slipping on no ice.
I'm going to die for the people because
I'm going to live for the people.
I'm going to live for the people
because I love the people.
** Fred Rogers
Love isn't a state of perfect caring. It is an active noun like struggle.
To love someone is to strive to accept that person exactly the way he or she is, right here and now.

We deal with such things as - as inner drama of childhood. We don't have to bop somebody over the head to make drama on the screen.
We deal with such things as getting a haircut, or the feelings about brothers and sisters,
and the kind of anger that arises in simple family situations.
** Frederick Douglass
“I assert most unhesitatingly, that the religion of the south is a mere covering for the most horrid crimes, - a justifier of the most appalling barbarity, - a sanctifier of the most hateful frauds, - and a dark shelter under, which the darkest, foulest, grossest, and most infernal deeds of the slaveholders find the strongest protection. Were I to be again reduced to the chains of slavery, next to enslavement, I should regard being the slave of a religious master the greatest calamity that could befall me. For of all slaveholders with whom I have ever met, religious slaveholders are the worst. I have ever found them the meanest and basest, the most cruel and cowardly, of all others.”

 “I love the pure, peaceable, and impartial Christianity of Christ; I therefore hatethe corrupt, slaveholding, women-whipping, cradle-plundering, partial, and hypocritical Christianity of this land. Indeed, I can see no reason, but the most deceitful one, for calling the religion of this land Christianity. I look upon it as the climax of all misnomers, the boldest of all frauds, and the grossest of all libels.”
** George Monbiot
If wealth was the inevitable result of hard work and enterprise, every woman in Africa would be
a millionaire.
** George Orwell
But if thought corrupts langugage, language can also corrupt thought.
"... putting them together again in new shapes of your own choosing."

"Until they become conscious they will never rebel,
and until after they have rebelled they cannot become conscious."
- 1984

** George W. Bush
People are poor because they are lazy.
** Glinner
If your civil rights movement opposes data and peer reviewed science, it's not a civil rights movement,
it's a cult.

** Goodhart
when a metric becomes a target to be optimized, it risks no longer being a useful metric

** Gore Vidal
There is only one party in the United States, the Property Party ... and it has two right wings: Republican and Democrat. Republicans are a bit stupider, more rigid, more doctrinaire in their laissez-faire capitalism than the Democrats, who are cuter, prettier, a bit more corrupt – until recently ... and more willing than the Republicans to make small adjustments when the poor, the black, the anti-imperialists get out of hand. But, essentially, there is no difference between the two parties.
- [[https://archive.org/details/mattersoffactoff00vida/page/265][Archive.org Matters of Fact and Fiction]]
** H. L. Mencken
The trouble with fighting for human freedom is that one spends most of one's time defending
scoundrels. For it is against scoundrels that oppressive laws are first aimed, and
oppression must be stopped at the beginning if it is to be stopped at all.
** Hannah Arendt
"You ask about the effect my work has on others.
If I may speak ironicaly, that's a masculine question.
Men always want to be influential.
Do I see myself as influential?
No, I want to understand."

"The ideal subject of totalitarian rule is not the convinced Nazi or the dedicated communist,
but people for whom the distinction between fact and fiction, true and false, no longer exists."

 “The trouble with Eichmann was precisely that so many were like him, and that the many were neither perverted nor sadistic, that they were, and still are, terribly and terrifyingly normal. From the viewpoint of our legal institutions and of our moral standards of judgment, this normality was much more terrifying than all the atrocities put together.”
** Harry Leslie Smith
Austerity, along with politics of fear, is being used in this country like an economic martial law.
It has kept ordinary citizens in line because they are fearful of losing their jobs, being unable to make their rent,
their credit card or mortgage payments.
** Henry A. Wallace
A Fascist is one who lust for money or power is combined with such an intensity of intolerance toward
those of other races, parties, classes, religions, cultures, regions or nations as to make him
ruthless in his use of deceit or violence to attain his ends.
- American Fascism, NYT, 1944
** Henry David Thoreau
"Disobedience is the true foundation of liberty. The obedient must be slaves"
** Henry Kissinger
The emigration of Jews from the Soviet Union is not an objective of American foreign policy.
And if they put Jews into gas chambers in the Soviet Union, it is not an American concern.
Maybe a humanitarian concern.

** Herophilus of Calcedone
When health is absent, wisdom cannot reveal itself,
art cannot become manifest, strength cannot fight,
wealth becomes useless, and intelligence cannot be applied.

** Hitler
In this they proceeded on the sound principle that the magnitude of a lie always contains a certain factor of credibility, since the great masses of the people in the very bottom of their hearts tend to be corrupted rather than consciously and purposely evil, and that, therefore, in view of the primitive simplicity of their minds they more easily fall a victim to a big lie than to a little one, since they themselves lie in little things, but would be ashamed of lies that were too big. Such a falsehood will never enter their heads and they will not be able to believe in the possibility of such monstrous effrontery and infamous misrepresentation in others; yes, even when enlightened on the subject, they will long doubt and waver, and continue to accept at least one of these causes as true. Therefore, something of even the most insolent lie will always remain and stick – a fact which all the great lie-virtuosi and lying-clubs in this world know only too well and also make the most treacherous use of.
- Mein Kampf
** Howard Zinn
“Civil disobedience is not our problem. Our problem is civil obedience. Our problem is that people all over the world have obeyed the dictates of leaders…and millions have been killed because of this obedience…Our problem is that people are obedient allover the world in the face of poverty and starvation and stupidity, and war, and cruelty. Our problem is that people are obedient while the jails are full of petty thieves… (and) the grand thieves are running the country. That’s our problem.”
- [[https://www.howardzinn.org/state-of-nature-zinn-civil-disobedience/][Zinn on Civil Disobedience]]
** Iain Banks
"I'm not arguing there are no decent people in the Tory Party, but they're like bits of sweetcorn in a turd;
technically they've kept their integrity, but they're still embedded in shit."
** Ira Glass
 “Nobody tells this to people who are beginners, I wish someone told me. All of us who do creative work, we get into it because we have good taste. But there is this gap. For the first couple years you make stuff, it’s just not that good. It’s trying to be good, it has potential, but it’s not. But your taste, the thing that got you into the game, is still killer. And your taste is why your work disappoints you. A lot of people never get past this phase, they quit. Most people I know who do interesting, creative work went through years of this. We know our work doesn’t have this special thing that we want it to have. We all go through this. And if you are just starting out or you are still in this phase, you gotta know its normal and the most important thing you can do is do a lot of work. Put yourself on a deadline so that every week you will finish one story. It is only by going through a volume of work that you will close that gap, and your work will be as good as your ambitions. And I took longer to figure out how to do this than anyone I’ve ever met. It’s gonna take awhile. It’s normal to take awhile. You’ve just gotta fight your way through.”
** James Henry Hammond
In all social systems there must be a class to do the menial duties, to perform the drudgery of life. That is, a class requiring but a low order of intellect and but little skill. Its requisites are vigor, docility, fidelity. Such a class you must have, or you would not have that other class which leads progress, civilization, and refinement. It constitutes the very mud-sill of society and of political government; and you might as well attempt to build a house in the air, as to build either the one or the other, except on this mud-sill. Fortunately for the South, she found a race adapted to that purpose to her hand. A race inferior to her own, but eminently qualified in temper, in vigor, in docility, in capacity to stand the climate, to answer all her purposes. We use them for our purpose, and call them slaves. We found them slaves by the common "consent of mankind," which, according to Cicero, "lex naturae est." The highest proof of what is Nature's law. We are old-fashioned at the South yet; slave is a word discarded now by "ears polite;" I will not characterize that class at the North by that term; but you have it; it is there; it is everywhere; it is eternal.

The Senator from New York said yesterday that the whole world had abolished slavery. Aye, the name, but not the thing; all the powers of the earth cannot abolish that. God only can do it when he repeals the fiat, "the poor ye always have with you;" for the man who lives by daily labor, and scarcely lives at that, and who has to put out his labor in the market, and take the best he can get for it; in short, your whole hireling class of manual laborers and "operatives," as you call them, are essentially slaves. The difference between us is, that our slaves are hired for life and well compensated; there is no starvation, no begging, no want of employment among our people, and not too much employment either. Yours are hired by the day, not cared for, and scantily compensated, which may be proved in the most painful manner, at any hour in any street in any of your large towns. Why, you meet more beggars in one day, in any single street of the city of New York, than you would meet in a lifetime in the whole South. We do not think that whites should be slaves either by law or necessity. Our slaves are black, of another and inferior race. The status in which we have placed them is an elevation. They are elevated from the condition in which God first created them, by being made our slaves. None of that race on the whole face of the globe can be compared with the slaves of the South. They are happy, content, unaspiring, and utterly incapable, from intellectual weakness, ever to give us any trouble by their aspirations. Yours are white, of your own race; you are brothers of one blood. They are your equals in natural endowment of intellect, and they feel galled by their degradation. Our slaves do not vote. We give them no political power. Yours do vote, and, being the majority, they are the depositories of all your political power. If they knew the tremendous secret, that the ballot-box is stronger than "an army with banners," and could combine, where would you be? Your society would be reconstructed, your government overthrown, your property divided, not as they have mistakenly attempted to initiate such proceedings by meeting in parks, with arms in their hands, but by the quiet process of the ballot-box. You have been making war upon us to our very hearthstones. How would you like for us to send lecturers and agitators North, to teach these people this, to aid in combining, and to lead them?
- Speech to the US Senate, March 4, 1858.
** James Tiptree Jr
Being, I imagine, must be very simple.
It is Becoming which is so messy and which I am all for.
** Jason Nelson
Protesters don't block traffic to gain your support. They do it so you can see what it feels
like to be stuck in a powerless situation.
How do you respond to this situation?
Are you calm and peaceful?
Do you want to spend years organizing political talks about it?
Nope, you want to run those protesters over, kill them, kill them all.
If you want to kill protesters who have you stuck in traffic, imagine what you would want to do
to a system that patrols, harasses and kills you.
The sooner you learn perspective the sooner you won't have to be stuck in traffic.
** JFK
What do our opponents mean when they apply to us the label, "Liberal"? If by "Liberal" they mean, as they want people to believe, someone who is soft in his policies abroad, who is against local government, and who is unconcerned with the taxpayer's dollar, then the record of this party and its members demonstrate that we are not that kind of "Liberal." But, if by a "Liberal," they mean someone who looks ahead and not behind, someone who welcomes new ideas without rigid reactions, someone who cares about the welfare of the people - their health, their housing, their schools, their jobs, their civil rights, and their civil liberties - someone who believes that we can break through the stalemate and suspicions that grip us in our policies abroad, if that is what they mean by a "Liberal," then I'm proud to say that I'm a "Liberal."
- [[https://www.jfklibrary.org/archives/other-resources/john-f-kennedy-speeches/liberal-party-nomination-nyc-19600914][Accepting the Liberal Party Nomination for President, New York, New York, September 14, 1960]]

Our country can't afford to continue losing our best and brightest to gun violence.
** Jim Jarmusch
“Nothing is original. Steal from anywhere that resonates with inspiration or fuels your imagination. Devour old films, new films, music, books, paintings, photographs, poems, dreams, random conversations, architecture, bridges, street signs, trees, clouds, bodies of water, light and shadows. Select only things to steal from that speak directly to your soul. If you do this, your work (and theft) will be authentic. Authenticity is invaluable; originality is non-existent. And don’t bother concealing your thievery - celebrate it if you feel like it. In any case, always remember what Jean-Luc Godard said: “It’s not where you take things from - it’s where you take them to."
** Joe Wintergreen
Randomly started thinking about AI and started making a system where like, each type of action
(take cover/flank/shoot target/throw grenade/wander/move to target) is kept in an object with a
CanExecute function (which returns wheter i'ts a good idea to do that thing right now or not)
and then on tick the ai goes through a list of actions and executes the first one that CanExecute.
So theoretically you can have like, a Combat row on a data table that has a list of objects with the thing you
really want the AI to do at the top and fallbacks under that like this.
** John Allen Paulos
It's harder to be a politican than it is to be a scientist, and less fun.
In science, you have to suspend belief, and it has to be shown to you, whereas
politicans have to always be certain.
The problem is that most things aren't very certain, and that's not a way to inspire voters,
to say, 'maybe'.
** John Brown
I believe to have interfered as I have done... on behalf of His despised poor, was not wrong,
but right. Now, if it be deemed necesssary that I should forfeit my life for the
furtherance of the ends of justice, and mingle my blood further with the blood of my children,
and with the blood of millions in this slave country whose rights are disregarded by wicked, cruel and unjust
enactments, I submit: so leet it be done.
** John G. Self
Authenticity is important. If you are authentic it means you are staying true to who you are,
what you do and to those you serve.
** John Green
Let me explain why I like to pay taxes for schools even though I don't personally have a kid
in school:
I don't like living in a country with a bunch of stupid people.
** John Tanton
I've come to the point of view that for European-American society and culture to persist
requires a European-American majority, and a clear one at that.
** Jon Stewart
I think I'm beginning to get it.
If it's a policy that benefits the rich, it doesn't have to be paid for, should
last forever and is good for America.
But if it benefits the poor, we can't afford it, we should end it as soon as possible
and it will destroy our nation from within.

** Jonathan Foster
If someone says it's raining & another person says it's dry, it's not your job to quote them both.
Your job is to look out the fucking window and find out which is true.

** Joseph Goebbels
A lie told once remains a lie but a lie told a thousand times becomes the truth.
** Julia Roberts
Women, you are not rehabilitation centers for badly raised men.
It is not your job to fix him, change him, parent him or raise him.
You want a partner not a project.
** K. Gibran
They deem me mad because I will not sell my days for gold and I deem them mad because they think my days have a price.
** Kate Lister
The idea of sexual shame shifts all over the world, which is refreshing for us because that
shame is not set in stone.
These ideas are movable.
They change and they shift.
Even if they are lurching backwards now for certain reproductive rights, they will move forward
again.
This is in spite of a certain orange spunk trumpet in Washington.

** Katherine Jjohnson
Girls are capable of doing everything men are capable of doing.
Sometimes they have more imagination than men.
** Kim Stanley Robinson
Thats libertarians for you - anarchists who want police protection from their slaves.
- Green Mars.
** Kofi Annan
We need to regulate drugs because they are risky.
Drugs are infinitely more dangerous when produced and sold by criminals who do not worry about any safety measures.
Legal regulation protects health.
** Kumail Nanjiani
He's just so stupid.

He's so breathtakingly stupid that the above statement is all it takes for every person reading this
to know exactly who I'm talking about.
** Kwame Ture
 "The job of a revolutionary is, of course, to overthorw unjust systems and replace them with just systems
because a revolutionary understands this can only be done by the masses of the people."

"In order for non-violence to work, your opponent must have a conscience.
The United states has none, has none."

“If a white man wants to lynch me, that's his problem. If he's got the power to lynch me, that's my problem. Racism is not a question of attitude; it's a question of power. Racism gets its power from capitalism. Thus, if you're anti-racist, whether you know it or not, you must be anti-capitalist. The power for racism, the power for sexism, comes from capitalism, not an attitude.”


“This country is a nation of thieves. It stole everything it has, beginning with black people. The U.S. cannot justify its existence as the policeman of the world any longer. I do not want to be a part of the American pie. The American pie means raping South Africa, beating Vietnam, beating South America, raping the Philippines, raping every country you’ve been in. I don’t want any of your blood money. I don’t want to be part of that system. We must question whether or not we want this country to continue being the wealthiest country in the world at the price of raping everybody else.”
** Langston Hughes
Misery is when the teacher asked you who was the Father of our Country and you said
'Booker T. Washington.'

Misery is when you heard on the radio that the neighborhood you live in is a slum but
you always thought it was home.

Misery is when your pals see Harry Belafonte walking down the street and they holler,
"Look, there's Sidney Poitier".

Misery is when your white teacher tells the class that all Negroes can sing and you
can't even carry a tune.

** Lee Atwater
Atwater: Y'all don't quote me on this. You start out in 1954 by saying, "Nigger, nigger, nigger". By 1968 you can't say "nigger"—that hurts you. Backfires. So you say stuff like forced busing, states' rights and all that stuff. You're getting so abstract now [that] you're talking about cutting taxes, and all these things you're talking about are totally economic things and a byproduct of them is [that] blacks get hurt worse than whites. And subconsciously maybe that is part of it. I'm not saying that. But I'm saying that if it is getting that abstract, and that coded, that we are doing away with the racial problem one way or the other. You follow me—because obviously sitting around saying, "We want to cut this", is much more abstract than even the busing thing, and a hell of a lot more abstract than "Nigger, nigger". So, any way you look at it, race is coming on the back-burner.
- [[https://www.thenation.com/article/archive/exclusive-lee-atwaters-infamous-1981-interview-southern-strategy/][Southern Strategy interview]]

** Lesley Lokko
"My decision to leave Spitzer after less than a year is fairly straightforward: I was not able to build enough support to be able to deliver on either my promise of change, or my vision of it. The reasons why are more complex. Part of it has to do with COVID-19 and the rapid lockdown, which occurred after only three months in post. It's hard enough to build social capital in a new place without having to do it over Zoom. Part of it too has to do with the wider inflexibility of U.S. academic structures. In an incredibly bureaucratic and highly-regulated context, change is as much administrative as it is conceptual. The lack of meaningful support—not lip service, of which there's always a surfeit—meant my workload was absolutely crippling. No job is worth one's life and at times I genuinely feared for my own. Race is never far from the surface of any situation in the U.S. Having come directly from South Africa, I wasn't prepared for the way it manifests in the U.S. and quite simply, I lacked the tools to both process and deflect it. The lack of respect and empathy for Black people, especially Black women, caught me off guard, although it's by no means unique to Spitzer. I suppose I'd say in the end that my resignation was a profound act of self-preservation."
** Linda B. Buck
As a woman in science, I sincerely hope that my receiving a Nobel Prize will send a message to
young women everywhere that the doors are open to them and that they should follow their dreams.
** Lucy Parsons
Never be decieved that the rich will allow you to vote away their wealth.
** Lyndon B. Johnson
If you can convince the lowest white man he's better than the best colored man,
he won't notice you're picking his pocket. Hell, give him somebody to look down on and
he'll empty his pockets for you.
** Malcolm X
."We, the Black masses, don't want these leaders who seek our support coming to us representing a certain political party. They must come to us today as Black Leaders representing the welfare of Black people. We won't follow any leader today who comes on the basis of political party. Both parties (Democrat and Republican) are controlled by the same people who have abused our rights, and who have deceived us with false promises every time an election rolls around."
- [[https://malcolm-x.org/quotes.htm][Malcolm X Quotes]]
** Mallory Ortberg
Q: Hate the house rules: What are your thoughts on people who have “house rules” for commonly played board or card games? My in-laws have some for Gin Rummy that are terribly irritating, and people all seem to have their own rules for Monopoly. Am I allowed to insist on the real rules being played at my own house? I hate to be a stickler, but who just makes up rules for board games?

A: All rules for board games are made up. All games were, at some point, made up; there is no natural, immutable way to play Gin Rummy. The original rules of Monopoly only exist because someone in the early 1900s wanted to explain the tax theories of Henry George via a board game; there is no objective version of Monopoly. Moreover, the worst sort of argument one can have with relatives is one where the stakes are low but the sense of grievance is high. You will likely never convince your in-laws that their game rules are irritating, no matter how passionately you argue your case. Cheerfully embrace your in-laws’ ridiculous house rules (or politely decline to play and read a book instead), and feel free to make up your own rules at home, although if you find yourself at a point where every time you play a game you have to insist that everyone else follow “the real rules,” you might want to do something besides play board games with your guests. (There are no real rules. There are no real games, only endless variations on an arbitrary theme. Embrace chaos.)
- [[https://slate.com/human-interest/2017/02/dear-prudence-my-boss-didnt-give-me-the-raise-he-promised.html][Dear Prudence Interview]]

** Marcus Aurelius
Live a good life.
If there are gods and they are just, then they will not care how devout you have been,
but will welcome you based on the virtues you have lived by.
If there are gods, but unjust, then tyou should not want to worship them.
If there are no gods, then you will be gone, but will have lived a noble life that will live on in the memories of your loved ones.

** Margaret Chase Smith
I don't want to see the Republican Party ride to political victory on the Four Horsemen of Calumny
-- Fear, Ignorance, Bigotry and Smear.

As an American, I condemn a Republican "Fascist" just as much I condemn a Democratic "Communist".
They are equally dangerous to you and me and to our country.
As an American, I want to see our nation recapture the strength and unity it once had when we fought
the enemy instead of ourselves.
** Marie Curie
I am among those who think that science has great beauty.
** Marissa Mayer
People ask me all the time "What is it like to be a woman at Google?"
I'm not a women at Google; I'm a Geek at Google.
And beeing a geek is just great.

** Mark Twain
If voting made any difference They wouldn't let us do it.
** Marshall McLuhan
New technological environments are commonly cast in the molds of the
preceding technology out of the sheer unawareness of their designers.


The older, traidtional ideas of private, isolated thoughts and actions -
the patterns of mechanistic technologies -
are very seriously threatened by new methods of instantaneous electric information
retrieval, by the electrically computerized dossier -
that one big gossip column that is unforgiving, unforgetful and from which
there is no redemption, no erasure of early mistakes.
** Martin Baron
This special section is dedicated to them and to their families and friends.
Our purpose is to ensure that none of us forgets what all of us, as a nation, have lost.
- Execustive editor of the washington post.

** Martin Luther King
"Power without love is reckless and abusive, and love without power is sentimental and anemic.
Power at its best is love implementing the demands of justice, and justice at its best is
power correcting everything that stands against love."

The time is always right to do what is right.

I have almost reached the regrettable conclusion that the Negro's great stumbling block in his
stride toward freedom is not the Ku Klux Klanner, but the white moderate, who is more
devoted to 'order' than to justice.
** Martin Niemoller
First they came for the socialists, and I did not speak out- Because I was not a socialist.
Then they came for the trade unionists, and I did not speak out- Because I was not a trade unionist.
Then they came for the Jews, and I did not speak out- Because I was not a Jew.
Then they came for me- and there was no one left to speak for me.
** Matthew Schultz
“You’re allowed to believe in a god. You’re allowed to believe unicorns live in your shoes for all I care. But the day you start telling me how to wear my shoes so I don’t upset the unicorns, I have a problem with you. The day you start involving the unicorns in making decisions for this country, I have a BIG problem with you.”
** Maurice Merleau-Ponty
Each one of us knows for his own part that the world as it is, is unacceptable.
** Maurice Mitchell
"When you hear moderate Democrats pin their losses on 'defund' or the movement for Black lives...
it shows how little they care about police violence actually and how little they care about
Black death."
** Max Weinreich
A Language is a dialect with an army and a navy.

** MC Hammer
"When you measure, include the measurer."
** Michael Rosen
 "The data have landed.
First they said they needed data about the childrern to find out what they're learning.

Then they said they needed data about the children to make sure they are learning.

Then the children only learnt what could be turned into data.

Then the Children became data".
** Mike Pompeo
If any good comes out of ignorance, then I'll take the ignorance.
** Mohamed Baquir al-Nimr
Ali said to his mother if he has the chance to live he wants to be a lawyer or a political activist
so he can get the chance to help others.

** Mohandas Gandhi
I like your Christ,
I do not like your Christians.
Your Christians are so unlike your Christ.
** Mueller Report
"... the evidence doees indicate that a thorough FBI investigation would uncover facts about the campaign and
the president personallty that the president could have understood to be crimes or that would give rise to
personal and political concerns."
- Vol 2, page 76.
** Nadia Bolz-Weber
People don't leave Christianity because they stop believing in the teachings of Jesus.
People leave Christianity because they believe in the teachings of Jesus so much,
they can't stomach being part of an institution that claims to be about that and clearly
isn't.
** Nancy Fraser
"The free-rider worry, incidentally, is typically defined androcentrically as a worry
about shirking paid employment.
Little attention is paid, in contrast, to a far more widespread problem, namely,
men's free riding on women's unpaid domestic labour."
** Neil Gaiman
It is a fool's prerogative to utter truths no one else will speak.

*** Sim city essay
Cities are not people. But, like people, cities have their own personalities: in some cases one city has many different personalities -- there are a dozen Londons, a crowd of different New Yorks.

A city is a collection of lives and buildings, and it has identity and personality. Cities exist in location, and in time.

There are good cities -- the ones that welcome you, that seem to care about you, that seem pleased you're in them. There are indifferent cities -- the ones that honestly don't care if you're there or not; cities with their own agendas, the ones that ignore people. There are cities gone bad, and there are places in otherwise healthy cities as rotten and maggoty as windfall apples. There are even cities that seem lost -- some, lacking a centre, feel like they would be happier being elsewhere, somewhere smaller, somewhere easier to understand.

Some cities spread, like cancers or B-movie slime monsters, devouring all in their way, absorbing towns and villages, swallowing boroughs and hamlets, transmuting into boundless conurbations. Other cities shrink -- once prosperous areas empty and fail: buildings empty, windows are boarded up, people leave, and sometimes they cannot even tell you why.

Occasionally I idle time away by wondering what cities would be like, were they people. Manhattan is, in my head, fast-talking, untrusting, well-dressed but unshaven. London is huge and confused. Paris is elegant and attractive, older than she looks. San Francisco is crazy, but harmless, and very friendly.

It's a foolish game: cities aren't people.

Cities exist in location, and they exist in time. Cities accumulate their personalities as time goes by. Manhattan remembers when it was unfashionable farmland. Athens remembers the days when there were those who considered themselves Athenians. There are cities that remember being villages. Other cities -- currently bland, devoid of personality -- are prepared to wait until they have history. Few cities are proud: they know that it's all too often a happy accident, a mere geographical fluke that they exist at all -- a wide harbour, a mountain pass, the confluence of two rivers.

At present, cities stay where they are.

For now cities sleep.

But there are rumblings. Things change. And what if, tomorrow, cities woke, and went walking? If Tokyo engulfed your town? If Vienna came striding over the hill toward you? If the city you inhabit today just upped and left, and you woke tomorrow wrapped in a thin blanket on an empty plain, where Detroit once stood, or Sydney, or Moscow?

Don't ever take a city for granted.

After all, it is bigger than you are; it is older; and it has learned how to wait...
- [[https://www.neilgaiman.com/Cool_Stuff/Essays/Essays_By_Neil/SIMCITY][Sim city essay]]

** Nikola Tesla
Man, like the universe, is a machine.
Nothing enters our minds or determines our actions which is not
directly or indirectly a response to stimuli beating upon our sense organs from without.
** Ozy Aloziem
White Privilege is your history being part of the core curriculum and mine
being taught as an elective.
** Paul S. Ryan
The right recognizes something that few on the left recognize: That campaign finance law
underlies all other substantive law.

In other words, no matter what you care about - climate, women's rights, abortion, taxes, healthcare,
it all comes back to who pays for elections.
- How to sweep dark money out of politics.
** Paul Virilio
The accident is an inverted miracle, a secular miracle, a revelation.
When you invent the ship, you also invent the shipwreck;
when you invent the plane you also invent the plane crash;
and when you invent electricity, you invent electrocution...
Every technology carries its own negativity, which is invented at the same time as technical progress.
- Politics of the Very Worst.
** Peter Brabeck
The one opinion, which I think is extreme, is represented by the NGOs, who bang on about declaring water
a public right. That means as a human being you should have a right to water.
That's an extreme solution.
** Philip Graham
Journalism is the first rough draft of history.

** Pierre Bourdieu
Charm and charisma in fact designate the power, which certain people
have, to impose their own self-image as the objective and collective image of
their body and being; to persuade others, as in love or faith, to abdicate their
generic power of objectification and delegate it to the person who should be its
object, who thereby becomes an absolute subject, without an exterior (being his
own Other), fully justified in existing, legitimated.

(Bourdieu, Distinction,
p.208).
** Plato
Good people don't need laws to tell them to act responsibly... and bad people will find a way around
the laws.

** Pope Francis
The union is an expression of the prophetic profile of society. The union is born and reborn every time that, like the biblical prophets, it gives a voice to those who have none, denounces those who would “sell the needy for a pair of sandals” (cf. Amos 2: 6), unmasks the powerful who trample the rights of the most vulnerable workers, defends the cause of the foreigner, the least, the discarded.

The capitalism of our time does not understand the value of the trade union, because it has forgotten the social nature of the economy, of the business. This is one of the greatest sins. Market economy: no. Let us say, social market economy, as St. John Paul II taught: social market economy. The economy has forgotten the social nature that it has as a vocation, the social nature of business, of life, of bonds and pacts. But perhaps our society does not understand the union also because it does not fight enough in terms of the “not yet rights”: of the existential peripheries, among those rejected from work.
- [[https://press.vatican.va/content/salastampa/en/bollettino/pubblico/2017/06/28/170628a.html][Audience with Delegates from the Confederation of Trade Unions in Italy, 28.06.2017]]

** Queen Kristina
There are men who are as much women as their mothers, and women who are as much men as their fathers, for
the soul has no gender.
- 1641.

** Rand Paul
Quoting @judgenap: Why do we have a second amendment? It's not to shoot deer.
It's to shoot at the government when it becomes tyrannical.
** Randall Terry
"Our goal must be simple. We must have a Christian nation built on God's law, on the ten Commandments. No apologies."

"I don't think Christians should use birth control. You consummate your marriage as often as you like and if you have babies, you have babies."

"When I, or people like me, are running the country, you'd better flee, because we will find you, we will try you, and we will execute you. I mean every word of it. I will make it part of my mission to see to it that they are tried and executed... If we're going to have true reformation in America, it is because men once again, if I may use a worn out expression, have righteous testoserone flowing through their veins. They are not afraid of contempt for their contemporaries. They are not even here to get along. They are here to take over... Somebody like Susan Smith should be dead. She should be dead now. Some people will go, "Well how do you know God doesn't have a wonderful plan for her life?" He does, it's listed in the Bible. His plan for her is that she should be dead."

I want you to just let a wave of intolerance wash over you. I want you to let a wave of hatred wash over you. Yes, hate is good. … Our goal is a Christian nation. We have a Biblical duty, we are called by God, to conquer this country. We don't want equal time. We don't want pluralism.
** Richard Buckminster Fuller
“We should do away with the absolutely specious notion that everybody has to earn a living. It is a fact today that one in ten thousand of us can make a technological breakthrough capable of supporting all the rest. The youth of today are absolutely right in recognizing this nonsense of earning a living. We keep inventing jobs because of this false idea that everybody has to be employed at some kind of drudgery because, according to Malthusian Darwinian theory he must justify his right to exist. So we have inspectors of inspectors and people making instruments for inspectors to inspect inspectors. The true business of people should be to go back to school and think about whatever it was they were thinking about before somebody came along and told them they had to earn a living.”

It is now highly feasible to take care of everybody on Earth at a ‘higher standard of living than any have ever known.’ It no longer has to be you or me. Selfishness is unnecessary and henceforth unrationalizable as mandated by survival. Most importantly we have learned that from here on it is success for all or none, for it is experimentally proven by physics that “unity is plural and at minimum two” – the complementary but not mirror-imaged proton and neutron. You and I are inherently different and complimentary. Together we average as zero – that is, as eternity.

"We can now take care of everybody at a higher standard of living than anybody has ever known. It does not have to be “you or me,” so selfishness is unnecessary and war is obsolete. This has never been done before.“

You never change things by fighting the existing reality. To change something, build a new model that
makes the existing model obsolete.
** Richard Littler
At the centre of Daniel's claims is a dangerous cult obsessed by staionary and office supplies.
Like the Freemasons, the Officists have as their symbols of religious ower the simple tools of
their trade: hole-punchers, staple guns, pencils, erasers, typewriters, paperclips, ring binders, etc.

The Cult treats bureaucrats as holy and is strictly hierarchical.
No one knows what the following cult roles might entail:
Grand Master Photocopier, Post Boy Penitent, The Night Mayor,
Assistant Sellotape Wizard, Dave the Novelty Pencil Eraser,
but what is clear is the cult's desire to place its members, voluntary or otherwise, in positions
of societal influence.
By whatever means necessary...
- Discovering Scarfolk

** Roger Fisher
My favorite activity is inventing.  An early arms control proposal
dealt with the problem of distancing that the President would
have in the circumstance of facing a decision about nuclear war.
There is a young man, probably a Navy officer, who accompanies
the President.    This young man has a black attache case which
contains the codes that are needed to fire nuclear weapons.
I could see the President at a staff meeting considering nuclear
was as an abstract question.  He might conclude: "On SIOP Plan
One, the decision is affirmative.  Communicate the Alpha line
XYZ."  Such jargon holds what is involved at a distance.

My suggestion was quite simple: Put that needed code number in
a little capsule, and then implant that capsule right next to
the heart of a volunteer.  The volunteer would carry with him
a big, heavy butcher knife as he accompanied the President.
If ever the President wanted to fire nuclear weapons, the only
way he could do so would be for him first, with his own hands,
to kill one human being.  The President says, "George, I'm sorry
but tens of millions must die."  He has to look at someone and
realize what death is -- what an innocent death is.  Blood on
the White House carpet.  It's reality brought home.

What I suggested this to friends in the Pentagon, they said,
"My God, that's terrible.  Having to kill someone would distort
the President's judgment.  He might never push the button."

- [[https://www.tandfonline.com/doi/abs/10.1080/00963402.1981.11458828][Bulletin of the Atomic Scientists]]
** Roland Freisler
This jurisprudence would suit us perfectly, with a single exception.
Over there they have in mind, practically speaking, only coloreds and half-coloreds, which includes
mestizos and mulattoes; but the jews, who are also of interest to us, are not reckoned among the coloreds.
- Nazi judge talking about the USA.
** Ronald Reagan
She has 80 names, 30 addresses, 12 social security cards and is collecting veteran's benefits on four non-existing deceased husbands. And she is collecting social security on her cards. She's got medicaid, getting food stamps, and she is collecting welfare under each of her names.
- 1976 on the 'welfare queen'.

There is no more essential ingredient than a free, strong, and independent press to our continued
success in what the Founding Fathers called our 'noble experiment' in self-government.
** Ronald Reagan (Humourous)
The second amendment doesn't exist for hunting. It exists so undocumented immgrants can shoot ICE agents in self defense.
** Roosh
When a female gets a tattoo, she is giving a permanent oath of fealty to the oligarchs and their hired managers.
Her mind is controlled by their Satanic inversions, her body destined to be used and abused in exchange for
pleasure and power. Her tattoo is the mark of the beast.

** Rosa Parks
People always say that I didn't give up my seat because i was tired, but that isn't true...
No, the only tired I was, was tired of giving in.
** Rosie Cappuccino
She should not apologise for the trauma that formed her.
** Roy Moore
These women have had 30 years to come forward, and the one and only reason they're speaking out now is because they
suddenly have less fear that their lives will be utterly destroyed.
** Salvador Dali
It is not necessary for the public to know whether I am joking or whether I am serious,
just as it is not necessary for me to know it myself.

I am not strange. I am just not normal.

The Sole difference between myself and a madman is the fact that I am not mad!

I don't do drugs. I am drugs.
** Sam Haskins
A photographer went to a socialite party in New York.
As he entered the front door, the host said 'I love your pictures - they're wonderful;
you must have a fantastic camera.'
He said nothing until dinner was finished, then: 'That was a wonderful dinner, you must have
a terrific stove.'
** Sankara
"Sankara: Yes. You cannot carry out fundamental change without a certain amount of madness.
In this case, it comes from noncomformity, the courage to turn your back on the old formulas,
the courage to invent the future. Besides, it took the madmen of yesterday for us to be able to act with
extreme clarity today. I want to be one of those madmen.
Rapp: To Invent the future?
Sankara: Yes. We must dare to invent the future."
** Sarah Kendzior
When wealth is passed off as merit, bad luck is seen as bad character.
This is how ideologues justify punishing the sick and the poor.
But poverity is neither a crime not a character flaw.
Stigmatise those who let people die, not those who struggle to live.
** Schultz
If it can be destroyed by the truth, it deserves to be destroyed by the truth.

** Simone de Beauvoir
Never forget that a political, economic or religious crisis is enough to cast doubt on women's rights.
These rights will never be vested. You have to stay vigilant your whole life.

** Stephen Fry
It's now very common to hear people say "I'm rather offended by that".
As if that gives them certain rights.
It's no more than a whine. It has no meaning, it has no purpose.
It has no reason to be respected as a phrase.
"I'm offended by that".
Well, so fucking what?

** Susan B. Anthony
I distrust those people who know so well what God wants them to do, because I notice
it always coincides with their own desires.

** Susan Wojcicki
Though we do need more women to graduate with technical degrees, I always like to remind women
that you don't need to have science or technology degrees to build a career in tech.
** Talia Lavin
Vanity Fair: Do you worry about the reaction to your book?
Lavin: You mean am I worried I'm going to be murdered?
VF: Yes.
Lavin: I think anyone who engages with the far right journalistically or as an activist worries
about being murdered. But I worked on an operating principle of not letting these people steal my
right to speak out of fear, and that's how I'm continuing to operate. On the balance of things
I'd prefer not to be murdered, but if I have to go somehow, I guess standing up against Nazis in
2020 America isn't the worst reason.
** Terry Pratchett
“The reason that the rich were so rich, Vimes reasoned, was because they managed to spend less money.

Take boots, for example. He earned thirty-eight dollars a month plus allowances. A really good pair of leather boots cost fifty dollars. But an affordable pair of boots, which were sort of OK for a season or two and then leaked like hell when the cardboard gave out, cost about ten dollars. Those were the kind of boots Vimes always bought, and wore until the soles were so thin that he could tell where he was in Ankh-Morpork on a foggy night by the feel of the cobbles.

But the thing was that good boots lasted for years and years. A man who could afford fifty dollars had a pair of boots that'd still be keeping his feet dry in ten years' time, while the poor man who could only afford cheap boots would have spent a hundred dollars on boots in the same time and would still have wet feet.

This was the Captain Samuel Vimes 'Boots' theory of socioeconomic unfairness.”
- Men at Arms.

 “You'd like Freedom, Truth, and Justice, wouldn't you, Comrade Sergeant?' said Reg encouragingly.
'I'd like a hard-boiled egg,' said Vimes, shaking the match out.
There was some nervous laughter, but Reg looked offended.
'In the circumstances, Sergeant, I think we should set our sights a little higher--'
'Well, yes, we could,' said Vimes, coming down the steps. He glanced at the sheets of papers in front of Reg. The man cared. He really did. And he was serious. He really was. 'But...well, Reg, tomorrow the sun will come up again, and I'm pretty sure that whatever happens we won't have found Freedom, and there won't be a whole lot of Justice, and I'm damn sure we won't have found Truth. But it's just possible that I might get a hard-boiled egg.”
― Night Watch

 "It's not as simple as that. IT's not a black and white issue. There are so many shades of grey.'
'Nope'.
'Pardon?'
'There's no greys, only white that's got grubby. I'm surprised you don't know that. And sin, young man,
is when you treat people as things. Including yourself. That's what sin is.'
'It's a lot more complicated than that-'
'No. It ain't. When people say things are more complicated than that,
they means they're getting worried that they won't like the truth.
People as things, that's where it starts.'
'Oh, I'm sure there are worse crimes-'
'But they starts with thinking about people as things...'"
 - Carpe Jugulum.


Good Ain't Nice.

She always said you can't help people with magic, but you can help them with skin.
By doin' real things, she meant.

'You'd have to go a long day's journey to find someone basically nastier than Esme' said Nanny Ogg,
'and this is me sayin' it. She knows exactly what she is. She was born to be good and she don't like it.'
** The Onion
"What part of 'stand back and stand by' did these idiots not understand?"
** Theodore Roosevelt
Patriotism means to stand by the country. It does not mean to stand by the president.

Human kindness has never weakened the stamina or softened the fiber of a free people.
A Nation does not have to be cruel to be tough.
** Tommy Douglas
 "Once more, let me remind you what fascism is. I need not wear a brown shirt or a green shirt.
Fascism begins the moment a ruling class, fearing the people may use their political democracy to gain
economic democracy, begins to destroy political democracy in order to retains its power of exploitation
and special privilege."
** Toni Cade Bambara
This society has rewards for those who demonstrate skills in nimble avoidance of
uncomfortable realities that threaten the bogus peace. But no mercy for those
who dare penetrate the social garments and speak out on the emperor's clothes.
** Tony Benn
The way a government treats refugees is very instructive because it shows you how they would treat
the rest of us if they thought they could get away with it.


I expect that the House has heard of the little document, which is circulating, about the boat race between the NHS and a Japanese crew. Both sides tried hard to do well, but the Japanese won by a mile. The NHS was very discouraged and set up a consultancy. The consultancy came to the conclusion that the Japanese had eight people rowing and one steering, whereas the NHS had eight people steering and one rowing. The NHS appointed people to look at the problem and decided to reorganise the structure of the team so that there were three steering managers, three assistant steering managers and a director of steering services, and an incentive was offered to the rower to row harder. When the NHS lost a second race, it laid off the rower for poor performance and sold the boat. It gave the money it got from selling the boat to provide higher than average pay awards for the director of steering services.
- [[https://publications.parliament.uk/pa/cm199596/cmhansrd/vo951122/debtext/51122-36.htm][Hansard Archive]]
** Tony Morrison
"And fantasy it was, for we were not strong, only aggressive;
we were not free, merely licensed;
we were not compassionate, we were polite;
not good, but well behaved.
We courted death in order to call ourselves brave, and hid like thieves from life.
We substituted good grammar for intellect; we switched habits to simulate maturity;
we arranged lies and called it truth, seeing in the new pattern of an old idea the Revelation
and the Word."
- The Bluest Eye

“The function, the very serious function of racism is distraction. It keeps you from doing your work. It keeps you explaining, over and over again, your reason for being. Somebody says you have no language and you spend twenty years proving that you do. Somebody says your head isn’t shaped properly so you have scientists working on the fact that it is. Somebody says you have no art, so you dredge that up. Somebody says you have no kingdoms, so you dredge that up. None of this is necessary. There will always be one more thing.”
** Tressie McMillan Cottom
If Hannah Arendt is the definitive voice on fascism among our intellectual classes,
then surely black women who have lived under fascists US policies here and abroad can
shed light on our cultural moment.
- Thick: and other essays

** Tucker Carlson
How'd we get to a place where it's normal that two parts of the country despise each other?
That you can imagine the other side encouraging terror?
Our thinking changed.
We stopped debating politics & ideas & started attacking others for things we can't change,
for who we are.
- Carlson, 11.09.18
** Tukey
 https://doi.org/10.2307/2683137

 The data may not contain the answer. The combination of some data and an aching desire for an answer does not ensure that a reasonable answer can be extracted from a given body of data.

** Ursula K. Le Guin.
 “With the myth of the State out of the way, the real mutuality and reciprocity of society and individual became clear. Sacrifice might be demanded of the individual, but never compromise: for though only the society could give security and stability, only the individual, the person, had the power of moral choice - the power of change, the essential function of life. The Odonian society was conceived as a permanent revolution, and revolution begins in the thinking mind.”
- The Dispossessed (1974)

We live in Capitalism. It's Power seems inescapable.
So did the Divine Right of Kings.
Any Human Power can be resisted and changed by human beings.

“We have nothing but our freedom. We have nothing to give you but your own freedom. We have no law but the single principle of mutual aid between individuals. We have no government but the single principle of free association. We have no states, no nations, no presidents, no premiers, no chiefs, no generals, no bosses, no bankers, no landlords, no wages, no charity, no police, no soldiers, no wars. Nor do we have much else. We are sharers, not owners. We are not prosperous. None of us is rich. None of us is powerful. If it is Anarres you want, if it is the future you seek, then I tell you that you must come to it with empty hands. You must come to it alone, and naked, as the child comes into the world, into his future, without any past, without any property, wholly dependent on other people for his life. You cannot take what you have not given, and you must give yourself. You cannot buy the Revolution. You cannot make the Revolution. You can only be the Revolution. It is in your spirit, or it is nowhere.”
- The Dispossessed

"Commodified fantasy takes no risks: it invents nothing, but imitates and trivializes. It proceeds by depriving the old stories of their intellectual and ethical complexity, turning their action to violence, their actors to dolls, and their truth-telling to sentimental platitude. Heroes brandish their swords, lasers, wands, as mechanically as combine harvesters, reaping profits. Profoundly disturbing moral choices are sanitized, made cute, made safe. The passionately conceived ideas of the great storytellers are copied, stereotyped, reduced to toys, molded in bright-colored plastic, advertised, sold, broken, junked, replaceable, interchangeable.
What the commodifiers of fantasy count on and exploit is the insuperable imagination of the reader, child or adult, which gives even these dead things life - of a sort, for a while."
-  "Ursula Le Guin and the Scourge of the Uncritical Reader."

** Vilna Bashi Treitler
TODO "how an ethnic group comes to be recognized as such"
** Weed man Lue
Due to the coronavirus I will no longer be accepting cash or hand to hand transactions.
Please continue to use cashapp or Venmo.

Please also designate a safe place where I can Leave your order so that we do not have to make contact
Thanks
** Werner Herzog
Dear America:
You are waking up, as Germany once did, to the awareness that
1/3 of your people would kill another 1/3, while 1/3 watches.
** William Stafford
There is no such thing as writer's block for writers whose standard are low enough.
** Yeats
The Choice

The intellect of man is forced to choose
Perfection of the life, or of the work,
And if it take the second must refuse
A heavenly mansion, raging in the dark.
When all that story's finished, what's the news?
In luck or out the toil has left its mark:
That old perpelxity an empty purse,
Or the day's vanity, the night's remorse.
** Zach Galifianakis
Destroy the idea that you have to be constantly working or grinding in order to be successful.
Embrace the concept that rest, recovery, reflection are essential parts of the progress towards
a successful and happy life.
** Zora Neale Hurston
If you are silent about your pain, they'll kill you and say you enjoyed it.
** [[https://antichamber.fandom.com/wiki/List_of_Signs][AntiChamber]]
1) Every journey is a series of choices. The first is to being the journey.
2) Patience has its own rewards.
3) Taking the first step can be harder than the rest of the challenge.
4) Many small obstacles can make for one large problem.
5) Some choices leave us running around a lot without really getting anywhere.
6) Live on your own watch, not on someone else's.
7) Failing to succeed does not mean failing to progress.
8) Some paths are clearer than others.
9) Some paths are straight forward.
10) A choice may be as simple as going left or going right.
11) The choice doesn't matter if the outcome is the same.
12) If you don't like where you've ended up, try doing something else.
13) When you return to where you have been, things aren't always as remembered.
14) We fall down when there is nothing there to support us.
15) Building a buridge can get you over a problem.
16) Some hurdles are too high to jump over.
17) Life is full of ups and downs.
18) Connecting the pieces can solve a puzzle.
19) Life has a way of pushing us in the right direction.
20) the end may come before we were ready to get there.
21) Life isn't about getting to the end.
22) It's harder to progress if you're leaving things behind.
23) The further we get, the less help we need.
24) Moving forward may require making the most of what you've got.
25) Some tasks require a lot of care and observation.
26) Taking one path often means missing out on another.
27) A path may not be right or wrong. It may just be different.
28) Look a little harder, and you will find a way forward.
29) Venturing into the unknown can lead to great rewards.
30) If you're only focusin on right now, you won't have enough for later.
31) A dead end will only stop you if you don't try to move through it.
32) Going a certain way may require building your own path.
33) There's nothing wrong with taking shortcuts.
34) We often fall into things when we least expect.
35) What looks out of reach may only be a few steps away.
36) There are multiple ways to approach a situation.
37) When you've hit rock bottom, the only way is up.
38) Some outcomes are more favourable than others.
39) How we perceive a problem can change every time we see it.
40) The solution to a problem may just require a more thorough look at it.
41) Rushing through a problem won't always give the right results.
42) Moving through a problem slower may help find the solution.
43) If you never strop trying, you will get there eventually.
44) Raw persistence may be the only option other than giving up entirely.
45) Some problems just come down to size.
46) A Problem may only be difficult when you are missing the right tools.
47) What we've done before may impact what we can do next.
48) If you aren't paying attention, you will miss everything around you.
49) Some choices can leave us running around in circles.
50) Splitting a problem up may help you find the answer.
51) What appears impossible may have a very simple answer.
52) If you lose sight of what's important, it may not be there when you need it.
53) Too much curiosity can get the best of us.
54) Signs may be helping you more than you realize.
55) Understanding a problem requires filling in the pieces.
56) Small steps can take you great distances.
57) The path of least resistance is a valid option.
58) No matter how high you climp, there's always more to achieve.
59) Falling down teaches us how to get up and try again.
60) The world rarely changes when we watch to see it happen.
61) Half way through is half way finished.
62) The problem may not be where you're going, but how to get there.
63) New skills enable further progress.
64) Mastering a skill requires practice.
65) A little kind direction can get obstacles out of your way.
66) Solving a problem may require approaching it from a different angle.
67) Try hard enough and you will get to where you want to be.
68) Some doors will close unless we hold them open.
69) When you absorb your surroundings, you may notice things that you didn't see before.
70) Dig a little deeper and you may find something new.
71) Attention to detail can lead to very rewarding outcomes.
72) Solving a problem may require using abilities that we didn't realize we had.
73) Old skills are useful even after we have learned new ones.
74) The right answers may also be the most obvious ones.
75) Some Obstacles are more stubborn than others.
76) Some things don't have a deeper meaning.
77) The right decisions at the right time will get you where you want to go.
78) Some choices are only useful when we make them early.
79) With forethought, things have a way of just working themselves out.
80) Some challenges are far harder than they first appear.
81) To get past a problem, you may just need to keep pushing through it.
82) Getting to a solution requires cutting out what doesn't work.
83) The further we explore, the more connected everything becomes.
84) A Window of opporunity can lead to new places if you are willing to take a closer look.
85) The world looks different on the other side.
86) When you have enough resources, you can start growing more.
87) You can grow a garden anywhere.
88) The best solutions may still be the most primitive ones.
89) If you lead the way, others will follow.
90) Straightforward problems can often require roundabout solutions.
91) If you are missing information, it's easy to be misled.
92) When you look beyond the surface, there may be more to find.
93) Sometimes we only have just enough to get by.
94) When what you have is not enough, find ways to turn it into more.
95) Getting where we want may require jumping through some hoops.
96) Throwing yourself into things can take you to new heights.
97) Similar problems can have entirely different solutions.
98) Some events happen whether we want them to or not.
99) Old solutiosn can apply to new problems.
100) The consequences of the one choice can cut us off from making others.
101) At times we need to view the world from someone else's perspective.
102) Sometimes you need to be carried.
103) There comes a time when you can work your way through anything.
104) With more experience, previous challenges aren't so difficult.
105) There's no need to take apart what already works.
106) A few steps backwards may keep you moving forwards.
107) Obscure problems may require unusual solutions.
108) Getting to the end requires tying off the loose ends.
109) The world is always finding new ways to surprise us.
110) Sometimes we do things just to go along for the ride.
111) The more we complete, the harder it gets to find what we missed.
112) Some challenges exist just to test how much we know.
113) You can't do everything yourself.
114) The world is full of secrets waiting to be uncovered.
115) Peeking behind the curtains lets us see how everything works.
116) Some problems can't be solved until you're more experienced.
117) We move on when there is nothing left to learn.
118) Complicated problems are easier when solved one step at a time.
119) We can appreciate the entire journey by looking back at how far we have come.
120) Every journey comes to an end.
