* Alfred Bester Extracts                                                        :bester:extracts:scifi:

*** The Stars my destination

The old Bureaux of Motor Vehicles took over the new job and regularly tested and classed jaunte applicants, and the old American Automobile Association changed its initials to A.J.A.

Despite all efforts, no man had ever jaunted across the voids of space although many experts and fools had tried. Helmut Grant, for one, who spent a month memorizing the co-ordinates of a jaunte stage on the moon and visualized every mile of the two hundred-and-forty-thousand-mile trajectory from Times Square to Kepler City. Grant jaunted and disappeared. They never found him. They never found Enzio Dandridge, a Los Angeles revivalist looking for Heaven; Jacob Maria Freundlich, a paraphysicist who should have known better than to jaunte into a deep space searching for meta-dimensions; Shipwreck Cogan, a professional seeker after notoriety; and hundreds of others, lunatic fringers, neurotics, escapists and suicides. Space was closed to teleportation. Jaunting was restricted to the planets of the solar system.

But within three generations the entire solar system was on the jaunte. The transition was more spectacular than the change-over from horse and buggy to gasoline age four centuries before. On three planets and eight satellites, social, legal and economic structures crashed while the new customs and laws demanded by universal jaunting mushroomed in their place.

There were land riots as the jaunting poor deserted slums to squat in plains and forests, raiding the livestock and wildlife. There was a revolution in home and office building, labyrinths and masking devices had to be introduced to prevent unlawful entry by jaunting. There were crashes and panics and strikes and famines as pre-jaunte industries failed.

Plagues and pandemics raged as jaunting vagrants carried disease and vermin into defenseless countries. Malaria, elephantiasis and the break-bone fever came north to Greenland; rabies returned to England after an absence of three hundred years. The Japanese beetle, the citrons scale, the chestnut blight and the elm borer spread to every corner in the world, and from one forgotten pest-hole in Borneo, leprosy, long imagined extinct, reappeared.

Crime waves swept the planets and satellites as the underworlds took to jaunting with the night around the clock, and there were brutalities as the police fought them without quarter. There came a hideous return to the worst prudery of Victorianism as society fought the sexual and moral dangers of jaunting with protocol and taboo. A cruel and vicious war broke out between the Inner Planets, Venus, Terra and Mars, and the Outer Satellites . . . a war brought on by the economic and political pressures of teleportation.

Until the Jaunte Age dawned, the three inner planets (and the Moon) had lived in delicate economic balance with the seven inhabited outer satellites; Io, Europa, Ganymede and Callisto of Jupiter; Rhea and Titan of Saturn; and Lassell of Neptune. The United Outer Satellites supplied raw materials for the Inner Planets manufactories, and a market for their finished goods. Within a decade this balance was destroyed by jaunting.

The Outer Satellites, raw young worlds in the making, had bought seventy per cent of the L.P. transportation production. Jaunting ended that. They had bought ninety per cent of the LP. communications production. Jaunting ended that too. In consequence L.P. purchase of O.S. raw materials fell off. With trade exchange destroyed it was inevitable that the economic war would degenerate into a shooting war. Inner Planets cartels refused to ship manufacturing equipment to the Outer Satellites, attempting to protect themselves against competition. The O.S. confiscated the planets already in operation on their worlds, broke patent agreements, ignored royalty obligations . . . and the war was on.

It was an age of freaks, monsters and grotesques. All the world was misshapen in marvelous and malevolent ways. The Classicists and Romantics who hated it were unaware of the potential greatness of the twenty-fourth century. They were blind to a cold fact of evolution . . . that progress stems from clashing merger of antagonistic extremes, out of the marriage of pinnacle freaks. Classicists and Romantics alike were unaware that the solar system was trembling on the verge of a human explosion that would transform man and make him the master of the universe.

It is against this seething background of the twenty-fourth century that the vengeful history of Gully Foyle begins.




The distant sun blazed through; the air was hot and moist. Foyle gazed around dimly. A devil face peered at him. Cheeks, chin, nose and eyelids were hideously tattooed like an ancient Maori mask. Across the brow was tattooed JOSEPH. The '0' 1n JOSEPH had a tiny arrow thrust up from the right shoulder, turning it into the symbol of Mars, used by scientists to designate male sex.

'We are The Scientific People,' Joseph said. 'I am Joseph; these are my brethren.' He gestured. Foyle gazed at the grinning crowd surrounding his litter. All faces were tattooed into devil masks; all brows had names blazoned across them.

'How long did you drift?' Joseph asked.

'Vorga,' Foyle mumbled.

'You are the first to arrive alive in fifty years. You are a puissant man. Very. Arrival of the fittest is the doctrine of Holy Darwin. Most scientific.'

'Quant Suff!' the crowd bellowed.

Joseph seized Foyle's elbow in the manner of a physician taking a pulse. His devil mouth counted solemnly up to ninety-eight.

'Your pulse. Ninety-eight-point-six,' Joseph said, producing a thermometer and shaking it reverently. 'Most scientific.' 'Quant Suff!' came the chorus.

Joseph proffered an Erlenmeyer flask. It was labeled: Lung Cat, c.c., hematoxylin and eosin. 'Vitamin?' Joseph inquired.

When Foyle did not respond, Joseph removed a large pill from the flask, placed it in the bowl of a pipe and lit it. He puffed once and then gestured. Three girls appeared before Foyle. Their faces were hideously tattooed. Across each brow was a name: JOAN and MOIRA and FOLLY. The 'O' of each name had a tiny cross at the base.

'Choose,' Joseph said. 'The Scientific People practice Natural Selection. Be scientific in your choice. Be genetic.'

As Foyle fainted again, his arm slid off the litter and glanced against Moira.

'Quant Suff!'

He was in a circular hall with a doomed roof. The hall was filled with rusting antique apparatus: a centrifuge, an operating-table, a wrecked fluoroscope, autoclaves, cases of corroded surgical instruments.

They strapped Foyle down on the operating-table while he raved and rambled. They fed him. They shaved and bathed him. Two men began turning the ancient centrifuge by hand. It emitted a rhythmic clanking like the pounding of a war drum. The assembled began tramping and chanting.

They turned on the ancient autoclave. It boiled and geysered filling the hall with howling steam. They turned on the old fluoroscope. It was short-circuited and spat sizzling bolts of lightning across the steaming hall.

A ten-foot figure loomed up to the table. It was Joseph on stilts. He wore a surgical cap, a surgical mask, and a surgeon's gown that hung from his shoulders to the floor. The gown was heavily embroidered with red and black thread illustrating anatomical sections of the body. Joseph was a lurid tapestry out of a surgical text.

'I pronounce you Nomad!' Joseph intoned.

The uproar became deafening. Joseph tilted a rusty can over Foyle's body. There was the reek of ether. Foyle lost his tatters of consciousness and darkness enveloped him. Out of the darkness Vorga-T: 1339 surged again and again, accelerating on a sunward course that burst through Foyle's blood and brains until he could not stop screaming silently for vengeance.

He was dimly aware of washings and feedings and trampings and chantings. At last he awoke to a lucid interval. There was silence. He was in bed. The girl, Moira, was in bed with him.

'Who you?' Foyle croaked.

'Your wife, Nomad.'

'What?'

'Your wife. You chose me, Nomad. We are gametes.'

'What?'

'Scientifically mated,' Moira said proudly. She pulled up the sleeve of her nightgown and showed him her arm. It was disfigured by four, ugly slashes. 'I have been inoculated with something old, something new, something borrowed and something blue.' Foyle struggled out of bed.

'Where we now?'

'In our home.'

'What home?'

'Yours. You are one of us, Nomad. You must marry every month and beget many children. That will be scientific. But I am the first.' Foyle ignored her and explored. He was in the main cabin of a small rocket launch of the early 2300s . . . once a private yacht. The main cabin had been converted into a bedroom.

He lurched to the ports and looked out. The launch was sealed into the mass of the asteroid, connected by passages m the main body. He went aft. Two smaller cabins were filled with growing plants for oxygen. The engine-room had been inverted into a kitchen. There was Hi-Thrust in the fuel tanks, but it fed the burners of a small stove atop the rocket chambers. Foyle went forward. The control cabin was now a parlor, but the controls were still operative.

He thought.

He went aft to the kitchen and dismantled the stove. He reconnected the fuel tanks to the original jet combustion chambers. Moira followed him curiously.

'What are you doing, Nomad?'

'Got to get out of here, girl,' Foyle mumbled. 'Got business with a ship called Vorga. You dig me, girl? Going to ram out in this boat, is all.' Moira backed away in alarm. Foyle saw the look in her eyes and leaped for her. He was so crippled that she avoided him easily. She opened her mouth and let out a piercing scream. At that moment a mighty clangor filled the launch; it was Joseph and his devil-faced brethren outside, banging on the metal hull, going through the ritual of a scientific charivari for the newlyweds.

Moira screamed and dodged while Foyle pursued her patiently. He trapped her in a corner, ripped her nightgown off and bound and gagged her with it. Moira made enough noise to split the asteroid open, but the scientific charivari was louder.

Foyle finished his rough patching of the engine-room; he was almost an expert by now. He picked up the writhing girl and took her to the main hatch.

'Leaving,' he shouted in Moira's ear. 'Take-off. Blast right out of asteroid. Hell of a smash, girl. Maybe all die, you.

Everything busted wide open. Guesses for grabs what happens. No more air. No more asteroid. Go tell'm. Warn'm. Go girl' He opened the hatch, shoved Moira out, slammed the hatch and dogged it. The charivari stopped abruptly.

At the controls Foyle pressed ignition. The automatic takeoff siren began a howl that had not sounded in decades. The jet chambers ignited with dull concussions. Foyle waited for the temperature to reach firing heat. While he waited he suffered. The launch was cemented into the asteroid. It was surrounded by stone and iron. Its rear jets were flush on the hull of another ship packed into the mass. He didn't know what would happen when his jets began their thrust, but he was driven to gamble by Vorga.

He fired the jets. There was a hollow explosion as Hi-Thrust flamed out of the stern of the ship. The launch shuddered, yawned, heated. A squeal of metal began. Then the launch grated forward. Metal, stone and glass split asunder and the ship burst out of the asteroid into space.

The L.P. navy picked him up ninety thousand miles outside Mars's orbit. After seven months of shooting war, the patrols were alert but reckless. When the launch failed to answer and give recognition countersigns, it should have been shattered with a blast and questions could have been asked of the wreckage later. But the launch was small and the cruiser crew was hot for prize money. They closed and grappled.

They found Foyle inside, crawling like a headless worm through a junk-heap of spaceship and home furnishings. He was bleeding again, ripe with stinking gangrene, and one side of his head was pulpy. They brought him into the sick-bay aboard the cruiser and carefully curtained his tank. Foyle was no sight even for the tough stomachs of lower deck navy men.




'Yeah. I found out where you live. They know up at the hospital. I come here and looked around. I read your diary, Miss Robin. You got a family on Callisto, mother and two sisters.'

'For God's sake!'

'So that makes you an alien-belligerent. When the war started you and all the rest was given one month to get out of the Inner Planets and go home. Any which didn't became spies by law. You're on the hook, girl.' Foyle opened his hand. 'I got you right here, girl.' He clenched his hand.

'My mother and sisters have been trying to leave Callisto for a year and a half: We belong here. We -'

'Got you right here,' Foyle repeated. 'You know what they do to spies? They cut information out of them. They cut you apart, Miss Robin. They take you apart, piece by piece -'

Robin screamed. Foyle nodded happily and took her shaking shoulders in his hands. 'I got you, is all, girl. You can't even run from me because all I got to do is tip Intelligence and where are you? There ain't nothing nobody can do to stop me; not the hospital or even Mr. Holy Mighty Presteign of Presteign.'



Devoted to the principle of conspicuous waste, on which all society is based, Presteign of Presteign had fitted his Victorian mansion in Central Park with elevators, housephones, dumbwaiters and all the other labor-saving devices which jaunting had made obsolete. The servants in that giant gingerbread castle walked dutifully from room to room, opening and closing doors, and climbing stairs.

Presteign of Presteign arose, dressed with the aid of his valet and barber, descended to the morning-room with the aid of an elevator and breakfasted, assisted by a butler, footman and waitresses. He left the morning-room and entered his study. In an age when communication systems were virtually extinct; when it was far easier to jaunte directly to a man's office for a discussion than to telephone or telegraph; Presteign still maintained an antique telephone switchboard with operator in his study.

'Get me Dagenham,' he said.

The operator struggled and at last put a call through to Dagenham Couriers, Inc. This was a hundred million credit organization of bonded Jaunters guaranteed to perform any public or confidential service for any principal. The fee was Cr 1 per mile. Dagenham guaranteed to get a courier around the world in eighty minutes.

Eighty seconds after Presteign's call was put through, a Dagenham courier appeared on the private jaunte stage outside Presteign's home, was identified and admitted through the jaunte-proof labyrinth behind the entrance. Like every member of the Dagenham staff, he was an M class Jaunter, capable of teleporting a thousand miles a jump indefinitely, and familiar with thousands of jaunte coordinates. He was a senior specialist in chicanery and cajolery, trained to the incisive efficiency and boldness that characterized Dagenham Couriers and reflected the ruthlessness of its founder.

'Presteign?' he said, wasting no time on protocol.

'I want to hire Dagenham'.

'Ready, Presteign.'

'Not you. I want Saul Dagenham himself.'

'Mr. Dagenham no longer gives personal service for less than Cr 100,000.'

'The amount will be five times that.'

'Fee or percentage.'

'Both. Quarter of a million fee, and a quarter of a million guaranteed against ten per cent of the total amount at risk.'

'Agreed. The matter?'

'PyrE.'

'Spell it, please.'

'The name means nothing to you?'

'No.'

'Good. It will to Dagenham. PyrE. Capital P-Y-R-Capital E. Tell Dagenham we've located the PyrE. He's engaged to get it . . . at all costs . . . through a man named Foyle. Gulliver Foyle.' The courier produced a tiny silver pearl, a memo-bead, repeated Presteign's instructions into it, and left without another word.

Presteign turned to his telephone operator. ' Get me Regis Sheffield,' he directed.

Ten minutes after the call went through to Regis Sheffield's law office, a young law clerk appeared on Presteign's private jaunte stage, was vetted and admitted through the maze. He was a bright young man with a scrubbed face and the expression of a delighted rabbit.

'Excuse the delay, Presteign,' he said. 'We got your call in Chicago and I'm still only a D class five-hundred-miler. Took me a while getting here.'

' Is your chief trying a case in Chicago?'

'Chicago, New York and Washington. He's been on the jaunte from court to court all morning. We fill in for him when he's in another court.'

'I want to retain him.'

'Honored, Presteign, but Mr. Sheffield's pretty busy.'

'Not too busy for PyrE.'

'Sorry, sir; I don't quite -'

'No, you don't, but Sheffield will. Just tell him: PyrE and the amount of his fee.'

'Which is?' 'Quarter of a million retainer and a quarter of a million guaranteed against ten per cent of the total amount at risk.'

'And what performance is required of Mr. Sheffield?'

'To prepare every known legal device for kidnapping a man and holding him against the army, the navy and the police.'

'Right. And the man?'

'Gulliver Foyle.' The law clerk muttered quick notes into a memo-bead, thrust the bead into his ear, listened, nodded and departed. Presteign left the study and ascended the plush stairs to his daughter's suite to pay his morning respects.

In the homes of the wealthy, the rooms of the female members were blind, without windows or doors, open only to the jaunting of intimate members of the family. Thus was morality maintained and chastity defended. But since Olivia Presteign was herself blind to normal sight, she could not jaunte. Consequently her suite was entered through doors closely guarded by ancient retainers in the Presteign clan livery.

Olivia Presteign was a glorious albino. Her hair was white silk, her skin was white satin, her nails, her lips and her eyes were coral. She was beautiful and blind in a wonderful way, for she could see in the infra red only, from Moo Angstroms to one millimeter wavelengths. She saw heat waves, magnetic fields, radio valves, radar, sonar and electro-magnetic fields.

She was holding her Grand Levee in the drawing-room of the suite. She sat in a brocaded wing chair, sipping tea guarded by her duenna, holding court, chatting with a dozen men and women standing about the room. She looked like an exquisite statue of marble and coral, her blind eyes flashing as she saw and yet did not see.

She saw the drawing-room as a pulsating flow of heat emanations ranging from hot highlights to cool shadows. She saw the dazzling magnetic patterns of clocks, phones, lights and locks. She saw and recognized people by the characteristic heat patterns radiated by their faces and bodies. She saw, around each head, an aura of the faint electro-magnetic brain pattern, and sparkling through the heat radiation of each body, the ever-changing tone of muscle and nerve.

Presteign did not care for the artists, musicians and fops Olivia kept about her, but he was pleased to see a scattering of society notables this morning. There was a Sears-Robuck, a Gillet, young Sidney Kodak who would one day be Kodak of Kodak, a Houbigant, Buick of Buick, and R. H. Macy XVI, head of the powerful Saks-Gimbel clan.

Presteign paid his respects to his daughter and left the house. He set off for his clan headquarters at 99 Wall Street, in a coach and four driven by a coachman assisted by a groom, both wearing the Presteign trademark of red, black and blue. That black 'P' on a field of scarlet and cobalt was one of the most ancient and distinguished trademarks in the social register, rivaling the '57' of the Heinz clan and the 'RR' of the Rolls-Royce dynasty in antiquity.

The head of the Presteign clan was a familiar sight to New York Jaunters. Iron grey, handsome, powerful, impeccably dressed and mannered in the old-fashioned style, Presteign of Presteign was the epitome of the socially elect, for he was so exalted in station that he employed coachmen, grooms, hostlers, stableboys and horses to perform a function for him which ordinary mortals performed by jaunting.

As men climbed the social ladder these days, they displayed their position by their refusal to jaunte. The newly adopted into a great commercial clan rode an expensive bicycle. A rising clansman drove a small sports car. The captain of a sept was transported in a chauffeur-driven antique from the old days, a vintage Bentley or Cadillac or a towering Lagonda. An heir-presumptive in direct line of succession to the clan chieftainship staffed a yacht or a plane. Presteign of Presteign, head of the clan of Presteign, owned carriages, cars, yachts, planes and trains. His position in society was so lofty that he had not jaunted in forty years. He scorned the bustling new-rich like the Dagenhams and Sheffields who still jaunted and were unashamed.

Presteign entered the crenellated keep at, 99 Wall Street, that was Castle Presteign. It was staffed and guarded by his famous Jaunte-Watch, all in clan livery. Presteign walked with the stately gait of a chieftain as they piped him into his office. Indeed, he was grander than a chieftain as an importunate government official awaiting audience discovered to his dismay. The unfortunate man leaped forward from the waiting crowd of petitioners as Presteign passed.

'Mr. Presteign,' he began. 'I'm from the Internal Revenue Department, I must see you this morn-' Presteign cut him short with an icy stare.

'There are thousands of Presteigns,' he pronounced. 'All are addressed as Mister. But I am Presteign of Presteign, head of house and sept, first of the family, chieftain of the clan. I am addressed as Presteign' Not "Mister" Presteign. Presteign.'

He turned and entered his office where his staff greeted him with a muted chorus: 'Good morning, Presteign.' Presteign nodded, smiled his basilisk smile and seated himself behind the enthroned desk while the Jaunte-Watch skirled their pipes and ruffled their drums. Presteign signaled for the audience to begin. Presteign disdained memo-beads and all mechanical business devices.

'Report on Clan Presteign enterprises,' the Equerry began. 'Common Stick: High-201 1/2, Low-201 1/4. Average quotations New York, Paris, Ceylon, Tokyo -'

Presteign waved his hand irritably. The Equerry retired to be replaced by Black Rod.

'Another Mr. Presto to be invested, Presteign.' Presteign restrained his impatience and went through the tedious ceremony of swearing in the 497th Mr. Presto in the hierarchy of Presteign Prestos who managed the shops in the Presteign retail division. Until recently the man had had a face and body of his own. Now, after ten years of cautious testing and careful introductions, he had elected to join the Prestos.

After six months of surgery and psycho-conditioning, he was identical to the other Mr. Prestos and to the idealized portrait of Mr. Presto which hung behind Presteign's dais . . . a kindly, honest man resembling Abraham Lincoln, a man yon must love and trust. No matter where you bought around the world, you entered the identical Presteign store and were fathered by the identical manager, Mr. Presto. He was rivaled, but not surpassed, by the Kodak clan's Mr. Kwik and Montgomery Ward's Uncle Monty.

When the ceremony was completed, Presteign arose abruptly to indicate that the public audience was ended. The office was cleared of all but the high officials. Presteign paced, obviously repressing his seething impatience. He never swore, but his restraint was more terrifying than profanity.

'Foyle,' he said in a suffocated voice. 'A common sailor. Dirt. Dregs. Gutter scum. And I am Presteign of Presteign. But that man stands between me and -'

'If you please, Presteign,' Black Rod interrupted timidly. 'It's eleven o'clock Eastern time; eight o'clock Pacific time.'

'What?

'If you please, Presteign, I remind you that there is a launching ceremony at nine, Pacific time. You are to preside at the Vancouver shipyards.'

'Launching? 'Our new freighter, the Presteign Princess. It will take some time to establish three-dimensional broadcast contact with the shipyard so we had better -'

'I will attend in person.'

'In person!' Black Rod faltered.

'But we cannot possibly fly to Vancouver in an hour, Presteign. We -'

'I will jaunte,' Presteign of Presteign snapped. Such was his agitation.

His appalled staff made hasty preparations. Messengers jaunted ahead to warn the Presteign offices across the country, and the private jaunte stages were cleared. Presteign was ushered to the stage within his New York office. It was a circular platform in a black-hung room without windows. This masking and concealment was necessary to prevent unauthorized persons from discovering and memorizing its co-ordinates. For the same reason, all homes and offices had one-way windows and confusion labyrinths behind their doors.

To jaunte it was necessary (among other things) to know exactly where you were, and where you were going, or you had no hope of arriving alive anywhere. It was as impossible to jaunte from an undetermined starting point as it was to arrive at an unknown destination. Like shooting a pistol, you had to know where to aim and which end of the gun to hold. But a glance through a window or door might be enough to enable a man to memorize the L-E-S co-ordinates of a place.

Presteign stepped on the stage, visualized the co-ordinates of his destination in the Philadelphia office, seeing the picture clearly and the position accurately. He relaxed and energized one concentrated thrust of will and belief towards the target. He jaunted. There was a dizzy moment in which his eyes blurred. The New York stage faded out of focus; the Philadelphia stage blurred into focus. There was a sensation of falling down, and then up. He arrived. Black Rod and other of his staff arrived a respectful moment later.

So, in jauntes of one and two hundred miles each, Presteign crossed the continent, and arrived outside the Vancouver shipping yards at exactly nine o'clock in the morning, Pacific time. He had left New York at eleven a.m. He had gained two hours of daylight. This, too, was a commonplace in a jaunting world.

The square mile of unfenced concrete (what fence could bar a Jaunter) looked like a white table covered with black pennies neatly arranged in concentric circles. But on closer approach, the pennies enlarged into the hundred-foot mouths of black pits dug deep into the bowels of the earth. Each circular mouth was rimmed with concrete buildings, offices, check-rooms, canteens, changing-rooms.

These were the take-off and landing pits, the dry dock and construction pits of the shipyards. Spaceships, like sailing vessels, were never designed to support their own weight unaided against the drag of gravity. Normal terran gravity would crack the spine of a spaceship like an eggshell. The ships were built in deep pits, standing vertically in a network of catwalks and construction grids, braced and supported by anti-gravity screens. They took off from similar pits, riding the anti-grav beams upward like motes mounting the vertical shaft of a searchlight until at last they reached the Riche Limit and could thrust with their own jets. Landing spacecraft cut drive jets and rode the same beams downwards into the pits.

As the Presteign entourage entered the Vancouver yards they could see which of the pits were in use. From some the noses and hulls of spaceships extruded, raised a quarter-way or half-way above ground by the anti-grav screens as workmen in the pits below brought their aft sections to particular operational levels. Three Presteign V-class transports, Vega, Vestal and Vorga stood partially raised near the centre of the yards, undergoing flaking and replating, as the heat-lighting flicker of torches around Vorga indicated.

At the concrete building marked: ENTRY, the Presteign entourage stopped before a sign that read: YOU ARE ENDANGERING YOUR LIFE IF YOU ENTER THESE PREMISES UNLAWFULLY. YOU HAVE BEEN WARNED! Visitor badges were distributed to the party, and even Presteign of Presteign received a badge. He dutifully pinned it on for he well knew what the result of entry without such a protective badge would be. The entourage continued, winding its way through pits until it arrived at O-3 where the pit-mouth was decorated with bunting in the Presteign colors, and a small grandstand had been erected.

Presteign was welcomed and, in turn, greeted his various officials. The Presteign band struck up tie clan song, bright and brassy, but one of the instruments appeared to have gone insane. It struck a brazen note that blared louder and louder until it engulfed the entire band and the surprised exclamations. Only then did Presteign realize that it was not an instrument sounding, but the shipyard alarm.

An intruder was in the yard, someone not wearing an identification or visitor's badge. The radar field of the protection system was tripped and the alarm sounded. Through the raucous bellow of the alarm, Presteign could hear a multitude of 'Pops' as the yard guards jaunted from the grandstand and took positions around the square mile of concrete field. His own Jaunte-Watch closed in around him, looking wary





When Y'ang-Yeovil saw the short blond cadaver with leaden skin and death's-head smile enter the Star Chamber, he knew he was assured of defeat in this encounter. He was no match for the three men together. He arose at once.

'I'm getting an Admiralty order for Foyle,' he said. 'As far as Intelligence is concerned, all negotiations are ended. From now on it's a shooting war.'

'Captain Yeovil is leaving,' Presteign called to the Jaunte-Watch officer who had guided Dagenham in. 'Please see him out through the maze.'

Y'ang-Yeovil waited until the officers stepped alongside him and bowed. Then, as the man courteously motioned to the door, Y'ang-Yeovil looked directly at Presteign, smiled ironically and disappeared with a faint Pop!

'Presteign!' Bunny exclaimed. 'He jaunted. This room isn't blind to him. He -'

'Evidently,' Presteign said icily. 'Inform the Master of the Household,' he instructed the amazed Watch officer. 'The coordinates of the Star Chamber are no longer secret. They must be changed within twenty-four hours. And now, Mr. Dagenham.

'One minute,' Dagenham said. 'There's that Admiralty order.' Without apology or explanation he disappeared too. Presteign raised his eyebrows. 'Another party to the Star Chamber secret,' he murmured. 'But at least he had the tact to conceal his knowledge until the secret was out' Dagenham reappeared. 'No point in wasting time going through the motions of the maze,' he said. ' I've given orders in Washington. They'll hold Yeovil up; two hours guaranteed, three hours probably, four hours possible.' 'How will they hold him up?' Bunny asked.

Dagenham gave him his deadly smile. 'Standard F.F.C.C. Operation of Dagenham Couriers. Fun, fantasy, confusion, catastrophe . . . We'll need all four hours. Damn! I've disrupted your dolls, Presteign.' The robots were suddenly capering in lunatic fashion as Dagenham's hard radiation penetrated their electronic systems. 'No matter, I'll be on my way.'


He appeared in Green Bay, smelling so abominably of singed hair and scorched skin that he entered the local Presteign shop (jewels, perfumes, cosmetics, Tonics and surrogates) to buy a deodorant. But the local Mr. Presto had evidently witnessed the arrival of the Four-Mile Circus and recognized him. Foyle at once awoke from his detached intensity and became the outlandish Fourmyle of Ceres. He clowned and cavorted, bought a twelve-ounce flagon of Euge No. 5 at Cr 500 the ounce, dabbed himself delicately and tossed the bottle into the street to the edification and delight of Mr. Presto.

The Record Clerk at the County Record Office was unaware of Foyle's identity and obdurate and uncompromising.

'No, Sir. County Records Are Not Viewed Without Proper Court Order For Sufficient Cause. That Is My Final Word.'

Foyle examined him keenly and without rancor. 'Asthenic type,' he decided. 'Slender, long-boned, no strength. Epileptoid character. Self-centered, pedantic, single-minded, shallow. Not bribable; too repressed and straitlaced. But repression's the chink in his armor.'

An hour later six followers from the Four-Mile Circus waylaid the Record Clerk. They were of the female persuasion and richly endowed with vice. Two hours late, the Record Clerk, dazed by flesh and the devil, delivered up his information. The apartment building had been opened to Jack-jaunting by a gas explosion two weeks previous. All tenants had been forced to move. Robin Wednesbury was in protective confinement in Mercy Hospital near the Iron Mountain Proving Grounds.

'Protective confinement?'

Foyle wondered. 'What for? What's she done?'

It took thirty minutes to organize a Christmas Party in the Four-Mile Circus. It was made up of musicians, singers, actors and rabble who knew the Iron Mountain co-ordinates. Led by their chief buffoon, they jaunted up with music, fireworks, firewater, and gifts. They paraded through the town spreading largesse and laughter. They blundered into the radar field of the Proving Ground protection system and were driven out with laughter. Fourmyle of Ceres, dressed as Santa Claus, scattering banknotes from a huge sack over his shoulder and leaping in agony as the induction field of the protection system burned his bottom, made an entrancing spectacle. They burst into Mercy Hospital, following Santa Claus who roared and cavorted with the detached calm of a solemn elephant. He kissed the nurses, made drunk the attendants, pestered the patients with gifts, littered the corridors with money, and abruptly disappeared when the happy rioting reached such heights that the police had to be called. Much later it was discovered that a patient had disappeared too, despite the fact that she had been under sedation and was incapable of jaunting. As a matter of fact she departed from the hospital inside Santa's sack.

Foyle jaunted with her over his shoulder to the hospital grounds. There, in a quiet grove of pines under a frosty sky, he helped her out of the sack. She wore severe white hospital pajamas and was beautiful. He removed his own costume, watching the girl intently, waiting to see if she would recognize him and remember him.

She was alarmed and confused; her telesending was like heat-lightning: 'My God! Who is he? What's happened? Jacks again? Murder, this time? The music. The uproar. Why kidnapped in a sack? Drunks slurring on trombones. " Yes. Virginia, there is a Santa Claus." Adeste Fidelis. There go rockets. Feu de joi or feu d'enfer? What's he want from me? Who is he?'

'I'm Fourmyle of Ceres,' Foyle said.

'What? Who? Fourmyle of -? Yes, of course. The buffoon. The bourgeois gentilhomme. Vulgarity. Imbecility. Obscenity. The Four Mile Circus. My God! Am I telesending? Can you hear me?'

'I hear you, Miss Wednesbury,' Foyle said quietly.

'What have you done? Why? What do you want with me? I-'

'I want you to look at me.'

'Bonjour, Madame. Into my sack, Madame. Ecco! Look at me. I'm looking,' Robin said, trying to control the jangle of her thoughts. She gazed up into his face without recognition. 'It's a face. I've seen so many like it. The faces of men, oh God! The features of masculinity. Everyman in rut. Will God never save us from brute's desire?'

'My rutting season's over, Miss Wednesbury.'

'I'm sorry you heard that. I'm terrified, naturally. I - You know me?'

'I know you.'

'We've met before?'

She scrutinized him closely, but still without recognition. Deep down inside Foyle there was a surge of triumph. If this woman of all women failed to remember him he was safe, provided he kept blood and brains and face under control.

'We've never met,' he said. 'I've heard of you. I want something from you. That's why we're here; to talk about it. If you don't like my offer you can go back to the hospital.'

'You want something? But I've got nothing . . . nothing, nothing. Nothing's left but shame and - Oh God! Why did the suicide fail? Why couldn't I-'

'So that's it?' Foyle interrupted softly. 'You tried to commit suicide, eh? That accounts for the gas explosion that opened the building . . . And your protective confinement. Attempted suicide. Why weren't you hurt in the explosion?'

'So many were hurt. So many died. But I didn't. I'm unlucky, I suppose. I've been unlucky all my life.'

'Why suicide?'

'I'm tired. I'm finished. I've lost everything . . . I'm on the army greylist . . . suspected, watched, reported. No job. No family. No - Why suicide? Dear God, what else but suicide?'

'You can work for me.'

'I can . . . What did you say?'

'I want you to work for me, Miss Wednesbury.'

She burst into hysterical laughter. 'For you? Another camp-follower. Another Whore of Babylon in the Circus. Work for you, Fourmyle?'

'You've got sex on the brain,' he said gently. 'I'm not looking for tarts. They look for me, as a rule.'

'I'm sorry. I'm obsessed by the brute who destroyed me. I - I'll try to make sense.' Robin calmed herself. 'Let me understand you. You've taken me out of the hospital to offer me a job. You've heard of me. That means you want something special. My specialty is telesending.'

'And charm.'

'What?'

'I want to buy your charm, Miss Wednesbury.'

'I don't understand.'

'Why,' Foyle said mildly. 'It ought to be simple for you. I'm the buffoon. I'm vulgarity, imbecility, obscenity. That's got to stop. I want you to be my social secretary.'

'You expect me to believe that? You could hire a hundred social secretaries . . . a thousand, with your money. You expect me to believe that I'm the only one for you? That you had to kidnap me from protective confinement to get me?'

Foyle nodded. 'That's right, there are thousands, but only one that can telesend.'

'What's that got to do with it?'

'You're going to be the ventriloquist; I'm going to be your dummy. I don't know the upper classes; you do. They have their own talk, their own joker, their own manners. If a man wants to be accepted by them he's got to talk their language. I can't, but you can. You'll talk for me, through my mouth. . .

'But you could learn.'

'No. It would take too long. And charm can't be learned. I want to buy your charm, Miss Wednesbury. Now, about salary. I'll pay you a thousand a month.'

Her eyes widened. 'You're very generous, Fourmyle.'

'I'll clean up this suicide rap for you.'

'You're very kind.'

'And I'll guarantee to get you off the army greylist. You'll be back on the whitelist by the time you finish working for me. You can start with a clean slate and a bonus. You can start living again.'

Robin's lips trembled and then she began to cry. She sobbed and shook and Foyle had to steady her. 'Well,' he asked. 'Will you do it?'

She nodded. 'You're so kind . . . It's . . . I'm not used to kindness any more.'

The dull concussion of a distant explosion made Foyle stiffen.

'Christ!' he exclaimed in sudden panic. 'Another Blue jaunte. I -'

'No,' Robin said. 'I don't know what blue jaunte is, but that's the Proving Ground. They -' She looked up at Foyle's face and screamed. The unexpected shock of the explosion and the vivid chain of associations had wrenched loose his iron control. The blood-red scars of tattooing showed under his skin. She stared at him in horror, still screaming.

He touched his face once, then leaped forward and gagged her. Once again he had hold of himself.

'It shows, eh?' he murmured with a ghastly smile.

'Lost my grip for a minute. Thought I was back in Gouffre Martel listening to a Blue jaunte. Yes, I'm Foyle. The brute who destroyed you. You had to know, sooner or later, but I'd hoped it would be later. I'm Foyle, back again. Will you be quiet and listen to me?'

She shook her head frantically, trying to struggle out of his grasp. With detached calm he punched her jaw. Robin sagged. Foyle picked her up, wrapped her in his coat and held her in his arms, waiting for consciousness to return. When he saw her eyelids flutter he spoke again.

'Don't move or you'll be sick. Maybe I didn't pull that punch enough.'

'Brute . . . Beast. .'

'I could do this the wrong way,' he said. 'I could blackmail you. I know your mother and sisters are on Callisto, that you're classed as an alien belligerent by association. That puts you on the blacklist, ipso facto. Is that right? Ipso facto. "By the very fact." Latin. You can't trust hypno-learning. I could point out that all I have to do is send anonymous information to Central Intelligence and you wouldn't be just suspect any more. They'd be ripping information out of you inside twelve hours. . .'

He felt her shudder. 'But I'm not going to do it that way. I'm going to tell you the truth because I want to turn you into a partner. Your mother's in the Inner Planets. She's in the Inner Planets,' he repeated. 'She may be on Earth.'

'Safe?' she whispered.

'I don't know.'

'Put me down.'

'You're cold.'

'Put me down.'

He set her on her feet.

'You destroyed me once,' she said in choked tones. 'Are you trying to destroy me again?'

'No. Will you listen?' She nodded.

'I was lost in space. I was dead and rotting for six months. A ship came up that could have saved me. It passed me by. It let me die. A ship named Vorga. Vorga-T: 1339. Does that mean anything to you?'

'No.'

'Jiz McQueen - A friend of mine who's dead now once told me to find out why I was left to rot. That would be the answer to who gave the order. So I started buying information about Vorga. Any information.'

'What's that to do with my mother?'

'Just listen. Information was tough to buy. The Vorga records were removed from the Bo'ness and Uig files. I managed to locate three names . . . three out of a standard crew of four officers and twelve men. Nobody knew anything or nobody would talk. And I found this.'

Foyle took a silver locket from his pocket and handed it to Robin. 'It was pawned by some spaceman off the Vorga. That's all I could find out' Robin uttered a cry and opened the locket with trembling fingers. Inside was her picture and the pictures of two other girls. As the locket was opened, the 3D photos smiled and whispered: 'Love from Robin, Mama . . . Love from Holly, Mama... Love from Wendy, Mama . . .'

'It is my mother's,' Robin wept. 'It . . . She . . . For pity's sake, where is she? What happened?'

'I don't know,' Foyle said steadily. 'But I can guess. I think your mother got out of that concentration camp . . . one way or another.'

'And my sisters too. She'd never leave them.'

'Maybe your sisters too. I think Vorga was running refugees out of Callisto. Your family paid with money and jewelry to get aboard and be taken to the Inner Planets. That's how a spaceman off the Vorga came to pawn this locket.'

'Then where are they?'

'I don't know. Maybe they were dumped on Mars or Venus. Most probably they were sold to a labor camp on the Moon, which is why they haven't been able to get in touch with you. I don't know where they are, but Vorga can tell us.'

'Are you lying? Tricking me?'

'Is that locket a lie? I'm telling the truth . . . all the truth I know. I want to find out why they left me to die, and who gave the order. The man who gave the order will know where your mother and sisters are. He'll tell you . . . before I kill him. He'll have plenty of time. He'll be a long time dying.'

Robin looked at him in horror. The passion that gripped him was making his face once again show the scarlet stigmata. He looked like a tiger closing in for the kill.

'I've got a fortune to spend . . . never mind how I got it. I've got three months to finish the job. I've learned enough maths to compute the probabilities. Three months is the outside before they figure that Fourmyle of Ceres is Gully Foyle. Ninety days. From New Year's to All Fools. Will you join me?'

'You?' Robin cried with loathing. 'Join you?'

'All this Four-Mile Circus is camouflage. Nobody ever suspects a clown. But I've been studying, learning, preparing for the finish. All I need now is you.'

'Why?'

'I don't know where the hunt is going to lead me . . . society or slums. I've got to be prepared for both. The slums I can handle alone. I haven't forgotten the gutter; but I need you for society. Will you come in with me?'

'You're hurting me.' Robin wrenched her arm out of Foyle's grasp.

'Sorry. I lose control when I think about Vorga. Will you help me find Vorga and your family?'

'I hate you,' Robin burst out. 'I despise you. You're rotten. You destroy everything you touch. Some day I'll pay you back.'

'But we work together from New Year's to All Fools?'

'We work together.'






On New Year's Eve, Geoffrey Fourmyle of Ceres made his onslaught on society. He appeared first in Canberra at the Government House ball, half an hour before midnight. This was a highly formal affair, bursting with color and pageantry, for it was the custom at formats for society to wear the evening dress that had been fashionable the year its clan was founded or its trademark patented.

Thus, the Morses (Telephones and Telegraph) wore nineteenth-century frock coats and the women wore Victorian hoop-skirts. The Skodas (Powder and Guns) harked back to the late eighteenth century, wearing Regency tights and crinolines. The daring Peenemundes (Rockets and Reactors), dating from the 1920's wore tuxedos, and the women unashamedly revealed legs, arms and necks in the decolletee of antique Worth and Mainbocher gowns.

Fourmyle of Ceres appeared in evening clothes, very modern and very black, relieved only by a white sunburst on his shoulder, the trademark of the Ceres clan. With him was Robin Wednesbury in a glittering white gown, her slender waist tight in whalebone, the bustle of the gown accentuating her long straight back and graceful step.

The black and white contrast was so arresting that an orderly was sent to check the sunburst trademark in the Almanack of Peerages and Patents. He returned with the news that it was of the Ceres Mining Company, organized in 2250 for the exploitation of the mineral resources of Ceres, Pallos and Vesta.

The resources had never manifested themselves and the House of Ceres had gone into eclipse but had never become extinct. Apparently it was now being revived.

'Fourmyle? The clown?'

'Yes. The Four Mile Circus. Everybody's talking about him.'

'Is that the same man?'

'Couldn't be. He looks human.' Society clustered around Fourmyle, curious but wary.

'Here they come,' Foyle muttered to Robin.

'Relax. They want the light touch. They'll accept anything if it's amusing. Stay tuned.' She prompted.

'Are you that dreadful man with the circus, Fourmyle?'

'Sure you are. Smile.' She prompted.

'I am, madam. You may touch me.'

'Why, you actually seem proud. Are you proud of your bad taste?'

'The problem today is to have any taste at all.' She prompted.

'The problem today is to have any taste at all. I think I'm lucky.'

'Lucky but dreadfully indecent.'

'Indecent but not dull.'

'And dreadful but delightful. Why aren't you cavorting now?'

'I'm "under the influence", Madam.'

'Oh dear. Are you drunk? I'm Lady Shrapnel. When will you be sober again?'

'I'm under your influence, Lady Shrapnel.'

'You wicked young man. Charles! Charles, come here and save Fourmyle. I'm ruining him.'

'That's Victor of R.C.A. Victor.' She prompted.

'Fourmyle, is it? Delighted. What's that entourage of yours cost?'

'Tell him the truth.' She prompted.

'Forty thousand, Victor.'

'Good Lord! A week?'

'A day.'

'My God! What on earth d'you want to spend all that money for?'

'The truth!' She prompted.

'For notoriety, Victor.'

'Ha! Are you serious?'

'I told you he was wicked, Charles.'

'Damned refreshing. Klaus! Here a moment. This impudent young man is spending forty thousand a day; for notoriety, if you please.'

'Skoda of Skoda.' She prompted.

'Good evening, Fourmyle. I am much interested in this revival of the name. You are, perhaps, a cadet descendant of the original founding board of Ceres, Inc?'

'Give him the truth.' She prompted.

'No, Skoda, It's a title by purchase. I bought the company. I'm an upstart.'

'Good. Toujours audace!'

'My word, Fourmyle! You're frank.'

'Told you he was impudent. Very refreshing. There's a parcel of damned upstarts about, young man, but they don't, admit it. Elizabeth, come and meet Fourmyle of Ceres.'

'Fourmyle! I've been dying to meet you.'

'Lady Elizabeth Citroen.'

'Is it true you travel with a portable college?'

'The light touch here.' She prompted.

'A portable high school, Lady Elizabeth.'

'But why on earth, Fourmyle?'

'Oh, Madam, it's so difficult to spend money these days. We have to find the silliest excuses. If only someone would invent a new extravagance.'

'You ought to travel with a portable inventor, Fourmyle.'

'I've got one. Haven't I, Robin? But he wastes his time on perpetual motion. What I need is a resident spendthrift. Would any of your clans care to lend me a younger son?'

'Welcome, by God! And there's many a clan would pay for the privilege of unloading.'

'Isn't perpetual motion spendthrift enough for you, Fourmyle?'

'No. It's a shocking waste of money. The whole point of extravagance is to act like a fool and feel like a fool, but enjoy it. Where's the joy in perpetual motion? Is there any extravagance in entropy? Millions for nonsense but not one cent for entropy. That's my slogan.'

They laughed and the crowd clustering around Fourmyle grew. They were delighted and amused. He was a new top. Then it was midnight, and as the great clock tolled in the New Year, the gathering prepared to jaunte with midnight around the world.

'Come with us to Java, Fourmyle. Regis Sheffield's giving a marvelous legal party. We're going to play "Sober The Judge".'

'Hong Kong, Fourmyle.'

'Tokyo, Fourmyle. It's raining in Hong Kong. Come to Tokyo and bring your circus.'

'Thank you, no. Shanghai for me. The Soviet Duomo. I promise an extravagant reward to the first one who discovers the deception of my costume. Meet you all in two hours. Ready, Robin?'

'Don't jaunte. Bad manners. Walk out. Slowly. Languor is chic. Respects to the Governor . . . To the Commissioner . . . Their Ladies . . . Bien. Don't forget to tip the attendants. Not him, idiot! That's the Lieutenant Governor. All right, you made a hit. You're accepted. Now what?'

'Now what we-came to Canberra for.'

'I thought we came for the ball'

'The ball and a man named Forrest.'

'Who's that?'

'Ben Forrest, spaceman off the Vorga. I've got three leads to the man who gave the order to let me die. Three names. A cook in Rome named Poggi; a quack in Shanghai named Orel; and this man, Forrest. This is a combined operation . . . society and search. Understand?'

'I understand.'

'We've got two hours to rip Forrest open. D'you know the co-ordinates of the Aussie Cannery? The Company Town?'

'I don't want any part of your Vorga revenge. I'm searching for my family.'

'This is a combined operation . . . every way,' he said with such detached savagery that she winced and at once jaunted. When Foyle arrived in his tent in the Four-Mile Circus on Jervis Beach, she was already changing into travel clothes. Foyle looked at her. Although he forced her to live in his tent for security reasons, he had never touched her again. Robin caught his glance, stopped changing and waited.

He shook his head. 'That's all finished.'

'How interesting. You've given up rape?'

'Get dressed,' he said, controlling himself. 'Tell them they've got two hours to get the camp up to Shanghai.'

It was twelve-thirty when Foyle and Robin arrived at the front office of the Aussie Cannery company town. They applied for identification tags and were greeted by the mayor himself.

'Happy New Year,' he caroled. 'Happy! Happy! Happy! Visiting? A pleasure to drive you around. Permit me.'

He bundled them into a lush helicopter and took off. 'Lots of visitors tonight. Ours is a friendly town. Friendliest company town in the world.'

The plane circled giant buildings. 'That's our ice palace . . . Swimming baths on the left . . . Big dome is the ski-jump. Snow all year 'round . . . Tropical gardens under that glass roof. Palms, parrot, orchids, fruit. There's our market . . . theatre . . . got our own broadcasting company, too. 3D-SS. Take a look at the football stadium. Two of our boys made All-American this year. Turner at Right Rockne and Kowalsky at Left Heffilfinger.'

'Do tell,' Foyle murmured.

'Yessir, we've got everything. Everything. You don't have to jaunte around the world looking for fun. Aussie Cannery brings the world to you. Our town's a little universe. Happiest little universe in the world.'

'Having absentee problems, I see.'

The mayor refused to falter in his sales-pitch. 'Look down at the streets. See those bikes? Motor-cycles? Cars? We can afford more luxury transportation per capita than any other town on earth. Look at those homes. Mansions. Our people are rich and happy. We keep 'em rich and happy.'

'But do you keep them?'

'What d'you mean? Of course we -'

'You can tell us the truth. We're not job prospects. Do you keep them?'

'Christ, we can't keep 'em more than six months,' the mayor groaned. 'It's a hell of a headache, Mac. We give 'em everything but we can't hold on to 'em. They get the wanderlust and jaunte. Absenteeism's cut our production by twelve per cent. We can't hold on to steady labor.'

'Nobody can.'

'There ought to be a law. Forrest, you said? Right here.'

He landed them before a Swiss chalet set in an acre of gardens and took off, mumbling to himself. Foyle and Robin stepped before the door of the house, waiting for the monitor to pick them up and announce them. Instead, the door flashed red, and a white skull and crossbones appeared on it. A canned voice spoke:

'WARNING. THIS RESIDENCE IS MANTRAPPED BY THE LETHAL DEFENSE CORPORATION OF SWEDEN. R: 77-23. YOU HAVE BEEN LEGALLY NOTIFIED.'

'What the hell?' Foyle muttered. 'On New Year's Eve? Friendly fella. Let's try the back.'

They walked around the chalet, pursued by the skull and crossbones flashing at intervals, and the canned warning. At one side, they saw the top of a cellar window brightly illuminated and heard the muffled chant of voices: 'The Lord is my shepherd, I shall not want . . .

'Cellar-Christians!'

Foyle exclaimed. He and Robin peered through the window. Thirty worshippers of assorted faiths were celebrating the New Year with a combined and highly illegal service. The twenty-fourth century had not yet abolished God, but it had abolished organized religion.

'No wonder the house is man-trapped,' Foyle said. 'Filthy practices like that. Look, they've got a priest and a rabbi, and that thing behind them is a crucifix.'

'Did you ever stop to think what swearing is?' Robin asked quietly. 'You say "Jesus" and "Jesus Christ", you know what that is?'

'Just swearing, that's all. Like "Ouch" or "Pshaw'

'No, it's religion. You don't know it, but there are two thousand years of meaning behind words like that'

'This is no time for dirty talk,' Foyle said impatiently. 'Save it for later. Come on.'

The rear of the chalet was a solid wall of glass, the picture window of a dimly lit, empty living-room.

'Down on your face,' Foyle ordered. 'I'm going in.'

Robin lay prone on the marble patio. Foyle triggered his body, accelerated into a lightning blur, and smashed a hole in the glass wall. Far down on the sound spectrum he heard dull concussions. They were shots. Quick projectiles laced towards him. Foyle dropped to the floor and tuned his ears, sweeping from low bass to supersonic until at last he picked up the hum of the Man-Trap control mechanism. He turned his head gently, pin-pointed the location by binaural D/F, wove in through the stream of shots and demolished the mechanism. He decelerated.

'Come in, quick!'

Robin joined him in the living-room, trembling. The Cellar-Christians were pouring up into the house somewhere, emitting the sounds of martyrs.

'Wait here,' Foyle grunted. He accelerated, blurred through the house, located the Cellar-Christians in poses of frozen flight, and sorted through them. He returned to Robin and decelerated.

'None of them is Forrest,' he reported. 'Maybe he's upstairs.

The back way, while they're going out the front. Come on!'

They raced up the back stairs. On the landing they paused to take bearings.

'Have to work fast,' Foyle muttered. 'Between the shots and the religion riot, the world and his wife'll be jaunting around asking questions -' He broke off. A low mewling sound came from a door at the head of the stairs. Foyle sniffed.

'Analogue!' he exclaimed. 'Must be Forrest. How about that? Religion in the cellar and dope upstairs.'

'What are you talking about?'

'I'll explain later. In here. I only hope he isn't on a gorilla kick.'

Foyle went through the door like a diesel tractor. They were in a large, bare room. A heavy rope was suspended from the ceiling. A naked man was entwined with the rope midway in the air. He squirmed up and down the rope, emitting a mewling sound and a musky odor.

'Python,' Foyle said. 'That's a break. Don't go near him. He'll mash your bones if he touches you.'

Voices below began to call: 'Forrest! What's all the shooting? Happy New Year, Forrest! Where in hell's the celebration?'

'Here they come,' Foyle grunted. 'Have to jaunte him out of here. Meet you back at the beach. Go.'

He whipped a knife out of his pocket, cut the rope, swung the squirming man to his back and jaunted. Robin was on the empty Jervis beach a moment before him. Foyle arrived with the squirming man oozing over his neck and shoulders like a python, crushing him in a terrifying embrace. The red stigmata suddenly bursts out on Foyle's face.



Presteign of Presteign's Mansion in Central Park was ablaze for the New Year. Charming antique electric bulbs with zigzag filaments and pointed tips shed yellow light. The jaunte-proof maze had been removed and the great door was open for the special occasion. The interior of the house was protected from the gaze of the crowd outside by a jeweled screen just inside the door.

The sightseers buzzed and exclaimed as the famous and near-famous of clan and sept arrived by car, by coach, by litter, by every form of luxurious transportation. Presteign of Presteign himself stood before the door, iron-grey, handsome, smiling his basilisk smile, and welcomed society to his open house. Hardly had a celebrity stepped through the door and disappeared behind the screen when another, even more famous, came clattering up in a vehicle even more fabulous.

The Colas arrived in a bandwagon. The Esso family (six sons, three daughters) was magnificent in a glass-topped Greyhound Bus. But Greyhound arrived (in an Edison Electric Runabout) hard on their heels and there was much laughter and chaffing at the door. But when Edison of Westinghouse dismounted from his Esso-fuelled gasoline buggy, completing the circle, the laughter on the steps turned into a roar.

Just as the crowd of guests turned to enter Presteign's home, a distant commotion attracted their attention. It was a rumble, a fierce chatter of pneumatic punches, and an outrageous metallic bellowing. It approached rapidly. The outer fringe of sightseers opened a broad lane. A heavy truck rumbled down the lane. Six men were tumbling baulks of timber out of the back of the truck. Following them came a crew of twenty arranging the baulks neatly in rows.

Presteign and his guests watched with amazement. A giant machine, bellowing and pounding, approached, crawling over the ties. Behind it were deposited parallel rails of welded steel. Crews with sledges and pneumatic punches spiked the rails to the timber ties. The track was laid to Presteign's door in a sweeping arc and then curved away. The bellowing engine and crews disappeared into the darkness.

'Good God!' Presteign was distinctly heard to say. Guests poured out of the house to watch.

A shrill whistle sounded in the distance. Down the track came a man on a white horse, carrying a large red flag. Behind him panted a steam locomotive drawing a single observation car. The train stopped before Presteign's door. A conductor swung down from the car followed by a Pullman porter. The porter arranged steps. A lady and gentleman in evening clothes descended.

'Shan't be long,' the gentleman told the conductor. 'Come back for me in an hour.'

'Good God!' Presteign exclaimed again.

The train puffed off. The couple mounted the steps.

'Good evening, Presteign,' the gentleman said. 'Terribly sorry about that horse messing up your grounds, but the old New York franchise still insists on the red flag in front of trains.'

'Fourmyle!' the guests shouted.

'Fourmyle of Ceres!' the sightseers cheered. Presteign's party was now an assured success.

Inside the vast velvet and plush reception hall, Presteign examined Fourmyle curiously. Foyle endured the keen iron-grey gaze with equanimity, meanwhile nodding and smiling to the enthusiastic admirers he had acquired from Canberra to New York.

'Control,' he thought. 'Blood, bowels and brain. He grilled me in his office for one hour after that crazy attempt I made on Vorga. Will he recognize me? Your face is familiar, Presteign,' Fourmyle said. 'Have we met before?'

'I have not had the honor of meeting a Fourmyle until tonight,' Presteign answered ambiguously. Foyle had trained himself to read men, but Presteign's hard, handsome face was inscrutable. Standing face to face, the one detached and compelled, the other reserved and indomitable, they looked like a pair of brazen statues at white heat on the verge of molten.

'I'm told that you boast of being an upstart, Fourmyle'

'Yes. I've patterned myself after the first Presteign'

'Indeed?'

'You will remember that he boasted of starting the family fortune in the plasma black market during the Third World War.'

'It was the second war, Fourmyle. But the hypocrites of our clan never acknowledge him. The name was Payne then.'

'I hadn't known.'

'And what was your unhappy name before you changed it to Fourmyle?'

'It was Presteign.'

'Indeed?' The basilisk smile acknowledged the hit. 'You claim a relationship with our clan?'

'I will claim it in time.'

'Of what degree?'

'Let's say . . . a blood relationship'

'How interesting. I detect a certain fascination for blood in you, Fourmyle'

'No doubt a family weakness, Presteign'

'You're pleased to be cynical,' Presteign said, not without cynicism, 'but you speak the truth. We have always had a fatal weakness for blood and money. It is our vice. I admit it.'

'And I share it.'

'A passion for blood and money?'

'Indeed I do. Most passionately.'

'Without mercy, without forgiveness, without hypocrisy?'

'Without mercy, without forgiveness, without hypocrisy.'

'Fourmyle, you are a young man after my own heart. If you do not claim a relationship with our clan I shall be forced to adopt you.'

'You're too late, Presteign. I've already adopted you.'

Presteign took Foyle's arm. 'You must be presented to my daughter, Lady Olivia. Will you allow me?'

They crossed the reception hall. Triumph surged within Foyle: He doesn't know. He'll never know. Then doubt came: But I'll never know if he does know. He's crucible steel. He could teach me a thing or two about control.

Acquaintances hailed Fourmyle.

'Wonderful deception you worked in Shanghai.'

'Marvelous carnival in Rome, wasn't it? Did you hear about the burning man who appeared on the Spanish Stairs?'

'We looked for you in London.'

'What a heavenly entrance that was,' Harry Sherwin-Williams called. 'Outdid us all, by God. Made us look like a pack of damned pikers.'

'You forget yourself, Harry,' Presteign said coldly. 'You know I permit no profanity in my home.'

'Sorry, Presteign. Where's the circus now, Fourmyle?'

'I don't know,' Foyle said. 'Just a moment.'

A crowd gathered, grinning in anticipation of the latest Fourmyle folly. He took out a platinum watch and snapped open the case. The face of a valet appeared on the dial.

'Ahhh . . . whatever your name is . . . Where are we staying just now?'

The answer was tiny and tinny. 'You gave orders to make New York your permanent residence, Fourmyle.'

'Oh? Did I? And?'

'We bought St Patrick's Cathedral, Fourmyle.'

'And where is that?'

'Old St Patrick's, Fourmyle. On Fifth Avenue and what was formerly Both Street. We've pitched the camp inside.'

'Thank you.'

Fourmyle closed the platinum Hunter. 'My address is Old St Patrick's, New York: There's one thing to be said for the outlawed religions . . . At least they built churches big enough to house a circus.'

Olivia Presteign was seated on a dais, surrounded by admirers. She was a Snow-Maiden, an Ice Princess with coral eyes and coral lips, imperious, unattainable, beautiful. Foyle looked at her once and lowered his eyes in confusion before her blind gaze that could only see electromagnetic waves and infra-red light. His heart began to beat faster.

'Don't be a fool!' he thought desperately. 'Control yourself. This can be dangerous. .

He was introduced; was addressed in a husky, silvery voice; was given a cool, slim hand; but the hand seemed to explode in his with an electric shock. It was almost a start of mutual recognition.

'Of what? She's a symbol. The Dream Princess . . . The Unattainable . . . Control!'

He was fighting so hard that he scarcely realized he had been dismissed, graciously and indifferently. He could not believe it. He stood, gaping like a lout.

'What? Are you still here, Fourmyle?'

'I couldn't believe I'd been dismissed, Lady Olivia.'

'Hardly that, but I'm afraid you are in the way of my friends.'

'I'm not used to being dismissed. (No. No. All wrong.) At least by someone I'd like to count as a fiend.'

'Don't be tedious, Fourmyle. Do step down.'

'How have I offended you?'

'Offended me? Now you're being ridiculous.'

'Lady Olivia . . . (Christ! Can't I say anything right? Where's Robin?) Can we start again, please?'

'If you're trying to be gauche, Fourmyle, you're succeeding admirably.'

'Your hand again, please. Thank you. I'm Fourmyle of Ceres.'

'All right.' She laughed. 'I'll concede you're a clown. Now do step down. I'm sure you can find someone to amuse.'

'What's happened this time?'

'Really, sir, are you trying to make me angry?'

'No. (Yes, I am. Trying to touch you somehow . . . cut through the ice.) The first time our handclasp was . . . violent. Now it's nothing. What happened?'

'Fourmyle,' Olivia said wearily, 'I'll concede that you're amusing, original, witty, fascinating . . . anything, if you will only go away.'

He stumbled off the dais. 'Bitch. Bitch. Bitch. No. She's the dream just as I dreamed her. The icy pinnacle to be stormed and taken. To lay siege... invade... ravish . . . force to her knees ....'

He came face to face with Saul Dagenham.

He stood paralyzed, coercing blood and bowels.

'Ali, Fourmyle,' Presteign said. 'This is Saul Dagenham. He can only give us thirty minutes and he insists on spending one of them with you.'

Does he know? Did he send for Dagenham to make sure? Attack. Toujours audace.

'What happened to your face, Dagenham?' Fourmyle asked with detached curiosity.

The death's-head smiled. 'And I thought I was famous. Radiation poisoning. I'm hot. Time was when they said "Hotter than a pistol". Now they say "Hotter than Dagenham": The deadly eyes raked Foyle. 'What's behind that circus of yours?'

'A passion for notoriety.'

'I'm an old hand at camouflage myself. I recognize the signs. What's your larceny?'

'Does Dillinger tell Capone?'

Foyle smiled back, beginning to relax, restraining his triumph, 'I've outfaced them both. You look happier, Dagenham.'

Instantly he realized the slip.

Dagenham picked it up in a flash. 'Happier than when? Where did we meet before?'

'Not happier than when; happier than me.'

Foyle turned to Presteign. 'I've fallen desperately in love with Lady Olivia! ' Saul, your half hour's up.'

Dagenham and Presteign, on either side of Foyle, turned. A tall woman approached, stately in an emerald evening gown, her red hair gleaming. It was Jisbella McQueen. Their glances met. Before the shock could seethe into his face, Foyle turned, ran six steps to the first door he saw, opened it and darted through.

The door slammed behind him. He was in a short, blind corridor. There was a click, a pause, and then a canned voice spoke courteously: 'You have invaded a private portion of this residence. Please retire.'

Foyle gasped and struggled with himself.

'You have invaded a private portion of this residence. Please retire.' 'I never knew . . . Thought she was killed out there . . . She recognized me. .

'You have invaded a private portion of this residence. Please retire.'

'I'm finished . . . She'll never forgive me . . . Must be telling Dagenham and Presteign now.'

The door from the Reception Hall opened, and for a moment Foyle thought he saw his flaming image. Then he realized he was looking at Jisbella's flaming hair. She made no move, just stood and smiled at him in furious triumph. He straightened.

'By God, I won't go down whining.'

Without haste, Foyle sauntered out of the corridor, took Jisbella's arm and led her back to the reception hall. He never bothered to look around for Dagenham or Presteign. They would present themselves, with force and arms, in due time. He smiled at Jisbella; she smiled back, still in triumph.

'Thanks for running away, Gully. I never dreamed it could be so satisfying.'

'Running away? My dear Jiz!'

'Well?'

'I can't tell you how lovely you're looking tonight. We've come a long way from Gouffre Martel, haven't we?' Foyle motioned to the ballroom. 'Dance?'

Her eyes widened in surprise at his composure. She permitted him to escort her to the ballroom and take her in his firms.

'By the way, Jiz, how did you manage to keep out of Gouffre Martel?'

'Dagenham arranged it. So you dance now, Gully?'

'I dance, speak four languages miserably, study science and philosophy, write pitiful poetry, blow myself up with idiotic experiments, fence like a fool, box like a buffoon . . . In short, I'm the notorious Fourmyle of Ceres'

'No longer Gully Foyle.'

'Only to you, dear, and whoever you've told.'

'Just Dagenham. Are you sorry I blew it?'

'You couldn't help yourself any more than I could.'

'No, I couldn't. Your name just popped out of me. What would you have paid to keep my mouth shut?'

'Don't be a fool, Jiz. This accident's going to earn you about Cr 17,980,000.'

'What d'you mean?'

'I told you I'd give you whatever was left over after I finished Vorga.'

'You've finished Vorga?' she said in surprise.

'No, dear, you've finished me. But I'll keep my promise.'

She laughed. 'Generous Gully Foyle. Be real generous. Gully. Make a run for it. Entertain me a little.'

'Squealing like a rat? I don't know how, Jiz. I'm trained for hunting; nothing else.'

'And I killed the tiger. Give me one satisfaction, Gully. Say you were close to Vorga. I ruined you when you were half step from the finish. Yes?'

'I wish I could, Jiz, but I can't. I'm nowhere. I was trying to pick up another lead here tonight.'

'Poor Gully. Maybe I can help you out of this jam. I can say . . . oh . . . that I made a mistake . . . or a joke . . . that you really aren't Gully Foyle. I know how to confuse Saul. I can do it, Gully . . . if you still love me.'

He looked down at her and shook his head. 'It's never been love between us, Jiz. You know that. I'm too one-track to be anything but a hunter.'

'Too one-track to be anything but a fool!'

'What did you mean, Jiz. . . "Dagenham arranged to keep you out of Gouffre Martel". . : 'You know how to confuse Saul Dagenham"? What have you got to do with him?'

'I work for him. I'm one of his couriers.'

'You mean he's blackmailing you? Threatening to send you back if you don't. .

'No. We hit it off the minute we met. He started off capturing me; I ended up capturing him.'

'How do you mean?'

'Can't you guess?'

He started at her. Her eyes were veiled, but he understood. 'Jiz! With him?'

'Yes.'

'But how? He 'There are precautions. It's . . . I don't want to talk about it, Gully.'

'Sorry. He's a long time returning.'

'Returning?'

'Dagenham. With his army.'

'Oh. Yes of course.' Jisbella laughed again, then spoke in a low, furious tone. 'You don't know what a tightrope you've been walking, Gully. If you'd begged or bribed or tried to romance me . . . By God, I'd have ruined you. I'd have told the world who you were . . . Screamed it from the housetops'

'What are you talking about?'

'Saul isn't returning. He doesn't know. You can go to hell on your own.'

'I don't believe you.'

'D'you think it would take him this long to get you? Saul Dagenham?'

'But why didn't you tell him? After the way I ran out on you . . . .'

'Because I don't want him going to hell with you. I'm not talking about Vorga. I mean something else, PyrE. That's why they hunted you. That's what they're after. Twenty pounds of PyrE.'

'What's that?'

'When you got the safe open was there a small box in it? Made of I.L.I. . . Inter Lead Isomer?'

'Yes.'

'What was inside the I.L.I. box?'

'Twenty slugs that looked like compressed iodine crystals.'

'What did you do with the slugs?'

'Sent two out for analysis. No one could find out what they are. I'm trying to run an analysis on a third in my lab . . . when I'm not clowning for the public.'

'Oh, you are, are you? Why?'

'I'm growing up, Jiz.' Foyle said gently. 'It didn't take much to figure out that was what Presteign and Dagenham were after.'

'Where have you got the rest of the slugs?'

'In a safe place.'

'They're not safe. They can't ever be safe. I don't know what PyrE is, but I know it's the road to hell, and I don't want Saul walking it'

'You love him that much?'

'I respect him that much. He's the first man that eves showed me an excuse for the double standard.'

'Jiz, what is PyrE? You know.'

'I've guessed. I've pieced together the hints I've heard. I've got an idea. And I could tell you, Gully, but I won't.' The fiery in her face was luminous. 'I'm running out on you, this time. I'm leaving you to hang helpless in the dark. See what it feels like, boy! Enjoy!'

She broke away from him and swept across the ballroom floor. At that moment the first bombs fell.

They came in like meteor swarms; not so many, but far more deadly. They came in on the morning quadrant, that quarter of the globe in darkness from midnight to dawn. They collided head on with the forward side of the earth in its revolution around the sun. They had been travelling a distance of four hundred million miles.

Their excessive speed was matched by the rapidity of the Terran defense computers, which traced and intercepted these New Year gifts from the Outer Satellites within the space of micro-seconds. A multitude of fierce new stars prickled in the sky and vanished; they were bombs detected and detonated five hundred miles above their target.

But so narrow was the margin between speed of defense and speed of attack that many got through. They shot through the aurora level, the meteor level, the twilight limit, the stratosphere, and down to earth. The invisible trajectories ended in titanic convulsions.

The first atomic explosion which destroyed Newark shook the Presteign mansion with an unbelievable quake. Floors and walls shuddered and the guests were thrown in heaps along with furniture and decorations. Quake followed quake as the random shower descended around New York. They were deafening, numbing, chilling. The sounds, the shocks, the flares of lurid light on the horizon were so enormous, that reason was stripped from humanity, leaving nothing but flayed animals to shriek, cower and run. Within the space of five seconds Presteign's New Year party was transformed from elegance into anarchy.

Foyle arose from the floor. He looked at the struggling bodies on the ballroom parquet, saw Jisbella fighting to free herself, took a step towards her and then stopped. He revolved his head, dazedly, feeling it was no part of him. The thunder never ceased. He saw Robin Wednesbury in the reception hall, reeling and battered. He took a step towards her and then stopped again. He knew where he must go.

He accelerated. The thunder and lightning dropped down the spectrum to grinding and flickering. The shuddering quakes turned into greasy undulations. Foyle blurred through the giant house, searching, until at last he found her, standing in the garden, standing tiptoe on a marble bench looking like a marble statue to his accelerated senses . . . the state of exaltation.

He decelerated. Sensation leaped up the spectrum again and once more he was buffeted by that bigger-than-death size bombardment.

'Lady Olivia,' he called.

'Who is that?'

'The clown.'

'Fourmyle?'

'Yes.'

'And you came searching for me? I'm touched, really touched.'

'You're insane to be standing out here like this. I beg you to let me '

'No, no, no. It's beautiful . . . Magnificent!'

'Let me jaunte with you to some place that's safe.'

'Ali, you see yourself as a knight in armor? Chivalry to the rescue. It doesn't suit you, my dear. You haven't the flair for it. You'd best go.'

'I'll stay.'

'As a beauty-lover?'

'As a lover.'

'You're still tedious, Fourmyle. Come, be inspired. This is Armageddon . . . Flowering Monstrosity. Tell me what you see.'

'There's nothing much,' he answered, looking around and wincing. 'There's light all over the horizon. Quick clouds of it. Above there's a . . . a sort of sparkling effect. Like Christmas lights twinkling.'

'Oh, you see so little with your eyes. See what I see! There's a dome in the sky, a rainbow dome. The colors run from deep tang to brilliant burn. That's what I've named the colors I see. What would that dome be?'

'The radar screen,' Foyle muttered.

'And then there are vast shafts of fire thrusting up and swaying, weaving, dancing, sweeping. What are they?'

'Interceptor beams. You're seeing the whole electronic defense system.'

'And I can see the bombs coming down too. . , quick streaks of what you call red. But not your red; mine. Why can I see them?'

'They're heated by air friction, but the inert lead casing doesn't show the color to us.'

'See how much better you're doing as Galileo than Galahad. Oh! There's one coming down in the east. Watch for it! It's coming, coming, coming . . . Now!'

A flare of light on the eastern horizon proved it was not her imagination.

'There's another to the north. Very close. Very. Now!' A shock tore down from the north.

'And the explosions, Fourmyle . . . They're not just clouds of light. They're fabrics, webs, tapestries of meshing colors. So beautiful. Like exquisite shrouds.'

'Which they are, Lady Olivia.'

'Are you afraid?'

'Yes.'

'Then run away.'

'No.'

'Ah, you're defiant.' 'I don't know what I am. I'm scared, but I won't run.'

'Then you're brazening it out. Making a show of knightly courage.'

The husky voice sounded amused, 'Just think, Galahad. How long does it take to jaunte? You could be safe in seconds, in Mexico, Canada, Alaska. So safe. There must be millions there now. We're probably the last left in the city.'

'Not everybody can jaunte so far and so fast.'

'Then we're the last left who count. Why don't you leave me? Be safe. I'll be killed soon. No one will ever know your pretence turned tail.'

'Bitch!'

'Ah, you're angry. What shocking language. It's the first sign of weakness. Why don't you exercise your better judgement and carry me off? That would be the second sign.'

'Damn you!'

He stepped close to her, clenching his fists in rage. She touched his cheek with a cool, quiet hand, but once again there was that electric shock.

'No, it's too late, my dear,' she said quietly. 'Here comes a whole cluster of red streaks . . . down, down, down, directly at us. There'll be no escaping this. Quick, now! Run! Jaunte! Take me with you. Quick! Quick!'

He swept her off the bench. 'Bitch! Never!'

He held her, found the soft coral mouth and kissed her; bruised her lips with his, waiting for the final blackout.

The concussion never came.

'Tricked!' he exclaimed. She laughed. He kissed her again and at last forced himself to release her. She gasped for breath, then laughed again, her coral eyes blazing, 'It's over,' she said.

'It hasn't begun yet,'

'You mean the war?'

'The war between us.'

'Make it a human war,' she said fiercely. 'You're the first not to be deceived by my looks. Oh God! The boredom of the chivalrous knights and their milk-warm passion for the princess. But I'm not like that . . . inside. I'm not. I'm not. Never. Make it a savage war between us. Don't win me . . . destroy me!'

Suddenly she was Lady Olivia again, the gracious snow maiden. 'I'm afraid the bombardment has finished, my dear Fourmyle. The show is over. But what an exciting prelude to the New Year. Good night.'

'Good night?' he echoed incredulously.

'Good night,' she repeated. 'Really, my dear Fourmyle, are you so gauche that you never know when you're dismissed? You may go now. Good night.'

He hesitated, searched for words, and at last turned and lurched out of the house. He was trembling with elation and confusion. He walked in a daze, scarcely aware of the confusion and disaster around him. The horizon now was lit with the light of red flames. The shock waves of the assault had stirred the atmosphere so violently that winds still whistled in strange gusts. The tremor of the explosions had shaken the city so hard that brick, cornice, glass and metal were tumbling and crashing. And this despite the fact that no direct hit had been made on New York.

The streets were empty; the city was deserted. The entire population of New York, of every city, had jaunted in a desperate search for safety . . . to the limit of their ability . . . five miles, fifty miles, five hundred miles. Some had jaunted into the center of a direct hit. Thousands died in jaunte-explosions, for the public jaunte stages had never been designed to accommodate the crowding of mass exodus.

Foyle became aware of white-armored Disaster Crews appearing on the streets. An imperious signal directed at him warned him that he was about to be summarily drafted for disaster work. The problem of jaunting was not to get populations out of cities, but to force them to return and restore order. Foyle had no intention of spending a week fighting fire and looters. He accelerated and evaded the Disaster Crew






After two centuries of colonization, the air-struggle on Mars was still so critical that the V-L Law, the Vegetative-Lynch Law, was still in effect. It was a killing offence to endanger or destroy any plant vital to the transformation of Mars' carbon dioxide atmosphere into an oxygen atmosphere. Even blades of grass were sacred. There was no need to erect KEEP OFF THE GRASS warnings. The man who wandered off a path on to a lawn would be instantly shot. The woman who picked a flower would be killed without mercy. Two centuries of sudden death had inspired a reverence for green growing things that almost amounted to a religion.




The ancient Sklotsky sect of White Russia, believing that sex was the root of all evil, practiced an atrocious self-castration to extirpate the root. The modern Sklotskys, believing that sensation was the root of all evil, practiced an even more barbaric custom. Having entered the Sklotsky Colony and paid a fortune for the privilege, the initiates submitted joyously to an operation that severed the sensory nervous system, and lived out their days without sight, sound, speech, smell, taste or touch.

When they first entered the monastery, the initiates were shown elegant ivory cells in which it was intimated they would spend the remainder of their lives in rapt contemplation, lovingly tended. In actuality, the senseless creatures were packed in catacombs where they sat on rough stone slabs and were fed and exercised once a day. For twenty-three out of twenty-four hours they sat alone in the dark, untended, unguarded, unloved.

'The living dead,' Foyle muttered. He decelerated, put Sigurd Magsman down, and switched on the retinal light in his eyes, trying to pierce the womb-gloom. It was midnight above ground. It was permanent midnight down in these catacombs. Sigurd Magsman was broadcasting terror and anguish with such a telepathic bray that Foyle was forced to shake the child again.



*** The demolished Man


Like all upper-grade Espers, Lincoln Powell, Ph.D. 1, lived in a private house. It was not a question of conspicuous consumption, but rather a problem of privacy. Although thought transmission was too faint to penetrate masonry, the average plastic apartment unit was too flimsy to block this transmission. Life in any such multiple dwelling was life in an inferno of naked emotion for an Esper.

Powell, the Police Prefect, could afford a small lime-stone maisonette on Hudson Ramp overlooking the North River. There were only four rooms; upstairs a bedroom and study, downstairs a living room and kitchen. There was no servant in the house. Like most upper-grade Espers, Powell required large quantities of solitude. He preferred to do for himself. He was in the kitchen, checking over the refreshment-dials in preparation for the party, whistling a plaintive, crooked tune.

He was a slender man in his late thirties, tall, loose, slow moving. His wide mouth seemed perpetually on the verge of laughter, but at the moment he wore an expression of sad disappointment. He was lecturing himself on the follies and stupidities of his worst vice. The essence of the Esper is his responsiveness. His personality always takes color from his surroundings. The trouble with Powell was an enlarged sense of humor, and his response was invariably exaggerated. He had attacks of what he called "Dishonest Abe" moods. Someone would ask Lincoln Powell an innocent question, and Dishonest Abe would answer. His fervent imagination would cook up the wildest tall-story and he would deliver it with straight-faced sincerity. He could not suppress the liar in him.

Only this afternoon, Police Commissioner Crabbe had inquired about a routine blackmail case, and simply because he'd mispronounced a name, Powell had been inspired to fabricate a dramatic account involving a make-believe crime, a daring midnight raid, and the heroism of an imaginary Lieutenant Kopenick. Now the Commissioner wanted to award Lieutenant Kopenick a medal.

"Dishonest Abe," Powell muttered bitterly. "You give me a stiff pain."



AUGUSTUS TATE, E.M.D. 1, received Cr. 1,000 per hour of analysis... not a high fee considering that a patient rarely required more than an hour of the doctor's devastating time; but it placed his income at Cr. 8,000 a day or well over Cr. 2 million a year. Few people knew what proportion of that income was paid into the Esper Guild for the education of other Telepaths and the furthering of the Guild's Eugenic plan to bring Extra Sensory Perception to everyone in the world.

Augustus Tate knew, and the 95% he paid was a sore point with him. Consequently, he belonged to "The League of Esper Patriots," an extreme right-wing political group within the Guild, dedicated to the preservation of the autocracy and incomes of the upper grade Espers. It was this membership that placed him in Ben Reich's BRIBERY (POTENTIAL) category. Reich marched into Tate's exquisite consultation room, glanced once at Tate's tiny frame  a figure slightly out of proportion but carefully realigned by tailors. Reich sat down and grunted: "Peep me quick."

He glared in concentration at Tate while the elegant little peeper examined him with a glittering eye and spoke in quick bursts: "You're Ben Reich of Monarch. Ten billion credit firm. Think I should know you. I do. You're involved in a death struggle with the D'Courtney Cartel. Right? You're savagely hostile toward D'Courtney. Right? Offered merger this morning. Coded message: YYJI TTED RRCB UUFE AALK QQBA. Offer refused. Right? In desperation you have resolved to" Tate broke off abruptly.

"Go ahead," Reich said.

"To murder Craye D'Courtney as the first step in taking over his cartel. You want my help... Mr. Reich, this is ridiculous! If you keep on thinking like this, I'll have to commit you. You know the law."

"Clever-up, Tate. You're going to help me break the law."

"No, Mr. Reich. I'm not in a position to help you."

"You say that? A 1st Class Esper? And I'm supposed to believe it? I'm supposed to believe you're incapable of outwitting any man, any group, the whole world?"

Tate smiled. "Sugar for the fly," he said. "A characteristic device of"

"Peep me," Reich interrupted. "It'll save time. Read what's in my mind. Your gift. My resources. An unbeatable combination. My God! It's lucky for the world I'm willing to stop at one murder. Together we could rape the universe."

"No," Tate said with decision. "This won't do. I'll have to commit you, Mr. Reich."

"Wait. Want to find out what I'm offering you? Read me deeper. How much am I willing to pay? What's my top limit?"

Tate closed his eyes. His mannequin face tightened painfully. Then his eyes opened in surprise. "You can't be serious," he exclaimed.

"I am," Reich grunted. "And what's more, you know it's an offer in good faith, don't you?"

Tate nodded slowly.

"And you're aware that Monarch plus D'Courtney can make the offer good."

"I almost believe you."

"You can believe me. I've been financing your League of Esper Patriots for five years. If you've peeped me deep enough you know why. I hate the damned Esper Guild as much as you do. Guild ethics are bad for business... lousy for making money. Your League is the organization that can break the Esper Guild some day..."

"I've got all that," Tate said sharply.

"With Monarch and D'Courtney in my pocket I can do better than help your faction break the Guild. I can make you President of a new Esper Guild for life. That's an unconditional guarantee. You can't do it alone, but you can do it with me."

Tate closed his eyes and murmured: "There hasn't been a successful premeditated murder in 79 years. Espers make it impossible to conceal intent before murder. Or, if Espers have been evaded before the murder, they make it impossible to conceal the guilt afterwards."

"Esper evidence isn't admitted in court."

"True, but once an Esper discovers guilt he can always uncover objective evidence to support his peeping. Lincoln Powell, the Prefect of the Police Psychotic Division, is deadly." Tate opened his eyes. "D'you want to forget this conversation?"

"No," Reich growled. "Look it over with me first. Why have murders failed? Because mind-readers patrol the world. What can stop a mind-reader? Another one. But no killer ever had the sense to hire a good peeper to run interference for him; or if he had the sense, he couldn't make the deal. I've made the deal."

"Have you?"

"I'm going to fight a war," Reich continued. "I'm going to fight one sharp skirmish with society. Let's look at it as a problem in strategy and tactics. My problem's simply the problem of any army. Audacity, bravery, and confidence aren't enough. An army needs Intelligence. A war is won with Intelligence. I need you for my G-2."

"Agreed."

"I'll do the fighting. You'll provide the Intelligence. I'll have to know where D'Courtney will be, where I can strike, when I can strike. I'll take care of the killing myself, but you'll have to tell me when and where the opportunity will be."

"Understood."

"I'll have to invade first... cut through the defensive network surrounding D'Courtney. That means reconnaissance from you. You'll have to check the normals, spot the peepers, warn me and block their mind-reading if I can't avoid them. I'll have to retreat after the killing through another network of normals and peepers. You'll have to help me fight a rear-guard action. You'll have to remain on the scene after the murder. You'll find out whom the police suspect and why. If I know suspicion is directed against myself, I can divert it. If I know it's directed against someone else, I can clinch it. I can fight this war and win this war with your Intelligence. Is that the truth? Peep me."



SEVEN DAYS OF COMBAT.

One week of action and reaction, attack and defense, all fought on the surface while deep below the agitated waters Powell and Augustus Tate swam and circled like silent sharks awaiting the onset of the real war.

A patrol officer, now in plainclothes, believed in the surprise attack. He waylaid Maria Beaumont during a theater intermission, and before her horrified friends bellowed: "It was a frame. You were in cahoots with the killer. You set up the murder. That's why you was playin' that Sardine game. Go ahead and answer me."

The Gilt Corpse squawked and ran. As the Rough Tail set off in hot pursuit, he was peeped deeply and thoroughly.



Tate to Reich: The cop was telling the truth. His department believes Maria was an accomplice.

Reich to Tate: All right. We'll throw her to the wolves. Let the cops have her.



In consequence, Madame Beaumont was left unprotected. She took refuge, of all places, in the Loan Brokerage that was the source of the Beaumont fortune. The patrol officer located her there three hours later and subjected her to a merciless grilling in the office of the peeple Credit Supervisor. He was unaware that Lincoln Powell was just outside the office, chatting with the Supervisor.



Powell to staff: She got the game out of some ancient book Reich gave her. Probably purchased at Century. They handle that stuff. Pass the word. Did he ask for it specifically? Also, check Graham, the appraiser. How come the only intact game in the book was 'Sardine'? Old Man Mose'll want to know. And where's that girl?



A traffic officer, now in plainclothes, was going to come through on his Big Chance with the suave approach. To the manager and staff of the Century Audio-bookstore, he drawled: "I'm in the market for old game books... The kind my very good friend, Ben Reich, asked for last week."



Tate to Reich: I've been peeping around. They're going to check that book you sent Maria.

Reich to Tate: Let 'em. I'm covered. I've got to concentrate on that girl.



The manager and staff carefully explained matters at great length in response to the Rough Tail's suave questions. Many clients lost patience and left the store. One sat quietly in a corner, too rapt in a crystal recording to realize he was left unattended. Nobody knew that Jackson Beck was completely tone-deaf.



Powell to staff: Reich apparently found the book accidentally. Stumbled over it while he was looking for a present for Maria Beaumont. Pass the word. And where's that girl?



In conference with the agency that handled copy for the Monarch Jumper ("the only Family Air-Rocket on the market"), Reich came up with a new advertising program.

"Here's the slant," Reich said. "People always anthropomorphize the products they use. They attribute human characteristics to them. They give 'em pet names and treat 'em like family pets. A man would rather buy a Jumper if he can feel affectionate toward it. He doesn't give a damn for efficiency. He wants to love that Jumper."

"Check, Mr. Reich. Check!"

"We're going to anthropomorphize our Jumper," Reich said. "Let's find a girl and vote her the Monarch Jumper Girl. When a consumer buys one, he's buying the girl. When he handles one, he's handling her."

"Check!" the account man cried. "Your idea has a sense of solar scope that dwarfs us, Mr. Reich. This is a wrap-up and blast!"

"Start an immediate campaign to locate the Jumper Girl. Get every salesman onto it. Comb the city. I want the girl to be about twenty-five. About five-five tall; weighing a hundred and twenty pounds. I want her built. Lots of appeal."

"Check, Mr. Reich. Check."

"She ought to be a blonde with dark eyes. Full mouth. Good strong nose. Here's a sketch of my idea of the Jumper Girl. Look it over, have it reproduced and passed out to your crew. There's a promotion for the man who locates the girl I have in mind."



Tate to Reich: I've been peeping the police. They're sending a man into Monarch to dig up collusion between you and that appraiser, Graham.

Reich to Tate: Let 'em. There isn't anything, and Graham's left town on a buying spree. Something between me and Graham! Powell couldn't be that dumb, could he? Maybe I've been overrating him.



Expense was no object to a squadman, now in plainclothes, who believed in the disguises of plastic surgery. Freshly equipped with mongoloid features, he took a job in Monarch Utilities' Accounting-city and attempted to unearth Reich's financial relations with Graham, the appraiser. It never occurred to him that his intent had been peeped by Monarch's Esper Personnel Chief, reported upstairs, and that upstairs was quietly chuckling.



Powell to staff: Our stooge was looking for bribery recorded in Monarch's books. This should lower Reich's opinion of us by fifty per cent; which makes him fifty per cent more vulnerable. Pass the word. Where's that girl?


At the board meeting of "The Hour," the only round-the-clock paper on earth, twenty-four editions a day, Reich announced a new Monarch charity.

"We're calling it 'Sanctuary'," he said. "We offer aid and comfort and sanctuary to the city's submerged millions in their time of crisis. If you've been evicted, bankrupted, terrorized, swindled... If you're frightened, for any reason and don't know where to turn... If you're desperate... Take Sanctuary."

"It's a terriffic promotion," the managing editor said, "but it'll cost like crazy. What's it for?"

"Public Relations," Reich snapped. "I want this to hit the next edition. Jet!"

Reich left the board room, went down to the street and located a public phone booth. He called "Recreation" and gave careful instructions to Ellery West. "I want a man placed in every Sanctuary office in the city. I want a full description and photo of every applicant relayed to me at once. At once, Ellery. As they come in."

"I'm not asking any questions, Ben, but I wish I could peep you on that."

"Suspicious?" Reich snarled.

"No. Just curious."

"Don't let it kill you."

As Reich left the booth, a man clothed in an air of inept eagerness accosted him.

"Oh, Mr. Reich. Lucky I bumped into you. I just heard about Sanctuary and I thought a human interest interview with the originator of this wonderful new charity might"

Lucky he bumped into him! The man was the "Industrial Critic's" famous peeper reporter. Probably tailed him down and  Tenser, said the Tensor. Tenser, said the Tensor. Tension, apprehension, and dissension have begun.

"No comment," Reich mumbled. Eight, sir; seven, sir; six, sir; five, sir...

"What childhood episode in your life brought about the realization of this crying need for"

Four, sir; three, sir; two, sir; one...

"Was there ever a time when you didn't know where to turn? Were you ever afraid of death or murder? Were"

Tenser, said the Tensor. Tenser, said the Tensor. Tension, apprehension, and dissension have begun.

Reich dove into a Public Jumper and escaped.



Tate to Reich: The cops are really after Graham. They've got their entire Lab looking for the appraiser. God knows what kind of red-herring Powell's following, but it's away from you. I think the safety margin's increasing.

Reich to Tate: Not until I've found that girl.



Marcus Graham had left no forwarding address and was pursued by half a dozen impractical tracer-robots dug up by the police lab. They were accompanied by their impractical inventors to various parts of the solar system. In the meantime, Marcus Graham had arrived on Ganymede where Powell located him at an auction of rare primitive books conducted at break-neck speed by a peeper auctioneer. The books had been part of the Drake estate, inherited by Ben Reich from his mother. They had been unexpectedly dumped on the market.

Powell interviewed Graham in the foyer of the auction room, before a crystal port overlooking the arctic tundra of Ganymede with the belted red-brown bulk of Jupiter filling the black sky. Then Powell took the Fortnighter back to Earth, and Dishonest Abe was inspired by a pretty stewardess to disgrace him. Powell was not a happy man when he arrived at headquarters, and Wynken, Blynken, and Nod did some salacious wynking, blynking and nodding.



Powell to staff: No hope. I don't know why Reich even bothered to decoy Graham to Ganymede with that sale.

Beck to Powell: What about the game book?

Powell to Beck: Reich bought it, had it appraised, and sent it as a gift. It was in bad condition and the only game Maria could select was 'Sardine.' We'll never get Mose to pin anything on Reich with that. I know how that machine's mind works. Damn it! Where's that girl!



Three low-grade operatives in succession were smitten with Miss Duffy Wyg& and retired in disgrace to don their uniforms once more. When Powell finally reached her, she was at the "4,000" Ball. Miss Wyg& was delighted to talk.



Powell to staff: I called Ellery West down at Monarch and he supports Miss Wyg&'s story. West did complain about gambling and Reich bought a psych-song to stop it. It looks like he picked up that mind-block by accident. What about that gimmick Reich used on the guards? And what about that girl?



In response to bitter criticism and loud laughter, Commissioner Crabbe gave an exclusive press interview in which he revealed that Police Laboratories had discovered a new investigation technique which would break the D'Courtney Case within 24 hours. It involved photographic analysis of the Visual Purple in the corpse's eyes which would reveal a picture of the murderer. Rhodopsin researchers were being requisitioned by the police.

Unwilling to run the risk of having Wilson Jordon, the physiologist who had developed the Rhodopsin Ionizer for Monarch picked up and questioned by the police, Reich phoned Keno Quizzard and devised a ruse to get Dr. Jordon off the planet.

"I've got an estate on Callisto," Reich said. "I'll relinquish title and let a court throw it up for grabs. I'll make sure the cards are stacked for Jordon."

"And I tell Jordon?" Quizzard asked in his sour voice.

"We won't be that obvious, Keno. We can't leave a back-trail. Call Jordon. Make him suspicious. Let him find out the rest for himself."

As a result of that conversation, an anonymous person with a sour voice phoned Wilson Jordon and casually attempted to purchase Dr. Jordon's interest in the Drake estate on Callisto for a small sum. The sour voice sounded suspicious to Dr. Jordon, who had never heard of the Drake estate, and he called a lawyer. He was informed that he had just become the probable legatee to half a million credits. The astonished physiologist jetted for Callisto one hour later.



Powell to staff: We've flushed Reich's man into the open. Jordon must be our lead on the Rhodopsin angle. He's the only Visual Physiologist to disappear after Crabbe's announcement. Pass the word to Beck to tail him to Callisto and handle it. What about that girl?



Meanwhile, the slick side of operation Rough & Smooth was quietly in progress. While Maria Beaumont was occupying Reich's attention with her squawking flight, a bright young attorney from Monarch's legal department was deftly decoyed to Mars and held there anonymously on a valid, if antiquated, vice charge. An astonishing duplication of that young attorney went to work for him.



Tate to Reich: Check your legal department. I can't peep what's going on, but something's fishy. This is dangerous.



Reich brought in an Esper 1 Efficiency Expert, ostensibly for a general check-up, and located the substitution. Then he called Keno Quizzard. The blind croupier produced a plaintiff who suddenly appeared and sued the bright young attorney for barratry. That ended the substitute's connection with Monarch painlessly and legitimately.



Powell to staff: Damn it! We're being licked. Reich's slamming every door in our face... Rough & Smooth. Find out who's doing the legwork for him, and find that girl.



While the squadman was cavorting around Monarch Tower with his brand new mongolian face, one of Monarch's scientists who had been badly hurt in a laboratory explosion, apparently left the hospital a week early and reported back for duty. He was heavily bandaged, but eager for work. It was the old Monarch spirit.



Tate to Reich: I've finally figured it. Powell isn't dumb. He's running his investigation on two levels. Don't pay any attention to the one that shows. Watch out for the one underneath. I've peeped something about a hospital. Check it.



Reich checked. It took three days and then he called Keno Quizzard again. Monarch was promptly burgled of Cr. 50,000 in laboratory platinum and the Restricted Room was destroyed in the process. The newly returned scientist was unmasked as an imposter, accused of complicity in the crime, and handed over to the police.



Powell to staff: Which means we'll never prove Reich got that Rhodopsin stuff from his own lab. How in God's name did he un-slick our trick? Can't we do anything on any level? Where's that girl?



While Reich was laughing at the ludicrous robot search for Marcus Graham, his top brass was greeting the Continental Tax Examiner, an Esper 2, who had arrived for a long delayed check on Monarch Utilities & Resources' books. One of the new additions to the Examiner's squad was a peeper ghost-writer who prepared her chiefs reports. She was an expert in official work... mainly police work.



Tate to Reich: I'm suspicious of that Examiner's squad. Don't take any chances.



Reich smiled grimly and turned his public books over to the squad. Then he sent Hassop, his Code Chief, to Spaceland on that promised vacation. Hassop obligingly carried a small spool of exposed film with his regular photographic equipment. That spool contained Monarch's secret books, cased in a thermite seal which would destroy all records unless it was properly opened. The only other copy was in Reich's invulnerable safe at home.



Powell to staff: And that just about ends everything. Have Hassop double-tailed; Rough & Smooth. He's probably got vital evidence on him, so Reich's probably got him beautifully protected. Damn it, we're licked. I say it. Old Man Mose would say it. You know it. For Christ's sake! Where is that goddamn missing girl?



Like an anatomical chart of the blood system, colored red for the arteries and blue for the veins, the underworld and overworld spread their networks. From Guild headquarters the word passed to instructors and students, to their families, to their friends, to their friends' friends, to casual acquaintances, to strangers met in business. From Quizzard's Casino the word was passed from croupier to gamblers, to confidence men, to the heavy racketeers, to the light thieves, to hustlers, steerers, and suckers, to the shadowy fringe of the semi-crook and near-honest.





THE REICH CASE WAS READY for final submission to the District Attorney's office. Powell hoped it was also ready for that cold-blooded, cynical monster of facts and evidence, Old Man Mose.

Powell and his staff assembled in Mose's office. A round table had been set up in the center, and on it was constructed a transparent model of the key rooms of Beaumont House, inhabited by miniature android models of the dramatis personae. The lab's model division had done a superlative job, and actually had characterized the leading players. The tiny Reich, Tate, Beaumont, and others moved with the characteristic gaits of their originals. Alongside the table was massed the documentation the staff had prepared, ready for presentation to the machine.

Old Man Mose himself occupied the entire circular wall of the giant office. His multitudinous eyes winked and glared coldly. His multitudinous memories whirred and hummed. His mouth, the cone of a speaker, hung open in a kind of astonishment at human stupidity. His hands, the keys of a multiflex typewriter, poised over a roll of tape, ready to hammer out logic. Mose was the Mosaic Multiplex Prosecution Computer of the District Attorney's Office, whose awful decisions controlled the preparation, presentation, and prosecution of every police case.

"We won't bother Mose to start with," Powell told the D.A. "Let's take a look at the models and check them against the Crime Schedule. Your staff has the time sheets. Just watch them while the dolls go through the motions. If you catch anything our gang's missed, make a note and we'll kick it around."

He nodded to De Santis, the harassed Lab Chief, who inquired in an overwrought voice: "One to one?"

"That's a little fast. Make it one to two. Half slow motion."

"The androids look unreal at that tempo," De Santis snarled. "It can't do them justice. We slaved for two weeks and now you"

"Never mind. We'll admire them later."

De Santis verged on mutiny, then touched a button. Instantly the model was illumined and the dolls came to life. Acoustics had faked a background. There was a hint of music, laughter, and chatter. In the main hall of Beaumont House, a pneumatic model of Maria Beaumont slowly climbed to a dais with a tiny book in her hands.

"The time is 11:09 at that point," Powell said to the D.A.'s staff. "Watch the clock above the model. It's geared to synchronize with the slow motion."

In rapt silence, the legal division studied the scene and jotted notes while the androids reproduced the actions of the fatal Beaumont party. Once again Maria Beaumont read the rules of the Sardine game from the dais in the main hall of Beaumont House. The lights dimmed and went out. Ben Reich slowly threaded his way through the main hall to the music room, turned right, mounted the stairs to the Picture Gallery, passed through the bronze doors leading to the Orchid Suite, blinded and stunned the Beaumont guards, and then entered the suite.

And again Reich met D'Courtney face to face, closed with him, drew a deadly knife-pistol from his pocket and with the blade pried D'Courtney's mouth open while the old man hung weak and unresisting. And again a door of the Orchid Suite burst open to reveal Barbara D'Courtney in a frost-white transparent dressing gown. And she and Reich feinted and dodged until Reich suddenly blew the back of D'Courtney's head out with a shot through the mouth.

"Got that material from the D'Courtney girl," Powell murmured. "Peeped her. It's authentic."

Barbara D'Courtney crawled to the body of her father, seized the gun and suddenly dashed out of the Orchid Suite, followed by Reich. He pursued her down into the darkened house and lost her as she darted out through the front entrance into the street. Then Reich met Tate and they marched to the Projection Room, pretending to play Sardine. The drama came to an end at last with the stampede of the guests up to the Orchid Suite where the dolls burst in and crowded around the tiny dead body. There they froze in a grotesque little tableau.

There was a long pause while the legal staff digested the drama.

"All right," Powell said. "That's the picture. Now let's feed the data to Mose for an opinion. First, Opportunity. You won't deny that the Sardine game provided Reich with perfect opportunity?"

"How'd Reich know they were going to play Sardine?" the D.A. muttered.

"Reich bought the book and sent it to Maria Beaumont. He provided his own Sardine game."

"How'd he know she'd play the game?"

"He knew she liked games. Sardine was the only legible game in the book."

"I don't know..." The D.A. scratched his head.

"Mose takes a lot of convincing. Feed it to him. Won't do any harm."

The office door banged open and Commissioner Crabbe marched in as though heading a parade.

"Mr. Prefect Powell," Crabbe pronounced formally.

"Mr. Commissioner?"

"It has come to my attention, sir, that you are perverting that mechanical brain for the purpose of implicating my good friend, Ben Reich, in the foul and dastardly murder of Craye D'Courtney. Mr. Powell, such a purpose is grotesque. Ben Reich is an honorable and leading citizen of our country. Furthermore, sir, I have never approved of that mechanical brain. You were chosen by the electorate to exercise your intellectual powers, not bow in slavery to that"

Powell nodded to Beck, who began feeding the punched data into Mose's ear. "You're absolutely right, commissioner. Now, about the Method. First question: How'd Reich knock out the guards. De Santis?"

"And furthermore, gentlemen..." Crabbe continued.

"Rhodopsin Ionizer," De Santis spat. He picked up a plastic sphere and tossed it to Powell who exhibited it. "Man named Jordan developed it for Reich's private police. I've got the empiric processing formula ready for the Computer, and the sample we mocked up. Anybody care to try it?"

The D.A. looked dubious. "I don't see the use. Mose can make up his own mind about that."

"In addition to which, gentlemen..." Crabbe summarized.

"Oh come on," De Santis said with unpleasant cheerfulness. "You'll never believe us unless you see it for yourself. It doesn't hurt. Just makes you non compos for six or seven"

The plastic bulb shattered in Powell's fingers. A vivid blue light flared under Crabbe's nose. Caught in mid-oration, the Commissioner collapsed like an empty sack. Powell looked around in horror.

"Good heavens!" be exclaimed. "What have I done? That bulb simply melted in my fingers." He looked at De Santis and spoke severely. "You made the covering too thin, De Santis. Now see what you've done to Commissioner Crabbe."

"What I've done!"

"Feed that data to Mose," the D.A. said in a voice rigid with control. "This I know he'll buy."

They made the Commissioner's body comfortable in a deep chair. "Now, the murder method," Powell continued. "Kindly watch this, gentlemen. The hand is quicker than the eye." He exhibited a revolver from the police museum. From the chambers he removed the shells, and from one of the shells he extracted the bullet. "This is what Reich did to the gun Jerry Church gave him before the murder. Pretended to make it safe. A phoney alibi."

"Phoney, hell! That gun is safe. Is that Church's evidence?"

"It is. Look at your sheet."

"Then you don't have to bother Mose with the problem." The D.A. threw his papers down in disgust. "We haven't got a case."

"Yes we have."

"How can a cartridge kill without a bullet? Your sheet doesn't say anything about Reich reloading."

"He reloaded."

"He did not," De Santis spat. "There was no projectile in the wound or the room. There was nothing."

"There was everything. It was easy once I figured the clue."

"There was no clue!" De Santis shouted.

"Why, you located it, De Santis. That bit of candy gel in D'Courtney's mouth. Remember? And no candy in the stomach."

De Santis glared, Powell grinned. He took an eye-dropper and filled a gel capsule with water. He pressed it into the open end of the cartridge above the charge and placed the cartridge in the gun. He raised the gun, aimed at a small wooden block on the edge of the model table, and pulled the trigger. There was a dull, flat explosion and the block leaped into fragments.

"For the love of  That was a trick!" The D.A. exclaimed. "There was something in that shell besides water." He examined the fragments of wood.

"No, there was not. You can shoot an ounce of water with a powder charge. You can shoot it with enough muzzle velocity to blow out the back of a head if you fire through the soft roof of the mouth. That's why Reich had to shoot through the mouth. That's why De Santis found the bit of gel. That's why he found nothing else. The projectile was gone."

"Give it to Mose," the D.A. said faintly. "By God, Powell, I'm beginning to think we've got a case."

"All right. Now, Motive. We picked up Reich's business records, and Accounting's gone through them. D'Courtney had Reich with his back to the wall. With Reich it was 'if you can't lick 'em, join 'em.' He tried to join D'Courtney. He failed. He murdered D'Courtney. Will you buy that?"

"Sure I'll buy it. But will Old Man Mose? Feed it in and let's see."

They fed in the last of the punched data, warmed the computer up from 'Idle' to 'Run,' and kicked him into it. Mose's eyes blinked in hard meditation; his stomach rumbled softly; his memories began to hiss and stutter. Powell and the others waited with mounting suspense. Abruptly, Mose hiccupped. A soft bell began to "Ping-Ping-Ping-Ping-Ping-Ping " and Mose's type began to flail the virgin tape under it.

"IF IT PLEASE THE COURT," Mose said, "WITH PLEADERING OF NON VULTS AND DEMURERS, LEGAL SIGNATURES. SS. LEADING CASE HAY v. COHOES AND THE RULE IN SHELLEY'S CASE. URP."

"What the" Powell looked at Beck.

"He gets kittenish," Beck explained.

"At a time like this!"

"Happens now and then. We'll try him again."

They filled the computer's ear again, held the warmup for a good five minutes and then kicked him into it. Once again his eyes blinked, his stomach growled, his memories hissed, and Powell and the two staffs waited anxiously. A month's hard work hung on this decision. The type-hammers began to fall.

"BRIEF #921,088. SECTION C-1. MOTIVE," Mose said. "PASSION MOTIVE FOR CRIME INSUFFICIENTLY DOCUMENTED. CF STATE v. HANRAHAN, 1202 SUP. COURT. 19, AND SUBSEQUENT LINE OF LEADING CASES."

"Passion motive?" Powell muttered. "Is Mose crazy? It's a profit motive. Check C-1, Beck."

Beck checked. "No mistake here."

"Try him again."

They ran the computer through it a third time. This time he spoke to the point: "BRIEF #921,088. SECTION C-1. MOTIVE. PROFIT MOTIVE FOR CRIME INSUFFICIENTLY DOCUMENTED. CF STATE v. ROYAL 1197 SUP. COURT 388."

"Didn't you punch C-1 properly?" Powell inquired.

"We got everything in that we could," Beck replied.

"Excuse me," Powell said to the others, "I've got to peep this out with Beck. You don't mind, I hope." He turned to Beck: "Open up, Jackson. I smelted an evasion in them last words. Let me have it..."

"Honestly, Linc, I'm not aware of any"

"If you were aware, it wouldn't be an evasion. It'd be a downright lie. Now lemme see... Oh. Of course! Idiot. You don't have to be ashamed because Code's a little slow."

Powell spoke aloud to the staffs: "Beck's missing one small datum point. Code's still working with Hassop upstairs trying to bust Reich's private code. So far all we've got is the knowledge that Reich offered merger and was refused. We haven't got the definite offer and refusal yet. That's what Mose wants. A cautious monster."

"If you didn't bust the code, how do you know the offer was made and refused?" the D.A. asked.

"Got that from Reich himself through Gus Tate. It was one of the last things Tate gave me before he was murdered. I tell you what, Beck. Add an assumption to the tape. Assuming that our merger evidence is unassailable (which it is) what does Mose think of the case?"

Beck hand punched a strip, spliced it to the main problem and fed it in again. By now well warmed up, the Mosaic Multiplex Computer answered in thirty seconds: "BRIEF #921,088. ACCEPTING ASSUMPTION, PROBABILITY OF SUCCESSFUL PROSECUTION 97.0099%."

Powell's staff grinned and relaxed. Powell tore the tape out of the typewriter and presented it to the D.A. with a flourish. "And there's your case, Mr. District Attorney... Sewn up and delivered."

"By God!" the D.A. said. "Ninety seven per cent! Jesus, we haven't had one in the ninety bracket all my term. I thought I was lucky when I broke seventy. Ninety seven per cent... Against Ben Reich himself! Jesus!" He looked around at his staff in a kind of wild surmise. "We'll make goddam history!"

The office door opened and two perspiring men darted in waving manuscript.

"Here's Code now," Powell said. "You bust it?"

"We busted it," they said, "and now you're busted, Powell. The whole case is busted."

"What? What the hell are you talking about?"

"Reich knocked off D'Courtney because D'Courtney wouldn't merge, didn't he? He had a nice fat profit motive for killing D'Courtney, didn't he? In a pig's eye he did."

"Oh God!" Beck groaned.

"Reich sent YYJI TTED RRCB UUFE AALK QQBA to D'Courtney. That reads: SUGGEST MERGER BOTH OUR INTERESTS EQUAL PARTNERSHIP."

"Damn it, that's what I've said all along. And D'Courtney replied: WWHG. That was a refusal. Reich told Tate. Tate told me."

"D'Courtney answered WWHG. That reads: ACCEPT OFFER."

"The hell it does!"

"The hell it don't. WWHG. ACCEPT OFFER. It was the answer Reich wanted. It was the answer that gave Reich every reason for keeping D'Courtney alive. You'll never convince any court in the solar system that Reich had a motive for murdering D'Courtney. Your case is washed out."

Powell stood stock still for half a minute, his fists clenched, his face working. Suddenly he turned on the model, reached in and pulled out the android figure of Reich. He twisted its head off. He went to Mose, yanked out the tapes of punched data, crumpled them into a wad and hurled the wad across the room. He strode to Crabbe's recumbent figure and launched a tremendous kick at the seat of the chair. While the staffs watched in an appalled silence, the chair and Commissioner overturned to the floor.

"God damn you! You're always sitting in that God damned chair!" Powell cried in a shaking voice and stormed out of the office.



A gavel pounding

A clock face

Hour hand at 9

Minute hand at 59

Second hand at 60

EMERGENCY MEETING

To examine a request for Mass Cathexis with Lincoln Powell as the human canal for the Capitalized energy.

(Consternation)

T'sung: You can't be serious, Powell. How can you make such a request? What can possibly require such an extraordinary and dangerous measure?

Powell: An astonishing development in the D'Courtney Case which I would like you all to examine.

(Examination)

Powell: You all know that Reich is our most dangerous enemy. He is supporting the Anti-Esper smear campaign. Unless that is blocked we may suffer the usual history of minority groups.

@kins: True enough.

Powell: He is also supporting the League of Esper Patriots. Unless that organization is blocked we may be plunged into a civil war and be lost forever in a morass of internal chaos.

Franion: That's true too.

Powell: But there is an additional development which you have all examined. Reich is about to become a Galactic focal point... A crucial link between the positive past and the probable future. He is on the verge of a powerful reorganization at this moment. Time is of the essence. If Reich can readjust and reorient before I can reach him, he will become immune to our reality, invulnerable to our attack, and the deadly enemy of Galactic reason and reality.

(Alarm)

@kins: Surely, you're exaggerating, Powell.

Powell: Am I? Inspect the picture with me. Look at Reich's position in time and space. Will not his beliefs become the world's belief? Will not his reality become the world's reality? Is he not, in his critical position of power, energy, and intellect, a sure road to utter destruction?

(Conviction)

T'sung: That's true. Nevertheless I'm reluctant to authorize the Mass Cathexis Measure. You will recall that the MCM has invariably destroyed the human energy canal in past attempts. You're too valuable to be destroyed, Powell.

Powell: I must be permitted to run the risk, Reich is one of the rare Universe-shakers... a child as yet, but about to mature. And all reality... Espers, Normals, Life, the earth, the solar system, the universe itself... all reality hangs precarlously on his awakening. He cannot be permitted to awake to the wrong reality. I call the question.

Franion: You're asking us to vote your death.

Powell: It's my death against the eventual death of everything we know. I call the question.

@kins: Let Reich awaken as he will. We have the time and the warning to attack him at another crossroad.

Powell: Question! I call the question!

(Request granted)

Meeting adjourned

Clock face

Hour hand at 9

Minute hand at 01

Second hand at Demolition






"Drunk? Sure, I'm drunk." Reich thrust his legs out of the bed and stood up, reeling slightly. Duffy came to him at once and he put his arm around her waist for support. "Why shouldn't I be drunk? I've licked D'Courtney. I've licked Powell. I'm forty years old. I've got sixty years of owning the whole world ahead of me. Yes. Duffy... the whole damned world!" He began walking around the room with Duffy. It was like a stroll through her ebullient erotic mind. A peeper decorator had reproduced Duffy's psyche perfectly in the decor.

"How'd you like to start a dynasty with me, Duffy?"

"I wouldn't know about starting dynasties."

"You start with Ben Reich. First you marry him. Then"

"That's enough. When do I start?"

"Then you have children. Boys. Dozens of boys..."

"Girls. And only three."

"And you watch Ben Reich take over D'Courtney and merge it with Monarch. You watch the enemies go down... like this!" In full stride, Reich kicked the leg of a busty vanity table. It toppled and crashed a score of crystal bottles to the floor.

"After Monarch and D'Courtney become Reich, Incorporated, you watch me eat up the rest... the small ones... the fleas. Case and Umbrel on Venus. Eaten!" Reich brought his fist down on a torso-shaped side table and smashed it. "United Transaction on Mars. Mashed and eaten!" He crushed a delicate chair. "The GCI Combine on Ganymede, Callisto, and Io... Titan Chemical & Atomics... And then the smaller lice: the backbiters, the haters, the Guild of Peepers, the moralists, the patriots... Eaten! Eaten! Eaten!" He pounded his palm against a marble nude until it toppled from its pedestal and shattered.

"Clever-up, dog," Duffy hung on his neck. "Why waste all that dear violence? Punch me around a little."

He lifted her in his arms and shook her until she squealed. "And parts of the world will taste sweet... like you, Duffy; and parts will stink to high heaven ... but I'll gobble them all." He laughed and crushed her against him. "I don't know much about the God business, but I know what I like. We'll tear it all down, Duffy, and we'll build it all up to suit us... You and me and the dynasty."

He carried her to the window, tore away the drapes and kicked open the sashes with a mighty jangle of smashed glass. Outside, the city was in velvet darkness. Only the skyways and streets twinkled with lights, and the scarlet eyes of an occasional Jumper popped up over the jet skyline. The rain had stopped and a slender moon hung pale in the sky. The night wind came whispering in, cutting through the cloy of the spilled perfume.

"You out there!" Reich roared. "Can you hear me! All of you... sleeping and dreaming. You'll dream my dreams from now on! You'll"

Abruptly he was silent. He relaxed his hold on Duffy and permitted her to slide to the floor alongside him. He seized the sides of the window and poked his head far out into the night, twisting his neck to stare up. When he drew his head back into the room, his face wore a bewildered expression.

"The stars," he mumbled. "Where are the stars?"

"Where are the what?" Duffy wanted to know.

"The stars," Reich repeated. He gestured timidly toward the sky. "The stars. They're gone."

Duffy looked at him curiously. "The what are gone?"

"The stars!" Reich cried. "Look up at the sky. The stars are gone. The constellations are gone! The Great Bear... The Little Bear... Cassiopeia... Draco... Pegasus... They're all gone! There's nothing but the moon! Look!"

"It's the way it always is," Duffy said.

"It is not! Where are the stars?"

"What stars?"

"I don't know their names... Polaris and... Veg... and... How the hell should I know their names? I'm not an astronomer. What's happened to us? What's happened to the stars?"

"What are stars?" Duffy asked.

Reich seized her savagely. "Suns... Boiling and blazing with light. Thousands of them. Billions of them... shining through the night. What the hell's the matter with you? Don't you understand? There's been a catastrophe in space, the stars are gone!"

Duffy shook her head. Her face was terrified. "I don't know what you're talking about, Ben. I don't know what you're talking about."

He shoved her away, turned and ran to the bathroom, and locked himself in. While he was hurriedly bathing and dressing, Duffy pounded on the door and pleaded with him. Finally, she broke off, and seconds later he heard her calling Kingston Hospital, using a guarded voice.

"Let her start explaining about the stars," Reich muttered, halfway between anger and terror. He finished his toilette and came out into the bedroom.

Duffy cut the phone off hastily and turned to him.

"Ben," she began.

"Wait here for me," he growled. "I'm going to find out."

"Find out about what?"

About the stars!" he yelled. "The Christ almighty missing stars!"

He flung out of the apartment and rushed down to the street. On the empty footway, he paused and stared up again. There was the moon. There was one brilliant red point of light... Mars. There was another... Jupiter. There was nothing else. Blackness. Blackness. Blackness. I hung over his head, enigmatic, unrelieved, terrifying. It pressed downward, by some trick of the eye, oppressive, stifling, deadly.

He began to run, still staring upward. He turned a corner of the footway and collided with a woman, knocking her flat. He pulled her to her feet.

"You clumsy bastard!" she screamed, adjusting her feathers. Then in an oily voice: "Lookin' for a good time, pilot?"

Reich held her arm. He pointed up. "Look. The stars are gone. Have you noticed? The stars are gone."

"What's gone?"

"The stars. Don't you see? They're gone."

"I don't know what you're talking about, pilot. Cmon. Let's have us a ball."

He tore himself away from her claws and ran. Halfway down the footway was a public v-phone alcove. He stepped in and dialed information. The screen lit and a robot voice spoke: "Question?"

"What's happened to the stars?" Reich asked. "When did it happen? It must have been noticed by now. What's the explanation?"

There was a click, a pause, then another click. "Will you spell the word, please."

"Star!" Reich roared. "S-T-A-R. Star!"

Click, pause, click. "Noun or verb?"

"God damn you! Noun!"

Click, pause, click. "There is no information listed under that heading," the canned voice announced.

Reich swore, then fought to control himself. "Where's the nearest Observatory to the city?"

"Kindly specify city."

"This city. New York."

Click, pause, click. "The Lunar Observatory at Croton Park is situated thirty miles north. It may be reached by Jumper Route North Coordinate 227. The Lunar Observatory was endowed in the year two thousand"

Reich slammed down the phone. "No information listed under that heading! My God! Are they all crazy?" He ran out into the streets, searching for a Public Jumper. A piloted machine cruised past and Reich signalled. It swooped to pick him up.

"Northco 227," he snapped as he stepped into the cabin. "Thirty miles. The Lunar Observatory."

"Premium trip," the driver said.

"I'll pay it. Jet!"

The cab jetted. Reich restrained himself for five minutes, then began casually: "Notice the sky?"

"Why, mister?"

"The stars are gone."

Sycophantic laugh.

"It's not supposed to be a joke," Reich said. "The stars are gone."

"If it ain't a joke, it needs explaining," the driver said. "What the hell are stars?"

A blasting reply trembled on Reich's lips. Before it could erupt, the cab landed him on the observatory grounds close to the domed roof. He snapped: "Wait for me," and ran across the lawns to the small stone entrance.

The door was ajar. He entered the observatory and heard the low whine of the dome mechanism and the quiet click of the observatory clock. Except for the low glow of the clock-light, the room was in darkness. The twelve-inch refractor was in operation. He could see the observer, a dim outline, crouched over the eyepiece of the guiding telescope.

Reich walked toward him, nervous, strained, flinching at the loud clack of his footsteps in the silence. There was a chill in the air.

"Listen," Reich began in a low voice. "Sorry to bother you but you must have noticed. You're in the star business. You have noticed, haven't you? The stars. They're gone. All of them. What's happened? Why hasn't there been any alarm? Why's everybody pretending? My God! The stars! We always take them for granted. And now they're gone. What's happened? Where are the stars?"

The figure straightened slowly and turned toward Reich. "There are no stars," it said.

It was the Man With No Face.

Reich cried out. He turned and ran. He flew out of the door, down the steps and across the lawn to the waiting cab. He blundered against the crystal cabin wall with a crack that dropped him to his knees.





Powell went up to Crabbe's ebony and silver office, knocked, heard the imperious: "Come!" and entered. Crabbe was properly solicitous, but stiff. The D'Courtney Case had not improved his relations with Powell. The denouement had come as an additional blow.

"It was a remarkably complex case, sir," Powell began tactfully. "None of us could understand it, and none of us are to blame. You see, Commissioner, even Reich himself was not consciously aware of why he had murdered D'Courtney. The only one who grasped the case was the Prosecution Computer, and we thought it was acting kittenish."

"The machine? It understood?"

"Yes, sir. When we ran our final data through the first time, the Computer told us that the 'passion motive' was insufficiently documented. We'd all been assuming profit motive. So had Reich. Naturally we assumed the Computer was having kinks, and we insisted on computation based on the profit motive. We were wrong..."

"And that infernal machine was right?"

"Yes, Commissioner. It was. Reich told himself that he was killing D'Courtney for financial reasons. That was his psychological camouflage for the real passion motive. And it couldn't hold up. He offered merger to D'Courtney. D'Courtney accepted. But Reich was subconsciously compelled to misunderstand the message. He had to. He had to go on believing he murdered for money."

"Why?"

"Because he couldn't face the real motive..."

"Which was... ?"

"D'Courtney was his father."

"What!" Crabbe stared. "His father? His flesh and blood?"

"Yes, sir. It was all there before us. We just couldn't see it... because Reich couldn't see it. That estate on Callisto, for instance. The one that Reich used to decoy Dr. Jordan off the planet. Reich inherited it from his mother who'd received it from D'Courtney. We all assumed Reich's father had chiseled it out of D'Courtney and placed it in his wife's name. We were wrong. D'Courtney had given it to Reich's mother because they were lovers. It was his love-gift to the mother of his child. Reich was born there. Jackson Beck uncovered all that, once we had the lead."

Crabbe opened his mouth, then closed it.

"And there were so many other signposts. D'Courtney's suicide drive, produced by intense guilt sensations of abandonment. He had abandoned his son. It was tearing him apart. Then, Barbara D'Courtney's deep half-twin image of herself and Ben Reich; somehow she knew they were half-brother and sister. And Reich's inability to kill Barbara at Chooka Frood's. He knew it too, deep down in the unconscious. He wanted to destroy the hateful father who had rejected him, but he could not bring himself to harm his sister."

"But when did you unearth all this?"

"After the case was closed, sir. When Reich attacked me for setting those booby-traps."

"He claimed you did. He  But if you didn't, Powell, who did?"

"Reich himself, sir."

"Reich!"

"Yes, sir. He murdered his father. He discharged his hatred. But his super-ego... his conscience, could not permit him to go unpunished for such a horrible crime. Since the police apparently were unable to punish him, his conscience took over. That was the meaning of Reich's nightmare image... The Man With No Face."

"The Man With No Face?"

"Yes, Commissioner. It was the symbol of Reich's real relationship to D'Courtney. The figure had no face because Reich could not accept the truth... that he had recognized D'Courtney as his father. The figure appeared in his dreams when he made the decision to kill his father. It never left him. It was first the threat of punishment for what he contemplated. Then it became the punishment itself for the murder."

"The booby-traps?"

"Exactly. His conscience had to punish him. But Reich had never admitted to himself that he murdered because he hated D'Courtney as the father who had rejected and abandoned him. Therefore, the punishment had to take place on the unconscious level. Reich set those traps for himself without ever realizing it... in his sleep, somnambulistically... during the day, in short fugues... brief departures from conscious reality. The tricks of the mind-mechanism are fantastic."

"But if Reich himself knew none of this... how did you get at it, Powell?"

"Well, sir. That was the problem. We couldn't get it by peeping him. He was hostile and you have to have complete cooperation from a subject to get that kind of material. It takes months anyway. Also, if Reich recovered from the series of shocks he'd had, he would be able to readjust, reorient, and become immune to us. That was dangerous, too, because he was in a position of power to rock the solar system. He was one of those rare World-Shakers whose compulsions might have torn down our society and irrevocably committed us to his own psychotic pattern."

Crabbe nodded.

"He very nearly succeeded. These men appear every so often... links between the past and the future. If they are permitted to mature... If the link is permitted to weld... The world finds itself chained to a dreadful tomorrow."

"Then what did you do?"

"We used the Mass Cathexis Measure, sir. It's difficult to explain, but I'll do my best. Every human being has a psyche composed of latent and capitalized energy. Latent energy is our reserve... the untapped natural resources of our mind. Capitalized energy is that latent energy which we call up and put to work. Most of us use only a small portion of our latent energy."

"I understand."

"When the Esper Guild uses the Mass Cathexis Measure, every Esper opens his psyche, so to speak, and contributes his latent energy to a pool. One Esper alone taps this pool and becomes the canal for the latent energy. He captilizes it and puts it to work. He can accomplish tremendous things... if he can control it. It's a difficult and dangerous operation. About on a par with jetting to the moon with a stick of dynamite stuck  er  riding on dynamite sticks..."

Suddenly Crabbe grinned. "I wish I were a peeper," he said. "I'd like to get the real image in your mind."

"You've got it already, sir." Powell grinned back. A rapport had been established between them for the first time.

"It was necessary," Powell continued, "to confront Reich with The Man With No Face. We had to make him see the truth before we could get the truth. Using the pool of latent energy, I built a common neurotic concept for Reich... the illusion that he alone in the world was real."

"Why, I've  Is that common?"

"Oh yes, sir. It's one of the run-of-the-mill escape patterns. When life gets tough, you tend to take refuge in the idea that it's all make-believe... a giant hoax. Reich had the seeds of that weakness in him already. I simply forced them and let Reich defeat himself. Life was getting tough for him. I persuaded him to believe that the universe was a hoax... a puzzle-box. Then I tore it down, layer by layer. I made him believe that the test was ended. The puzzle was being dismantled. And I left Reich alone with The Man With No Face. He looked into the face and saw himself and his father... and we had everything."

Powell picked up his parcel and arose. Crabbe jumped up and escorted him to the door with a friendly hand on his shoulder.

"You've done a phenomenal job, Powell. Really phenomenal. I can't tell you... It must be a wonderful thing to be an Esper."

"Wonderful and terrible, sir."

"You must all be very happy."

"Happy?" Powell paused at the door and looked at Crabbe. "Would you be happy to live your life in a hospital, Commissioner?"

"A hospital?"

"That's where we live... All of us. In the psychiatric ward. Without escape... without refuge. Be grateful you're not a peeper, sir. Be grateful that you only see the outward man. Be grateful that you never see the passions, the hatreds, the jealousies, the malice, the sicknesses... Be grateful you rarely see the frightening truth in people. The world will be a wonderful place when everyone's a peeper and everyone's adjusted... But until then, be greatful you're blind."

He left headquarters, hired a Jumper and was jetted North toward Kingston Hospital. He satin the cabin with the parcel on his knees, gazing down at the magnificent Hudson Valley, whistling a crooked tune. Once he grinned and muttered: "Wow! That was some line I handed Crabbe. But I had to cement our relations. Now he'll feel sorry for peepers... and friendly."

Kingston Hospital came into view... acre upon rolling acre of magnificent landscaping. Solariums, pools, lawns, athletic fields, dormitories, clinics... all in exquisite neo-classic design. As the Jumper descended, Powell could make out the figures of patients and attendants... all bronzed, active, laughing, playmg. He thought of the vigilant measures the Board of Governors was forced to take to prevent Kingston Hospital from becoming another Spaceland. Too many fashionable malingerers were already attempting to obtain admission.

Powell checked in at the Visitors Office, found Barbara D'Courtney's location and started across the grounds. He was weak, but he wanted to leap hedges, vault gates, run races. He had awakened after seven days' exhaustion with a question  one question to ask Barbara. He felt exhilarated.

They saw one another at the same moment. Across a broad stretch of lawn flanked by field-stone terraces and brilliant gardens. She flew toward him, waving, and he ran toward her. Then as they approached, both were stricken with shyness. They stopped a few feet apart, not daring to look at each other.


