* Cultural Anthropology notes                                                   :bodley:tribal:anthropology:
** Chapter 1:
*** p1
    Tribal Societies typically contained fewer than 2,000 there was no need for government at birth all people received a personal estate that guaranteed
    them access to all the natural, social and cultural wealth needed to make a
    successful living

*** p4
    Three 'worlds' of increasing scale and complexity: tribal, imperial,
    commercial

*** p11
    tribal world: humanization conceptualization, materialization,
    berbalization, socialization (through exogamy), cultural transmission

    imperial world: politicization taxation, conquest, specialization,
    militarization, bureaucratization, urbanization

    commercial world: commercialization commodification, industrialization,
    capitalization, corporatization, externalization, supralocalization,
    finacialization

    primates use 'hands-on' social grooming to remain integrated humans can groom
    and manipulate others at a distance

*** p12
    tribal clans, neolithic villages, church congregations, small military
    units, ad the social network of individuals

    culture: what people think, make and do.

    Edward B Tylor: "Culture.. is that complex whole which includes knowledge
    ,belief, art ,law, morals, custom, and any other capabilities and habits
    acquired by man as a member of society.

    Culture is a humanly directed response to historical events. We use culture
    to change our behaviour and the behaviour of others for personal benefit, but
    the conscious choices that we make are aimed at immediated outcomes.

*** p13
    Four types of social power: ideological, economic, military, and
    polticial. Cultural organization of social power: by kin in tribal world by
    rules in the imperial world by business owners, managers and financiers in
    the commercial world

    Individuals construct self-centered personal networks of power, or 'imperia'
    incorporating individuals and institutionally organized groups of people they
    can personally command or influence to do things for their personal
    advantage.

    Personal power networks are based on kinship, marriage, friendship and
    patronage.

*** p16
    differences in colour descriptions and terms

*** p17
    The functional organization of sociocultural systems: superstructure,
    structure, and infrastructure.

*** p18
    infrastructure: population size, materials, and technology structure:
    economy, society, polity/government superstructure: ideology

*** p22
    acculturation: culture change brought about by contact between peoples
    with different cultures.

    emic: relating to cultural meanings derived from inside a given culture and
    presumed to be unique to that culture Etic: cultural meaning as translated
    for cross-cultural comparison
** Chapter 2: Amazon tribes
*** p30
    gardening through slash and burn

*** p35
    Formula for environmental limits on gardening on amazonian villagers: P
    = ([T/(R+Y)] Y) / A Where: P= Village population T = arable land R = years in
    forest fallow Y= years garden cultivated A = garden area per person

*** p36
    the Ashaninka make only about 120 separately named material items apart
    from food products

    Exchange on a deferred basis

*** p39
    Extended families are formed when marreied children reside near their
    parents, either matriolocally, or patrilocally. Each married couple
    constitutes an indepenedent domestic unit with its own kitchen hearth and
    garden, but there is daily economic cooperation between households, and fish
    and game are pooled.

    The Ashaninka recognize three categories of people: Kin, formal trading
    parters, and strangers who are potential enemies. If friendly interaction is
    to take place, strangers are immediately placed in a kinship category and
    treated appropriately. For example, men who want to request a favor from me
    would address me as "brother".

*** p43
    One of the most distinctive features of tribal cultures is the way they
    resist any concentration of political power that might threaten the autonomy
    of households and communities.

    Political autonomy means that people can relocate their village whenever they
    choose, can kill intruders in self-defense, and can control their natural
    resources.

*** p45
    An Ashaninka househould network of 100 persons in 26 households in 10
    household groups.

    Amazon villages are "societies against the state, designed to prevent the
    concentration of political power that would allow anyone to gain control of
    the economy for his own benefit.

    A good headman must be a good public speaker and be especially generous,
    giving things away on request, but he is not distinguished by special dress
    or insignias of office. The importance of the headman's oratorical skills
    further shows that he cannot use coercive violence. He must be verbally
    persuasive at settling intravillage conflicts, but if he fails as a
    peacemaker, the village simply breaks apart.

*** p46
    The Ashaninka headman's position is temporary because it is based on his
    personality and the number of his sons and sons-in-law that he can persuade
    to remain in his hamlet to form a local group.

    The underlying source of village conflict is the shortage of game and the
    related competition between village men for access to women.

*** p53
    In the tribal world there are no central political authorities or
    institutions with police, courts, and judges that could curb offenders,
    settle disputes, and prevent endless cycles of revenge and killing.

*** p61
    Shaman. A part-time religious specialist with special skills for dealing
    with the spirit world. May help his community by healing, by divination, and
    by directing supernatural powers against enemies.

*** p89
    kinship and mother-in-law avoidance

*** p93
    male initiationp

** Chapter 3: African Cattle peoples: Tribal Pastoralists
*** p115
    segmentary lineage system. where geographic distance corresponds to
    social distance
