* Dan Abnett Extracts                                                           :examples:scifi:abnett:

*** Ravenor

**** Bonner's Reach
--------------------
THEY WERE APPROACHING the entry gate at the end of the jetty. Its ancient stone form was decorated with interwoven carved figures that symbolised leaping flame. Heaps of votive offerings were piled up either side of the gate pillars. Dolls, figurines, ritual pots, small tied-up sacks, drinking vessels, ribbons, occasionally an icon like an aquila; and those were simply the ones of human origin that Nayl could identify. Any others were alien objects he could make no sense of. It was customary to leave a token offering at the gate on departure, to vouchsafe one’s next voyage.

Two Vigilants awaited them at the gate.

‘You ready with the tribute?’ Preest whispered.

‘The servitors have been instructed,’ Ravenor replied through Mathuin’s mouth.

The Order of Vigilants administered the Reach. They collected tariffs, saw to the station’s smooth running, and to the congress of fair trade. The pair that now approached them were lean and tall, at least as tall as Harlon or Zeph. They walked with an easy, nimble step that told Nayl right off they were consummate close fighters. Each Vigilant wore a sleeveless, antique gown of ribbed armour, marvellously constructed, baggy black pantaloons that were tight-cinched at the ankle, and black felt slippers that were shaped around the big toe. Their exposed arms were either bionic, or encased in some form of skinplant technology. It was a tech-design neither Nayl nor Ravenor had ever seen before. Sheathed over their shoulders they carried ceremonial hand-and-a-half swords.

Their heads were bare and shaved. More of the curiously-wrought skinplant tech encased their necks, so that their heads seemed to be resting on slender columns of intricately inscribed metal. The skin of their faces and scalps was entirely covered in swirling flame tattoos, echoing the design around the doorway. Their eyes were augmetic implants that glowed a dull green.

‘Welcome,’ said one. Its voice was like silk.

‘The immaterium has brought you to Bonner’s Reach,’ said the other, its tone rasping and deep.

‘Free trade is welcome here,’ uttered the first.

Perched on her hovering platform, Preest bowed. ‘Thank you for your greeting and welcome,’ she said. ‘I most humbly crave admittance. I have brought a tribute for the welfare of all.’

‘Let us examine it,’ said the rasping one.

At a signal from Nayl, the servitors brought forward the caskets and opened some of them. Foodstuffs, much of it stasis-fresh, wine and some flasks of amasec.

‘This is acceptable tribute,’ said the rasping Vigilant.

‘Welcome,’ repeated the silky one. ‘Do you wish us to advertise your presence and identity to the merchants here?’

‘I am Shipmistress Zeedmund. Of the sprint trader Tarnish. I am here for Firetide, but I also seek interesting commerce.’

‘Zeedmund. Tarnish…’ they echoed.

‘I have serious collateral,’ she added. ‘Make that known. I am interested in genuine business.’

‘You appreciate the Code of the Reach?’ asked the Vigilant with the silk voice.

‘Peace and discourse,’ Preest replied. ‘And no weapon within the bounds of the Reach with a range longer than a human arm.’

Nayl and Mathuin dutifully displayed the empty holsters at their hips, the ritual sign of unarmed intent.

‘You are familiar with our rules,’ said the silky-voiced Vigilant.

‘You have been here before,’ the rasping one said. It was more of a statement than a question. Nayl stiffened.

‘I am a trader,’ said Preest. ‘I go where I please.’

‘Voice-pattern records show you to be Cynia Preest, shipmistress. Not Zeedmund.’

‘Traders change their identities. Is that a problem?’

‘Not at all. We are ever discreet,’ The Vigilants stood aside and ushered them through the threshold. ‘Enter and make your trade.’

Beyond the gate, they entered a capacious chamber hewn out of the planetary rock. The air was still muggy and over-used. The place was bathed in a yellow, fulminous light from bioluminescent tank-lamps mounted at regular intervals along the wall. Archways led off into other chambers, and at the far end, a well-lit tunnel disappeared away into the free trade areas. More Vigilants appeared, to conduct Preest’s servitors to the communal larders where the tribute could be left.

One of them, his voice a whisper, approached the ship-mistress.

‘Do you require a guide? A translator? Any other service?’

‘I will ask if I need any such service,’ she said. The Vigilant bowed and backed away.

With her bodyguards either side of her, Preest began to glide sedately down the long tunnel.
--------------------
ON BONNER’S REACH, visiting traders could avail themselves of drink and nourishment free of charge. Indeed, almost all services were free. A berthing fee was required, of course, but once that was paid, a trader could luxuriate in the bountiful hospitality of the station. The level of comfort was designed to relax visitors and encourage profitable, unhurried mercantile negotiation. The Vigilants merely expected a fee equivalent to one per cent of gross on any deal or transaction made within their precincts.

Of course, this apparent largesse was helped enormously by the recognised custom of tribute. Every captain, master or venturer, human or otherwise, was expected to offer something in the way of foodstuffs, liquor or other intoxicants upon arrival.

Preest’s tribute was conducted down three kilometres of rock-cut corridors into a handling bay that adjoined one of the station’s many food preparation areas. There the servitors set the caskets down as instructed and made their way back to the Hinterlight. A Vigilant labelled the caskets with storage instructions. Before long, kitchen labour would sort through the caskets and distribute the contents: perishables into cold stores and stasis vaults, wine to cellars, dry goods to the well-stocked pantries, specialist foods into appropriate containers, and narcotics to the tenders who walked the floors of the free trade salons.

The Vigilant was called away. Two pot-men were having an altercation in the nearby kitchen.

Preest’s caskets were left unattended against the wet quartz wall of the handling bay.

The lid of the fourth casket along popped open. Telescopic levers hissed taut, lifting the produce tray up, revealing it to be merely a shallow false top.

Breathing deeply and slowly, Kara Swole slid herself out of the hidden cavity. She had contorted her body into a tiny space. As she emerged, she paused, grimacing, to pop her shoulder joints back into place.

Kara looked around. There was no time to complete a full body recovery here. She reached her hands up and detached the fibre-optic patch from over her left eye. The adhesive took some lashes with it. She rubbed her eye and wound the patch up in its long string of wire, unplugging the far end of it from the inside of the casket. Thanks to the fibre-optic, she’d been able to see a cold-light view of the outside and judge the best time for emergence accordingly.

Keeping a watchful eye around her, Kara tucked the fibre-optic into a hip pouch. She was wearing a skin-tight light-reflective bodyglove with only her head exposed. Her thick red hair was slicked into a tight latex net that made her look bald. She opened the next casket along, and removed its false top layer too. Her equipment was stowed beneath. First, a small, prepacked rucksack on a tight fylon harness. Then, a compact vox, and a multikey that slipped neatly into holder loops on her waistband.

Her limbs and back were sore. She stayed wary, expecting discovery at any moment. The thin combat knife slipped into place in her glove’s calf sheath. Nearly done.

She could hear footsteps approaching. One last task. Two almost empty tribute caskets would be more than a little suspicious. She tore open the shrink-wrapped packs of dehydrated kelp and shook their dry contents out into the bottom of each casket. Then she tore the top off a water flask and emptied its glugging contents after them.

Footsteps came closer. She pushed the produce trays back into place, closed the casket lids, and dashed into the shadows at the far end of the handling bay. Then, like an arachnid, she went clear up the sheer quartz wall. The palms and soles of her bodyglove were angle-ribbed with razor-steel filament hooks that could find purchase on almost any surface. She reached the top of the wall, slid into a rocky cavity, and lay still.

A troupe of kitchen labourers wandered into the bay below her, flipping up the lids of Preest’s caskets to examine the fare. As she watched, they opened the casket where she had been concealed and took out the top tray.

The rest of the casket was chock full of glistening kelp. She heard the labourers scoff and moan. It was typical cheapskate rogue trader behaviour. Come bearing plenty when in fact most of the makeweight was sea cabbage.

Kara grinned to herself.

As soon as the labourers began to heft the caskets out into the larders, Kara began to move again, scuttling across the rock wall and in under the great flinty arch to the kitchen. Her arms and legs were throbbing with pain. Sheer climbing put an enormous stress on musculature, and her body wasn’t yet limber from the forced contortions of the casket.

She forced herself on. A cramp in her left calf lost her some grip, but she clenched her teeth and persisted.

The kitchen below her was a vast and dingy haze, steam surging up from a dozen canisters on a dozen stoves, smoke trailing off roast veal and orkunu and marinated sinqua on the fire pits, drums of broiling ketelfish, pans of frying lardons, tureens of potage, steamers of fubi dumplings and blanching wilt-leaf. The roof of the chamber was a thick smog, which suited her just right. Though stone-cut, the kitchen hall was bolstered with thick cross-members of steel that formed ceiling beams. She dropped down onto the nearest one, swathed in oily smoke and vapour. There, invisible to the staff twenty metres below her, she stood for a long while, tension-flexing and relaxing her tortured body. Arms, joints, digits, spine, ribs, pelvis. As if performing to some great invisible audience, she began to stretch and slide, backflip, rotate and split.

Then she lay on her back on the beam, the kitchen clattering and broiling below her. She was still sore – that was inevitable after two hours in the box. But she was at last spry and warmed up.

Kara Swole rolled over, rose and began to run across the beam towards the interior of the station.
--------------------
**** Culzean
--------------------
ORFEO CULZEAN WAS a rare beast. His papers declared him to be a dealer and purveyor of antiquities, but that merely described the legitimate business he conducted to disguise his real work. It allowed him to travel widely through the sector, and availed him of opportunities to acquire curios and inspect the reserved collections of many museums and archives. His scholarship was highly regarded. He had not a single blemish of criminal activity on his record.

But Orfeo Culzean was a professional malcontent, a mercenary, a shaper of destiny. No warrior he – Culzean had never lifted a finger against another soul personally – his speciality was subtle and invidious. He made things happen. He was an architect of fate, one of the foremost expeditors employed by the Divine Fratery.

Culzean did not belong to the Fratery itself. He had no interest in being a seer, and bore no wish to sacrifice an eye or blister his skin. But it was he, and a few rare beasts like him, that the Fratery turned to when it wished to make its prospects into a reality.

Under normal circumstances, he would have been the most dangerous man alive on Eustis Majoris. But that winter, he was up against stiff opposition.

The Fratery had summoned him to Eustis Majoris, financed his passage, and paid for an exclusive suite at the Regency Viceroy in Formal C, at the heart of Petropolis. Two days after his arrival, the magus-clancular of the Divine Fratery cell active in Petropolis came to visit him.

The magus-clancular was called Cornelius Lezzard. He was three hundred and ten years old, infirm and riddled with disease, his crippled body supported in an upright exoskeleton. Two brothers of the Fratery escorted him. All three wore simple black suits with velvet hats. All three had moved their purple velvet eye patches to cover their everyday augmetic optics, so as to do Culzean the honour of regarding him with their sacred, real eyes.

What those eyes saw when they entered the opulent suite was a portly man in late middle age, dressed in a high-buttoned suit of blue worsted, his thick, dark hair and beard perfectly groomed. He was sitting in a leather armchair, caressing a little simivulpa that played on his lap. As the fraters came in, he put the pet down and got to his feet. The silky fox-monkey barked and clambered up to perch on the back of the chair.

Culzean bowed slightly.

‘Magus-clancular, a pleasure to meet you again,’ Culzean’s voice was as soft and heavy as comb honey.

‘We look upon you, Orfeo,’ Lezzard replied.

‘Please, repatch yourselves. Let us not stand on ceremony.’

The two escorts replaced their velvet patches over their organic eyes, exposing their crude, glowing augmetics.

One had to help Lezzard, who fumbled at his own patch with palsied hands.

‘It has been a few years since we last worked together on a prospect,’ Lezzard said. His voice had a tremulous, breathless quality. Tubes from his exoskeleton’s bio-support pack were sutured into his scrawny neck.

‘Indeed. On Promody. The plague was a thing of exquisite beauty.’

‘This prospect is many times more wonderful.’

‘I imagined it would be. The summons was… eager. As I understand it, this particular prospect is the Fratery’s chief current interest.’

‘It is. That is why I asked the Fratery masters to engage your services. Let me introduce my companions. Arthous and Stefoy, both able seers.’

‘Brothers,’ Culzean nodded. The men were typical of the Fratery: their faces scarred and twisted from the rigours of cult initiation, their hands worn and eroded from working the silver mirrors. ‘Will you take refreshment?’

‘A little wine, or secum liquor, perhaps?’ Lezzard said.

Culzean nodded. Nearby stood his watcher, a tall, muscular woman with short blonde hair and an anvil-hard face. She wore a tight khaki bodyglove with a fur trim. Her name was Leyla Slade.

‘Leyla?’

She retreated obediently to call for service.

Lezzard limped around the chamber, the pistons of his exoskeleton wheezing. Culzean had decorated the room with his own ornaments. Lezzard examined a few, chuckling from time to time.

‘Your collection grows, I see,’ he said.

‘People die all the time,’ Culzean replied lightly.

‘Indeed they do. But tell me… this key?’

‘It choked a child on Gudrun.’

‘Did it? And this paving stone?’

‘Once lay at the very top of the processional steps outside the templum at Arnak. The glass vial beside it contains some of the rainwater that made it wet and treacherous to an unsuspecting pilgrim.’

‘Forgive me,’ one of the fraters – Arthous – said, ‘I don’t understand.’

Culzean smiled. ‘I collect deodands,’ he said.

Arthous looked bemused.

‘A deodand,’ Culzean said, ‘is an object that has directly caused the death of a person or persons. This tile, from the roof of an auction house on Durer, which cracked the skull of a passing magistrate. This ink pen, whose filthy nib poisoned the blood of the Administratum cleric who accidentally speared himself in the buttock. This thunderstone, falling like a missile from the open sky onto a herdsman in Migel County. This apple, sealed in a plastek block to preserve it – you notice the single bite mark? The poor woman was allergic to the juice.’

‘Extraordinary,’ said Arthous. ‘May I ask… why?’

‘Why do I collect them? Cherish them? You know what I do, Frater Arthous. 1 engineer destiny. These objects fascinate me. I believe they contain a vestige of some outer force, some happenstance. Each one crude, and of itself worthless, but empowered. I keep them by me as charms. Every single one has changed a person’s fate. They remind me how fickle and sudden fate can be, how easily twisted.’

‘They’re the source of your power?’ Stefoy wondered.

‘They’re just a collection of things,’ Culzean said. ‘All of them yearn to shape the future as completely and as fully as I do.’

Leyla Slade returned, with a tray of hot secum in drinking kettles. She served the men as they took their seats under the tall windows of the suite. The simivulpa scurried playfully under their chairs. Outside, the rain lashed the grim, high stacks of the city.

‘Tell me about the prospect,’ Culzean said, sipping from his drinking kettle’s spout.

‘How much do you know, Orfeo?’ Lezzard replied.

Culzean shrugged. ‘The Fratery’s seers on Nova Durma have seen something in their silver mirrors. A prospect that is – and I understand this is almost unheard of – almost one hundred per cent likely. Something will occur here, on Eustis Majoris, before the end of the year. A daemonic manifestation. It will shake history. Its name will be Slyte.’

‘A decent appraisal,’ the magus-clancular replied, as Stefoy helped him suck from his kettle. ‘Arthous, the rest.’

Arthous leaned forward in his seat, and put his kettle down. He stank from the sores on his body, but Orfeo Culzean was too well-mannered to register distaste.

‘The name, expeditor, will indeed be Slyte. Perhaps the name may be Sleet or Slate or—’

‘Slyte will do,’ Culzean said, raising a hand. ‘What I don’t understand is this. I was told of an almost one hundred per cent certainty. Why in the name of darkness do you need my services?’

‘The key word, sir, is almost,’ Stefoy said. ‘In the last few months, our brother-seers on Nova Durma have reported a clouding.’

‘A clouding?’

‘The prospect is becoming less certain. As if fate is twisting against it. We need to confirm fate’s path. Make it certain again. Make it true. The prospect was seen to occur between the start of 400 and the end of 403. That time is almost on us now.’

‘I see,’ said Culzean. ‘Now, does this prospect have a focus?’

Arthous reached into his suit pocket and produced a sheaf of crumpled parchments. ‘These are the transcripts made by the seers. The focus is named here, you see. A person called Gideon Ravenor.’

‘Ravenor?’ Culzean said. ‘The writer?’

‘He is an Imperial inquisitor.’

‘Yes, but he writes too. Various essays, treatises. All rather fey and ponderous to my taste, but well thought of. This Ravenor’s the focus?’

‘Him, or one of his close associates,’ Lezzard nodded.

‘Curious,’ Culzean said, taking the parchments and studying them.

‘The Inquisition is already alert to this prospect,’ Stefoy said. ‘They have attempted to thwart us. One agent in particular, Ravenor’s old mentor, the inquisitor Eisenhorn.’

Culzean looked up. ‘Eisenhorn? That old bull? Now he I’ve most certainly heard of. Where is he in this picture?’

‘He attempted to warn Ravenor of the prospect on Malinter last year. We were unable to stop him, though it seems Ravenor himself did not believe the warning. Eisenhorn was later tracked down and slain by our brothers on Fedra.’

‘Glory! You killed Gregor Eisenhorn?’ asked Culzean.

‘We believe so. He was confronted on Fedra, at the Mechanicus temple on Mars Hill. A considerable battle ensued, which ended with the explosive destruction of the entire site. His thread vanished from the seers’ vision thereafter. To a degree of certainty, we are sure he is dead.’

‘To a degree of certainty?’

‘He no longer appears in our scrying mirrors,’ Lezzard said dryly.

‘What about Ravenor? Is he here?’

‘This is where the clouding troubles us. There is contradiction in the seers’ visions. Some say he is dead already. Others say he is here, amongst us, in Petropolis. It is possible he is here under a veil of the utmost secrecy. If so, that might explain the contradiction.’

‘And what are the determiners I can use?’ Culzean asked.

With Stefoy’s help, the master-clancular produced more crinkled papers. ‘These are the determiners we have established. Nineteen names; persons who, we have predicted, will manifestly influence the outcome of the prospect.’

‘Some of these people are… highly placed,’ Culzean said, reading.

‘Indeed.’

‘And Ravenor himself is on the list.’

‘Yes. At this time,’ Lezzard said. ‘We don’t know why.’

Culzean looked up at Leyla Slade. ‘I’ll need a psyker, immediately. Non-aligned, black market. Find out if Saul Keener is still operating on Eustis Majoris. He does good work.’

‘At once,’ she replied.

‘Can you help us?’ Stefoy asked. ‘Can you expedite this?’

‘I believe so,’ Culzean said, rising to his feet. The simivulpa ran up his sleeve and sat on his shoulder. Culzean was still studying the papers. ‘We need to be quick and ruthless. We can’t worry about these determiners. They are all fungible elements. We have to clear the field and hone the prospect down to a bare, simple fact.’

‘You mean we have to kill them?’ Arthous said.

‘Probably. It’s like surgery. We have to excise the muddle. I think we should start with him.’

Culzean showed Lezzard the page.

‘The Fratery couldn’t begin to attempt a killing like th—’

‘That’s what you pay me for. I’ve brought devices with me.’

‘Devices?’ mumbled Stefoy.

‘Shining weapons of destiny,’ Culzean said with a smile. ‘I believe we should wake the incunabula.’

‘Really? Are you sure, sir?’ Leyla Slade asked.

Culzean nodded energetically. He was hitting his stride now, in command, in control. ‘The Brass Thief is very malleable, very adaptive. Yes, I’m sure. We’ll wake him up.’
--------------------
**** Molotch
--------------------
IT TOOK A certain sort of man to perform eight ritual killings in three hours, and he was, without doubt, that sort of man.

Each killing was random, opportunistic, each one carried out with wildly different methods and weapons. The first, with a purloined knife, looked like a back street mugging. The second, a strangulation, was made to seem like a sex crime. The third and fourth, together, would later appear to be a drunken argument over cards that ended with both parties shooting one another simultaneously. The fifth, a poisoning, would have any medicae examiner blaming poorly preserved shellfish. The sixth and seventh, also simultaneous, were electrocutions, and made faulty hab wiring seem responsible. The eighth, the most grisly, was staged to resemble a robbery gone wrong.

She finally caught up with him during the eighth murder. A local moneylender, and part-time fence, owned a house on the lower pavements behind the Basilica Mechanicus. He had slipped in through the back kitchen, found the moneylender alone in a shuttered study, and bludgeoned him to death with a votive statue of Saint Kiodrus.

Then he’d removed some paper money orders and gold bars from the moneylender’s floor safe to cement the notion of a robbery.

‘What are you doing?’ she asked, cautiously entering the gloomy room behind him. The rank, metallic stink of blood choked the close air.

Bent over the body, he glanced at her. ‘What needs to be done.’

He reached down and did something to the bloodstained corpse.

‘You don’t need that,’ he added.

She kept the snub-nosed Hostec 5 aimed at the back of his head. ‘I’ll be the judge of what I need,’ she replied.

‘Really, you don’t need that,’ he repeated, using the tone of command this time.

She lowered her aim, but she was strong and well trained. She didn’t put the gun away.

‘This is madness.’ she said. ‘You were told to stay in the exclave. Secrecy is paramount. To walk abroad invites discovery. And this… this killing…’

Her voice caught on the word. Leyla Slade was not a squeamish woman. She’d done her fair share of killing, but it had always been professional work. She’d never killed for pleasure, or to appease some mental deviation.

She was disappointed with him, he could tell. He didn’t really care, because Leyla Slade wasn’t very important in the grand sweep of things. But, for the moment, there were good reasons for keeping her on his side. She was one of his few friends in the cosmos. He could see the disgust on her face, as if she was being asked to babysit some sociopath. She didn’t understand. He decided it was time she did.

If nothing else, he didn’t like the idea that she considered him to be a homicidal pervert.

‘You think I’m killing for kicks?’ he asked.

Leyla shrugged. ‘It looks like what it looks like. I don’t care what kind of animal you are. I just get paid to mind you. In this case, that means dragging your psycho arse back to the exclave.’

He rose to his feet, facing her. The body on the floor lay in an undignified heap, one slipper off, one stockinged toe turned at right angles. The clothes had been ruffled and disarrayed by the fury of the attack. The votive statue of Saint Kiodrus had made a pink pulp of the moneylender’s face.

‘And if I don’t want to go back to the exclave?’ he asked.

‘Well, I’m not sure I can force you. I have no doubt of your abilities. At the very least, though, we’ll hurt each other. A lot.’

He nodded, and smiled. The smile was genuine. ‘Yes, I believe we would. I like you because you’re honest about these things. We would hurt each other. Let’s not.’

‘Let’s not. Agreed. Now, are you coming back?’

‘Soon. Let’s talk first, Leyla.’

She raised the gun. ‘No. No negotiation. We’re going back.’

He nodded, half turned, and made some kind of quick, flicking gesture with his right arm. She flinched, felt a slight impact against her wrist, and then the Hostec 5 was in his right hand.

He aimed it at her. He expected anger, dismay, perhaps even a futile attempt to retake possession of the weapon.

Instead she said, ‘Teach me to do that.’
--------------------
THEY CLEANED THE moneylender’s house of incriminating traces, and left the victim on the floor of his study, beside the open floor safe. He stood patiently while she dabbed the specks of impact-spatter blood from his face and neck with a wet cloth. His clothes were black, and the rest wouldn’t show.

‘A robber would set a fire to cover the body, if a burglary had gone wrong.’ she suggested. ‘Oh…’

He had already overturned a lamp bowl, and small, blue flames were dancing along the edge of the rug.
--------------------
FIVE STREETS FROM the moneylender’s hab, they entered a small eating house, and took a table at the back. Leyla selected the place because of the low light levels and the fact they could sit away from the street. She ordered a pitcher of petal water, sweetmeats, a cauldro of lemon and tchail rice, and a carafe of the local red wine.

‘This is nice.’ he said.

‘It’s not. You still have my gun.’

He displayed his hands, open. They were very pale, very expressive.

She frowned, reached inside her jacket, and found her Hostec 5 secure in its rig.

‘You can teach me how to do that, too.’

‘If you like. Are you eager to learn?’

‘Some things. I have skills, and they earn me a market price. My skills are good enough to please my master. And he teaches me some of his skills too.’

‘I’m sure he does.’

‘But a girl always wants to learn new things. From a man like you—’

‘Like me? My dear Leyla, not so many minutes past, you characterised me as a deviant killer. A psycho.’

She shrugged. ‘With skills.’ she said.

He laughed. She was a piece of work. When the time came, he might even spare her. Or at least, kill her mercifully.

The food arrived. The waitress gave them no more than a passing look. A couple, taking a late lunch. An off-worlder girl, tall, built like a swimmer, with short fair hair and a hard, unforgiving face and what? Her lover? Her employer? A slender man, dignified, dressed in black, with a hairless face that, though handsome, seemed uncomfortably asymmetrical.

Leyla picked at the rice. ‘You wanted to talk.’

He poured some wine. ‘Six months since we left Eustis Majoris.’ he said. ‘All that while, you’ve sheltered me. Kept me hidden, in your custody.’

‘For safety.’

‘I understand. 1 appreciate that. I also appreciate, if I haven’t told you, the efforts you and the others have made to secure my safety.’

‘It doesn’t look that way. The first opportunity you get, you slip away from us, and go off into a strange city, killing.’

‘There’s that,’ he nodded.

‘So?’ She had no desire to tell him the truth. No need to let him in on the fact that her master had told her to allow his escape, and to monitor it.

‘Our principal is getting stir crazy, Ley,’ Orfeo Culzean had said. ‘He’s kicking his heels, pacing the cage. Let him out for a while. Let him think he’s given us the slip. Give him his head for an hour or two, but tail him and bring him back before he, oh, I don’t know, tries to undermine the planetary government or something.’

Leyla Slade had laughed. ‘I’ll watch him,’ she’d promised. ‘If all he wants is a bit of fresh air…’

Molotch took a finger pinch of rice, added a sweetmeat, and slid the load into his mouth. He munched and then washed it down with a sip of petal water.

‘I needed to get out,’ he said. ‘I have been handled for too long. By you, and, before that, by my Secretists at Petropolis. My life has been lived according to the timetables of others. I needed to walk, free.’

‘If you’d asked, it could have been arranged.’

‘If it had been arranged, then it wouldn’t have been freedom, would it?’

‘Point,’ she conceded.

He sat back. ‘On Eustis Majoris, Leyla, I came so close. I came so close to doing something extraordinary, something that would have changed the Imperium forever. Ended it, probably. But I was thwarted, and I failed, and you and your master were on hand to pull me out of the fire and bundle me away. Now, your master and I work on new schemes.’

‘But?’

‘Do you know who I serve, Leyla?’

‘Yourself? The deep-time plans of the Cognitae?’

‘Yes, and before all of those things?’

She shrugged.

‘I won’t speak their names aloud, or all the food in this emporium will spoil and all the wine turn to vinegar. They are Ruinous Powers.’

‘I understand.’

‘Good. So, you see, I had to give thanks. Though my mission to Eustis Majoris failed, I escaped with my life, to continue my work. I had to give thanks for that.’

‘Orfeo would—’

‘Dear Orfeo doesn’t really understand. I don’t know what he tells you he is, Leyla, but he’s a mercenary. A prostitute. Brilliant, skilled, talented… but he works for money. I don’t do what I do for money, or even power, as power is understood by the grandees of this Imperium of Man. I am, I suppose, a man of quite strong religious beliefs.’

‘You needed to give thanks?’ she asked, drinking a sip of water.

‘To the old gods I serve. I had to make appeasement, benediction. I had to make a sacrifice of thanks for deliverance, even though that meant risking discovery. A sacrifice must honour the eight, for eight is the symbol, eight-pointed. A common follower might have killed eight at the eighth house on the eighth street in the eighth enclave, at eight in the evening, but I eschew such crudity. The agents of the Throne would have recognised the occult significance in a moment. Even they are not that stupid. So I made eight subtle sacrifices that, according to inspection, would seem random and unconnected.’

‘But they still had ritual purpose?’

He nodded. He ate some more, and drank some wine. She refilled his glass. ‘The beggar in the alley I made eight incisions with a knife that weighed eight ounces. I did this at eight minutes to the hour. The housemaid had eight moles on her left thigh, and took eight minutes to suffocate. I was very particular. The gamblers both held double eights in their hands, and eight shots were discharged. And so on. The moneylender, killed at eight minutes past the hour, was slain with eight primary blows, no more, no less, and had been busy accounting the books for the eighth trading month. I anointed all the bodies with certain marks and runes, all made in water now long evaporated. It was ritual, Leyla. It was worship. It was not the act of a psychopath.’

‘I see that now,’ she said.

He felt her remark was perhaps sardonic. He half-smiled anyway and drank some water.

‘Such an extraordinary level of detail.’ she added, scooping up more rice. ‘To plan it like that…’

‘I was taught to improvise. Leyla, I don’t mean to be rude, but I don’t think like you think. My mind doesn’t work like yours does.’

‘Really?’

‘I was trained from birth to utilise the full dynamic of my mind. Trained in noetic techniques that give me an edge. More than an edge. What would take another man a week to plan, 1 can do in a moment.’

‘Really?’ she repeated.

He enjoyed the hauteur in her voice. The scorn. She was tolerating him.

‘Really. Leyla, I’m not boasting or showing off. This is what the Cognitae does to a mind. Acute observation, for a start. The ability to read low-level, passive body language. The ability to notice and compare. To analyse. To predict.’

‘Prove it.’

He lifted his glass and smiled. ‘Where would you like me to start?’ he asked.

‘Oh, you go right ahead.’

‘How many buttons did the waitress have on her bodice?’

Leyla hunched her shoulders. ‘Six.’

‘Six. Correct. Good. How many were undone?’

‘Two.’ she said.

‘Well noticed. The top two?’

‘No, the top one and the bottom one. Her hips were wide.’

‘Again, excellent. Are you sure you haven’t had Cognitae training, Leyla?’

She snorted. ‘All you’ve proved is we both like to look at pretty girls.’

‘Dressed in?’

‘What?’

‘Dressed in?’

‘A bodice?’

‘The silk from?’

‘Hesperus.’

‘Good, but no. Sameter. The weave is tighter, and there is a rumpled quality, a Touching, to Sameter silk. And the buttons were made on Gudrun.’

‘Really?’

‘They were gold, and had a hallmark. As she leaned over…’

Leyla put down her glass. ‘You’re making this up.’

‘Am I? The man at the booth next to us. We passed him on the way in. Rogue trader, armed. Where was his concealed weapon?’

‘Left armpit. I saw the bulge. Got a blade in his right boot too, under the hem of the trouser.’

‘You are sharp.’

‘It’s my business to know.’

‘Was his moustache longer on the left or right?’

‘I… why does that matter?’

‘Shorter on the right, because he smokes an obscura pipe, and the hairs don’t grow so fast on the side he sucks the mouthpiece. You could see it in his mannerisms, with the lho-stick. A habitual rise and draw. Which means?’

‘He’ll be unpredictable. And jumpy. Obscura does that.’

‘Now you’re learning.’

‘It means nothing,’ she laughed.

‘The man by the window. Left- or right-handed?’

‘Right. He’s drumming the fingers of his right hand on the table top beside his cup of caffeine.’

‘Wrong. He’s watching the street crowd, because he’s waiting for a business partner he doesn’t know. His left hand is under the table, on the butt of his weapon. A Hecuter model, badly stowed. The right hand is a distraction.’

Leyla shook her head. ‘Should I go over and ask him to prove it?’

‘If you want to get shot. The barman. 19th Gudrunite Irregulars. A Guard veteran.’

‘Why?’

‘Tattoo on his left wrist. “Company of Angels”. The vets of the 19th took that as a tat after Latislaw Heights.’

‘You can see that?’

‘Not from here. But on the way in. And you—’

‘Me?’

‘You’ve eaten enough, you’re full. But you like the rice, so you keep picking at it, even though you don’t want it.’

‘It’s good rice.’

‘And you haven’t touched your wine in thirteen minutes. You keep playing with the glass, but you don’t drink, because you’re afraid that if you get merry, you’ll lose control of this situation. But you play with the glass all the same, so as not to draw attention to the fact you’re not drinking.’

‘That’s just nonsense.’

‘Is it?’ He looked at her. ‘You sit slightly sidelong to me, favouring your left buttock, because your right hip gives you pain. Old wound? An augmetic?’

She breathed out. ‘An augmetic.’

Molotch clapped his hands. ‘You dearly want to go back now, but you’re afraid of goading me, or having to force me. You want to make it seem like my idea.’

‘Now, look—’

‘You’re quite certain I don’t know that Orfeo instructed you to let me loose for a few hours. Orfeo thinks I’m going stir crazy. The idea was to let me walk around and blow off steam.’

‘Dammit, Molotch—’

‘Don’t damn it at all. Enjoy it. What could I do, do you suppose? What could I do, just sitting here?’

‘I don’t know.’

Molotch removed a tiny phial from his sleeve and put it on the table top beside the cauldro of rice. ‘Osicol Plague, in suspension. I took it from Orfeo’s personal kit. If I release it here, I could decimate the entire city quarter.’

‘For the love of— No!’

‘I won’t. There’d be no sense in that. But consider the options. The banker at the table to our left. He works at the city mint. He has a brooch on his waistcoat, before you ask. The sigil of the banking guild, and the office of coinage circulation. If I dropped the phial into his business case, he would find it and open it when he returned to his office. The mint would be contaminated, and would have to be sealed off for fifteen years. The local currency would crash, and bring the subsector economy down. Decades of damage. Or take that young man over there, the one in the private booth. He’s the second son of a minor baron, slumming it, but I know he’s in with the court crowd.’

Molotch produced a small medical injector from his pocket and put it down on the table beside the phial. It was full of clear fluid. ‘Suspension liquid. Inert and viscous, metabolised in six hours. I could go into the washrooms, load the plague solution into it, and bump into that second son as I came back. In a day or two, the entire royal house of this planet would be dead from contact plague. An ideal moment to stage a coup.’

‘But that’s just… just…’ she whispered.

‘Now you’re getting the idea,’ he said. ‘What about this? That drunk by the bar. I’ve been gently hypnotising him with finger movements since we came in. Allow me to prove it.’

Molotch moved his fingers. The drunken man lurched and tottered over to them.

‘What’s your name?’ Molotch asked.

‘Sire Garnis Govior, sir,’ the man wobbled.

‘And your job?’

‘I am chief under translator to the House of the Governor, sir.’

Leyla stared at Molotch.

‘And you thought I’d let you pick this bar.’ he smiled. ‘It’s a famous haunt of the Administratum classes. I noticed Garnis here because of his signet ring.’

‘This ring?’ the man asked, displaying it so abruptly he swayed.

‘The very same. You have face time with the governor, then?’

‘I do, sir, I surely do.’ the man said, wobbling.

‘So, if I asked you to strangle him the next time you saw him, setting off a local sector war that would bring in Houses Gevaunt, Nightbray and Clovis, you’d have no problem?’

‘None at all,’ the man assured Molotch. ‘Not a problem at all.’

‘You’d strangle the Lord Governor?’ Leyla asked.

‘Like a bloody shot. Like he was a bloody whelp. Yes, mam.’

‘But I won’t,’ said Molotch. ‘You can go now, Garnis.’

‘Thank you kindly,’ the man said, and staggered off.

Molotch looked at the wide-eyed Leyla. ‘Every opening. Every chance. Every chink. That’s what the Cognitae are trained to do. To look, to see, to find, to use. In the course of this delightful lunch, Leyla, I could have brought the subsector down three or four times over. Just like that.’

He flicked something away with his thumb. It landed on the floor of the bar and broke, oozing fluid.

‘Oh holy-!’ Leyla began.

‘Relax. It’s just the suspension fluid. The plague’s in my pocket. So, let’s consider the Inquisition.’

‘The Inquisition?’

‘Most particularly, the office of the ordos on this world.’

‘You can’t see that from here.’

‘Oh, I can. In the over-bar mirror. See?’

‘Terra, I hadn’t noticed that.’

He sipped his wine. ‘I can see the fortress of the Inquisition from my seat. Such a big fortress. Towering over the city. It was built by the Black Templars, you know? Long since vacated, but one day they might be back. Until then, the Inquisition uses the keep. It’s going to be a bloody fight the day the Templars return. Anyway, they’re flying flags. Several dark flags. What does that mean?’

‘Does it mean anything? They’re flying flags.’

‘The Inquisition doesn’t suppose anyone understands their protocols and heraldry. Black flags above their fortress. Just for show. Just for threat. But I have made it my business to understand and monitor the way they signal to one another.’

‘So? I can barely see the mirror from where I’m sitting.’

‘I’ll tell you what it means. The flags are the black crests of Siquo, Bilocke and Quist, symbols the Inquisition identify with respect and honour. They are flying ceremonially. There are envoys in residence. Several high-ranking envoys. Actually, you can tell that simply by the number of weapon ports they’ve uncovered. Someone important is here.’

‘Meaning?’

‘Meaning, Ravenor’s here, as we feared, and they’ve decided to rein him in. Which is good news for us.’

There was a sudden, brutal crash. Voices around the eating house rose in alarm. Garnis had slipped over in the pool of suspension fluid and brained himself on the edge of the bar rail.

He was dead.

‘Let’s go,’ said Molotch.

They rose and picked their way out of the eating house, moving around the crowd that had gathered around Garnis’s misfortune.

‘That’s nine, ‘ Leyla whispered. ‘I thought you only wanted eight?’

‘I did, but I’m not stupid. This one isn’t ritual. This is a ninth to ruin the pattern. The ordos are sharp and clever. They would have seen a pattern of eight except for this.’

He bent down in the edge of the crowd and picked up a small piece of the broken glass phial Garnis had slipped on.

‘A present,’ he said. ‘A deodand for your master.’

‘I’m sure he’ll love it,’ said Leyla Slade. ‘Wait.’ she added.

He paused. She licked her right index finger, reached out, and wiped away one last lone speck of blood from his face that she’d missed earlier.

‘Thank you.’ he said.

They stepped out into the bright day and the bustling crowd swallowed them up.
--------------------
**** Coherence
--------------------
THE FACTOR’S NAME was Stine. This piece of information emerged early on in what turned out to be over twenty minutes of loquacious preamble. Stine liked to talk. It was part of his performance.

+Stick with it.+

Every factor they had made approaches to (every factor in every hall in Berynth, most likely) had his own version of the performance, some variation of the mercantile courtship dance, the wooing of the customer. It was all part of the purchasing experience. Customers expected it.

There would be a warm greeting, a guided stroll from the reception chamber into the factor’s display rooms, an offer of refreshments and a steady, light flow of conversation leading to a more specific extolment of the merits and traditions of the hall the customer had chosen to patronise. Certain themes were developed by the factor, with practiced verbal skill, designed to snag in the customer’s thoughts and stay there: luxury, exclusivity, quality. The customer was, after all, going to spend a great deal of currency.

And the customer wasn’t a customer. That was too coarse a term. He or she was an emptor. Just as the factor wasn’t a salesman or a shopkeeper. There were standards of decorum in Berynth.

+He’s going on and on and on.+

+Stick with it.+

Stine had met her at reception. The hall stood at the northern end of the Promenade St Jakob, an area of up-hive Berynth densely and famously packed with noted hall premises. The deep street-stacks outside were tiered with ouslite walkways and black iron railings, and strung with thimble lamps, a cavernously dark place of rising black towers, some of which grew up through the hive’s great armoured roof like a sea urchin’s thorns. He wore a patterned coat and a practiced smile. Reception was a wide, inviting vault panelled in varnished wood.

Stine had bowed and led her back through the show galleries into the main chamber of display. Pools of emerald light contained glass showcases in the gloom. The floor was panelled with bronze slabs, and centuries of footsteps had worn a bright patina pathway across them. There was a simple wooden desk, faced by some leather sofas, and he invited her to sit down. Stine talked all the way. His performance, it seemed, would be all about words. Some of the factors she had so far encountered favoured a discreet approach, or a humble one, or allowed the emptor to lead the conversation. He was prolix. He, said Stine, was the ninetieth Stine, uninterrupted, to serve in the post of factor for Stine and Stine’s Hall. That was a legacy, a family business. Stines had been at Berynth for sixteen centuries. The hall was one of the oldest, their marks amongst the most noteworthy in the sector.

‘Here,’ said Stine, ‘you may admire the hall’s marks, on this trinket.’ He held it up in front of a magnifying viewer for her to inspect. His hands were overly pale and well manicured, looming in the lens. The trinket had more pearls in it than some oceans. ‘The Stine mark.’

‘I see it repeated, in stylised form, upon your doublet coat,’ the emptor remarked.

Stine simpered, delighted that she should notice. He complimented her, extensively, on her eye and her intelligence.

+I think he wants to marry me.+

+Shush. Stick with it.+

Stine was very taken with this particular emptor: an elegant woman, well dressed, moneyed. Custom had been slack in the last few weeks, with few clients of note delivered by ferry ship to inspect the halls.

This woman was something different. She had taste. She was beautiful, if you liked that kind of thing.

He was telling her a little more about the business, about the fact that he was not as accomplished in the lapidary work as his many brothers, which is why he was the factor. He left the skilled lapidary to his kin, who could ‘assay and value’, so he boasted, with their bare hands.

But he sensed she was becoming bored. That happened. She had stopped sipping the amasec he had fetched out on a lacquered tray, and she no longer picked at the candied ginger in the little finger bowl. A good factor noticed these details. A good factor knew when to up the tempo and move the courtship towards the consummation of purchase.

‘Are you looking for a particular piece?’ he asked, walking around the simple hardwood desk with its velvet panels. He took out his keys and opened the doors of the nearest plate glass displays. Recessed fans murmured in the invisible ceiling of the chamber of display. It was a comfortable twenty-two degrees, with the right amount of humidity and air-flow to keep emptors fresh and relaxed. Outside Berynth, it was a murderous sixty below.

‘I am,’ said the emptor, sitting back on one of the leather sofas and crossing her long legs. ‘Or rather, a particular piece for a particular purpose. A society wedding on Gudrun. I won’t use names—’

‘Of course not!’ the factor said with a bow.

The emptor smiled. ‘But the match involves some people of influence. Of blood.’

‘I understand.’

‘The son of a governor subsector.’

‘My word!’

+Oh, try to stay in the realms of reality, please!+

‘Shut up.’

‘Pardon?’ asked the factor with a slightly bewitched blink.

‘Nothing. I said, my niece… the bride… deserves something special.’

The factor bowed again. ‘I do understand. And, if I may make so bold, financially…?’

He let the deadly word hang.

She shrugged. ‘Nothing less than a quarter million,’ she said mildly.

For the third time, he bowed. ‘Oh, ma’am. I have a few trinkets that may well please your eye and your taste.’

+I think I just made him very happy.+

+Well, that’s all he’s getting. I’m not paying for a quarter million crowns’ worth of anything.+

+Except information?+

+Except that.+

She kept her grin fixed. Oblivious, the factor began to lift red satin trays out of the display cases. Several servitors appeared from the shadows, took each tray as he lifted them out, and brought them over to her, holding them so as to display them. The servitors were old and worn, but of great mechanical quality. She realised that the hall cultivated a slightly worn, slightly Spartan feel, so that the pieces would glow by comparison. It was all very clever, very judged.

‘A design for the throat is always appreciated. These on the first trays are allochromatic zalachite, with red gold. I have them in diamond too. Cabochon cut is usually preferred.’

‘They’re delicious.’

‘Or a jewel setting for the brow? Sapphire, with opal and signet. Black silver or chased adamite are very sought after.’

‘This one is nice,’ the emptor said.

The factor came over, lifting the piece from its tray with a midwife’s care. The jewels shone in the light. The lights above the desk were well placed to make jewels scintillate at that particular point in the chamber.

‘The chrysoberyl? Yes, a favourite of mine. Note the glorious asterism. Would you like…?’ he asked, holding it up.

‘Please.’

‘Glass!’ the factor called, and other servitors hurried forward, holding up looking glasses all around the client. The factor placed the necklace around the emptor’s throat and fastened it.

She admired herself.

‘Has she your colouring?’

‘I am somewhat paler than my niece,’ the emptor said.

‘Then something with cygate or quofire? Tourmaline, perhaps? I have a pendaloque-cut tourmaline with the most stunning dichroic properties.’

‘You know your business, sir.’

She tried on three or four more pieces. The servitors held the looking glasses perfectly still.

‘I worry,’ she said, at length, ‘this is a nuptial gift. It should be for the groom as much as the bride. He is my brother’s son, after all.’

The factor paused. ‘And the bride is your niece?’

‘Did I say that?’

+You said that.+

‘You said that, I’m sure.’

‘By marriage, I mean. You know how it is, in the dynastic melee that is court life.’

‘Court… life?’

‘Yes,’ she replied.+Did I get away with that?+

+He’s too awestruck to notice. Play up the court thing. He thinks you’re anonymous nobility.+

‘I really don’t like to talk about it,’ the emptor said.

‘Of course not. Well, perhaps I can show you some of our ornamental settings? Horologs, rosettes, Imperial aquilas. For aquilas, we favour gold and composites, and also organic gems. The oceans here on Utochre produce the most iridescent nacre effects.’

‘You have a charter to produce authentic aquilas?’

‘We are Imperial jewellers, of course. By appointment.’

‘Show on,’ she said.

He displayed several more complex objects to her. Some were so valuable he had to silently lock the suspension shields around the desk while she admired them.

‘This is really stunning work,’ she murmured, turning a piece over in her hands. She held it up to the light. ‘What do you call this property?’

‘Birefringence, or double refraction.’ Stine replied.

‘Oh, I can’t decide.’

The factor smiled warmly.

‘I just can’t decide. I feel… incoherent.’

The factor’s smile froze and became cold.

‘What?’

‘I feel incoherent. Can you help me with that?’

The factor took the piece out of her hands and put it back on its satin tray. ‘Did I say something wrong?’ the emptor asked, slightly taken aback.

+Yes, I think you did. He’s not happy. Make your apologies and get out.+

‘We don’t cater for that sort of thing here.’ Stine said sniffily. ‘You’ve been wasting my time. Perhaps you’d like to leave.’ The factor was angry with himself. It wasn’t often he misread an emptor so completely.

‘I’m sorry,’ she said, rising. ‘I didn’t mean offence.’

‘Please leave,’ Stine spat. He took a control wand from his belt and waved it briskly. All the servitors retreated obediently back into the shadows.

+Get out.+

‘I meant no offence,’ she repeated. ‘I’m sorry.’

‘Your kind are always sorry,’ said Stine. ‘I should report you.’

‘Report me to whom?’ she asked.

+Get out, Patience. Now. We can’t afford an incident.+

Stine turned to look at her. His face was hard, poisonous. ‘You come in here, into this distinguished hall, looking for access to that ungodly place! Stine and Stine does not do that sort of thing!’

‘I have apologised. I have apologised sincerely, sir.’

+Patience…+

‘I should call the magistrates,’ Stine blustered. He waved the control wand he had taken from his belt again, reaching into the air for a hive-hub connection. She heard the buzz of a handshake.

‘Berynth Magistratum, I have you,’ the speakers on the desk warbled.

‘This is Stine at Stine and Stine. I have a—’

There was a click as the link disconnected.

‘Hello? Hello?’ Stine said.

+I’ve blocked his comm. Now, Patience, please walk out of there.+

Stine, of Stine and Stine, tried his wand again. When he looked around, the woman had gone.
--------------------
SHE STORMED OUT of the hall’s reception chamber onto the iron-railed promenade. The hanging thimble lamps shone overhead with a feeble, pearly light. Instinctively, she allowed the stream of pedestrian traffic to swallow her up and carry her along. All around her were the rich and privileged of a double-dozen worlds, strolling along, some body-guarded, some carried in ornate litters, some sporting parasols or long trains.

+Sorry,+ she sent.+I fumbled that.+

+It doesn’t matter.+

+It does. It took me by surprise. His reaction. He was so… angry.+

+Proud, that’s all. We aimed a little too high, trying an Imperial jeweller. We can learn from this.+

She threaded through the crowd and headed down a flight of iron steps onto a lower stack. It was quieter there. She stopped and leaned on the guard rail, gazing down into the deep interstack drop and the street levels below. She got her breath.

+I’m off my game, Gideon.+

+You’re not. You’re fine.+

+I can tell when you don’t mean it. I’m off my game.+

+Maybe you are, Patience. Would you like to talk about why?+

+I’m off my game because I can’t stand this. I hate what we’re being forced to do.+

+That’s only reasonable. So do I.+

She sighed, let go of the guard rail, and started walking again.

+How are the others getting on?+

+Much like you. They’re not getting anywhere. Although they’re not quite as combative as you.+

+I said I was sorry, Gideon. What happened back there? The last few places I tried just got a bit cagey when the subject came up, but that… he was so venomous. As if I was a criminal.+

+As I said, I think we aimed too high. Stine and Stine is about as illustrious a hall as there is on Utochre. The man felt insulted. His hall was insulted. The inference hurt him. Put it behind you.+

+I think you should switch me out for Kara. Kara would do this better.+

+Put it behind you.+

She had walked to the far end of the stack level, into the gloomy architectural cleft where the armoured curve of the roof dome met the stack ends. There was a small and dingy dining house there, built into the eaves of the giant outer roof. It clearly catered for under staff and the utility personnel who worked menial jobs in the halls. The staff frowned and whispered at the sight of her fine, expensive clothes. She ignored them and sat down at a vacant table. Around her, household staffers, gig drivers and stack-gutters hunched over and murmured to one another.

‘Mamzel?’ asked a maid in an apron, coming over. ‘There is a good place a level up where you might be more comfortable.’

‘I’m comfortable here, thanks,’ said Kys. ‘A caffeine. Black, sweet, and an amasec, if you have it. Cooking will do.’

‘Yes, mamzel.’

Waiting for her order to arrive, she rose again and approached the heavy shield plate that formed the norm wall of the dining house. She touched the control stud, and the shield slid up. She looked out on the world outside through the thick glass. The blackened, fat bellied slopes of Berynth hive shelving away below, the ice beyond, under a broiling sky. The savage gales beat at the glass and bombarded it with ice crystals.+We are criminals now, aren’t we?’+

+Patience…+

+Oh, stop it. We are. I know it. Rogue.+

+It’s the only way we have left.+

+I hate it, Gideon, and I hate the idea that he’s still out there. I hadn’t realised before, but when you told me he was dead, it felt like a weight lifting off me.+

+I’m sorry. It felt that way to me too, if that’s any consolation.+

Kys put her hand against the glass and stared out at the nocturnal blizzard.

+However… Patience, we need to retain control. We can’t afford to be seen, and I think you were about to pin that Stine fellow to his chair by his scrotum.+

She smiled.+At the very least. I am so sorry. I’m finding this hard. So… how are the others doing?+

+Maud and Carl have covered five halls between them. Nothing. Harlon has managed to secure us an underboat. Now Carl is off buying rings down in the brash quarters.+

+Doesn’t he have enough rings?+

+I don’t know. I don’t pay attention to such things. Can one have enough rings?+

+Not if you’re Carl, apparently.’

The maid returned with the order. Kys went back to her table, drank the amasec in one and sipped her caffeine. It was too hot, and the amasec had been rough. Cooking, definitely. She dropped a generous number of coins on the table and stood up.+What’s next?+

+Can you handle another?+

+Yes. Of course.+

+Only when you’re ready. Exit and head up a stack. Then along to your right. Corlos and Saquettar, Lapidary.+

Patience sighed.+How do I look?+

+Beautiful.+

+Then let’s go.+

+Wait. Wait, Patience. Sit back down. Drink your caffeine. I believe Carl has found something.+

‘What’s your name?’ Thonius asked.

‘I am Lenec Yanvil, sir,’ the man replied. He was small and potbellied, with nimble hands. He smelled of pitch and polishing amalgams.

‘Well, Lenec Yanvil, if I was to, say, purchase that gorgeous lapis signet I wavered over, would you confide in me?’

‘I’d be delighted to,’ said Yanvil.

Thonius produced some more large denomination coins and counted them out onto the stall’s stained baize cover. Yanvil picked up the signet ring, and carefully wrapped it in a small piece of felt.

‘It’s all about reward, you see,’ he said quietly. ‘Palms greasing palms. The halls have an arrangement with the House. They have had for centuries. Some will admit it, quietly, others deny it, but they all benefit.’

‘How so?’

‘Every single hall in Berynth pays a retainer to the House in return for coherent information about new seams, stone beds and metal deposits. The jewellery business here is what Berynth is famous for, but it’s just a by-product of Berynth’s heavy industry. The first halls to set up here in the old days made their profits from the spoil of the intensive ore mining, but no one these days is going to sustain a business on accidental finds. Neither do the halls have the financial resources to maintain comprehensive mining operations of their own. So they pay to know where to look, and then hire out the mining complexes to do spot excavations. Everyone profits.’

‘It sounds very companionable.’

Yanvil shrugged. ‘The halls are very proprietorial about who gets access to the House. They vet. It’s an exclusive service. But then, Throne knows, you have to be pretty exclusive to come all this way to go jewellery shopping.’

‘How do they vet?’

‘You need to find an agent. They’re very exclusive too. They don’t advertise. A client hooks up with an agent, the agent takes them to an appropriate hall and makes an introduction. Then the client has to make a purchase, something pricy. Horologs are good, I hear. The purchase price is the hall’s fee. The client then gives the item to the agent as a gift. Later, the agent sells the item back to the hall for a cut of the fee. The item goes back in the hall’s display, and the hall’s made a tidy profit.’

‘Very neat.’

‘Palms are greased, backs are mutually scratched. Everyone smiles.’

‘So, to find an agent…?’
--------------------
TWO
--------------------
‘INCOHERENT? WELL, THAT’S a different thing altogether.’

‘Oh? How so?’ asked Carl Thonius sweetly.

Down in the brash quarters, in the low hive, things were more basic. The stack-depths were cluttered with dirty stalls and tented stands of soiled canvas, selling knock-off and bad-cut gems, trinkets, keepsakes, totems and charms. The air was smoggy from the oil drum fires and stank of liquor and refuse. Bagpipes keened and drums beat. There were fire dancers, shucksters, lhofers, and the constant, shabby bustle of the hab classes and the migrant workers, washing aimlessly back and forth in the low hive like rank water in a bilge.

The stall holder glanced around to see if anyone was listening. He had one sunken eye, from years of using a stubby jeweller’s loupe.

‘Seeing as how you’ve bought so many rings from me, my friend, let me tell you. Coherence comes at a price. You have to be introduced, for a start.’

‘You do?’

‘Have yourself an introduction. The halls expect that.’

‘Can you provide such a service?’

The stall holder laughed a phlegmy laugh. ‘Mercy, no!’ He gestured around at his modest stall. ‘I’m brash, born and bred. I don’t move in those kind of circles.’

‘But you know the system?’

He nodded.

‘Well, I might know something.’

‘Palms are greased and backs are mutually scratched, eh?’ said Thonius. ‘That gold thumb ring there…’
--------------------
‘SO STINE KNEW all about it?’ asked Patience.

‘According to my source, they all do,’ said Carl. ‘They just don’t like to talk about it.’

‘That little shit. He made me feel this big, and—’

‘Because you weren’t introduced,’ said Carl quietly. He was sitting on a couch in the bay window of the chamber, admiring the new rings on his hand. The winter night ticked and rattled at the window panes behind him.

‘I’ve half a mind to go back there and shove a kineblade up his arse,’ Kys growled.

‘Half a mind is all you’ll need for that,’ said Ballack, overhearing her as he walked in from the adjoining room. ‘We have to be careful.’

Kys turned slowly and glared at the interrogator. In the two months he’d been with them, he’d shown an unfailing ability to wind her up.

She felt sorry for him, of course. Ballack had been through an ordeal, and he’d lost the hand, after all. He’d also shown creditable initiative bringing the whole matter to Ravenor. Still, he was, as Kara might say, a smug little ninker when all was said and done, and far too pretty for his own good, with that long white hair and those ion-drive blue eyes.

For once, he seemed to notice her displeasure. ‘Sorry, Kys,’ he said. ‘That was rude of me. It’s just… sometimes I’m very aware that I’m risking my entire career doing this. No offence, sir.’

‘None taken,’ Ravenor replied, his voice issuing as an electronic monotone from his chair. ‘We’re all risking our careers.’

No one spoke for a moment. The fire crackled in the grate and warmed the room, part of a rented suite in Berynth high-hive. The floor was a checkerboard of brown and cream wooden tiles, the walls panelled in dark umwood. The fireplace was an extraordinary frame porcelain inlaid with silver and nacrous shell. The logs spat and coughed. Kys, Ballack and Thonius reflected quietly on their situation, each in their own way. Patience wondered what depth of worry knotted in Ravenor’s mind.

+I realised why Stine’s reaction upset me so,+ she sent.

+Go on.+

+It wasn’t that he made me feel like a criminal. It was that I am a criminal and he forced me to realise what that means. Everything I’ve ever done in your service, Gideon, I’ve done in the knowledge that I’m serving the Emperor’s ultimate will, but there’s no legitimacy any more.+

+There will be. I will make the ordos understand why I’ve had to take this course. We will have our sanction.+

+But there isn’t any right now.+

The chair swung around from the fireplace and faced the three of them. They all looked up respectfully. ‘I’ve said it before, but for the record, let me repeat… when we’re done, I will bring us to Myzard. To Rorken, if necessary. 1 will make account, and I will take the reprimand.’

‘I wonder who they’ll send after us?’ Carl mused, admiring his rings again. He looked up at Ravenor. ‘I mean, they’re bound to send someone, right?’

Ballack sat down on a tub chair. ‘Lilith. Myzard will send Lilith and a team. Lilith Abfequarn is good. She already has a black notation rating. We can only hope she doesn’t have the first clue where to start looking. That means, we can’t make a scene.’ He looked pointedly at Kys.

‘Fair point. It’s been made already. No one needs to tell me again,’ Patience replied. ‘So, Carl? Where do we find this agent?’

Thonius was about to reply when the apartment’s outer hatch slid open. Patience saw how quickly – how nervously – Ballack rose and placed his good hand on the grip of his pistol.

It was Maud Plyton. A version of Maud Plyton, at least. She looked strange, buttoned into a long gown of Parsiji lace and deep green silk. The material strained and bulged voluptuously. Her cropped hair and heavy make-up created the unfortunate suggestion of a man in drag. ‘Nice to see you too,’ she sneered at Ballack, seeing his hand on his gun. ‘Not had a good day, Maud?’ asked Kys.

Maud flopped down heavily on the nearest couch and yanked off her high, feminine shoes. She’d borrowed them from Kara and they didn’t fit well. Her feet were sore. ‘Bastard things!’ she declared as she tossed them over the back of the couch. ‘I’m sorry to say,’ she said, ‘I got nothing.’ ‘It’s all right, Maud,’ Ravenor replied, ‘we have a lead now.’

‘Oh, good.’ Plyton replied, getting up. In one, ungainly upward drag, she wrenched her expensive dress off over her head. The dress was another lend from Kara, tight and too short for Maud Playton’s frame. She wriggled the dress off her arms, and headed out of the room in her support hose and whalebone corsetry. There was a considerable sense of pneumatic tension. ‘Thank Throne that’s off! It was throttling me. 1 don’t do posh.’ ‘You do it very well.’ said Ravenor.

Plyton grunted dismissively from the next room and called out, ‘I do undercover all right, but that was not a bit of me. I haven’t had that many unfamiliar hands in my chest area since I was last assigned to vice.’

‘Well, fancy,’ said Carl.

Plyton stuck her head back around the door, and then lifted one arm and sniffed her armpit. ‘And I stink. That’s not high-class, is it?’

‘I can’t begin to tell you,’ Carl said.

‘Is there a drink going?’ Maud asked.

‘I’ll get you one,’ said Ballack.

‘Help me unlace this bastard corsetry someone. I beg you. Preferably you, Patience, seeing as it’s yours.’

Smiling, Kys walked across the room and followed Plyton into the adjoining chamber. Plyton leaned forward and Kys started to untie the laces. It was a struggle.

‘Emperor help me, I can’t breathe. How do you wear this stuff, Kys?’

‘Well,’ said Patience smoothly.

‘Here’s that drink,’ said Ballack, appearing in the doorway with a glass. He hovered.

‘Here. In my hand!’ Plyton said. ‘I can’t reach it when you’re standing over there.’

‘I was just… mindful of your…’

‘I’m sure I haven’t got anything you haven’t seen before,’ Plyton said.

‘No, just a little more of it.’

‘Oh, you wish!’ mocked Plyton, taking the drink and sipping. ‘Yum, lovely.’

‘If anyone gets to go back to Stine and Stine,’ Kys called out, tugging at the corset laces, ‘it’s going to be me.’

‘I was hoping to participate myself,’ said Ballack. He had returned to the fireside in the neighbouring room, and was trying to secure his long white hair into a pony tail. It was a hard feat to accomplish with just one hand. Evisorex had severed his left hand cleanly, and his wrist stump was sealed in a black leather nub packed with micro healing systems. It would be another month at least before it was ready for an augmetic graft. ‘I really would like to serve, sir,’ he said. ‘I want to be useful.’

‘The pair of you, then,’ said Ravenor. ‘If that’s all right with you, Carl?’

Thonius shrugged. ‘I’m happy.’ He rose to his feet. ‘Can I help you with that, Gall?’

‘Thank you.’ Ballack replied. Carl began to comb Ballack’s mane with his fingers to tie it up.

‘We’ll wait for the others to return,’ said Ravenor. ‘You can get started in the morning.’

‘So what’s keeping Nayl?’ grimaced Plyton as Kys slowly released her torso from its confinement.
--------------------
