* Dan Abnett Extracts                                                           :examples:scifi:abnett:

*** Legion

**** Insertion

THE ESCORT, A young geno company bashaw and three sleepy troopers, were waiting for him in the rear yard of the palace compound. The ride was a light speeder, the hull of which had been sand-blasted back to bare metal by the environment.

‘Sir,’ the bashaw saluted as Grammaticus walked out of the lit doorway into the darkness of the yard with his bag over his shoulder. It took a second to place the man’s background accent… Yndonesia, Purwakarta Administrative District, perhaps one of the Cianjur hives.

‘What’s your unit?’ Grammaticus asked in Bahasa Malay. The bashaw blinked in surprise and smiled.

‘Arachne, sir,’ he replied. ‘I didn’t know you were a Pan-Pac, sir.’

‘I’m not. I’m from all over.’

They got in and rode out of the yard, and through the descending levels of the ancient desert palace, via checkpoints, gateways and night-watch barricades where sentries lurked beside sputtering braziers, their rifles hooked through their folded arms. Papers and biometrics were routinely checked.

The Nurthene had a subversive streak. Experience had taught the Imperial Army that the Nurthene had spies of their own, saboteurs too. It felt odd to be a spy checked on the way out.

Outside the palace perimeter, the speeder picked up velocity and coasted along the bombed-out avenues and dust-dressed streets of the township surrounding the compound. The sun was threatening to rise behind the passing ruins. Grammaticus sat back in the rear seat, trying to relax, trying to compose his focus into identity immersion, feeling the breeze of motion against his face. He began to regret making a connection with the young bashaw. The officer, sitting up front, kept leaning around and talking to Grammaticus about places in Cianjur that Grammaticus had never visited, nor had any wish to visit. Grammaticus had been in Cianjur once, long ago. He’d been there as part of an army that had burned the place down, five hundred years before the hive the bashaw had grown up in had even been planned.

He closed his eyes and thought of Rukhsana.

It’s as if you see right into me. There was too much truth in that. His mind saw into everything. It made him think of the thing he tried never to think about: that day, long ago, meeting the Emperor, shaking his hand, tasting the power, and seeing, behind the glamour of that handsome, noble, healthy face, seeing…

Just for a nanosecond. Seeing…

‘Are you quite well, sir?’ the bashaw asked. ‘You went rather pale all of a sudden. Is it motion sickness?’

‘No. I’m fine. Absolutely fine,’ Grammaticus replied.
--------------------
THEY CAME UP out of the ruins, and followed the rutted dispersal tracks around the back of the dug-in Imperial lines. The sun was rising, crisping the lower edge of the sky. In the lea of the earthworks, for kilometre after kilometre, gun emplacements made sulking silhouettes against the dawn, and millions of bivouac tents covered the ground like blisters, breakfast fires glowing. They passed standards and banners hanging limp in the slowly heating air.

‘That’s my lot,’ the bashaw called out as they shot past a particular standard. Grammaticus turned his head to look, and saw Arachne, a mousy but surprisingly large bosomed girl, if the banner’s image was any guide, weaving her complex web of fate and destiny.
--------------------
THE INSERTION POINT was an outfall of the city’s antique sewer system some eighteen kilometres west of the palace. It had been exposed by shelling about three months earlier, and was well guarded. Apart from the geno sentries, automated gun-servitors watched it, unblinking, day and night. The Nurthene guarded the other end just as proficiently, but Grammaticus wasn’t going all the way to the other end.

The bashaw introduced him to the point officer, a ruddy-faced hetman called Maryno. Maryno wanded the servitors to default/passive, and stood watching with the bashaw as Grammaticus slithered down the shattered embankment into the maw of the outfall.

Darkness, as had so often been the case in his life, embraced him.
--------------------
TEN KILOMETRES AND ninety minutes later, he pulled himself out of a run-off vent not far from the rising walls and banked towers of Mon Lo Harbour.

He had already switched off his lamp, and left it in the bag, along with his canvas jacket and army boots, stuffed behind the loose bricks of a culvert.

His journey along the dark chute had provided him with almost enough time to complete his identity immersion. He was no longer Konig Heniker. He was D’sal Huulta. In all, he had taken very few real measures to disguise himself: a wrap of pink silk over his desert suit, felt shoes in place of the army boots, a desert shawl expertly pulled around his head. His skin was tanned, though not as dark as the average Nurthene, and a strict Nurthene observer of the Pa’khel would have worn his hair tied in a net under his shawl, and anointed his scalp, armpits, groin and belly with scented oil.

Grammaticus never went to such extremes, even though his Imperial spymasters recommended he should. He knew that his mind was more than capable of smoothing over most epistemological blemishes. Besides, the anointing oils smacked of a ritual offering to the Primordial Annihilator, something he was not prepared to undertake.

He fastened the hooked knife worn by all Nurthene to his under-belt, then strapped on the broad over-belt with its three pouches for fluid, mineral salt and currency. He washed his hands in the trackside dust to blacken his fingernails. Apart from the knife, he carried no weapon, except, of course, for the ring.

The sun was crawling up into the sky, having revealed itself during his trek through the dank underworld. He felt its searing heat on his head and shoulders, but he was near the sea, close enough to both feel and smell it. Fresh winds came in from the harbour shore, snaking in across the desert outland. He sniffed moisture. He began to walk towards the banked towers and enamelled walls of the port city.

Others were doing the same. War or no war, life went on. Straggles of traders and merchants, some with trains of pack animals, were heading into Mon Lo from the hinterland, hoping to do business at the city markets. Migrant workers were walking to the port in search of employment. Refugees and displaced citizens were coming to the gates, fleeing the Imperial advance. Grammaticus fell in with them.

As he walked, Grammaticus began the psychic litany in his head, the final progression towards immersion in another dialect and culture base.

I am John Grammaticus. I am John Grammaticus. I am John Grammaticus pretending to be Konig Heniker. I am Konig Heniker. I am Konig Heniker pretending to be D’sal Huulta. I am D’sal Huulta. I chey D’sal Huulta lem pretending. El-chey D’sal samman Huulta lem tanay ek. El’chey D’sal samman Huulta lem tanay ek…

‘Who are you, fellow?’ one of the echvehnurth warriors at the city gate asked as he approached. The echvehnurth had been resting his falx against his silver breastplate, but now he raised it. Some of his companions did likewise. Others were stopping and searching some water merchants heading in out of the desert through the ancient arch.

‘I am D’sal Huulta,’ Grammaticus replied in Demotic Nurthene, making the obeisance of all-the-sunlight to the echvehnurth. ‘I am a merchant.’

Falx held ready across the left shoulder to strike, the echvehnurth stared at Grammaticus. ‘Show me your palms, your face, and your brands.’

Grammaticus made as if to do so.

+I’m safe and you’ve seen all you need to reassure you,+ he sent at the same moment.

The echvehnurth nodded, and waved him into the city, already sweeping the incomers for his next subject.

Grammaticus had shown him nothing.
--------------------
MON LO WAS waking up. As a city girded to the expectation of assault, it never truly slept, but its habits followed a circadian ebb and flow.

The outer walls were well defended by squadrons of echvehnurth, by iron mortars and bombasts, and by platoons of the regular nurthadtre ground troops. They loitered in unruly, spitting gatherings around the heavy steps of the city’s thick walls, or stood on the wall’s fighting platforms, watching the distant, unmoving enemy through spyglasses.

Deeper in the city, the rhythmic pulse of life was easier to discern. Markets woke up. Merchants announced their wares. Morning devotions were declaimed by strong-lunged priests. Water-carriers called their services as they wandered the plazas and the winding, cobbled streets and lanes.

Grammaticus retraced his steps, trying to recall the specific layout of the place as he had experienced it the first time. Passing merchants and elders nodded and made the all-the-sunlight gesture to him as they acknowledged his status.

He made the gesture back.

Grammaticus wanted to get into the northern suburb, an area called Kurnaul, so he could get a good look at the city’s north wall. Tuvi would appreciate his efforts. lie stood aside to let a grox-cart trundle past. Street washers cleaned the cobbles with bristle brooms and pails of water, using spades for the animal dung. They sang as they worked.

The faience tiled walls of the port city glimmered around him in the morning sun, showing reeds and reptiles in mosaic. The Nurthene had no street names, just pictorial emblems. He looked at a particular symbol, a great monitor lizard delineated in cherry red tiles, and knew, with a trained certainty, that he had never seen it before. He’d made a wrong turn. Mon Lo was so complex, so interwoven, it was hard to recall the specific plan. It was like Arachne’s web; mousy, big-bosomed Arachne.

He was the needle, he fancied, her needle, moving through the net of fate.

He halted and took a moment to consider. His internal compass was out. He checked with the rising sun and established where east was. He slowed his breathing, and allowed himself to perspire for a minute, just to stabilise his body. He had his bearings again. He’d just gone a street too far west, that was all. Kurnaul district was over to his left.

Except it wasn’t. He halted again, refusing to allow panic to dig in.

A water-carrier came up to him and offered a ladle of water.

‘No, thank you,’ Grammaticus said. ‘God love you anyway,’ the carrier replied, moving on.

Grammaticus shuddered. What the water-carrier had actually said literally translated as, The Primordial Annihilator immolate your living soul.

What’s wrong with me, Grammaticus thought? Last time I was here, I slipped easily from street to street. This time, I’m behaving like an amateur. My head is swimming. This is… this is stupid.

He crossed through two more busy streets, looking for familiar landmarks. It felt as if Kurnaul district was further away than ever. It was as if something was distracting him, baffling his abilities.

On impulse, he reached into the bag of mineral salts hooked to his broad over-belt, and closed his fingers around the memeseed hidden in the salt inside. The seed was the size of an earlobe, set into a small silver clasp. Gahet had given it to him. The seeds, fruited from some xenotype tree on a world somewhere in the Cabal’s range of influence, were psychically sensitive. If they grew warm, or desiccated in any way, it was a sign that psychic activity was close by.

Grammaticus looked at the memeseed. It was always a little warm and dry, because it reacted to his own talents. In his hand, the seed was positively hot, like a burning coal. It had shrivelled in its setting.

He was in trouble. The memeseed screamed a warning that something was nearby, perhaps something hunting him.

‘D’sal? D’sal Huulta?’

Grammaticus looked over his shoulder and saw a portly merchant waving to him. The man had been standing in conversation with a group of his brethren on the steps of a counting house, but he left them to hurry over. Grammaticus quickly put the memeseed away.

What is his name? His name? You’ve met him before. ‘D’sal, my good fellow,’ the portly merchant declared, making the all-the-sunlight gesture and adding a bow. ‘I have missed your face at the market these last few days. What news of the fire-brick deal we sketched out on our last meeting? Has your supplier delivered?’

H’dek. H’dek Rootun. That was his name.

‘H’dek, my good fellow, I am pained to respond that my supplier has become a goat’s maw,’ Grammaticus answered politely, ‘taking more than it gives. It turns out I can’t deliver on that fire-brick deal. I apologise.’

H’dek waved his pudgy hand. ‘Oh, don’t worry! I quite understand. In these times of hardship and oppression, with the alien siege at our door, things like this happen.’

He looked at Grammaticus more earnestly. ‘You have my fetish, my gene-print? Yes? Good, we can deal in future! I look forward to receiving your envoy.’

‘I am always your servant, H’dek,’ Grammaticus mumbled. He made the sign of all-the-sunlight, and added the gesture of the moons-entire as he ended the meeting.

He strode on down the length of the street feeling as uneasy and lost as before. Then he hurried into an open square, where the foot traffic was lighter, hoping the freedom of the space would give him room to clear his head, and perhaps even identify the source of the psychic activity the seed had detected. Clarity obstinately refused to come.

Grammaticus paused, and slowly raised his eyes.

He was standing in the Pa’khel Awan Nurth, the square of the pre-eminent temple in Mon Lo. High above him on the temple’s tympanum, a bas-relief frieze showed the four properties of the Primordial Annihilator: death, ecstasy, mortality and mutability, blending together into one, huge, ghastly symbol of unity.

What gross mistake had led his feet here, what clumsy mis-turn? This was the last place in the city he would have visited voluntarily.

The tympanum symbol seemed to pulse, to throb, pressing his eyeballs back into their sockets. Sunlight flared and buzzed. He gagged, and forced hot reflux back down into his gut. His previous visit hadn’t been anything like this. It was as if the city had become aware of him, and his role as an intruder, and had become a web, spun to trap him. Someone, something, was playing with him.

The vomit wasn’t going to stay down. He hurried off into an alley away from the temple precinct, and bent over in the shadows to release the acid liquid. It rushed out of him in a geyser. He barely had time to drag his head shawl off.

He sank to his knees, trembling and spitting.

Two figures, two men who were just dark shadows, were moving down the alley towards him. They weren’t rushing, but there was a purposeful, urgent stride to their gait. Grammaticus got to his feet and made off in the opposite direction, with equal purpose, not quite running.

Three more figures rounded the opposite end of the long, winding alley, and came towards him. What were they? Militia? Echvehnurth? Agents of the Pa’khel Awan, the temple’s zealous doctrinal clerics?

The alley had a couple of side turnings along its length. Grammaticus took the first, and broke into a run as soon as he was out of sight of the figures closing in on him. He reached a dead end, a closed courtyard behind some tall, fine town houses. He heard footsteps approaching behind him. He tried the doors, and found all of them bolted, except a heavy gate of painted wood, where green reptiles intercoiled and made helical patterns. Grammaticus pushed the gate open and ducked into the blessed cool and darkness of the room beyond it. He closed the gate, and drew the bolt across to hold it. He waited, listening to the muffled footsteps and voices outside.

A gigantic hand, gloved in steel, reached out of the darkness and picked him up by the neck. It turned him around and slammed him back against the wall, holding him by the throat.

Grammaticus was being throttled, his feet kicking off the ground. The steel hand pressed him back against the wall. Terracotta brickwork ground into his back.

‘I have a suspicion,’ a deep voice said, coming out of the darkness, ‘you’ve been looking for me, John Grammaticus.’

It knew his name.

‘Th-that’s possible,’ Grammaticus gasped, ‘though it m-might depend upon who you are.’

‘My name? You know my name, you treacherous bastard. My name is Alpharius.’
--------------------
**** Hydra
--------------------
House of the Hydra, Mon Lo Harbour, Nurth, continuous
--------------------
THE POUNDING BLOOD vessels in Grammaticus’s head felt as if they were about to burst. His windpipe had closed.

+Let me go,+ he sent, desperately.

The steel-gloved hand released its grip, and Grammaticus fell awkwardly onto the tiled floor. Hurt and dazed, he forced his mind to work fast. His eyes were becoming accustomed to the cold blue darkness of the chamber.

He could see the giant shadow of his captor, and the hot, red glow of a visor, but he could not read a mind. Something was screening it. Nevertheless, his urgent commands were getting through.

+Step back, and keep your hands away from your weapons.+

The giant shadow above him took a step backwards. ‘Stop him doing that,’ the shadow’s deep voice growled.

There was someone else in the room, in this bolt-hole that had not been safe at all. Grammaticus saw the second person as a hooded figure, though he could not actually see the man with his eyes. The figure was hooded in his mind.

Grammaticus tried to rise. A piercing liquid squeal, like a wet finger sliding on glass, stabbed into his neocortex. Pain fired through his autonomic nervous system and sizzled down his spine. He grunted and fell back against the wall.

‘He is fierce. Strong and well protected,’ the hooded figure said out loud.

‘Too much for you?’ asked the giant shadow.

‘No.’

‘Then keep him down.’

The squeal increased in power. Grammaticus convulsed.

‘We’re going to have a conversation, John,’ the giant shadow said, bending down and looming close. ‘I want some truth out of you, or so help me, I’ll simply crush your psyk-cursed skull. Yes? Are we clear?’

Grammaticus nodded. The agony was immense. He could feel blood running out of his nose and over his top lip.

‘Good. Shere is going to release you. That will be nice, won’t it? When Shere releases you, no mind tricks. Are we still clear?’

‘Yes,’ Grammaticus hissed, his throat bruised and sore.

‘Let him go, Shere,’ the giant commanded.

The squeal went away and took the worst of the pain with it. Grammaticus slumped forwards onto his hands, gasping.

‘Lights,’ the giant’s voice ordered.

There was a brief pulse of telekinetic effect, and several dozen wax candles arranged around the room spontaneously lit, a decent pyrokinetic display. The light from the candles was soft and yellow. It showed Grammaticus a shuttered greeting room, typical of Nurthene houses, with a faience tiled floor and mosaic walls that snagged the candlelight like water. It also showed him his antagonists: an armoured trans-human giant and a standard human in black whose face Grammaticus couldn’t see, even though the man wore no physical mask or hood.

‘Your name is John Grammaticus?’ the giant asked.

‘If you say so.’

‘I can get Shere to start again, if you prefer.’

Grammaticus shook his head. Spots of his blood dappled the tiles around him. “Yes, my name is John Grammaticus. You already knew that.’

‘Look at me,’ the giant commanded.

Grammaticus looked up. The giant was clad in power armour, the metal and ceramic wargear of an Imperial Astartes. The armour was a rich purple with silver edging. Green heraldry had been marked on the shoulder plates. The helm was the very latest, baleen-snout version. Dull red light shone inside the visor slit. To the left of the towering Astartes stood the mind-hooded figure, small by comparison.

‘No, me,’ said the Astartes. ‘Look at me. Ignore my psyker. Better.’

‘I—’ Grammaticus began.

‘Quiet,’ said the Astartes, raising a massive index finger. ‘You’re going to tell me what I want to know, not what you want to say.’

Grammaticus nodded.

‘You’ve been looking for me. That’s why you keep coming into this city. You knew I’d be here.’

Grammaticus nodded again.

‘How did you know that?’

‘Because we invited you here,’ Grammaticus replied.

‘You invited me here? Who’s “we”?’

‘The Cabal I work for.’

The Astartes turned to look at the hooded figure. ‘Once again,’ he said.

The squeal speared into Grammaticus’s head and made him shriek.

‘What is the Cabal?’ the Astartes asked.

Grammaticus sobbed. He could barely answer. ‘They… I don’t know… they are eternal and… and they…’

‘That’s not really very good,’ said the Astartes. ‘Maybe I should just shoot you.’

‘The Cabal is… the Cabal is the only hope!’ Grammaticus pleaded.

‘Go on.’

‘Please!’

‘Stop it now, Shere,’ the giant instructed.

The squeal died back.

‘Whose only hope?’ asked the Astartes.

‘Mine. Yours. Mankind’s,’ Grammaticus sighed.

‘You’re talking about the Imperium?’

Grammaticus shook his head. ‘Broader than that. The species.’

‘The Imperium is the species,’ the giant replied.

‘You don’t really believe that, do you?’ Grammaticus asked. ‘The worlds you’ve seen, the worlds you’ve been obliged to bring to compliance… worlds like this one, sapling shoots of human culture, cuttings from the root plant. The human race is far, far more than the militant tribe that is spilling out from Terra to accomplish the Emperor’s vision.’

The Astartes drew his boltgun. Grammaticus did not actually see it happen. One moment, the hefty weapon was holstered at the giant’s hip, the next it was in his steel fist, aimed at Grammaticus’s head.

‘Are you insane?’ the giant asked. ‘Are you blind? Look at me. I am an Astartes warrior, oathed to this moment and sworn to serve the Emperor. Why would you say something that sounds so perilously close to treason?’

‘I apologise if that’s how it sounded. I meant no disrespect.’

The boltgun remained aimed at him. ‘You said this Cabal of yours invited us here. Explain that.’

Grammaticus swallowed. ‘Of all the Astartes Legions, the Cabal believes the Alpha Legion to be most receptive to its message.’

‘Why?’

‘In all truth, sir, I do not know. I am simply a go-between. The Cabal wanted the Alpha Legion to become involved in the compliance war here on Nurth, so that it could see the evidence for itself.’

‘See what, John?’

Grammaticus straightened slightly and looked boldly at the muzzle of the gun aimed at his face. ‘What was at stake. The real enemy. Not the Nurthene, but the Primordial Annihilator that holds sway over them.’

The Astartes slowly lowered his weapon. ‘You’re talking about their warp-magick?’

‘It’s not—’ Grammaticus began. ‘May I stand, sir? This floor is cold.’

The snouted helm nodded. Grammaticus rose to his feet. The Astartes still towered over him.

‘It’s not magick. It’s not some fanciful trickery. It’s the visible manifestation of a deep power – a universal, pervasive abomination.’

‘Chaos,’ the Astartes replied. ‘If that is what your masters wanted us to see, they have wasted your errand. We already know of Chaos, and have numbered it in the litany of xenos hazards.’

Grammaticus shook his head sadly. ‘The simplest name for it is Chaos. You’ve numbered it in the litany of xenos hazards, have you? Then you know it only as a child knows the world. It has always been and will always be, and compared to it, nothing – not mankind, not the Imperium, not the Emperor’s mighty design – is of any consequence. Unchecked, it will poison and stagnate the galaxy. Fuelled and driven, it will destroy everything. The Cabal wanted you to see it properly, to see it with your own eyes, so that you would take its message seriously.’

He paused. ‘And it needed you to see it quickly.’

‘Why?’ asked the giant.

‘Because a great war is coming.’

‘A war against what?’

‘Against yourselves,’ said Grammaticus.

The giant Astartes stared at Grammaticus for a moment. Grammaticus heard the dull click of his helmet vox operating. A private conversation was taking place. Grammaticus waited. The candle flames trembled. A tiny green house lizard scuttled across the tiled floor and up a wall.

The giant turned back to look at Grammaticus.

‘What is the message your Cabal wants us to take so seriously?’ he asked.

‘I don’t know. I was simply sent here to propose a dialogue.’

The Astartes looked over at the mind-hooded man. ‘I am called for,’ he said. ‘Take him to the parlour and stay with him. Do not allow him to play any tricks.’

The psyker nodded.

The Astartes went over to the wooden gate, unbolted it, and stepped out into the sunlight. Just before the gate closed, Grammaticus saw that the intercoiled green reptiles painted on the wood were dragons, each one with three serpentine heads. Hydras.

‘This way,’ said the psyker to Grammaticus.
--------------------
HE FOLLOWED THE psyker through the rooms of the house, rambling chambers and hallways that followed no more logical a scheme than the streets of Mon Lo. All the rooms were dark and shuttered, and dust sheets covered the few pieces of furniture. This was a place of convenience, Grammaticus decided, a safe house. He had been meant to open that painted gate all along.

The psyker led the way with a single fluttering candle.

‘You contrived to bring me here?’ Grammaticus asked. ‘You baffled my mind and got me lost, so I could be directed to this house?’

‘Not on my own,’ the hooded man replied. ‘You are a powerful being. We’ve been aware of you, these last few weeks, operating here, shadowing us, watching us. We thought it was time to ask why.’

‘You’re not Astartes.’

The man turned and looked back at him but, despite the candlelight, Grammaticus could still not resolve his face. ‘The Alpha Legion uses any and all instruments to get its work done. I am honoured to serve them.’

The psyker took Grammaticus into a dark sitting room where several low couches and upholstered stools had been brought into use, their dust sheets folded and put away. A golden ewer of Nurthene wine, some small silver-dished mazers, and an earthenware bowl of preserved fruit stood on an inlaid table.

The psyker nodded slightly and the many candles arranged around the room’s surfaces spontaneously lit. The sudden light made a couple of little house lizards skitter into the shadows.

‘I do hate lumen and glow-globe light,’ the psyker said. ‘It kills the darkness. Candles illuminate it.’

‘And darkness is just another instrument of the Alpha Legion?’ asked Grammaticus.

Though he could not see the man’s face, Grammaticus understood that the psyker was smiling. ‘You really have been watching us carefully, haven’t you?’ the psyker said.

‘It’s my job,’ Grammaticus replied.

‘Help yourself to wine, to a bite of food,’ the psyker offered, sitting down on a couch and putting the candle he was carrying down on a low table.

Grammaticus poured some wine into one of the silver drinking bowls. He needed something to wash his mouth with, but would have preferred water. As he sipped from the mazer, he focused his limbic system to negate the effects of the alcohol.

He took a seat opposite the psyker. ‘You’re called Shere, right?’

‘Yes.’

‘You’re a gifted pyrokine. It’s a technique that never manifested in me.’

Shere shrugged. ‘You get what you get, John. I’m far more impressed by your particular talent. Logokinetic skill. That’s rare.’

‘You can read that in me?’

‘Of course,’ said Shere, ‘but I can’t understand it. Is it any language, or just specific groups?’

‘I’ve never encountered a tongue I couldn’t master.’

‘Including xenos?’

Grammaticus smiled. ‘They’re not so hard. It depends on the organ they use for speech. I can understand some, but am unable to respond in kind because I lack the necessary biology to manufacture reciprocal sounds. And some are just abstruse. The eldar have a particular verb form that always trips me up.’

‘And you can tell where a person is from, just by their speech?’ Shere asked, deftly switching from Low Gothic to Sinhala.

‘Nice try,’ said Grammaticus in fluent Sinhala, ‘but your palatal voicing gives you away. You are speaking Sinhala well, but I read Farsi vowels underneath, and something else. You are Uzbek or Azerbaijani.’

‘Uzbek.’

‘And the something else, the long diphthongs, that’s a trace of Mars, isn’t it?’

‘I spent eight years growing up in the habitats of Ipluvian Maximal. You’re very good. I presume, as a result, you are very good at reading the truth?’

Grammaticus nodded. ‘I am. It is particularly hard to lie to me, a fact which I hope you’ll mention to your masters when you report this conversation back to them. I excel at recognising truth, so I am not unwittingly conveying someone else’s lies to the ears of the Alpha Legion.’

Shere chuckled. ‘You may recognise the truth, John. We have no guarantee you are transmitting it.’

‘That’s a decent point, I suppose,’ Grammaticus replied, taking another sip from the mazer cradled in his fingers.

‘How did you invite them?’ Shere asked. ‘They’ll want to know.’

‘It’s taken about a decade,’ said Grammaticus. ‘Agents like me have been planting seeds and suggestions for a while now. Using Imperial codes and cyphers, we’ve logged reports and bulletins into the Crusade’s data-architecture, certain things that we thought would tantalise the Alpha Legion. We diverted a few orders, reversed a few command communiqués. Little by little, we made sure that when the time came for the 670th Expedition to request assistance in prosecuting the Nurthene campaign, it would be the Alpha Legion that responded to Lord Commander Namatjira’s plea.’

‘Great Terra,’ Shere breathed, ‘that’s astonishing. The level of influence, of access… the strategy, the patience. Incredible! Such subtle manipulation!’

‘That’s the Cabal’s way, Shere,’ Grammaticus replied, ‘strategy, subtle influence, the long view. They’re very good at it. They’ve always been very good at it.’

‘They could have simply asked.’

Grammaticus laughed. It hurt his bruised throat. ‘That’s not their way! Besides, would the Alpha Legion have said yes?’

‘Not in a thousand years,’ Shere agreed. ‘Look, I’d be careful how I explained that to them, if I were you. The Alpha Legion prides itself on knowing everything. They prize knowledge above all things, and hate the idea of anyone knowing more than they do. That’s how they win their battles. In fact, the only thing they hate more is the idea that they’re being manipulated.’

‘So noted, thank you. I had already foreseen that as a stumbling block.’ Grammaticus put the empty mazer down on the tray by the ewer. ‘You’re no slouches when it comes to manipulation, though. You got me, today. From the moment I entered Mon Lo, you were misleading me, clouding my mind, pulling me to where you wanted me to be.’

‘Well, not quite,’ said Shere.

‘Don’t be so modest, you admitted it to me just now.’

Shere looked up at Grammaticus in the candlelight. His lack of a coherent face was hard to look at, but Grammaticus could read alarm. ‘John, I’m not being modest. Yes, we led you here, but only once we had located and identified you. That was just before you entered the temple square, on Red Monitor Street. Before that, we weren’t aware of you at all.’

‘No,’ said Grammaticus, ‘it was before that. I—’

Shere got up. ‘John, are you telling me that you were being influenced from the moment you entered the city today?’

‘I—’

‘This is important, John! Was something on to you right from your point of entry?’

Grammaticus swallowed. His guts suddenly felt as if they were full of ice. ‘Yes,’ he said.

‘Damn,’ Shere murmured. ‘That wasn’t us. That wasn’t us. They made you.’

‘Shere, I—’

‘Be quiet, please. We may have just been seriously compromised.’

Shere walked over to the parlour door and bent his head, talking urgently into a vox microbead. Grammaticus waited, his head spinning slightly. An awful creep of realisation was coming over him. The Cabal and the Alpha Legion had not been the only forces playing games that morning.

Shere looked over at Grammaticus, his conversation over. ‘We’re moving,’ he said. ‘We’re getting out of here.’

‘What’s going on?’

‘It’s as bad as I feared. The city’s gone quiet. The Nurthene identified you and used you as a lure to draw us out.’

‘I’m so sorry,’ Grammaticus said.

‘Your apology hardly counts for anything. Come on.’

Footsteps were thumping up the hallway outside. The door opened and three men came in. Two were standard humans, dressed in mail sleeves and head shawls, carrying crude pattern lascarbines. The third, attired identically to the other two, was a gene-big beast lugging a bolter.

‘We’re quitting the house,’ the gene-giant told Shere. ‘Is this the wretch who blew our operation?’

Without waiting for confirmation, the gene-giant turned and advanced towards Grammaticus.

‘Leave him, Herzog! Please, sir!’ Shere called out. ‘He’s valuable. Pech told me to watch him and keep him safe.’

‘Shame the rodent couldn’t do the same for us,’ the gene-giant growled. ‘All right, let’s head out. Double time.’

They flanked Grammaticus and hurried him down the hall. Scared as he was, Grammaticus sorted the data that had just come his way. The gene-giant was called Herzog, apparently. Grammaticus could smell the whiff of Astartes about him. The other two, the mail-sleeved standard humans, suggested to Grammaticus that the Alpha Legion used all sorts of non-Astartes operatives to accomplish their missions, not just specialists like the psyker Shere. What had Shere said? The Alpha Legion uses any and all instruments to get its work done. Grammaticus risked a quick surface read of the men’s minds, and saw they were soldiers of the Imperial Army, though there was something definitely non-standard about the biological samples he was getting. He dared not risk a deeper probe.

And that other thing Shere had said: Pech told me to watch him and keep him safe. He could only have meant the armoured giant, but the giant had identified himself as Alpharius. Was that another lie? How did the names connect?

They reached the ground floor of the house. Herzog raised a hand to activate his link.

The shutters opened. They banged aside, one by one, opening each window in turn, spilling hot, hard daylight into the closed house. Grammaticus flinched at each opening, feeling the residual pulse of the telekinetic power responsible. A trio of minute green house lizards danced in over an open sill.

‘Damn,’ Herzog murmured.

More lizards skittered in, running like water over the sills, some falling onto the floor with little plips. Inside five seconds, they were pouring in like a flood, thousands of them, rushing over the window ledges and under the doors, flowing as if dumped out of handcarts.

‘Back up! Upstairs!’ Herzog ordered.

They thumped back up the staircase. The tide of lizards behind them quickly covered the tiled floor of the hall and began to pour, like green water disobeying gravity, up the stairs.

Grammaticus could feel a malevolence in the air, a pervading touch of cloying heat and rage, the trademark of an angry, potent psyker.

‘We’re in trouble,’ he whispered. The others ignored him, except for Shere, who glanced in his direction. For a brief second, Grammaticus saw Shere’s face, the face of a startled young man with fine features. Shere was so unnerved he was letting his psyk-hood slip.

Rivers of pattering lizards were pouring in through the upper windows too. The shutters on the first floor had been yanked open. Tiny, sinuous green shapes rippled across sheet-wrapped furniture and spilled along the tiled flooring.

‘Oh hell’s teeth,’ one of the mail-sleeved operatives gasped.

‘Second floor!’ Herzog ordered. ‘Make for the bridge!’

Herzog’s mind was unguarded by distraction. Grammaticus skimmed its surface and saw that the bridge was a brick walkway linking the house to its neighbour. He started to run. They all started to run. Behind them, the swarming lizards filled the hallways, making no sound except for the plick-plack of their billion sticky feet.

The running men, led by the Astartes, reached the second floor. The torrent of lizards was running up the walls, coating the ceiling with a carpet of scurrying bodies.

‘Arkus! Delay them!’ Herzog yelled out.

‘Why me?’ one of the mail-sleeved operatives wailed.

‘Just do it. Broad burn!’

The operative turned, adjusting his lascarbine to the widest emission setting. He started to fire, blasting unfocused washes of energy back down the stairs, singeing and crisping the wriggling mat of advancing lizards. Tiny, smouldering bodies dropped off the ceiling and walls. The hand-painted wallpaper crisped.

Arkus kept firing, cooking thousands of squirming shapes, adjusting his aim rapidly to check each front of the swarming plague in turn.

It wasn’t enough. It was never going to be enough. They reached him, and he screamed and jiggled as they rushed up his legs and his body, covering him. He started to flail wildly, enveloped by tiny, biting, snapping green shapes. He lost his footing and fell, crashing down the staircase into the main body of the green torrent. In seconds, his form was lost from view, submerged in the writhing flow.

Ignoring the grim demise of his operative, Herzog ran down the hallway, his moving weight creaking the old floorboards. He reached a door, and halted, preparing to kick it in.

Before he could, the door splintered in towards him, throwing him backwards. A snout, two metres long, shoved its way through the shattered opening. Shere yelped.

The crocodilian was a massive thing, the sort of creature that simply had no business existing on the second floor of a domestic house. It rammed its way forwards, its colossal skull swinging left and right as it came on. Its huge, scuted body and immense tail trailed back across the bridge into the neighbouring building. The house shook under its gigantic mass as it moved.

Herzog tried to drag himself back out of its path. Shere retreated, slipping over on the scurrying house lizards that were darting underfoot. Grammaticus grabbed him and hauled him to his feet, smacking the wriggling, biting things off Shere’s robe with his bare hands.

The remaining operative fired twice at the advancing monster. The crocodilian lunged forwards, extending its white-scaled neck, and took the operative like a grazer at a waterhole, snatching him up in a huge V of jaws. The man tore open, screeching, as the jaws shook him apart like a straw doll.

Herzog, on his back, fired his boltgun, and blew out one of the crocodilian’s eyes. It thrashed in pain, slamming its vast body to and fro into the walls of the bridge and the corridor, shattering plaster and shaking the building. The mangled corpse of the operative tumbled out of its jaws and it snapped forwards, seizing Herzog by the leg. Mail rings cracked and pinged away as the gigantic teeth bit down.

Herzog roared.

Grammaticus had never heard an Astartes cry in pain before. He decided he never wanted to hear the sound again. He pushed Shere aside against the moving wall of lizards and adjusted his ring. It was an Old Kind digital weapon, a gift from Gahet.

He triggered it. An incandescent blue beam lanced out from it and exploded the crocodilian’s braincase in a wet blast of meat, bone and tissue.

‘Come on!’ Grammaticus yelled.

Herzog pulled his leg free of the ruptured jaws, and got to his feet. Limping, he led Grammaticus and Shere across the bridge. They had to clamber over the apparently endless bulk of the dead crocodilian. It was still twitching.

They reached the stairs of the neighbouring house and headed down. Herzog’s leg was badly lacerated from the bite, and he was faltering. Behind them, they could hear the advancing patter of the lizard tide. The first few green shapes were appearing above them, scurrying out across the ceiling, some falling like drops of water down the stairwell around them.

‘Where did you get that?’ Herzog yelled at Grammaticus. ‘What?’

‘That weapon!’

‘Does it matter?’

‘You could have used it on us earlier,’ Shere said, scrambling down the stairs beside Grammaticus.

‘The fact that I didn’t might persuade you that I’m serious,’ Grammaticus replied.

They snatched open the main street door of the house, and came out into bright sunlight, and into the middle of a gun battle. Two Astartes warriors in purple power armour – one of them, Grammaticus was certain, the giant who had questioned him earlier – were exchanging shots along the dusty, sunlit street with gangs of nurthadtre ground troops. Crowds of braying Nurthene civilians were urging the nurthadtre on, hurling cobbles and other missiles. Half a dozen mail-sleeved operatives, anonymous in their desert shawls, were supporting the outnumbered Astartes. Las-rounds and ballistic loads streaked up and down the narrow thoroughfare.

‘Pech?’ Herzog called out.

The armoured giant glanced around. So, not Alpharius then, Grammaticus thought, unless ‘Pech’ was some nickname or surname unknown to the Cabal.

‘Get out, Thias!’ the giant yelled. ‘We’ll hold them here and rendezvous as soon as we can!’

‘For the Emperor, Pech!’ Herzog shouted, pausing to add his bolter fire to the fight for a moment.

‘Let’s go!’ he declared, turning to face Shere and Grammaticus.

They began to run again, covering the sun-heated cobbles, the sounds of the firefight behind them echoing along the overhanging walls.

‘Where to?’ Grammaticus found the courage to ask.

‘To wherever is safe,’ Herzog replied. He was still limping badly.

‘I don’t think there’s anywhere safe for us in this town,’ Shere grunted.

‘No, neither do I,’ agreed Herzog, ‘thanks to him.’ He glared at Grammaticus.

‘This was not my doing,’ Grammaticus insisted as he ran. He checked his stride suddenly, flinching as he sensed the stomach-churning ripple of psyker activity again.

Shere had felt it too. ‘What—’ he began.

The street ahead of them split as if torn open by a fierce earthquake. The road surface burst upwards, and cobblestones flew like hail.

A vast monitor hauled itself up out of the ground in front of them, pulling its bulk free of the cloven street and the earth beneath. Cobblestones, hardcore and soil spilled out around it as it emerged. Its skull alone was the size of a lifepod. Its tongue, long, dry and forked, flickered in and out of its extravagantly massive maw. The tongue was as pink as Nurthene silk. The monitor was covered in cherry-red scales. They could smell the carrion stink of its jaws, feel the tremor of its advancing steps.

‘Here be dragons,’ Grammaticus whispered.

‘What?’ Shere yelled.

Here be dragons. It was no longer a quaintly phrased notation of warning, no longer the shorthand motto of man’s ignorance of the darker places of his universe. Dragons were real, not ambiguous scrawls on fading maps.

Grammaticus could see into it, past the giganticised body it wore, past the scale and flesh and muscle of the varanidae-genus form it had chosen, or been instructed, to take. He could see the absolute fury of its daemon heart.

Herzog began to fire, slamming bolt after bolt into the red monster’s head. Blood splattered from the snout, and two or three teeth were blown out of their sockets. The dragon lunged.

Shere screamed and lashed out with his pyrokinetic talent, and flames swirled along the reptile’s back and flanks in wild, flaring streams. The immense beast began to thrash as its scales scorched. Flames travelled down its length, engulfing it in a molten inferno too bright to look at. Its whipping, burning body and tail convulsed furiously and smashed into the surrounding buildings, bringing down their facades in thunderous torrents of brick and dry mortar.

Dust rose in solid, gagging walls. Grammaticus lost sight of Herzog and Shere. He began to run. Behind him, the death throes of the burning dragon sounded as though they were demolishing the entire city.

Grammaticus kept running. He didn’t look back.
--------------------
