* Dan Abnett Extracts                                                           :examples:scifi:abnett:

*** Gaunt's Ghosts

**** Gereon

On the six hundred and fourth Day of Pain, the two hundred and twenty-first day of the Imperial Year 774, Gerome Landerson left his place of work at the sounding of the carnyx horn. The horn signalled the change from day-labour to night-labour.

He was weary, hungry and drenched with sweat. His arms and spine ached from swinging a hammer, and his hands were so numbed from the constant impacts that he could no longer feel his fingers. But he did not trudge towards the cookshops or the washhouses with the other day-labourers from the Iconoclave, nor did he begin the long walk back to the consented habitats along the river wall of Ineuron Town.

Instead, he walked west, down through the fractured arches of the town’s old commercia. Markets had once thrived there — the daily cheaps of foodstuffs, grain, livestock, instruments — and the licensed mercantile houses had once raised their lavish silk tents and displayed the gewgaws and trinkets of their trade.

Landerson had always loved the commercia for its flavour of the faraway. He’d once bought a small metal plaque with an engraving of an Ecclesiarchy templum on Enothis just because it had travelled so far. Now the faraway seemed even more remote and unreachable, even though it was his business tonight.

The commercia was a ruin these days. What remained of the vast roof vault was smoke-blackened and rotten, and the rows of metal stalls where the traders had congregated for the daily cheaps were twisted and corroding. On the rubble-strewn ground, a few furtive dealers lurked by oilcan fires, bartering luxuries like marrowbones and bent cutlery for ration coins and consent wafers. Every time there was a hint of an excubitor patrol passing nearby, the scavengers melted away into the shadows.

Landerson walked on, trying to rub some life back into his soot-caked hands. He left the commercia via the wide flight of white marble steps, steps still riddled with the black boreholes of lasfire, and began down the Avenue of Shins. That wasn’t its real name of course, but the yoke of oppression bred black humour in the conquered. This had been the Avenue of the Aquila. Long and broad, it was lined on either side by rows of ouslite plinths. The statue of an Imperial hero had once stood on each. The invaders had demolished them all. Now only splintered stone shins rose from the proud feet planted on those plinths. Hence the name.

Talix trees, tall and slender, grew along the outsides of the avenue. At least two had been decapitated and remade into gibbets for the wirewolves. There was no point trying to avoid them. Landerson walked on, trying not to look up at the skeletal mannequins hanging limply from the axl-trees on their metal strings. They creaked, swinging slightly in the breeze.

Daylight was fading. The sky, already hazy with the perpetual canopy of dust, had taken on a sheen as if a fog were closing in. To the west, the furnaces of the meat foundries glazed the low clouds with a glow the colour of pomegranate flesh. Landerson knew he had to hurry now. His imago consented him only for activity during daylight.

He was crossing the square at Tallenhall when he smelled the glyf. It stank like a discharged battery pack, an ionized scent, the tang of blood and metal. He huddled down in the overgrown hedge by the tangled iron railings and watched. The glyf appeared in the northern corner of the square, drifting like a balloon eight metres up, slow and lazy. As soon as he had located it, he tried to look away, but it was impossible. The floating sigils, bright as neon, locked his attention. He felt his stomach churn at the sight of those abominable, intertwined symbols, his gorge rising. At the back of his mind, he heard a chattering, like the sound of swarming insects rubbing their wing cases. The imago in the flesh of his left arm twitched.

The glyf wavered, then began to glide away, out of sight behind the shell of the town library. As soon as it was gone, Landerson sank onto his hands and dry-heaved violently into the burned grass. When he closed his eyes, he could see the obscene symbols shining in meaningless repeats on the back of his eyelids.

Unsteady, he rose to his feet, succumbed to a spell of giddiness, and slumped against the bent railings for support.

“Voi shet!” a hard voice barked.

He shook his head, trying to straighten up. Boots crunched across the brick dust towards him.

“Voi shet! Ecchr Anark setriketan!”

Landerson raised his hands in supplication. “Consented! Consented, magir!”

The three excubitors surrounded him. Each was two metres tall and clad in heavy buckled boots and long coats of grey scale armour. They aimed their ornate las-locks at him.

“I am consented, magir!” he pleaded, trying to show them his imago.

One of them cuffed him down onto his knees.

“Shet atraga ydereta haspa? Voi leng haspa?”

“I… I don’t speak your—”

There was a click, and a crackle of vox noise. One of them spoke again, but its coarse words were obscured by a rasping mechanical echo.

“What is your purpose here?”

“I am consented to pass in daylight, magir,” he answered.

“Look at me!” Again, the barbarous tongue was overlaid with augmetically-generated speech.

Landerson looked up. The excubitor leaning over him was as hellish as any of its kind. Only the upper half of its head was visible — pale, shrivelled and hairless. A dripping cluster of metal tubes and pipes sprouted from the back of its wrinkled skull and connected to the steaming, panting support box strapped across its back. Three huge, sutured scars split its face, one down through each eye socket — in which augmetic ocular mounts were now sewn — and the third straight down over the bridge of a nose from which all flesh had been debrided. A large brass collar rose in front of the face, mercifully obscuring the excubitor’s mouth and most of the nasal area. The front of this collar mounted a wire-grilled speaking box, which the excubitor had switched to “translate”.

“I… I look upon you, and I am graced by your beauty,” Landerson gasped as clearly as he could.

“Name?” the thing snapped.

“Landerson, Gerome, consented of day, b-by the will of the Anarch.”

“Place of industry?”

“The Iconoclave, magir.”

“You work in the Breaking House?”

“Yes, magir.”

“Display to me your consent!”

Landerson lifted his left arm and drew back the sleeve of his torn workcoat to reveal the imago in its blister of clear pus.

“Eletraa kyh drowk!” the excubitor said to one of its companions.

“Chee ataah drowk,” came the reply. The sentinel drew a long metal tool from its belt, the size and shape of a candle-snuffer, and placed the cup over Landerson’s imago. Landerson gasped as he felt the thing in his flesh writhe. Small runes lit up on the shank of the tool. The cup withdrew.

The third excubitor grabbed Landerson by the head and turned it roughly so as to better examine the stigma on his left cheek.

“Fehet gahesh,” it said, letting him go.

“Go home, interceded one,” the first excubitor told Landerson, the machine words back-echoed by the alien speech. “Go home and do not let us catch you out here again.”

“Y-yes, magir. At once.”

“Or we will have sport with you. Us, or the wirewolves.”

“I understand, magir. Thank you.”

The excubitor stepped back. It covered the grille of its speaking box with one hand. Its brethren did the same.

“We serve the word of the Anarch, whose word drowns out all others.”

Landerson covered his own mouth quickly. “Whose word drowns out all others,” he repeated quickly.

The excubitors looked at him for a moment longer, then shouldered their massive las-locks and walked away across the overgrown square.

It was a long while before Landerson had recovered enough to get back on his feet.
--------------------
It was almost dark when he reached the abandoned mill at the edge of the town. The dimming sky was lit by fires: the burning masses of the distant hives and the closer glows of the ahenum furnaces that powered the town’s new industries. On the wide roadway below the mill, torches were bobbing and drums were beating. Another procession of proselytes was being led to the shrines by the ordinals.

Landerson tapped on the wooden door.

“How is Gereon?” asked a voice from within.

“Gereon lives,” Landerson replied.

“Despite their efforts,” the voice responded. The door swung open, revealing only darkness. Landerson peered in.

Then he felt the nudge of an autopistol muzzle against the back of his head.

“You’re late.”

“I ran into trouble.”

“It had better not have followed you.”

“No, sir.”

“Step in, nice and easy.”

Landerson edged into the darkness. A light came on, in his face.

“Check him!” a voice said, as the door swung closed behind him.

Hands grabbed him and hustled him forward. The paddle of an auspex buzzed as it was passed up and down his body.

“Clean!” someone said.

The hands withdrew. Landerson squinted into the light, resolving his surroundings. A dank cellar of the old mill, figures all around, flashlights aimed his way.

Colonel Ballerat stepped into the light, holstering his pistol.

“Landerson,” he said.

“Good to see you, sir,” Landerson, replied.

Ballerat moved forward and embraced Landerson. He did so with only one hand. Ballerat’s left arm and left leg had been ripped away in the foundries. He had a crude prosthetic that allowed him to walk, but his left arm was just a nub.

“I’m relieved you got the message.” Ballerat smiled. “I was beginning to worry you hadn’t.”

“I got it all right,” Landerson said. “Dropped into my food pail. It was difficult getting away. Is it tonight, sir?”

Ballerat nodded. “Yes, it is. They’re definitely down. We need to make contact so we can move to the next stage.”

Landerson nodded. “How many, sir?”

“How many what?” Ballerat asked.

“I mean… what sort of numbers, sir? Disposition? What sort of size is the liberation force?”

Ballerat paused. “We… we don’t know yet, major. Working on that. The key thing right now is to make contact with their recon advance so we can lead them in.”

“Understood, sir.”

“I’m sending you, Lefivre and Purchason.”

“I know them both, sir. Good men. We served in the PDF together.”

Ballerat smiled. “That’s what I thought. So you know the area well. Rendezvous is an agri-complex at the Shedowtonland Crossroads. Contact code is ‘Tanith Magna’.”

Landerson repeated the words. “What does that mean, sir?”

Ballerat shrugged. “Damned if I know. A Guard code. Ah, here they come.”

Lefivre and Purchason approached. Both were dressed in the ragged, scrabbled-together remnants of PDF combat gear. Lefivre was a short, blond man with a scrappy beard. Purchason was taller, leaner and dark-haired. Both shook hands with Landerson. Both carried silenced autorifles.

Another member of the resistance hurried over with a set of fatigues, equipment and weapons for Landerson. Crouching, Landerson began to sort through the stuff.

“That can wait,” Ballerat said. “We have to strip you out first, son.”

Landerson nodded and rose to his feet. Ballerat led him into an adjoining chamber that stank of animals, chyme and dung. The air was warm and heavy. Landerson could hear grox snorting and farting in the gloom.

“Ready?” Ballerat asked him.

“I’d just like to get it over with, sir,” Landerson said. He pulled up the sleeve of his left arm.

Several other men appeared and took him by the shoulders, holding him tight. One offered him a bottle of amasec. Landerson took a deep swig. “Good boy,” the man said. “Helps dull the pain. Now bite on this. You’ll need it.”

Landerson bit down hard on the leather belt that was pushed into his mouth.

The chirurgeon was a woman, an old lady from the habs. She smiled at Landerson, who was now pinned by four men, and poured more amasec over the imago.

Landerson felt it squirm.

“They don’t like that at all,” the chirurgeon muttered. “It numbs them. Makes them sleepy, dull. Makes them easier to withdraw. Steel yourself, boy.”

She produced a scalpel, and quickly slit open the huge blister on his forearm. It popped, and viscous fluid poured out. Landerson bit down. It hurt already. The coiled black thing in the meat of his arm, now exposed, fidgeted and tightened in the sore, red cavity. He tried not to look, but he could not help it.

The chirurgeon reached in with long-handled tweezers.

She began to pull. Most of the glistening black grub came away in the first tug, but the long, barbed tail, dark and thorned like razor-wire, resisted. She pulled more firmly and Landerson bit down harder, feeling his flesh tear. The grub began to squirm and wriggle between the tips of the tweezers. Agony pulsed down Landerson’s arm. It felt like a barbed fishing line was being drawn out down an artery.

The chirurgeon doused the wound with more alcohol, and yanked hard. Landerson bit through the belt. The whipping grub tore free, jiggling at the end of her surgical tool.

“Now!” she cried.

One of Ballerat’s men had already slit open the haunch of one of the grox in the stalls. The old woman stabbed the twitching grub into the wound, and then, as she released it, clamped the wound shut with a wadding of anaesthotape and bandage.

She held it tight, fighting as if something was trying to get out from under the wadding.

“We’re all right,” she said finally. “I think it’s taken.”

Everyone fell silent for a few long minutes, listening intently for the sound of an excubitor alarm or worse. Landerson realised he was shaking hard. The old woman beckoned to one of the men to hold the wadding tight to the animal’s flank, and came over to Landerson to bind his wound.

She cleaned it carefully, sealed it, bandaged it, and then gave him a shot of painkillers and counterseptic agents.

Landerson began to feel a little better, though he was slightly distressed to note an odd sensation of absence. All those months, longing to be rid of the foul, twitching thing under his skin, and now his body seemed to miss the imago.

“Are you feeling all right?” Ballerat asked him, emerging from the shadows.

“Yes, sir,” Landerson lied.

“I’d like to give you more time to recover, but we don’t have it. Set to move?”

Landerson nodded.

Ballerat showed him a crumpled, hand-drawn map. “Take a moment to study this. Memorise it, because I can’t let you take it. This is the route I suggest you follow. These are the times and locations of the patrols we know about.”

Landerson studied the information hard, looking away from time to time and then back at the map to test his recall. Then Ballerat handed him an envelope, and Landerson glanced inside.

“What’s this for?” he asked.

“You never know,” the colonel replied. Landerson put the envelope inside his jacket.

“Right,” said Ballerat, nodding Lefivre and Purchason over to join them. “Rendezvous is set for twenty-three fifteen. Find out what they need from us and do your best to provide it. Contact with us is via the usual methods. We’ll be staging a diversion event about forty minutes prior to rendezvous that should draw surplus attention away from your zone. Any questions?”

The three men shook their heads.

Ballerat couldn’t make the full sign of the aquila, but he placed his right hand over his heart as if he were. “Good fortune, and for the sake of Gereon, may the Emperor protect you.”
--------------------
The night was cool and damp. Landerson had almost forgotten how it felt to be outside in the dark. They made good progress out of Ineuron Town, smuggling themselves through the western palisades, and then headed out across the old ornamental park called the Ambulatory. The lights of the town flickered behind them, and once in a while they heard distant horns and kettle drums.

The bloodiest phase of the battle for Ineuron Town had been fought around the precincts of the Ambulatory and the ground, now fully overgrown, was littered with machine debris and pathetic scatters of human bone. The three men made no sound. Ballerat hadn’t picked them for this mission simply because of their local knowledge. All three had been in the ranger-recon brigade of the PDF.

Halfway across the Ambulatory they had to take cover behind a thicket of juvenile talix trees as a patrol went by: two half-tracks, blazing with hunting spotlights, the lead one resembling an ice sled because of the long string of fetch-hounds straining ahead of it on chains. The animals growled and rasped, pulling at their harnesses. They were trained to scent imagos and also human pheromones. The last thing Landerson and his companions had done before leaving the mill was stand under a crude gravity shower that soaked them with scent-repellers.

The patrol moved away. Landerson signalled the other two men forward. He used the sign language fluently, like his last ranger-recon mission had been the day before. But he noticed that his left arm felt curiously light. Had the old woman got it all out? Or was there some piece of the grub still inside him, yearning for—

Landerson dismissed the thought. If even a scrap of the imago had been left behind, corposant would be crackling over every gibbet in the town and the wire-wolves would be gathering.

They left the Ambulatory, and picked their way through the silent ruins of the tiered hab blocks that ran down the slopes of Mexley Hill. This suburb was an agriculture district, marking the point at which the heavy industry of the inner conurbations gave way to the farmland disciplines of the town’s rural skirts. Behind the habs, strips of crop fields were laid out across the hillside and over into the next valley. Landerson could smell silage, plant rot, and the distinctive perfume of canter-wheat. But the crop, unharvested, had gone over, and the smell was unpleasantly strong, with a sickly tinge of fermentation.

Purchason stopped dead and signed a warning. The trio melted into cover behind the yard wall at the rear of one of the habs.

Thirty metres away, a glyf hung, almost stationary, above the lane.

In the dark, the glyf was even more terrifying than the one that had passed Landerson by in daylight. Its coiled, burning symbols seemed to writhe like snakes, forming one unholy rune then another, bright against the night sky as if they were written in liquid flame. Landerson could hear it crackling like a log fire. He could hear the thick, nauseating insect noise. This time, he managed to look away.

He was suddenly aware of Lefivre next to him. The man was shaking badly. Glancing round, Landerson saw that his companion had his eyes locked on the infernal glyf. Tears were trickling from eyes that refused to blink. Landerson reached out quickly and took Lefivre’s weapon just moments before it slithered out of the man’s nerveless hands. In the half light, he could see Lefivre’s jaw working and his adam’s apple bobbing. Lefivre’s lips were pinched and white. He was fighting not to scream, but it was a fight he was about to lose.

Landerson clamped his hand over Lefivre’s mouth. Realising what was happening, Purchason grabbed Lefivre too, hugging him tight to keep him upright and pin his arms. Landerson felt Lefivre’s mouth grind open, and squeezed his hand tighter, fighting back a cry as Lefivre’s teeth bit into his palm.

The glyf trembled. The insect noise increased, purring, then sank away. The glyf drifted off to the north, hissing over the shattered roofs of the hab terrace and then away across the park. Landerson and Purchason maintained their grip on Lefivre. Ten seconds later, five excubitors ran past along the lane, heading towards the town. The glyf had found something, and now the patrol was drawing in. After a few minutes, they heard the dull bark of las-locks discharging.

Some poor unconsented, no doubt, hiding in the rambles of the park.

Landerson realised he was now unconsented too.

He took his hand away. Blood pattered onto the stony path. Lefivre slumped over, panting like a dog. In his terror, he’d lost control of his bladder.

“I’m sorry… I’m sorry…” he gasped.

“It’s fine,” Landerson whispered.

“Your hand…”

“It’s fine,” Landerson repeated. His hand really hurt. Lefivre had bitten a large chunk out of his palm. Now he smelled of blood, Lefivre smelled of piss, and they all stank of the sweat the tension had engulfed them in.

Landerson wrapped his hand in his neck cloth, and prayed they would not meet any fetch-hounds.
--------------------
**** Gereon Converts
--------------------
They made their way down around the skirts of the commercia into the depths of the town. On one of the main avenues, a torch-lit parade was winding past, filling the night with the din of drums and cymbals. A mixture of excubitors and battle-troops formed the vanguard. Many of them held aloft spiked, racemose standards and filthy banners on long poles. The bulk of the procession was citizenry, shackled in long, trudging lines, singing and clapping.

These were proselytes. It saddened Gaunt to see so many. Every day, more and more members of the cowed populace elected to convert to the wretched faiths of the enemy. Some saw it, perhaps, as their only chance to survive. Others regarded it as a way of securing a better life, with greater liberties and consents. For the most part, Gaunt thought darkly, they converted because Chaos had swallowed their bewildered souls.

Ordinals led the parade towards the temple. Landerson had told Gaunt that “ordinals” was a blanket term for the senior administrators of the enemy power. Some were priests, others scholars, bureaucrats, financiers, merchants. They wore elaborately coloured robes and headdresses, and their be-ringed fingers hefted ornate staves and ceremonial maces. Some were female, some male, others indeterminate, and many displayed horrifying mutation traits. Gaunt couldn’t tell — didn’t want to tell — what the variations in dress and decoration denoted. They were all enemies. But they intrigued him nevertheless. In his career, he had faced the warriors and the devotees of the Ruinous Powers in many guises, but this was the first time he had properly laid eyes on the dignitaries and officials who ordered their culture and society. These were the fiends who followed the smouldering wake of battle and established rule and control over the territories conquered by their warrior hosts.

Once the parade had passed, the three men hurried on into the low pavements where the town’s administratum buildings had once stood. Here, the faces of the broken walls and chipped plasterwork were covered with paint daubs and scribbles that made nonsense words and strange designs. In one large square, lit by fierce bonfires, hundreds of human slaves laboured under the attentive guns of excubitor squads. The slaves, some on makeshift ladders, were painting more designs on the open walls.

“Petitioners,” Landerson whispered. “Or criminals trying to atone for minor infractions. They labour day and night until they either drop of exhaustion, or make a mark that is deemed true.”

“True?” Mkoll echoed.

“The enemy does not teach its signs and symbols, except to the converted. It is said they believe that those touched with Chaos will know the marks instinctively. So the petitioners make random marks, scribing anything and everything their imagination comes up with. If they make any mark or sign that the ordinals recognise, they are taken away for purification and conversion.”

Amongst the gangs of excubitors, three ordinals lurked, overseeing the insane graffiti. One of them sat astride a mechanical hobbyhorse, a bizarre machine whose body rose above its small wheels on four thin, strut-like legs. The ordinal trundled around on his high perch, shouting orders. He looked like a child with a nursery plaything, as dreamed up in a nightmare. There was nothing childish about the twin stubber pintle-mounted in place of the hobbyhorse’s head, though.

Avoiding the square, they darted from cover across an empty street and into the breezeway opposite. This was a narrow rockcrete passage, which smelt of urine. At the far end of it, behind a row of overflowing garbage canisters, was a low hatch.
--------------------
**** Pheguth interrogation
--------------------
Idresha Cluwge had been belching at him for three hours now. True, her skeletal hand-maids had been translating her guttural questions, but the pheguth felt like he’d been burped at for long enough.

“I’m tired,” he said.

The Anarch’s chief ethnologue leaned back in her grav-chair and steepled her massive fingers across her domed chest.

“We have barely begun, pheguth,” she said, via one of her life-wards.

The pheguth shrugged. The ethnologue bemused him. Not as a person — she was a grotesque monster, and that was bafflement enough. No, it was her purpose. It was her duty to learn in all detail about the life and culture of the enemy. That’s what she’d told him on the dam. She asked him curious questions like:

“How does a man make the sign of the aquila, and what does it represent?”

or

“Eggs, when fried, are popular amongst men of the Imperium, are they not?”

or

“How old must an Imperial child be before he or she is considered fit for military service?”

or

“Explain simply the financial mechanisms of the Munitorum.”
--------------------
They knew nothing. Nothing! It made the pheguth laugh. For all its might, for all its frightening power, the archenemy of mankind understood virtually nothing about the day-to-day workings of the Imperium.

The ethnologue was, in his opinion, the archenemy’s most formidable weapon. The forces of the Ruinous Powers might lay waste to worlds, conquer planets, and burn fleets out of the void, but they did not even begin to understand the mechanisms of their sworn enemy.

Cluwge was an instrument in that subtle war. She asked the questions that were unanswerable during the heat of combat. She asked about the little details, the small particulars of Imperial life. The hosts of the Archon might crush the warriors of the Imperium, might drive them to rout, but Cluwge’s understanding offered them true mastery. Defeating the enemy was one thing. Comprehending the workings of its society so that it might be controlled and suppressed — that was quite another.

Idresha Cluwge was a tool of domination. What she learned informed the higher powers and armed them for rule.

The pheguth had answered his best.

“I want to go now,” he said. The nagging pain of transcoding soaked his brain. “Tomorrow, or the day after, we can take this up again.”

Cluwge shrugged.

The pheguth rose. “A pleasure,” he said and walked out of the room.

He had expected to find his antlered handlers in the anteroom, but there was no sign of them. The door stood open and bright sunlight beckoned from the gallery beyond.

The pheguth walked through the door and out onto the gallery. Daylight spilled in through the windows. The gallery was empty right down its length. At the far end, the next door was also open.

“Desolane, Desolane,” the pheguth tutted as he scurried down the gallery in his slippers. “When will you stop these tests of my loyalty?”

A figure stepped in through the doorway at the end of the hall. It was not Desolane. The pheguth had never seen this person before. He came to a halt, eyes narrowed in curiosity.

“Who—?” he began.

The man was tall and clad in dark khaki fatigues. He was sweating, as if he was scared.

“Are you the pheguth?” he asked in a curiously accented voice.

The pheguth began to step backwards. “That is what they call me…” he replied, his voice tailing off.

The man in khaki produced a laspistol from his tunic and aimed it at the pheguth’s head.

“In the name of the Pact and the Archon!” he said.

And fired.
--------------------
**** drinker of seas
--------------------
They drove for an hour, down through the steep cliff passes away from the bastion, onto a highway that had been repaired after shelling. The squadron of excubitors escorted them in their growling half-tracks. Deathships, fat-winged and freckled with gunpods, tracked them overhead.

“There is a function,” said Desolane, sitting back in one of the transport’s ornate seats.

“A function?”

“For which your presence is required.”

“Am I going to like it?” he asked.

“That hardly matters,” the life-ward replied.

They passed through some burned-out towns, through tenement rows of worker hab-stacks that the enemies of the Imperium had turned their meltas on. Finally, the cavalcade drew to a halt on the head road of a massive dam that curved between the shoulders of a craggy mountain range. The daylight was cold and clear, and water vapour hung like mist.

About three hundred battle troops stood in files along the dam top, weapons shouldered. Several pennants fluttered in the wind. As he dismounted from the transport, pulling the cloak around him for warmth, the pheguth saw the waiting group of dignitaries. Ambassadors, stewards, division commanders, warrior-officers, chroniclers, all attended by their own life-wards.

And the Plenipotentiary Isidor Sek Incarnate himself.

“By the Throne!” the pheguth gasped as he saw him.

The troops and excubitors in earshot cursed and ruffled, some spitting against ill-omen.

“Try not to say that,” said Desolane.

“My apologies. Old habits.”

“This way.”

Desolane walked him down to the waiting group. There was some back-and-forth formal ceremony involving Desolane and the other life-wards. Challenges were shouted, antique oaths and ritual insults, a drawing and brandishing of weapons.

Isidor waited until the performance was done, and then beckoned to the pheguth.

He’d met Isidor twice before, once on arrival on Gereon, then again the night before the transcoding sessions had begun. Isidor Sek Incarnate was a short, plump human male wearing long black robes and a grey cowl. His pale, hairless face presented a permanent expression of disdain. He was the Anarch’s instrument of government on Gereon.

There was nothing about him that was at all intimidating or frightening, and that’s why he terrified the pheguth. This little man was surrounded by monsters— a veritable minotaur held a black parasol over his head deferentially — and massive Chaos Marines paid him fealty, yet there was no visible clue to his source of power. He was just a little man under a parasol.

“Welcome, pheguth,” the Plenipotentiary said. His voice was like a sharp knife slicing satin.

“Magir magus,” the pheguth responded as he had been rehearsed, bowing.

“There are two persons I would like you to meet,” said the Plenipotentiary. “You will be spending a lot of time with them in the next few months.”

“What, may I ask, about the transcoding, magir magus?” he asked.

“That will continue. Transcoding you is our foremost agenda. But other issues will grow in importance. Otherwise, there is no point keeping you alive. Meet these persons.”

“Of course, magir magus.”

Isidor made a signal. Something vast and vaguely female crawled forward. She was immense and swollen, like the effigies of the Earth Mother early humans had fashioned, so morbidly obese that all the features of her face had vanished into folds of skin except her loose mouth. A wide-brimmed Phrygian hat perched on her scalp and swathes of green and silver fabric enveloped her bulk and flapped loose in the wind. Four midget servitors, squat and thick, clung around her lower body in the folds of her gown, to support her weight. Two hooded life-wards, both women, both skeletally thin, walked beside her, their long fingers implanted with bright scalpels.

“This is Idresha Cluwge, Chief Ethnologue of the Anarch,” said the Plenipotentiary. “She will be interviewing you over the coming weeks.”

“I…” he began.

The female slug spoke. A barbaric clutch of consonants burst from her fat mouth like a burp. Immediately, her two female life-wards translated, in chorus.

“This is the pheguth, Isidor? How intriguing. He is a little man. He looks not at all like a commander of soldiers.”

“I’d like to say you don’t look like an ethnologue,” said the pheguth. “Except that I have no idea what one of those is.”

The female life-wards hissed and raised their blade-fingers towards him.

“Oh, have I erred on the protocol front?” the pheguth asked dryly.

“Show respect, or I will slay you,” Desolane warned him.

“He’ll eat your liver…”

“I’ll take that chance. The chief ethnologue is a person of consequence. You will evidence respect for her at all times.”

“Just playing with you, Desolane. Can she at least tell me what an ethnologue is?”

“It is my duty to learn in all detail about the life and culture of the enemy,” the life-wards said in unison the moment the female thing had stopped burping out more noises.

“I’m sure it is,” said the pheguth.

“All will become evident,” said the Plenipotentiary. He nodded, and a second figure stepped forward. “This is the other person I wish you to greet.”

The man was a warrior. The pheguth recognised that at once. Straight-backed, broad, powerful. He wore a simple coat of brown leather, insignia-less army fatigues and steel-shod boots. His head was bald and deeply, anciently scarred. Ritually scarred. The warrior took off one glove and held out an oddly soft and pink hand to the pheguth.

“I believe this is how one warrior greets another in your part of the galaxy,” he said in clipped, learned Low Gothic.

“We also salute,” said the pheguth, shaking the man’s hand.

“Forgive me. I can clasp your hand, sir, but I cannot salute you. That would result in unnecessary liver-eating.”

The pheguth smiled. “I didn’t catch your name, sir,” he said.

“I am Mabbon Etogaur. The etogaur is an honorific.”

“I know,” said the pheguth. “It’s a rank name. The Guard had pretty damn good intelligence. It’s indicative of a colonel rank or its equivalent.”

“Yes, sir, it is. General, actually.”

“It’s a Blood Pact rank.”

Mabbon nodded. “Indeed.”

“But you present to me unmasked and your hands are clean of rite scars.”

Mabbon pulled his glove back on. “You appreciate a great deal.”

“I was a general too, you know.”

“I know.”

“And you’re going to be talking to me?”

Mabbon nodded.

“I look forward to it, sir. I wonder if at some point we might explore the meaning of the word ‘pheguth’.”

Mabbon looked away. “If needs be, that might happen,”

The pheguth looked back at the Plenipotentiary.

“Are we done?” he asked.

“Not even slightly, pheguth,” the magir magus replied. “Nine worlds in the Anarch’s domain lack water sources. They are parched, thirsty. Today, here, we conduct a ceremony that will access Gereon’s resources to aid them. The process has already been done at four sites on the planet already. I wanted you to oversee this one.”

“Another test of my resolve?”

“Of course another test. Wards, bring the cylinder.”

With Desolane and the minotaur at their heels, the Plenipotentiary led him to the wall of the dam overlooking the vast reservoir beyond.

“Eight billion cubic metres of fresh water, replenished on a three-day cycle. Do you know what a jehgenesh is?”

“No, magir magus, I don’t.”

Isidor smiled. “Literally, a ‘drinker of seas’. That’s quite accurate. It leaves out the warp-fold part, but other than that…”

Two goat-headed servants clopped up to the wall, and held out a glass canister in which about three litres of green fluid sloshed. Deep in the fluid suspension, the pheguth could see something writhing.

Isidor Sek Incarnate took the cylinder and handed it to the pheguth. “Don’t be misled by its current size. It’s dormant and infolded. Released into the water, it will grow. Essentially, it’s a huge maw. On one end, flooding in, this water source. The jehgenesh is a warp beast. The water that pours into its mouth will be ejected through the holy warp onto another world. The arid basins of Anchisus Bone, for example.”

The pheguth gazed at the cylinder in his hands. “This is how you plunder?”

“It is one way amongst many.”

“But this is why so many worlds we find have been drained?”

The Plenipotentiary nodded. “The drinkers swallow water, also fuel oil, promethium, certain gas reserves. Why would we conquer worlds if we didn’t actually use them? I mean, literally, use them?”

The pheguth shrugged. “It makes perfect sense. What do I have to do?”

“Unscrew the lid. Release it.”

“And prove I am loyal?”

“It’s another step on the way.”

The pheguth turned the steel cap of the canister slowly. He felt the warp-thing inside writhing, agitated. The lid came off. There was a smell… like dry bones. Like desert air.

“Quickly,” said the Plenipotentiary. “Or it will drink you.”

The pheguth up-ended the canister, and the green water poured out into the reservoir, along with something slithering and coiled.

“Two days,” said Desolane. “Then it will grow.”

“I’d like to go back to the bastion now,” the pheguth said, turning away from the lake.
--------------------
