* Dissertation bits and pieces
** Dissertation                                                                 :structure:
*** Prior Work and Context
    Sociology/ Anthropology / Ethnology
    Economics
    Critical Theory
    AI and MAS
    Computational Media

    Identification of Hole in Literature:

*** Methodology
    Phenomenology and Grounded Theory
    Inhabited Institutions
    Computational Media and code studies

    Resulting Methodology:

*** Existing in the World
    Fiction
    Non-Fiction
    Theory
    Computational

    Result: Dataset

*** Pre-formal Theory
    Analysis of existing forms and examples
    Source Code Analysis
    Grounded Theory Coding

    Result:

*** Formal Calculus
    Delegation Logic, Monads, Exclusion logic,
    Temporal Calculus etc

    Result:

*** Computational Implementation
    consideration of Cif, Versu, Rete, Neural Networks, haskell, monad transformers
    Tidal and ChuCk, Meta/Reflective towers, MOISE

    result: python layered DSL Production System, temporal, reflective, typed? modular

*** Authoring / UX Considerations
    WebShell, prior authoring programs, programming, netlogo,
    user interfaces, live coding
    emacs, spacemacs

*** Resulting Experiences
    city map, newspaper, soundscape, vault, street, bot?

    Result:

*** Rebuttal of Criticisms
    Games criticisms
    Theory criticisms
    Engineering criticisms

*** Reflection
*** Title
*** Introduction
*** Abstract
** [[file:designDocNotes.org::*Generalised%20Design%20Document][Generalised Design Document]]                                                  :design:
** [[file:typewriter.org::*Typewritten%20Notes][Typewritten Notes]]                                                            :raw:
** Plans and Dissertation Structure                                             :dissertation:structure:plans:
   Interspersed with Examples:
   Games / Fiction / Anthropological

   Intro
   Background   : Institutional theory, Examples
   Background 2 : Systems and Games, Examples
   The Structure of Institutions
   The authoring of Institutions
   The modelling of Institutions
   Example Models
   Analysis and Assessment
   Discussion
   Conclusion

*** Argument
    Institutions are *structured* collections of normative rules.
    They inform all aspects of social action.
    They make for cheaper, faster, and better reperesentations to author social simulations with.
    (Better in that they can encode interactions?)

    They structure of Institutions is fluid, changing, and ill defined.
    Assistive authoring tools are required to feasibly create them (why?)

    Assessment of modelled institutions should look less at coherence and more at ... what?
    Not intelligibility or stability.

**** Questions
     What are Institutions?
     What does an Institutional Analysis of Games/AI Reveal?
     What does an Institutional Architecture Enable?
     Why would we want to model Institutions?


     Related to Cohen:
     What will happen if you vary an institution?
     Does an institution generated and varied in a procedural way model
     real world institutions accurately?
     Do Institutions explain the changes that can occur socially?
** Dissertation Chapters                                                        :structure:
*** Title
*** Introduction
**** Institutions 101
**** Problems
**** Socially Inspired Computing
**** Research Questions
**** Contributions
*** Institutional Design 101
*** Core Theory Influences
**** New Institutionalism / Field Theory
**** Activity Theory
**** Normative Multi-Agent Systems

*** General Background
**** Theories
***** Giddens
**** Media
***** Games
***** Fiction
**** Formalisms
***** Grossi
***** Evans Exclusion Logic
**** NorMAS
***** Balke
**** Sociology and Anthropology
***** Graeber
**** Authoring Tool Design
*** Theory of Institutions
**** Structure of Institutions
**** Norms and Rules
*** Institutional Analysis of Existing Media
**** Fiction
**** Games
*** Institutionally Inspired Simulations/Games
*** Architecture
**** Authoring Tool
**** Institution Sim
*** Implementations
**** Vault Sim

*** Results and Analysis

*** Conclusion
**** Future Work
*** Bibliography
** Institutions                                                                 :writing:plan:
*** Introduction
    [[file:notes/argumentOverview.org::*On%20Inserting%20Ritual%20structure%20into%20social%20interactions][On Inserting Ritual structure into  social interactions]]
    [[file:notes/dissertationOutline.org::*Socio-Institutional%20Action][Possible Structure]]
    [[file:notes/evansNotes.org::*A%20Socio-Institutional%20Approach%20to%20Action][A Socio-Institutional Approach to Action]]
    [[file:notes/research/extracts.org::*Text%20extracts%20of%20interesting%20Cultural%20interactions:][Text extracts of interesting Cultural interactions:]]
    [[file:notes/research/extracts2.org::*Extracts%202][Extracts 2]]
    [[file:notes/research/extracts3.org::*Extracts%203][Extracts 3]]
    [[file:notes/research/sia.org::*SIA][SIA]]
    [[file:notes/tribeDescriptions.org::*Tribe%20Descriptions][Tribe Descriptions]]
*** Related Work
    [[file:notes/bookNotes.org::*General%20Books%20notes][General Books notes]]
    [[file:notes/culturalAntroNotes.org::*Cultural%20Anthropology%20notes][Cultural Anthropology notes]]
**** [[file:General_Games.org::*General%20Games%20and%20IF][General Games and IF]]
**** Nor-MAS systems                                                            :norMAS:
     Moise
**** Institutional-Philosophical Systems (nomic)
*** Norms                                                                       :norms:
*** [[file:phenomenologyOfInstitutions.org::*The%20Phenomenological%20Experience%20of%20Institutional%20Variation][The Phenomenological Experience of Institutional Variation]] :phenomenology:
*** [[file:game_concepts.org::*Game%20Concepts][Game Concepts]]                 :concepts:games:
*** [[file:Rational_Reconstructions.org::*Rational%20Reconstructions][Rational Reconstructions]] :rationalReconstructions:
*** Implementations
*** [[file:institutions.lhs::Institutions.%20A%20Way%20of%20conceptualising%20social%20interactions%20and%20their%20interrelation][Formal Description of Institutions]] :institution:formal:
*** [[file:notes/anotherAttempt.org::*Socio-Institutional%20Action][Socio-Institutional Action]] :socioInstitutional:
*** [[file:threeIdeas.org][Real time Functional AI Authoring]]                  :authoring:ai:
*** Conclusion
    In conclusion, I have shown how underdeveloped the systems in videogames are regarding institutions.
    Literature on Institutions, as structured collections of norms, glosses over structural and mechanical descriptions of,
    in all but the most trivial of cases.
    Those computational systems that have approached simulation of institutions (CiF and Versu in particular),
    have only supported authored situations, lacking the ability to vary and generate institutions themselves.
    By describing the structural and procedural components of existing historical institutions, it is clear that the
    rational coherence of institutions are typically overstated.
    I have implemented, inspired by current Nor-MAS systems, a variety of social institutions, and varied them procedurally.
** Vault Sim Design Doc                                                         :design:

   A Fallout Shelter Simulation to bootstrap simulations and norms into
*** Components
**** Vault
     A Stack of Floors
***** Floor
      A Row of Rooms
****** Room
       Each room holds actors and objects, and has a purpose.
       Can be an elevator to another floor.
******* Actor
        Moves horizontally,
        interacts with objects and other actors.
        Moves between floors using elevators.
******* Object
        Existing in a room, can be picked up, manipulated, produced, consumed.
*** Simulation Components
    Actors, objects, sources, sinks.
    Room purposes: Water, food, raw materials, produced materials.
    Floors
*** Norms
*** Connection to underlying model
    Network based to either: JS Rete, Python iElPy, Haskell FSM.
*** Plan
    Define rooms: Size, width, slots for items. - Fixed height and width for the moment.
    Create Elevator room type.
    Create floor controller: A Row of rooms, with elevators at specified points.
    Create Actor: Move left and right
    Create Vault Controller: A Stack of floors, with elevators aligned.
    Create Simulation Controller: Central repo to hold food, water, power information
    Create Item Generator and Sink.
** Socio-Institutional Action                                                   :writing:socioInstitutional:

*** Introduction
**** What is Socio-Institutional Action?

     Human behaviour operates on numerous levels of
     abstraction. Individual, personal relations such as family
     and friends. Institutional interactions in schools and
     churches. More abstracted interactions such as mass media,
     with cultural norms and values even further abstracted. All
     of these combine to create the rich and complex society and
     social interactions that we observe every day.

     Current computational social models focus primarily on the
     less abstracted, interpersonal interactions of
     individuals, in the form of games like Prom Week and
     Versu. On the other end of the scale there are 4X games such
     as Civilisation that deal with highly abstracted concepts of
     society. Between these two extremes is a level of human
     behaviour currently invisible in computational models and
     game design. Let us define this intermediate level of
     behaviour as Socio-Institutional Action (SIA).

     SIA characterises behaviour that bridges interpersonal
     interactions with structurally modifying consequences. The
     easiest example of SIA is politics. The ways in which
     individuals in positions of power define and create the laws
     by which others live. Consider the personal interactions
     that are required in tv shows such as House of Cards and The
     West Wing to bring about political actions.

**** What is it different from?

     SIA contrasts significantly with the majority of current
     architectures, games, and discussions. Structural Change in
     games is typically a factor of the narrative rather than the
     system within which a player operates. Games such as
     Civilisation presumes no resistance to making changes to a
     society. Prom Week does not question the system which in a
     school prom occurs and does not model the power
     differentials of teachers to students. The Sims lets players
     control agents behaviours and accomodations, but not the
     society in which they operate. SimCity Societies approaches
     concerns of different societies, but, as Fable 3 does,
     limits itself to societal traits with relatively little
     freedom. Democracy 3 abstracts political change and relies
     on explicitly defined policies.

     In contrast, consider The Wolf Among Us, and Dragon Age
     Origins. They place particular individuals in positions that
     will decide the fate of many others. Unfortunately, they are
     explicitly authored narratives, rather than simulated
     societal changes.

**** Why is it important?

     Videogames are well suited to explore through simulation
     issues challenging society at the moment. The possibility of
     being able to role play in varieties of different social
     configurations can provide a large number of learning
     experiences. Institutionalised racism, command rape,
     discrimination, welfare. Simulated societies provide the
     possibility for individuals to understand the challenges
     facing those who are different.

     One simple example would be a computational implementation
     of Rawl's 'Veil of Ignorance' thought
     experiment. Implementing the capability of players to select
     the rules by which a society works, without having control
     or foreknowledge of their own position in society, is a
     compellingly different gameplay experience.

**** What are some good examples of it?

     In games, examples of actual SIA's are few and far between. Some of
     the best examples are recent Telltale games like the Wolf Among Us and
     Tales from the Borderlands. Games that place critically important
     decisions to shape the future course, not of a narrative, but of a
     society within a narrative, in the hands of the player. Fable 3
     attempted something along those lines as well.

     In realms less game related, the West Wing, Neal
     Stephenson's Anathem, and Robert Greene's the 48 Laws of
     Power all provide numerous examples of individuals being in
     the right place at the right time to change the course of a
     society.

**** Research Questions
     A number of research questions arise once the concept of SIA
     has been brought to the fore, primarily:

***** How can we describe Socio-Institutional Actions?
***** Can we create dynamic societies within which SIA's can occur?
***** Can dynamic societies provide new media experiences?
***** How might we utilize dynamic societies in games?

*** Background
**** Existing Games that employ Socio-Institutional Action
***** Middle Earth: Shadows of Mordor
***** Dragon Age: Origins
***** The Wolf Among Us, Tales from the Borderlands
***** Papers Please, This war of mine
***** Sunless Sea, Analogue a hate story, Skyrim, Mass Effect, VTMB,
***** Prison Architect, Redshirt, Dwarf Fortress, Sir you are being hunted.
**** Literature Review
***** Searle and Austin
***** Giddens
***** Biccheri
***** Fligstein
***** Bourdieu
*** Theoretical Aspects
**** Time, Circularity, and Change
**** Ritual beyond Social Practice
**** Power and Authority
*** Methodology and Architecture
**** Current Systems
**** Next Steps
*** Proposed Media Experiences
*** other
    Socio-institutional action, a level of individually observable
    behaviour that takes into account more than personal motivations. The
    majority of games and AI today have statically allocated allegiances
    to factions, global communicative behaviour, and global cultural
    norms. By foregrounding the social organisation of groups of agents, a
    different type of social behaviour can be modelled.

    Consider this problem from another angle. Current understandings of
    action, and the criteria by which we judge 'social' intelligence in
    AI, stems heavily from an ethnocentric viewpoint of modern, western
    cultures. There are games such as Unrest and Never Alone are starting
    to explore non-western and non-modern cultural descriptions. However,
    the majority of games, even when dealing with fantasy settings such as
    Skyrim, typically do not stray far from modern cultural concepts.

    Consider a comparison between Skyrim and Metro:2033. In Skyrim
    traveling to a different city does not bring about any important
    changes in behaviour or social norms. I can rest assured that there
    will be traders, a market economy, houses for families,and so on. I do
    not need to consider that there will be vastly different social norms
    as to how to successfully greet npc's, nor that i need to pay
    attention to individuals behaviours to be able to survive.

    Contrast this, somewhat, with Metro:2033. Although much more linear,
    each metro station has it's own atmosphere, politics, and
    allegiances. The factions are still static, but at least I get the
    sense that they each have their own sets of values rather than being
    cardboard cutouts of each other. The Reich, the Reds, the
    Rangers... each have goals that can be expressed in opposition to the
    other factions.

    Now consider fiction such as Altered Carbon, or Gormenghast. In these,
    there are multiple layers of social norms, centuries of tradition,
    and goals that group individuals together. Part of the attraction of
    seeing the characters in these works manipulate their situations is
    that some things are inviolable, while others are not.

    How could such variation and fluidity be achieved? There do exist social
    simulations that enable individuals to have personal goals, and
    interact with other agents in broad and complex ways. Yet there is no
    capability to manipulate structural aspects of their lives. They can
    not have realisable political goals.

    Such viewpoints may bring about useful and novel play
    experiences. Rawl's Veil of Ignorance is one such possibility if we
    can author societies instead of individuals. Allowing a player in an
    RPG to roll a society, with their character being placed in that
    society randomly, may enable a level of cultural criticism and
    exploration not currently feasible. Current events such as Trayvon
    Martin and Eric Garner have highlighted the consequences of ingrained
    cultural views on particular classes of people, both police and
    minorities. To be able to allow players to explore the difficulties of
    living in particular societies that on the face of it are entirely
    just, but only become problematic when power differences become
    apparent, would be a valuable contribution to society.

**** Theory
**** Sociology

     There is a whole host of sociological, philosophical, and
     anthropological literature that goes into various ways of describing
     and reasoning about such structures in human lives. Discussion of
     power by Bourdieu, Greene, and Levi-martin. Considerations of cultural
     structures include people such as Bill Bryson, Norbert Elias, and Ruth
     Benedict. There is a whole host of literature in organisational theory
     by Powell and Dimaggio, Fligstein and McAdam, and many others.

     All of the above examples provide usable resources with which to add
     higher level structures onto existing personally focused social models.

**** AI

     In applied Artificial Intelligence, there are the two primary social
     models of CiF and Praxis. There are considerations of continued
     actions interrupted by other higher importance actions by Bryson with
     Bod and Posh. Castelfranchi, spanning philosophy and AI, has
     considered different levels of social actions.

**** Architecture
**** Praxis
**** CiF
**** Media
**** Existing

     Existing games that move towards a foregrounding of socio-institutional action include

**** Intended

** On Inserting Ritual structure into  social interactions                      :socialInteractions:ritual:

*** The Question
    Can a ritualistic or tribal society be
    procedurally generated over the top of CiF
    and/or Praxis?

*** Clarification

    Tribal Societies defined as group structures,
    that provide a number of:
    a) transformative representations of a society's
    reality (ie: war parties => dancing)
    b) Consequential, irremedial, irrevocable acts
    c) a Stake in the proceedings
    d) status change
    e) use of space
    f) marking of time
    g) display / reaffirmation of relation
    h) power structure / authority
    i) hygene, courtesy, norms,
    j) information transfer / indoctrination
    h) social action
    i) signaling modification of a different rule

*** Example: Gormenghast
*** Example: Schechner
*** How
*** The Conclusion

** Computational Social Science Thoughts
*** Musings on Jurafsky et al's computational politeness

    Praxis deals with social transgressions through explicitly authored
    actions.  This is somewhat ill suited to my general task of replacing
    as much authoring as possible with a generative approach.

    Jurafsky talks about politeness being a central force in communication
    'as basic a pressure as to be truthful, informative, relevant, and
    clear'. This is a far nobler view of communication than I wish to
    model. I agree that language provides numerous and diverse means for
    encoding politeness in conversation.

    I want to be able to vary the level of encoding of politeness, truth,
    information, relevance, and clarity. What else could be varied, and
    should be varied?

    If we can define politeness markers, identify their position in speech
    acts such that they act as markers, *and* can identify their
    correlation with higher level concepts such as power, *and* such
    relatively easily defined terms that comprise power, such as social
    status, authority and autonomy, then why are we not using it to
    structure and procedurally generate agents, enabling them to have a
    rudimentary economy, and then playing with the knobs?

    Computational Social Science seems to have a broad number of means of
    modeling a reasonable number of different social structures (ie: see
    Axtell's Sugarscape that seems to have evolved a ton of
    behaviours). We should be able to combine such behaviours, and pair
    them with at least rudimentary speech acts surely?

*** Walker et al. Improvising linguisting style: social and affective bases for agent personality.

    This may be the starting point, coupled with a set of cultural rules,
    a vocabulary and linguistic styling of walker, could then feed up to
    personal agents emotional status. This can interact with their
    institutional authority.

    Thus: 1) Cultural rules: always be polite to little old
    men. Politeness consists of: marking + following their
    requests. Honourifics: Sir, Madam, etc...
    2) Polite Markings: Please {Honourific}. etc.
    3) Basic Speech Acts to decorate.
    4) institutional acts to perform, as verbs of
       combinations of sequences of behaviours?
** Dark Souls and The Institution of 'Praise The Sun'                           :examples:games:institution:darkSouls:
*** The Dark Souls Base Game
**** The Physical System
***** Combat - Physical attacks
      The combat is a large amount of complexity. Light, Heavy, Two Handed
      attacks, kicking, blocking, Weapons, items, and armour all provide changes
      to the events that can, and do, occur.
***** Movement
      The speed of movement is based upon, essentially, what a player is wearing.
***** Conversation with specific individuals
      Linear sequences of individual meetings, with specified binary response
      points, and triggered by particular actions in the larger game world. Can
      enable purchasing, and simple quests.
***** Purchase of Items and Spells
      Spells fall into a couple of particular categories (Sourcery, Pyromancer,
      Dark, Light) which can also have meaning related to affiliation and likely
      actions
***** Bloodstains and Ghosts
      Provide short inaccurate histories of player deaths, a visual record of
      someones actions.
***** Fog Doors
      Hint at major location transitions, and Bosses, but it can be hard to know
      which
***** Bonfires
      Hub points for individuals to gather to some extent
***** Physical Objects
***** Enemies

**** NPCs
     There is the despondent knight, the cleric, etc. People to talk to you can
     buy items from, or summon them during fights, and who provide information.
***** [[http://darksouls.wikidot.com/solaire-of-astora][Solaire]]
      As a recurring, iconic individual, Solaire grabs attention, and 'Praise the
      Sun' has become a favourite. It has *meaning* and ties people together.
***** [[http://darksouls.wikidot.com/siegmeyer-of-catarina][Siegmeyer]]
      Siegmeyer is another iconic character, remaining ironic as you progress
      past him constantly, while he is always friendly.
*** [[http://darksouls.wikia.com/wiki/Covenant][Dark Souls Covenants]]
    The covenants provide an institution in isolation. The actions of the base
    game limit what can be done, while the covenant collects behaviours, meaning,
    and messages to interact with others. The covenants are essentially the
    institution, abstracted from the organization. They provide a set of base
    concepts, and idealised behaviours, without there being a formal organisation
    with actions, tasks etc. There are no relations between members of the
    covenants in most situations.
**** Warriors of Sunlight
     Solaires Covenant.

*** Communication with NPCs and Others
    Communication falls into Scripted text sequences between the player and NPCs,
    and limited grammar messages between players.
**** Custom Language Sequences
     NPCs can have limited amounts of customised language, fully english.
**** [[http://darksouls.wikia.com/wiki/Messages][Dark Souls Grammar]]
     Messages meanwhile are limited to a limited grammar, providing sequences of
     simple symbols. 
**** Surroundings + Symbols + Meaning -> Message
     You see an impressive (meaning) sight (surrounding), and leave a message to
     communicate that with others.

     You get killed by an enemy (surrounding) that you hadn't noticed initially
     (concept: ambush), and leave a message to warn others.

     You read a message of symbols which provides you a direction to praise the
     sun.

     (Note: the surrounding, and grammar are very strictly defined) Can this be
     represented as a simple algebra? meaning + surrounding + symbols -> message
     So: message - surrounding -> symbols + meaning all the while holding the
     following constant: message - surrounding - meaning - > symbols

     But what is important about this is that language is powerful enough to
     allow repeated uses to perform: message - grammar - meaning -> surrounding
     and: message - surrounding - symbols -> meaning


     If we make up a type system for this: Meaning :: Grammar Surrounding ::
     Grammar Symbols :: Grammar AgentState :: (Meaning, Surrounding) Message ::
     AgentState -> Meaning -> Surrounding -> Symbols -> AgentState

     A Message is an operation of an agent, with limited grammars for thinking,
     observing, and manipulating the world, which triggers a state change in some
     other agent.

     The above describes a base functional system that lacks institutions. The
     effect of institutions on those formulae could be: Institution :: Rules ->
     Institution Institution(M) :: message -> Institution -> Institution(Message)

     Ie: An Institution is a co-monad. It holds contextual information, which can
     then be bound with an actual message, to encode effects.

     So, an institution can provide coherence between messages more complex than
     the message on its own can handle.
** Firefighting as a Game/Sci-fi concept                                        :concepts:
   Mech suits (eg: X-Com) are typically combat focused. Also fire is rarely a
   primary mechanic, but Far-Cry 2 had detailed models of fire spreading. Power
   fantasies don't have to be combat oriented. The image of, after having played
   for hours, finally obtaining a mech suit built for firefighting, making you able
   to walk through walls and ignore fire, when you've been limited the entire game,
   would give the same power fantasy achievement.

   Narratives could easily include arsonists, terrorists, etc.
** Game Concepts                                                                :games:concepts:design:
*** Institutional Modification                                                  :institution:
**** Society Generator
     See Red Mars / Galactica / Walking Dead / other Post-apocalyptic stories. A
     linear set of challenges which define the rules of a society as it grows,
     which is then simulated afterwards. Eg: The choices of whether to ban or
     allow abortion, limit military control etc in Galactica set up a particular
     society. The difference is obvious when comparing Galactica to Pegasus.
**** Social Leaders
     Designated individuals are Institutional Entrepreneurs, leading the way for
     how others should behave. Trump is an example for bringing out blatant
     racism.
**** Reified Policy Maker
     Red Mars. Democracy connected to the Sims. The King of Dragon Pass. Seeing
     how prescribed, allowed, preferred behaviours shift general trends. Racially
     focused policing, essentially BLM / Police. Modelling agents
     knowing/anticipating the likelihood of positive or negative outcomes from
     interactions with others. Knowledge of minimum and maximum outcomes. If you
     know the worst a situation can get is only so much changes how you behave.
     Polite to people who, in the rules of the system can cause negative
     consequences. Rude to people who can't. Angry at someone going negative when
     the expectation is positive.

**** Observable Democracy
     A Positech Democracy like simulation, but where actions are modelled,
     possibly sims like, that *shows* the consequences of legalising drugs /
     banning firearms / increase in crime etc.

**** Judiciary / Activist Judge
     Generate Criminal / Civil disputes, allow the player to set binding rulings,
     punishments, fines, and restrictions. Define the hierarchy of values for a
     society.

     See also: Graeber: Accounting in defunct Roman coinage / Slaves / Cows /
     Maidens.

*** Situation Models                                                            :situations:
**** Squad Dynamics
     XCom doesn't include interactions between squad members. See MGS5's Diamond
     Dogs, with some soldiers getting put in the brig. MGS's weakness however is
     that the conflicts are left implicit, and aren't shown ever.

     Soldiers joke, get nervous, shell-shocked, tired, and can hold grudges. As
     they get injured, they can get particular scars and prosthetics. The is
     similar to Elevator Conversations.
**** Apartment Block Simulator
     Simulate the interactions between individuals in an apartment block. Could
     think of JG Ballard's High Rise, Dredd, The Grand Budapest Hotel.
**** Elevator Simulator
     Conversations between individuals in an elevator. Dungeon of the Endless.
     Mad Men. The original thought I had from DotE was the awkward but character
     building conversations had going from one level to another. Take that and
     expand it to have connected conversations, interleaving: character, combat
     event recollection and discussion, and vying for social position.
**** Elevator Conversations
     Dungeon of the Endless has conversations in the elevator, that hint at more
     complex modeling. Distrust, blame, optimism etc could all come into play
     during those elevator rides. Characters could refer back to events that
     happened in the level just gone.

     Conversations between individuals in an elevator. Dungeon of the Endless.
     Mad Men. The original thought I had from DotE was the awkward but character
     building conversations had going from one level to another. Take that and
     expand it to have connected conversations, interleaving: character, combat
     event recollection and discussion, and vying for social position.
**** Organisational Promotion Simulator
     Shadow of Mordor, Voyager. Gormenghast. The Night Watch

**** Public Restroom simulator
     Inspired by North Carolina. Simulate Norms related to Bathroom. Parallels
     with Elevator simulator? Such as Design, Occupancy, Organising principle
     (caste? gender? sexual orientation? organisational position? religion?

**** Institution Play
     American Psycho / The Office / Parks and Rec / *Suits* like office games.
     Favours and grudges within bounds, reverting to working together when
     dealing with outside threats.

**** Office Politics
     Similar to the Shadow of Mordor simulator. Inter office squabbles. Who likes
     and dislikes whom.

**** Space Colonies
     2312-like Terraria / Off world Colonies. The fragility of space living, and
     the influence of orbiting planets for travel and trade.

**** Space Journey
     Gateway, Red Mars initial journey.

**** Social Lemmings
*** Institutional Variation                                                     :institution:
**** 'Go to the shops, I dare you'
     Sliders. Bill Bryson - At Home. John Brunner - Stand on Zanzibar. Alfred
     Bester. Rick and Morty take it to the extreme. The idea of life being put in
     situations that are familiar, but which are varied in infinite ways. Some
     major (Philip K Dick: TMITHC. Nazi's won the war), to the very minor (There
     was no Elvis, someone else is 'The King'). Let Money be shells. Everyone
     Greets in a strange formal way. Clothing Styles.
**** Country Differences

     Stand On Zanzibar compares broad descriptions of different countries. This
     could work well in a Positech Democracy style game.
**** Social Roguelike
     Binding of Isaac / Dungeon of Dredmor style game. Generated maps, with
     social predicaments in collections of rooms instead of violent enemies.
     Binding of Isaac style combination of a wide variety of pickups would be
     interesting. Queuing as an example? Very British Problems?

     Games still prefer violence and combat to social interactions. Anne Sullivan
     highlights it, but what does it really mean to have social gameplay instead
     of combat focused gameply? We can look at game dseign, and the systems that
     facilitate player to player social systems in games like Eve Online, and
     what Raph Loster has written about the variety of social gameplay mechanics
     that multiplayer games can use.

     His focus has typically been multiplayer games, but such mechanics should be
     able to be used for AI opponents as well.

     We can also look at how Cif and Versu enable social narratives to be encoded
     and reasoned about in computational systems.

     Going further, we can look at narratives and real world structures that
     describe the social gameplay that interests us.

     Organizations, Institutions, and politics. Red Mars and Discworld. The real,
     and fictional, worlds that exist in other media have no real equivalent as
     yet, but have suh potential.

     One important example is A Series of unfortunate events. A sequence of books
     that are all very simiar, but which the social system that surrounds the
     main characters changes dramatically each time.
**** Newspaper Generator
     A Dynamic form of Papers Please' Newspaper. Just front page, but with a
     headline, a couple of subheadings, a few quotes, links to particular pages,
     smaller topics. Exposes, corruption, scandals, celebrities, the front page
     is definitional of what is 'newsworthy'. So model that society's
     representation of it's own understanding.

**** Censorship simulator.
     Ministry of Truth in 1984, Censors in Media Positions today. The raw feed of
     actual actions, and the ability to choose what, or how much, to let through.

**** "Go Down to the Shops and Buy Some Milk"
     Sliders-style world variation, where the player needs to survive for a
     specified amount of time. Alt: Institutionalized / Normalized violence
     against specific classes of people. Spawn as White / Black / Male / Female,
     and see how behaviours towards you change.

*** Institutionally Aware Design                                                :institution:
**** Socially Responsive RPGs

     Where players have to abide by the norms instead of looting peasants'
     houses. Downton Abbey, Upstairs/Downstairs, and Gosford Park are good
     examples. Social contracts of how a hierarcy behaves. Those upstairs have
     rules to abide by just as those downstairs.

**** At Home
     The variations and peculiarities that Bill Bryson highlights, integrated
     into the Sims.

**** Guild Politics
     Similar to Institution Play. Think Elder Scrolls, and Discworld's Night
     Watch and Wizards. Wizards have rules on how they can assassinate others and
     climb the ranks, Night watch covers the behaviour of the police, and who
     supports whom.

     Also of note: The Night Watch scene of the assassination of Lord Winder.
     Birds eye view of supporters and opposition, with intended steering of
     parties.

     Elder Scroll's Guilds don't particularly get you to do anything. Tithes,
     preferred / prohibited / obligated behaviours etc. See Graeber for the cycle
     of debt that African trader institutions worked within.

**** Monetary - Warfare - Slavery complex
**** Post Invasion Occupation
     Star Trek DS-9. Subjugated populations.

**** Debt
     ie : David Graeber, Debt.
**** Daily Life
     ie: Bill Bryson, Home.

**** Civil Institutions
     ie: Terry Pratchett: The Night Watch, Religion, Wizards, The Post
     Office/Clacks/Bank/Tax Also African Tribes/Max Gluckman/Elias


*** Accidents in Real Life                                                      :accidents:
    The accidents of life. Tripping on the stairs, getting hit by a car, being
    ill. Stubbing your toe, not getting enough sleep. The thousand and one ways
    in which mood and behaviour is shifted tiny amounts by unrelated elements.

    Games do not typically include concepts of accidents. Tripping, falling,
    hitting yourself accidentally. Swallowing food badly. We often fail at being
    human, or will accidentally break. Such events are what add uncertainty and
    stress to our lives. Related: Douglas Adams pseudo fractures.

** Prototype Ideas                                                              :prototype:
*** Social Roguelike
    [[file:research/socialRoguelike][Social Roguelike Notes]]
    [[file:notes/research/socialRoguelike::*The%20Social%20Roguelike][The Social Roguelike]]

    Binding of Isaac / Dungeon of the endless influence,

*** Gormenghast Sim

    Maze of rooms generator with rituals and tradition to match. Cif overlay of
    individuals with power plays

*** Kraken Wakes

    Narrative focused apocalypse sim by John Wyndham.

*** Veil of ignorance / Red Mars spaceship society generator

    Galactica / Red Mars / Foundation inspired repeated crisis point and shift to
    generate a society.

*** Sol System

    Possibly merge with the above, but Horus Heresy style ship to ship combat and
    planet invasion House on haunted hill style reversal of allegiances.

*** Thud

    As close a translation as i can manage of the discworld game.

*** Walking Sim

    Something peaceful

*** Titan

    Dynamic LOD based game of scales, titans walking around with villages on top.
    Zelda like story would work well here.

*** Obselete

**** People/Ant Farm

     Similar to the sims, but where you have no control apart from given them
     general AI behaviours.

**** AI Hotel

     Playing as the AI hotel from Altered Carbon

**** City Gen

     General attempt to make a city generator that can do blocks and english
     organic growth styles. Possibly incorporate churches in to.

**** Fencing

     Transistor inspired turned based fluidic movement of foils, sabres, and
     epee's. Possibly used as the combat for the social roguelike.

**** Unnamed Horror

     Ghost's Hinzerhaus inspired soldier management.

**** American Psycho Sim

     The social power plays of Patrick Bateman. Meeting cards, lunches at
     restaurants, dynamic conversation, With a bit of going postal thrown in to.

**** Boarding School Power Plays

     Similar to above, possibly related to unnamed horror.

**** Commander Keen Copy

     Like the class, and RORC

**** Risk of Rain Copy (RORC)

     Narrative-lite, focus on generation of levels and shooting and wotnot

**** DOW 2 / Last Stand Copy

     Arena based semi rts/rpg class based play.
*** General Ideas to Sort


    the court politics of discworld's night watch, of the west wing and house of
    cards, combined with the societal change due to decisions that result in a
    red mars like society builder. If CiF and Praxis represent a
    computationalised model of charismatic power, then it could be combined with
    simplistic rule systems for the legal-rational and moral sides of power.

    Conflict would arise from individuals assessments of how best to use
    resources, what rules to enforce etc, and changes would be brought about by
    making use of the three forms of power to get votes. Thus: computational
    republic.

    There are two sides to this plan. One the one hand is the individual
    interactions that realise power, and on the other is the manifestations of
    that power into societal structures. Games like Prom Week, Wolf Among us, and
    Mass Effect are closer aligned with the former. You don't really need to
    strategise about keeping people under your thumb, or the capabilities of an
    individual you are going to blackmail.

    Linked with this is the emphasis on *time*. in that time needs to progress,
    slowly but steadily, as you manipulate. This is different from there being a
    timer on things. The closest I can think of that gets to this is dead rising,
    or majora's mask. The repeated pattern of days lets you plan things out, but
    in those games only physically.

    If you can daily schedules, then you can plan other actions, such as social
    actions. Set in motion slow mentions of things, train individuals to respond
    to particular cues. (in this way i'm getting towards hannibal style
    gameplay).

    So: Interpersonal Power interactions situated in cyclical time. Charismatic,
    legal-rational, economic, and moralistic among others, as the basis for
    manipulating the institutional structures to get what you want. Imperfect and
    changing information is a must, as is the need for misunderstandings of
    authority.

    FTL crossed with under the dome, difficulties that make you rely on people
    you can't trust, forming alliances for as long as you need.

*** Rimworld thoughts
    Rimworld, along with Prison architect, have a level of graphical interface
    quit distinct from Dwarf Fortress, URR, the Sims, Versu, and Prom Week. It
    defines a (relatively) small set of physical/viewable information, plus plain
    textual descriptions for non-visually perceivable information. There is a
    defined technical model of physical changes to the world, that characters
    respond to and and interfere with, manipulating the world around them. They
    also have perceptions of the non-visually represented aspects of the world,
    and social concepts.

    (Modal Opportunities: Similar to Sims Smart Objects) (Galactica related: A
    system where you have a simulation running, that searches somewhat randomly
    thought the state space for N number of turns, selects the most interesting,
    and then presents options to the player, those decisions used to dramatically
    influence the simulation, step by step society evolution, creating
    institutions and patterns of behaviour)

    (Sort of Ridcully/Science of Discworld-like: "I only stepped away for dinner,
    the little buggers went all religious, imprisoned the unbelievers, had a
    civil war and now have a memorial every year)

    (Rule systems as layered semiotically? Iconic, Referential, Symbolic?
    (Communicative as a separate category for simulation coherence?))

    Symbolics with different types, consuming tags, rejecting others.

    So:

    Physical World (Searlian Brute Facts) -> Visual Representations (Colour,
    Shape etc) -> Textual Representation (Temperature, Sound, Texture,
    Characteristics, Causal Modal Opportunities from the Technical Model of the
    world)

    Phyiscal World(V+T) -> Causal Technical Model of the World (Brute Rules) ->
    Individuals (Collections of Data)

    Individuals -> Strategy for interaction with the Technical Model (Physical
    Requirements: Eat, Sleep, Temperature) -> Strategies for causal improvement
    of the Environment (Upgrade items, increase efficiency / output, -> Rules for
    interpretation of the technical model into Semiotic/Institutional Facts
    (Monadic Lifting functions of Brute -> Institutional) -> Rules for Pure
    Symbolic rules (Institutional -> Institutional) -> Rules for Symbolic ->
    Brute actions -> Rules for action on other rules (Permissions, Weightings,
    Condition/Consequence modification) -> Known (Brute/Institutional) Facts ->
    Social Influence

    Social Influence -> bleed through of rules from others?


    ----

** Social Norm Contrasts and Patterns                                           :norms:

*** Red Mars/2312 - The Expanse
    Both are examples of a colonised solar system. Differing amounts of
    corruption, economy, speech patterns and political structure.

*** Galactica - Voyager - Gateway
    Both are examples of principal-led ships compared with less-principled
    counterparts. They have the same structure, but vastly different ethics.
    Gateway similarly models

*** Night Watch - The Cable Street Particulars

*** Social XCom - Forever War - Generation Kill
    Tracking the social aspects of being a soldier. Fatigue, Squad dynamics,
    feuds, leave, relationships.

*** The progression of the doctor
    The way the doctor treats patients, working to getting turned off when people
    leave.

** Games Prototypes                                                             :design:
*** Social Roguelike
    [[file:research/socialRoguelike][Social Roguelike Notes]]


    Binding of Isaac / Dungeon of the endless influence,

*** Gormenghast Sim

    Maze of rooms generator with rituals and tradition to match. Cif overlay of
    individuals with power plays

*** Kraken Wakes

    Narrative focused apocalypse sim by John Wyndham.

*** Veil of ignorance / Red Mars spaceship society generator

    Galactica / Red Mars / Foundation inspired repeated crisis point and shift to
    generate a society.

*** Sol System

    Possibly merge with the above, but Horus Heresy style ship to ship combat and
    planet invasion House on haunted hill style reversal of allegiances.

*** Thud

    As close a translation as i can manage of the discworld game.

*** Walking Sim

    Something peaceful

*** Titan

    Dynamic LOD based game of scales, titans walking around with villages on top.
    Zelda like story would work well here.

*** Obselete

**** People/Ant Farm

     Similar to the sims, but where you have no control apart from given them
     general AI behaviours.

**** AI Hotel

     Playing as the AI hotel from Altered Carbon

**** City Gen

     General attempt to make a city generator that can do blocks and english
     organic growth styles. Possibly incorporate churches in to.

**** Fencing

     Transistor inspired turned based fluidic movement of foils, sabres, and
     epee's. Possibly used as the combat for the social roguelike.

**** Unnamed Horror

     Ghost's Hinzerhaus inspired soldier management.

**** American Psycho Sim

     The social power plays of Patrick Bateman. Meeting cards, lunches at
     restaurants, dynamic conversation, With a bit of going postal thrown in to.

**** Boarding School Power Plays

     Similar to above, possibly related to unnamed horror.

**** Commander Keen Copy

     Like the class, and RORC

**** Risk of Rain Copy (RORC)

     Narrative-lite, focus on generation of levels and shooting and wotnot

**** DOW 2 / Last Stand Copy

     Arena based semi rts/rpg class based play.
*** General Ideas to Sort


    the court politics of discworld's night watch, of the west wing and house of
    cards, combined with the societal change due to decisions that result in a
    red mars like society builder. If CiF and Praxis represent a
    computationalised model of charismatic power, then it could be combined with
    simplistic rule systems for the legal-rational and moral sides of power.

    Conflict would arise from individuals assessments of how best to use
    resources, what rules to enforce etc, and changes would be brought about by
    making use of the three forms of power to get votes. Thus: computational
    republic.

    There are two sides to this plan. One the one hand is the individual
    interactions that realise power, and on the other is the manifestations of
    that power into societal structures. Games like Prom Week, Wolf Among us, and
    Mass Effect are closer aligned with the former. You don't really need to
    strategise about keeping people under your thumb, or the capabilities of an
    individual you are going to blackmail.

    Linked with this is the emphasis on *time*. in that time needs to progress,
    slowly but steadily, as you manipulate. This is different from there being a
    timer on things. The closest I can think of that gets to this is dead rising,
    or majora's mask. The repeated pattern of days lets you plan things out, but
    in those games only physically.

    If you can daily schedules, then you can plan other actions, such as social
    actions. Set in motion slow mentions of things, train individuals to respond
    to particular cues. (in this way i'm getting towards hannibal style
    gameplay).

    So: Interpersonal Power interactions situated in cyclical time. Charismatic,
    legal-rational, economic, and moralistic among others, as the basis for
    manipulating the institutional structures to get what you want. Imperfect and
    changing information is a must, as is the need for misunderstandings of
    authority.

    FTL crossed with under the dome, difficulties that make you rely on people
    you can't trust, forming alliances for as long as you need.

** Procedural Society Examples                                                  :examples:society:
*** Streets
    The way streets look, and the composition of them. The width, materials, and
    buildings on the street. Police, homeless, and pedestrian presence.
    Cleanliness, sanitation, parks. Level of technology, cars, lighting. Climate,
    smog. Variation between night and day. Likeliness of terrorism and crime.
    Behaviour of police, sexual harassment, racism, class tensions. Children
    playing. Friendliness of strangers, styles of greeting, and clothing.
    Grouping of individuals. What locations are popular.
*** Newspapers
    Headlines display the values, and ordering of values, of a society.
    England/America: Different scales of scandals vs normal. Small scale spending
    scandals vs massive and accepted 'campaign contributions'. What acts of
    violence are major vs minor. Big headlines for domestic terrorism by
    outsiders, minor headlines for foreign terrorism. Scale of reporting.
    America: big deal out of small terrorist attacks while Iraq has massive
    casualties, which are barely reported by American media. The statements of
    political candidates. The rate of police abuse, and protests. Strange versus
    normal stories. 'Aliens did X' versus 'Tax rates to increase' Calls for
    violence and assassinations, admissions of wrong doing, micro vs macro
    reporting
*** Violence Escalation
    The pathways and steps in which non-compliance is escalated to eventual
    police violence. Ie: Graeber's notes on accessing a school library without a
    student id. Library staff -> School police -> State police. What is the path
    of escalation when you keep saying "No" to someone's demands.
*** Bureaucracy
    To do task X, how many committees, boards, and agencies must you contact,
    forms filled out, licenses obtained, permits applied for, fees paid, studies
    conducted Officials bribed, killed, owed,

** Rational Reconstructions                                                     :games:
*** Dungeon of the Endless                                                      :mazeGen:
    Generate a Maze, with a start point (the arriving elevator with crystal), and
    destination point (the next elevator). Take moves exploring, randomly adding
    power. Stream enemies spawned from unpowered rooms to the crystal. Then
    transport the crystal to the destination when found. Activate elevator,
    repeat.

*** Shadow of Mordor / Redshirt                                                 :individualisation:hierarchy:
    [[https://www.rockpapershotgun.com/2013/07/29/hands-on-redshirt][redshirt review]] Hierarchical Organisation, with promotions, conflicts, removal,
    alliances, and weaknessses.

    With an Entity(Org,Agents,Norms) approach, formal specification can remain,
    but change over time Two layers of Institutions. Two sides of armies, with
    their own hierarchies, but different norms, Individuals in each army both
    fight internally and externally, and have feuds etc.

*** Papers Please                                                               :bureaucracy:institution:
    Bureaucracy. Arbitrary Rules supplemented with further arbitrary rules.

*** X-Com                                                                       :system:individualisation:combat:turnBased:institution:
    Turn based movement around a map, based on sight lines. Minimal Health, DR,
    fixed damage weapons, particular additional skills. Item Equips.

*** Alien                                                                       :environment:institution:hunting:
    Movement about a map, performing tasks, avoiding/being hunted by an
    adversary.

*** Stalker                                                                     :system:hierarchy:factions:
    Rival factions fighting and raiding each other
*** Democracy                                                                   :system:rules:network:
    Support for particular high level policies
*** Dota                                                                        :system:
    Teams moving around a symmetrical map, flows of mobs, steady levelling up and
    gain of stats, items paid for by goal
*** DF / SBDF-9                                                                 :factions:institution:environment:individualisation:simulation:
    Individuals moving around a map, performing routine tasks. Growing food,
    cleaning, building.
*** Pokemon                                                                     :simulation:individualisation:system:rules:turnBased:combat:
    Turn based combat, collection, movement around a map, interactional conflict.
*** Borderlands                                                                 :system:individualisation:factions:proceduralGeneration:
    Generated weapons with individual characteristics, and also brand
    characteristics.
** Network Layers, metaphors, and the DCEL

   The dcel is a clear means of representing a 3-layer ladder of abstraction. Vertex <-> HalfEdge <-> Face
   With Voronoi, and tensor based city gen as generators. 
   
   Society is a DCEL of many layers of abstraction.
   CiF showed how to flatten the layers for interactions somewhat.
   Versu showed a different layer structure, of greater range of interactions. 

   I'm trying to get to an understanding of layer descriptions in a similar way to deep learning descriptions.
   To describe particular structures, recombine and open particular transforms of outside data into internal data.
   
   
   inputs --> (--> InputTransform --> (Selection, SelectAll, Gate, Parameterize, Compile, Delay, Store, Retrieve) -> OutputTransform) -> Actions

   This is very like reaktor. Passing signals that carry information in various ways between instruments, voices, that can include standards like MIDI.
   

   Gameplay / Generation of Aletheiometer Output. Combinations of associations.
** The Phenomenological Experience of Institutional Variation                   :phenomenology:
   A Consideration of the poverty of (videogame) representations of the
   intersection between:
   - The lived experience of an individual,
   - Institutions (and a focus, if anything, on organisations)
   - Generative Systems

**** The Lived Experience of the Individual || Phenomenology

     - Rejection of Objectivity
     - Analysis of Daily Human Behaviour can provide understanding of nature
     - Persons should explore and focused on
     - Conscious experience over traditional data.
     - Intentionality (thought:Normative Intentionality?)
     - Empty Intentions vs Intuited Objects
     - Noesis vs Noema. (real vs ideal content of intentional act)
     - Empathy and intersubjectivity
     - Lifeworld
     - Dreyfus and AI conceptions of abilities

**** Institutions
     The normative structures, the organisations that form around those norms.
     They are implicitly represented, and statically.

**** Generative Systems
     Spore, Dwarf Fortress, URR,

*** Examples
**** Models
     Fligstein. CiF, Praxis,
**** Social Simulation
     Sugarscape and everything that followed in ABM.
**** Videogames
     Prom Week, Versu, Mass Effect. Tales from the Borderlands, The Wolf Among
     Us.
*** Concepts
**** Frasca's Sims Mod
**** Paper's Please / Inverted Democracy 3
     You are reading the newspaper, and voting. Voting -> Governments -> Policies
     -> Behaviours and Actions -> News Stories
**** Society Explorations.
     The Stars my Destination, The Demolished Man. Stand On Zanzibar. Doctor Who?
***** Social Roguelikes
      Sliders, Doctor Who. Gateway. Generated small group situations, constant
      threat of death.
****** 'Go down the shops and buy an ice cream'
       Dawn of the Dead, Hot Fuzz, The World's End. Sliders.
**** Society Builders.
     Discworld, Red Mars, Galactica. Stand on Zanzibar.
***** Apocalypse Reactions
      (related to Society Builders) The Walking Dead, The Day of the Triffids and
      the Kraken Wakes.
** Questions to ask about institutions                                          :institutions:questions:
*** Descriptive Questions
    How are institutions structured? How do they change?
    Who are the people in institutions? Do they always fulfill the same roles?
    Where are institutions located? Physically? Mentally?
    When do institutions form? When do they die? When do they change?
    When are institutions 'activated' in a given situation?
    What do institutions do?
    What are individuals' relations to an institution
    What size are institutions? What does size of an institution mean?
    How do we model institutions? How do we describe their structure?
    How do we describe the interactions between institutions?
    How do similar institutions vary?

*** Predictive Questions
    How do they change when X occurs?
    Which institution of a conflict set is preferred in a given situation?

*** Explanatory Questions
    Does an institution modeled by Fligsteins structure allow for similar behaviour to real institutions?
    Why do institutions change? Why do they exist?
    How do institutions operate?
    How are institutions maintained?
    How are institutions transmitted?

*** Misc
**** What is important about our experience of institutions?
**** How can we describe institutions?
**** How can we phenomenologically operationalise institutions?
**** What are the variants and invariants of an institution?
**** How do the variants of an institution change?
**** How are those changes experienced?
**** How are the consequences of the changes experienced?
**** What language would describe these changes?
**** What are examples of the ranges of:
***** Institutions
***** Inter-Institutional Variance (religion <-> disgust)
***** How do institutions vary across time?
***** Institutional Experiences
***** Institutional Purposes
      Do all institutions have purposes?
***** Components of Institutions:
****** Values
****** Rules
****** Roles
****** Actions
****** Timescales
****** Agency
****** Locations
****** Events
****** Means of individual variation / pure symbolics
****** means of communication / semi-symbolics
****** actions / non-symbolics
**** What is the process by which an individual acts according to a multitude of institutions?
**** How do you get from social rules to actions?
**** How do you differentiate universally applicable institutions to individual/instrumental/situational institutions?
**** How do you vary an institution?
     feedback loop. resonance.
**** How are institutions formed?
     Is this the question to ask at the moment? probably not. Institutions *exist*, the creation of them is rarer.
     Possibly consider Facebook as an institution.
** The Authoring Shell and Modal Systems
*** A useful set of pieces to model a complex system:
    That uses:
    1) Static data nodes
    2) Scoped and Global Rules
       collections of rules that apply to categories of relations. [X,i] rules
       get applied to instantiations, [Y,S] rules apply to defined scopes.
       Global, local, descendents, ancestors..., things with a tag T
    3) Instantiation rules
       1 and 2 get towards describing a platonic item. IRs allow 'there are 25
       apples, with the instId of 0-25, in play in the world'. String
       instantiation and modification would fit here to.
    4) FSMs
       Enabling transition systems between states of the local world's
       instantiations
    5) Parameterised freedom

    6) Layers, Gradient Descent, Evolution,
       By Specifying layers and groups with parameterised freedom, be able to
       treat them as nodes in a network, and have them learn, die, mate...


    If you represent all of these with a level of abstraction to get them all
    similar, authoring could become alot easier.
*** A Modal editor, where a node can have the forms:

    1) A Raw Node, with variables
    2) A Node where Children are alternatives. Array/Set/Queue/Stack behaviour
    3) A Node where variables are instantiations.
       Ie: parent's are prototypes or components, and children are existing
       instantiations. Instantiations can be existentially exclusive of a set of
       options, mututally exclusive, complementary, inclusive, indexed.
    4) A Node as a rule, where parents are conditions, children are actions, and the node body holds transforms of bound variables
       Where nodes are the the fluents being tested and manipulated in
       conditions, and actions. Rules would be instantiable themselves, able to
       act in particular scopes, applicable only when attached to an instance
       able to test for instances, and select them by index
    5) A Node as a FSM, where the fsm has states, and conditions as modal children. (An FSM would also be instantiable)
       Instiantiable, and then testable.`
    6) A Node that collects a group of rules into a category, a variation on (2)
    7) A Node that has a defined substructure
       So a prototypical copy of another segment of the shell?
    8) A Node where nodes have modification controlled
       Either permanently, modifiably, depthly or shallowly. Down to specified
       options, or freely.
    9) A Node where change can view positively or negatively, and action taken accordingly?
       Where there is a defined error assessment?


    What does this result in as a semantics and structures for node, that will
    cover everything else?
**** Structure:
     The node would need a unique id, and a dictionary of modes that it fulfills.
     Categories being: Variable-value edges Value-node edges Parent-Child Edges
     Condition-Rule-Action Edges Instantiation-Exclusion-Alternative edges
     FSM-Event-State edges Local-Rule edges Instantiation-Rule edges


*** On Learning Haskell, Monads and Parsers in the right way
    While haskell is great, it is the wrong language to use to learn how to write
    haskell. Javascript is the *right* way to learn haskell, then you add types.

    Although Monads are a type theory concept, they are a *functional* construct.
    By which I mean that although type theory describes and enables monads, they
    only *require* the ability to do first class functional programming. They are
    used as a means to solve a problem, namely, *code repetition*.

    Parsers are the prime area to learn and use monads, and not in haskell. In
    Haskell you get bogged down in the type system. In javascript, you have to
    track it in your head, but also learn the underlying patterns.

    Namely, the ability to pass a function in, and possibly use it, possibly do
    something else, but still returning a result that can be used in a similarly
    chained function. Text -> (Maybe Parse).

    ... Here, follow the example out. expanding out what monads save in terms of
    if tests and hard coding Show why 'return' is better seen as 'lift', to take
    a value, and return the value the input wrapping function can use.

    Parsing shows how to chain functions together. Also, Parsec shouldn't be
    imported unqualified when learning. Everything should . Parsec.<|> etc

*** Red-black heuristic ranking
    Apply a Beachline style red-black tree to ranking/weighting. leaves will form
    a (possibly bin'd) ordering of weights. Don't bother giving the value itself,
    just its relation to neighbours. Red-black keeps it balanced so you don't
    need too many pairings to determine a rank

** An authoring methodology                                                     :methodology:
   BOD would have primitives described, then repeatedly refine each level.
   Instead, have questions, work out from the middle to define inputs and
   outputs.

   Have a hypergraph of institutions of the form: inputs -> Institutional Spec ->
   outputs

   Described by repeatedly asking questions to refine the specification:

   What is the name of the Institutions? What are the core values of {name}? What
   are some Categories / Roles in {name} ? What is the role structure for {name}
   ? What are the performable actions ? What are the goals? What are the jobs /
   permissions ? What can be delegated? What can be parallelised? What can be
   split across sessions? What are the habits? What are the sanctions? What is
   the weighting of values / roles/ categories / goals / jobs /sanctions ? ( use
   heuristic weighting ) What are the physical laws? (unmodifiable rules of
   physicality) What are the communicative acts? What are the regulative laws?
   What are the normative expectations? What are the monitoring / sanctioning /
   disrupting activities? What are the artifacts? What are the artifact
   specification rules? What are the object standards? What are the symbolic
   variations of artifacts? What are the artifacts functional uses? What is the
   IGU in {name}? Person / Role / Group / Institution -> specify Who are the
   incumbents of the institution? Who are the challengers of the institution? For
   each activity, what is its object, what are the tools usable in the activity?
   What community of individuals are involved with the task, what is the division
   of labour? And What are the additional rules beyond that? What is the
   time/space specification of the activities / jobs/ roles ...?


   Carriers: Symbolic Systems, relational systems, activities, artifacts (for
   scott) Pillars: Regulative, Normative, Cultural Cognitive With Institutional
   Entrepreneurs
** SIA                                                                          :writing:socioInstitutional:
*** Socio-Institutional Actions.
**** Introduction:
     If we characterise the scope of systems surrounding an individual in the way of Bronfenbrenner:
     a) Individual
     b) Microsystem
     c) Meso System
     d) ExoSystem
     e) MacroSystem

     Then I am proposing a system that, leveraging the interpersonal
     capabilities of CiF and Praxis, enables actions on a dynamic higher
     system. Actions that, due to the authorizations and culture of a
     society, have a greater impact that on just the relationship with the
     other person, while that interpersonal aspect remains a factor.

     This has a broad structure of:
     Individual -> Speech Acts -> Social Fields Changes -> Individual Behaviour Changes

     A Core component of this is Gidden's discussion of routinization,
     regularization, and time.
**** Key Concepts:
***** Power and Authority
***** The Cyclical nature of time
***** Indoctrination and Decision
*** Core Research
**** Bourdieu
     Fields, Conception of Symbolic Power, discusses in relation to speech acts
**** Giddens
     Duality of Social Existence, Time
**** Castelfranchi
     Types of Social Actions
**** Fligstein
     Structure for Social Fields
**** Searle
     Speech Acts
**** Dimaggio
     Institutional Structures
**** Brandom
     Considering Speech acts as pragmatically sufficient metavocabularies to bootstrap social field manipulations to.
**** Greene
     Real World Examples

*** Examples:
**** First Tier
     Society Generation.
***** Gormenghast
      Steerpike and Lecter. Sociopathic exploration of norm violation.
****** House of Cards
****** Hannibal.

***** Stand on Zanzibar
****** Discworld
******* Guards
******* Moist Von Lipwig
******* The Truth
****** Red Mars
****** The Dispossessed
****** Horus Heresy
***** The Trial
      Ritual.
****** Gormenghast.
***** On Politics
      Politics
****** 48 Laws of Power
****** The Stars my Destination
****** Dune
***** Galactica
      [[http://themonkeycage.org/2013/06/13/the-political-science-of-battlestar-galactica/][polisci of galactica]]
****** Torn
       Adama having to dress down Tigh and Starbuck. The idea of having
       a command,

****** Crossroads
       The trial of Gaius Baltar. His covering of his accent, the
       decisions of what to do with people who collaborated during the
       occupation.

****** 33
       Destruction of the olympic carrier. Linking to suicide bombers,
       muckers, and imperfect information.

****** Six Degrees of Separation
       baltar and his response to different six's

****** Flesh and Bone
       interrogation, psychologial warfare, ethical treatment of
       prisoners. what defines someone who is protected under the law.

****** Scattered
       Power vacuums when adama is shot

****** Blood on the Scales
       Gaeta and Zarek's mutiny.

****** Pegasus
       everything about cain

****** Dirty Hands
       tyrol and the class based society that was arising in galactica.
       responses to that,

       A Raptor piloted by Racetrack experiences engine failure soon after launch and collides with Colonial One, nearly killing President Roslin and her aide Tory Foster. An investigation reveals that a recent batch of Tylium fuel contains impurities and Roslin calls upon Xeno Fenner, the director of the fleet's refinery ship, for answers. When Fenner meets Roslin and Admiral Adama, he is sarcastic and uncooperative, calling the situation a "glitch." He admits that it may be his workers' way of getting some attention after repeatedly being ignored regarding the squalid and dangerous conditions they face every day without a single break. Roslin doesn't sympathize, explaining that fuel production is critical and must be maintained. When Fenner quotes text from an underground book by Gaius Baltar, "If you hear the people, you never have to fear the people" and threatens a few more "glitches," Roslin has him arrested.

       Adama is stunned by her action and inquires about the book. Visibly angered, Roslin whispers that Gaius Baltar's attorney has passed a manuscript around the fleet written by Baltar entitled, My Triumphs, My Mistakes. It deals with class struggle, and she says she is thinking about having a "good ol' fashioned book burning." Adama contacts Chief Tyrol, informs him of Fenner's arrest, and orders him to go to the refinery ship to take charge of the situation. Tyrol's wife Cally admits to Tyrol that she has read Baltar's book, which discusses the unfair labor differences between the people of the Twelve Colonies. She questions why the people from the poorer colonies like Gemenon, Sagittaron, and Aerelon are forced to work in harsh blue-collar jobs while the more elite and educated colonials from places like Caprica, Tauron and Virgon get to keep their plush white-collar jobs.

       Roslin goes to Baltar's cell and demands that he hand over the pages from his book. She lies, saying it was intercepted before anyone could read it, and orders the guards to tear the room apart. She concludes with a partial strip search of Baltar during which Six appears in Baltar's mind and tells him to protect his dignity. Six slides her hand into his open pants, but Baltar stops her. He withdraws the pages of his book and surrenders them to Roslin, who sneers that she's been "dying to see how it ends" and mocks his attempt to appear as a "man of the people."

       Meanwhile, Tyrol arrives on the refinery ship and takes a tour of the facility, led by a foreman named Cavett. He witnesses the somber glances from the tired, grime-covered workers who are both men and women ranging in age from the elderly to mere children. Tyrol goes to the massive Tylium storage room where a single, dwindling pile of ore remains. Cavett says they're lucky if the supply lasts long enough to get them out of the system. Next, Tyrol goes to the main conveyor line where the work has completely shut down. Tyrol asks for a reason for the shutdown, but the workers remain silently defiant until a young boy named Milo speaks up and says the pressure seals are broken. Tyrol notices that the seals are completely missing and have been removed by the workers in protest of Fenner's arrest.

       Tyrol returns to Galactica and informs Roslin and Adama of the missing seals and explains the workers are buying time for their pleas to be heard. He adds that some of the workers have been doing the same grueling job since the attack on the Colonies and requests Roslin accede to some of their demands for a break. Roslin objects, however, saying it is just as difficult to work aboard the algae processing, recycling and waste handling ships. She sees their work stoppage as extortion and demands the names of the organizers. Tyrol hesitantly surrenders Cavett's name.

       Cavett is arrested and joins Fenner in an adjacent cell. When Tyrol visits them, he finds that Cavett is having a breakdown and injuring himself. Fenner reminds Tyrol that Cavett was tortured by the Cylons back on New Caprica, and confinement is causing him post-traumatic stress. Tyrol tells Fenner there is no time for games and demands Cavett reveal where the seals have been hidden. Fenner hesitates, then angrily reveals that they were hidden in the air vents. Tyrol then has the men released and work is resumed aboard the refinery ship.

       Later, Tyrol goes to Colonial One to talk to Roslin. He explains parents are passing down their skills to their children, and they are forever stuck doing the same job in the next generation. He says they should be given a chance to choose their future. Roslin understands the problem and tells him to make a list of colonists with relevant skills to supplement those aboard the labor ships. Next, Tyrol deals with a protesting young man named Danny Noon who was pulled from Dogsville. Noon had worked a summer job on a farm to earn money for college, but agriculture is not his career choice. Tyrol tells him the job is only temporary and has the angry youth escorted away.

       Tyrol then finds a copy of Baltar's book and opens to a page entitled The Emerging Aristocracy and the Emerging Underclass. Tyrol goes to Baltar's cell and refers to the book. Baltar learns the truth that the book has been leaked and asks Tyrol what he thinks about it. Tyrol responds that he thinks it's a load of crap, disbelieving Baltar's claim that he grew up on a farm on Aerelon - especially since Baltar's accent is different from other Aerelons he knows. Baltar, speaking in an Aerelon accent, states that he learned to mimic the Caprican accent to help hide the fact he was from Aerelon, a poor farming world known as the "food basket for the twelve worlds." Baltar explains the purpose of the book was to show that class-strife has continued to follow the fleet well after the Cylon attack, and they will find that those in the aristocracy will continue to hold onto their power.

       Tyrol returns to the refinery ship where work halts when the conveyor system becomes jammed. Fenner says the belt must be repaired or else a back-up will occur which could cause the "hot" Tylium further down the line to go critical and cause a chain reaction that will take out the whole ship. Without stopping the slipping belt, Tyrol finds the problem is a jammed drive mechanism, but he is unable to reach it. Danny Noon frees the jam but injures his arm in the processes. Fed up, Tyrol walks to main control levers and shuts down the entire factory. He declares the workers to be on strike.

       Aboard Galactica, Starbuck finds her flight mission delayed by hangar workers who are playing cards on a Raptor wing. She demands they get back to work where the senior deckhand, Pollux, tells her that they are only servicing vital missions per orders from Chief Tyrol. Tyrol is immediately arrested. Admiral Adama angrily confronts Tyrol in the brig and orders him to call off the work stoppage, but Tyrol refuses. Adama says he will not tolerate the disobedience of orders, calling it mutiny and reminding him that mutineers are shot, but Tyrol stays put. Adama grabs the phone and orders the arrest of Cally. Alarmed, Tyrol asks what he's doing. To get his point across, Adama says he will execute Cally as mutineer and continue with the rebellious deck crew if he has to. He admits it's something he doesn't want to do, but will to maintain the survival of the fleet. Tyrol relents and calls off the strike. Adama tells him to report to Roslin who wishes to discuss the labor situation.

       Tyrol meets with Roslin on Colonial One and they talk about the cultural vocations that some colonists are locked into by birth. Tyrol suggests setting up a training program to allow the colonists to learn more than one trade, and a work rotation started so that those in dangerous and dirty jobs get an equal chance to work in more comfortable and safer positions in the fleet. He adds that he'd like to see some of Colonial One's crew get their hands dirty for a change. Roslin agrees, but tells Tyrol to consider the reestablishment of the worker's union that he led back on New Caprica as it will ensure stability within the fleet.

       Later, Tyrol calls his deck crew to muster when Starbuck arrives and demands to know why Seelix is 20 minutes late for her first day of pilot training. Seelix is confused and Tyrol apologizes, explaining that Seelix has been promoted to Ensign and assigned to flight training - something she was turned down for earlier because her job as an avionics specialist was too important. Tyrol pins the Ensign rank on her collar and salutes her while Starbuck tells the newly recruited nugget to double-time it to debriefing. Seelix rushes off with an excited smile on her face.



***** House of Cards

      Frank helped ensure the election of President Garrett Walker, who
      promised to appoint Frank as Secretary of State.

      However, before Walker is sworn in, Chief of Staff Linda Vasquez
      announces that Walker will not honor the agreement and will instead
      nominate Senator Michael Kern.

      Linda tells Frank that they want him to continue helping their
      administration from within the House of Representatives, starting with
      working on an education reform bill with Representative Donald Blythe.

      Furious at Walker's betrayal, Frank and his wife Claire, an
      environmental activist, make a pact to destroy Walker, starting with
      Kern.

      Frank starts seeking out pawns in his war against Walker.

      When the troubled Representative Peter Russo is arrested for drunk
      driving, Frank offers him a reprieve in exchange for his loyalty,
      covering up the incident by bribing the commissioner with funds for
      his political ambitions.

      Frank also encounters Zoe Barnes, a young political reporter for the
      Washington Herald newspaper.

      The two come to an agreement where Frank will give Zoe inside
      information that will further Zoe's own stagnating career, and giving
      Frank a patsy to serve incriminating information to destroy his
      opponents.

      He starts by leaking a copy of the first draft of Donald's education
      bill that proposes massive increases in government control of
      education, promptly causing a scandal one day after the inauguration.

      In the aftermath of the leak of the education bill draft, Frank
      manages to secure full control of the legislative course from the
      president and promptly removes Donald, who graciously takes the fall
      for the controversy in the press for Frank's sake.

      Claire fires over half of her NGO's staff to secure the necessary
      level of funds for her own plans for the organization.

      With Zoe's help, Frank plants a story that loosely ties Kern to an
      anti-Israel editorial that ran in the college newspaper he edited.

      Kern gravely mishandles the resulting media questions, throwing doubt
      on his candidacy.

      Frank then forces Russo to travel to meet a conspiracy junkie who
      used to be on the college newspaper and encourages him to state that
      Kern wrote the article himself, and the resulting firestorm of
      controversy destroys Kern's chances.

      Frank then tosses Catherine Durant's name to Zoe as the likely
      replacement before reinforcing her credentials to Vasquez.



      Frank is forced to return to his hometown of Gaffney, South Carolina
      in the midst of negotiating the education bill's reforms to the
      teachers' unions when his main rival stirs trouble.

      A young woman has been killed in a car accident after texting while
      driving, apparently distracted by a peach water tower that Frank has
      advocated to keep standing.

      His rival encourages the parents to sue, forcing Frank into a
      difficult negotiation.



      Frank resorts to intricate political string-pulling when House Speaker
      Bob Birch refuses to support putting the education bill through the
      house with its controversial amendments.

      As a result, Frank organizes a coup that forces the majority leader
      to step down in place of one that Frank wants, in order to put
      pressure on Birch to cooperate and keep his Speakership.

      Frank forces Russo to allow a shipyard in his district to close to
      keep a military base in his new majority leader Terry Womack's
      district open, ensuring his support for a coup if necessary.

      Tom is exasperated at Zoe's rebelliousness but the Herald's publisher
      overrules him.

      Tom offers Zoe the post of White House correspondent but she has
      doubts and is ultimately drawn closer to Frank.

      Remy re-tables an offer to the CWI but Claire refuses it at Frank's
      urging.

      Claire meets with photographer Adam Galloway, a former lover who
      tries to rekindle their relationship.


      The changes to the education bill lead to a frosty meeting between
      Frank and the head lobbyist for the teachers' union, who proves
      himself a dangerous adversary.

      The fallout from being forced to close the shipyard along with
      thousands of jobs for his constituents by Frank, along with the
      departure of Christina, sends Peter Russo into depression.

      Frank and Claire foil the lobbyist's attempt to disrupt their
      fundraising plans.

      In retaliation, the lobbyist calls for a nationwide strike.



      As the teachers' strike escalates and the president quickly loses
      support due to it extending over three weeks, Frank is pressured to
      drop the bill entirely.

      He now has to achieve total victory to get the bill through and end
      the strike on his terms.

      A brick through Frank's window allows him to target the architect of
      the strike, lobbyist Marty Spinella, and the pair go head-to-head on
      TV in a confrontation that ends up embarrassing Frank further, and
      Frank is barely able to keep the president from forcing him to cut
      the bill.

      A cleaned-up Russo confides his intention to run for Governor of
      Pennsylvania; Frank sets the wheels in motion by enlisting Claire's
      help to draft a mutually beneficial environmental bill.

      A night spent scanning the police frequencies pays off when a local
      tragedy deals Frank a winning card, forcing Spinella to confront him.

      He goads Spinella into a rage, revealing he organized the brick
      incident himself, resulting in Spinella assaulting him when no one
      else is in the room.

      This gives Frank the leverage he needs: end the strike now, or Frank
      will press charges and send Spinella to jail.



      President Walker finally signs the education bill into law, earning
      Frank a major victory by affording him great influence and favor with
      Walker.

      Vice President Matthews is feeling sidelined and expresses discontent
      with Walker.

      Peter Russo readies himself for the governor's race ahead by
      attending AA meetings while his campaign team discusses strategies.

      Frank uses his relationship with Zoe to generate some positive spin
      on the announcement and taps Christina for the position of deputy
      campaign manager.

      Zoe recommends Janine Skorsky for a job.



      Along with Claire, Frank visits his alma mater at his military
      college, which is honoring him by naming a new library after him.

      He spends the night reminiscing and drinking with old friends,
      including one who may have been his former boyfriend, allowing a
      glimpse behind Frank's mask.

      Among the guests of the event is Remy Danton, who advises that
      SanCorp has concerns about Peter Russo running for governor.

      In the meantime, Peter returns to Philadelphia and visits his mother.

      He then tries to convince former shipyard employees to support him;
      an angry meeting with them reveals an uphill struggle ahead but he
      remains undeterred.



      Peter goes on a bus tour around Pennsylvania with Vice-President
      Matthews.

      Matthews initially torpedoes Peter's campaign but is eventually won
      over.

      Frank tries to whip support in Congress for the Delaware River bill.

      He needs Claire's help, but she is disappointed about how little help
      she is receiving for her own projects and goes behind Frank's back to
      ensure that the bill fails.

      Zoe decides her relationship with Frank should be purely professional
      but changes her mind when he stonewalls her.



      Frank is upset with Claire regarding the bill's failure, and Claire
      storms out.

      She approaches Zoe and informs her that the affair with her husband
      is not a secret.

      She then goes away to meet her own lover Adam, not telling Frank
      where she is.

      Frank is losing control of Russo and Zoe, who are turning on Frank
      for their own ends.

      He needs to keep Russo in line and also find out his wife's
      whereabouts.

      Russo slips in his sobriety and gets drunk with Rachel (the
      prostitute he was initially caught with in the premiere), falling
      into the trap Frank is setting for him.

      A drunk Russo makes a mess of a phone interview which Frank plans to
      use to crush his chances for governor and make his next move.



      After Russo's disastrous phone interview, Frank convinces Matthews to
      run for Governor in Russo's place.

      Vasquez asks Frank forthrightly if he is ambitious to be Vice
      President himself and, after some reticence, he admits that this was
      his plan all along and reaches out to her as an ally.

      Meanwhile, after attempting to reconnect with his children, a
      still-inebriated Russo hands himself in to the police.

      Frank picks him up from jail and, recognizing him to be too much of a
      liability, proceeds to kill Russo through Carbon monoxide poisoning,
      making it look like a suicide.



      With Matthews about to win the governor's race, Frank is helping the
      White House vet VP candidates.

      The President suddenly sends him to evaluate Raymond Tusk, a
      multi-billionaire who lives modestly in St.

      Louis.

      But after staying with him, Frank eventually discovers deeper
      connections between Tusk and the President and learns that he is the
      one being vetted.

      Tusk offers to support him in return for an unspecified favor  but
      Frank refuses.

      Meanwhile Janine and Zoe's persistence starts to pay off as they
      begin to see through the conspiracy regarding Frank and Russo.


      Frank meets again with Tusk and reaches an accommodation; the
      President offers him the VP post and he accepts.

      Claire consults a doctor about possible fertility treatments.

      She also fires Gillian, who then sues her for wrongful termination
      and refuses any settlement.

      Meanwhile, Zoe, Lucas, and Janine learn Rachel's identity and begin
      to put together more of the pieces of Frank's plots.




***** Stanislaw Lem
****** Trurl and Klapaucius

       Trurl and Klapaucius are brilliant (robotic) engineers, called
       "constructors" (because they can construct practically anything at
       will), capable of almost God-like exploits.

       For instance, on one occasion Trurl creates an entity capable of
       extracting accurate information from the random motion of gas
       particles, which he calls a "Demon of the Second Kind".

       He describes the "Demon of the First Kind" as a Maxwell's demon.

       On another, the two constructors re-arrange stars near their home
       planet in order to advertise.

       The duo are best friends and rivals.

       When they are not busy constructing revolutionary mechanisms at home,
       they travel the universe, aiding those in need.

       As the characters are firmly established as good and righteous, they
       take no shame in accepting handsome rewards for their services.

       If rewards were promised and not delivered, the constructors may even
       severely punish those who deceived them.

****** The world and its inhabitants

       The universe of The Cyberiad is pseudo-Medieval.

       There are kingdoms, knights, princesses, and even dragons in
       abundance.

       Robots are usually anthropomorphic, to the point of being divided
       into sexes.

       Love and marriage are possible.

       Physical and mental disabilities, old age and death, particularly in
       case of accidents or murder, are also common, though mechanical
       language is used to describe them.

       Death is theoretically avoidable (by means of repair), and sometimes
       even reversible.



       In fact, the teacher of Trurl and Klapaucius, Master Cerebron, is
       deceased, but can still be reanimated at his tomb.

       The level of technology of the vast majority of inhabitants is
       pseudo-Medieval also, with swords, robotic steeds, and gallows
       widespread.

       With this co-exist space travel, extremely advanced technology made
       by the Constructors and futuristic weapons and devices used or
       mentioned on occasion.

       There even exists a civilization that has achieved the "HPLD" 
       Highest Possible Level of Development.

****** Romantic stories

       Some stories are basically self-conscious parodies of romantic novels
       about knights, with more profound issues of psychology and social
       dynamics under a cartoonish and swashbuckling facade.

       A typical example is the fairy tale O krlewiczu Ferrycym i krlewnie
       Krystali) ("Prince Ferrix and the Princess Crystal").

       A princely (robotic) knight falls in love with a beautiful (robotic)
       princess.

       Unfortunately, the princess is somewhat eccentric, and is captivated
       by stories of an alien non-robotic, "paleface" civilization (the
       humans).

       She declares that she will only marry a "paleface".

       Therefore, the knight decides to masquerade as a paleface.

       He covers himself with mud, starting to resemble one, and then comes
       to woo her.



       Meanwhile, a real "paleface" captive arrives, given as a gift to the
       king.

       It immediately becomes obvious to the princess who is the "muddier"
       one, but the "paleface" turns out to be too squishy and overall
       disgusting.

       Not wanting to back down at the last minute, however, the princess
       declares a joust between the two suitors to select the worthier one.

       When the "paleface" charges at the robot, he splatters himself on the
       latter's metal chest, revealing the metallic body to all.

       The princess, beholding the beauty of the exposed robot (compared
       with the ugliness of the "paleface"), changes her mind.

       The knight and the princess live happily ever after.

****** Stories involving technology and the Constructors

       Most of the stories involve Trurl and Klapaucius using their
       extraordinary technological abilities to help the inhabitants of the
       medieval planets, usually involving neutralizing tyrants.

       For example:

       Trurl and Klapaucius come to a planet ruled by a king who loves
       hunting.

       He has already "conquered" all the most dangerous of predators, and
       now hires constructors (engineers) to make new, mighty robotic beasts
       for him to hunt.

       He has already executed all of the previous constructors who visited
       because they could not build beasts that would be challenging enough
       to hunt.

       When the two famous Constructors arrive, they are arrested and
       ordered to construct a worthy foe for the king within twelve days.



       The two face a dilemma: if they make something that the king will
       kill, they will be executed by the mad king.

       But if the king himself is killed, then they will be executed, for
       the next king will be pressured to show his respect for the previous.

       They solve the problem by building an animal that survives the hunt
       (involving both cyber-hounds and nuclear tipped missiles unleashed
       upon it, in the characteristic cartoonish manner) and takes the king
       hostage by, nothing less, turning into several police officers and
       presenting an order for his arrest.

       All the king's men fail to find and free the king (partially because
       in searching for the fake policemen one half of the real police force
       arrests the other half), and he is released only after the
       Constructors' numerous demands are met.



       On another occasion, Trurl and Klapaucius are captured by an
       interstellar "PHT" pirate.

       Trurl offers to build a machine capable of turning hydrogen into gold
       (something he can do manually, which he demonstrates by hand, mixing
       up protons and putting electrons around).

       However, the pirate turns out to have a PhD and cares not for the
       riches, but for knowledge (and in fact points out that gold becomes
       cheap if it is abundant).

       Trurl therefore makes a modified Maxwell's demon for him, an entity
       that looks at moving particles of gas and reads information that is,
       coincidentally, encoded in their random perturbations.

       This way, all the information in the universe becomes easily
       available.

       The demon prints out this information on a long paper tape, but
       before the pirate realizes most of the information is completely
       useless (although strictly factual) he is buried under the endless
       rolls of tape, ceasing to bother anyone.

****** Stories involving the search for happiness and ideal society

       The Highest Possible Level of Development civilization.

       A gravely injured hermit comes to Trurl's house and tells Trurl of
       Klapaucius's adventure: Klapaucius wanders across an old robot, who
       tells him that he has logically deduced the existence of a
       civilization that reached the highest possible level of development
       (hence "HPLD").

       He has inferred the existence of such a civilization by figuring that
       if there are different stages of development, there will be one that
       is the highest.

       He was then faced with a problem of identifying that one; as he
       noted, everyone claimed that theirs was the HPLD.

       Upon much research and thought, he decided that the only way to find
       it is by looking for a "wonder", i.e.  something that has no rational explanation.

       Eventually Klapaucius discovers one such wonder: a star in the shape
       of a cube, orbited by a planet also shaped like a cube with the huge
       letters HPLD written on it.

       He lands and meets its inhabitants: a group of about 100 individuals
       lying around doing nothing.

       When the HPLDs grow tired with Klapaucius's efforts to extract
       answers from them, they teleport him and his ship far into outer
       space, albeit after filling the ship with gifts.


       Seeing how he will not get anywhere this way, Klapaucius constructs a
       massive machine capable of simulating the entire universe, including a
       member of the HPLD civilization.

       Upon questioning the simulation, he is informed that over six million
       such interrogations took place in the past.

       The simulation also reveals that the civilization in question has
       long since achieved the HPLD, and thus has nothing else to strive
       for.



       When Klapaucius asks why the HPLD civilization does not continuously
       engage in helping other, less advanced civilizations, the simulation
       explains that their attempts to do so in the past have proven
       extremely counter-productive.

       For instance, having dropped some millions of wish-fulfilling devices
       on a planet, they saw it blow up in a matter of hours.

       Eventually, the HPLD representative provides Klapaucius with the
       formula for "Altruizine"  a substance that allows individuals within
       a limited area to completely share all feelings and emotions,
       including both pain and joy.

       The idea behind Altruizine is that people who feel each other's pain
       as their own should treat each other as they would themselves.


****** Altruizine.

       Klapaucius produces a large quantity of the substance and sends the
       above mentioned hermit (who is eager to help others) in human guise
       to experiment on the population of a single planet.

       Some of the results include villagers feeling the birth pains of a
       cow, depressed people being violently attacked and driven off and a
       crowd storming the house of the newlyweds to vicariously participate
       in their unaccustomed sensations.

       Eventually, the hermit is identified for a robot (because he does not
       feel the humans' pain), is thoroughly beaten and tortured, then shot
       into outer space via a cannon.

       He then lands near Trurl's house, where the story began.

       Concluding his tale, the hermit assures Trurl that his thirst for
       altruism has vanished.


****** Trurl and the construction of happy worlds.

       Trurl is not deterred by the cautionary tale of altruizine and
       decides to build a race of robots happy by design.

       His first attempt are a culture of robots who are not capable of
       being unhappy (e.g. they are happy if seriously beaten up).

       Klapaucius ridicules this.

       Next step is a collectivistic culture dedicated to common happiness.

       When Trurl and Klapaucius visit them, they are drafted by the
       Ministry of Felicity and made to smile, sing, and otherwise be happy,
       in fixed ranks (with other inhabitants).



       Trurl annihilates both failed cultures and tries to build a perfect
       society in a small box.

       The inhabitants of the box develop a religion saying that their box
       is the most perfect part of the universe and prepare to make a hole
       in it in order to bring everyone outside the Box into its perfection,
       by force if needed.

       Trurl disposes of them and decides that he needs more variety in his
       experiments and smaller scale for safety.



       He creates hundreds of miniature worlds on microscope slides (i.e. he
       has to observe them through a microscope).

       These microworlds progress rapidly, some dying out in revolutions and
       wars, and some developing as regular civilizations without any of
       them showing any intrinsic perfection or happiness.

       They do achieve inter-slide travel though, and many of these worlds
       are later destroyed by rats.



       Eventually, Trurl gets tired of all the work and builds a computer
       that will contain a programmatic clone of his mind that would do the
       research for him.

       Instead of building new worlds, the computer sets about expanding
       itself.

       When Trurl eventually forces it to stop building itself and start
       working, the clone-Trurl tells him that he has already created lots
       of sub-Trurl programs to do the work and tells him stories about
       their research (which Trurl later finds out is bogus).

       Trurl destroys the computer and temporarily stops looking for
       universal happiness.

***** Asimov/Foundation
**** Second Tier
***** Sociology:
****** Graeber
****** Bitchierri
****** Benedict
****** Martin.
       Specific Examples of the variety of culturally specific norms.
***** Psychology:
****** Forsyth
***** The soundscape
***** private life
***** Political Economy of Noise.
      On the effects of technologies on a culture.
***** By the sword.
      For linking with Social Roguelikes and Fencing.
*** Methods:
**** Machine Learning.
     Classifiers and Repeated Relearning on multiple scales of simulation.
     ***Bloom filters
     as a particular form of guaranteed classification
**** Cellular Autonoma,
**** Genetic Algorithms,
**** Rete Net Pattern matching
     making larger numbers of rules feasible, allowing generation of large sets of rules.

     Statistical support for arguments:
     wow analysis
     novel progression and change nlp
*** Resulting Games
**** Social Roguelike
     Court Politics, Fencing, Highly Formal Rituals.  Rather than combat to get
     through to the next level, you're talking your way in.
***** Gormenghast generator
      Ritual / Society Generation

***** Psychopath Simulator

**** Strategy
***** The Kraken Wakes / Day of the Triffids
***** Evacuation Management
***** Solar System Combat Simulation / Fleet Political Management
**** Surreal Walking Sim
*** Come back to later
    silly hats only.
    http://www.mpi-sws.org/~cristian/Echoes_of_power.html
    www.mpi-sws.org/~cristian/Echoes_of_power_files/echoes_of_power.pdf
    https://confluence.cornell.edu/display/llresearch/Supreme+Court+Dialogs+Corpus

    http://web.stanford.edu/~jurafsky/pubs/linguistic_change_lifecycle.pdf

    http://i.stanford.edu/~julian/pdfs/www13.pdf

    https://ed.stanford.edu/faculty/mcfarland
    https://css-center.stanford.edu/
    http://www.amazon.com/Agent_Zero-Neurocognitive-Foundations-Generative-Complexity/dp/0691158886/ref=la_B000AQ4OYM_1_1?s=books&ie=UTF8&qid=1413792447&sr=1-1
**** Discworld
***** Hogfather and Belief
      +++ Humans Have Always Ascribed Random, Seasonal, Natural Or Inexplicable
      Actions To HumanShaped Entities. Such Examples Are jack Frost, The Hogfather,
      The Tooth Fairy And Death +++
      'Oh, them. Yes, but they exist,' said Ridcully. 'Met a couple of 'em myself.'
      +++ Humans Are Not Always Wrong +++
      'All right, but I'm damn sure there's never been an Eater of Socks or God of
      Hangovers.'
      +++ But There Is No Reason Why There Should Not Be +++
      'The thing's right, you know,' said the Lecturer in Recent Runes. 'A little man
      who carries verrucas around is no more ridiculous than someone who takes away
      children's teeth for money, when you come to think about it.'
      'Yes, but what about the Eater of Socks?' said the Chair of Indefinite Studies.
      'Bursar just said he always thought something was eating his socks and, bingo,
      there it was.'

***** Eric and Writing
      It was around noon. In the jungle behind Rincewind creatures whooped and gibbered. Mosquitoes the size of humming-birds whined around his head.
      "Of course," he said, for the tenth time, "They've never really got around to inventing paper."
      The stonemason stood bake, handed the latest blunted obsidian chisel to his assistant, and gave Rincewind and expectant look.
      Rincewind stood back and examined the rock critically.
      "It's very good," he said. "I mean, it's a very good likeness. You've got his hairstyle and everything. Of course, he's not as, er, square as that normally but, yes, very good. And here's the chariot and there's the step-pyramids. Yes. Well, it looks as though they want you to go to the city with them," he said to Eric.
      "Tell them yes," said Eric firmly.
      Rincewind turned to the headman.
      "Yes," he said.
      "[Hunched-figure-in-triple-feathered-headdress-over-three-dots]?"
      Rincewind sighed. Without saying a word, the stonemason put a fresh stone chisel into his unresisting fingers and manhandled a new slab of granite into position.
      One of the problems of being a Tezuman, apart from having a god like Quezovercoatl, is that if you unexpectedly need to order an extra pint of milk tomorrow you should have started writing the note last month. Tezumen are the only people who beat themselves to death with their own suicide notes.

***** Eric and wossnames
      Rincewind felt something claw its way up his back and onto his shoulder, where a voice like a sheet of metal being torn in half said, "That's better. Very wossname, comfy. If you try and knock me off, demon, you can wossname your ear goodbye. What a turn up for the scrolls, eh? They seemed to be expecting him."
      "Why do you keep saying wossname?" said Rincewind.
      "Limited wossname. Doodah. Thingy. You know. It's got words in it," said the parrot.
      "Dictionary?" said Rincewind. They passengers in the other chariots had got out and were also groveling to Eric, who was beaming like an idiot.
      The parrot considered this.

***** Eric and Tribe
      Rincewind stared at the blocks nearest the statue. It had taken the
      Tezumen two storeys, twenty years and ten thousand tons of granite to
      explain what they intended to do to the Ruler of the World, but the
      result was, well, graphic. He would be left in no doubt that they were
      annoyed. He might even go so far as to deduce that they were quite
      vexed.  "But why do they give him all these jewels to start with?" he
      said, pointing.  "Well, he is the Ruler," said da Quirm. "He's
      entitled to some respect, I suppose."  Rincewind nodded. There was a
      sort of justice in it. If you were a tribe who lived in a swamp in the
      middle of a damp forest, didn't have any metal, had been saddled with
      a god like Quezovercoatl, and then found someone who said he was in
      charge of the whole affair, you probably would want to spend some time
      explaining to him how incredibly disappointed in him you were. The
      Tezumen had never seen any reason to be subtle in dealing with
      deities.

***** Eric and The Tezumen
      "Chin up, lad," said da Quirm. "At least you're being sacrificed for something worthwhile. I just suggested they tried using the wheels upright, so they'd roll. I'm afraid they're not very responsive to new ideas around here. Still, nil desperandum. Where there's life there's hope."
      Rincewind growled. If there was one thing he couldn't stand, it was people who were fearless in the face of death. It seemed to strike at something absolutely fundamental in him.
      "In fact," said da Quirm, "I think -" He rolled from side to side experimentally, tugging at the vines which were holding him down. "Yes, I think when they did these ropes up - yes, definitely, they -"
      "What? What?" said Rincewind.
      "Yes, definitely," said da Quirm. "I'm absolutely sure about it. They did them up very tightly and professionally. Not an inch of give in them anywhere."
      "Thank you," said Rincewind.
      The flat top of the truncated pyramid was in fact quite large, with plenty of room for statues, priests, slabs, gutters, knife-chipping production lines and all the other things the Tezumen needed for the bulk disposal of religion. In front of Rincewind several priests were busily chanting a long list of complaints about swamps, mosquitoes, lack of metal ore, volcanoes, the weather, the way obsidian never kept it's edge, the trouble with having a god like Quezovercoatl, the way wheels never worked properly however often you laid them flat and pushed them, and so on.
      The prayers of most religions generally praise and thank the gods involved, either out of general piety or in the hope that he or she will take the hint and start acting responsibly. The Tezumen, having taken a long hard look around their world and decided bluntly that things were just about as bad as they were ever going to get, had perfected the art of the plain-chant winge.
      "Won't be long now," said the parrot, from its perch atop a statue of one of the Tezumen's lesser gods.

***** Eric and Demons
      Rincewind ignored it and crept over to the window. It was small, but gave out on to a gently sloping roof. And out there was a real life, real sky, real buildings. He reached out to open the shutters -
      A crackling current coursed up his arm and earthed itself in his cerebellum.
      He sat on the floor, sucking his fingers.
      "He tole you," said the parrot, swinging backwards and forwards upside down. "But you wouldn't wossname. He's got you by the wossnames."
      "But it should only work on demons!"
      "Ah," said the parrot, achieving enough momentum to swing upright again, whereupon it steadied itself with the stubby remains of what had once been wings. "It's all according, isn't it. If you come in the door marked `wossnames` that means you get treated as a wossname, right? Demon, I mean. Subject to all the rules and wossnames. Tough one for you."
      "But you know I'm a wizard, don't you!"
      The parrot gave a squawk. "I've seen 'em, mate. The real McWossname. Some of the ones we've had in here, they'd make you choke on your millet. Great scaly fiery wossnames. Took weeks to get the soot off the walls," it added, in an approving tone of voice. "That was in his granddad's day, of course. The kid hasn't been any good at it. Up to now. Bright lad. I blame the wossnames, parents. New money, you know. Wine business. Spoil him rotten, let him play with his wossname's old stuff, `Oh, he's such an intelligent lad, nose always in a book`," the parrot mimicked. "They never give him any of the things a sensitive growing wossname really needs, if you was to ask me."
      "What you mean love and guidance?" said Rincewind.
      I was thinking of a bloody good wossname, thrashing," said the parrot.
      Rincewind clutched at his aching head. If this was what demons usually had to go through, no wonder they were always so annoyed.
      "Polly want a biscuit," said the parrot vaguely, in much the same way as a human would say "Er" or "As I was saying", and went on, "His granddad was keen on it. That and his pigeons."
      "Pigeons," said Rincewind
      "Not that he was particularly successful. It was all a bit trial and wossname."
      "I thought you said great big scaly -
      "Oh, yes. But that wasn't what he was after. He was trying to conjure up a succubus." It should be impossible to leer when all you've got is a beak, but the parrot managed it. "That's a female demon what comes in the night and makes mad passionate wossn -"
      "I've heard of them," said Rincewind. "Bloody dangerous things."
      The parrot put its head on one side. "It never worked. All he ever got was a neuralger."
      "What's that?"
      "It's a demon that comes and has a headache at you."

      Demons have existed on the Discworld for at least as long as the gods, who in many ways they closely resemble. The difference is basically the same as that between terrorists and freedom fighters.
      Most of the demons occupy a spacious dimension close to reality, traditionally decorated in shades of flame and maintained at roasting point. This isn't actually necessary, but if there is one thing that your average demon is, it is a traditionalist.
      In the centre of the inferno, rising majestically from a lake of lava substitute and with unparalleled views of the Eight Circles, lies the city of Pandemonium.[5] At the moment, it was living up to its name.

***** Hogfather and belief
      'What do they do with the teeth? What
      use is there for a lot of teeth? But ... what harm can a tooth fairy do?'
      'Have we got time to find one and ask her?' said the oh god.
      'Time isn't the problem,' said Susan.
      There are those who believe knowledge is something that is acquired - a precious
      ore hacked, as it were, from the grey strata of ignorance.
      There are those who believe that knowledge can only be recalled, that there was
      some Golden Age in the distant past when everything was known and the stones
      fitted together so you could hardly put a knife between them, you know, and
      it's obvious they had flying machines, right, because of the way the earthworks
      can only be seen from above, yeah? and there's this museum I read about where
      they found a pocket calculator under the altar of this ancient temple, you know
      what I'm saying? but the government hushed it up ... [18]
      Mustrum Ridcully believed that knowledge could be acquired by shouting at
      people, and was endeavouring to do so. The wizards were sitting around the
      Uncommon Room table, which was piled high with books.
      'It is Hogswatch, Archchancellor,' said the Dean reproachfully, thumbing through
      an ancient volume.
      'Not until midnight,' said Ridcully. 'Sortin' this out will give you fellows an
      appetite for your dinner.'
      'I think I might have something, Archchancellor,' said the Chair of Indefinite
      Studies. 'This is Woddeley's Basic Gods. There's some stuff here about lares and
      penates that seems to it the bill.'
      'Lares and penates? What were they when they were at home?' said Ridcully.
      'Hahaha,' said the Chair.
      'What?' said Ridcully.
      'I thought you were making a rather good joke, Archchancellor,' said the Chair.
      'Was I? I didn't mean to,' said Ridcully.
      'Nothing new there,' said the Dean, under his breath.
      'What was that, Dean?'
      'Nothing, Archchancellor.'
      'I thought you made the reference "at home" because they are, in fact, household
      gods. Or were, rather. They seemed to have faded away long ago. They were ...
      little spirits of the house, like, for example---'
      Three of the other wizards, thinking quite fast for wizards, clapped their hands
      over his mouth.
      'Careful!' said Ridcully. 'Careless talk creates lives! That's why we've got a
      big fat God of Indigestion being ill in the privy.


      All right, all right, I'll be careful. I'm just saying man is
      naturally a mythopoeic creature.'  'What's that mean?' said the Senior
      Wrangler. 'Means we make things up as we go along,' said the Dean, not
      looking up.
** Software Possibilities                                                       :software:
*** Algorithms
**** Partial Ordering
     As Heuristic Red Black Tree Weighting, seems workable. Doesn't
     have binning yet. Does sort and output the order based on user input.
     Could allow for range and indeterminacy, using node ranges.
     What would the values be of required number of specifications for particular depths?
    
**** Voronoi - island/city gen
     Voronoi is written and works, island and city gen needs work.
    
**** Hexboard
     Written, but accompanying AI needs reworking.
**** Dungeon gen
     Hyphae could cover dungeon gen.
     Should try some graph growing with networkx. 
     The problem is always translating a graph into a physical representation.
**** Graph Algorithms
     Usable in networkx
     Links with network analysis, source code analysis etc.
*** Games
**** Platformer
**** Roguelike
**** RPG
**** Interactive Fiction
*** Simulations
    In Netlogo?
**** Disease and Healthcare?
     Agents of two forms: Wealth and Vitality. 
     Sources of Wealth, providing a % of what you alreday have.
     Likelihood of disease.
     Specific Agents that process Wealth + Disease -> Vitality
     Different sources, individual, small groups, single large group
**** Gatekeepers
     Walled off area, Agents that only allow particular agents through.
     Different rules of reject vs allow, require vs optional, etc.
     Based on visual cues?

**** Voting
     Nick Case's voting sim. Look at that.

*** Tools
**** Authoring
***** Shell
      Shell rewrite progresses, edge types need some refinement.
      Then FSM and Rete can be added in. 
      Instances will take work.
**** Describing
***** iELPy
      Queries are proving tricky.
***** BTree
      Needs work. EL.js needs updating.
*** Exploration and Analysis
**** Game Code.
     code -> parsed -> JGShell. See the size and depth, number of children of calls etc.
**** Game Data.
     data -> parsed -> JGShell. See the structure of concepts.
***** Democracy 3
**** Deep Learning
     Tensorflow, LSTMs, Pixel Art, FFTs. : interesting, but not important.
**** Music
     Supercollider, Ableton Live. Python Midi.
**** Graphics
     Cairo, Fluxus, Ogre, PIL, Unity.

*** Concepts
**** Conversation Maze
     Pick a conversation:
     Plan it on post it notes:
     Generalise
     Implement
**** Solar System
     Interesting but unimportant.
**** Veil of Ignorance
     Society Gen. Questions prior to newspaper/street gen?
**** Pirate ship
     FTL Expanded.
**** Kraken Wakes
     Interlocking system of: The Deeps, Governments, Journalists,
     Civilians, Scientists. Its FTL without the war.

**** Gormenghast
     Ritual. The absurdity of ritual, and the leeway of action within it.

*** Rational Reconstructions
**** XCom - Strategy / Quad Dynamics
**** MGS V - PMC running
**** Stalker - Factions
**** Borderlands - Weapon Gen
**** Dins Curse - Quests
**** Dota - Character variation
**** Shadow of Mordor - Enemy Customisation, hierarchy
**** Pokemon - Battle System
**** Papers please - Bureaucratic system
**** Redshirt - Career Progression
**** Democracy - Law Network
**** Spacebase - Simulation
*** Generative System Grammars
**** Guilds
**** Violence Escalation
**** Values
**** Societies
**** Sanctions
**** Bureacracy
**** Accidents
**** Names
*** System Expressions
**** Streets
**** Newspapers
**** Clothing
*** Misc
    Have actions propose their preferred result, as subtext of the
    expression.  Some agents take the initiative, while others are
    Responding agents, and choose among preferred options, but can
    venture out if they desire. Similar to versu approach, but broader?
*** Tyranny notes
    A Similarity with the horus heresy.  Conquest of Kyros vs Crusade
    of the Emperor. Theres a similarity between the Archons of Tyranny
    and the Primarchs of the HH. 
   
    The designation of fatebinder is similar to mass effect, The
    *social* designation of power to decide others fates. Tyranny makes
    it similar to Judge Dredd, making the player a walking embodiment
    of the law, and your interpretation of it is part of the law.  What
    *would* be interesting is having your judgement's influence how
    other fatebinders judge, shifting the overall sense of justice and
    behaviour be close to the players decisions.

    The differences between the two armies contrast well. The rules of
    induction and recruiting, magic use, leader temperament, trophies,
    armor are all used. Gender Balance is actually uniform between them.
   
** Social rule as a hierarchical graph                                          :architecture:design:socialRules:
   In the way that a voronoi diagram sweeps down, differentiating between the beach
   and sweep line, have recursive connections between layers of social rules.

   Rules can describe a net of facts and other rules.

   let:
   F,G,H be distinct grammars of facts.

   R be a set of rules comprised of a tuple r(I,O,S) where:
   I is the input of the rule, as a string of facts in F.
   O is the output of the rule, as a string of facts in G
   S is the symbol string associated with the rule, providing
   additional information about it in language H

   F,G,H could equal, be a superset, or be disjoint from each other.

   Layers can then be formed of distinct layers of rules L,L',L'' etc,
   which are of the form L(R,F,G,H), L'(R',F',G',H').
   such that F' and I' of L' are the same as S and H of L. That is, the output of
   one layer is the input of another layer.

   The first layer's input, F, would be the base facts of the simulating
   system, as would the last layer, R^ that would trigger the simulating
   system to perform actions.

   This can imply the simulating system, the container typically, to be a
   black box of rules itself, whatever they may be. This can imply
   thinking of the super set L" (consisting of all layers) is a loop.

   f(L") = f(L) -> F(L') -> F(L'') -> etc to f(L_last)

   What if there were branches to previous loops:
   F(L"") = f(L) <-> F(L') ...

   With inverse ruleset R#, which would work in the opposite direction:
   r#(O,I,S) = r(I,O,S)

   And the rule engine has an order of sweeps to evaluate and update by:
   Order = [L,L',L,L',L'',L_last]

   CiF has a similar system: Volition rules -> Influence rules -> Actions -> Trigger
   Rules.

   let F_1, the input set for R_1 of L_1, be the set of brute facts, dependent
   on the simulating system. this is also H_j of L_j, the triggering
   layer out of L_n layers.

   All other facts are social facts, but are they all equal? No.
   Differentiate them into different types and further specified layers:

   There can be representable facts F_rep, and silent facts F_sil, as
   subsets of F_1,
   things that present observable differences and unobservable
   differences in the underlying system. The difference between knocking
   on a door and firing radiation through a door.

   There can rule types as well:
   Physical->Physical Rules (Physical feedback, the Simulation blackbox layer)
   Physical->Social Rules (Physically constitutive/definitional)
   Social -> Social Rules (Social definitions, pure symbolic)
   Social -> Social Rules(Transformational, communicative)
   Social -> Physical Rules (Socially initiated actions)

   Constitutive and Symbolic rules could change with only indirect,
   meaning based changes to the behaviour of the system. Favourite
   colours, or shouting when angry versus whispering when angry.

   Communicative rules are distinct, because we rely on some level of
   natural language to be able to understand. (Though James Ryan's
   islanders didn't need that, using a bit mask description of language).

   If there are transformative layers, such as aggregation, weighting,
   or data assembly from multiple sources...

*** Authoring for Layers.                                                       :authoring:
    Be able to define inputs, and ouputs, for a layer, and orders of
    assessment. Specify that inputs for L_1 are a,b,c,d,e.. and the
    outputs are w,x,y,z.

    Then move to L_2, that has w,x,y,z as inputs already, with the
    inputs marked as unused. Any new inputs defined will be recursively added to L_1's output, and
    marked as undefined.Outputs work similarly to L_3.

    Have the system warn of used ouputs, be able to enforce/define types
    of the outputs/inputs, and specify generics, and cross-layer
    facts. Preferences, and recursive changes are also possible.

    System keeps prompting till L_1 input == L_action output

    Transformational layers could be standardised (eg: combine down inputs to
    n [new/defined] super facts), select m from input options, weight
    rules in a bell curve) could be varied in defined ways (curve changes,
    selection number, reset). (Similar to Reaktor system components to
    create a synth).

    A Transformational layer could also be Societal / Individual based
    calculation (ie: Specify the bracketed layers should be run on an
    individual rather than societal, or statistical, or... normative?
    basis).

    A UI similar to Reaktor, wiring together an architecture graphically,
    would be intersting. Or at least part of the system, modularly?
    Treat individuals as 'voices' of the synth?
** Why Institutions are important for video-games                               :argument:

   Institutions are important because they structure almost all life, action, and systems.

*** Institutions are currently ignored in games

**** There has always been a bias to the physics in game systems.
     Mario. Donkey Kong. Modern Warfare. Minecraft. Even games like Dragon age, where
     dialogue and party interactions are praised, still rely primarily on (physical) combat systems.
     Even the Sims encodes a large amount of its word in physical smart objects.

     This is changing, with games like Prom Week, and Versu, placing more of a focus on social interactions,
     and social rules.

*** Institutions provide structure to social rules
    Currently, CiF collects rules into 'micro-theories', and Versu into 'social practices'.
    In the words of Josh McCoy, micro-theories are 'big bags of rules'. The complexity of institutions can surely
    be described better than this.

*** Institutions fill the structuring role of narrative and story in real life interactions.
*** Institutional changes themselves can be the focus of narrative.
    See Red Mars, and Gormenghast.

***** Phenomenological models and portrayals of Institutions are shallow and lacking
      There has started to be some (Paper's Please, We Happy Few), but they are the exception.
** ASP and rules
   see cite:Eiter2009 for *stratified programs*.
   Specifies evaluation order for predicates in a logic program.
