* Network Layers, metaphors, and the DCEL

  The dcel is a clear means of representing a 3-layer ladder of abstraction. Vertex <-> HalfEdge <-> Face
  With Voronoi, and tensor based city gen as generators. 
   
  Society is a DCEL of many layers of abstraction.
  CiF showed how to flatten the layers for interactions somewhat.
  Versu showed a different layer structure, of greater range of interactions. 

  I'm trying to get to an understanding of layer descriptions in a similar way to deep learning descriptions.
  To describe particular structures, recombine and open particular transforms of outside data into internal data.
   
   
  inputs --> (--> InputTransform --> (Selection, SelectAll, Gate, Parameterize, Compile, Delay, Store, Retrieve) -> OutputTransform) -> Actions

  This is very like reaktor. Passing signals that carry information in various ways between instruments, voices, that can include standards like MIDI.
   

  Gameplay / Generation of Aletheiometer Output. Combinations of associations.
