* The Phenomenological Experience of Institutional Variation                    :phenomenology:
A Consideration of the poverty of (videogame) representations of the intersection between:
- The lived experience of an individual, 
- Institutions (and a focus, if anything, on organisations)
- Generative Systems

*** The Lived Experience of the Individual || Phenomenology

- Rejection of Objectivity
- Analysis of Daily Human Behaviour can provide understanding of nature
- Persons should explore and focused on
- Conscious experience over traditional data.
- Intentionality (thought:Normative Intentionality?)
- Empty Intentions vs Intuited Objects
- Noesis vs Noema. (real vs ideal content of intentional act)
- Empathy and intersubjectivity
- Lifeworld
- Dreyfus and AI conceptions of abilities


*** Institutions
The normative structures, the organisations that form around those norms. They
are implicitly represented, and  statically.

*** Generative Systems
Spore, Dwarf Fortress, URR,


** Examples

*** Models
Fligstein.
CiF, Praxis,  

*** Social Simulation
Sugarscape and everything that followed in ABM. 

*** Videogames
Prom Week, Versu, Mass Effect.
Tales from the Borderlands, The Wolf Among Us.

** Concepts

*** Frasca's Sims Mod

*** Paper's Please / Inverted Democracy 3
You are reading the newspaper, and voting.
Voting -> Governments -> Policies -> Behaviours and Actions -> News Stories

*** Society Explorations.
The Stars my Destination, The Demolished Man. Stand On Zanzibar.
Doctor Who?

**** Social Roguelikes
Sliders, Doctor Who. Gateway.
Generated small group situations, constant threat of death.

***** 'Go down the shops and buy an ice cream' 
Dawn of the Dead, Hot Fuzz, The World's End. Sliders.

*** Society Builders. 
Discworld, Red Mars, Galactica. Stand on Zanzibar.

**** Apocalypse Reactions
(related to Society Builders)
The Walking Dead, The Day of the Triffids and the Kraken Wakes.
