* Questions to ask about institutions                                           :institutions:questions:
** Descriptive Questions
   How are institutions structured? How do they change? 
   Who are the people in institutions? Do they always fulfill the same roles?
   Where are institutions located? Physically? Mentally?
   When do institutions form? When do they die? When do they change?
   When are institutions 'activated' in a given situation?
   What do institutions do?
   What are individuals' relations to an institution
   What size are institutions? What does size of an institution mean?
   How do we model institutions? How do we describe their structure?
   How do we describe the interactions between institutions?
   How do similar institutions vary?

** Predictive Questions
   How do they change when X occurs?
   Which institution of a conflict set is preferred in a given situation?

** Explanatory Questions
   Does an institution modeled by Fligsteins structure allow for similar behaviour to real institutions?
   Why do institutions change? Why do they exist?
   How do institutions operate?
   How are institutions maintained?
   How are institutions transmitted?

** Misc
*** What is important about our experience of institutions?
*** How can we describe institutions?
*** How can we phenomenologically operationalise institutions?
*** What are the variants and invariants of an institution?
*** How do the variants of an institution change?
*** How are those changes experienced?
*** How are the consequences of the changes experienced?
*** What language would describe these changes?
*** What are examples of the ranges of:
**** Institutions
**** Inter-Institutional Variance (religion <-> disgust)
**** How do institutions vary across time?
**** Institutional Experiences
**** Institutional Purposes
     Do all institutions have purposes?
**** Components of Institutions:
***** Values
***** Rules
***** Roles
***** Actions
***** Timescales
***** Agency
***** Locations
***** Events
***** Means of individual variation / pure symbolics
***** means of communication / semi-symbolics
***** actions / non-symbolics
*** What is the process by which an individual acts according to a multitude of institutions?
*** How do you get from social rules to actions?
*** How do you differentiate universally applicable institutions to individual/instrumental/situational institutions?
*** How do you vary an institution?
    feedback loop. resonance.
*** How are institutions formed?
    Is this the question to ask at the moment? probably not. Institutions *exist*, the creation of them is rarer.
    Possibly consider Facebook as an institution.






