* Institutions and Organizations
  by W. Richard Scott
** Introduction
   Origins in the middle of the 19th century.
   Dominated social sciences from 1850s to 1920s.
   Subsided until the 1970s.
*** Questions institutional theory asks:
**** Why do organizations of the same type so closely resemble one another?
**** What specific types of institutions are associated with the rise of organizations?
**** How are we to regard behavior in organizational settings?
     Does it reflect the pursuit of rational interests and the
     exercise of conscious choice, or is it primarily shaped by
     conventions, routines, and habits?
**** What is the relation between freedom and control in social life?
**** Why do individuals and organizations conform to institutions?
     Is it because they are rewarded for doing so, because they
     believe they are morally obligated to obey, or because they can
     conceive of no other way of behaving?
**** Why is the behaviour of participants observed to depart from the formal rules and stated goals of the organization? 
**** Why is it, if formal rules are largely ignored, that resources and energy are expended to maintain these formal structures?
**** Where do interests come from? 
     Do they stem from nature, or are they constructed/inflected by social context?
**** Why and how do formal and informal control structures arises?
     Do individuals voluntarily construct rule systems that then operate to bind their own behavior?
**** Do control systems function only when they are associated with incentives - rewards and punishments - or are other processes sometimes at work?
**** How do differences in cultural beliefs shape the nature and operation of organizations?
**** If institutions regulate and constitute individuals, how can individuals hope to alter the institutions in which hthey are embedded?

** Early Institutionalists

*** Economics
    
**** European
     [p2]
     Schmoller (1900-1904): Historical school: Economic processes operate within a social
     framework that is in turn shaped by a set of cultural and
     historical forces. Argued to shed views on simplistic 'economic man'.

     Carl Menger (1883): Classical approach. Institutions as social phenomena. 
     Possibly (Langlois) the original institutional economist.

**** American
     Veblen, Commons, Mitchell.
     
     Veblen focused on economic change. Focused on individual actors and dynamic models of economy/society.
     Argued against the 'conception of man as that of a lightning calculator of pleasures and pain', focusing on habit and convention.
     Defined institutions as 'settled habits of thought common to the generality of man'.
     *Conspicuous consumption*. 
     Dichotomy between institutions and technology?

     Commons focused on *transactions*. 'The transaction is two or
     more wills giving, taking, persuading, coercing, defrauding,
     mechanisms and rules of conduct'.  
     Institutional rules were necessary to define the limits within
     which individuals and firms could perform their objectives.
     Institutions existing at a specific time are imperfect and pragmatic solutions to reconcile past conflicts.
     They are solutions consisting of:
     1) a set of rights and duties
     2) an authority for enforcing them
     3) adherence to collective norms of reasonable behaviour

     Jacoby: Early institutionalists departed from mainstream approaches in 4 ways:
     1) Indeterminacy vs determinacy
     2) Endogenous vs exogenous preferences
     3) Behavioural realism vs simplifying assumptions
     4) Diachronic vs synchronic analysis (static vs dynamic analysis)
        
     Schumpeter, Polanyi, Galbraith, Myrdal.

     Failed because of *tendency to degenerate into naive empiricism and historicism.*

*** Political Science
    [p6]
    Tocqueville.

*** Sociology
    [p10]
**** Spencer and Sumner

**** Cooley, Thomas and Blumer

**** Mark, Durkheim, Weber and Parsons

**** Mead, Schutz, Bourdieu, Berger and Luckmann

** Organization Studies
   [p21]
*** Columbia School: Merton and Selznick

*** Chicago School: Hughes

*** Parsons

*** Carnegie School: Simon

*** Neo-Institutional theory in Economics

*** Neo-Institutional Theory in Political Science

*** Cognitive Psychology and Cultural Anthropology

*** Neo-Institutional theory in Sociology

** Three Pillars of Institutions
   [p55]
*** Definitions of Institutions
** Logics, Agency, Carriers and Levels
   [p87]
** Institutional Construction
   [p113]
** Institutionalization
   [p143]
** Institutional Processes and Organizations
   [p181]
** Institutional Processes and Organization Fields
   [p219]
