#+TITLE: Script Notes

* Overview

* Main
** ADB
Tablet will periodically de-authorize adb,
so re-pair with `adb pair`
** Awk
#+begin_src awk
awk 'match($0, /HREF="(.+?)"/, a) {print a[1]}'

#+end_src awk

** Compiling Aseprite from source
  Follow the instructions to install google depot_tools, then skia.
  The missing instruction is to *unset python3 and anaconda in the path*
  as depot_tools, and the setup script for skia uses *python 2*.
  after that, compilation is straight forward, making sure to target the
  OSX version you are actually on.

** Emacs Straight Recipes
https://github.com/radian-software/straight.el#the-recipe-format

#+begin_src elisp
;; Disable Byte Compilation
(package! a-package :recipe (:build (:not compile)))
;; Or disable byte compilation with
;; -*- no-byte-compile: t; -*-

;; Specify a local repo
(package! a-package :recipe (:local-repo "~/.doom.d/packages/a-package"))


#+end_src

** File encoding
file -I {}
iconv -f {enc} -t {enc} {} > conv-{}

** Firefox
Get to configs with about:about
Use: reader.parse-on-load.force-enabled
for reader view force

Set: browser.bookmarks.editDialog.firstEditField
to: tagsField
for a better bookmarking default

** GPG Notes (v 2.2.11)
*** *Short IDs*: Last 8 digits of fingerprint
*** Basic Protocol
   Create Key
   Create Revocation Cert
   Create Fingerprint
   Export Public and Secret Keys
   Backup [Public, Secret, Revocation]

   Import other persons public key
   Verify it against their fingerprint
   Sign the Key
   (optional, give the signed key back by exporting it)

   Then decrypt messages sent to you,
   encrypt messages to them using their public key,
   or verify they sent a plaintext signature.

*** Setup for Emacs
   To use, add "allow-emacs-pinentry" to "~/.gnupg/gpg-agent.conf",
   reload the configuration with "gpgconf --reload gpg-agent", and
   start the server with M-x pinentry-start. (or add (pinentry-start) to .emacs)

*** List keys
   gpg -k
   gpg --list-sigs
*** Importing a key:
   Works for secret and public keys
   gpg --import [filename]
*** Generating a key
   gpg --gen-key
   gpg --gen-revoke --armor --output=RevocationCertificate.asc [email]
*** Deleting a key:
   gpg --delete-secret-keys
   gpg --delete-keys
*** Get a fingerprint
   Fingerprints give a shorter to verify hash of public keys
   gpg --fingerprint [email]
*** Sign a key
   gpg --sign-key [email]
   or
   gpg --interactive --edit-key [email]
*** Export keys
   gpg --armor --export[-secret-keys] [-o file] [-a ID | email]
*** Encrypt
   *Don't forget to add yourself to the recipients*
   gpg [-o output] --sign --armor [-r recipient] [-e file]
*** Decrypt
   gpg  -o output -d file
*** Sign a plaintext message
   gpg --clearsign file
*** Verify a signature
   gpg --verify file
*** Using Stronger Encrpytion
   gpg --interactive --edit-key [email]
   Then 'showpref' will show algorithm preferences
   from most - least.

   modify using 'setpref [algorithms..]'

   then 'save'

** Image Pdf calls
#+NAME: image to pdf generation
#+begin_src bash :results value
convert ? -alpha off ./temp/`?`
mogrify -orient bottom-left ?
img2pdf --output `?`.pdf --pagesize A4 --auto-orient ?
pdftk * cat output diagrams.pdf
#+end_src

#+NAME: text to pdf generation
#+begin_src bash :results value
pandoc ? -o output.pdf
#+end_src

** Markdown html export
Add a local file to `markdown-css-paths`,
can use npm package `generate-github-markdown-css` as a start

** Pdf Metadata
#+begin_src bash
exiftool file.pdf

# or:
pdftk file.pdf dump_data_utf8 > file.info
# edit
pdftk file.pdf update_info_utf8 file.info output file2.pdf
#+end_src

# From https://askubuntu.com/questions/1264322
#+begin_src bash
# For Creating Bookmarks/TOC in pdfs:
# BookmarkBegin
# BookmarkTitle:
# BookmarkLevel: 1
# BookmarkPageNumber:
pdftk ? dump_data > info.txt
# -- Add bookmarks
pdftk ? update_info info.txt output updated.pdf
#+end_src

** Sed
Filter lines with:
'/pattern/d'

Print Matching lines with:
'/pattern/p'

case Invariant:
'/pattern/I'

** Wordnet
`wn`

#+begin_src bash
# For Nouns
-hypen		Hypernyms
-hypon, -treen	Hyponyms & Hyponym Tree
-synsn		Synonyms (ordered by estimated frequency)
-derin		Derived Forms
-famln		Familiarity & Polysemy Count
-coorn		Coordinate Terms (sisters)
-grepn		List of Compound Words
-over		Overview of Senses
#+end_src

#+begin_src bash
# For verbs
-hypev		Hypernyms
-hypov, -treev	Hyponyms & Hyponym Tree
-synsv		Synonyms (ordered by estimated frequency)
-deriv		Derived Forms
-famlv		Familiarity & Polysemy Count
-framv		Verb Frames
-coorv		Coordinate Terms (sisters)
-simsv		Synonyms (grouped by similarity of meaning)
-grepv		List of Compound Words
-over		Overview of Senses
#+end_src

#+begin_src bash
# Adjectives
-antsa		Antonyms
-synsa		Synonyms (ordered by estimated frequency)
-attra		Attributes
-deria		Derived Forms
-domna		Domain
-famla		Familiarity & Polysemy Count
-grepa		List of Compound Words
-over		Overview of Senses
#+end_src

#+begin_src bash
# Adverbs
-antsr		Antonyms
-synsr		Synonyms (ordered by estimated frequency)
-pertr		Pertainyms
-famlr		Familiarity & Polysemy Count
-grepr		List of Compound Words
-over		Overview of Senses
#+end_src

** XML
*** XPath
#+NAME: Example Code
#+begin_src xpath :results output
# display the last names of all people in the doc
//person/@last-name

# get the 2nd person node
/people/person[2]

# get all the person nodes that have addresses in denver
//person[address/@city='denver']

# get all the addresses that have "south" in the street name
//address[contains(@street, 'south')]

# reject certain nodes:
//(* except script)
//*[not(self::script)]

# Extract an attribute value:
//a/extract(@href, '.*')
#+end_src

#+begin_src xpath
# Axes
ancestor
ancestor-or-self
attribute / @
child
descendant
descendantor-self
following
following-sibling
parent
preceding
preceding-sibling
self / .


#+end_src

*** [[https://www.videlibri.de/xidel.html][xidel]]
#+begin_src bash
# Extracts between table and footer
xidel -s --output-format=xml --xpath "//table/following-sibling::*[//*[@id='printfooter']/preceding::node()]" `?`
#+end_src
*** [[http://xmlstar.sourceforge.net/][XML Starlet]]

#+begin_src bash
# query, -I(indenting output), -t(template:) -f(file name) -n(new line) -m(match xpath) //Trait -c(copy xpath) . -n -b(break nesting) file
xml sel -I -t -f -n -m //Trait -c . -n -b ./facade_messy.xml

# delete a path:
xml ed -d "//div[@id='toc']" ? > mod-`?`
#+end_src

*** [[http://saxon.sourceforge.net/][Saxon]]

** Gradle

** Wget
https://www.networkinghowtos.com/howto/change-the-user-agent-in-wget/
https://www.networkinghowtos.com/howto/common-user-agent-list/

wget --user-agent="Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"
wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"

** Latex

*** tlmgr

:outdated_l3_layer:
https://tex.stackexchange.com/questions/586467/

sudo fmtutil-sys --all
:END:


*** texdoc
https://tex.stackexchange.com/questions/297004/
tlmgr option docfiles 1
tlmgr install --reinstall $(tlmgr list --only-installed | sed -E 's/i (.*):.*$/\1/')

* Links
[[https://www.futureboy.us/pgp.html][GPG General Howto]]
https://pandoc.org/
