* Software Possibilities
** Algorithms
*** Partial Ordering
    As Heuristic Red Black Tree Weighting, seems workable. Doesn't
    have binning yet. Does sort and output the order based on user input.
    Could allow for range and indeterminacy, using node ranges.
    What would the values be of required number of specifications for particular depths?
    
*** Voronoi - island/city gen
    Voronoi is written and works, island and city gen needs work.
    
*** Hexboard
    Written, but accompanying AI needs reworking.
*** Dungeon gen
    Hyphae could cover dungeon gen.
    Should try some graph growing with networkx. 
    The problem is always translating a graph into a physical representation.
*** Graph Algorithms
    Usable in networkx
    Links with network analysis, source code analysis etc.
** Games
*** Platformer
*** Roguelike
*** RPG
*** Interactive Fiction
** Simulations
   In Netlogo?
*** Disease and Healthcare?
    Agents of two forms: Wealth and Vitality. 
    Sources of Wealth, providing a % of what you alreday have.
    Likelihood of disease.
    Specific Agents that process Wealth + Disease -> Vitality
    Different sources, individual, small groups, single large group
*** Gatekeepers
    Walled off area, Agents that only allow particular agents through.
    Different rules of reject vs allow, require vs optional, etc.
    Based on visual cues?

*** Voting
    Nick Case's voting sim. Look at that.

** Tools
*** Authoring
**** Shell
     Shell rewrite progresses, edge types need some refinement.
     Then FSM and Rete can be added in. 
     Instances will take work.
*** Describing
**** iELPy
     Queries are proving tricky.
**** BTree
     Needs work. EL.js needs updating.
** Exploration and Analysis
*** Game Code.
    code -> parsed -> JGShell. See the size and depth, number of children of calls etc.
*** Game Data.
    data -> parsed -> JGShell. See the structure of concepts.
**** Democracy 3
*** Deep Learning
    Tensorflow, LSTMs, Pixel Art, FFTs. : interesting, but not important.
*** Music
    Supercollider, Ableton Live. Python Midi.
*** Graphics
    Cairo, Fluxus, Ogre, PIL, Unity.

** Concepts
*** Conversation Maze
    Pick a conversation:
    Plan it on post it notes:
    Generalise
    Implement
*** Solar System
    Interesting but unimportant.
*** Veil of Ignorance
    Society Gen. Questions prior to newspaper/street gen?
*** Pirate ship
    FTL Expanded.
*** Kraken Wakes
    Interlocking system of: The Deeps, Governments, Journalists,
    Civilians, Scientists. Its FTL without the war.

*** Gormenghast
    Ritual. The absurdity of ritual, and the leeway of action within it.

** Rational Reconstructions
*** XCom - Strategy / Quad Dynamics
*** MGS V - PMC running
*** Stalker - Factions
*** Borderlands - Weapon Gen
*** Dins Curse - Quests
*** Dota - Character variation
*** Shadow of Mordor - Enemy Customisation, hierarchy
*** Pokemon - Battle System
*** Papers please - Bureaucratic system
*** Redshirt - Career Progression
*** Democracy - Law Network
*** Spacebase - Simulation
** Generative System Grammars
*** Guilds
*** Violence Escalation
*** Values
*** Societies
*** Sanctions
*** Bureacracy
*** Accidents
*** Names
** System Expressions
*** Streets
*** Newspapers
*** Clothing
** Misc
   Have actions propose their preferred result, as subtext of the
   expression.  Some agents take the initiative, while others are
   Responding agents, and choose among preferred options, but can
   venture out if they desire. Similar to versu approach, but broader?
** Tyranny notes
   A Similarity with the horus heresy.  Conquest of Kyros vs Crusade
   of the Emperor. Theres a similarity between the Archons of Tyranny
   and the Primarchs of the HH. 
   
   The designation of fatebinder is similar to mass effect, The
   *social* designation of power to decide others fates. Tyranny makes
   it similar to Judge Dredd, making the player a walking embodiment
   of the law, and your interpretation of it is part of the law.  What
   *would* be interesting is having your judgement's influence how
   other fatebinders judge, shifting the overall sense of justice and
   behaviour be close to the players decisions.

   The differences between the two armies contrast well. The rules of
   induction and recruiting, magic use, leader temperament, trophies,
   armor are all used. Gender Balance is actually uniform between them.
   
