* Vault Sim Design Doc

A Fallout Shelter Simulation to bootstrap simulations and norms into
** Components
*** Vault
    A Stack of Floors
**** Floor
     A Row of Rooms
***** Room
      Each room holds actors and objects, and has a purpose.
      Can be an elevator to another floor.
****** Actor
       Moves horizontally,
       interacts with objects and other actors. 
       Moves between floors using elevators.
****** Object
       Existing in a room, can be picked up, manipulated, produced, consumed.
** Simulation Components
   Actors, objects, sources, sinks.
   Room purposes: Water, food, raw materials, produced materials.   
   Floors
** Norms
** Connection to underlying model
   Network based to either: JS Rete, Python iElPy, Haskell FSM.
** Plan
   Define rooms: Size, width, slots for items. - Fixed height and width for the moment.
   Create Elevator room type.
   Create floor controller: A Row of rooms, with elevators at specified points.
   Create Actor: Move left and right
   Create Vault Controller: A Stack of floors, with elevators aligned.
   Create Simulation Controller: Central repo to hold food, water, power information
   Create Item Generator and Sink.
   
