* Dan Abnett Extracts                                                           :examples:scifi:abnett:
*** Eisenhorn
**** Hubris
     --------------------
     I WENT TO see Carpel at noon the next day. It was always noon in the
     Sun-dome, but this was real noon by the clock. By then, Lowink, Aemos and
     Betancore had all dredged up new information for me.

     I shaved, and dressed in black linen with high boots and a formal jacket of
     scaled brown hide. I wore my inquisitorial rosette at my throat. I intended
     to show Carpel I meant business.

     Aemos and I descended from the landing platform superstructure by caged
     elevator and found yellow-robed custodians waiting to escort us. Despite
     the rancid white light all around, they still held ignited light poles. We
     made short, hard shadows on the dry rockcrete of the concourse as we
     crossed to an open limousine. It was a massive chrome-grilled beast with
     pennants bearing the Hubris crest fluttering on its cowling. There were
     four rows of overstuffed leather benches behind the centre-set driver’s
     cockpit.

     We hummed through the streets on eight fat wheels. The boulevards were wide
     and, needless to say, bright. To either hand, glass-fronted buildings rose
     towards the blazing plasma sun-globe high above, like flowers seeking the
     light. Every thirty metres along every street, chemical lamps on ornate
     posts strained to add their own light to the brilliance.

     Traffic was sparse, and there were at most a few thousand pedestrians on
     the streets. I noticed most wore yellow silk sashes, and that garlands of
     yellow flowers decorated every lamp post.

     ‘The flowers?’ I asked.

     ‘From the hydroponic farms on east-dome seven,’ one of the custodians told
     me.

     ‘Signifying?’

     ‘Mourning.’

     ‘Same as the sashes,’ Aemos whispered in confidence. ‘What happened last
     night is a major tragedy for this world. Yellow is their holy colour. I
     believe the local religion is a solar belief.’

     ‘The sun as Emperor?’

     ‘Common enough. Extreme here, for obvious reasons.’

     The custodial hall was a glass spire close to the town centre, a solar disk
     overlaid with the double-headed eagle of the Imperium decorating its upper
     faces. Nearby was the local chapel of the Ecclesiarchy, and several
     buildings given over to the Imperial Administratum. It amused me to see
     they were all built of black stone and virtually windowless. Those Imperial
     servants stationed here obviously had as little track as me with the
     constant light.

     We drew in under a glass portico and were escorted into the main hall. It
     was seething with people, most of them custodians in yellow robes, some
     local officials and technomagi, some clerks and servitors. The hall itself
     was of the scale of an Imperial chapel, but raised in yellow-stained glass
     on a frame of black cast-iron. The air was full of golden light shafting
     down through the glass. The carpet was vast, black, with a sun-disk woven
     into its centre.

     ‘Inquisitor Eisenhorn!’ declared one of my escorts through a vox-hailer.
     The hall fell silent, and all turned to watch us approach. High Custodian
     Carpel sat on a hovering lifter-throne with gilt decorations. A burning
     chemical light was mounted above the head of the floating chair. He swung
     in through the parting crowd towards me.

     ‘High custodian,’ I said with a dutiful nod.

     ‘They are all dead,’ he informed me. ‘All twelve thousand, one hundred and
     forty-two. Processional Two-Twelve is dead. None survived the trauma.’

     ‘Hubris has my sincere sympathies, high custodian.’

     The hall exploded in pandemonium, voices screeching and shouting and
     clamouring.

     ‘Your sympathies? Your damned sympathies?’ Carpel screamed above the roar.
     ‘A great part of our ruling elite die in one night, and we have your
     sympathies to console us?’

     ‘That is all I can offer, high custodian.’ I could feel Aemos shivering at
     my side, making aimless notes on his wrist slate about custom and clothing
     and language forms... anything to take his mind from the confrontation.

     ‘That’s hardly good enough!’ spat a young man nearby. He was a local noble,
     young and firm enough, but his skin had a dreadful, sweaty pallor and
     custodians supported him as he stumbled forward.

     ‘Who are you?’ I asked.

     ‘Vernal Maypell, heir-lord of the Dallowen Cantons!’ If he expected me to
     fall to my knees in supplication, he was in for a disappointment.

     ‘Because of the gravity of this event, we have roused some of our highborn
     early from their dormancy,’ Carpel said. ‘Liege Maypell’s brother and two
     of his wives died in Processional Two-Twelve.’

     So the pallor was revival sickness. I noticed that fifty or more of the
     congregation present were similarly wasted and ill.

     I turned to Maypell.

     ‘Liege. I repeat, you have my condolences.’

     Maypell exploded with rage. ‘Your arrogance astounds me, off-worlder! You
     bring this monster to our world, battle with him through our most sacred
     sanctums, a private war that slaughters our best and you—’

     ‘Wait!’ I used my will. I didn’t care. Maypell stopped as if stunned and
     the vast hall rang silent. ‘I came here to save you and deny Eyclone’s
     plans. But for the efforts of myself and my companions, he might have
     destroyed more than one of your hibernation tombs. I broke none of your
     laws. I was careful to preserve your codes in pursuit of my work. What do
     you mean, I brought this monster here?’

     ‘We have made enquiries,’ answered an elderly noblewoman nearby. Like
     Maypell, she was ailing with revival sickness, and sat hunched on a litter
     carried by slaved servitors.

     ‘What enquiries, madam?’

     ‘This long feud with the murderer Eyclone. Five years, is it now?’

     ‘Six, lady.’

     ‘Six, then. You have hounded him here. Driven him. Brought him, as Liege
     Maypell said.’

     ‘How?’

     ‘We registered no off-world ship these past twenty days except yours,
     Eisenhorn,’ Carpel said, reviewing a data-slate. ‘The Regal Akwitane. That
     ship must have brought him as it brought you, to finish your war here and
     damn our lives. Did you choose Hubris because it was quiet, out of the way
     a place where you might finish your feud undisturbed, in the long dark?’

     I was angry by now. I concentrated to control my rage. ‘Aemos?’

     Beside me, he was muttering ‘...and what silicate dyes do they use in their
     stained glass manufacture? Is the structure armoured? The supports are
     early Imperial Gothic in style, but—’

     ‘Aemos! The report!’

     He started and handed me a data-slate from his leather case.

     ‘Read this, Carpel. Read it thoroughly.’ I pushed it at him – then snatched
     it away as he reached for it. ‘Or should I read it aloud to all here
     assembled? Should I explain how I came here at the last minute when I
     learned Eyclone was moving to Hubris? That I learned that only by
     astropathic decryption of a cipher message sent by Eyclone two months ago?
     A cipher that killed my astropath in his efforts to translate it?’

     ‘Inquisitor, I—’ Carpel began.

     I held up the data-slate report for them all, thumbing the stud that
     scrolled the words across the screen. ‘And what about this? The evidence
     that Eyclone has been planning a move against your world for almost a year?
     And this, gathered this last night – that an unregistered starship moved in
     and out of your orbit to deliver Eyclone three days ago, unnoticed by your
     planetary overwatch and the custodian “Guardians”? Or the itemised stream
     of astropathic communication that your local enclave noticed but didn’t
     bother to source or translate?’

     I tossed the slate into Carpel’s lap. Hundreds of eyes stared at me in
     shocked silence.

     ‘You were wide open. He exploited you. Don’t blame me for anything except
     being too late to stop him. As I said, you have my sincere condolences.

     ‘And next time you choose to confront an Imperial inquisitor,’ I added,
     ‘you may want to be more respectful. I’m excusing a lot because I recognise
     the trauma and loss you have suffered. But my patience isn’t limitless...
     unlike my authority.’

     I turned to Carpel. ‘Now, high custodian, can we talk? In private, as I
     think I requested.’
     --------------------
     WE FOLLOWED CARPEL’S floating throne into a side annexe leaving a hall full
     of murmuring shocked voices behind us. Only one of his men accompanied us,
     a tall, blond fellow in a dark brown uniform I didn’t recognise. A
     bodyguard, I presumed. Carpel set his throne down on the carpet and raised
     a remote wand that tinted the glass plates of the room at a touch.

     Reasonable light levels at last. From that alone, I knew Carpel was taking
     me seriously.

     He waved me to a seat opposite. Aemos lurked in the shadows behind me. The
     man in brown stood by the windows, watching.

     ‘What happens now?’ Carpel asked.

     ‘I expect your full co-operation as I extend my investigation.’

     ‘But the matter is over,’ said the man in brown.

     I kept my gaze on Carpel. ‘I want your consent for me to continue as well
     as your full co-operation. Eyclone may be dead, but he was just the
     blade-point of a long and still dangerous weapon.’

     ‘What are you talking about?’ the man in brown snapped.

     Still I did not look at him. Staring at Carpel, I said, ‘If he speaks again
     without me knowing who he is, I will throw him out of the window. And I
     won’t open it first.’

     ‘This is Chastener Fischig, of the Adeptus Arbites. I wanted him present.’

     Now I looked at the man in brown. He was a heavy-set brute with a loop of
     shiny pink scar tissue under one milky eye. I’d taken him to be a young man
     with his clean skin and blond hair, but now I studied him, I saw he was at
     least my age.

     ‘Chastener,’ I nodded.

     ‘Inquisitor,’ he returned. ‘My question stands.’

     I sat back in my chair. ‘Murdin Eyclone was a facilitator. A brilliant,
     devious man, one of the most dangerous I have ever hunted. Sometimes to
     hunt down your prey is to finish his evil. I’m sure you have experience of
     that.’

     ‘You called him a “facilitator”.’

     ‘That was where his danger lay. He believed he could serve his obscene
     masters best by offering his considerable skills to cults and sects that
     needed them. He had no true allegiances. He worked to facilitate the grand
     schemes of others. What he was doing here on Hubris was to advance and
     develop someone else’s plans. Now he is dead, and his scheme thwarted. We
     may be thankful. But my task is not done. I must work back from Eyclone,
     his men, from any clue he left and dig my way into whatever greater, secret
     darkness was employing him.’

     ‘And for this you want the co-operation of the people of Hubris?’ asked
     Carpel.

     ‘The people, the authorities, you... everyone. This is the Emperor’s work.
     Will you shrink from it?’

     ‘No sir, I will not!’ snapped Carpel.

     ‘Excellent.’

     Carpel tossed a gold solar-form badge to me. It was heavy and old, mounted
     on a pad of black leather.

     ‘This will give you authority. My authority. Conduct your work thoroughly
     and quickly. I ask two things in return.’

     ‘And they are?’

     ‘You report all findings to me. And you allow the chastener to accompany
     you.’

     ‘I work my own way—’

     ‘Fischig can open doors and voiceboxes here in the Sun-dome that even that
     badge may not. Consider him a local guide.’

     And your ears and eyes, I thought. But I knew he was under immense pressure
     from the nobility to produce results, so I said: ‘I will be grateful for
     his assistance.’

     ‘Where first?’ Fischig asked, down to business at once, a hungry look on
     his face. They want blood, I realised. They want someone to punish for the
     deaths, someone they can say they caught, or at least helped to catch. They
     want to share in whatever successes I have so that they can look good when
     the rest of their population wakes up to this disaster in a few months’
     time.

     I couldn’t blame them.

     ‘First,’ I said, ‘the mortuary.’
     --------------------
**** Guild Sinesias
     --------------------
     GUILD SINESIAS OWNED some of the most imposing premises in the commercial
     district of Dorsay. A spur of the Grand Canal actually fed in under the
     coloured glass portico of the main buildings, so that visiting traders
     could ran their skiffs inside and disembark under cover in a tiled and
     carpeted reception dock.

     Our grav-skiff carried us in, and we stepped out amid clusters of tall,
     thin, gowned traders from Messina, merchants from Sameter in ludicrously
     heavy hats and veils, and obese bankers from the Thracian hives.

     I strode ashore and turned to offer Bequin my hand. She nodded courteously
     as she left the skiff. I hadn’t briefed her much. The aristocratic airs and
     graces were her own spontaneous invention. Though I still loathed her, I
     admired her more with each passing moment. She was playing things
     perfectly.

     ‘Your name and business here, sire, madam?’ a Guild Sinesias chamberlain
     asked as he approached us. He was dripping in finery, gold brocaded gowns
     attiring every servant in the place. Augmetic implants blistered in place
     of his ears and he clutched a slate and stylus.

     ‘My name is Farchaval, a merchant from Hesperus. This is Lady Farchaval. We
     come to tender grain contracts with the high houses of this world, and we
     are told Guild Sinesias will provide us the necessary brokerage.’

     ‘Do you have a guild responser, sire?’

     ‘Of course. My contact was Saemon Crotes.’

     ‘Crotes?’ the chamberlain paused.

     ‘Oh, Gregor, I’m so bored.’ Bequin suddenly announced. ‘This is so, so very
     slow and dull. I want to cruise the canals again. Why can’t we go back and
     deal with those spirited fellows at Guild Mensurae?’

     ‘Later, my dearest,’ I said, delighted and wrong-footed by her
     improvisation.

     ‘You have already... visited another guild?’ the chamberlain asked quickly.

     ‘They were very nice. They brought me Solian tea.’ Bequin purred.

     ‘Let me escort you both,’ the chamberlain said at once. ‘Saemon Crotes is,
     of course, one of our most valued envoys. I will arrange an audience for
     you forthwith. In the meantime, please relax in this suite. I will have
     Solian tea sent up directly.’

     ‘And nafar biscuits?’ cooed Bequin.

     ‘But of course, madam.’

     He swept out and closed the double doors of the luxurious waiting room
     behind him. Bequin looked at me and giggled. I confess, I laughed out loud.

     ‘What got into you?’

     ‘You said we were monied merchants who expected the very best. I was just
     earning my salary.’

     ‘Keep it up,’ I said.

     We looked around the room. Gauze-draped windows ten metres high looked out
     over the Grand Canal, but they were insulated to keep the noise out. Rich
     tapestries dressed the walls between Sameter School oils that Maxilla would
     have loved to own.

     A burnished servitor brought in a tray of refreshments soon after that. It
     lowered it onto a marble-topped occasional table and trundled out.

     ‘Solian tea!’ Bequin squeaked, lifting the lid of a porcelain pot. ‘And
     nafar biscuits!’ she added with a smile, through the crumbs of the first
     one.

     She poured me a cup and I stood by the fireplace, sipping it, striking an
     appropriately haughty pose.

     The guild representative flew in through the doors a moment later. He was a
     small, spiky-haired man with flowing gowns and far too much jewellery. The
     Guild Sinesias brand mark was proudly displayed on his forehead.

     He was, the brand indicated, property.

     His name was Macheles.

     ‘Sire Farchaval! Madam! Had I known you were visiting, I would have
     cancelled meets to be here. Forgive my tardiness!’

     ‘I forgive it,’ I said. ‘But I’m afraid Lady Farchaval may be fast losing
     her patience.’

     Bequin yawned on cue.

     ‘Oh, that is not good! Not good at all!’ Macheles clapped his hands and
     servitors trundled in.

     ‘Provide the lady with whatever she requests!’ Macheles told them.

     ‘Ummm... vorder leaves?’ she said.

     ‘At once!’ Macheles instructed.

     ‘And a plate of birri truffles? Sautéed in wine?’

     I winced.

     ‘At once! At once!’ Macheles yelped, shushing the servitors out of the
     room.

     I stepped forward and put down my cup. ‘I’ll be straight with you, sir. I
     represent grain merchants on Hesperus, a significant cartel of grain
     merchants.’

     I handed him my holo-dent. It was fake, of course. Betancore and Aemos had
     run it up, using Aemos’s profound knowledge in general and his knowledge of
     Hesperus – gleaned from interviews with Maxilla – in particular.

     Macheles seemed impressed enough by my identification.

     ‘What sort of... size cartel are we talking about, sire?’

     ‘The entire western continent.’

     ‘And you offer?’

     I produced a sample tube from my pocket. ‘A gene-fixed strain of cereal
     that could be easily managed by many of your landowners now that their
     workforce is depleted. It is indeed a wonder.’

     The servitors reappeared, delivering Bequin’s delicacies.

     As she munched the soft-fleshed birri, she said, ‘The other guilds are
     bidding for this product, mister. I do hope Guild Sinesias won’t miss out.’

     Macheles shook the sample tube and looked at it.

     ‘Is this,’ he said, his voice dropping, ‘xenos cultured?’

     ‘Would that be a problem?’ I asked.

     ‘No, sire! Not officially. The Inquisition is of course very tight about
     such things. But that is precisely why we offer these discreet interviews.
     The entire guild buildings are buffered against trackers, intercept beams
     and vox-thieves.’

     ‘I am pleased to hear it. So a xenos-cultured cereal strain would not be
     hard to market?’

     ‘Naturally not. There are collective enterprises eager for assured crop
     yields. Especially those hot-housed by alien technology.’

     ‘Good,’ I lied. ‘But I want the best return. Saemon told me that House Glaw
     should be the first to approach.’

     ‘Saemon?’

     ‘Saemon Crotes. The Guild Sinesias envoy I dealt with on Hesperus.’

     ‘Quite so! You wish me to arrange a trade meeting with House Glaw?’

     ‘I think that’s what I said, didn’t I?’
     --------------------
**** Commodus Voke
     --------------------
     COMMODUS VOKE STARED at my rosette for a few lingering seconds, then looked
     away. I could feel the psychic throbbing of his rage.

     ‘We have a... conflict of jurisdiction,’ he managed to say, straightening
     his robes. His assistant, now back on his feet, stood in the corner of the
     chamber and gazed sullenly at me.

     ‘Then let us resolve it,’ I offered. ‘Explain to me why you invade my
     apartments in the dead of night.’

     ‘My work brought me to Gudrun eight months ago. An ongoing investigation, a
     complex matter. A rogue trader had come to my attention, one Effries
     Tanokbrey. I had begun to close my net around him when he was scared into
     flight and got himself killed. Simple cross-checking revealed that a grain
     merchant called Farchaval had somehow been instrumental in that incident.’

     ‘Farchaval is my cover here on Gudrun.’

     ‘You see fit to play-act and hide your true nature?’ he said scornfully.

     ‘We each have our methods, inquisitor,’ I replied.

     I’d never met the great Commodus Voke before, but his reputation preceded
     him. An intractable puritan in his ethic, almost leaning to the hard-line
     of the monodominants but for the fact of his remarkable psychic abilities.
     I believe something of a Thorian doctrine suited his beliefs. He had served
     as a noviciate with the legendary Absalom Angevin three hundred years
     before and since then had played a key role in some of the most thorough
     and relentless purges in sector history. His methods were open and direct.
     Stealth, co-operation and subterfuge were distasteful concepts to him. He
     used the full force of his status, and the fear it generated, to go where
     he pleased and demand anything of anyone to achieve his goals.

     In my experience, the heavy-handed, terror-inspiring approach closes as
     many doors as it smashes open. Frankly, it didn’t surprise me to learn he
     had already been on this planet for a full eight months.

     He looked at me as if I was something he had almost stepped in. ‘I am
     discomforted when I see inquisitors holding to the soft, cunning ways of
     the radical. That way heresy lies, Eisenhorn.’

     That made me start. I consider myself, as I have reported, very much of the
     puritanical outlook. Staunch, hard-line in my own way, though flexible
     enough to get the job done efficiently. Yet here was Voke gauging me as a
     radical! And at that moment, next to him, I felt I may as well be the most
     extreme, dangerous Horusian, the most artful and scheming recongregator.

     I tried to push past that. ‘We need to share more information, inquisitor.
     I’ll take a guess and say your investigation somehow involves the Glaw
     family.’

     Voke said nothing and showed no response, but I felt his assistant tense
     psychically behind me.

     ‘Our work is indeed clashing,’ I went on. ‘I, too, am interested in House
     Glaw.’ In short, simple terms I laid out the matter of Eyclone’s activities
     on Hubris, and drew the connection to Glaw and Gudrun by way of the
     mysterious Pontius.

     I had his interest now. ‘Pontius is just a name, Eisenhorn. Pontius Glaw on
     the other hand, is long dead. I served with worthy Angevin in the purge
     that destroyed him. I saw his corpse.’

     ‘Yet here you are, investigating the Glaws anyway.’

     He exhaled slowly, as if making his mind up. ‘After Pontius Glaw’s
     eradication, the House of Glaw made great efforts to distance itself from
     his heresy. But Angevin, rest his immortal soul, always suspected that the
     taint ran deeper and that the family was not free of corruption. It is an
     ancient house, and powerful. It is difficult to probe its secrets. But from
     time to time, over the past two hundred years, I have turned my eye to
     them. Fifteen months ago, prosecuting a coven on Sader VII, I uncovered
     traces which suggested that particular coven, and several other minor
     groups, were collectively being run by an all but invisible parent cult – a
     cult of great scope and power, old and hidden, stretching across many
     worlds. Some traces led to Gudrun. That Gudrun is the Glaw’s ancestral home
     was for me too much of a coincidence.’

     ‘Now we make progress,’ I said, sitting down in a high-backed chair and
     pulling on a shirt Bequin brought to me from my chamber. Aemos poured six
     glasses of amasec from a decanter on the dresser. Taking one as it was
     offered, Voke sat down opposite me. He sipped, contemplatively.

     His assistant refused the glass that Aemos offered and remained standing.

     ‘Sit down, Heldane!’ Voke said. ‘We have things to learn here.’

     The assistant took a glass and sat in the corner.

     ‘I hunt out a cabal controlled by a notorious facilitator,’ I continued, ‘a
     cabal set on performing an abominable crime. The trail leads to Gudrun and
     the Glaws. You do the same with another heretical cell—’

     ‘Three others, in fact,’ he corrected.

     ‘Three, then. And you see the shape of a far greater organisation. From the
     facts as they stand, we are both approaching the same evil from opposite
     sides.’

     He licked his lips with a tiny, pallid tongue and nodded. ‘Since coming to
     Gudrun I have rooted out and burned two heretical cells. I am reasonably
     sure of the activities of another nine, three here in Dorsay alone. I have
     allowed them to fester as I observe them. For months, they have seemed bent
     on preparation for some event. Abruptly, a matter of weeks ago, their
     behaviour changed. This would have been around the same time as your
     confrontation on Hubris.’

     ‘Eyclone’s undertaking was also great, with extensive preparatory work.
     Yet, at the eleventh hour, something either went wrong or plans were
     suddenly changed. Though I defeated and destroyed him, his plans were
     really thwarted by the fact that the Pontius didn’t arrive. What has your
     work revealed of House Glaw?’

     ‘I have visited them twice in three months. On both occasions, they have
     made every effort to answer my questions, allowing me to search the estate
     and their records. I have found nothing.’

     ‘I fear, perhaps, that is because they knew they were dealing with an
     inquisitor. Tomorrow, Sire Farchaval has a trade meeting with the Glaws at
     their estate.’

     He mused on this. ‘The Inquisition has a duty to stand together, firmly,
     against the arch-enemies of mankind. In the spirit of co-operation, I will
     wait and see what your dubious methods reveal. Precious little, I imagine.’

     ‘In the spirit of co-operation, Voke, I will share all I learn with you.’

     ‘You will do better than that. The Glaws know me, but not all of my
     students. Heldane will go with you.’

     ‘I don’t think so.’

     ‘I insist. I will not have years of work ruined by another agency such as
     yourself running rough-shod through the matter. I require my own observer
     on the ground, or my co-operation will not be extended.’

     He had me in a vice and he knew it. To refuse outright would simply confirm
     my radical, careless approach in his eyes. And I had no wish to draw
     battlelines against another of the Inquisition, especially a man as
     powerful and influential as Commodus Voke.

     ‘Then he had better do exactly as I instruct him,’ I said.
     --------------------
**** Preparation for 56-Izar
     --------------------
     I HAD ONE last visitor, a day or two before I was finally able to walk and
     go about my business uninterrupted by periods of fatigue. Heldane wheeled
     him in on a wire-spoked carrier chair.

     Voke was shrunken and ill. He could only speak by way of a vox-enhancer. I
     was sure he would be dead in a matter of months.

     ‘You saved me, Eisenhorn,’ he husked, haltingly, through the vox augmetic.

     ‘The astropaths made it possible for us to live,’ I corrected.

     Voke shook his gnarled, sunken head. ‘No... I was lost in a realm of
     damnation, and you pulled me back. Your voice. I heard you call my name and
     it was enough. Without that, without that voice, I would have succumbed to
     the warp.’

     I shrugged. What could I say?

     ‘We are not alike, Gregor Eisenhorn,’ he continued, tremulously. ‘Our
     concept of inquisition is wildly at variance. But still I salute your
     bravery and your dedication. You have proven yourself in my eyes. Different
     ways, different means, is that not the true ethic of our order? I will die
     peacefully – and soon, I think – knowing men such as you maintain the
     fight.’

     I was honoured. Whatever I thought of his modus operandi, I knew our
     purposes pointed in the same direction.

     With a weak gesture he beckoned Heldane forward. The man’s raw, damaged
     head was no prettier than when I had last seen it.

     ‘I want you to trust Heldane. Of all my students, he is the best. I intend
     to recommend his elevation to the level of high interrogator, and from
     there, inquisitional rank beckons. If I die, look to him for my sake. I
     have no doubt the Inquisition will benefit from his presence.’

     I promised Voke I would do so, and this seemed to please Heldane. I didn’t
     like the man much, but he had been resilient and unfaltering in the face of
     savage death, and there was no doubting his ability or dedication.

     Voke took my hand in his sweaty claw and rasped ‘Thank you, brother.’
     --------------------
     AS IT TURNED out, Commodus Voke lived on for another one hundred and three
     years. He proved nigh on impossible to kill. When Golesh Constantine
     Pheppos Heldane was finally elected to the rank of inquisitor, it was all
     Voke’s doing. The sins of the father, as they say.
     --------------------
     INVASION TRAINING BEGAN three weeks off 56-Izar. Initially, Admiral
     Spatian’s plan was for a fleet action, a simple annihilation of any targets
     from orbit. But Lord Rorken and the Deathwatch insisted that a physical
     invasion was required. The recovery and destruction of the xenos Necroteuch
     had to be authenticated, or we would never know for sure that it was truly
     gone. Only after that objective was achieved could extreme destructive
     sanction be unleashed on 56-Izar.

     All that could be learned from my associates and the surviving Gudrunites
     concerning the saruthi tetrascapes – ironically, we were using Malahite’s
     term by then – was collated during a scrupulously searching series of
     interviews conducted by naval tacticians and Brytnoth, the Deathwatch’s
     revered librarian and strategist.

     The collected information was profiled by the fleet’s cogitators, and
     simulations created to acclimatise the ground forces. To my eyes, the
     simulations conveyed nothing of the wrongness we had experienced on the
     world of the plateau.

     Brytnoth himself conducted my interviews, accompanied by Olm Madorthene.
     Shaven-headed, a giant of a man even without his armour, Brytnoth was
     nevertheless cordial and attentive, addressing me with respect and
     listening with genuine interest to my replies. I tried to do verbal justice
     to my memories of the experience, and additionally related the theories
     that Malahite had expounded during that fateful séance.

     Eschewing the luxury of a servitor scribe or clerk, Brytnoth made his own
     notes as he listened. I found myself engrossed watching the warrior’s paw
     working the dwarfed stylus almost delicately across the note-slate.

     We sat in my apartments for the sessions, which often lasted hours. Bequin
     brought in regular trays of hot mead or leaf infusions, and Brytnoth
     actually extended his little finger as he lifted the porcelain cups by the
     handle. He was to me the embodiment of war in peacetime, a vast power bound
     into genteel behaviour, striving to prevent his awesome strength from
     breaking loose. He would lift the cup, small finger extended, consult his
     notes and ask another question before sipping.

     The fact that small finger was the size and shape of an Arbites’ truncheon
     was beside the point.

     ‘What I’m trying to establish, brother inquisitor, is whether the
     environments of the saruthi xenos will hinder our forces or deprive them of
     optimum combat efficiency.’

     ‘You can be sure of that, brother librarian.’ I poured some more Olicet tea
     from the silver pot. ‘My comrades were disoriented for the entire duration
     of the mission, and the Gudrunite riflemen had broken because of the place
     more than anything else. There is a wrongness that quite disarms the
     senses. It had been conjectured by some that this is a deliberate effect
     used by the saruthi to undermine sentients used to three physical
     dimensions, but the traitor Malahite made more sense in my opinion. The
     wrongness is a by-product of the saruthi’s preferred environments. We can
     expect the effect to be the norm on any homeworld of theirs.’

     Brytnoth nodded and noted again.

     ‘I’m sure your chapter’s experience and specialised sensor equipment will
     be a match for it,’ put in Madorthene. ‘Myself, I’m worried about the
     guard. They’ll be the mainstay of this action.’

     ‘They’ve all seen the preliminary briefing simulations,’ Brytnoth murmured.

     ‘With respect, I have too and they hardly do justice to the places we will
     find ourselves in.’ I looked across the table into Brytnoth’s face. His
     rugged features were sunken and colourless, the common trait of one who
     spends most of his life hidden within a combat helmet. His hooded eyes
     regarded me with interest. What wars, what victories, had those eyes
     witnessed, I wondered. What defeats?

     ‘What do you suggest?’ Brytnoth asked.

     ‘Adverse cross-training,’ I replied. I’d thought about it long and hard.
     ‘Olm here knows I’m no military man, brother-librarian, but that’s the way
     it seems to me. Make the troops practise overburden and off-balance.
     Blindfold them in some exercises, cuff them in others, alter gravity in the
     training vaults. Make the weighted packs they carry off centre and awkward.
     Switch light levels without warning. Crank the temperature and air pressure
     up and down. Simply make it hard for them. Train them to run, cover, shoot
     and reload in off-putting extremes. Make them learn all their essential
     combat procedures so well they can do them anywhere, under any
     circumstances. When they hit the ground at 56-Izar, let the fight be all
     they worry about. Everything else should be instinctive.’

     Madorthene smiled confidently. ‘The infantry forces at our disposal are
     primarily navy troopers and Mirepoix light elite from the Imperial Guard,
     seasoned soldiers all, unlike the poor Gudrunite foundees you had to
     nursemaid, Gregor. We’ll put them through the hoops and raise their game
     for the big push. They’ve got the combat hours and the balls to do it.’

     ‘Don’t stint,’ I warned Madorthene. ‘And those foundees you refer to –
     Sergeant Jeruss and his men. I want them with me when I go in.’

     ‘Gregor! We can give you a crack squad of Mirepoix who—’

     ‘I want the Gudrunite survivors.’

     ‘Why?’ asked Brytnoth.

     ‘Because whatever their combat inexperience, they’ve seen a tetrascape.
     Those are the men I want at my side.’

     Madorthene and Brytnoth exchanged glances, and the procurator shrugged. ‘As
     you wish.’

     ‘As for the others, like I said, don’t stint on the training regime.’

     ‘We won’t!’ he chuckled, mock-outraged at the idea. ‘The drill masters will
     work the regiments so hard, they’ll yearn for real battle.’

     ‘I’m serious,’ I said. ‘Every man that deploys on to 56-Izar – the
     venerated Deathwatch chapter included, Emperor bless them – should be ready
     to lose control of his senses, his judgment, his fortitude and even his
     basic mental faculties. They’re going to be hit hard, but in an insidious
     way. I don’t care if every man jack of them forgets his own mother’s name
     and wets himself, they must still know how to hold a line, fire and reload,
     adore the Emperor and respond to orders.’

     ‘Succinctly put,’ Brytnoth said. ‘I will, of course, temper your proposals
     before I put them to my battle brothers.’

     ‘I don’t care what you tell them,’ I chuckled, ‘as long as you don’t let on
     who it came from.’

     ‘Your anonymity is assured,’ He smiled. A wonder, that. I consider myself
     one of the very few mortals to have made a librarian of the Adeptus
     Astartes smile. To have seen a librarian of the Adeptus Astartes smile
     even.

     Brytnoth pushed his slate and stylus aside and looked over at me with
     curiosity. ‘Mandragore,’ he said.

     ‘The bastard child of the Emperor? What of him?’

     ‘I’m told you killed him yourself. In single combat. Quite a feat for one
     such as you – and I mean no disrespect.’

     ‘No disrespect is taken.’

     ‘How did you do it?’ he asked frankly.

     I told him. I kept it simple. Brytnoth made no reaction but Madorthene was
     quietly agog.

     ‘Brother-Captain Cynewolf will be fascinated,’ Brytnoth said. ‘I promised
     him I’d find out the details. He was dying to ask you about it, but he
     didn’t dare.’

     Now that was funny.
     --------------------
**** Tantalid
     --------------------
     AS I WORKED my way back to health, I considered Tantalid. Arnaut Tantalid
     had risen from the rank of confessor militant in the Missionaria Galaxia
     seventy years before to become one of the Ministorum’s most feared and
     ruthless witch-hunters. Like many of his breed, he followed the doctrines
     of Sebastian Thor with such unswerving precision it bordered on clinical
     obsession.

     To most of the common folk of the Imperium, there would be blessed little
     to choose between an Ordo Xenos inquisitor such as myself and an
     ecclesiarchy witchkiller like Tantalid. We both hunt out the damning
     darkness that stalks mankind, we are both figures of fear and dread, we are
     both, so it seems, laws unto ourselves.

     Twinned though we may be in so many ways, we could not be more distinct. It
     is my personal belief that the Adeptus Ministorum, the Imperium’s vast
     organ of faith and worship, should focus its entire attention on the
     promulgation of the true church of the God-Emperor and leave the
     persecution of heretics to the Inquisition. Our jurisdictions often clash.
     There have, to my certain knowledge, been two wars of faith in the last
     century provoked and sustained by just such rivalry.

     Tantalid and I had locked horns twice before. On Bradell’s World, five
     decades earlier, we had faced each other across the marble floor of a synod
     court, arguing for the right to extradite the psyker Elbone Parsuval. On
     that occasion, he had triumphed, thanks mainly to the strict Thorian
     mindset of the Ministorum elders of Bradell’s World.

     Then, just eight years ago, our paths had crossed again on Kuuma.

     Tantalid’s fanatical hatred – indeed, I would venture, fear – of the psyker
     was by then insurmountable. I made no secret of the fact that I employed
     psychic methods in the pursuit of my work. There were psychic adepts in my
     staff, and I myself had worked to develop my own psychic abilities over the
     years. Such is my right, as an authorised bearer of the Inquisition’s seal.

     In my eyes, he was a blinkered zealot with psychotic streak. In his, I was
     the spawn of witches and a heretic.

     No courtroom argument for us on Kuuma. A little war instead. It lasted an
     afternoon, and raged through the tiered streets of the oasis town at Unat
     Akim.

     Twenty-eight latent psykers, none older than fourteen, had been rooted out
     of the population of Kuuma’s sprawling capital city during a purge, and
     sequestered prior to their collection by the Black Ships. They were
     recruits, a precious resource, untainted and ready to be shaped by the
     Adeptus Astropathicus into worthy servants of the God-Emperor. Some of
     them, perhaps, would have the ultimate honour of joining the choir of the
     Astronomican. They were frightened and confused, but this was their
     salvation.

     Better to be found early and turned to good service than to remain
     undetected and become tainted, corrupt and a threat to our entire society.

     But before the Black Ships could arrive to take them, they were spirited
     away by renegade slavers working in collusion with corrupt officials in the
     local Administratum. Vast sums could be made on the black market for
     unregistered, virgin psychic slaves.

     I followed the slavers’ trail across the seif dunes to Unat Akim with the
     intention of liberating the youngsters. Tantalid made his way there to
     exterminate them all as witches.

     By the end of the fight, I had driven the witchfinder and his cohorts,
     mostly foot soldiers of the Frateris Militia, out of the oasis town. Two of
     the young psykers had been killed in the crossfire, but the others were
     safely transferred into the hands of the Astropathicus.

     Tantalid, fleeing Kuuma to lick his wounds, had tried to have me declared
     heretic, but the charges were swiftly overturned. The Ministorum had, at
     that time, no wish to court conflict with their allies in the Inquisition.

     I had expected, known even, that Tantalid would return sometime to plague
     me. It was a personal matter now, one which his fanatical disposition would
     fix upon and transform into a holy calling.

     But the last I had heard, he had been leading an ecclesiarchy mission into
     the Ophidian sub-sector in support of the century-long Purge Campaign
     there.

     I wondered what had brought him to Lethe Eleven at so inopportune a moment.
     --------------------
**** Sea Terrace Politics
     --------------------
     THE SEA TERRACE was probably the main reason I had leased the Ocean House
     in the first place. It was a long, ceramite-vaulted hall with one entire
     wall made of armoured glass looking into the ocean. The industrialisation
     of Thracian Primaris had killed off a great part of the world’s sea-life,
     but at these depths, hardy survivors such as luminous deep anglers and
     schools of incandescent jellies could still be glimpsed in the emerald
     nocturnal glow. The candlelit room was washed by a rippling green
     half-light.

     Jarat’s servitors had set the long table for nine and those nine were
     already taking their seats and chatting over preprandial drinks as I
     arrived. Like most of them, I had dressed informally, putting on a simple
     black suit. The kitchen provided steamed fubi dumplings and grilled
     ketelfish, followed by seared haunches of rare, gamey orkunu, and then pear
     and berry tarts with a cinnamon jus. A sturdy Gudrunite claret and sweet
     dessert wine from the vineyards of Messina complemented the food perfectly.
     I had forgotten the excellent qualities of the house Jarat ran for me, so
     far away from the hardship of missions in the field.

     Around the table with me were Aemos, Bequin, Ravenor, von Baigg, my
     rubricator and scribe Aldemar Psullus, Jubal Kircher, the head of household
     security, a trusted field agent called Harlon Nayl, and Thula Surskova, who
     was Bequin’s chief aide with the Distaff. Medea Betancore had chosen not to
     join us, but I knew the intensity of the piloting chores down through
     Thracian airspace had undoubtedly worn her out.

     I was pleased to see that Ravenor was present. His injuries were healing,
     the physical ones at least, and though he was quiet and a little withdrawn,
     I felt he was beginning to come through the shock of Arianrhod’s death.

     Surskova, a short, ample woman in her forties, was quietly briefing Bequin
     on the progress of the newer Distaff initiates. Aemos chuntered on to
     Psullus and Nayl about the events on Lethe Eleven and they listened
     intently. Psullus, enfeebled and prematurely aged by a wasting disease,
     never left the Ocean House and devoted his life to the maintenance and
     preservation of my extensive private libraries. If Aemos hadn’t related the
     story of our last mission to him, I would have made sure I did. Such tales
     were his only connection to the active process of our business and he loved
     to hear them. Nayl, an ex-bounty hunter from Loki, had been injured on a
     mission the year before and had not been able to join us for the Lethe
     endeavour. He too lapped up Aemos’s account, asking occasional questions. I
     could tell he was itching to get back to work.

     Von Baigg and Kircher chatted idly about the preparations for the Novena
     that were now gripping the hives of Thracian, and the security consequences
     they brought. Kircher was an able man, ex-arbites, and dependable if a
     little unimaginative. As dessert was served, the discussion broadened
     across the table.

     ‘They say the Bestowment will be the making of the Warmaster,’ Nayl said,
     his loaded spoon poised in front of his mouth.

     ‘He’s made already, I’d say,’ I retorted.

     ‘Nayl’s right, Gregor. I heard that too,’ said Ravenor. ‘Feudal Protector.
     That’s as good as Imperial Lord Commander Helican admitting the Warmaster
     is on an equal footing with him.’

     ‘It’s a sinecure.’

     ‘Not at all. It makes Honorius the favourite to become warmaster-in-chief
     in the Acrotara theatre now that Warmaster Hiju is dead, and Hiju was being
     groomed for a place on the Senatorum Imperialis, perhaps even to sit
     amongst the High Lords of Terra.’

     ‘Honorius may be “Magnus”, but he’s not High Lord material,’ I ventured.

     ‘After this he might be,’ said Nayl. ‘Lord Commander Helican must think he
     has potential, or he wouldn’t be giving him such an almighty hand up.’

     Politics left me cold, and I seldom empathised with political ambitions. I
     only studied the subject because my duties often demanded a detailed
     working knowledge. Imperial Lord Commander Helican, which is to say Jeromya
     Faurlitz IV of the noble Imperial family Faurlitz, was the supreme secular
     authority in the Helican sub-sector, for which reason he styled himself
     with the sub-sector’s name in his appellation. On paper, even the cardinals
     of the Ministorium, the Grandmaster of the Inquisition, the senior
     luminaries of the Administratum and the Lords Militant had to answer to
     him, though as with all things in Imperial society, it was never as easy as
     that. Church, state and military, woven together as one, yet constantly
     inimical. In favouring Warmaster Honorius with the Bestowment, Lord Helican
     was throwing his lot in with the military – an overt signal to the other
     organs of government – and clearly expected the Warmaster to return the
     favour when he rose to levels of government beyond those of a single
     sub-sector. It was a dangerous game, and rare for so senior an official to
     play openly for such an advantage, though the battle-glory that surrounded
     Honorius made a perfect excuse.

     And that made it a dangerous time. Somebody would want to redress that
     balance. My money would be on the Ecclesiarchy, though it’s fair to say I’m
     biased. However, history has shown the Church to be chronically intolerant
     of losing power to the military or the state. I said as much.

     ‘There are many other elements,’ Aemos chuckled, accepting a refill of
     dessert wine. ‘The Faurlitz line is weak and lacks both support in the
     Adeptus Terra and a ready ear at the Senatorum Imperialis and the courts of
     the Golden Throne. Two powerful families, the De Vensii and the Fulvatorae,
     are seeking to make gains against the Faurlitz, and would take this as an
     open show of defiance. Then there’s the House of Eirswald, who see their
     own famous son, Lord Militant Strefon, as the only viable replacement for
     Hiju. And the Augustyn dynasty, let’s not forget, who were ousted from
     power when High Lord of Terra Giann Augustyn died in office forty years
     ago. They’ve been trying to get back in with feverish determination these
     last few years, pushing their candidate, Lord Commander Cosimo, with almost
     unseemly impudence. If Nayl’s right and the Bestowment makes Honorius a
     certainty as Hiju’s successor, he’d become a direct competitor with Cosimo
     for the High Lord’s vacant position.’

     Down the table, Bequin yawned and caught my eye.

     ‘Cosimo’s never going to make it,’ Psullus put in candidly. ‘His house is
     far too unpopular with the Adeptus Mechanicus, and without their consent,
     however tacit, no one ever makes it to High Lord rank. Besides, the
     Ministorum would block it. Giann Augustyn made no friends there with his
     reforms. They say it was a Callidus of the Officio Assassinorum, under
     orders from the Ecclesiarchy, that took old Giann off, not a stroke at
     all.’

     ‘Careful what you say, old friend, or they’ll be sending one after you,’
     Ravenor said. Psullus held up his bony hands in a dismissive gesture as
     laughter rippled around the table.

     ‘It is, still, most perturbatory,’ Aemos said. ‘This Bestowment could lead
     to a House war. Quite apart from all the obvious opponents, Lord Helican
     and the Warmaster could find themselves tasked by Imperial families who are
     thus far neutral. There are many who are quite comfortable with their
     situation, and who would strike with astonishing ruthlessness simply to
     avoid being drawn into an open bloody clash.’

     There was silence for a moment.

     ‘Psullus,’ said Ravenor quickly, changing the subject with a diplomat’s
     deftness, ‘I have a number of works for you that I collected on Lethe,
     including a palimpsest of the Analecta Phaenomena...’

     Psullus engaged the young interrogator eagerly. Aemos, von Baigg and Nayl
     continued to debate the Imperial intrigue. Bequin and Surskova made their
     goodnights and withdrew. I took my crystal balloon of amasec to the glass
     wall and looked out into the oceanic depths. Kircher joined me after a
     moment. He smoothed the front of his navy blue jacket and put on his black
     gloves before speaking.

     ‘We had intruders last month,’ he said quietly.

     I looked round at him. ‘When?’

     ‘Three times, in fact,’ he said, ‘though I didn’t realise that until the
     third occasion. During night cycle about six weeks ago, I had what seemed
     to be a persistent fault on the alarms covering the seawall vents. There
     was no further sign, and the servitors replaced that section of the system.
     Then again, a week later, on the service entrance to the food stores, and
     the outer doors of the Distaff annex, both on the same night. I suspected a
     system corruption, and planned an overhaul of the entire alarm net. The
     following week, I found the security code on the outer locks of the main
     door had been defaulted to zero. Someone had been in and left again. I
     scoured the building and found vox-thieves buried in the walls of six
     rooms, including your inner chambers, and discreet farcoders wired into
     three communication junction nodes, spliced to vox and pict lines. Someone
     had also tried, and failed, to force their way into your void-vault, but
     they didn’t know the shield codes.’

     ‘And there were no traces?’

     ‘No prints, no microspores, no follicles. I washed the air itself through
     the particle scrubber. The in-house pict recorders show nothing... except a
     beautifully disguised time-jump of thirty-four seconds. The astropaths
     sensed nothing. In one place, the intruder must have walked across four
     metres of under-floor pressure pads without setting them off. In
     retrospect, I realised the two prior incidents, far from being system
     faults, were experimental tests to probe, gauge and estimate our security
     net. Trial runs before the actual intrusion. For that, they used a code
     scrambler on the main doors. If they’d actually been able to crack it, they
     could have reset the code and I’d never have known they’d been in.’

     ‘You’ve double-checked everything? No more bugs to be found?’

     He shook his head. ‘Lord, I can only apologise for—’

     I held tip a hand. ‘No need, Kircher. You’ve done your job. Show me what
     they left.’
     --------------------
**** Inquisitional Councils
     --------------------
     PIECES NOW FELL into place. The sheer scale of the triumph celebrations,
     the magnitude of the Novena, were appropriate enough, but the number of
     senior inquisitors summoned to attend was heavy handed to say the least.
     Military and Ecclesiarch luminaries may be ordered around to swell such
     events, but inquisitors are a different breed, more aloof, more...
     independent. It is unusual for us to be called together in any great
     gathering, particularly by such incontestable orders. I had presumed Orsini
     was throwing his weight around to impress the Lord Commander Helican.

     But that was not the case. There was to be an Apotropaic Congress. That is
     why we had been called here.

     Apotropaic studies are conducted all the time by the Inquisition, and
     usually involve one or perhaps as many as three inquisitors. On a larger
     scale, they are named Councils, and require a quorum of at least eleven
     inquisitors. Larger than that, they become a Congress. Such assemblies are
     extremely rare. I knew for a fact that my late master Hapshant had served
     on the last such Congress held in the sub-sector. That was two hundred and
     seventy-nine years in the past.

     The purpose of these studies, even at their smallest level, is the acute
     examination and assessment of unusually valuable captives. Once in the
     custody of the Inquisition, a rogue psyker, a charismatic heretic, an alien
     warlord... whatever... undergoes a sometimes lengthy formal examination
     quite separate from the dissection of his or her actual crimes. They are
     often already condemned and only waiting for sentence to be carried out. At
     that stage, the Inquisition wishes to expand its own learning, to
     understand more precisely the nature of the enemies of mankind. The
     subjects are dissected, usually intellectually, sometimes psychically and
     occasionally literally, in order to discover their strengths, weaknesses,
     beliefs and drives. Vital truths have in this way been discovered by
     Apotropaic councils, truths that have armoured the servants of the Imperium
     for later clashes. To illustrate, the Imperial Guard’s famous victory over
     the Ezzel meta-breed was only successful thanks to methods of detecting
     their presence discovered by the examination of an Ezzel scoutform by the
     Apotropaic Council of Adiemus Ultima in 883.M40.

     The size of the inquiry depends on the number or magnitude of the subject.

     ‘Thirty-three heretic psykers of level alpha or above were captured by the
     Warmaster at Dolsene, during the final major engagement of the Ophidian
     Suppression,’ Rorken told me, showing me a data-slate. The security
     clearance on the slate was so high that even I was impressed. ‘Trained,
     somehow, to control and master the warp-spawned filth they channel, they
     formed the backbone of the Enemy’s high command defence, the beating heart
     of the adversary.’

     ‘How were they taken? Alive, I mean?’ It was astonishing. Untrained psykers
     are terrifying enough, their minds always carrying the horrendous potential
     to open up a gate into the immaterium, to let its daemons flood through
     into our universe. But these... these fiends, they had somehow learnt – or
     been trained – to focus their warp-spawned talents, to contain the daemons
     within themselves and use their damnable strength. My mind reeled at the
     threat they had posed, and posed still, though they were our prisoners.

     Rorken gestured to the slate in my hands. ‘You’ll find a summary of the
     incident there, appended to the main list. In brief, it was luck... luck,
     and the amazing courage of the Adeptus Astartes, working in conjunction
     with Inquisitors Heldane, Lyko and Voke.’

     ‘Voke... Commodus Voke.’

     ‘I forgot, you’re old friends, aren’t you? He was involved with the Glaw
     affair on Gudrun, just before the Schism.’

     ‘Old friends is probably pushing it. We worked together. We generated a
     mutual respect. I’ve seen him infrequently since then. I’m amazed the old
     dog is still alive.’

     ‘Alive, despite the prognoses of several generations of medicae experts.
     And still powerful. To achieve this, in his twilight years...’

     I nodded. Even a speed-reading of the incident suggested an act of near
     mythical valour. Voke’s service to the Emperor was, as ever, above and
     beyond any reasonable expectation of duty.

     ‘I know Heldane too. He was Voke’s pupil. So he’s finally made it to
     inquisitor rank too?’

     ‘For sixty years now... Eisenhorn, you lead a solitary life, don’t you?’

     ‘If you mean I don’t keep up with the comings and goings of elections and
     the businesses of other inquisitors, sir, yes. I do. I focus on my work,
     and the needs of my staff.’

     He smiled, as if indulging me. In truth, my attitude was not uncommon. As I
     have said, we of the Inquisition are an aloof, independent kind, and have
     little interest in the affairs of our colleagues. I saw another difference
     between myself and Rorken. Whatever my seniority, I was still an agent of
     the field, a worker, an achiever, who might be gone into the distant gulfs
     of the Halo Stars for months or even years at a time. His rank tied him to
     his palace, and wrapped him in the intrigues and mechanisms of the Imperial
     ruling classes in general and the Inquisition in particular.

     I remembered Commodus Voke as a poisonous old viper, but a determined ally.
     During the affair of the Necroteuch, believing himself to be on his
     deathbed, he had implored me to stand reference for his pupil Heldane. I
     had promised him that, though when Voke then proceeded to stay alive, I had
     never followed it through. He had been around to see that Heldane got his
     rosette.

     Heldane... I had never liked him at all.

     I’d never met Lyko, the third member of the glorious trio, but I knew him
     by reputation as an inquisitor whose star was very much in the ascendant.
     Their spectacular achievement on Dolsene would further all their careers
     magnificently.

     I read through the list of inquisitors summoned to form the Council, a list
     which included my name. There were sixty in all. Titus Endor was amongst
     them. So was Osma, and so was Bezier. Some names, like Schongard, Hand and
     Reiker, leapt out as men I had little wish to be in the same room with.
     Others – Endor, naturally, and Shilo, Defay and Cuvier – were individuals
     it would be a pleasure to see again.

     Some names I’d barely heard of, or never heard of at all; others were
     famous or infamous inquisitors who I knew only by reputation. It was quite
     an assembly, drawn from all over the sector.

     ‘My inclusion on this list?’ I began.

     ‘Is no surprise. You are a senior and respected member of our office.’

     ‘Thank you, sir. But I wonder, did Voke request me personally?’

     ‘He was going to,’ Rorken told me, ‘but you had already been nominated.’

     ‘By whom?’

     ‘Inquisitor Osma,’ he replied.
     --------------------
**** Lyko

     LYKO HAD BEEN a fool and had damned himself. The damaging revelation that
     it hadn’t been Esarhaddon who had been torched on the lawns of the Lange
     palace could have been circumvented if Lyko had kept his head. He could
     have claimed it a mistake, another example of the heretic psyker’s
     treachery.

     But Lyko had run. Out of fear, or chasing some timetable, I didn’t know.
     But he’d run and, in so doing, incriminated himself.

     I’d gone to his residence, a rented hab high in the spires of Hive Ten, the
     moment Inshabel had alerted me to the deceit. But Lyko had cleared out,
     taking his people with him. His hab was empty and abandoned, with just a
     few scatterings of trash left behind in the stripped rooms.

     I had set my staff to work tracing him, a tall order given the planet-wide
     data-access problems in the wake of the rioting. I had decided almost at
     once to pursue him alone, without informing the Inquisition. You may see
     this as odd, almost reckless. In a way, it was. But Lyko was an inquisitor
     of good repute, held in high regard, and with many friends. There was scant
     chance I could tell the ordos I was undertaking a hunt for him on the basis
     he was harbouring a notorious rogue psyker without the fact reaching him,
     or without his friends making trouble for me.

     Those friends of his, of course, included Heldane and Commodus Voke: the
     stalwart trio that had captured the thirty-three rogues on Dolsene in the
     first place. How empty that ‘heroic’ action now seemed to me. I had been so
     impressed when Lord Rorken had shown me the report. Perhaps the ‘capture’
     had been easy, or even staged, if Lyko was secretly in league with
     Esarhaddon. Perhaps it had all been part of an elaborate conspiracy to
     perpetrate the atrocity of Hive Primaris.

     I was dogged by grim, unanswerable speculations. I had no way to prove Lyko
     was corrupt, not even now, though I certainly suspected it. He might have
     been an unwitting pawn on Dolsene, or at the Lange palace, or he might have
     been in it all along. It was possible too that his departure from Thracian
     was a coincidence that I had misinterpreted. It wouldn’t have been the
     first time an inquisitor had moved undercover without announcement.

     It was even possible that he too had discovered the deceit after the event,
     and was moving fast following some lead to make amends for his mistake. Or
     that he was fleeing the shame... or...

     So many possibilities. I had to play the odds the safest way. I was sure
     Lyko was guilty to a greater or lesser extent, so I would follow him. Even
     if he was simply chasing Esarhaddon too, it would lead me in the right
     direction.

     And I couldn’t inform the Inquisition, or talk to Voke or Heldane. My
     uncertainty was such that I couldn’t even trust them not to be part of it.
     --------------------
     A COMPLEX TRAIL of almost subliminal clues had put me on his tail. I’ll
     spare you the bulk of the details, for they would merely document the
     painstaking tedium that is often the better part of an inquisitor’s work.
     Suffice to say, we searched and processed vox logs, and the broadcast
     archives of the local and planetary astropathic guilds. We watched ship
     transfers, orbital traffic, departure lists, cargo movements. I had
     personnel in the streets, watching key locations, asking off-the-record
     questions in trader bars, calling in favours from friends of friends,
     acquaintances of acquaintances, even one or too old adversaries. I hired
     trackers and bloodhounders, and took every scent trace I could from Lyko’s
     apartment. I had pheromone codes programmed into servitor skulls that I
     released into up-ports and orbital stations.

     I had well over a hundred personnel on my staff, many of them trained
     hunters, researchers or surveillancers, but I swear the sheer load of data
     would have burned out our brains.

     We would have failed without Aemos. My old savant simply rose to the
     challenge, never put off, never fatigued, his mind soaking in more and more
     information and making a thousand mental cross checks and comparisons every
     hour, tasks I couldn’t have managed in a day with a codifier engine and a
     datascope.

     He seemed, damn his old bones, to enjoy it.

     The clues came in, one by one. A shipment of cargo put into long-term
     storage in a holding house in Hive Eight and paid for by a debit transfer
     from one of Lyko’s known associates. A two-second pheromone trace in the
     departure halls of a commercial port down on the coast at Far Hive Beta. A
     fuzzy image captured from a Munitorium pict-watcher on the streets of Hive
     Primaris.

     A passenger on a manifest listing making an unnecessary number of
     interconnecting flights between up-ports before moving off planet, as if
     trying to lose pursuit.

     Then the key ones: a cursory excise exam of freight that registered the
     presence of psi-baffling equipment in an off-world shipment. A series of
     clumsily disguised and presumably hasty bribes to key longshoremen at the
     Primaris starport. A rogue trader vessel – the Princeps Amalgum – staying a
     day longer at high-anchor than it had logged permission to do, and then a
     sudden change in its course plans.

     Instead of a long run to the Ursoridae Reef, it was heading spinwards, via
     Front’s World, to the twist farms of Eechan.
     --------------------
**** Janissaries
     --------------------
     I considered this news. Vessor was a feral world on the rimward borders of
     the Antimar sub-sector that bred a small but hardy population famous for
     its vicious fighters. Attempts had been made to form a Guard regiment
     there, but the Vessorine were hard to control. It wasn’t that they lacked
     discipline, but they found loyalty to Terra too cerebral a concept. They
     were bonded into clan families, understanding simply the material wealth of
     land, property, homestead and weapons. As mercenaries, therefore, they
     excelled. They would fight, peerlessly, savagely and to the death, in the
     Emperor’s name, provided that name was stamped on high denomination
     coinage.
     --------------------
