50_cent                           : 1
a_j_hamilton                      : 1
a_o_martin                        : 1
a_wess_mitchell                   : 1
aaron_bady                        : 1
aaron_c_davis                     : 1
aaron_gilbreath                   : 1
aaron_hertzmann                   : 1
aaron_morrison                    : 1
aaron_reed                        : 1
aaron_siler                       : 1
aaron_swartz                      : 7
abbas_al_mussawi                  : 1
abdolkarim_soroush                : 1
abdou_maliq_simone                : 1
abdoumaliq_simone                 : 1 : abdou_maliq_simone
abe_fortas                        : 1
abi_wilkinson                     : 1
abraham_lincoln                   : 2
abraham_maslow                    : 3
abraham_ortelius                  : 1
abraham_vereide                   : 1
abu_mahdi_al_muhandi              : 1
adam_berger                       : 1
adam_conover                      : 1
adam_domby                        : 1
adam_harris                       : 1
adam_j_white                      : 1
adam_koszary                      : 1
adam_putnam                       : 1
adam_raymond                      : 2
adam_ruben                        : 1
adam_saltsman                     : 1
adam_satariano                    : 1
adam_serwer                       : 4
adam_smith                        : 2
adolfo_flores                     : 1
adolph_reed_jr                    : 1
adonte_washington                 : 1
adorno                            : 3
adrian_napier                     : 1
afua_hirsch                       : 1
agnels_sorel                      : 1
ahmaud_arbery                     : 3
ailes                             : 1 : roger_ailes
aimee_stephens                    : 1
al_capone                         : 1
al_weiwei                         : 1
alain_de_botton                   : 1
alain_locke                       : 1
alan_dershowitz                   : 3
alan_dix                          : 1
alan_freeman                      : 1
alan_kurdi                        : 1
alan_mcpherson                    : 1
alan_moore                        : 1
alan_newell                       : 1
alan_rickman                      : 1
alan_taylor                       : 1
alan_turing                       : 1
alan_watts                        : 1
alan_zucconi                      : 2
albert_camus                      : 2
alberto_cairo                     : 1
albertus_magnus                   : 1
alec_nevala_lee                   : 1
alec_snyder                       : 1
aleissia_laidacker                : 1
aleksander_hemon                  : 1
alessandro_cortini                : 1
alex_azar                         : 1
alex_byrne                        : 1
alex_emmons                       : 1
alex_fefegha                      : 1
alex_hanna                        : 1
alex_horton                       : 1
alex_jaffe                        : 1
alex_jones                        : 2
alex_konrad                       : 1
alex_kotch                        : 1
alex_moe                          : 1
alex_needham                      : 1
alex_tabarrok                     : 1
alex_thornton                     : 1
alex_zielinski                    : 1
alexander_2                       : 1
alexander_artikis                 : 5
alexander_george                  : 1
alexander_hamilton                : 4
alexander_stephens                : 1
alexander_zook                    : 2
alexandra_heal                    : 2
alexandra_petri                   : 1
alexandra_reeve_givens            : 1
alexandra_villarreal              : 1
alexandria_ocasio_cortez          : 3
alexey_radul                      : 1
alexis_de_tocqueville             : 4
alexis_kennedy                    : 5
alexis_madrigal                   : 1
alexis_rives                      : 1
alexsandr_barkovsky               : 1         :  alexsander_barkovsky
alfie_evans                       : 1
alfonso_cuaron                    : 1
alfred_casson                     : 1
alfred_e_neuman                   : 1
alfred_hitchcock                  : 1
alfred_ng                         : 1
alfred_north_whitehead            : 1
alfred_schutz                     : 1
alfred_wallace                    : 1
ali_shari_ati                     : 1
ali_spittel                       : 1
alia_wong                         : 1
alice_crites                      : 1
alice_denham                      : 1
alice_dreger                      : 1
alice_evans                       : 1
alice_goffman                     : 1
alice_goldfuss                    : 1
alice_munro                       : 1
alice_speri                       : 1
alice_sullivan                    : 1
alice_walker                      : 2
alicia_garza                      : 1
aliessia                          : 1  : aliessia_laidacker
aliessia_laidacker                : 1
alisha_jarwala                    : 1
alison_brie                       : 1
alison_flood                      : 1
allan_adam                        : 1
allan_sloan                       : 1
allan_weiland                     : 1
allen_ibrahim                     : 1
allie_brosh                       : 1
allison_hagan                     : 1
allison_parrish                   : 2
allison_roman                     : 1
allyson_hobbs                     : 1
alphonse_inoue                    : 1
alphonse_maddin                   : 2
althusser                         : 2  : louis_althusser
alton_sterling                    : 1
alvaro_huerta                     : 1
alvin_gouldner                    : 1
alvin_toffler                     : 1
alyse_galvin                      : 1
alyson_mcclaran                   : 1
alyssa_foote                      : 1
amanda_gorman                     : 1
amanda_palmer                     : 1
amber_case                        : 1
amber_phillips                    : 1
amelia_gentleman                  : 1
amika_george                      : 1
amin_maalouf                      : 1
amina_khan                        : 1
amit_patel                        : 1
amy_webb                          : 1
anais_duong_pedica                : 1
anastasia_yeschenko               : 1
anastatia_opara                   : 1
anders_hoff                       : 1
anderson_cooper                   : 1
andre_brock                       : 1
andre_donnel_cristian_cooper      : 1
andre_perry                       : 1
andrea_circle_bear                : 2
andrea_mitchell                   : 1
andrea_torres                     : 1
andreea_campeanu                  : 1
andres_guardado                   : 1
andrew_barto                      : 1
andrew_bennet                     : 1
andrew_coats                      : 1
andrew_delatolla                  : 1
andrew_ferguson                   : 1
andrew_gonzalez                   : 1
andrew_hanen                      : 1
andrew_heiss                      : 1
andrew_hugil                      : 1
andrew_jackson                    : 1
andrew_mccarthy                   : 2
andrew_plotkin                    : 2
andrew_reinhard                   : 1
andrew_roberts                    : 1
andrew_schmelyun                  : 1
andrew_selbst                     : 1
andrew_sullivan                   : 1
andrew_van_dam                    : 1
andrew_w_kahrl                    : 1
andrew_weissman                   : 1
andrew_yang                       : 3
andy_greenberg                    : 1
andy_harris                       : 1
andy_horowitz                     : 1
andy_kroll                        : 1
andy_miller                       : 1
andy_ngo                          : 5
andy_slavitt                      : 1
angel_leigh_mccoy                 : 1
angela_bryan                      : 1
angela_david                      : 1
angela_davis                      : 2
angela_giuffrida                  : 1
angela_merkel                     : 1
angela_ruiz_robles                : 1
angus_deaton                      : 1
ani_obrien                        : 1
anita_chan                        : 1
anita_sarkeesian                  : 1
anjali_dayal                      : 1
ann_coulter                       : 5
ann_crawford-roberts              : 1  : ann_crawford_roberts
ann_crawford_roberts              : 1
anna_anthropy                     : 7
anna_brones                       : 1
anna_fazackerley                  : 1
anna_jourdanous                   : 1
anna_massoglia                    : 1
anna_merlan                       : 1
anna_riedl                        : 1
anna_royal                        : 1
anne_anlin_cheng                  : 2
anne_applebaum                    : 1
anne_boleyn                       : 1
anne_case                         : 1
anne_elliott                      : 2
anne_frank                        : 1
anne_helen_petersen               : 1
anne_sexton                       : 1
annie_easley                      : 2
annie_karni                       : 1
anselm                            : 1
anthony_bourdain                  : 2
anthony_cormier                   : 1
anthony_giddens                   : 2
anthony_marcum                    : 2
anthony_weiner                    : 1
antigone_davis                    : 1
antisthenes                       : 1
antoine_banks                     : 1
antoine_helbert                   : 1
antonin_scalia                    : 1
antonio_gramsci                   : 3
antonio_negri                     : 1
antwon_rose                       : 1
anya_kamenetz                     : 1
AOC                               : 5  : alexandria_ocasio_cortez
aomartin                          : 1 : andrew_martin
aphex_twin                        : 2
apollonia_saintclair              : 1
april_de_simone                   : 1
april_glaser                      : 1
april_rosenblum                   : 1
aquinas                           : 1  : thomas_aquinas
aramis_ayala                      : 1
aranyo_aarjan                     : 1
arendt                            : 3  : hannah_arendt
arendy                            : 1  : hannah_arendt
argenis_hurtado_moreno            : 1
ari_berman                        : 1
ariana_grande                     : 1
aris_folley                       : 1
aristotle                         : 2
arnold_hendrick                   : 1
arseniy_kotiv                     : 1
art_spiegelman                    : 1
arthur_mitchell                   : 1
artie_ojeda                       : 1
arundhati_roy                     : 1
asa_hutchinson                    : 1
asha_bandele                      : 1
asha_ragappa                      : 1
ashanti_posey                     : 1
ashley_braun                      : 1
ashley_mears                      : 1
ashley_reese                      : 1
ashlyn_sparrow                    : 1
asim_qureshi                      : 2
asimov                            : 2  : isaac_asimov
asquith                           : 1  : h_h_asquith
assange                           : 1  : julian_assange
assia_djebar                      : 1
athabasca_chipewyan               : 1
atoss_abrahamian                  : 1
atwood                            : 1  : margaret_atwood
auguste_comte                     : 2
augustine                         : 1
augustus_osborne_lamplough        : 1
austin_frakt                      : 1
austin_jenkins                    : 1
autmn_peltier                     : 1  : autumn_peltier
autumn_peltier                    : 1
avery_alder                       : 1
axel_hartmann                     : 1
aya_hirata_kimura                 : 1
ayanna_pressley                   : 1
ayatollah_khomeini                : 1
ayla_jean_yackley                 : 2
ayn_rand                          : 1
b_f_skinner                       : 1
baars_franklin                    : 1
babbage                           : 1  : charles_babbage
bach                              : 2  : j_s_bach
bachman                           : 1  : charles_bachman
baffour_ankomah                   : 1
baked_alaska                      : 1
balin_brake                       : 1
baltar                            : 4  : gaius_baltar
banerjee                          : 1  : banny_banerjee
banny_banerjee                    : 1
banzhaf_powerl                    : 1
barabasi_albert                   : 1
barack_obama                      : 38
barbara_smith                     : 2
bari_weiss                        : 1
barisbi_alborov                   : 1
barnaby_rudge                     : 1
barry_eichengreen                 : 1
barry_goldman                     : 1
barry_goldwater                   : 1
bart_heijlen                      : 1
barthes                           : 3  : roland_barthes
bartosz_milewski                  : 1
bashar_assad                      : 1
bassem_saad                       : 1
bastien_girschig                  : 1
baudrillard                       : 3  : jean_baudrillard
baum_eagon                        : 1
beauvoir                          : 1  : simone_de_beauvoir
beck                              : 1
becky_birchmore                   : 1
belle_de_jour                     : 1
belly_mujinga                     : 1
ben_bauchau                       : 1
ben_blum                          : 2
ben_burt                          : 1
ben_cardin                        : 1
ben_fry                           : 1
ben_goldacre                      : 4
ben_golus                         : 2
ben_newell                        : 1
ben_schreckinger                  : 1
ben_shapiro                       : 7
ben_shaprio                       : 1  : ben_shapiro
ben_smee                          : 1
benjamin                          : 1  : walter_benjamin
benjamin_acosta                   : 1
benjamin_disraeli                 : 1
benjamin_grosof                   : 1
benjamin_netanyahu                : 1
benjamin_zephaniah                : 1
benjanun_sriduangkaew             : 1
bentham                           : 1  : jeremy_bentham
bently_ottmann                    : 1
berger                            : 1  : adam_berger
bergson                           : 1 : henri_bergson
berkman_klein                     : 2
bernie_dekoven                    : 1
bernie_sanders                    : 6
bertrand_meyer                    : 1
bertrand_russell                  : 2
bess_levin                        : 1
bessel_van_der_kolk               : 2
beth_leblanc                      : 1
beth_mandel                       : 2
beth_mole                         : 1
beth_skwarecki                    : 1
bethany_brookshire                : 2
beto_orourke                      : 1
betsy_de_vos                      : 2
betsy_devos                       : 2         :  betsy_de_vos
beyonce                           : 1
bharata_natyam                    : 1
BharataNatyam                     : 1  : bharata_natyam
bicchieri                         : 1  : christina_bicchieri
bill_barr                         : 2
bill_browning                     : 1
bill_buckley                      : 1
bill_clinton                      : 4
bill_cosby                        : 1
bill_gates                        : 5
bill_hader                        : 1
bill_jenkins                      : 1
bill_lee                          : 1
bill_morlin                       : 1
bill_moyers                       : 1
bill_nye                          : 2
bill_oreilly                      : 2
bill_rankin                       : 2
bill_scher                        : 1
billie_eilish                     : 2
billie_jean_king                  : 1
billy_bush                        : 1
billy_ciancaglini                 : 1
billy_steele                      : 1
bjorne_stroustrup                 : 1
blagojevich                       : 1  : rod_blagojevich
blair                             : 1 : tony_blair
blaire_white                      : 1
blaise_compaore                   : 1
blake                             : 1 : william_blake
bob_bassett                       : 1
bob_dylan                         : 2
bob_mazzer                        : 1
bob_van_voris                     : 1
bob_woodward                      : 1
bobby_riggs                       : 1
bobby_rush                        : 1
bobby_sands                       : 1
bobby_seale                       : 1
boden                             : 2  : margaret_boden
boehner                           : 1  : john_boehner
boethius                          : 1
boghossian                        : 1  : peter_boghossian
bogi_takacs                       : 1
bolaji_badejo                     : 1
bonnie_keeler                     : 1
bonnie_mckee                      : 2
bonnie_nardi                      : 1
bonny_brooks                      : 1
borges                            : 1 : jorge_luis_borges
boris_johnson                     : 12
bostock                           : 10 : mike_bostock
bourdieu                          : 17 : pierre_bourdieu
bourdieur                         : 1 : pierre_bourdieu
bourj_al_shamali                  : 1
bowlby                            : 1  : john_bowlby
brad_anderson                     : 1
brad_cox                          : 1
brad_heath                        : 1
brad_parscale                     : 1
brad_plumer                       : 2
brad_smith                        : 1
bradbury                          : 1  : ray_bradbury
bradley_bunn                      : 1
brandom                           : 4  : robert_brandom
brandon_saenz                     : 1
brandon_taylor                    : 1
brandy_jenson                     : 1  : brandy_jensen
brenda_braithwaite                : 1
brenda_laurel                     : 1
brenda_romero                     : 1
brendan_caldwell                  : 1
brendan_fraser                    : 1
brendan_keogh                     : 5
brendan_lake                      : 1
brendan_oconnor                   : 1
brent_staples                     : 1
brentin_mock                      : 1
breonna_taylor                    : 2
bret_stephens                     : 1
brett_crozier                     : 3
brett_kavanaugh                   : 6
briahna_gray                      : 1
brian_bergstein                   : 1
brian_encinia                     : 1
brian_eno                         : 2
brian_fargo                       : 1
brian_kemp                        : 2
brian_leveson                     : 1
brian_newlin                      : 1
brian_resnick                     : 2
brian_sanderson                   : 1
brian_wansink                     : 1
brianne_benness                   : 1
brindell_wilkins                  : 1
brittany_murphy                   : 2
brittany_smith                    : 1
brock_turner                      : 3
brody_condon                      : 1
brooke_magnanti                   : 1
bruce_bagley                      : 1
bruce_hill                        : 1
bruce_schneier                    : 2
bruce_sterling                    : 1
bruce_wydick                      : 1
brunner                           : 1 : john_brunner
bruno_dias                        : 2
bruno_iyda_saggese                : 1
bruno_latour                      : 4
bryan_cranston                    : 3
bryan_fuller                      : 1
bryan_hughes                      : 1
bryan_stevenson                   : 1
bryn_esplin                       : 1
brynn_anderson                    : 1
buckey_wolfe                      : 1
buckminster_fuller                : 1
bujangga_manik                    : 1
bunnie_huang                      : 1
burke                             : 2  : edmund_burke
burley                            : 1  : walter_burley
butch_locsin                      : 1
buttigieg                         : 1  : pete_buttigieg
byran_hughes                      : 1
byron                             : 1  : george_byron
byron_allen                       : 1
c_h_r_bailey                      : 1
c_j_ciaramella                    : 1
c_northcote_parkinson             : 1
cade_metz                         : 1
caitlin_flanagan                  : 1
caitlin_johnstone                 : 1
caitlin_logan                     : 1
caitlin_rosenthal                 : 1
caitlin_zaloom                    : 1
caleb_melby                       : 1
calum_chace                       : 1
calvin                            : 1 : john_calvin
calvin_duncan                     : 3
calvin_munerlyn                   : 1
calvino                           : 1  : italo_calvino
camara_jones                      : 1
cameron_kunzelman                 : 4
camus                             : 1  : albert_camus
candace_owens                     : 3
Capek                             : 1  : karel_capek
CAPT_PICARD                       : 1  : captain_picard
captain_america                   : 1
captain_picard                    : 1
captain_scarlett                  : 1
carl_disalvo                      : 1
carl_hasenpflug                   : 1
carl_malmud                       : 2
carl_rogers                       : 1
carl_schmitt                      : 1
carla_intal                       : 1
carlen_lavigne                    : 1
carlos_gregorio_hernandez_vasquez : 1
carlos_slim                       : 1
carlota_perez                     : 1
carlton_reeves                    : 2
carmack                           : 3  : john_carmack
carmen_ortiz                      : 1
carol_black                       : 1
carol_pinchefsky                  : 1
carolyn_van_houten                : 1
carrie_levinson                   : 1
casandra_butts                    : 1
casey_fiesler                     : 5
casey_muratori                    : 1
casey_newton                      : 2
cass_marshall                     : 1
cass_r_sunstein                   : 2
cassius_clay                      : 1
castelfranchi                     : 7  : christiano_castelfranchi
caster_semenya                    : 1
catherine_dIgnazio                : 2
catherine_hollander               : 1
catherine_pearson                 : 1
catherine_rampell                 : 1
catherine_tate                    : 1
catrin_nye                        : 1
cd_covington                      : 1
cecelia_holland                   : 1
cedar_attanasio                   : 1
celia_pearce                      : 1
ceridwen_dovey                    : 1
cerissa_riley                     : 1
cernovich                         : 1  : mike_cernovich
cesare_lombroso                   : 1
chad_hagen                        : 1
chad_mulligan                     : 1
chad_wolf                         : 1
chadwick_boseman                  : 1
chaminda_jayanetti                : 1
chanakya_sethi                    : 1
chanel_miller                     : 2
chantal_mouffe                    : 1
charlemagne                       : 1
charlene_carruthers               : 1
charles_babbage                   : 1
charles_bachman                   : 1
charles_darwin                    : 2
charles_dickens                   : 1
charles_grassley                  : 1
charles_II                        : 2
charles_kenny                     : 1
charles_kinsey                    : 1
charles_louis_montesquieu         : 1
charles_murray                    : 2
charles_payne                     : 1
charles_peirce                    : 1
charles_pierce                    : 1
charles_rabin                     : 1
charles_sacilotto                 : 1
charles_sheeler                   : 1
charlie_brooker                   : 1
charlie_kirk                      : 1
charlie_stross                    : 1
charlie_warzel                    : 2
charlize_theron                   : 1
chas_gillespie                    : 1
chaya_naor                        : 1
chelsea                           : 1
chelsea_manning                   : 5
chelsey_bonestell                 : 1
chelsey_carter                    : 1
chenyuan_liu                      : 1
cheree_peoples                    : 3
chester_doles                     : 1
chet_faliszek                     : 1
chevalied_d_eon                   : 1
chevalier_de_saint_georges        : 1
chief_martec                      : 1
chiefmartec                       : 1   : chief_martec
china_mieville                    : 5
chomsky                           : 8  : noam_chomsky
chris_avellone                    : 4
chris_cantwell                    : 1
chris_christie                    : 1
chris_coyier                      : 1
chris_crawford                    : 6
chris_d_angelo                    : 1
chris_dixon                       : 1
chris_dodd                        : 1
chris_fox                         : 1
chris_hecker                      : 2
chris_landry                      : 1
chris_lewis                       : 1
chris_martens                     : 5
chris_mathias                     : 1
chris_mcmurray                    : 1
chris_rossdale                    : 1
chris_simpson                     : 1
chris_stroop                      : 1
chris_vlatso                      : 1
chris_zubak_skees                 : 1
chrisstroop                       : 1  : chris_stroop
christian_donlan                  : 1
christian_nutt                    : 1
christian_vanderbrouk             : 1
christiane_gruber                 : 1
christiano_castelfranchi          : 7
christina_bicchieri               : 1
christina_hendricks               : 1
christine_ford                    : 4
christine_love                    : 5
christine_ro                      : 1
christopher_alexander             : 2
christopher_harrity               : 1
christopher_hasson                : 2
christopher_langton               : 1
christopher_lee                   : 1
christopher_moore                 : 1
christopher_paul                  : 1
christopher_revis                 : 2
christopher_walken                : 1
chritoph_schuringa                : 1 : christoph_schuringa
chuck_johnson                     : 2
chuck_schumer                     : 1
chuck_todd                        : 3
chuck_wendig                      : 1
cian_maher                        : 1
ciara_bryne                       : 1
ciara_wardlow                     : 1
cicely_tyson                      : 1
Cicero                            : 1 : marcus_tullius_cicero
cicero                            : 2 : marcus_tullius_cicero
ciel_fledge                       : 1
cindy_hyde_smith                  : 1
cj_hauser                         : 1
claire_burke                      : 1
claire_cain_miller                : 1
claire_malone                     : 1
clarence_cobbs                    : 1
clarence_thomas                   : 1
claude_jenkyns                    : 1
claude_shannon                    : 1
claus_wilke                       : 1
clayton_cubitt                    : 3
clement_haynsworth                : 1
cliff_bleszinski                  : 1
clifford_gertz                    : 2
clint_hocking                     : 3
clint_smith                       : 1
clinton                           : 11
clive_thompson                    : 1
clr_james                         : 1
coase                             : 1  : ronald_coase
cody_mello_klein                  : 1
coffeespoonie                     : 1
colbert                           : 1  : stephen_colbert
coleman                           : 1  : jenna_coleman
colin_kaepernick                  : 4
colleen_flaherty                  : 1
colleen_shalby                    : 1
colleen_taylor                    : 1
colleen_tighe                     : 1
collin_wiant                      : 1
colman_o_raghallaigh              : 1
coltrain                          : 1  : kelly_coltrain
comey                             : 2  : james_comey
commander_sisko                   : 1
conga_brazaville                  : 1   : congo_brazaville
congo_brazaville                  : 1
conor_friedersdorf                : 1
constance_markowitz               : 1
consuelo_arostegui_isaacson       : 1
conway                            : 3  : john_conway
cora                              : 1
coral_davenport                   : 1
coralina_ada                      : 1 : coraline_ada_ehmke
coraline_ada_ehmke                : 1
corbin_miller                     : 1
corbusier                         : 1  : le_corbusier
corbyn                            : 1  : jeremy_corbyn
corey_robin                       : 2
corina_ajder                      : 1
cory_booker                       : 1
cory_doctorow                     : 23
cory_doctorw                      : 1  : cory_doctorow
cory_maye                         : 1
cosby                             : 1  : bill_cosby
cotton_mather                     : 2
courtney_hagle                    : 1
courtney_irby                     : 1
courtney_weaver                   : 1
craig_brittain                    : 1
craig_perko                       : 1
craig_reynolds                    : 1
cranston                          : 3  : bryan_cranston
crawford                          : 1  : chris_crawford
cristian_danescu_niculescu_mizil  : 1
crockford                         : 2  : douglas_crockford
cudjo_lewis                       : 1
cynthia_koons                     : 1
cyntoia_brown                     : 1
dahlia_lithwick                   : 2
daisy_jones                       : 2
dalai_lama                        : 1
dale_lane                         : 1
dali                              : 2  : salvador_dali
damian_collins                    : 1
damien_gayle                      : 1
damnian_collins                   : 1  :  damian_collins
damon_centola                     : 1
damon_gameau                      : 1
dan_berger                        : 1
dan_berrett                       : 1
dan_brown                         : 4
dan_burns                         : 1
dan_coats                         : 1
dan_collyns                       : 1
dan_crenshaw                      : 1
dan_diamond                       : 1
dan_garcia                        : 1
dan_gilmor                        : 1
dan_horrigan                      : 1
dan_jurafsky                      : 6
dan_keating                       : 1
dan_meegan                        : 1
dan_mumford                       : 2
dan_shiffman                      : 1
dana_loesch                       : 1
dana_nessel                       : 1
dana_nuccitelli                   : 1
danah_boyd                        : 1
dani_donovan                      : 1
danica_mcadam                     : 1
daniel_aguirre_de_carcer          : 1
daniel_blake                      : 1
daniel_dennett                    : 2
daniel_drezner                    : 1
daniel_engber                     : 1
daniel_garber                     : 1
daniel_golding                    : 1
daniel_gonzalez                   : 1
daniel_katz                       : 1
daniel_kelly                      : 1
daniel_knight                     : 1
daniel_marx                       : 1
daniel_miskinis                   : 1
daniel_mullins                    : 1
daniel_sanchez                    : 1
daniel_shiffman                   : 2
daniel_vella                      : 1
daniel_webster                    : 1
daniel_ziblatt                    : 2
daniella_silva                    : 1
danielle_rindler                  : 1
danni_ashe                        : 1
danny_buerkli                     : 1
danny_devito                      : 1
danny_dorling                     : 1
danny_o_dwyer                     : 1
dante                             : 3 : dante_alighieri
danuta_danielsson                 : 1
danya_glabau                      : 2
danya_ruttenberg                  : 2
dao                               : 1  : peter_dao
darci_wilder                      : 1
darius_kazemi                     : 3
darlena_cunha                     : 1
darnell_gates                     : 1
darran_anderson                   : 2
darrell_issa                      : 1
darren_dahly                      : 1
darryl_pinckney                   : 1
darwin                            : 1  : charles_darwin
daryl_davis                       : 1
daryl_johnson                     : 1
daryll_forde                      : 1
dastani                           : 2  : mehdi_dastani
dave_brubeck                      : 1
dave_gershgorn                    : 1
dave_levitan                      : 1
dave_mark                         : 1
dave_morris                       : 1
dave_rupert                       : 1
dave_siegel                       : 1
dave_smith                        : 1
david_anderson                    : 2
david_armstrong                   : 3
david_astin_walsh                 : 1
david_attenborough                : 1
david_bevan                       : 1
david_bossie                      : 1
david_bowie                       : 3
david_brooks                      : 2
david_burdeny                     : 1
david_byrne                       : 2
david_cage                        : 1
david_cameron                     : 1
david_chalmers                    : 3
david_chapman                     : 5
david_churchill                   : 1
david_cope                        : 1
david_cronenberg                  : 1
david_crookes                     : 1
david_dacko                       : 1
david_davis                       : 1
david_dayden                      : 1
david_dobrik                      : 1
david_duke                        : 2
david_dunham                      : 1
david_fahrenthold                 : 1
david_frum                        : 1
david_gaider                      : 1
david_gelernter                   : 1
david_graeber                     : 16
david_gunkell                     : 1
david_harbour                     : 1
david_harshbarger                 : 1
david_hayter                      : 1
david_hilbert                     : 1
david_hilliard                    : 1
david_hume                        : 1
david_irving                      : 1
david_jaffe                       : 1
david_koch                        : 1
david_kocieniewski                : 1
david_krakauer                    : 1
david_kushner                     : 1
david_leonard                     : 1
david_leonhard                    : 1  : david_leonhardt
david_leonhardt                   : 3
david_lieb                        : 1
david_lowery                      : 2
david_lynch                       : 2
david_m_perry                     : 1
david_myers                       : 1
david_peitraszewski               : 1
david_perry                       : 2
david_petraeus                    : 1
david_pozen                       : 1
david_romer                       : 1
david_rose                        : 1
david_rosenhan                    : 3
david_rudlin                      : 1
david_rumsey                      : 1
david_sedaris                     : 2
david_smail                       : 1
david_snowden                     : 5
david_thomas                      : 1
david_vance                       : 1
david_voreacos                    : 1
david_ward                        : 1
david_whitehouse                  : 1
david_whitley                     : 1
davide_grossi                     : 1
davin_roth                        : 1
dawkins                           : 2  : richard_dawkins
de_blasio                         : 1
de_botton                         : 1  :  alain_de_botton
dean_burnett                      : 1
dean_spears                       : 1
deandre_levy                      : 1
debbie_nathan                     : 1
deblasio                          : 1         :  bill_de_blasio
deborah_small                     : 1
deborah_small asha_bandele        : 1  : deborah_small : asha_bandele
deborah_stone                     : 1
deen                              : 1  : james_deen
deidre_mccloskey                  : 1
deirdre_cooper_owens              : 1
deirdre_gentner                   : 3
deleuze                           : 6  : gilles_deleuze
dell_cameron                      : 1
denece_mohammed                   : 1
denis_wood                        : 1
dennet                            : 2  : daniel_dennett
dennett                           : 1  : daniel_dennett
dennis_noble                      : 1
dennis_wood                       : 1
derek_a_epp                       : 1
derek_epp                         : 3
derek_khanna                      : 5
derek_kilmer                      : 1
derek_thompson                    : 1
derrick_sanderlin                 : 1
derrida                           : 3  : jacques_derrida
dershowitz                        : 1  : alan_dershowitz
desantis                          : 3  : ron_desantis
dessie_woods                      : 1
dev_patel                         : 2
devah_pager                       : 1
devin_nunes                       : 4
devin_raposo                      : 2
devin_yalkin                      : 1
devon_price                       : 1
devonia_inman                     : 1
devos                             : 1  : betsy_de_vos
deyan_sudjic                      : 1
dhahr_jamail                      : 1
diana_helmuth                     : 1
diana_nucera                      : 1
diana_tourjee                     : 1
diana_wynne_jones                 : 2
diane_coffey                      : 1
diane_rutherford                  : 1
diane_tavenner                    : 1
diane_taylor                      : 1
dickens                           : 1  : charles_dickens
diego_rivera                      : 1
dignum                            : 7  : frank_dignum  : virginia_dignum
dijkstra                          : 1  : edsger_dijkstra
dilmer_valecillos                 : 1
dilthey                           : 1  : wilhelm_dilthey
dimitry_kochenov                  : 1
dina_cirlott                      : 1
dinesh_dsouza                     : 6
dionisio_gonzales                 : 1
dirty_harry                       : 2
disraeli                          : 1  : benjamin_disraeli
diwan_lughat_al_turk              : 1
doc_burford                       : 1
doc_seuss                         : 1  : doctor_seuss
dolly_lucio_sevier                : 1
dolly_parton                      : 2
dolores_umbridge                  : 1
domineque_ray                     : 1
dominique_remmie_fells            : 1
don_beyer                         : 1
don_butler                        : 1
don_hopkins                       : 1
don_knuth                         : 1
don_marsh                         : 1
don_mccullin                      : 3
don_norman                        : 3
don_young                         : 1
donald_friend                     : 1
donald_neely                      : 1
donald_p_moynihan                 : 1
donald_rumsfeld                   : 1
donald_tusk                       : 1
donna_brown                       : 1
donna_drucker                     : 1
donna_haraway                     : 3
donna_harawayh                    : 1         :  donna_haraway
donna_meadows                     : 3
donnie_cleveland_lance            : 1
donnie_lance                      : 1
donor_class                       : 1
dorian_dawes                      : 3
dorinne_kondo                     : 1
dorrie_o_brien                    : 1
dostoyevsky                       : 1 : fyodor_dostoyevsky
doug_wardlow                      : 1
dougal_dixon                      : 1
douglas_adams                     : 7
douglas_c_north                   : 1
douglas_crockford                 : 2
douglas_englebart                 : 1
douglas_hofstadter                : 4
douglas_rushkoff                  : 1
douglass                          : 1  : frederick_douglass
dr_phil                           : 1
dr_seuss                          : 2  : doctor_seuss
drew_desilver                     : 1
drew_harwell                      : 1
dreyfus                           : 1  : hubert_dreyfus
drucker                           : 1  : peter_drucker
du_bois                           : 12 : w_e_b_du_bois
duane_kearns_puryear              : 1
duncan_watts                      : 1
duomo_di_milano                   : 1
durkheim                          : 4  : emile_durkheim
durwood                           : 1  : l_durwood
duterte                           : 1 : rodrigo_duterte
duvalier                          : 1  : jean_claude_duvalier
dwight_eisenhower                 : 2
dylan_roof                        : 1
e_l_doctorow                      : 1
e_wesley_ely                      : 1
ea_nasir                          : 1
eamonn_holmes                     : 2
earl_long                         : 1
ed_accura                         : 1
ed_berkeley                       : 1
ed_buck                           : 1
ed_dwright                        : 1
ed_finn                           : 1
ed_gillespie                      : 2
ed_harris                         : 1
ed_key                            : 1
ed_mcmillen                       : 2
ed_mell                           : 1
ed_pilkington                     : 1
ed_regis                          : 1
ed_rooksby                        : 1
ed_yong                           : 1
edd_gent                          : 1
eddie_s_glaude_jr                 : 1
edgar_allen_poe                   : 1
edith_penrose                     : 1
ediwn_lord_weeks                  : 1  : edwin_lord_weeks
edmund_a_bowles                   : 1
edmund_berkeley                   : 1
edmund_burke                      : 2
edmund_clarke                     : 1
edmund_husserl                    : 5
edsger_dijkstra                   : 1
edward_burtnysky                  : 1  : edward_burtynsky
edward_burtynsky                  : 1
edward_dickinson_tayloe_II        : 1
edward_ongeweso                   : 1
edward_said                       : 1
edward_teller                     : 1
edward_tufte                      : 1
edwin_brady                       : 1
edwin_lord_weeks                  : 1
edwin_park                        : 1
eernst_balluf                     : 2
Egison                            : 1
einstein                          : 1 : albert_einstein
eisenhower                        : 2 : dwight_eisenhower
elaine_chao                       : 1
elaine_welterroth                 : 1
elanor_janega                     : 1
eldridge_cleaver                  : 1
eleanor_gordon_smith              : 1
eleanor_janega                    : 1
elena_kagan                       : 1
eli_bendersky                     : 1
eli_kline                         : 2
eli_lilly                         : 1
eli_rosenberg                     : 1
eli_valley                        : 1
elias                             : 1  : norbert_elias
elie_wiesel                       : 1
elijah_haahr                      : 1
elijah_mcclain                    : 1
elijah_meeks                      : 1
elinor_ostrom                     : 2
elise_swain                       : 1
eliza_strickland                  : 1
elizabeth_adetiba                 : 1
elizabeth_chin                    : 2
elizabeth_grosz                   : 1
elizabeth_king                    : 1
elizabeth_nolan_brown             : 4
elizabeth_ohene                   : 1
elizabeth_sampat                  : 1
elizabeth_warren                  : 17
elizabeth_weil                    : 1
ella_baker                        : 1
ella_fassler                      : 1
ella_scott_ireton                 : 1
ellen_mitchell                    : 1
ellen_pompeo                      : 1
ellie_kaufman                     : 1
elliot_abrams                     : 1  : elliott_abrams
elliot_hannon                     : 1
elliott_abrams                    : 2
ellner                            : 1  : stephen_ellner
elon_musk                         : 4
elsie_fisher                      : 1
elspeth_reeve                     : 1
elvis_presley                     : 1
emax                              : 1
emerson                           : 1
emile_durkheim                    : 1
emiliano_simione                  : 1
emilie_du_chatelet                : 1
emily_atkin                       : 1
emily_dugan                       : 1
emily_eakin                       : 1
emily_kassie                      : 1
emily_lennox                      : 1
emily_ludolph                     : 1
emily_martin                      : 1
emily_short                       : 22
emily_st_denny                    : 2
emily_thuma                       : 1
emily_van_der_werff               : 1
emily_wax_thibodeaux              : 1
emily_whetstone                   : 1
eminem                            : 2
emma_court                        : 1
emma_green                        : 1
emma_louise_backe                 : 1
emma_ockerman                     : 1
emma_pettit                       : 1
emmanuel_saez                     : 1
emmeline_pankhurst                : 1
emmett_till                       : 3
engels                            : 2 : friedrich_engels
engles                            : 1 : friedrich_engels
epicurus                          : 1
epstein                           : 11 : jeffrey_epstein
erc_smack                         : 1 : eric_smack
erdogan                           : 2  : recep_erdogan
eric_bennett                      : 1
eric_berne                        : 1
eric_boehm                        : 1
eric_evans                        : 1
eric_freedman                     : 1
eric_garner                       : 1
eric_holthaus                     : 1
eric_horvitz                      : 1
eric_kaufmann                     : 1
eric_lafforgue                    : 1
eric_lipton                       : 1
eric_litke                        : 1
eric_smack                        : 1
eric_swalwell                     : 1
eric_wilkrson                     : 1
eric_zimmerman                    : 1
erich_dieckmann                   : 1
erich_fromm                       : 1
ericsmack                         : 1  : eric_smack
erik_hoel                         : 1
erika_christakis                  : 1
erika_hall                        : 1
erikson                           : 1
erin_adler                        : 1
erin_davis                        : 2
erin_gilmer                       : 12
eriugena                          : 1
ernest_adams                      : 1
ernest_burgesss                   : 1
ernest_cole                       : 1
ernest_hemingway                  : 1
ernst_bloch                       : 1
ernst_haeckel                     : 1
erving_goffman                    : 1
eskil_steenberg                   : 4
estelle_puleston                  : 1
ethan_corey                       : 1
ethan_hein                        : 1
ethan_miller                      : 1
etherington_brothers              : 1
eudy_simelane                     : 1
eugene_linden                     : 1
euripedies                        : 1 : euripides
eva_marie_quinones                : 1
eva_moravec                       : 1
evan_miller                       : 1
evan_nicole_brown                 : 1
evan_osnos                        : 1
evan_peck                         : 1
evan_urquhart                     : 1
evans                             : 1  : richard_evans
everett_c_hughes                  : 1
evo_morales                       : 1
ewan_birney                       : 1
ewan_wilson                       : 1
eyvind_earle                      : 1
fabien_sanglard                   : 2
fabrizio_salvador                 : 1
fadi_abu_saleh                    : 1
fannie_lou_hamer                  : 1
farid_mokhati                     : 1
farrakahan                        : 1  : louis_farrakhan
fassbender                        : 1  : michael_fassbender
fatima_al_fihiri                  : 2
fatma_marouf                      : 1
feathers_mcgraw                   : 1
felicity_huffman                  : 2
felipe_gomez_alonzo               : 1
felix_de_boeck                    : 1
felix_guattari                    : 5
felix_vallotton                   : 2
feminista_jones                   : 1
ferdinand_de_saussure             : 2
ferdinand_verbiest                : 1
feuerbach                         : 1 : ludwig_feuerbach
feynman                           : 3  : richard_feynman
flan_falacci                      : 1
flavia_dzodan                     : 1
flynn                             : 1  : michael_flynn
fogleman                          : 3  : michael_fogleman
formosus                          : 1  : pope_formosus
forrest_stuart                    : 2
forstater                         : 1  : maya_forstater
foucault                          : 21 : michel_foucault
fox_harrell                       : 1
fran_sorin                        : 1
frances_a_yates                   : 1
frances_coppola                   : 1
frances_ellen_watkins_harper      : 1
frances_ryan                      : 1
francesco_corea                   : 1
franci_fukuyama                   : 2         :  francis_fukuyama
francis_bacon                     : 1
francis_crick                     : 1
franck_bohbot                     : 1
franco_recchia                    : 1
francois_avril                    : 1
francois_chollet                  : 1
frank_dignum                      : 7
frank_herbert                     : 1
frank_hirahara                    : 1
frank_lantz                       : 1
frank_larose                      : 1
frank_lloyd_wright                : 2
frank_lynch                       : 2
frank_miller                      : 1
frank_vyan_walkton                : 1
frank_zappa                       : 1
franklin_littel                   : 1
franklin_roosevelt                : 3
frantz_fanon                      : 1
franz_kafka                       : 11
franz_mayra                       : 1
frasca                            : 1  : gonzalo_fasca
fred_hampton                      : 6
fred_m_wilcox                     : 1
freddie_mercury                   : 1
freddy_deboer                     : 1
frederic_laloux                   : 2
frederick_brooks                  : 1
frederick_douglass                : 2
frederick_olmstead                : 1
frederick_pohl                    : 2
frege                             : 3  : gottlob_frege
freire                            : 1  : paulo_freire
friedman                          : 1  : milton_friedman
friedrich_hayek                   : 3
friedrich_nietzsche               : 1
froggi_vanRiper                   : 1
fukuyama                          : 2  : franci_fukuyama
g_a_barber                        : 1
g_i_jones                         : 1
G_S_Ghurye                        : 1
gabriela_saldiva                  : 1
gabrielle_jackson                 : 1
gaddafi                           : 1
gaetan_dugas                      : 2
gaiman                            : 1  : neil_gaiman
gaius_baltar                      : 4
gallaudet_eleven                  : 1
galole_orma                       : 1
gandhi                            : 2  : mohandas_karamchand_gandhi
garber                            : 1  : daniel_garber
garfinkel                         : 3  : harold_garfinkel
garrett_rolfe                     : 1
garry_shandling                   : 1
gary_cohn                         : 1
gary_gygax                        : 1
gary_jones                        : 1
gary_taubes                       : 1
gaston_bachelard                  : 1
gauido                            : 1  : juan_gauido
gauthier_boeda                    : 1
gavin_newsom                      : 1
gediminas_pranckevicius           : 1
gelernter                         : 1  : david_gelernter
gell_mann                         : 1
gentner                           : 3  : deirdre_gentner
geoffrey_hinton                   : 1
geoffrey_miller                   : 2
geoffrey_york                     : 1
geoge_hegel                       : 7
georg_bohle                       : 1
georg_lukacs                      : 1
georg_simmel                      : 1
george_3rd                        : 2
george_akerlof                    : 1
george_barnhill                   : 1
george_bush                       : 9
george_byron                      : 1
george_catlin                     : 1
george_church                     : 1
george_clooney                    : 1
george_cuvier                     : 1
george_floyd                      : 4
george_herbert_mead               : 1
george_hirahara                   : 1
george_III                        : 1
george_lakoff                     : 1
george_mason                      : 1
george_odling                     : 1
george_orwell                     : 1
george_osborne                    : 1
george_packer                     : 2
george_romero                     : 1
george_schuyler                   : 1
george_soros                      : 3
george_stinney                    : 2
george_takei                      : 1
george_tiller                     : 1
george_wallace                    : 1
george_zimmerman                  : 1
georges_sorel                     : 1
georgina_beyer                    : 1
georgy_nissky                     : 1
gerald_sussman                    : 3
gerard_halperin                   : 1
german_lopez                      : 1
gerry_anderson                    : 1
gerry_yaum                        : 1
gert_hofstede                     : 3
gibson                            : 3  : william_gibson
giddens                           : 2  : anthony_giddens
gideon_levy                       : 2
gilles_deleuze                    : 1
gillespie                         : 1  : ed_gillespie
gillian_edevane                   : 1
gillibrand                        : 1  : kirsten_gillibrand
gina_miller                       : 1
ginia_bellafante                  : 1
giordano_bruno                    : 2
giovanni_della_casa               : 1
giovanni_palmiero                 : 1
gisele_waters                     : 1
gita_jackson                      : 1
giuliani                          : 1  : rudy_giuliani
glenn_beck                        : 1
glenn_gould                       : 1
glenn_greenwald                   : 4
glenn_kessler                     : 10
glinner                           : 1 : graham_linehan
gluckman                          : 1  : max_gluckman
godel                             : 1  : kurt_godel
goffman                           : 7  : erving_goffman
golan_levin                       : 1
goldacre                          : 1  : ben_goldacre
goldwater                         : 1  : barry_goldwater
gonzalo_fasca                     : 1  : gonzalo_frasca
gordon_liddy                      : 1
gordon_sondland                   : 5
gorsuch                           : 6  : neil_gorsuch
gottlob_frege                     : 3
gouldner                          : 1  : alvin_gouldner
grace_church                      : 1
grace_haven                       : 1
grace_hopper                      : 1
gracehaven                        : 1  : grace_haven
graeber                           : 1  : david_graeber
graeme_kirkpatrick                : 1
graham_cassidy                    : 1
gramsci                           : 2  : antonio_gramsci
grant_w_robicheaux                : 1
grasci                            : 1  : antonio_gramsci
gray_scott                        : 2
greenberg                         : 1  : andy_greenberg
greenwald                         : 2  : glenn_greenwald
greg_abbott                       : 1
greg_bear                         : 2
greg_costikyan                    : 1
greg_doucette                     : 2
greg_lopiccolo                    : 1
greg_sargent                      : 1
gregory_h_shill                   : 1
gregory_hill                      : 1
gregory_ivanov                    : 1
gregory_korte                     : 1
greta_thunberg                    : 3
gretchen_whitmer                  : 1
griff_witte                       : 1
grossi                            : 1  : davide_grossi
guan_gonzalez                     : 1
guattari                          : 5  : felix_guattari
guillame_chaslot                  : 1
guillermo_del_toro                : 1
gulcynski                         : 1  : ray_gulcynski
gunkell                           : 1  : david_gunkell
gus_and_tycho                     : 1
gustave_dore                      : 1
guy_fieri                         : 1
gygax                             : 1  : gary_gygax
gyllenhaal                        : 1  : jake_gyllenhaal
gyorgy_lukacs                     : 1
h_g_wells                         : 1
h_h_asquith                       : 1
h_p_lovecraft                     : 6
h_r_geiger                        : 1
habermas                          : 10 : jurgen_habermas
hailey_gavin                      : 1
hakim_bey                         : 1
halcyon_lawrence                  : 1
haliehana                         : 1   : haliehana_stepetin
haliehana_stepetin                : 1
halim_el_dabh                     : 1
hamed_aleaziz                     : 1
hamilton                          : 3  : alexander_hamilton
hanes_walton                      : 1
hannah_arendt                     : 3
hannah_beacher                    : 1
hannah_hilligoss                  : 1
hannah_kozak                      : 1
hannibal                          : 1
hans_herman_hoppe                 : 1
hans_hermann_hoppe                : 1         :  hans_herman_hoppe
hans_poelzig                      : 1
hans_rosling                      : 2
hans_steinmuller                  : 1
hansi_lo_wang                     : 1
haraway                           : 1  : donna_haraway
hariton_pushwanger                : 1
harold_garfinkel                  : 3
harriet_martineau                 : 1
harriet_tubman                    : 2
harron_walker                     : 1
harry_benjamin                    : 1
harry_clarke                      : 2
harry_fox                         : 1
harry_haywood                     : 1
harry_potter                      : 5
harry_reid                        : 1
harry_truman                      : 3
harry_vaughan                     : 1
haruki_murakami                   : 3
harvey_weinstein                  : 2
harvey_whitehouse                 : 1
hasan_al_turabi                   : 1
hasan_nasrallah                   : 1
haska_meyna                       : 1
hassan_al_banna                   : 1
hava_stiegelmann                  : 1
hawk_dove_bourgeois               : 1
hayakawa_s_f                      : 1
hayao_miyazaki                    : 2
hayek                             : 3  : friedrich_hayek
haynsworth                        : 1  : clement_haynsworth
heath_robinson                    : 1
heather_heyer                     : 1
heather_hicks                     : 1
heather_timmons                   : 1
hector_de_la_garza                : 1
hegel                             : 6  : geoge_hegel
heidegger                         : 5  : martin_heidegger
heidi_przbyla                     : 1
heiko_maas                        : 1
heisenberg                        : 1
helen_branswell                   : 1
helen_hester                      : 1
helen_razer                       : 1
helen_rosner                      : 1
hennessy_milner                   : 1
henri_bergson                     : 1
henri_lefebvre                    : 5
henry_ford                        : 1
henry_fountain                    : 2
henry_jenkins                     : 1
henry_kissinger                   : 1
henry_miller                      : 1
henry_neville                     : 1
henry_rubin                       : 1
henry_sidgwick                    : 1
henry_wadsworth                   : 1
heraclitus                        : 1
herb_clark                        : 1
herbert_marcuse                   : 2
herbert_simon                     : 3
herbert_spencer                   : 1
herman_talmadge                   : 2
herman_tulleken                   : 1
hermine_ricketts                  : 1
hetero_cephalus_gabler            : 1
hettie_obrien                     : 2
hideo_kojima                      : 2
hieronymus_bos                    : 1   : hieronymus_bosch
hieronymus_bosch                  : 1
hilbert                           : 1  : david_hilbert
hillary_clinton                   : 4
hillary_sargent                   : 1
hilsa_fish                        : 1
hippocrates                       : 1
hippu_zukai                       : 1
hiro_ito                          : 1
hiroko_kubota                     : 1
hiroko_tabuchi                    : 2
hitchcock                         : 1  : alfred_hitchcock
hitler                            : 6
hoda_muthana                      : 2
hofstadter                        : 4  : douglas_hofstadter
hofstede                          : 3  : gert_hofstede
holly_yan                         : 1
homer_thornberry                  : 1
honore_de_alzac                   : 1  : honore_de_balzac
honore_de_balzac                  : 1
horkheimer                        : 3  : max_horkheimer
horswill                          : 1  : ian_horswill
howard_s_becker                   : 2
howard_zinn                       : 2
hp_lovecraft                      : 1         :  h_p_lovecraft
hraclitus                         : 1  : heraclitus
hubert_dreyfus                    : 1
hubery_maga                       : 1
huey_newton                       : 1
hugh_ferris                       : 1
hugo_seijas                       : 1
hume                              : 1  : david_hume
Hume                              : 1  : david_hume
husserl                           : 5  : edmund_husserl
hyde_smith                        : 1
iain_banks                        : 1
ian_acheson                       : 1
ian_banks                         : 1  : iain_banks
ian_bogost                        : 5
ian_coulson                       : 1
ian_cross                         : 1
ian_dunt                          : 1
ian_horswill                      : 1
ian_kershaw                       : 1
ian_mcaulay                       : 1
ian_mckellan                      : 1
ian_mcque                         : 1
ian_millhiser                     : 1
ian_philbrick                     : 1
iana_robitaille                   : 1
iannis_xenakis                    : 1
iberia_hampton                    : 1
ibn_khurradadhbih                 : 1
ibram_kendi                       : 4
ichiro_kawachi                    : 1
ida_b_wells                       : 1
ida_danewid                       : 1
ike_perlmutter                    : 1
ilan_pappe                        : 1
ildefons_cerda                    : 1
ilhan_omar                        : 9
ilya_chashnik                     : 1
ilya_dorman                       : 1
ilya_somin                        : 1
immanuel_kant                     : 2
imre_makovecz                     : 1
inae_oh                           : 1
inana_robitaille                  : 1         :  iana_robitaille
indya_moore                       : 1
ingrid_burrington                 : 1
ira_chernus                       : 2
ira_glass                         : 1
irin_carmon                       : 1
iris_marion_young                 : 1
irvng_yalom                       : 1
isaac_arnsdorf                    : 1
isaac_asimov                      : 7
isaac_butler                      : 1
isaac_chotiner                    : 1
isaac_karth                       : 1
isaac_sears                       : 1
isaac_stoner                      : 1
isabel_fall                       : 1
isabel_millar                     : 1
isabel_perera                     : 1
ise_monogatari                    : 1
isiah_murrietta_golding           : 1
israel_bartal                     : 1
italo_calvino                     : 1
itay_keren                        : 1
ivanka                            : 1  : ivanka_trump
ivanka_trump                      : 1
ivo_daalder                       : 1
j_edgar_hoover                    : 1
j_f_kennedy                       : 4
j_michael_bailey                  : 1
j_r_r_tokien                      : 4
j_s_bach                          : 2
j_s_mill                          : 1
jack_black                        : 1
jack_bothma                       : 1
jack_conte                        : 1
jack_murphy                       : 1
jack_robertson                    : 1
jack_the_ripper                   : 1
jack_turban                       : 1
jack_webb                         : 1
jackie_land                       : 1
jackson_dunstan                   : 1
jackson_mann                      : 1
jackson_mcmahon                   : 1
jacob                             : 1  : jacob_garbe
jacob_bacharach                   : 1
jacob_chansley                    : 1
jacob_garbe                       : 1
jacob_nelson                      : 1
jacob_rees_mogg                   : 1
jacob_walter_anderson             : 1
jacquard_similarity               : 1
jacqueline_rabe_thomas            : 1
jacques_derrida                   : 3
jacques_lacan                     : 3
jair_bolsonaro                    : 2
jake_gyllenhaal                   : 1
jakelin_maquin                    : 1
jakob_nielson                     : 1
jakob_sandtner                    : 1
jakobson                          : 1
jakub_dvorsky                     : 1
jamal_khashoggi                   : 1
jamelle_bouie                     : 1
james_acton                       : 1
james_adams                       : 1
james_aho                         : 1
james_allsup                      : 1
james_baldwin                     : 4
james_bond                        : 1
james_c_scott                     : 2
james_cameron                     : 3
james_cleverly                    : 1
james_comey                       : 2
james_cook                        : 1
james_cooray_smith                : 1
james_crombie                     : 1
james_deen                        : 1
james_earl_jones                  : 1
james_eastland                    : 2
james_gleick                      : 1
james_herbert                     : 1
james_ho                          : 1
james_hofmann                     : 1
james_hood                        : 1
james_joyce                       : 1
james_lindsay                     : 1
james_lovelock                    : 1
james_okeefe                      : 1
james_pita                        : 1
james_r_mann                      : 1
james_ryan                        : 1
james_troiano                     : 1
jamie_cheng                       : 1
jamie_doward                      : 1
jamie_grierson                    : 1
jan_vranovsky                     : 1
jane_austen                       : 1
jane_bradley                      : 1
jane_coaston                      : 3
jane_fonda                        : 1
jane_gerber                       : 1
jane_roe                          : 2
janelle_monae                     : 1
janet_abbate                      : 1
janet_murray                      : 1
janice_raymond                    : 1
janice_turner                     : 1
janna_herron                      : 1
jaoquin_sapien                    : 1
jared_diamond                     : 1
jared_kushner                     : 3
jasmin_rosemberg                  : 1
jason_damore                      : 1
jason_de_leon                     : 2
jason_hickey                      : 1
jason_hill                        : 1
jason_koebler                     : 2
jason_leopold                     : 1
jason_miller                      : 1
jason_rohrer                      : 5
jason_van_dyke                    : 1
jason_wilson                      : 4
jay_hulme                         : 1
jay_rosen                         : 4
jay_z                             : 1
jaya_zhane                        : 1
jazmine_headley                   : 1
jazz_mickle                       : 1
jean_baptiste_lamarck             : 1
jean_baudrillard                  : 4
jean_claude_duvalier              : 1
jean_claude_piris                 : 1
jean_huleth                       : 1
jean_jacques_dessalines           : 1
jean_lyotard                      : 2
jean_nidtech                      : 1
jean_paul_sartre                  : 2
jean_piaget                       : 2
jeff_bezos                        : 3
jeff_howard                       : 1
jeff_kowalsky                     : 1
jeff_niiya                        : 3
jeff_sessions                     : 1
jeff_vandermeer                   : 1
jefferson                         : 2  : thomas_jefferson
jeffrey_epstein                   : 8
jeffrey_lord                      : 1
jeffrey_oberman                   : 1
jeffrey_sachs                     : 1
jekyll                            : 7
jemele_hill                       : 1
jen_gunter                        : 1
jenkins                           : 1  : henry_jenkins
jenna_coleman                     : 1
jennifer_bendery                  : 2
jennifer_cohn                     : 3
jennifer_jacobs                   : 1
jennifer_lawrence                 : 1
jennifer_lopez                    : 2
jennifer_richards                 : 1
jennifer_scheurle                 : 2
jenny_odell                       : 1
jenny_zhang                       : 1
jeremy_antley                     : 1
jeremy_bentham                    : 1
jeremy_corbyn                     : 2
jeremy_kun                        : 2
jeremy_raff                       : 1
jerome_adams                      : 1
jerome_roos                       : 1
jerry_brown                       : 2
jerry_falwall                     : 1
jerry_hargrove                    : 1
jerry_mitchell                    : 1
jerry_sandusky                    : 1
jerry_taylor                      : 1
jesical_fjeld                     : 1
jesper_juul                       : 1
jess_haskins                      : 1
jesse_helms                       : 1
jesse_morton                      : 1
jesse_schell                      : 1
jesse_singal                      : 5
jessica_fjeld                     : 1
jessica_palmer                    : 1
jessica_perlstein                 : 1
jessica_pishko                    : 1
jessica_pressler                  : 1
jessica_price                     : 1
jessica_simpson                   : 1
jessica_sutherland                : 1
jessica_valenti                   : 1
jesus                             : 4
jethro_kuan                       : 1
jfk                               : 1  : j_f_kennedy
JFK                               : 3  : j_f_kennedy
jg_ballard                        : 5
jian_ghomeshi                     : 1
jichen_zhu                        : 1
jilian_weise                      : 1
jill_bliss                        : 1
jim_acosta                        : 2
jim_al_khalili                    : 1
jim_cannon                        : 1
jim_jordan                        : 1
jim_justice                       : 1
jim_morrill                       : 1
jim_rossignol                     : 3
jim_sinclair                      : 1
jim_waterson                      : 1
jimi_hendrix                      : 1
jimmie_gates                      : 1
jimmy_al_daoud                    : 3
jimmy_aldaoud                     : 1
jimmy_carter                      : 1
jimmy_kimmel                      : 1
jiz_lee                           : 1
jk_galbraith                      : 2
jk_rowling                        : 3
jo_ann_owusu                      : 1
jo_fu                             : 1
joan_donovan                      : 1
joan_little                       : 1
joanna_bryson                     : 1
joanna_gaughan                    : 1
joanna_moorhead                   : 1
joanne_yao                        : 2
joaqun_oliver                     : 1
jocelyn_benson                    : 1
jodi_cohen                        : 1
jodorowsky                        : 1 : alejandro_jodorowsky
joe_biden                         : 4
joe_conason                       : 1
joe_fassler                       : 1
joe_mcdermott                     : 1
joe_nye                           : 1
joe_price                         : 1
joe_rogan                         : 1
joel_carroll                      : 1
joel_de_la_garza                  : 1
joel_kurth                        : 1
joel_robbins                      : 1
joel_simon                        : 2
joel_whitney                      : 1
joey_gibson                       : 3
johana_medina_leon                : 1
johann_strauss                    : 2
johanna_pirker                    : 1
john_a_de_goes                    : 1
john_ballard                      : 1
john_bel_edwards                  : 2
john_betjeman                     : 1
john_blair                        : 1
john_boehner                      : 1
john_bolton                       : 1
john_bowlby                       : 1
john_brunner                      : 3
john_cage                         : 1
john_calvin                       : 1
john_carmack                      : 3
john_carter                       : 1
john_cleese                       : 1
john_conway                       : 3
john_cook                         : 1
john_cornyn                       : 1
john_crawford                     : 1
john_d_cook                       : 4
john_dingell                      : 1
john_donohue                      : 1
john_elledge                      : 1
john_fetterman                    : 1
john_galt                         : 1
john_gruber                       : 1
john_halpin                       : 1
john_harris                       : 1
john_harwood                      : 1
john_hopson                       : 1
john_kenneth_galbraith            : 1
john_kitchin                      : 3
john_krajewski                    : 1
john_krinsky                      : 1
john_lennon                       : 1
john_locke                        : 2
john_maynard_smith                : 1
john_mccain                       : 1
john_mellencamp                   : 1
john_milton                       : 1
john_mulaney                      : 1
john_neely_bryan                  : 1
john_nichols                      : 1
john_oliver                       : 1
john_paul_II                      : 1
john_paul_stevens                 : 1
john_perry_barlow                 : 1
john_rawls                        : 1
john_riccitiello                  : 1
john_richardson                   : 1
john_ridley                       : 1
john_roberts                      : 1
john_romero                       : 1
john_sanders                      : 1
john_scalzi                       : 3
john_scott                        : 1
john_searle                       : 1
john_sloan                        : 2
john_snow                         : 1
john_stuart_mill                  : 1
john_tedesco                      : 1
john_tozzi                        : 1
john_von_neumann                  : 1
john_walker                       : 2
john_wayne                        : 1
john_wyndham                      : 2
johnathan_blow                    : 3
johnathan_edwards                 : 1
johnathan_hume                    : 1
johnathan_turley                  : 1
johnathon_selstad                 : 1
johns_hopkins                     : 1
joli_jensen                       : 1
jon_bentley                       : 1
jon_husted                        : 1
jon_ingold                        : 1
jon_juarez                        : 1
jon_marcus                        : 1
jon_peterson                      : 2
jon_rosenberg                     : 2
jon_worth                         : 2
jonas_kyratzes                    : 1
jonas_salk                        : 1
jonathan_aledda                   : 1
jonathan_chait                    : 1
jonathan_cook                     : 1
jonathan_coulton                  : 1
jonathan_english                  : 1
jonathan_frome                    : 1
jonathan_katz                     : 1
jonathan_lambert                  : 1
jonathan_oosting                  : 2
jonathan_rothwell                 : 1
jonathan_rowe                     : 1
jonathan_stray                    : 1
jones_act                         : 1
jonnie_penn                       : 1
jordan_cofer                      : 1
jordan_engel                      : 1
jordan_mechner                    : 1
jordan_peele                      : 1
jordan_petersen                   : 2
jordan_smith                      : 1
jorge_luis_borges                 : 1
joris_dormans                     : 2
jose_gonzalez_carranza            : 1
jose_itzigsohn                    : 1
josef_schneider                   : 1
joseph_bologne                    : 1
joseph_cox                        : 2
joseph_cranney                    : 2
joseph_ducreux                    : 2
joseph_irby                       : 1
joseph_kony                       : 1
joseph_lawrence                   : 1
joseph_marks                      : 1
joseph_mccarthy                   : 1
joseph_nye                        : 1
joseph_paxton                     : 1
joseph_weizenbaum                 : 1
josh_ge                           : 2
josh_hawley                       : 2
josh_kovensky                     : 1
josh_marshall                     : 3
josh_rosenberg                    : 1
josh_walker                       : 1
joshua_aizenman                   : 1
joshua_bickel                     : 1
joshua_blackburn                  : 1
joshua_ceballos                   : 1
joshua_clover                     : 1
joshua_partlow                    : 1
joshua_rivers                     : 1
joshua_tree                       : 3
josiah_charles_stamp              : 1
joss_whedon                       : 1
joyce_beatty                      : 1
joyce_carol_oate                  : 1  : joyce_carol_oates
joyce_carol_oates                 : 1
joyce_white_vance                 : 1
jp_le_breton                      : 2
juan_alberto_silva                : 1
juan_gauido                       : 1
juan_ignaciorios                  : 1
juan_rafael_bustillo              : 1
jude_stewart                      : 1
judea_pearl                       : 2
judge_dredd                       : 1
judge_pryor                       : 1
judge_troiano                     : 1
judita_k                          : 1
judith_butler                     : 1
judy_lynn_del_Rey                 : 1
jugalk_patel                      : 1
juhani_pallasamaa                 : 2 : juhani_pallasmaa
juhani_pallasmaa                  : 1
julia_belluz                      : 1
julia_brooks                      : 1
julia_gaffield                    : 1
julia_isabel_amparao_medina       : 1
julia_kristeva                    : 1
julia_rohrer                      : 1
julia_serano                      : 1
julia_wilder                      : 1
julian_assange                    : 1
julian_borger                     : 1
julian_brave_noisecat             : 2
julian_carr                       : 1
julian_castro                     : 1
julian_gill                       : 1
julian_oliver                     : 1
julian_sturdy                     : 1
julian_togelius                   : 13
julie_brown                       : 1
julie_carr_smyth                  : 1
julie_henry                       : 1
julie_libarkin                    : 1
julie_moronuki                    : 1
julie_tate                        : 1
julius_orion_smith                : 1
junot_diaz                        : 1
jurgen_habermas                   : 11
justice_kagan                     : 1
justice_kennedy                   : 2
justice_scalia                    : 2
justin_amas                       : 1
justin_amash                      : 1
justin_rohrlich                   : 2
justin_trudeau                    : 1
juzema_goldring                   : 1
k_gibran                          : 1
KA_mclaughlin                     : 1
kaepernick                        : 4  : colin_kaepernick
kafa                              : 1 : franz_kafka
kafka                             : 9  : franz_kafka
kagan                             : 1  : elena_kagan
kai_ashante_wilson                : 1
kaileigh_schmidt                  : 1
kaite_welsh                       : 1
kakfa                             : 2  : franz_kafka
kalev_leetaru                     : 1
kalief_browder                    : 1
kalonymus_ben_kalonymus           : 1
kamala_harris                     : 7
kandace_montgomery                : 1
kanger_lindahl                    : 1
kanger_lindahl_porn               : 1
kanishk_tharoor                   : 1
kant                              : 2  : immanuel_kant
kanye_west                        : 1
kardashian                        : 1
karel_capek                       : 1
karen_bretell                     : 1
karen_hao                         : 2
karen_washington                  : 1
kari_bingen                       : 1
karida_l_brown                    : 1
karina_popp                       : 1
karl_drlica                       : 1
karl_evers-hillstrom              : 1  : karl_evers_hillstrom
karl_evers_hillstrom              : 1
karl_jung                         : 1
karl_marx                         : 63
karl_ove_knausgaard               : 2
karl_popper                       : 1
karl_schmitt                      : 1
karl_sims                         : 1
karl_taylor                       : 1
karl_weick                        : 1
karlene_roberts                   : 1
karrera_djoko                     : 1
karyn_turk                        : 1
kate_brown                        : 1
kate_clancy                       : 1
kate_crawford                     : 2
kate_gray                         : 1
kate_howland                      : 1
kate_klonick                      : 1
kate_lister                       : 4
kate_manne                        : 1
kate_mclean                       : 1
kate_middleton                    : 1
kate_rubins                       : 1
kate_starbird                     : 1
kate_steinle                      : 1
kate_zambreno                     : 1
katelyn_burns                     : 5
katerine_dunn                     : 1
katherine_chiglinsky              : 1
katherine_crocker                 : 1
katherine_cross                   : 1
katherine_highnett                : 2
katherine_robbins                 : 1
katherine_stanton                 : 1
kathleen_davis                    : 1
kathleen_stock                    : 1
kathryn_tenpas                    : 1
katie_holten                      : 1
katie_lombardo                    : 1
katie_mettler                     : 1
katie_shelef                      : 1
katie_shepherd                    : 1
kats_kitties                      : 1
katt_williams                     : 1
katy_ryan                         : 1
kavanaugh                         : 16 : brett_kavanaugh
kawaski_trawick                   : 1
kay_ivey                          : 1
kayla_williams                    : 1
kayleigh_mcenany                  : 2
kazimir_malevich                  : 1
kc_green                          : 1
KC_Viz                            : 1
keats                             : 1 : john_keats
kee_hinckley                      : 1
keeanga_yamahtta_taylor           : 1
keegan_kyle                       : 1
keisha_blain                      : 1
keisha_jenkins                    : 1
keith_davis                       : 1
keith_jackson                     : 1
keith_kohn                        : 1
keller_easterling                 : 1
kellie_jay_keen_minshull          : 1
kelly_coltrain                    : 1
kelly_savage                      : 1
kellyanne_conway                  : 1
kelsen                            : 1 : hans_kelsen
ken_cuccinelli                    : 1
ken_klippenstein                  : 2
ken_levine                        : 1
ken_saro_wiwa                     : 1
ken_zucker                        : 2
kendra_pierre_louis               : 2
kenneth_pietrobono                : 2
kenneth_ross                      : 1
kenneth_shepsle                   : 1
kent_beck                         : 1
keri_leigh_merrit                 : 1
kermit                            : 2
kevin_baker                       : 1
kevin_bauman                      : 1
kevin_collier                     : 1
kevin_hartnett                    : 1
kevin_kruse                       : 3
kevin_reuning                     : 1
kevin_sleff                       : 1
kevin_t_baker                     : 1
kevin_williamson                  : 1
kid_rock                          : 2
kieran_corcoran                   : 1
kieran_devlin                     : 2
kieran_fisher                     : 1
kieran_healy                      : 1
kierkegaard                       : 1  : soren_kierkegaard
kieron_gillen                     : 2
kim_dotcom                        : 4
kim_fortun                        : 1
kim_gardner                       : 1
kim_jong_un                       : 1
kim_kelly                         : 2
kim_stanley_robinson              : 9
kimberle_crenshaw                 : 2
kimberly_hamlin                   : 1
kinjal_dave                       : 1
kira_lerner                       : 1
kirabo_jackson                    : 1
kirk_hamilton                     : 1
kirsten_ainley                    : 1
kirsten_berg                      : 1
kirsten_cornelson                 : 1
kirsten_gillibrand                : 1
kirsten_west_savali               : 1
kirstjen_nielsen                  : 3
kirtsaeng                         : 5  : supap_kirtaeng
kishonna_gray                     : 1
klein                             : 1
koch                              : 2
kojima                            : 2  : hideo_kojima
kondwani_fidel                    : 1
konstantinos_dimopoulos           : 3
kripke                            : 4  : saul_kripke
kris_kobach                       : 4
kristen_stewart                   : 1
kristeva                          : 1  : julia_kristeva
kristin_fawcett                   : 1
kristin_naylor                    : 1
kristin_stock                     : 1
krithika_varagur                  : 1
kritseva                          : 1    : julia_kristeva
krugman                           : 2  : paul_krugman
ksr                               : 5  : kim_stanley_robinson
kubrick                           : 1  : stanley_kubrick
kuhn_tucker                       : 1
kurt_godel                        : 1
kurt_repanshek                    : 1
kurt_volker                       : 1
kv_storage                        : 2
kwame_nkrumah                     : 1
kyle_c_barry                      : 1
kyle_chayka                       : 1
kyle_hopkins                      : 1
kyle_korver                       : 3
kyratzes                          : 1  : jonas_kyratzes
l_durwood                         : 1
la_boetie                         : 1
labov                             : 1  : william
lacan                             : 3  : jacques_lacan
lakeidra_chavis                   : 1
lakeith_smith                     : 1
lamar_johnson                     : 1
lamarck                           : 1  : jean_baptiste_lamarck
lana_wachowski                    : 1
lance_mason                       : 1
lando_calrissian                  : 1
langston_hughes                   : 1
lansing                           : 1  : stephen_lansing
laquan_mcdonald                   : 1
larry_arnold                      : 1
larry_ellison                     : 1
larry_hogan                       : 1
larry_krasner                     : 1
larry_mcCaffery                   : 1
larry_niven                       : 2
larry_page                        : 1
laszlo_versenyi                   : 1
lateshia_beachum                  : 1
laura_de_veua                     : 2
laura_forlano                     : 1
laura_geggel                      : 1
laura_hazard_owen                 : 1
laura_hickman                     : 1
laura_hudson                      : 1
laura_ingraham                    : 2
laura_mulvey                      : 1
laura_pena                        : 1
laurel_wamsley                    : 1
lauren_bard                       : 1
lauren_duca                       : 1
lauren_fox                        : 1
lauren_klein                      : 2
lauren_macivor_thompson           : 1
lauren_mcCluskey                  : 1
lauren_morton                     : 1
lauren_southern                   : 1
laurence_nowell                   : 1
laurie_garrett                    : 1
laurie_lee_brom                   : 1
laurie_spiegel                    : 1
laurie_wilki                      : 1
lawrence_brown                    : 1
lawrence_glickman                 : 1
lawrence_lessing                  : 2
lawrence_livermore                : 1
le_corbusier                      : 1
le_guin                           : 3  : ursula_le_guin
leah_christiani                   : 2
leah_lakshmi_piepzna_samarasinha  : 1
lee                               : 1  : mike_lee
lee_carter                        : 1
lee_drutman                       : 1
lee_moran                         : 1
lee_pace                          : 1
lee_zeldin                        : 1
lefebvre                          : 4  : henri_lefebvre
leibniz                           : 1  : gottfried_wilhelm_leibniz
leif_johnson                      : 1
leigh_alexander                   : 22
leigh_ann_caldwell                : 1
lemony_snicket                    : 1
lenin                             : 1  : vladimir_lenin
leo_III                           : 1
leo_smith                         : 1
leo_strauss                       : 1
leo_tolstoy                       : 2
leo_varadkar                      : 1
leon_bates                        : 1
leon_cooperman                    : 1
leon_mcray                        : 1
leona_baumgartner                 : 1
leonard_richardson                : 1
leonard_susskind                  : 1
leopold_                            2                         :   1
lesley_lokko                      : 1
lesli_furcron                     : 1         :  leslie_furcon
leslie_furcron                    : 1
lessig                            : 2  : lawrence_lessing
lev_manovich                      : 4
lev_vygotsky                      : 1
leveson                           : 1  : brian_leveson
levi_strauss                      : 4  : claude_levi_strauss
levitsky                          : 1  : steven_levitsky
lewis_gordon                      : 1
lewis_wallace                     : 2
leyla_acaroglu                    : 1
li_bendersky                      : 1  : eli_bendersky
liam_casey                        : 1
liat_clark                        : 1
lil_loofbourow                    : 1
lil_nas_x                         : 2
lila_fenwick                      : 1
lili_loofbourow                   : 4
lillian_liu                       : 1
lily_meyer                        : 1
lily_newman                       : 1
linda_gordon                      : 1
linda_j_skitka                    : 1
linda_tirado                      : 1
linden_reid                       : 1
lindsay_gibbs                     : 1
lindsay_graham                    : 1
lindsay_schnell                   : 1
lindsey_graham                    : 1
lindsey_reid                      : 1
linus_pauling                     : 1
lionel_shaw                       : 1
lisa_adkins                       : 1
lisa_bloom                        : 1
lisa_grabnsky                     : 1
lisa_montgomery                   : 1
lisa_munro                        : 1
lisa_o_carroll                    : 1
lisa_stampitzky                   : 1
lisa_yaszek                       : 1
lise_olsen                        : 1
liv_mcconnell                     : 1
livia_albeck_ripka                : 2
liz_cheney                        : 1
liz_england                       : 1
liz_fong_jones                    : 1
liz_quinlan                       : 1
liz_ryerson                       : 1
liz_truss                         : 1
liza_koshy                        : 1
lizabeth_cohen                    : 1
lizzie_dearden                    : 1
lizzie_presser                    : 1
locke                             : 2  : john_locke
logan_kirkland                    : 1
lombroso                          : 1  : cesare_lombroso
lonnie_shaw                       : 3
lord_mountbatten                  : 1
loren_white                       : 1
lorenzo_franceschi_bicchierai     : 1
lori_kido_lopez                   : 1
lori_loughlin                     : 1
lorraine_boissoneault             : 1
lorrie_shepard                    : 1
louis_althusser                   : 2
louis_barron                      : 1
louis_farrakhan                   : 1
louis_gohmert                     : 1
louis_le_breton                   : 1
louis_perez                       : 1
lovecraft                         : 6  : h_p_lovecraft
lubart                            : 2
luc_besson                        : 1
luc_forsyth                       : 1
lucas_pope                        : 3
lucas_reilly                      : 1
lucas_zimmerman                   : 1
luckmann                          : 1  : thomas_luckmann
lucky_tran                        : 1
lucy_morris                       : 1
lucy_suchman                      : 1
ludwig_favre                      : 1
ludwig_von_mises                  : 1
ludwig_wittgenstein               : 5
luis_ferre_sadurni                : 1
lukacs                            : 1  : gyorgy_lukacs
luke_dicken                       : 2
luke_oneil                        : 1
luliu_cosmin_oniscu               : 1
luna_younger                      : 3
lux_alptraum                      : 1
lyndo_jones                       : 1
lyndon_johnson                    : 1
lynn_margulis                     : 3
lynn_parramore                    : 1
lynsey_chutel                     : 1
lyotard                           : 2  : jean_lyotard
lyra_mckee                        : 1
lyz_lenz                          : 1
m_c_demarco                       : 1
m_g_mcintyre                      : 1
m_worlf_meyer                     : 1 : m_wolf_meyer
ma_huateng                        : 1
maamajomboo                       : 1
machiavelli                       : 1
maciej_ceglowski                  : 1
mack_briggs                       : 1
mack_lamoureux                    : 1
madeleine_joung                   : 1
madison_cawthorn                  : 1
mae_sot                           : 1
mael_nison                        : 1
maggie_bozeman                    : 1
maggie_haberman                   : 1
maja_wronska                      : 1
makeda_bizuneh                    : 1
malaika_handa                     : 1
malcolm_x                         : 1
malcom_gladwell                   : 1
malcom_x                          : 2  : malcolm_x
malthus                           : 1  : thomas_malthus
mamdou_cisse                      : 1
mamud_al_kashgari                 : 1
manafort                          : 3  : paul_manafort
manning_marable                   : 1
manuel_ellis                      : 1
manuel_oliver                     : 1
mar_hicks                         : 2
marc_parry                        : 1
marcel                            : 1
marcel_mauss                      : 1
marcia_silva                      : 1
marcos_parras_molto               : 1
marcus_aurelius                   : 1
marcus_garvey                     : 1
marcus_tullius_cicero             : 1
marcuse                           : 2  : herbert_marcuse
margaret_atwood                   : 1
margaret_boden                    : 2
margaret_cavendish                : 1
margaret_court                    : 1
margaret_foster                   : 1
margaret_krauss                   : 1
margaret_masterman                : 1
margaret_sanger                   : 1
margaret_thatcher                 : 2
margaret_wilson                   : 1
mari_ramsawakh                    : 1
maria_godoy                       : 1
maria_la_ganga                    : 1
maria_popova                      : 1
maria_szantho                     : 1
marianne_williamson               : 1
marie_granmar                     : 1
marie_hicks                       : 1
marie_kondo                       : 2
marie_le_conte                    : 1
marie_quinones_eva                : 1
marie_renaud                      : 1
marily_strathern                  : 1
marilyn_manson                    : 3
marilyn_mosby                     : 1
marina_de_vos                     : 1
mario                             : 10
mario_vittone                     : 1
marion_stokes                     : 1
mark_bergen                       : 1
mark_brown                        : 1
mark_burgess                      : 1
mark_christian                    : 1
mark_cohen                        : 1
mark_davies                       : 1
mark_duggan                       : 1
mark_ellis                        : 1
mark_fisher                       : 2
mark_frauenfelder                 : 1
mark_halperin                     : 2
mark_hicks                        : 1
mark_humphries                    : 1
mark_joseph_stern                 : 2
mark_nelson                       : 1
mark_ovenden                      : 1
mark_recapture                    : 1
mark_riedel                       : 1
mark_riedl                        : 3
mark_ryden                        : 1
mark_sumner                       : 1
mark_thornton                     : 1
mark_townsend                     : 1
mark_whitehouse                   : 1
mark_zuckerberg                   : 4
marloes_horst                     : 1
marsha_blackburn                  : 1
marshal_mcluhan                   : 6         :  marshall_mcluhan
marshall_allen                    : 1
marshall_mcluhan                  : 1
marshall_sahlins                  : 1
marshall_steinbaum                : 1
marsilius_of_padua                : 1
martha_crenshaw                   : 1
martha_davis                      : 1
martin_cobliner                   : 1
martin_daniel                     : 1
martin_heidegger                  : 5
martin_luther                     : 1
martin_luther_king                : 10
martin_oleary                     : 2
martin_van_maele                  : 1
martineau                         : 1  : harriet_martineau
marvin_minskey                    : 1
marvin_minsky                     : 1
marx                              : 63 : karl_marx
mary_allen_wilkes                 : 1
mary_beard                        : 1
mary_hui                          : 1
mary_j_carruthers                 : 1
mary_lumbers                      : 1
mary_preston                      : 1
mary_surratt                      : 1
mashpee_wampanoag                 : 1
maslow                            : 3  : abraham_maslow
massimo_pigliucci                 : 1
mateas                            : 4  : michael_mateas
mathias_prideaux                  : 1
matilda_sissieretta_jones         : 1
matin_van_maele                   : 1
matt_baker                        : 1
matt_baume                        : 1
matt_bevin                        : 1
matt_bors                         : 1
matt_clancy                       : 1
matt_damon                        : 1
matt_elliot                       : 1
matt_gaetz                        : 2
matt_hancock                      : 1
matt_kelly                        : 1
matt_kenney                       : 1
matt_mcmanus                      : 1
matt_novak                        : 1
matt_pharr                        : 1
matt_precey                       : 1
matt_ruff                         : 1
matt_shea                         : 11
matt_smith                        : 1
matt_stieb                        : 1
matthew_charles                   : 1
matthew_connelly                  : 1
matthew_dunlap                    : 2
matthew_gault                     : 2
matthew_longo                     : 1
matthew_salesses                  : 1
mattie_brice                      : 1
maud_simonet                      : 1
maureen_dowd                      : 4
maureen_tkacik                    : 1
maurice_chammah                   : 1
mavis_gallant                     : 1
mawlana_mawdudi                   : 1
mawza_exile                       : 1
max_boot                          : 1
max_gluckman                      : 2
max_green                         : 1
max_horkheimer                    : 3
max_kennerly                      : 1
max_kreminski                     : 2
max_levchin                       : 1
max_liboiron                      : 1
max_rivlin_nadler                 : 1
max_roser                         : 1
max_scheler                       : 1
max_tegmark                       : 1
max_weber                         : 1
maxine_waters                     : 1
maxwell_dev                       : 1
maya_forstater                    : 1
maya_francis                      : 1
maya_goodfellow                   : 1
maya_oppenheim                    : 1
mccain                            : 1  : john_mccain
mccarrick                         : 1
McCarthy                          : 1 : mccarthy
mccarthy                          : 4
mccloskey                         : 1  : deidre_mccloskey
mcconnell                         : 1  : mitch_mcconell
mcdemarco                         : 1  : m_c_demarco
mclaughlin                        : 1  : KA_mclaughlin
mcLuhan                           : 1  : marshal_mcluhan
mcluhan                           : 5  : marshal_mcluhan
mcveigh                           : 1  : tim_mveigh
mechner                           : 1  : jordan_mechner
medgar_evers                      : 1
meg_brock                         : 1
meg_oconnor                       : 1
megan_konar                       : 1
megan_marz                        : 1
megan_molin                       : 1
meghan_markle                     : 3
meghan_mccain                     : 1
megyn_kelly                       : 1
mehdi_dastani                     : 2
meier                             : 1  : sid_meier
meka_beresford                    : 1
melinda_cooper                    : 1
melissa_brinks                    : 1
melissa_del_bosque                : 1
melissa_gira_grant                : 1
melissa_jeltsen                   : 1
melissa_rubio                     : 1
melody_kramer                     : 1
melvin_davis                      : 1
meredith_somers                   : 1
merkel                            : 1  : angela_merkel
merleau_ponty                     : 1  : maurice_merleau_ponty
merrick_garland                   : 1
merton                            : 2  : robert_merton
merve_emre                        : 1
meryl_kornfield                   : 1
meyer                             : 1  : bertrand_meyer
michael_barajas                   : 1
michael_batty                     : 1
michael_bay                       : 1
michael_birnbaum                  : 1
michael_blakey                    : 1
michael_brice_saddler             : 1
michael_casey                     : 1
michael_cohen                     : 2
michael_cook                      : 1
michael_crichton                  : 3
michael_dell                      : 1
michael_fassbender                : 1
michael_flood                     : 2
michael_flynn                     : 1
michael_fogleman                  : 3
michael_folmer                    : 1
michael_gove                      : 2
michael_graham                    : 1
michael_hard                      : 1
michael_hobbes                    : 1
michael_hudson                    : 1
michael_loizos                    : 1
michael_macagnone                 : 1
michael_mann                      : 1
michael_mateas                    : 2
michael_mccain                    : 1
michael_moorcock                  : 1
michael_munger                    : 2
michael_oman_reagan               : 3
michael_reynolds                  : 3
michael_robertson                 : 1
michael_rosfeld                   : 1
michael_schulson                  : 1
michael_schur                     : 1
michael_shannon                   : 1
michael_shur                      : 1
michael_strain                    : 1
michael_w_twitty                  : 1
michael_weiss                     : 1
michael_wolf                      : 1
michael_zhang                     : 1
michaeleen_doucleff               : 1
michah_zenko                      : 1
michel_barnier                    : 1
michel_foucault                   : 23
michel_gondry                     : 1
michelle_anderson                 : 1
michelle_andrews                  : 2
michelle_kim                      : 1
michelle_minkoff                  : 1
michelle_wolf                     : 2
mick_mulvaney                     : 1
mierle_laderman_ukele             : 1
miguel_sicart                     : 1
mikaela_pitcan                    : 1
mikaella_clements                 : 1
mike_acton                        : 1
mike_bloomberg                    : 3
mike_bostock                      : 6
mike_brown                        : 1
mike_cernovich                    : 1
mike_dewine                       : 1
mike_fortun                       : 1
mike_gravel                       : 1
mike_huckabee                     : 1
mike_lee                          : 1
mike_omeara                       : 1
mike_pence                        : 6
mike_pompeo                       : 2
mike_selinker                     : 1
mikhael_subotzky                  : 1
mikhail_bakhtin                   : 1
mikiso_hane                       : 1
miles_klee                        : 1
milewski                          : 1  : bartosz_milewski
miley_cyrus                       : 1
milo                              : 2  : milo_yiannopoulos
milo_yiannopoulos                 : 3
milton                            : 1  : john_milton
milton_friedman                   : 1
mimi_onuoha                       : 1
mindy_jones                       : 1
Mini_Tichu                        : 1
minna_zack                        : 1
minsky                            : 1  : marvin_minsky
miriam_matthews                   : 1
mirna_alsharif                    : 1
misaharu_motoda                   : 1
miss_major                        : 1
mitch_duneier                     : 1
mitch_landrieu                    : 1
mitch_mcconell                    : 2
mitch_mcconnell                   : 3
mitchell_and_webb                 : 1
mitchell_innes                    : 2
mitt_romney                       : 1
miyazaki                          : 1  : hayao_miyazaki
MLK                               : 2  : martin_luther_king
mnuchin                           : 1  : steve_mnuchin
mo_ansar                          : 1
mo_brooks                         : 2
modiba_keita                      : 1
moebius                           : 3
mohammad_khatami                  : 1
mohammed_al_halabi                : 1
mohammed_mosadegh                 : 1
moiz_syed                         : 1
molly_redden                      : 2
molly_russell                     : 1
mona_lisa                         : 1
monica_crowley                    : 1
monique_davis                     : 1
montaigne                         : 1 : michel_de_montaigne
montequieu                        : 1  : charles_louis_montesquieu
montesqueiu                       : 1 : charles_louis_montesquieu
montesquieu                       : 1 : charles_louis_montesquieu
montesuieu                        : 1 : charles_louis_montesquieu
moshe_tennenholtz                 : 1
mossadegh                         : 1  : mohammed_mosadegh
mourid_barghouti                  : 1
mr_friendly                       : 1
mr_pot                            : 1
mr_rogers                         : 1
mrs_butterworth                   : 1
mueller                           : 9  : robert_mueller
muhammad                          : 3
mulvaney                          : 1  : mick_mulvaney
mulvey                            : 1  : laura_mulvey
muntazer_al_zaidi                 : 2
murakami                          : 3  : haruki_murakami
murraygm                          : 1 : murray_grigo_mcmahon
mychal_denzel_smith               : 1
myke_cole                         : 1
n_c_wyeth                         : 1
N_K_jemsin                        : 1
nadav_kander                      : 1
nadja_popovich                    : 2
nadra_nittle                      : 1
nahdlatul_ulama                   : 1
namwali_serpell                   : 1
nancy_astor                       : 2
nancy_drew                        : 1
nancy_fraser                      : 1
nancy_huston                      : 1
nancy_pelosi                      : 3
nancy_roman                       : 2
naomi_klein                       : 1
naomi_oleary                      : 1
naomi_wolf                        : 2
naomi_wu                          : 1
napolean                          : 1  : napoleon_bonaparte
napoleon                          : 1  : napoleon_bonaparte
napoleon_bonaparte                : 2
narendra_modi                     : 1
natalia_mehlman_petrzela          : 1
natalie_martinez                  : 1
natalie_moore                     : 1
natalie_nanasi                    : 1
natalie_portman                   : 1
natalie_shure                     : 1
natalie_wexler                    : 1
natalie_wolchover                 : 1
natasha_aughey                    : 1
natasha_lennard                   : 1
natasha_lyonee                    : 4
nate_boyer                        : 1
nate_chambers                     : 1
nate_crowley                      : 1
nate_silver                       : 2
nathalie_lawhead                  : 1
nathan_bedford_forrest            : 1
nathan_robinson                   : 2
natsumi_hayashi                   : 1
neal_adams                        : 1
neal_stephenson                   : 3
needham_schroeder                 : 1
neel_krishnaswami                 : 1
neelke_doorn                      : 1
neil_comess_daniels               : 1
neil_flightstein                  : 1
neil_fligstein                    : 1
neil_gaiman                       : 3
neil_gorsuch                      : 7
neil_lewis                        : 1
neitzsche                         : 2
nelson_mandela                    : 1
nelson_phillips                   : 1
neta_bomani                       : 1
newell                            : 1  : alan_newell
nicholas_evans                    : 1
nicholas_kristof                  : 2
nicholas_negroponte               : 1
nicholas_rodriquez                : 1
nicholas_watt                     : 1
nichole_roxas                     : 1
nick_blanchette                   : 1
nick_bostrom                      : 1
nick_case                         : 4
nick_fuentes                      : 1
nick_irvin                        : 1
nick_kawa                         : 1
nick_keppler                      : 1
nick_miroff                       : 1
nick_montfort                     : 1
nick_morgan                       : 1
nick_powell                       : 1
nick_seaver                       : 6
nicky_case                        : 1
nicolas_feliciano                 : 1
nicolas_rivero                    : 1
nicole_flatow                     : 1
nicole_goodkind                   : 1
nicole_hemmer                     : 1
nicole_marie_poole_franklin       : 1
nicole_rojas                      : 1
nicole_rudick                     : 1
nidya_sarria                      : 1
nielson                           : 4
nietzsche                         : 1  : friedrich_nietzsche
nigel_farage                      : 1
nigel_warburton                   : 1
nikki_delamotte                   : 2
nikki_giovanni                    : 1
nikki_haley                       : 2
nikki_jones                       : 1
nikki_minage                      : 1
niklas_luhmann                    : 3
nikolas_cruz                      : 1
nina_freeman                      : 1
nina_martin                       : 1
nisha_mody                        : 1
nixon                             : 8  : richard_nixon
noah_smith                        : 1
noam_chomsky                      : 1
noelle_mcafee                     : 1
nolan_h_miller                    : 1
nora_capla_bricker                : 1
norbert_elias                     : 1
norbert_wiener                    : 2
noriega                           : 1  : pablo_noriega
norman_rockwell                   : 1
northam                           : 2  : ralph_northam
norvig                            : 1  : peter_norvig
nozick                            : 1  : robert_nozick
nozik                             : 1  : robert_nozick
nuevo_laredo                      : 1
obama                             : 34 : barack_obama
ocasio_cortez                     : 7
octavia_butler                    : 4
odo_of_cluny                      : 1
olga_khazan                       : 1
olga_lengyel                      : 1
oliver_knight                     : 1
oliver_roeder                     : 1
olivette_otele                    : 1
olivia_hooker                     : 1
olivia_kemp                       : 1
olivia_paschal                    : 1
olivia_pearson                    : 1
olivia_schwob                     : 1
olivia_vane                       : 2
olle_fredriksson                  : 1
olmstead                          : 1  : frederick_olmstead
olson                             : 1
om_tandon                         : 1
omar                              : 1  : ilhan_omar
omar_lizardo                      : 1
omayeli_arenyeka                  : 1
omid_safi                         : 1
oren_nimni                        : 1
orrin_hatch                       : 1
orval_faubus                      : 1
orwell                            : 5  : george_orwell
osama_bin_laden                   : 1
oscar_cain                        : 1
oscar_neimeyer                    : 1
oscar_ramirez                     : 1
Ostrom                            : 1  : elinor_ostrom
ostrom                            : 7  : elinor_ostrom
oswald_spengler                   : 1
otis_wright                       : 3
otto_hoppe                        : 1
owen_bowcott                      : 1
owen_jones                        : 1
ozymandias                        : 1
p_k_dick                          : 1  : philip_k_dick
pablo_azpurua                     : 1
pablo_noriega                     : 1
pablo_torres                      : 1
pachecgo_vega                     : 1  : raul_pacheco_vega
pacheco_vega                      : 23 : raul_pacheco_vega
padma_lakshmi                     : 1
paige_pfleger                     : 1
paine                             : 1 : thomas_paine
palle_nielsen                     : 2
pamela_herd                       : 1
pamela_j_hobart                   : 1
pamela_turner                     : 1
pank_a_squith                     : 1
panumas_king                      : 1
paolo_pedercini                   : 3  : paolo_pedericini
paolo_pedericini                  : 2
parkinson                         : 1  : c_northcote_parkinson
parsons                           : 2  : talcot_parsons
pascal_hausermann                 : 1
pat_buchanan                      : 2
pat_roberts                       : 1
pat_robertson                     : 1
patricia_hernandez                : 10
patricia_huon                     : 1
patricia_matthew                  : 1
patrick_butler                    : 1
patrick_carlineo                  : 2
patrick_kelley                    : 1
patrick_klepek                    : 1
patrick_mckenzie                  : 1
patrick_stewart                   : 2
patrick_tucker                    : 1
patrick_wolfe                     : 1
pauil_manafort                    : 1  : paul_manafort
paul_baran                        : 1
paul_blumenthal                   : 1
paul_cairney                      : 2
paul_chadeisson                   : 2
paul_chiusano                     : 1
paul_cilliers                     : 2
paul_ford                         : 1
paul_graham                       : 1
paul_kelso                        : 1
paul_kingsnorth                   : 1
paul_krugman                      : 2
paul_manafort                     : 1
paul_martin                       : 1
paul_mchugh                       : 2
paul_musgrave                     : 4
paul_nehlen                       : 1
paul_niehaus                      : 2
paul_p_murphy                     : 1
paul_pierson                      : 1
paul_ricoeur                      : 1
paul_robes                        : 1
paul_robeson                      : 1
paul_romer                        : 1
paul_ryan                         : 8
paul_smaldino                     : 1
paul_sturtevant                   : 1
paul_virilio                      : 2
paul_virillo                      : 1
paul_weber                        : 1
paul_weiss                        : 1
paul_weyrich                      : 1
paula_white                       : 1
paulo_freire                      : 1
paulo_pedercini                   : 1
paulo_pedericini                  : 1 : paulo_pedercini
pearl                             : 2  : judea_pearl
pedro_medeiros                    : 2
peel                              : 1  : robert_peel
peirce                            : 1  : charles_peirce
peitraszewski                     : 1  : david_peitraszewski
pelosi                            : 2  : nancy_pelosi
pence                             : 1  : mike_pence
penner                            : 1
perkins_gilman                    : 1
perry_bacon_jr                    : 1
pete_buttigieg                    : 5
pete_cordell                      : 1
pete_keen                         : 1
pete_worth                        : 1
peter_alexander                   : 1
peter_arnell                      : 1
peter_benenson                    : 1
peter_boghossian                  : 1
peter_bradshaw                    : 1
peter_breslow                     : 1
peter_dao                         : 1
peter_drucker                     : 1
peter_funt                        : 1
peter_jamison                     : 1
peter_johnson                     : 1
peter_labarbera                   : 1
peter_molydeux                    : 1
peter_molyneux                    : 4
peter_norvig                      : 3
peter_paul_verbeek                : 1
peter_suber                       : 2
peter_suderman                    : 1
peter_the_great                   : 1
peter_thiel                       : 5
peter_van_roy                     : 1
Petraeus                          : 1  : david_petraeus
pewdiepie                         : 2
phil_agre                         : 2
phil_roe                          : 1
phil_salvador                     : 1
philip_alston                     : 1
philip_k_dick                     : 1
philip_randolph                   : 1
philip_zimbardo                   : 4
philippe_bonnin                   : 1
phillipe_borgio                   : 1
phineas                           : 1
phoebe_sengers                    : 1
piaget                            : 2  : jean_piaget
piccola                           : 1
Piccola                           : 1 : piccola
piero_annoni                      : 1
pierre_bourdieu                   : 19
piers_morgan                      : 2
piketty                           : 2  : thomas_piketty
pippin_barr                       : 4
plato                             : 2
pliny_the_younger                 : 1
pohl                              : 1  : frederick_pohl
pola_oloixarac                    : 1
pompeo                            : 1  : mike_pompeo
pope                                 : 2
pope_formosus                     : 1
pope_francis                      : 1
popehat                           : 7
popeye                            : 1
porpentine                        : 3
posie_parker                      : 1
pressley                          : 1  : ayanna_pressley
primo_levi                        : 1
prince                            : 1
prince_andrew                     : 1
priti_patel                       : 2
prmila_jayapal                    : 1
prue_macsween                     : 1
pynchon                           : 1
qasem_soleimani                   : 1
qasr_kabaw                        : 1
qi_wang                           : 1
queen_victoria                    : 1
quentin_tarantino                 : 1
quine                             : 1 : willard_van_orman_quine
Quixote                           : 1  : don_quixote
r_a_lafferty                      : 1
r_kelly                           : 3
r_lang                            : 5
rachael_tatman                    : 1
rachana_pradhan                   : 1
rachel_armstrong                  : 1
rachel_aviv                       : 1
rachel_brewson                    : 1
rachel_laudan                     : 1
rachel_schon                      : 1
rachel_west                       : 2
rachel_wright                     : 1
rachelle_hampton                  : 1
radiator_yang                     : 1
radiator_yank                     : 1      : radiator_yang
radley_balko                      : 2
radomir_lukic                     : 1
rafael_reif                       : 1
ragnar_tornquist                  : 1
raj_ammanbrolu                    : 1
ralph_borsodi                     : 1
ralph_nader                       : 1
ralph_northam                     : 3
rami_ismail                       : 2
rand_miller                       : 1
rand_paul                         : 2
randall_schriver                  : 1
randall_williams                  : 1
randy_halprin                     : 1
randy_shilts                      : 1
raph_koster                       : 23
raphael_lemkin                    : 1
rashid_al_ghannushi               : 1
rashida_tlaib                     : 1
raul_pacheco_vega                 : 3
raulpacheco                       : 2  : raul_pacheco_vega
rawls                             : 2  : john_rawls
ray_blanchard                     : 3
ray_bradbury                      : 1
ray_cromartie                     : 1
ray_gulcynski                     : 1
ray_kurzweil                      : 2
ray_self                          : 1
raymond_hettinger                 : 1
raymond_reiter                    : 1
raymond_scott                     : 1
rayshard_brooks                   : 5
reagan                            : 14 : ronald_reagan
rebecca_bryant                    : 1
rebecca_buell                     : 1
rebecca_onion                     : 1
rebecca_traister                  : 1
rebecca_vallas                    : 1
recep_erdogan                     : 2
reed_solomon                      : 1
regan                             : 1  : ronald_reagan
rene_thom                         : 1
resnick                           : 2  : brian_resnick
resnick_family                    : 1
reynolds                          : 1  : craig_reynolds
rhodri_phillipps                  : 1
ria_harpsichord                   : 1
riah_milton                       : 1
ricardo_bofill                    : 2
rich_firth_godbehere              : 1
rich_stanton                      : 1
rich_sutton                       : 1
richar_posner                     : 1
richard_attenborough              : 1
richard_bartle                    : 2
richard_branson                   : 1
richard_brath                     : 1
richard_butler                    : 4
richard_carrier                   : 2
richard_cobbett                   : 2
richard_collins                   : 1
richard_corbet                    : 1
richard_dawkins                   : 2
richard_epstein                   : 2
richard_evans                     : 5
richard_feynman                   : 1
richard_garriott                  : 1
richard_gould                     : 1
richard_hamming                   : 1
richard_hartley_parkinson         : 1
richard_hofmeier                  : 1
richard_k_morgan                  : 2
richard_kadrey                    : 1
richard_leong                     : 1
richard_lester                    : 1
richard_morgan                    : 1
richard_nixon                     : 9
richard_odwyer                    : 1
richard_oppel                     : 1
richard_rorty                     : 1
richard_rothstein                 : 1
richard_sackler                   : 3
richard_salame                    : 1
richard_scott                     : 2
richard_spencer                   : 3
richard_sutton                    : 1
richardson                        : 1  : leonard_richardson
rick_beato                        : 1
rick_santorum                     : 1
rick_scott                        : 1
rick_turner                       : 1
ricky_gervais                     : 2
ricoeur                           : 2  : paul_ricoeur
ridley_scott                      : 1
riedl                             : 4  : mark_riedl
rigoberta_vasquez                 : 1
riley_griffin                     : 1
rob_altenhaus                     : 1
rob_beschizza                     : 2
rob_beshizza                      : 1
rob_kitchin                       : 1
rob_portman                       : 1
rob_sheridan                      : 1
rob_zacny                         : 1
robert_atkey                      : 1
robert_auer                       : 1
robert_benchley                   : 1
robert_brandom                    : 4
robert_braxton_jr                 : 1
robert_caroll                     : 1
robert_chazan                     : 1
robert_downen                     : 1
robert_e_lee                      : 1
robert_eads                       : 1
robert_fludd                      : 1
robert_goodin                     : 2
robert_graham                     : 1
robert_jensen                     : 1
robert_keegan                     : 1
robert_kegan                      : 1
robert_mccarter                   : 1
robert_merton                     : 2
robert_moses                      : 2
robert_mueller                    : 9
robert_mugabe                     : 1
robert_nozick                     : 2
robert_paxton                     : 2
robert_peel                       : 1
robert_schuyler                   : 1
robert_sokolowsi                  : 1
robert_steward_sherriffs          : 1
robert_taft                       : 1
robert_tarjan                     : 1
robert_wilensky                   : 1
robert_yang                       : 3
robert_zubek                      : 1
robin_diangelo                    : 1
robin_nagle                       : 1
robin_snyder                      : 1
robtel_neajai_pailey              : 1
roch_kabore                       : 1
rockafeller                       : 1 : john_d_rockafeller
rockwell_anyoha                   : 1
rod_blagojevich                   : 1
rod_ponton                        : 1
rodney_brooke                     : 1
rodney_brooks                     : 2
rodney_howard_browne              : 2
rodney_reese                      : 1
roger_hargreaves                  : 1
roger_highfield                   : 1
roger_schank                      : 1
rokeya_hossain                    : 1
roland_barthes                    : 1
romanovs                          : 3
romero                            : 1  : john_romero
romney                            : 2  : mitt_romney
ron_desantis                      : 1
ron_gilbert                       : 1
ron_hubbard                       : 1
ron_paul                          : 1
ron_perlman                       : 2
ron_wyden                         : 5
ronald_coase                      : 1
ronald_reagan                     : 1
ronan_farrow                      : 1
roosevelt                         : 3  : franklin_roosevelt
roosh                             : 1
roryce_dirden                     : 1
rosa_freedman                     : 1
rosa_furneaux                     : 1
rosa_parks                        : 1
rosamund_snow                     : 1
rosenhan                          : 3  : david_rosenhan
rosh_hashanah                     : 1
rosie_cappuccino                  : 2
rosie_spinks                      : 1
ross_benes                        : 1
rossignol                         : 3  : jim_rossignol
rousseau                          : 1  : jean_jacques_rousseau
rowan_atkinson                    : 1
rowan_kaiser                      : 1
roxsana_hernandez                 : 1
roy_barnes                        : 1
roy_harrison                      : 1
roy_moore                         : 2
roy_more                          : 1
roy_savarimuthu                   : 1
rua_williams                      : 1
rube_goldberg                     : 1
rubert_murdoch                    : 1
rubert_neate                      : 1
rubin                             : 1  : henry_rubin
ruby_bridges                      : 1
ruby_hamad                        : 1
rudy_giuliani                     : 1
rush_limbaugh                     : 2
russell                           : 2  : bertrand_russell
russell_strong                    : 1
ruth_aylett                       : 1
ruth_bader_ginsburg               : 1
ruth_orkin                        : 1
ruth_padawer                      : 1
ruth_simmons                      : 1
ryan_cooper                       : 2
ryan_grim                         : 2
ryan_grimm                        : 1
ryan_zinke                        : 2
ryland_g                          : 1
saac_arnsdorf                     : 1  : isaac_arnsdorf
saartjie                          : 1  : sarah_saartjie_baartman
sabr_al_ashqar                    : 1
sackler                           : 3  : richard_sackler
sadie_roberts_joseph              : 2
sadiq_khan                        : 1
sady_doyle                        : 1
saez                              : 1  : emmanuel_saez
safiya_noble                      : 1
sahar_khalifeh                    : 1
sahlins                           : 1  : marshall_sahlins
said_roberts_joseph               : 1  : saidie_roberts_joseph
saidie_roberts_joseph             : 1
saint_anthony                     : 1
saint_maurice                     : 1
saint_nicholas                    : 1
salar_de_atacama                  : 1
sally_thorne                      : 1
salvador                          : 1  : fabrizio_salvador
salvador_dali                     : 1
salvador_hernandez                : 1
sam_bloch                         : 1
sam_block                         : 1
sam_burns                         : 1
sam_gaye                          : 1
sam_karlin                        : 1
sam_o_nella                       : 1
sam_sykes                         : 1
sam_vimes                         : 1
samanth_subramanian               : 1
samantha_stahlke                  : 1
samar_yazbek                      : 1
samara_weaving                    : 1
samer_muscati                     : 1
samira_shackle                    : 1
samuel_clowes_huneke              : 1
samuel_delaney                    : 1
samuel_hardrix                    : 1
samuel_james_gulik                : 1
samuel_pepys                      : 1
samuel_scott                      : 2
samuel_sinyangwe                  : 1
sandra_bland                      : 1
sandra_fluke                      : 1
sandra_park                       : 1
sandro_meloni                     : 1
sandy_allen                       : 1
sandy_stone                       : 1
sanjoy_chakravorty                : 1
santorum                          : 1      : rick_santorum
sapna_maheshwari                  : 1
sara_ahmed                        : 1
sara_ann_wylie                    : 1
sara_baartman                     : 1
sara_kay                          : 1
sara_mchenry                      : 1
sarah_baylus                      : 1
sarah_cowan                       : 1
sarah_dye                         : 1
sarah_everard                     : 1
sarah_goodridge                   : 1
sarah_graley                      : 1
sarah_jeong                       : 10
sarah_kay                         : 1
sarah_kendzior                    : 3
sarah_kleiner                     : 1
sarah_kliff                       : 1
sarah_laskow                      : 2
sarah_mei                         : 1
sarah_miller                      : 1
sarah_palin                       : 1
sarah_ruhl                        : 1
sarah_saadoun                     : 1
sarah_saartjie_baartman           : 1
sarah_sanders                     : 3
sarah_shannon                     : 1
sartre                            : 2  : jean_paul_sartre
sasannah_cahalan                  : 2
saul_kripke                       : 4
sauntore_thomas                   : 1
saussue                           : 1  : ferdinand_de_saussure
saussure                          : 1  : ferdinand_de_saussure
savarimuthu                       : 1  : roy_savarimuthu
sayyid_ahmad_khan                 : 1
sayyid_qutb                       : 1
scalia                            : 5
scalzi                            : 3  : john_scalzi
schelling                         : 1 : thomas_schelling
schmitt                           : 1  : karl_schmitt
schnelling                        : 1  : thomas_schelling
schumpeter                        : 1 : joseph_a_schumpeter
schutz                            : 1  : alfred_schutz
schwartz                          : 1  : shalom_schwartz
scot_meyers                       : 1
scott_brinker                     : 1
scott_lemieux                     : 2
scott_page                        : 2
scott_pruitt                      : 1
scott_simon                       : 1
scott_wagner                      : 1
scott_walker                      : 4
scott_warren                      : 1
scotti_andrew                     : 1
sean_hannity                      : 3
sean_illing                       : 1
sean_lee_contra                   : 1
sean_maloney                      : 1
sean_mcelwee                      : 1
sean_reed                         : 1
sean_spicer                       : 1
sean_stearns                      : 1
searle                            : 7  : john_searle
sebastian_lague                   : 1
sebastian_theiler                 : 2
sedaris                           : 1  : david_sedaris
seema_verma                       : 1
sejal_singh                       : 1
sekiu_toure                       : 1
selene_montgomery                 : 1
sellars                           : 1      : wilfred_sellars
selznick                          : 1 : philip_selznick
senator_warren                    : 1
serge_marshennikov                : 1
sergey_brin                       : 1
sergio_martinez_beltran           : 1
seth_abramson                     : 1
seth_dickinson                    : 1
seth_donnelly                     : 2
seth_rogan                        : 1
seumas_milne                      : 1
seydou_keita                      : 1
seyla_benhabib                    : 1
shah_bano                         : 1
shaiann_frazer                    : 1
shakespeare                       : 3  : william_shakespeare
shalom_schwartz                   : 1
shami_chakrabarti                 : 1
shamima_begum                     : 6
shana_grice                       : 1
shannon_palus                     : 1
shannon_vallor                    : 1
shantania_love                    : 1
sharon_durbin                     : 1
sharon_lerner                     : 2
sharon_nunn                       : 1
shaun_king                        : 6
shawnda_brookshire                : 2
shay_akil_maclean                 : 1
sheldon_adelson                   : 1
sheldon_cooper                    : 1
shelley_duvall                    : 1
shelley_harrison_reed             : 1
shelly_pearson                    : 1
shepsle                           : 1  : kenneth_shepsle
sherri_bothwell                   : 1
sherri_peach                      : 1
sherrod_brown                     : 1
sherry_rusinack                   : 1
shi_jinsong                       : 1
shia_labeouf                      : 3
shirley_chrisholm                 : 1
shiv_sena                         : 1
Shiva                             : 1
shoham                            : 1  : yoav_shoham
shon_faye                         : 1
shoshana_weissmann                : 2
shoshana_zuboff                   : 1
sid_meier                         : 2
siddhartha_mahanta                : 1
sidgwick                          : 1  : henry_sidgwick
sidney_mintz                      : 1
sigal_samuel                      : 1
silvia_federici                   : 2
simmel                            : 1  : georg_simmel
simon                             : 1  : herbert_simon
simon_baron_cohen                 : 1
simon_biles                       : 1
simon_carless                     : 1
simon_de_thullieres               : 1
simon_dedeo                       : 1
simon_donner                      : 1
simon_murphy                      : 1
simon_parkin                      : 3
simon_roth                        : 1
simon_schama                      : 1
simon_stalenhag                   : 1
simone_biles                      : 2
simone_brown                      : 1
simone_de_beauvoir                : 1
simone_landon                     : 1
sirin_kale                        : 1
siva_vaidhyanathan                : 1
skrillex                          : 2
slava_zilber                      : 1
slavoj_zizek                      : 1
smith                             : 2
snowden                           : 5  : david_snowden
snyder                            : 1  : robin_snyder
snydr                             : 1 : snyder
socrates                          : 1
soleimani                         : 4  : qasem_soleimani
sonia_sotomayor                   : 1
sophie_haigney                    : 1
soren_ahren                       : 1
soren_johnson                     : 2
soren_kierkegaard                 : 1
soren_stevenson                   : 1
spike_lee                         : 1
spinoza                           : 1
srinivas_kuchibhotla              : 1
st_augustine                      : 1
stacey_abrams                     : 1
stan_horaczek                     : 1
stanislas_chaillou                : 2
stanislaw_lem                     : 1
stanley_kubrick                   : 1
steenberg                         : 1  : eskil_steenberg
stefan_bleekrode                  : 2
stefan_kojouharov                 : 1
stefani_crabtree                  : 1
stefanie_mauksch                  : 1
steinle                           : 1  : kate_steinle
steph_black                       : 1
stephane_haffner                  : 1
stephanie_dick                    : 1
stephanie_hofeller                : 1
stephanie_hurlburt                : 1
stephanie_k_baer                  : 1
stephanie_snook                   : 1
stephen_bush                      : 1
stephen_carter                    : 1
stephen_colbert                   : 1
stephen_cummings                  : 1
stephen_diehl                     : 7
stephen_ellner                    : 1
stephen_foster                    : 1
stephen_fry                       : 3
stephen_gill                      : 1
stephen_lansing                   : 1
stephen_lavelle                   : 1
stephen_miller                    : 5
stephen_moore                     : 1
stephen_yaxley_lennon             : 1
stephenson                        : 1  : neal_stephenson
stephon_clark                     : 1
steve_bann                        : 1
steve_crocker                     : 2
steve_eder                        : 2
steve_hasty                       : 1
steve_hickman                     : 1
steve_jobs                        : 1
steve_king                        : 4
steve_mnuchin                     : 1
steve_shapin                      : 1
steve_whittaker                   : 2
steven_feld                       : 1
steven_holl                       : 1
steven_k_vogel                    : 1
steven_levitsky                   : 2
steven_melendez                   : 1
steven_pinker                     : 1
steven_vogel                      : 2
steven_walker                     : 1
stieg_larsson                     : 1
stinchcombe                       : 1
stoya                             : 5
strauss                           : 2  : johann_strauss
Strickland_Bosavi                 : 1
stross                            : 1  : charlie_stross
stroustrup                        : 1  : bjorne_stroustrup
stuart_collier                    : 1
stuart_garner                     : 1
sudano_saheli                     : 1
sue_webster                       : 1
suhaiymah_manzoor_khan            : 1
summer_stephan                    : 1
summer_zervos                     : 1
sun_araw                          : 1
sune_lindstrom                    : 1
sung_cho                          : 1
sung_won_cho                      : 1
supap_kirtaeng                    : 5
suresh_venkatasubramanian         : 1
susan_b_anthony                   : 2
susan_bradley                     : 1
susan_collins                     : 1
susan_cooper                      : 1
susan_crawford                    : 2
susan_silk                        : 1
susan_sontag                      : 1
susana_tosca                      : 1
sussman                           : 3  : gerald_sussman
suzanne_schotz                    : 1
sylvia_monreal                    : 1
t_rex                             : 1
t_s_eliot                         : 1
t_s_ellis                         : 1
ta_nehisi_coates                  : 1
taehoon_kim                       : 1
taha_yasseri                      : 1
tain_bo_culainge                  : 1
takami_s_delisle                  : 1
takato_yamamoto                   : 1
takesada_arisawa                  : 2
talcot_parsons                    : 2
talia_jane                        : 1
talia_lavin                       : 1
tamara_nopper                     : 1
tameen_antoniades                 : 1
tamir_rice                        : 1
tammy_jackson                     : 1
tamsyn_muir                       : 1
tana_ganeva                       : 2
tanya_short                       : 1
tara_murtha                       : 1
tarantino                         : 1  : quentin_tarantino
tarik_ayoub                       : 1
tarjan                            : 1  : robert_tarjan
tarn_adams                        : 1
tate_reeves                       : 1
tatman                            : 1  : rachael_tatman
taylor_swift                      : 1
ted_bundy                         : 1
ted_chiang                        : 2
ted_cruz                          : 3
ted_kaczynski                     : 1
ted_kennedy                       : 1
ted_nelson                        : 2
tej_adeleye                       : 1
tennenholtz                       : 1  : moshe_tennenholtz
tera_hunter                       : 1
teresa_bo                         : 1
teresa_may                        : 10
teri_buhl                         : 2
terrence_parr                     : 1
terri_sewell                      : 1
terry_cavanaugh                   : 1
terry_gilliam                     : 3
terry_pratchett                   : 11
terry_shropshire                  : 1
terry_winograd                    : 1
tess_owen                         : 1
thales                            : 1
thatcher                          : 1 : margaret_thatcher
thea_hunter                       : 1
theirry_urbain                    : 1
thelma_smith                      : 1
theo-stamos                       : 1  : theo_stamos
theo_stamos                       : 1
theodor_adorno                    : 1
theresa_fractale                  : 1
theresa_may                       : 6
theresa_waldrop                   : 1
therese_fractale                  : 1
thibault_le_texier                : 1
thierry_mugler                    : 1
thierry_urbain                    : 1
thomas_aquinas                    : 1
thomas_friedman                   : 1
thomas_grip                       : 1
thomas_hobbes                     : 1
thomas_jefferson                  : 2
thomas_luckmann                   : 1
thomas_malthus                    : 1
thomas_modly                      : 2
thomas_more                       : 1
thomas_nast                       : 1
thomas_petricek                   : 1
thomas_piketty                    : 2
thomas_schelling                  : 1
thomas_scoville                   : 1
thomas_sowell                     : 1
thornton_oakley                   : 1
tiana_cornelius                   : 1
tiana_smalls                      : 1
tiffany_haddish                   : 1
tim_brap                          : 1
tim_cornwell                      : 1
tim_durrant                       : 1
tim_ferris                        : 1
tim_ferriss                       : 1
tim_langdell                      : 1
tim_leary                         : 1
tim_meko                          : 1
tim_miller                        : 1
tim_mveigh                        : 1
tim_noble                         : 1
tim_o_reilly                      : 1
tim_razumovsky                    : 1
tim_reynolds                      : 1
tim_sullivan                      : 1
tim_wu                            : 1
timothy_brown                     : 1
timothy_dugan                     : 1
timothy_leary                     : 2
timothy_may                       : 1
timothy_pachirat                  : 1
tin_tin                           : 1
tina_burnside                     : 1
tina_kaidanow                     : 1
tina_vasquez                      : 1
tinker_princess                   : 2
tlaib                             : 1  : rashida_tlaib
toby_fox                          : 1
toby_walsh                        : 1
toby_young                        : 1
tocqueville                       : 4  : alexis_de_tocqueville
todd_bridgman                     : 1
todd_spitzer                      : 1
tolkien                           : 4  : j_r_r_tokien
tolstoy                           : 2  : leo_tolstoy
tom_austin                        : 1
tom_carroll                       : 1
tom_clancy                        : 2
tom_coburn                        : 1
tom_cruise                        : 1
tom_eckerle                       : 1
tom_gauld                         : 1
tom_hall                          : 1
tom_hanks                         : 1
tom_jennings                      : 1
tom_lawrence                      : 1
tom_odonnell                      : 1
tom_price                         : 1
tom_robbins                       : 1
tom_simonite                      : 1
tom_steyer                        : 1
tom_waidzunas                     : 1
tomi_laren                        : 1
tommy_robinson                    : 2
tommy_thompson                    : 1
tondalao_hall                     : 2
tony_blair                        : 2
tony_evers                        : 1
tony_larsen                       : 1
tony_rackauckas                   : 1
tonya_mosley                      : 1
toph_tucker                       : 1
torre_van_der                     : 1  : leendert_van_der_torre
toshio_saeki                      : 1
toufik_marir                      : 1
tracey_lindeman                   : 1
tracey_tully                      : 1
tracy_hickman                     : 1
travion_blount                    : 1
trayvon_martin                    : 1
trent_lott                        : 1
trent_reznor                      : 2
tresa_baldas                      : 1
tressie_mcmillan_cottom           : 2
tricia_lockwood                   : 1
tristan_strong                    : 1
troiano                           : 1  : james_troiano
troy_duster                       : 1
trudeau                           : 1  : justin_trudeau
tsutomu_nihei_a                   : 1
tucker_calson                     : 1 : tucker_carlson
tucker_carlson                    : 7
tufte                             : 1  : edward_tufte
tukufu_zuberi                     : 1
turing                            : 1  : alan_turing
turley                            : 1  : johnathan_turley
tye_anders                        : 1
tyler_cowen                       : 1
tynan_sylvester                   : 1
tyra_hunter                       : 1
uma_jayakumar                     : 1
umberto_eco                       : 3
umbridge                          : 1  : dolores_umbridge
ursuala_le_guin                   : 1  : ursula_le_guin
ursula_le_guin                    : 2
valeria_ramierz                   : 1
valerie_complex                   : 1
valerie_strauss                   : 1
valonia_ventricosa                : 1
van_der_kolk                      : 1  : bessel_van_der_kolk
vandermeer                        : 1  : jeff_vandermeer
vanessa_kirby                     : 1
vannevar_bush                     : 1
venkatesh_rao                     : 1
ventresca                         : 1 : mark_ventresca
veronica_walsingham               : 1
vi_hart                           : 2
vic_mignona                       : 1
vickers_cunningham                : 1
vicki_boykis                      : 1
vicki_schieber                    : 1
vicky_alvear_shecter              : 1
vicky_osterweil                   : 1
vicky_schaubert                   : 2
victor_hugo                       : 3
victor_zhou                       : 1
victoria_dailey                   : 1
victoria_krakovna                 : 1
victoria_peckham                  : 1
victoria_tran                     : 1
vikram_dodd                       : 1
viktor_macha                      : 1
viktor_shokin                     : 1
vilem_flusser                     : 1
vimal_patel                       : 1
vincent_le_moign                  : 1
vincent_price                     : 1
vincent_shilling                  : 1
vincent_warmerdam                 : 1
vincenzo_galdi                    : 1
vint_cerf                         : 1
virginia_dignum                   : 7
virginia_eubanks                  : 1
vivian_malone                     : 1
vladimir_putin                    : 1
vladimir_shukhov                  : 1
volkmom                           : 1
voltarine_de_cleyre               : 1
von_mises                         : 1
vqr                               : 1 : venkatesh_rao
vy_higgensen                      : 1
vygotsky                          : 1  : lev_vygotsky
w_e_b_du_bois                     : 1
wachowski                         : 1  : lana_wachowski
waidzunas                         : 1  : tom_waidzunas
walida_imarisha                   : 1
walt_heyer                        : 1
walter_benjamin                   : 1
walter_burley                     : 1
walter_kaufmann                   : 1
walter_lippman                    : 1         :  walter_lippmann
walter_lippmann                   : 1
walter_rodney                     : 1
walter_white                      : 1
Wang_tta                          : 1
ward_shelley                      : 1
warren                            : 2  : elizabeth_warren
warren_spector                    : 1
wayne_mcgregor                    : 1
weber                             : 10
weinstein                         : 2  : harvey_weinstein
weiyi_cai                         : 1
weizenbaum                        : 3  : joseph_weizenbaum
wendy_blchere                     : 1
wendy_carlos                      : 1
wendy_cross                       : 1
wes_anderson                      : 1
wes_goodman                       : 1
wesley_ryan                       : 1
wharram_percy                     : 1
whit_taylor                       : 1
wieyi_cai                         : 1  : weiyi_cai
wilfred_sellars                   : 1
wilhelm_dilthey                   : 1
wilhelm_rustow                    : 2
will_lowe                         : 1
will_mcavoy                       : 1
will_oremus                       : 1
will_partin                       : 1
will_self                         : 1
will_wright                       : 5
willa_paskin                      : 1
william_barr                      : 4
william_camden                    : 1
william_cheng                     : 1
william_dawley                    : 1
william_gibson                    : 3
william_hawkeswood                : 1
william_hogeland                  : 1
william_huber                     : 3
william_labov                     : 1
william_lambarde                  : 1
william_obrien                    : 1
william_perry                     : 2
william_quiller_orchardson        : 1
william_shakespeare               : 3
william_stafford                  : 1
william_taylor                    : 1
william_thompson                  : 1
william_whitfield                 : 1
williamson                        : 1  : kevin_williamson
winograd                          : 1  : terry_winograd
winston_churchill                 : 1
winston_duke                      : 1
wittgenstein                      : 5  : ludwig_wittgenstein
wollstonecraft                    : 1 : mary_wollstonecraft
woodrow_wilson                    : 1
wordsworth                        : 1 : william_wordsworth
wudan_yan                         : 1
xavier_portela                    : 1
xenakis                           : 5  : iannis_xenakis
xeni                              : 1  : xeni_jardin
xeni_jardin                       : 1
xenophanes                        : 1
xi_jinping                        : 1
xojane                            : 1
y_nakajima                        : 1
yad_vashem                        : 1
yang_song                         : 1
yanis_varoufakis                  : 3
yarden_katz                       : 1
yarin_gal                         : 1
yascha_mounk                      : 1
yasha_levine                      : 1
yasmeen_khan                      : 1
yoav_shoham                       : 1
yob_zacny                         : 1
yochai_benkler                    : 3
yogita_goyal                      : 2
yohanan_petrovsky_shter           : 1
yoshito_hasaka                    : 1
young_lee                         : 1
yuda_pearl                        : 1
yusuf_al_qaradawi                 : 1
zachary_macaulay                  : 1
zachary_pleat                     : 1
zak_smith                         : 1
zdzislaw_beksinski                : 1
zeynep_tufecki                    : 3  : zeynep_tufekci
zeynep_tufekci                    : 1
zhuo_chen                         : 1
ziblatt                           : 1  : daniel_ziblatt
zieselman_mascott_kimberly        : 1
zigmunt_bauman                    : 1
zimbardo                          : 4  : philip_zimbardo
zimmerman                         : 1  : eric_zimmerman
zinn                              : 1  : howard_zinn
zipporah_arielle                  : 1
ziyad_marar                       : 1
zizek                             : 1  : slavoj_zizek
zoe_williams                      : 1
zolan_kanno_youngs                : 1
zook                              : 2  : alexander_zook
zora                              : 1  : zora_neale_hurston
zora_neale_hurston                : 1
zubek                             : 1  : robert_zubek
zuckerberg                        : 1  : mark_zuckerberg
zucman                            : 1 : gabriel_zucman
zynep_tufecki                     : 1
