#+title: AntiChamber Lessons

* [[https://antichamber.fandom.com/wiki/List_of_Signs][AntiChamber]]
1) Every journey is a series of choices. The first is to being the journey.
2) Patience has its own rewards.
3) Taking the first step can be harder than the rest of the challenge.
4) Many small obstacles can make for one large problem.
5) Some choices leave us running around a lot without really getting anywhere.
6) Live on your own watch, not on someone else's.
7) Failing to succeed does not mean failing to progress.
8) Some paths are clearer than others.
9) Some paths are straight forward.
10) A choice may be as simple as going left or going right.
11) The choice doesn't matter if the outcome is the same.
12) If you don't like where you've ended up, try doing something else.
13) When you return to where you have been, things aren't always as remembered.
14) We fall down when there is nothing there to support us.
15) Building a buridge can get you over a problem.
16) Some hurdles are too high to jump over.
17) Life is full of ups and downs.
18) Connecting the pieces can solve a puzzle.
19) Life has a way of pushing us in the right direction.
20) the end may come before we were ready to get there.
21) Life isn't about getting to the end.
22) It's harder to progress if you're leaving things behind.
23) The further we get, the less help we need.
24) Moving forward may require making the most of what you've got.
25) Some tasks require a lot of care and observation.
26) Taking one path often means missing out on another.
27) A path may not be right or wrong. It may just be different.
28) Look a little harder, and you will find a way forward.
29) Venturing into the unknown can lead to great rewards.
30) If you're only focusin on right now, you won't have enough for later.
31) A dead end will only stop you if you don't try to move through it.
32) Going a certain way may require building your own path.
33) There's nothing wrong with taking shortcuts.
34) We often fall into things when we least expect.
35) What looks out of reach may only be a few steps away.
36) There are multiple ways to approach a situation.
37) When you've hit rock bottom, the only way is up.
38) Some outcomes are more favourable than others.
39) How we perceive a problem can change every time we see it.
40) The solution to a problem may just require a more thorough look at it.
41) Rushing through a problem won't always give the right results.
42) Moving through a problem slower may help find the solution.
43) If you never strop trying, you will get there eventually.
44) Raw persistence may be the only option other than giving up entirely.
45) Some problems just come down to size.
46) A Problem may only be difficult when you are missing the right tools.
47) What we've done before may impact what we can do next.
48) If you aren't paying attention, you will miss everything around you.
49) Some choices can leave us running around in circles.
50) Splitting a problem up may help you find the answer.
51) What appears impossible may have a very simple answer.
52) If you lose sight of what's important, it may not be there when you need it.
53) Too much curiosity can get the best of us.
54) Signs may be helping you more than you realize.
55) Understanding a problem requires filling in the pieces.
56) Small steps can take you great distances.
57) The path of least resistance is a valid option.
58) No matter how high you climp, there's always more to achieve.
59) Falling down teaches us how to get up and try again.
60) The world rarely changes when we watch to see it happen.
61) Half way through is half way finished.
62) The problem may not be where you're going, but how to get there.
63) New skills enable further progress.
64) Mastering a skill requires practice.
65) A little kind direction can get obstacles out of your way.
66) Solving a problem may require approaching it from a different angle.
67) Try hard enough and you will get to where you want to be.
68) Some doors will close unless we hold them open.
69) When you absorb your surroundings, you may notice things that you didn't see before.
70) Dig a little deeper and you may find something new.
71) Attention to detail can lead to very rewarding outcomes.
72) Solving a problem may require using abilities that we didn't realize we had.
73) Old skills are useful even after we have learned new ones.
74) The right answers may also be the most obvious ones.
75) Some Obstacles are more stubborn than others.
76) Some things don't have a deeper meaning.
77) The right decisions at the right time will get you where you want to go.
78) Some choices are only useful when we make them early.
79) With forethought, things have a way of just working themselves out.
80) Some challenges are far harder than they first appear.
81) To get past a problem, you may just need to keep pushing through it.
82) Getting to a solution requires cutting out what doesn't work.
83) The further we explore, the more connected everything becomes.
84) A Window of opporunity can lead to new places if you are willing to take a closer look.
85) The world looks different on the other side.
86) When you have enough resources, you can start growing more.
87) You can grow a garden anywhere.
88) The best solutions may still be the most primitive ones.
89) If you lead the way, others will follow.
90) Straightforward problems can often require roundabout solutions.
91) If you are missing information, it's easy to be misled.
92) When you look beyond the surface, there may be more to find.
93) Sometimes we only have just enough to get by.
94) When what you have is not enough, find ways to turn it into more.
95) Getting where we want may require jumping through some hoops.
96) Throwing yourself into things can take you to new heights.
97) Similar problems can have entirely different solutions.
98) Some events happen whether we want them to or not.
99) Old solutiosn can apply to new problems.
100) The consequences of the one choice can cut us off from making others.
101) At times we need to view the world from someone else's perspective.
102) Sometimes you need to be carried.
103) There comes a time when you can work your way through anything.
104) With more experience, previous challenges aren't so difficult.
105) There's no need to take apart what already works.
106) A few steps backwards may keep you moving forwards.
107) Obscure problems may require unusual solutions.
108) Getting to the end requires tying off the loose ends.
109) The world is always finding new ways to surprise us.
110) Sometimes we do things just to go along for the ride.
111) The more we complete, the harder it gets to find what we missed.
112) Some challenges exist just to test how much we know.
113) You can't do everything yourself.
114) The world is full of secrets waiting to be uncovered.
115) Peeking behind the curtains lets us see how everything works.
116) Some problems can't be solved until you're more experienced.
117) We move on when there is nothing left to learn.
118) Complicated problems are easier when solved one step at a time.
119) We can appreciate the entire journey by looking back at how far we have come.
120) Every journey comes to an end.
