#+TITLE: Douglas Adams Quotes

* Hitchhikers Guide

** On Going Mad
#+begin_quote
'The point is, you see,' said Ford, 'that there is no point driving yourself mad trying to stop
yourself going mad. You might as well give in and save your sanity for later'.
'And this is you sane again, is it?' asked Arthur. 'I ask merely for information.'
#+end_quote

** Being able to govern
#+begin_quote
“The major problem—one of the major problems, for there are several—one of the many major problems with governing people is that of whom you get to do it; or rather of who manages to get people to let them do it to them.
To summarize: it is a well-known fact that those people who most want to rule people are, ipso facto, those least suited to do it.
To summarize the summary: anyone who is capable of getting themselves made President should on no account be allowed to do the job.”
#+end_quote

** Thats Terrible
#+begin_quote
'Listen Bud', said Ford, 'if I had One Altairian dollar for every time I heard one bit of the
Universe look at another bit of the Universe and say "That's Terrible" I wouldn't be sitting here
like a lemon looking for a gin. But I haven't and I am. Anyway, what are you looking so placid
and moon-eyed for? Are you in love?'
#+end_quote

** Human Beings are Great Adaptors
#+begin_quote
"Human Beings are great adaptors, and by lunchtime life in the environs of
Arthur's house had settled into a steady routine. It was Arthur's accepted role
to lie squelching in the mud making occasional demands to see his lawyer, his
mother or a good book; it was Mr Prosser's accepted role to tackle Arthu with
the occasional new ply such as the For the Public Good talk, or the March of
Progress talk, the They Knocked My House Down Once You Know, Never Looked Back
talk and various other cajoleries and threats; and it was the bulldozer drivers'
accepted role to sit around drinking coffee and experimenting with union
regulations to see how they could turn the situtation to their financial
advantage."
#+end_quote

** The Man who rules the universe
#+begin_quote
FORD PREFECT:    Er, excuse me, do you rule the Universe?

MAN:     I try not to. Are you wet?

FORD:    Wet! Well, doesn't it look as if we're wet?

MAN:    That's how it looks to me, but how you feel about it might be a different matter. If you find warmth makes you feel dry you'd better come in.
#+end_quote

** The creation of the universe
#+begin_quote
In the beginning the Universe was created. This has made a lot of people very
angry and has been widely regarded as a bad move.
#+end_quote

** Real small furry creatures from alpha centauri
#+begin_quote
In those days spirits were brave, the stakes were high, men were real men, women
were real women and small furry creatures from Alpha Centauri were real small
furry creatures from Alpha Centauri.
#+end_quote

** Vogon Ships
#+begin_quote
The ships hung in the sky in much the same way that bricks don't.
#+end_quote

** Theory of the Universe
#+begin_quote
There is a theory which states that if ever anybody discovers exactly what the
Universe is for and why it is here, it will instantly disappear and be replaced
by something even more bizarre and inexplicable. There is another theory which
states that this has already happened.
#+end_quote

** Time is an Illusion
#+begin_quote
Time is an illusion. Lunchtime doubly so.
#+end_quote

** Life as some kind of dream
#+begin_quote
He felt that his whole life was some kind of dream and he sometimes wondered
whose it was and whether they were enjoying it.
#+end_quote

** The speed of bad news
#+begin_quote
Nothing travels faster than the speed of light with the possible exception of
bad news, which obeys its own special laws.
#+end_quote

** Strange definition of safe
#+begin_quote
Ah, this is obviously some strange usage of the word 'safe' that I wasn't
previously aware of.
#+end_quote

** When something that can't possibly go wrong, does.
#+begin_quote
The major difference between a thing that might go wrong and a thing that cannot
possibly go wrong is that when a thing that cannot possibly go wrong goes wrong
it usually turns out to be impossible to get at or repair.
#+end_quote

** Presidencies
#+begin_quote
Anyone who is capable of getting themselves made President should on no account
be allowed to do the job.
#+end_quote

** Space is big
#+begin_quote
Space is big. You just won't believe how vastly, hugely, mind- bogglingly big it
is. I mean, you may think it's a long way down the road to the chemist's, but
that's just peanuts to space.
#+end_quote

* Dirk Gently

** Going Where I needed to be
#+begin_quote
I may not have gone where I intended to go, but I think I have ended up where I needed to be.
#+end_quote

* Misc
#+begin_quote
For us, there is no longer a fundamental mystery about Life. It is all the
process of extraordinary eruptions of information, and it is information which
gives us this fantastically rich, complex world in which we live; but at the
same time that we've discovered that we are destroying it at a rate that has no
precedent in history, unless you go back to the point when we are hit by an
asteroid!
#+end_quote

#+begin_quote :source Dirk Gently
"What really is the point of trying to teach anything to anybody?"

This question seemed to provoke a murmur of sympathetic approval from up and
down the table.

Richard continued,
"What I mean is that if you really want to understand something, the best way is to try and explain it to someone else.
That forces you to sort it out in your mind. And the more slow and dim-witted your pupil,
the more you have to break things down into more and more simple ideas.
And that's really the essence of programming.
By the time you've sorted out a complicated idea into little steps that even a stupid machine can deal with, you've learned something about it yourself."
#+end_quote

#+begin_quote
Part of how we come to take command of our world, to take command of our
environment, to make these tools by which we're able to do this, is we ask
ourselves questions about it the whole time. So this man starts to ask himself
questions. "This world," he says, "so who made it?" Now, of course he thinks
that, because he makes things himself. So he's looking for someone who would
have made this world. He says, "Well, so who would have made this world? Well,
it must be something a little like me. Obviously much much bigger. And
necessarily invisible. But he would have made it. Now why did he make it?" Now
we always ask ourselves "why?" because we look for intention around us; because
we always intend– we do something with intention. We boil an egg in order to eat
it. So we look at the rocks, and we look at the trees, and we wonder what
intention is here even though it doesn't have intention.
#+end_quote

#+begin_quote
If we think that the world is here for us we will continue to destroy it the way we have been destroying it, because we think we can do no harm.
#+end_quote

#+begin_quote
All opinions are not equal. Some are a very great deal more robust, sophisticated and well supported in logic and argument than others.
#+end_quote

** Extraordinary Genius and Naive Incompetence
#+begin_quote
He attacked everything in life with a mix of extraordinary genius and naive
incompetence, and it was often difficult to tell which was which.
#+end_quote

** Deadlines
#+begin_quote
I love deadlines. I like the whooshing sound they make as they fly by.
#+end_quote

** Living and Learning
#+begin_quote
You live and learn. At any rate, you live.
#+end_quote

** Humans and learning from others
#+begin_quote
Human beings, who are almost unique in having the ability to learn from the
experience of others, are also remarkable for their apparent disinclination to
do so.
#+end_quote

** Normality
#+begin_quote
Anything that is in the world when you’re born is normal and ordinary and is
just a natural part of the way the world works. Anything that’s invented between
when you’re fifteen and thirty- five is new and exciting and revolutionary and
you can probably get a career in it. Anything invented after you’re thirty-five
is against the natural order of things.
#+end_quote

** Pretty Smart
#+begin_quote
Even he, to whom most things that most people would think were pretty smart were
pretty dumb, thought it was pretty smart.
#+end_quote
** Scientific Method
#+begin_quote
"See first, think later, then test. But always see first. Or, you will only see what you were expecting. Most scientists forget that."
#+end_quote
