#+TITLE: John Brunner

* Stand on Zanzibar

** Chad C Mulligan Fictional Quotes
1) (IMPOSSIBLE Means: 1 I wouldn’t like it and when it happens I won’t approve; 2 I can’t be bothered; 3 God can’t be bothered. Meaning 3 may perhaps be valid but the others are 101% whaledreck.

—The Hipcrime Vocab by Chad C. Mulligan)

2) (RUMOUR Believe all you hear. Your world may not be a better one than the one the blocks live in but it’ll be a sight more vivid.

—The Hipcrime Vocab by Chad C. Mulligan)

3) (HIPCRIME You committed one when you opened this book. Keep it up. It’s our only hope.

—The Hipcrime Vocab by Chad C. Mulligan)

4) (COINCIDENCE You weren’t paying attention to the other half of what was going on.

—The Hipcrime Vocab by Chad C. Mulligan)

5) It's no cooincidence “that we have muckers. Background: ‘mucker’ is an Anglicisation of ‘amok’. Don’t believe anyone who says it’s a shifted pronunication of ‘mugger’. You can survive a mugger, but if you want to survive a mucker the best way is not to be there when it happens.

“Prior to the twentieth century the densest concentration of human beings was almost certainly found in Asian cities. (Except Rome and I’m coming to Rome later.) When too many people got in your way you armed yourself with a panga or a kris and went out to cut some throats. It didn’t matter if you were educated in their use or not—the people you came up against were in their normal frame of reference and died. You were in the berserk frame of reference. Background: the berserkers developed from communities who for a large part of the year sat on their asses in Norwegian fjordal valleys with an unclimbable mountain range on each side, a lid of horrible grey cloud on top, and you couldn’t get away by sea either because of the winter storms.

“There’s a saying among the Nguni of South Africa that you didn’t only have to kill a Zulu warrior—you had to push him over to make him lie down. Background: Chaka Zulu made it a policy to take his assegai-fodder from their parents in early childhood and raise them in barrack-like conditions owning no possessions bar a spear, a shield and a sheath to hide the penis, with absolutely no privacy. He made independently the same discovery the Spartans made.

“Also it was when Rome had already become the world’s first million-city that the Eastern mystery religions with their concomitant self-privation and self-mutilation took hold. You fell in behind the procession honouring Cybele, you seized a knife from one of the priests, you cut your balls off and ran through the streets waving them till you came to a house with the door open when you threw them over the threshold. They gave you an outfit of women’s clothing and you joined the priesthood. Reflect on the pressure that drove you to think that that was the easy way out!”

—You’re an Ignorant Idiot by Chad C. Mulligan

6) (HUMAN BEING You’re one. At least, if you aren’t, you know you’re a Martian or a trained dolphin or Shalmaneser.

If you want me to tell you more than that, you’re out of luck. There’s nothing more anybody can tell you.

—The Hipcrime Vocab by Chad C. Mulligan)

7) “Rather painfully, we managed to digest Darwinian evolution so far as physical attributes were concerned within half a century of the initial controversy. (I say ‘we,’ but if you’re a bible-thumping fundamentalist I expect you at this point to take the book by one corner at arm’s length and ceremonially consign it to the place where you put most sensible ideas, along with everything else you decline to acknowledge the existence of, such as mainly shit.)

“We still haven’t digested the truth that evolution applies to mental functions, too—that because a dog is a dog, a dolphin a dolphin, it has an awareness and sense of personal identity distinct from ours but not necessarily inferior. Is an apple inferior to an orange?

“But I’m trying to tell you what’s happening to you, not what’s happening to Crêpe Suzette your neurotic poodle. A good veterinary psychologist can probably be located by calling Information. You wouldn’t believe him if he started telling you how much you have in common with that pet of yours, and likely you won’t believe me. But if I annoy you sufficiently you may at least try to think up arguments to demonstrate how wrong I am.

“Basically, then: you have two things in common. You’re a pack-animal; so is a dog. You’re a territorial animal; so is a dog. (The fact that we mark our manors with walls instead of urine is irrelevant.)

“The depiction of Man the Noble Savage standing off the wolves at the cave entrance, all by himself with a club, while his mate and their young cower in the background, is so much whaledreck. When we were at the stage of taking refuge in caves our habit was almost certainly to congregate in troupes the way baboons still do, and when the dog-baboons move in everyone else—note that everyone!—moves out. I mean like lions will shift the scene, and a lion is not what you’d call a defenceless creature.

“Lions are rather solitary, tending to work by couples over a manor which affords them adequate game for subsistence. Or not, depending on outside pressure from other members of the species. (Try owning a whole tomcat and you’ll see the process in miniature.) Pack-animals have the evolutionary edge—in combination they’re deadly. Lions learn this as cubs and then ignore the practice, which is why baboons can cave them in.

“NB: I said ‘everyone’, not ‘everything’. You wouldn’t recognise your ancestors as people, but they were, and you still are. Those ancestors were arrogant bastards—how else did they become boss species on our ball of mud? You’ve inherited from them just about everything that makes you human, apart from a few late glosses such as language. You got territoriality along with the rest. If somebody trespasses on it you’re liable to turn killer—although if you don’t like the idea you can kill yourself, which is among our few claims to uniqueness.

“Territoriality works this way. Take some fast-breeding animals like rats—or even rabbits, though they’re herbivorous rodents, not carnivores as we are—and let them multiply in an enclosure, making sure at all stages they have enough food and water. Early on you’ll see them behaving in the traditional rat fashion when conflicts arise: the quarrellers will square up to one another, feint, jab, charge and withdraw, the victory going to the more efficient braggart. Also the mothers will take good care, rat-style, of their young.

“When the pen becomes crowded past a certain point, the fights won’t be symbolic any more. There’ll be corpses. And the mothers will start to eat their young.

“It’s even more spectacular in the case of solitary creatures. Put a female ripe for mating into too small a cage that’s already occupied by a healthy male, and he’ll drive her out rather than give way to the reproductive urge. He may even kill her.

“Very baldly, then: shortage of territory, of space to move around and call your own, leads to attacks on members of your own species in defiance even of the normal group-solidarity displayed by pack-animals. Lost your temper with anyone lately?

“However, being a member of a species that’s nothing if not ingenious, you’ve figured out two directions in which you can abstract your territoriality: one is to privacy, the other is to property.

“Of the two, the former is more animal and more reliable. Your base need is to have a manor defined against a peer group, but you don’t have to do as dogs, tomcats and sundry other species do—mark it out with a physical trace, then patrol it constantly to scare away intruders. You can abstract to a small enclosed area where no one else trespasses without your permission, and on this basis you can operate fairly rationally. One of the first concomitants of affluence is a rapid raising of privacy-standards: someone from a comparatively low-income background has to accept that his childhood will be lived in a crowded, busy environment—in contemporary household terms, one room of the dwelling (if it has more than one) will be a family-room and that’s the centre of operations. Someone from a more prosperous home, however, will take it for granted from about the time he learns to read that there’s a room where he can go in and shut the door against the world.

“This is why (a) men from wealthy backgrounds make better companions under privative conditions such as a Moon voyage—they don’t feel that their human environment is a permanent infringement of their right to a manor, no matter how thoroughly it’s been abstracted from the original referent of a piece of terrain (b) the standard route out of the slum or ghetto is crime—equals getting your own back on other members of your species who trespass continually on your manor; (c) gangs develop primarily in two contexts—first, in the slum or ghetto where privacy as a counterpart of the manor can’t be had and a reversion takes place to the wild state, with pack-hunting and the patrolling of an actual physical patch of ground; and second, in the armed services, where the gang is dignified by being called a ‘regiment’ or some other hifalutin dirty word but where the reversion to the wild state is deliberately fostered by deprivation of privacy (barracks accommodation) and deprivation of property (you don’t wear the clothes you chose and bought, you wear a uniform which belongs to US!!!). Fighting in an army is a psychotic condition encouraged by a rule-of-thumb psychological technique discovered independently by every son-of-a-bitch conqueror who ever brought a backward people out of a comfortable, civilised state of nonentity (Chaka Zulu, Attila, Bismarck, etc.) and started them slaughtering their neighbours. I don’t approve of people who encourage psychoses in their fellow human beings. You probably do. Cure yourself of the habit.

“We are breeding so fast that we cannot provide adequate privacy for our population. That might not be fatal—after all, it wasn’t until as a species we discovered affluence that the demand for it became overwhelming. But we’re undermining the alternative form of abstraction of territoriality, and deprived of both we’re going to wind up psychotic in the same way as a good soldier.

“The point of abstracting to property is that the manor forms an externalised aid to self-identification. Put a man in a sensory deprivation tank, he comes out screaming or shaking or … We need continual environmental reassurance that we are who we think we are. In the wild state, the manor provides such a reassurance. In the state we’ve been describing a few paragraphs back, the ability to shut ourselves away from the continually fluctuating pressure of our peers enables an intermittent reassessment of our identity. We can lean on a group of objects—a clever surrogate for a patch of ground—but only if they have (a) strong personal connotations and (b) continuity. The contemporary environment denies us both. The objects we possess weren’t made by ourselves (unless we’re fortunate enough to display strong creative talents) but by an automated factory, and furthermore and infinitely worse we’re under pressure every week to replace them, change them, introduce fluidity into precisely that area of our lives where we most need stability. If you’re rich enough you go and buy antiques and you like them as a pipeline into the past, not because you’re a connoisseur.

“The classical slave system survived for a long while despite the paradoxical discontinuity of pan-human identity which is implicit in any such social pattern. The American slave system was already breaking to pieces before the Civil War. Why? The answer is in the Code of Hammurabi, among other places—the first truly elaborate legal code we have any record of. It lays down fines and other punishments for personal injury. Although it’s true that the penalty for injuring a free man is heavier than for injuring a slave, the slave is always there. Under the Romans, a slave had a certain inalienable minimum both of property (NB!) and of civil rights, which not even his owner could infringe. It was thinkable for a debtor to sell himself into slavery and pay off what he owed, in the rational—maybe far-fetched, but not lunatic—anticipation of recouping his fortunes. The first successful banker we know about was a Greek slave called Pasion who made himself a millionaire, bought his freedom and went into partnership with his former bosses.

“In the case of the American negro slave this possibility was not inherent in the system. The slave had the same human rights as a head of cattle—nil. A good master might conceivably manumit a slave who’d done him a good turn, or pension him off with his freedom as a favourite horse would be put out to pasture to spend his declining years in peace. But a bad one might decide to maim the man, brand him, or flog him to death with an iron-tipped cat-o’-nine-tails, and there was no one to call him to account.

“True, you’re not a slave. You’re worse off than that by a long, long way. You’re a predatory beast shut up in a cage of which the bars aren’t fixed, solid objects you can gnaw at or in despair batter against with your head until you get punch-drunk and stop worrying. No, those bars are the competing members of your own species, at least as cunning as you on average, forever shifting around so you can’t pin them down, liable to get in your way without the least warning, disorienting your personal environment until you want to grab a gun or an axe and turn mucker. (This is in essence why people do that.)

“And there are more of them than ever before—and you’ve grown to expect privacy so that every now and then you can take the pressure off, but that privacy is becoming more and more expensive so that it’s considered normal for even well-paid businessmen to share their apartments in order to enjoy luxuries their own salaries won’t stretch to, such as rooms large enough to hold their private possessions as well as themselves—and you’re being commanded by today’s aggressive advertising to throw out those cherished belongings and get others which are strange to you—and you’re being told day and night from authoritative official sources that people you don’t know but who adhere to some mysterious quasi-religious precepts known as Marxist-Leninist-Maoist dogma and communicate in a language whose characters you can’t even recognise as real writing are trying to trespass on your national gang’s manor—and …

“In the last decade of the twentieth century sales of tranks soared a whopping thirteen hundred per cent. Unless you’ve been living in a country too poor to furnish the supplies, the odds are that two of every five of your acquaintances are dicties—perhaps on some socially acceptable drug like alcohol, but quite likely on a trank that by way of side-effect depresses orgasmic capacity and compels the user to resort to orgies in order to stimulate flagging potency, or on a product like Skulbustium which offers the tempting bait of a totally, untrespassably private experience and entrains senile dementia rather more certainly than tobacco entrains cancer of the lung.

“In short: your life from birth to death resembles the progress of a hopelessly drunk tightrope walker whose act has been so bad up till now that he’s being bombarded with rotten eggs and broken bottles.

“And if you fall off, what they will do is broadly this: they’ll take you out of the environment you’re used to—you don’t like it much, but at least it’s not totally strange—and put you somewhere else you’ve never been before. Your key deprivation is of territoriality; they will shove you in a cell which has nothing whatever about it to help identify you as an individual. Your secondary lacks are of abstracted territoriality-equivalents; they will take away the clothes you chose yourself and give you tattered second- or twentieth-hand garments, and you will have no privacy whatever because on the basis of a time-schedule deliberately randomised so that you can’t even brace yourself for the impact by the clock of hunger you carry in your stomach they will fling open the door and stare at you to see what you’re doing.

“You will wind up inventing a private language because there’s no other way of isolating yourself; you’ll scrawl on the walls with your excrement because nothing else in the place belongs to you except the products of your own body; and they will call you a hopeless case and intensify the ‘treatment’ you’re receiving.

“Don’t say that it won’t happen to you. The odds in favour have been going up daily for a hundred years. You know at least half a dozen people who have been in mental hospitals, and of that half-dozen at least one was related to you, even if no more closely than as a cousin. Again, if this is not the case, that’s because you’ve been living in a country too poor to afford enough mental hospitals for its population on the generally accepted scale.

“Thank heaven for such countries! You might do worse than emigrate to one if what I’ve been saying worries you.”

—You: Beast by Chad C. Mulligan

8) (NEGRO Member of a subgroup of the human race who hails, or whose ancestors hailed, from a chunk of land nicknamed—not by its residents—Africa. Superior to the Caucasian in that negroes did not invent nuclear weapons, the automobile, Christianity, nerve gas, the concentration camp, military epidemics, or the megalopolis.

—The Hipcrime Vocab by Chad C. Mulligan)

9) (PATRIOTISM A great British writer once said that if he had to choose between betraying his country and betraying a friend he hoped he would have the decency to betray his country.

Amen, brothers and sisters! Amen!

—The Hipcrime Vocab by Chad C. Mulligan)

10) “At bottom the human species finds idealism an uncomfortable posture. Prime evidence of this can be found in the way neither of the two groups locked in irresoluble conflict around the Pacific has been able to achieve its stated goal—even though, given the lucid, simple, obviously attractive statement of either of their ideals, an impartial observer might wonder why commitment had not ensued like sunrise after night.

“‘Give the wealth back to the people who created it!’ Here’s an ideal capable of generating crusades among people who interpret it as expropriating greedy landlords, sharing out land so that every family may enjoy reasonable nutrition and repudiating debts to moneylenders at usurious rates of interest. Having hit on this, the Chinese charged ahead—until they overreached themselves. They became unable to distinguish between the evils they were preaching against and those traditional influences which literally constituted the way of life of people they hoped to recruit to their cause. In short order they fell into the same pit as their rivals, who had for decades ignored the plain and simple fact that to a starving man ‘freedom’ implies a full rice-bowl—or, if he has an exceptional imagination, a healthy ox to pull his plough. It has nothing to do with voting for a political delegate.

“Analogously with the way the Tsarist army deserted en masse during the First World War, not because of Bolshevik impact on the soldiers but because they were sick of fighting and wanted to go tend their farms, the eager early recruits to the red flag discovered that while they were dying abroad the things they wanted to guard were being undermined at home. So they quit. China, like Russia before her, found she was surrounded by a gaggle of heirs to the mantle of the late Marshal Tito, not a few of whom were themselves within China’s boundary.

“However, by that time, thanks to ineptitude, racial prejudice against them, fighting the right wars with the wrong weapons, and general mismanagement of their affairs, the opposition (or if you prefer, which I don’t because I’d rather not identify with such a bunch of incompetents, ‘our side’) was so far in arrears that the greatest single territorial gain to date in a contest which bids fair to outdo the Hundred Years’ War both for duration and for inconclusiveness only restored a rough balance and didn’t tip the scales the other way.

“We can’t even claim in honesty that it was the result of foresight and planning—only that when the grabbing was good, we grabbed. Don’t believe anyone who tries to claim that the existence of Isola is proof of the superiority of the Western system. The Chinese couldn’t have taken over. There was no form of discontent they could have exploited. How do you whip up resentment against absentee landlords and pocketers of bribes when the highest ambition of the people concerned is either to become the former or be in a position to receive the latter?

“Life in the Philippines had become intolerable well before the civil war of the 1980s. The state of things obtaining (which some accounts misname anarchy, but which any decent dictionary will tell you was nothing of the sort, but free-enterprise capitalism gone out of its skull) was on the verge of ruining the country permanently. The annual average of unsolved murders was running around 30,000 in a population of under fifty million. In the eyes of the inhabitants of the Sulu Archipelago, where most of them were committed, the offence for which they revolted against and ultimately assassinated President Sayha was that he interfered in their traditional right to slaughter and steal. This was unforgivable.

“Oh, doubtless there were some among the people who gave that celebrated majority of eighty-eight per cent in the plebiscite on secession who hoped that being policed and governed by Big Brother in Washington would ensure them a quieter life, free them from the need to fit bullet-proof shutters and plant man-traps in their gardens. Far more, however, seem to have hoped that the bait on the hook (full States’ rights and a billion dollars of aid) would offer another and fatter cake of which they could snatch their slice.

“Which of these parties saw its dream fulfilled? Dear reader, you must be joking. That vaunted billion-dollar aid budget went nowhere near the natives’ pockets. It was spent on roads, airfields, port facilities and fortifications. And, while it’s true that the smugglers and black-marketeers who had hitherto rampaged unchecked had their hinder ends smartly kicked, to get rid of them the new owners imposed martial law and it hasn’t been lifted since 1991!

“Dubbed ‘Isola’ on the grounds that Montana was a mountainous territory and the new acquisition was an island territory, the Junior State went from the frying-pan into the fire. However, the Americans had been desperately in need of bases closer to the Asian mainland than what they currently had, and they were reasonably well satisfied.

“The Chinese, on the other hand, when they tried a counterstroke by wooing Yatakang, were disappointed. The Yatakangi are descendants of the former dominant people in South-East Asia and firm believers in the traditional military dictum that the first thing you do after contracting an alliance is prepare plans for the day when your ally welshes on you. Just because they’re Asiatics it doesn’t follow that they’re going to invite their yellow fellows into their beds. Nor, because they haven’t performed the Peking kotow, should it be assumed (as some blockbottoms I know in Washington have assumed) that they are all set to become the second Isola. Why should they? Things are peachy down in Yatakang; it’s among the world’s great nations, by Asian standards it’s fabulously wealthy, and it can enjoy the game of playing off Washington against Peking until doomsday, on present evidence.

“Until doomsday? Well, perhaps that’s a slight exaggeration. There’s one bright spot in the generally gloomy picture known as the Pacific Conflict Zone. According to my calculations, by the year 2500 or so we should have killed off every last member of our species who is stupid enough to take part in so futile a pastime as this war between ‘ideals’, and with luck they won’t have left their genes behind because they’ll typically have been killed at an age when society thinks they’re too young to assume the responsibility of childbearing. And after that we may get some peace and quiet for a change.”

—Better ? than ? by Chad C. Mulligan

11) “People who feel the need to foul up their perceptions with hop or Yaginol or Skulbustium simply aren’t turned on to the essential truth that the real world can always be identified by its unique characteristic: it, and it only, can take us completely by surprise.

“Take two lumps of greyish metal and bring them together. Result: one wrecked city.

“Could anyone have predicted or envisaged that until they knew enough about the real world to calculate the properties of a substance called Uranium-235?

“People are going around marvelling at the fact that there’s a solid scientific basis for palmistry. Anybody with a grain of intelligence could have said, directly the notion of the genetic code was formulated, that there was no a priori reason why the pattern of the folds in the palm should not be related to a person’s temperament by way of an association of genes sharing the same chromosome. Indeed, there were all kinds of reasons for assuming this actually was so, because we aren’t totally stupid—as I’ve pointed out before—and unless there was in palmistry some element of relevance to real experience we’d have given it up and gone chasing some other will-o’-the-wisp. There’s no shortage of them.

“But it took forty years for someone to conduct a properly rigorous study of the subject and demonstrate that the suspicion was well-founded. This I do find remarkable—or disheartening might be a better word.

“All right: what should you be surprised at, these days?

“The fact that, having learned so much about ourselves—the designs on our palms being just one example of the way we’ve analysed ourselves down to the constituent molecules, so that we can claim to be in sight of the day when we won’t merely be able to ensure the sex of our offspring (if we can afford the fee) but also to choose whether we’ll have a math genius in the family, or a musician, or a moron (some people might like to breed a moron for a pet, I guess…)—having got to this state, then, we know less about our reactions in the mass than we do about the behaviour of non-human things like a lump of U-235.

“Or maybe it’s not so amazing. Without being totally stupid, we do display a tremendous aptitude for it.”

—You: Beast by Chad C. Mulligan

12) (HISTORY Papa Hegel he say that all we learn from history is that we learn nothing from history. I know people who can’t even learn from what happened this morning. Hegel must have been taking the long view.

—The Hipcrime Vocab by Chad C. Mulligan)

13) (ART A Friend of mine in Tulsa, Okla., when I was about eleven years old. I’d be interested to hear from him. There are so many pseudos around taking his name in vain.

—The Hipcrime Vocab by Chad C. Mulligan)

14) “To my mind the most frightening book ever published is Lewis F. Richardson’s Statistics of Deadly Quarrels. You’ve probably never heard of it even though its relevance to the mess you’re in is at least as great as that of Darwin’s On the Origin of Species, which you learned about in fourth grade. And that’s because it’s so completely terrifying only those ‘experts’ who are adequately armoured with preconceived contrary ideas which will enable them to disregard Richardson’s work completely ever get to study it.

“The subject, of course, is one which you think you’re an expert on, too—just as was the case when Darwin started stirring things up. People knew they were conscious, intelligent beings and apparently if they conceded the resemblance between themselves and the animals they were well acquainted with they attributed it to a lack of imagination on the part of the Creator—or perhaps even lauded a proper Puritan parsimony in His unwillingness to waste a good working design after it had been field-tested by the apes.

“So you believe that it’s in the interests of your family, friends and compatriots when you doll yourself up in uniform, take the gun you’re issued and go off to a messy death in the swamps of some place you wouldn’t visit on vacation even if you were a centenarian who’d been every place else bar Mars.

“What Richardson demonstrated in essence (and what has been reinforced by the small handful of people who’ve followed up his work over the past half-century) was that war follows a stochastic distribution: that’s to say, it’s neither absolutely random, nor yet is it definable in a systematic pattern, but something between the two. The pattern is there, but we cannot attribute one-for-one a causal relationship that would account for every specific case.

“In other words, the incidence of war is independent of the volitional element. It makes no odds whatever whether a rational decision has been taken—war, like the weather, just happens.

“Much earlier than Richardson, before World War I, in fact, Norman Angell had shown that the idea of fighting a war for profit was obsolete. The victors would pay a heavier cost than the losers. He was right, and that First World War proved the fact. The second one hammered it home with everything up to and including nuclear weapons. In an individual one would regard it as evidence of insanity to see someone repeatedly undertaking enterprises that resulted in his losing precisely what he claimed he was trying to achieve; it is not less lunatic to do it on the international scale, but if you’ve been catching the news lately you’ll have noticed it’s being done more than ever. The Chinese go on bleating about the withering away of the state and never stop conducting a series of harassing skirmishes on their neighbours’ territory that compels them with true Marxist inevitability to regiment and regulate their population. The Americans and their allies—what few we have left—boast of their unprecedented degree of personal freedom and submit their sovereignty to a computer in Washington, known as the draft selector, which every day condemns several hundreds of them to a death as pointless as that of the Roman gladiators. Put it this way: suppose there were a mindless idiot on your block (and until GT produces proof that Shalmaneser really can develop intelligence I shall go on regarding computers of whatever breed as idiots savants), and once a week his mental condition cycled into a state where he needed to tear someone else apart with his nails and teeth—and the consensus among your neighbours was that every family in turn should detail one of its members to stroll along to where this idiot lived and lie down for him to slaughter …

“There: I told you you were an expert on this subject. This is exactly what the draft does, except that it doesn’t take the sort of member your family might spare—grandma aged 107 who’s been senile for years, for example, or that baby who somehow crept through the filter of eugenic legislation and wound up with phenylketonuria. It takes the handsomest, healthiest, most vigorous, and nobody else.

“Remind you of something? It should do; the folk imagination has occasional curious insights and one of them has been repeated for uncountable millennia. From Andromeda chained on her rock to the maidens offered up to the dragon St. George slew, the theme of destroying the most precious, the most valuable, the least replaceable of our kinfolk recurs and recurs in legend. It tells us with a wisdom that we do not possess as individuals but certainly possess collectively that when we go to war we are ruining ourselves.

“But you’re an expert on this, aren’t you? You know very well that it’s thanks to the Confederate dead, or the victims of the Long March, or the heroic pilots of the Battle of Britain, or self-incinerated kamikazes, that you’re here, today, enjoying your wonderful daily life so full of pleasure, reward, love, joy and excitement.

“Actually I’ll wager that it’s rather more full of anxiety, problems, economic difficulties, quarrels and disappointments, but if you’re so attached to them I shan’t be able to shake you loose. Love and joy are incredibly habit-forming; often a single exposure is enough to cause permanent addiction. But I have no doubt you steer clear as much as you can of anything so masterful.”

—You’re an Ignorant Idiot by Chad C. Mulligan

15) “If you want to know what’s shortly due for the guillotine look for the most obvious of all symptoms: extremism. It is an almost infallible sign—a kind of death-rattle—when a human institution is forced by its members into stressing those and only those factors which are identificatory, at the expense of others which it necessarily shares with competing institutions because human beings belong to all of them. A sound biological comparison would be the development of the fangs of the sabre-tooth tiger to the point where the beasts can’t close their mouths any more, or the growth of armour that’s indisputably impregnable but which weighs so much the owner can’t support his bulk.

“On this basis, it’s fairly certain that Christianity won’t last out the twenty-first century. To take but a couple of prime instances: the hiving off from Rome of the so-called Right Catholics, and the appearance of the Divine Daughters as an influential pressure-group. The former exhibits a remarkable deviation from the traditional attitude of the Catholic Church as an institution that above all concerned itself with the family, Western style; the Right Catholics have become so obsessed with the simple act of fucking that they appear to have no time left for other aspects of human relationships, although they issue pronunciamenti galore on them. None of these bears even the slight relevance to contemporary reality which a sympathetic eye (not mine) can detect in similar statements originating from the Vatican. And the latter, who professedly model themselves on the mediaeval orders of nuns but who actually have borrowed the majority of their tenets—antimechanisation, distrust of bodily pleasure and so on—from respectable, well-integrated groups like the Amish and then soured them by a judicious admixture of the vinegar of hatred, are capitalising on about the most self-defeating of modern trends, our reluctance to further overburden our resources by having large families. They exploit our vicarious appreciation of people, especially women, who decline to have any progeny whatever, thus relieving us of a sense of personal responsibility for the whole damned mess.

“They won’t last.

“I can’t say I see much better times ahead for Muslims, either; though Islam has become a sizeable minority religion in the Western West in the past half-century, the spearhead of its advance has been the descendant of a schism, like the Right Catholics. I mean, naturally, the Children of X, who have constructed nothing more than an analogue of Christianity using their murdered patron as their Osiris-Attis-Jesus figure. They’ll go the way of the mystery religions of ancient times, and for the same reason: they’re exclusionist, and you aren’t allowed in unless you fulfil certain conditions of birth, primarily that you should be recognisably coloured. (I feel a lot less strongly, by the way, about racial discrimination in organisations I don’t want to join. It’s an indication that they’ll die out eventually.)

“Regrettably, however, this leper-mark of extremism isn’t confined to such expendable traits as religion. Look at sex, for example. More and more people are spending more time at it, and resorting to ever more devious ways of keeping up their enthusiasm, like commercially available aphrodisiacs and parties that are considered to be failures unless they evolve into orgies. A hundred different shiggies a year, which is something a young man can achieve without doing more than taking off his clothes, fulfils neither of the essential biological requirements of the sexual urge: it doesn’t lead to a stable environment for the cubs of the next generation, nor does it establish the kind of rapport between couples (or multiples—marriage works on all kinds of bases, not invariably monogamous) which serves to avert crisis over the possession of other members of the species. On the contrary, it leads rather to a kind of frenzy, because instead of the partners enjoying a continual and reciprocal reassurance about their respective masculinity/femininity they are driven to seek that reassurance anew every few days.

“In effect, applying the yardstick of extremism leads one to conclude that the human species itself is unlikely to last very long.”

—You’re an Ignorant Idiot by Chad C. Mulligan

16) (LEADERSHIP A form of self-preservation exhibited by people with autodestructive imaginations in order to ensure that when it comes to the crunch it’ll be someone else’s bones which go crack and not their own.

—The Hipcrime Vocab by Chad C. Mulligan)

17) (SHALMANESER That real cool piece of hardware up at the GT tower. They say he’s apt to evolve to true consciousness one day. Also they say he’s as intelligent as a thousand of us put together, which isn’t really saying much, because when you put a thousand of us together look how stupidly we behave.

—The Hipcrime Vocab by Chad C. Mulligan)

18) (UNFAIR Term applied to advantages enjoyed by other people which we tried to cheat them out of and didn’t manage. See also DISHONESTY, SNEAKY, UNDERHAND and JUST LUCKY I GUESS.

—The Hipcrime Vocab by Chad C. Mulligan)

19) (POPULATION EXPLOSION Unique in human experience, an event which happened yesterday but which everyone swears won’t happen until tomorrow.

—The Hipcrime Vocab by Chad C. Mulligan)

20) (LOGIC The principle governing human intellection. Its nature may be deduced from examining the two following propositions, both of which are held by human beings to be true and often by the same people: “I can’t so you mustn’t,” and “I can but you mustn’t.”

—The Hipcrime Vocab by Chad C. Mulligan)

** Mr. & Mrs. Everywhere: Calypso
#+begin_quote
“Like the good Lord God in the Valley of Bones

Engrelay Satelserv made some people called Jones.

They were not alive and they were not dead—

They were ee-magi-nary but always ahead.

What was remarkably and uniquely new—

A gadget on the set made them look like you!

“Watching their sets in a kind of a trance

Were people in Mexico, people in France.

They don’t chase Jones but the dreams are the same—

Mr. and Mrs. Everywhere, that’s the right name!

Herr und Frau Uberall or les Partout,

A gadget on the set makes them look like you.

“You can’t see all the places of interest,

Go to the Moon and climb Mount Everest,

So you stay at home in a comfortable chair

And rely on Mr. and Mrs. Everywhere!

Doing all the various things you would like to do,

A gadget on the set makes them look like you.

“Wearing parkas and boots made by Gondola

You see them on an expedition polar.

They’re sunning on the beach at Martinique

Using lotion from Guinevere Steel’s Beautique.

Whether you’re red, white, black or blue

A gadget on the set makes them look like you!

“When the Everywhere couple crack a joke

It’s laughed at by all right-thinking folk.

When the Everywhere couple adopt a pose

It’s the with-it view as everyone knows.

It may be a rumour or it may be true

But a gadget on the set has it said by you!

“English Language Relay Satellite Service

Didn’t do this without any purpose.

They know very well what they would like—

A thousand million people all thinking alike.

When someone says something you don’t ask who—

A gadget on the set has it said by you!

“‘What do you think about Yatakang?’

‘I think the same as the Everywhere gang.’

‘What do you think of Beninia then?’

‘The Everywheres will tell me but I don’t know when.’

Whatever my country and whatever my name

A gadget on the set makes me think the same.”
#+end_quote

** THE PROS AND CONS OF A LUNATIC SOCIETY

“Thank you for that kind introduction, Madam Chairman. Well, ladies and
gentlemen—you will forgive me for sitting down while I address you, I’m
sure, because coming home from Moonbase Zero after a long stay is rather
like getting up after being bedridden for a month and carrying one’s own
weight under six times the lunar gravity is a tiring task.

“I thought I might begin by answering some of the questions which people
most commonly ask me, and to which I assume the answers aren’t very widely
known or else they wouldn’t crop up so often. As you know, my speciality is
psychology, so people very often say to me, ‘Isn’t it a terrible strain
living up there on the Moon—isn’t it a hostile, terrifying environment?’

“They’re always surprised when I say no, not nearly as bad as right here on
Earth. But that’s the literal truth. You see, on the Moon you know exactly
how the environment can be hostile to you. You know that if you puncture a
tunnel-wall, or snag your suit, you’re in danger of death, or at least of
losing a limb to dehydratory gangrene when the sphincter at the next joint
inwards seals off the empty section of the suit. You know that if you forget
to switch your suit to reflecting before crossing a patch of open ground in
full sunlight you’ll bake before you return to shadow, and if you don’t cut
in your heaters when you go out at night your feet will be frostbitten
within fifty metres.

“More important than that, though, you know you’re in an environment where
co-operation is essential to survival.

“There are no strangers on the Moon. I’ve had my life saved three separate
times by people I’d never met before and one of them was a Chinese. I’ve
done the same—and this is not in any sense boasting because it’s a fact of
lunar existence—for two people, one a professional colleague and one a
novice I hadn’t even spoken to since his arrival a week earlier.

“Living-space is at a premium, of course, and we’re all jammed together in a
sort of immobile submarine, but we’re hand-picked for our ability to make
allowances for the failings of our fellow human beings, and anyone who
doesn’t measure up to the intensive demands of the lunar base is shipped
home fast. Perhaps some of you have seen a play called ‘Macbeth of Moonbase
Zero’, Hank Sodley’s remake of the Shakespeare original, in which this
paranoid establishes contact with aliens who can predict the future? The
whole thing’s a nonsense, because paranoia loses its meaning on the Moon.
You are being threatened, and you can learn and control the forces
threatening you.

“Down here on Earth, though, you may walk around the corner and find
yourself confronting a mucker with an axe or a gun. You may catch a strain
of antibiotic-resistant germs. You may—especially here on the West Coast—run
into one of the little pranks invented by the funny people who treat
sabotage as an amusing hobby. You have absolutely no way of telling whether
that innocuous stranger over there is about to haul out a weapon and attack
you, or blow a disease your way, or explode an incendiary bomb in your
disposall tube.

“In short, life on the Moon is much more like Bushman society prior to
European contamination, or the basal culture of the Zuñi, than it is like
life here in California or Moscow or Peking.

“That’s why we Lunatics don’t regard our environment as intolerable. Muckers
don’t develop where people feel that everyone else is on their own side
rather than out to undermine them. Diseases can be controlled almost down to
single organisms because we have the finest sterilisation facilities
imaginable—just let a little space and raw sunlight in, and you’ve cooked
every known terrestrial germ to a faretheewell. Lunar-native organisms, of
course, can’t infect human bodies. And as for playing dangerous pranks with
sabotage gadgets, this is literally unthinkable.

“Now when I’ve explained that, people usually say how odd it is to find the
staff of one of mankind’s most advanced scientific projects behaving more
like Bushmen than modern Americans. That is, if they’ve seen the point of my
earlier explanation.

“So I have to say no, it’s the reverse of odd, it’s a simple consequence of
the fact that the lunar environment contains a fixed number of variables.
Human beings can cope with big plain facts like seasons or lunar night and
day, like drought or vacuum, like a pestilence among the game animals they
feed off or a rocket going astray and crashing a load of provisions into a
mountainside. What we can’t cope with is seven billion competing members of
our own species. You have too many incalculable variables to make a rational
response when a crisis occurs.

“And one more thing, too. There’s no one on the moon who doesn’t know that
he’s making a contribution to the whole. Not a day goes past but you can
point to something you’ve done and say, ‘I achieved that today!’ It may be
physical, like adding an extension to the living accommodation, or it may be
intangible, like adding to our stock of stellar observations, but it’s
indescribably satisfying. These days, an urban psychiatrist here on Earth
thinks twice about handling a case with a rural background, but up there
I’ve been responsible for the mental welfare of people not only from
different countries but of different religions and different ideologies, and
I’ve never had a major problem from it.

“When I get this far people usually flinch and inquire nervously whether
that includes the little red brothers. And I can say nothing else except
that trying to subvert vacuum or a solar storm will get you one place and
that’s a grave.

“Of course I’m including Chinese! Like I said, I owe my life to a Chinese
colleague, a man we’d exchanged with the staff of the communist observatory
at Aristarchus. And down here in the middle of the Pacific, which apart from
Antarctica is the only part of the planet that you can compare to the Moon
for loneliness and lack of life-supports, all you can think of doing is
blasting each other. It makes me sick. Madam Chairman, somebody had better
get me a trank, and maybe then I’ll be able to get on with the cosy
tourist-type gossip I have down here in the rest of my notes. Right now I
don’t think I could read it without vomiting.”

Back on the road, Norman said, “And what would State think of
that—uh—presentation?”

“It was honest,” Gideon said with a shrug. “It’s hardly what they’ll hear
over the TV, but it’s honest.”

Norman hesitated. “There was something I wanted to ask, but it seems foolish
… The hole! Why was young Simon so eager to stress that he’d seen someone
lose his temper?”

“That’s a very bright kid. And sophisticated.”

“Anyone could see he’s no simpleton! But I asked—”

“He could say that in English. He couldn’t have said it in Shinka, which is
his native language, and that’s good for a boy barely into his teens, isn’t
it?”

Norman shook his head in bewilderment.

“Ask this linguist—what’s his name? The one you brought with you.”

“Derek Quimby.”

“Ah-hah. Ask him if you can express the idea of losing your temper in
Shinka. You can’t. You can only use the word which means ‘insane’.”

“But—”

“I’m telling you.” Gideon guided the car around a wide curve, seeking a
route between potholes. “I don’t speak the language well myself, but I can
get along. Facts are: you can say ‘annoyed’ or even ‘exasperated’, but both
those words came originally from roots meaning ‘creditor’. Someone you get
angry with owes you an apology in the same way you’re owed money or a cow.
You can say ‘crazy’ and put one of two modifiers on the front of it—either
the root for ‘amusing’ or the root for ‘tears’. In the latter case, you’re
talking about someone who’s hopelessly out of his mind, sick, to be tended
and cleaned up after. In the former, you’re inviting people to laugh at
someone who’s lost his temper, but will return to normal sooner or later.”

“They regard anger as being literal insanity?”

“They don’t regard it as being important enough to have a separate word to
label it, that’s all I can say.”

“But people must lose their tempers occasionally!”

“Of course they do. I’ve even seen Zad lose his temper. But that wasn’t at
anybody—it was the day his doctors told him he must retire or die. Did him a
power of good, too, like any catharsis. What they don’t do is go crazy-mad
and smash things that they’ll regret later. I’ve been here more than two
years and I haven’t seen a parent hit a child. I haven’t seen a child hit
another child. Trip him over, yes, or jump out at him from around a corner
and pretend to be a leopard. You know what the Mandingo used to say about
the Shinka in the old days?”

Norman gave a slow nod. “They were magicians who could steal the heart out
of a warrior.”

“Right. And the way they do it is by dodging passion. I don’t know how they
manage it, but there’s the record. A thousand or more years in the same
spot, not bothering anyone, and like I said the day you arrived they
swallowed up the Holaini and the Inoko and Kpala immigrants … Shall I tell
you something you really won’t believe?”

“You already did.”

“I mean really. Laying out that corpse and painting its face white reminded
me. The first Christian missionary to come here was a Spanish friar called
Domingo Rey. You know the Spanish had a trading post not far from Port Mey,
an outstation for Fernando Po? There’s a marker on the site you could go and
look at if you have time.

“Anyway, this friar did a very un-Christian thing. He went out of his mind
and drowned himself after he’d been here seven years. He was convinced he’d
been trapped by Satan. He’d learned enough Shinka to start preaching, and
started off with some of the parables and highlights of the gospel, and to
his dismay the people he talked to said no, you’ve got that wrong, it wasn’t
anyone far away called Jesus but our own man Begi who did that. You know
about Begi?”

“I don’t think I do,” Norman said after a pause.

“Any briefing on Beninia that leaves Begi out of account isn’t worth
having,” Gideon grunted. “I guess you’d call him a folk-hero, a sort of Jack
character, or maybe like this Anancy that you find in the West Indies. His
name apparently means ‘winter-born’, and they say he always used to carry a
blunt spear and a shield with a hole in it—to look through. And as you might
expect the stories about him were more to the Shinka taste than those about
Jesus.

“The one which allegedly drove the poor friar out of his skull—want to hear
it?”

“Sure, go ahead.”

Gideon eased the car down a particularly rutted stretch of road, avoiding
potholes. “Well, the stories say he’d reached a ripe old age and enormous
popular esteem because he’d made wizards look foolish and overcome a
sea-monster and even got the better of his grandfather’s ghost, so everybody
used to bring problems to him. And one time the boss Holaini, the Emir—which
the Shinka turned into ‘Omee’, incidentally, meaning ‘indigestion’; they
love bad puns—the Emir, anyway, got sick of the way the Shinka kept
outsmarting their lords and masters. Like for instance they’d imposed a
swingeing tax and people went to Begi and complained, and he said why don’t
you drive your fertile cows into the Holaini bull-pens and give them back
their own calves when you pay the tax? Which sort of tickled their sense of
humour. And, by the way, he said, according to the story, ‘Give the Emir
what belongs to the Emir!’”

“Render unto Caesar?” Norman muttered.

“You’ve hit it. So finally the Emir sent messengers to demand who was
playing these underhand tricks, and Begi owned up and off he went, and the
Emir pegged him out on an anthill in the traditional style. And when his old
blind father the chief came to visit him in his last moments, he said the
Shinka shouldn’t hold his death against the Holaini because they were too
stupid to see the point of what he had said to them.”

“Father, forgive them, for they know not what they do?”

“Your being raised as a Baptist saves me explaining a lot of things to you,
doesn’t it? I guess if Friar Rey had been a bit more sophisticated he’d have
thought of the possibility that some Christian legends had reached here on
the grapevine, like the story of Buddha is supposed to have got to Rome and
led to his being canonised as St. Josaphat—you heard that one? But I guess
the climate of ideas wasn’t on his side in those days.

“Well, what it boils down to is that Begi already enshrined the Shinka
concept of a perfect man, tolerant, level-headed, witty—the whole shtick. It
wasn’t till some more broad-minded missionary hit on the notion of saying
that Begi was a prophet sent to the Shinka that Christianity made any
progress here. And nowadays you’ll hear Shinkas saying that Begi had better
sense than Jesus because he brought his teaching to people who understood
it, while Jesus overreached himself and preached to people like the British
who can’t have understood or they wouldn’t behave as they do.”

There was a period of silence except for the humming of the motor and
occasional complaints from the suspension. At last Norman said, “I told you
I’d never seen a dead body before. I don’t know how I could have said that.”
He swallowed enormously, his throat seeming to be blocked against the
admission he was trying to make. “Because … Well, the other day I killed
somebody.”

“What? Who?”

“A Divine Daughter. She took an axe to Shalmaneser. She’d already chopped
the hand off one of our technicians.”

Gideon thought that over. He said eventually, “There’s a Shinka proverb.”

“What?”

“You have many years to live—do things you will be proud to remember when
you’re old.”

** MOTHER AND BABY DOING WELL?

“Hello, you out there, furious at the Eugenics Processing Board for denying
you the right to parenthood! Wouldn’t be so bad if paternalism were out of
fashion altogether, would it? But it’s inner than in. You put up with a
hundred and one things that are forbidden ‘for your own good’, and if
there’s anything you are allowed to do it’s probably for the good of the
people who could forbid it and don’t.

“I’m lucky, since they tell me I have a couple of good healthy
prodgies—matter of fact, they’ve both called me recently since they learned
I hadn’t returned my phosphorus to the planetary pool. Their calls set me
thinking about the chances I took when I started them on their merry way,
and some of the facts I’ve dug up are kind of scary. I mean, without a
computer analysis would you ordinarily do something that gave eight chances
out of a hundred of saddling you for ten, fifteen years—maybe for life—with
a greedy, demanding and stupid animal?

“Right. I’m talking about a subnormal child.

“Digging around, I came up with an estimate given to a reporter in Stockholm
in 1959 by Professor Linus Pauling, the man who hung a name and identity on
a disease called phenylketonuria. That’s the earliest place I’ve found the
hard, cold figure of eight per cent, and I’m too lazy to look any further
right now.

“Pauling said: approximately two of every hundred babies born in communities
for which records existed suffered from some kind of congenital disorder,
and the few studies which had at that time been continued to puberty
suggested the eventual total might run as high as eight. This would include
speech defects, alexia, colour-blindness and assorted other handicaps not
detectible by inspection of a new-born infant.

“Not all these, naturally, were hereditary. Many were the result of
intrauterine or natal trauma. The genotype of a spastic might be admirable.

“However, a barrel of dreck has been thrown down over the neat dividing line
between hereditary, due to the genes, and congenital, due to accident. None
of the experts, let alone members of the lay public, that I’ve talked to has
been able to agree on the cause of the difficult cases without an expensive
and time-consuming study of the parental germ-plasm.

“You see, traumata—which is Greek for ‘bruises’ but means outside
interference in this case—include the consequence of excessive exposure to
X-rays in the womb, infection of the mother with German measles, ingestion
of a carcinogenic or mutagenic substance which gets to the gonads,
hitripping on Yaginol while you’re pregnant—and that’s so addictive there
are some mothers-to-be you could write on with a hot iron, ‘It’ll deform
your baby!’ and they’d say get off my orbit, you’re crowding me down—and
additionally the gradual deposition in body-tissue of long-life radioactives
such as radio-strontium, radio-iodine, radio-caesium and radio-carbon … et
caetera.

“And these things have just about counteracted the advances in medical
science which have eliminated the traditional causes of spasticism. You
decide to have that kid, you’re still bucking an eight per cent risk that if
he reaches puberty he’ll suffer from a congenital disorder.

“Mark you, some of them are pretty minor. For instance, pollen-allergy is
hereditary, not congenital even, but modern antidotes make it possible for a
child with pollen-asthma to lead a fairly normal life. Sounds like nothing,
doesn’t it—these days?

“Except that before he dies that child will likely have spent seventy-five
thousand bucks on antidotes!

“Now if you’ve been turned down by the Eugenic Processing Board, what’s
happened is that they’ve assessed the risk of you having a handicapped child
not at eight but at eighty per cent. You may disagree with them on the
definition of a handicap—this recent row over dichromatism, for example.
They have solid achievements to their credit, though. Fifty years ago
Pauling said it would take twenty generations for all the recessives due to
radioactive fallout to appear; now, they have tabs on enough of them to say
they’ll be eliminated in fewer than twelve. That ought to cheer up your
ten-times-great-grandchildren, if any!

“But I tell you this, having looked at you for a good many years with the
maximum cynicism I could contrive. There’s nothing so good about you that it
deserves to be physically perpetuated in the body of your own born child.
You’re hiding behind that Eugenics Board decision to conceal the fact that
you’re really evading the responsibility of looking after a person who’s
eventually got to go and face the world alone. You don’t want to risk him
coming back and saying it was your fault he didn’t emerge a winner in the
game of life. I know some people, even, who are lying about their clean
genotype, pretending to a hereditary handicap to excuse their childless
state.

“Why can’t they be honest about it? I’m in favour of people who don’t breed,
mostly. But not because I prefer dogmatic homosexuals, or because I favour
religious fanatics like the Divine Daughters, who put on celibacy to mask
their borderline hysteria. No! Only because a person who doesn’t insist on
the expensive luxury of being a parent frees himself, or herself, to become
a parent for one of the underprivileged children we already have.

“If you’ve been forbidden to start a prodgy, you know there are potential
adoptees around who are superior to anything you could breed. Wouldn’t you
like to raise a child to be brighter than you are, more successful,
handsomer, sexier, healthier?

“No, you sheeting well wouldn’t. You’d prefer it to stay in a public
orphanage where substandard nutrition will reduce its intelligence and lack
of maternal affection will turn it into an unsuccessful neurotic.

“When a species becomes terrified of its own young, it appears to be
scheduled for the grand disposall down which went the dinosaurs. Some of us,
as I’ve just demonstrated, are afraid in case their prodgies will prove
inferior to themselves, which is halfway rational, but some are afraid
they’ll be the opposite, and that’s insane. Now you’re erecting an Asiatic
scientist you’d never heard of before a couple of weeks back into a
Messiah-figure. All right, suppose Sugaiguntung can do as they maintain and
tailor a baby to specification? What are you going to ask for?

“Cleverer than you? But you don’t want to spend your old age feeling you’re
a drag on your prodgies.

“Stupider than you? But you don’t want to waste the rest of your life
looking after a fool.

“What you want is one which is guaranteed to behave itself until it’s old
enough to run away from home, so that forever after you can complain about
the ingratitude it displayed. But I doubt whether even Sugaiguntung can
build that into an ovum with warranty of success.”

—From an article which an over-eager journal commissioned Chad Mulligan to
write when they realised he wasn’t after all dead

** A FAVOURITE STORY OF CHAD MULLIGAN’S

“This very distinguished philosophy professor came out on the platform in
front of this gang of students and took a bit of chalk and scrawled up a
proposition in symbolic logic on the board. He turned to the audience and
said, ‘Well now, ladies and gentlemen, I think you’ll agree that that’s
obvious?’

“Then he looked at it a bit more and started to scratch his head and after a
while he said, ‘Excuse me!’ And he disappeared.

“About half an hour later he came back beaming all over his face and said
triumphantly, ‘Yes, I was right—it is obvious!’”

“How can you say that? It was the kind of important thing kids my age needed
to be told! Six wasn’t too young for me to have learned that the kid I liked
most on our block, the one I thought of as my best friend, was ready at a
minute’s notice to join with other kids I didn’t like and call me a dirty
nigger bastard.”

“Have you noticed you don’t hear that used so much any longer—that
particular insult? Probably you wouldn’t have. I notice the shifts in usage
because I spend years at a time out of the country, and the process has gone
quite a long way whenever I return. Nowadays where you used to say ‘bastard’
you tend to say ‘bleeder’ instead—to mean ‘haemophiliac’, I assume.”

“Right.” Elihu resumed his original position, elbows on chair-arms,
fingertips together. “A short while ago I remarked on something that
apparently struck you as irrelevant—the fact that you don’t hear people
calling each other ‘bastard’ so much any more. It’s important. To be born
out of wedlock doesn’t signify, any more than it did in slavery days when
our forefathers and mothers didn’t marry—they simply bred. What you do hear
used as an insult is a word that probably means ‘haemophiliac’. It matches
the preoccupations of our society; it’s become detestable, anti-social, to
have children if you’re carrying a harmful gene like that one. Are you on my
orbit now?”

“Things change,” Norman said.

“Exactly. You aren’t six years old any longer. A boss can’t do to his
subordinates what a long-ago white man did to your three times
great-grandfather. But is the world a paradise because of those truisms?”

“Paradise?”

“Of course not. Aren’t there enough problems to handle in present time, that
you should brood over ancient ones?”

“Yes, but—” Norman made a helpless gesture. “You don’t know what sort of a
dead end I’ve been lured down! I’ve been working on the current version of
myself for years, for decades! What am I to do?”

“That’s for you to work out.”

“It’s easy enough to say ‘work out’ the answer! You’ve been away from this
country for years at a time, you said so yourself. You don’t know what The
Man is like, even nowadays—you don’t know how he leans on you all the time,
needles you, goads you. You just haven’t experienced my life.”

“I guess that’s a fair comment.”

“For example…” Norman gazed without seeing at the wall behind Elihu’s head.
“Heard of a woman called Guinevere Steel?”

“I gather she’s responsible for the mechanical styles women are affecting
here at the moment, as though they were built in a factory and not born of a
mother.”

“Right. She’s planning to hold a party. It’ll be a microcosm of what I mean,
all there in the one apartment and dripping slime. I should drag you along
with me, and then perhaps you’d—”

He stopped in mid-sentence, suddenly appalled at what he was saying and who
he was saying it to.

“Mr. Masters, I’m dreadfully sorry! I have no business to talk to you this
way!” Rising to his feet, covered in embarrassment. “I ought to be thanking
you very sincerely for your tolerance, and here I am insulting you and…”

“Sit down,” Elihu said.

“What?”

“I said sit down. I haven’t finished, even if you have. Do you feel you owe
me anything?”

“Of course. If I hadn’t been able to talk to somebody tonight, I think I’d
have gone insane.”

“How well you express my feelings,” Elihu said with ponderous irony. “May I
take it that right now you aren’t excessively concerned with GT’s company
secrets remaining inviolate?”

“I know too damned well that they aren’t.”

“I’m sorry?” Elihu blinked.

“A private problem … Oh, why try and hide it? The shiggy I’ve been keeping
around lately turned out this evening to be an industrial spy; my roomie
discovered an eavesdropping gadget hidden in a polyorgan she brought with
her.” Norman gave a harsh laugh. “Anything you want to know, just ask—I can
always claim she was the one who got away with the secret.”

“I’d rather you told me openly if you tell me at all.”

“Yes, I shouldn’t have said that. Go ahead.”

“What do GT’s people think is my purpose in approaching them?”

“I don’t know. No one has told me.”

“Have you figured it out for yourself?”

“Not exactly. I was talking about it with my roomie earlier this evening.
But we didn’t reach any definite conclusion.”

“Well, suppose I were to say my intention is to sell my dearest friend into
slavery to The Man, and that I believe it’s for his own good—what then?”

Norman’s mouth rounded slowly into an O. He snapped his fingers. “President
Obomi?” he said.

“You’re a very intelligent man, Mr. House. Well—your verdict?”

“But what have they got that GT might want?”

“It isn’t GT as such. It’s State.”

“Not willing to risk another Isola-type crisis?”

“You’re beginning to amaze me, and I’m not joking.”

Norman looked uncomfortable. “To be frank, it was one of the ideas my roomie
and I were tossing around. If I hadn’t heard it from yourself, though, I’d
never have credited it.”

“Why not? GT’s annual profit is almost fifty times the gross national
product of Beninia; they could buy and sell many of the underdeveloped
countries.”

“Yes, but even granting their ability to do it, which I can’t contest, the
question remains: what is there in Beninia that GT might want?”

“A twenty-year rehabilitation project that will create an advanced
industrial bridgehead in West Africa, serviced by the best port on the Bight
of Benin, able to compete on their own terms and on their own ground with
the Dahomalians and the RUNGs. State has a computer analysis which suggests
that the intervention of a third force is the only factor likely to prevent
a war over Beninia when my good friend Zad dies—and that day can’t be as far
off as I’d like it to be. He’s working himself into his grave.”

“And this will belong to GT?”

“It’ll be—mortgaged to GT, let me put it that way.”

“Then don’t do it.”

“But if the alternative is war—?”

“From the inside, from the status of a junior VP in the corporation, I say
that war itself isn’t as foul as what GT can do to a man’s self-respect.
Listen!” Norman leaned forward earnestly. “Do you know what they’ve duped me
into doing? I subscribe to these Genealogical Research outfits, these
near-crank businesses which claim to trace your descent on the basis of your
genotype. And do you know I haven’t commissioned one to track my Afram
heritage? I don’t know where my black ancestors came from to within two
thousand miles!”

“And supposing it’s a cousin of yours—and mine—who gives the order and the
armies march into Beninia! What’s going to be left of the country? The loser
is going to scorch the earth behind him when he retreats, and there will be
nothing left except rubble and corpses!”

Norman’s intensity faded. He shrugged and nodded. “I guess you’re right.
We’re all human beings, after all.”

“Let me tell you the scheme. GT will float a loan to finance the operation,
and State will buy a fifty-one percent interest through front agents—mainly
African banks. GT will guarantee five per cent per annum for the twenty-year
period of the project, and publish estimates of a yield in excess of eight
per cent. That’s solidly based, by the way, on State’s computations; when
they give the data to Shalmaneser they expect it to be confirmed. Then
they’ll recruit the teaching staff, mainly among people who were colonial
administrators and so on in the old days, people who are used to West
African conditions. The first three years will go on diet, sanitation and
building. The next decade will go on training—a literacy drive first, then a
technical education programme designed to make eighty per cent of the
population of Beninia into skilled workers. I see you’re looking
incredulous, but I say I believe this will work. There’s no other country in
the world where you could bring it off, but in Beninia you can. And the last
seven years will go to build the factories, install the machine-tools,
string the powerlines, level the roads—everything else, in short, to leave
Beninia as the most advanced country on the continent, South Africa not
excepted.”

“Allah be merciful,” Norman said softly. “But where do you get the power to
feed into the lines?”

“It’s going to be tidal, solar, and deep-sea thermal. Mainly the latter. The
temperature gradient between the surface and the sea-bed at those latitudes
could apparently run a whole country much larger than Beninia.”

Norman hesitated. “In that case,” he ventured at length, “the raw materials
will presumably be coming from MAMP?”

A new cordiality entered Elihu’s manner. “As I said before, Mr. House, you
suddenly astonish me. When we met earlier today your—ah—superficial image
was so flawless as to conceal from me this sort of perceptivity. Yes, that’s
going to be the carrot with which we coax the GT donkey into agreement: the
promise of a built-in market that will enable them to put the MAMP mineral
deposits to work.”

“On the basis of what you’ve told me,” Norman said, “I presume they jumped
at the idea.”

“You’re the first person at GT to hear the full details.”

“The—? But why?” Norman’s question was almost a cry.

“I don’t know.” Elihu seemed suddenly weary. “I guess because I’d kept it to
myself too long, and you were here when it broke loose. Shall I call Miss
Buckfast and tell her I want you sent to Port Mey to conduct the initial
negotiations?”

“I—wait a moment! What makes you so sure she’ll consent when you haven’t
even explained the project to her?”

“I’ve met her,” Elihu said. “And I only need to meet someone once to know if
this is the sort of person who’d like to own nine hundred thousand slaves.”

** ISOLATION

“At bottom the human species finds idealism an uncomfortable posture. Prime
evidence of this can be found in the way neither of the two groups locked in
irresoluble conflict around the Pacific has been able to achieve its stated
goal—even though, given the lucid, simple, obviously attractive statement of
either of their ideals, an impartial observer might wonder why commitment
had not ensued like sunrise after night.

“‘Give the wealth back to the people who created it!’ Here’s an ideal
capable of generating crusades among people who interpret it as
expropriating greedy landlords, sharing out land so that every family may
enjoy reasonable nutrition and repudiating debts to moneylenders at usurious
rates of interest. Having hit on this, the Chinese charged ahead—until they
overreached themselves. They became unable to distinguish between the evils
they were preaching against and those traditional influences which literally
constituted the way of life of people they hoped to recruit to their cause.
In short order they fell into the same pit as their rivals, who had for
decades ignored the plain and simple fact that to a starving man ‘freedom’
implies a full rice-bowl—or, if he has an exceptional imagination, a healthy
ox to pull his plough. It has nothing to do with voting for a political
delegate.

“Analogously with the way the Tsarist army deserted en masse during the
First World War, not because of Bolshevik impact on the soldiers but because
they were sick of fighting and wanted to go tend their farms, the eager
early recruits to the red flag discovered that while they were dying abroad
the things they wanted to guard were being undermined at home. So they quit.
China, like Russia before her, found she was surrounded by a gaggle of heirs
to the mantle of the late Marshal Tito, not a few of whom were themselves
within China’s boundary.

“However, by that time, thanks to ineptitude, racial prejudice against them,
fighting the right wars with the wrong weapons, and general mismanagement of
their affairs, the opposition (or if you prefer, which I don’t because I’d
rather not identify with such a bunch of incompetents, ‘our side’) was so
far in arrears that the greatest single territorial gain to date in a
contest which bids fair to outdo the Hundred Years’ War both for duration
and for inconclusiveness only restored a rough balance and didn’t tip the
scales the other way.

“We can’t even claim in honesty that it was the result of foresight and
planning—only that when the grabbing was good, we grabbed. Don’t believe
anyone who tries to claim that the existence of Isola is proof of the
superiority of the Western system. The Chinese couldn’t have taken over.
There was no form of discontent they could have exploited. How do you whip
up resentment against absentee landlords and pocketers of bribes when the
highest ambition of the people concerned is either to become the former or
be in a position to receive the latter?

“Life in the Philippines had become intolerable well before the civil war of
the 1980s. The state of things obtaining (which some accounts misname
anarchy, but which any decent dictionary will tell you was nothing of the
sort, but free-enterprise capitalism gone out of its skull) was on the verge
of ruining the country permanently. The annual average of unsolved murders
was running around 30,000 in a population of under fifty million. In the
eyes of the inhabitants of the Sulu Archipelago, where most of them were
committed, the offence for which they revolted against and ultimately
assassinated President Sayha was that he interfered in their traditional
right to slaughter and steal. This was unforgivable.

“Oh, doubtless there were some among the people who gave that celebrated
majority of eighty-eight per cent in the plebiscite on secession who hoped
that being policed and governed by Big Brother in Washington would ensure
them a quieter life, free them from the need to fit bullet-proof shutters
and plant man-traps in their gardens. Far more, however, seem to have hoped
that the bait on the hook (full States’ rights and a billion dollars of aid)
would offer another and fatter cake of which they could snatch their slice.

“Which of these parties saw its dream fulfilled? Dear reader, you must be
joking. That vaunted billion-dollar aid budget went nowhere near the
natives’ pockets. It was spent on roads, airfields, port facilities and
fortifications. And, while it’s true that the smugglers and black-marketeers
who had hitherto rampaged unchecked had their hinder ends smartly kicked, to
get rid of them the new owners imposed martial law and it hasn’t been lifted
since 1991!

“Dubbed ‘Isola’ on the grounds that Montana was a mountainous territory and
the new acquisition was an island territory, the Junior State went from the
frying-pan into the fire. However, the Americans had been desperately in
need of bases closer to the Asian mainland than what they currently had, and
they were reasonably well satisfied.

“The Chinese, on the other hand, when they tried a counterstroke by wooing
Yatakang, were disappointed. The Yatakangi are descendants of the former
dominant people in South-East Asia and firm believers in the traditional
military dictum that the first thing you do after contracting an alliance is
prepare plans for the day when your ally welshes on you. Just because
they’re Asiatics it doesn’t follow that they’re going to invite their yellow
fellows into their beds. Nor, because they haven’t performed the Peking
kotow, should it be assumed (as some blockbottoms I know in Washington have
assumed) that they are all set to become the second Isola. Why should they?
Things are peachy down in Yatakang; it’s among the world’s great nations, by
Asian standards it’s fabulously wealthy, and it can enjoy the game of
playing off Washington against Peking until doomsday, on present evidence.

“Until doomsday? Well, perhaps that’s a slight exaggeration. There’s one
bright spot in the generally gloomy picture known as the Pacific Conflict
Zone. According to my calculations, by the year 2500 or so we should have
killed off every last member of our species who is stupid enough to take
part in so futile a pastime as this war between ‘ideals’, and with luck they
won’t have left their genes behind because they’ll typically have been
killed at an age when society thinks they’re too young to assume the
responsibility of childbearing. And after that we may get some peace and
quiet for a change.”

—Better ? than ? by Chad C. Mulligan

“People who feel the need to foul up their perceptions with hop or Yaginol
or Skulbustium simply aren’t turned on to the essential truth that the real
world can always be identified by its unique characteristic: it, and it
only, can take us completely by surprise.

“Take two lumps of greyish metal and bring them together. Result: one
wrecked city.

“Could anyone have predicted or envisaged that until they knew enough about
the real world to calculate the properties of a substance called
Uranium-235?

“People are going around marvelling at the fact that there’s a solid
scientific basis for palmistry. Anybody with a grain of intelligence could
have said, directly the notion of the genetic code was formulated, that
there was no a priori reason why the pattern of the folds in the palm should
not be related to a person’s temperament by way of an association of genes
sharing the same chromosome. Indeed, there were all kinds of reasons for
assuming this actually was so, because we aren’t totally stupid—as I’ve
pointed out before—and unless there was in palmistry some element of
relevance to real experience we’d have given it up and gone chasing some
other will-o’-the-wisp. There’s no shortage of them.

“But it took forty years for someone to conduct a properly rigorous study of
the subject and demonstrate that the suspicion was well-founded. This I do
find remarkable—or disheartening might be a better word.

“All right: what should you be surprised at, these days?

“The fact that, having learned so much about ourselves—the designs on our
palms being just one example of the way we’ve analysed ourselves down to the
constituent molecules, so that we can claim to be in sight of the day when
we won’t merely be able to ensure the sex of our offspring (if we can afford
the fee) but also to choose whether we’ll have a math genius in the family,
or a musician, or a moron (some people might like to breed a moron for a
pet, I guess…)—having got to this state, then, we know less about our
reactions in the mass than we do about the behaviour of non-human things
like a lump of U-235.

“Or maybe it’s not so amazing. Without being totally stupid, we do display a
tremendous aptitude for it.”

—You: Beast by Chad C. Mulligan

(HISTORY Papa Hegel he say that all we learn from history is that we learn
nothing from history. I know people who can’t even learn from what happened
this morning. Hegel must have been taking the long view.

—The Hipcrime Vocab by Chad C. Mulligan)

She found the intruder confronting Danny-boy, her chief usher—him of the
Parisian artist’s smock—and growling belligerently. Fortunately, to call it
“shouting” was an exaggertion, so the customers in even the nearest posts
were unlikely to have noticed anything wrong. Moreover the blonde member of
the come-hither team had shown enough presence of mind to move the
changeochrome partition so it screened the disgusting stranger from outside.

He was a hulking man, well over six feet, and probably strong in spite of
his revolting condition. His hair hung in lank strands all over his collar
and merged into a beard and moustache that might as well never have been
trimmed, but served as a soup-filter and catch-all for scraps of food. There
was a singed indentation in the right lower edge of the moustache as though
from smoking hand-rolled joints to the last fraction of a roach. His
sweaterette had once been red but was now patched, smeared and streaked with
other colours, and if his slax had ever fitted him that must have been years
ago; now the waistband had given up struggling against the encroachment of
his belly. His feet were planted four-square on her lovely hand-inlaid floor
in things that might have been loafers but now were incrustations of garbage
totally concealing any fabric that might separate dirt from skin.

He broke off his tirade at Guinevere’s approach. “Ah!” he exclaimed. “You
must be Steely Gwin from Port of Sin—I’ve heard such a lot about you! I even
wrote a poem about you once. Just a second … Ah yes—‘Girls made up by
Guinevere Steel Look a treat but are lousy to feel. She turns meat that was
cute Into plasticised fruit With the juices locked under the peel.’ One of
those shiggies called you Danny-boy, didn’t she?” he added to the quaking
usher. “That should make you feel right at home, then. Limericks are Irish
too.” He hee-hawed with laughter and rocked on his heels.

“Want to hear another? ‘If you fancy a shiggy and seize her, And find she’s
as cold as Teresa, She isn’t a freak, It’s because the Beautique—’”

Guinevere said with all the dignity she could command, “What do you want in
here?”

“Whatinole do you think I want? One of your window-display dummies?” He
gestured with black-tipped fingers at the cowering come-hither girls.
“Thanks, if I need an inflatable masturbator I’ll build my own. Ah,
whatinole do you think somebody wants who comes into a place like this?”

“You must be drunk or orbiting,” Guinevere snapped. “I don’t believe you
know where you are.” She cast a nervous glance at the wall-clock. The
current hour’s appointments were nearly up, and if the clients were to
emerge and see this revolting specimen blocking their exit … “Danny-boy,
you’ll have to call the police. I don’t see anything else for it.”

“What for?” the stranger demanded in an aggrieved tone. “What do I do? All I
want is to be beautified.”

“To be what?” Guinevere said. Her breath ran out on the third word. “You
must be insane! We don’t accept male clients anyway, let alone—let alone
objects like you!”

“No?” The intruder took a threatening pace closer to her. “New York State
Code provisions on discrimination, any commercial establishment offering a
service to the general public and declining to accept a prospective client
on racial, linguistic, religious or sexual grounds shall forthwith have its
licence revoked!”

Belatedly Guinevere realised that the man neither spoke nor acted as she
felt would match his appearance.

“In any case I know perfectly well you don’t discriminate. Apart from
Danny-boy—and you’re not going to tell me he doesn’t get you to help him
with that impeccable surface sheen!—my old beddy Doll Clark has been coming
here for years and he still has his balls. What do you want I should do?
Come back in a kilt wagging my hips?”

Guinevere said, with a faint sensation of unreality as though someone had
slipped her a cap of Yaginol, “I can ask for proof of ability to pay, at
least. And if you could meet my rates you wouldn’t be walking around
stinking like”—she borrowed Danny-boy’s simile because it was definitive—“a
whole barrel of whaledreck!”

“Oh, if credit is all that’s eating on you—!” The stranger made a face.
“Here!”

He reached inside his sweaterette and produced a thick wad of documents.
Flipping through them like a dealer riffling a new deck of cards, he
extracted one and held it out.

“That do?”

“Hold it so I can read it,” Guinevere snapped. “I don’t want to touch it, or
you.”

She looked. It was a bank credit authorisation good for a thousand dollars
at sight of bearer. But that wasn’t what shook her to the core. It was the
name neatly printed across the bottom, under the picture of a much younger
man with his moustache and beard trimmed into Louis-Napoleon elegance.

“But he’s dead!” she said faintly. “Danny-boy! Surely Chad C. Mulligan is
dead!”

“Who?” Danny-boy looked blank for a moment. Then: “Did you say Chad
Mulligan?”

“Dead?” said the filthy stranger. “Christ, no. And if you make me stand
around much longer I’ll prove it conclusively. Come on, come on!”

The clock crept towards the final five minutes of the current session. Any
second now the first of the clients being attended to would leave the
shelter of the curtains. Guinevere swallowed hard. Which of her assistants
could be persuaded to handle this job for a hundred-dollar bonus?

“Danny-boy,” she whispered, “take Mr. Mulligan in charge and do whatever he
wants.”

“But, Gwinnie—!”

“Do as I tell you!” She stamped her foot.

After all, he is a considerable celebrity …

Forcing herself to overcome her nausea, she said, “Forgive me, won’t you,
Mr. Mulligan? But—well, this is rather an incongruous guise to find you in!”

“Incongruous my insalubrious hole,” Chad Mulligan grunted. “It’s the same
way I’ve been looking for the past two years or more. What I’m going to find
incongruous is what I’ll be like after your mechanics have overhauled me.
But I’m giving up. I’m quitting. The sheer God-blasted inertia of this
asinine species has defeated me. I can’t make people pay me attention
whether I argue, or bellow, or daub myself with shit. I propose to pretty
myself up and join the rest of you Gadarene swine in debauching myself
magnificently to death. All right, where do you want to put me so your other
customers won’t see the state I’m in?”

And he added over his shoulder as Danny-boy led him away: “Send someone out
for a quart of liquor, will you? I need something to nerve me for this.”

** BE KIND TO YOUR FORFEITED FRIENDS

LOCALE: since it was illegal by city ordinance to occupy that much space by
herself what Guinevere had done was to make a settlement on her husband whom
she was divorcing largely because his name was Dwiggins and get him to buy
with it the vacant apartment below her penthouse and then lease it to her
for an indefinite period at a peppercorn rent which was not illegal and the
chief method by which the ostentatiously wealthy in the modern super-crowded
city secured for themselves that ultimate in contemporary status symbols a
home many times larger than one person could reasonably require—to wit two
rooms one above the other forty-eight feet by thirty-two, two (ditto) thirty
by eighteen, two (ditto) twenty-one by eighteen, four bathrooms en suite and
two not, four additional toilets, two kitchen-eateries, and a roof-garden
which Guinevere had had as it were hollowed out by an ingenious architect so
that it became a bower with its main level corresponding to the lower
apartment and the upper containing the automatic watering and fertilising
sprays together with the artificial sunlight lamps required to keep the
plants and flowers healthy.

CONTENTS (PERMANENT): the largest unit-based suite of polyform furniture
ever manufactured for a private customer including large tables convertible
into desks or screens and small tables convertible into book-racks or
trolleys and chairs upright convertible into chairs relaxing and chairs
relaxing convertible into lounges and lounges convertible into sofas and
sofas convertible into beds and beds convertible for single or double or
multiple occupation and so on—in theory capable of adapting the apartment
for everything from a well-attended political meeting with everyone sitting
around paying serious attention to the subject in hand to a party like the
present one with everyone paying serious attention to the subject hoped to
be in hand eventually.

CONTENTS (TRANSIENT IMMOBILE NON-PERISHABLE): the latest decorations and
pictures and ornaments and models of phone and TV and polyformer and
holographic record reproducer and cosmoramic projector and even books—though
the latter were hanging in the balance as potentially non-fashionable.

CONTENTS (TRANSIENT IMMOBILE PERISHABLE): an assortment of seven dozen
different kinds of foodstuffs guaranteed by the catering company to be
accurately twentieth-century in substance and appearance but not necessarily
in flavour—certain essential compounds in such items as free-ranged chicken
and slow-smoked bacon being no longer reproducible under modern
manufacturing conditions—plus bottles and cases and barrels and boxes and
jars and cans and packs of liquor and incense and wine and marijuana and
beer and even tobacco to give the guests a decadent life-in-my-hands thrill
that would also be properly in period.

CONTENTS (TRANSIENT MOBILE BUT IN A SENSE EQUALLY PERISHABLE): a hundred
fifty people including the hostess and her guests and many human staff from
the catering company which had a good reputation among the new poor of the
happening world for concealing payments to waiters and cleaners by inflating
their charges for purchase of goodies and thus enabling them to escape the
moonlighting tax supposed to wipe out the profit a fully-supported recipient
of welfare might derive from odd jobs like these.

EXCUSE AND REASON: making the guests pay forfeits which if she chose she
could make so hideously embarrassing the victims would never want to see her
again.

COST: about three thousand dollars.

VALUE RECEIVED: that would have to wait until the end of the party to be
assessed.

***

Click and cram the elevators cycling, splash and crash the guzzling well
begun.

AUDIO: the most bearable re-made recordings from the latter part of last
century, not the most recent (stuff from the nineties was intolerably
vieux-jeu). No, it had to be from the seventies, endowed now with a certain
quaint charm, and on top of that it had to be the kind of music which led
most directly to what was currently acceptable in the real world
outside—chants sans paroles in the rather bland monotonous rhythms of five
against four and seven against eight. The quality of the recordings was
lousy and the divisible-by-two rhythms seemed banal and boring after
subtleties like five against eleven. But each of the records allegedly had
sold a million.

If someone comes in wearing Arpège Twenty-first Scentury or anything else
like that what shall I make her—or him—do?

COSMORAMIC: mostly the fashionable colours of the nineties because they were
currently bearable—apple-green, sour lemon-yellow, and the inevitable pale
blues—but changeochrome was newer than the century and there wasn’t a moiré
setting on the projector which would have been marginally allowable, so it
was all stark flat colours and rather drab.

Come to think of it, that stuff of Mel Ladbroke’s is new, so what if someone
drecky claims forfeit off him for bringing it? The hole; it’s my party and I
say what’s allowed.

GUSTATORY: likely to be the biggest success of the party, no whistlers or
moonjuice or any other this-very-instant drinks, but that weird cocktail
chart dug up from about 1928 and programmed specially into the
consoles—things called “Old-Fashioned” and “Bosom-Caresser” ought to appeal
if only for their amusing silly names. Also the food exotic. Out of period,
but absolutely unavoidable, generous supplies of antalc, disgorgeant and
counter-agents to the most popular lifters, Yaginol, Skulbustium and
Triptine. Not permitted at the party, all too new, all post-turn-of-century,
but people would certainly turn up orbiting on one or two or maybe all of
them.

Snff…? That’s Dior Catafalque, I swear it is! Whereinole did she dredge it
up? It’s been off the market for twenty years! Make a point of asking her
what it is; recognising it would date me …

SARTORIAL: the most incredible, the most phenomenal mish-mash assembled
under one roof this generation except maybe in the General Assembly of the
UN.

That girl’s wearing Nipicaps. I can tell—who better? Bit early to start
imposing forfeits but that will be a lovely lovely start. Something
mild—after all, they’re one of my own products—but something forceful enough
to make people realize I mean business. One moment: girl? That’s no shiggy!
Well, that forfeit defines itself, doesn’t it? Yum!

1969: the hostess in an outfit of PVC which was about as near as they were
coming in those days to the stark sleek mechanical styles of the current
trend, regrettably needing to be underpinned with the badly engineered and
somewhat uncomfortable brassière and girdle appropriate to it—a discovery
she had made too late, not having obtained and tried on the costume until it
was too close to the start of the party to change her mind. But at least the
slick surface was a kind of foreshadowing of 2010; she hated the idea of fur
or velvet or one of those other crudely textured fabrics women used to stuff
themselves into.

“My dear, haven’t seen you in lightyears! That’s a most marvellous rig
you’re sailing under—did it belong to your grandmother?”

19??: Norman House in a full set of jet-black evening dress with a genuine
stiff shirt and white bow-tie and even shoes of that revolting stuff called
“patent leather”—a hundred per cent genuine to judge from the cracks in
them. Guinevere gave him a venomous smile for not allowing her an instant
opening for attack and wished that he didn’t look so inarguably magnificent
in the sombre garb.

“You mean this is really tobacco? Cigarettes of that stuff that was supposed
to cause so much cancer? My dear, I must try some—my parents didn’t smoke it
ever and I hardly believe I saw the stuff before!”

1924: Sasha Peterson in a softly draped tea-gown of semi-translucent chiffon
hanging almost to her ankles but slashed behind to the waist, invoking an
old-fashioned air called “elegance”. Guinevere thought of what the
mode-masters were saying about a swing back to a more natural look in
shiggies and wished she had never dreamed up this sheeting party.

“Well, if I can’t have a whistler whatinole can I have? Oh, give me some
bourbon on the rocks, then—I take it that’s allowed? I mean, if they had
cold drinks at the court of Emperor Nero they had them in the last century?”

1975: a very young shiggy with a beautiful bosom wearing a niltop over a
minisarong. Can’t legislate for that—any girl who’s recently discovered that
her body attracts men will go the available limit to display it to them.

“Are we not even supposed to talk about the real scene? I mean, I don’t know
whatinole people did talk about at parties in the last century—I wasn’t old
enough to go to them.

1999 and only scraping under the limit by a chronological accident: Donald
Hogan in a curiously antique-seeming brown and green totalsuit with a spiral
zipper going from right ankle twice around to the left shoulder, face
flushed and apparently worried about something but ascribing it for official
purposes to the fact that if Norman hadn’t remembered to book him whatever
was available from the rental agency he’d have had to turn up in the only
universally acceptable costume—his skin.

“I shouldn’t hope for too much, darling. All tobacco ever did to me was make
me throw up. I don’t know whatinole people used it for. No, darling, you
can’t take it in like the smoke from a joint, you have to sort of puff it in
straight and then accustom yourself to inhaling it without dilution.”

1982 or thereabouts: a positive travesty in the literal sense, in one of
these ghastly outfits with five or six layers of mesh in contrasting colours
hanging from the hips and shoulders, and shoes of enormous size sticking out
below.

“One of the reasons I come to Gwinnie’s parties is she doesn’t feel
obligated to ask all these sheeting brown-noses you keep treading on
everywhere else, but there are too many of them here for my liking tonight!”

Right. Find out who they are and why.

“Of course the whole thing is sheeting crazy. That was the wildest
roller-coaster of a century the human race has ever lived through, if you
can call it living—hey, notice that good in-period catchphrase I used?”

Any time: Elihu Masters in a regal suit of Beninian robes, a loose
red-and-white top over baggy pants and open sandals his round balding head
framed in a kind of crown of upright feathers varnished into brown rigidity
around a velvet skullcap.

“Yes, but what kind of a twentieth-century party? One of those stiff soirées
you read about in old magazines dating back to 1901, or something right up
close to our own day like a Sexual Freedom League meeting? I don’t know
whatinole I’m supposed to be doing and Gwinnie has that forfeit light in her
eye. Maybe it’s safest to tag along after her and be in the support group
when she picks on someone.”

1960: Chad Mulligan perspiring in a hound’s-tooth check tweed suit which was
all the costume rental agency had left in his size when he shrugged and let
Guinevere persuade him to attend.

“Yes, of course I’m nervous. I hate to miss these parties of Gwinnie’s
because normally I make out fine and she’s never picked on me yet, but this
time I’m violating the conditions so flagrantly—I mean, this isn’t a
last-century costume, it’s all I could dig out from my father’s wardrobe and
it says right on the label ‘Summer collection 2000’ but there wasn’t
anything older.”

1899: an incredible multi-caped garment vainly hauled in around a large
waist and a skirt dangling to the ground and a silly bonnet on top of it all
and the excuse prepared that there was no reason in those days why a dress
shouldn’t have been worn for two years or even longer.

“When Gwinnie gets really nasty I’m going to blast off. I know another party
which ought to be humming by then.”

Any time: Gennice, Donald’s one-time shiggy, in a minor stroke of genius, an
undatable Japanese happi-coat and traditional slippers to match.

“Must have been funny living in those days. I know someone who rebuilds and
runs cars for a hobby, for instance, but for all he can do to the—what’s it
called? Exhaust?—they stink worse than a barrel of whaledreck. Makes my eyes
water just to go near one when he’s got it running!”

1978: Horace, a friend of Norman’s, in a ventilated parka with contrasting
hood over jodhpurs, a perfect memorial to the way men’s fashions were going
over the edge into pure schizophrenia in that hysterical epoch.

SITUATION: a lot of people drifting about and looking each other over
covertly or sometimes overtly, knotting gradually into groups of former
acquaintances separated by strands of people who never met before and who
haven’t yet softened their self-consciousness to the point of blending in.
In short, as was probably the case in Pharaonic Egypt where they first
established the tradition of giving parties, a party that hasn’t jelled.

“That’s a very curious perfume you’re wearing, darling.”

Nervous laugh. “Of course, you’re an expert on that, aren’t you? Do you like
it? It’s a bit musty, isn’t it? It’s something called Dior Catafalque that
my mother gave me when she heard I was coming to your party.”

“Catafalque? Really? Isn’t that the thing they lay out corpses on when
they’re lying in state?”

“Yes—I think that’s the idea. It’s supposed to be sort of musty and
decaying.” Shudder. “Actually it’s pretty horrible, but it is in period,
isn’t it?”

“Goodness, I wouldn’t know for certain. I’ll take your word for it, though.”

SITUATION: same.

“Don! Don!”

“Oh—hullo, Gennice. Nice to see you again.”

“Don, this is Walter that I’m living with now—Don Hogan that I was with
before, Walter. Don, you don’t look as if you’re enjoying yourself at all.”

It shows that much? But they said keep on with your ordinary life until you
leave, so … Wish I had the guts to back down. I’m frightened!

“I need a lift, I think. Don’t suppose Guinevere would approve, though.”

“There’s plenty of pot. And someone did say that that codder there—I think
the name’s Ladbroke—was from Bellevue. He may have something.”

SITUATION: same.

“You’re Chad Mulligan? Prophet’s beard, I thought you were dead!”

“Might as well be. Intend to be. Just think I might as well take a lazy
man’s way out. Get me another drink.”

“Elihu, here’s a man you ought to meet! I saw one of his books in your room
when I called the other night!”

SITUATION: same.

“I say, someone told me you were from Bellevue and … Oh. Excuse me. I just
saw somebody I know.”

“Yes, that’s right. My name’s Schritt—Mister—Helmut Schritt.” A quick glance
around and an insincere smile. “Routine precaution. There’s a vanishing
chance that someone might try to foul up your—uh—business along the lines I
recall being mentioned last time we met. Act as normally as you can and
avoid any entanglements that would prevent you leaving a bit earlier than
the mass, okay?”

“Act normally!”

“That’s what I said. Like keep your voice down when you talk about
the—uh—subject of importance, hm?” Another of the insincere smiles.

SITUATION: same.

“Darling, that’s a wild rig you’re sailing under!”

“Gwinnie, I’m so glad you like it!”

“But aren’t those Nipicaps a trifle out of period…?”

Sudden tension. A personal silence for all the screaming of the records in
the background. A shifting of several of Guinevere’s closest sparewheels to
encircle the victim and savour the inaugural forfeit of the evening.

“I—uh—I…”

“Well, I mean, I should know, darling, since I have them made specially for
the Beautique and sell them by the literally thousands! And they only made
their splash two years ago.”

“Forfeit!” someone said decisively, and there were grins.

“Ye-es, I think so. And it sort of writes itself, doesn’t it? Take it off,
darling, from there”—shoulder—“to there”—waist.

Sickly embarrassed but complying: result, the strange hermaphrodite. Scalp
to neck, elaborate coiffure, immaculately painted face with eyebrows arched
and lashes lengthened and lips clear red and earrings jangling; waist to
floor, skirt and hose and jewelled 1988-style boots; between them, that
incongruous bare male chest with good solid muscle and hair in concentric
curves swirling out from the nipples.

“I think that’ll do nicely,” Guinevere said with satisfaction, and those
around chortled and clapped her and each other on the back and those as yet
out of range of her decisions relaxed and began to chatter loudly again.

SITUATION: same but with an admixture of high nervous laughter.

“Darling, of course I’m only really well grounded in feminine fashions, but
I do seem to detect something a teeny bit incongruous in that outfit you’re
wearing…?”

“Well”—swallow hard—“ah … as a matter of fact—”

“Darling, don’t prevaricate. You know how much I detest prevarication.”

“Forfeit! Forfeit!”

“Well, Gwinnie dear, it’s as old as I could lay hands on, honestly it is.”

“No doubt, darling, but you’ve been to lots of my parties and I’m sure
you’ve had as much fun out of seeing other people pay forfeits as they’re
going to get out of you. Now let’s see. What would be appropriate? Bearing
in mind that it’s early yet, so because of that and because we like you a
whole great slobbering lot we’ll want to keep it a mild one, won’t we?”

SITUATION: less laughter, more tension.

“Sadistic bitch, isn’t she?”

“You should see her when she gets on to an Afram, Mr. Mulligan.”

“If you call me ‘Mr. Mulligan’ one more time I’ll throw this liquor all over
your smart period-piece.” Gulp. “Cancel that—I’ll break the glass on your
ought-to-be-nappy skull. Anyway, she’s wrong.”

“What?”

“She’s wrong. But that’s irrelevant, I guess. If that’s the way her guests
like her to run her parties I’ll just sit quietly here and give thanks to
any deity who may exist that I ran into intelligent company. Elihu, I’d like
to know something more about this place Beninia. There are some highly
anomalous factors in what you’ve been telling me—”

“Excuse me, Chad, please. How did you mean, ‘she’s wrong’?”

“Norman, you do have eyes, hm? And you’re blessed with a reliable memory,
hm? The hole, then! What were you wearing in the summer of 2000? Something
like that, I’ll wager.”

“The summer of—? Prophet’s beard, of course! I’m an idiot.”

“You belong to an idiotic species. I even wrote a book to draw attention to
the fact. I was idiotic myself to think it would do any good.”

He turned back to Elihu and waved his empty glass without looking away to
his right, hoping that a passing waiter would take it in exchange for a full
one.

Norman shouldered his way through the people crowding close around Guinevere
and her intended victim. He heard suggestions: “Take it off and put it back
to front! Take off everything that’s newer than the century! Make it look a
bit older—like by tearing a few holes in it at the right places!”

“Just a second, Gwinnie,” he said boredly, triumphantly.

“What do you want to do, Norman—arbitrate?”

“As a matter of fact, yes. That looks like a year 2000 garment to me. How
about it, friend?”

“Why, it says right here on the label that it is, but—”

“Twentieth century, then.”

“What? Norman, you’re spouting dreck. Go away. Now I think what we ought to
do is—”

“The twenty-first century didn’t begin until a minute past midnight January
first 2001.”

Awkward pause. Someone: “Sheeting hole, I think he’s right.”

“Dreck. I recall distinctly on New Year’s 2000 we all—”

“And the commentators did say that wasn’t right, it comes back to me now.”

“The hole, let’s make him do it anyway.”

“No, got to fly by the course we set in the first place.”

Silence in the immediate vicinity.

“Gwinnie, I’m dreadfully afraid he’s right. He is, you know.”

Nods.

“Well, how funny! Lucky for him you came along, isn’t it, Norman? Never
mind, sparewheels, there’s bound to be someone else. Break it up and let it
fall free, hm?”

And, as she contrived to brush against Norman on her way to match orbits
with a circulating waiter: “Fix you later, you clever brown-nose!”

“You’re welcome to try, darling,” Norman said. “You’re welcome to try.”

SITUATION: suddenly and to Guinevere’s enormous chagrin, a real party flying
high and free in a genuine party-type orbit.

“Chad Mulligan? Never in a million lightyears!”

“I so testify.”

“Not the fat Afram?”

“No, the one with the beard.”

“The lean Afram?”

“Sheeting hole! No! The WASP talking to both of them.”

“Christ, everybody’s been saying he was dead!”

“Mel, I think some time later on we might break out a few caps of that stuff
I asked you to bring. There’s a too-clever bleeder here I’d like to fetch
down from orbit.”

“Hi, Don. Elihu, this is my roomie Donald Hogan—Chad Mulligan, Don.”

“Hi. Now, as I was saying, what McLuhan didn’t foresee although he came
sheeting close to it was—”

“I’m delighted to meet you, Mr. Masters, but this is about the last place
I’d have expected to run into you.”

“When Norman called on me the other night he mentioned this party and said I
should come if I wanted to see the kind of problems Aframs still have to
cope with in this country, so I thought it over and decided he was probably
right, I ought to.”

“You won’t get the full measure of Guinevere’s ingenuity just standing by
and watching, sir. You need to be someone like Norman, who’s about on her
own level, not someone with cachet like yours.”

“Why?”

“If you’d turned up wearing your ordinary street-clothes she’d only have
made you pay some kind of nominal forfeit—standing on your head for ten
seconds, or singing a song, or taking off your shoes. Something that
wouldn’t have interfered with your enjoyment of the rest of the party, I
mean.”

“That’s what one generally expects at a forfeits party, isn’t it?”

“There’s been a change since you went abroad, sir.” Why all this “sirring”?
Must be a subconscious response to the fact that as of this morning I’m
officially Lieutenant Hogan! “A few years ago that was true. Not any more.”

“I see. I think. Give me examples.”

“Oh … Well, I’ve seen her compel guests to daub themselves all over with
ketchup—and shave their heads bald—and crawl around the floor on hands and
knees for an hour, until she got tired of enforcing that—and, if you’ll
forgive me going into such details, to piss themselves. That comes later and
is used to get rid of people she doesn’t want to stay around when the orgy
starts.”

“That goes without saying, does it?”

“Oh yes.”

“Is that why people stand for such treatment?”

Chad Mulligan broke in; for the past few moments, unnoticed, he had
abandoned the conversation he was having with Norman and had been listening
to Donald and Elihu.”

“Sheeting hole, no! At least I’ll wager it’s not why Norman keeps coming,
unless you’ve got a well-concealed masochistic streak—hey, Norman?”

“Some people come out of masochism, definitely,” Norman shrugged. “They like
to be publicly humiliated. You can generally spot them; they’re blatantly
infringing whatever the rule of the evening is, but steering clear of
Guinevere’s direct attention until fairly late when they’ve drunk enough or
smoked or ingested whatever they need to give them sufficient offyourass for
the show-down. Then they go in for cringing and begging to be let off and
being jeered at for spoilsports—the whole shtick—and generally they come
while they’re getting the treatment. Which of course makes everything
free-falling for them and that’s why they accepted the invitation anyway.
Harmless, mostly.”

“I was asking about you, not them,” Chad said impatiently.

“Me? I keep coming here because—okay, I’ll open up wide. It’s a constant
challenge. She’s a mean bitch, but she’s never yet caved me in on one single
forfeit, and there have been times when there were thirty or forty of her
pet sparewheels yelling for me to pay one. That’s why I keep on accepting.
And frankly it seems to me like a damned stupid reason. This one is going to
be my last, and if you weren’t here, Chad, and if I hadn’t conned Elihu into
coming, I’d have left already.”

Donald looked at Chad Mulligan. He still only half-believed that this was
the genuine article, but the resemblance to the pictures on the jackets of
Mulligan’s books was unmistakable—the keen eyes peering out from under heavy
brows, the hair combed diagonally back, the neatly trimmed moustache and
beard setting off the cynical line of the mouth. There was a more dissipated
look to the face in reality than there had been in the publicity shots, but
maybe that was due to age rather than actual surrender.

He hoped so.

“Darling, you do the zock marvellously! You have the genuine free-fall
touch!”

“Why, Gwinnie, that’s sweet of you.”

“There’s just one trouble, darling. The zock is strictly a this-minute
dance, isn’t it?”

“Forfeit! Forfeit!”

“I’m afraid they’re right, darling, much as it pains me to insist. Don’t you
know any of the old dances? How about the shaitan? That goes to this kind of
rhythm, I think.”

“Of course it does, Gwinnie. I’m terribly sorry, I should have thought. You
want me to do the shaitan for my forfeit?”

“That’s right. But—somebody hand me that dish of honey from the table there?
Thank you, lover-girl. Hold this in between your elbows while you’re
demonstrating it.”

“But—Gwinnie! It’ll get all over everything!”

“That’s the idea, darling. Come on now, and make with the whole bit. I want
to see you touch the floor with the back of your head.”

“Well, yes, I am a bit out of sorts, I guess. You see, I’m taking this
metabolic-rebalancing course that the Orbital Clinic provides for people who
don’t respond to Triptine—you’ve heard about that? Uh-huh. And there’s one
drecky drawback, which is it makes you much more susceptible to colds, so
I’m full to here with counteragents and what with one thing and another my
hormones and enzymes are going over Niagara in a barrel. I say, is that
twentieth-century or nineteenth?”

“Of course, it’s public knowledge that if the Nark Force was given the funds
and support it needs to enforce the legislation it’s supposed to the
government would be out on its ear tomorrow. But the discontent needed for a
genuine revolution is being drained off into orbit somewhere and that suits
Washington fine.”

“So they got these two volunteers, you see, this codder and this shiggy who
didn’t give a pint of dreck about doing it in public, and they laid on this
exhibition of human reproductive processes for Shalmaneser.”

“No matter what they say I can’t tolerate adherents to a cult which doesn’t
respect the human rights of non-members. That’s bigotry irrespective of what
verbal haze you generate around it. And these Right Catholics with their
insistence on unrestricted breeding are trespassing on the human rights of
everyone else’s children. They sheeting well ought to be banned.”

“Right across the block from where my brother-in-law lives. And such a
mild-mannered old codder too, he said. Just picked up this butcher’s cleaver
and chopped the heads off the kids he was looking after, then went up on the
roof with this crate of empty bottles, and started hurling them down on the
people below. Killed one, blinded another, had to be fused by a police
copter. Could be anybody, you see—and without universal
personality-profiling how can one be sure who’s going to turn mucker?”

“Well, we’re pretty lucky, you see. We managed to get into a club—about
fifteen couples, all celebrated their twenty-first, very nice people—and
there’s a sitting rota so we get to look after the prodgies of members who
have clean genotypes. There are nearly a dozen altogether and one of the
shiggies is supposed to be preg with twins. Marvellous. We can reckon on
having prodgies around the place at least one night a week. It’s not like
having one’s own, but—well, there’s no help for it. We have schizophrenia on
both sides of the marriage and the risk is far too great.”

“Oh no. Philip is much too young to come along to a party like this. Time
enough later on to become sophisticated and cynical and debauched like us
oldsters, that’s what I keep telling him. Of course he doesn’t like it—goes
on all the time about what other parents allow their prodgies to do at his
age—but one doesn’t want to see the bloom of innocence rubbed off too soon,
does one? You’re only young once, after all.”

“Frank and Sheena? Oh, they went to Puerto Rico. Didn’t have any
choice—they’d sold the apt, bought the tickets, got jobs out there … But
they were furious! Said they were going to get out of the States altogether
as soon as possible so they could after all have their own prodgies. But
lord knows where they can go. Can’t see them roughing it in some benighted
backwater country for long, myself, and of course they’d never be allowed
back if they did start a family after being forbidden to do so here.”

“You heard what happened? Thought they were being clever. Found someone in
the Eugenics office who was open to—ah—persuasion and got themselves a
forged genalysis. Went to a private clinic, and the karyotype said they were
going to have a mongoloid idiot. Twenty-five thousand buckadingdongs it cost
them to get that gene certificate, and they had to have the kid aborted
after all!”

“We got ours through the Olive Almeiro Agency. Very big operation. Naturally
it can’t be passed off as our own—my wife is even fairer than I am and the
kid is dark, hair, skin, eyes, the whole shtick—but we could have waited
five, six years for a baby to match our own genotype and then not been able
to afford the cost.”

“So when these two had finished Shalmaneser said where’s the baby? And they
said oh, you have to wait nine months for that.”

“Look, I don’t mind panhandlers as such—in fact I think it’s a damned good
idea to license them because at least that gives you the option of choosing
whether you’re going to support a given individual case instead of simply
taxing you and passing the money on in welfare allotments to wastrels and
vagabonds. But the way the union has got whole districts of the city sewn up
now and insists on kickbacks and drives non-members out of the area—that’s
more than I can swallow!”

“Oh, are those the new Too Much joints? May I try one? I heard very good
things about the strain. Thanks. I hope Gwinnie doesn’t recognise them or
she’ll make us pay forfeit on them and I don’t like the look in her eye.
She’s building up to something really nasty, I suspect.”

“The draft got his balls. They’re cracking down very hard at the moment. Did
everything he could—turned up for the board with mother in tow, wearing one
of her dresses, orbiting like crazy, and they took him anyway. He’s in that
horrible army hospital St. Faith’s right this minute undergoing aversion
therapy for ambivalence and tripping both at once. It’s absolutely inhuman,
and of course if it works when he comes back he won’t want to know any of
his old friends, he’ll be one of their automatic push-button people, a good
solid respectable citizen. Doesn’t it make you want to weep?”

“One thing about this crazy party, I do depose—I never expected to see so
many shiggies at Guinevere’s place looking like shiggies instead of like
sterile-wrapped machines. Do you suppose she’s testing the temperature to
see if she should move the Beautiques over to the natural trend?”

“Happened all in a moment. One second, just a bunch of people walking down a
street, not going any place in particular, and the next, these brown-noses
clanging on big empty cans with sticks like drummers leading an army and all
sorts of dreck flying through the air and windows being smashed if they
weren’t out already and screaming and hysteria and the stink of panic. Did
you know you can actually smell terror when people start rioting?”

“Louisiana isn’t going to last much longer, you know. There’s a bill up for
next session in the state legislature which will ban child-bearing by anyone
who can’t prove three generations of residence. And what’s worse they’re
only offering five to two against it being passed. The governor has his two
prodgies now, you see.”

“I was in Detroit last week and that’s the most eerie place I ever did set
foot. Like a ghost town. All those abandoned factories for cars. And
crawling with squatters, of course. Matter of fact I went to a block party
in one of them. You should hear a zock group playing full blast under a
steel roof five hundred feet long! Didn’t need lifting—just stand and let
the noise wipe you out.”

“It’s more than a hobby, it’s a basic necessity for modern man. It fulfils a
fundamental psychological urge. Unless you know that if you have to you can
kill someone who gets in your way, preferably with your bare hands, the
pressure from all these people is going to cave you in.”

“I graduated with a master’s rating on throwing knives and a grade one
rating on hand-to-hand. I already have a marksman certificate on bolt-guns,
and next I’m intending to collect one for projectile weapons—rifles, pistols
and crossbows.”

“Sure you can come around, but don’t hope for too much. I’m living in a
group, you see, and there are eight of us, so I don’t feel much need for
variety. Also we have two kids and our shrinker says they have positively
Polynesian emotional stability so the last thing I want is to interfere with
a setup that’s paying such fine dividends. It’s the extended family bit, of
course.”

“Nevada’s mavericking again, did you hear? There’s a bill up for next
session to recognise polygamy and institute proper marriage and divorce laws
to cover it. Up to groups of ten, I think it says in the draft.”

“Don’t lie to me, darling. I saw that codder’s blip go up on your screens
the moment he asked you to dance. I’ve told you before and I’m telling you
again, I don’t mind you bivving it privately but I won’t stand for it in
public. So I’m an old-fashioned block, so I’m still your wife and if you
want me to stay that way you behave when you’re in company—catch me?”

“So Shalmaneser said well, if it takes nine months, why were you in such a
sheeting hurry at the end? Haw-haw-haw!”

“I’ve been hoping to have a word with Chad Mulligan, but I can’t pry him
away from those Aframs he’s talking to. I want to ask him whyinole when all
our dreams are about wide-open spaces and room to move and breathe we like
to cram ourselves together at parties till we can’t hardly cross the floor
of a room without shoving aside twenty other people.”

“Look, lover, you carry it off very well but I fly a perfectly straight
orbit and what’s more I’m married so why don’t you find someone who likes to
biv and stop harassing me?”

“I got one of these super disposalls, too, because the garbage clearance
down our block is five weeks—catch me, five!—overdue. And the first day I
try to use it comes in this sheeting little pest and says I’m violating the
clean-air laws. Great balls of dreck, clean air! There hasn’t been any clean
air in our neighbourhood for sheeting weeks because of rotting dreck all
over the streets and now it’s beginning to block the passages!”

“Yes, but what’s the use of arguing about politics these days? Isn’t such a
thing as politics. There’s just a choice between the ways you’re going to
cave in through force of circumstances. Look at Common Europe, look at
Russia, look at China, look at Africa. The sheeting pattern’s the same
except in some places it’s gone further than others.”

“Look, Schritt—all right! Look, Helmut! If you don’t get off my orbit and
let me fall free for a bit I’m going to stand right up where everyone can
hear me and pull rank, do you hear me? I don’t give a pint of whaledreck if
Chad Mulligan does sound subversive to you—he happens to be talking to our
ambassador to Beninia and I’m interested in what they’re saying. I was told
to carry on with my ordinary activities and if you’ve read my original brief
you sheeting well ought to know that it includes being interested in
everything relevant or not relevant to my assignment. Now go dig a hole and
lie down in it!”

“Things are getting tough again in India, apparently. It’s the protein that
was lost when the slit-eyes poisoned the Indian Ocean. And by the way, I
hear the containment programme is running behind—a current spilled over past
one of the barrages and they’ve been hauling out contaminated fish as far
north as Angola.”

“I have this new autoshout of GT’s that programmes itself on a signal from
the satellite. Haven’t missed a show in three weeks through rescheduling.
Should get one.”

“I use nothing but Kodak Wholopan R myself. The rating is 2400, to start
with, which means there’s practically nothing you can’t catch, and there’s
ninety-five per cent recovery on a division factor of twenty, which means
you never need more than one print and a pair of scissors.”

“No, that’s what’s so extraordinary. Freefly-suiting is terrific exercise, a
sort of dynamic tension method because all your muscles are working against
each other. Of course, you have to watch your calcium balance like a spy,
but there are treatments which actually improve it over normal Earthside
levels now.”

“The acceleratube makes commuting perfectly possible. I can get to work
quicker from Buffalo than I used to when I lived in Elizabeth.”

“I think I’ll have to take copter lessons.”

“You know that magnificent new block in Delaware that we spotted from the
plane as we were coming in and thought what a great place it could be to
live? Well, I just met someone who told me what it’s meant for, and unless
you feel like going out and shooting a fuzzy-wuzzy we can kiss the dream
goodbye. It’s a sheeting jail, that’s what it is—a new maxecurity jail!”

“We’re going to have to do as they’ve done in London and Frankfurt. We’re
going to have to make better use of the space already enclosed by the cities
we have. In London they’ve more or less given up the idea of streets except
for arterial throughways. They’re building over them and leaving nothing but
tubeways for passenger transit.”

“It just sort of folded like a leaky accordion, all thirty storeys of it.
Girders bulged outwards, floors lay down on top of each other, and squelch,
all the people who were living in it—I think they said nine hundred—were
flattened out like sardines in a sandwich. Apparently when they programmed
the computer which designed it they forgot to instruct it to allow for the
weight of the occupants.”

“Exceptionally good freevent the other night. It was literally indescribable
because it was so abstract. I still haven’t got over it.”

“What it does is sort of invert the responses—for example I never found
anything in my life quite so funny as the B Minor Mass. And let’s face it,
you know, in the ultimate analysis that’s a proper response in contemporary
terms.”

“Yes, I knew somebody who applied to them. Wanted to go out being gored by a
bull in front of a big cheering audience, believe it or not. So they fixed
it, got the setup from Mexico, wrung the buckadingdongs out of him and the
cost ran to plenty, of course, and he had a heart attack from overexcitement
before they turned the bull loose, so back he went to hospital to be revived
and he ran out of funds while he was getting better and in the end he just
signed an ordinary release and they withdrew his prosthetics. A débâcle on a
grand scale, but still a débâcle!”

“He and his sister joined the Mrs. Grundy Memorial Foundation and some
sheeting little prig turned up some forgotten ordinance and the case comes
up next week. Going to be a major point of principle at stake.”

“Skiing in Patagonia, I think. We were going to spend it under the
Caribbean, but Mr. and Mrs. Everywhere go there such a lot we’re afraid
it’ll be dreadfully crowded.”

“She’s quite marvellous. All I did was give her that lock of my mother’s
hair and she told me the most fantastic things—I mean, I never knew mother
had all those affairs, one after the other, and most of them with
brown-noses! I knew I was right not to trust her with what father left!”

“The Vedantas, of course, say something quite contrary.”

“One of these Antarctic treks, probably. I hate the snow but whereinole else
is there that Mr. and Mrs. Everywhere haven’t been recently? I can’t stand
all these interchangeable people!”

“The future is inherently perfectly knowable. All the faculty takes to
develop is the proper kind of exercise and meditation.”

“You sound as though you fell in love with Beninia right from the start. Was
it just because you knew and admired Zadkiel Obomi or was there something
else to it?”

“There’s this tour to Khajuraho which sounds like fun, with all those
parties planned around the erotic sculptures on the old temples, but
apparently the tourists have to go there under armed guard because of danger
from native robbers and frankly I don’t see how I could enjoy it to the full
with a circle of gunmen standing all around me.”

“This marvellous recording of the Ninth which puts you right in the middle
of the choir—when the Ode to Joy lets loose it’s like an earthquake!”

“I’ve been painting some Jackson Pollocks with my polyformer this week and
it’s left my arms stiff as fenceposts.”

“Moonbase Zero is more like a submarine than anything else. I really admire
the people who stay there for a whole tour—some of them stick it for over
six months, you realise?”

“Our shrinker recommended sending Shirley to this new school at Great Bend
and I think that’s a marvellous idea but Olaf has these dreadfully antique
views about juvenile eroticism and says they lay too much emphasis on
sensuality, so I’m going to file for divorce and get custody and then Wendy
and I will take her out there ourselves.”

“Makes you wonder how our ancestors ever managed to breed such a sheeting
horde of human beings when every time you felt like it you had to take off
all these layers and layers of cloth.”

“I think I’m going to sue them even though they didn’t give me a guarantee.
I mean, eight thousand isn’t to be dropped like an empty pack of reefers, is
it? And all the pup did when we got it home was sit around snivelling and
pee on the floor every half-hour. The prodgies were heart-broken, of course,
because they did so much want a green dog and they just wept and wept so I’m
sure it was traumatic for them. Edna says I should have gone to some other
company who’ve cut down the side-effects, but believe me I’m not going to
risk another gene-moulded pet. They can make do with a regular cat next
time.”

“Well, if your genotype is okay, why don’t you just get yourself preg by
someone else who’s also clean? Me, for example? I have my genalysis with me,
as it happens.”

“Charlie, got any stiffener with you? I just had this shiggy in the
roof-garden and I promised Louise as well and I don’t want to be left
dangling when the big scene takes over later.”

“This mutated cactus with the huge orange flowers that last for weeks after
they’re cut, but you have to keep them under a glass bell because they do
stink rather, a bit like rotting meat.”

“I never took to polyforming. Rather stay with my old hobby of vicarious
music. Blocky it may be, but I don’t have the talent to go through a Cage
score on my own jets, and I do love the feeling of actually creating the
sounds with my fingers.”

“The bleeder slipped her a cap of Yaginol while she was preg and of course
they had to abort the phocomelus. She’s suing him.”

“Thinking of cutting out to join one of these communities in Arizona.”

“Dead set on going into the space service but I guess he’ll grow out of it
when he discovers shiggies.”

“Sold my shares in Hitrip like a sheeting idiot and then two months later
they announced the Too Much strain and I guess I lost fifty thousand
buckadingdongs on the deal.”

“So they programmed Shalmaneser with the formula for Triptine, you see, and
then these jokers fed in the question How Hi is a Chinaman.”

“I think instead of increasing it to four months’ vacation they should
operate two shifts on monthly rotation. Of course it would cost but the
degree to which it would increase the self-respect of the employees would
more than make up for it.”

“Most of them seem to be at it in the roof-garden. Want to go and watch, get
some pressure up for later?”

“I think these cigarettes are horrible. Made my throat so sore. And my guts
are all sour and nasty. Did people really use twenty in a day?”

“They call it streamlining, of course, but what it comes down to is they’re
undermining my responsibility in the firm and I’m going to fight tooth and
claw to hang on to what I’ve got. If I have to play it dirty that’ll be
their fault, not mine.”

“It makes genuine three-dimensional poetry possible for the first time in
history. Right now he’s experimenting with motion added, and some of the
things he’s turned out are hair-raising.”

“You hold the knife this way, see?”

“Refuse to teach their children to read and write, say it handicaps them for
the post-Gutenberg era.”

“Not many people have spotted it but there’s a loophole in the Maryland
eugenics law.”

“A polyformer for water-sculpture, quite new.”

“Of course I don’t love Henry the way I love you but the shrinker did tell
me I ought to occasionally.”

“I’m just cutting jets for a prayer or two but I’ll be back—don’t get
involved with anyone else.”

“That makes seventeen different mixtures I’ve tried, and I’d better have
some antalc, right away.”

“I think it was bitchy not to tell Miriam it was pig-meat.”

“They’re trying to ranch the orange ones in Kenya but apparently so far only
the pale-blue ones will breed true in the wild state.”

“I think I’m going to shake off my holding in MAMP. It’s been years after
all and by this time I’m wondering if the rumours about the big strike were
just propaganda.”

“Had a chance to talk to Chad Mulligan? Nor have I. I was wondering whether
to be really twentieth-century and go ask for his autograph.”

“Campaign to get whales back by breeding up from smaller aquatic mammals but
the cost is astronomical!”

“Blew up three bridges before the fuzzy-wuzzies fused them and one of them
turned out to be in the same class as my son Hugh.”

“I’m sorry to snivel like this but it’s damned unfair having him killed in a
stupid sheeting accident like that and now being married to someone who’s
not allowed to father prodgies. And he was only six, he couldn’t even read
yet!”

“Watch out for Guinevere—I think she’s building up to the big staged ones.
I’m going up to the other floor for a bit. Some of the things she does when
she’s in that mood don’t strike me as funny.”

“I got on fine with Don and to be quite honest I half-hoped he’d ask me to
make it permanent. But I couldn’t stand his roomie.”

“Of course it can’t be the Chinese who supply them with sabotage equipment.
Explosives and thermite maybe, but not the tailored bacteria they used to
bring down that apartment building in Santa Monica.”

“So Shalmaneser said how high is a Chinaman? I don’t know, but if he’s any
higher than I am we might as well quit because they have us beat.”

“Accused of reviving thuggee—you know, Kali-worship?—and the crowd stormed
the court and set them free.”

“Spend my vacation taking that induced-schizophrenia course they offer at
the Leary Clinic—think it’ll broaden my horizons.”

“Wanted to be burned alive in protest against the draft but the directors of
the company apparently decided it was interfering in politics and not in
accordance with their corporation charter so he tried to do it by himself
and they put him out before he’d done more than sustain third-degree burns.
Going to jail for ten years, I gather. Evasion.”

“A totally corrupt police-force is the next best to a perfectly honest one.
Ours is quite livable with. Mark you, it takes a bit of time occasionally
finding out who’s bidding against you, but there are only a few
possibilities in a small community like ours.”

“So when he said he had a clean genotype but he was going to be sterilised
anyway I lost my temper—can you blame me?”

“It’s twentieth-century for me to be jealous, isn’t it? You keep away from
my wife or I’ll get Gwinnie to make you pay forfeit for behaving in a
twenty-first century manner!”

“I’m going to have to find out more about Beninia, Elihu. I can’t really
believe what you say is true.”

“I got two glasses of the ’98 Château Lafite before it ran out and believe
me it was quite an experience.”

“Have you tried it intravenously? You can get diadermic guns for about forty
or fifty bucks, and it makes a galaxy of difference to the lift.”

“Talking about clearing the old Renault factory but it’ll be like civil
war—there are sixty thousand squatters on the ground and apparently some of
them have bolt-guns and the place is crawling with old projectile weapons of
course because they went over to sporting guns when they closed.”

“Told me about this public execution he went to in Algeria and it got me so
excited I just couldn’t help myself. Why don’t you ask him about it? He did
say he bivs occasionally.”

“So she told her to smear her belly with apple-butter and let the sparewheel
lick it off. She’s getting nasty, darling. Next time it won’t be licking,
it’ll be biting. Want to blast off for home?”

“Look out, he’s got a knife!”

“But the whole aesthetic of holographic television is being called in
question by Eldred’s work.”

“I’ve taken over the selection programme for the Museum of Last Week, did
you hear? How about letting me have some of your stuff?”

“Tripping.”

“By the way, Norman, I did men-

“Work”

tion, didn’t I, that I’m being

“Religion.”

thrown out of my place and I’m

“Psychology.”

looking for a spare tatami?”

“Eugenics.”

“How are we doing for liquor?”

“Society.”

“Mel Ladbroke, right? Look,

“War and peace.”

you don’t by any chance—? Oh,

“Sex.”

sheeting hole! Forget it.”

“Food and drink.”

“Are you by yourself, lover?”

“Politics.”

“It would make a difference if

“Hobbies.”

they could afford to buy gene-

“Art.”

moulded maize stocks, for exam-

“Entertainment.”

ple. But they can’t.”

“Housing.”

“Gwinnie’s saving you up, you know!”

“Travel.”

“People are stupid, including me.”

“Guinevere got anybody’s balls yet?”

GRAPH GUINEVERE: an early peak followed by a flat low line marked at its
inception by Norman’s correction of her judgment regarding the man in the
year 2000 suit. Since then, a state of suppressed anger, punctuated by only
enough minor forfeits to keep that hard core of her sparewheels contented.
Saving up the remainder—all noted with sharp eyes and double-checked
mentally to avoid a second similar gaffe—for an unusually extensive series
of set-piece forfeits at the end of the evening. Included with
question-marks, people like the ambassador who has completely wasted his
cachet and Chad Mulligan’s into the bargain by talking together non-stop
throughout the evening despite several attempts to make them circulate.
Trust a brown-nose to foul things up, ambassador or no.

GRAPH DONALD HOGAN: a jagged line varying between sick dismay masked with
polite and occasionally quite interesting chat to Elihu, Chad, Gennice and
other acquaintances, and raw fury at being dogged by Sergeant Schritt. Four
separate attempts to corner the man from Bellevue privately and perform that
quasi-suicidal act of obtaining from him some sort of lifter or whatever
that would enable him to break his cover under the pretence of being slipped
a cap by someone unknown. Shortly, the line due to snap up into the
unknowable hyperbolic future course of the activated spy.

GRAPH GENNICE: a high-level curve with a lot of peaks of amusement and
enjoyment because she’s very fond of her new man, but with occasional
wistful dips caused by wondering whether it’s her departure that made that
nice Don Hogan feel so low tonight.

GRAPH CHAD AND ELIHU: an early plateau low on the scale, then a simultaneous
rise and a long, long parallel run not across the regular chart of the party
but away from it at an angle of their own, pacing each other and still
rising.

GRAPH NORMAN: an early peak caused by so successfully scoring off Guinevere,
followed by a slow decline with occasional bumps tending towards
determination to see her look equally foolish if she tries to involve him in
a set-piece forfeit or towards self-disgust because he prizes such a petty
achievement.

GRAPH THE PARTY: a planar representation hillocking over the roof-garden
where those interested mostly in sex congregated early and heavily indented
in the vicinity of Donald, Norman, Guinevere herself and one or two more,
otherwise generally on an acceptably high level although a good many people
have had the edge taken off their enjoyment by the aura radiating from
Guinevere by now consulting in whispers with certain chosen sparewheels and
who can be sure what infelicity, what incongruity, as minor as having
referred to a post-turn-of-century artwork has given her the opening for
another arrowed forfeit?

“If Gwinnie picks on me I’m going to give her a present. From this firm that
sends people around to invade your apt and wreck the furniture!”

Now I can get the two shiggies, the fat and the thin ones, to change
clothes, which ought to be good for five minutes and a few giggles, and
during that time slip Norman a cap of …

“What was that?”

“That girl with the hideous caped outfit, I think—I saw Gwinnie consulting a
history of costume in the other room just now.”

“Excuse me, do you mind saying that again?”

Like a cool breeze soughing through the room: a wave of interest and
curiosity.

“No, that weird codder Lazarus hasn’t been through the mill yet and I never
knew him to miss. He loves being humiliated, gives him the strangest kind of
lift, apparently.”

“Are you sure? Who told you?”

“I made a wager with myself that she’d pick on Renée—you know, the fat
shiggy with the glandular thing they can’t cure, like a big sagging jelly?
She always gets hit hard.”

And what I’m going to do to Norman will make history. Not this time the
cunning brown-nose doesn’t get off lightly! That codder with the Black Belt
in case he tries to duck out, to be safe. Where is he? Not involved with
another shiggy!

“But it must be pure propaganda! I mean, so far not even the dogs and cats
and bushbabies they’ve made over for pets are…”

“Is something going on over there?”

“Let’s find out, shall we?”

“Darlings, how convenient for me to have caught you talking to each other!
You see, I’m terribly afraid that—”

“If SCANALYZER carried it the news must have been processed by Shalmaneser
so it’s at least possible. Unless they carried it in the rumour slot, was
that it?”

It began to dawn on Guinevere by slow degrees that for the first time ever
since she took to throwing forfeits parties the arrival of her well-briefed
gang of sparewheels in the neighbourhood of the victims chosen for the first
of the grand forfeits, the set-pieces that would include dialogue and climax
in acts of maximum humiliation to get rid of people she was tired of
knowing, had not signalled silence and giggling and craning of necks and
climbing on furniture for a better view. Instead, on the far side of the
room, a large number of the guests were talking to each other with serious
faces, apparently sceptical but not scoffing. She waited a moment. A few
people drifted away from the unidentified focus of attention and others
joined; somebody hurried out of the room and came back with half a dozen
friends also to be told—whatever the news might be.

“Hullo!” Norman said softly. “What’s going on? Guinevere isn’t getting the
rapt audience she counts on.”

“Think war’s broken out?” Chad muttered and grabbed a fresh drink from a
passing tray.

Alarm transfixed Donald like a lightning strike. The randomness of his
activating this morning, unaccountable in terms of what the news channels
were carrying, made him think for a moment that it could all too easily be
war.

“Chad, what did you say about crying wolf in The Hipcrime Vocab?”

“Howinole do you expect me to remember? I’m drunk!”

“Wasn’t it something about—?”

“Ah, sheeting hole! I said it was an ad-hoc form of Pavlovian conditioning
adopted by those with a lust for power to prevent the people due to be
slaughtered in the next war from taking them out and humanely drowning them.
Okay?”

“Why do you hate Miss Steel so much?” Elihu asked Norman under his breath.

“I don’t hate her personally, though if she were enough of a person to be
worth such a strong emotion I think I easily could. What I hate is what she
represents: the willingness of human beings to be reduced to a slick visual
package, like a new television set—up-to-the-minute casing, same old works.”

“I hope I can believe that,” Elihu said unhappily.

“Why?”

“People who hate in concrete terms are dangerous. People who manage to hate
only in abstracts are the only ones worth having for your friends.”

“Plagiarist!” Chad threw at him.

“Did you say that?”

“Christ yes. Put it in a book.”

“Someone quoted it to me once.” A look of wonder crossed Elihu’s face. “As a
matter of fact it was Zad Obomi.”

“Profit but no honour in my own country,” Chad grunted.

“What’s she going to do now?” Norman said, watching Guinevere intently. They
all turned to look; they were in a good spot from which to see what
happened, able to view it along a sort of alley between the clump of people
who had congregated to witness the humiliation of the fat girl and the thin
one, and the other group worriedly muttering to each other about the as yet
mysterious news.

“Shelley-lover,” Guinevere said to the man at the centre of the latter
assembly, “if the news you’re spreading is so millennially important don’t
you think you should share it with everybody rather than letting it wander
around on its own, suffering the folk-process? What is it—have the Chinese
towed California out to sea, possibly, or has the Second Coming been
announced?”

“Second!” someone unidentifiable said within earshot of Don. “Prophet’s
beard, you should try that new stiffener Ralph’s been feeding me!”

Guinevere looked for him with a glare of murderous ferocity and failed to
locate him.

“Well, it’s something that was on SCANALYZER earlier this evening, Gwinnie,”
the man she had addressed as Shelley explained in an apologetic manner.
“Apparently the government of Yatakang has announced a two-generation
programme based on a new breakthrough in tectogenetics. First off they’re
going to optimise their population by making sure that only children of
first-class heredity get born, and later, when they’ve done that, they’re
going to start improving the genalysis and—well, I guess the only way you
can put it is to say they propose to breed supermen.”
