#+TITLE: Chick Corea's Advice for Playing Music in a Group


1. Play only what you hear.
2. If you don't hear anything, don't play anything.
3. Don't let your fingers and limbs just wander--place them intentionally.
4. Don't improvise on endlessly--play, something with intention, develop it or not, but then end off, take a break.
5. Leave space--create space--intentionally create places where you don't play.
6. Make your sound blend. Listen to your sound and adjust it to the rest of the band and the room.
7. If you play more than one instrument at a time--like a drum kit or multiple keyboards-make sure that they are balanced with one another.
8. Don't make any of your music mechanically or just through patterns of habit. Create each sound, phrase, and piece with choice--deliberately.
9. Guide your choice of what to play by what you like-not by what someone else will think.
10. Use contrast and balance the elements: high/low, fast/slow, loud/soft, tense/relaxed, dense/sparse.
11. Play to make the other musicians sound good. Play things that will make the overall music sound good.
12. Play with a relaxed body. Always release whatever tension you create.
13. Create space--begin, develop, and end phrases with intention.
14. Never beat or pound your instrument--play it easily and grace- fully.
15. Create space-- then place something in it.
16. Use mimicry sparsely--mostly create phrases that contrast with and develop the phrases of the other players.
