#+TITLE: Anon Quotes
* Top
** 19th century british society
Women's twentieth-century roles outside the workplace also owed a
cultural debt to industrailization.
In the nineteeth century, British society increasingly codified separate spheres of endeavour for men and women
in response to the changes brought about by industrialization.
Factory acts began to restrict where and when women could work, ostensibly to
preserve their more delicate natures.
Middle-class women were corralled in the home so as not to have their femininity tainted by the industrialized city.
The "angel in the house" ideal circumscribed middle-class women's lives and strongly discouraged them
from seeking paid work in an expanding economy.
If required to work, the modesty expected for their future roles as mothers and wives limited
middle-class women's options:
"They should not flaunt their independence like the mill girls did".
In the 20th century, most women who aspired to middl-eclass existence therefore
found their choice of job dictated not only by gender but by class.
** 2009 Baptist Teen Camp
(see point 3).

#+begin_quote
Camps is for fun, for growing as Christians, and for God's honor.
All the rules center around this goal. We do not have fun at another's expense,
therefore:

1) No conversation ever concerning: rock music (Christian or Secular), booze, drugs, immorality,
   movies, vulgarity. This is neverto be a part of our talk, even in jest.
2) Suspected possession of booze, tobacco, or drugs, is a "Send home" offense.
3) The adults are always right, even when they are wrong. Keep a good attitude
   and let Pastor Goddard know of any problem. Do not mention it to anyone else.
4) Never touch another's property- tooth paste, shaving cream, water, etc.
   If you see a prank, turn it in or you are guilty too.
   All involved will go home - right then!
5) Be in your place, on time. If sick or a problem, tell a counselor.
6) Never wander off as a couple, guys or girls, or mixed.
7) No guy/girl contact ever, even with adults.
8) Stay away from cabins of opposite gender.
9) If you won't do it with a counselor watching, don't do it!
   Fire extinguishers, fires, firecrackers, or other daring, dumb things are prohibited.
10) No tape players, CD's or radios.
11) Pool area is off limits (including restrooms and area around pool) to those no scheduled to use pool
    at that time.
12) Never go into someone else's cabin without being invited.
13) Stay out of the kitchen.
14) Afternoon clean up time is for clean up and quiet: To read, pray, nap, etc.
    Don't bother each other. Stay in or near your cabin.
15) No one allowed in cabin alone.
#+end_quote
** A City Like a Guillotine Shivers on Its Way to the Neck

Alfonso stumbles from the corpse of the soldier. The townspeople are cheering,
elated, pounding him on the back. Those who climbed the trees to watch applaud
from the branches. Momma Galya shouts about pigs, pigs clean as men.

At the trial of God, we will ask: why did you allow all this?
And the answer will be an echo: why did you allow all this?
** African Proverb
"Until lions have their historians, tales of the hunt shall always glorify the hunter"

** Anon
*** No sources
The reason why i give no sources is that it is a matter of indifference to me
whether the thoughts that I have had have been anticipated by someone else.
*** English Language
English doesn't borrow from other languages.
English follows other languages down dark alleys, knocks them over
and goes through their pockets for loose grammar.
*** Brookhaven
A Few years later, the radiation intensity posed a serious problem when the mechanism
for raising and lowering the source failed, leaving the source at its position atop the pipe
-- effectively preventing any entrance to the field and certainly any effort to approach and
repair the snag.

The eventual solution decided on was to have the Brookhaven machinist Edward Nicholson,
who also happened to be an expert marksman, shoot through the cable from a distance, thereby
releasing the source into the lead shielding below.

Per orders of the Health Physics Department, Nicholson had to stay at least 100 feet from the pipe,
and he was only given one minute to make the attempt.
According to a later account, he succeeded on the second shot, liberating the field for use
-- and avoiding the still worse outcome of striking the cobalt, the dispersal of which would
have contaiminated the site for years.

*** Grant Application
I resent the imperative to describe
my work to you in terms other
than the work itself. I resent
the requirement of purpose
and even intention. I resent criteria.
I resent all comparable metrics
of value. I am fundamentally
opposed to value. I resent the expectation
I participate in a manner of speech
that serves your understanding.
I resent the scarcity model,
patronage, and the volume of art
created by people who have never known
hunger or precarity. I resent leisure
as a vantage from which we articulate
notions of beauty. I resent relevane.
I resent the distribution of resources
to confer tectonic supremacies
of words and perspective. I resent interest
in terms of both likeability and accrual.
I resent submission and acceptance.
I believe in language.
*** Organisation Theory
To finish on a more general note,
I think that the field of organization theory is facing a pandemic:
all papers want to claim three contributions.
This is less deadly than covid19, but it's still a pandemic we need to get rid of.
The more contributions a paper claims, the weaker each of these
contributions is (if only for lack of space to elaborate).
So, feel free to focus on what really matters, and what you can really claim.
I will definitely favor one strong contribution over three weak ones.
*** DSLs
DSLs should be embedded in a real programming language.
DSLs should be embedded in a real programming language.
DSLs should be embedded in a real programming language.
DSLs should be embedded in a real programming language...
*** Norms in a diverse society
The egalitarianism, civility, sense of freedom, and shared purpose portrayed by
E.B. White were the essence of mid-twentieth-century American democracy.
Today that vision is under assault. To save our democracy, Americans need to
restore the basic norms that once protected it.
But we must do more than that.

We must extend those norms through the whole of a diverse society.
We must make them truly inclusive.

America's democratic norms, at their core, have always been sound.
But for much of our history, they were accompanied -- indeed, sustained --
by racial exclusion.

Now those norms must be made to work in an age of racial equality
and unprecedented ethnic diversity.
Few societies in history have managed to be both multiracial and genuinely democratic.
That is our challenge.
It is also our opporunity.
If we meet it, America will truly be exceptional.
*** Why Cheap Art? Manifesto
the Why Cheap Art? Manifesto
PEOPLE have been THINKING too long that
ART is a PRIVILEGE of the MUSEUMS & the RICH.
ART IS NOT BUSINESS!
It does not belong to banks & fancy investors
ART IS FOOD.
You cant EAT it BUT it FEEDS you.
ART has to be CHEAP & available to EVERYBODY.
It needs to be EVERYWHERE because it is the INSIDE of the WORLD.
ART SOOTHES PAIN!
Art wakes up sleepers!
ART FIGHTS AGAINST WAR & STUPIDITY!
ART SINGS HALLELUJA!
ART IS FOR KITCHEN!
ART IS LIKE GOOD BREAD!
Art Is Like Green Trees!
Art is like White clouds in blue sky!
ART IS CHEAP!
HURRAH!

Bread & Puppet Glover, Vermont 1984
*** Mask wearing
The man who is unwilling to wear a flu mask usually is of the
kind who expects everybody to listen to him when he speaks
- old newspaper clipping
*** Work
Arbeit hat bittre Wurzeln, aber süße Früchte.

Work has bitter roots, but sweet fruits.
*** On Breaking the Repo
If you are ever worried that you broke the repo,
PLEASE ANNOUNCE THAT HERE.
You aren't necessarily responsible for fixing any disasters you cause,
but you *are* responsible for letting us know as a team so we can all repair broken things.

(^ this is true of real world code teams as well, the worst teammate
you can have is one who doesn't want anyone to see their mistake and tries
to silently fix their error with duct tape as the boat sinks.)

*** Peelite Policing
If one actually reads the one-famous Peelite principles of policing, you
will see this as the second principle:

"To recognise always the the power of the police to fulfill their functions
and duties is dependent on public approval of their existence, actions,
and behaviour and on their ability to secure and maintain public respect."

*** Criminalists
Criminalists are a model case of what happens to expert workers like
teachers, doctors, or engineers who have "good jobs" but are required to
work within systems beyond their control.
Perhaps securing expertise onece promised some level of autonomy;
this was particularly true for professionals, who often worked in partnerships managed
through the collegial interactions of a set of peers.
Today, being an expert worker often means that you report to nonexperts,
or must justify your existence to those who do not know your field.
Working with and depending on those outside of their occupational boundaries influences
experts' work practices.
Watching criminalists adapt to new technologies, invent new ways to communicate
their science, and struggle to show how their subjective yet informed judgements
are better than allegedly objective machines or automated algorithms is valuable;
it offers lessons for other expert workers.
*** Self-consciousness.
'Why don't you wear your influenza mask?'
'I'm afraid I might look funny.'
'Suppose you do. Wouldn't you rather introduce a little comedy into your household than subject it to a tragedy?'

*** Ad Hominem
"when the debate is lost, slander becomes the tool of the losers" - misattributed to socrates.

*** Satire
"Satire requires a clarity of purpose and target lest it be mistaken for and contribute to that which it intends to criticize"
- meme


*** ds9_quote
 "We got a lot of phone calls and lettes, probably more than any other episode I can recall.
Interestingly, most of the phone calls were negative, while most of the letters were positive.
One that I always remember was a call that one of our PAs took.
A man said, 'You're ruining my kids by making them watch two women kiss like that.'
And our PA said, 'Let me ask you a question. Would you have been okay if one of the women had shot the other to death with a phaser and the kids watched that?'
And he said, 'Yes, of course'.
And the PA said, 'Well, maybe you'd better think about who it is that is ruining your kids'. "
 Quote regarding DS9 lesbian kiss.


*** Making progress
"The legendary cellist Pablo Casals was asked why he continued to practice at age 90.
'Because I think I'm making progress' he replied."

*** Debate
"When you debate a person about something that affects them more than it affects you, remember
that it will take a much greater emotional toll on tem than you. For you it make feel like an
academic exercise. For them, it feels like revealing their pain only to have you dismiss their experience
and sometimes their humanity. The fact that you might remain more calm under these circumstances is a
consequence of your privilege, not increased objectivity on your part. Stay Humble."

*** Dying on a hill
"Weird hill to die on, but at least you're dead."

*** Trauma Informed Education
"In this school we are trauma-informed.
We connect before we correct.
We stay curious not furious.
We understand behaviour is communication.
We believe in co-regulation, that children regulate off the adults in their lives.
We think can't - not won't.
We empathise when someone is flipping their lid.
We believe in restoration - not punishment.
We believe that relationships buffer stress and build resilience.
All of us need one another, always.
Resilience means we see you, we hear you, we are with you."

*** Fighting Nazis
"Mother, I've weight the risks which I prefer to living in a world dominated by Nazis."
- Bill, on his headstone.


*** Capitalist Insanity
"Capitalist Insanity: A Scientist prophesies that by the year 2020 the inhabitants of the world
will all be insane. Some of us are inclued to think that today the world is one huge insane asylum,
where the sane are kept in bondage by the insane." - old news clipping

*** Racism
"In 1995 racism may wear a new dress, buy a new pair of boots, but neither it nor its succubus twin
fascism is new or can make anything new. It can only reproduce the environment that supports its
own health: fear, denial and an atmosphere in which its victims have lost the will to fight.
The forces interested in fascist solutions to national problems are not to be found in
one political party or another, or in one or another wing of any single political party.
Democrats have no unsullied history of egalitarianism. Nor are liberals free of domination agendas.
Republicans have housed abolitionists and white supremacists.
Conservative, moderate, liberal; right, left, hard left, far right; religious, secular, socialist-
we must not be bliindsided by these Pepsi-Cola, Coca-Cola labels because the genius of fascism is
that any political structure can host the virus and virtually any developed country can
become a suitable home. Fascism talks ideology, but it is really just marketing -
marketing for power."

*** Videogame Manifesto
"Manifesto:
Make bad videogames
with orbs
where you can get stuck in walls
and fall through floors
that embrace the glitches and bugs
with amateurish hand draw grafix
that explore unexplored emotions
where you can pet animals
and pick flowers
and make friends
with no other goals."


*** The writer, daytime insomniac

Granted, to write is to renounce being in command of oneself or having a proper name,
and at the same time it is not to renounce, but to announce, welcoming without recognition the absent.
Or, it is to be in relation, through words in their absence, with what one cannot remember -
a withness to the unencountered, answerable not only for the void in the subject, but for the subject
as a void, it's disappearance in the imminence of a death which has already taken place,
out of place, any place at all."

*** Kindness
"It pleases me that we may explore kindness with one another," Besarion said. "But do not mistake
my kindness for a gentle nature."

*** Not using the literature to make a point
"I am not about to use literature to make this point. Anyone who is interested can discuss it at length with actual women."

*** When White folks can't defeat you
"When white folks can't defeat you they'll always find some Negro - some boot-licking, butt-licking
buck-dancing, bamboozled, half-baked, half-fried, sissified, punkified, pasteurized, homogenized nigger -
that they can trot out in front of you."

*** Six-inch layer of topsoil
"Despite all our accomplishments we owe our existence to a six-inch layer of topsoil and the fact it rains"


*** Not making political statements
"We weren't making a political statement. == We made a political statement unconsciously."

*** Satan doesnt create evil
When ya find out Satan ain't the one creating evil:
"I form the light and create darkness
I make peace and create evil:
I the Lord do all these things"
- Isaiah 45:7

*** Imaginary Friends and Enemies
Whats Crazier than having an imaginary friend?
Having an Imaginary Enemy.

*** Conservatism
"Conservatism is the dread fear that somewhere, somehow, someone you think is your inferior
is being treated as your equal."


*** Experimental Economics
"We investigate the methodology used in a significant genre of experimental
economics, in which experiments are designed to test theoretical models by
implementing them in a laboratory.
Using two case studies, we argue that such an experiment is a test, not of what the
model says about its target domain, but of generic theoretical components used in the model.
The properties that make a model interesting as a putative explanation of phenomena in its
target domain are not necessarily appropriate for such tests."

*** Restoration is fear of mortality
"Restoration is fear of mortality, or wanting to believe that anything that's broken can return
to how it was."

*** Choosing not to vote
"When you choose not to vote, you allow for the worst people to decide not only your future,
but the future of everyone you love."

*** Humans are born free
"All human beings are born free and equal in dignity and rights".

*** Complicating things
I think we like to complicate things when it is really quite simple;
find what it is that makes you happy and who it is that makes you happy and you're set.
promise.

*** Repeat After Me: I Am Free
Go to work, send your kids to school,
follow fashion, act normal,
walk on the pavement, watch TV.
Save for your old age, obey the law
Repeat after me: I am Free.

*** Writing advice
1) Never open a book with the weather.
2) Avoid Prologues
3) Never use a verb other than "said" to carry dialogue
4) Never use an adverb to modify the verb "said"
5) Keep your exclamation points under control.
6) Never use the words "suddenly" or "all hell broke loose"
7) Use dialect sparingly
8) Avoid Detailed descriptions of characters
9) Same for places and things
10) leave out the parts readers tend to skip

*** Writing Advice 2
1) Never use a metaphor, simile, or other figure of speech which you are used to seeing in pring.
2) Never use a long word where a short one will do.
3) If it is possible to cut a word out, always cut it out.
4) Never use the passive where you can use the active.
5) Never use a foreign phrase, a scientific word or a jargon word if you can think of an everyday English equivalent.
6) Break any of these rules sooner than say anything outright barbarous.


*** Westworld guests
 It’s not about giving the guests what you think they want. That’s simple. The
 guests don’t return for the obvious things we do, the garish things. They come
 back because of the subtleties, the details. They come back because they
 discover something they imagine no one had ever noticed before. Something they
 have fallen in love with. They’re not looking for a story that tells them who
 they are. They already know who they are. They’re here because they want a
 glimpse of who they could be.”
 - [[https://www.kotaku.com.au/2016/10/the-video-game-horror-of-hbos-westworld/][Westworld]]


*** Theory and Practice
 Theory is when you know everything but nothing works.
 Practice is when everything works but no one knows why.
 In our lab, theory and practice are combined: nothing works and nobody knows why.

*** Pronounciation
 Never make fun of someone if they mispronounce a word. It means they learned it by reading.


*** Jewish Apple Pie
Jewish Recipe for Apple Pie
First, fry up some onions and garlic so the kitchen smells like you're cooking


*** You are the books you read
"You are the books you read, the films you watch,
the music you listen to, the people you meet,
the dreams you have, the conversations you engage in.
You are what you take from these.
You are the sound of the ocean, the breath of fresh air,
the brightest light and the darkest corner.
You are a collective of every experience you have had in your life.
You are every single second of every single day.
So drown yourself in a sea of knowledge and existence.
Let the words run through your veins and let the colours fill your mind."


*** Debugging
The activity of “debugging”, or removing bugs from a program, ends when people
get tired of doing it, not when the bugs are removed.
- Datamation, January 15, 1984.

*** Social Distancing is a privilege
"Social Distancing is a privilege. It means you live in a house large enough
to practice it. Hand washing is a privilege too. It means you have access to running water.
Hand Sanitisers are a privilege. It means you have money to buy them.
Lockdowns are a privilege. It means you can afford to be at home.
Most of the ways to ward the Corona off are accessible only to the affluent.
In essence, a disease that was spread by the rich as they flew around the globe
will now kill millions of the poor.
All of us who are practising social distancing and have imposed a lockdown on
ourselves must appreciate how privileged we are.
Many Indians won't be able to do any of this."

*** Latour
About Latour: "The graduate student reader of his work is forced to ask: Are the
politics between people - men and women, colonizer and colonized, elite managers
and rank-and-file workers - the same as the politics between humans and door
hinges?"

*** The Morgue is filled with busy people
The Morgue is filled with people who had busy schedules and were planning to
start living their best lives in a few years. Whatever it is you want to do,
do-it-now. You don't know how much time you have left.

*** Billionaires
"If ... billionaires had simply been content with staying at their 2016
wealth, and had given their one-year gains to the world’s poorest people
instead, then extreme poverty would have been eradicated." GET IT DONE.
[[https://causeandeffect.fm/oxfams-excellent-inequality-report-1822314028][https://causeandeffect.fm/oxfams-excellent-inequality-report-1822314028]]

*** We expect women to work like they don't have children
"we expect women to work like they don't have children, and raise children as if
they don't work."

*** Working with a laptop
"Never have your laptop plugged in while you work. Charge it to 100%, and
when it's about to die, that's when it's time to take a break."

*** People in power and data
"those in power control the means of gathering and distributing data"
https://urbanomnibus.net/2019/09/to-stop-displacement-disclose-the-data/


*** Dystopia is a white people word
"Dystopia is a white people word for 'What if all that shit happened TO US?'"

*** When an oppressed group speaks, We need to Listen.
I'll say it again.
Men don't get to decide what's misogynistic.
Straight people don't get t odecide what's homophobic.
White people don't get to decide what's racist.
Christians don't get to decide what's antsemitic or Islamophobic.
Abled and neurotypical people don't get to decide what's ableist.
Cis people don't get to decide what's transphobic.
Rich people don't get to decide what's classist.
Bottom line: people in positions of privilege don't get to define oppression. If we allow them
to do so, minorities and disadvantaged populations lose their voice and their interests get pushed aside as
unsubstantiated demands.
Activism loses momentum and our society becomes increasingly regressive.

When an oppressed group speaks, we need to listen.
Thats's how we create a progressive society: a community that recognises the need for and actively supports positive change.
*** On Genocide Deniers
This brings us back to the question of why genocide-deniers will devote so much
time to writing texts that cannot withstand scholarly scrutiny, and that merely
succeed in covering the deniers with infamy in the eyes of everyone outside
their tiny denialist circle.  These are the activities of a sect that needs its
own mythes to feed its followers so as to perpetuate itself. Bosnia and Rwanda
are not treated as subjects for genuine scholarly enquiry, but merely episodes
to be incorporated into the mythical narrative.  So long as the sect's followers
continue to imbibe the myths, it does not matter if the rest of the world
despises the sect and its myths.

In this context, the task of genuine genocide scholars is not to struggle to
de-programme the sect's followers - a generally impossible task - but merely to
ensure that their poison is kept out of mainstream discourse on genocide.

*** Tips for reading
If you're having trouble keeping up with the reading for this history class,
here are some tips that may help you read faster and retain more:

1) Read for argument. (write it down).
2) Figure out what details are important by seeing if they align (or strongly conflict) with the argument.
3) Be able to formulate your own response to the reading/argument, using evidence from the text. (you don't have to agree
   with the argument but you should be able to give some specifics to show why you do or don't).
4) Have a sense of what the most important or interesting new thing you learned was. (This can help you see what you've accomplished and helps with memory/retention).

Lastly, reading dense material is a process and you'll get better at it.
Remember too that the class discussion is part of the process that will help you truly "get" what you read, even if you're
still confused right after you finish reading a piece.
*** Hurricane Gentrification
1) Segregate people into flood zones
2) Raise prices so people can't escape
3) Threaten people with deportation and arrest for seeking shelter
4) Ridicule "idiots who stayed" on TV
5) Make a show of pithy relief donations to avoid conversation on wealth inequality
6) Force residents of destroyed poor neighborhoods to move
7) Redevelop, flip properties at a mark up to richer, Whiter residents.
*** Variation on Niemoller's First They Came
I Keep seeing variations on "First they came for the Muslims",
and it bugs me a bit bc i feel like its more like
"First they came for the Black children, and we let them lock them up.
Then they came for the unions, and we dissolved them.
Then they came for the intellectuals and secularists, and we kicked them out of the government.
Then they came for the muslims and we were finally like whoaaaahhhh real nazi shit".
** "daniel"
"I just realized i'd totally play twine games about disillusioned hardy boys.
The mystery of Whoe Ate My Lunch at the Factory.
The Curse of Misreporting Taxes That One Time."

** Facebook
As we've said many times, the documents Six4Three gathered for their baseless case are only part
of the story and are presented in a way that is very misleading without additional context.
We stand by the platform changes we made in 2015 to stop a person from sharing their
friends' data with developers.
Like any business, we had many of internal conversations about the various ways we could build a
sustainable business model for our platform.
But the facts are clear: We've never sold people's data.
** Girl who kissed Timothee Chalamet
“Everyone is asking me if | was kissing Timothée
Chalamet at Coachella, and that is a good
question,” her statement continues. “But a great
question would be asking our world leaders why
the Earth is now losing 1.2 trillion tons of ice each
year due to global warming and why climate crisis
reform has been completely ineffective.”
** On Complex Systems
To Stewart:
A by-the-by: I've noticed that all these complex systems generators (such as 'Life' and 'Boids' (the flocking one) and "The Great Learning') have something in common - just three rules for each.
 And these three rules seem to share a certain similarity of relationship: one rule generates, another reduces, another maintains.
 I suppose it's obvious, really, but perhaps it's not trivial to wonder if those three conditions are all you need to specify in order to create a complex system generator (and then to wonder how those are actually being expressed in complex systems we see around us).
** On Nasa Astronauts
In the Apollo years, NASA sent military test
pilots into space, not poets or preachers;
they came back in possession of
extraordinary knowledge that, by dint of
personality or professional inclination, they
seemed helpless to communicate. As the
Gemini and Apollo astronaut Michael
Collins once put it, “It was not within our
ken to share emotions or to utter
extraneous information.” Asked what it was
like to go to the moon, Apollo 12’s Pete
Conrad replied: “Super! Really enjoyed it!”
** Racial oppression enabled land exploitation on a massive scale.
Racial oppression enabled land exploitation on a massive scale.
During slavery, black slaves pulled profit from the dirt but had no claim to the land.
After the Civil War, freed slaves saw in landownership the possibility of true liberation, but during Reconstruction wealthy whites maintained a virtual monopoly on the soil as lands seized from or abandoned by Confederates were restored to their original owners.
Returning to plantations as sharecroppers, black families descended into a cycle of subsistence farming and debt, while white planters continued to grow rich.
The slave shacks stood, and so did the plantation mansions.

In the early decades of the twentieth century, African-American families seeking freedom and good jobs participated in the Great Migration, moving en masse from the rural South to cities like Chicago, Philadelphia, and Milwaukee.
When they arrived in those cities, they were crowded into urban ghettos, and the vast majority depended on landlords for housing.
Ghetto landlords had a segregated and captive tenant base and had nothing to gain by improving their run-down houses.
They began dividing their properties into small "kitchenette" units, throwing up so many plywood walls their apartments resembled "rabbit warrens".
Many houses lacked heating and complete plumbing.
So black families cooked and ate in winter coats and relieved themselves in outhouses or homemade toilets.
They came to know well the sound of the tuberculosis cough.
In 1930, the death rate for Milwaukee's blacks was nearly 60 percent higher than the citywide rate, due in large part to poor housing conditions.
For the first time in the history of America, New Deal policies made homeownership a real possibility for white families.

...

Maybe it began in the late fifteenth century, the weaponry of war to blame.
With the invention of the iron cannonball, cities could no longer rely on moats and modest ramparts to fend off attack.
Complicated systems of defense had to be constructed and cities had to grow vertically behind high walls. Old Geneva and Paris saw tenements climb six stories.
Edinburgh boasted of tenements twice as high.
While agrarian families were driven from the land to increasingly congested cities, the competition for space drove up land values and rents.
Urban landlords quickly realized that piles of money could be made by creating slums: "maximum profits came, not from providing first-class accommodations for those who could well afford them... but from crowded slum accommodations, for those whose pennies were scarcer than the rich man's pounds."
Beginning in the sixteenth century, slum housing would be reserved not only for outcasts, beggars, and thieves but for a large segment of the population.

During its rapid period of urbanization, America imported this model.
Colonial proprietors adopted the institutions and laws of England's landed gentry, including the doctrine of absolute liability for rent, which held tenants unequivocally responsible for payments even in the event of fire or flood.
Throughout the eighteenth and nineteenth centuries, America's poor lived in cellars, attics, cattle sheds, and windowless rooms that held multiple families.
Some slums were cut off from basic municipal services and local wells; so families begged for water in other parts of town.
Rents continued to rise as living conditions deteriorated.
Soon, many families could not afford their housing.

** Racism
"He yelled 'Get out of my country', withnesses say, and then shot 2 men from India, killing one"

** Risking the Soverignty of our own stories.


Risking the sovereignty of our own stories.
What if the practice of referencing, sourcing, and crediting is always
bursting with intellectual life and takes us outside ourselves?
What if we read outside ourselves not for ourselves but to actively unknow ourselves,
to unhinge, and thus come to know each other, intellectually, inside and outside the academy,
as collaborators of collective and generous and capacious stories?
Unknowing ourselves.

The unhinging opens up a different conversation about why we
do what we do, here, in this place, that despises us—not focusing on
reparation of the self, alone, but instead sharing information and stories and
resources to build the capacity for social change.

Alternative outcomes.

The unhinging, unknowing ourselves, opens up learning processes that
are uninterested in a self that is economized by citations.
And still, displacing the self, unknowing who we are, is awful:
it is indeterminate and unpredictable and lonely.
Togetherness can be difficult and lonely, too.

** schools and bombers
It will be a great day when our schools get all the money they need and the
air force has to hold a bake sale to buy a bomber.
** Speaking with the young on hitler
For us to speak with the young becomes ever more difficult.
We see it as a duty and, at the same time, as a risk: the risk of appearing anachronistic, of not being listened to.
We must be listened to: above and beyond our personal experiences, we have collectively witnessed a fundamental, unexpected event, fundamental precisely because unexpected, not foreseen by anyone.
It took place in the teeth of all forecasts; it happened in Europe; incredibly, it happened that an entire civilized people, just issued from the fervid cultural flowering of Weimar, followed a buffoon whose figure today inspires laughter, and yet Adolf Hitler wa obeyed and his praises were sung right up to the catastrophe.
It happened, therefore it can happen again: this i the core of what we have to say.
** The IRA
(now an inspirational facebook quote)
We only need to be lucky once.
You need to be lucky every time.
** The Modes of categorisation and bureaucracy
The modes of categorisation and bureaucracy which allowed colonial powers
to efficiently extract resources from the colonised gave rise to the technology
which powers video games. We design games in the afterlife of empire, with
tools that have been used to subjugate and annihilate. The pleasures of
naming, categorisation and collecting are deeply embedded into the
normative design frameworks of the video game. Management sims and
Tycoon-style games are about the effective bureaucratic deployment of
resources.

Even when games turn away from designs of violent domination
they often replicate other imperialist pleasures: the museum, the explorer, the
merchant, the scientist, the bureaucrat. Assassins Creed: Origins
demonstrates this beautifully: the enemies can be turned off, and the
gorgeously designed and imagined spaces turned into a virtual museum,
complete with tours. We can switch between the battleground and the
museum with an airy gesture, revealing them both as connected imperial
modes of play. Underneath the cobblestones, not the beach — but the
playground.
** Unfortuate description of suspects
Casey White stands 6 feet 9 inches and weighs approximately 330 pounds. He has brown hair and hazel
eyes. He should be considered armed and dangerous.

Vicky White is 5 feet 5 inches and weighs approximately 145 pounds. She has blond hair and brown eyes
and reportedly has a waddling gait.
** Walter Plecker was an asshole

In the 1920s, he was registrar of Virginia’s Bureau of Vital Sta-
tistics, the state government office that controlled birth, death,
marriage, and divorce records (http://bkaprt.com/eia/00-01/). As
a frothing-at-the-mouth white supremacist, Plecker was terri-
fied of interracial marriage. Its very existence, he insisted, was
the result of poor categorization: white people were marrying
non-white people only because the government hadn’t labeled
them “correctly.”

Plecker decided that he could use bureaucracy to change this,
and he was right: all he had to do was relabel Virginia’s racial
categories, and racist laws took care of the rest. He reduced the
number of racial identity categories to just two, then altered and
enforced documentation to reflect his definitions.

This meant that a very small and specific group of people
were labeled white, and everyone who fell outside of Plecker’s
narrow view were not—and their lives changed accordingly.
The government saw them differently, identified them dif-
ferently, treated them differently. They no longer had access
to the same public spaces, the same schools, the same ser-
vices and safety nets afforded to white people. Marriages were
invalidated. Children were separated from parents. Virginians
lost agency over who they were—all because Walter Plecker
changed a label.

Changing a label is a design decision—one calculated, in this
case, to disenfranchise specific human beings.

Now, most of us don’t have Walter Plecker’s job. We are,
instead, designers, developers, copywriters, strategists. We
work on the web, and we may not think our work carries that
same weight.

I’m here to argue that it does. Whatever our role, we are
designers of information. Our choices alter the presentation
and flow of human knowledge. We control how people find,
understand, and use information in every facet of their lives.

We must be very, very careful.
** When I Write RPGS
When I Write RPGS, I don't just design them for gamers,
I design them for farmers.

Specifically, I design them for my younger brother - a western PA cattle farmer
who's never played an RPG I haven't handed him.
He doesn't have time for (or interest in) complex players' handbooks and he
doesn't own any "weird dice", but he's always one of the best players at my table
because he's a natural storyteller.
It's just a matter of getting the story started, adding some twitsts, and watching him be surprised by his own creativity.

Possible worlds is the culmination of that design ethos.
Pulling from years of design and publishing experience, I'vev written these games with
first-time, long-time, and diverse players in mind.
Each game in this collection is simple enough to be played with zero preparation
but robust enough to run hundreds of times and never get the same story twice
- all small enough to fit in your back pocket.
