#+TITLE: Author Quotes

* Top
** Dan Abnett
#+begin_quote Titanicus
Politics is just the feeding frenzy for power.
The possibility of annihilation doesn't stop that - in fact, it probably just makes it worse.
#+end_quote

#+begin_quote
It's all about data, you see? The Imperium is the greatest data-gathering institution in history.
A bureaucracy with sharp teeth.
#+end_quote

** David Foster Wallace
#+begin_quote
"Look, if the contemporary condition is hopelessly shitty, insipid,
materialistic, emotionally retarded, sadomasochistic, and stupid, then I (or any
writer) can get away with slapping together stories with characters who are
stupid, vapid, emotionally retarded, which is easy, because these sorts of
characters require no development. [...] If readers simply believe the world is
stupid and shallow and mean, then Ellis can write a mean shallow stupid novel
that becomes a mordant deadpan commentary on the badness of everything. Look
man, we'd probably most of us agree that these are dark times, and stupid ones,
but do we need fiction that does nothing but dramatize how dark and stupid
everything is? In dark times, the definition of good art would seem to be art
that locates and applies CPR to those elements of what's human and magical that
still live and glow despite the times' darkness. Really good fiction could have
as dark a worldview as it wished, but it'd find a way both to depict this world
and to illuminate the possibilities for being alive and human in it. Fiction's
about what it is to be a fucking human being. If you operate, which most of us
do, from the premise that there are things about the contemporary U.S. that make
it distinctively hard to be a real human being, then maybe half of fiction's job
is to dramatize what it is that makes it tough. The other half is to dramatize
the fact that we still are human beings, now. Or can be ... I just think that
fiction that isn't exploring what it means to be human today isn't art. We've
all got this literary' fiction that simply monotones that we're all becoming
less and less human, that presents characters without souls or love, characters
who really are exhaustively describable in terms of what brands of stuff they
wear, and we all buy the books and go like 'Golly, what a mordantly effective
commentary on contemporary materialism!'  But we already know U.S. culture is
materialistic. This diagnosis can be done in about two lines.  It doesn't engage
anybody. What's engaging and artistically real is, taking it as axiomatic that
the present is grotesquely materialistic, how is it that we as human beings
still have the capacity for joy, charity, genuine connections, for stuff that
doesn't have a price? And can these capacities be made to thrive? And if so,
how, and if not why not?"
#+end_quote

** David Sedaris
#+begin_quote
When you write humor, people think that you just record into a tape recorder and
then someone else transcribes your words. It doesn’t occur to them that you have
to choose this word over that word—and do so very carefully. I’m often asked in
interviews, “How long have you been a storyteller?” To me, that implies some
woman in bare feet who comes to the local library and tells stories. I just
cringe when people say that. Most people have no concept of writing, or what’s
involved with the process.
#+end_quote

#+begin_quote
"To put them in perspective, I think of being on an airplane.
The flight attendant comes down the aisle with her food cart and,
eventually, parks it beside my seat.
'Can I interest you in the chicken?' She Asks. 'Or would you prefer the
platter of shit with bits of broken glass in it?'

to be undecided in this election is to pause for a moment and then ask how the chicken is cooked."
#+end_quote

** John Scalzi                                     :intelligence:
#+begin_quote
The Failure mode of clever is asshole.
#+end_quote

** Neil Gaiman
#+begin_quote
It is a fool's prerogative to utter truths no one else will speak.
#+end_quote

*** Rules for Writing
#+begin_quote
1) Write
2) Put one word after another. Find the right word, put it down.
3) Finish what you're writing. Whatever you have to do to finish it, finish it.
4) Put it aside. Read it pretending you've never read it before. Show it to friends whose opinion you respect and who like the kind of thing that this is.
5) Remember: when people tell you something's wrong or doesn't work for them, they are almost always right. When they tell you exactly what they think is wrong and how to fix it, they are almost always wrong.
6) Fix it. Remember that, sooner of later, before it ever reaches perfection, you will have to let it go and move on and start to write the next thing. Perfection is like chasing the horizon. Keep moving.
7) Laugh at your own jokes.
8) The main rule of writing is that if you do it with enough assurance and confidence, you're allowed to do whatever you like. (That may be a rule for life as well as for writing. But it's definitely true for writing.) So write your story as it needs to be written. Write it honestly, and tell it as best you can. I'm not sure that there are any other rules. Not ones that matter.
#+end_quote

*** Sim city essay
#+begin_quote
Cities are not people. But, like people, cities have their own personalities: in some cases one city has many different personalities -- there are a dozen Londons, a crowd of different New Yorks.

A city is a collection of lives and buildings, and it has identity and personality. Cities exist in location, and in time.

There are good cities -- the ones that welcome you, that seem to care about you, that seem pleased you're in them. There are indifferent cities -- the ones that honestly don't care if you're there or not; cities with their own agendas, the ones that ignore people. There are cities gone bad, and there are places in otherwise healthy cities as rotten and maggoty as windfall apples. There are even cities that seem lost -- some, lacking a centre, feel like they would be happier being elsewhere, somewhere smaller, somewhere easier to understand.

Some cities spread, like cancers or B-movie slime monsters, devouring all in their way, absorbing towns and villages, swallowing boroughs and hamlets, transmuting into boundless conurbations. Other cities shrink -- once prosperous areas empty and fail: buildings empty, windows are boarded up, people leave, and sometimes they cannot even tell you why.

Occasionally I idle time away by wondering what cities would be like, were they people. Manhattan is, in my head, fast-talking, untrusting, well-dressed but unshaven. London is huge and confused. Paris is elegant and attractive, older than she looks. San Francisco is crazy, but harmless, and very friendly.

It's a foolish game: cities aren't people.

Cities exist in location, and they exist in time. Cities accumulate their personalities as time goes by. Manhattan remembers when it was unfashionable farmland. Athens remembers the days when there were those who considered themselves Athenians. There are cities that remember being villages. Other cities -- currently bland, devoid of personality -- are prepared to wait until they have history. Few cities are proud: they know that it's all too often a happy accident, a mere geographical fluke that they exist at all -- a wide harbour, a mountain pass, the confluence of two rivers.

At present, cities stay where they are.

For now cities sleep.

But there are rumblings. Things change. And what if, tomorrow, cities woke, and went walking? If Tokyo engulfed your town? If Vienna came striding over the hill toward you? If the city you inhabit today just upped and left, and you woke tomorrow wrapped in a thin blanket on an empty plain, where Detroit once stood, or Sydney, or Moscow?

Don't ever take a city for granted.

After all, it is bigger than you are; it is older; and it has learned how to wait...
#+end_quote
- [[https://www.neilgaiman.com/Cool_Stuff/Essays/Essays_By_Neil/SIMCITY][Sim city essay]]

** Octavia Butler
#+begin_quote Octavia’s Brood, 2015
“Whenever we try to envision a world without war, without violence, without
prisons, without capitalism, we are engaging in speculative
fiction.” -Walidah Imarisha
#+end_quote

#+begin_quote
There’s no new world, my friend, no New seas, no other planets, nowhere to
flee. You’re tied in a knot you can never undo when you realize Earth is a
starship too and it's the only one any human will EVER have until the heat
death of the universe…
#+end_quote

#+begin_quote
institutions no longer working except to collect taxes and fees and to arrest people [and] exploit their labor
#+end_quote

#+begin_quote
You don't start out writing good stuff. You start out writing crap and thinking its good stuff, and
then gradually get better at it.
Thats why I say one of the most valuable traits is persistence.
#+end_quote
