#+TITLE: Social Media Quotes
* Twitter
** @alexandraerin
If Handler's most famous work has any lessons to teach us, I think they would include the fact
that one need not be a card-carrying villain to do great harm.

The kind of moral complexity alluded to in the thread does not consist of
"This person is my friend, and has done great things, so he can't have done anything so bad"
That is the opposite of moral complexity. It's moral reductionism.

** @alexhern                                     :twitter:
“The incentive under capitalism is to use robots for everything except hard
wear-and-tear work, because if you wear out your robot, you have to pay to fix
it, but if you wear out your person, the NHS pays to fix them.”
** @AliceAvizandum
Every videogame has a level where you infiltrate a fancy masquerade party but nobody has the guts to make a whole game of that.

** @alliebland                                   :race:technology:twitter:
"Then Google Maps was like, 'turn right on Malcolm Ten Boulevard' and I knew there were no
black engineers working there".
** @amybphd                                      :gaslighting:twitter:
I needed the reminder that gaslighting is less about truth than it is about
control. When someone repeatedly tells you 1+1=3, they're not looking for
your help with math.
** @AnarchBooty
Eugenics by bureaucracy
(in reply to propublica story "In San Francisco, Hundreds of Homes for the Homeless Sit Vacant)
** @AsimCP
"Representation is not a solution to problems we see. Institutionalised
racism within the police doesn’t get solved by adding more black officers to
the force"
** @blackleftaf                                  :twitter:white_supremacy:
White supremacy is equal parts petty, absurd, and violent.
** @BlkHistStudies                               :twitter:
The grave is full of dreams, unfulfilled promises, inventions,
business plans, etc. You better start living NOW.
** @chouxsalax and @alt254                       :twitter:
 The Greatest trick the videogame industry ever pulled was convincing the world that videogames were games in the first place.
 Unlike traditional games in which voluntary rules are consciously chosen to further constrain
 or interpret the physical properties of dice and cards, balls and bats, or track and field,
 videogames conflate the rulse of a game with the mechanics of the equipment.
- Metagaming
** @DaltonPD
DPD on scene at report of shot or shots fired at Dalton High. NO CHILDREN ARE INJURED OR IN DANGER.

There is a barricaded subject in a classroom. It is believed to be a teacher.

PARENTS DO NOT COME TO DALTON HIGH.

Students will be taken to the NE GA Trade Center. Parents should go there.

Repeat: no children hurt, no children in danger.

** @davidcapello                                 :design:twitter:
The best measure to check the complexity of an UI is the number of steps you
have to do to create a tutorial about it.

** @dlldlldlldll                                 :twitter:writing:
Start a blog and start writing my friend. Doesn’t matter if
no one sees it, helps you improve your craft and comms skills... and then when
an opportunity (like @Gaohmee looking for good stuff) pops up, you’re ready to
go!
** @DocDre
From this epistemological standpoint? Ain't no good foundation for AI Models.
They inherited the interpretive weakness of info science,
the anti-humanist theoretical disposition of CS,
and a modernity's desire to extract and control.

Also: They antiblack AF.
** @dril                                         :twitter:
The wise man bowed his head solemnly and spoke:
"Theres actually zero difference between good & bad things. you imbecile. you fucking moron."
** @ebthen
I'm autistic. I accept miscommunication as a fact of life. Try it Sometime.

** Elon Musk                                     :stupidity:
Marx was a capitalist. He even wrote a book about it.

** @FedGlos
Chair of Gloucestershire Police Federation.
(March 27 2021)
Policing by consent is a general principle not duty.
Peaceful protest is a qualified not absolute right, has limits when it infringes
on rights of others.
The law includes the current prohibition on public gatherings.
And technically we're crown servants not public servants.

** @feministabulous
(Elizabeth Plank)

"You know you live in the patriarchy when writing about fashion disqualifies you
from writing about politics but writing about sports doesn't."
"Never believe that anti-Semites are completely unaware of the absurdity of their replies.
They know that their remarks are frivolous, open to challenge.
But they are amusing themselves, for it is their adversary who is obliged to use words responsibly, since he believes in words.
The anti-Semites have the right to play.
They even like to play with discourse for, by giving ridiculous reasons, they discredit the seriousness of their interlocutors.
They delight in acting in bad faith, since they seek not to persuade by sound argument but to intimidate and disconcert.
If you press them too closely, they will abruptly fall silent, loftily indicating by some phrase that the time for argument is past."

** @generativist
I remain committed to my belief that user-controlled BYOAlgo content-moderation would substantially reduce the TAM of web-scale assholes.

*** The Real Unix Philosophy (tm)
QT: @kevinbaker : It's all the ingredients I had: quinoa, eggs, butter, and like half a cup of buffalo sauce.
This is the most fucked up thing i could do with it.

*** A lot of us out here doing it for free.
Who is the real clown?
QT: @NeerajKA : CEOs should hire court jesters to keep them humble, ridicule bad ideas, and generally relay information others dare not.

*** If I could pick one magic wand wave event,
I'd rather them act as marketplaces for #BYOAlgo than open source their primary one.
Cat-and-mouse games are easier with a mono-culture (of incentives);
heterogeneity for great good

@cdixon: Search Engines should open source their ranking algorithms.

*** Simulations within simulations
"but how would they sample the weird edges and not all the others too?"

Simulations within simulations, shared little stories as cheap training data for the agents,
with resulting attention as novelty estimate...

QT: @generativist : they wouldn't simulate historical reproductions. they'd simulate historically plausible sample paths drawn from the exciting edges...

R: @generativist: like most of the french fucks, Baudrillard has slowly gone from "annoying writing style" to "lmao okay that's cool" to "shit wait no what is happening?" over time

** @Glinner
18/05/2019
If your civil rights movement opposes data and peer reviewed science, it's not a civil rights movement,
it's a cult.

** @hypervisible                                 :empathy:racism:twitter:
Computational tools aren't going to make people recognize our humanity.
** @itsmaddiebee
some of y'all don't understand that resistance isn't about behaving in a way the systems find acceptable

ask yourself "if my resistance is being deemed acceptable, is it really resistance?"
no change has ever come without a little good trouble.
** Jason Rohrer
(Jan 23, 2021)
Mr President: Your message of Unity and Healing was heart-felt, but there
are 74M lost souls.
If we really care about healing, they need a big olive branch.
Simple and obvious gestures:
1) Pardon Trump, so we can ALL move on.
2) Promise to complete their wall.
@POTUS @JoeBiden

** @jessejanderson
My behavior may seem erratic to some, but that's because rationality has rarely served me well.

** J.K. Rowling
I've ignored porn tweeted at children.

** @JPLeBreton                                   :game_design:twitter:
[[https://gist.github.com/JPLeBreton/cef18e516047db06df8d7f41bced8a7e][Against Coercion: A Game Design Manifesto]]
let players wonder about things and trust them to find answers.

connect players with patterns they find intrinsically fulfilling.

never treat a number going up as an inherently positive or meaningful event.

teach respect for the autonomy and boundaries of all things.

posit alternatives to fantasies of accumulation and extraction.

do not think of emotional responses as something you extract from players.

produce and distribute ethically.

aspire to more than escape.
** @jpwarren
"Computers yelling Numberwang at each other" is my absolute favourite description of blockchain.
** @jshelat1
Me: teach Anne Lamott's "Shitty First Drafts" almost every semester and tell students, "All drafts are shitty the first time, and even the second or third time. It's part of the process! Embrace it!"

Also me: "Wow, if this first draft isn't perfect, I'm gonna hate myself."
https://twitter.com/jshelat1/status/1428012635237326855
** @kevinbaker
This somehow explains everything about this site:
@BaudrillardUSA:
The slightest vibration in a statistical model,
the tiniest whim of a compuare are enough to bathe some piece of abnormal behaviour,
however banal, in a fleeting glow of fame.

(crossed out: A CPU is literally a rock that we tricked into thinking)
Programming is literally when a rock has tricked you into typing.
Coding is a brutal 24/7 job where you spend all day getting owned by electric sand.
** @KHandozo                                     :activism:twitter:
Years of "gUns DoN'T kiLl PEoPle" rhetoric and suddenly every weapon cops use against civilians is animate.

The act of being visibly yourself becomes activism to people who
oppose your existence.
** @lillydancyger

I don't care that much about wrinkles
and gray hair, I'm more worried about
keeping my worldview flexible
enough that when I'm older I don't
condescendingly tell young people
to play by the rules that worked in my
day, with no concern for whether or
not those rules still apply
** @lizardengland
6/19/17
Belief: In Scribblenauts the objects were all data driven & relied on inheritances, systems.

Reality: hand authored 1 by 1 & lots of crunch.

The belief that it's all systems lets players interpret more intelligence to the game than really exists.
"Mythmaking" perhaps.

** @LolGOP
"When they say pot is not legal in ____, they mean it's even legal for minorities now."
** @LukewSavage
6/8/20
Adolph Reed Jr. once remarked that liberals don't really believe in politics anymore,
just in "bearing withness to suffering."
I think about that a lot.
** @MaartenenvSmeden
Before you develop a clinical prediction model, ask:
once finalized, do I really want and expect it to be successfully validated and implemented in patient care?
If no, why do it at all?
** @mathbabedotorg                               :twitter:
A white-shoe law firm or an exclusive prep school will lean far more on recommendations
and face-to-face interviews than will a fast-food chain or a cash-strapped urban school district.

The privileged, we'll see time and again, are processed more by people, the masses by machines.
- Weapons of Math Destruction
** @Mcclure111
*** Art
What if art criticism was banned unless it came in the form of more art.
Want to write a blog post about this video game? No.
You have to make it as a small twine game. Your album review has to be read over a beatnik bass line.
Poor aesthetics wholly forgiven but you have to do it.

- Mike bithell, replying:
  The Chains would be glorious:

  "Hi, I'm Mike, and this is my card game critique of Sarah's twine game
  brazenly celebrating Dan's mashup of Tetris and Dominoes inspired by his mild
  disappointment with Gears of War 4".

*** Time
(tweeted 2/20/18)
2015: My timeline is full of people gofundme-ing their medical care and I feel horrified.
2018: My timeline is full of people gofundme-ing the medical care for their school shooting injuries and I feel horrified.
What will 2021 feel like?

** @nfinitefreetime
- @techreview (MIT Tech Review)
  Ready for a world in which a $50 DNA test can predict your odds
  of earning a PhD or forecast which toddler gets intoa selective preschool?
- @nfinitefreetime
  You can do this already with a ZIP code.
** @OmanReagan                                   :facebook:institutional_power:surveillance:twitter:
"Facebook is not only a tool for social networking and activism, it is also a
U.S.-based, corporate, for-profit, data-mining enterprise and its potential
for use in resisting institutional power must be considered in that context."

** @pinboard
Aug 5, 2016.
The programmer's credo: we do thse things not because they are easy,
but because we thought they were going to be easy.
** @prchovanec                                   :policy:twitter:
There are two ways of making policy:
- tell yourself a story about what will happen and hope that it does
- rigorously ask yourself what could go wrong and have some idea what you might do if it does

  Guess which happens more often?
** @rajiinio
28/06/21
We can't keep regulating AI as if it.. works.

Most policy interventions start with the assumption that the technology lives up
to its claims of performance but policymakers & critical scholars
need to stop falling for the corporate hype and should
scrutinize these claims more.

** @RonPaul
(Ron Paul, 7/2/18)

"Are you stunned by what has become of American Culture?
Well, it's not an accident. You've probably heard of 'Cultural Marxism,'
but do you know what it means? ... More here: [facebook link]
[image of an edited ben garrison cartoon, depicting racial stereotypes
of Jewish, Asian, South American and Black People punching the US]"

** @rooshv                                       :bigotry:
4/19/19
When a female gets a tattoo, she is giving a permanent oath of fealty to the oligarchs and their hired managers.
Her mind is controlled by their Satanic inversions, her body destined to be used and abused in exchange for
pleasure and power. Her tattoo is the mark of the beast.

** @SatansJacuzzi                                :STEM:twitter:
"Stem w/o the humanities is just a raytheon training program".
** @shaun_vids                                   :twitter:
billionaires should be desperate to be taxed. something is going to happen to
them, and 'taxed' is the best verb they can hope for at this point
** @skulldelacreme (@dirtbagboyfren)             :twitter:
You can't force people to live under capitalism which equates your worth to how
much you own, then not understand property damage as protest.
** @steam_umm                                    :twitter:
friendly reminder in times of uncertainty and misinformation: anecdotes are
not data. (good) data is carefully measured and collected information based
on a range of subject-dependent factors, including, but not limited to,
controlled variables, meta-analysis, and randomization
outliers attempting to counter global consensus around this pandemic with
amateur reporting or unverified sourcing are not collecting data. breaking
news stories that only relay initial findings of an event are not
collecting data. we have to be careful in our media consumption
it can be difficult to know what to believe in a time when institutional
trust is diminished and the gatekeepers of information have been
dismantled, but it's more crucial now than ever before to follow a range
of credentialed sources for both breaking news and data collection
all we currently have are limited and evolving metrics that experts are
deciphering and acting upon immediately to the best of their ability. this
terrain leaves many openings for opportunists and charismatic manipulators
to lead people astray by exploiting what they want to hear
breaking news and storytelling will always be spun with interpretive bias
from different media perspectives, but data is a science that can't be
replaced by one-off anecdotes. try to remember this to avoid fear-based
sensationalism or conspiracy theories taking over your mind
you can maintain independent, critical thinking toward institutions
without dipping into fringe conspiracies that get jumpstarted by
individual anecdotes being virally spread as data. it's not easy, but it's
necessary to keep any semblance of responsible online information flow
we're a frozen meat brand posting ads inevitably made to misdirect people
and generate sales, so this is peak irony, but hey we live in a society so
please make informed decisions to the best of your ability and don't let
anecdotes dictate your worldview ok steak-umm bless
if you thought this thread was useful, we posted another one recently
touching on small, simple ways that the average person can take on the
daily cultural challenges of this pandemic without demonizing or
otherizing our neighbors
** @stone_prof
Today I was puzzling through a work problem and said to myself "Damn, it takes
so much work to know stuff" which I guess sums up the whole scholarly endeavor.

 - https://twitter.com/stone_prof/status/1425556436495609870
** @Theophite                                    :bitcoin:twitter:
On Bitcoin: "Imagine if keeping your car idling 24/7 produced solved sudokus you could trade for heroin."
** @toniasutherland                              :twitter:
"Too often archivists recreate harmful descriptive (and other professional)
practices, simply via uncritical transfer from analog to digital formats"
[[http://doi.org/10.33137/ijidi.v5i1.34669]]
** @Ugarles                                      :twitter:
Conservatives are very big on cost/benefit analysis when it comes to
regulating for clean air and water but find it morally repugnant when you
mention it regarding wars of choice.

"these are the assumptions. it's where you hide your preferred outcome."
** @uk_domain_names
(Edwin Hayward)
Here's the truth about Brexit,
the "punishment" some people claim the EU wants to inflict on us,
the full horrific consequences of no deal,
and the dangers lurking behind any deal we reach.
Buckle in, i'ts pretty long.
Better to be thorough than to leave anything out.

** @Vanessa_ABee                                 :GOP:abortion:reproductive_rights:twitter:
"Never too young to date, always too young to choose abortion" - ancient GOP Proverb
** @XLNB
15 Aug 2017

Racists: "George Washington was a slave owner! Should we stop praising him too?"
Black People: "Yes."
Racists: "..."
Black People: [unimpressed face of Black Guy from the Office]
** @zoombapup
(Phil Carlisle, 6/28/16)
I Really love the potential games have to show us other worlds and other ways of being,
but that notion is commercially unpopular sadly.

** @ztsamudzi                                    :twitter:
Maxim of her friend Jeff:
“There is a correlation between a man’s sensual ineptitude and his
ruthlessness.”
* Tumblr
** TheMightyGlamazon
(tumblr)
I enforce federal worker health and safety and pollution regulations.

When I was learning my trade, when my classmates and I were having a chuckle of the "well duh" level of specificity
written into the Code of Federal Regulations (try "no hazardous material shall be stored in crew berthing" on for size).
I will never forget the silence that followed when our instructor spoke these words:

"Your regulations are written in blood."

These regulations were not written on a whim. They were written because someone thought they could cut costs by
storing however many more pounds of radioactive, toxic, carcinogenic, or whatever else material in the same rooms
where the human beings they paid to transport those materials slept, and then did that. Because no one was telling them not to.

They were written because people died. Horrifically. Because unregulated capitalism values profit over human life and suffering.

Can I say it again, for those not paying attention?

Unregulated capitalism values profit over human life and suffering.

* Facebook
** Adam Protextor                                :fight_club:male_fragility:satire:
 "When people call you a "snowflake" just remember they're quoting Fight Club, a satire written by a gay man about how male fragility causes men to destroy themselves, resent society, and become radicalized, and that Tyler Durden isn't the hero but a personification of the main character's mental illness, and that his "snowflake" speech is a dig at how fascists use dehumanizing language to breed loyalty from insecure people.

So basically people who say "snowflake" as an insult are quoting a domestic terrorist who blows up skyscrapers because he's insecure about how good he is in bed."

* Memes
** Cats
Do not meddle in the affairs of Cats
for they are subtle and will piss on your computer.
** Glados
Well done. Here come the test results: "You are a horrible person."
That's what it says.
We werent even testing for that.
** Ronald Reagan (Humourous)
The second amendment doesn't exist for hunting. It exists so undocumented immgrants can shoot ICE agents in self defense.
* Instagram
** feministastic
Expecting marginalized peoples to disregard their own emotions
to calmly educate you is the epitome of entitlement.
* Reddit
** RhinelandBasterd
Reddit Post on r/FullCommunism

"This game is too damn hard and I can't get past the first level.
The enemis won't listo to my reasoned discourse on why their ideology is flawed
and just shoot me to death.
I have a lot of weapons at my disposal, but killing the nazis would make me as bad as them.
Does anyone have links to a walkthrough that would allow me to keep the moral high ground?"
