#+TITLE: Terry Pratchett
https://en.m.wikiquote.org/wiki/Discworld

* Collecting books
#+begin_quote Good Omens
“Aziraphale collected books.
 If he were totally honest with himself he would have to have admitted that his bookshop was simply somewhere to store them.
 He was not unusual in this.
 In order to maintain his cover as a typical second-hand book seller, he used every means short of actual physical violence to prevent customers from making a purchase.
 Unpleasant damp smells, glowering looks, erratic opening hours - he was incredibly good at it. ”
#+end_quote

* Death
 #+begin_quote
 “In theory it was, around now, Literature. Susan hated Literature. She'd much prefer to read a good book.”
 #+end_quote

** On Cats
#+begin_quote
"I meant," said Ipslore bitterly, "what is there in this world that truly makes living worthwhile?"
Death thought about it.
"Cats," he said eventually. "Cats are nice."
#+end_quote

** Asking Questions
#+begin_quote
“Albert grunted. "Do you know what happens to lads who ask too many questions?"
Mort thought for a moment.
"No," he said eventually, "what?"
There was silence.
Then Albert straightened up and said, "Damned if I know. Probably they get answers, and serve 'em right.”
#+end_quote

** Human Lies
#+begin_quote
“All right," said Susan. "I'm not stupid. You're saying humans need... fantasies to make life bearable."

REALLY? AS IF IT WAS SOME KIND OF PINK PILL? NO. HUMANS NEED FANTASY TO BE HUMAN. TO BE THE PLACE WHERE THE FALLING ANGEL MEETS THE RISING APE.

"Tooth fairies? Hogfathers? Little—"

YES. AS PRACTICE. YOU HAVE TO START OUT LEARNING TO BELIEVE THE LITTLE LIES.

"So we can believe the big ones?"

YES. JUSTICE. MERCY. DUTY. THAT SORT OF THING.

"They're not the same at all!"

YOU THINK SO? THEN TAKE THE UNIVERSE AND GRIND IT DOWN TO THE FINEST POWDER AND SIEVE IT THROUGH THE FINEST SIEVE AND THEN SHOW ME ONE ATOM OF JUSTICE, ONE MOLECULE OF MERCY. AND YET—Death waved a hand. AND YET YOU ACT AS IF THERE IS SOME IDEAL ORDER IN THE WORLD, AS IF THERE IS SOME...SOME RIGHTNESS IN THE UNIVERSE BY WHICH IT MAY BE JUDGED.

"Yes, but people have got to believe that, or what's the point—"

MY POINT EXACTLY.”
#+end_quote

** Alcohol
#+begin_quote
“Death: "THERE ARE BETTER THINGS IN THE WORLD THAN ALCOHOL, ALBERT."
Albert: "Oh, yes, sir. But alcohol sort of compensates for not getting them.”
#+end_quote

* Vimes
#+begin_quote
“Vimes's lack of interest in other people's children was limitless.”
#+end_quote

#+begin_quote
“Once you had a good excuse, you opened the door to bad excuses.”
#+end_quote

** Torture
#+begin_quote
Yeah, all right, but everyone knows they torture people," mumbled Sam.
"Do they?" said Vimes. "Then why doesn't anyone do anything about it?"
"'cos they torture people.”
#+end_quote

** Go Postal, with Precision
#+begin_quote
“The important thing is not to shout at this point, Vimes told himself. Do
not…what do they call it…go postal? Treat this as a learning exercise. Find out
why the world is not as you thought it was. Assemble the facts, digest the
information, consider the implications. THEN go postal. But with precision.”
#+end_quote

** Boots theory of socioeconomic unfairness.
#+begin_quote Men At Arms
“The reason that the rich were so rich, Vimes reasoned, was because they managed to spend less money.

Take boots, for example. He earned thirty-eight dollars a month plus allowances. A really good pair of leather boots cost fifty dollars. But an affordable pair of boots, which were sort of OK for a season or two and then leaked like hell when the cardboard gave out, cost about ten dollars. Those were the kind of boots Vimes always bought, and wore until the soles were so thin that he could tell where he was in Ankh-Morpork on a foggy night by the feel of the cobbles.

But the thing was that good boots lasted for years and years. A man who could afford fifty dollars had a pair of boots that'd still be keeping his feet dry in ten years' time, while the poor man who could only afford cheap boots would have spent a hundred dollars on boots in the same time and would still have wet feet.

This was the Captain Samuel Vimes 'Boots' theory of socioeconomic unfairness.”
#+end_quote

** Vimes Morality.
#+begin_quote
“There was no universe, anywhere, where a Sam Vimes would give in on this,
because if he did then he wouldn't be sam vimes anymore.”
#+end_quote

** Policing
#+begin_quote
“You took an oath to uphold the law and defend the citizens without fear or favor," said Vimes.
 "And to protect the innocent. That's all they put in.
 Maybe they thought those were the important things.
 Nothing in there about orders, even from me.
 You're an officer of the law, not a soldier of the government.”
#+end_quote

** Freedom, Truth, Justice, and a Hard Boiled Egg.
#+begin_quote Night Watch
“You'd like Freedom, Truth, and Justice, wouldn't you, Comrade Sergeant?' said Reg encouragingly.
'I'd like a hard-boiled egg,' said Vimes, shaking the match out.
There was some nervous laughter, but Reg looked offended.
'In the circumstances, Sergeant, I think we should set our sights a little higher--'
'Well, yes, we could,' said Vimes, coming down the steps.
He glanced at the sheets of papers in front of Reg.
The man cared. He really did. And he was serious. He really was.
'But...well, Reg, tomorrow the sun will come up again, and I'm pretty sure that whatever happens we won't have found Freedom,
and there won't be a whole lot of Justice, and I'm damn sure we won't have found Truth.
But it's just possible that I might get a hard-boiled egg.”
#+end_quote

** Night Watch Oath
#+begin_quote
“I comma square bracket recruit's name square bracket comma do solemnly swear by
square bracket recruit's deity of choice square bracket to uphold the Laws and
Ordinances of the City of Ankh-Morpork comma serve the public truƒt comma and
defend the ƒubjects of his ƒtroke her bracket delete whichever is inappropriate
bracket Majeƒty bracket name of reigning monarch bracket without fear comma
favour comma or thought of perƒonal ƒafety semi-colon to purƒue evildoers and
protect the innocent comma comma laying down my life if neceƒsary in the cauƒe
of said duty comma so help me bracket aforeƒaid deity bracket full stop Gods
Save the King stroke Queen bracket delete whichever is inappropriate bracket
full stop.”
#+end_quote

** People thinking they are good
#+begin_quote
“I tell you, commander, it's true that some of the most terrible things in the
world are done by people who think, genuinely think, that they're doing it for
the best, especially if there is some god involved.”
#+end_quote

** Questions and Answers
#+begin_quote
“Not all questions are answered, commander, but fortunately some answers are
questioned.”
#+end_quote

** Everyone's done something wrong.
#+begin_quote
“He's bound to have done something,” Nobby repeated.

In this he was echoing the Patrician's view of crime and punishment. If there
was crime, there should be punishment. If the specific criminal should be
involved in the punishment process then this was a happy accident, but if not
then any criminal would do, and since everyone was undoubtedly guilty of
something, the net result was that, in general terms, justice was done.”
#+end_quote

** People in Charge
#+begin_quote
“One of the hardest lessons in young Sam's life had been finding out that the
people in charge weren't in charge. It had been finding out that governments
were not, on the whole, staffed by people who had a grip, and that plans were
what people made instead of thinking.”
#+end_quote

** Corporal Swing
#+begin_quote
“Swing, though, started in the wrong place. He didn't look around, and watch and
learn, and then say, 'This is how people are, how do we deal with it?' No, he
sat and thought: This is how the people ought to be, how do we change them?' And
that was a good enough thought for a priest but not for a copper, because
Swing's patient, pedantic way of operating had turned policing on its head.”
#+end_quote

** Everyday badness
#+begin_quote Guards Guards
“Down there - he said - are people who will follow any dragon, worship any god, ignore any inequity.
All out of a kind of humdrum, everyday badness.
Not the really high, creative loathsomeness of the great sinners, but a sort of mass-produced darkness of the soul.
Sin, you might say, without a trace of originality.
They accept evil not because they say yes, but because they don't say no.”
#+end_quote


** Policing and excuses.
#+begin_quote
And if you did it for a good reason, you'd do it for a bad one.
You couldn't say "we're the good guys" and do bad-guy things.
#+end_quote

** Shooting at people who weren't shooting back
#+begin_quote
"He asked you to shoot at people who weren't shooting back", growled Vimes, striding forward.

"They are throwing STRONES, Sarge", said Colon.

"So? Stay out of range. They'll get tired before we do".
#+end_quote

** on killing people
#+begin_quote
I'm not a natural killer! See this? See what it says?
I'm supposed to KEEP the peace, I am!
If I kill people to do it, I'm reading the wrong manual!
#+end_quote

** Orders
#+begin_quote
You couldn't say "I had orders."
You couldn't say "It's not fair."
No one was listening. There were no Words.
You owned yourself ...

Not 'Thou Shalt Not'.
Say 'I WILL NOT'.
#+end_quote

** Slumlords
#+begin_quote
“And, while it was regarded as pretty good evidence of criminality to be
living in a slum, for some reason owning a whole street of them merely got
you invited to the very best social occasions.”
#+end_quote

** Stealing humanity.
#+begin_quote
There were people who'd steal money from people. Fair enough. That was just theft.

But there were people who, with one easy word, would steal the humanity from people.
That was something else.
#+end_quote

** Human Nature
#+begin_quote
But we were dragons. We were supposed to be cruel, cunning, heartless and terrible.
But this much I can tell you, we never burned and tortured and ripped one another apart
and called it morality.
#+end_quote

** Vessels of Hatred
#+begin_quote
For the enemy is not Troll, not is it Dwarf,
but it is the baleful, the malign, the cowardly, the vessels of hatred,
those who do a bad thing and call it good.
#+end_quote


** When the rich take to crime
#+begin_quote
... but what should we do when the highborn and wealthy take to crime?
Indeed, if a poor man will spend a year in prison for stealing out of hunger,
how high would the gallows need to be to hang the rich man who breaks the law out of greed?
#+end_quote

** When the world needs policemen
#+begin_quote
There were times when the world did not need policemen,
because what it really did need was for somebody who knew what they were doing
to shut it all down and start it all up again so THIS time it could be done properly.
#+end_quote

** Patriotism
#+begin_quote
After the flurry of orders, he sat back and stared at the map. Some things at least made sense. All these
barricades looked inward. People were barricading themselves against the Palace and the center of the city. No
one would be bothered much about the outside world. If you had to take an outlying part of the city in those
circumstances, then the thing to do would be to go in via a gatehouse in the city wall. They might not be quite
so guarded as they ought to be.

“Tom?”

“Yes, Clive?”

“Have you ever sung the national anthem?”

“Oh, lots of times, sir.”

“T don’t mean officially.”

“You mean just to show I’m patriotic? Good gods, no. That would be a rather odd thing to do,” said the
captain.

“And how about the flag?”

“Well, obviously I salute it every day, sir.”

“But you don’t wave it, at all?” the major enquired.

“I think I waved a paper one a few times when I was a little boy. Patrician’s birthday or something. We stood
in the streets as he rode by and we shouted “Hurrah!”

“Never since then?”

“Well, no, Clive,” said the captain, looking embarrassed. “I’d be very worried if I saw a man singing the
national anthem and waving the flag, sir. It’s really a thing foreigners do.”

“Really? Why?”

“We don’t need to show we’re patriotic, sir. I mean, this is Ankh-Morpork. We don’t have to make a big fuss
about being the best, sir. We just know.”
#+end_quote

* Moist Von Lipwig
** Choose Death
#+begin_quote
“There is always a choice."
"You mean I could choose certain death?"
"A choice nevertheless, or perhaps an alternative. You see I believe in freedom.
Not many people do, although they will of course protest otherwise. And no
practical definition of freedom would be complete without the freedom to take
the consequences. Indeed, it is the freedom upon which all the others are
based.”
#+end_quote

* The Witches
** Ethics
 #+begin_quote
 “Evil begins when you begin to treat people as things.”
 #+end_quote

#+begin_quote Carpe Jugulum
"It's not as simple as that. It's not a black and white issue. There are so many shades of grey.'
'Nope'.
'Pardon?'
'There's no greys, only white that's got grubby. I'm surprised you don't know that. And sin, young man,
is when you treat people as things. Including yourself. That's what sin is.'
'It's a lot more complicated than that-'
'No. It ain't. When people say things are more complicated than that,
they means they're getting worried that they won't like the truth.
People as things, that's where it starts.'
'Oh, I'm sure there are worse crimes-'
'But they starts with thinking about people as things...'"
#+end_quote

** Good Ain't Nice.
#+begin_quote
She always said you can't help people with magic, but you can help them with skin.
By doin' real things, she meant.

'You'd have to go a long day's journey to find someone basically nastier than Esme' said Nanny Ogg,
'and this is me sayin' it. She knows exactly what she is. She was born to be good and she don't like it.'
#+end_quote

** Mrs Gogle and the homeless
#+begin_quote
Mrs Gogol could feel them among the trees. The homeless.
The hungry. The silent people.
Those foresaken by men and gods.
The people of the mists and the mud, whose only strength was somewhere on the other si
side of weaknes, whose beliefs were as rickety and homemade as their homes.
And the people from the city -- not the ones who lived in the big white houses and went to balls in
fine coaches, but the other ones.
They were the ones that stories are never about. Stories are not, on the whole,
interested in swineherds who remain swineherds and poor and humble shoe-makers whose
destiny is to die slightly poorer and much humbler.
#+end_quote

* The Wizards
** Memories
#+begin_quote
“Rincewind tried to force the memory out of his mind, but it was rather enjoying
itself there, terrorizing the other occupants and kicking over the furniture.”
#+end_quote

** Students
#+begin_quote
“But we're a university! We have to have a library!" said Ridcully. "It adds
tone. What sort of people would we be if we didn't go into the library?"
"Students," said Senior Wrangler morosely.”
#+end_quote

* William de Worde
#+begin_quote
“A lie can run round the world before the truth has got its boots on.”
#+end_quote

** Offense
#+begin_quote
“...William wondered why he always disliked people who said 'no offense meant.'
Maybe it was because they found it easier to to say 'no offense meant' than
actually to refrain from giving offense.”
#+end_quote

* Brutha
** Truth
#+begin_quote
“But is all this true?" said Brutha.
Didactylos shrugged. "Could be. Could be. We are here and it is now. The way I
see it is, after that, everything tends towards guesswork."
"You mean you don't KNOW it's true?" said Brutha.
"I THINK it might be," said Didactylos. "I could be wrong. Not being certain is
what being a philosopher is all about.”
#+end_quote

** Philosophers
#+begin_quote
“What's a philosopher?' said Brutha.
Someone who's bright enough to find a job with no heavy lifting,' said a voice
in his head.”
#+end_quote

* Other
#+begin_quote
Always be wary of any helpful item that weighs less than its operating manual.
#+end_quote

#+begin_quote
No. Men should die for lies. But the truth is too precious to die for.
#+end_quote

#+begin_quote
It is said that your life flashes before your eyes just before you die. That is true, it's called Life.
#+end_quote

#+begin_quote
 I'll be more enthusiastic about encouraging thinking outside the box when there's evidence of any thinking going on inside it.
 #+end_quote

#+begin_quote
Gods don't like people not doing much work. People who aren't busy all the time might start to think.
#+end_quote

#+begin_quote
He says gods like to see an atheist around. Gives them something to aim at.
#+end_quote

#+begin_quote
Give a man a fire and he's warm for the day. But set fire to him and he's warm for the rest of his life.
#+end_quote

#+begin_quote
Pulling together is the aim of despotism and tyranny. Free men pull in all kinds of directions.
#+end_quote

#+begin_quote
Real stupidity beats artificial intelligence every time.
#+end_quote

#+begin_quote
 Revolutions always come around again. That's why they're called revolutions.
 #+end_quote

#+begin_quote
 Stupid men are often capable of things the clever would not dare to contemplate...
 #+end_quote

#+begin_quote
 The duke had a mind that ticked like a clock and, like a clock, it regularly went cuckoo.
 #+end_quote

#+begin_quote
The truth may be out there, but the lies are inside your head.
#+end_quote

#+begin_quote
 “Do you not know that a man is not dead while his name is still spoken?”
 #+end_quote

#+begin_quote
 “Even if it's not your fault, it's your responsibility.”
 #+end_quote

#+begin_quote
“Wisdom comes from experience. Experience is often a result of lack of wisdom.”
#+end_quote

#+begin_quote
“This book was written using 100% recycled words.”
#+end_quote

#+begin_quote
“We are here and it is now. The way I see it is, after that, everything tends towards guesswork.”
#+end_quote

#+begin_quote
“We who think we are about to die will laugh at anything.”
#+end_quote

#+begin_quote
“What is normal? Normal is yesterday and last week and last month taken together”
#+end_quote

#+begin_quote
“If you have enough book space, I don't want to talk to you.”
#+end_quote

#+begin_quote
“The first draft is just you telling yourself the story.”
#+end_quote

#+begin_quote
“Stories of imagination tend to upset those without one.”
#+end_quote

#+begin_quote
“Steal five dollars and you're a common thief. Steal thousands and you're either the government or a hero.”
#+end_quote

#+begin_quote
“People aren't just people, they are people surrounded by circumstances.”
#+end_quote

#+begin_quote
“Look, that's why there's rules, understand? So that you think before you break 'em.”
#+end_quote

#+begin_quote
“In ancient times cats were worshipped as gods; they have not forgotten this.”
#+end_quote

#+begin_quote
“Goodness is about what you do. Not who you pray to.”
#+end_quote

#+begin_quote
“Five exclamation marks, the sure sign of an insane mind.”
#+end_quote

** Patriotism
#+begin_quote
(The pamphlet) was very patriotic. That is, it talked about killing foreigners.
#+end_quote

** Bookshops
#+begin_quote
A good bookshop is just a genteel Black Hole that knows how to read.
#+end_quote

** Education
#+begin_quote
An education was a bit like a communicable sexual disease. It made you
unsuitable for a lot of jobs and then you had the urge to pass it on.
#+end_quote

** Fame
#+begin_quote
Famous I don't know about. It's hard to be famous and alive. I just want to play
music every day and hear someone say, 'Thanks, that was great, here's some
money, same time tomorrow, okay?'
#+end_quote

** Animals
#+begin_quote
For animals, the entire universe has been neatly divided into things to (a) mate
with, (b) eat, (c) run away from, and (d) rocks.
#+end_quote

** God and Dice
#+begin_quote
God does not play dice with the universe; He plays an ineffable game of his own
devising, which might be compared, from the perspective of any of the other
players, to being involved in an obscure and complex version of poker in a pitch
dark room, with blank cards, for infinite stakes, with a dealer who won't tell
you the rules, and who smiles all the time.
#+end_quote

** Science
#+begin_quote
He was determined to discover the underlying logic behind the universe.
Which was going to be hard, because there wasn't one.”
#+end_quote

** Evidence
#+begin_quote
It could not be happening because this sort of thing did not happen. Any
contradictory evidence could be safely ignored.
#+end_quote

** Us versus Them.
#+begin_quote
It was so much easier to blame it on Them. It was bleakly depressing to think
that They were Us. If it was Them, then nothing was anyone's fault. If it was
us, what did that make Me? After all, I'm one of Us. I must be. I've certainly
never thought of myself as one of Them. No one ever thinks of themselves as one
of Them. We're always one of Us. It's Them that do the bad things.
#+end_quote

** Exams and Sobriety.
#+begin_quote
Of course, it is very important to be sober when you take an exam. Many
worthwhile careers in the street- cleansing, fruit-picking and
subway-guitar-playing industries have been founded on a lack of understanding of
this simple fact.
#+end_quote

** Seeing and Believing
#+begin_quote
Seeing, contrary to popular wisdom, isn't believing. It's where belief stops,
because it isn't needed any more.
#+end_quote

** Sham Harga
#+begin_quote
Sham Harga had run a succesful eatery for many years by always smiling, never
extending credit, and realizing that most of his customers wanted meals properly
balanced between the four food groups: sugar, starch, grease, and burnt crunchy
bits.
#+end_quote

** Europeans versus Americans
#+begin_quote
That seems to point up a significant difference between Europeans and Americans.
A European says: "I can't understand this, what's wrong with me?" An American
says: "I can't understand this, what's wrong with him?"
#+end_quote

** Military Thinking
#+begin_quote
the consensus seemed to be that if really large numbers of men were sent to
storm the mountain, then enough might survive the rocks to take the citadel.
This is essentially the basis of all military thinking.
#+end_quote

** Open Minds
#+begin_quote
The trouble with having an open mind, of course, is that people will insist on
coming along and trying to put things in it.
#+end_quote

** Types of people in the world.
#+begin_quote
There are, it has been said, two types of people in the world. There are those
who, when presented with a glass that is exactly half full, say: this glass is
half full. And then there are those who say: this glass is half empty. The world
belongs, however, to those who can look at the glass and say: What's up with
this glass? Excuse me? Excuse me? This is my glass? I don't think so. My glass
was full! And it was a bigger glass!
#+end_quote

** Fear
#+begin_quote
When the least they could do to you was everything, then the most they could do
to you suddenly held no terror.
#+end_quote

** Words
#+begin_quote
Words are the litmus paper of the minds. If you find yourself in the power of
someone who will use the word "commence" in cold blood, go somewhere else very
quickly. But if they say "Enter", don't stop to pack.
#+end_quote

** Convincing yourself
#+begin_quote
“...and the funny thing was that people who weren't entirely certain they were
right always argued much louder than other people, as if the main person they
were trying to convince were themselves.”
#+end_quote

** Life after death
#+begin_quote
“Anyway, if you stop tellin' people it's all sorted out after they're dead, they
might try sorting it all out while they're alive. ”
#+end_quote

** Aristocrats
#+begin_quote
“Aristocrats don't notice philosophical conundra. They just ignore them.
Philosophy includes contemplating the possibility that you might be wrong, sir,
and a real aristocrat knows that he is always right. It's not vanity, you
understand, it's built-in absolute certainty. They may sometimes be as mad as a
hatful of spoons, but they are always definitely and certainly mad.”
#+end_quote

** Smart versus Intelligent
#+begin_quote
“Don't be smart. Smart is only a polished version of dumb. Try intelligence. It
will surely see you through.”
#+end_quote

** Exercise for the mind
#+begin_quote
“Fantasy is an exercise bicycle for the mind. It might not take you anywhere,
but it tones up the muscles that can. Of course, I could be wrong.”
#+end_quote

** The greatest tragedy
#+begin_quote
“Ginger: You know what the greatest tragedy is in the whole world?... It's all
the people who never find out what it is they really want to do or what it is
they're really good at. It's all the sons who become blacksmiths because their
fathers were blacksmiths. It's all the people who could be really fantastic
flute players who grow old and die without ever seeing a musical instrument, so
they become bad plowmen instead. It's all the people with talents who never even
find out. Maybe they are never even born in a time when it's even possible to
find out. It's all the people who never get to know what it is that they can
really be. It's all the wasted chances.”
#+end_quote

** Observing others
#+begin_quote
“He’d forgotten the ancient wisdom: take care, when you are closely observing,
that you are not closely observed.”
#+end_quote

** Drinking and Philosophy
#+begin_quote
“His philosophy was a mixture of three famous schools -- the Cynics, the Stoics
and the Epicureans -- and summed up all three of them in his famous phrase, 'You
can't trust any bugger further than you can throw him, and there's nothing you
can do about it, so let's have a drink.”
#+end_quote

** Ignorance
#+begin_quote
“His progress through life was hampered by his tremendous sense of his own
ignorance, a disability which affects all too few.”
#+end_quote

** Bad People, on different sides.
#+begin_quote
“I believe you find life such a problem because you think there are good people
and bad people. You're wrong, of course. There are, always and only, the bad
people, but some of them are on opposite sides.”
#+end_quote

** Cats and Style
#+begin_quote
“If cats looked like frogs we'd realize what nasty, cruel little bastards they
are. Style. That's what people remember.”
#+end_quote

** Crimes by the rich
#+begin_quote
“If you had enough money, you could hardly commit crimes at all. You just
perpetrated amusing little peccadilloes.”
#+end_quote

** Trusting in yourself
#+begin_quote
“If you trust in yourself. . .and believe in your dreams. . .and follow your
star. . . you'll still get beaten by people who spent their time working hard
and learning things and weren't so lazy.”
#+end_quote

** Getting paid
#+begin_quote
“In the words of the philosopher Sceptum, the founder of my profession: am I
going to get paid for this?”
#+end_quote

** Sanity
#+begin_quote
“Inside every sane person there's a madman struggling to get out," said the
shopkeeper. "That's what I've always thought. No one goes mad quicker than a
totally sane person.”
#+end_quote

** Words of power
#+begin_quote
“It is true that words have power, and one of the things they are able to do is
get out of someone’s mouth before the speaker has the chance to stop them.”
#+end_quote

** Horrible acts by ordinary people
#+begin_quote
“It was much better to imagine men in some smokey room somewhere, made mad and
cynical by privilege and power, plotting over brandy. You had to cling to this
sort of image, because if you didn't then you might have to face the fact that
bad things happened because ordinary people, the kind who brushed the dog and
told the children bed time stories, were capable of then going out and doing
horrible things to other ordinary people. It was so much easier to blame it on
Them. It was bleakly depressing to think that They were Us. If it was Them, then
nothing was anyone's fault. If it was Us, then what did that make Me? After all,
I'm one of Us. I must be. I've certainly never thought of myself as one of Them.
No one ever thinks of themselves as one of Them. We're always one of Us. It's
Them that do the bad things.”
#+end_quote

** Us versus them
#+begin_quote
“It was so much easier to blame it on Them. It was bleakly depressing to think
that They were Us. If it was Them, then nothing was anyone's fault. If it was
us, what did that make Me? After all, I'm one of Us. I must be. I've certainly
never thought of myself as one of Them. No one ever thinks of themselves as one
of Them. We're always one of Us. It's Them that do the bad things.”
#+end_quote

** The City as process.
#+begin_quote
“It wasn’t a city, it was a process, a weight on the world that distorted the
land for hundreds of miles around. People who’d never see it in their whole life
nevertheless spent that life working for it. Thousands and thousands of green
acres were part of it, forests were part of it. It drew in and consumed…  …and
gave back the dung from its pens, and the soot from its chimneys, and
steel, and saucepans, and all the tools by which its food was made. And also
clothes, and fashions, and ideas, and interesting vices, songs, and knowledge,
and something which, if looked at in the right light, was called civilization.
That was what civilization meant. It meant the city.”
#+end_quote

** Worth doing things.
#+begin_quote
“It's not worth doing something unless someone, somewhere, would much rather you
weren't doing it.”
#+end_quote

** Imagination
#+begin_quote
“Look, he said to his imagination, if this is how you're going to behave, I
shan't bring you again.”
#+end_quote

** The Human Spirit
#+begin_quote
“One of the things forgotten about the human spirit is that while it is, in the
right conditions, noble and brave and wonderful, it is also, when you get right
down to it, only human.”
#+end_quote

** People and Change
#+begin_quote
“People don't like change. But make the change fast enough and you go from one
type of normal to another.”
#+end_quote

** Libraries
#+begin_quote
“People were stupid, sometimes. They thought the Library was a dangerous place
because of all the magical books, which was true enough, but what made it really
one of the most dangerous places there could ever be was the simple fact that it
was a library.”
#+end_quote

** Ignoring rules
#+begin_quote
“She was already learning that if you ignore the rules people will, half the
time, quietly rewrite them so that they don't apply to you.”
#+end_quote

** Humans doing things
#+begin_quote
“Some humans would do anything to see if it was possible to do it. If you put a
large switch in some cave somewhere, with a sign on it saying 'End-of-the-World
Switch. PLEASE DO NOT TOUCH', the paint wouldn't even have time to dry.”
#+end_quote

** Knowing then what you know now
#+begin_quote
“That was always the dream, wasn't it? 'I wish I'd known then what I know now'?
But when you got older you found out that you NOW wasn't YOU then. You then was
a twerp. You then was what you had to be to start out on the rocky road of
becoming you now, and one of the rocky patches on that road was being a twerp.”
#+end_quote

** The enemy
#+begin_quote
“The enemy isn't men, or women, it's bloody stupid people and no one has the
right to be stupid.”
#+end_quote

** The Female mind
#+begin_quote
“The female mind is certainly a devious one, my lord."
Vetinari looked at his secretary in surprise. "Well, of course it is. It has to
deal with the male one.”
#+end_quote

** The intelligence of the crowd
#+begin_quote
“The intelligence of that creature known as a crowd is the square root of the
number of people in it.”
#+end_quote

** Someone
#+begin_quote
“The phrase 'Someone ought to do something' was not, by itself, a helpful one.
People who used it never added the rider 'and that someone is me'.”
#+end_quote

** Cliches
#+begin_quote
“The reason that clichés become clichés is that they are the hammers and
screwdrivers in the toolbox of communication.”
#+end_quote

** The truth
#+begin_quote
“The truth isn't easily pinned to a page. In the bathtub of history the truth is
harder to hold than the soap and much more difficult to find.”
#+end_quote

** The wages of sin
#+begin_quote
“The wages of sin is death but so is the salary of virtue, and at least the evil
get to go home early on Fridays.”
#+end_quote

** People with no voice
#+begin_quote
“Them as can do has to do for them as can't. And someone has to speak up for
them as has no voices.”
#+end_quote

** Psychopaths and normal family men
#+begin_quote
“There are hardly any excesses of the most crazed psychopath that cannot easily
be duplicated by a normal kindly family man who just comes in to work every day
and has a job to do.”
#+end_quote

** Finding God
#+begin_quote
“There is a rumour going around that I have found God. I think this is unlikely
because I have enough difficulty finding my keys, and there is empirical
evidence that they exist.”
#+end_quote

** Old Money
#+begin_quote
“They were indeed what was known as 'old money', which meant that it had been
made so long ago that the black deeds which had originally filled the coffers
were now historically irrelevant. Funny, that: a brigand for a father was
something you kept quiet about, but a slave-taking pirate for a
great-great-great-grandfather was something to boast of over the port. Time
turned the evil bastards into rogues, and rogue was a word with a twinkle in its
eye and nothing to be ashamed of.”
#+end_quote

** Government and criminals
#+begin_quote
“What kind of man would put a known criminal in charge of a major branch of
government? Apart from, say, the average voter.”
#+end_quote

** Clearly
#+begin_quote
“When people say "clearly" something that means there's a huge crack in their
argument and they know things aren't clear at all.”
#+end_quote

** Being a possession
#+begin_quote
“When you have been a possession,
then you really understand what freedom means
in all its magnificent terror.”
#+end_quote

** Language
#+begin_quote
“Y’know,’ he said, ‘it’s very hard to talk quantum using a language originally
designed to tell other monkeys where the ripe fruit is.”
#+end_quote
* Misc
#+begin_quote
"They were, by their own standards, honest men, in that they only did
what they knew or suspected that everyone else did."
#+end_quote
