#+TITLE: Ursula Le Guin

* Earthsea

* The Dispossessed
#+begin_quote The Dispossessed (1974)
 “With the myth of the State out of the way, the real mutuality and reciprocity of society and individual became clear.
 Sacrifice might be demanded of the individual, but never compromise:
 for though only the society could give security and stability, only the individual, the person, had the power of moral choice - the power of change, the essential function of life.
 The Odonian society was conceived as a permanent revolution, and revolution begins in the thinking mind. ”
#+end_quote

#+begin_quote The Dispossessed (1974)
“We have nothing but our freedom
We have nothing to give you but your own freedom
We have no law but the single principle of mutual aid between individuals
We have no government but the single principle of free association
We have no states, no nations, no presidents, no premiers, no chiefs, no generals, no bosses, no bankers, no landlords, no wages, no charity, no police, no soldiers, no wars
Nor do we have much else
We are sharers, not owners
We are not prosperous
None of us is rich
None of us is powerful
If it is Anarres you want, if it is the future you seek, then I tell you that you must come to it with empty hands
You must come to it alone, and naked, as the child comes into the world, into his future, without any past, without any property, wholly dependent on other people for his life
You cannot take what you have not given, and you must give yourself
You cannot buy the Revolution
You cannot make the Revolution
You can only be the Revolution
It is in your spirit, or it is nowhere.”
#+end_quote

* Misc
#+begin_quote
The end justifies the means.
But what if there never is an end?
All we have is means.
#+end_quote

#+begin_quote
We live in Capitalism. It's Power seems inescapable.
So did the Divine Right of Kings.
Any Human Power can be resisted and changed by human beings.
#+end_quote

#+begin_quote "Ursula Le Guin and the Scourge of the Uncritical Reader."
"Commodified fantasy takes no risks:
 it invents nothing, but imitates and trivializes.
It proceeds by depriving the old stories of their intellectual and ethical complexity, turning their action to violence, their actors to dolls, and their truth-telling to sentimental platitude.
Heroes brandish their swords, lasers, wands, as mechanically as combine harvesters, reaping profits.
Profoundly disturbing moral choices are sanitized, made cute, made safe.
The passionately conceived ideas of the great storytellers are copied, stereotyped, reduced to toys, molded in bright-colored plastic, advertised, sold, broken, junked, replaceable, interchangeable.
What the commodifiers of fantasy count on and exploit is the insuperable imagination of the reader, child or adult, which gives even these dead things life - of a sort, for a while."
#+end_quote

#+begin_quote
Art as an assembly-line commodity leaves me cold.
#+end_quote
JG: *AI* as an assembly-line commodity leaves me cold
