** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017035.wav
    Length: 12
** Laughter into applause and whistles at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017034.wav
    Length: 19
** Crowd at protest meeting saying 'Aye'. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017033.wav
    Length: 13
** Mild applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017032.wav
    Length: 8
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017031.wav
    Length: 14
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017030.wav
    Length: 15
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017029.wav
    Length: 17
** General atmosphere of crowd at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017028.wav
    Length: 395
** Mixed cheerful chatter. (Thirty people.)                                                                                ::
    ID: 07017027.wav
    Length: 187
** Mixed continuous outdoor laughter. (Thirty people.)                                                                                ::
    ID: 07017026.wav
    Length: 45
** Three cheers from group of women. (Thirty women.)                                                                                ::
    ID: 07017025.wav
    Length: 12
** Three cheers from mixed group of people. (Thirty people.)                                                                                ::
    ID: 07017024.wav
    Length: 15
** Three cheers from group of men. (Thirty men.)                                                                                ::
    ID: 07017023.wav
    Length: 11
** One burst of mixed cheering. (Thirty people.)                                                                                ::
    ID: 07017022.wav
    Length: 25
** Two long bursts of mixed cheering. (Thirty people.)                                                                                ::
    ID: 07017021.wav
    Length: 26
** Applause from thirty people.                                                                                ::
    ID: 07017020.wav
    Length: 13
** Applause from thirty people.                                                                                ::
    ID: 07017019.wav
    Length: 12
** Applause from thirty people.                                                                                ::
    ID: 07017018.wav
    Length: 9
** Crowd at International Ladies Hockey Match, including approx 60,000 girls. (General match atmosphere at Wembley, 1961)                                                                                ::
    ID: 07017017.wav
    Length: 396
** Excited chatter from large crowd. (Wide perspective)                                                                                ::
    ID: 07017016.wav
    Length: 401
** Group of youthful supporters with occasional speech and cheering. (Suggested use, sports meetings, fetes)                                                                                ::
    ID: 07017015.wav
    Length: 202
** Group of boys assembling with speech, laughter and footsteps on gravel.                                                                                ::
    ID: 07017014.wav
    Length: 200
** Group of 16-19 year old boys talking, occasional laughter.                                                                                ::
    ID: 07017013.wav
    Length: 199
** Group of 16-19 year old boys talking, occasional pauses and footsteps.                                                                                ::
    ID: 07017012.wav
    Length: 198
** Three hundred people rioting, with boos and shouts. (No gunfire.)                                                                                ::
    ID: 07017011.wav
    Length: 363
** Large crowd of men rioting, with boos and shouts. (No gunfire.)                                                                                ::
    ID: 07017010.wav
    Length: 392
** One hundred men, constant background of excited chatter with laughter and occasional distinct speech.                                                                                ::
    ID: 07017009.wav
    Length: 393
** Mixed excited chatter with laughter and occasional distinct speech.                                                                                ::
    ID: 07017008.wav
    Length: 387
** Large crowd in marquee, indistinct busy speech.                                                                                ::
    ID: 07017007.wav
    Length: 215
** Large crowd in marquee, indistinct busy speech.                                                                                ::
    ID: 07017006.wav
    Length: 148
** Large excited carnival crowd with frequent cheering.                                                                                ::
    ID: 07017005.wav
    Length: 337
** Cheerful chatter.                                                                                ::
    ID: 07017004.wav
    Length: 186
** General chatter.                                                                                ::
    ID: 07017003.wav
    Length: 184
** Chatter and footsteps on gravel, animated.                                                                                ::
    ID: 07017002.wav
    Length: 150
** Chatter and footsteps on gravel.                                                                                ::
    ID: 07017001.wav
    Length: 187
** Hand loom with flying shuttles operating. (Old textile machinery.)                                                                                ::
    ID: 07016344.wav
    Length: 141
** Spinning mule operating. (Old textile machinery.)                                                                                ::
    ID: 07016343.wav
    Length: 174
** Geared spinning machinery operating. (Old textile machinery.)                                                                                ::
    ID: 07016342.wav
    Length: 111
** Improved spinning jenny, drawing back, spinning & winding up. (Old textile machinery.)                                                                                ::
    ID: 07016341.wav
    Length: 161
** Winding up yarn after spinning. (Old textile machinery.)                                                                                ::
    ID: 07016340.wav
    Length: 69
** Spinning jenny operating with squeaks. (Old textile machinery.)                                                                                ::
    ID: 07016339.wav
    Length: 211
** Textile factory, general atmosphere with spinning jennies operating. (Old textile machinery.)                                                                                ::
    ID: 07016338.wav
    Length: 132
** Spinning jenny operating with several starts & stops. (Old textile machinery.)                                                                                ::
    ID: 07016337.wav
    Length: 153
** Crompton's spinning mule operating. (Old textile machinery, invented by Samuel Crompton.)                                                                                ::
    ID: 07016336.wav
    Length: 145
** Lapping machine mechanism operating , with several starts & stops. (Old textile machinery.)                                                                                ::
    ID: 07016335.wav
    Length: 176
** Arkwright's original spinning machine operating at speed. (Invented by Richard Arkwright, 1769.)                                                                                ::
    ID: 07016334.wav
    Length: 183
** Arkwright's original spinning machine operating. (Invented by Richard Arkwright, 1769.)                                                                                ::
    ID: 07016333.wav
    Length: 181
** Arkwright's water-twist frame operating. (Invented by Richard Arkwright, c. 1790.)                                                                                ::
    ID: 07016332.wav
    Length: 182
** Twenty Saurer looms, start, run & stop.                                                                                ::
    ID: 07016331.wav
    Length: 257
** Pirn automatic winder operating.                                                                                ::
    ID: 07016330.wav
    Length: 72
** Loom starts, runs & stops.                                                                                ::
    ID: 07016329.wav
    Length: 205
** Four looms, start, run & stop.                                                                                ::
    ID: 07016328.wav
    Length: 127
** Several looms operating in a carpet factory.                                                                                ::
    ID: 07016327.wav
    Length: 364
** Shearing machine operating in a carpet factory.                                                                                ::
    ID: 07016326.wav
    Length: 162
** Wool winder operating in a carpet factory.                                                                                ::
    ID: 07016325.wav
    Length: 165
** Loom operating in carpet factory, with double beat.                                                                                ::
    ID: 07016324.wav
    Length: 369
** Loom operating in carpet factory.                                                                                ::
    ID: 07016323.wav
    Length: 362
** Dentists, mouth rinse & general surgery atmosphere.                                                                                ::
    ID: 07016322.wav
    Length: 212
** Dentists, high-speed drill operating, sounds of scraping & rinsing. (Repeated once.)                                                                                ::
    ID: 07016321.wav
    Length: 140
** Dentists, high-speed drill operates with pauses & general surgery atmosphere.                                                                                ::
    ID: 07016320.wav
    Length: 150
** Dentists, slow speed drill operates with pauses, sounds of scraping & rinsing.                                                                                ::
    ID: 07016319.wav
    Length: 113
** Dentists, high-speed drill switched on, operates & switched off, sound of rinsing. (Repeated once.)                                                                                ::
    ID: 07016318.wav
    Length: 65
** Women's Ward, atmosphere in ward with footsteps, coughing & some indistinct speech.                                                                                ::
    ID: 07016317.wav
    Length: 337
** Hospital trolley passing in hospital corridor.                                                                                ::
    ID: 07016316.wav
    Length: 26
** Men's Ward, atmosphere in ward with footsteps, coughing & indistinct speech, some laughter.                                                                                ::
    ID: 07016315.wav
    Length: 335
** Hospital trolley passing in hospital corridor.                                                                                ::
    ID: 07016314.wav
    Length: 22
** Operating Theatre, atmosphere in theatre with hum of air conditioner, instruments & equipment being used & moved about, some indistinct speech.                                                                                ::
    ID: 07016313.wav
    Length: 365
** Hospital pharmcy, atmosphere with mixing of liquids, clinking of crockery & bottles & some indistinct speech.                                                                                ::
    ID: 07016312.wav
    Length: 364
** Autoclave steriliser, operating with sound of water in steriliser and spraying. (Close perspective)                                                                                ::
    ID: 07016311.wav
    Length: 343
** Outpaitients Department, atmosphere recorded in outpatients department, indistinct speech, footsteps, coughs, opening and closing of doors. (Wide perspective.)                                                                                ::
    ID: 07016310.wav
    Length: 366
** Pathological Laboratory, atmosphere recorded at workbench, clattering & clinking of metal & glass instruments, some liquids poured & occasional machinery hum.                                                                                ::
    ID: 07016309.wav
    Length: 366
** Pathological Laboratory, atmosphere recorded at laboratory workbench, clattering and clinking of metal & glass instruments, some liquids being poured.                                                                                ::
    ID: 07016308.wav
    Length: 316
** Maternity Ward, atmosphere in ward with newborns crying & indistinct adult speech. (Some distant traffic.)                                                                                ::
    ID: 07016307.wav
    Length: 366
** Childrens' Ward, atmosphere in ward with continuous indistinct speech of children & adults.                                                                                ::
    ID: 07016306.wav
    Length: 354
** General airfield atmosphere with Avro Shackleton aircraft revving and taking off. (Post-war maritime reconnaissance mission, four pistone engines.)                                                                                ::
    ID: 07016305.wav
    Length: 398
** Avro Shackleton, exterior, two passing in succession. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016304.wav
    Length: 101
** Avro Shackleton, exterior, two passing overhead together. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016303.wav
    Length: 59
** Avro Shackleton, exterior, passing overhead. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016302.wav
    Length: 45
** Avro Shackleton, exterior, taxi in and switch off. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016301.wav
    Length: 131
** Avro Shackleton, exterior, landing to mid-distance. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016300.wav
    Length: 63
** Avro Shackleton, exterior, take-off. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016299.wav
    Length: 56
** Avro Shackleton, exterior, take-off. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016298.wav
    Length: 59
** Avro Shackleton, exterior, taxi to mid-distance. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016297.wav
    Length: 44
** Avro Shackleton, exterior, generator, start and run up engines. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016296.wav
    Length: 213
** Avro Shackleton, interior, erratic constant flight. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016295.wav
    Length: 188
** Avro Shackleton, interior, constant flight. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016294.wav
    Length: 230
** Avro Shackleton, interior, descent & landing. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016293.wav
    Length: 178
** Avro Shackleton, interior, take off & climb. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016292.wav
    Length: 215
** Avro Shackleton, interior, commence & continue to taxi. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016291.wav
    Length: 155
** Avro Shackleton, interior, start & run up engines. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016290.wav
    Length: 213
** Avro Shackleton, interior, start engines & splutter out. (Post-war maritime reconnaissance mission, four piston engines.)                                                                                ::
    ID: 07016289.wav
    Length: 13
** Avro Lancaster, exterior, several planes taking off in succession. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016288.wav
    Length: 208
** Avro Lancaster, interior, constant flight. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016287.wav
    Length: 146
** Avro Lancaster, exterior, four planes circling overhead. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016286.wav
    Length: 131
** Avro Lancaster, exterior, warming up on perimeter. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016285.wav
    Length: 217
** Avro Lancaster, interior, landing. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016284.wav
    Length: 214
** Avro Lancaster, interior, taxi and take off. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016283.wav
    Length: 134
** Avro Lancaster, exterior, passing overhead. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016282.wav
    Length: 27
** Avro Lancaster, exterior, taxi up, switch off. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016281.wav
    Length: 70
** Avro Lancaster, exterior, landing. (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016280.wav
    Length: 37
** Avro Lancaster, exterior, start up, take off.  (World War II bomber, four piston engines.)                                                                                ::
    ID: 07016279.wav
    Length: 122
** Epsom Race Course, Oaks Stakes, end of race with general atmosphere. (Flat racing.)                                                                                ::
    ID: 07016278.wav
    Length: 184
** Epsom Race Course, Oaks Stakes, race announcements over P.A. system ("Under Starter's orders" & "They're off". (Flat racing.)                                                                                ::
    ID: 07016277.wav
    Length: 7
** Epsom Race Course, Oaks Stakes, general atmosphere before race. (Flat racing.)                                                                                ::
    ID: 07016276.wav
    Length: 168
** Epsom Race Course, Derby Stakes, general atmosphere between races. (Flat racing.)                                                                                ::
    ID: 07016275.wav
    Length: 396
** Cheltenham Race Course, general course atmosphere. (No P.A. system.) (Steeplechasing.)                                                                                ::
    ID: 07016274.wav
    Length: 197
** Cheltenham Race Course, general course atmosphere with P.A system. (Steeplechasing.)                                                                                ::
    ID: 07016273.wav
    Length: 177
** Cheltenham Race Course, general course atmosphere beteween races. (Steeplechasing.)                                                                                ::
    ID: 07016272.wav
    Length: 373
** Cheltenham Race Course, end of Cheltenham Gold Cup race. (Steeplechasing.)                                                                                ::
    ID: 07016271.wav
    Length: 115
** Cheltenham Race Course, horses jumping fence. (Steeplechasing.)                                                                                ::
    ID: 07016270.wav
    Length: 32
** Cheltenham Race Course, horses jumping fence. (Steeplechasing.)                                                                                ::
    ID: 07016269.wav
    Length: 31
** Cheltenham Race Course, horses jumping fence. (Steeplechasing.)                                                                                ::
    ID: 07016268.wav
    Length: 20
** Cheltenham Race Course, horses jumping fence. (Steeplechasing.)                                                                                ::
    ID: 07016267.wav
    Length: 21
** Cheltenham Race Course, horses jumping fence. (Steeplechasing.)                                                                                ::
    ID: 07016266.wav
    Length: 30
** Cheltenham Race Course, Starter's voice & horses away, with P.A. system. (Steeplechasing.)                                                                                ::
    ID: 07016265.wav
    Length: 23
** Cheltenham Race Course, Starter's voice & horses away. (Steeplechasing.)                                                                                ::
    ID: 07016264.wav
    Length: 19
** Cheltenham Race Course, starting tape & horses away. (Steeplechasing.)                                                                                ::
    ID: 07016263.wav
    Length: 22
** Cheltenham Race Course, starting tape & horses away. (Steeplechasing.)                                                                                ::
    ID: 07016262.wav
    Length: 15
** Cheltenham Race Course, starting tape. (Steeplechasing.)                                                                                ::
    ID: 07016261.wav
    Length: 7
** Horses gallop past on grass surface.                                                                                ::
    ID: 07016260.wav
    Length: 26
** Horses gallop past on grass surface.                                                                                ::
    ID: 07016259.wav
    Length: 30
** Horses gallop past on grass surface.                                                                                ::
    ID: 07016258.wav
    Length: 31
** Horses gallop past on grass surface.                                                                                ::
    ID: 07016257.wav
    Length: 23
** Horses gallop past on grass surface.                                                                                ::
    ID: 07016256.wav
    Length: 25
** Horses gallop past on grass surface.                                                                                ::
    ID: 07016255.wav
    Length: 25
** Horses gallop past on grass surface.                                                                                ::
    ID: 07016254.wav
    Length: 33
** Horses canter past on grass surface.                                                                                ::
    ID: 07016253.wav
    Length: 105
** Newbury Race Course, atmosphere at starting gate, horses away. (Flat racing.)                                                                                ::
    ID: 07016252.wav
    Length: 8
** Newbury Race Course, atmosphere at starting gate, horses away. (Flat racing.)                                                                                ::
    ID: 07016251.wav
    Length: 9
** Newbury Race Course, atmosphere at starting gate. (Flat racing.)                                                                                ::
    ID: 07016250.wav
    Length: 6
** Newbury Race Course, tote background with customers placing bets. (Flat racing.)                                                                                ::
    ID: 07016249.wav
    Length: 245
** Newbury Race Course, tote background with customers placing bets & tote bell. (Flat racing.)                                                                                ::
    ID: 07016248.wav
    Length: 139
** Newbury Race Course, general course background with busy crowd. (Flat racing.)                                                                                ::
    ID: 07016247.wav
    Length: 393
** Newbury Race Course, public address system announcement "under starter's orders, they're off" & race commentary, with general atmosphere. (Flat racing.)                                                                                ::
    ID: 07016246.wav
    Length: 185
** Newbury Race Course, public address system announcement about runners for Washington Stakes, with general atmosphere. (Flat racing.)                                                                                ::
    ID: 07016245.wav
    Length: 109
** Newbury Race Course, public address system announcement "jockeys please mount", with general atmosphere. (Flat racing.)                                                                                ::
    ID: 07016244.wav
    Length: 80
** Newbury Race Course, public address system announcement about tote returns, with general atmosphere. (Flat racing.)                                                                                ::
    ID: 07016243.wav
    Length: 91
** Newbury Race Course, public address system announcement about tote announcement for jackpot & starting prices, with general atmosphere. (Flat racing.)                                                                                ::
    ID: 07016242.wav
    Length: 94
** Newbury Race Course, public address system announcement about race draw, with general atmosphere. (Flat racing.)                                                                                ::
    ID: 07016241.wav
    Length: 183
** Newbury Race Course, crowd atmosphere with commentary on P.A. system. ("Under starters orders, they're off', race commentary & photo finish.) (Flat racing.)                                                                                ::
    ID: 07016240.wav
    Length: 119
** Newbury Race Course, Silver Ring atmosphere before race. (Flat racing.)                                                                                ::
    ID: 07016239.wav
    Length: 241
** Newbury Race Course, crowd atmosphere with commentary & results on P.A. system. (Indistinct P.A. at times.) (Flat racing.)                                                                                ::
    ID: 07016238.wav
    Length: 141
** Newbury Race Course, atmosphere before race. (Flat racing.)                                                                                ::
    ID: 07016237.wav
    Length: 265
** Point to Point meeting, general atmosphere. (No bookmakers.)                                                                                ::
    ID: 07016236.wav
    Length: 374
** Point to Point meeting, general atmosphere with bookmakers.                                                                                ::
    ID: 07016235.wav
    Length: 367
** Big Tom, bell in Christchurch College clock, striking 101 times.                                                                                ::
    ID: 07016234.wav
    Length: 291
** Christchurch College clock striking twelve o'clock.                                                                                ::
    ID: 07016233.wav
    Length: 66
** Christchurch College clock striking eleven o'clock.                                                                                ::
    ID: 07016232.wav
    Length: 62
** Christchurch College clock striking ten o'clock.                                                                                ::
    ID: 07016231.wav
    Length: 58
** Christchurch College clock striking nine o'clock.                                                                                ::
    ID: 07016230.wav
    Length: 55
** Christchurch College clock striking eight o'clock.                                                                                ::
    ID: 07016229.wav
    Length: 51
** Christchurch College clock striking seven o'clock.                                                                                ::
    ID: 07016228.wav
    Length: 48
** Christchurch College clock striking six o'clock.                                                                                ::
    ID: 07016227.wav
    Length: 44
** Christchurch College clock striking five o'clock.                                                                                ::
    ID: 07016226.wav
    Length: 40
** Christchurch College clock striking four o'clock.                                                                                ::
    ID: 07016225.wav
    Length: 37
** Christchurch College clock striking three o'clock.                                                                                ::
    ID: 07016224.wav
    Length: 33
** Christchurch College clock striking two o'clock.                                                                                ::
    ID: 07016223.wav
    Length: 29
** Christchurch College clock striking one o'clock.                                                                                ::
    ID: 07016222.wav
    Length: 31
** New College clock striking twelve o'clock.                                                                                ::
    ID: 07016221.wav
    Length: 61
** New College clock striking eleven o'clock.                                                                                ::
    ID: 07016220.wav
    Length: 58
** New College clock striking ten o'clock.                                                                                ::
    ID: 07016219.wav
    Length: 56
** New College clock striking nine o'clock.                                                                                ::
    ID: 07016218.wav
    Length: 54
** New College clock striking eight o'clock.                                                                                ::
    ID: 07016217.wav
    Length: 54
** New College clock striking seven o'clock.                                                                                ::
    ID: 07016216.wav
    Length: 52
** New College clock striking six o'clock.                                                                                ::
    ID: 07016215.wav
    Length: 49
** New College clock striking five o'clock.                                                                                ::
    ID: 07016214.wav
    Length: 47
** New College clock striking four o'clock.                                                                                ::
    ID: 07016213.wav
    Length: 45
** New College clock striking three o'clock.                                                                                ::
    ID: 07016212.wav
    Length: 43
** New College clock striking two o'clock.                                                                                ::
    ID: 07016211.wav
    Length: 41
** New College clock striking one o'clock.                                                                                ::
    ID: 07016210.wav
    Length: 35
** New College clock striking quarter to the hour.                                                                                ::
    ID: 07016209.wav
    Length: 25
** New College clock striking half past the hour.                                                                                ::
    ID: 07016208.wav
    Length: 22
** New College clock striking quarter past the hour.                                                                                ::
    ID: 07016207.wav
    Length: 19
** Balliol College clock striking twelve o'clock.                                                                                ::
    ID: 07016206.wav
    Length: 38
** Balliol College clock striking eleven o'clock.                                                                                ::
    ID: 07016205.wav
    Length: 36
** Balliol College clock striking ten o'clock.                                                                                ::
    ID: 07016204.wav
    Length: 34
** Balliol College clock striking nine o'clock.                                                                                ::
    ID: 07016203.wav
    Length: 30
** Balliol College clock striking eight o'clock.                                                                                ::
    ID: 07016202.wav
    Length: 29
** Balliol College clock striking seven o'clock.                                                                                ::
    ID: 07016201.wav
    Length: 27
** Balliol College clock striking six o'clock.                                                                                ::
    ID: 07016200.wav
    Length: 25
** Balliol College clock striking five o'clock.                                                                                ::
    ID: 07016199.wav
    Length: 24
** Balliol College clock striking four o'clock.                                                                                ::
    ID: 07016198.wav
    Length: 21
** Balliol College clock striking three o'clock.                                                                                ::
    ID: 07016197.wav
    Length: 20
** Balliol College clock striking two o'clock.                                                                                ::
    ID: 07016196.wav
    Length: 16
** Balliol College clock striking one o'clock.                                                                                ::
    ID: 07016195.wav
    Length: 14
** Trinity & St John's College clock striking twelve o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016194.wav
    Length: 65
** Trinity & St John's College clock striking eleven o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016193.wav
    Length: 61
** Trinity & St John's College clock striking ten o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016192.wav
    Length: 57
** Trinity & St John's College clock striking nine o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016191.wav
    Length: 55
** Trinity & St John's College clock striking eight o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016190.wav
    Length: 51
** Trinity & St John's College clock striking seven o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016189.wav
    Length: 49
** Trinity & St John's College clock striking six o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016188.wav
    Length: 45
** Trinity & St John's College clock striking five o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016187.wav
    Length: 44
** Trinity & St John's College clock striking four o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016186.wav
    Length: 40
** Trinity & St John's College clock striking three o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016185.wav
    Length: 36
** Trinity & St John's College clock striking two o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016184.wav
    Length: 35
** Trinity & St John's College clock striking one o'clock. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016183.wav
    Length: 30
** Trinity & St John's College clock striking quarter to the hour. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016182.wav
    Length: 21
** Trinity & St John's College clock striking half past the hour. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016181.wav
    Length: 22
** Trinity & St John's College clock striking quarter past the hour. (Trinity clock strikes a second time for St. John's College.)                                                                                ::
    ID: 07016180.wav
    Length: 20
** Caius College clock striking twelve o'clock.                                                                                ::
    ID: 07016179.wav
    Length: 55
** Caius College clock striking eleven o'clock.                                                                                ::
    ID: 07016178.wav
    Length: 50
** Caius College clock striking ten o'clock.                                                                                ::
    ID: 07016177.wav
    Length: 47
** Caius College clock striking nine o'clock.                                                                                ::
    ID: 07016176.wav
    Length: 45
** Caius College clock striking eight o'clock.                                                                                ::
    ID: 07016175.wav
    Length: 42
** Caius College clock striking seven o'clock.                                                                                ::
    ID: 07016174.wav
    Length: 40
** Caius College clock striking six o'clock.                                                                                ::
    ID: 07016173.wav
    Length: 38
** Caius College clock striking five o'clock.                                                                                ::
    ID: 07016172.wav
    Length: 35
** Caius College clock striking four o'clock.                                                                                ::
    ID: 07016171.wav
    Length: 35
** Caius College clock striking three o'clock.                                                                                ::
    ID: 07016170.wav
    Length: 31
** Caius College clock striking two o'clock.                                                                                ::
    ID: 07016169.wav
    Length: 27
** Caius College clock striking one o'clock.                                                                                ::
    ID: 07016168.wav
    Length: 27
** Caius College clock striking quarter to the hour.                                                                                ::
    ID: 07016167.wav
    Length: 19
** Caius College clock striking half past the hour.                                                                                ::
    ID: 07016166.wav
    Length: 19
** Caius College clock striking quarter past the hour.                                                                                ::
    ID: 07016165.wav
    Length: 17
** Keble College clock striking twelve o'clock.                                                                                ::
    ID: 07016164.wav
    Length: 72
** Keble College clock striking eleven o'clock.                                                                                ::
    ID: 07016163.wav
    Length: 70
** Keble College clock striking ten o'clock.                                                                                ::
    ID: 07016162.wav
    Length: 68
** Keble College clock striking nine o'clock.                                                                                ::
    ID: 07016161.wav
    Length: 64
** Keble College clock striking eight o'clock.                                                                                ::
    ID: 07016160.wav
    Length: 64
** Keble College clock striking seven o'clock.                                                                                ::
    ID: 07016159.wav
    Length: 61
** Keble College clock striking six o'clock.                                                                                ::
    ID: 07016158.wav
    Length: 59
** Keble College clock striking five o'clock.                                                                                ::
    ID: 07016157.wav
    Length: 56
** Keble College clock striking four o'clock.                                                                                ::
    ID: 07016156.wav
    Length: 53
** Keble College clock striking three o'clock.                                                                                ::
    ID: 07016155.wav
    Length: 51
** Keble College clock striking two o'clock.                                                                                ::
    ID: 07016154.wav
    Length: 49
** Keble College clock striking one o'clock.                                                                                ::
    ID: 07016153.wav
    Length: 46
** Keble College clock striking quarter to the hour.                                                                                ::
    ID: 07016152.wav
    Length: 19
** Keble College clock striking half past the hour.                                                                                ::
    ID: 07016151.wav
    Length: 23
** Keble College clock striking quarter past the hour.                                                                                ::
    ID: 07016150.wav
    Length: 24
** Wadham College clock striking nine o'clock.                                                                                ::
    ID: 07016149.wav
    Length: 19
** Wadham College clock striking eight o'clock.                                                                                ::
    ID: 07016148.wav
    Length: 17
** Wadham College clock striking seven o'clock.                                                                                ::
    ID: 07016147.wav
    Length: 17
** Wadham College clock striking six o'clock.                                                                                ::
    ID: 07016146.wav
    Length: 16
** Wadham College clock striking five o'clock.                                                                                ::
    ID: 07016145.wav
    Length: 14
** Wadham College clock striking four o'clock.                                                                                ::
    ID: 07016144.wav
    Length: 14
** Wadham College clock striking three o'clock.                                                                                ::
    ID: 07016143.wav
    Length: 13
** Wadham College clock striking two o'clock.                                                                                ::
    ID: 07016142.wav
    Length: 12
** Wadham College clock striking one o'clock.                                                                                ::
    ID: 07016141.wav
    Length: 11
** Wadham College clock striking twelve o'clock.                                                                                ::
    ID: 07016140.wav
    Length: 22
** Wadham College clock striking eleven o'clock.                                                                                ::
    ID: 07016139.wav
    Length: 20
** Wadham College clock striking ten o'clock.                                                                                ::
    ID: 07016138.wav
    Length: 20
** Lincoln College clock striking nine o'clock.                                                                                ::
    ID: 07016137.wav
    Length: 27
** Lincoln College clock striking eight o'clock.                                                                                ::
    ID: 07016136.wav
    Length: 25
** Lincoln College clock striking seven o'clock.                                                                                ::
    ID: 07016135.wav
    Length: 23
** Lincoln College clock striking six o'clock.                                                                                ::
    ID: 07016134.wav
    Length: 22
** Lincoln College clock striking five o'clock.                                                                                ::
    ID: 07016133.wav
    Length: 19
** Lincoln College clock striking four o'clock.                                                                                ::
    ID: 07016132.wav
    Length: 18
** Lincoln College clock striking three o'clock.                                                                                ::
    ID: 07016131.wav
    Length: 16
** Lincoln College clock striking two o'clock.                                                                                ::
    ID: 07016130.wav
    Length: 14
** Lincoln College clock striking one o'clock.                                                                                ::
    ID: 07016129.wav
    Length: 11
** Lincoln College clock striking twelve o'clock.                                                                                ::
    ID: 07016128.wav
    Length: 33
** Lincoln College clock striking eleven o'clock.                                                                                ::
    ID: 07016127.wav
    Length: 32
** Lincoln College clock striking ten o'clock.                                                                                ::
    ID: 07016126.wav
    Length: 30
** Jesus College clock striking nine o'clock.                                                                                ::
    ID: 07016125.wav
    Length: 27
** Jesus College clock striking eight o'clock.                                                                                ::
    ID: 07016124.wav
    Length: 25
** Jesus College clock striking seven o'clock.                                                                                ::
    ID: 07016123.wav
    Length: 22
** Jesus College clock striking six o'clock.                                                                                ::
    ID: 07016122.wav
    Length: 20
** Jesus College clock striking five o'clock.                                                                                ::
    ID: 07016121.wav
    Length: 18
** Jesus College clock striking four o'clock.                                                                                ::
    ID: 07016120.wav
    Length: 16
** Jesus College clock striking three o'clock.                                                                                ::
    ID: 07016119.wav
    Length: 14
** Jesus College clock striking two o'clock.                                                                                ::
    ID: 07016118.wav
    Length: 13
** Jesus College clock striking one o'clock.                                                                                ::
    ID: 07016117.wav
    Length: 10
** Jesus College clock striking twelve o'clock.                                                                                ::
    ID: 07016116.wav
    Length: 33
** Jesus College clock striking eleven o'clock.                                                                                ::
    ID: 07016115.wav
    Length: 30
** Jesus College clock striking ten o'clock.                                                                                ::
    ID: 07016114.wav
    Length: 28
** Worcester College clock striking nine o'clock.                                                                                ::
    ID: 07016113.wav
    Length: 29
** Worcester College clock striking eight o'clock.                                                                                ::
    ID: 07016112.wav
    Length: 26
** Worcester College clock striking seven o'clock.                                                                                ::
    ID: 07016111.wav
    Length: 24
** Worcester College clock striking six o'clock.                                                                                ::
    ID: 07016110.wav
    Length: 22
** Worcester College clock striking five o'clock.                                                                                ::
    ID: 07016109.wav
    Length: 19
** Worcester College clock striking four o'clock.                                                                                ::
    ID: 07016108.wav
    Length: 17
** Worcester College clock striking three o'clock.                                                                                ::
    ID: 07016107.wav
    Length: 15
** Worcester College clock striking two o'clock.                                                                                ::
    ID: 07016106.wav
    Length: 12
** Worcester College clock striking one o'clock.                                                                                ::
    ID: 07016105.wav
    Length: 10
** Worcester College clock striking twelve o'clock.                                                                                ::
    ID: 07016104.wav
    Length: 35
** Worcester College clock striking eleven o'clock.                                                                                ::
    ID: 07016103.wav
    Length: 33
** Worcester College clock striking ten o'clock.                                                                                ::
    ID: 07016102.wav
    Length: 31
** University College, Oxford clock striking nine o'clock.                                                                                ::
    ID: 07016101.wav
    Length: 33
** University College, Oxford clock striking eight o'clock.                                                                                ::
    ID: 07016100.wav
    Length: 29
** University College, Oxford clock striking seven o'clock.                                                                                ::
    ID: 07016099.wav
    Length: 24
** University College, Oxford clock striking six o'clock.                                                                                ::
    ID: 07016098.wav
    Length: 22
** University College, Oxford clock striking five o'clock.                                                                                ::
    ID: 07016097.wav
    Length: 21
** University College, Oxford clock striking four o'clock.                                                                                ::
    ID: 07016096.wav
    Length: 17
** University College, Oxford clock striking three o'clock.                                                                                ::
    ID: 07016095.wav
    Length: 14
** University College, Oxford clock striking two o'clock.                                                                                ::
    ID: 07016094.wav
    Length: 10
** University College, Oxford clock striking one o'clock.                                                                                ::
    ID: 07016093.wav
    Length: 11
** University College, Oxford clock striking twelve o'clock.                                                                                ::
    ID: 07016092.wav
    Length: 42
** University College, Oxford clock striking eleven o'clock.                                                                                ::
    ID: 07016091.wav
    Length: 39
** University College, Oxford clock striking ten o'clock.                                                                                ::
    ID: 07016090.wav
    Length: 36
** Oriel College clock striking nine o'clock.                                                                                ::
    ID: 07016089.wav
    Length: 23
** Oriel College clock striking eight o'clock.                                                                                ::
    ID: 07016088.wav
    Length: 21
** Oriel College clock striking seven o'clock.                                                                                ::
    ID: 07016087.wav
    Length: 19
** Oriel College clock striking six o'clock.                                                                                ::
    ID: 07016086.wav
    Length: 18
** Oriel College clock striking five o'clock.                                                                                ::
    ID: 07016085.wav
    Length: 16
** Oriel College clock striking four o'clock.                                                                                ::
    ID: 07016084.wav
    Length: 14
** Oriel College clock striking three o'clock.                                                                                ::
    ID: 07016083.wav
    Length: 14
** Oriel College clock striking two o'clock.                                                                                ::
    ID: 07016082.wav
    Length: 12
** Oriel College clock striking one o'clock.                                                                                ::
    ID: 07016081.wav
    Length: 9
** Oriel College clock striking twelve o'clock.                                                                                ::
    ID: 07016080.wav
    Length: 27
** Oriel College clock striking eleven o'clock.                                                                                ::
    ID: 07016079.wav
    Length: 25
** Oriel College clock striking ten o'clock.                                                                                ::
    ID: 07016078.wav
    Length: 24
** Oriel College clock ticking.                                                                                ::
    ID: 07016077.wav
    Length: 166
** Trinity College clock ticking.                                                                                ::
    ID: 07016076.wav
    Length: 184
** Trinity College clock striking twelve o'clock.                                                                                ::
    ID: 07016075.wav
    Length: 40
** Trinity College clock striking eleven o'clock.                                                                                ::
    ID: 07016074.wav
    Length: 38
** Trinity College clock striking ten o'clock.                                                                                ::
    ID: 07016073.wav
    Length: 36
** Trinity College clock striking nine o'clock.                                                                                ::
    ID: 07016072.wav
    Length: 35
** Trinity College clock striking eight o'clock.                                                                                ::
    ID: 07016071.wav
    Length: 33
** Trinity College clock striking seven o'clock.                                                                                ::
    ID: 07016070.wav
    Length: 30
** Trinity College clock striking six o'clock.                                                                                ::
    ID: 07016069.wav
    Length: 28
** Trinity College clock striking five o'clock.                                                                                ::
    ID: 07016068.wav
    Length: 26
** Trinity College clock striking four o'clock.                                                                                ::
    ID: 07016067.wav
    Length: 24
** Trinity College clock striking three o'clock.                                                                                ::
    ID: 07016066.wav
    Length: 23
** Trinity College clock striking two o'clock.                                                                                ::
    ID: 07016065.wav
    Length: 20
** Trinity College clock striking one o'clock.                                                                                ::
    ID: 07016064.wav
    Length: 18
** Trinity College clock striking quarter to the hour.                                                                                ::
    ID: 07016063.wav
    Length: 14
** Trinity College clock striking half past the hour.                                                                                ::
    ID: 07016062.wav
    Length: 10
** Trinity College clock striking quarter past the hour.                                                                                ::
    ID: 07016061.wav
    Length: 10
** Clock of the University Church of St Mary the Virgin, Oxford striking twelve o'clock.                                                                                ::
    ID: 07016060.wav
    Length: 62
** Clock of the University Church of St Mary the Virgin, Oxford striking eleven o'clock.                                                                                ::
    ID: 07016059.wav
    Length: 59
** Clock of the University Church of St Mary the Virgin, Oxford striking ten o'clock.                                                                                ::
    ID: 07016058.wav
    Length: 56
** Clock of the University Church of St Mary the Virgin, Oxford striking nine o'clock.                                                                                ::
    ID: 07016057.wav
    Length: 52
** Clock of the University Church of St Mary the Virgin, Oxford striking eight o'clock.                                                                                ::
    ID: 07016056.wav
    Length: 50
** Clock of the University Church of St Mary the Virgin, Oxford striking seven o'clock.                                                                                ::
    ID: 07016055.wav
    Length: 48
** Clock of the University Church of St Mary the Virgin, Oxford striking six o'clock.                                                                                ::
    ID: 07016054.wav
    Length: 44
** Clock of the University Church of St Mary the Virgin, Oxford striking five o'clock.                                                                                ::
    ID: 07016053.wav
    Length: 41
** Clock of the University Church of St Mary the Virgin, Oxford striking four o'clock.                                                                                ::
    ID: 07016052.wav
    Length: 39
** Clock of the University Church of St Mary the Virgin, Oxford striking three o'clock.                                                                                ::
    ID: 07016051.wav
    Length: 36
** Clock of the University Church of St Mary the Virgin, Oxford striking two o'clock.                                                                                ::
    ID: 07016050.wav
    Length: 33
** Clock of the University Church of St Mary the Virgin, Oxford striking one o'clock.                                                                                ::
    ID: 07016049.wav
    Length: 30
** Clock of the University Church of St Mary the Virgin, Oxford striking quarter to the hour.                                                                                ::
    ID: 07016048.wav
    Length: 18
** Clock of the University Church of St Mary the Virgin, Oxford striking half past the hour.                                                                                ::
    ID: 07016047.wav
    Length: 17
** Clock of the University Church of St Mary the Virgin, Oxford striking quarter past the hour.                                                                                ::
    ID: 07016046.wav
    Length: 12
** Queens College clock striking twelve o'clock.                                                                                ::
    ID: 07016045.wav
    Length: 56
** Queens College clock striking eleven o'clock.                                                                                ::
    ID: 07016044.wav
    Length: 52
** Queens College clock striking ten o'clock.                                                                                ::
    ID: 07016043.wav
    Length: 51
** Queens College clock striking nine o'clock.                                                                                ::
    ID: 07016042.wav
    Length: 46
** Queens College clock striking eight o'clock.                                                                                ::
    ID: 07016041.wav
    Length: 44
** Queens College clock striking seven o'clock.                                                                                ::
    ID: 07016040.wav
    Length: 41
** Queens College clock striking six o'clock.                                                                                ::
    ID: 07016039.wav
    Length: 38
** Queens College clock striking five o'clock.                                                                                ::
    ID: 07016038.wav
    Length: 36
** Queens College clock striking four o'clock.                                                                                ::
    ID: 07016037.wav
    Length: 33
** Queens College clock striking three o'clock.                                                                                ::
    ID: 07016036.wav
    Length: 31
** Queens College clock striking two o'clock.                                                                                ::
    ID: 07016035.wav
    Length: 28
** Queens College clock striking one o'clock.                                                                                ::
    ID: 07016034.wav
    Length: 25
** Queens College clock striking quarter to the hour.                                                                                ::
    ID: 07016033.wav
    Length: 15
** Queens College clock striking half past the hour.                                                                                ::
    ID: 07016032.wav
    Length: 12
** Queens College clock striking quarter past the hour.                                                                                ::
    ID: 07016031.wav
    Length: 9
** Merton College clock striking twelve o'clock.                                                                                ::
    ID: 07016030.wav
    Length: 82
** Merton College clock striking eleven o'clock.                                                                                ::
    ID: 07016029.wav
    Length: 78
** Merton College clock striking ten o'clock.                                                                                ::
    ID: 07016028.wav
    Length: 71
** Merton College clock striking nine o'clock.                                                                                ::
    ID: 07016027.wav
    Length: 68
** Merton College clock striking eight o'clock.                                                                                ::
    ID: 07016026.wav
    Length: 66
** Merton College clock striking seven o'clock.                                                                                ::
    ID: 07016025.wav
    Length: 65
** Merton College clock striking six o'clock.                                                                                ::
    ID: 07016024.wav
    Length: 63
** Merton College clock striking five o'clock.                                                                                ::
    ID: 07016023.wav
    Length: 58
** Merton College clock striking four o'clock.                                                                                ::
    ID: 07016022.wav
    Length: 56
** Merton College clock striking three o'clock.                                                                                ::
    ID: 07016021.wav
    Length: 54
** Merton College clock striking two o'clock.                                                                                ::
    ID: 07016020.wav
    Length: 50
** Merton College clock striking one o'clock.                                                                                ::
    ID: 07016019.wav
    Length: 48
** Merton College clock striking quarter to the hour.                                                                                ::
    ID: 07016018.wav
    Length: 34
** Merton College clock striking half past the hour.                                                                                ::
    ID: 07016017.wav
    Length: 27
** Merton College clock striking quarter past the hour.                                                                                ::
    ID: 07016016.wav
    Length: 21
** Magdalen College clock striking twelve o'clock.                                                                                ::
    ID: 07016015.wav
    Length: 62
** Magdalen College clock striking eleven o'clock.                                                                                ::
    ID: 07016014.wav
    Length: 60
** Magdalen College clock striking ten o'clock.                                                                                ::
    ID: 07016013.wav
    Length: 57
** Magdalen College clock striking nine o'clock.                                                                                ::
    ID: 07016012.wav
    Length: 54
** Magdalen College clock striking eight o'clock.                                                                                ::
    ID: 07016011.wav
    Length: 51
** Magdalen College clock striking seven o'clock.                                                                                ::
    ID: 07016010.wav
    Length: 47
** Magdalen College clock striking six o'clock.                                                                                ::
    ID: 07016009.wav
    Length: 44
** Magdalen College clock striking five o'clock.                                                                                ::
    ID: 07016008.wav
    Length: 42
** Magdalen College clock striking four o'clock.                                                                                ::
    ID: 07016007.wav
    Length: 40
** Magdalen College clock striking three o'clock.                                                                                ::
    ID: 07016006.wav
    Length: 37
** Magdalen College clock striking two o'clock.                                                                                ::
    ID: 07016005.wav
    Length: 35
** Magdalen College clock striking one o'clock.                                                                                ::
    ID: 07016004.wav
    Length: 32
** Magdalen College clock striking quarter to the hour.                                                                                ::
    ID: 07016003.wav
    Length: 22
** Magdalen College clock striking half past the hour.                                                                                ::
    ID: 07016002.wav
    Length: 18
** Magdalen College clock striking quarter past the hour.                                                                                ::
    ID: 07016001.wav
    Length: 17
** Triumph 650cc twin, approach, stop, tickover, depart                                                                                ::
    ID: 07015201.wav
    Length: 55
** Triumph 650cc twin, several machines approach and stop.                                                                                ::
    ID: 07015200.wav
    Length: 65
** Triumph 650cc twin, approach, stop, switch off.                                                                                ::
    ID: 07015199.wav
    Length: 20
** Triumph 650cc twin, approach, turn, switch off.                                                                                ::
    ID: 07015198.wav
    Length: 27
** Triumph 650cc twin, approach, stop, switch off.                                                                                ::
    ID: 07015197.wav
    Length: 18
** Triumph 650cc twin, approach, stop, switch off.                                                                                ::
    ID: 07015196.wav
    Length: 21
** Triumph 650cc twin, several machines depart.                                                                                ::
    ID: 07015195.wav
    Length: 31
** Triumph 650cc twin, two machines start and depart (revving)                                                                                ::
    ID: 07015194.wav
    Length: 29
** Triumph 650cc twin, start, revving, depart fast.                                                                                ::
    ID: 07015193.wav
    Length: 31
** Triumph 650cc twin, start, turn and depart.                                                                                ::
    ID: 07015192.wav
    Length: 36
** Triumph 650cc twin, start & depart (revving)                                                                                ::
    ID: 07015191.wav
    Length: 25
** Triumph 650cc twin, start & depart.                                                                                ::
    ID: 07015190.wav
    Length: 33
** Triumph 650cc twin, several machines revving.                                                                                ::
    ID: 07015189.wav
    Length: 416
** Triumph 650cc twin, start, tickover, revving, switch off.                                                                                ::
    ID: 07015188.wav
    Length: 98
** Triumph 650cc twin, start, revving, switch off.                                                                                ::
    ID: 07015187.wav
    Length: 116
** Triumph 650cc twin, start, revving, switch off.                                                                                ::
    ID: 07015186.wav
    Length: 55
** Triumph 650cc twin, start, revving, switch off.                                                                                ::
    ID: 07015185.wav
    Length: 115
** Norton 500cc, passing at fast speed.                                                                                ::
    ID: 07015184.wav
    Length: 17
** Norton 500cc, passing at fast speed.                                                                                ::
    ID: 07015183.wav
    Length: 18
** Norton 500cc, passing at medium speed.                                                                                ::
    ID: 07015182.wav
    Length: 18
** Norton 500cc, passing slowly.                                                                                ::
    ID: 07015181.wav
    Length: 20
** Norton 500cc, approach, tickover, depart.                                                                                ::
    ID: 07015180.wav
    Length: 45
** Norton 500cc, approach, tickover, depart.                                                                                ::
    ID: 07015179.wav
    Length: 43
** Norton 500cc, approach, stop, switch off.                                                                                ::
    ID: 07015178.wav
    Length: 22
** Norton 500cc, approach, stop, switch off.                                                                                ::
    ID: 07015177.wav
    Length: 27
** Norton 500cc, start, tickover, depart.                                                                                ::
    ID: 07015176.wav
    Length: 22
** Norton 500cc, start, tickover, depart.                                                                                ::
    ID: 07015175.wav
    Length: 22
** Norton 500cc, start, tickover, switch off.                                                                                ::
    ID: 07015174.wav
    Length: 145
** Norton 500cc, false starts.                                                                                ::
    ID: 07015173.wav
    Length: 17
** Triumph 650cc twin, start up, medium speed run in traffic, stop. (Recorded on machine)                                                                                ::
    ID: 07015172.wav
    Length: 243
** Triumph 650cc twin, start up, medium speed run, stop. (Recorded on machine)                                                                                ::
    ID: 07015171.wav
    Length: 76
** Triumph 650cc twin, passing at speed.                                                                                ::
    ID: 07015170.wav
    Length: 23
** Triumph 650cc twin, passing.                                                                                ::
    ID: 07015169.wav
    Length: 21
** Triumph 650cc twin, approach, stop, switch off.                                                                                ::
    ID: 07015168.wav
    Length: 29
** Triumph 650cc twin, approach, stop, switch off.                                                                                ::
    ID: 07015167.wav
    Length: 31
** Triumph 650cc twin, start and depart.                                                                                ::
    ID: 07015166.wav
    Length: 23
** Triumph 650cc twin, start, tickover, depart.                                                                                ::
    ID: 07015165.wav
    Length: 22
** Triumph 650cc twin, start, tickover, switch off.                                                                                ::
    ID: 07015164.wav
    Length: 145
** Triumph 650cc twin, false starts.                                                                                ::
    ID: 07015163.wav
    Length: 32
** Constant sound of paddles. (2,400 h.p. paddle steamer. On deck)                                                                                ::
    ID: 07015162.wav
    Length: 124
** Vessel leaving pier. (2,400 h.p. paddle steamer. On pier)                                                                                ::
    ID: 07015161.wav
    Length: 83
** Vessel approaching pier. (2,400 h.p. paddle steamer. On pier)                                                                                ::
    ID: 07015160.wav
    Length: 178
** Telegraph bell signals. Slow engines, various bell sequences. Engines gather speed.                                                                                ::
    ID: 07015159.wav
    Length: 122
** Telegraph bell signals. Full ahead.                                                                                  ::
    ID: 07015158.wav
    Length: 138
** Telegraph bell signals. Ahead.                                                                                 ::
    ID: 07015157.wav
    Length: 73
** Telegraph bell signals. Going astern.                                                                                 ::
    ID: 07015156.wav
    Length: 52
** Atmosphere in engine room with engines idling (On board a 2,400 h.p. Paddle Steamer)                                                                                ::
    ID: 07015155.wav
    Length: 142
** Interior, sound of engines as heard from empty saloon with some distant voices. (On board a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015154.wav
    Length: 244
** Interior, general atmosphere in engine room. (On board a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015153.wav
    Length: 394
** Constant sound of paddles recorded in paddle chamber. (On board a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015152.wav
    Length: 153
** Bow wave with engine in background. (On board a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015151.wav
    Length: 241
** Vessel leaving pier, 'full speed ahead' on telegraph, signal bell at 1'25". (On board a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015150.wav
    Length: 258
** Vessel arriving at pier, starts with telegraph bell. (On board a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015149.wav
    Length: 138
** Exterior, vessel leaving with sound of paddles and ship's telegraph. (On board a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015148.wav
    Length: 364
** Exterior, passengers embarking with sound of general chatter and activity. (On deck of a 2,400 h.p. paddle steamer)                                                                                ::
    ID: 07015147.wav
    Length: 403
** Major water pump starts, hoses play, pump switched off.                                                                                ::
    ID: 07015146.wav
    Length: 370
** Scene of fire, general activity.                                                                                ::
    ID: 07015145.wav
    Length: 164
** Fire engine passing fast with horn.                                                                                ::
    ID: 07015144.wav
    Length: 31
** Fire engine passing slowly with bell.                                                                                ::
    ID: 07015143.wav
    Length: 62
** Fire engine arrives with horn.                                                                                ::
    ID: 07015142.wav
    Length: 37
** Fire engine departs with horn.                                                                                ::
    ID: 07015141.wav
    Length: 29
** Three fire engines passing fast. (With 2-tone horns.)                                                                                ::
    ID: 07015140.wav
    Length: 43
** Three fire engines passing medium-fast. (With 2-tone horns.)                                                                                ::
    ID: 07015139.wav
    Length: 45
** Three fire engines passing slowly. (With bells and horns.)                                                                                ::
    ID: 07015138.wav
    Length: 66
** Three fire engines approach and stop (With 2-tone horns.)                                                                                ::
    ID: 07015137.wav
    Length: 52
** Three fire engines depart. (With 2-tone horns.)                                                                                ::
    ID: 07015136.wav
    Length: 47
** Three fire engines depart (With 2-tone horns.)                                                                                ::
    ID: 07015135.wav
    Length: 42
** Fire engines being parked in station area, with directions given.                                                                                ::
    ID: 07015134.wav
    Length: 173
** Fire station, bell, men turn out, fire engines depart.                                                                                ::
    ID: 07015133.wav
    Length: 68
** Fire station, bells for turn out to fire. (Close perspective, no speech.)                                                                                ::
    ID: 07015132.wav
    Length: 30
** Ambulance, interior, starts and moves off into constant run with horn, stop, tickover, doors, stretchers taken out. (As heard by patient.) (Bedford ambulance.)                                                                                ::
    ID: 07015131.wav
    Length: 224
** Ambulance, interior, starts and moves into constant run with bell, stops. (As heard by patient.) (Bedford ambulance.)                                                                                ::
    ID: 07015130.wav
    Length: 216
** Ambulance, interior, starts, and moves off. (As heard by patient.) (Bedford ambulance.)                                                                                ::
    ID: 07015129.wav
    Length: 216
** Ambulance, interior, starts, ticks over and moves off. (Recorded in cab.) (Bedford ambulance.)                                                                                ::
    ID: 07015128.wav
    Length: 220
** Ambulance, interior, start, run with horn, stop. (Austin Automatic ambulance.)                                                                                ::
    ID: 07015127.wav
    Length: 94
** Ambulance, exterior, stretchers wheeled out. (No ambulance sounds.) (Bedford ambulance.)                                                                                ::
    ID: 07015126.wav
    Length: 32
** Ambulance, exterior, horn only. (No ambulance sounds, close perspective.) (Bedford ambulance.)                                                                                ::
    ID: 07015125.wav
    Length: 50
** Ambulance, exterior, bell only. (No ambulance sounds, close perspective.) (Bedford ambulance.)                                                                                ::
    ID: 07015124.wav
    Length: 51
** Ambulance, exterior, starts and ticks over. (Bedford ambulance.)                                                                                ::
    ID: 07015123.wav
    Length: 125
** Ambulance, exterior, one passing. (With horn.) (Bedford ambulance.)                                                                                ::
    ID: 07015122.wav
    Length: 22
** Ambulance, exterior, passing. (With horn.) (Bedford ambulance.)                                                                                ::
    ID: 07015121.wav
    Length: 25
** Ambulance, exterior, approaches and stops, doors, stretchers taken out. (With horn.) (Bedford ambulance.)                                                                                ::
    ID: 07015120.wav
    Length: 57
** Ambulance, exterior, approaches and stops, doors, stretchers taken out. (With horn.) (Bedford ambulance.)                                                                                ::
    ID: 07015119.wav
    Length: 47
** Ambulance, exterior, departs. (With horn.) (Bedford ambulance.)                                                                                ::
    ID: 07015118.wav
    Length: 20
** Ambulance, exterior, starts and departs. (With horn.) (Bedford ambulance.)                                                                                ::
    ID: 07015117.wav
    Length: 21
** Ambulance, exterior, passing. (With horn.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015116.wav
    Length: 28
** Ambulance, exterior, passing. (With horn.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015115.wav
    Length: 28
** Ambulance, exterior, approaches and stops, doors, stretchers taken out. (With horn.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015114.wav
    Length: 42
** Ambulance, exterior, approaches and stops, doors, stretchers taken out. (With horn.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015113.wav
    Length: 40
** Ambulance, exterior, departs. (With horn.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015112.wav
    Length: 16
** Ambulance, exterior, doors, start, depart, (With horn.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015111.wav
    Length: 30
** Ambulance, exterior, passing. (With bell.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015110.wav
    Length: 24
** Ambulance, exterior, passing. (With bell.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015109.wav
    Length: 19
** Ambulance, exterior, approaches, stops, doors, stretcher taken out. (With bell.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015108.wav
    Length: 39
** Ambulance, exterior, approaches and stops, doors. (With bell.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015107.wav
    Length: 33
** Ambulance, exterior, one departs. (With bell.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015106.wav
    Length: 23
** Ambulance, exterior, doors, starts and departs. (With bell.) (Austin Automatic ambulance.)                                                                                ::
    ID: 07015105.wav
    Length: 29
** Police car, interior, starts, medium-speed run in town with signals, as on patrol, stop. (Jaguar police car.)                                                                                ::
    ID: 07015104.wav
    Length: 411
** Police car, interior, starts, run in town without signals, stop. (Jaguar police car.)                                                                                ::
    ID: 07015103.wav
    Length: 368
** Police car, interior, starts, run with horn and stops. (Jaguar police car.)                                                                                ::
    ID: 07015102.wav
    Length: 215
** Police car, interior, starts, runs with bell and stops. (Jaguar police car.)                                                                                ::
    ID: 07015101.wav
    Length: 175
** Police car, interior, horn on its own. (Jaguar police car.)                                                                                ::
    ID: 07015100.wav
    Length: 120
** Police car, interior, bell on its own. (Jaguar police car.)                                                                                ::
    ID: 07015099.wav
    Length: 122
** Police car, interior, starts and ticks over. (Jaguar police car.)                                                                                ::
    ID: 07015098.wav
    Length: 118
** Police car, exterior, passing. (With bell)                                                                                ::
    ID: 07015097.wav
    Length: 29
** Police car, exterior, passing. (With bell)                                                                                ::
    ID: 07015096.wav
    Length: 28
** Police car, exterior, arrives and stops. (With bell)                                                                                ::
    ID: 07015095.wav
    Length: 16
** Police car, exterior, arrives and stops. (With bell)                                                                                ::
    ID: 07015094.wav
    Length: 16
** Police car, exterior, starts and departs. (With bell)                                                                                ::
    ID: 07015093.wav
    Length: 18
** Police car, exterior, starts and departs. (With bell)                                                                                ::
    ID: 07015092.wav
    Length: 24
** Police car, exterior, passing. (With two-tone horn)                                                                                ::
    ID: 07015091.wav
    Length: 31
** Police car, exterior, passing. (With two-tone horn)                                                                                ::
    ID: 07015090.wav
    Length: 24
** Police car, exterior, arrives and stops. (With two-tone horn)                                                                                ::
    ID: 07015089.wav
    Length: 21
** Police car, exterior, arrives and stops. (With two-tone horn)                                                                                ::
    ID: 07015088.wav
    Length: 23
** Police car, exterior, self-starts and departs. (With two-tone horn)                                                                                ::
    ID: 07015087.wav
    Length: 22
** Police car, exterior, starts, ticks over and departs. (With two-tone horn)                                                                                ::
    ID: 07015086.wav
    Length: 34
** Fire engine, interior, start, run, stop. (Recorded on board vehicle)                                                                                ::
    ID: 07015085.wav
    Length: 138
** Fire engine approaches and stops.                                                                                ::
    ID: 07015084.wav
    Length: 57
** Fire engine makes long approach, passes and stops, activity.                                                                                ::
    ID: 07015083.wav
    Length: 93
** Fire engine passing.                                                                                ::
    ID: 07015082.wav
    Length: 48
** Fire engine passing.                                                                                ::
    ID: 07015081.wav
    Length: 35
** Fire engine departs.                                                                                ::
    ID: 07015080.wav
    Length: 32
** Fire station bell sounds, fire engine departs.                                                                                ::
    ID: 07015079.wav
    Length: 64
** German ambulance arrives, activity, departs with martinhorn.                                                                                ::
    ID: 07015078.wav
    Length: 84
** German police car departs with martinhorn.                                                                                ::
    ID: 07015077.wav
    Length: 15
** German police car approaches and stops with martinhorn.                                                                                ::
    ID: 07015076.wav
    Length: 13
** German police car, stationary with martinhorn.                                                                                ::
    ID: 07015075.wav
    Length: 25
** German police car on constant run, with martinhorn.                                                                                ::
    ID: 07015074.wav
    Length: 36
** German fire engine approaches & passes with horn.                                                                                ::
    ID: 07015073.wav
    Length: 43
** German fire engine approaches & passes with bell.                                                                                ::
    ID: 07015072.wav
    Length: 41
** German fire engine approaches & passes with horn and bell.                                                                                ::
    ID: 07015071.wav
    Length: 37
** German fire engine arriving at scene of fire, activity and speech.                                                                                ::
    ID: 07015070.wav
    Length: 221
** German fire engine with bells ringing leaving fire station. (Some speech.)                                                                                ::
    ID: 07015069.wav
    Length: 57
** Brno Cathedral bells ringing. (Bells c. 17th century.)                                                                                ::
    ID: 07015068.wav
    Length: 120
** Domazlice Cathedral bells ringing. (Bells c. 1747)                                                                                ::
    ID: 07015067.wav
    Length: 121
** Cesky Budejovice Dominican monastery, bells of Black Tower, with start & stop.                                                                                ::
    ID: 07015066.wav
    Length: 130
** Cesky Krumlov, 12th century castle bells ringing.                                                                                ::
    ID: 07015065.wav
    Length: 122
** St. Georges Church, Rip, bell tolling. (Also known as 'Bell of Legendary Mountain', c. 1126.)                                                                                ::
    ID: 07015064.wav
    Length: 123
** St. Vidus Cathedral, Prague, Zigmund bell tolling.                                                                                ::
    ID: 07015063.wav
    Length: 123
** Dublin Cathedral, Single tenor bell tolling.                                                                                ::
    ID: 07015062.wav
    Length: 362
** St. Nicholas Church, Hamburg, single tenor bell tolling.                                                                                ::
    ID: 07015061.wav
    Length: 364
** Cologne Cathedral, single bell tolling.                                                                                ::
    ID: 07015060.wav
    Length: 364
** Stradkirche, Bad-Segeburg, single bell tolling.                                                                                ::
    ID: 07015059.wav
    Length: 365
** Berlin Freedom Bell, single bell tolling.                                                                                ::
    ID: 07015058.wav
    Length: 100
** St. Michael's Church, Hamburg, bell ringing ends.                                                                                ::
    ID: 07015057.wav
    Length: 100
** St. Michael's Church, Hamburg, bell ringing starts and builds up.                                                                                ::
    ID: 07015056.wav
    Length: 138
** St. Michael's Church, Hamburg, bells ringing.                                                                                ::
    ID: 07015055.wav
    Length: 366
** Church bells ringing. (Unidentified foreign location.)                                                                                ::
    ID: 07015054.wav
    Length: 322
** Bells ringing at St. Nicholas Church, Alsterdorf.                                                                                ::
    ID: 07015053.wav
    Length: 365
** Salzburg Cathedral bells ringing.                                                                                ::
    ID: 07015052.wav
    Length: 305
** Munster Cathedral bells ringing.                                                                                ::
    ID: 07015051.wav
    Length: 366
** Aachen Cathedral bells ringing.                                                                                ::
    ID: 07015050.wav
    Length: 366
** Cologne Cathedral bells ringing.                                                                                ::
    ID: 07015049.wav
    Length: 348
** Ethiopia, chatter outside hut in Anuak language.                                                                                ::
    ID: 07015048.wav
    Length: 187
** Ethiopia, crowd singing & dancing with tom-tom drum accompaniment.                                                                                ::
    ID: 07015047.wav
    Length: 187
** Ethiopia, women washing at well. (Quiet.)                                                                                ::
    ID: 07015046.wav
    Length: 183
** Ethiopia, women washing at well.                                                                                ::
    ID: 07015045.wav
    Length: 189
** Ethiopia, small crowd in local cafe, distinct speech & occasional singing in Amharic & Galligna languages.                                                                                ::
    ID: 07015044.wav
    Length: 322
** Ethiopia, village centre, general atmosphere with indistinct Galligna speech.                                                                                ::
    ID: 07015043.wav
    Length: 182
** Southern Ethiopia, herd boys & camels, with occasional commands & whistles.                                                                                ::
    ID: 07015042.wav
    Length: 191
** Ethiopia, village market atmosphere.                                                                                ::
    ID: 07015041.wav
    Length: 192
** Ethiopia, exterior, small group of people talking in Somali language.                                                                                ::
    ID: 07015040.wav
    Length: 198
** Ethiopia, interior, small group of men talking in Amharic language.                                                                                ::
    ID: 07015039.wav
    Length: 382
** Downtown Lagos, busy traffic & crowd atmosphere                                                                                ::
    ID: 07015038.wav
    Length: 75
** Lagos, native quarter with traffic & crowd atmosphere.                                                                                ::
    ID: 07015037.wav
    Length: 99
** Nigeria, excited crowd.                                                                                ::
    ID: 07015036.wav
    Length: 32
** Nigeria, village welcome, singing with tom-tom drum accompaniment.                                                                                ::
    ID: 07015035.wav
    Length: 67
** Nigeria, village chatter, medium-sized crowd.                                                                                ::
    ID: 07015034.wav
    Length: 80
** Nigeria, large crowd cheering.                                                                                ::
    ID: 07015033.wav
    Length: 22
** Nigeria, large mixed crowd, distant traffic. (Tom-tom drums audible from 1'20" to end.)                                                                                ::
    ID: 07015032.wav
    Length: 193
** Nigeria, large crowd, mixed chatter.                                                                                ::
    ID: 07015031.wav
    Length: 80
** Nigeria, speech with tom-tom drums.                                                                                ::
    ID: 07015030.wav
    Length: 80
** Interior, conversational mixed speech, spoken in English with West Indian accent.                                                                                ::
    ID: 07015029.wav
    Length: 88
** Interior, subdued mixed conversation, spoken in English with West Indian accent.                                                                                ::
    ID: 07015028.wav
    Length: 127
** Interior, cheerful mixed conversation, spoken in English with West Indian accent.                                                                                ::
    ID: 07015027.wav
    Length: 123
** Barbados, exterior, street atmosphere, with traffic & voices.                                                                                ::
    ID: 07015026.wav
    Length: 183
** Barbados, exterior, general atmosphere at bus stop, with speech & traffic.                                                                                ::
    ID: 07015025.wav
    Length: 187
** Beirut, busy road junction, with horns & crowd atmosphere.                                                                                ::
    ID: 07015024.wav
    Length: 402
** Beirut, traffic & crowds with occasional cries from newspaper sellers.                                                                                ::
    ID: 07015023.wav
    Length: 403
** Cairo, atmosphere in large hall.                                                                                ::
    ID: 07015022.wav
    Length: 389
** Israel, crowd atmosphere in a large communal hall.                                                                                ::
    ID: 07015021.wav
    Length: 196
** Israel, crowd atmosphere in cinema before performance.                                                                                ::
    ID: 07015020.wav
    Length: 202
** Helsinki, railway station atmosphere with trains arriving & departing, occasional public address.                                                                                ::
    ID: 07015019.wav
    Length: 393
** Helsinki, busy street market atmosphere with traffic.                                                                                ::
    ID: 07015018.wav
    Length: 395
** Valletta, crowds promending. with tolling bells.                                                                                ::
    ID: 07015017.wav
    Length: 393
** Valletta, crowds promending.                                                                                ::
    ID: 07015016.wav
    Length: 394
** Tangier, atmosphere in Casbah market.                                                                                ::
    ID: 07015015.wav
    Length: 154
** Tangier, atmosphere in fruit market.                                                                                ::
    ID: 07015014.wav
    Length: 157
** Tangier, blind beggar actuality.                                                                                ::
    ID: 07015013.wav
    Length: 60
** Tangier, tourist cafe general atmosphere.                                                                                ::
    ID: 07015012.wav
    Length: 211
** Tangier, tourist cafe general atmosphere.                                                                                ::
    ID: 07015011.wav
    Length: 221
** Kano, Nigeria, crowd leaving mosque, busy atmosphere with some children.                                                                                ::
    ID: 07015010.wav
    Length: 207
** Macao, junk village, crowd atmosphere with occasional traffic.                                                                                ::
    ID: 07015009.wav
    Length: 213
** Vietnam, Tiger Street Market, busy crowd atmosphere.                                                                                ::
    ID: 07015008.wav
    Length: 212
** Vietnam, crowd at checkpoint, some birdsong.                                                                                ::
    ID: 07015007.wav
    Length: 211
** Beirut clothes market, crowd atmosphere with occasional cries from stall holders.                                                                                ::
    ID: 07015006.wav
    Length: 208
** Beirut fruit market, busy crowd atmosphere with some distinct speech.                                                                                ::
    ID: 07015005.wav
    Length: 206
** Beirut restaurant, indistinct speech with crockery sounds.                                                                                ::
    ID: 07015004.wav
    Length: 210
** Beirut vegetable market, busy crowd atmosphere with stall holders' cries.                                                                                ::
    ID: 07015003.wav
    Length: 227
** Busy side street in Middle Eastern town, with traffic, pauses & occasional speech. (Excact location unknown.)                                                                                ::
    ID: 07015002.wav
    Length: 366
** Busy traffic in Middle Eastern town, with pauses, horns, speech. (Wide perspective recording, exact location unknown.)                                                                                ::
    ID: 07015001.wav
    Length: 372
** Many bicycles passing, with some birdsong. (Racing model c. 1983.)                                                                                ::
    ID: 07014201.wav
    Length: 322
** Bicycle passing with bell, with some birdsong. (Model c. 1936.)                                                                                ::
    ID: 07014200.wav
    Length: 7
** Bicycle passing with bell, with some birdsong. (Model c. 1936.)                                                                                ::
    ID: 07014199.wav
    Length: 8
** Bicycle passing through puddle, with some birdsong. (Model c. 1936.)                                                                                ::
    ID: 07014198.wav
    Length: 8
** Bicycle passing through puddle, with some birdsong. (Model c. 1936.)                                                                                ::
    ID: 07014197.wav
    Length: 12
** Bicycle passing on gravel, with some birdsong. (Model c. 1936.)                                                                                ::
    ID: 07014196.wav
    Length: 7
** Bicycle passing on gravel, with some birdsong. (Model c. 1936.)                                                                                ::
    ID: 07014195.wav
    Length: 13
** Bicycle pedalling and freewheeling. (Straight handle barred model, c. 1936.)                                                                                ::
    ID: 07014194.wav
    Length: 437
** Bulldozer, starting up, earth moving. (Tracked vehicle.)                                                                                ::
    ID: 07014193.wav
    Length: 202
** Bulldozer, approaching, stopping, switching off. (Tracked vehicle.)                                                                                ::
    ID: 07014192.wav
    Length: 40
** Bulldozer, starting, ticking over, driving away. (Tracked vehicle.)                                                                                ::
    ID: 07014191.wav
    Length: 136
** Mechanical digger, working close. (Four wheeled vehicle.)                                                                                ::
    ID: 07014190.wav
    Length: 47
** Mechanical digger, digging concrete. (Four wheeled vehicle, recorded close to bucket.)                                                                                ::
    ID: 07014189.wav
    Length: 94
** Mechanical digger, digging soft ground. (Four wheeled vehicle, recorded close to bucket.)                                                                                ::
    ID: 07014188.wav
    Length: 93
** Mechanical digger, approaching & passing. (Four wheeled vehicle.)                                                                                ::
    ID: 07014187.wav
    Length: 54
** Mechanical digger, shutdown. (Four wheeled vehicle.)                                                                                ::
    ID: 07014186.wav
    Length: 14
** Mechanical digger, start up & tickover. (Four wheeled vehicle.)                                                                                ::
    ID: 07014185.wav
    Length: 64
** Apricot portable micro computer, machine hum at high level. (1985 model.)                                                                                ::
    ID: 07014184.wav
    Length: 93
** Apricot portable micro computer, single data entry. (1985 model.)                                                                                ::
    ID: 07014183.wav
    Length: 8
** Apricot portable micro computer, disk unloaded, switch off. (1985 model.)                                                                                ::
    ID: 07014182.wav
    Length: 8
** Apricot portable micro computer, disk unloaded. (1985 model.)                                                                                ::
    ID: 07014181.wav
    Length: 6
** Apricot portable micro computer, disk loaded. (1985 model.)                                                                                ::
    ID: 07014180.wav
    Length: 9
** Apricot portable micro computer, switch on. (1985 model.)                                                                                ::
    ID: 07014179.wav
    Length: 6
** Apricot portable micro computer, switch on, disk loaded, machine boots & operator runs programme. (1985 model.)                                                                                ::
    ID: 07014178.wav
    Length: 397
** Electronic game, Space Invaders. (NB track is mono.)                                                                                ::
    ID: 07014177.wav
    Length: 173
** Gentle alarm. (Specially created electronic sound.)                                                                                ::
    ID: 07014176.wav
    Length: 124
** Urgent alarm, with acceleration. (Specially created electronic sound.)                                                                                ::
    ID: 07014175.wav
    Length: 94
** Accelerating alarm. (Specially created electronic sound.)                                                                                ::
    ID: 07014174.wav
    Length: 32
** Three harmonic stings. (Specially created electronic sound.)                                                                                ::
    ID: 07014173.wav
    Length: 6
** Rapid click sequence. (Specially created electronic sound.)                                                                                ::
    ID: 07014172.wav
    Length: 14
** Rapid bleep sequence. (Specially created electronic sound.)                                                                                ::
    ID: 07014171.wav
    Length: 7
** Hollow sound, with buzz. (Specially created electronic sound.)                                                                                ::
    ID: 07014170.wav
    Length: 83
** Three high 'pings'. (Specially created electronic sound.)                                                                                ::
    ID: 07014169.wav
    Length: 7
** High pitched bleeps. (Pelican Crossing)                                                                                ::
    ID: 07014168.wav
    Length: 16
** Busy buzzing. (Specially created electronic sound.)                                                                                ::
    ID: 07014167.wav
    Length: 89
** Hum burst. (Specially created electronic sound.)                                                                                ::
    ID: 07014166.wav
    Length: 6
** Huge rumble. (Specially created electronic sound.)                                                                                ::
    ID: 07014165.wav
    Length: 12
** Gently pulsating humming. (Specially created electronic sound.)                                                                                ::
    ID: 07014164.wav
    Length: 214
** Grating noise, as of boat running aground. (Specially created electronic sound.)                                                                                ::
    ID: 07014163.wav
    Length: 12
** Sharp clunk. (Specially created electronic sound.)                                                                                ::
    ID: 07014162.wav
    Length: 6
** Medium pitched warble. (Specially created electronic sound.)                                                                                ::
    ID: 07014161.wav
    Length: 34
** Gong sounded. (Specially created electronic sound.)                                                                                ::
    ID: 07014160.wav
    Length: 33
** Roar, with tinkles over. (Specially created electronic sound.)                                                                                ::
    ID: 07014159.wav
    Length: 214
** Sharp hum, with variations. (Specially created electronic sound.)                                                                                ::
    ID: 07014158.wav
    Length: 39
** Sharp hum. (Specially created electronic sound.)                                                                                ::
    ID: 07014157.wav
    Length: 154
** Gentle hum, with start & stop. (Specially created electronic sound.)                                                                                ::
    ID: 07014156.wav
    Length: 84
** Rising pulses & bang. (Specially created electronic sound.)                                                                                ::
    ID: 07014155.wav
    Length: 23
** High pitched bleeps & warbles. (Specially created electronic sound.)                                                                                ::
    ID: 07014154.wav
    Length: 61
** Deep rumble. (Specially created electronic sound.)                                                                                ::
    ID: 07014153.wav
    Length: 19
** Sharp pulses increasing in speed. (Specially created electronic sound.)                                                                                ::
    ID: 07014152.wav
    Length: 35
** High pitched warble & sting. (Specially created electronic sound.)                                                                                ::
    ID: 07014151.wav
    Length: 12
** Laser guns, with hits. (Specially created electronic sound.)                                                                                ::
    ID: 07014150.wav
    Length: 7
** High pitched warble. (Specially created electronic sound.)                                                                                ::
    ID: 07014149.wav
    Length: 49
** Gas capsule. (Specially created electronic sound.)                                                                                ::
    ID: 07014148.wav
    Length: 25
** Two-pitched double warble. (Specially created electronic sound.)                                                                                ::
    ID: 07014147.wav
    Length: 15
** Varied hollow warble with start & stop. (Specially created electronic sound.)                                                                                ::
    ID: 07014146.wav
    Length: 59
** Hollow warble. (Specially created electronic sound.)                                                                                ::
    ID: 07014145.wav
    Length: 24
** Cavern door. (Specially created electronic sound.)                                                                                ::
    ID: 07014144.wav
    Length: 17
** Rise & fall. (Specially created electronic sound.)                                                                                ::
    ID: 07014143.wav
    Length: 13
** Rapid pulse. (Specially created electronic sound.)                                                                                ::
    ID: 07014142.wav
    Length: 11
** Urgent alarm gong. (Specially created electronic sound.)                                                                                ::
    ID: 07014141.wav
    Length: 32
** Heavy ray gun shots. (Specially created electronic sound.)                                                                                ::
    ID: 07014140.wav
    Length: 24
** Triple warble. (Specially created electronic sound.)                                                                                ::
    ID: 07014139.wav
    Length: 7
** Deep hum, repeated twice. (Specially created electronic sound.)                                                                                ::
    ID: 07014138.wav
    Length: 11
** Alarm sounded. (Specially created electronic sound.)                                                                                ::
    ID: 07014137.wav
    Length: 6
** Warble. (Specially created electronic sound.)                                                                                ::
    ID: 07014136.wav
    Length: 35
** Deep roar. (Specially created electronic sound.)                                                                                ::
    ID: 07014135.wav
    Length: 213
** Double pulse. (Specially created electronic sound.)                                                                                ::
    ID: 07014134.wav
    Length: 19
** Hand-held ray guns. (Specially created electronic sound.)                                                                                ::
    ID: 07014133.wav
    Length: 22
** Deep shimmer. (Specially created electronic sound.)                                                                                ::
    ID: 07014132.wav
    Length: 63
** Drop to lower shimmer. (Specially created electronic sound.)                                                                                ::
    ID: 07014131.wav
    Length: 63
** Shimmer. (Specially created electronic sound.)                                                                                ::
    ID: 07014130.wav
    Length: 44
** Light rumble. (Specially created electronic sound.)                                                                                ::
    ID: 07014129.wav
    Length: 34
** Rumble. (Specially created electronic sound.)                                                                                ::
    ID: 07014128.wav
    Length: 31
** Heavy motor hum with start & stop. (Specially created electronic sound.)                                                                                ::
    ID: 07014127.wav
    Length: 12
** Electronic alarm gong. (Specially created electronic sound.)                                                                                ::
    ID: 07014126.wav
    Length: 20
** Electronic engine with start & stop. (Specially created electronic sound.)                                                                                ::
    ID: 07014125.wav
    Length: 27
** Gentle bleeps. (Specially created electronic sound.)                                                                                ::
    ID: 07014124.wav
    Length: 12
** Gentle pulsations. (Specially created electronic sound.)                                                                                ::
    ID: 07014123.wav
    Length: 154
** Steady electronic motor hum. (Specially created electronic sound.)                                                                                ::
    ID: 07014122.wav
    Length: 61
** Spacecraft hit by plasma guns. (Specially created electronic sound.)                                                                                ::
    ID: 07014121.wav
    Length: 10
** Light electronic door, open & close. (Specially created electronic sound.)                                                                                ::
    ID: 07014120.wav
    Length: 11
** Heavy electronic door, open & close. (Specially created electronic sound.)                                                                                ::
    ID: 07014119.wav
    Length: 12
** Steady pulse stream. (Specially created electronic sound.)                                                                                ::
    ID: 07014118.wav
    Length: 12
** Long computer bleeps at various pitches. (Specially created electronic sound.)                                                                                ::
    ID: 07014117.wav
    Length: 21
** Rapid computer bleeps. (Specially created electronic sound.)                                                                                ::
    ID: 07014116.wav
    Length: 24
** Sharp pulsation. (Specially created electronic sound.)                                                                                ::
    ID: 07014115.wav
    Length: 124
** Pulsating hum, changes to higher pitch. (Specially created electronic sound.)                                                                                ::
    ID: 07014114.wav
    Length: 75
** Pulsating hum. (Specially created electronic sound.)                                                                                ::
    ID: 07014113.wav
    Length: 133
** Steady deep humming. (Specially created electronic sound.)                                                                                ::
    ID: 07014112.wav
    Length: 215
** Deep pulsations. (Specially created electronic sound.)                                                                                ::
    ID: 07014111.wav
    Length: 216
** Sound of computer touch panel bleeps. (Specially created electronic sound.)                                                                                ::
    ID: 07014110.wav
    Length: 44
** Sound of an airlock opening & closing. (Specially created electronic sound.)                                                                                ::
    ID: 07014109.wav
    Length: 10
** Cascade. (Specially created electronic sound.)                                                                                ::
    ID: 07014108.wav
    Length: 12
** Double hum. (Specially created electronic sound.)                                                                                ::
    ID: 07014107.wav
    Length: 7
** Gong sounded. (Specially created electronic sound.)                                                                                ::
    ID: 07014106.wav
    Length: 6
** Gong sounded. (Specially created electronic sound.)                                                                                ::
    ID: 07014105.wav
    Length: 8
** Wind tunnel and crescendo. (Specially created electronic sound.)                                                                                ::
    ID: 07014104.wav
    Length: 69
** Laser gun. (Specially created electronic sound.)                                                                                ::
    ID: 07014103.wav
    Length: 24
** Pulsating hum. (Specially created electronic sound.)                                                                                ::
    ID: 07014102.wav
    Length: 9
** Sharp hum with trail out. (Specially created electronic sound.)                                                                                ::
    ID: 07014101.wav
    Length: 21
** Medium pitched hum. (Specially created electronic sound.)                                                                                ::
    ID: 07014100.wav
    Length: 6
** Three harmonic stings. (Specially created electronic sound.)                                                                                ::
    ID: 07014099.wav
    Length: 6
** Platoon strolls single-file on parade ground. without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014098.wav
    Length: 48
** Platoon marches past, right to left on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014097.wav
    Length: 30
** Platoon marches past, left to right on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014096.wav
    Length: 26
** Platoon backwards march, 4 paces, on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014095.wav
    Length: 6
** Platoon sideways march, three paces, on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014094.wav
    Length: 8
** Platoon grounds arms on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014093.wav
    Length: 8
** Platoon presents arms on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014092.wav
    Length: 7
** Platoon about turns on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014091.wav
    Length: 6
** Platoon left turns on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014090.wav
    Length: 6
** Platoon coming to attention on parade ground, without spoken command. (Recorded at Royal Military Academy, Sandhurst.) (NB Platoon = 24 men.)                                                                                ::
    ID: 07014089.wav
    Length: 6
** Fox Combat Vehicle, start, run, stop. (4 wheeled, petrol engined vehicle.)                                                                                ::
    ID: 07014088.wav
    Length: 189
** Scorpion Main Tank, start, run, stop. (Petrol engined tank.)                                                                                ::
    ID: 07014087.wav
    Length: 181
** Fox Combat Vehicle, approach & stop. (4 wheeled, petrol engined vehicle.)                                                                                ::
    ID: 07014086.wav
    Length: 17
** Fox Combat Vehicle, pass. (4 wheeled, petrol engined vehicle.)                                                                                ::
    ID: 07014085.wav
    Length: 15
** Scorpion Main Tank, approach & stop. (Petrol engined tank.)                                                                                ::
    ID: 07014084.wav
    Length: 20
** Scorpion Main Tank, approach & stop. (Petrol engined tank.)                                                                                ::
    ID: 07014083.wav
    Length: 20
** Scorpion Main Tank, pass. (Petrol engined tank.)                                                                                ::
    ID: 07014082.wav
    Length: 16
** Scorpion Main Tank, start & depart. (Petrol engined tank.)                                                                                ::
    ID: 07014081.wav
    Length: 18
** Chieftain Main Battle Tank, exterior, turning, mid-distance perspective. (Diesel engined tank.)                                                                                ::
    ID: 07014080.wav
    Length: 29
** Chieftain Main Battle Tank, exterior, approach & stop. (Diesel engined tank.)                                                                                ::
    ID: 07014079.wav
    Length: 32
** Chieftain Main Battle Tank, exterior, pass on hard surface. (Diesel engined tank.)                                                                                ::
    ID: 07014078.wav
    Length: 20
** Chieftain Main Battle Tank, exterior, pass on soft surface. (Diesel engined tank.)                                                                                ::
    ID: 07014077.wav
    Length: 40
** Chieftain Main Battle Tank, exterior, start & depart. (Diesel engined tank.)                                                                                ::
    ID: 07014076.wav
    Length: 37
** Chieftain Main Battle Tank, exterior, start, run, stop. (Diesel engined tank, recorded from turret top.)                                                                                ::
    ID: 07014075.wav
    Length: 155
** Chieftain Main Battle Tank, interior, start, run, stop. (Diesel engined tank.)                                                                                ::
    ID: 07014074.wav
    Length: 227
** High velocity light machine gun firing single shots from 500 yards. (At receiving end.)                                                                                ::
    ID: 07014073.wav
    Length: 6
** High velocity light machine gun firing in short bursts from 500 yards. (At receiving end.)                                                                                ::
    ID: 07014072.wav
    Length: 12
** High velocity light machine gun firing short bursts.                                                                                ::
    ID: 07014071.wav
    Length: 87
** Drill with orders, arms drill with 303 rifles.                                                                                ::
    ID: 07014070.wav
    Length: 42
** Drill with orders, ragged marching.                                                                                ::
    ID: 07014069.wav
    Length: 112
** Drill with orders, right turn, quick march, left wheel, halt.                                                                                ::
    ID: 07014068.wav
    Length: 76
** Drill with orders, quick march, halt.                                                                                ::
    ID: 07014067.wav
    Length: 38
** Drill with orders, left turn, right dress, eyes front, stand at ease, stand easy.                                                                                ::
    ID: 07014066.wav
    Length: 25
** Drill with orders, left turn, double march, quick march, halt.                                                                                ::
    ID: 07014065.wav
    Length: 44
** Parade Ground atmosphere with orders.                                                                                ::
    ID: 07014064.wav
    Length: 211
** Children shouting with seawash in background.                                                                                ::
    ID: 07014063.wav
    Length: 364
** Seawash & children shouting.                                                                                ::
    ID: 07014062.wav
    Length: 365
** London Airport tunnel, traffic entering and leaving. (Later renamed Heathrow Airport.)                                                                                ::
    ID: 07014061.wav
    Length: 183
** London Airport tunnel, general traffic atmosphere. (Later renamed Heathrow Airport.)                                                                                ::
    ID: 07014060.wav
    Length: 183
** Dartford tunnel, traffic entering and leaving.                                                                                ::
    ID: 07014059.wav
    Length: 183
** Dartford tunnel, general traffic atmosphere.                                                                                ::
    ID: 07014058.wav
    Length: 182
** Dartford tunnel, empty tunnel atmosphere, rumble of distant traffic.                                                                                ::
    ID: 07014057.wav
    Length: 399
** Dartford tunnel, single horn, stationary car.                                                                                ::
    ID: 07014056.wav
    Length: 16
** Dartford tunnel, car approach with horn, stop, depart.                                                                                ::
    ID: 07014055.wav
    Length: 66
** Dartford tunnel, car approach and pass with horn.                                                                                ::
    ID: 07014054.wav
    Length: 41
** Dartford tunnel, public address system instructing drivers to keep close together and speed up on leaving.                                                                                ::
    ID: 07014053.wav
    Length: 64
** Dartford tunnel, Victor 2000 car entering with passing vehicles.                                                                                ::
    ID: 07014052.wav
    Length: 145
** Occasional night traffic, atmosphere with distant trains passing over bridge.                                                                                ::
    ID: 07014051.wav
    Length: 421
** London street atmosphere with children playing, car doors and traffic.                                                                                ::
    ID: 07014050.wav
    Length: 194
** Atmosphere of traffic moving through snow.                                                                                ::
    ID: 07014049.wav
    Length: 144
** Playground atmosphere with children and distant traffic.                                                                                ::
    ID: 07014048.wav
    Length: 80
** Quiet village atmosphere with light traffic and birdsong.                                                                                ::
    ID: 07014047.wav
    Length: 302
** Small town atmosphere with children playing in street, occasional traffic.                                                                                ::
    ID: 07014046.wav
    Length: 416
** One lorry passing slowly.                                                                                ::
    ID: 07014045.wav
    Length: 60
** One heavy wheeled tractor passes slowly.                                                                                ::
    ID: 07014044.wav
    Length: 141
** One tractor passes slowly.                                                                                ::
    ID: 07014043.wav
    Length: 26
** One caterpillar road tractor towing, passes slowly.                                                                                ::
    ID: 07014042.wav
    Length: 144
** One lorry passing slowly.                                                                                ::
    ID: 07014041.wav
    Length: 39
** One lorry passing slowly.                                                                                ::
    ID: 07014040.wav
    Length: 39
** Two lorries passing slowly.                                                                                ::
    ID: 07014039.wav
    Length: 52
** One lorry passing slowly.                                                                                ::
    ID: 07014038.wav
    Length: 32
** One lorry passing slowly.                                                                                ::
    ID: 07014037.wav
    Length: 34
** One lorry passing slowly.                                                                                ::
    ID: 07014036.wav
    Length: 27
** Horsedrawn traffic, at night, fairly busy without footsteps or speech.                                                                                ::
    ID: 07014035.wav
    Length: 465
** Horsedrawn traffic, busy with chatter and footsteps, occasional pauses in traffic with children playing.                                                                                ::
    ID: 07014034.wav
    Length: 446
** Horsedrawn traffic, fairly busy with hansom cabs, some quiet periods without footsteps or speech.                                                                                ::
    ID: 07014033.wav
    Length: 472
** Horsedrawn traffic, fairly busy, some quiet periods without footsteps or speech.                                                                                ::
    ID: 07014032.wav
    Length: 391
** Horsedrawn traffic, very quiet with occasional horse and carriage.                                                                                ::
    ID: 07014031.wav
    Length: 455
** Horsedrawn traffic, in small town with footsteps and chatter.                                                                                ::
    ID: 07014030.wav
    Length: 448
** Busy traffic at crossroads, traffic lights with filter lanes.                                                                                ::
    ID: 07014029.wav
    Length: 390
** Fairly busy traffic entering a roundabout.                                                                                ::
    ID: 07014028.wav
    Length: 198
** Fairly busy traffic leaving a roundabout.                                                                                ::
    ID: 07014027.wav
    Length: 198
** Mid-distant perspective sound of fast motorway traffic passing continously. (M1.)                                                                                ::
    ID: 07014026.wav
    Length: 390
** Close perspective sound of fast motorway traffic, occasional quiet periods. (M1.)                                                                                ::
    ID: 07014025.wav
    Length: 391
** Light traffic, quiet periods with atmosphere and speech. (Knightsbridge, London.)                                                                                ::
    ID: 07014024.wav
    Length: 202
** Light traffic passing on bridge with quiet spells and speech. (Westminster Bridge, London.)                                                                                ::
    ID: 07014023.wav
    Length: 196
** Rumble of traffic with fountains and speech. (Trafalgar Square, London.)                                                                                ::
    ID: 07014022.wav
    Length: 398
** Heavy traffic passing. (Shepherds Bush, London.)                                                                                ::
    ID: 07014021.wav
    Length: 390
** Roar of traffic with distant chatter, some heavy vehicles passing. (Oxford Circus, London.)                                                                                ::
    ID: 07014020.wav
    Length: 390
** Small quiet town atmosphere with birds, speech and occasional traffic.                                                                                ::
    ID: 07014019.wav
    Length: 388
** Small country town high street atmosphere, light traffic with intervals of footsteps and speech.                                                                                ::
    ID: 07014018.wav
    Length: 440
** Light and heavy traffic in a provincial town, without footsteps or chatter.                                                                                ::
    ID: 07014017.wav
    Length: 421
** Light traffic in a provincial town, with footsteps and chatter.                                                                                ::
    ID: 07014016.wav
    Length: 423
** A41 during day, occasional fast traffic with birdsong.                                                                                ::
    ID: 07014015.wav
    Length: 413
** A41 at night, occasional fast traffic with quiet intervals. (No bird song)                                                                                ::
    ID: 07014014.wav
    Length: 376
** Fairly heavy traffic on main road, with some footsteps. (Hammersmith, London.)                                                                                ::
    ID: 07014013.wav
    Length: 196
** Fairly heavy traffic on main road, faint cry of news vendor at end calling 'Star, News, Standard'. (Hammersmith, London.)                                                                                ::
    ID: 07014012.wav
    Length: 195
** Cars driving off ferry ramp in harbour, some speech. (Recorded from interior of car ferry)                                                                                ::
    ID: 07014011.wav
    Length: 393
** Fast traffic, occasional pauses, on a wet main road.                                                                                ::
    ID: 07014010.wav
    Length: 370
** Slow traffic in fog, some speech and footsteps.                                                                                ::
    ID: 07014009.wav
    Length: 422
** Main street of small town, fairly heavy traffic with occasional pauses and footsteps.                                                                                ::
    ID: 07014008.wav
    Length: 390
** Murmur of distant suburban traffic.                                                                                ::
    ID: 07014007.wav
    Length: 388
** Rumble of traffic with pedestrians. (Few horns)                                                                                ::
    ID: 07014006.wav
    Length: 423
** Fairly heavy traffic on wet road. (No pedestrians)                                                                                ::
    ID: 07014005.wav
    Length: 424
** Traffic passing, pedestrians and speech. (Oxford Circus, London.)                                                                                ::
    ID: 07014004.wav
    Length: 421
** Light traffic, occasionally heavy, on main road. (Shepherds Bush, London.)                                                                                ::
    ID: 07014003.wav
    Length: 432
** City side street with distant traffic, speech and footsteps.                                                                                ::
    ID: 07014002.wav
    Length: 413
** Fast traffic passing on a trunk road.                                                                                ::
    ID: 07014001.wav
    Length: 429
** Various amounts of change issued on one-man bus. (London Transport bus.)                                                                                ::
    ID: 07013153.wav
    Length: 30
** 6d piece issued as change on one-man bus. (London Transport bus.)                                                                                ::
    ID: 07013152.wav
    Length: 6
** 3d piece issued as change on one-man bus. (London Transport bus.)                                                                                ::
    ID: 07013151.wav
    Length: 6
** Automatic turnstile on one-man bus, coin inserted, regain button pressed. (London Transport bus.)                                                                                ::
    ID: 07013150.wav
    Length: 10
** Automatic turnstile on one-man bus, coin rejected twice. (London Transport bus.)                                                                                ::
    ID: 07013149.wav
    Length: 10
** Automatic turnstile on one-man bus, two 3d pieces inserted, adult through turnstile, repeated several times. (London Transport bus.)                                                                                ::
    ID: 07013148.wav
    Length: 30
** Automatic turnstile on one-man bus, tone, 6d inserted, adult through turnstile, repeated several times. (London Transport bus.)                                                                                ::
    ID: 07013147.wav
    Length: 39
** Automatic turnstile on one-man bus, tone, 6d inserted, adult through turnstile. (London Transport bus.)                                                                                ::
    ID: 07013146.wav
    Length: 9
** Automatic turnstile on one-man bus, tone, 3d inserted, child through turnstile, repeated several times. (London Transport bus.)                                                                                ::
    ID: 07013145.wav
    Length: 33
** Automatic turnstile on one-man bus, tone, 3d inserted, child through turnstile. (London Transport bus.)                                                                                ::
    ID: 07013144.wav
    Length: 9
** Auto-Slot mk 2 ticket machine, adult fare of 6d inserted several times. (London Transport green Country bus.)                                                                                ::
    ID: 07013143.wav
    Length: 50
** Auto-Slot mk 2 ticket machine, child's fare of 3d inserted several times. (London Transport green Country bus.)                                                                                ::
    ID: 07013142.wav
    Length: 33
** Ultimate ticket machine issuing several tickets. (London Transport.)                                                                                ::
    ID: 07013141.wav
    Length: 58
** Ultimate ticket machine issuing two tickets. (London Transport.)                                                                                ::
    ID: 07013140.wav
    Length: 8
** Ultimate ticket machine issuing a ticket. (London Transport.)                                                                                ::
    ID: 07013139.wav
    Length: 6
** Ultimate ticket machine, setting machine. (London Transport.)                                                                                ::
    ID: 07013138.wav
    Length: 19
** Almex ticket machine issuing several tickets. (London Transport.)                                                                                ::
    ID: 07013137.wav
    Length: 30
** Almex ticket machine issuing one ticket. (London Transport.)                                                                                ::
    ID: 07013136.wav
    Length: 7
** Almex ticket machine, setting machine. (London Transport.)                                                                                ::
    ID: 07013135.wav
    Length: 9
** Gibson ticket machine issuing several tickets. (London Transport.)                                                                                ::
    ID: 07013134.wav
    Length: 13
** Gibson ticket machine issuing one ticket. (London Transport.)                                                                                ::
    ID: 07013133.wav
    Length: 6
** Gibson ticket machine, setting machine. (London Transport.)                                                                                ::
    ID: 07013132.wav
    Length: 18
** Bell Punch ticket machine operated several times. (London Transport.)                                                                                ::
    ID: 07013131.wav
    Length: 12
** Bell Punch ticket machine operated once. (London Transport.)                                                                                ::
    ID: 07013130.wav
    Length: 6
** Bus depot, atmosphere with buses parking for the night.                                                                                ::
    ID: 07013129.wav
    Length: 220
** Bus depot, atmosphere with buses departing.                                                                                ::
    ID: 07013128.wav
    Length: 212
** Diesel bus, interior, on congested London route in low gear, bell rung once at beginning of track. (Make of bus not known)                                                                                ::
    ID: 07013127.wav
    Length: 192
** Diesel bus, interior, on London route, bell rung once at beginning of track, faintly at end. (Make of bus not known)                                                                                ::
    ID: 07013126.wav
    Length: 213
** Diesel bus, interior, general atmosphere with school children on board, running with intermediate stops. (On country route, make of                                                                                 ::
    ID: 07013125.wav
    Length: 264
** Diesel bus, exterior, approach, stop, start up, depart. (On country route, make of bus not known)                                                                                ::
    ID: 07013124.wav
    Length: 69
** Diesel bus, exterior, passing. (On country route, make of bus not known)                                                                                ::
    ID: 07013123.wav
    Length: 37
** Diesel bus, interior, start, move off, running with intermediate stops. (On country route, make of bus not known)                                                                                ::
    ID: 07013122.wav
    Length: 406
** Petrol bus, exterior, arrives and stops. (On country route, make of bus not known)                                                                                ::
    ID: 07013121.wav
    Length: 27
** Petrol bus, exterior, arrives and stops. (On country route, make of bus not known)                                                                                ::
    ID: 07013120.wav
    Length: 22
** Petrol bus, exterior, passing. (On country route, make of bus not known)                                                                                ::
    ID: 07013119.wav
    Length: 36
** Petrol bus, exterior, start up, pass, depart. (On country route, make of bus not known)                                                                                ::
    ID: 07013118.wav
    Length: 24
** Petrol bus, exterior, start up, depart. (On country route, make of bus not known)                                                                                ::
    ID: 07013117.wav
    Length: 22
** Petrol bus, interior, sliding door open and close. (On country route, make of bus not known)                                                                                ::
    ID: 07013116.wav
    Length: 9
** Petrol bus, interior, move off, running on trunk road, slow down, stop. (On country route, make of bus not known)                                                                                ::
    ID: 07013115.wav
    Length: 379
** Charing Cross Station, general station atmosphere. (Charing Cross, London.) (British Rail Southern Region.)                                                                                ::
    ID: 07013114.wav
    Length: 363
** Multiple unit Diesel train, exterior, tickover in station with atmosphere. (British Rail Southern Region train.)                                                                                ::
    ID: 07013113.wav
    Length: 307
** Multiple unit Diesel train, exterior, four coaches passing at speed. (British Rail Southern Region train.)                                                                                ::
    ID: 07013112.wav
    Length: 21
** Multiple unit Diesel train, exterior, doors, tickover, guard's whistle, departs. (British Rail Southern Region train.)                                                                                ::
    ID: 07013111.wav
    Length: 167
** Multiple unit Diesel train, exterior, tickover, indistinct public address, departs. (British Rail Southern Region train.)                                                                                ::
    ID: 07013110.wav
    Length: 89
** Multiple unit Diesel train, exterior, tickover, guard's whistle, departs. (British Rail Southern Region train.)                                                                                ::
    ID: 07013109.wav
    Length: 103
** Multiple unit Diesel train, exterior, arrives in station, tickover, doors, partly identifiable public address, departs. (British Rail Southern Region train.)                                                                                ::
    ID: 07013108.wav
    Length: 127
** Multiple unit Diesel train, exterior, arrives in station, tickover. (British Rail Southern Region train.)                                                                                ::
    ID: 07013107.wav
    Length: 57
** Multiple unit Diesel train, interior, slow constant run with carriage creaks into crawl, some speed increase, slow down to stop in station. (BR Southern Region train.)                                                                                ::
    ID: 07013106.wav
    Length: 362
** Multiple unit Diesel train, interior, fast constant run, occasional marked rhythm. (British Rail Southern Region train.)                                                                                ::
    ID: 07013105.wav
    Length: 368
** Multiple unit Diesel train, interior, tickover into constant run with carriage creaks and subdued rhythm. (British Rail Southern Region train.)                                                                                ::
    ID: 07013104.wav
    Length: 369
** Multiple unit Diesel train, interior, move off into constant run with marked rhythm, slow down, stop. (British Rail Southern Region train.)                                                                                ::
    ID: 07013103.wav
    Length: 379
** 1966 F.A. Cup Final, double cheer. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013102.wav
    Length: 22
** 1966 F.A. Cup Final, off-side. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013101.wav
    Length: 23
** 1966 F.A. Cup Final, infringement. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013100.wav
    Length: 12
** 1966 F.A. Cup Final, half-time whistle. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013099.wav
    Length: 30
** 1966 F.A. Cup Final, frustrated crowd. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013098.wav
    Length: 47
** 1966 F.A. Cup Final, whistle and boos. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013097.wav
    Length: 33
** 1966 F.A. Cup Final, goal attempt. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013096.wav
    Length: 28
** 1966 F.A. Cup Final, near miss. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013095.wav
    Length: 21
** 1966 F.A. Cup Final, goal scored. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013094.wav
    Length: 45
** 1966 F.A. Cup Final, goal scored. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013093.wav
    Length: 33
** 1966 F.A. Cup Final, goal scored. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013092.wav
    Length: 34
** 1966 F.A. Cup Final, goal scored. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013091.wav
    Length: 27
** 1966 F.A. Cup final, general atmosphere with constant crowd background and highlights. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013090.wav
    Length: 401
** 1966 F.A. Cup final, general atmosphere with highlights. (Everton v Sheffield Wednesday, Wembley Stadium.)                                                                                ::
    ID: 07013089.wav
    Length: 447
** County rugby match, whistle.                                                                                ::
    ID: 07013088.wav
    Length: 6
** County rugby match, mild applause.                                                                                ::
    ID: 07013087.wav
    Length: 18
** County rugby match, shouts and applause.                                                                                ::
    ID: 07013086.wav
    Length: 27
** County rugby match, goal kick, applause.                                                                                ::
    ID: 07013085.wav
    Length: 19
** County rugby match, applause for goal kick.                                                                                ::
    ID: 07013084.wav
    Length: 18
** County rugby match, try scored, applause.                                                                                ::
    ID: 07013083.wav
    Length: 22
** County rugby match, general atmosphere during match.                                                                                ::
    ID: 07013082.wav
    Length: 412
** Local football match, goal scored.                                                                                ::
    ID: 07013081.wav
    Length: 22
** Local football match, goal scored.                                                                                ::
    ID: 07013080.wav
    Length: 18
** Local football match, near miss.                                                                                ::
    ID: 07013079.wav
    Length: 15
** Local football match, angry crowd.                                                                                ::
    ID: 07013078.wav
    Length: 21
** Local football match, end of match with cheers and dispersal of crowd.                                                                                ::
    ID: 07013077.wav
    Length: 105
** Local football match, footsteps and conversation in stand.                                                                                ::
    ID: 07013076.wav
    Length: 128
** Local football match, small enthusiastic crowd.                                                                                ::
    ID: 07013075.wav
    Length: 402
** Football League match, general atmosphere during match.                                                                                ::
    ID: 07013074.wav
    Length: 419
** Football League match, half-time whistle.                                                                                ::
    ID: 07013073.wav
    Length: 30
** Football League match, whistle, angry crowd.                                                                                ::
    ID: 07013072.wav
    Length: 29
** Football League match, goal scored.                                                                                ::
    ID: 07013071.wav
    Length: 36
** Football League match, goal scored.                                                                                ::
    ID: 07013070.wav
    Length: 38
** Football League match, whistle for throw in.                                                                                ::
    ID: 07013069.wav
    Length: 8
** Football League match, near miss, applause.                                                                                ::
    ID: 07013068.wav
    Length: 15
** Football League match, final whistle and crowd disperses.                                                                                ::
    ID: 07013067.wav
    Length: 359
** Football League match, half-time whistle and crowd reaction.                                                                                ::
    ID: 07013066.wav
    Length: 200
** Football League match , crowd of 20,000 before kick-off.                                                                                ::
    ID: 07013065.wav
    Length: 179
** Sports crowd at German sports meeting. (Location unknown.)                                                                                ::
    ID: 07013064.wav
    Length: 363
** German association football match in progress, crowd reaction with whistles and horns. (Participating team and location unknown.)                                                                                ::
    ID: 07013063.wav
    Length: 363
** Rugby union match in progress, crowd reaction with some quiet periods. (Twickenham Stadium.)                                                                                ::
    ID: 07013062.wav
    Length: 360
** Football League match in progress, crowd reaction. (Selhurst Park, Crystal Palace FC.)                                                                                ::
    ID: 07013061.wav
    Length: 362
** Exterior, approach and stop. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013060.wav
    Length: 20
** Exterior, passing. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013059.wav
    Length: 27
** Exterior, start up, depart. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013058.wav
    Length: 32
** Interior, start, quiet tickover, revving switch off. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013057.wav
    Length: 91
** Interior, two doors open and close. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013056.wav
    Length: 6
** Interior, one door open and close. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013055.wav
    Length: 6
** Interior, constant high-speed run in overdrive. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013054.wav
    Length: 272
** Interior, tickover with windscreen wipers operating. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013053.wav
    Length: 35
** Interior, sounds horn while on move. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013052.wav
    Length: 34
** Interior, reversing. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013051.wav
    Length: 35
** Interior, travelling over rough ground with manouevring. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013050.wav
    Length: 197
** Interior, changes down gear to climb hill, changes up. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013049.wav
    Length: 180
** Interior, start, run on motorway up to 90 m.p.h. in overdrive, slow down, stop, switch off. (2.6 litre Rover saloon car.)                                                                                ::
    ID: 07013048.wav
    Length: 375
** Interior, start, run on trunk road, slow down, stop, switch off. (2.6 litre Rover saloon car)                                                                                ::
    ID: 07013047.wav
    Length: 370
** Interior, start, move off into town run, slow down, stop, switch off. (2.6 litre Rover saloon car)                                                                                ::
    ID: 07013046.wav
    Length: 369
** Train slows down and stops in station. (Interior)                                                                                ::
    ID: 07013045.wav
    Length: 302
** Train arrives in station, tickover. (Extterior)                                                                                ::
    ID: 07013044.wav
    Length: 302
** Train tickover in station. (Exterior)                                                                                ::
    ID: 07013043.wav
    Length: 48
** Train arrives and stops. (Interior)                                                                                ::
    ID: 07013042.wav
    Length: 58
** Siren, train passes at speed into distance. (Exterior, with birdsong)                                                                                ::
    ID: 07013041.wav
    Length: 85
** Train tickover, sound of siren, departs into distance. (Exterior with birdsong)                                                                                ::
    ID: 07013040.wav
    Length: 111
** Train tickover, sound of siren, departs. (Exterior)                                                                                ::
    ID: 07013039.wav
    Length: 303
** Train arrives and stops. (Exterior, with birdsong)                                                                                ::
    ID: 07013038.wav
    Length: 308
** Diesel railcar, fast constant run. (Interior)                                                                                ::
    ID: 07013037.wav
    Length: 62
** Diesel railcar, tickover, doors close, gathering speed. (Interior recording with some speech and birdsong)                                                                                ::
    ID: 07013036.wav
    Length: 154
** Diesel railcar, tickover, depart, gathering speed with siren. (Interior)                                                                                ::
    ID: 07013035.wav
    Length: 90
** General farm bird atmosphere with chickens, cockerels, geese and turkeys.                                                                                ::
    ID: 07013034.wav
    Length: 199
** Geese cackling.                                                                                ::
    ID: 07013033.wav
    Length: 196
** Many turkeys.                                                                                ::
    ID: 07013032.wav
    Length: 194
** Ducks quacking, with occasional flap of wings.                                                                                ::
    ID: 07013031.wav
    Length: 196
** Atmosphere of chickens feeding, some squawking.                                                                                ::
    ID: 07013030.wav
    Length: 303
** Hens cackling.                                                                                ::
    ID: 07013029.wav
    Length: 48
** Cock crows, several with hens.                                                                                ::
    ID: 07013028.wav
    Length: 171
** Cock crows, several from various perspectives.                                                                                ::
    ID: 07013027.wav
    Length: 122
** Three cock crows.                                                                                ::
    ID: 07013026.wav
    Length: 11
** Single cock crow.                                                                                ::
    ID: 07013025.wav
    Length: 7
** Geese cackling. (Disturbed)                                                                                ::
    ID: 07013024.wav
    Length: 30
** Geese cackling. (Animated)                                                                                ::
    ID: 07013023.wav
    Length: 310
** Geese cackling.                                                                                ::
    ID: 07013022.wav
    Length: 359
** Turkeys.                                                                                ::
    ID: 07013021.wav
    Length: 167
** Day-old chicks. (Close perspective)                                                                                ::
    ID: 07013020.wav
    Length: 166
** Busy atmosphere in chicken house.                                                                                ::
    ID: 07013019.wav
    Length: 127
** Atmosphere in chicken house.                                                                                ::
    ID: 07013018.wav
    Length: 211
** General farmyard atmosphere with chickens, animals and birds.                                                                                ::
    ID: 07013017.wav
    Length: 360
** Broody hens.                                                                                ::
    ID: 07013016.wav
    Length: 78
** Hens.                                                                                ::
    ID: 07013015.wav
    Length: 92
** Hens and chicks.                                                                                ::
    ID: 07013014.wav
    Length: 78
** Single hen.                                                                                ::
    ID: 07013013.wav
    Length: 63
** Harbour wall, night time atmosphere in force 5 wind.                                                                                ::
    ID: 07013012.wav
    Length: 393
** Harbour wall, daytime atmosphere with seagulls.                                                                                ::
    ID: 07013011.wav
    Length: 393
** Coastal garden in winter, approximately fifty birds flying past.                                                                                ::
    ID: 07013010.wav
    Length: 9
** Coastal garden in winter, with starlings, blackbirds, sparrows and distant traffic.                                                                                ::
    ID: 07013009.wav
    Length: 378
** Coastal garden in winter, birds taking off.                                                                                ::
    ID: 07013008.wav
    Length: 8
** Coastal garden in winter, with starlings, blackbirds, sparrows and distant traffic.                                                                                ::
    ID: 07013007.wav
    Length: 379
** Suburban garden at dawn with bird song, occasional distant aircraft and traffic.                                                                                ::
    ID: 07013006.wav
    Length: 372
** Cliff top atmosphere with seagulls circling overhead, heavy seawash below.                                                                                ::
    ID: 07013005.wav
    Length: 394
** Suburban garden in winter with bird song, traffic and occasional speech.                                                                                ::
    ID: 07013004.wav
    Length: 899
** Countryside atmosphere in summer with birdsong.                                                                                ::
    ID: 07013003.wav
    Length: 894
** Provincial town atmosphere, wide perspective rumble of traffic. (Suitable for skyline effect e.g. background ambience)                                                                                ::
    ID: 07013002.wav
    Length: 888
** Outside atmosphere, wide perspective rumble. (Specially created background ambience from recording of Victoria Falls.)                                                                                ::
    ID: 07013001.wav
    Length: 904
** Atmosphere of goats in yard with animal sounds and bird song.                                                                                ::
    ID: 07012181.wav
    Length: 260
** Atmosphere in goat house with bleating and animal sounds.                                                                                ::
    ID: 07012180.wav
    Length: 82
** One Anglo-Nubian goat kid bleating. (Bird song)                                                                                ::
    ID: 07012179.wav
    Length: 43
** One female Anglo-Nubian goat bleating. (Bird song)                                                                                ::
    ID: 07012178.wav
    Length: 132
** One female British Alpine goat bleating. (Bird song)                                                                                ::
    ID: 07012177.wav
    Length: 39
** One goat bleating. (Distant bird song)                                                                                ::
    ID: 07012176.wav
    Length: 44
** One goat bleating. (Distant bird song)                                                                                ::
    ID: 07012175.wav
    Length: 63
** Several lambs and sheep bleating and moving in snow.                                                                                ::
    ID: 07012174.wav
    Length: 199
** Several lambs and sheep bleating.                                                                                ::
    ID: 07012173.wav
    Length: 200
** Single lamb bleating. (7 days old)                                                                                ::
    ID: 07012172.wav
    Length: 106
** Single lamb bleating. (2 days old)                                                                                ::
    ID: 07012171.wav
    Length: 104
** Single lamb bleating. (1 day old)                                                                                ::
    ID: 07012170.wav
    Length: 62
** Single lamb bleating. (1 day old)                                                                                ::
    ID: 07012169.wav
    Length: 64
** Many sheep bleating and bumping as animals feed from troughs, with distant birdsong. (Approxiamtely 300 sheep.)                                                                                ::
    ID: 07012168.wav
    Length: 363
** Many sheep bleating, with distant birdsong. (Approximately 300 sheep.)                                                                                ::
    ID: 07012167.wav
    Length: 363
** 5-month old piglets.                                                                                ::
    ID: 07012166.wav
    Length: 361
** 3-month old piglets.                                                                                ::
    ID: 07012165.wav
    Length: 122
** Sow with piglets.                                                                                ::
    ID: 07012164.wav
    Length: 62
** One piglet squealing.                                                                                ::
    ID: 07012163.wav
    Length: 17
** 6-week old piglets.                                                                                ::
    ID: 07012162.wav
    Length: 101
** Sow with 6-week old piglets.                                                                                ::
    ID: 07012161.wav
    Length: 156
** Three pigs grunting and feeding.                                                                                ::
    ID: 07012160.wav
    Length: 155
** Two pigs grunting and snuffling.                                                                                ::
    ID: 07012159.wav
    Length: 272
** One sow grunting and feeding. (Close perspective)                                                                                ::
    ID: 07012158.wav
    Length: 62
** Bull bellowing.                                                                                ::
    ID: 07012157.wav
    Length: 130
** Bull bellowing in stall.                                                                                ::
    ID: 07012156.wav
    Length: 146
** Cows and calves in shed.                                                                                ::
    ID: 07012155.wav
    Length: 118
** Cows in shed, occasional distant calls, some quiet periods                                                                                ::
    ID: 07012154.wav
    Length: 211
** Cows and heifers grazing and feeding.                                                                                ::
    ID: 07012153.wav
    Length: 360
** Cows and calves grazing. (Animal sounds, birdsong and some distant traffic in distance)                                                                                ::
    ID: 07012152.wav
    Length: 358
** Distant roar of sea.                                                                                ::
    ID: 07012151.wav
    Length: 397
** Heavy sea breaking on shore.                                                                                ::
    ID: 07012150.wav
    Length: 398
** Rough sea on sand and rocks.                                                                                ::
    ID: 07012149.wav
    Length: 369
** Quiet seawash on sand and rocks.                                                                                ::
    ID: 07012148.wav
    Length: 363
** Heavy seawash on shingle.                                                                                ::
    ID: 07012147.wav
    Length: 367
** Heavy seawash on promenade.                                                                                ::
    ID: 07012146.wav
    Length: 367
** Seawash on rocks.                                                                                ::
    ID: 07012145.wav
    Length: 422
** Seawash on shingle.                                                                                ::
    ID: 07012144.wav
    Length: 423
** Water churning, with some splashing.                                                                                ::
    ID: 07012143.wav
    Length: 76
** Three small splashes.                                                                                ::
    ID: 07012142.wav
    Length: 11
** Three small splashes.                                                                                ::
    ID: 07012141.wav
    Length: 12
** One small splash.                                                                                ::
    ID: 07012140.wav
    Length: 6
** Three small splashes.                                                                                ::
    ID: 07012139.wav
    Length: 12
** Sound of stones ricocheting across pond. (Fade for length of throw)                                                                                ::
    ID: 07012138.wav
    Length: 18
** Close perspective sound of water lapping.                                                                                ::
    ID: 07012137.wav
    Length: 419
** Sound of fountains, with street atmosphere. (Rome, Italy.)                                                                                ::
    ID: 07012136.wav
    Length: 260
** Sound of fountains, with voices in background. (Rome, Italy.)                                                                                ::
    ID: 07012135.wav
    Length: 134
** Small fountain.                                                                                ::
    ID: 07012134.wav
    Length: 129
** Large fountain.                                                                                ::
    ID: 07012133.wav
    Length: 129
** Fairly small fountain.                                                                                ::
    ID: 07012132.wav
    Length: 134
** Water running into a large drain.                                                                                ::
    ID: 07012131.wav
    Length: 390
** Water surging into a cave.                                                                                ::
    ID: 07012130.wav
    Length: 386
** Water rushing through lock gates.                                                                                ::
    ID: 07012129.wav
    Length: 394
** Water over weir in full flood.                                                                                ::
    ID: 07012128.wav
    Length: 383
** Water gurgling down a drain.                                                                                ::
    ID: 07012127.wav
    Length: 43
** Water running in a cavern.                                                                                ::
    ID: 07012126.wav
    Length: 304
** Water running over mill race.                                                                                ::
    ID: 07012125.wav
    Length: 363
** Rapids, rushing water. (Close perspective from river bank.)                                                                                ::
    ID: 07012124.wav
    Length: 394
** Rapids, rushing water. (General perspective)                                                                                ::
    ID: 07012123.wav
    Length: 395
** Victoria Falls. (Zambia/Zimbabwe.)                                                                                ::
    ID: 07012122.wav
    Length: 394
** Heavy waterfall.                                                                                ::
    ID: 07012121.wav
    Length: 392
** Mountain stream, fast running water over rocks. (Isle of Skye.)                                                                                ::
    ID: 07012120.wav
    Length: 911
** Water lapping on loch shore. (Loch Broom, Ullapool.)                                                                                ::
    ID: 07012119.wav
    Length: 914
** Doubles match on hard court in park.                                                                                ::
    ID: 07012118.wav
    Length: 279
** Two players knocking up on hard court in park.                                                                                ::
    ID: 07012117.wav
    Length: 96
** Singles match on hard court in park.                                                                                ::
    ID: 07012116.wav
    Length: 274
** Single player practising Services on hard court in park.                                                                                ::
    ID: 07012115.wav
    Length: 93
