** Coach Horn, sounded twice.                                                                                ::
    ID: 07035056.wav
    Length: 28
** Coach Horn, sounded six times.                                                                                ::
    ID: 07035055.wav
    Length: 48
** Coach Horn, sounded three times.                                                                                ::
    ID: 07035054.wav
    Length: 28
** Ten Pin Bowling, American-style bowling, busy period with 12 lanes in use.                                                                                ::
    ID: 07035053.wav
    Length: 418
** Ten Pin Bowling, American-type bowling, quiet period with two lanes in use.                                                                                ::
    ID: 07035052.wav
    Length: 408
** Ten Pin Bowling, two people playing, quiet game.                                                                                ::
    ID: 07035051.wav
    Length: 401
** Ten Pin Bowling, machinery room, quiet tick over of machines, two distant games in progress.                                                                                ::
    ID: 07035050.wav
    Length: 196
** Ten Pin Bowling, general atmosphere in machinery room.                                                                                ::
    ID: 07035049.wav
    Length: 194
** Ten Pin Bowling, league game in progress across 12 lanes.                                                                                ::
    ID: 07035048.wav
    Length: 408
** Ten Pin Bowling, players practising before match.                                                                                ::
    ID: 07035047.wav
    Length: 396
** SRN 6 Hovercraft, approach, stop switch off. (Saunders Roe Nautical 6 hovercraft.)                                                                                ::
    ID: 07035046.wav
    Length: 125
** SRN 6 Hovercraft, approach & stop, engines running. (Saunders Roe Nautical 6 hovercraft.)                                                                                ::
    ID: 07035045.wav
    Length: 253
** SRN 6 Hovercraft, switch on, depart. (Depart at 002m20s.) (Saunders Roe Nautical 6 hovercraft.)                                                                                ::
    ID: 07035044.wav
    Length: 268
** SRN 6 Hovercraft, fast departure. (Saunders Roe Nautical 6 hovercraft.)                                                                                ::
    ID: 07035043.wav
    Length: 87
** SRN 6 Hovercraft, slow down, stop switch off. (Saunders Roe Nautical 6 hovercraft.)                                                                                ::
    ID: 07035042.wav
    Length: 209
** SRN 6 Hovercraft, start up, manoeuvering (hooter sounds at 000m30s). (Saunders Roe Nautical 6 hovercraft.)                                                                                ::
    ID: 07035041.wav
    Length: 199
** SRN 6 Hovercraft, start up, into constant run. (Saunders Roe Nautical 6 hovercraft.)                                                                                ::
    ID: 07035040.wav
    Length: 396
** Lambretta Scooter, medium pass.                                                                                ::
    ID: 07035039.wav
    Length: 43
** Lambretta Scooter, slow pass.                                                                                ::
    ID: 07035038.wav
    Length: 51
** Lambretta Scooter, fast pass.                                                                                ::
    ID: 07035037.wav
    Length: 35
** Lambretta Scooter, approach, stop, tick over, depart.                                                                                ::
    ID: 07035036.wav
    Length: 56
** Lambretta Scooter, approach, stop, tick over, depart.                                                                                ::
    ID: 07035035.wav
    Length: 68
** Lambretta Scooter, approach, stop, switch off.                                                                                ::
    ID: 07035034.wav
    Length: 31
** Lambretta Scooter, approach, stop, switch off.                                                                                ::
    ID: 07035033.wav
    Length: 32
** Lambretta Scooter, start, depart.                                                                                ::
    ID: 07035032.wav
    Length: 25
** Lambretta Scooter, start, depart.                                                                                ::
    ID: 07035031.wav
    Length: 28
** Lambretta Scooter, start, tick over, stop.                                                                                ::
    ID: 07035030.wav
    Length: 125
** Lambretta Scooter, starts, stops immediately.                                                                                ::
    ID: 07035029.wav
    Length: 9
** Lambretta Scooter, seven false starts.                                                                                ::
    ID: 07035028.wav
    Length: 16
** Vespa Scooter, start into constant run with gear changes, stop, switch off. (Recorded on scooter.)                                                                                ::
    ID: 07035027.wav
    Length: 269
** Vespa Scooter, start, revving, switch off. (Recorded on scooter.)                                                                                ::
    ID: 07035026.wav
    Length: 33
** Vespa Scooter, start, tick over, switch off. (Recorded on scooter.)                                                                                ::
    ID: 07035025.wav
    Length: 62
** Vespa Scooter, start into fast run, skids to stop, tick over, switch off. (Recorded on scooter.)                                                                                ::
    ID: 07035024.wav
    Length: 102
** Vespa Scooter, start into medium-fast run, stop, switch off. (Recorded on scooter.)                                                                                ::
    ID: 07035023.wav
    Length: 229
** Vespa Scooter, start, tick over, switch off. (Recorded on scooter.)                                                                                ::
    ID: 07035022.wav
    Length: 38
** Vespa Scooter, fast pass. (1956 model.)                                                                                ::
    ID: 07035021.wav
    Length: 31
** Vespa Scooter, passing. (1956 model.)                                                                                ::
    ID: 07035020.wav
    Length: 30
** Vespa Scooter, start, mid-distant approach and pass. (1956 model.)                                                                                ::
    ID: 07035019.wav
    Length: 47
** Vespa Scooter, approach, skid to stop. (1956 model.)                                                                                ::
    ID: 07035018.wav
    Length: 21
** Vespa Scooter, approach, stop, switch off. (1956 model.)                                                                                ::
    ID: 07035017.wav
    Length: 29
** Vespa Scooter, stand raised, start, depart. (1956 model.)                                                                                ::
    ID: 07035016.wav
    Length: 36
** Vespa Scooter, start, depart. (1956 model.)                                                                                ::
    ID: 07035015.wav
    Length: 21
** Vespa Scooter, start, fast depart. (1956 model.)                                                                                ::
    ID: 07035014.wav
    Length: 20
** Vespa Scooter, start, revving, switch off. (1956 model.)                                                                                ::
    ID: 07035013.wav
    Length: 45
** Vespa Scooter, two false starts, start, tickover, switch off. (1956 model.)                                                                                ::
    ID: 07035012.wav
    Length: 145
** Vespa Scooter, six false starts. (1956 model.)                                                                                ::
    ID: 07035011.wav
    Length: 24
** Vespa Scooter, stand raised. (1956 model.)                                                                                ::
    ID: 07035010.wav
    Length: 7
** Eight unshod donkeys walking on a dirt road.                                                                                ::
    ID: 07035009.wav
    Length: 149
** Eight donkeys walking.                                                                                ::
    ID: 07035008.wav
    Length: 218
** Eight donkeys approach & pass.                                                                                ::
    ID: 07035007.wav
    Length: 24
** Eight donkeys approach & pass.                                                                                ::
    ID: 07035006.wav
    Length: 23
** Donkey braying.                                                                                ::
    ID: 07035005.wav
    Length: 25
** Donkey braying.                                                                                ::
    ID: 07035004.wav
    Length: 23
** Donkey braying.                                                                                ::
    ID: 07035003.wav
    Length: 35
** Donkey braying.                                                                                ::
    ID: 07035002.wav
    Length: 25
** Donkey braying.                                                                                ::
    ID: 07035001.wav
    Length: 114
** Swift planer operating with machine section atmosphere.                                                                                ::
    ID: 07034237.wav
    Length: 122
** Loewy forge, close perspective.                                                                                ::
    ID: 07034236.wav
    Length: 117
** Loewy forge, shot blasting with machine atmosphere.                                                                                ::
    ID: 07034235.wav
    Length: 123
** Factory atmosphere & arc furnace.                                                                                ::
    ID: 07034234.wav
    Length: 243
** Hereaus Arc Furnace control platform with general machinery background.                                                                                ::
    ID: 07034233.wav
    Length: 162
** Bofors Guns, crew clearing up 40mm shell cases.                                                                                ::
    ID: 07034232.wav
    Length: 51
** Bofors Guns, barrage fired, cases falling.                                                                                ::
    ID: 07034231.wav
    Length: 95
** Bofors Guns, shells fired, cases falling.                                                                                ::
    ID: 07034230.wav
    Length: 24
** Sound of machine gun bursts.                                                                                ::
    ID: 07034229.wav
    Length: 149
** Liverpool 1 o'clock Gun fired, with ships' sirens.                                                                                ::
    ID: 07034228.wav
    Length: 53
** Edinburgh 1 o'clock Gun fired, with traffic.                                                                                ::
    ID: 07034227.wav
    Length: 26
** Tank Guns, six-pounder guns fired.                                                                                ::
    ID: 07034226.wav
    Length: 59
** Tank Guns, three shots fired.                                                                                ::
    ID: 07034225.wav
    Length: 30
** Tank Guns, single shot with distant blast.                                                                                ::
    ID: 07034224.wav
    Length: 18
** Tank Guns, single shot.                                                                                ::
    ID: 07034223.wav
    Length: 11
** Tank Guns, six-pounder gun loaded.                                                                                ::
    ID: 07034222.wav
    Length: 53
** Tank Guns, shell cases thrown on to ground.                                                                                ::
    ID: 07034221.wav
    Length: 35
** Tank Guns, 120mm gun fired three times. (Recorded at target end.)                                                                                ::
    ID: 07034220.wav
    Length: 37
** Tank Guns, 7.62mm machine gun firing. (Recorded at target end.)                                                                                ::
    ID: 07034219.wav
    Length: 48
** Tank Guns, .3 machine gun firing. (Recorded at target end.)                                                                                ::
    ID: 07034218.wav
    Length: 61
** Tank Guns, .3 machine gun firing. (Recorded at target end.)                                                                                ::
    ID: 07034217.wav
    Length: 35
** Tank Guns, .3 machine gun firing. (Recorded outside tank.)                                                                                ::
    ID: 07034216.wav
    Length: 36
** Tank Guns, .3 machine gun firing. (Recorded inside tank.)                                                                                ::
    ID: 07034215.wav
    Length: 55
** Tank Guns, 76mm smoke shells fired twice. (Recorded at target end.)                                                                                ::
    ID: 07034214.wav
    Length: 17
** Tank Guns, 76mm high explosive shells fired three times. (Recorded at target end.)                                                                                ::
    ID: 07034213.wav
    Length: 28
** Tank Guns, 76mm high explosive shells fired three times. (Recorded outside tank.)                                                                                ::
    ID: 07034212.wav
    Length: 14
** Tank Guns, 76mm smoke shells fired four times. (Recorded inside tank.)                                                                                ::
    ID: 07034211.wav
    Length: 37
** 7.62mm tank machine gun firing. (Recorded outside tank.)                                                                                ::
    ID: 07034210.wav
    Length: 28
** 7.62mm tank machine gun firing. (Recorded inside tank.)                                                                                ::
    ID: 07034209.wav
    Length: 22
** 120mm Tank Gun firing 4 times. (Recorded outside tank.)                                                                                ::
    ID: 07034208.wav
    Length: 27
** 120mm Tank Gun firing. (Recorded inside tank.)                                                                                ::
    ID: 07034207.wav
    Length: 21
** Sten Gun, firing in bursts. (Used during World War II.)                                                                                ::
    ID: 07034206.wav
    Length: 26
** Sten Gun, firing in bursts. (Used during World War II.)                                                                                ::
    ID: 07034205.wav
    Length: 44
** .303 Rifle firing.                                                                                ::
    ID: 07034204.wav
    Length: 67
** .303 Rifle firing.                                                                                ::
    ID: 07034203.wav
    Length: 34
** .303 Rifle firing.                                                                                ::
    ID: 07034202.wav
    Length: 24
** Machine Gun fire, short bursts.                                                                                ::
    ID: 07034201.wav
    Length: 39
** Machine Gun fire, long bursts.                                                                                ::
    ID: 07034200.wav
    Length: 44
** Lewis Gun firing with frequent stoppages. (Used mainly by British Army, c. 1915-1939.)                                                                                ::
    ID: 07034199.wav
    Length: 116
** Vickers Mark 1 Machine Guns firing. (Used by British Army c. 1912-65.)                                                                                ::
    ID: 07034198.wav
    Length: 69
** 5.5-inch Guns, single shots fired.                                                                                ::
    ID: 07034197.wav
    Length: 58
** Heavy Mortar fire.                                                                                ::
    ID: 07034196.wav
    Length: 125
** Mortar fire.                                                                                ::
    ID: 07034195.wav
    Length: 65
** Artillery barrage.                                                                                ::
    ID: 07034194.wav
    Length: 390
** Shells whistling & landing.                                                                                ::
    ID: 07034193.wav
    Length: 93
** Shells whistling & landing.                                                                                ::
    ID: 07034192.wav
    Length: 97
** 25-pounder Guns fired..                                                                                ::
    ID: 07034191.wav
    Length: 93
** 8-inch Guns, single shots fired.                                                                                ::
    ID: 07034190.wav
    Length: 62
** 8-inch Guns, barrage fired.                                                                                ::
    ID: 07034189.wav
    Length: 185
** Shells passing overhead.                                                                                ::
    ID: 07034188.wav
    Length: 57
** 40mm Bofors Gun shells bursting. (Anti-aircraft guns in use from c. 1930s onwards.)                                                                                ::
    ID: 07034187.wav
    Length: 56
** 105mm shells fired, with vehicle noise & some voices in background.                                                                                ::
    ID: 07034186.wav
    Length: 41
** Furniture crashes.                                                                                ::
    ID: 07034185.wav
    Length: 17
** Continuous body falls, continuous heavy movement.                                                                                ::
    ID: 07034184.wav
    Length: 127
** Two body falls.                                                                                ::
    ID: 07034183.wav
    Length: 11
** Punches, three backhanders.                                                                                ::
    ID: 07034182.wav
    Length: 9
** Punches, four stomach punches.                                                                                ::
    ID: 07034181.wav
    Length: 14
** Punches, two uppercuts.                                                                                ::
    ID: 07034180.wav
    Length: 9
** Thirty-six people brawling.                                                                                ::
    ID: 07034179.wav
    Length: 60
** Six people brawling.                                                                                ::
    ID: 07034178.wav
    Length: 124
** Three people brawling.                                                                                ::
    ID: 07034177.wav
    Length: 123
**  South American parrot talking and screeching.                                                                                ::
    ID: 07034176.wav
    Length: 196
** Parrot talking & squawking.                                                                                ::
    ID: 07034175.wav
    Length: 164
** 450 budgerigars & canaries in a show.                                                                                ::
    ID: 07034174.wav
    Length: 199
** Canary singing.                                                                                ::
    ID: 07034173.wav
    Length: 184
** 56 budgerigars in a show.                                                                                ::
    ID: 07034172.wav
    Length: 395
** Budgerigar singing & flying in a room.                                                                                ::
    ID: 07034171.wav
    Length: 131
** Two budgerigars singing.                                                                                ::
    ID: 07034170.wav
    Length: 111
** Budgerigar singing.                                                                                ::
    ID: 07034169.wav
    Length: 130
** Armoured Car, exterior, fails to climb steep gradient, reverses. (Alvis Saracen or Saladin armoured car - both use same chassis.)                                                                                ::
    ID: 07034168.wav
    Length: 50
** Armoured Car, exterior approach, stop, start up, depart. (Alvis Saracen or Saladin armoured car - both use same chassis.)                                                                                ::
    ID: 07034167.wav
    Length: 36
** Armoured Car, exterior, start up, depart. (Alvis Saracen or Saladin armoured car - both use same chassis.)                                                                                ::
    ID: 07034166.wav
    Length: 36
** Armoured Car, exterior, approach, stop, switch off. (Alvis Saracen or Saladin armoured car - both use same chassis.)                                                                                ::
    ID: 07034165.wav
    Length: 20
** Armoured Car, exterior, approach and pass on gradient. (Alvis Saracen or Saladin armoured car - both use same chassis.)                                                                                ::
    ID: 07034164.wav
    Length: 33
** Armoured Car, exterior, approach and pass on gradient. (Alvis Saracen or Saladin armoured car - both use same chassis.)                                                                                ::
    ID: 07034163.wav
    Length: 74
** Armoured Car, interior, start, reversing, into constant run, stop, switch off. (Alvis Saracen or Saladin armoured car - both use same chassis.)                                                                                ::
    ID: 07034162.wav
    Length: 334
** English Electric Lightning, exterior, starting-up proceedure. (Jet engined fighter plane.)                                                                                ::
    ID: 07034161.wav
    Length: 231
** English Electric Lightning, exterior, twenty-six planes passing over. (Jet engined fighter plane.)                                                                                ::
    ID: 07034160.wav
    Length: 46
** English Electric Lightning, exterior, two waves of four planes passing over. (Jet engined fighter plane.)                                                                                ::
    ID: 07034159.wav
    Length: 57
** English Electric Lightning, exterior, plane passing over. (Jet engined fighter plane.)                                                                                ::
    ID: 07034158.wav
    Length: 22
** English Electric Lightning, exterior, plane passing over. (Jet engined fighter plane.)                                                                                ::
    ID: 07034157.wav
    Length: 28
** English Electric Lightning, exterior, plane passing over. (Jet engined fighter plane.)                                                                                ::
    ID: 07034156.wav
    Length: 58
** English Electric Lightning, exterior, plane passing over. (Jet engined fighter plane.)                                                                                ::
    ID: 07034155.wav
    Length: 43
** English Electric Lightning, exterior, plane passing over. (Jet engined fighter plane.)                                                                                ::
    ID: 07034154.wav
    Length: 63
** English Electric Lightning, exterior, three planes land in succession. (Jet engined fighter plane.)                                                                                ::
    ID: 07034153.wav
    Length: 63
** English Electric Lightning, exterior, several planes landing. (Jet engined fighter plane.)                                                                                ::
    ID: 07034152.wav
    Length: 142
** English Electric Lightning, exterior, landing. (Jet engined fighter plane.)                                                                                ::
    ID: 07034151.wav
    Length: 30
** English Electric Lightning, exterior, landing. (Jet engined fighter plane.)                                                                                ::
    ID: 07034150.wav
    Length: 25
** English Electric Lightning, exterior, twenty-six planes take off. (Jet engined fighter plane.)                                                                                ::
    ID: 07034149.wav
    Length: 138
** English Electric Lightning, exterior, two planes take off. (Jet engined fighter plane.)                                                                                ::
    ID: 07034148.wav
    Length: 46
** English Electric Lightning, exterior, take off. (Jet engined fighter plane.)                                                                                ::
    ID: 07034147.wav
    Length: 26
** English Electric Lightning, exterior, take off. (Jet engined fighter plane.)                                                                                ::
    ID: 07034146.wav
    Length: 70
** English Electric Lightning, exterior, taxi & take off. (Jet engined fighter plane.)                                                                                ::
    ID: 07034145.wav
    Length: 130
** English Electric Lightning, exterior, taxi away. (Jet engined fighter plane.)                                                                                ::
    ID: 07034144.wav
    Length: 55
** Heart beating, 18 year old male's heart.                                                                                ::
    ID: 07034143.wav
    Length: 331
** Small crowd gasps.                                                                                ::
    ID: 07034142.wav
    Length: 13
** Maniacal laughter.                                                                                ::
    ID: 07034141.wav
    Length: 44
** Woman yawning.                                                                                ::
    ID: 07034140.wav
    Length: 28
** Woman sighing.                                                                                ::
    ID: 07034139.wav
    Length: 20
** Woman groaning.                                                                                ::
    ID: 07034138.wav
    Length: 57
** Six men groaning.                                                                                ::
    ID: 07034137.wav
    Length: 54
** Man groaning.                                                                                ::
    ID: 07034136.wav
    Length: 31
** Woman snoring.                                                                                ::
    ID: 07034135.wav
    Length: 100
** Man snoring.                                                                                ::
    ID: 07034134.wav
    Length: 80
** Heavy breathing, man breathing (000m56s) into woman breathing (001m15s).                                                                                ::
    ID: 07034133.wav
    Length: 143
** Thirteen hiccoughs.                                                                                ::
    ID: 07034132.wav
    Length: 34
** Six belches.                                                                                ::
    ID: 07034131.wav
    Length: 21
** Man coughing.                                                                                ::
    ID: 07034130.wav
    Length: 68
** Woman, sneezes seven times.                                                                                ::
    ID: 07034129.wav
    Length: 24
** Man, sneezes seven times.                                                                                ::
    ID: 07034128.wav
    Length: 41
** Man blowing nose.                                                                                ::
    ID: 07034127.wav
    Length: 23
** Three men screaming with echo.                                                                                ::
    ID: 07034126.wav
    Length: 11
** Man screaming twice.                                                                                ::
    ID: 07034125.wav
    Length: 13
** Man screaming.                                                                                ::
    ID: 07034124.wav
    Length: 8
** Woman, hysterical crying.                                                                                ::
    ID: 07034123.wav
    Length: 62
** Woman, uncontrolled sobbing.                                                                                ::
    ID: 07034122.wav
    Length: 65
** Woman, two burlesque screams.                                                                                ::
    ID: 07034121.wav
    Length: 21
** Woman, two screams as at apparition.                                                                                ::
    ID: 07034120.wav
    Length: 25
** Woman, two long screams.                                                                                ::
    ID: 07034119.wav
    Length: 24
** Woman, three fairly short screams.                                                                                ::
    ID: 07034118.wav
    Length: 13
** Two women screaming.                                                                                ::
    ID: 07034117.wav
    Length: 14
** Referee's whistle blown, single blast, double blast, long blast, longer blast.                                                                                ::
    ID: 07034116.wav
    Length: 13
** Police whistles blown, single blast, double blast, treble blast.                                                                                ::
    ID: 07034115.wav
    Length: 17
** Tuneless whistling.                                                                                ::
    ID: 07034114.wav
    Length: 139
** Five finger whistles.                                                                                ::
    ID: 07034113.wav
    Length: 15
** Six wolf whistles.                                                                                ::
    ID: 07034112.wav
    Length: 22
** Shipyard: Fabrication Shed, Exterior, general atmosphere on the berth,  Wallsend, April 1985.                                                                                :Boats:Shipyard:
    ID: 07034111.wav
    Length: 245
** Shipyard: Fabrication Shed, Interior, joiner's shop, vertical moulding machine, Wallsend, April 1985.                                                                                :Boats:Shipyard:
    ID: 07034110.wav
    Length: 31
** Shipyard: Fabrication Shed, Interior, static machine grinder, Wallsend, April 1985.                                                                                :Boats:Shipyard:
    ID: 07034109.wav
    Length: 72
** Shipyard: Fabrication Shed, Interior, caulking with pneumatic chipping hammer, Wallsend, April 1985.                                                                                :Boats:Shipyard:
    ID: 07034108.wav
    Length: 81
** Ship Launch: 3,200 Tons, Sideways, before launch, Yorkshire crowd, close perspective. (Rec. Cochranes Shipyard. Selby July 1985)                                                                                :Boats:Ship Launch:
    ID: 07034107.wav
    Length: 202
** Ship Launch: 3,200 Tons, Sideways, bottle breaks, men hammer at props, cheers as boat begins to move, hits water at 1'43", 3 cheers.                                                                                :Boats:Ship Launch:
    ID: 07034106.wav
    Length: 175
** Beam Fishing Trawler: On Board, Washing catch on deck with hosepipe.                                                                                :Boats:Trawlers:Beam Fishing:
    ID: 07034105.wav
    Length: 54
** Beam Fishing Trawler: On Board, Gutting fish on deck.                                                                                :Boats:Trawlers:Beam Fishing:
    ID: 07034104.wav
    Length: 43
** Beam Fishing Trawler: On Board, Collecting trawled fish from deck.                                                                                 :Boats:Trawlers:Beam Fishing:
    ID: 07034103.wav
    Length: 110
** Beam Fishing Trawler: On Board, Catch being hauled inboard, opening and clearing trawl gear.                                                                                :Boats:Trawlers:Beam Fishing:
    ID: 07034102.wav
    Length: 116
** Beam Fishing Trawler: On Board, On deck before hauling trawl.                                                                                :Boats:Trawlers:Beam Fishing:
    ID: 07034101.wav
    Length: 172
** Beam Fishing Trawler: On Board, Trawl gear lowered into water.                                                                                :Boats:Trawlers:Beam Fishing:
    ID: 07034100.wav
    Length: 222
** Beam Fishing Trawler: On Board, Interior, docking, engine slows to tick over.                                                                                :Boats:Trawlers:Beam Fishing:
    ID: 07034099.wav
    Length: 89
** Beam Fishing Trawler: On Board, Interior, wheelhouse with vibration, track plotter, quiet.                                                                                 :Boats:Trawlers:Beam Fishing:
    ID: 07034098.wav
    Length: 143
** Beam Fishing Trawler: On Board, Interior, wheelhouse with gears, radio telephone, track plotter.                                                                                :Boats:Trawlers:Beam Fishing:
    ID: 07034097.wav
    Length: 170
** Beam Fishing Trawler: On Deck, at sea.                                                                                 :Boats:Trawlers:Beam Fishing:
    ID: 07034096.wav
    Length: 418
** Submarine: 1960 'P' class, night alarm in submarine.                                                                                :Boats:Submarine:1960 'P' Class:
    ID: 07034095.wav
    Length: 11
** Submarine: 1960 'P' class, during Emergency Stations, air conditioning closed down.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034094.wav
    Length: 65
** Submarine: 1960 'P' class, Emergency Stations.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034093.wav
    Length: 58
** Submarine: 1960 'P' class, air conditioning turned on.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034092.wav
    Length: 31
** Submarine: 1960 'P' class, bulkhead door closed.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034091.wav
    Length: 8
** Submarine: 1960 'P' class, bulkhead door opened.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034090.wav
    Length: 9
** Submarine: 1960 'P' class, air conditioning.                                                                                :Boats:Submarine:1960 'P' Class:
    ID: 07034089.wav
    Length: 217
** Submarine: 1960 'P' class, passive sonar.                                                                                :Boats:Submarine:1960 'P' Class:
    ID: 07034088.wav
    Length: 229
** Submarine: 1960 'P' class, Steering operated.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034087.wav
    Length: 24
** Submarine: 1960 'P' class, Hydroplanes operated.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034086.wav
    Length: 21
** Submarine: 1960 'P' class, Conning tower hatch closed.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034085.wav
    Length: 19
** Submarine: 1960 'P' class, Conning tower hatch opened.                                                                                :Boats:Submarine:1960 'P' Class:
    ID: 07034084.wav
    Length: 16
** Submarine: 1960 'P' class, Control room telegraph with reply gongs.                                                                                :Boats:Submarine:1960 'P' Class:
    ID: 07034083.wav
    Length: 12
** Submarine: 1960 'P' class, Control room telegraph of submarine.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034082.wav
    Length: 11
** Submarine: 1960 'P' class, Hydraulic pump.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034081.wav
    Length: 31
** Submarine: 1960 'P' class, Periscope moving downwards.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034080.wav
    Length: 26
** Submarine: 1960 'P' class, Periscope moving upwards.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034079.wav
    Length: 14
** Submarine: 1960 'P' class, Surfacing, full sequence with orders.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034078.wav
    Length: 44
** Submarine: 1960 'P' class, Klaxon , 2 blasts, vents open, dive.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034077.wav
    Length: 26
** Submarine: 1960 'P' class, Klaxon, 3 blasts.                                                                                 :Boats:Submarine:1960 'P' Class:
    ID: 07034076.wav
    Length: 15
** Boeing Jetfoil: Interior, constant run.                                                                                 :Boats:Hydrofoil:Boeing Jetfoil:
    ID: 07034075.wav
    Length: 197
** Boeing Jetfoil: Exterior, start and depart.                                                                                 :Boats:Hydrofoil:Boeing Jetfoil:
    ID: 07034074.wav
    Length: 92
** Boeing Jetfoil: Exterior, arrive and stop.                                                                                 :Boats:Hydrofoil:Boeing Jetfoil:
    ID: 07034073.wav
    Length: 103
** Hovercraft: SRN Super 4, Interior, constant run, some indistinguishable voices.                                                                                :Boats:Hovercraft:SRN Super 4:
    ID: 07034072.wav
    Length: 176
** Hovercraft: SRN Super 4, Exterior, start and depart.                                                                                 :Boats:Hovercraft:SRN Super 4:
    ID: 07034071.wav
    Length: 111
** Hovercraft: SRN Super 4, Exterior, arrive, stop with slight activity at end.                                                                                :Boats:Hovercraft:SRN Super 4:
    ID: 07034070.wav
    Length: 128
** Sailing Ship: Gaff-rigged Ketch, Exterior, four man ship's whaler pulls alongside ship.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034069.wav
    Length: 29
** Sailing Ship: Gaff-rigged Ketch, Exterior, four men rowing ship's whaler.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034068.wav
    Length: 85
** Sailing Ship: Gaff-rigged Ketch, Exterior, ship's anchor being run out.                                                                                :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034067.wav
    Length: 17
** Sailing Ship: Gaff-rigged Ketch, Exterior, man rowing ship's tender at sea, boat pulled onto shingle beach.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034066.wav
    Length: 75
** Sailing Ship: Gaff-rigged Ketch, Exterior, man rowing ship's tender, medium pace, stops with shipping of oars.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034065.wav
    Length: 68
** Sailing Ship: Gaff-rigged Ketch, Exterior, man rowing ship's tender gently.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034064.wav
    Length: 76
** Sailing Ship: Gaff-rigged Ketch, Exterior, mizzen sail hoisted.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034063.wav
    Length: 39
** Sailing Ship: Gaff-rigged Ketch, Exterior, mizzen sail dropped.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034062.wav
    Length: 44
** Sailing Ship: Gaff-rigged Ketch, Exterior, foresail sheets squealing with sail flap.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034061.wav
    Length: 50
** Sailing Ship: Gaff-rigged Ketch, Exterior, hauling mainsail.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034060.wav
    Length: 52
** Sailing Ship: Gaff-rigged Ketch, Exterior, seven bells rung.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034059.wav
    Length: 14
** Sailing Ship: Gaff-rigged Ketch, Exterior, eight bells rung.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034058.wav
    Length: 16
** Sailing Ship: Gaff-rigged Ketch, water slopping and bubbling in bilges, distant seawash.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034057.wav
    Length: 218
** Sailing Ship: Gaff-rigged Ketch, in forecastle, flap of sails, foresail hoisted, sound of seawash.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034056.wav
    Length: 216
** Sailing Ship: Gaff-rigged Ketch, Interior, below decks, at sea, crashes, distant sea spray.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034055.wav
    Length: 22
** Sailing Ship: Gaff-rigged Ketch, Interior, below decks, at sea, creaks, distant sea spray.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034054.wav
    Length: 366
** Sailing Ship: Gaff-rigged Ketch, Exterior, sails flapping, ropes creaking, distant seawash, on deck.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034053.wav
    Length: 248
** Sailing Ship: Gaff-rigged Ketch, Interior, mast creaking, in day cabin.                                                                                :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034052.wav
    Length: 217
** Sailing Ship: Gaff-rigged Ketch, Interior, day cabin, creaks.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034051.wav
    Length: 397
** Sailing Ship: Gaff-rigged Ketch, Exterior, heavy sea, rain, force 5-6 wind from midships.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034050.wav
    Length: 430
** Sailing Ship: Gaff-rigged Ketch, Exterior, bow wave in heavy sea.                                                                                 :Boats:Sailing:Gaff-rigged Ketch:
    ID: 07034049.wav
    Length: 416
** Paddle Steamer: Built 1940, horizontal steam engine, water lapping against steamer in dock.                                                                                 :Boats:Paddle Steamers:
    ID: 07034048.wav
    Length: 393
** Paddle Steamer: Built 1940, horizontal steam engine, boiler being stoked.                                                                                 :Boats:Paddle Steamers:
    ID: 07034047.wav
    Length: 161
** Paddle Steamer: Built 1940, horizontal steam engine, loading coal from quayside trucks.                                                                                 :Boats:Paddle Steamers:
    ID: 07034046.wav
    Length: 64
** Paddle Steamer: Built 1940, horizontal steam engine, loading coal from quayside trucks.                                                                                 :Boats:Paddle Steamers:
    ID: 07034045.wav
    Length: 88
** Paddle Steamer: Built 1940, horizontal steam engine, arrival & mooring, on deck.                                                                                 :Boats:Paddle Steamers:
    ID: 07034044.wav
    Length: 197
** Paddle Steamer: Built 1940, horizontal steam engine, departure from quay, on deck.                                                                                 :Boats:Paddle Steamers:
    ID: 07034043.wav
    Length: 131
** Paddle Steamer: Built 1940, horizontal steam engine, hooter, on deck.                                                                                 :Boats:Paddle Steamers:
    ID: 07034042.wav
    Length: 10
** Paddle Steamer: Built 1940, horizontal steam engine, paddles in motion, at water level.                                                                                 :Boats:Paddle Steamers:
    ID: 07034041.wav
    Length: 199
** Paddle Steamer: Built 1940, horizontal steam engine, constant run, in engine room.                                                                                 :Boats:Paddle Steamers:
    ID: 07034040.wav
    Length: 207
** Paddle Steamer: Built 1940, horizontal steam engine, stop with telegraph, in engine room.                                                                                 :Boats:Paddle Steamers:
    ID: 07034039.wav
    Length: 208
** Paddle Steamer: Built 1940, horizontal steam engine, start & run with telegraph, in engine room.                                                                                 :Boats:Paddle Steamers:
    ID: 07034038.wav
    Length: 221
** Paddle Steamer: Built 1940, horizontal steam engine, departure, from quay.                                                                                 :Boats:Paddle Steamers:
    ID: 07034037.wav
    Length: 96
** Paddle Steamer: Built 1940, horizontal steam engine, arrival and mooring, from quay.                                                                                 :Boats:Paddle Steamers:
    ID: 07034036.wav
    Length: 305
** Steam Launch: 19thC "Victoria", 31ft long, engine at cruising speed, boiler being stoked.                                                                                 :Boats:Steam Launch:
    ID: 07034035.wav
    Length: 377
** Steam Launch: 19thC "Victoria", 31ft long, several whistles.                                                                                 :Boats:Steam Launch:
    ID: 07034034.wav
    Length: 16
** Steam Launch: 19thC "Victoria", 31ft long, engine starts and runs, boiler stoked, engine stops.                                                                                 :Boats:Steam Launch:
    ID: 07034033.wav
    Length: 207
** Steam Launch: 19thC "Victoria", 31ft long, pre-running, engine stops.                                                                                 :Boats:Steam Launch:
    ID: 07034032.wav
    Length: 99
** Steam Launch: 19thC "Victoria", 31ft long, pumping water into boiler, start and stop.                                                                                :Boats:Steam Launch:
    ID: 07034031.wav
    Length: 83
** Small Boats On Lake: Rowed from left to right.                                                                                :Small Boats On Lake:Rowed from left to right:
    ID: 07034030.wav
    Length: 60
** Small Boats On Lake: Rowing Boat, beaching.                                                                                :Small Boats On Lake:Rowing Boat, beaching:
    ID: 07034029.wav
    Length: 23
** Small Boats On Lake: Rowing Boat, launch.                                                                                :Small Boats On Lake:Rowing Boat, launch:
    ID: 07034028.wav
    Length: 12
** Small Boats On Lake: Rowing Boat, start rowing and stop.                                                                                :Small Boats On Lake:Rowing Boat, start rowing and stop:
    ID: 07034027.wav
    Length: 207
** Small Boats On Lake: Sails flapping.                                                                                :Small Boats On Lake:Sails flapping:
    ID: 07034026.wav
    Length: 23
** Small Boats On Lake: Sailing Dinghy,sails lowered.                                                                                :Small Boats On Lake:Sailing Dinghy,sails lowered:
    ID: 07034025.wav
    Length: 22
** Small Boats On Lake: Sailing Dinghy,sails raised.                                                                                :Small Boats On Lake:Sailing Dinghy,sails raised:
    ID: 07034024.wav
    Length: 50
** Small Boats On Lake: Sailing Dinghy, water lapping, ropes creaking, squeaks, movement.                                                                                :Small Boats On Lake:Sailing Dinghy, water lapping, ropes creaki:
    ID: 07034023.wav
    Length: 214
** Ferry: Mersey, Liverpool, Interior, moving, cabin, occasional voices and activity.                                                                                :Boats:Ferries:Mersey:
    ID: 07034022.wav
    Length: 367
** Ferry: Mersey, Liverpool, Exterior, moving, bow wash.                                                                                :Boats:Ferries:Mersey:
    ID: 07034021.wav
    Length: 119
** Ferry: Mersey, Liverpool, quayside, departs.                                                                                :Boats:Ferries:Mersey:
    ID: 07034020.wav
    Length: 108
** Ferry: Mersey, Liverpool, quayside, arrives, gang planks put out, people board.                                                                                 :Boats:Ferries:Mersey:
    ID: 07034019.wav
    Length: 127
** Ferry: Mersey, Liverpool, on board, arrives, gang-plank lowered, passengers disembark.                                                                                :Boats:Ferries:Mersey:
    ID: 07034018.wav
    Length: 159
** Ferry: Mersey, Liverpool, diesel engines, in engine room.                                                                                 :Boats:Ferries:Mersey:
    ID: 07034017.wav
    Length: 255
** Ferry: Mersey, Liverpool, upper deck whilst underway.                                                                                :Boats:Ferries:Mersey:
    ID: 07034016.wav
    Length: 363
** Ferry: Cross-Channel, 'Dover', Engine room, distant voices.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034015.wav
    Length: 374
** Ferry: Cross-Channel, 'Dover', Boiler room, distant voices.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034014.wav
    Length: 374
** Ferry: Cross-Channel, 'Dover', Seawash recorded from anchor chain locker.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034013.wav
    Length: 369
** Ferry: Cross-Channel, 'Dover', Bar atmosphere, quiet.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034012.wav
    Length: 371
** Ferry: Cross-Channel, 'Dover', Seawash recorded from starboard bow. (Biased to L.)                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034011.wav
    Length: 355
** Ferry: Cross-Channel, 'Dover', Seawash recorded from stern.                                                                                 :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034010.wav
    Length: 357
** Ferry: Cross-Channel, 'Dover', bridge, ship comes into dock, intelligible orders, siren.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034009.wav
    Length: 456
** Ferry: Cross-Channel, 'Dover', bridge, as ship approaches harbour.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034008.wav
    Length: 423
** Ferry: Cross-Channel, 'Dover', sea-going motor launch, starts and runs.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034007.wav
    Length: 152
** Ferry: Cross-Channel, 'Dover', bridge, casting off, distinct orders and replies.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034006.wav
    Length: 286
** Ferry: Cross-Channel, 'Dover', bridge, siren sounded.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034005.wav
    Length: 17
** Ferry: Cross-Channel, 'Dover', bridge, radio, telephone, voices.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034004.wav
    Length: 45
** Ferry: Cross-Channel, 'Dover', bridge, before sailing, machine hum, movement, quiet voices.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034003.wav
    Length: 239
** Ferry: Cross-Channel, 'Dover', ship's engines.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034002.wav
    Length: 402
** Ferry: Cross-Channel, 'Dover', vehicles loading onto car deck.                                                                                :Boats:Ferries:Cross-Channel:Dover:
    ID: 07034001.wav
    Length: 397
** Mark V Tank, interior, start up, constant run over rough ground (stops at 002m30s). (World War I Tank, c. 1916.)                                                                                ::
    ID: 07033192.wav
    Length: 322
** Mark V Tank, interior, false start, start, misfire, tickover. (World War I Tank, c. 1916.)                                                                                ::
    ID: 07033191.wav
    Length: 66
** Mark V Tank, exterior, stop, switch off. (World War I Tank, c. 1916.)                                                                                ::
    ID: 07033190.wav
    Length: 22
** Mark V Tank, exterior, approach climbing steep bank, with gear changes. (World War I Tank, c. 1916.)                                                                                ::
    ID: 07033189.wav
    Length: 175
** Mark V Tank, exterior, start up, passing & manoeuvring on rough ground. (World War I Tank, c. 1916.)                                                                                ::
    ID: 07033188.wav
    Length: 186
** World War II Anti-aircraft Fire.                                                                                ::
    ID: 07033187.wav
    Length: 250
** World War II Air Raid Siren, French, all clear sounded.                                                                                ::
    ID: 07033186.wav
    Length: 69
** World War II Air Raid Siren, French, alert sounded.                                                                                ::
    ID: 07033185.wav
    Length: 70
** World War II Air Raid Siren, Italian, all clear sounded.                                                                                ::
    ID: 07033184.wav
    Length: 62
** World War II Air Raid Siren, Italian, alert sounded.                                                                                ::
    ID: 07033183.wav
    Length: 73
** World War II Air Raid Siren, German, all clear sounded.                                                                                ::
    ID: 07033182.wav
    Length: 53
** World War II Air Raid Siren, German, alert sounded.                                                                                ::
    ID: 07033181.wav
    Length: 69
** World War II Air Raid Sirens, English, all clear sounded.                                                                                ::
    ID: 07033180.wav
    Length: 85
** World War II Air Raid Siren, English, alert sounded.                                                                                ::
    ID: 07033179.wav
    Length: 67
** Local Diesel Train, train arrives, one door, departs (with birdsong).                                                                                ::
    ID: 07033178.wav
    Length: 86
** Local Diesel Train, train arrives, no doors, departs.                                                                                ::
    ID: 07033177.wav
    Length: 97
** Local Diesel Train, general atmosphere as train arrives at station.                                                                                ::
    ID: 07033176.wav
    Length: 158
** Local Diesel Train, train departs.                                                                                ::
    ID: 07033175.wav
    Length: 124
** Local Diesel Train, train arrives, passengers disembark.                                                                                ::
    ID: 07033174.wav
    Length: 131
** Local Diesel Train, Guard's whistle, train departs.                                                                                 ::
    ID: 07033173.wav
    Length: 64
** Railway Station, country town diesel train termius, general atmosphere with doors, chatter & footsteps.                                                                                ::
    ID: 07033172.wav
    Length: 392
** Railway Station, country town diesel train termius, general atmosphere with factory siren at start & occassional traffic.                                                                                ::
    ID: 07033171.wav
    Length: 397
** Railway Station, small diesel train termius, general atmosphere.                                                                                ::
    ID: 07033170.wav
    Length: 380
** Railway Station, small diesel train termius, general atmosphere.                                                                                ::
    ID: 07033169.wav
    Length: 375
** Train corridor door opened & closed.                                                                                ::
    ID: 07033168.wav
    Length: 13
** Train corridor door opened & closed.                                                                                ::
    ID: 07033167.wav
    Length: 13
** Old-type train window opened & closed.                                                                                ::
    ID: 07033166.wav
    Length: 22
** Train window with leather strap window opened & closed.                                                                                ::
    ID: 07033165.wav
    Length: 11
** Train window with leather strap opened (after struggle with strap).                                                                                ::
    ID: 07033164.wav
    Length: 26
** Train window opened & closed.                                                                                ::
    ID: 07033163.wav
    Length: 14
** Local Train, ratchet-type window blind raised & lowered.                                                                                ::
    ID: 07033162.wav
    Length: 14
** Local Train, window blind raised & lowered.                                                                                ::
    ID: 07033161.wav
    Length: 12
** Local Train, exterior, door opened & closed.                                                                                ::
    ID: 07033160.wav
    Length: 12
** Local Train, interior, door opened & closed.                                                                                ::
    ID: 07033159.wav
    Length: 14
** Long-Distance Train, exterior, window lowered, door opened & closed.                                                                                ::
    ID: 07033158.wav
    Length: 16
** Long-Distance Train, interior, window lowered, door opened & closed, window raised.                                                                                ::
    ID: 07033157.wav
    Length: 25
** London Bridge Railway Station, station bar atmosphere with P.A. in background.                                                                                ::
    ID: 07033156.wav
    Length: 205
** London Bridge Railway Station, station buffet atmosphere before rush hour.                                                                                ::
    ID: 07033155.wav
    Length: 196
** Tonbridge Railway Station, station buffet atmosphere during evening.                                                                                ::
    ID: 07033154.wav
    Length: 190
** Tonbridge Railway Station, station buffet atmosphere at teatime.                                                                                ::
    ID: 07033153.wav
    Length: 193
** Birmingham New Street Railway Station, general atmosphere (no announcements).                                                                                ::
    ID: 07033152.wav
    Length: 293
** Birmingham New Street Railway Station, station announcements in early morning.                                                                                ::
    ID: 07033151.wav
    Length: 52
** Birmingham New Street Railway Station, station announcements at 2130 hours.                                                                                 ::
    ID: 07033150.wav
    Length: 184
** Birmingham New Street Railway Station, station announcements at 0930 hours.                                                                                ::
    ID: 07033149.wav
    Length: 198
** Erith Railway Station, booking hall atmosphere with arrivals & steady flow of trains.                                                                                 ::
    ID: 07033148.wav
    Length: 207
** Erith Railway Station, booking hall atmosphere with evening arrivals.                                                                                ::
    ID: 07033147.wav
    Length: 192
** Bexleyheath Railway Station, booking hall atmosphere at 0920 hours, predominately women.                                                                                 ::
    ID: 07033146.wav
    Length: 200
** Bexleyheath Railway Station, booking hall atmosphere at 0700 hours.                                                                                ::
    ID: 07033145.wav
    Length: 198
** Charing Cross Railway Station, booking office atmosphere, near ticket machines.                                                                                ::
    ID: 07033144.wav
    Length: 195
** Charing Cross Railway Station, booking office atmosphere, with footsteps on wooden floor.                                                                                ::
    ID: 07033143.wav
    Length: 200
** London Bridge Railway Station, general atmosphere.                                                                                ::
    ID: 07033142.wav
    Length: 402
** Liverpool Street Railway Station, general atmosphere.                                                                                ::
    ID: 07033141.wav
    Length: 400
** Euston Railway Station, general atmosphere.                                                                                ::
    ID: 07033140.wav
    Length: 395
** Kings Cross Railway Station, general atmosphere.                                                                                ::
    ID: 07033139.wav
    Length: 400
** Charing Cross Railway Station, general atmosphere.                                                                                ::
    ID: 07033138.wav
    Length: 404
** Paddington Railway Station, general atmosphere.                                                                                ::
    ID: 07033137.wav
    Length: 401
** Waterloo Railway Station, general atmosphere.                                                                                ::
    ID: 07033136.wav
    Length: 397
** London Bridge Railway Station, public address announcements & atmosphere.                                                                                ::
    ID: 07033135.wav
    Length: 183
** Liverpool Street Railway Station, public address announcements & atmosphere. (Recorded early afternoon.)                                                                                ::
    ID: 07033134.wav
    Length: 205
** Euston Railway Station, public address announcements & atmosphere. (Recorded early afternoon.)                                                                                ::
    ID: 07033133.wav
    Length: 395
** Kings Cross Railway Station, public address announcements & atmosphere. (Recorded late morning.)                                                                                ::
    ID: 07033132.wav
    Length: 199
** Charing Cross Railway Station, continuous public address announcements & atmosphere. (Recorded early afternoon.)                                                                                ::
    ID: 07033131.wav
    Length: 194
** Victoria Railway Station, continuous public address announcements & atmosphere. (Recorded early afternoon.)                                                                                ::
    ID: 07033130.wav
    Length: 203
** Paddington Railway Station, continuous public address announcements & atmosphere. (Recorded early afternoon.)                                                                                ::
    ID: 07033129.wav
    Length: 198
** Waterloo Railway Station, continuous public address announcements & atmosphere. (Recorded early afternoon.)                                                                                ::
    ID: 07033128.wav
    Length: 210
** Four men walking in single file along a small passage in a cave.                                                                                ::
    ID: 07033127.wav
    Length: 129
** Four men walking with nailed boots in a dry passage in a cave.                                                                                ::
    ID: 07033126.wav
    Length: 126
** Four men walking in a dry passage in a cave.                                                                                ::
    ID: 07033125.wav
    Length: 124
** Man crawling quickly away through a 30ft drainpipe in a cave wearing steel toe-caps.                                                                                ::
    ID: 07033124.wav
    Length: 76
** Man crawling away through a 30ft drainpipe in a cave.                                                                                ::
    ID: 07033123.wav
    Length: 141
** Two men moving quickly along a 30ft drainpipe in a cave.                                                                                ::
    ID: 07033122.wav
    Length: 120
** Man approaching through a 30ft drainpipe in a cave.                                                                                ::
    ID: 07033121.wav
    Length: 83
** Water dripping in a large cavern.                                                                                ::
    ID: 07033120.wav
    Length: 123
** Boulders falling 70ft into a cavern. (Five takes.)                                                                                ::
    ID: 07033119.wav
    Length: 49
** Small boulders rolling & falling in a cave. (Six takes.)                                                                                ::
    ID: 07033118.wav
    Length: 61
** Stones falling down 60ft pot-hole in a cave. (Six takes.)                                                                                ::
    ID: 07033117.wav
    Length: 50
** Man descending ladder in a cave.                                                                                ::
    ID: 07033116.wav
    Length: 139
** Man climbing ladder quickly in a cave with rubber boots.                                                                                ::
    ID: 07033115.wav
    Length: 99
** Man climbing ladder in a cave with rubber boots.                                                                                ::
    ID: 07033114.wav
    Length: 105
** Man climbing ladder in a cave with rubber boots and steel toe-caps.                                                                                ::
    ID: 07033113.wav
    Length: 79
** Wire ladder hauled up in a cave. (Medium perspective recording.)                                                                                ::
    ID: 07033112.wav
    Length: 81
** Wire ladder hauled up in a cave. (Close perspective recording.)                                                                                ::
    ID: 07033111.wav
    Length: 95
** Wire ladder thrown down pitch in a cave. (Medium perspective recording.)                                                                                ::
    ID: 07033110.wav
    Length: 9
** Wire ladder thrown down pitch in a cave. (Close perspective recording.)                                                                                ::
    ID: 07033109.wav
    Length: 11
** Wire ladder unrolled at top of 60ft pitch in a cave.                                                                                ::
    ID: 07033108.wav
    Length: 73
** Stream trickling through small cavern in a cave. (Close perspective recording.)                                                                                ::
    ID: 07033107.wav
    Length: 123
** Stream trickling through small cavern in a cave.                                                                                ::
    ID: 07033106.wav
    Length: 122
** Water running into small underground lake in a cave.                                                                                ::
    ID: 07033105.wav
    Length: 126
** 20ft waterfall in a cave. (Recorded from bottom of fall.)                                                                                ::
    ID: 07033104.wav
    Length: 123
** 20ft waterfall in a cave. (Recorded from top.)                                                                                ::
    ID: 07033103.wav
    Length: 122
** 40ft waterfall in a cave. (Recorded from bottom of fall.)                                                                                ::
    ID: 07033102.wav
    Length: 123
** 40ft waterfall in a cave. (Recorded at the top from distance of 15 feet.)                                                                                ::
    ID: 07033101.wav
    Length: 124
** Water in small passage leading to waterfall in a cave.                                                                                ::
    ID: 07033100.wav
    Length: 126
** 40ft waterfall in a cave. (Recorded from top.)                                                                                ::
    ID: 07033099.wav
    Length: 122
** 40ft waterfall in a cave.                                                                                ::
    ID: 07033098.wav
    Length: 124
** 40ft waterfall in a cave. (Recorded from top.)                                                                                ::
    ID: 07033097.wav
    Length: 124
** Stream running through a medium-sized cave.                                                                                ::
    ID: 07033096.wav
    Length: 123
** Stream flowing in a cave.                                                                                ::
    ID: 07033095.wav
    Length: 123
** Stream entering a cave.                                                                                ::
    ID: 07033094.wav
    Length: 123
** Small stream running through field near caves.                                                                                ::
    ID: 07033093.wav
    Length: 129
** Signal sequence, whistles with spoken introduction.                                                                                ::
    ID: 07033092.wav
    Length: 37
** Single stone falling in cave.                                                                                ::
    ID: 07033091.wav
    Length: 9
** Single rock falling in cave.                                                                                ::
    ID: 07033090.wav
    Length: 9
** Single stone falling in cave.                                                                                ::
    ID: 07033089.wav
    Length: 8
** Man climbing & slipping.                                                                                ::
    ID: 07033088.wav
    Length: 21
** Man climbing rock face.                                                                                ::
    ID: 07033087.wav
    Length: 42
** Man climbing, with start & stop.                                                                                ::
    ID: 07033086.wav
    Length: 20
** Woman climbing, with start & stop.                                                                                ::
    ID: 07033085.wav
    Length: 35
** Tired man walking with start & stop.                                                                                ::
    ID: 07033084.wav
    Length: 45
** Two tired men walking with start & stop.                                                                                ::
    ID: 07033083.wav
    Length: 45
** Two men constant walking up sharp incline of loose stones.                                                                                ::
    ID: 07033082.wav
    Length: 43
** Man constant walking up sharp incline of loose stones.                                                                                ::
    ID: 07033081.wav
    Length: 62
** Two men crawling along small passage.                                                                                ::
    ID: 07033080.wav
    Length: 127
** Man crawling along small passage, approach & pass.                                                                                ::
    ID: 07033079.wav
    Length: 51
** Group walking through large chamber.                                                                                ::
    ID: 07033078.wav
    Length: 75
** Group walking through small chamber, with start & stop.                                                                                ::
    ID: 07033077.wav
    Length: 110
** Water at bottom of pitch.                                                                                ::
    ID: 07033076.wav
    Length: 112
** Water dripping in a passage. (Close perspective recording.)                                                                                ::
    ID: 07033075.wav
    Length: 47
** Water dripping in a passage. (Distant perspective recording.)                                                                                ::
    ID: 07033074.wav
    Length: 45
** Water running in a cavern. (Close perspective recording.)                                                                                ::
    ID: 07033073.wav
    Length: 58
** Water running in a cavern. (Medium perspective recording.)                                                                                ::
    ID: 07033072.wav
    Length: 67
** Brickworks, roller clay-crushing machine operating.                                                                                ::
    ID: 07033071.wav
    Length: 202
** Brickworks, 'Clayton Goodfellows' junior brick-stamping machine operating.                                                                                ::
    ID: 07033070.wav
    Length: 196
** Brickworks, diesel heavy-duty fork-lift truck operating, loading bricks on to lorry.                                                                                ::
    ID: 07033069.wav
    Length: 334
** Brickworks, diesel heavy-duty fork-lift truck operating, load collapses & falls.                                                                                ::
    ID: 07033068.wav
    Length: 27
** Brickworks, works closing down.                                                                                ::
    ID: 07033067.wav
    Length: 242
** Brickworks, stacking & sorting bricks, throwing out rejects, with birdsong in background.                                                                                ::
    ID: 07033066.wav
    Length: 127
** Brickworks, warning hooter, works start up.                                                                                ::
    ID: 07033065.wav
    Length: 389
** Papermaking, pulp breaker slow down & switch off.                                                                                ::
    ID: 07033064.wav
    Length: 81
** Papermaking, pulp breaker running.                                                                                ::
    ID: 07033063.wav
    Length: 96
** Papermaking, pulp breaker switch on & run.                                                                                ::
    ID: 07033062.wav
    Length: 191
** Papermaking, atmosphere in a vat room.                                                                                ::
    ID: 07033061.wav
    Length: 188
** Papermaking, atmosphere in a pressing room.                                                                                ::
    ID: 07033060.wav
    Length: 193
** Papermaking, drying process in operation.                                                                                ::
    ID: 07033059.wav
    Length: 125
** Papermaking, pulp grinding.                                                                                ::
    ID: 07033058.wav
    Length: 124
** Papermaking, boiler being rotated.                                                                                ::
    ID: 07033057.wav
    Length: 128
** Papermaking, boiler lid being fitted.                                                                                ::
    ID: 07033056.wav
    Length: 182
** Papermaking, rag cutting machine operating with start, run, stop.                                                                                ::
    ID: 07033055.wav
    Length: 211
** Papermaking, Wohlenberg Flying Carpet guillotine operating.                                                                                ::
    ID: 07033054.wav
    Length: 202
** Papermaking, air knife coater operating.                                                                                ::
    ID: 07033053.wav
    Length: 197
** Papermaking, atmosphere in yard.                                                                                ::
    ID: 07033052.wav
    Length: 200
** Papermaking, hand sorting paper, rejecting imperfect sheets.                                                                                ::
    ID: 07033051.wav
    Length: 199
** Papermaking, changing a reel centre.                                                                                ::
    ID: 07033050.wav
    Length: 153
** Papermaking, dry end of reeler.                                                                                ::
    ID: 07033049.wav
    Length: 139
** Papermaking, sludge pump operating with start & stop.                                                                                ::
    ID: 07033048.wav
    Length: 97
** Papermaking, machine house atmosphere.                                                                                ::
    ID: 07033047.wav
    Length: 249
** Papermaking, machine house atmosphere.                                                                                ::
    ID: 07033046.wav
    Length: 147
** Papermaking, atmosphere in a shaft room.                                                                                ::
    ID: 07033045.wav
    Length: 124
** Papermaking, clay storage chest operating.                                                                                ::
    ID: 07033044.wav
    Length: 125
** Papermaking, clay slurry ram pump operating.                                                                                ::
    ID: 07033043.wav
    Length: 124
** Papermaking, potcher (pulp machine) operating.                                                                                ::
    ID: 07033042.wav
    Length: 123
** Papermaking, several potchers (pulp machines) operating.                                                                                ::
    ID: 07033041.wav
    Length: 125
** Papermaking, potchers (pulp machine) operating.                                                                                ::
    ID: 07033040.wav
    Length: 124
** Gasworks, box purifier operating.                                                                                ::
    ID: 07033039.wav
    Length: 196
** Gasworks, steam hammer operating.                                                                                ::
    ID: 07033038.wav
    Length: 157
** Gasworks, general yard background atmosphere.                                                                                ::
    ID: 07033037.wav
    Length: 160
** Gasworks, exhauster operating.                                                                                ::
    ID: 07033036.wav
    Length: 181
** Gasworks, loading coke on to lorries.                                                                                ::
    ID: 07033035.wav
    Length: 157
** Gasworks, fan booster being switched off.                                                                                ::
    ID: 07033034.wav
    Length: 213
** Gasworks, retort house operating.                                                                                ::
    ID: 07033033.wav
    Length: 198
** Gasworks, retort house operating.                                                                                ::
    ID: 07033032.wav
    Length: 189
** Gasworks, coke grader operating.                                                                                ::
    ID: 07033031.wav
    Length: 303
** Gasworks, crane moving on caterpillar tracks.                                                                                ::
    ID: 07033030.wav
    Length: 152
** Gasworks, cranes re-piling coke.                                                                                ::
    ID: 07033029.wav
    Length: 149
** Gasworks, two lorries crossing weighbridge.                                                                                ::
    ID: 07033028.wav
    Length: 95
** Gasworks, vertical retort house discharging coke from bottom stage hopper on to belt conveyor.                                                                                ::
    ID: 07033027.wav
    Length: 295
** Gasworks, shunting empty trucks.                                                                                ::
    ID: 07033026.wav
    Length: 104
** Gasworks, conveying coke to hoppers.                                                                                ::
    ID: 07033025.wav
    Length: 195
** Gasworks, filling sacks with coke.                                                                                ::
    ID: 07033024.wav
    Length: 160
** Gasworks, boiler alarm blowing off.                                                                                ::
    ID: 07033023.wav
    Length: 19
** Gasworks, cleaning a producer fire.                                                                                ::
    ID: 07033022.wav
    Length: 155
** Gasworks, retort nodding to keep coal running evenly.                                                                                ::
    ID: 07033021.wav
    Length: 153
** Gasworks, filling retort with coal from top hoppers.                                                                                ::
    ID: 07033020.wav
    Length: 85
** Gasworks, Governor House, general atmosphere in late morning, machinery starts up.                                                                                ::
    ID: 07033019.wav
    Length: 201
** Gasworks, Governor House, general atmosphere in early morning.                                                                                ::
    ID: 07033018.wav
    Length: 183
** Glassworks, flatting the top of a vase.                                                                                ::
    ID: 07033017.wav
    Length: 31
** Glassworks, polishing glassware on cork.                                                                                ::
    ID: 07033016.wav
    Length: 36
** Glassworks, bevelling glassware.                                                                                ::
    ID: 07033015.wav
    Length: 20
** Glassworks, hand cutting glassware.                                                                                ::
    ID: 07033014.wav
    Length: 38
** Glassworks, sharpening a cutter wheel.                                                                                ::
    ID: 07033013.wav
    Length: 53
** Glassworks, shaping tumblers with cutters.                                                                                ::
    ID: 07033012.wav
    Length: 51
** Glassworks, grinding glassware.                                                                                ::
    ID: 07033011.wav
    Length: 111
** Glassworks, polishing & grinding glassware.                                                                                ::
    ID: 07033010.wav
    Length: 112
** Glassworks, colour printing machine operating with the sound of bottles.                                                                                ::
    ID: 07033009.wav
    Length: 113
** Glassworks, bottles being hand inspected on a conveyor belt with some chatter.                                                                                ::
    ID: 07033008.wav
    Length: 88
** Glassworks, molten glass poured into moulds.                                                                                ::
    ID: 07033007.wav
    Length: 90
** Glassworks, manufacturing glass bottles, furnace & casting.                                                                                ::
    ID: 07033006.wav
    Length: 89
** Glassworks, cutting a glass sheet with some talking in background.                                                                                ::
    ID: 07033005.wav
    Length: 89
** Glassworks, processing plant operating, cutting & returning broken glass.                                                                                ::
    ID: 07033004.wav
    Length: 95
** Glassworks, furnace operating.                                                                                ::
    ID: 07033003.wav
    Length: 185
** Glassworks, sieving fine sand.                                                                                ::
    ID: 07033002.wav
    Length: 52
** Glassworks, sandmix being loaded & transported to furnace.                                                                                ::
    ID: 07033001.wav
    Length: 36
** Shop Floor atmosphere, with crane operating.                                                                                ::
    ID: 07032353.wav
    Length: 187
** 10-ton Travelling Crane, hoist traverses shop floor. (Recorded in cab.)                                                                                ::
    ID: 07032352.wav
    Length: 179
** Clyde crane, motor room. (Crane's maxium load 8 tons.)                                                                                ::
    ID: 07032351.wav
    Length: 289
** Hand-operated 2-ton Electric Hoist.                                                                                ::
    ID: 07032350.wav
    Length: 77
** Wharf, ship's cargo unloaded from main hold.                                                                                ::
    ID: 07032349.wav
    Length: 183
** Wharf, ship's cargo unloaded from main hold.                                                                                ::
    ID: 07032348.wav
    Length: 184
** Wharf, cargo of paper loaded into barges.                                                                                ::
    ID: 07032347.wav
    Length: 393
** Old-type Electric Crane operating.                                                                                ::
    ID: 07032346.wav
    Length: 197
** 25-ton Mobile Crane operating.                                                                                ::
    ID: 07032345.wav
    Length: 193
** Diesel Fork Lift Truck operating.                                                                                ::
    ID: 07032344.wav
    Length: 203
** Electric Fork Lift Truck operating.                                                                                ::
    ID: 07032343.wav
    Length: 199
** Warehouse Loading Bay atmosphere.                                                                                ::
    ID: 07032342.wav
    Length: 198
** Provisions Warehouse, atmosphere with fork lift truck operating during busy period.                                                                                ::
    ID: 07032341.wav
    Length: 201
** Provisions Warehouse, atmosphere with rumble of iron-wheeled barrows.                                                                                ::
    ID: 07032340.wav
    Length: 200
** Warehouse, packing cases nailed up.                                                                                ::
    ID: 07032339.wav
    Length: 199
** Pottery glazing. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032338.wav
    Length: 93
** Mixing glazing material. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032337.wav
    Length: 99
** Grinding dry glazing material with pestle & mortar. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032336.wav
    Length: 68
** Grinding dry glazing material with pestle & mortar.                                                                                ::
    ID: 07032335.wav
    Length: 67
** Grinding dry glazing material with pestle & mortar. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032334.wav
    Length: 78
** Sieving glazing material with an 80 mesh sieve. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032333.wav
    Length: 124
** Loading Kiln. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032332.wav
    Length: 134
** Throwing pots on to Kick Wheel. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032331.wav
    Length: 150
** Banging & wedging clay. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032330.wav
    Length: 64
** Banging clay on bench for throwing pot. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032329.wav
    Length: 62
** Balls of clay prepared for repetition throwing pot. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032328.wav
    Length: 65
** Plug Mill operating with start, run and stop. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032327.wav
    Length: 191
** Clay Mixer operating with start, run & stop. (Recorded at a Studio Pottery.)                                                                                ::
    ID: 07032326.wav
    Length: 158
** Local Train, interior, slow down & stop, with doors. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032325.wav
    Length: 132
** Local Train, interior, start into constant run, with occassional sirens . (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032324.wav
    Length: 274
** Express Train, interior, fast constant run. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032323.wav
    Length: 396
** Express Train, interior, slow down & stop. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032322.wav
    Length: 121
** Express Train, interior, start into constant run. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032321.wav
    Length: 272
** Locomotive passing with siren. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032320.wav
    Length: 35
** Freight Train passing. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032319.wav
    Length: 46
** Freight Train passing with siren. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032318.wav
    Length: 111
** Freight Train passing. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032317.wav
    Length: 48
** Freight Train with open wagons passing. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032316.wav
    Length: 46
** Express Train passing. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032315.wav
    Length: 26
** Express Train passing. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032314.wav
    Length: 22
** Express Train passing with siren. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032313.wav
    Length: 24
** Express Train passing with siren. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032312.wav
    Length: 33
** Express Train passing with siren. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032311.wav
    Length: 34
** Freight Train departs. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032310.wav
    Length: 93
** Freight Train arrives. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032309.wav
    Length: 54
** Local Train departs. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032308.wav
    Length: 52
** Express Train departs. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032307.wav
    Length: 56
** Local Train arrives, Express Train passes, local departs. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032306.wav
    Length: 68
** Local Train arriving with siren. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032305.wav
    Length: 56
** Express Train arriving. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032304.wav
    Length: 36
** Express Train arriving. (British Rail London Midland Region train, 25kV Pantograph system.)                                                                                ::
    ID: 07032303.wav
    Length: 33
** Sickle with Fagin hook being used.                                                                                ::
    ID: 07032302.wav
    Length: 127
** Sweeping on concrete.                                                                                ::
    ID: 07032301.wav
    Length: 123
** Sweeping earth & stones.                                                                                ::
    ID: 07032300.wav
    Length: 125
** Raking grass.                                                                                ::
    ID: 07032299.wav
    Length: 123
** Raking stony ground.                                                                                ::
    ID: 07032298.wav
    Length: 123
** Hedge clipping.                                                                                ::
    ID: 07032297.wav
    Length: 123
** Garden hose turned on & runs.                                                                                ::
    ID: 07032296.wav
    Length: 206
** Hoeing garden.                                                                                ::
    ID: 07032295.wav
    Length: 188
** Spade digging gravel.                                                                                ::
    ID: 07032294.wav
    Length: 190
** Spade digging earth.                                                                                ::
    ID: 07032293.wav
    Length: 196
** Scythe used.                                                                                ::
    ID: 07032292.wav
    Length: 94
** Shears Used To Trim Grass                                                                                ::
    ID: 07032291.wav
    Length: 93
** Electric Lawn Mower, various cutting patterns.                                                                                ::
    ID: 07032290.wav
    Length: 187
** 4-Stroke Rotary Motor Lawn Mower, stops.                                                                                ::
    ID: 07032289.wav
    Length: 14
** 4-Stroke Rotary Motor Lawn Mower, start up, continuous run..                                                                                ::
    ID: 07032288.wav
    Length: 250
** 4-Stroke Rotary Motor Lawn Mower, stops.                                                                                ::
    ID: 07032287.wav
    Length: 14
** 4-Stroke Rotary Motor Lawn Mower, start, tickover.                                                                                ::
    ID: 07032286.wav
    Length: 63
** 4-Stroke Rotary Lawn Mower, false starts.                                                                                ::
    ID: 07032285.wav
    Length: 36
** Rotary Lawn Mower, start, mowing medium size lawn, stop.                                                                                ::
    ID: 07032284.wav
    Length: 269
** Rotary Lawn Mower, start, revving, stop.                                                                                ::
    ID: 07032283.wav
    Length: 60
** Rotary Lawn Mower, false starts.                                                                                ::
    ID: 07032282.wav
    Length: 35
** Roller-type Lawn Mower, continuous mowing with turns.                                                                                ::
    ID: 07032281.wav
    Length: 175
** Roller-type Lawn Mower, fast short pushes.                                                                                ::
    ID: 07032280.wav
    Length: 31
** Roller-type Lawn Mower, medium pushes.                                                                                ::
    ID: 07032279.wav
    Length: 63
** Roller-type Lawn Mower, slow pushes.                                                                                ::
    ID: 07032278.wav
    Length: 67
** Paris Riots, banging on shields, smoke grenades.                                                                                ::
    ID: 07032277.wav
    Length: 124
** Paris Riots, P.A. announcement, smoke grenades.                                                                                ::
    ID: 07032276.wav
    Length: 140
** Paris Riots, fire built up & started.                                                                                ::
    ID: 07032275.wav
    Length: 106
** Paris Riots, general background, with many smoke grenades.                                                                                ::
    ID: 07032274.wav
    Length: 197
** Paris Riots, general background, with a few smoke grenades.                                                                                ::
    ID: 07032273.wav
    Length: 200
** Public Demonstration in a London square, subdued crowd after demonstration.                                                                                ::
    ID: 07032272.wav
    Length: 394
** Public Demonstration in a London square, angry crowd background.                                                                                ::
    ID: 07032271.wav
    Length: 298
** Public Demonstration in a London square, surge of angry crowd.                                                                                ::
    ID: 07032270.wav
    Length: 91
** Lift doors close, lift runs.                                                                                ::
    ID: 07032269.wav
    Length: 46
** Lift doors close, lift runs.                                                                                ::
    ID: 07032268.wav
    Length: 21
** Lift doors close, lift runs.                                                                                ::
    ID: 07032267.wav
    Length: 43
** Lift doors open, ventilator hum.                                                                                ::
    ID: 07032266.wav
    Length: 11
** Lift doors open, ventilator hum.                                                                                ::
    ID: 07032265.wav
    Length: 116
** Lift doors open, ventilator hum.                                                                                ::
    ID: 07032264.wav
    Length: 70
** Eiffel Tower Lifts, lift gates close, lift descends to 1st stage, announcement & atmosphere.                                                                                ::
    ID: 07032263.wav
    Length: 59
** Eiffel Tower Lifts, lift gates close, bell, lift ascends to 2nd stage, announcement & atmosphere.                                                                                ::
    ID: 07032262.wav
    Length: 57
** Eiffel Tower Lifts, lift gates close, bell, lift ascends to 1st stage, announcement & atmosphere.                                                                                ::
    ID: 07032261.wav
    Length: 80
** Eiffel Tower Lifts, small crowd waiting for lift.                                                                                ::
    ID: 07032260.wav
    Length: 182
** Heavy Goods Lift, lift stops, gates open.                                                                                ::
    ID: 07032259.wav
    Length: 14
** Heavy Goods Lift, lift gates close, constant run, stops, gates open.                                                                                ::
    ID: 07032258.wav
    Length: 38
** Heavy Goods Lift, lift stops, gates open.                                                                                ::
    ID: 07032257.wav
    Length: 16
** Heavy Goods Lift, gates close, constant run, stops, gates open.                                                                                ::
    ID: 07032256.wav
    Length: 34
** Heavy Goods Lift, lift stops, gates open.                                                                                ::
    ID: 07032255.wav
    Length: 16
** Heavy Goods Lift, gates close, constant run, stops, gates open.                                                                                ::
    ID: 07032254.wav
    Length: 33
** Lift buzzers sounding.                                                                                ::
    ID: 07032253.wav
    Length: 19
** Lift gates open.                                                                                ::
    ID: 07032252.wav
    Length: 9
** Lift gates close, lift ascends & stops, gates open. (With hum.)                                                                                ::
    ID: 07032251.wav
    Length: 40
** Lift stops, gates open.                                                                                ::
    ID: 07032250.wav
    Length: 10
** Old Hotel Lift, gates close, lift descends & stops, gates open.                                                                                ::
    ID: 07032249.wav
    Length: 41
** Old Hotel Lift, gates close, lift ascends & stops, gates open. (No hum.)                                                                                ::
    ID: 07032248.wav
    Length: 31
** Single rifles firing among rocks with ricochets. (Exterior recording.)                                                                                ::
    ID: 07032247.wav
    Length: 63
** Rifle fire among rocks with ricochets. (Exterior recording.)                                                                                ::
    ID: 07032246.wav
    Length: 107
** 100 muskets firing continuously. (Studio recording.)                                                                                ::
    ID: 07032245.wav
    Length: 125
** Two muskets firing at random. (Studio recording.)                                                                                ::
    ID: 07032244.wav
    Length: 58
** Six single musket shots. (Studio recording.)                                                                                ::
    ID: 07032243.wav
    Length: 16
** 100 rifles firing rapidly. (Studio recording.)                                                                                ::
    ID: 07032242.wav
    Length: 123
** Two revolvers firing at random. (Studio recording.)                                                                                ::
    ID: 07032241.wav
    Length: 34
** Six single revolver shots. (Studio recording.)                                                                                ::
    ID: 07032240.wav
    Length: 17
** Turnstiles at a football match, in use during busy period.                                                                                ::
    ID: 07032239.wav
    Length: 197
** Turnstiles at a football match, in use during quiet period.                                                                                ::
    ID: 07032238.wav
    Length: 174
** Turnstile operating.                                                                                ::
    ID: 07032237.wav
    Length: 9
** Kar-park Parking Meter, coin inserted.                                                                                ::
    ID: 07032236.wav
    Length: 20
** Venner Parking Meter, four coins inserted. (Meter c. 1961.)                                                                                ::
    ID: 07032235.wav
    Length: 17
** Venner Parking Meter, two coins inserted. (Meter c. 1961.)                                                                                ::
    ID: 07032234.wav
    Length: 12
** Venner Parking Meter, coin inserted. (Meter c. 1961.)                                                                                ::
    ID: 07032233.wav
    Length: 7
** Jukebox mechanism operating, no music. (Jukebox c. 1962.)                                                                                ::
    ID: 07032232.wav
    Length: 39
** Setrite Push-Button Ticket Machine, emptying machine.                                                                                ::
    ID: 07032231.wav
    Length: 39
** Setrite Push-Button Ticket Machine, 4/11d. rejected.                                                                                ::
    ID: 07032230.wav
    Length: 10
** Setrite Push-Button Ticket Machine, 6d. inserted & rejected.                                                                                ::
    ID: 07032229.wav
    Length: 13
** Setrite Push-Button Ticket Machine, 6/10d. inserted.                                                                                ::
    ID: 07032228.wav
    Length: 24
** Setrite Push-Button Ticket Machine, 5/9d. inserted.                                                                                ::
    ID: 07032227.wav
    Length: 26
** Setrite Push-Button Ticket Machine, 4/8d. inserted.                                                                                ::
    ID: 07032226.wav
    Length: 17
** Setrite Push-Button Ticket Machine, 3/7d. inserted.                                                                                ::
    ID: 07032225.wav
    Length: 22
** Setrite Push-Button Ticket Machine, 2/6d. inserted.                                                                                ::
    ID: 07032224.wav
    Length: 14
** Setrite Push-Button Ticket Machine, 1/6d. inserted.                                                                                ::
    ID: 07032223.wav
    Length: 15
** Setrite Push-Button Ticket Machine, 1/- inserted.                                                                                ::
    ID: 07032222.wav
    Length: 11
** Setrite Push-Button Ticket Machine, 9d. inserted.                                                                                ::
    ID: 07032221.wav
    Length: 14
** Setrite Push-Button Ticket Machine, 6d. inserted.                                                                                ::
    ID: 07032220.wav
    Length: 11
** Background hum suitable for food & drink machines, lighter sound.                                                                                ::
    ID: 07032219.wav
    Length: 183
** Background hum suitable for food & drink machines, deep sound.                                                                                ::
    ID: 07032218.wav
    Length: 185
** Selector Dial operated, drink or food machines.                                                                                ::
    ID: 07032217.wav
    Length: 27
** Soup & Sandwiches Machine operating.                                                                                ::
    ID: 07032216.wav
    Length: 14
** Hot Drink Machine operating.                                                                                ::
    ID: 07032215.wav
    Length: 16
** Sandwich Machine operating.                                                                                ::
    ID: 07032214.wav
    Length: 11
** Beverage Machine operating.                                                                                ::
    ID: 07032213.wav
    Length: 25
** Change Machine operating.                                                                                ::
    ID: 07032212.wav
    Length: 11
** Cigaratte Machine operating.                                                                                ::
    ID: 07032211.wav
    Length: 16
** Coin put into slot of machine.                                                                                ::
    ID: 07032210.wav
    Length: 7
** 1d. in slot of a pre-war Weighing Machine.                                                                                ::
    ID: 07032209.wav
    Length: 12
** Pre-war Weighing Machine operating, issues printed ticket.                                                                                ::
    ID: 07032208.wav
    Length: 13
** 6d. Chocolate Machine.                                                                                ::
    ID: 07032207.wav
    Length: 9
** 2d. Chocolate Machine.                                                                                ::
    ID: 07032206.wav
    Length: 11
** 1d. Chocolate Machine.                                                                                ::
    ID: 07032205.wav
    Length: 10
** Nameplate Machine operating, 12 letters for 1d. (c. 1908.)                                                                                ::
    ID: 07032204.wav
    Length: 43
** 2d. in slot Football Game.                                                                                ::
    ID: 07032203.wav
    Length: 35
** 2d. in slot Race Game.                                                                                ::
    ID: 07032202.wav
    Length: 16
** Electric Hand-Reading Machine in operation.                                                                                ::
    ID: 07032201.wav
    Length: 30
** Home Bagatelle board in use.                                                                                ::
    ID: 07032200.wav
    Length: 124
** Jackpot won on Slot Machine.                                                                                ::
    ID: 07032199.wav
    Length: 11
** Pintable, coin in slot, ball round 3 times with bells, 'flippers' and buzzes.                                                                                ::
    ID: 07032198.wav
    Length: 67
** Pintable, coin in slot, ball round 3 times, bell.                                                                                ::
    ID: 07032197.wav
    Length: 72
** Pintable, coin in slot, ball round 3 times, no bell.                                                                                ::
    ID: 07032196.wav
    Length: 76
** Shooting Cats Machine operating.                                                                                ::
    ID: 07032195.wav
    Length: 17
** Fortune Telling Machine operating.                                                                                ::
    ID: 07032194.wav
    Length: 35
** Ball bearing in Spiral Machine in amusement arcade.                                                                                ::
    ID: 07032193.wav
    Length: 34
** Talking Weight Machine, 8st. 51b.                                                                                ::
    ID: 07032192.wav
    Length: 14
** Talking Weight Machine, 13st. 31b.                                                                                ::
    ID: 07032191.wav
    Length: 12
** Talking Weight Machine, 12st. 11b.                                                                                ::
    ID: 07032190.wav
    Length: 18
** Gift Crane operating in an amusement arcade.                                                                                ::
    ID: 07032189.wav
    Length: 28
** 1960 Fruit Machine operating.                                                                                ::
    ID: 07032188.wav
    Length: 127
** Greyhound Racing, general atmosphere.                                                                                ::
    ID: 07032187.wav
    Length: 199
** Greyhound Racing, general atmosphere.                                                                                ::
    ID: 07032186.wav
    Length: 201
** Greyhound Racing, atmosphere behind Tote Office counter.                                                                                ::
    ID: 07032185.wav
    Length: 133
** Greyhound Racing, general atmosphere at Tote Office.                                                                                ::
    ID: 07032184.wav
    Length: 253
** Greyhound Racing, atmosphere during & after a race.                                                                                ::
    ID: 07032183.wav
    Length: 196
** Greyhound Racing, crowd and bookies before race.                                                                                ::
    ID: 07032182.wav
    Length: 195
** Greyhound Racing, dogs put into traps, hare started, race takes place. (As heard from traps)                                                                                ::
    ID: 07032181.wav
    Length: 152
** Greyhound Racing, dogs barking in kennels.                                                                                ::
    ID: 07032180.wav
    Length: 153
** Greyhound Racing, hare going round a track. (No dogs or crowd.)                                                                                ::
    ID: 07032179.wav
    Length: 38
** Greyhound Racing, dog trap shuts.                                                                                ::
    ID: 07032178.wav
    Length: 6
** Greyhound Racing, dog trap springs open.                                                                                ::
    ID: 07032177.wav
    Length: 8
** Canal Longboat, constant run.                                                                                ::
    ID: 07032176.wav
    Length: 282
** Canal Longboat, hooter sounds, into constant run.                                                                                ::
    ID: 07032175.wav
    Length: 48
** Canal Longboat, engine ticking over.                                                                                ::
    ID: 07032174.wav
    Length: 352
** Canal Longboat, constant run. (Recorded on board.) (Vessel carrying general cargo, 16 h.p. Petter engine.)                                                                                ::
    ID: 07032173.wav
    Length: 411
** Canal Longboat, lock gates close, boat edges out into constant run. (Recorded on board.) (Vessel carrying general cargo, 16 h.p. Petter engine.)                                                                                ::
    ID: 07032172.wav
    Length: 106
** Canal Longboat, winding flood gate at lock, rush of water. (Recorded on board.) (Vessel carrying general cargo, 16 h.p. Petter engine.)                                                                                ::
    ID: 07032171.wav
    Length: 118
** Canal Longboat, engines start, revving & manoeuvring. (Recorded on board.) (Vessel carrying general cargo, 16 h.p. Petter engine.)                                                                                ::
    ID: 07032170.wav
    Length: 122
** Lotus 15 Sports Car, exterior, passes with skid.                                                                                ::
    ID: 07032169.wav
    Length: 20
** Cooper Monaco Sports, exterior, passes cornering hard. (1960 model.)                                                                                ::
    ID: 07032168.wav
    Length: 23
** Lagonda Rapier, exterior, passing. (1935 model.)                                                                                ::
    ID: 07032167.wav
    Length: 22
** Car passing in tunnel with horn.                                                                                ::
    ID: 07032166.wav
    Length: 49
** Wolseley 1600cc, exterior, passes at 40 m.p.h.                                                                                ::
    ID: 07032165.wav
    Length: 28
** Vauxhall Velox, exterior, passes at 40 m.p.h. (1966 model.)                                                                                ::
    ID: 07032164.wav
    Length: 38
** Ford Zephyr, exterior, passes at 50 m.p.h. (1968 model.)                                                                                ::
    ID: 07032163.wav
    Length: 29
** Mini Cooper, exterior, passes at speed. (1968 model.)                                                                                ::
    ID: 07032162.wav
    Length: 40
** Ford Corsair, exterior, passes at speed. (1968 model.)                                                                                ::
    ID: 07032161.wav
    Length: 31
** Lotus sports car, exterior, passes cornering fast. (Sports car, 1960 model.)                                                                                ::
    ID: 07032160.wav
    Length: 27
** Triumph TR3, exterior, passing at speed with horn. (Sports car, 1960 model.)                                                                                ::
    ID: 07032159.wav
    Length: 15
** Triumph TR3, exterior, passing at speed with horn. (Sports car, 1960 model.)                                                                                ::
    ID: 07032158.wav
    Length: 22
** Christ's College clock striking twelve o'clock.                                                                                ::
    ID: 07032157.wav
    Length: 44
** Christ's College clock striking eleven o'clock.                                                                                ::
    ID: 07032156.wav
    Length: 42
** Christ's College clock striking ten o'clock.                                                                                ::
    ID: 07032155.wav
    Length: 41
** Christ's College clock striking nine o'clock.                                                                                ::
    ID: 07032154.wav
    Length: 39
** Christ's College clock striking eight o'clock.                                                                                ::
    ID: 07032153.wav
    Length: 37
** Christ's College clock striking seven o'clock.                                                                                ::
    ID: 07032152.wav
    Length: 36
** Christ's College clock striking six o'clock.                                                                                ::
    ID: 07032151.wav
    Length: 34
** Christ's College clock striking five o'clock.                                                                                ::
    ID: 07032150.wav
    Length: 34
** Christ's College clock striking four o'clock.                                                                                ::
    ID: 07032149.wav
    Length: 32
** Christ's College clock striking three o'clock.                                                                                ::
    ID: 07032148.wav
    Length: 30
** Christ's College clock striking two o'clock.                                                                                ::
    ID: 07032147.wav
    Length: 28
** Christ's College clock striking one o'clock.                                                                                ::
    ID: 07032146.wav
    Length: 23
** General college street atmosphere.                                                                                ::
    ID: 07032145.wav
    Length: 423
** Christ's College clock striking quarter to the hour.                                                                                ::
    ID: 07032144.wav
    Length: 14
** Christ's College clock striking half past the hour.                                                                                ::
    ID: 07032143.wav
    Length: 13
** Christ's College clock striking quarter past the hour.                                                                                ::
    ID: 07032142.wav
    Length: 11
** Emmanuel College clock striking twelve o'clock, into general background. (Recorded in quadrangle.)                                                                                ::
    ID: 07032141.wav
    Length: 214
** Emmanuel College clock striking twelve o'clock.                                                                                ::
    ID: 07032140.wav
    Length: 49
** Emmanuel College clock striking eleven o'clock.                                                                                ::
    ID: 07032139.wav
    Length: 45
** Emmanuel College clock striking ten o'clock.                                                                                ::
    ID: 07032138.wav
    Length: 44
** Emmanuel College clock striking nine o'clock.                                                                                ::
    ID: 07032137.wav
    Length: 40
** Emmanuel College clock striking eight o'clock.                                                                                ::
    ID: 07032136.wav
    Length: 38
** Emmanuel College clock striking seven o'clock.                                                                                ::
    ID: 07032135.wav
    Length: 36
** Emmanuel College clock striking six o'clock.                                                                                ::
    ID: 07032134.wav
    Length: 33
** Emmanuel College clock striking five o'clock.                                                                                ::
    ID: 07032133.wav
    Length: 31
** Emmanuel College clock striking four o'clock.                                                                                ::
    ID: 07032132.wav
    Length: 29
** Emmanuel College clock striking three o'clock.                                                                                ::
    ID: 07032131.wav
    Length: 27
** Emmanuel College clock striking two o'clock.                                                                                ::
    ID: 07032130.wav
    Length: 24
** Emmanuel College clock striking one o'clock.                                                                                ::
    ID: 07032129.wav
    Length: 23
** Diesel goods train crossing metal bridge.                                                                                ::
    ID: 07032128.wav
    Length: 49
** Local 2-car Diesel train crossing metal bridge.                                                                                ::
    ID: 07032127.wav
    Length: 22
** Local train crossing metal bridge.                                                                                ::
    ID: 07032126.wav
    Length: 27
** Local train crossing metal bridge.                                                                                ::
    ID: 07032125.wav
    Length: 30
** Express train crossing metal bridge.                                                                                ::
    ID: 07032124.wav
    Length: 26
** Express train crossing metal bridge.                                                                                ::
    ID: 07032123.wav
    Length: 35
** Goods train crossing brick-built bridge.                                                                                ::
    ID: 07032122.wav
    Length: 37
** Local train crossing brick-built bridge.                                                                                ::
    ID: 07032121.wav
    Length: 28
** Local train crossing brick-built bridge.                                                                                ::
    ID: 07032120.wav
    Length: 24
** Local train crossing brick-built bridge.                                                                                ::
    ID: 07032119.wav
    Length: 29
** Express train crossing brick-built bridge.                                                                                ::
    ID: 07032118.wav
    Length: 18
** Express train crossing brick-built bridge.                                                                                ::
    ID: 07032117.wav
    Length: 22
** Express train emerges from under bridge.                                                                                ::
    ID: 07032116.wav
    Length: 56
** Local train goes under bridge.                                                                                ::
    ID: 07032115.wav
    Length: 46
** Train goes under bridge.                                                                                ::
    ID: 07032114.wav
    Length: 29
** Train emerges from under bridge.                                                                                ::
    ID: 07032113.wav
    Length: 36
** Electric express train goes under bridge.                                                                                ::
    ID: 07032112.wav
    Length: 20
** Electric express train emerges from under bridge.                                                                                ::
    ID: 07032111.wav
    Length: 23
** Local train under bridge, goods train emerges.                                                                                ::
    ID: 07032110.wav
    Length: 45
** Express train leaving tunnel, second train sounds siren & enters.                                                                                ::
    ID: 07032109.wav
    Length: 32
** Local train leaving tunnel.                                                                                ::
    ID: 07032108.wav
    Length: 34
** Local train leaving tunnel with siren.                                                                                ::
    ID: 07032107.wav
    Length: 34
** Local train entering tunnel.                                                                                ::
    ID: 07032106.wav
    Length: 26
** Local train entering tunnel.                                                                                ::
    ID: 07032105.wav
    Length: 29
** Goods train leaving tunnel without siren. (Recorded at trackside.)                                                                                ::
    ID: 07032104.wav
    Length: 39
** Goods train entering tunnel without siren. (Recorded at trackside.)                                                                                ::
    ID: 07032103.wav
    Length: 36
** Goods train entering tunnel with siren. (Recorded at trackside.)                                                                                ::
    ID: 07032102.wav
    Length: 38
** Express passenger train leaving tunnel without siren. (Recorded at trackside.)                                                                                ::
    ID: 07032101.wav
    Length: 38
** Express passenger train leaving tunnel without siren. (Recorded at trackside.)                                                                                ::
    ID: 07032100.wav
    Length: 31
** Express passenger train leaving tunnel without siren. (Recorded at trackside.)                                                                                ::
    ID: 07032099.wav
    Length: 31
** Express passenger train entering tunnel without siren. (Recorded at trackside.)                                                                                ::
    ID: 07032098.wav
    Length: 35
** Express passenger train entering tunnel without siren. (Recorded at trackside.)                                                                                ::
    ID: 07032097.wav
    Length: 22
** Express passenger train entering tunnel with siren. (Recorded at trackside.)                                                                                ::
    ID: 07032096.wav
    Length: 32
** Express passenger train entering tunnel with siren. (Recorded at trackside.)                                                                                ::
    ID: 07032095.wav
    Length: 23
** Express passenger train entering tunnel with siren. (Recorded at trackside.)                                                                                ::
    ID: 07032094.wav
    Length: 26
** Express passenger train entering tunnel with siren. (Recorded at trackside.)                                                                                ::
    ID: 07032093.wav
    Length: 23
** Diesel Electric Locomotive shunting.                                                                                ::
    ID: 07032092.wav
    Length: 217
** Level C rossing, diesel train passing over crossing.                                                                                ::
    ID: 07032091.wav
    Length: 30
** Level Crossing, diesel freight train passing over crossing.                                                                                ::
    ID: 07032090.wav
    Length: 52
** Level Crossing, pedestrian gates opened & closed several times.                                                                                ::
    ID: 07032089.wav
    Length: 23
** Level Crossings, gates closed mechanically.                                                                                ::
    ID: 07032088.wav
    Length: 6
** Level Crossing, gates closed mechanically from signal box. (Recorded in signal box.)                                                                                ::
    ID: 07032087.wav
    Length: 22
** Level Crossing, gates opened mechanically from signal box. (Recorded in signal box.)                                                                                ::
    ID: 07032086.wav
    Length: 29
** Level Crossing, train passes, gates opened by hand, traffic resumes.                                                                                ::
    ID: 07032085.wav
    Length: 81
** Level Crossing, gates closed by hand.                                                                                ::
    ID: 07032084.wav
    Length: 46
** Level Crossing, train passes, gates opened by hand, traffic resumes.                                                                                ::
    ID: 07032083.wav
    Length: 68
** Level Crossing, gates closed by hand.                                                                                ::
    ID: 07032082.wav
    Length: 49
** Diesel Trains shunting in goods yard.                                                                                ::
    ID: 07032081.wav
    Length: 281
** Platelayers Trolley passing.                                                                                ::
    ID: 07032080.wav
    Length: 28
** Platelayers Trolley approaching.                                                                                ::
    ID: 07032079.wav
    Length: 23
** Platelayers Trolley departing.                                                                                ::
    ID: 07032078.wav
    Length: 33
** Platelayers Trolley.                                                                                ::
    ID: 07032077.wav
    Length: 99
** Steam Train, wheel tapping with brakes on. (Testing for defects in wheels.)                                                                                ::
    ID: 07032076.wav
    Length: 109
** Steam Train, wheel tapping with brakes off. (Testing for defects in wheels.)                                                                                ::
    ID: 07032075.wav
    Length: 130
** Railway Breakdown Crane operating with occasional distant speech.                                                                                ::
    ID: 07032074.wav
    Length: 210
** Manual Railway Signal Box, interior, atmosphere.                                                                                ::
    ID: 07032073.wav
    Length: 204
** Coal Hopper, raking coal in hopper.                                                                                ::
    ID: 07032072.wav
    Length: 116
** Railway Signal Box, approach of light engine, signals received & acknowledged.                                                                                ::
    ID: 07032071.wav
    Length: 30
** Railway Signal Box, approach of express freight train, signals received & acknowledged.                                                                                ::
    ID: 07032070.wav
    Length: 38
** Railway Signal Box, approach of passenger train, signals received & acknowledged.                                                                                ::
    ID: 07032069.wav
    Length: 37
** Railway Signal Box, closing down with signals received & acknowledged.                                                                                ::
    ID: 07032068.wav
    Length: 18
** Railway Signal Box, opening up with signals received & acknowledged.                                                                                ::
    ID: 07032067.wav
    Length: 16
** Goods yard warning klaxon sounded.                                                                                ::
    ID: 07032066.wav
    Length: 10
** Level crossing, continental-type, lorry crosses, bell sounds, train passes, traffic resumes.                                                                                ::
    ID: 07032065.wav
    Length: 107
** Level crossing, continental-type, car crosses, bell sounds, train passes, traffic resumes.                                                                                ::
    ID: 07032064.wav
    Length: 70
** Level crossing, continental-type, bell sounds, train passes (after 001m00s).                                                                                ::
    ID: 07032063.wav
    Length: 85
** Diesel train, siren sounded three times. (Train stationary.)                                                                                ::
    ID: 07032062.wav
    Length: 20
** Diesel train, siren sounded three times. (Train stationary.)                                                                                ::
    ID: 07032061.wav
    Length: 18
** Diesel train, siren sounded once (multiple tones). (Train stationary.)                                                                                ::
    ID: 07032060.wav
    Length: 20
** Diesel train, siren sounded twice. (Train stationary.)                                                                                ::
    ID: 07032059.wav
    Length: 17
** Diesel train, siren sounded three times. (Train stationary.)                                                                                ::
    ID: 07032058.wav
    Length: 17
** Diesel train, siren sounded twice. (Train stationary.)                                                                                ::
    ID: 07032057.wav
    Length: 12
** Electric Trams, pedestrians & motor traffic.                                                                                ::
    ID: 07032056.wav
    Length: 394
** Diesel Tram, start up, constant run, stop, tickover, switch off.                                                                                ::
    ID: 07032055.wav
    Length: 103
** Two Cable Trams passing.                                                                                ::
    ID: 07032054.wav
    Length: 65
** Cable Tram departs.                                                                                ::
    ID: 07032053.wav
    Length: 39
** Horse-drawn Tram starts, constant run, stop, with motor traffic passing.                                                                                ::
    ID: 07032052.wav
    Length: 125
** Points at Tram terminus.                                                                                ::
    ID: 07032051.wav
    Length: 24
** Tram stopping.                                                                                ::
    ID: 07032050.wav
    Length: 40
** Tram, start up, bell sounded, fast run (squeaks at 000m17s), intermediate stop (at 001m45s).                                                                                ::
    ID: 07032049.wav
    Length: 153
** Tram approach & pass, stops, with wheel squeak at end.                                                                                ::
    ID: 07032048.wav
    Length: 24
** Tram start up & depart.                                                                                ::
    ID: 07032047.wav
    Length: 39
** Tram approach & stop with brake squeal at end.                                                                                ::
    ID: 07032046.wav
    Length: 30
** Tram departs with bell being sounded.                                                                                ::
    ID: 07032045.wav
    Length: 24
** Tram approach & pass slowly with bell being sounded.                                                                                ::
    ID: 07032044.wav
    Length: 31
** Tram approach & stop.                                                                                ::
    ID: 07032043.wav
    Length: 19
** Tram departs, bells rung.                                                                                ::
    ID: 07032042.wav
    Length: 28
** Tram approach & pass with bell.                                                                                ::
    ID: 07032041.wav
    Length: 24
** Tram approach & pass.                                                                                ::
    ID: 07032040.wav
    Length: 36
** Sheffield, Tram, interior, tram stopping. (Tram built 1938.)                                                                                ::
    ID: 07032039.wav
    Length: 23
** Sheffield, Tram, interior, bells sound, tram starts, continuous run. (Tram built 1938.)                                                                                ::
    ID: 07032038.wav
    Length: 121
** Sheffield, Tram, interior, brake release, five second pause, sanding gear. (Tram built 1938.)                                                                                ::
    ID: 07032037.wav
    Length: 17
** Sheffield, Tram, interior, compressor released. (Tram built 1938.)                                                                                ::
    ID: 07032036.wav
    Length: 14
** Sheffield, Tram, interior, tram stopping. (Tram built 1938.)                                                                                ::
    ID: 07032035.wav
    Length: 17
** Sheffield, Tram, interior, bell rung to start tram, continuous run. (Tram built 1938.)                                                                                ::
    ID: 07032034.wav
    Length: 118
** Leicester Tram, exterior, approach & pass. (Tram built 1904.)                                                                                ::
    ID: 07032033.wav
    Length: 25
** Leicester Tram, interior, start up with bell, slow run with intermediate stop, tram stops at end. (Tram built 1904.)                                                                                ::
    ID: 07032032.wav
    Length: 125
** Leicester Tram, interior, reversing seats. (Tram built 1904.)                                                                                ::
    ID: 07032031.wav
    Length: 21
** Leicester Tram, interior, communicating doors closing twice. (Tram built 1904.)                                                                                ::
    ID: 07032030.wav
    Length: 10
** Leicester Tram, interior, tram stopping. (Tram built 1904.)                                                                                ::
    ID: 07032029.wav
    Length: 22
** Leicester Tram, interior, start up, continuous run on upper deck. (Tram built 1904.)                                                                                ::
    ID: 07032028.wav
    Length: 112
** Leicester Tram, interior, bulkhead door closing four times. (Tram built 1904.)                                                                                ::
    ID: 07032027.wav
    Length: 16
** Leicester Tram, interior, emergency bell sounded. (Tram built 1904.)                                                                                ::
    ID: 07032026.wav
    Length: 16
** Leicester Tram, interior, tram stopping. (Tram built 1904.)                                                                                ::
    ID: 07032025.wav
    Length: 27
** Interior, start up, bell sounded, tram running at medium speed. (Tram built 1904.)                                                                                ::
    ID: 07032024.wav
    Length: 209
** Leicester Tram, interior, slow down to stop. (Tram built 1904.)                                                                                ::
    ID: 07032023.wav
    Length: 22
** Leicester Tram, interior, start up, bell sounded, tram running at medium speed. (Tram built 1904.)                                                                                ::
    ID: 07032022.wav
    Length: 109
** Leicester Tram, interior, passenger bell sounded, single rings. (Tram built 1904.)                                                                                ::
    ID: 07032021.wav
    Length: 8
** Leicester Tram, interior, passenger bell sounded, double rings. (Tram built 1904.)                                                                                ::
    ID: 07032020.wav
    Length: 25
** Leicester Tram, interior, bell sounded. (Tram built 1904.)                                                                                ::
    ID: 07032019.wav
    Length: 12
** Leicester Tram, interior, bell sounded. (Tram built 1904.)                                                                                ::
    ID: 07032018.wav
    Length: 16
** Blackpool Tram, interior, start, run with intermediate stops.                                                                                ::
    ID: 07032017.wav
    Length: 415
** Blackpool Tram, interior, start, run with intermediate stops.                                                                                ::
    ID: 07032016.wav
    Length: 253
** Blackpool Tram, exterior, passing.                                                                                ::
    ID: 07032015.wav
    Length: 21
** Blackpool Tram, exterior, passing.                                                                                ::
    ID: 07032014.wav
    Length: 57
** Blackpool Tram, exterior, depart, bell sounded.                                                                                ::
    ID: 07032013.wav
    Length: 28
** Blackpool Tram, approach & stop.                                                                                ::
    ID: 07032012.wav
    Length: 37
** Blackpool Tram, approach, stop, depart.                                                                                ::
    ID: 07032011.wav
    Length: 56
** Blackpool Tram, approach, stop, depart.                                                                                ::
    ID: 07032010.wav
    Length: 70
** Blackpool Tram points being changed.                                                                                ::
    ID: 07032009.wav
    Length: 7
** Blackpool Tram points being changed.                                                                                ::
    ID: 07032008.wav
    Length: 8
** Blackpool Tram crossing points.                                                                                ::
    ID: 07032007.wav
    Length: 36
** Blackpool Tram, hooter sounds as tram crosses points.                                                                                ::
    ID: 07032006.wav
    Length: 25
** Blackpool Tram, hooter sounds as tram crosses points.                                                                                ::
    ID: 07032005.wav
    Length: 30
** Blackpool Tram, warning bell sounded.                                                                                ::
    ID: 07032004.wav
    Length: 28
** Blackpool Tram, bell rung three times. (Tram full.)                                                                                ::
    ID: 07032003.wav
    Length: 8
** Blackpool Tram, bell rung twice to start tram.                                                                                ::
    ID: 07032002.wav
    Length: 9
** Blackpool Tram, bell rung once to stop tram.                                                                                ::
    ID: 07032001.wav
    Length: 9
** Water: Small light flowing stream, close perspective                                                                                :Water:Small light flowing stream:
    ID: 07031104.wav
    Length: 152
** Water: Small light flowing stream, medium distance                                                                                :Water:Small light flowing stream:
    ID: 07031103.wav
    Length: 137
** Water: Small fast flowing stream in gully                                                                                :Water:
    ID: 07031102.wav
    Length: 95
** Water: Fast flowing small stream, close perspective                                                                                :Water:Fast flowing small stream:
    ID: 07031101.wav
    Length: 142
** Water: Streams, small trickle with rain and rain drops, one foot away                                                                                :Water:Streams:
    ID: 07031100.wav
    Length: 93
** Water: Medium stream, close perspective                                                                                :Water:Medium stream:
    ID: 07031099.wav
    Length: 42
** Water: Heavy stream trickling fast in confined space                                                                                :Water:
    ID: 07031098.wav
    Length: 97
** Water: Fentle stream flowing                                                                                :Water:
    ID: 07031097.wav
    Length: 396
** Water: Small river flowing, distant perspective                                                                                :Water:Small river flowing:
    ID: 07031096.wav
    Length: 215
** Water: Sea lapping around legs of pier                                                                                :Water:
    ID: 07031095.wav
    Length: 213
** Water: Gently running stream with birdsong, season unknown                                                                                :Water:Gently running stream with birdsong:
    ID: 07031094.wav
    Length: 220
** Water: River lapping                                                                                :Water:
    ID: 07031093.wav
    Length: 215
** Water: Stream bubbling over rocks, close perspective                                                                                :Water:Stream bubbling over rocks:
    ID: 07031092.wav
    Length: 217
** Water: Running through a culvert or bridge                                                                                :Water:
    ID: 07031091.wav
    Length: 215
** Water: River rippling over stones, close perspective                                                                                :Water:River rippling over stones:
    ID: 07031090.wav
    Length: 395
** Water: Weir in full flood                                                                                :Water:
    ID: 07031089.wav
    Length: 394
** Water: Running continuously over two metre drop                                                                                :Water:
    ID: 07031088.wav
    Length: 395
** Water: River cascading over rocks, close perspective                                                                                :Water:River cascading over rocks:
    ID: 07031087.wav
    Length: 396
** Water: Pystyll Rhadn waterfall                                                                                :Water:
    ID: 07031086.wav
    Length: 178
** Water: Cwm Or waterfall                                                                                :Water:
    ID: 07031085.wav
    Length: 193
** Water: Small river running over rocks                                                                                :Water:
    ID: 07031084.wav
    Length: 206
** Water: Mountain stream bubbling over stones                                                                                :Water:
    ID: 07031083.wav
    Length: 199
** Water: Waterfall, close perspective                                                                                :Water:Waterfall:
    ID: 07031082.wav
    Length: 451
** Water: Stream, close perspective                                                                                :Water:Stream:
    ID: 07031081.wav
    Length: 467
** Water: Stream                                                                                :Water:
    ID: 07031080.wav
    Length: 336
** Water: Pool, Lapping, birds, more activity, siren at start                                                                                :Water:Pool:
    ID: 07031079.wav
    Length: 390
** Water: Pool, Lapping, birds, voices and engines                                                                                :Water:Pool:
    ID: 07031078.wav
    Length: 382
** Water: Large Fountain, recorded close right centre with some traffic                                                                                :Water:Large Fountain:
    ID: 07031077.wav
    Length: 175
** Water: Large Fountain, recorded close, left centre with some traffic                                                                                :Water:Large Fountain:
    ID: 07031076.wav
    Length: 176
** Water: Tap dripping slowly                                                                                :Water:
    ID: 07031075.wav
    Length: 110
** Water: Running out of sink with 'glug' sounds                                                                                :Water:
    ID: 07031074.wav
    Length: 40
** Water: Running out of hand basin                                                                                :Water:
    ID: 07031073.wav
    Length: 14
** Water: Running from two taps into hand basin                                                                                :Water:
    ID: 07031072.wav
    Length: 23
** Water: Running into cistern                                                                                :Water:
    ID: 07031071.wav
    Length: 50
** Water: W.C. flushing                                                                                :Water:W:
    ID: 07031070.wav
    Length: 29
** Water: Under bridge, atmosphere, Canal                                                                                 :Water:Under bridge:
    ID: 07031069.wav
    Length: 427
** Water: Riverside atmosphere, London (Technical note, for use at low level)                                                                                :Water:Riverside atmosphere:
    ID: 07031068.wav
    Length: 388
** Insurance: Lloyds of London, Atmosphere, Underwriting room, tannoy announcements removed                                                                                :London:Lloyds Of London:
    ID: 07031067.wav
    Length: 340
** Insurance: Lloyds of London, Atmosphere, Main entrance foyer, late afternoon                                                                                :London:Lloyds Of London:
    ID: 07031066.wav
    Length: 185
** Insurance: Lloyds of London, Atmosphere, Underwriting room lunchtime, quiet                                                                                :London:Lloyds Of London:
    ID: 07031065.wav
    Length: 117
** Insurance: Lloyds of London, Atmosphere, Lutine bell, rung eight times                                                                                :London:Lloyds Of London:
    ID: 07031064.wav
    Length: 27
** Insurance: Lloyds of London, Atmosphere, Lutine bell, rung twice                                                                                :London:Lloyds Of London:
    ID: 07031063.wav
    Length: 16
** Crowd Outdoor: Large moving crowd with footsteps and voices.                                                                                :Crowds:Outdoors:
    ID: 07031062.wav
    Length: 397
** Crowd Outdoor: Close, good natured crowd at public demonstration.                                                                                :Crowds:Outdoors:
    ID: 07031061.wav
    Length: 396
** Large Crowd: Outside St. Paul's Cathedral, large cheer.                                                                                :Large Crowd:Outside St:
    ID: 07031060.wav
    Length: 31
** Large Crowd: Outside St. Paul's Cathedral, large cheer.                                                                                :Large Crowd:Outside St:
    ID: 07031059.wav
    Length: 50
** Large Crowd: Outside St. Paul's Cathedral, orders shouted, small cheer.                                                                                :Large Crowd:Outside St:
    ID: 07031058.wav
    Length: 38
** Large Crowd: Outside St. Paul's Cathedral, cheering and whistling builds up.                                                                                :Large Crowd:Outside St:
    ID: 07031057.wav
    Length: 66
** Large Crowd: Outside St. Paul's Cathedral, shouts of orders, carriage procession arrives, cheers.                                                                                :Large Crowd:Outside St:
    ID: 07031056.wav
    Length: 107
** Large Crowd: Outside St. Paul's Cathedral, shouts of orders, carriage procession arrives, cheers.                                                                                :Large Crowd:Outside St:
    ID: 07031055.wav
    Length: 56
** Large Crowd: Outside St. Paul's Cathedral, mid-distant perspective recording, wedding of H.R.H. Prince of Wales.                                                                                 :Large Crowd:Outside St:
    ID: 07031054.wav
    Length: 395
** Crowds: Outside Buckingham Palace, Chant of 'We Want The Queen'.                                                                                :Crowds:Outside Buckingham Palace, Chant of 'We Want The Queen':
    ID: 07031053.wav
    Length: 22
** Crowds: Outside Buckingham Palace, Cheers, Applause.                                                                                :Crowds:Outside Buckingham Palace, Cheers, Applause:
    ID: 07031052.wav
    Length: 80
** Crowds: Outside Buckingham Palace, Cheers.                                                                                :Crowds:Outside Buckingham Palace, Cheers:
    ID: 07031051.wav
    Length: 12
** Crowds: Outside Buckingham Palace, subdued crowd, close perspective recording.                                                                                :Crowds:Outside Buckingham Palace, subdued crowd, close perspect:
    ID: 07031050.wav
    Length: 214
** Crowds: Outside Buckingham Palace, large subdued crowd.                                                                                :Crowds:Outside Buckingham Palace, large subdued crowd:
    ID: 07031049.wav
    Length: 181
** Crowds: Outside Buckingham Palace, Subdued, Horseguards pass, mid-distant perspective.                                                                                :Crowds:Outside Buckingham Palace, Subdued, Horseguards pass, mi:
    ID: 07031048.wav
    Length: 75
** Crowds: Outside Buckingham Palace, Noisy, footsteps, distant national anthem played and sung.                                                                                :Crowds:Outside Buckingham Palace, Noisy, footsteps, distant nat:
    ID: 07031047.wav
    Length: 117
** Crowds: Outside Buckingham Palace, Cheer, Applause, mid-distant perspective.                                                                                :Crowds:Outside Buckingham Palace, Cheer, Applause, mid-distant:
    ID: 07031046.wav
    Length: 22
** Outdoor Crowd: Fete, children and adults, distant birdsong.                                                                                :Outdoor Crowd:Fete, children and adults, distant birdsong:
    ID: 07031045.wav
    Length: 366
** Outdoor Crowd: Henley Regatta, applause, atmosphere.                                                                                :Outdoor Crowd:Henley Regatta, applause, atmosphere:
    ID: 07031044.wav
    Length: 30
** Outdoor Crowd: Henley Regatta, close perspective recording (Occasional indistinct p.a. and boats).                                                                                :Outdoor Crowd:Henley Regatta, close perspective recording (Occa:
    ID: 07031043.wav
    Length: 306
** Market Square: Small Town, Wisbech, Cambridge, footsteps, voices and some traffic, busier towards end. (For use at low level)                                                                                :Market Square:Small Town, Wisbech, Cambridge, footsteps, voices:
    ID: 07031042.wav
    Length: 368
** St. Mark's Square, Venice: Quiet, early morning, occasional distant voices, footsteps and pigeons, no traffic.                                                                                 :Streets:Venice:
    ID: 07031041.wav
    Length: 396
** Crowd: Italy, Large Square, chatter and footsteps, no traffic. (Some distinct speech)                                                                                :Crowds:Italy, Large Square, chatter and footsteps, no traffic:
    ID: 07031040.wav
    Length: 186
** Crowd: Italy, Street Atmosphere, children and footsteps, no traffic. (Some distinct speech)                                                                                :Crowds:Italy, Street Atmosphere, children and footsteps, no tra:
    ID: 07031039.wav
    Length: 184
** Italian Market: Rialto, Venice, children, chatter and footsteps, no traffic. (Some distinct speech)                                                                                :Italian Market:Rialto, Venice, children, chatter and footsteps,:
    ID: 07031038.wav
    Length: 366
** Crowd: Large, expectant, with birdsong. (Wide perspective recording)                                                                                :Crowds:Large, expectant, with birdsong:
    ID: 07031037.wav
    Length: 377
** Crowd: Background, expectant, with birdsong, occasional footsteps and speech.                                                                                :Crowds:Background, expectant, with birdsong, occasional footste:
    ID: 07031036.wav
    Length: 408
** Crowd: London Zoo, Sealions at feeding time, barks, splashes, children.                                                                                :Crowds:London Zoo:
    ID: 07031035.wav
    Length: 375
** Crowd: London Zoo, Outdoor, general, children. (No animal sounds).                                                                                :Crowds:London Zoo, Outdoor, general, children:
    ID: 07031034.wav
    Length: 365
** Crowds: Exterior, Berwick Street Market, speech, coins, footsteps. (Recorded walking along).                                                                                :Crowds:Exterior, Berwick Street Market, speech, coins, footstep:
    ID: 07031033.wav
    Length: 379
** Crowds: Exterior, Aylesbury Market, speech, traffic, footsteps, ventilator hum.                                                                                :Crowds:Exterior, Aylesbury Market, speech, traffic, footsteps,:
    ID: 07031032.wav
    Length: 452
** Crowds: Exterior, shouting, screaming and laughing.                                                                                :Crowds:Exterior, shouting, screaming and laughing:
    ID: 07031031.wav
    Length: 139
** Crowds: Exterior, Angry jeering crowd.                                                                                :Crowds:Exterior, Angry jeering crowd:
    ID: 07031030.wav
    Length: 239
** Crowds: Exterior, Berwick Street Market, London, footsteps and chatter.                                                                                :Crowds:Exterior, Berwick Street Market, London, footsteps and c:
    ID: 07031029.wav
    Length: 270
** Crowds: Exterior, Paternoster Square, London, footsteps and chatter.                                                                                :Crowds:Exterior, Paternoster Square, London, footsteps and chat:
    ID: 07031028.wav
    Length: 227
** Traffic: A fire engine passing through side streets.                                                                                :Traffic:A fire engine passing through side streets:
    ID: 07031027.wav
    Length: 408
** Traffic: Quiet night atmosphere in side street.                                                                                :Traffic:Quiet night atmosphere in side street:
    ID: 07031026.wav
    Length: 366
** Traffic: French, bank of River Seine. Ambulance passes at 6'                                                                                :Traffic:French, bank of River Seine:
    ID: 07031025.wav
    Length: 421
** Traffic: Whistle from French traffic police.                                                                                :Traffic:Whistle from French traffic police:
    ID: 07031024.wav
    Length: 8
** Traffic: Parisian square with footsteps, occasional speech, distant traffic police whistle.                                                                                :Traffic:Parisian square with footsteps, occasional speech, dist:
    ID: 07031023.wav
    Length: 336
** Traffic: Busy motorway traffic passing with occasional pause. (M.4. Slough)                                                                                :Traffic:Busy motorway traffic passing with occasional pause:
    ID: 07031022.wav
    Length: 368
** Traffic: Daytime city background with pauses in traffic and birdsong. (Occasional hiss from vehicle or machine)                                                                                :Traffic:Daytime city background with pauses in traffic and bird:
    ID: 07031021.wav
    Length: 366
** Traffic: Sound of fast traffic on a trunk road.                                                                                :Traffic:Sound of fast traffic on a trunk road:
    ID: 07031020.wav
    Length: 373
** Traffic: A busy city skyline. (Technical note, for use at low level)                                                                                :Traffic:A busy city skyline:
    ID: 07031019.wav
    Length: 371
** Traffic: Heavy in a one way street, occasional dog bark( R - L)                                                                                :Traffic:Heavy in a one way street:
    ID: 07031018.wav
    Length: 370
** Traffic: Heavy, with footsteps in a one-way street.                                                                                :Traffic:Heavy, with footsteps in a one-way street:
    ID: 07031017.wav
    Length: 431
** Traffic: Car Park of Television Centre, distant traffic with occasional close vehicle and footsteps.                                                                                :Traffic:Car Park of Television Centre, distant traffic with occ:
    ID: 07031016.wav
    Length: 349
** Traffic: Forecourt of Television Centre, occasional Metropolitan Line train.                                                                                :Traffic:Forecourt of Television Centre, occasional Metropolitan:
    ID: 07031015.wav
    Length: 383
** Traffic: Mid-Distant, atmosphere from roof top, with wind & birds(Technical note, for use at low level)                                                                                :Traffic:Mid-Distant:
    ID: 07031014.wav
    Length: 344
** Traffic: Quiet City background, wide perspective, distant clock at 5'. (Technical note, for use at low level)                                                                                :Traffic:Quiet City background, wide perspective, distant clock:
    ID: 07031013.wav
    Length: 361
** Traffic:  Wet City street with dripping water, from steps of Westminster Abbey                                                                                :Traffic:Wet City street with dripping water:
    ID: 07031012.wav
    Length: 352
** Traffic: Wet city street, from steps of St Paul's                                                                                :Traffic:Wet city street:
    ID: 07031011.wav
    Length: 351
** Traffic: Regent's Park, Carpark, atmos' from inside closed car. (Technical note, for use at low level)                                                                                :Traffic:Regent's Park, Carpark, atmos' from inside closed car:
    ID: 07031010.wav
    Length: 299
** Traffic: Regent's Park, Carpark, atmos' with close and distant traffic. (Technical note, for use at low level)                                                                                :Traffic:Regent's Park, Carpark, atmos' with close and distant t:
    ID: 07031009.wav
    Length: 310
** Traffic: Horses, sound of horse traffic.                                                                                :Traffic:Horses, sound of horse traffic:
    ID: 07031008.wav
    Length: 318
** Traffic: French,Busy traffic.                                                                                :Traffic:French,Busy traffic:
    ID: 07031007.wav
    Length: 456
** Traffic: recorded from top of building.                                                                                :Traffic:recorded from top of building:
    ID: 07031006.wav
    Length: 412
** Traffic: Quiet main road, evening.                                                                                :Traffic:Quiet main road, evening:
    ID: 07031005.wav
    Length: 416
** Traffic : Sound of night traffic in town.                                                                                :Traffic:Sound of night traffic in town:
    ID: 07031004.wav
    Length: 325
** Traffic : Trafalgar Square, recording of night traffic                                                                                 :Traffic:Trafalgar Square:
    ID: 07031003.wav
    Length: 384
** Traffic: London side street                                                                                :Traffic:
    ID: 07031002.wav
    Length: 326
** Traffic: London West End, Portland Place                                                                                :Traffic:London West End:
    ID: 07031001.wav
    Length: 385
** Pheasant shoot, general background.                                                                                ::
    ID: 07030114.wav
    Length: 233
** Pheasant shoot, shots at cock pheasants.                                                                                ::
    ID: 07030113.wav
    Length: 41
** Pheasant shoot, footsteps in undergrowth, flushing birds out.                                                                                ::
    ID: 07030112.wav
    Length: 72
** Clay Pigeon Shoot, Marker calling Singles, shooters call, shots & other atmosphere.                                                                                ::
    ID: 07030111.wav
    Length: 23
** Clay Pigeon Shoot, shots, whistles, foreground chatter.                                                                                ::
    ID: 07030110.wav
    Length: 79
** Clay Pigeon Shoot, shots & background shouts.                                                                                ::
    ID: 07030109.wav
    Length: 23
** Clay Pigeon Shoot, shots, springs of launchers pulled back, whistles & shouts in background.                                                                                ::
    ID: 07030108.wav
    Length: 52
** Double-barrel Shotgun, both barrels fired.                                                                                ::
    ID: 07030107.wav
    Length: 8
** Double-barrel Shotgun, both barrels fired.                                                                                ::
    ID: 07030106.wav
    Length: 8
** 17-bore Twin-barrel Shotgun, two guns firing both barrels. (Shotgun c. 1870.)                                                                                ::
    ID: 07030105.wav
    Length: 12
** 17-bore Twin-barrel Shotgun, both barrels fired. (Shotgun c. 1870.)                                                                                ::
    ID: 07030104.wav
    Length: 8
** 17-bore Twin-barrel Shotgun, both barrels fired. (Shotgun c. 1870.)                                                                                ::
    ID: 07030103.wav
    Length: 6
** 17-bore Twin-barrel Shotgun, second barrel fired. (Shotgun c. 1870.)                                                                                ::
    ID: 07030102.wav
    Length: 6
** 17-bore Twin-barrel Shotgun, first barrel fired. (Shotgun c. 1870.)                                                                                ::
    ID: 07030101.wav
    Length: 6
** 17-bore Twin-barrel Shotgun, powder & shot poured in, rammed. (Shotgun c. 1870.)                                                                                ::
    ID: 07030100.wav
    Length: 66
** 12-bore Shotgun, load, shot & cartridge ejected.                                                                                ::
    ID: 07030099.wav
    Length: 21
** 12-bore Shotgun, load & single shot.                                                                                ::
    ID: 07030098.wav
    Length: 11
** 12-bore Shotgun, three shots. (Distant perspective recording.)                                                                                ::
    ID: 07030097.wav
    Length: 11
** 12-bore Shotgun, single shot. (Distant perspective recording.)                                                                                ::
    ID: 07030096.wav
    Length: 6
** 12-bore Shotgun, single shot. (Close perspective recording.)                                                                                ::
    ID: 07030095.wav
    Length: 6
** 12-bore Shotgun, single shot.                                                                                ::
    ID: 07030094.wav
    Length: 7
** Shoe Repairing, general atmosphere in a large repair shop.                                                                                ::
    ID: 07030093.wav
    Length: 396
** Shoe Repairing, general atmosphere in a repair shop.                                                                                ::
    ID: 07030092.wav
    Length: 274
** Shoe Repairing, final polish.                                                                                ::
    ID: 07030091.wav
    Length: 106
** Shoe Repairing, setting edges.                                                                                ::
    ID: 07030090.wav
    Length: 107
** Shoe Repairing, padding and polishing.                                                                                ::
    ID: 07030089.wav
    Length: 132
** Shoe Repairing, trimming sole edges.                                                                                ::
    ID: 07030088.wav
    Length: 133
** Shoe Repairing, scouring.                                                                                ::
    ID: 07030087.wav
    Length: 146
** Shoe Repairing, hammering out a shoe.                                                                                ::
    ID: 07030086.wav
    Length: 127
** Shoe Repairing, closing of channels.                                                                                ::
    ID: 07030085.wav
    Length: 106
** Shoe Repairing, chain stitching.                                                                                ::
    ID: 07030084.wav
    Length: 197
** Shoe Repairing, welted shoe being stitched rapidly.                                                                                ::
    ID: 07030083.wav
    Length: 191
** Shoe Repairing, cutting new soles.                                                                                ::
    ID: 07030082.wav
    Length: 244
** Shoe Repairing, work being done at bench.                                                                                ::
    ID: 07030081.wav
    Length: 138
** Pet Shop: Thirty budgerigars in shed.                                                                                :Shops:Pet Shop:
    ID: 07030080.wav
    Length: 124
** Pet Shop: Agitated birds and cockatiel screeching.                                                                                :Shops:Pet Shop:
    ID: 07030079.wav
    Length: 17
** Pet Shop: Agitated birds and cockatiel screeching.                                                                                :Shops:Pet Shop:
    ID: 07030078.wav
    Length: 12
** Pet Shop: Birds flapping wings with faint calls.                                                                                :Shops:Pet Shop:
    ID: 07030077.wav
    Length: 15
** Pet Shop: Cockatiel calling.                                                                                :Shops:Pet Shop:
    ID: 07030076.wav
    Length: 12
** Pet Shop: Small, caged birds. (Rec. in a pet shop but suitable for aviary. Rec. Petersfield, Hants)                                                                                :Shops:Pet Shop:
    ID: 07030075.wav
    Length: 66
** Pet Shop: Small, aquaria bubbling.                                                                                :Shops:Pet Shop:
    ID: 07030074.wav
    Length: 69
** Pet Shop: Large, aquaria, mixed birds, occasional indistinct speech.                                                                                :Shops:Pet Shop:
    ID: 07030073.wav
    Length: 424
** Pigeons: Flying off.                                                                                :Birds:Pigeons:
    ID: 07030072.wav
    Length: 8
** Pigeons: Flying off.                                                                                :Birds:Pigeons:
    ID: 07030071.wav
    Length: 11
** Pigeons: Flying off.                                                                                :Birds:Pigeons:
    ID: 07030070.wav
    Length: 7
** Pigeons: Flying off.                                                                                :Birds:Pigeons:
    ID: 07030069.wav
    Length: 10
** Pigeons: Flying, Chasing in coop.                                                                                :Birds:Pigeons:
    ID: 07030068.wav
    Length: 68
** Pigeons: Flying out of coop.                                                                                :Birds:Pigeons:
    ID: 07030067.wav
    Length: 8
** Pigeons: Flapping and Cooing in coop.                                                                                :Birds:Pigeons:
    ID: 07030066.wav
    Length: 394
** Gardens: Farm garden with housemartins, swallows, pigeons, rooks, bees and grasshoppers, mid-morning.                                                                                :Gardens:Farm garden with housemartins, swallows, pigeons, rooks:
    ID: 07030065.wav
    Length: 410
** Gardens: Early morning in garden, July.                                                                                :Gardens:Early morning in garden, July:
    ID: 07030064.wav
    Length: 397
** Autumn, Atmosphere: Quiet birds, insects, light breeze.                                                                                :Atmospheres:Autumn:
    ID: 07030063.wav
    Length: 214
** Autumn, Atmosphere: Blackbirds, evening calls.                                                                                :Atmospheres:Autumn:
    ID: 07030062.wav
    Length: 213
** Autumn, Atmosphere: Sparrows, Starlings, Blackbirds roosting in thicket, subdued.                                                                                :Atmospheres:Autumn:
    ID: 07030061.wav
    Length: 215
** Autumn, Atmosphere: Sparrows, Starlings roosting in thicket, lively.                                                                                :Atmospheres:Autumn:
    ID: 07030060.wav
    Length: 213
** Woodland Edge: March with robins, great tits, jays, (Technical note: for use at low level).                                                                                :Atmospheres:Woodlands:
    ID: 07030059.wav
    Length: 393
** Summer, Atmosphere: June, hot weather, close buzzing of bees. (For use at low level).                                                                                :Atmospheres:Summer:
    ID: 07030058.wav
    Length: 394
** Moorland: Exmoor, June, chaffinch, redpolls, distant cuckoo, cattle, sheep.                                                                                :Moorland:Exmoor, June, chaffinch, redpolls, distant cuckoo, cat:
    ID: 07030057.wav
    Length: 392
** Woodland Edge: Early morning, June, thrushes, willow warblers predominate, occasional crow.                                                                                :Atmospheres:Woodlands:
    ID: 07030056.wav
    Length: 394
