** Very quiet lochside mixed woodland atmosphere in afternoon, waves lapping, occasional coal lit, wind in trees.                                                                                :Atmospheres:Afternoon:
    ID: 07049088.wav
    Length: 194
** Harbour atmosphere, with herring gull calls and quayside activity.                                                                                :Atmospheres:Winter:
    ID: 07049087.wav
    Length: 177
** Herring gull breeding colony on roof top.                                                                                :Atmospheres:Summer:
    ID: 07049086.wav
    Length: 97
** Sea Cliffs & Rocky Shores, heavy seas with eiders, artic terns, fulmers, skylark & wren. (Recorded on a late spring evening.)                                                                                :Atmospheres:Evening:
    ID: 07049085.wav
    Length: 341
** Early evening atmosphere, closeup and mid distant calls from a flock grazing in field, blackbird, woodpigeons and other                                                                                 :Atmospheres:Evening:
    ID: 07049084.wav
    Length: 231
** Early evening atmosphere, mid close and distant calls from flock feeding on open hillside, chiffchaff and jackdaw in                                                                                 :Atmospheres:Evening:
    ID: 07049083.wav
    Length: 201
** Early evening atmosphere, mid distance calls from flock of sheep grazing in field, calls echo round valley, robin,                                                                                 :Atmospheres:Evening:
    ID: 07049082.wav
    Length: 284
** Summer afternoon farmyard atmosphere with house sparrow and blackbird calling, mid distance, with collared dove,                                                                                 :Atmospheres:Farms:
    ID: 07049081.wav
    Length: 286
** Summer afternoon atmosphere in farmyard with house sparrow calling mid distance, rook collared doves, sheep, insects                                                                                 :Atmospheres:Afternoon:
    ID: 07049080.wav
    Length: 252
** Atmosphere in farmyard, summer afternoon, with house sparrow calling, woodpigeon, collared dove, chaffinch, rook,                                                                                 :Atmospheres:Afternoon:
    ID: 07049079.wav
    Length: 266
** Summer afternoon atmosphere, house sparrow calling close, collared dove, woodpigeon, distant sheep, rooks, wren,                                                                                 :Atmospheres:Afternoon:
    ID: 07049078.wav
    Length: 235
** Rookery at dawn, also calls from jackdaw.                                                                                :Atmospheres:Dawn:
    ID: 07049077.wav
    Length: 262
** Early summer mixed woodland atmosphere, early morning with chiffchaff, goldcrest, wren alarm, lambs, fox yapping and                                                                                 :Atmospheres:Morning:
    ID: 07049076.wav
    Length: 240
** Deciduous woodland atmosphere at dawn with robins, wrens, woodpigeon, song thrush, rooks, chiffchaff, blackbird and                                                                                 :Atmospheres:Dawn:
    ID: 07049075.wav
    Length: 281
** Early morning mixed woodland atmosphere during early spring with robin, nuthatch, song thrush and blue tit, distant                                                                                 :Atmospheres:Spring:
    ID: 07049074.wav
    Length: 245
** Ammunition Factory, cartidges on conveyor belt.                                                                                :Conveyor Belts:
    ID: 07049073.wav
    Length: 83
** Ammunition Factory, cartridge printing machine in operation, with occasional indistinct speech.                                                                                :Industry:Ammunition Factories:
    ID: 07049072.wav
    Length: 64
** Ammunition Factory, cartridge capping machine in operation.                                                                                :Industry:Ammunition Factories:
    ID: 07049071.wav
    Length: 85
** Ammunition Factory, general background atmosphere. (No speech.)                                                                                :Industry:Ammunition Factories:
    ID: 07049070.wav
    Length: 50
** Ammunition Factory, plastic tubes being straightened.                                                                                :Industry:Ammuntion Factories:
    ID: 07049069.wav
    Length: 46
** Ammunition Factory, paper cartridge machine operating.                                                                                :Industry:Ammumition Factories:
    ID: 07049068.wav
    Length: 92
** Ammunition Factory, plastic tubing cut into lengths (with pause between each cut).                                                                                :Industry:Ammunition Factories:
    ID: 07049067.wav
    Length: 77
** Ammunition Factory, plastic cartridge extrusion machine operating.                                                                                :Industry:Ammunition Factories:
    ID: 07049066.wav
    Length: 43
** Ammunition Factory, background atmosphere in a plastic cartridge extrusion room. (No speech.)                                                                                :Industry:Ammunition Factories:
    ID: 07049065.wav
    Length: 111
** Sporting Gun Factory, checking firing mechanism of guns.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049064.wav
    Length: 29
** Sporting Gun Factory, general background with some voices.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049063.wav
    Length: 155
** Sporting Gun Factory, atmosphere in finishing department with machinery.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049062.wav
    Length: 62
** Sporting Gun Factory, shaping machine switched on, operates with occasional pauses.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049061.wav
    Length: 62
** Sporting Gun Factory, general background atmosphere with occasional indistinct speech.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049060.wav
    Length: 65
** Sporting Gun Factory, band saw switched on, operates with occasional pauses.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049059.wav
    Length: 132
** Sporting Gun Factory, copy lathe turning.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049058.wav
    Length: 134
** Sporting Gun Factory, copy lathe cutting gun butts.                                                                                :Industry:Sporting Gun Factories:
    ID: 07049057.wav
    Length: 23
** Drop forge shop, general atmosphere.                                                                                :Industry:Drop Forges:
    ID: 07049056.wav
    Length: 157
** 30cwt. Massey drop hammer and 5cwt. power hammer operating in a drop forge shop.                                                                                :Hammers:Drop Hammers:
    ID: 07049055.wav
    Length: 79
** 20cwt. Massey drop hammer operating in a drop forge shop.                                                                                :Hammers:Drop Hammers:
    ID: 07049054.wav
    Length: 80
** 5cwt. Massey power hammer operating in a drop forge shop.                                                                                :Hammers:Power Hammers:
    ID: 07049053.wav
    Length: 25
** Coining press in operation in drop forge shop, with some indistinct speech.                                                                                :Industry:Drop Forges:
    ID: 07049052.wav
    Length: 80
** Drop forge shop, interior, atmosphere.                                                                                :Industry:Drop Forges:
    ID: 07049051.wav
    Length: 151
** Drop forge shop, exterior, atmosphere.                                                                                :Industry:Drop Forges:
    ID: 07049050.wav
    Length: 153
** Sheet metal engineering machine shop, general atmosphere.                                                                                :Industry:Sheet Metal Engineering:
    ID: 07049049.wav
    Length: 373
** Electrical engineering, arc squeaking and striking.                                                                                :Electrical Engineering:
    ID: 07049048.wav
    Length: 118
** Electrical engineering, arc striking.                                                                                :Electrical Engineering:
    ID: 07049047.wav
    Length: 12
** Chemical Works, crucible quenching in progress.                                                                                :Chemical Works:
    ID: 07049046.wav
    Length: 11
** Chemical Works, crucible quenching in progress.                                                                                :Chemical Works:
    ID: 07049045.wav
    Length: 10
** Sheet metal engineering, plate metal rolling machine operating with occasional pauses.                                                                                :Industry:Sheet Metal Engineering:
    ID: 07049044.wav
    Length: 65
** Sheet metal engineering, sheet metal being drilled, continuous sound.                                                                                :Drills:Industrial:
    ID: 07049043.wav
    Length: 72
** Sheet metal engineering, portable grinding machine operating.                                                                                :Grinders:Metal:
    ID: 07049042.wav
    Length: 54
** Sheet metal engineering, stationary machine grinding metal.                                                                                :Grinders:Metal:
    ID: 07049041.wav
    Length: 63
** Sheet metal engineering, auto hacksaw cutting through sheet metal.                                                                                :Industry:Sheet Metal Engineering:
    ID: 07049040.wav
    Length: 150
** Sheet metal engineering, friction metal saw switched on, operates with pauses.                                                                                :Industry:Sheet Metal Engineering:
    ID: 07049039.wav
    Length: 80
** Sheet metal engineering, sheet metal cut by guillotine.                                                                                :Guillotines:
    ID: 07049038.wav
    Length: 54
** Sheet metal engineering, sheet metal cut by an oxy-acetylene torch. (Bangs at start.)                                                                                :Acetylene Torches:
    ID: 07049037.wav
    Length: 93
** Sheet metal engineering, special welding in progress, pauses and indistinct speech. (Sounds like static.)                                                                                :Industry:Sheet Metal Engineering:
    ID: 07049036.wav
    Length: 156
** Sheet metal engineering, arc welding with some indistinct speech.                                                                                :Industry:Sheet Metal Engineering:
    ID: 07049035.wav
    Length: 62
** Workers clocking on or off work at factory, general atmosphere with indistinct speech with footsteps.                                                                                :Clocking Machines:
    ID: 07049034.wav
    Length: 123
** Workers clocking on or off work at factory, general atmosphere with indistinct speech with footsteps & sound of clocking machine bell.                                                                                :Clocking Machines:
    ID: 07049033.wav
    Length: 118
** Oxy-acetylene torch cutting sheet metal.                                                                                :Acetylene Torches:
    ID: 07049032.wav
    Length: 132
** Oxy-acetylene torch cutting steel girder.                                                                                :Acetylene Torches:
    ID: 07049031.wav
    Length: 107
** Internal grinder switched on, operating & run down to stop. (Repeated once at lower speed.)                                                                                :Grinders:Internal:
    ID: 07049030.wav
    Length: 116
** Surface grinder operating, with occasional pauses.                                                                                :Grinders:Surface:
    ID: 07049029.wav
    Length: 77
** Electric drill, three bursts.                                                                                :Drills:Electric:
    ID: 07049028.wav
    Length: 26
** Motor Car Works, buffing sheet metal parts with some pauses.                                                                                :Buffers:Metal:
    ID: 07049027.wav
    Length: 202
** Motor Car Works, scurfing sheet metal parts with constant hum of machinery.                                                                                :Industry:Motor Car Manufacture:
    ID: 07049026.wav
    Length: 203
** Motor Car Works, 750 ton press stamping out metal parts. (Some indistinct speech)                                                                                :Industry:Motor Car Manufacture:
    ID: 07049025.wav
    Length: 191
** Motor Car Works, high pressure air pipes singing.                                                                                :Industry:Motor Car Manufacture:
    ID: 07049024.wav
    Length: 197
** Motor Car Works high-pressure spray plant, general atmosphere with pauses & indistinct speech.                                                                                :Industry:Motor Car Manufacture:
    ID: 07049023.wav
    Length: 195
** Motor Car Works, spot welding of car bodies. (No speech)                                                                                :Industry:Motor Car Manufacture:
    ID: 07049022.wav
    Length: 148
** Motor Car Works, tightening nuts mechanically, some pauses & background hammering.                                                                                :Industry:Motor Car Manufacture:
    ID: 07049021.wav
    Length: 62
** Motor Car Works, body building shop atmosphere. (No speech.)                                                                                :Industry:Motor Car Manufacture:
    ID: 07049020.wav
    Length: 220
** Motor Car Works, general atmosphere. (No speech.)                                                                                :Industry:Motor Car Manufacture:
    ID: 07049019.wav
    Length: 210
** Tyre factory, tyre beading machine operating.                                                                                :Industry:Tyre Manufacture:
    ID: 07049018.wav
    Length: 183
** Tyre factory, weathering tyres with hum & rattling of machinery.                                                                                :Industry:Tyre Manufacture:
    ID: 07049017.wav
    Length: 149
** Tyre factory, mixing raw rubber.                                                                                :Industry:Tyre Manufacture:
    ID: 07049016.wav
    Length: 246
** Tyre factory, heavy steam hisses. (Close perspective with some pauses.)                                                                                :Industry:Tyre Manufacture:
    ID: 07049015.wav
    Length: 88
** Tyre factory, general atmosphere in a mill room. (No speech.)                                                                                :Industry:Tyre Manufacture:
    ID: 07049014.wav
    Length: 361
** Tyre factory, debagging tyres, hisses with pauses.                                                                                :Industry:Tyre Manufacture:
    ID: 07049013.wav
    Length: 365
** Tyre factory, general atmosphere. (No speech.)                                                                                :Industry:Tyre Manufacture:
    ID: 07049012.wav
    Length: 304
** Motor accessories assembly shop, general atmosphere.                                                                                :Industry:Motor Car Manufacture:
    ID: 07049011.wav
    Length: 305
** Assembly shop, general atmosphere with sound of machinery & some indistinct speech.                                                                                :Industry:Light:
    ID: 07049010.wav
    Length: 362
** Machine shop, general atmosphere with constant sound of machinery. (No speech.)                                                                                :Industry:Light:
    ID: 07049009.wav
    Length: 324
** Injection moulding shop, general atmosphere with machinery & some indistinct speech.                                                                                :Industry:Light:
    ID: 07049008.wav
    Length: 364
** Assembly shop, general atmosphere with sound of machinery, occasional drilling & some indistinct speech.                                                                                :Industry:Light:
    ID: 07049007.wav
    Length: 299
** Assembly shop, general atmosphere with sounds of machinery & machinery operating at quick pace.                                                                                :Industry:Light:
    ID: 07049006.wav
    Length: 347
** Assembly shop, general atmosphere with sounds of machinery & machinery operating at quick pace.                                                                                :Industry:Light:
    ID: 07049005.wav
    Length: 317
** Weingarten hydraulic press operating.                                                                                :Industry:Light:
    ID: 07049004.wav
    Length: 366
** Wire cutting machine operating, some pauses & indistinct speech.                                                                                :Industry:Light:
    ID: 07049003.wav
    Length: 118
** Braiding machine operating, some pauses & indistinct speech.                                                                                :Braiding Machines:
    ID: 07049002.wav
    Length: 143
** Moulding crusher operating.                                                                                :Crushers:
    ID: 07049001.wav
    Length: 50
** Two in flight,steep and shallow dives,1944 (reprocessed)                                                                                :Fighters:
    ID: 07048212.wav
    Length: 30
** Two taxi and take off,1944 (reprocessed)                                                                                :Fighters:
    ID: 07048211.wav
    Length: 55
** Landing,1944 (reprocessed)                                                                                :Aircraft:Tempests:
    ID: 07048210.wav
    Length: 22
** Take off ,1944 (reprocessed)                                                                                :Fighters:
    ID: 07048209.wav
    Length: 24
** In flight(overhead)1944 (reprocessed)                                                                                :Fighters:
    ID: 07048208.wav
    Length: 59
** In flight(overhead)1944 (reprocessed)                                                                                :Fighters:
    ID: 07048207.wav
    Length: 73
** In flight,circles aerodrome twice,lands,1944(reprocessed)                                                                                :Fighters:
    ID: 07048206.wav
    Length: 157
** Taxi to runway and take off,1944(reprocessed)                                                                                :Fighters:
    ID: 07048205.wav
    Length: 49
** Start up engine,tick over,shut off,1944 (reprocessed)                                                                                :Fighters:
    ID: 07048204.wav
    Length: 79
** Tempest (Single Engined Fighter) (GB) start up engine,tick over,rev up,shut off,1944(reprocessed)                                                                                :Fighters:
    ID: 07048203.wav
    Length: 105
** Landing (reprocessed)                                                                                :Bombers:
    ID: 07048202.wav
    Length: 34
** Approaching and landing (reprocessed)                                                                                :Bombers:
    ID: 07048201.wav
    Length: 79
** Circling aerodrome at 1,000-2,000 ft (reprocessed)                                                                                :Bombers:
    ID: 07048200.wav
    Length: 77
** Taking off with others overhead(reprocessed)                                                                                :Bombers:
    ID: 07048199.wav
    Length: 55
** Taking off (reprocessed)                                                                                :Bombers:
    ID: 07048198.wav
    Length: 36
** Taking off (reprocessed)                                                                                :Bombers:
    ID: 07048197.wav
    Length: 40
** Taking off (reprocessed)                                                                                :Bombers:
    ID: 07048196.wav
    Length: 34
** Starting up,engines running,stop engines(rec.outside aircraft) (reprocessed)                                                                                :Bombers:
    ID: 07048195.wav
    Length: 195
** Stirling (4 Engined Heavy Bomber, Transport) (GB) starting up with orders,engine running,stop engines with orders(rec.inside aircraft) (reprocessed)                                                                                :Bombers:
    ID: 07048194.wav
    Length: 154
** One Spitfire taking off towards mic. (reprocessed)                                                                                :Aircraft:Spitfire:
    ID: 07048193.wav
    Length: 43
** One Spitfire taking off towards mic.(reprocessed)                                                                                :Aircraft:Spitfire:
    ID: 07048192.wav
    Length: 23
** One Spitfire flying low overhead (reprocessed)                                                                                :Aircraft:Spitfire:
    ID: 07048191.wav
    Length: 31
** One Spitfire flying low overhead (reprocessed)                                                                                :Aircraft:Spitfire:
    ID: 07048190.wav
    Length: 30
** Two squadrons passing at 1500 ft (reprocessed)                                                                                :Aircraft:Spitfire:
    ID: 07048189.wav
    Length: 74
** Spitfire (Reconnaissance Fighter) (GB), two squadrons taking off in formation (reprocessed)                                                                                :Aircraft:Spitfire:
    ID: 07048188.wav
    Length: 153
** Bombers circling aerodrome and coming in to land (reprocessed)                                                                                :Bombers:
    ID: 07048187.wav
    Length: 73
** Bombers in flight overhead (reprocessed)                                                                                :Bombers:
    ID: 07048186.wav
    Length: 65
** Mitchell B25 (Bomber) (USA), 5 aircraft taxi-ing and taking off in succession(reprocessed)                                                                                :Bombers:
    ID: 07048185.wav
    Length: 178
** Landing, March 1945 (reprocessed)                                                                                :Bombers:
    ID: 07048184.wav
    Length: 36
** Taking off, March 1945 (reprocessed)                                                                                :Bombers:
    ID: 07048183.wav
    Length: 36
** Taking off, March 1945 (reprocessed)                                                                                :Bombers:
    ID: 07048182.wav
    Length: 31
** Marauder B24 (4 Engined Bomber) (USA) taking off,March 1945 (reprocessed)                                                                                :Bombers:
    ID: 07048181.wav
    Length: 25
** Aerodrome atmosphere with Liberators,engines idling,some aircraft movement,background birds,March 1945 (reprocessed)                                                                                :Bombers:
    ID: 07048180.wav
    Length: 174
** Taking off,March 1945 (reprocessed)                                                                                :Bombers:
    ID: 07048179.wav
    Length: 28
** Liberator B24 (4 Engined Bomber) (USA) taking off,March 1945 (reprocessed)                                                                                :Bombers:
    ID: 07048178.wav
    Length: 25
** Taxi-ing and tick over (reprocessed)                                                                                :Fighters:
    ID: 07048177.wav
    Length: 46
** Coming in to land (reprocessed)                                                                                :Fighters:
    ID: 07048176.wav
    Length: 33
** Starting up                                                                                :Fighters:
    ID: 07048175.wav
    Length: 47
** Diving (reprocessed)                                                                                :Fighters:
    ID: 07048174.wav
    Length: 22
** Diving (reprocessed)                                                                                :Fighters:
    ID: 07048173.wav
    Length: 13
** Diving (reprocessed)                                                                                :Fighters:
    ID: 07048172.wav
    Length: 14
** Diving (reprocessed)                                                                                :Fighters:
    ID: 07048171.wav
    Length: 18
** Hurricane (Fighter) (GB) diving (reprocessed)                                                                                :Fighters:
    ID: 07048170.wav
    Length: 13
** Lands on ship and taxis forward,occasional voices (reprocessed)                                                                                :Fighters:
    ID: 07048169.wav
    Length: 41
** Diving from ship (reprocessed)                                                                                :Fighters:
    ID: 07048168.wav
    Length: 14
** Takes off from ship (reprocessed)                                                                                :Fighters:
    ID: 07048167.wav
    Length: 21
** Hellcat (Carrier Fighter, Fleet Air Arm) (USA) lands on ship,occasional voices (reprocessed)                                                                                :Fighters:
    ID: 07048166.wav
    Length: 21
** Passing over in formation (from bomb bay) (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048165.wav
    Length: 135
** Passing over in formation (from ground) (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048164.wav
    Length: 88
** Interior in flight (rec.in lower blister) (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048163.wav
    Length: 101
** Landing,March 1945 (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048162.wav
    Length: 28
** Landing,March 1945 (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048161.wav
    Length: 28
** Taking off,March 1945 (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048160.wav
    Length: 25
** Taking off,March 1945 (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048159.wav
    Length: 34
** Flying Fortress B17 (4 Engined Bomber) (USA) taking off,March 1945 (reprocessed)                                                                                :Aircraft:Flying Fortress:
    ID: 07048158.wav
    Length: 51
** In flight (passing overhead) (reprocessed)                                                                                :Fighters:
    ID: 07048157.wav
    Length: 58
** Take off (reprocessed)                                                                                :Fighters:
    ID: 07048156.wav
    Length: 40
** Taxi-ing (reprocessed)                                                                                :Fighters:
    ID: 07048155.wav
    Length: 34
** Defiant (Turret Fighter) (GB) revving engine (reprocessed)                                                                                :Fighters:
    ID: 07048154.wav
    Length: 40
** Catalina (Twin-Engine Patrol Flying Boat) (USA/Canada) diving,from nose (reprocessed)                                                                                :Aircraft:Catalinas:
    ID: 07048153.wav
    Length: 85
** Starts up,revs up,slows down,mic.placed in cockpit,perspex hood closed,normal flight speed,power dive and pull out(imitated) (reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048152.wav
    Length: 228
** Takes off from ship,occasional voices (reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048151.wav
    Length: 28
** Takes off after revving up.Swordfish revs up in background and takes off (reprocessed)                                                                                :Aircraft:Swordfish:
    ID: 07048150.wav
    Length: 39
** Revving up,occasional voices (reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048149.wav
    Length: 26
** Lands on ship (reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048148.wav
    Length: 19
** Lands on ship,high speed revving,taxis forward,cuts out engine,occasional voices(reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048147.wav
    Length: 38
** Lands on ship and taxis forward,occasional voices (reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048146.wav
    Length: 33
** Lands on ship,ticks over,revs up,takes off,occasional voices in background (reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048145.wav
    Length: 95
** Barracuda (Light Bomber, Fleet Air Arm) (GB) misfire on starting,twice (reprocessed)                                                                                :Aircraft:Barracuda:
    ID: 07048144.wav
    Length: 23
** Market, Moscow (interior) morning, busy with clanks, speech, footsteps and general bustle                                                                                :Moscow:
    ID: 07048143.wav
    Length: 276
** Central Market, Moscow (exterior) very lively, with some distinct speech also distant traffic                                                                                :Moscow:
    ID: 07048142.wav
    Length: 230
** Metro ride, Moscow, train stops and starts several times, with doors opening and closing, also PA and some speech                                                                                :Trains:Doors And Windows:
    ID: 07048141.wav
    Length: 182
** Mayakovskovo Metro Station, platform, continuous noise of trains arriving and departing, also footsteps and air conditioning noise                                                                                :Moscow:
    ID: 07048140.wav
    Length: 286
** Mayakovskovo Metro Station, ticket hall during evening rush hour, very busy with footsteps, escalator noise, some distinct speech                                                                                :Moscow:
    ID: 07048139.wav
    Length: 282
** Red Square outside Lenin Mausoleum, some speech, including foreign tourists, also bells (indexed) and footsteps                                                                                :Moscow:
    ID: 07048138.wav
    Length: 255
** Street shopping mall, with footsteps, chat and distant traffic                                                                                :Shops:Shopping Precincts:
    ID: 07048137.wav
    Length: 250
** Foyer, Rossiya Hotel, Moscow (large cosmopolitan hotel, Red Square) chat in various languages and general bustle                                                                                :Foyers:
    ID: 07048136.wav
    Length: 218
** Horse-drawn carriages on cobbles in Stephansplatz, also speech (including children) footsteps, some traffic                                                                                :Cobblestones:
    ID: 07048135.wav
    Length: 220
** Courtyard in Hofburg Palace, footsteps and distinct speech (including foreign tourists and children) exterior with echo                                                                                :Austria:
    ID: 07048134.wav
    Length: 271
** Traffic in Opernring (main road in middle of city) heavy traffic, including trams with bells, also roadworks                                                                                :Trams:Bells:
    ID: 07048133.wav
    Length: 229
** Station cafe, Westbahnhof Station, echoey with loud clinks and some chat                                                                                :Austria:
    ID: 07048132.wav
    Length: 253
** Beer garden in Am Coblenzl suburb, chat (some distinct) birdsong, cock-crows, distant traffic, sounds of barbecue being cooked and served                                                                                :Birds:
    ID: 07048131.wav
    Length: 221
** Coffee house (Cafe Hawelka) with chat (some distinct) newspaper rustles, clinks from kitchen and creaky footsteps                                                                                :Kitchens:
    ID: 07048130.wav
    Length: 224
** Station, Venice - rec.on platform, with train noise and PA (intelligable)                                                                                :Italy:Venice:
    ID: 07048129.wav
    Length: 231
** Street restaurant, Venice - exterior, busy with chat, footsteps, sounds of tables being moved and clinks                                                                                :Restaurants:Italy:
    ID: 07048128.wav
    Length: 292
** Church bells and village band outside church (Poland) during harvest festival celebrations, bells, chat, brass band (very bad) makes circuit of church playing hymn and returns (indexed 2'02'')                                                                                :Atmospheres:Villages:
    ID: 07048127.wav
    Length: 324
** Opera house auditorium, Poland, general atmosphere before performance, occas. distinct speech                                                                                :Poland:
    ID: 07048126.wav
    Length: 296
** Forecourt, Theatre Wiecki, just before performance - latecomers rushing in, echoey stone floor, occ.distinct speech, bell for start of performance                                                                                :Bells:Theatre:
    ID: 07048125.wav
    Length: 269
** Restaurant, Warsaw - with muted chat (occas.distinct) clinks, exterior traffic and some very distant music                                                                                :Traffic:Poland:
    ID: 07048124.wav
    Length: 236
** Small cafe (Milk Bar) Cracow - with chat, clinks and general noise                                                                                :Cafes:Poland:
    ID: 07048123.wav
    Length: 266
** Bus station ticket hall, Warsaw - internal with speech, footsteps, no PA                                                                                :Poland:
    ID: 07048122.wav
    Length: 264
** Train station ticket hall, Cracow - with PA,footsteps,muted chat                                                                                :Trains:Ticket Halls:
    ID: 07048121.wav
    Length: 294
** Library reading room, University of Warsaw - quiet with some paper rustles, creaks of chairs, no speech                                                                                :Libraries:
    ID: 07048120.wav
    Length: 246
** Department store, Warsaw - large acoustic with general bustle, footsteps, clinks and some distinct speech                                                                                :Poland:
    ID: 07048119.wav
    Length: 260
** Bank, Cracow - with speech, footsteps, phones, stamping of documents and till noise                                                                                :Banks:
    ID: 07048118.wav
    Length: 186
** Football crowd, Legia Stadium, Warsaw - large noisy crowd, with chants, cheers, songs and whistling (at end)                                                                                :Crowds:Chanting:
    ID: 07048117.wav
    Length: 367
** Market, Warsaw, fairly animated with distinct speech (in Russian and Polish) and footsteps                                                                                :Markets:Poland:
    ID: 07048116.wav
    Length: 304
** 'Sukienice' (covered craft market) Cracow - echoey with footsteps and some speech                                                                                :Markets:Poland:
    ID: 07048115.wav
    Length: 190
** Market square,Cracow, evening, footsteps, indistinct speech and some traffic - bell of 'Church of Our Lady' chimes 8 (1'33'') and trumpeteer plays traditional call                                                                                :Traffic:Poland:
    ID: 07048114.wav
    Length: 290
** Street, Warsaw, with traffic, footsteps, speech (occas.distinct)                                                                                :Traffic:Poland:
    ID: 07048113.wav
    Length: 231
** Heavy traffic, Cracow, with cars, trams and bikes                                                                                :Bicycles:
    ID: 07048112.wav
    Length: 256
** All clear (France) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048111.wav
    Length: 63
** Alert (France) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048110.wav
    Length: 65
** All clear (Italy) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048109.wav
    Length: 57
** Alert (Italy) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048108.wav
    Length: 66
** All clear (Germany) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048107.wav
    Length: 43
** Alert (Germany) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048106.wav
    Length: 65
** All clear (England) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048105.wav
    Length: 79
** Alert (England) - 1968 (162A)                                                                                :Sirens:Air Raid Sirens:
    ID: 07048104.wav
    Length: 60
** Anti-aircraft fire - 1968 (162A)                                                                                :Air Raids:
    ID: 07048103.wav
    Length: 201
** Air raid on Battersea Park, London - 1940 (500R)                                                                                :Air Raids:
    ID: 07048102.wav
    Length: 174
** Rockets guns, bombs falling (rec. during air raid on London) 1944 (500R)                                                                                :Air Raids:
    ID: 07048101.wav
    Length: 70
** Rocket guns (rec. during air raid on London) 1944 (500R)                                                                                :Air Raids:
    ID: 07048100.wav
    Length: 40
** Night air raid on London - 1944 (500R)                                                                                :Air Raids:
    ID: 07048099.wav
    Length: 145
** Night air raid on London - 1944 (500R)                                                                                :Air Raids:
    ID: 07048098.wav
    Length: 176
** Night air raid on London, barage of anti-aircraft fire - 1943 (500Q)                                                                                :Air Raids:
    ID: 07048097.wav
    Length: 101
** Intensive night air raid on London, anti-aircraft  fire, bombs falling and bursting, fire engine bells (500Q)                                                                                :Air Raids:
    ID: 07048096.wav
    Length: 166
** Night air raid on London, anti-aircraft fire, drone of planes - 1941 (500Q)                                                                                :Air Raids:
    ID: 07048095.wav
    Length: 166
** Night air raid, country district, night alert, faint droning of planes, siren at end - 1944 (500Q)                                                                                :Air Raids:
    ID: 07048094.wav
    Length: 164
** Messerschmitts attack on balloon barrage, driven off by anti-aircraft fire (act. of Dover raid during Battle of Britain) - 1940 (500P)                                                                                :Air Raids:
    ID: 07048093.wav
    Length: 121
** Massed formation of German bombers in steady flight - 1940 (500P)                                                                                :Air Raids:
    ID: 07048092.wav
    Length: 149
** Battle of Britain actuality, air battle (rec. Kent/Sussex border) 1940 (500P)                                                                                :Air Raids:
    ID: 07048091.wav
    Length: 152
** Battle of Britain actuality, air battle (rec. Kent/Sussex border) 1940 (500P)                                                                                :Air Raids:
    ID: 07048090.wav
    Length: 119
** Battle of Britain actuality, air battle (rec. Kent/Sussex border) 1940 (500N)                                                                                :Air Raids:
    ID: 07048089.wav
    Length: 120
** Bombers overhead, anti-aircraft fire, bombs fall 1975 (500N)                                                                                :Air Raids:
    ID: 07048088.wav
    Length: 177
** Night raid on London, stick of bombs, anti-aircraft fire, close, warden's voices - 1940 (500N)                                                                                :Air Raids:
    ID: 07048087.wav
    Length: 127
** Night raid on London, anti-aircraft fire over London's streets - 1940 (500M)                                                                                :Air Raids:
    ID: 07048086.wav
    Length: 129
** Night raid on London, stick of bombs falling, distant anti-aircraft of plane - 1940 (500M)                                                                                :Air Raids:
    ID: 07048085.wav
    Length: 120
** Night raid on London, bombs fall, anti-aircraft fire A.R.P. warden's of plane - 1940 (500M)                                                                                :Air Raids:
    ID: 07048084.wav
    Length: 131
** Night raid on London, distant anti-aircraft fire, bomb falls, drone of plane - 1940 (500M)                                                                                :Air Raids:
    ID: 07048083.wav
    Length: 84
** Night raid on London, one bomb falls, close 1940 (500M)                                                                                :Air Raids:
    ID: 07048082.wav
    Length: 30
** Night raid on London, two bombs fall, close 1940 (500M)                                                                                :Air Raids:
    ID: 07048081.wav
    Length: 23
** Massed formations of German bombers fighters (World War II actuality rec. Kent/Sussex border) 1975 (500K)                                                                                :Battles:Air Battles:
    ID: 07048080.wav
    Length: 146
** Dive bomber attack with pom pom guns, bombs and machine guns - 1975 (500K)                                                                                :Battles:Air Battles:
    ID: 07048079.wav
    Length: 196
** Actuality of air battle, planes diving and zooming, gunfire (German film) - 1975 (500J)                                                                                :Battles:Air Battles:
    ID: 07048078.wav
    Length: 163
** London Central Mosque, Regents Park - congregation at Friday prayers - near end of prayers, with chanted responses from congregation                                                                                :Mosques:
    ID: 07048077.wav
    Length: 105
** London Central Mosque, Regents Park - Friday prayers in main mosque - from beginning of midday Friday prayers, with PA - some noise and bustle as worshippers come and go                                                                                :Mosques:
    ID: 07048076.wav
    Length: 249
** London Central Mosque, Regents Park - call to prayer (long version) for weekly midday Friday prayers, recorded outside in mosque forecourt - some traffic noise                                                                                :Mosques:
    ID: 07048075.wav
    Length: 293
** London Central Mosque, Regents Park - main mosque before prayers - expectant hush, with some sounds of coughing etc, as people settle down                                                                                :Mosques:
    ID: 07048074.wav
    Length: 219
** London Central Mosque, Regents Park - ladies prayer area with general muted chatter and sounds of women praying                                                                                :Mosques:
    ID: 07048073.wav
    Length: 241
** London Central Mosque, Regents Park - mosque entrance hall before main Friday prayers - busy and echoey, with speech and footsteps                                                                                :Entrance Halls:
    ID: 07048072.wav
    Length: 253
** Singing in temple leader on PA, congregation singing, clapping and playing bells                                                                                :Hinduism:
    ID: 07048071.wav
    Length: 193
** Temple dining room general atmosphere with chat (Hindi and English) and kitchen noise - good general-purpose background                                                                                :Dining Rooms:
    ID: 07048070.wav
    Length: 252
** Evening prayers, end of ceremony - animated chanting 4'08" chanting stops, bells and then leader solo (some noise from child)                                                                                :Bells:Buddhism:
    ID: 07048069.wav
    Length: 356
** Nichiren Shoshu - evening prayers, beginning of ceremony - chanting, with noise of beads and bells 2'09" chanting pauses, bells 2'43" chanting starts again in different rhythm 3'59" bells                                                                                :Bells:Buddhism:
    ID: 07048068.wav
    Length: 268
** Atmosphere before service, Westminster Cathedral, bell tolls and congregation gather for service                                                                                :Bells:Cathedrals:
    ID: 07048067.wav
    Length: 241
** Choir passes at beginning of service, Westminster Abbey - just footsteps, no music and fairly quiet congregation                                                                                :Abbeys:
    ID: 07048066.wav
    Length: 41
** Congregation leaving after Sunday service, Westminster Abbey - busy with footsteps and speech                                                                                :Abbeys:
    ID: 07048065.wav
    Length: 280
** Cloisters, Westminster Abbey.  Busy, with footsteps and speech from tourists and children                                                                                :Abbeys:
    ID: 07048064.wav
    Length: 273
** Congregation going to communion, Lichfield Cathedral - footsteps, shuffling, coughing and occasional whispered speech                                                                                :Atmospheres:Lichfield Cathedral:
    ID: 07048063.wav
    Length: 233
** Bells for Easter Sunday service, Lichfield Cathedral - some passing footsteps                                                                                :Bells:Cathedrals:
    ID: 07048062.wav
    Length: 188
** Conning tower rising (reprocessed)                                                                                :Submarines:
    ID: 07048061.wav
    Length: 27
** Surfacing orders (reprocessed)                                                                                :Submarines:
    ID: 07048060.wav
    Length: 37
** Crew snoring (reprocessed)                                                                                :Snores:
    ID: 07048059.wav
    Length: 12
** Orders 'all ready for movements on the port side' (reprocessed)                                                                                :Submarines:
    ID: 07048058.wav
    Length: 15
** Orders 'out pipes' (reprocessed)                                                                                :Submarines:
    ID: 07048057.wav
    Length: 11
** Submerging (reprocessed)                                                                                :Submarines:
    ID: 07048056.wav
    Length: 48
** Dynamos (reprocessed)                                                                                :Submarines:
    ID: 07048055.wav
    Length: 130
** Minesweeper - sweep out - donkey engine, paravane hits water, hawser (reprocessed)                                                                                :Warships:
    ID: 07048054.wav
    Length: 45
** Minesweeper - sweep out - donkey engine, paravane hits water, hawser (reprocessed)                                                                                :Warships:
    ID: 07048053.wav
    Length: 43
** Minesweeper - sweep in - donkey engine, hawser, paravane made fast on deck (reprocessed)                                                                                :Warships:
    ID: 07048052.wav
    Length: 45
** Minesweeper - sweep in - donkey engine, hawser, paravane made fast on deck (reprocessed)                                                                                :Warships:
    ID: 07048051.wav
    Length: 40
** Hoisting and hosing anchor - occasional voices (reprocessed)                                                                                :Boats:Cruisers:
    ID: 07048050.wav
    Length: 131
** Shortening cable (reprocessed)                                                                                :Boats:Cruisers:
    ID: 07048049.wav
    Length: 43
** Dropping anchor without speech (reprocessed)                                                                                :Boats:Cruisers:
    ID: 07048048.wav
    Length: 78
** Light cruiser - dropping anchor with speech (reprocessed)                                                                                :Boats:Cruisers:
    ID: 07048047.wav
    Length: 88
** Weighing anchor - occasional voices and orders (reprocessed)                                                                                :Boats:Cruisers:
    ID: 07048046.wav
    Length: 115
** Letting go anchor - voices in background (reprocessed)                                                                                :Boats:Cruisers:
    ID: 07048045.wav
    Length: 87
** Letting go anchor (reprocessed)                                                                                :Boats:Cruisers:
    ID: 07048044.wav
    Length: 17
** Siren (reprocessed)                                                                                :Boats:Battleships:
    ID: 07048043.wav
    Length: 23
** Corvette (reprocessed) - no timing                                                                                :Boats:Battleships:
    ID: 07048042.wav
    Length: 23
** Gyro-compass room - occasional voices in background (reprocessed)                                                                                :Boats:Battleships:
    ID: 07048041.wav
    Length: 166
** No.1 low power room - occasional voices in background (reprocessed)                                                                                :Boats:Battleships:
    ID: 07048040.wav
    Length: 168
** 5.25 conveyor space (reprocessed)                                                                                :Boats:Battleships:
    ID: 07048039.wav
    Length: 91
** Port diesel dynamo room (reprocessed)                                                                                :Boats:Battleships:
    ID: 07048038.wav
    Length: 179
** Battleship - Y-turret gun house - 14'' gun - shouting, orders, movement, metallic clatter, gun fired (reprocessed)                                                                                :Boats:Battleships:
    ID: 07048037.wav
    Length: 179
** Lowering boat,orders and voices (reprocessed)                                                                                :Boats:Trawlers:
    ID: 07048036.wav
    Length: 112
** 2 men running on deck (reprocessed)                                                                                :Boats:Trawlers:
    ID: 07048035.wav
    Length: 57
** Communication whistle (several versions - longer blasts) (reprocessed)                                                                                :Whistles:
    ID: 07048034.wav
    Length: 9
** Armed trawler, communication whistle (several versions) (reprocessed)                                                                                :Whistles:
    ID: 07048033.wav
    Length: 14
** Light spasmodic bangs (smoke bombs) - suitable for old type rifle fire (reprocessed)                                                                                :Explosions:
    ID: 07048032.wav
    Length: 34
** Small explosions with reverberation (reprocessed)                                                                                :Explosions:
    ID: 07048031.wav
    Length: 114
** Heavy explosions (some distortion-German wartime rec.) (reprocessed)                                                                                :Explosions:
    ID: 07048030.wav
    Length: 88
** Anti aircraft fire (reprocessed)                                                                                :Guns:Anti Aircraft:
    ID: 07048029.wav
    Length: 248
** Complete range finding and firing drill (close to predictor) - Nov.1942  - ATS plotting positions - Nov.1942 (reprocessed)                                                                                :Guns:Anti Aircraft:
    ID: 07048028.wav
    Length: 56
** Complete range finding and firing drill (close to predictor) - Nov.1942 (reprocessed)                                                                                :Guns:Anti Aircraft:
    ID: 07048027.wav
    Length: 68
** Complete range finding and firing drill - Nov.1942 (reprocessed)                                                                                :Anti Aircraft Batteries:British:
    ID: 07048026.wav
    Length: 105
** Orders to sound off guns (close to guns) mid-distance orders to 'fire' - close guns firing with distant gunfire in background (reprocessed)                                                                                :Anti Aircraft Batteries:British:
    ID: 07048025.wav
    Length: 170
** Landing at night at RAF Station - radio telephone, flare path lit, directions to aircraft, chance light, aircraft landing - Dec.1940 (reprocessed)                                                                                :RAF Stations:
    ID: 07048024.wav
    Length: 212
** Crew briefing by meteorological officer - anti-cyclone - Dec.1940 (reprocessed)                                                                                :RAF Stations:
    ID: 07048023.wav
    Length: 29
** Crew briefing by wireless officer -  Dec.1940 (reprocessed)                                                                                :RAF Stations:
    ID: 07048022.wav
    Length: 22
** Crew briefing by station intelligence officer - size of 'Tirpiz', torpedo boats; Bremerhaven, two liners 'Bremen' & 'Europa' - Dec.1940 (reprocessed)                                                                                :RAF Stations:
    ID: 07048021.wav
    Length: 39
** Crew briefing - giving objectives which will include bombing 'Tirpiz' in Bremerhaven, also Ruhr blast-furnace, steel works & marshalling yard in Dusseldorf - Dec.1940 (reprocessed)                                                                                :RAF Stations:
    ID: 07048020.wav
    Length: 141
** RAF Station - Bomber Command - crew disembarking on return from raid - crew talking 'absolutely wizard' 'good show' - Dec.1940 (reprocessed)                                                                                :RAF Stations:
    ID: 07048019.wav
    Length: 50
** Wildcat followed by Hellcat diving over ship (reprocessed)                                                                                :Fighters:
    ID: 07048018.wav
    Length: 38
** Dives (reprocessed)                                                                                :Fighters:
    ID: 07048017.wav
    Length: 22
** Takes off from ship (reprocessed)                                                                                :Fighters:
    ID: 07048016.wav
    Length: 19
** Takes off from ship (reprocessed)                                                                                :Fighters:
    ID: 07048015.wav
    Length: 23
** In flight (passing overhead)                                                                                :Fighters:
    ID: 07048014.wav
    Length: 58
** Warms up and takes off from ship (reprocessed)                                                                                :Fighters:
    ID: 07048013.wav
    Length: 37
** Warming up (reprocessed)                                                                                :Fighters:
    ID: 07048012.wav
    Length: 27
** Lands on ship - Swordfish waved away - occasional voices (reprocessed)                                                                                :Aircraft:Swordfish:
    ID: 07048011.wav
    Length: 62
** Lands on ship and ticks over - occasional voices (reprocessed)                                                                                :Fighters:
    ID: 07048010.wav
    Length: 48
** Wildcat (Carrier Fighter, Fleet Air Arm) (USA) lands on ship and taxis forward (reprocessed)                                                                                :Fighters:
    ID: 07048009.wav
    Length: 30
** Whitley (Twin Engined Bomber) (GB) approaching and switch off (reprocessed)                                                                                :Bombers:
    ID: 07048008.wav
    Length: 73
** Wellington (Twin Engined Bomber) (GB) landing, occasional voices in background - Dec.1944 (reprocessed)                                                                                :Aircraft:Wellington:
    ID: 07048007.wav
    Length: 73
** Typhoon (Fighter) (GB) taking off (reprocessed)                                                                                :Fighters:
    ID: 07048006.wav
    Length: 35
** Wing taking off - March 1945 (reprocessed)                                                                                :Aircraft:Thunderbolt:
    ID: 07048005.wav
    Length: 18
** Diving - March 1945 (reprocessed)                                                                                :Aircraft:Thunderbolt:
    ID: 07048004.wav
    Length: 28
** Diving - March 1945 (reprocessed)                                                                                :Aircraft:Thunderbolt:
    ID: 07048003.wav
    Length: 21
** Passing over low, 500ft (reprocessed)                                                                                :Aircraft:Thunderbolt:
    ID: 07048002.wav
    Length: 17
** Thunderbolt B47 (Single Engined Fighter-Bomber) (USA) taking off - March 1945 (reprocessed)                                                                                :Aircraft:Thunderbolt:
    ID: 07048001.wav
    Length: 19
** London Underground Train, interior, District Line train starts into constant run, stops at several stations, with indistinct station announcement first stop.                                                                                ::
    ID: 07047222.wav
    Length: 270
** London Underground Train, interior, Central Line train starts into constant run, slows & stops, doors (no voices).                                                                                ::
    ID: 07047221.wav
    Length: 113
** London Underground, squeaking escalator in station.                                                                                ::
    ID: 07047220.wav
    Length: 82
** London Underground, atmosphere on escalator in station.                                                                                ::
    ID: 07047219.wav
    Length: 75
** London Underground, Central Line train sliding door closes.                                                                                ::
    ID: 07047218.wav
    Length: 4
** London Underground, Central Line train sliding door opens.                                                                                ::
    ID: 07047217.wav
    Length: 3
** London Underground, District Line train sliding door closes.                                                                                ::
    ID: 07047216.wav
    Length: 5
** London Underground, District Line train sliding door opens.                                                                                ::
    ID: 07047215.wav
    Length: 4
** London Underground Train, atmosphere on board stationary train.                                                                                ::
    ID: 07047214.wav
    Length: 56
** London Underground, daytime platform atmosphere, footsteps & fire buckets filled.                                                                                ::
    ID: 07047213.wav
    Length: 46
** London Underground, quiet late-night platform atmosphere (no voices or footsteps).                                                                                ::
    ID: 07047212.wav
    Length: 64
** London Underground, Central Line train arrives with indistinct platform announcements, doors, depart. (Exterior acoustic.)                                                                                ::
    ID: 07047211.wav
    Length: 95
** London Underground, Bakerloo Line train arrives, "Mind the gap", departs. (Exterior acoustic.)                                                                                ::
    ID: 07047210.wav
    Length: 85
** London Underground, Central line train arrives, doors, depart. (Exterior acoustic.)                                                                                ::
    ID: 07047209.wav
    Length: 71
** Diesel Heavy Goods Train passes under bridge left to right with hooter.                                                                                ::
    ID: 07047208.wav
    Length: 90
** Diesel commuter train passes under bridge left to right.                                                                                ::
    ID: 07047207.wav
    Length: 39
** Diesel Goods Train passes under bridge right to left, followed by Inter City 125.                                                                                ::
    ID: 07047206.wav
    Length: 114
** Single Diesel Locomotive passes under bridge left to right.                                                                                ::
    ID: 07047205.wav
    Length: 43
** Diesel Goods Train emerges from tunnel.                                                                                ::
    ID: 07047204.wav
    Length: 47
** Single Diesel Locomotive, pass left to right with rail noise.                                                                                ::
    ID: 07047203.wav
    Length: 47
** Diesel Express Train, high speed pass left to right.                                                                                ::
    ID: 07047202.wav
    Length: 50
** Inter City 125, high speed pass right to left.                                                                                ::
    ID: 07047201.wav
    Length: 32
** Inter City 125, high speed pass left to right.                                                                                ::
    ID: 07047200.wav
    Length: 40
** Diesel Railcar, high speed pass right to left.                                                                                ::
    ID: 07047199.wav
    Length: 39
** Diesel Railcar, slow pass left to right.                                                                                ::
    ID: 07047198.wav
    Length: 70
** Electric Commuter Train, high speed pass right to left.                                                                                ::
    ID: 07047197.wav
    Length: 42
** Diesel Railcar Driver's Cab, start into constant run with noticeable gear changes, signaling bell & buzzer, slows & stops with airbrakes applied, door.                                                                                ::
    ID: 07047196.wav
    Length: 262
** Diesel Train, interior, move from toilets to carriage with opening & closing doors.                                                                                ::
    ID: 07047195.wav
    Length: 37
** Diesel Train, toilet flush.                                                                                ::
    ID: 07047194.wav
    Length: 9
** Diesel Train, interior, atmosphere in toilet compartment.                                                                                ::
    ID: 07047193.wav
    Length: 76
** Diesel Train, interior, station atmosphere from train with indistinct P.A., starts into constant run, slows & stops.                                                                                ::
    ID: 07047192.wav
    Length: 347
** Diesel Commuter Railcar, interior, starts into constant run on welded track, with voices on welded track, several passing trains, slows & stops, doors.                                                                                ::
    ID: 07047191.wav
    Length: 347
** Inter City 125, passes at speed. (Interior acoustic.)                                                                                ::
    ID: 07047190.wav
    Length: 7
** Diesel Train, sliding window closed.                                                                                ::
    ID: 07047189.wav
    Length: 1
** Diesel Train, sliding window opened.                                                                                ::
    ID: 07047188.wav
    Length: 1
** Diesel Train, door closed.                                                                                ::
    ID: 07047187.wav
    Length: 1
** Diesel Train, interior, station atmosphere as heard from train, distant voices only.                                                                                ::
    ID: 07047186.wav
    Length: 74
** Diesel Commuter Railcar, interior, train boarded, with doors & voices.                                                                                ::
    ID: 07047185.wav
    Length: 23
** Diesel Train hooter (starts mid sequence).                                                                                ::
    ID: 07047184.wav
    Length: 2
** Diesel Train two blasts on hooter.                                                                                ::
    ID: 07047183.wav
    Length: 2
** Diesel Train, one blast on hooter.                                                                                ::
    ID: 07047182.wav
    Length: 1
** Diesel Train shunting trucks in goods depot.                                                                                ::
    ID: 07047181.wav
    Length: 150
** Inter City 125, exterior, arrives at station, atmosphere as train is boarded, train departs.                                                                                ::
    ID: 07047180.wav
    Length: 137
** Diesel Mainline Express Train, exterior, arrives at station, doors as train is boarded, guard's whistle, train departs.                                                                                ::
    ID: 07047179.wav
    Length: 165
** Busy Mainline Station, atmosphere before arrival of train.                                                                                ::
    ID: 07047178.wav
    Length: 86
** Diesel Train, local railcar engine ticking over, with distant station activity.                                                                                ::
    ID: 07047177.wav
    Length: 72
** Diesel Train, exterior, mainline express engine ticking over, with distant station activity.                                                                                ::
    ID: 07047176.wav
    Length: 156
** Electric Train, exterior, arrives at local station (left to center), doors.                                                                                ::
    ID: 07047175.wav
    Length: 36
** Electric Train, exterior, arrives at local station, doors, departs right to left.                                                                                ::
    ID: 07047174.wav
    Length: 89
** Electric Train, interior, starts into constant run on welded track, slows & stops, doors. (Corridor acoustic.)                                                                                ::
    ID: 07047173.wav
    Length: 199
** Electric Train, interior, starts into constant run on mainly welded track, slows & stops, doors. (Compartment acoustic.)                                                                                ::
    ID: 07047172.wav
    Length: 198
** Electric Train, interior, starts into constant run on unwelded track, slows & stops, doors. (Compartment acoustic.)                                                                                ::
    ID: 07047171.wav
    Length: 130
** Electric Train, doors opened & closed as train is boarded. (Some birdsong in background.)                                                                                ::
    ID: 07047170.wav
    Length: 19
** Electric Train, carriage door slammed.                                                                                ::
    ID: 07047169.wav
    Length: 1
** Electric Train, carriage door slammed.                                                                                ::
    ID: 07047168.wav
    Length: 1
** Electric Train, interior, sliding door closes.                                                                                ::
    ID: 07047167.wav
    Length: 1
** Electric Train, interior, sliding door opens.                                                                                ::
    ID: 07047166.wav
    Length: 2
** Electric Train, compressor running.                                                                                ::
    ID: 07047165.wav
    Length: 41
** Electric Train, electronic starting bleeps. (Single person operated train, no guard.)                                                                                ::
    ID: 07047164.wav
    Length: 5
** A tornado. (Spot effect.)                                                                                ::
    ID: 07047163.wav
    Length: 135
** Antartic whiteout.                                                                                ::
    ID: 07047162.wav
    Length: 285
** Howling wind.                                                                                ::
    ID: 07047161.wav
    Length: 338
** A blizzard.                                                                                ::
    ID: 07047160.wav
    Length: 154
** High pitched wind.                                                                                ::
    ID: 07047159.wav
    Length: 209
** Polar wind.                                                                                ::
    ID: 07047158.wav
    Length: 335
** Low pitched wind.                                                                                ::
    ID: 07047157.wav
    Length: 336
** Wind whistling through crack.                                                                                ::
    ID: 07047156.wav
    Length: 216
** Gale through boat rigging.                                                                                ::
    ID: 07047155.wav
    Length: 138
** Gusty wind through wires.                                                                                ::
    ID: 07047154.wav
    Length: 160
** Blustery wind through fence.                                                                                ::
    ID: 07047153.wav
    Length: 174
** Tree creaking in strong wind.                                                                                ::
    ID: 07047152.wav
    Length: 229
** Gale heard from inside house, with rattling windows.                                                                                ::
    ID: 07047151.wav
    Length: 324
** Gusty wind in bushes.                                                                                ::
    ID: 07047150.wav
    Length: 275
** Strong wind in trees.                                                                                ::
    ID: 07047149.wav
    Length: 335
** Flag flapping in breeze with birdsong.                                                                                ::
    ID: 07047148.wav
    Length: 245
** Steady night breeze.                                                                                ::
    ID: 07047147.wav
    Length: 259
** Road Maintenance, repairs with tar-laying machine, grit laid, diesel rollers prepare surface. (Occasional distant speech.)                                                                                ::
    ID: 07047146.wav
    Length: 132
** Road Maintenance, pneumatic drill compressor, constant run.                                                                                ::
    ID: 07047145.wav
    Length: 92
** Road Maintenance, pneumatic drill, constant run.                                                                                ::
    ID: 07047144.wav
    Length: 63
** Refuse Collection, unloading dust-carts at tip. (Occasional distant speech.)                                                                                ::
    ID: 07047143.wav
    Length: 93
** Refuse Collection, loading crusher. (Close perspective, occasional distant speech.)                                                                                ::
    ID: 07047142.wav
    Length: 94
** Refuse Collection, dust-cart arrives, bins emptied, departs. (Occasional distant speech.)                                                                                ::
    ID: 07047141.wav
    Length: 96
** Water Mill, water driver hoist (chain noises, bangs & creaks).                                                                                ::
    ID: 07047140.wav
    Length: 89
** Water Mill, electric wheat cracking machine.                                                                                ::
    ID: 07047139.wav
    Length: 43
** Water Mill, shaker separates grain from wheat.                                                                                ::
    ID: 07047138.wav
    Length: 73
** Water Mill, hopper feeding wheat to stones.                                                                                ::
    ID: 07047137.wav
    Length: 13
** Water Mill, sluice opened, water runs on to wheel then stops.                                                                                ::
    ID: 07047136.wav
    Length: 88
** Water Mill, water runs down mill race, on to wheel & stops.                                                                                ::
    ID: 07047135.wav
    Length: 128
** Water Mill, grinding wheat, start, run & stop.                                                                                ::
    ID: 07047134.wav
    Length: 143
** Water Mill, wheatstones stop.                                                                                ::
    ID: 07047133.wav
    Length: 16
** Water Mill, wheatstones start & grind corn.                                                                                ::
    ID: 07047132.wav
    Length: 88
** Vickers Viscount, interior, constant flight, descent, landing & passengers disembark. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047131.wav
    Length: 211
** Vickers Viscount, interior, pre-landing announcement. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047130.wav
    Length: 49
** Vickers Viscount, interior, constant flight. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047129.wav
    Length: 385
** Vickers Viscount, interior, taxiing & preflight announcement. (Short/medium-range airliner.)                                                                                ::
    ID: 07047128.wav
    Length: 28
** Vickers Viscount, interior, in-flight prelanding announcement. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047127.wav
    Length: 50
** Vickers Viscount, interior, in-flight announcement by captain. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047126.wav
    Length: 55
** Vickers Viscount, interior, in-flight announcement. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047125.wav
    Length: 36
** Vickers Viscount, interior, taxiing, preflight announcement (at 0m45s), take off (at 2m35). (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047124.wav
    Length: 262
** Vickers Viscount, exterior, passing over. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047123.wav
    Length: 61
** Vickers Viscount, exterior, passing over. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047122.wav
    Length: 58
** Vickers Viscount, exterior, passing over low. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047121.wav
    Length: 48
** Vickers Viscount, exterior, landing. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047120.wav
    Length: 66
** Vickers Viscount, exterior, landing & taxiing. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047119.wav
    Length: 91
** Vickers Viscount, exterior, landing. (Short/medium-range airliner, 4 piston-engines.)                                                                                ::
    ID: 07047118.wav
    Length: 65
** De Havilland Vemon, pass over.                                                                                ::
    ID: 07047117.wav
    Length: 43
** De Havilland Vampire, aircraft land in succession.                                                                                ::
    ID: 07047116.wav
    Length: 97
** De Havilland Vampire, aircraft take off in succession.                                                                                ::
    ID: 07047115.wav
    Length: 116
** Massed aircraft flypast.                                                                                ::
    ID: 07047114.wav
    Length: 62
** Gloster Meteor, four aircraft pass over into slow roll.                                                                                ::
    ID: 07047113.wav
    Length: 39
** Aircraft Standard Beam Approach, complete run with outer & inner Marker beacons. (Recorded on aircraft.)                                                                                ::
    ID: 07047112.wav
    Length: 299
** Aircraft Standard Beam Approach, complete run with outer & inner Marker beacons. (Recorded on aircraft.)                                                                                ::
    ID: 07047111.wav
    Length: 286
** Bristol Britannia on-board pre-flight announcement.                                                                                ::
    ID: 07047110.wav
    Length: 53
** On-board London Airport arrival announcement.                                                                                ::
    ID: 07047109.wav
    Length: 68
** On-board Rangoon Airport transit announcement.                                                                                ::
    ID: 07047108.wav
    Length: 61
** On-board BOAC post-take off announcement (suitable for use for any long-distance BOAC plane).                                                                                ::
    ID: 07047107.wav
    Length: 36
** Pre-flight announcement over aircraft P.A. system by stewardess (on board De Havilland Comet).                                                                                ::
    ID: 07047106.wav
    Length: 70
** Military Aerodrome, De Havilland Vampires running up, Gloster Meteor take off (at 2m15s).                                                                                ::
    ID: 07047105.wav
    Length: 347
** De Havilland Vampire, interior, engine running, take off, climb, levelling out. (Single jet-engined fighter plane.)                                                                                ::
    ID: 07047104.wav
    Length: 223
** De Havilland Vampire, interior, start engine, run-up & taxi. (Single jet-engined fighter plane.)                                                                                ::
    ID: 07047103.wav
    Length: 207
** De Havilland Vampire, exterior, two planes taxiing. (Single jet-engined fighter plane.)                                                                                ::
    ID: 07047102.wav
    Length: 113
** De Havilland Vampire, exterior, approach & pass. (Single jet-engined fighter plane.)                                                                                ::
    ID: 07047101.wav
    Length: 60
** De Havilland Vampire, interior, descent, touchdown & stop. (Single jet-engined fighter plane.)                                                                                ::
    ID: 07047100.wav
    Length: 209
** De Havilland Vampire, interior, constant flight into descent. (Single jet-engined fighter plane.)                                                                                ::
    ID: 07047099.wav
    Length: 245
** De Havilland Comet DH 106, exterior, landing. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07047098.wav
    Length: 22
** De Havilland Comet DH 106, exterior, pass over. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07047097.wav
    Length: 70
** De Havilland Comet DH 106, exterior, take off. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07047096.wav
    Length: 78
** De Havilland Comet III, exterior, landing. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07047095.wav
    Length: 36
** De Havilland Comet IV, exterior, taxiing. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07047094.wav
    Length: 76
** De Havilland Comet IV, exterior, landing. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07047093.wav
    Length: 68
** Audience in hall, applause.                                                                                ::
    ID: 07047092.wav
    Length: 23
** Audience in hall, applause.                                                                                ::
    ID: 07047091.wav
    Length: 17
** Audience in hall, cheers and applause.                                                                                ::
    ID: 07047090.wav
    Length: 13
** Audience in hall, groans.                                                                                ::
    ID: 07047089.wav
    Length: 7
** Audience in hall, continuous derision.                                                                                ::
    ID: 07047088.wav
    Length: 70
** Audience in hall, two bursts of derisive cries.                                                                                ::
    ID: 07047087.wav
    Length: 10
** Audience in hall, continuous mixed laughter.                                                                                ::
    ID: 07047086.wav
    Length: 211
** Audience in hall, mixed chatter, fairly quiet. (30 people)                                                                                ::
    ID: 07047085.wav
    Length: 173
** General applause with faint cheers.                                                                                ::
    ID: 07047084.wav
    Length: 14
** General applause with faint cheers.                                                                                ::
    ID: 07047083.wav
    Length: 10
** General applause at concert.                                                                                ::
    ID: 07047082.wav
    Length: 21
** General applause at concert.                                                                                ::
    ID: 07047081.wav
    Length: 20
** General applause at concert.                                                                                ::
    ID: 07047080.wav
    Length: 14
** General applause.                                                                                ::
    ID: 07047079.wav
    Length: 15
** Slight applause.                                                                                ::
    ID: 07047078.wav
    Length: 11
** Slight applause.                                                                                ::
    ID: 07047077.wav
    Length: 8
** Applause at meeting, with reaction.                                                                                ::
    ID: 07047076.wav
    Length: 16
** Applause at meeting, with reaction.                                                                                ::
    ID: 07047075.wav
    Length: 15
** Applause at meeting, with reaction.                                                                                ::
    ID: 07047074.wav
    Length: 23
** Applause at meeting, with thumping.                                                                                ::
    ID: 07047073.wav
    Length: 14
** Dance Hall atmosphere during interval, with odd notes on piano.                                                                                ::
    ID: 07047072.wav
    Length: 392
** Dance Hall applause.                                                                                ::
    ID: 07047071.wav
    Length: 41
** Dance Hall applause.                                                                                ::
    ID: 07047070.wav
    Length: 10
** Dance Hall applause.                                                                                ::
    ID: 07047069.wav
    Length: 11
** Dance Hall applause.                                                                                ::
    ID: 07047068.wav
    Length: 10
** Dance Hall applause.                                                                                ::
    ID: 07047067.wav
    Length: 14
** Dance Hall atmosphere, "Thanks" & applause into chatter.                                                                                ::
    ID: 07047066.wav
    Length: 20
** Male crowd, exterior, rowdy crowd of male teenagers.                                                                                ::
    ID: 07047065.wav
    Length: 277
** Male crowd, interior, ,rowdy crowd hall.                                                                                ::
    ID: 07047064.wav
    Length: 177
** Male crowd, interior, derisive with whistles. (200 men.)                                                                                ::
    ID: 07047063.wav
    Length: 32
** Male crowd, interior, rowdy with applause & booing. (200 men.)                                                                                ::
    ID: 07047062.wav
    Length: 56
** Applause at concert, sustained final applause. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047061.wav
    Length: 244
** Applause at concert after musical item. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047060.wav
    Length: 124
** Applause at concert after musical item. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047059.wav
    Length: 63
** General applause at concert. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047058.wav
    Length: 31
** Applause at concert for Soloist. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047057.wav
    Length: 20
** Applause at concert for Conductor. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047056.wav
    Length: 22
** Applause at concert for Orchestra Leader. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047055.wav
    Length: 15
** Applause at concert for Orchestra Leader. (Recorded at the Royal Albert Hall, London.)                                                                                ::
    ID: 07047054.wav
    Length: 21
** Teenage crowd, stamping, booing & whistling crowd in a stadium.                                                                                ::
    ID: 07047053.wav
    Length: 116
** Teenage crowd, girls scream & applaud in a theatre.                                                                                ::
    ID: 07047052.wav
    Length: 64
** Teenage crowd, girls screaming in a theatre.                                                                                ::
    ID: 07047051.wav
    Length: 145
** Teenage crowd, girls screaming in street, with traffic & motor horns.                                                                                ::
    ID: 07047050.wav
    Length: 100
** Teenage crowd, girls screaming in street, with much movement & general excitement.                                                                                ::
    ID: 07047049.wav
    Length: 233
** Applause at concert, audience of 500 people.                                                                                ::
    ID: 07047048.wav
    Length: 45
** Applause at concert, audience of 500 people.                                                                                ::
    ID: 07047047.wav
    Length: 34
** Applause at concert, audience of 250 people.                                                                                ::
    ID: 07047046.wav
    Length: 20
** Applause at concert, audience of 250 people.                                                                                ::
    ID: 07047045.wav
    Length: 13
** Applause at concert, audience of 50 people.                                                                                ::
    ID: 07047044.wav
    Length: 27
** Applause at concert, audience of 50 people.                                                                                ::
    ID: 07047043.wav
    Length: 15
** Applause at concert, sustained final applause.                                                                                ::
    ID: 07047042.wav
    Length: 213
** Applause at concert after musical item.                                                                                ::
    ID: 07047041.wav
    Length: 86
** Applause at concert for Conductor.                                                                                ::
    ID: 07047040.wav
    Length: 17
** Applause at concert for Orchestra Leader.                                                                                ::
    ID: 07047039.wav
    Length: 18
** Applause, crowd of 50 people.                                                                                ::
    ID: 07047038.wav
    Length: 12
** Applause, crowd of 50 people.                                                                                ::
    ID: 07047037.wav
    Length: 12
** Applause, crowd of 50 people.                                                                                ::
    ID: 07047036.wav
    Length: 14
** Applause, crowd of 30 people.                                                                                ::
    ID: 07047035.wav
    Length: 17
** Applause, crowd of 30 people.                                                                                ::
    ID: 07047034.wav
    Length: 11
** Applause, crowd of 30 people.                                                                                ::
    ID: 07047033.wav
    Length: 12
** Applause, small group of people.                                                                                ::
    ID: 07047032.wav
    Length: 23
** Applause, small group of people.                                                                                ::
    ID: 07047031.wav
    Length: 12
** Applause, small group of people.                                                                                ::
    ID: 07047030.wav
    Length: 9
** Applause, small group of people.                                                                                ::
    ID: 07047029.wav
    Length: 15
** Applause, small group of people.                                                                                ::
    ID: 07047028.wav
    Length: 18
** Applause, small group of people.                                                                                ::
    ID: 07047027.wav
    Length: 15
** National Daily Newspaper Despatch Department, general atmosphere.                                                                                ::
    ID: 07047026.wav
    Length: 216
** National Daily Newspaper Compositors' Area, general atmosphere.                                                                                ::
    ID: 07047025.wav
    Length: 214
** National Daily Newspaper Copytype Department, general atmosphere.                                                                                ::
    ID: 07047024.wav
    Length: 214
** National Daily Newspaper Linotype Department, general atmosphere.                                                                                ::
    ID: 07047023.wav
    Length: 214
** National Daily Newspaper Foundry Casting Room.                                                                                ::
    ID: 07047022.wav
    Length: 454
** National Daily Newspaper Foundry Bench Room.                                                                                ::
    ID: 07047021.wav
    Length: 141
** National Daily Newspaper Foundry, moulding of page under 350 ton press.                                                                                ::
    ID: 07047020.wav
    Length: 268
** National Daily Newspaper Printing Press, chatter, hooter at 0m40s, presses start up & gather speed.                                                                                ::
    ID: 07047019.wav
    Length: 455
** National Daily Newspaper Reference Library, atmosphere with staff extracting & sorting newspaper cuttings.                                                                                ::
    ID: 07047018.wav
    Length: 245
** National Daily Newspaper Typesetting Area, general atmosphere.                                                                                ::
    ID: 07047017.wav
    Length: 182
** National Daily Newspaper Block Department, proving press operating.                                                                                ::
    ID: 07047016.wav
    Length: 100
** National Daily Newspaper Block Department, grouting machine operating.                                                                                ::
    ID: 07047015.wav
    Length: 93
** National Daily Newspaper Block Department, beveller operating.                                                                                ::
    ID: 07047014.wav
    Length: 59
** National Daily Newspaper Block Department, plate cutting saw operating.                                                                                ::
    ID: 07047013.wav
    Length: 56
** National Daily Newspaper Block Department, powder etching machine operating.                                                                                ::
    ID: 07047012.wav
    Length: 42
** National Daily Newspaper Block Department, acid machine operating.                                                                                ::
    ID: 07047011.wav
    Length: 135
** National Daily Newspaper Block Department, coating machine operating.                                                                                ::
    ID: 07047010.wav
    Length: 107
** National Daily Newspaper Block Department, printing with a Devon Frame.                                                                                ::
    ID: 07047009.wav
    Length: 63
** National Daily Newspaper Artistic Department, retouching picture with air brush.                                                                                ::
    ID: 07047008.wav
    Length: 76
** National Daily Newspaper Picture Transmitting & Receiving Room, general atmosphere with instructions over P.A. system.                                                                                ::
    ID: 07047007.wav
    Length: 429
** National Daily Newspaper Picture Transmitting & Receiving Room, picture transmission & reception.                                                                                ::
    ID: 07047006.wav
    Length: 183
** National Daily Newspaper Picture Transmitting & Receiving Room, picture transmission.                                                                                ::
    ID: 07047005.wav
    Length: 107
** National Daily Newspaper Picture Transmitting & Receiving Room, picture transmission.                                                                                ::
    ID: 07047004.wav
    Length: 131
** National Daily Newspaper Tape Room, atmosphere with indistinct speech.                                                                                ::
    ID: 07047003.wav
    Length: 216
** National Daily Newspaper Creed Teleprinter Room, general atmosphere.                                                                                ::
    ID: 07047002.wav
    Length: 213
** National Daily Newspaper Newsroom, general atmosphere with indistinct speech & occasional typing.                                                                                ::
    ID: 07047001.wav
    Length: 428
** Goosestep marching, with orders in German - 1982 (500T)                                                                                ::
    ID: 07046200.wav
    Length: 17
** Goosestep marching, with orders in German - 1982 (500T)                                                                                ::
    ID: 07046199.wav
    Length: 35
** V2 Rocket launching - 1975 (500B)                                                                                ::
    ID: 07046198.wav
    Length: 43
** V2 Rocket double explosion - 1975 (500B)                                                                                ::
    ID: 07046197.wav
    Length: 16
** V2 Rocket explosion, rumble - 1975 (500B)                                                                                ::
    ID: 07046196.wav
    Length: 18
** V2 Rocket double explosion - 1975 (500B)                                                                                ::
    ID: 07046195.wav
    Length: 14
** V2 Rocket double explosion - 1975 (500B)                                                                                ::
    ID: 07046194.wav
    Length: 13
** V2 Rocket explosion and rumble - 1975 (500B)                                                                                ::
    ID: 07046193.wav
    Length: 21
** V2 Rocket heavy rumble, taxi drives off (rec. Marble Arch) - 1975 (500B)                                                                                ::
    ID: 07046192.wav
    Length: 38
** V1 Flying Bomb (Doodle Bug) explosion - 1975 (500B)                                                                                ::
    ID: 07046191.wav
    Length: 8
** V1 Flying Bomb (Doodle Bug) passing over and anti aircraft fire - 1975 (500B)                                                                                ::
    ID: 07046190.wav
    Length: 64
** V1 Flying Bomb (Doodle Bug) approach, engine cuts out, explosion - 1975 (500A)                                                                                ::
    ID: 07046189.wav
    Length: 41
** V1 Flying Bomb (Doodle Bug) approach, engine cuts out, explosion - 1975 (500A)                                                                                ::
    ID: 07046188.wav
    Length: 40
** V1 Flying Bomb (Doodle Bug) seven approach in quick succession, engines cut out, explosion - 1975 (500A)                                                                                ::
    ID: 07046187.wav
    Length: 251
** Int. starting, running, shutting off - 1982 (500U)                                                                                ::
    ID: 07046186.wav
    Length: 97
** Int. starting, revving, ticking over, shutting off - 1982 (500U)                                                                                ::
    ID: 07046185.wav
    Length: 130
** Ext. starting, revving, ticking over, shutting off - 1982 (500U)                                                                                ::
    ID: 07046184.wav
    Length: 92
** Ext. passing - 1982 (500U)                                                                                ::
    ID: 07046183.wav
    Length: 39
** Starting, moving over rough country and stopping - 1982 (500U)                                                                                ::
    ID: 07046182.wav
    Length: 81
** Moving over rough country - 1982 (500U)                                                                                ::
    ID: 07046181.wav
    Length: 150
** Starting, revving, stopping - 1982 (500U)                                                                                ::
    ID: 07046180.wav
    Length: 55
** Tank procession with crowds cheering - 1982 (500U)                                                                                ::
    ID: 07046179.wav
    Length: 66
** Tank battle (World War 11 actuality) - 1975 (500S)                                                                                ::
    ID: 07046178.wav
    Length: 208
** Heavy constant barrage rec. during the Rhine Crossing - 1945 (600W)                                                                                ::
    ID: 07046177.wav
    Length: 137
** Heavy barrage, with tanks and flail tanks moving up rec. during attack on the Siegfried Line - 1945 (500W)                                                                                ::
    ID: 07046176.wav
    Length: 149
** Heavy barrage rec. during attack on the Siegreied Line, Reischwald Forest - 1945 (500W)                                                                                ::
    ID: 07046175.wav
    Length: 111
** Heavy barrage, occasional faint bagpipes rec. during attack on the Siegfried Line, 1945 (500W)                                                                                ::
    ID: 07046174.wav
    Length: 202
** British artillery (World War II actuality) - 1975 (500S)                                                                                ::
    ID: 07046173.wav
    Length: 160
** Artillery with machine gun fire - 1975 (500S)                                                                                ::
    ID: 07046172.wav
    Length: 178
** Enemy artillery (World War II actuality) - 1975 (500S)                                                                                ::
    ID: 07046171.wav
    Length: 176
** Enemy mortar fire from 400 yards - Nebelwerfer (6 barrelled mortar) from enemy lines - 1945 (500X)                                                                                ::
    ID: 07046170.wav
    Length: 58
** Enemy mortar fire from 400 yards - 1945 (500X)                                                                                ::
    ID: 07046169.wav
    Length: 98
** Machine gun and small arms fire, Bessa guns, enemy shells landing (some in canal) - 1945 (500X)                                                                                ::
    ID: 07046168.wav
    Length: 109
** Allied 3" mortars, burst of machine gunfire, rec. Netherlands - 1945 (500X)                                                                                ::
    ID: 07046167.wav
    Length: 47
** Street fighting, tanks, Priest self propelled guns, enemy shells landing - 1945 (500X)                                                                                ::
    ID: 07046166.wav
    Length: 106
** MG 42 (nickname Spandau) machine gun, Bren gun, small arms fire, Bofor gunfire - 1945 (500X)                                                                                ::
    ID: 07046165.wav
    Length: 142
** Barrage, with soft shells and whistles - 1945 (500Y)                                                                                ::
    ID: 07046164.wav
    Length: 85
** Enemy shells landing - 1945 (500Y)                                                                                ::
    ID: 07046163.wav
    Length: 85
** Enemy shell, mortar fire, MG 42 (nickname Spandau) machine gunfire in background - 1945 (500Y)                                                                                ::
    ID: 07046162.wav
    Length: 78
** Rifle and machine gunfire- 1945 (500Y)                                                                                ::
    ID: 07046161.wav
    Length: 110
** River Maas - heavy artillery and shell whines- 1945 (55Y)                                                                                ::
    ID: 07046160.wav
    Length: 60
** Battle of Arnhem infantry with 2" mortar, rifle, Bren and Tommy gunfire advance, 25 pounder barage- 1945 (500Y)                                                                                ::
    ID: 07046159.wav
    Length: 150
** Ship launch - bottle breaks, men hammer away at props, cheers as boat begins to move, hits water at 1'43, three cheers given, general atmosphere - 1985 (recorded at Cochrane's Shipyard, Selby) (2S23,reprocessed)                                                                                ::
    ID: 07046158.wav
    Length: 171
** Seagulls at rubbish tip - occasional background voices (technical note - for use at low level)                                                                                ::
    ID: 07046157.wav
    Length: 104
** Cliff top with seagulls circling overhead (20C,reprocessed)                                                                                ::
    ID: 07046156.wav
    Length: 210
** Seagulls fighting for food - close perspective gulls with background waves and distant boat engine (1S10,reprocessed)                                                                                ::
    ID: 07046155.wav
    Length: 207
** Petrol pump turned on, runs, turned off, with light rain and traffic in background - 1985 (4P1,reprocessed)                                                                                ::
    ID: 07046154.wav
    Length: 96
** Petrol pump turned on, runs, turned off - background traffic - 1985 (4P1, reprocessed)                                                                                ::
    ID: 07046153.wav
    Length: 70
** Exterior automated car wash - 1985 (4P1, reprocessed)                                                                                ::
    ID: 07046152.wav
    Length: 96
** Sheltered concourse with pumps operating and traffic noises - 1985 (4P1,reprocessed)                                                                                ::
    ID: 07046151.wav
    Length: 211
** Air pressure pump, background traffic - 1985 (4P1,reprocessed)                                                                                ::
    ID: 07046150.wav
    Length: 32
** A heavy object dragged through ice and snow (2J1, reprocessed)                                                                                ::
    ID: 07046149.wav
    Length: 26
** Hacking ice with axe (2J1,reprocessed)                                                                                ::
    ID: 07046148.wav
    Length: 32
** Three ice crashes (2J1,reprocessed)                                                                                ::
    ID: 07046147.wav
    Length: 10
** Firework display (no voices) (1F2,reprocessed)                                                                                ::
    ID: 07046146.wav
    Length: 206
** Firework display at Thames, South Bank (with crowd) - 1973 (1F1, reprocessed)                                                                                ::
    ID: 07046145.wav
    Length: 314
** Firework display at Alexandra Palace (with crowd) - 1973 (1F1, reprocessed)                                                                                ::
    ID: 07046144.wav
    Length: 317
** Heavy flames crackling (75F,reprocessed)                                                                                ::
    ID: 07046143.wav
    Length: 211
** Roaring wood fire - close perspective (2F2,reprocessed)                                                                                ::
    ID: 07046142.wav
    Length: 241
** Bonfire - close perspective (2F2,reprocessed)                                                                                ::
    ID: 07046141.wav
    Length: 240
** Bonfire - close perspective (1F2,reprocessed)                                                                                ::
    ID: 07046140.wav
    Length: 240
** Atmosphere in open field with church clock striking four, with distant traffic and birdsong - 1980 (2513, reprocessed) (technical note - to be used at low level)                                                                                ::
    ID: 07046139.wav
    Length: 17
** Mechanical digger (four wheels) - working close - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046138.wav
    Length: 46
** Mechanical digger (four wheels) - digging concrete (rec. close to bucket) - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046137.wav
    Length: 92
** Mechanical digger (four wheels) - digging soft ground (rec. close to bucket) - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046136.wav
    Length: 88
** Mechanical digger (four wheels) - approaching and passing - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046135.wav
    Length: 52
** Mechanical digger (four wheels) - shutdown - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046134.wav
    Length: 12
** Mechanical digger (four wheels) - start up and tickover - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046133.wav
    Length: 50
** Bulldozer (tracked vehicle) - starting up, earth moving - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046132.wav
    Length: 198
** Bulldozer (tracked vehicle) - approaching, stopping, switching off - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046131.wav
    Length: 37
** Bulldozer (tracked vehicle) - starting ticking over, driving away - 1981 (6B1, reprocessed)                                                                                ::
    ID: 07046130.wav
    Length: 133
** Atmosphere at building site with heavy machinery - 1982 (1N2, reprocessed)                                                                                ::
    ID: 07046129.wav
    Length: 271
** General background of men mixing and laying ballast with distant conversation - 1967 (136A, reprocessed)                                                                                ::
    ID: 07046128.wav
    Length: 203
** An avalanche of ice - distant perspective (2J1,reprocessed)                                                                                ::
    ID: 07046127.wav
    Length: 141
** An avalanche of ice - close perspective  (2J1, reprocessed)                                                                                ::
    ID: 07046126.wav
    Length: 60
** Busy city skyline with brake squeals (1T10, reprocessed)                                                                                ::
    ID: 07046125.wav
    Length: 240
** Traffic from top of city building (1T3, reprocessed)                                                                                ::
    ID: 07046124.wav
    Length: 272
** Open skyline (specially created) (1N1, reprocessed)                                                                                ::
    ID: 07046123.wav
    Length: 271
** Wide perspective skyline (specially created ambience) (1N1,reprocessed)                                                                                ::
    ID: 07046122.wav
    Length: 273
** Road repairs - tar laying machine, grit laid, diesel rollers prepare surface, occas.distant speech (4C1, reprocessed)                                                                                ::
    ID: 07046121.wav
    Length: 129
** Road Maintenance - pneumatic drill, constant run, compressor start, run, stop (4C1, reprocessed)                                                                                ::
    ID: 07046120.wav
    Length: 91
** Road Maintenance - pneumatic drill, constant run (4C1, reprocessed)                                                                                ::
    ID: 07046119.wav
    Length: 61
** Refuse collection - unloading dustcart at tip (4C1, reprocessed)                                                                                ::
    ID: 07046118.wav
    Length: 90
** Refuse collection - leading crusher (close perspective) occas. distant speech (4C1, reprocessed)                                                                                ::
    ID: 07046117.wav
    Length: 91
** Refuse collection - dust cart arrives, bins emptied, departs, occas. distant speech (4C1, reprocessed)                                                                                ::
    ID: 07046116.wav
    Length: 90
** Pigeons flapping and cooing in coop (1B18,reprocessed)                                                                                ::
    ID: 07046115.wav
    Length: 180
** Pigeons flying and chasing in coop (1B18,reprocessed)                                                                                ::
    ID: 07046114.wav
    Length: 65
** Pigeons flying out of coop (1B18,reprocessed)                                                                                ::
    ID: 07046113.wav
    Length: 7
** Pigeons flying off (1B18,reprocessed)                                                                                ::
    ID: 07046112.wav
    Length: 5
** Pigeons flying off (1B18,reprocessed)                                                                                ::
    ID: 07046111.wav
    Length: 7
** Pigeons flying off (1B18,reprocessed)                                                                                ::
    ID: 07046110.wav
    Length: 4
** Pigeons flying off (1B18,reprocessed)                                                                                ::
    ID: 07046109.wav
    Length: 7
** Suburban garden at night - distant traffic, distant plane overhead,occas.speech - 1981(1B7, reprocessed) (technical note - to be used at low level)                                                                                ::
    ID: 07046108.wav
    Length: 246
** Garden in north London at evening - rain begins at 1'30'' - 1985 (2N2, reprocessed) (technical note - to be used at low level)                                                                                ::
    ID: 07046107.wav
    Length: 242
** Autumn suburban atmosphere - blackbirds evening calls with traffic background - 1981(1B16, reprocessed)                                                                                ::
    ID: 07046106.wav
    Length: 210
** Quiet park atmosphere - distant traffic and light wind, distant jet aircraft passes overhead from 0'34 - 1972 (1B2, reproccessed)                                                                                ::
    ID: 07046105.wav
    Length: 230
** Town park atmosphere - birds and wind in trees - 1972 (1B2,reprocessed)                                                                                ::
    ID: 07046104.wav
    Length: 272
** Small town in summer - with birds, distant traffic and some speech - 1980 (1B9, reprocessed) (technical note - to be used at low level)                                                                                ::
    ID: 07046103.wav
    Length: 271
** Town atmosphere from roof top - with wind, birds and mid distant traffic - 1981 (1T7,reprocessed)                                                                                ::
    ID: 07046102.wav
    Length: 270
** Suburb - North of London with birdsong (1B1,reprocessed)                                                                                ::
    ID: 07046101.wav
    Length: 271
** Suburban traffic - heavy traffic with footsteps in one way street (right to left) (1T9, reprocessed)                                                                                ::
    ID: 07046100.wav
    Length: 269
** Suburban traffic - heavy traffic and footsteps - 1972 (1T9, reprocessed)                                                                                ::
    ID: 07046099.wav
    Length: 271
** 30 cwt Massey drop hammer & 5 cwt power hammer.                                                                                ::
    ID: 07046098.wav
    Length: 75
** 20 cwt Massey drop hammer.                                                                                ::
    ID: 07046097.wav
    Length: 75
** 5 cwt Massey power hammer.                                                                                ::
    ID: 07046096.wav
    Length: 36
** Coining press.                                                                                ::
    ID: 07046095.wav
    Length: 75
** Atmosphere inside drop forge shop.                                                                                ::
    ID: 07046094.wav
    Length: 146
** Atmosphere outside drop forge shop.                                                                                ::
    ID: 07046093.wav
    Length: 143
** Machine shop, general atmosphere - use at low level.                                                                                ::
    ID: 07046092.wav
    Length: 210
** Drilling and milling machine operates.                                                                                ::
    ID: 07046091.wav
    Length: 210
** Milling machine operating.                                                                                ::
    ID: 07046090.wav
    Length: 150
** Machining & tapping machinery operating.                                                                                ::
    ID: 07046089.wav
    Length: 202
** Shaft orientation machine operating.                                                                                ::
    ID: 07046088.wav
    Length: 153
** Drilling and reaming machine operating.                                                                                ::
    ID: 07046087.wav
    Length: 167
** Lathe shop atmosphere.                                                                                ::
    ID: 07046086.wav
    Length: 240
** Turning aluminium.                                                                                ::
    ID: 07046085.wav
    Length: 140
** Grinding tool.                                                                                ::
    ID: 07046084.wav
    Length: 125
** Turning steel.                                                                                ::
    ID: 07046083.wav
    Length: 159
** Turning brass.                                                                                ::
    ID: 07046082.wav
    Length: 90
** Compressed air hand disc grinder, operating in short bursts.                                                                                ::
    ID: 07046081.wav
    Length: 38
** Compressed air hand disc grinder.                                                                                ::
    ID: 07046080.wav
    Length: 119
** Schloemann 40-inch cogging mill.                                                                                ::
    ID: 07046079.wav
    Length: 148
** Hot saw in operation in steel works.                                                                                ::
    ID: 07046078.wav
    Length: 45
** Oxypropane flame cutter, cuts and idles.                                                                                ::
    ID: 07046077.wav
    Length: 170
** 'Snow' surface grinder operating at steel works 1969.                                                                                ::
    ID: 07046076.wav
    Length: 132
** Portable metal grinding machine operating.                                                                                ::
    ID: 07046075.wav
    Length: 49
** Stationary machine grinding metal.                                                                                ::
    ID: 07046074.wav
    Length: 58
** Auto hacksaw cutting through sheet metal.                                                                                ::
    ID: 07046073.wav
    Length: 145
** Friction metal saw operating.                                                                                ::
    ID: 07046072.wav
    Length: 77
** Sheet metal being cut by a guillotine.                                                                                ::
    ID: 07046071.wav
    Length: 47
** Oxy-acetylene cutting in sheet metal engineering works.                                                                                ::
    ID: 07046070.wav
    Length: 89
** Special welding, sheet metal engineering 1969.                                                                                ::
    ID: 07046069.wav
    Length: 152
** Arc welding, sheet metal engineering 1969.                                                                                ::
    ID: 07046068.wav
    Length: 59
** Cutting metal with oxy-acetylene torch.                                                                                ::
    ID: 07046067.wav
    Length: 126
** Cutting steel girder with oxy-acetylene torch.                                                                                ::
    ID: 07046066.wav
    Length: 103
** Internal grinder.                                                                                ::
    ID: 07046065.wav
    Length: 112
** Surface grinder.                                                                                ::
    ID: 07046064.wav
    Length: 72
** Electric drill - 3 bursts.                                                                                ::
    ID: 07046063.wav
    Length: 23
** Open top vintage bus: Dennis (1925) 4 cylinder petrol engine - journey on lower deck with occasional gear changes, stops and starts.                                                                                :Open top vintage bus:Dennis (1925) 4 cylinder petrol engine - j:
    ID: 07046062.wav
    Length: 97
** Open top vintage bus: Dennis (1925) 4 cylinder petrol engine - journey on open top with occasional gear changes, stops and starts.                                                                                :Open top vintage bus:Dennis (1925) 4 cylinder petrol engine - j:
    ID: 07046061.wav
    Length: 211
** Exterior - bus on country route arrives and stops.                                                                                ::
    ID: 07046060.wav
    Length: 24
** Exterior - bus on country route arrives and stops.                                                                                ::
    ID: 07046059.wav
    Length: 17
** Exterior - bus on country route passing.                                                                                ::
    ID: 07046058.wav
    Length: 34
** Exterior - start up, pass and depart, bus on country route.                                                                                ::
    ID: 07046057.wav
    Length: 22
** Exterior - start up and depart, bus on country route.                                                                                ::
    ID: 07046056.wav
    Length: 22
** Exterior - sliding door open and close, bus on country route.                                                                                ::
    ID: 07046055.wav
    Length: 6
** Interior of bus on country route - self starter, move off, running on trunk road, slow down, stop.                                                                                ::
    ID: 07046054.wav
    Length: 373
** Exterior - approach, stop, start up, depart - bus on country route.                                                                                ::
    ID: 07046053.wav
    Length: 67
** Exterior - bus passing, on coutry route.                                                                                ::
    ID: 07046052.wav
    Length: 32
** Interior - general atmosphere with school children on board, running with odd stops.                                                                                ::
    ID: 07046051.wav
    Length: 256
** Interior - running with intermediate stops on country route.                                                                                ::
    ID: 07046050.wav
    Length: 358
** Atmosphere - with buses parking for the night.                                                                                ::
    ID: 07046049.wav
    Length: 134
** Atmosphere - with buses departing.                                                                                ::
    ID: 07046048.wav
    Length: 205
** Interior - on congested London route.                                                                                ::
    ID: 07046047.wav
    Length: 185
** Interior - on London route.                                                                                ::
    ID: 07046046.wav
    Length: 210
** Interior, London Green Line Coach - start up, bells, doors, into medium fast run.                                                                                ::
    ID: 07046045.wav
    Length: 160
** Interior, London Green Line Coach - start up, run with stops and starts, stop, tickover, switch off.                                                                                ::
    ID: 07046044.wav
    Length: 358
** Interior, London Green Line Coach - start, tickover, switch off (use at low level).                                                                                ::
    ID: 07046043.wav
    Length: 181
** Interior, London Green Line Coach - fan heater switched on, runs, switched off.                                                                                ::
    ID: 07046042.wav
    Length: 122
** Exterior, London Green Line Coach - start, tickover, switch off.                                                                                ::
    ID: 07046041.wav
    Length: 187
** Exterior, London Green Line Coach passing at speed.                                                                                ::
    ID: 07046040.wav
    Length: 13
** Exterior, London Green Line Coach passing at medium speed.                                                                                ::
    ID: 07046039.wav
    Length: 27
** Exterior, London Green Line Coach passing at medium speed.                                                                                ::
    ID: 07046038.wav
    Length: 31
** Exterior, London Green Line Coach passing slowly.                                                                                ::
    ID: 07046037.wav
    Length: 46
** Exterior - London Green Line Coach, approach, stop, tickover, bell, doors, departs.                                                                                ::
    ID: 07046036.wav
    Length: 54
** Exterior - London Green Line Coach approach, stop, tickover.                                                                                ::
    ID: 07046035.wav
    Length: 23
** Exterior - London Green Line Coach approach, stop, switch off.                                                                                ::
    ID: 07046034.wav
    Length: 38
** Exterior - doors, departs. London Green Line Coaches.                                                                                ::
    ID: 07046033.wav
    Length: 34
** Bell, doors, departs. London Green Line Coach.                                                                                ::
    ID: 07046032.wav
    Length: 33
** Self starter, bell, doors, departs, London Green Line Coach.                                                                                ::
    ID: 07046031.wav
    Length: 38
** Pneumatic doors closed, london Green Line Coach.                                                                                ::
    ID: 07046030.wav
    Length: 4
** Pneumatic doors opened, London Green Line Coach.                                                                                ::
    ID: 07046029.wav
    Length: 3
** Horn sounded several times, London Green Line Coach.                                                                                ::
    ID: 07046028.wav
    Length: 17
** Bell sounded 3 times on a full coach, London Green Line Coach.                                                                                ::
    ID: 07046027.wav
    Length: 5
** Bell sounded twice to start, London Green Line Coach.                                                                                ::
    ID: 07046026.wav
    Length: 4
** Bell sounded once to stop, London Green Line coach.                                                                                ::
    ID: 07046025.wav
    Length: 3
** Ultimate ticket machine issuing several tickets.                                                                                ::
    ID: 07046024.wav
    Length: 54
** Ultimate ticket machine issuing two tickets.                                                                                ::
    ID: 07046023.wav
    Length: 6
** Ultimate ticket machine issuing one ticket.                                                                                ::
    ID: 07046022.wav
    Length: 4
** Setting Ultimate ticket machine.                                                                                ::
    ID: 07046021.wav
    Length: 17
** Almex ticket machine issuing several tickets.                                                                                ::
    ID: 07046020.wav
    Length: 28
** Almex ticket machine issuing one ticket.                                                                                ::
    ID: 07046019.wav
    Length: 5
** Setting an Almex ticket machine.                                                                                ::
    ID: 07046018.wav
    Length: 7
** Gibson ticket machine issuing several tickets.                                                                                ::
    ID: 07046017.wav
    Length: 12
** Gibson ticket machine issuing one ticket.                                                                                ::
    ID: 07046016.wav
    Length: 5
** Setting a Gibson ticket machine.                                                                                ::
    ID: 07046015.wav
    Length: 17
** Bell punch operated several times.                                                                                ::
    ID: 07046014.wav
    Length: 10
** Bell punch operated once.                                                                                ::
    ID: 07046013.wav
    Length: 3
** Various amounts issued as change, one-man operated red Central buses.                                                                                ::
    ID: 07046012.wav
    Length: 25
** 6d piece issued as change, one-man operated red Central buses.                                                                                ::
    ID: 07046011.wav
    Length: 5
** 3d piece issued as change, one-man operated red Central buses.                                                                                ::
    ID: 07046010.wav
    Length: 5
** Coin inserted, regain button pressed on one-man operated red Central bus.                                                                                ::
    ID: 07046009.wav
    Length: 7
** Coin rejected twice, one-man operated red Central bus.                                                                                ::
    ID: 07046008.wav
    Length: 8
** Several adults through turnstile - two 3d pieces inserted, one-man operated red Central bus.                                                                                ::
    ID: 07046007.wav
    Length: 27
** Several adults - 6d fares through turnstile, one-man operated red Central bus.                                                                                ::
    ID: 07046006.wav
    Length: 36
** Adult - 6d fare through turnstile, one-man operated red Central bus.                                                                                ::
    ID: 07046005.wav
    Length: 3
** Several children through turnstile - 3d fares inserted, one-man operated red Central bus.                                                                                ::
    ID: 07046004.wav
    Length: 32
** Child through turnstile - 3d fare inserted, one-man operated red Central bus.                                                                                ::
    ID: 07046003.wav
    Length: 7
** Adult's 6d fare (several times) in Auto slot MK.2 on Green country buses.                                                                                ::
    ID: 07046002.wav
    Length: 41
** Child's 3d fare (several times) in Auto slot MK.2 on Green country buses.                                                                                ::
    ID: 07046001.wav
    Length: 32
** Ambulance service R/T chat (indistinct) with urban background as heard in ambulance without engine running.                                                                                ::
    ID: 07045326.wav
    Length: 47
** Ambulance service R/T selcall bleep.                                                                                ::
    ID: 07045325.wav
    Length: 1
** Ambulance rear doors opened and stretcher unloaded, hospital loading area acoustic.                                                                                ::
    ID: 07045324.wav
    Length: 21
** Ambulance rear door closed. (interior acoustic)                                                                                ::
    ID: 07045323.wav
    Length: 10
** Ambulance rear doors opened. (interior acoustic)                                                                                ::
    ID: 07045322.wav
    Length: 6
** Ambulance hand brake applied.                                                                                ::
    ID: 07045321.wav
    Length: 1
** Ambulance, start into constant with bell (not used these days) slows, stops.                                                                                ::
    ID: 07045320.wav
    Length: 174
** Ambulance, start into constant run with two-tone horn siren at speed through heavy traffic, various acoustic changes as                                                                                 ::
    ID: 07045319.wav
    Length: 185
** Ambulance approach and stop, idle, off, no siren.                                                                                ::
    ID: 07045318.wav
    Length: 22
** Ambulance, start engine and depart without siren.                                                                                ::
    ID: 07045317.wav
    Length: 18
** Ambulance approaches junction and turns right with two-tone horn, urban background.                                                                                ::
    ID: 07045316.wav
    Length: 34
** Ambulance, pass left to right with two-tone horn siren, urban background.                                                                                ::
    ID: 07045315.wav
    Length: 34
** Ambulance, pass right to left with two-tone horn siren.                                                                                ::
    ID: 07045314.wav
    Length: 40
** Ambulance arrives with two-tone horn siren.                                                                                ::
    ID: 07045313.wav
    Length: 27
** Ambulance departs with two-tone horn siren.                                                                                ::
    ID: 07045312.wav
    Length: 17
** Ambulance two-tone horn siren, exterior acoustic. (Used by National Ambulance Service.)                                                                                ::
    ID: 07045311.wav
    Length: 17
** Ambulance wail siren changing to yelp and back several times, exterior acoustic.                                                                                ::
    ID: 07045310.wav
    Length: 64
** Ambulance yelp siren, exterior acoustic. (Used by St John Ambulance Service.)                                                                                ::
    ID: 07045309.wav
    Length: 47
** Ambulance wail siren, exterior acoustic. (Used by St John ambulance services.)                                                                                ::
    ID: 07045308.wav
    Length: 68
** Carbon Dioxide (CO2) fire extinguisher used.                                                                                ::
    ID: 07045307.wav
    Length: 23
** General activity at scene of the fire.                                                                                ::
    ID: 07045306.wav
    Length: 225
** Hoses used on fire, distant voices.                                                                                ::
    ID: 07045305.wav
    Length: 115
** Auxiliary fire pump run.                                                                                ::
    ID: 07045304.wav
    Length: 89
** Fire engine, start, engage main pump, run pump, idle, off.                                                                                ::
    ID: 07045303.wav
    Length: 251
** Ladder loaded onto fire engine.                                                                                ::
    ID: 07045302.wav
    Length: 8
** Fire hoses run and ladders erected, indistinct voices.                                                                                ::
    ID: 07045301.wav
    Length: 88
** Fire engine, sliding side panels lowered.                                                                                ::
    ID: 07045300.wav
    Length: 5
** Fire engine, sliding panels raised.                                                                                ::
    ID: 07045299.wav
    Length: 6
** Fire engine, door slammed.                                                                                ::
    ID: 07045298.wav
    Length: 1
** Fire engine, start into constant run with two-tone horns arrive, idle, off. (Interior acoustic)                                                                                ::
    ID: 07045297.wav
    Length: 200
** Fire engine, long approach with electronic two-tone siren, arrive, idle, off.                                                                                ::
    ID: 07045296.wav
    Length: 68
** Fire engine, pass left to right with electronic two-tone siren.                                                                                ::
    ID: 07045295.wav
    Length: 43
** Fire engine, pass left to right with yelp siren.                                                                                ::
    ID: 07045294.wav
    Length: 44
** Fire engine, pass right to left with wail siren.                                                                                ::
    ID: 07045293.wav
    Length: 45
** Fire engine, testing electronic sirens, used increasingly with engine idling.                                                                                ::
    ID: 07045292.wav
    Length: 71
** Fire engine, pass right to left with revving engine and two-tone horns.                                                                                ::
    ID: 07045291.wav
    Length: 51
** Fire engine, pass right to left with two tone horns.                                                                                ::
    ID: 07045290.wav
    Length: 44
** Fire engine, long approach and pass right to left with two horns.                                                                                ::
    ID: 07045289.wav
    Length: 59
** Fire engine arrives with two-tone horns, idle, off.                                                                                ::
    ID: 07045288.wav
    Length: 48
** Fire engine arrives with two-tone horns, slight skid as it stops, idle off.                                                                                ::
    ID: 07045287.wav
    Length: 75
** Fire engine departs with two-tone horns, urban acoustic with reflections from buildings.                                                                                ::
    ID: 07045286.wav
    Length: 27
** Fire engine started, revving, departs from fire station with two tone horns.                                                                                ::
    ID: 07045285.wav
    Length: 39
** Fire engine started, idle, switch off                                                                                ::
    ID: 07045284.wav
    Length: 82
** Firs Station, alarm bell & fireman descend pole.                                                                                ::
    ID: 07045283.wav
    Length: 21
** Police car constant run with yelp siren switched on/off, interior acoustic.                                                                                ::
    ID: 07045282.wav
    Length: 67
** Police car constant run with wail siren switched on/off, interior acoustic.                                                                                ::
    ID: 07045281.wav
    Length: 66
** Police car arrive with slight skid and without siren, interior acoustic.                                                                                ::
    ID: 07045280.wav
    Length: 12
** Police car start and depart without siren, interior acoustic.                                                                                ::
    ID: 07045279.wav
    Length: 17
** Police car yelp siren, interior acoustic.                                                                                ::
    ID: 07045278.wav
    Length: 61
** Police car wail siren, interior acoustic.                                                                                ::
    ID: 07045277.wav
    Length: 55
** Police car, high speed pass right to left on motorway with yelp siren.                                                                                ::
    ID: 07045276.wav
    Length: 32
** Police car, high speed pass right to left on motorway with wail siren.                                                                                ::
    ID: 07045275.wav
    Length: 31
** Police car, pass right to left changing from wail to yelp siren.                                                                                ::
    ID: 07045274.wav
    Length: 19
** Police car, pass from left to right changing from wail to yelp siren.                                                                                ::
    ID: 07045273.wav
    Length: 21
** Police car, pass left to right with wail siren, urban background.                                                                                ::
    ID: 07045272.wav
    Length: 26
** Police car, pass right to left with wail siren, urban background.                                                                                ::
    ID: 07045271.wav
    Length: 38
** Police car, pass right to left with wail siren, switched off as it passes.                                                                                ::
    ID: 07045270.wav
    Length: 30
** Police car, pass left to right with yelp siren, urban background.                                                                                ::
    ID: 07045269.wav
    Length: 22
** Police car, pass right to left with yelp siren, urban background.                                                                                ::
    ID: 07045268.wav
    Length: 37
** Police car, pass from left to right with yelp siren.                                                                                ::
    ID: 07045267.wav
    Length: 26
** Police car arrive with yelp siren.                                                                                ::
    ID: 07045266.wav
    Length: 21
** Police car arrive with yelp siren.                                                                                ::
    ID: 07045265.wav
    Length: 17
** Police car start and depart with yelp siren.                                                                                ::
    ID: 07045264.wav
    Length: 16
** Police car arrives with wail siren.                                                                                ::
    ID: 07045263.wav
    Length: 35
** Police car departs with wail siren.                                                                                ::
    ID: 07045262.wav
    Length: 28
** Police car arrives with wail siren.                                                                                ::
    ID: 07045261.wav
    Length: 16
** Police car departs with wail siren.                                                                                ::
    ID: 07045260.wav
    Length: 26
** Police car yelp siren, exterior acoustic.                                                                                ::
    ID: 07045259.wav
    Length: 78
** Police car wail siren, exterior acoustic.                                                                                ::
    ID: 07045258.wav
    Length: 49
** Building collapses.                                                                                ::
    ID: 07045257.wav
    Length: 16
** Light aircraft, dive and crash.                                                                                ::
    ID: 07045256.wav
    Length: 24
** Steam train, derailed and crash.                                                                                ::
    ID: 07045255.wav
    Length: 41
** Car, emergency stop, interior acoustic.                                                                                ::
    ID: 07045254.wav
    Length: 18
** Car skids whilst cornering, from right.                                                                                ::
    ID: 07045253.wav
    Length: 9
** Car skids whilst cornering, from left.                                                                                ::
    ID: 07045252.wav
    Length: 10
** Car, braking skid and minor accident.                                                                                ::
    ID: 07045251.wav
    Length: 4
** Car, braking skid.                                                                                ::
    ID: 07045250.wav
    Length: 3
** Car, braking skid.                                                                                ::
    ID: 07045249.wav
    Length: 3
** Car, braking skid.                                                                                ::
    ID: 07045248.wav
    Length: 4
** Burglar alarm, combined bell and electronic siren.                                                                                ::
    ID: 07045247.wav
    Length: 59
** Burglar alarm.                                                                                ::
    ID: 07045246.wav
    Length: 102
** Burglar alarm.                                                                                ::
    ID: 07045245.wav
    Length: 61
** Car alarm.                                                                                ::
    ID: 07045244.wav
    Length: 47
** Housebreaking, front door glass smashed.                                                                                ::
    ID: 07045243.wav
    Length: 6
** 999 dialed, "Emergency, which service?"                                                                                ::
    ID: 07045242.wav
    Length: 4
** Burmese cat hissing and growling.                                                                                ::
    ID: 07045241.wav
    Length: 105
** Burmese cat hisses twice, and then long cry of anger.                                                                                ::
    ID: 07045240.wav
    Length: 15
** Burmese cat meowing.                                                                                ::
    ID: 07045239.wav
    Length: 98
** Burmese cat, individual meows.                                                                                ::
    ID: 07045238.wav
    Length: 1
** Burmese cat, individual meows.                                                                                ::
    ID: 07045237.wav
    Length: 1
** Burmese cat, individual meows.                                                                                ::
    ID: 07045236.wav
    Length: 1
** Burmese cat, individual meows.                                                                                ::
    ID: 07045235.wav
    Length: 1
** Burmese cat, individual meows.                                                                                ::
    ID: 07045234.wav
    Length: 2
** Siamese cat meowing.                                                                                ::
    ID: 07045233.wav
    Length: 157
** Siamese cat, individual meows.                                                                                ::
    ID: 07045232.wav
    Length: 1
** Siamese cat, individual meows.                                                                                ::
    ID: 07045231.wav
    Length: 1
** Siamese cat, individual meows.                                                                                ::
    ID: 07045230.wav
    Length: 1
** Siamese cat, individual meows.                                                                                ::
    ID: 07045229.wav
    Length: 1
** Siamese cat, individual meows.                                                                                ::
    ID: 07045228.wav
    Length: 1
** Cat washing.                                                                                ::
    ID: 07045227.wav
    Length: 62
** Cat tail trodden on.                                                                                ::
    ID: 07045226.wav
    Length: 1
** Miserable tom cat outside in the rain.                                                                                ::
    ID: 07045225.wav
    Length: 142
** Cats in a suburban garden, one close perspective, others more distant.                                                                                ::
    ID: 07045224.wav
    Length: 167
** Cat coughing.                                                                                ::
    ID: 07045223.wav
    Length: 107
** Tom cat hissing at dog.                                                                                ::
    ID: 07045222.wav
    Length: 78
** Tom cat attacking strike and hiss.                                                                                ::
    ID: 07045221.wav
    Length: 1
** Tom cat hiss.                                                                                ::
    ID: 07045220.wav
    Length: 1
** Tom cat growl and hiss.                                                                                ::
    ID: 07045219.wav
    Length: 3
** Cat sniffing.                                                                                ::
    ID: 07045218.wav
    Length: 18
** Tom cat growling.                                                                                ::
    ID: 07045217.wav
    Length: 182
** Tom cat growling, individual growls.                                                                                ::
    ID: 07045216.wav
    Length: 2
** Tom cat growling, individual growls.                                                                                ::
    ID: 07045215.wav
    Length: 4
** Tom cat growling, individual growls.                                                                                ::
    ID: 07045214.wav
    Length: 5
** Tom cat growling, individual growls.                                                                                ::
    ID: 07045213.wav
    Length: 3
** Tom cat growling, individual growls.                                                                                ::
    ID: 07045212.wav
    Length: 4
** Tom cat growling, individual growls.                                                                                ::
    ID: 07045211.wav
    Length: 5
** Tom cat growling, individual growls.                                                                                ::
    ID: 07045210.wav
    Length: 1
** Cat guzzling greedily.                                                                                ::
    ID: 07045209.wav
    Length: 33
** Cat drinking milk.                                                                                ::
    ID: 07045208.wav
    Length: 143
** Cat eating, nice crunchy sound.                                                                                ::
    ID: 07045207.wav
    Length: 230
** Tom cat, purring.                                                                                ::
    ID: 07045206.wav
    Length: 201
** Tom cat, meowing.                                                                                ::
    ID: 07045205.wav
    Length: 107
** Tom cat, individual meows.                                                                                ::
    ID: 07045204.wav
    Length: 5
** Tom cat, individual meows.                                                                                ::
    ID: 07045203.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045202.wav
    Length: 2
** Tom cat, individual meows.                                                                                ::
    ID: 07045201.wav
    Length: 3
** Tom cat, individual meows.                                                                                ::
    ID: 07045200.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045199.wav
    Length: 3
** Tom cat, individual meows.                                                                                ::
    ID: 07045198.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045197.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045196.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045195.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045194.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045193.wav
    Length: 1
** Tom cat, individual meows.                                                                                ::
    ID: 07045192.wav
    Length: 1
** Ten week old kitten, purring.                                                                                ::
    ID: 07045191.wav
    Length: 163
** Ten week old kitten, mews.                                                                                ::
    ID: 07045190.wav
    Length: 194
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045189.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045188.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045187.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045186.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045185.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045184.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045183.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045182.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045181.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045180.wav
    Length: 1
** Ten week old kitten, individual mews.                                                                                ::
    ID: 07045179.wav
    Length: 1
** Four week old kitten, mewing and drinking milk from bottle.                                                                                ::
    ID: 07045178.wav
    Length: 146
** Four week old kitten, individual mews.                                                                                ::
    ID: 07045177.wav
    Length: 1
** Four week old kitten, individual mews.                                                                                ::
    ID: 07045176.wav
    Length: 1
** Four week old kitten, individual mews.                                                                                ::
    ID: 07045175.wav
    Length: 1
** Four week old kitten, individual mews.                                                                                ::
    ID: 07045174.wav
    Length: 1
** Four week old kitten, individual mews.                                                                                ::
    ID: 07045173.wav
    Length: 1
** Four week old kitten, individual mews.                                                                                ::
    ID: 07045172.wav
    Length: 1
** Building site, concrete airator used to remove air bubbles from liquid concrete, close perspective.                                                                                ::
    ID: 07045171.wav
    Length: 71
** Building site, hammering steel girders, close perspective.                                                                                ::
    ID: 07045170.wav
    Length: 99
** Building site, interior acoustic of building under construction with bricklayers in foreground.                                                                                ::
    ID: 07045169.wav
    Length: 235
** General atmosphere on building site, closer perspective, steel girders cut and general site activity.                                                                                ::
    ID: 07045168.wav
    Length: 345
** General atmosphere on building site, mid distant acoustic, starts with dumper truck passing.                                                                                ::
    ID: 07045167.wav
    Length: 267
** Pneumatic drill used on tarmac.                                                                                ::
    ID: 07045166.wav
    Length: 187
** Anvil, metal hammered hard by blacksmith.                                                                                ::
    ID: 07045165.wav
    Length: 102
** Gas blowlamp lit, used to heat surface, changing acoustic, off.                                                                                ::
    ID: 07045164.wav
    Length: 212
** Gas blowlamp lit, constant roar of flame, off.                                                                                ::
    ID: 07045163.wav
    Length: 124
** Arc welding machine, switch on, attempt to strike arc, fall, switch off.                                                                                ::
    ID: 07045162.wav
    Length: 59
** Arc welding machine, switch on, strike arc 2nd attempt, weld off.                                                                                ::
    ID: 07045161.wav
    Length: 38
** Arc welding machine, switch on, weld off.                                                                                ::
    ID: 07045160.wav
    Length: 36
** Arc welding machine, switch on, weld, lose arc, restrike, weld, off.                                                                                ::
    ID: 07045159.wav
    Length: 50
** Arc welding machine, switch on, transformer hum in standby mode, off.                                                                                ::
    ID: 07045158.wav
    Length: 111
** Pressure hose, cleaning yard.                                                                                ::
    ID: 07045157.wav
    Length: 194
** Electric grinder, long bursts on metal sheet.                                                                                ::
    ID: 07045156.wav
    Length: 67
** Electric grinder, short burst on metal sheet.                                                                                ::
    ID: 07045155.wav
    Length: 8
** Electric grinder, freewheels.                                                                                ::
    ID: 07045154.wav
    Length: 14
** Electric jigsaw, plywood sheet.                                                                                ::
    ID: 07045153.wav
    Length: 74
** Electric jigsaw, small piece of wood.                                                                                ::
    ID: 07045152.wav
    Length: 20
** Electric drill, rotart sanding attachment used on plywood sheet.                                                                                ::
    ID: 07045151.wav
    Length: 143
** Electric drill, single hole in thick metal bar.                                                                                ::
    ID: 07045150.wav
    Length: 30
** Electric drill, single hole in metal sheet.                                                                                ::
    ID: 07045149.wav
    Length: 12
** Electric drill, single hole in wood, jams, is freed.                                                                                ::
    ID: 07045148.wav
    Length: 16
** Electric drill, single hole in wood.                                                                                ::
    ID: 07045147.wav
    Length: 11
** Electric drill, short burst freewheeling.                                                                                ::
    ID: 07045146.wav
    Length: 3
** Electric hoist assembled, with metal clattering noise.                                                                                ::
    ID: 07045145.wav
    Length: 44
** Spray painting.                                                                                ::
    ID: 07045144.wav
    Length: 86
** Can of spray paint shaken.                                                                                ::
    ID: 07045143.wav
    Length: 49
** Painting, roller.                                                                                ::
    ID: 07045142.wav
    Length: 192
** Painting, brush.                                                                                ::
    ID: 07045141.wav
    Length: 177
** Large spanner dropped.                                                                                ::
    ID: 07045140.wav
    Length: 2
** Small spanner dropped.                                                                                ::
    ID: 07045139.wav
    Length: 1
** Hand-drill, single hole in metal, jams, is freed.                                                                                ::
    ID: 07045138.wav
    Length: 19
** Hand-drill, single hole in metal.                                                                                ::
    ID: 07045137.wav
    Length: 18
** Hand-drill, single hole in wood.                                                                                ::
    ID: 07045136.wav
    Length: 7
** Hand-drill, 2 holes in wood.                                                                                ::
    ID: 07045135.wav
    Length: 16
** Chisel sharpened on grindstone.                                                                                ::
    ID: 07045134.wav
    Length: 58
** Wood levered with chisel, splinters.                                                                                ::
    ID: 07045133.wav
    Length: 28
** Nail pulled.                                                                                ::
    ID: 07045132.wav
    Length: 2
** Nail pulled.                                                                                ::
    ID: 07045131.wav
    Length: 2
** Nail pulled.                                                                                ::
    ID: 07045130.wav
    Length: 3
** Nail pulled.                                                                                ::
    ID: 07045129.wav
    Length: 2
** Chiseling wood, splintering noise.                                                                                ::
    ID: 07045128.wav
    Length: 81
** Sanding, sheet of metal.                                                                                ::
    ID: 07045127.wav
    Length: 50
** Sanding, edge of plywood.                                                                                ::
    ID: 07045126.wav
    Length: 55
** Sanding, paper folded then sheet of plywood.                                                                                ::
    ID: 07045125.wav
    Length: 87
** Sanding, paper folded then small piece of wood.                                                                                ::
    ID: 07045124.wav
    Length: 42
** Sanding, small piece of wood.                                                                                ::
    ID: 07045123.wav
    Length: 58
** Planing, piece of wood.                                                                                ::
    ID: 07045122.wav
    Length: 44
** File, metal.                                                                                ::
    ID: 07045121.wav
    Length: 32
** File, formica with squealing on some strokes.                                                                                ::
    ID: 07045120.wav
    Length: 39
** File, wood.                                                                                ::
    ID: 07045119.wav
    Length: 35
** Hacksaw, piece of metal, cut piece falls on floor.                                                                                ::
    ID: 07045118.wav
    Length: 47
** Hacksaw, small piece of Formica, cut piece falls on floor.                                                                                ::
    ID: 07045117.wav
    Length: 20
** Hacksaw, small piece of Formica.                                                                                ::
    ID: 07045116.wav
    Length: 13
** Hand saw through sheet of plywood, saw jams on some strokes.                                                                                ::
    ID: 07045115.wav
    Length: 25
** Tenon saw, small piece of wood, close perspective.                                                                                ::
    ID: 07045114.wav
    Length: 19
** Tenon saw, small piece of wood, variable rythm.                                                                                ::
    ID: 07045113.wav
    Length: 17
** Tenon saw, small piece of wood, steady rythm.                                                                                ::
    ID: 07045112.wav
    Length: 17
** Small nails dropped on bench, one falls on metal surface.                                                                                ::
    ID: 07045111.wav
    Length: 3
** Small nails dropped on bench.                                                                                ::
    ID: 07045110.wav
    Length: 1
** Floor nail hammered, changing rhythm with hammer ring.                                                                                ::
    ID: 07045109.wav
    Length: 9
** Floor nail hammered, faster rythm with hammer ring.                                                                                ::
    ID: 07045108.wav
    Length: 10
** Floor nail hammered, slow rhythm with hammer ring.                                                                                ::
    ID: 07045107.wav
    Length: 15
** Tack miss-hit twice and then hammered in.                                                                                ::
    ID: 07045106.wav
    Length: 12
** Large tack nail hammered.                                                                                ::
    ID: 07045105.wav
    Length: 9
** Tack nail hammered.                                                                                ::
    ID: 07045104.wav
    Length: 8
** Tack nail hammered.                                                                                ::
    ID: 07045103.wav
    Length: 10
** Tack nail hammered.                                                                                ::
    ID: 07045102.wav
    Length: 11
** Glass hammered from smashed front door pane, surround levered up.                                                                                ::
    ID: 07045101.wav
    Length: 48
** Chisel hammered and wood levered up.                                                                                ::
    ID: 07045100.wav
    Length: 15
** Chisel hammered with mallet.                                                                                ::
    ID: 07045099.wav
    Length: 2
** Screwdriver removed from toolbox.                                                                                ::
    ID: 07045098.wav
    Length: 3
** Spanner removed from toolbox.                                                                                ::
    ID: 07045097.wav
    Length: 4
** Hand-drill removed from toolbox.                                                                                ::
    ID: 07045096.wav
    Length: 3
** Tools removed from box and put on bench.                                                                                ::
    ID: 07045095.wav
    Length: 29
** Tool box closed.                                                                                ::
    ID: 07045094.wav
    Length: 4
** Tool box opened.                                                                                ::
    ID: 07045093.wav
    Length: 7
** Workshop door closed.                                                                                ::
    ID: 07045092.wav
    Length: 4
** Workshop door opened.                                                                                ::
    ID: 07045091.wav
    Length: 4
** Railway Carriage andbasin tap operated.                                                                                ::
    ID: 07045090.wav
    Length: 8
** Railway Carriage toilet flushed.                                                                                ::
    ID: 07045089.wav
    Length: 16
** Railway Carriage toilet compartment, atmosphere on unwelded track.                                                                                ::
    ID: 07045088.wav
    Length: 125
** Steam Train starts into constant run, various acoustic changes as train passes through cuttings, etc., alows & stops in station. (Seaside Special, recorded leaning out of carriage window.)                                                                                ::
    ID: 07045087.wav
    Length: 477
** Steam Train starts into constant run, passes through tunnel, slows & stops. (Compartment acoustic.)                                                                                ::
    ID: 07045086.wav
    Length: 306
** Railway Carriage, interior, window closed (leather strap type).                                                                                ::
    ID: 07045085.wav
    Length: 3
** Railway Carriage, interior, window opened (leather strap type).                                                                                ::
    ID: 07045084.wav
    Length: 2
** Railway Carriage, interior, door closed.                                                                                ::
    ID: 07045083.wav
    Length: 1
** Railway Carriage, interior, door opened.                                                                                ::
    ID: 07045082.wav
    Length: 1
** Railway Carriage, interior, sliding windows closed.                                                                                ::
    ID: 07045081.wav
    Length: 4
** Railway Carriage, interior, sliding windows opened.                                                                                ::
    ID: 07045080.wav
    Length: 4
** Railway Carriage, interior, compartment double doors closed.                                                                                ::
    ID: 07045079.wav
    Length: 4
** Railway Carriage, interior, compartment double doors opened.                                                                                ::
    ID: 07045078.wav
    Length: 4
** Steam Train passes at very high speed on welded track, left to right. (Vintage reprocessed recording, simulated stereo.)                                                                                ::
    ID: 07045077.wav
    Length: 38
** Steam Train passes at high speed without whistle, right to left.                                                                                ::
    ID: 07045076.wav
    Length: 64
** Steam Train passes at high speed with whistle, right to left.                                                                                ::
    ID: 07045075.wav
    Length: 83
** Steam Train passes at high speed with track noise & whistle, left to right.                                                                                ::
    ID: 07045074.wav
    Length: 62
** Steam Train passes at high speed with track noise & whistle, right to left.                                                                                ::
    ID: 07045073.wav
    Length: 80
** Steam Train climbs steep gradient in cutting, passes left to right & long tail to distance (with heavy natural reverb).                                                                                ::
    ID: 07045072.wav
    Length: 121
** Steam Train coasts past at medium speed, right to left with whistle.                                                                                ::
    ID: 07045071.wav
    Length: 57
** Steam Train coasts past left to right with whistle.                                                                                ::
    ID: 07045070.wav
    Length: 58
** Distant Steam Train starts from station, passes right to left with whistle.                                                                                ::
    ID: 07045069.wav
    Length: 95
** Steam Train approaches from left, coasts past with whistle.                                                                                ::
    ID: 07045068.wav
    Length: 85
** Steam Train coasts past right to left.                                                                                ::
    ID: 07045067.wav
    Length: 79
** Steam Goods Engine shunting trucks, express passes, some distant voices.                                                                                ::
    ID: 07045066.wav
    Length: 309
** Steam Goods Train passes left to right.                                                                                ::
    ID: 07045065.wav
    Length: 53
** Steam Train passes slowly right to left, with distant gunfire.                                                                                ::
    ID: 07045064.wav
    Length: 79
** Steam Train starts up steep gradient & passes left to right.                                                                                ::
    ID: 07045063.wav
    Length: 134
** Steam Train, stationary with blowing safety valve.                                                                                ::
    ID: 07045062.wav
    Length: 110
** Steam Train approaches, stopped by signal, safety valve blowing, signal drops, whistle, train passes left to right, slipping several time on wet track.                                                                                ::
    ID: 07045061.wav
    Length: 189
** Railway Platform atmosphere as distant steam train accelerates up hill, with birdsong.                                                                                ::
    ID: 07045060.wav
    Length: 122
** Steam Train departs from station, to left with one engine pushing & one pulling.                                                                                ::
    ID: 07045059.wav
    Length: 55
** Steam Train departs from station, left to right (long fade to distance).                                                                                ::
    ID: 07045058.wav
    Length: 92
** Steam Train departs from station, left to right, with whistle at start.                                                                                ::
    ID: 07045057.wav
    Length: 45
** Porter's trolley wheeled past, right to left.                                                                                ::
    ID: 07045056.wav
    Length: 13
** Guard's whistle.                                                                                ::
    ID: 07045055.wav
    Length: 1
** Steam Train arrives at station, from left, squealing brakes & doors.                                                                                ::
    ID: 07045054.wav
    Length: 49
** Steam Train arrives at station, from right, squealing brakes & doors.                                                                                ::
    ID: 07045053.wav
    Length: 72
** Stream Train letting off steam.                                                                                ::
    ID: 07045052.wav
    Length: 75
** Steam Train passes through station without stopping, left to right.                                                                                ::
    ID: 07045051.wav
    Length: 64
** Steam train passes through station R-L, another arrives, people disembark.                                                                                ::
    ID: 07045050.wav
    Length: 138
** Steam Engine whistle (London, Midland & Scottish Railway).                                                                                ::
    ID: 07045049.wav
    Length: 4
** Steam Engine whistle (London, Midland & Scottish Railway).                                                                                ::
    ID: 07045048.wav
    Length: 2
