** Old Vic: Applause at end of act, interval chatter.                                                                                :Theatres:Old Vic:
    ID: 07003045.wav
    Length: 63
** Old Vic: Busy speech whilst audience take their seats, full house                                                                                :Theatres:Old Vic:
    ID: 07003044.wav
    Length: 236
** Old Vic: Quiet audience, people entering auditorium with some noise from bars. (Tehnical note for use 2+ low level)                                                                                :Theatres:Old Vic:
    ID: 07003043.wav
    Length: 212
** Quiet atmosphere in a bank, traffic noise increases when door opens.                                                                                ::
    ID: 07003042.wav
    Length: 390
** Quiet transport cafe atmosphere with occasional speech and clatter.                                                                                ::
    ID: 07003041.wav
    Length: 432
** Royal Festival Hall: Atmosphere                                                                                 :London:Royal Festival Hall:
    ID: 07003040.wav
    Length: 215
** Royal Festival Hall: Applause 0m19s quiet                                                                                :London:Royal Festival Hall:
    ID: 07003039.wav
    Length: 30
** Royal Festival Hall: Atmosphere 1m00s applause, 1m22s atmosphere, 1m30s violin tuning to piano                                                                                :London:Royal Festival Hall:
    ID: 07003038.wav
    Length: 117
** Royal Festival Hall: Applause 0m26s quiet                                                                                :London:Royal Festival Hall:
    ID: 07003037.wav
    Length: 37
** Royal Festival Hall: Full orchestra tuning, 3m04s appaluse for conductor                                                                                :London:Royal Festival Hall:
    ID: 07003036.wav
    Length: 206
** Royal Festival Hall:  Applause, at 1' atmosphere.                                                                                :London:Royal Festival Hall:
    ID: 07003035.wav
    Length: 143
** Royal Festival Hall: Closing applause, swelling periodically with 'encores' 4'53" atmosphere                                                                                :London:Royal Festival Hall:
    ID: 07003034.wav
    Length: 313
** Royal Festival Hall:  Applause, at 14" atmosphere, settling down, score rustles, at 25" quartet tuning quiet                                                                                :London:Royal Festival Hall:
    ID: 07003033.wav
    Length: 64
** Royal Festival Hall: Closing applause                                                                                :London:Royal Festival Hall:
    ID: 07003032.wav
    Length: 75
** Royal Festival Hall: Atmosphere, people walking about, distant sound of 5 minute warning gong                                                                                :London:Royal Festival Hall:
    ID: 07003031.wav
    Length: 304
** London Airport: First floor lounge, terminal III & occasional tannoy                                                                                :London:London Airport:First floor lounge:
    ID: 07003030.wav
    Length: 373
** London Airport. Ground floor. Terminal III, lively acoustic, feet, voices, movement, indistinc tannoy                                                                                ::
    ID: 07003029.wav
    Length: 365
** Last Night Of The Proms: Applause, atmosphere                                                                                :Last Night Of The Proms:Applause:
    ID: 07003028.wav
    Length: 25
** Last Night Of The Proms: Applause, atmos, applause                                                                                :Last Night Of The Proms:Applause:
    ID: 07003027.wav
    Length: 142
** Last Night Of The Proms: Wild applause - atmos - applause                                                                                :Last Night Of The Proms:
    ID: 07003026.wav
    Length: 114
** Last Night Of The Proms: Applause - end of item, atmos.                                                                                :Last Night Of The Proms:Applause - end of item, atmos:
    ID: 07003025.wav
    Length: 93
** Last Night Of The Proms: Applause before concert for leader, then conductor, tuning, then more applause                                                                                :Last Night Of The Proms:Applause before concert for leader:
    ID: 07003024.wav
    Length: 138
** Royal Albert Hall: Last Night Of The Proms: General atmosphere                                                                                :London:Royal Albert Hall:
    ID: 07003023.wav
    Length: 347
** Royal Albert Hall: Applause at end of item, with shouts of 'more' & atmosphere                                                                                :London:Royal Albert Hall:
    ID: 07003022.wav
    Length: 135
** Royal Albert Hall: Final applause, some cheers into atmos.                                                                                :London:Royal Albert Hall:
    ID: 07003021.wav
    Length: 212
** Royal Albert Hall: Applause into atmosphere.                                                                                 :London:Royal Albert Hall:
    ID: 07003020.wav
    Length: 57
** Royal Albert Hall: Atmosphere, applause into atmos.                                                                                :London:Royal Albert Hall:
    ID: 07003019.wav
    Length: 30
** Royal Albert Hall: Enthusiastic applause                                                                                :London:Royal Albert Hall:
    ID: 07003018.wav
    Length: 62
** Royal Albert Hall: Chamber orchestra tuning                                                                                :London:Royal Albert Hall:
    ID: 07003017.wav
    Length: 131
** Royal Albert Hall: Symphony orchestra tuning, at 2'52", at 3'40" applause for conductor & quiet atmopshere                                                                                :London:Royal Albert Hall:
    ID: 07003016.wav
    Length: 249
** Royal Albert Hall: Applause, at 47" tuning strings, at 1'23" applause.                                                                                :London:Royal Albert Hall:
    ID: 07003015.wav
    Length: 117
** Royal Albert Hall: Atmosphere, no tuning, fountain & programme seller.                                                                                :London:Royal Albert Hall:
    ID: 07003014.wav
    Length: 339
** Royal Albert Hall: Atmosphere , with tuning & fountain , at 1'09" applause for leader, at 1'27" applause for conductor 1'48" quiet atmosphere                                                                                :London:Royal Albert Hall:
    ID: 07003013.wav
    Length: 120
** Royal Albert Hall: Atmosphere before concert. No tuning                                                                                :London:Royal Albert Hall:
    ID: 07003012.wav
    Length: 302
** Lively Spanish conversation indoors. 10 people.                                                                                ::
    ID: 07003011.wav
    Length: 366
** Indoor conversation at a cocktail party                                                                                ::
    ID: 07003010.wav
    Length: 253
** Crowd atmosphere in Westminster Abbey with voices and footsteps.                                                                                ::
    ID: 07003009.wav
    Length: 404
** Church atmosphere with crowd.                                                                                ::
    ID: 07003008.wav
    Length: 377
** Atmosphere recorded in John Lewis department store.                                                                                ::
    ID: 07003007.wav
    Length: 336
** Atmosphere recorded in British Home Stores.                                                                                ::
    ID: 07003006.wav
    Length: 299
** Atmosphere, feet, distant traffic distant clock, recorded in Westminster Abbey, London                                                                                ::
    ID: 07003005.wav
    Length: 359
** St. Pauls Cathederal, London. Atmosphere                                                                                ::
    ID: 07003004.wav
    Length: 110
** St. Paul's Cathedral, London. Atmosphere in Whispering Gallery.                                                                                 ::
    ID: 07003003.wav
    Length: 295
** Extension reception hall.                                                                                ::
    ID: 07003002.wav
    Length: 454
** Main reception hall.                                                                                 ::
    ID: 07003001.wav
    Length: 473
** One start, drive out of shed, harrow hitched, drives to and fro, harrow unhitched, returns to shed. (Perkins-Fordson                                                                                 ::
    ID: 07002331.wav
    Length: 270
** One start, tickover, switch off. (Perkins-Fordson tractor)                                                                                ::
    ID: 07002330.wav
    Length: 94
** One passing. (Perkins-Fordson tractor)                                                                                ::
    ID: 07002329.wav
    Length: 90
** One passing. (Perkins-Fordson tractor)                                                                                ::
    ID: 07002328.wav
    Length: 128
** One approach and stop. (Perkins-Fordson Tractor)                                                                                ::
    ID: 07002327.wav
    Length: 28
** One start and depart. (Perkins-Fordson tractor)                                                                                ::
    ID: 07002326.wav
    Length: 78
** A 160 foot elm felled by chain saw driven by a 2-stroke motor, wedges hammered in at 4', tree falls.                                                                                ::
    ID: 07002325.wav
    Length: 390
** A tractor starts up, driving a circular saw, sawing ends, tractor switched off.                                                                                ::
    ID: 07002324.wav
    Length: 344
** Chopping a tree with an axe, some bird song.                                                                                ::
    ID: 07002323.wav
    Length: 32
** Footsteps walking through undergrowth. Several people walking through.                                                                                ::
    ID: 07002322.wav
    Length: 236
** Footsteps walking through undergrowth.                                                                                 ::
    ID: 07002321.wav
    Length: 95
** Tree branches being chopped by axe. Several men chopping branches.                                                                                ::
    ID: 07002320.wav
    Length: 123
** Tree branches being chopped by axe. One man chopping branch.                                                                                ::
    ID: 07002319.wav
    Length: 125
** Tree branches being chopped by axe. One man chopping branch.                                                                                ::
    ID: 07002318.wav
    Length: 113
** Hand-pressing of hops.                                                                                ::
    ID: 07002317.wav
    Length: 213
** A potato riddling machine, constant run.                                                                                ::
    ID: 07002316.wav
    Length: 178
** Potato harvester starting, running, stopping. (Outside machine)                                                                                 ::
    ID: 07002315.wav
    Length: 203
** Potato harvester starting, running, stopping. (Inside machine)                                                                                 ::
    ID: 07002314.wav
    Length: 204
** A potato riddling machine switched on, runs, switched off.                                                                                ::
    ID: 07002313.wav
    Length: 209
** A carrot and beetroot washing machine switched on, runs, switched off.                                                                                ::
    ID: 07002312.wav
    Length: 196
** Winnowing machine. Start, corn fed in, corn seperated from chaff; machine switched off. (Sieve End)                                                                                ::
    ID: 07002311.wav
    Length: 202
** Winnowing machine. Start, corn fed in, corn seperated from chaff; machine switched off.                                                                                ::
    ID: 07002310.wav
    Length: 187
** A winnowing machine starts, runs with no corn and stops.                                                                                ::
    ID: 07002309.wav
    Length: 207
** A corn sucker feeding corn from silo to lorry                                                                                ::
    ID: 07002308.wav
    Length: 190
** Grain stacker blowing corn through funnel from trailer to silo. (Inside silo)                                                                                ::
    ID: 07002307.wav
    Length: 215
** Grain stacker blowing corn through funnel from trailer to silo. (Outside silo)                                                                                ::
    ID: 07002306.wav
    Length: 145
** A tractor-drawn straw baler approaches, bales and departs.                                                                                ::
    ID: 07002305.wav
    Length: 212
** A tractor-drawn straw baler commences to bale and departs.                                                                                ::
    ID: 07002304.wav
    Length: 183
** A tractor-drawn straw baler approaches, bales and stops.                                                                                ::
    ID: 07002303.wav
    Length: 146
** Combine Harvester. Starts, runs and harvests, stops. (Recorded at discharging end)                                                                                ::
    ID: 07002302.wav
    Length: 234
** Combine Harvester. Starts, runs and harvests, stops.                                                                                ::
    ID: 07002301.wav
    Length: 373
** Combine Harvester. Starts and departs.                                                                                ::
    ID: 07002300.wav
    Length: 73
** Combine Harvester. Approaches and passes.                                                                                ::
    ID: 07002299.wav
    Length: 91
** Combine Harvester. Approaches and stops, moves into cutting position and departs                                                                                ::
    ID: 07002298.wav
    Length: 194
** Drum threshing machine in operation. Pitching side. Runs, stops.                                                                                ::
    ID: 07002297.wav
    Length: 53
** Drum threshing machine in operation. Pitching side. Starts, runs, stops.                                                                                ::
    ID: 07002296.wav
    Length: 305
** Drum threshing machine in operation. Runs, stops,                                                                                 ::
    ID: 07002295.wav
    Length: 48
** Drum threshing machine in operation. Starts, runs, stops,                                                                                 ::
    ID: 07002294.wav
    Length: 297
** Tree falling                                                                                ::
    ID: 07002293.wav
    Length: 18
** A two-stroke band saw being used for felling tree, start, run, tree felled at 1'15"                                                                                ::
    ID: 07002292.wav
    Length: 90
** A two-stroke band saw being used for felling tree, start, run, stop.                                                                                ::
    ID: 07002291.wav
    Length: 167
** A two-stroke band saw being used for felling tree, start, run, stop.                                                                                ::
    ID: 07002290.wav
    Length: 101
** Start, constant run, stop. (Recorded behind Massey Ferguson Motor Mower drawn by tractor)                                                                                ::
    ID: 07002289.wav
    Length: 137
** Approach, turn, depart. (Massey Ferguson Motor Mower drawn by tractor)                                                                                ::
    ID: 07002288.wav
    Length: 97
** Start, depart. (Massey Ferguson Motor Mower drawn by tractor)                                                                                ::
    ID: 07002287.wav
    Length: 125
** Exterior, seed lids closed, tractor start up, seed drills, stop. (Ferguson tractor)                                                                                ::
    ID: 07002286.wav
    Length: 197
** Exterior, start up, ploughing and passing to and fro, stop. (Ferguson tractor)                                                                                ::
    ID: 07002285.wav
    Length: 206
** Start up, mowing, stop. (Rec. on Ferguson tractor)                                                                                ::
    ID: 07002284.wav
    Length: 116
** Long approach & stop. (Ferguson tractor)                                                                                ::
    ID: 07002283.wav
    Length: 101
** Start up, tickover, depart. (Ferguson tractor)                                                                                ::
    ID: 07002282.wav
    Length: 53
** Start up, tickover, switch off. (Ferguson tractor)                                                                                ::
    ID: 07002281.wav
    Length: 84
** One tractor, start up, passes to & fro, stop.                                                                                ::
    ID: 07002280.wav
    Length: 178
** One tractor, passing.                                                                                ::
    ID: 07002279.wav
    Length: 48
** One tractor, approach & stop.                                                                                ::
    ID: 07002278.wav
    Length: 48
** One tractor, start up, depart.                                                                                ::
    ID: 07002277.wav
    Length: 58
** One tractor, start up, constant run, stop. (Recorded on tractor)                                                                                ::
    ID: 07002276.wav
    Length: 307
** One tractor, start up, tickover, switch off.                                                                                ::
    ID: 07002275.wav
    Length: 70
** Church clock striking, 12 o'clock. (All Saints Church)                                                                                ::
    ID: 07002274.wav
    Length: 34
** Church clock striking, 11 o'clock. (All Saints Church)                                                                                ::
    ID: 07002273.wav
    Length: 30
** Church clock striking, 10 o'clock. (All Saints Church)                                                                                ::
    ID: 07002272.wav
    Length: 28
** Church clock striking, 9 o'clock. (All Saints Church)                                                                                ::
    ID: 07002271.wav
    Length: 26
** Church clock striking, 8 o'clock. (All Saints Church)                                                                                ::
    ID: 07002270.wav
    Length: 24
** Church clock striking, 7 o'clock. (All Saints Church)                                                                                ::
    ID: 07002269.wav
    Length: 23
** Church clock striking, 6 o'clock. (All Saints Church)                                                                                ::
    ID: 07002268.wav
    Length: 19
** Church clock striking, 5 o'clock. (All Saints Church)                                                                                ::
    ID: 07002267.wav
    Length: 18
** Church clock striking, 4 o'clock. (All Saints Church)                                                                                ::
    ID: 07002266.wav
    Length: 17
** Church clock striking, 3 o'clock. (All Saints Church)                                                                                ::
    ID: 07002265.wav
    Length: 15
** Church clock striking, 2 o'clock. (All Saints Church)                                                                                ::
    ID: 07002264.wav
    Length: 13
** Church clock striking, 1 o'clock. (All Saints Church)                                                                                ::
    ID: 07002263.wav
    Length: 9
** Church clock striking, 12 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002262.wav
    Length: 30
** Church clock striking, 11 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002261.wav
    Length: 28
** Church clock striking, 10 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002260.wav
    Length: 25
** Church clock striking, 9 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002259.wav
    Length: 23
** Church clock striking, 8 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002258.wav
    Length: 21
** Church clock striking, 7 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002257.wav
    Length: 20
** Church clock striking, 6 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002256.wav
    Length: 17
** Church clock striking, 5 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002255.wav
    Length: 16
** Church clock striking, 4 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002254.wav
    Length: 15
** Church clock striking, 3 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002253.wav
    Length: 13
** Church clock striking, 2 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002252.wav
    Length: 12
** Church clock striking, 1 o'clock. (St. John the Evangelist)                                                                                ::
    ID: 07002251.wav
    Length: 11
** Osterley House Clock striking 12 o'clock                                                                                ::
    ID: 07002250.wav
    Length: 36
** Osterley House Clock striking 11 o'clock                                                                                ::
    ID: 07002249.wav
    Length: 33
** Osterley House Clock striking 10 o'clock                                                                                ::
    ID: 07002248.wav
    Length: 30
** Osterley House Clock striking 9 o'clock                                                                                ::
    ID: 07002247.wav
    Length: 27
** Osterley House Clock striking 8 o'clock                                                                                ::
    ID: 07002246.wav
    Length: 25
** Osterley House Clock striking 7 o'clock                                                                                ::
    ID: 07002245.wav
    Length: 23
** Osterley House Clock striking 6 o'clock                                                                                ::
    ID: 07002244.wav
    Length: 20
** Osterley House Clock striking 5 o'clock                                                                                ::
    ID: 07002243.wav
    Length: 18
** Osterley House Clock striking 4 o'clock                                                                                ::
    ID: 07002242.wav
    Length: 16
** Osterley House Clock striking 3 o'clock                                                                                ::
    ID: 07002241.wav
    Length: 13
** Osterley House Clock striking 2 o'clock                                                                                ::
    ID: 07002240.wav
    Length: 11
** Osterley House Clock striking, 1 o'clock                                                                                ::
    ID: 07002239.wav
    Length: 8
** Mechanism                                                                                ::
    ID: 07002238.wav
    Length: 205
** Anne Boleyn's Clock, chimes & 12 o'clock                                                                                ::
    ID: 07002237.wav
    Length: 56
** Anne Boleyn's Clock, chimes & 11 o'clock                                                                                ::
    ID: 07002236.wav
    Length: 52
** Anne Boleyn's Clock, chimes & 10 o'clock                                                                                ::
    ID: 07002235.wav
    Length: 47
** Anne Boleyn's Clock, chimes & 9 o'clock                                                                                ::
    ID: 07002234.wav
    Length: 44
** Anne Boleyn's Clock, chimes & 8 o'clock                                                                                ::
    ID: 07002233.wav
    Length: 43
** Anne Boleyn's Clock, chimes & 7 o'clock                                                                                ::
    ID: 07002232.wav
    Length: 41
** Anne Boleyn's Clock, chimes & 6 o'clock                                                                                ::
    ID: 07002231.wav
    Length: 37
** Anne Boleyn's Clock, chimes & 5 o'clock                                                                                ::
    ID: 07002230.wav
    Length: 33
** Anne Boleyn's Clock, chimes & 4 o'clock                                                                                ::
    ID: 07002229.wav
    Length: 33
** Anne Boleyn's Clock chimes & 3 o'clock                                                                                ::
    ID: 07002228.wav
    Length: 31
** Anne Boleyn's Clock chimes & 2 o'clock                                                                                ::
    ID: 07002227.wav
    Length: 27
** Anne Boleyn's Clock chimes & 1 o'clock                                                                                ::
    ID: 07002226.wav
    Length: 22
** Anne Boleyn's Clock striking three-quarters                                                                                ::
    ID: 07002225.wav
    Length: 20
** Anne Boleyn's Clock striking quarter-hour                                                                                ::
    ID: 07002224.wav
    Length: 17
** Anne Boleyn's Clock striking half-hour                                                                                ::
    ID: 07002223.wav
    Length: 16
** Outdoor clock striking, 12 o'clock - SS. Peter & Paul                                                                                ::
    ID: 07002222.wav
    Length: 79
** Outdoor clock striking, 11 o'clock - SS. Peter & Paul                                                                                ::
    ID: 07002221.wav
    Length: 73
** Outdoor clock striking, 10 o'clock - SS. Peter & Paul                                                                                ::
    ID: 07002220.wav
    Length: 68
** Outdoor clock striking, 9 o'clock - SS. Peter & Paul                                                                                 ::
    ID: 07002219.wav
    Length: 65
** Outdoor clock striking, chimes & 8 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002218.wav
    Length: 60
** Outdoor clock striking, chimes & 7 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002217.wav
    Length: 58
** Outdoor clock striking, chimes & 6 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002216.wav
    Length: 56
** Outdoor clock striking, chimes & 5 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002215.wav
    Length: 54
** Outdoor clock striking, chimes & 4 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002214.wav
    Length: 49
** Outdoor clock striking, chimes & 3 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002213.wav
    Length: 46
** Outdoor clock striking, chimes & 2 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002212.wav
    Length: 45
** Outdoor clock striking, chimes & 1 o'clock  SS. Peter & Paul                                                                                 ::
    ID: 07002211.wav
    Length: 39
** Outdoor clock striking, three-quarters - SS. Peter & Paul                                                                                 ::
    ID: 07002210.wav
    Length: 37
** Outdoor clock striking, half-hour - SS. Peter & Paul                                                                                 ::
    ID: 07002209.wav
    Length: 28
** Outdoor clock striking, quarter-hour - SS. Peter & Paul                                                                                 ::
    ID: 07002208.wav
    Length: 27
** Outdoor clock striking, 12 o'clock St. Mary's Church                                                                                ::
    ID: 07002207.wav
    Length: 47
** Outdoor clock striking, 11 o'clock St. Mary's Church                                                                                ::
    ID: 07002206.wav
    Length: 43
** Outdoor clock striking, 10 o'clock St. Mary's Church                                                                                ::
    ID: 07002205.wav
    Length: 41
** Outdoor clock striking, 9 o'clock St. Mary's Church                                                                                ::
    ID: 07002204.wav
    Length: 38
** Outdoor clock striking, 8 o'clock St. Mary's Church                                                                                ::
    ID: 07002203.wav
    Length: 36
** Outdoor clock striking, 7 o'clock St. Mary's Church                                                                                ::
    ID: 07002202.wav
    Length: 32
** Outdoor clock striking, 6 o'clock St. Mary's Church                                                                                ::
    ID: 07002201.wav
    Length: 28
** Outdoor clock striking, 5 o'clock St. Mary's Church                                                                                ::
    ID: 07002200.wav
    Length: 26
** Outdoor clock striking, 4 o'clock St. Mary's Church                                                                                ::
    ID: 07002199.wav
    Length: 25
** Outdoor clock striking, 3 o'clock St. Mary's Church                                                                                ::
    ID: 07002198.wav
    Length: 21
** Outdoor clock striking, 2 o'clock St. Mary's Church                                                                                ::
    ID: 07002197.wav
    Length: 21
** Outdoor clock striking, 1 o'clock St. Mary's Church                                                                                ::
    ID: 07002196.wav
    Length: 16
** Outdoor clock striking, 12 o'clock                                                                                ::
    ID: 07002195.wav
    Length: 31
** Outdoor clock striking, 11 o'clock                                                                                ::
    ID: 07002194.wav
    Length: 28
** Outdoor clock striking, 10 o'clock                                                                                ::
    ID: 07002193.wav
    Length: 26
** Outdoor clock striking, 9 o'clock                                                                                ::
    ID: 07002192.wav
    Length: 26
** Outdoor clock striking, 8 o'clock                                                                                ::
    ID: 07002191.wav
    Length: 24
** Outdoor clock striking, 7 o'clock                                                                                ::
    ID: 07002190.wav
    Length: 23
** Outdoor clock striking, 6 o'clock                                                                                ::
    ID: 07002189.wav
    Length: 21
** Outdoor clock striking, 5 o'clock                                                                                ::
    ID: 07002188.wav
    Length: 18
** Outdoor clock striking, 4 o'clock                                                                                ::
    ID: 07002187.wav
    Length: 18
** Outdoor clock striking, 3 o'clock                                                                                ::
    ID: 07002186.wav
    Length: 16
** Outdoor clock striking, 2 o'clock                                                                                ::
    ID: 07002185.wav
    Length: 15
** Outdoor clock striking, 1 o'clock                                                                                ::
    ID: 07002184.wav
    Length: 13
** Sound of carillon playing 'Oranges and Lemons'. St. Clement Danes Church, London                                                                                ::
    ID: 07002183.wav
    Length: 283
** St. Clement Danes Church Clock, striking 2 o'clock followed by Oranges & Lemons                                                                                ::
    ID: 07002182.wav
    Length: 201
** St. Clement Danes Church Clock, striking three-quarters                                                                                ::
    ID: 07002181.wav
    Length: 28
** St. Clement Danes Church Clock, striking half-hour                                                                                ::
    ID: 07002180.wav
    Length: 24
** St. Clement Danes Church Clock, striking quarter-hour                                                                                ::
    ID: 07002179.wav
    Length: 25
** Great Tom clock with street atmosphere                                                                                ::
    ID: 07002178.wav
    Length: 184
** Great Tom clock with street atmosphere striking 12 o'clock                                                                                ::
    ID: 07002177.wav
    Length: 79
** Great Tom clock with street atmosphere striking three-quarters                                                                                ::
    ID: 07002176.wav
    Length: 35
** Great Tom clock with street atmosphere striking half-hour.                                                                                ::
    ID: 07002175.wav
    Length: 34
** Great Tom clock with street atmosphere striking quarter-hour                                                                                ::
    ID: 07002174.wav
    Length: 34
** Great Tom clock striking 12 o'clock                                                                                ::
    ID: 07002173.wav
    Length: 80
** Great Tom clock striking 11 o'clock                                                                                ::
    ID: 07002172.wav
    Length: 75
** Great Tom clock striking 10 o'clock                                                                                ::
    ID: 07002171.wav
    Length: 70
** Great Tom clock striking 9 o'clock                                                                                ::
    ID: 07002170.wav
    Length: 68
** Great Tom clock striking 8 o'clock                                                                                ::
    ID: 07002169.wav
    Length: 66
** Great Tom clock striking 7 o'clock                                                                                ::
    ID: 07002168.wav
    Length: 60
** Great Tom clock striking 6 o'clock                                                                                ::
    ID: 07002167.wav
    Length: 57
** Great Tom clock striking 5 o'clock                                                                                ::
    ID: 07002166.wav
    Length: 53
** Great Tom clock striking 4 o'clock                                                                                ::
    ID: 07002165.wav
    Length: 51
** Great Tom clock striking 3 o'clock                                                                                ::
    ID: 07002164.wav
    Length: 47
** Great Tom clock striking 2 o'clock                                                                                ::
    ID: 07002163.wav
    Length: 44
** Great Tom clock striking 1 o'clock                                                                                ::
    ID: 07002162.wav
    Length: 42
** Great Tom clock striking three-quarters                                                                                ::
    ID: 07002161.wav
    Length: 30
** Great Tom clock striking half-hour                                                                                ::
    ID: 07002160.wav
    Length: 27
** Great Tom clock striking quarter-hour                                                                                ::
    ID: 07002159.wav
    Length: 25
** Gound level with traffic in 1969. 12 o'clock                                                                                ::
    ID: 07002158.wav
    Length: 182
** Gound level with traffic in 1969. 1 o'clock                                                                                ::
    ID: 07002157.wav
    Length: 47
** Gound level with traffic in 1969. Three-quarters                                                                                ::
    ID: 07002156.wav
    Length: 40
** Gound level with traffic in 1969. Half-hour                                                                                ::
    ID: 07002155.wav
    Length: 35
** Gound level with traffic in 1969. Quarter-hour                                                                                ::
    ID: 07002154.wav
    Length: 30
** Big Ben recorded in 1969. 12                                                                                ::
    ID: 07002153.wav
    Length: 92
** Big Ben recorded in 1969. 11                                                                                ::
    ID: 07002152.wav
    Length: 85
** Big Ben recorded in 1969. 10                                                                                ::
    ID: 07002151.wav
    Length: 78
** Big Ben recorded in 1969. 9 o'clock                                                                                ::
    ID: 07002150.wav
    Length: 76
** Big Ben recorded in 1969. 8 o'clock                                                                                ::
    ID: 07002149.wav
    Length: 82
** Big Ben recorded in 1969. 7 o'clock                                                                                ::
    ID: 07002148.wav
    Length: 65
** Big Ben recorded in 1969. 6 o'clock                                                                                ::
    ID: 07002147.wav
    Length: 59
** Big Ben recorded in 1969. 5 o'clock                                                                                ::
    ID: 07002146.wav
    Length: 61
** Big Ben recorded in 1969. 4 o'clock                                                                                ::
    ID: 07002145.wav
    Length: 58
** Big Ben recorded in 1969. 3 o'clock                                                                                ::
    ID: 07002144.wav
    Length: 54
** Big Ben recorded in 1969. 2 o'clock                                                                                ::
    ID: 07002143.wav
    Length: 52
** Big Ben recorded in 1969. 1 o'clock                                                                                ::
    ID: 07002142.wav
    Length: 45
** Big Ben recorded in 1969. Three-quarters                                                                                ::
    ID: 07002141.wav
    Length: 32
** Big Ben recorded in 1969. Half-hour                                                                                ::
    ID: 07002140.wav
    Length: 28
** Big Ben recorded in 1969. Quarter-hour                                                                                ::
    ID: 07002139.wav
    Length: 28
** Sound of Big Ben ticking.                                                                                ::
    ID: 07002138.wav
    Length: 186
** Sound of Big Ben chiming and striking 12 o'clock, recorded prior to repair in 1956. (Inside clock tower)                                                                                ::
    ID: 07002137.wav
    Length: 87
** Greenwich Time Signal, pips                                                                                ::
    ID: 07002136.wav
    Length: 9
** Greenwich Time Signal, pips                                                                                ::
    ID: 07002135.wav
    Length: 9
** Big Ben recorded prior to repair in 1956. 12 o'clock                                                                                ::
    ID: 07002134.wav
    Length: 85
** Big Ben recorded prior to repair in 1956. 11 o'clock                                                                                ::
    ID: 07002133.wav
    Length: 79
** Big Ben recorded prior to repair in 1956. 10 o'clock                                                                                ::
    ID: 07002132.wav
    Length: 74
** Big Ben recorded prior to repair in 1956. 9 o'clock                                                                                ::
    ID: 07002131.wav
    Length: 71
** Big Ben recorded prior to repair in 1956. 8 o'clock                                                                                ::
    ID: 07002130.wav
    Length: 68
** Big Ben recorded prior to repair in 1956. 7 o'clock                                                                                ::
    ID: 07002129.wav
    Length: 63
** Big Ben recorded prior to repair in 1956. 6 o'clock                                                                                ::
    ID: 07002128.wav
    Length: 60
** Big Ben recorded prior to repair in 1956. 5 o'clock                                                                                ::
    ID: 07002127.wav
    Length: 52
** Big Ben recorded prior to repair in 1956. 4 o'clock                                                                                ::
    ID: 07002126.wav
    Length: 51
** Big Ben recorded prior to repair in 1956. 3 o'clock                                                                                ::
    ID: 07002125.wav
    Length: 47
** Big Ben recorded prior to repair in 1956. 2 o'clock                                                                                ::
    ID: 07002124.wav
    Length: 43
** Big Ben recorded prior to repair in 1956. 1 o'clock                                                                                ::
    ID: 07002123.wav
    Length: 38
** Big Ben recorded prior to repair in 1956. Three-quarters                                                                                ::
    ID: 07002122.wav
    Length: 34
** Big Ben recorded prior to repair in 1956. Half-hour                                                                                ::
    ID: 07002121.wav
    Length: 29
** Big Ben recorded prior to repair in 1956. Quarter hour                                                                                ::
    ID: 07002120.wav
    Length: 26
** Clearing a table after a meal.                                                                                ::
    ID: 07002119.wav
    Length: 89
** Laying a table in preparation for a meal.                                                                                ::
    ID: 07002118.wav
    Length: 92
** A tap dripping, fast double drip.                                                                                ::
    ID: 07002117.wav
    Length: 185
** Tap dripping. Slow dripping                                                                                ::
    ID: 07002116.wav
    Length: 188
** Tap dripping. Fast dripping.                                                                                ::
    ID: 07002115.wav
    Length: 187
** Two milk bottles placed on step.                                                                                ::
    ID: 07002114.wav
    Length: 21
** Clatter of utensils on kitchen range.                                                                                ::
    ID: 07002113.wav
    Length: 121
** Beating an egg with a spatula.                                                                                ::
    ID: 07002112.wav
    Length: 65
** Beating an egg with a fork.                                                                                ::
    ID: 07002111.wav
    Length: 42
** Cracking an egg into a basin.                                                                                ::
    ID: 07002110.wav
    Length: 11
** Pouring liquid into large cups.                                                                                ::
    ID: 07002109.wav
    Length: 31
** Laying heavy crockery on wooden table. (Period)                                                                                ::
    ID: 07002108.wav
    Length: 57
** Liquid poured into four glasses.                                                                                ::
    ID: 07002107.wav
    Length: 26
** A bucket dropped three times.                                                                                ::
    ID: 07002106.wav
    Length: 18
** A flit spray operated. (Fly spray)                                                                                ::
    ID: 07002105.wav
    Length: 35
** A match struck three times.                                                                                ::
    ID: 07002104.wav
    Length: 27
** A soda water siphon operated, 1 long blast, 2 short blasts, 1 long blast, 3 short blasts.                                                                                ::
    ID: 07002103.wav
    Length: 24
** Chopping firewood.                                                                                ::
    ID: 07002102.wav
    Length: 65
** Beating a carpet.                                                                                ::
    ID: 07002101.wav
    Length: 66
** A knitting machine being operated.                                                                                ::
    ID: 07002100.wav
    Length: 63
** Sound of clothes being washed on a dolly board.                                                                                ::
    ID: 07002099.wav
    Length: 152
** A gas meter, one two-shilling piece inserted.                                                                                ::
    ID: 07002098.wav
    Length: 11
** An electricity meter, two two-shilling pieces inserted.                                                                                ::
    ID: 07002097.wav
    Length: 17
** An electricity meter, two one-shilling pieces inserted.                                                                                ::
    ID: 07002096.wav
    Length: 22
** A gas meter, two one-shilling pieces inserted.                                                                                ::
    ID: 07002095.wav
    Length: 25
** An electric coffee bean roasting machine, switch on, run, switch off.                                                                                ::
    ID: 07002094.wav
    Length: 121
** Raking coffee beans to remove husks.                                                                                ::
    ID: 07002093.wav
    Length: 19
** A dustbin lid falling and being replaced.                                                                                ::
    ID: 07002092.wav
    Length: 15
** Sound of coffee beans being roasted by hand.                                                                                ::
    ID: 07002091.wav
    Length: 84
** Cutting bread with a saw knife.                                                                                ::
    ID: 07002090.wav
    Length: 58
** Scrubbing a wooden table.                                                                                ::
    ID: 07002089.wav
    Length: 133
** Opening two cans with a wall-type opener.                                                                                ::
    ID: 07002088.wav
    Length: 30
** A hand operated food mixer.                                                                                ::
    ID: 07002087.wav
    Length: 96
** Sound of fish frying in a pan.                                                                                ::
    ID: 07002086.wav
    Length: 185
** Three cork pops.                                                                                ::
    ID: 07002085.wav
    Length: 13
** Grating vegetables by hand.                                                                                ::
    ID: 07002084.wav
    Length: 63
** Mechanical food cutter being used in a kitchen.                                                                                ::
    ID: 07002083.wav
    Length: 70
** Cutting and chopping food on a board.                                                                                ::
    ID: 07002082.wav
    Length: 93
** Sharpening a knife in a kitchen.                                                                                ::
    ID: 07002081.wav
    Length: 31
** Crockery and cutlery being washed up.                                                                                ::
    ID: 07002080.wav
    Length: 118
** Opening a can by hand.                                                                                ::
    ID: 07002079.wav
    Length: 67
** A coffee percolator bubbling.                                                                                ::
    ID: 07002078.wav
    Length: 126
** A whistling kettle.                                                                                ::
    ID: 07002077.wav
    Length: 28
** A kettle boiling.                                                                                ::
    ID: 07002076.wav
    Length: 122
** Lid removed and kettle filled with water.                                                                                ::
    ID: 07002075.wav
    Length: 24
** Several electric light switches operated.                                                                                ::
    ID: 07002074.wav
    Length: 44
** A pop-up electric toaster. (Operated three times)                                                                                ::
    ID: 07002073.wav
    Length: 13
** A gas stove burner roar. (Natural gas)                                                                                ::
    ID: 07002072.wav
    Length: 61
** Emptying hod of coal into grate.                                                                                ::
    ID: 07002071.wav
    Length: 14
** Filling a plastic coal hod. (Twice)                                                                                ::
    ID: 07002070.wav
    Length: 66
** Filling iron bucket with water.                                                                                ::
    ID: 07002069.wav
    Length: 57
** Filling a plastic watering-can with water.                                                                                ::
    ID: 07002068.wav
    Length: 60
** Filling a saucepan with water.                                                                                ::
    ID: 07002067.wav
    Length: 32
** Water running into sink. (Tap full on)                                                                                ::
    ID: 07002066.wav
    Length: 41
** Water running into sink. (Plug out, tap half on)                                                                                ::
    ID: 07002065.wav
    Length: 152
** A kettle filled with water.                                                                                ::
    ID: 07002064.wav
    Length: 29
** A teapot filled with water.                                                                                ::
    ID: 07002063.wav
    Length: 15
** Match struck, gas mantle lit and burns. (Gas light)                                                                                ::
    ID: 07002062.wav
    Length: 134
** A gas water boiler lit, burns.                                                                                ::
    ID: 07002061.wav
    Length: 50
** A gas grill lit, burns.                                                                                ::
    ID: 07002060.wav
    Length: 60
** A gas fire lit. (Ignites twice)                                                                                ::
    ID: 07002059.wav
    Length: 10
** A gas poker lit and burns.                                                                                ::
    ID: 07002058.wav
    Length: 77
** Open coal fire burning.                                                                                ::
    ID: 07002057.wav
    Length: 181
** Open coal fire, poking fire and adding coal.                                                                                ::
    ID: 07002056.wav
    Length: 43
** Riddling a boiler fire.                                                                                ::
    ID: 07002055.wav
    Length: 33
** Open coal fire, shovelling coal into a rubber hod.                                                                                ::
    ID: 07002054.wav
    Length: 36
** Open coal fire, shovelling coal into a metal hod.                                                                                ::
    ID: 07002053.wav
    Length: 24
** Open fireplace. Match struck; fire lit; crackle of flames                                                                                ::
    ID: 07002052.wav
    Length: 173
** Open fireplace. Laying fire                                                                                ::
    ID: 07002051.wav
    Length: 31
** Open fireplace. Shovelling out cinders                                                                                ::
    ID: 07002050.wav
    Length: 31
** Open fireplace. Brushing out                                                                                ::
    ID: 07002049.wav
    Length: 29
** Open fireplace. Raking out.                                                                                 ::
    ID: 07002048.wav
    Length: 36
** Old-fashioned mangle operated with washing in rollers. (With squeak)                                                                                ::
    ID: 07002047.wav
    Length: 101
** Old-fashioned mangle operated with washing in rollers.                                                                                ::
    ID: 07002046.wav
    Length: 123
** Old-fashioned mangle operated without washing.                                                                                ::
    ID: 07002045.wav
    Length: 39
** Old-fashioned mangle. tin bath moved in preparation for drying clothes.                                                                                ::
    ID: 07002044.wav
    Length: 20
** Old-fashioned mangle moved on stone floor.                                                                                ::
    ID: 07002043.wav
    Length: 31
** Breaking ice in bucket.                                                                                ::
    ID: 07002042.wav
    Length: 56
** An electric trimmer switched off.                                                                                ::
    ID: 07002041.wav
    Length: 11
** An electric trimmer switched on, runs.                                                                                ::
    ID: 07002040.wav
    Length: 65
** An electric shaver switched off.                                                                                ::
    ID: 07002039.wav
    Length: 9
** An electric shaver switched on, runs.                                                                                ::
    ID: 07002038.wav
    Length: 93
** An electronic metal detector operating.                                                                                ::
    ID: 07002037.wav
    Length: 91
** A blowlamp turned off.                                                                                ::
    ID: 07002036.wav
    Length: 13
** A blowlamp re-lit, runs with pumping from 19"                                                                                ::
    ID: 07002035.wav
    Length: 138
** Pumping a blowlamp.                                                                                ::
    ID: 07002034.wav
    Length: 26
** Failed attempt to start a blowlamp.                                                                                ::
    ID: 07002033.wav
    Length: 41
** A refrigerator hum with switch on and off                                                                                ::
    ID: 07002032.wav
    Length: 121
** A refrigerator hum with switch on and off.                                                                                ::
    ID: 07002031.wav
    Length: 130
** A deep-freezer motor hum.                                                                                ::
    ID: 07002030.wav
    Length: 123
** A refrigerator hum with switch on and off                                                                                ::
    ID: 07002029.wav
    Length: 121
** A refrigerator hum with switch on and off                                                                                ::
    ID: 07002028.wav
    Length: 124
** A strip lighting hum.                                                                                ::
    ID: 07002027.wav
    Length: 121
** An electric food mixer, potato peeler switched on, runs, switched off.                                                                                ::
    ID: 07002026.wav
    Length: 128
** An electric food mixer, liquidizer switched on, runs, switched off.                                                                                ::
    ID: 07002025.wav
    Length: 132
** An electric food mixer, mixing dough, switch on, runs, switch off.                                                                                ::
    ID: 07002024.wav
    Length: 124
** An electric food mixer, liquid in bowl, switch on, fast run, switch off.                                                                                ::
    ID: 07002023.wav
    Length: 126
** An electric food mixer, liquid in bowl, switch on, run, switch off.                                                                                ::
    ID: 07002022.wav
    Length: 129
** An electric food mixer, empty bowl, switch on, run, switch off.                                                                                ::
    ID: 07002021.wav
    Length: 125
** Electric automatic washing machine. Background; hum of boiler                                                                                ::
    ID: 07002020.wav
    Length: 125
** Electric automatic washing machine. Cleaning & replacing parts of machine                                                                                ::
    ID: 07002019.wav
    Length: 125
** Electric automatic washing machine. Pumping out water (at water outlet)                                                                                ::
    ID: 07002018.wav
    Length: 125
** Electric automatic washing machine. Pumping out water after final wash                                                                                ::
    ID: 07002017.wav
    Length: 122
** Electric automatic washing machine. Spin dryer, water pump                                                                                ::
    ID: 07002016.wav
    Length: 143
** Electric automatic washing machine. Spin dryer operating at high speed.                                                                                 ::
    ID: 07002015.wav
    Length: 139
** Electric automatic washing mashine. Spin dryer, pumping water away                                                                                ::
    ID: 07002014.wav
    Length: 126
** Electric automatic washing mashine. Agitator                                                                                ::
    ID: 07002013.wav
    Length: 126
** Electric automatic washing mashine. Sizzle of soapsuds                                                                                ::
    ID: 07002012.wav
    Length: 122
** Electric automatic washing mashine. Water boiling                                                                                ::
    ID: 07002011.wav
    Length: 158
** Electric automatic washing mashine. Filling with water                                                                                ::
    ID: 07002010.wav
    Length: 152
** Electric automatic washing machine. Preparing machine, general background.                                                                                 ::
    ID: 07002009.wav
    Length: 57
** Junior type vacuum cleaner, stopping on carpet.                                                                                ::
    ID: 07002008.wav
    Length: 8
** Junior type vacuum cleaner, start, constant run on carpet.                                                                                ::
    ID: 07002007.wav
    Length: 168
** Cylinder type vacuum cleaner stopping.                                                                                ::
    ID: 07002006.wav
    Length: 9
** Cylinder type vacuum cleaner in use. (Distant recording)                                                                                ::
    ID: 07002005.wav
    Length: 168
** Cylinder type vacuum cleaner. Stop on carpet                                                                                ::
    ID: 07002004.wav
    Length: 13
** Cylinder type vacuum cleaner. Start; constant run on carpet                                                                                ::
    ID: 07002003.wav
    Length: 168
** Cylinder type vacuum cleaner. Stop on lino.                                                                                 ::
    ID: 07002002.wav
    Length: 14
** Cylinder type vacuum cleaner. Start, constant run on lino.                                                                                ::
    ID: 07002001.wav
    Length: 169
** Exterior, start, tickover and occasional traffic, switch off. (1968 Austin A35 Van)                                                                                ::
    ID: 07001185.wav
    Length: 273
** Exterior, slow approach and pass. (1968 Austin A35 Van)                                                                                ::
    ID: 07001184.wav
    Length: 38
** Exterior, fast approach and pass. (1968 Austin A35 Van)                                                                                ::
    ID: 07001183.wav
    Length: 22
** Exterior, approach, stop, switch off. (1968 Austin A35 Van)                                                                                ::
    ID: 07001182.wav
    Length: 17
** Exterior, approach, stop, tickover. (1968 Austin A35 Van)                                                                                ::
    ID: 07001181.wav
    Length: 19
** Exterior, approach and stop. (1968 Austin A35 Van)                                                                                ::
    ID: 07001180.wav
    Length: 16
** Exterior, approach and stop in mid-distance. (1968 Austin A35 Van)                                                                                ::
    ID: 07001179.wav
    Length: 14
** Exterior, fast depart. (1968 Austin A35 Van)                                                                                ::
    ID: 07001178.wav
    Length: 23
** Exterior, start, depart. (1968 Austin A35 Van)                                                                                ::
    ID: 07001177.wav
    Length: 29
** Exterior, 1 door open and close. (1968 Austin A35 Van)                                                                                ::
    ID: 07001176.wav
    Length: 6
** Interior, start, constant run as in traffic, stop, switch off. (1968 Austin A35 Van)                                                                                ::
    ID: 07001175.wav
    Length: 319
** Interior, start, reversing, stop, switch off. (1968 Austin A35 Van)                                                                                ::
    ID: 07001174.wav
    Length: 55
** Interior, start, long hill climb, stop, switch off. (1968 Austin A35 Van)                                                                                ::
    ID: 07001173.wav
    Length: 387
** Interior, slow down, stop, switch off. (1968 Austin A35 Van)                                                                                ::
    ID: 07001172.wav
    Length: 28
** Interior, start, constant run. (1968 Austin A35 Van)                                                                                ::
    ID: 07001171.wav
    Length: 370
** Interior, start, revving, tickover. (1968 Austin A35 Van)                                                                                ::
    ID: 07001170.wav
    Length: 254
** Interior, 4 false starts. (1968 Austin A35 Van)                                                                                ::
    ID: 07001169.wav
    Length: 22
** Exterior, rear door open and close. (1968 Austin A35 Van)                                                                                ::
    ID: 07001168.wav
    Length: 8
** Interior, 2 doors open and close. (1968 Austin A35 Van)                                                                                ::
    ID: 07001167.wav
    Length: 11
** Interior, 1 door open and close. (1968 Austin A35 Van)                                                                                ::
    ID: 07001166.wav
    Length: 8
** Interior, stop. (1929 Austin Seven)                                                                                ::
    ID: 07001165.wav
    Length: 15
** Interior, start, constant run, stop, switch off. (1929 Austin Seven)                                                                                ::
    ID: 07001164.wav
    Length: 215
** Exterior, approach and pass. (1929 Austin Seven)                                                                                ::
    ID: 07001163.wav
    Length: 17
** Exterior, start, reverse. (1929 Austin Seven)                                                                                ::
    ID: 07001162.wav
    Length: 45
** Exterior, approach and stop. (1929 Austin Seven)                                                                                ::
    ID: 07001161.wav
    Length: 16
** Exterior, start, tickover, depart. (1929 Austin Seven)                                                                                ::
    ID: 07001160.wav
    Length: 28
** Exterior, false start, start, tickover. (1929 Austin Seven)                                                                                ::
    ID: 07001159.wav
    Length: 62
** Exterior, 2 false starts. (1929 Austin Seven)                                                                                ::
    ID: 07001158.wav
    Length: 12
** Exterior, door closed. (1929 Austin Seven)                                                                                ::
    ID: 07001157.wav
    Length: 6
** Exterior, door, opened. (1929 Austin Seven)                                                                                ::
    ID: 07001156.wav
    Length: 6
** Cross-country vehicle, exterior, approach, stop, switch off. (Austin Gipsy)                                                                                ::
    ID: 07001155.wav
    Length: 30
** Cross-country vehicle, exterior, approach, stop, tickover, switch off. (Austin Gipsy)                                                                                ::
    ID: 07001154.wav
    Length: 56
** Cross-country vehicle, exterior, approach, stop, revving, depart. (Austin Gipsy)                                                                                ::
    ID: 07001153.wav
    Length: 52
** Cross-country vehicle, exterior, approach, stop, tickover, depart. (Austin Gipsy)                                                                                ::
    ID: 07001152.wav
    Length: 48
** Cross-country vehicle, exterior, approach and pass with horn. (Austin Gipsy)                                                                                ::
    ID: 07001151.wav
    Length: 27
** Cross-country vehicle, exterior, approach and pass. (Austin Gipsy)                                                                                ::
    ID: 07001150.wav
    Length: 24
** Cross-country vehicle, exterior, approach and pass. (Austin Gipsy)                                                                                ::
    ID: 07001149.wav
    Length: 30
** Cross-country vehicle, exterior, start, 3-point turn, depart. (Austin Gipsy)                                                                                ::
    ID: 07001148.wav
    Length: 54
** Cross-country vehicle, exterior, start, depart. (Austin Gipsy)                                                                                ::
    ID: 07001147.wav
    Length: 41
** Cross-country vehicle, exterior, start, depart. (Austin Gipsy)                                                                                ::
    ID: 07001146.wav
    Length: 30
** Cross-country vehicle, exterior, 2 doors open and close. (Austin Gipsy)                                                                                ::
    ID: 07001145.wav
    Length: 14
** Cross-country vehicle, exterior, 1 door open and close. (Austin Gipsy)                                                                                ::
    ID: 07001144.wav
    Length: 10
** Cross-country vehicle, interior, start, tickover, switch off. (Austin Gipsy)                                                                                ::
    ID: 07001143.wav
    Length: 125
** Cross-country vehicle, interior, start, revving. (Austin Gipsy)                                                                                ::
    ID: 07001142.wav
    Length: 123
** Cross-country vehicle, interior, start, revving, stop, switch off. (Austin Gipsy)                                                                                ::
    ID: 07001141.wav
    Length: 107
** Cross-country vehicle, interior, 3 false starts. (Austin Gipsy)                                                                                ::
    ID: 07001140.wav
    Length: 20
** Cross-country vehicle, interior, start, run in traffic, stop, switch off. (Austin Gipsy)                                                                                ::
    ID: 07001139.wav
    Length: 361
** Cross-country vehicle, interior, self starter, medium speed run, stop, switch off. (Austin Gipsy)                                                                                ::
    ID: 07001138.wav
    Length: 392
** Cross-country vehicle, interior, start, run over rough ground, stop, switch off. (Austin Gipsy)                                                                                ::
    ID: 07001137.wav
    Length: 382
** Stallholder selling toys.                                                                                ::
    ID: 07001136.wav
    Length: 118
** Stallholder selling glass cutting tools.                                                                                ::
    ID: 07001135.wav
    Length: 121
** A singing beggar recorded in London street market.                                                                                ::
    ID: 07001134.wav
    Length: 122
** Stallholders selling goods in London street market. Selling daffodils                                                                                ::
    ID: 07001133.wav
    Length: 150
** Stallholders selling goods in London street market. Selling girls stretch tights.                                                                                 ::
    ID: 07001132.wav
    Length: 120
** Stallholders selling goods in London street market. Selling tomatoes.                                                                                ::
    ID: 07001131.wav
    Length: 63
** General west country market atmosphere with speech. Under cover.                                                                                ::
    ID: 07001130.wav
    Length: 397
** General west country market atmosphere with speech. In the open.                                                                                ::
    ID: 07001129.wav
    Length: 391
** Auctioning cattle at west country market.                                                                                ::
    ID: 07001128.wav
    Length: 202
** Auctioning calves at west country market.                                                                                ::
    ID: 07001127.wav
    Length: 203
** Auctioning pigs at west country market with general atmosphere.                                                                                ::
    ID: 07001126.wav
    Length: 401
** Auctioning fish at Peterhead harbour fish market.                                                                                ::
    ID: 07001125.wav
    Length: 405
** Atmosphere inside (Billingsgate Fish Market)                                                                                ::
    ID: 07001124.wav
    Length: 208
** Atmosphere outside market. (Billingsgate Fish Market)                                                                                 ::
    ID: 07001123.wav
    Length: 218
** General atmosphere recorded at an indoor shopping centre.                                                                                ::
    ID: 07001122.wav
    Length: 423
** Outdoor rag market, general atmosphere.                                                                                ::
    ID: 07001121.wav
    Length: 215
** Outdoor market, evangelist and general stalls atmosphere.                                                                                ::
    ID: 07001120.wav
    Length: 227
** Atmosphere in china shop (outside Bullring Market)                                                                                 ::
    ID: 07001119.wav
    Length: 244
** Amosphere recorded at a china shop. (Bullring)                                                                                 ::
    ID: 07001118.wav
    Length: 183
** Atmosphere of general wares being sold. (Bullring)                                                                                ::
    ID: 07001117.wav
    Length: 210
** Atmosphere of fish, meat and poultry stalls. (Bullring)                                                                                ::
    ID: 07001116.wav
    Length: 213
** Auctioning pigs, general atmosphere in market. (Winslow)                                                                                ::
    ID: 07001115.wav
    Length: 423
** Auctioning beef cattle, general atmosphere in market. (Winslow)                                                                                ::
    ID: 07001114.wav
    Length: 380
** General market atmosphere. (Pontypridd)                                                                                ::
    ID: 07001113.wav
    Length: 423
** General market atmosphere. (Maidstone)                                                                                ::
    ID: 07001112.wav
    Length: 422
** Atmosphere at plant stalls. (Aylesbury)                                                                                ::
    ID: 07001111.wav
    Length: 183
** General market atmosphere. (Aylesbury)                                                                                ::
    ID: 07001110.wav
    Length: 244
** Sound of lorries parking and unloading, with speech and occasional footsteps. (Covent Garden)                                                                                ::
    ID: 07001109.wav
    Length: 198
** General atmosphere with trolleys. (Covent Garden)                                                                                ::
    ID: 07001108.wav
    Length: 198
** Flower hall atmosphere. (Covent Garden)                                                                                ::
    ID: 07001107.wav
    Length: 388
** Early morning atmosphere with porters and trolleys. (Covent Garden)                                                                                ::
    ID: 07001106.wav
    Length: 393
** Interior, stop, tickover, door opened and closed, switch off. (Diesel Taxi)                                                                                ::
    ID: 07001105.wav
    Length: 52
** Interior, start, running in traffic, stop, switch off. (Diesel Taxi)                                                                                ::
    ID: 07001104.wav
    Length: 308
** Interior, slow down, stop, switch off. (Diesel Taxi)                                                                                ::
    ID: 07001103.wav
    Length: 46
** Interior, start into constant run, stop, switch off. (Diesel Taxi)                                                                                ::
    ID: 07001102.wav
    Length: 301
** Exterior, start, tickover, stop. (Diesel Taxi)                                                                                ::
    ID: 07001101.wav
    Length: 149
** Exterior, door open and close. (Diesel Taxi)                                                                                ::
    ID: 07001100.wav
    Length: 9
** Exterior, door open and close. (Diesel Taxi)                                                                                ::
    ID: 07001099.wav
    Length: 8
** Exterior, passing with horn. (Diesel Taxi)                                                                                ::
    ID: 07001098.wav
    Length: 22
** Exterior, passing. (Diesel Taxi)                                                                                ::
    ID: 07001097.wav
    Length: 38
** Exterior, passing. (Diesel Taxi)                                                                                ::
    ID: 07001096.wav
    Length: 41
** Exterior, passing. (Diesel Taxi)                                                                                ::
    ID: 07001095.wav
    Length: 28
** Exterior, approach, stop, tickover, depart. (Diesel Taxi)                                                                                ::
    ID: 07001094.wav
    Length: 28
** Exterior, approach, stop, tickover, door closes, depart. (Diesel Taxi)                                                                                ::
    ID: 07001093.wav
    Length: 51
** Exterior, approach, stop, tickover, depart. (Diesel Taxi)                                                                                ::
    ID: 07001092.wav
    Length: 56
** Exterior, approach and stop. (Diesel Taxi)                                                                                ::
    ID: 07001091.wav
    Length: 37
** Exterior, start, depart. (Diesel Taxi)                                                                                ::
    ID: 07001090.wav
    Length: 34
** Interior, start, constant run in traffic, stop, switch off. (Diesel Taxi)                                                                                ::
    ID: 07001089.wav
    Length: 382
** Interior, start, constant run in traffic, stop, switch off. (Diesel Taxi)                                                                                ::
    ID: 07001088.wav
    Length: 403
** Exterior, high pass overhead. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001087.wav
    Length: 55
** Exterior, low pass overhead. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001086.wav
    Length: 42
** Exterior, passing overhead. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001085.wav
    Length: 33
** Exterior, taxi up, switch off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001084.wav
    Length: 53
** Exterior, taxi up, revving, switch off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001083.wav
    Length: 47
** Exterior, land, switch off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001082.wav
    Length: 41
** Exterior, take off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001081.wav
    Length: 43
** Exterior, start, tickover, revving, slow tickover, taxi away. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001080.wav
    Length: 194
** Exterior, start, tickover, taxi away. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001079.wav
    Length: 41
** Exterior, start, tickover, revving, switch off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001078.wav
    Length: 90
** Interior, constant flight. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001077.wav
    Length: 396
** Interior, revving, tickover, switch off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001076.wav
    Length: 111
** Interior, land, taxi in, switch off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001075.wav
    Length: 64
** Interior, start, take off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001074.wav
    Length: 139
** Interior, start, tickover, switch off. (Tiger Moth Light Aircraft, Single piston engine; open cockpit)                                                                                ::
    ID: 07001073.wav
    Length: 70
** Exterior, passing overhead. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001072.wav
    Length: 32
** Exterior, passing overhead. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001071.wav
    Length: 26
** Exterior, land, taxi up and switch off. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001070.wav
    Length: 42
** Exterior, taxi up and switch off. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001069.wav
    Length: 57
** Exterior, landing. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001068.wav
    Length: 46
** Exterior, start, taxi past and take off. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001067.wav
    Length: 72
** Exterior, take off. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001066.wav
    Length: 29
** Exterior, take off. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001065.wav
    Length: 53
** Exterior, start, taxi past and away. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001064.wav
    Length: 47
** Interior, descent, land, taxi, switch off. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001063.wav
    Length: 195
** Interior, constant flight. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001062.wav
    Length: 386
** Interior, take off, climb into level flight. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001061.wav
    Length: 231
** Interior, start, taxi, run up for checking purposes, switch off. (Piper private light aircraft, 1 piston engine)                                                                                ::
    ID: 07001060.wav
    Length: 172
** Exterior, flying overhead and manoeuvring. (1916 Bristol Fighter, First World War, two-seater fighter with single Rolls Royce engine)                                                                                ::
    ID: 07001059.wav
    Length: 136
** Exterior, passing overhead with steep turns. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce engine)                                                                                ::
    ID: 07001058.wav
    Length: 64
** Exterior, passing overhead. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce piston engine)                                                                                ::
    ID: 07001057.wav
    Length: 36
** Exterior, passing overhead. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce piston engine)                                                                                ::
    ID: 07001056.wav
    Length: 33
** Exterior, approach, taxi to stop, tickover. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce piston engine)                                                                                ::
    ID: 07001055.wav
    Length: 68
** Exterior, approach and land, taxi up, tickover, switch off. (1916 Bristol Fighter, First World War two-seater fighter with Rolls Royce piston engines)                                                                                ::
    ID: 07001054.wav
    Length: 155
** Exterior, take off. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce piston engine)                                                                                ::
    ID: 07001053.wav
    Length: 58
** Exterior, start up, taxi away. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce piston Engine)                                                                                ::
    ID: 07001052.wav
    Length: 56
** Exterior, tickover. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce piston engine)                                                                                ::
    ID: 07001051.wav
    Length: 110
** Exterior, start up, engine running and revving. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Engine)                                                                                ::
    ID: 07001050.wav
    Length: 261
** Interior, landing, taxi to stop, tickover, switch off. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce Engines)                                                                                 ::
    ID: 07001049.wav
    Length: 109
** Interior, take off, climb into constant flight. (1916 Bristol Fighter, First World War two-seater fighter with single Rolls Royce Engines)                                                                                 ::
    ID: 07001048.wav
    Length: 259
** Exterior, land, switch off. (S.E. 5A First World War single-seater fighter, 1 piston engine)                                                                                ::
    ID: 07001047.wav
    Length: 38
** Exterior, pass over, land, switch off. (S.E. 5A First World War single-seater fighter, 1 piston engine)                                                                                ::
    ID: 07001046.wav
    Length: 308
** Exterior, aerobatics as in dog fight. (S.E. 5A First World War single-seater fighter, 1 piston engine)                                                                                ::
    ID: 07001045.wav
    Length: 368
** Aircraft warming up and taking off, aerodrome, 1917                                                                                ::
    ID: 07001044.wav
    Length: 340
** Exterior, aerobatics. (S.E. 5A First World War single-seater fighter, 1 piston engine)                                                                                ::
    ID: 07001043.wav
    Length: 150
** Exterior, taxi away, take off, aerobatics. (S.E. 5A First World War single-seater fighter, 1 piston engine)                                                                                ::
    ID: 07001042.wav
    Length: 79
** Exterior, take off. (S.E. 5A First World War single-seater fighter, 1 piston engine)                                                                                ::
    ID: 07001041.wav
    Length: 21
** Exterior, start up, tickover, taxis. (S.E. 5A First World War single-seater fighter, 1 piston engine)                                                                                ::
    ID: 07001040.wav
    Length: 135
** Stropping a razor.                                                                                ::
    ID: 07001039.wav
    Length: 28
** Setting large saw                                                                                ::
    ID: 07001038.wav
    Length: 154
** Small saw being set by hand using a file.                                                                                ::
    ID: 07001037.wav
    Length: 154
** Small spring-steel tools heated in blow torch flame, then quenched.                                                                                ::
    ID: 07001036.wav
    Length: 188
** Small spring wheel tools being sharpened on electric grinder. (With switch on and off)                                                                                ::
    ID: 07001035.wav
    Length: 182
** Twist drill being sharpened on an electric grinder. (With switch on and off)                                                                                ::
    ID: 07001034.wav
    Length: 80
** Cold chisel being sharpened on an electric grinder. (With switch on and off)                                                                                ::
    ID: 07001033.wav
    Length: 96
** Carving knife being sharpened on an old fashioned, hand-turned stone wheel.                                                                                ::
    ID: 07001032.wav
    Length: 178
** Tree felling axe being sharpened on an old fashioned, hand-turned stone wheel.                                                                                ::
    ID: 07001031.wav
    Length: 185
** Chopper being sharpened on an old fashioned, hand-turned stone wheel.                                                                                ::
    ID: 07001030.wav
    Length: 198
** Wood chisel being sharpened on oil stone.                                                                                ::
    ID: 07001029.wav
    Length: 88
** Lawn mower blades being sharpened.                                                                                ::
    ID: 07001028.wav
    Length: 83
** Sharpening sickle.                                                                                ::
    ID: 07001027.wav
    Length: 56
** Sharpening scythe.                                                                                ::
    ID: 07001026.wav
    Length: 53
** Paint scraper being sharpened on step.                                                                                ::
    ID: 07001025.wav
    Length: 27
** Tree felling axe being sharpened on step.                                                                                ::
    ID: 07001024.wav
    Length: 54
** Chopper being sharpened on step.                                                                                ::
    ID: 07001023.wav
    Length: 27
** Knife being sharpened on step.                                                                                ::
    ID: 07001022.wav
    Length: 31
** Knife being sharpened on step.                                                                                ::
    ID: 07001021.wav
    Length: 37
** Carving knife being sharpened on step.                                                                                ::
    ID: 07001020.wav
    Length: 36
** Carving knife being sharpened on steel.                                                                                ::
    ID: 07001019.wav
    Length: 37
** General atmosphere with excavators.                                                                                ::
    ID: 07001018.wav
    Length: 396
** Single shot and rock fall.                                                                                ::
    ID: 07001017.wav
    Length: 20
** Shot blasting.                                                                                ::
    ID: 07001016.wav
    Length: 87
** Crusher.                                                                                ::
    ID: 07001015.wav
    Length: 85
** Heavy lorry climbing hill.                                                                                ::
    ID: 07001014.wav
    Length: 56
** Heavy lorry (loaded) climbing hill.                                                                                ::
    ID: 07001013.wav
    Length: 79
** Primary screen grader.                                                                                ::
    ID: 07001012.wav
    Length: 78
** Pulverizer.                                                                                ::
    ID: 07001011.wav
    Length: 79
** Stone grader.                                                                                ::
    ID: 07001010.wav
    Length: 79
** Drilling.                                                                                ::
    ID: 07001009.wav
    Length: 71
** Breaking large stones.                                                                                ::
    ID: 07001008.wav
    Length: 61
** Breaking small stones.                                                                                ::
    ID: 07001007.wav
    Length: 35
** Crushing.                                                                                ::
    ID: 07001006.wav
    Length: 63
** Crushing.                                                                                ::
    ID: 07001005.wav
    Length: 65
** Tipping rock in a granite quarry.                                                                                ::
    ID: 07001004.wav
    Length: 60
** Break drilling.                                                                                ::
    ID: 07001003.wav
    Length: 70
** Loading stone on to a lorry.                                                                                ::
    ID: 07001002.wav
    Length: 96
** Drilling.                                                                                ::
    ID: 07001001.wav
    Length: 62
** Flying Fortress, exterior, taxi-ing. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000229.wav
    Length: 38
** Kittyhawk, interior, steady flight. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000228.wav
    Length: 48
** Kittyhawk, exterior, steady flight, dive and zoom. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000227.wav
    Length: 44
** Sunderland flying boat, exterior, passing over. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000226.wav
    Length: 42
** Sunderland flying boat, interior, cruising. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000225.wav
    Length: 66
** Sunderland flying boat, exterior, take off. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000224.wav
    Length: 29
** Sunderland flying boat, interior, cruising, rec, beside pilot. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000223.wav
    Length: 42
** Sunderland flying boat, interior, cruising, rec. from fitter's position. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000222.wav
    Length: 42
** Sunderland flying boat, interior, cruising, rec. midships. World War II. (From 78 disc)                                                                                ::
    ID: 07000221.wav
    Length: 47
** Sunderland flying boat, interior, cruising, rec. wardroom. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000220.wav
    Length: 62
** Sunderland flying boat, interior, cruising, rec. from bridge. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000219.wav
    Length: 35
** Sunderland flying boat, interior, take off. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000218.wav
    Length: 38
** Exterior, dive and climb, followed by dive on one engine. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000217.wav
    Length: 93
** Exterior, taxi-ing. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000216.wav
    Length: 29
** Exterior, two dives, followed by constant flight. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000215.wav
    Length: 88
** Exterior, taxi-ing, switching off. World War II fighter-bomber. (From 78 r.p.m disc)                                                                                ::
    ID: 07000214.wav
    Length: 67
** Exterior, landing. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000213.wav
    Length: 52
** Exterior, take off, distant. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000212.wav
    Length: 39
** Exterior, take off, close. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000211.wav
    Length: 51
** Exterior, manoeuvring from disposal point, taxi-ing away. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000210.wav
    Length: 98
** Exterior, starting, running, ticking over. World War II fighter-bomber. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000209.wav
    Length: 141
** Wellington, steady flight and dive. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000208.wav
    Length: 80
** Wellington (twin-engined) bomber passing over, diving twice. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000207.wav
    Length: 75
** Halifax bombers passing over in succession. (From 78 r.m.p. disc)                                                                                ::
    ID: 07000206.wav
    Length: 153
** Exterior, passing over, several. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000205.wav
    Length: 73
** Exterior, taxis up, engines off. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000204.wav
    Length: 74
** Exterior, takes off. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000203.wav
    Length: 31
** Exterior, takes off. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000202.wav
    Length: 30
** Exterior, start engines, runs. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000201.wav
    Length: 74
** Searchlight working on aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000200.wav
    Length: 24
** Searchlight engine of aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000199.wav
    Length: 32
** Harvard ticking over, taking off from aircraft carrier, World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000198.wav
    Length: 80
** Swordfish taking off from aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000197.wav
    Length: 25
** Swordfish ticking over, taking off from aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000196.wav
    Length: 111
** Martlet landing on aircraft carrier. Noise of arrestor gear. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000195.wav
    Length: 27
** Wind and sea from flight-deck of aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000194.wav
    Length: 74
** Wind and sea from bridge of aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000193.wav
    Length: 66
** Ship's wake, from quarter-deck on board aircraft carrier. World War II. (from 78 r.p.m. disc)                                                                                ::
    ID: 07000192.wav
    Length: 92
** Hangar atmosphere, with voices. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000191.wav
    Length: 65
** Lift ascending on board aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000190.wav
    Length: 46
** Klaxon and lift descending on board aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000189.wav
    Length: 37
** Flight-deck atmosphere. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000188.wav
    Length: 151
** Footsteps running up ladder to flight-deck on board aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000187.wav
    Length: 16
** Footsteps from cabin, up ladder, along deck and return, on board aircraft carrier. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000186.wav
    Length: 74
** Mess deck atmosphere. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000185.wav
    Length: 57
** Weighing anchor, chain dropping into locker. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000184.wav
    Length: 76
** Internal atmos. Ship's fan. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000183.wav
    Length: 93
** Turbines, full speed. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000182.wav
    Length: 64
** Turbines, changing speed, slow to half-half to full, with telegraph. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000181.wav
    Length: 156
** Turbines, slow, World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000180.wav
    Length: 90
** Interior, C47 Dakota. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000179.wav
    Length: 259
** Interior, P47 Thunderbolt. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000178.wav
    Length: 105
** Exterior, P51 Mustang. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000177.wav
    Length: 33
** Exterior, P51 Mustang. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000176.wav
    Length: 117
** Exterior, C47 Dakota. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07000175.wav
    Length: 221
** Bristol Beaufighter. (Exerior) Squadron diving in succession                                                                                ::
    ID: 07000174.wav
    Length: 80
** Bristol Beaufighter. (Exterior) Four planes diving in succession with bursts of machine gun & cannon fire                                                                                ::
    ID: 07000173.wav
    Length: 64
** Bristol Beaufighter.(Exterior) Start up engines alternately with orders, warm up & switch off (with orders)                                                                                ::
    ID: 07000172.wav
    Length: 204
** Exterior, steep climb. (Bristol Beaufighter, World War II)                                                                                ::
    ID: 07000171.wav
    Length: 27
** Exterior, several planes diving with whine. (Bristol Beaufighter, World War II)                                                                                ::
    ID: 07000170.wav
    Length: 97
** Exterior, two planes in low flight with whine. (Bristol Beaufighter, World War II)                                                                                ::
    ID: 07000169.wav
    Length: 97
** Exterior, land. (Bristol Beaufighter, World War II)                                                                                ::
    ID: 07000168.wav
    Length: 26
** Take off. (Bristol Beaufighter, World War II)                                                                                ::
    ID: 07000167.wav
    Length: 24
** Interior, start with orders, warm up and switch off. (Bristol Beaufighter, World War II)                                                                                ::
    ID: 07000166.wav
    Length: 87
** Aircraft: Barracuda (on aircraft carrier) Lands & taxis forward                                                                                :Aircraft:Barracuda:
    ID: 07000165.wav
    Length: 39
** Aircraft: Barracuda (on aircraft carrier) Lands                                                                                :Aircraft:Barracuda:
    ID: 07000164.wav
    Length: 22
** Aircraft: Barracuda (on aircraft carrier) Revs, takes off (Swordfish in background)                                                                                :Aircraft:Barracuda:
    ID: 07000163.wav
    Length: 44
** Aircraft: Barracuda (on aircraft carrier) Take off                                                                                :Aircraft:Barracuda:
    ID: 07000162.wav
    Length: 29
** Aircraft: Barracuda (on aircraft carrier) Revving up                                                                                :Aircraft:Barracuda:
    ID: 07000161.wav
    Length: 28
** Aircraft: Barracuda (on aircraft carrier) Misfires twice on starting                                                                                 :Aircraft:Barracuda:
    ID: 07000160.wav
    Length: 22
** Aircraft: Avro York Transport. Two take off                                                                                :Aircraft:Avro York Transport:
    ID: 07000159.wav
    Length: 57
** Aircraft: Avro York Transport. Take off                                                                                :Aircraft:Avro York Transport:
    ID: 07000158.wav
    Length: 93
** Aircraft: Avro York Transport. Take off                                                                                :Aircraft:Avro York Transport:
    ID: 07000157.wav
    Length: 33
** Aircraft: Avro York Transport. Start, run engines & switch off                                                                                :Aircraft:Avro York Transport:
    ID: 07000156.wav
    Length: 113
** Aircraft: Airspeed Oxford. Diving                                                                                :Aircraft:Airspeed Oxford:
    ID: 07000155.wav
    Length: 23
** Aircraft: Airspeed Oxford. Two take off in succession                                                                                :Aircraft:Airspeed Oxford:
    ID: 07000154.wav
    Length: 43
** Beagle Pup, exterior recordings. Land                                                                                ::
    ID: 07000153.wav
    Length: 27
** Beagle Pup, exterior recordings. Aerobatics.                                                                                ::
    ID: 07000152.wav
    Length: 136
** Beagle Pup, exterior recordings. Pass over several times.                                                                                ::
    ID: 07000151.wav
    Length: 138
** Beagle Pup, exterior recordings. Pass over several times                                                                                ::
    ID: 07000150.wav
    Length: 117
** Beagle Pup, exterior recordings. Low pass over                                                                                ::
    ID: 07000149.wav
    Length: 35
** Beagle Pup, exterior recordings. Take off                                                                                ::
    ID: 07000148.wav
    Length: 24
** Beagle Pup, exterior recordings. Taxi (some voices)                                                                                ::
    ID: 07000147.wav
    Length: 85
** Beagle Pup, exterior recordings. Start up engines.                                                                                ::
    ID: 07000146.wav
    Length: 28
** Beagle Airdale, interior recordings, Lands (with buzzer); taxi & switch off                                                                                ::
    ID: 07000145.wav
    Length: 393
** Beagle Airdale, interior recordings. Constant flight and descent.                                                                                ::
    ID: 07000144.wav
    Length: 394
** Beagle Airdale, interior recordings, Constant flight.                                                                                ::
    ID: 07000143.wav
    Length: 395
** Beagle Airdale, interior recordings, Start, tickover, take off.                                                                                ::
    ID: 07000142.wav
    Length: 395
** Start up, taxi and take off. (Monoplane 1909)                                                                                ::
    ID: 07000141.wav
    Length: 57
** Start up, taxi and switch off. (Monoplane 1909)                                                                                ::
    ID: 07000140.wav
    Length: 77
** A single jet 707B aircraft passing overhead.                                                                                ::
    ID: 07000139.wav
    Length: 19
** A single jet 707B aircraft passing overhead.                                                                                ::
    ID: 07000138.wav
    Length: 19
** A single jet 707B aircraft, start, run up engines, switch off.                                                                                ::
    ID: 07000137.wav
    Length: 68
** Auster aircraft. Landing.                                                                                ::
    ID: 07000136.wav
    Length: 33
** Auster aircraft. Landing (hits soft patch)                                                                                ::
    ID: 07000135.wav
    Length: 33
** Auster aircraft. Landing.                                                                                ::
    ID: 07000134.wav
    Length: 37
** Auster aircraft. Passes overhead                                                                                ::
    ID: 07000133.wav
    Length: 37
** Auster aircraft. Passes overhead                                                                                ::
    ID: 07000132.wav
    Length: 42
** Auster aircraft. Passes overhead.                                                                                ::
    ID: 07000131.wav
    Length: 38
** Auster Aircraft. Circle and pass overhead (200ft)                                                                                ::
    ID: 07000130.wav
    Length: 64
** Auster Aircraft. Passes overhead slower                                                                                ::
    ID: 07000129.wav
    Length: 27
** Auster Aircraft. Passes overhead at 100 ft.                                                                                ::
    ID: 07000128.wav
    Length: 28
** Auster Aircraft. Take off, pass and circle overhead at 200 ft.                                                                                ::
    ID: 07000127.wav
    Length: 201
** Auster Aircraft. Take off                                                                                ::
    ID: 07000126.wav
    Length: 18
** Auster Aircraft. Approach and take off                                                                                ::
    ID: 07000125.wav
    Length: 42
** Auster Aircraft. Hand start, warm up and taxi away.                                                                                ::
    ID: 07000124.wav
    Length: 125
** Auster Aircraft. Rev up and taxi away.                                                                                 ::
    ID: 07000123.wav
    Length: 103
** Auster aircraft. Start, warm up and switch off (interior)                                                                                ::
    ID: 07000122.wav
    Length: 126
** Auster aircraft. Start, tick over and switch off.                                                                                ::
    ID: 07000121.wav
    Length: 103
** Auster aircraft. Start, with orders, warm up and switch off.                                                                                 ::
    ID: 07000120.wav
    Length: 137
** Aircraft passing overhead. (Jet Fighter)                                                                                ::
    ID: 07000119.wav
    Length: 12
** Aircraft passing overhead. (Jet Fighter)                                                                                ::
    ID: 07000118.wav
    Length: 12
** Aircraft passing overhead. (Jet Fighter)                                                                                ::
    ID: 07000117.wav
    Length: 10
** Aircraft passing overhead. (Jet Fighter)                                                                                ::
    ID: 07000116.wav
    Length: 10
** Aircraft taking off.                                                                                ::
    ID: 07000115.wav
    Length: 61
** Aircraft ticking over. (Naval Torpedo Bomber)                                                                                ::
    ID: 07000114.wav
    Length: 56
** White noise filtered to simulate wind at constant pitch. Wind 12. (3 tones up from Wind 11)                                                                                ::
    ID: 07000113.wav
    Length: 181
** White noise filtered to simulate wind at constant pitch. Wind 11. (3 tones up from Wind 10)                                                                                ::
    ID: 07000112.wav
    Length: 181
** White noise filtered to simulate wind at constant pitch. Wind 10. (3 tones up from Wind 9)                                                                                ::
    ID: 07000111.wav
    Length: 183
** White noise filtered to simulate wind at constant pitch. Wind 9. (3 tones up from Wind 8)                                                                                ::
    ID: 07000110.wav
    Length: 184
** White noise filtered to simulate wind at constant pitch. Wind 8. (3 tones up from Wind 7)                                                                                ::
    ID: 07000109.wav
    Length: 179
** White noise filtered to simulate wind at constant pitch. Wind 7. (3 tones up from Wind 6)                                                                                ::
    ID: 07000108.wav
    Length: 178
** White noise filtered to simulate wind at constant pitch. Wind 6. (3 tones up from Wind 5)                                                                                ::
    ID: 07000107.wav
    Length: 176
** White noise filtered to simulate wind at constant pitch. Wind 5. (3 tones up from Wind 4)                                                                                ::
    ID: 07000106.wav
    Length: 186
** White noise filtered to simulate wind at constant pitch. Wind 4 (3 tones up from Wind 3)                                                                                ::
    ID: 07000105.wav
    Length: 184
** White noise filtered to simulate wind at constant pitch. Wind 3 (3 tones up from Wind 2)                                                                                ::
    ID: 07000104.wav
    Length: 184
** White noise filtered to simulate wind at constant pitch. Wind 2 (3 tones up from Wind 1)                                                                                ::
    ID: 07000103.wav
    Length: 187
** White noise filtered to simulate wind at constant pitch. Wind 1. (Lowest note)                                                                                ::
    ID: 07000102.wav
    Length: 187
** Constant movement on a soft surface. (Created to simulate troop movements over rough ground)                                                                                ::
    ID: 07000101.wav
    Length: 421
** Constant movement background on a crisp surface. (Created to simulate troop movements over rough ground)                                                                                ::
    ID: 07000100.wav
    Length: 420
** White noise filtered to simulate sea effects. Ripples.                                                                                ::
    ID: 07000099.wav
    Length: 465
** White noise filtered to simulate sea effects. Low frequencies.                                                                                 ::
    ID: 07000098.wav
    Length: 482
** White noise filtered to simulate sea effects. Medium frequencies.                                                                                ::
    ID: 07000097.wav
    Length: 483
** White noise filtered to simulate sea effects. High frequencies.                                                                                ::
    ID: 07000096.wav
    Length: 484
** Under sail in high winds. (Sailing dinghy)                                                                                ::
    ID: 07000095.wav
    Length: 200
** Tacking to moorings, tie up and store sails. (Sailing dinghy)                                                                                ::
    ID: 07000094.wav
    Length: 214
** Under sail with wind in gusts. (Sailing dinghy)                                                                                ::
    ID: 07000093.wav
    Length: 215
** Preparing to sail. (Sailing dinghy)                                                                                ::
    ID: 07000092.wav
    Length: 189
** Light sea as heard from Halliards. (STS Malcolm Miller)                                                                                ::
    ID: 07000091.wav
    Length: 191
** Average sea as heard from inside sail locker. (STS Malcolm Miller)                                                                                ::
    ID: 07000090.wav
    Length: 196
** Head sails flapping with wash. (STS Malcolm Miller)                                                                                ::
    ID: 07000089.wav
    Length: 197
** Light ripples as heard from deck. (STS Malcolm Miller)                                                                                ::
    ID: 07000088.wav
    Length: 196
** Wash as heard from Lee Scuppers. (STS Malcolm Miller)                                                                                ::
    ID: 07000087.wav
    Length: 181
** Tacking in average sea. (STS Malcolm Miller)                                                                                ::
    ID: 07000086.wav
    Length: 53
** Tackles clanking in average sea. (STS Malcolm Miller)                                                                                ::
    ID: 07000085.wav
    Length: 53
** Sails flapping in average sea. (STS Malcolm Miller)                                                                                ::
    ID: 07000084.wav
    Length: 57
** Average sea as heard from Lee Halliards. (STS Malcolm Miller)                                                                                ::
    ID: 07000083.wav
    Length: 394
** Wind howling in rigging with occasional creak. (STS Malcolm Miller)                                                                                ::
    ID: 07000082.wav
    Length: 190
** Creaking and flapping boom in calm weather. (STS Malcolm Miller)                                                                                ::
    ID: 07000081.wav
    Length: 215
** Average sea with wind whistling on Lee Rail. (STS Malcolm Miller)                                                                                ::
    ID: 07000080.wav
    Length: 200
** Average sea as heard from Bowsprit with flapping sails. (STS Malcolm Miller)                                                                                ::
    ID: 07000079.wav
    Length: 184
** Bow wave as heard from Bowsprit at 4 knots, 9-knot wind. (STS Malcolm Miller)                                                                                ::
    ID: 07000078.wav
    Length: 371
** Bow wave as heard from Lee Quarter, light wind. (STS Malcolm Miller)                                                                                ::
    ID: 07000077.wav
    Length: 389
** Clipper sailing with sea and wind. In 'Trade Winds'                                                                                ::
    ID: 07000076.wav
    Length: 395
** Clipper sailing with sea and wind. In 'Roaring Forties'                                                                                ::
    ID: 07000075.wav
    Length: 386
** In cabin, sound of mooring chain being pulled in. (19ft cabin sloop)                                                                                ::
    ID: 07000074.wav
    Length: 52
** In cabin, general atmosphere. (19ft cabin sloop)                                                                                ::
    ID: 07000073.wav
    Length: 328
** In cockpit, 'Lee Ho' shouted in strength 5 wind. (19ft cabin sloop)                                                                                ::
    ID: 07000072.wav
    Length: 21
** In cockpit, sailing against strength 5 wind. (19ft cabin sloop)                                                                                ::
    ID: 07000071.wav
    Length: 381
** 500cc machines at Isle of Man Tourist Trophy Races. Passing at Bradden Bridge.                                                                                ::
    ID: 07000070.wav
    Length: 88
** 500cc machines at Isle of Man Tourist Trophy Races. Passing grandstand.                                                                                ::
    ID: 07000069.wav
    Length: 82
** 500cc machines at Isle of Man Tourist Trophy Races. Starting in pairs at 10 sec. intervals.                                                                                ::
    ID: 07000068.wav
    Length: 112
** 500cc machines at Isle of Man Tourist Trophy Races. Atmosphere in pits before start.                                                                                ::
    ID: 07000067.wav
    Length: 115
** 50cc machines at Isle of Man Tourist Trophy Races. Passing grandstand.                                                                                ::
    ID: 07000066.wav
    Length: 186
** 50cc machines at Isle of Man Tourist Trophy Races. Massed start.                                                                                ::
    ID: 07000065.wav
    Length: 38
** 50cc machines at Isle of Man Tourist Trophy Races. Atmosphere in pits before start.                                                                                ::
    ID: 07000064.wav
    Length: 141
** 50cc machines at Isle of Man Tourist Trophy Races. Siren to clear track.                                                                                ::
    ID: 07000063.wav
    Length: 12
** 350cc machines at Isle of Man Tourist Trophy Races - Junior T.T. Passing at Quarter Bridge                                                                                ::
    ID: 07000062.wav
    Length: 85
** 350cc machines at Isle of Man Tourist Trophy Races - Junior T.T. Passing grandstand                                                                                ::
    ID: 07000061.wav
    Length: 81
** 350cc machines at Isle of Man Tourist Trophy Races - Junior T.T. Starting in pairs at 10 sec. intervals before start.                                                                                ::
    ID: 07000060.wav
    Length: 110
** 350cc machines at Isle of Man Tourist Trophy Races - Junior T.T.  Atmosphere in pits before start.                                                                                ::
    ID: 07000059.wav
    Length: 136
** 125cc machines at Isle of Man Tourist Trophy Races. Passing grandstand                                                                                ::
    ID: 07000058.wav
    Length: 134
** 125cc machines at Isle of Man Tourist Trophy Races. Starting in pairs at 10sec. intervals                                                                                ::
    ID: 07000057.wav
    Length: 143
** 125cc machines at Isle of Man Tourist Trophy Races. Atmosphere in pits before start.                                                                                ::
    ID: 07000056.wav
    Length: 128
** A horsedrawn sleigh, start, constant run, stop.                                                                                ::
    ID: 07000055.wav
    Length: 95
** A horsedrawn sleigh, start, constant run, stop.                                                                                ::
    ID: 07000054.wav
    Length: 47
** A coach and four, stopping.                                                                                ::
    ID: 07000053.wav
    Length: 16
** A coach and four, start, constant run, stop.                                                                                ::
    ID: 07000052.wav
    Length: 207
** Coach and four. Door open & close                                                                                ::
    ID: 07000051.wav
    Length: 21
** Coach and four. Horses unharnessed                                                                                ::
    ID: 07000050.wav
    Length: 121
** Coach and four. Approach & stop; door open & close                                                                                ::
    ID: 07000049.wav
    Length: 46
** Coach and four. Approach & stop; horse moves about                                                                                ::
    ID: 07000048.wav
    Length: 61
** Coach and four. Jingle of harness; depart                                                                                ::
    ID: 07000047.wav
    Length: 38
** Coach and four. Approach and pass.                                                                                 ::
    ID: 07000046.wav
    Length: 37
** A coach and four, brake applied, some bird song season unknown.                                                                                ::
    ID: 07000045.wav
    Length: 19
** A coach and four, stop.                                                                                ::
    ID: 07000044.wav
    Length: 19
** A coach and four, start into constant run.                                                                                ::
    ID: 07000043.wav
    Length: 315
** A coach and four, stop, door opened.                                                                                ::
    ID: 07000042.wav
    Length: 19
** A coach and four, start into constant run. (Interior)                                                                                ::
    ID: 07000041.wav
    Length: 176
** A coach and four, start into constant run. (Interior)                                                                                ::
    ID: 07000040.wav
    Length: 98
** A coach and four, horses bridled and put into shafts.                                                                                ::
    ID: 07000039.wav
    Length: 58
** Four horse mail coach. Stopping. (Interior)                                                                                ::
    ID: 07000038.wav
    Length: 14
** Four horse mail coach. Start, constant run, stop. (Interior)                                                                                ::
    ID: 07000037.wav
    Length: 358
** Four horse mail coach, start and depart.                                                                                ::
    ID: 07000036.wav
    Length: 29
** Four horse mail coach, approach and stop.                                                                                ::
    ID: 07000035.wav
    Length: 27
** Four horse mail coach, stopping. (From drivers position)                                                                                ::
    ID: 07000034.wav
    Length: 17
** Four horse mail coach, start, constant run, stop. (From driver's position)                                                                                ::
    ID: 07000033.wav
    Length: 306
** Hansom cb with bells. (interior or exterior) Loose surface. Trop to stop                                                                                ::
    ID: 07000032.wav
    Length: 20
** Hansom cab with bells, (interior or exterior) Loose surface. Start, constant run, stop.                                                                                 ::
    ID: 07000031.wav
    Length: 372
** Hansome cab with bells, suitable for interior oe exterior use. Trot to stop                                                                                ::
    ID: 07000030.wav
    Length: 14
** Hansom cab with bells, suitable for interior or exterior use. Start, constant run, stop.                                                                                ::
    ID: 07000029.wav
    Length: 328
** Pony and cart, pony chewing and rattling bit.                                                                                ::
    ID: 07000028.wav
    Length: 48
** Pony and cart, passing.                                                                                ::
    ID: 07000027.wav
    Length: 53
** Pony and cart, passing.                                                                                ::
    ID: 07000026.wav
    Length: 30
** Pony and cart, approach, stop and depart.                                                                                ::
    ID: 07000025.wav
    Length: 40
** Pony and cart, approach and stop.                                                                                ::
    ID: 07000024.wav
    Length: 25
** Pony and cart, start and depart.                                                                                ::
    ID: 07000023.wav
    Length: 32
** Pony and cart, trot to stop.                                                                                ::
    ID: 07000022.wav
    Length: 12
** Pony and cart, start, trot and stop.                                                                                ::
    ID: 07000021.wav
    Length: 175
** Pony and cart, walk to stop.                                                                                ::
    ID: 07000020.wav
    Length: 10
** Pony and cart, start, walk and stop.                                                                                ::
    ID: 07000019.wav
    Length: 183
** Early morning atmosphere at stables in the open.                                                                                ::
    ID: 07000018.wav
    Length: 128
** Atmosphere at stables in an enclosed yard.                                                                                ::
    ID: 07000017.wav
    Length: 118
** Two horses led from stable.                                                                                ::
    ID: 07000016.wav
    Length: 64
** Horse neighing at mare.                                                                                ::
    ID: 07000015.wav
    Length: 27
** One horse unharnessed and led into stable on a cobbled surface.                                                                                ::
    ID: 07000014.wav
    Length: 37
** One horse departs with small cart on a cobbled surface.                                                                                ::
    ID: 07000013.wav
    Length: 32
** Two horses approach and stop with cart on a cobbled surface.                                                                                ::
    ID: 07000012.wav
    Length: 49
** Two horses approach and stop with cart on a cobbled surface.                                                                                ::
    ID: 07000011.wav
    Length: 32
** Two horses depart with cart on cobbled surface.                                                                                ::
    ID: 07000010.wav
    Length: 38
** Two horses approach and stop, harnessed up to cart on cobbled surface.                                                                                ::
    ID: 07000009.wav
    Length: 62
** Trot to stop with dog cart. (Recorded on one-horse cart)                                                                                ::
    ID: 07000008.wav
    Length: 15
** Start, trot and stop with dog cart. (Recorded on one-horse cart)                                                                                ::
    ID: 07000007.wav
    Length: 177
** Walk to stop with light cart. (Recorded on one-horse cart)                                                                                ::
    ID: 07000006.wav
    Length: 13
** Start, walk and stop with light cart. (Recorded on one-horse cart)                                                                                ::
    ID: 07000005.wav
    Length: 168
** Trot to stop with cart. (Recorded on two-horse cart)                                                                                ::
    ID: 07000004.wav
    Length: 15
** Start, trot and stop with cart. (Recorded on two-horse cart)                                                                                ::
    ID: 07000003.wav
    Length: 169
** Walk to stop with loaded cart. (Recorded on two-horse cart)                                                                                ::
    ID: 07000002.wav
    Length: 15
** Start, walk and stop with loaded cart. (Recorded on two-horse cart)                                                                                ::
    ID: 07000001.wav
    Length: 175
** tv static - white noise - shash                                                                                ::
    ID: 0010006.wav
    Length: 29
** tape spooling - dv cam - medium - various sport rushes - includi                                                                                ::
    ID: 0010005.wav
    Length: 28
** tape spooling - dv cam - medium - press conference - including s                                                                                ::
    ID: 0010004.wav
    Length: 11
** tape spooling - beta sp - rushes - medium spooling - various loc                                                                                ::
    ID: 0010003.wav
    Length: 45
** tape spooling - beta sp - male interview exterior - fast spoolin                                                                                ::
    ID: 0010002.wav
    Length: 8
** tape spooling - beta sp - cut story package - fast spooling - in                                                                                ::
    ID: 0010001.wav
    Length: 13
** weather - torrential rain                                                                                ::
    ID: 0009076.wav
    Length: 29
** weather - strong wind                                                                                ::
    ID: 0009075.wav
    Length: 29
** weather - strong gusty wind                                                                                ::
    ID: 0009074.wav
    Length: 29
** weather - rain                                                                                ::
    ID: 0009073.wav
    Length: 29
** weather - hurricane                                                                                ::
    ID: 0009072.wav
    Length: 29
** vacuum cleaner - hoover                                                                                ::
    ID: 0009071.wav
    Length: 29
** under water - diving - bubbles                                                                                ::
    ID: 0009070.wav
    Length: 29
** train - train arrives at station                                                                                ::
    ID: 0009069.wav
    Length: 39
** train - diesel train interior leaves station                                                                                ::
    ID: 0009068.wav
    Length: 29
** train - diesel train exterior passes                                                                                ::
    ID: 0009067.wav
    Length: 29
** traffic - shepherds bush                                                                                ::
    ID: 0009066.wav
    Length: 29
** traffic - motorway - road - distant                                                                                ::
    ID: 0009065.wav
    Length: 29
** suburban town                                                                                ::
    ID: 0009064.wav
    Length: 29
** suburban garden                                                                                ::
    ID: 0009063.wav
    Length: 29
** stream - gentle stream                                                                                ::
    ID: 0009062.wav
    Length: 30
** sports car - stop start and away                                                                                ::
    ID: 0009061.wav
    Length: 29
** sports car - interior and start                                                                                ::
    ID: 0009060.wav
    Length: 28
** small outdoor sporting event - rugby - football - running                                                                                ::
    ID: 0009059.wav
    Length: 29
** shopping - shopping precinct - mall                                                                                ::
    ID: 0009058.wav
    Length: 29
** shopping - shop interior - shopping - mall - precinct                                                                                ::
    ID: 0009057.wav
    Length: 29
** seaside - waves onto shore                                                                                ::
    ID: 0009056.wav
    Length: 29
** seaside - water lapping over pebbles                                                                                ::
    ID: 0009055.wav
    Length: 30
** seaside - sea wash rough - waves                                                                                ::
    ID: 0009054.wav
    Length: 29
** seaside - sea wash calm - waves                                                                                ::
    ID: 0009053.wav
    Length: 29
** seaside - harbour wall with gulls                                                                                ::
    ID: 0009052.wav
    Length: 29
** seaside - harbour wall at night                                                                                ::
    ID: 0009051.wav
    Length: 29
** seaside - calm sea                                                                                ::
    ID: 0009050.wav
    Length: 29
** seaside - beach with surf                                                                                ::
    ID: 0009049.wav
    Length: 30
** rifle - single shot                                                                                ::
    ID: 0009047.wav
    Length: 29
** rifle - machine gun                                                                                ::
    ID: 0009046.wav
    Length: 29
** rifle - automatic                                                                                ::
    ID: 0009045.wav
    Length: 29
** home - bath water                                                                                ::
    ID: 0009044.wav
    Length: 29
** fire - raging inferno                                                                                ::
    ID: 0009043.wav
    Length: 29
** fire - more fire                                                                                ::
    ID: 0009042.wav
    Length: 29
** fire - fire hoses                                                                                ::
    ID: 0009041.wav
    Length: 29
** fire - fire crackle                                                                                ::
    ID: 0009040.wav
    Length: 29
** fire - big fire                                                                                ::
    ID: 0009039.wav
    Length: 29
** cricket - bat on ball                                                                                ::
    ID: 0009038.wav
    Length: 29
** cricket - applause                                                                                ::
    ID: 0009037.wav
    Length: 29
** crash - various                                                                                ::
    ID: 0009036.wav
    Length: 29
** crash - car                                                                                ::
    ID: 0009035.wav
    Length: 29
** crash - aeroplane - piston                                                                                ::
    ID: 0009034.wav
    Length: 29
** countryside - summer skylarks                                                                                ::
    ID: 0009033.wav
    Length: 29
** countryside - summer                                                                                ::
    ID: 0009032.wav
    Length: 29
** countryside - crickets                                                                                ::
    ID: 0009031.wav
    Length: 29
** children - playing                                                                                ::
    ID: 0009030.wav
    Length: 29
** children - playground                                                                                ::
    ID: 0009029.wav
    Length: 29
** chatter - pub chatter 70 people                                                                                ::
    ID: 0009028.wav
    Length: 29
** chatter - pub chatter 20-30 people                                                                                ::
    ID: 0009027.wav
    Length: 29
** chatter - press conference - snappers - presser                                                                                ::
    ID: 0009026.wav
    Length: 30
** chatter - conference atmos                                                                                ::
    ID: 0009025.wav
    Length: 29
** chatter - conference applause                                                                                ::
    ID: 0009024.wav
    Length: 29
** chatter - cheers and applause                                                                                ::
    ID: 0009023.wav
    Length: 30
** chatter - chattering                                                                                ::
    ID: 0009022.wav
    Length: 29
** chatter - audience murmur                                                                                ::
    ID: 0009021.wav
    Length: 29
** chatter - 6000 people - exterior                                                                                ::
    ID: 0009020.wav
    Length: 29
** car - start and run exterior                                                                                ::
    ID: 0009019.wav
    Length: 29
** car - doors and horn                                                                                ::
    ID: 0009018.wav
    Length: 29
** car - arrives                                                                                ::
    ID: 0009017.wav
    Length: 28
** boat - ships sirens plus atmos                                                                                ::
    ID: 0009016.wav
    Length: 29
** boat - ships sirens                                                                                ::
    ID: 0009015.wav
    Length: 29
** boat - outboard motor 4HP start                                                                                ::
    ID: 0009014.wav
    Length: 6
** boat - outboard motor 40HP pass                                                                                ::
    ID: 0009013.wav
    Length: 29
** boat - outboard motor 40HP onboard                                                                                ::
    ID: 0009012.wav
    Length: 27
** boat - outboard motor 40HP ashore                                                                                ::
    ID: 0009011.wav
    Length: 29
** atmos - rumble roar                                                                                ::
    ID: 0009010.wav
    Length: 29
** atmos - police and fire sirens                                                                                ::
    ID: 0009009.wav
    Length: 29
** atmos - marching                                                                                ::
    ID: 0009008.wav
    Length: 29
** atmos - industrial skyline                                                                                ::
    ID: 0009007.wav
    Length: 29
** atmos - helicopter exterior                                                                                :Aircraft:Helicopters:
    ID: 0009006.wav
    Length: 29
** atmos - heavy engineering works                                                                                ::
    ID: 0009005.wav
    Length: 29
** atmos - city skyline                                                                                ::
    ID: 0009004.wav
    Length: 29
** aeroplane - light aircraft - exterior - runway                                                                                ::
    ID: 0009003.wav
    Length: 29
** aeroplane - light aircraft - exterior                                                                                ::
    ID: 0009002.wav
    Length: 29
** aeroplane - glider                                                                                ::
    ID: 0009001.wav
    Length: 29
** aeroplane - aircraft interior - light piston engine                                                                                ::
    ID: 0009000.wav
    Length: 29
** Workshop                                                                                ::
    ID: 00008125.wav
    Length: 29
** Waterfall                                                                                ::
    ID: 00008124.wav
    Length: 29
** Walk in the park                                                                                ::
    ID: 00008123.wav
    Length: 29
** Underground train (int.)                                                                                ::
    ID: 00008122.wav
    Length: 29
** Underground platform                                                                                ::
    ID: 00008121.wav
    Length: 29
** Turbine hall                                                                                ::
    ID: 00008120.wav
    Length: 29
** Trouble in townships                                                                                ::
    ID: 00008119.wav
    Length: 29
** Trains (moving slowly)                                                                                ::
    ID: 00008118.wav
    Length: 29
** Train interior                                                                                ::
    ID: 00008117.wav
    Length: 29
** Town traffic(wet road)                                                                                ::
    ID: 00008116.wav
    Length: 29
** Tennis (applause)                                                                                ::
    ID: 00008115.wav
    Length: 29
** Tanks                                                                                ::
    ID: 00008114.wav
    Length: 29
** Supermarket                                                                                ::
    ID: 00008113.wav
    Length: 29
** Street fighting                                                                                ::
    ID: 00008112.wav
    Length: 29
** Street battle                                                                                ::
    ID: 00008111.wav
    Length: 29
** Stream                                                                                ::
    ID: 00008110.wav
    Length: 29
** Stream-down drain                                                                                ::
    ID: 00008109.wav
    Length: 29
** Small group children                                                                                ::
    ID: 00008107.wav
    Length: 29
** Small arms (close)                                                                                ::
    ID: 00008106.wav
    Length: 29
** Small arms battle                                                                                ::
    ID: 00008105.wav
    Length: 29
** Shotgun rifle                                                                                ::
    ID: 00008104.wav
    Length: 29
** Shopping centre                                                                                ::
    ID: 00008103.wav
    Length: 29
** Sea wash on rocks                                                                                ::
    ID: 00008102.wav
    Length: 29
** Sea from clifftop                                                                                ::
    ID: 00008101.wav
    Length: 29
** S.African rioters                                                                                ::
    ID: 00008100.wav
    Length: 29
** S.Africa chanting 1                                                                                ::
    ID: 00008099.wav
    Length: 29
** Rugby crowd                                                                                ::
    ID: 00008098.wav
    Length: 29
** Rocket launcher                                                                                ::
    ID: 00008097.wav
    Length: 29
** Riot no. 2                                                                                ::
    ID: 00008096.wav
    Length: 29
** Riot no.1                                                                                ::
    ID: 00008095.wav
    Length: 29
** Research laboratory                                                                                ::
    ID: 00008094.wav
    Length: 29
** Reporters(large hall)                                                                                ::
    ID: 00008093.wav
    Length: 29
** Reporters(exterior)                                                                                ::
    ID: 00008092.wav
    Length: 29
** Rain                                                                                ::
    ID: 00008090.wav
    Length: 29
** Rainforest                                                                                ::
    ID: 00008089.wav
    Length: 29
** Railway station                                                                                ::
    ID: 00008088.wav
    Length: 29
** Quiet room                                                                                ::
    ID: 00008087.wav
    Length: 29
** Quiet hall                                                                                ::
    ID: 00008086.wav
    Length: 29
** Prison landing                                                                                ::
    ID: 00008085.wav
    Length: 29
** Prison cell interior                                                                                ::
    ID: 00008084.wav
    Length: 29
** Printing                                                                                ::
    ID: 00008083.wav
    Length: 29
** Presser(with cameras)                                                                                ::
    ID: 00008082.wav
    Length: 29
** Presser(small+cameras)                                                                                ::
    ID: 00008081.wav
    Length: 29
** Presser(quiet)                                                                                ::
    ID: 00008080.wav
    Length: 29
** Presser(noisey)                                                                                ::
    ID: 00008079.wav
    Length: 29
** Police car                                                                                ::
    ID: 00008078.wav
    Length: 29
** Playground                                                                                ::
    ID: 00008077.wav
    Length: 29
** Pharmacy                                                                                ::
    ID: 00008076.wav
    Length: 29
** Pedestrian street                                                                                ::
    ID: 00008075.wav
    Length: 29
** Office                                                                                ::
    ID: 00008074.wav
    Length: 29
** Motorway                                                                                ::
    ID: 00008073.wav
    Length: 29
** Modern tills                                                                                ::
    ID: 00008072.wav
    Length: 29
** Mining(pneumatic drills)                                                                                ::
    ID: 00008071.wav
    Length: 29
** Mining(general atmos)                                                                                ::
    ID: 00008070.wav
    Length: 29
** Mid-distance traffic                                                                                ::
    ID: 00008069.wav
    Length: 29
** Massed helicopters                                                                                :Aircraft:Helicopters:
    ID: 00008068.wav
    Length: 29
** Marching                                                                                ::
    ID: 00008067.wav
    Length: 29
** Light aircraft (interior)                                                                                ::
    ID: 00008066.wav
    Length: 29
** Large restless crowd                                                                                ::
    ID: 00008065.wav
    Length: 29
** Large moving crowd                                                                                ::
    ID: 00008064.wav
    Length: 29
** Large guns barrage                                                                                ::
    ID: 00008063.wav
    Length: 29
** Lakeside calm sea                                                                                ::
    ID: 00008062.wav
    Length: 29
** Jets overhead                                                                                ::
    ID: 00008061.wav
    Length: 29
** Industrial skyline                                                                                ::
    ID: 00008060.wav
    Length: 29
** Industrial dispute 2                                                                                ::
    ID: 00008059.wav
    Length: 29
** Industrial dispute 1                                                                                 ::
    ID: 00008058.wav
    Length: 29
** Indian chatter                                                                                ::
    ID: 00008057.wav
    Length: 29
** Hospital ward                                                                                ::
    ID: 00008056.wav
    Length: 29
** Hospital corridor                                                                                ::
    ID: 00008055.wav
    Length: 29
** High street                                                                                ::
    ID: 00008054.wav
    Length: 29
** Helicopter internal                                                                                :Aircraft:Helicopters:
    ID: 00008053.wav
    Length: 29
** Heavy engineering                                                                                ::
    ID: 00008052.wav
    Length: 29
** Golf(strokes & applause)                                                                                ::
    ID: 00008051.wav
    Length: 29
** General chatter(exterior)                                                                                ::
    ID: 00008050.wav
    Length: 29
** Furnace                                                                                ::
    ID: 00008049.wav
    Length: 29
** Football goals                                                                                ::
    ID: 00008048.wav
    Length: 29
** Football crowd                                                                                ::
    ID: 00008047.wav
    Length: 29
** Fire engines                                                                                ::
    ID: 00008046.wav
    Length: 29
** Film projector                                                                                ::
    ID: 00008045.wav
    Length: 29
** English countryside                                                                                ::
    ID: 00008044.wav
    Length: 29
** Downhill skiing                                                                                ::
    ID: 00008043.wav
    Length: 29
** Docks(busy)                                                                                ::
    ID: 00008042.wav
    Length: 29
** Department store                                                                                ::
    ID: 00008041.wav
    Length: 29
** Crowd-Royal occasion                                                                                ::
    ID: 00008040.wav
    Length: 29
** Cricket ovation                                                                                ::
    ID: 00008039.wav
    Length: 29
** Cricket(hit+applause)                                                                                ::
    ID: 00008038.wav
    Length: 29
** Convoy(lorries & tanks)                                                                                ::
    ID: 00008037.wav
    Length: 29
** Conference                                                                                ::
    ID: 00008036.wav
    Length: 29
** Classroom                                                                                ::
    ID: 00008035.wav
    Length: 29
** Classroom (infants)                                                                                ::
    ID: 00008034.wav
    Length: 29
** Clapping & whistling                                                                                ::
    ID: 00008033.wav
    Length: 29
** City traffic                                                                                ::
    ID: 00008032.wav
    Length: 29
** City-stock exchange                                                                                ::
    ID: 00008031.wav
    Length: 29
** City skyline                                                                                ::
    ID: 00008030.wav
    Length: 29
** City dealing room                                                                                ::
    ID: 00008029.wav
    Length: 29
** China-street+traffic                                                                                ::
    ID: 00008028.wav
    Length: 29
** China-narrow street                                                                                ::
    ID: 00008027.wav
    Length: 29
** Childrens ward                                                                                ::
    ID: 00008026.wav
    Length: 29
** Cheers for the Queen                                                                                ::
    ID: 00008025.wav
    Length: 29
** Chatter                                                                                ::
    ID: 00008024.wav
    Length: 29
** Chatter(politicians)                                                                                ::
    ID: 00008023.wav
    Length: 29
** Chatter & footsteps                                                                                ::
    ID: 00008022.wav
    Length: 29
** Car body plant                                                                                ::
    ID: 00008021.wav
    Length: 29
** Camera clicks                                                                                ::
    ID: 00008020.wav
    Length: 29
** Bus station                                                                                ::
    ID: 00008019.wav
    Length: 29
** Building site                                                                                ::
    ID: 00008018.wav
    Length: 29
** Breeze                                                                                ::
    ID: 00008017.wav
    Length: 29
** Bottling plant                                                                                ::
    ID: 00008016.wav
    Length: 29
** Blustery wind                                                                                ::
    ID: 00008015.wav
    Length: 29
** Big fire                                                                                ::
    ID: 00008014.wav
    Length: 29
** Beach+children                                                                                ::
    ID: 00008013.wav
    Length: 29
** Battlefield                                                                                ::
    ID: 00008012.wav
    Length: 29
** Battlefield(distant)                                                                                ::
    ID: 00008011.wav
    Length: 29
** Battlefield (close)                                                                                ::
    ID: 00008010.wav
    Length: 29
** Bank                                                                                ::
    ID: 00008009.wav
    Length: 29
** Arabic Chatter                                                                                ::
    ID: 00008008.wav
    Length: 29
** Applause+cheers                                                                                ::
    ID: 00008007.wav
    Length: 29
** Angry chatter                                                                                ::
    ID: 00008006.wav
    Length: 29
** Ambulance(interior)                                                                                ::
    ID: 00008005.wav
    Length: 29
** Ambulance(close)                                                                                ::
    ID: 00008004.wav
    Length: 29
** Air strike                                                                                ::
    ID: 00008003.wav
    Length: 29
** Airport terminal                                                                                ::
    ID: 00008002.wav
    Length: 29
** Airport exterior                                                                                ::
    ID: 00008001.wav
    Length: 29
** African market                                                                                ::
    ID: 00008000.wav
    Length: 29
