** Domestic clock striking eleven o'clock. (Nineteenth century domestic clock.)                                                                                ::
    ID: 07022142.wav
    Length: 24
** Domestic clock striking ten o'clock. (Nineteenth century domestic clock.)                                                                                ::
    ID: 07022141.wav
    Length: 23
** Domestic clock ticking.                                                                                ::
    ID: 07022140.wav
    Length: 95
** Domestic clock ticking.                                                                                ::
    ID: 07022139.wav
    Length: 96
** Domestic clock ticking.                                                                                ::
    ID: 07022138.wav
    Length: 98
** Domestic clock ticking.                                                                                ::
    ID: 07022137.wav
    Length: 96
** Domestic clock ticking. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022136.wav
    Length: 121
** Domestic clock striking nine o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022135.wav
    Length: 35
** Domestic clock striking eight o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022134.wav
    Length: 34
** Domestic clock striking seven o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022133.wav
    Length: 33
** Domestic clock striking six o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022132.wav
    Length: 32
** Domestic clock striking five o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022131.wav
    Length: 30
** Domestic clock striking four o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022130.wav
    Length: 29
** Domestic clock striking three o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022129.wav
    Length: 28
** Domestic clock striking two o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022128.wav
    Length: 27
** Domestic clock striking one o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022127.wav
    Length: 26
** Domestic clock striking twelve o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022126.wav
    Length: 38
** Domestic clock striking eleven o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022125.wav
    Length: 37
** Domestic clock striking ten o'clock. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022124.wav
    Length: 36
** Domestic clock striking quarter to the hour. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022123.wav
    Length: 34
** Domestic clock striking half past the hour. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022122.wav
    Length: 27
** Domestic clock striking quarter past the hour. (English domestic clock, manufactured 1810.)                                                                                ::
    ID: 07022121.wav
    Length: 23
** Domestic clock striking nine o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022120.wav
    Length: 22
** Domestic clock striking eight o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022119.wav
    Length: 20
** Domestic clock striking seven o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022118.wav
    Length: 18
** Domestic clock striking six o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022117.wav
    Length: 16
** Domestic clock striking five o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022116.wav
    Length: 14
** Domestic clock striking four o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022115.wav
    Length: 12
** Domestic clock striking three o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022114.wav
    Length: 10
** Domestic clock striking two o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022113.wav
    Length: 7
** Domestic clock striking one o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022112.wav
    Length: 6
** Domestic clock striking twelve o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022111.wav
    Length: 28
** Domestic clock striking eleven o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022110.wav
    Length: 26
** Domestic clock striking ten o'clock. (Domestic clock with double-strike on wood.)                                                                                ::
    ID: 07022109.wav
    Length: 24
** Domestic clock striking nine o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022108.wav
    Length: 30
** Domestic clock striking eight o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022107.wav
    Length: 28
** Domestic clock striking seven o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022106.wav
    Length: 26
** Domestic clock striking six o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022105.wav
    Length: 25
** Domestic clock striking five o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022104.wav
    Length: 23
** Domestic clock striking four o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022103.wav
    Length: 20
** Domestic clock striking three o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022102.wav
    Length: 19
** Domestic clock striking two o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022101.wav
    Length: 17
** Domestic clock striking one o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022100.wav
    Length: 15
** Domestic clock striking twelve o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022099.wav
    Length: 37
** Domestic clock striking eleven o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022098.wav
    Length: 34
** Domestic clock striking ten o'clock. (Domestic clock with heavy double-strike mechanism.)                                                                                ::
    ID: 07022097.wav
    Length: 32
** Domestic clock striking nine o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022096.wav
    Length: 21
** Domestic clock striking eight o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022095.wav
    Length: 19
** Domestic clock striking seven o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022094.wav
    Length: 18
** Domestic clock striking six o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022093.wav
    Length: 17
** Domestic clock striking five o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022092.wav
    Length: 16
** Domestic clock striking four o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022091.wav
    Length: 15
** Domestic clock striking three o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022090.wav
    Length: 13
** Domestic clock striking two o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022089.wav
    Length: 12
** Domestic clock striking one o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022088.wav
    Length: 11
** Domestic clock striking twelve o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022087.wav
    Length: 24
** Domestic clock striking eleven o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022086.wav
    Length: 23
** Domestic clock striking ten o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022085.wav
    Length: 23
** Domestic clock striking nine o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022084.wav
    Length: 29
** Domestic clock striking eight o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022083.wav
    Length: 26
** Domestic clock striking seven o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022082.wav
    Length: 25
** Domestic clock striking six o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022081.wav
    Length: 23
** Domestic clock striking five o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022080.wav
    Length: 21
** Domestic clock striking four o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022079.wav
    Length: 20
** Domestic clock striking three o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022078.wav
    Length: 17
** Domestic clock striking two o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022077.wav
    Length: 16
** Domestic clock striking one o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022076.wav
    Length: 13
** Domestic clock striking twelve o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022075.wav
    Length: 34
** Domestic clock striking eleven o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022074.wav
    Length: 32
** Domestic clock striking ten o'clock. (Domestic clock with heavy gong.)                                                                                ::
    ID: 07022073.wav
    Length: 31
** Domestic clock striking nine o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022072.wav
    Length: 24
** Domestic clock striking eight o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022071.wav
    Length: 21
** Domestic clock striking seven o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022070.wav
    Length: 19
** Domestic clock striking six o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022069.wav
    Length: 18
** Domestic clock striking five o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022068.wav
    Length: 16
** Domestic clock striking four o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022067.wav
    Length: 14
** Domestic clock striking three o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022066.wav
    Length: 12
** Domestic clock striking two o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022065.wav
    Length: 11
** Domestic clock striking one o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022064.wav
    Length: 8
** Domestic clock striking twelve o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022063.wav
    Length: 30
** Domestic clock striking eleven o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022062.wav
    Length: 28
** Domestic clock striking ten o'clock. (Mid-perspective recording of domestic clock with bell.)                                                                                ::
    ID: 07022061.wav
    Length: 27
** Domestic clock striking nine o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022060.wav
    Length: 22
** Domestic clock striking eight o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022059.wav
    Length: 21
** Domestic clock striking seven o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022058.wav
    Length: 20
** Domestic clock striking six o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022057.wav
    Length: 17
** Domestic clock striking five o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022056.wav
    Length: 17
** Domestic clock striking four o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022055.wav
    Length: 16
** Domestic clock striking three o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022054.wav
    Length: 14
** Domestic clock striking two o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022053.wav
    Length: 13
** Domestic clock striking one o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022052.wav
    Length: 13
** Domestic clock striking twelve o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022051.wav
    Length: 25
** Domestic clock striking eleven o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022050.wav
    Length: 25
** Domestic clock striking ten o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022049.wav
    Length: 25
** Domestic clock striking nine o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022048.wav
    Length: 31
** Domestic clock striking eight o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022047.wav
    Length: 28
** Domestic clock striking seven o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022046.wav
    Length: 24
** Domestic clock striking six o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022045.wav
    Length: 23
** Domestic clock striking five o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022044.wav
    Length: 20
** Domestic clock striking four o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022043.wav
    Length: 18
** Domestic clock striking three o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022042.wav
    Length: 14
** Domestic clock striking two o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022041.wav
    Length: 13
** Domestic clock striking one o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022040.wav
    Length: 10
** Domestic clock striking twelve o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022039.wav
    Length: 37
** Domestic clock striking eleven o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022038.wav
    Length: 34
** Domestic clock striking ten o'clock. (Domestic clock with bell & heavy machanism.)                                                                                ::
    ID: 07022037.wav
    Length: 32
** Domestic clock striking nine o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022036.wav
    Length: 19
** Domestic clock striking eight o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022035.wav
    Length: 18
** Domestic clock striking seven o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022034.wav
    Length: 16
** Domestic clock striking six o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022033.wav
    Length: 15
** Domestic clock striking five o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022032.wav
    Length: 14
** Domestic clock striking four o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022031.wav
    Length: 13
** Domestic clock striking three o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022030.wav
    Length: 11
** Domestic clock striking two o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022029.wav
    Length: 9
** Domestic clock striking one o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022028.wav
    Length: 7
** Domestic clock striking twelve o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022027.wav
    Length: 23
** Domestic clock striking eleven o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022026.wav
    Length: 21
** Domestic clock striking ten o'clock. (Domestic clock with bell.)                                                                                ::
    ID: 07022025.wav
    Length: 20
** Domestic clock striking nine o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022024.wav
    Length: 30
** Domestic clock striking eight o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022023.wav
    Length: 28
** Domestic clock striking seven o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022022.wav
    Length: 26
** Domestic clock striking six o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022021.wav
    Length: 24
** Domestic clock striking five o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022020.wav
    Length: 22
** Domestic clock striking four o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022019.wav
    Length: 20
** Domestic clock striking three o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022018.wav
    Length: 16
** Domestic clock striking two o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022017.wav
    Length: 16
** Domestic clock striking one o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022016.wav
    Length: 13
** Domestic clock striking twelve o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022015.wav
    Length: 38
** Domestic clock striking eleven o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022014.wav
    Length: 35
** Domestic clock striking ten o'clock. (Domestic clock with single-strike mechanism.)                                                                                ::
    ID: 07022013.wav
    Length: 33
** Domestic clock striking nine o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022012.wav
    Length: 35
** Domestic clock striking eight o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022011.wav
    Length: 32
** Domestic clock striking seven o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022010.wav
    Length: 30
** Domestic clock striking six o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022009.wav
    Length: 37
** Domestic clock striking five o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022008.wav
    Length: 27
** Domestic clock striking four o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022007.wav
    Length: 23
** Domestic clock striking three o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022006.wav
    Length: 20
** Domestic clock striking two o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022005.wav
    Length: 18
** Domestic clock striking one o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022004.wav
    Length: 15
** Domestic clock striking twelve o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022003.wav
    Length: 43
** Domestic clock striking eleven o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022002.wav
    Length: 40
** Domestic clock striking ten o'clock. (Domestic clock with double-strike mechanism.)                                                                                ::
    ID: 07022001.wav
    Length: 37
** Children's Swimming Pool, general atmosphere with young children.                                                                                ::
    ID: 07021138.wav
    Length: 393
** Children's Swimming Pool, general atmosphere.                                                                                ::
    ID: 07021137.wav
    Length: 394
** Indoor Swimming Pool, three dives.                                                                                ::
    ID: 07021136.wav
    Length: 14
** Indoor Swimming Pool, three dives.                                                                                ::
    ID: 07021135.wav
    Length: 25
** Indoor Swimming Pool, three dives.                                                                                ::
    ID: 07021134.wav
    Length: 16
** Indoor Swimming Pool, dive.                                                                                ::
    ID: 07021133.wav
    Length: 19
** Indoor Swimming Pool, dive.                                                                                ::
    ID: 07021132.wav
    Length: 16
** Indoor Swimming Pool, dive.                                                                                ::
    ID: 07021131.wav
    Length: 18
** Indoor Swimming Pool, footsteps on springboard and dive.                                                                                ::
    ID: 07021130.wav
    Length: 27
** Indoor Swimming Pool, footsteps on springboard and dive.                                                                                ::
    ID: 07021129.wav
    Length: 9
** Indoor Swimming Pool, footsteps on springboard and dive.                                                                                ::
    ID: 07021128.wav
    Length: 21
** Indoor Swimming Pool, footsteps on springboard and dive.                                                                                ::
    ID: 07021127.wav
    Length: 23
** Indoor Swimming Pool, footsteps on springboard and dive.                                                                                ::
    ID: 07021126.wav
    Length: 15
** Indoor Swimming Pool, footsteps on springboard and dive.                                                                                ::
    ID: 07021125.wav
    Length: 15
** Indoor Swimming Pool, succession of dives.                                                                                ::
    ID: 07021124.wav
    Length: 137
** Indoor Swimming Pool, three dives.                                                                                ::
    ID: 07021123.wav
    Length: 31
** Splash & voices in Indoor Swimming Pool.                                                                                ::
    ID: 07021122.wav
    Length: 16
** Splash in Indoor Swimming Pool.                                                                                ::
    ID: 07021121.wav
    Length: 21
** Splash in Indoor Swimming Pool.                                                                                ::
    ID: 07021120.wav
    Length: 12
** Indoor Swimming Pool, swimmer dives in, crawl.                                                                                ::
    ID: 07021119.wav
    Length: 133
** Indoor Swimming Pool, swimmer dives in, butterfly stroke.                                                                                ::
    ID: 07021118.wav
    Length: 123
** Indoor Swimming Pool, swimmer dives in, back stroke.                                                                                ::
    ID: 07021117.wav
    Length: 129
** Indoor Swimming Pool, swimmer dives in, breast stroke.                                                                                ::
    ID: 07021116.wav
    Length: 124
** Indoor Swimming Pool, general atmosphere with a few swimmers & very occassional voices.                                                                                ::
    ID: 07021115.wav
    Length: 454
** Indoor Swimming Pool, general atmosphere, uncrowded with  dives & splashes.                                                                                ::
    ID: 07021114.wav
    Length: 453
** Indoor Swimming Pool, general atmosphere with small children.                                                                                ::
    ID: 07021113.wav
    Length: 454
** Indoor Swimming Pool, general atmosphere with mainly adults.                                                                                ::
    ID: 07021112.wav
    Length: 454
** Thrashing in water in swimming pool.                                                                                ::
    ID: 07021111.wav
    Length: 216
** Springboard and splash in swimming pool.                                                                                ::
    ID: 07021110.wav
    Length: 14
** Springboard and splash in swimming pool.                                                                                ::
    ID: 07021109.wav
    Length: 11
** Springboard and splash in swimming pool.                                                                                ::
    ID: 07021108.wav
    Length: 9
** Springboard  in swimming pool.                                                                                ::
    ID: 07021107.wav
    Length: 7
** Multiple splash in swimming pool.                                                                                ::
    ID: 07021106.wav
    Length: 13
** Double splash in swimming pool.                                                                                ::
    ID: 07021105.wav
    Length: 10
** Splash in swimming pool.                                                                                ::
    ID: 07021104.wav
    Length: 13
** Splash in swimming pool.                                                                                ::
    ID: 07021103.wav
    Length: 12
** Splash in swimming pool.                                                                                ::
    ID: 07021102.wav
    Length: 13
** Splash in swimming pool.                                                                                ::
    ID: 07021101.wav
    Length: 12
** Outdoor swimming pool, children diving & using chute.                                                                                ::
    ID: 07021100.wav
    Length: 369
** Outdoor Swimming Pool, swimmer enters water, breast stroke, leaves water.                                                                                ::
    ID: 07021099.wav
    Length: 119
** Outdoor Swimming Pool, swimmer enters water, swims with legs only, leaves water.                                                                                ::
    ID: 07021098.wav
    Length: 99
** Outdoor Swimming Pool, swimmer enters water, front crawl, leaves water.                                                                                ::
    ID: 07021097.wav
    Length: 112
** Outdoor Swimming Pool, general atmosphere near diving board.                                                                                ::
    ID: 07021096.wav
    Length: 371
** Outdoor Swimming Pool, general atmosphere.                                                                                ::
    ID: 07021095.wav
    Length: 378
** Boys' School, boys in showers with indistinct speech in foreground. (Wide perspective recording.)                                                                                ::
    ID: 07021094.wav
    Length: 138
** Boys' School gymnasium, atmosphere in gym while boys play basketball, with some indistinct speech & coach's whistle blown occasionally.                                                                                ::
    ID: 07021093.wav
    Length: 250
** Boys' School hall, constant background of boys in hall.                                                                                ::
    ID: 07021092.wav
    Length: 195
** Boys' School, atmosphere in assembly with loud indistinct chatter. (Bell rings at 0m25s.)                                                                                ::
    ID: 07021091.wav
    Length: 190
** Boys' School, boys leave hall & pass along corridor, with indistinct chatter & footsteps.                                                                                ::
    ID: 07021090.wav
    Length: 197
** Boys' School, boys enter school, with indistinct speech & footsteps. (Bell sounds at 2m22s.)                                                                                ::
    ID: 07021089.wav
    Length: 196
** Boys' School, boys entering school, with indistinct speech and footsteps.                                                                                ::
    ID: 07021088.wav
    Length: 203
** Boys' School, juniors at play in schoolyard, with indistinct chatter & calls.                                                                                ::
    ID: 07021087.wav
    Length: 196
** Girls in gymnasium jumping over obstacles in pairs. (Some indistinct speech)                                                                                ::
    ID: 07021086.wav
    Length: 210
** Girls' Grammar School gymnasium, ball game started by mistress & girls commence playing in gym, with indistinct calls from mistress and chatter.                                                                                ::
    ID: 07021085.wav
    Length: 174
** Girls' Grammar School gymnasium, atmosphere in gymnasium while using medicine ball, with indistinct speech.                                                                                ::
    ID: 07021084.wav
    Length: 124
** Girls' Grammar School gymnasium, atmosphere in gymnasium with some skipping & indistinct speech.                                                                                ::
    ID: 07021083.wav
    Length: 122
** Girls' Grammar School gymnasium, atmosphere in gym with some skipping & indistinct speech.                                                                                ::
    ID: 07021082.wav
    Length: 120
** Girls' Grammar School, interior, indistinct chatter & footsteps on stairs.                                                                                ::
    ID: 07021081.wav
    Length: 124
** Girls' Grammar School cloisters, girls walking to and fro in cloisters, with some quiet indistinct chatter.                                                                                ::
    ID: 07021080.wav
    Length: 124
** Girls' Grammar School corridor, senior girls in corridor, with footsteps, laughter & some indistinct speech.                                                                                ::
    ID: 07021079.wav
    Length: 122
** Girls' Grammar School corridor, junior girls in corridor, with footsteps, laughter & some indistinct speech.                                                                                ::
    ID: 07021078.wav
    Length: 198
** Girls' Grammar School corridor, senior girls in corridor, with footsteps, laughter & some indistinct speech.                                                                                ::
    ID: 07021077.wav
    Length: 208
** Girls' Grammar School, interior, gong sounds, animated indistinct chatter commences.                                                                                ::
    ID: 07021076.wav
    Length: 199
** Girls' Grammar School, interior, indistinct chatter of 40 girls. (Wide perspective recording.)                                                                                ::
    ID: 07021075.wav
    Length: 197
** Girls' Grammar School classroom, footsteps & indistinct chatter as girls enter room.                                                                                ::
    ID: 07021074.wav
    Length: 256
** Girls' Grammar School classroom, laughter, chatter & atmosphere in class. (No distinct speech.)                                                                                ::
    ID: 07021073.wav
    Length: 40
** Girls' Grammar School, animated indistinct chatter of girls in hall, then silence as headmistress enters.                                                                                ::
    ID: 07021072.wav
    Length: 48
** Girls' Grammar School, chatter in laboratory during free period. (No distinct speech.)                                                                                ::
    ID: 07021071.wav
    Length: 199
** Girls' Grammar School, atmosphere in dining hall, with indistinct chatter & sounds of crockery being used. (Wide perspective recording.)                                                                                ::
    ID: 07021070.wav
    Length: 199
** Girls' Grammar School, girls filing out of hall with organ playing in background. (Footsteps, no chatter.)                                                                                ::
    ID: 07021069.wav
    Length: 212
** Girls' Grammar School, girls filing into hall with organ playing in background. (Footsteps, no chatter.)                                                                                ::
    ID: 07021068.wav
    Length: 199
** Girls' Grammar School, busy atmosphere of 300 girls in hall, with loud indistinct chatter & footsteps.                                                                                ::
    ID: 07021067.wav
    Length: 391
** Girls' Grammar School, girls filing into hall, with footsteps & indistinct chatter.                                                                                ::
    ID: 07021066.wav
    Length: 179
** Girls' Grammar School, chairs being set up in hall with some quiet periods & some chatter. (No distinct speech, wide perspective recording.)                                                                                ::
    ID: 07021065.wav
    Length: 199
** Girls' Grammar School, atmosphere in hall with footsteps & some indistinct chatter. (Wide perspective recording.)                                                                                ::
    ID: 07021064.wav
    Length: 198
** Girls' Grammar School, girls entering school building. (Footsteps & chatter, no distinct speech.)                                                                                ::
    ID: 07021063.wav
    Length: 203
** Girls' Grammar School, chatter in playground. (No distinct speech, some distant traffic.)                                                                                ::
    ID: 07021062.wav
    Length: 198
** Girls' Grammar School, chatter in playground & as girls enter school. (No distinct speech.)                                                                                ::
    ID: 07021061.wav
    Length: 199
** School Dining Hall, busy atmosphere with some indistinct speech & sounds of crockery being used.                                                                                ::
    ID: 07021060.wav
    Length: 364
** School Dining Hall, fairly quiet atmosphere with some indistinct speech & sounds of crockery being used.                                                                                ::
    ID: 07021059.wav
    Length: 362
** Fencing, in progress with scores called.                                                                                ::
    ID: 07021058.wav
    Length: 202
** Fencing, in progress, no scores called.                                                                                ::
    ID: 07021057.wav
    Length: 194
** Squash, game in progress.                                                                                ::
    ID: 07021056.wav
    Length: 256
** Squash, players knocking up.                                                                                ::
    ID: 07021055.wav
    Length: 119
** Badminton, doubles match. (No crowd)                                                                                ::
    ID: 07021054.wav
    Length: 243
** Badminton, singles match. (No crowd)                                                                                ::
    ID: 07021053.wav
    Length: 134
** Table Tennis, doubles match. (No crowd.)                                                                                ::
    ID: 07021052.wav
    Length: 189
** Table Tennis, singles match. (No crowd.)                                                                                ::
    ID: 07021051.wav
    Length: 184
** Snooker, game in progress. (Single game, no speech.)                                                                                ::
    ID: 07021050.wav
    Length: 334
** Snooker, setting up frame.                                                                                ::
    ID: 07021049.wav
    Length: 74
** Billiards, game in progress. (Single game, no speech.)                                                                                ::
    ID: 07021048.wav
    Length: 301
** Billiards, scoreboard being used. (Sliding indicator type.)                                                                                ::
    ID: 07021047.wav
    Length: 35
** Billiards, chalking cue. (Close perspective recording.)                                                                                ::
    ID: 07021046.wav
    Length: 46
** Billiards Saloon, general chatter in twelve table billiards saloon.                                                                                ::
    ID: 07021045.wav
    Length: 366
** Game of Snooker, small crowd chatters during game.                                                                                ::
    ID: 07021044.wav
    Length: 419
** Atmosphere at airfield with piston engined aircraft only, no jets. (Aircraft include Douglas Dakota, Airspeed Ambassador, Canadair Argonaut & Vickers Viking.)                                                                                ::
    ID: 07021043.wav
    Length: 372
** De Havilland Dove, exterior, passing overhead. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021042.wav
    Length: 44
** De Havilland Dove, interior, descend, land, taxi, switch off. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021041.wav
    Length: 311
** De Havilland Dove, exterior, passing overhead. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021040.wav
    Length: 40
** De Havilland Dove, exterior, rev up, taxi past & away. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021039.wav
    Length: 128
** De Havilland Dove, exterior, taxi to close-up, rev, switch off. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021038.wav
    Length: 102
** De Havilland Dove, exterior, landing. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021037.wav
    Length: 48
** De Havilland Dove, interior, climb into level flight. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021036.wav
    Length: 334
** De Havilland Dove, exterior, circling. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021035.wav
    Length: 110
** De Havilland Dove, exterior, taxi up & away, take off. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021034.wav
    Length: 216
** De Havilland Dove, exterior, take off. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021033.wav
    Length: 54
** De Havilland Dove, interior, engines run up, taxi, take off, climb. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021032.wav
    Length: 292
** De Havilland Dove, Exterior, start engines, warm up, taxi away. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021031.wav
    Length: 345
** De Havilland Dove, interior, start engines, rev up, taxi. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021030.wav
    Length: 103
** De Havilland Dove, interior, engines warm up, taxi. (Light civil aircraft, two piston engines.) (NB Military versions of this plane named Devon & Sea Devon.)                                                                                ::
    ID: 07021029.wav
    Length: 235
** BBC Paris Theatre, atmosphere during interval.                                                                                ::
    ID: 07021028.wav
    Length: 389
** BBC Paris Theatre, audience leaving.                                                                                ::
    ID: 07021027.wav
    Length: 199
** BBC Paris Theatre, audience entering & settling down.                                                                                ::
    ID: 07021026.wav
    Length: 198
** Theatre Foyer, atmosphere in foyer of large West Eend theatre, with bars.                                                                                ::
    ID: 07021025.wav
    Length: 211
** Theatre Foyer, atmosphere in foyer of West End theatre.                                                                                ::
    ID: 07021024.wav
    Length: 215
** Theatre Foyer, atmosphere in foyer of a small West End theatre.                                                                                ::
    ID: 07021023.wav
    Length: 215
** Theatre Foyer, atmosphere in foyer of repertory theatre.                                                                                ::
    ID: 07021022.wav
    Length: 207
** Royal Albert Hall, audience leaving.                                                                                ::
    ID: 07021021.wav
    Length: 123
** Royal Albert Hall, atmosphere during interval.                                                                                ::
    ID: 07021020.wav
    Length: 125
** Royal Albert Hall, tuning up after item. (Quiet after 0m40s.)                                                                                ::
    ID: 07021019.wav
    Length: 68
** Royal Albert Hall, atmosphere before concert.                                                                                ::
    ID: 07021018.wav
    Length: 346
** Royal Festival Hall, audience leaving.                                                                                ::
    ID: 07021017.wav
    Length: 122
** Royal Festival Hall, atmosphere during interval, builds up & dies down.                                                                                ::
    ID: 07021016.wav
    Length: 250
** Royal Festival Hall, atmosphere before concert.                                                                                ::
    ID: 07021015.wav
    Length: 370
** Broadcasting House Concert Hall, orchestra tuning up.                                                                                ::
    ID: 07021014.wav
    Length: 368
** Broadcasting House Concert Hall, string quartet tuning up.                                                                                ::
    ID: 07021013.wav
    Length: 43
** Broadcasting House Concert Hall, atmosphere before concert.                                                                                ::
    ID: 07021012.wav
    Length: 308
** A game of roulette being played in a casino with French croupier, some English voices.                                                                                ::
    ID: 07021011.wav
    Length: 380
** A game of cards being played in a small mixed social club.                                                                                ::
    ID: 07021010.wav
    Length: 273
** A roulette wheel spun several times. (Close perspective, no background)                                                                                ::
    ID: 07021009.wav
    Length: 84
** A game of craps being played in a club.                                                                                ::
    ID: 07021008.wav
    Length: 200
** A game of blackjack being played in a club.                                                                                ::
    ID: 07021007.wav
    Length: 198
** A game of roulette being played in a club with English female croupier.                                                                                ::
    ID: 07021006.wav
    Length: 179
** A game of roulette being played in a club, quiet atmosphere, English male croupier.                                                                                ::
    ID: 07021005.wav
    Length: 175
** Atmosphere, public address with voices in busy shop. (Betting Shop)                                                                                ::
    ID: 07021004.wav
    Length: 210
** Atmosphere, public address with voices. (Betting Shop)                                                                                ::
    ID: 07021003.wav
    Length: 213
** Atmosphere with public address. (Betting Shop)                                                                                ::
    ID: 07021002.wav
    Length: 214
** General atmosphere. (Betting Shop)                                                                                ::
    ID: 07021001.wav
    Length: 214
** Motorcycle Scrambling: Atmosphere near uphill bend, sidecars passing from right to left, some intelligible P.A.                                                                                :Motorcycle Scrambling:Atmosphere near uphill bend, sidecars pas:
    ID: 07020213.wav
    Length: 122
** Motorcycle Scrambling: Atmosphere near bend, pre 1965 machines                                                                                :Motorcycle Scrambling:Atmosphere near bend:
    ID: 07020212.wav
    Length: 56
** Motorcycle Scrambling: Atmosphere at beginning of pre-1965 race, starts 52" in                                                                                :Motorcycle Scrambling:Atmosphere at beginning of pre-1965 race:
    ID: 07020211.wav
    Length: 70
** Motorcycle Scrambling: Atmosphere at beginning of sidecar race starts 40" in                                                                                :Motorcycle Scrambling:
    ID: 07020210.wav
    Length: 60
** Motorcycle Scrambling: Atmosphere at beginning of solo race, starts 16" in                                                                                :Motorcycle Scrambling:Atmosphere at beginning of solo race:
    ID: 07020209.wav
    Length: 55
** Motorcycle Scrambling: General atmosphere, modern solo machines, 250-500cc                                                                                :Motorcycle Scrambling:General atmosphere:
    ID: 07020208.wav
    Length: 195
** Motorcycle Scrambling: General atmosphere, pre-1965 machines, 250-500cc                                                                                :Motorcycle Scrambling:General atmosphere:
    ID: 07020207.wav
    Length: 194
** Motor Cycles: Honda 250, Recorded on Bike, slow tickover                                                                                :Motorcycles:Honda 250:
    ID: 07020206.wav
    Length: 23
** Motor Cycles: Honda 250, Recorded on Bike, start, run, stop                                                                                :Motorcycles:Honda 250:
    ID: 07020205.wav
    Length: 64
** Motor Cycles: Honda 250, Recorded on Bike, start, fast move off, run                                                                                :Motorcycles:Honda 250:
    ID: 07020204.wav
    Length: 95
** Motor Cycles: Honda 250, kick start, manoeuvre                                                                                :Motorcycles:Honda 250:
    ID: 07020203.wav
    Length: 41
** Motor Cycles: Honda 250, pass with gear change                                                                                :Motorcycles:Honda 250:
    ID: 07020202.wav
    Length: 21
** Motor Cycles: Honda 250, pass with gear change                                                                                :Motorcycles:Honda 250:
    ID: 07020201.wav
    Length: 25
** Motor Cycles: Honda 250, medium pace approach, stop                                                                                :Motorcycles:Honda 250:
    ID: 07020200.wav
    Length: 21
** Motor Cycles: Honda 250, hurried approach, stop                                                                                :Motorcycles:Honda 250:
    ID: 07020199.wav
    Length: 27
** Motor Cycles: Honda 250, hurried approach, stop                                                                                :Motorcycles:Honda 250:
    ID: 07020198.wav
    Length: 20
** Motor Cycles: Honda 250, hurried approach, stop                                                                                :Motorcycles:Honda 250:
    ID: 07020197.wav
    Length: 19
** Motor Cycles: Honda 250, bike raised on to stand then lowered                                                                                :Motorcycles:Honda 250:
    ID: 07020196.wav
    Length: 14
** Motor Cycles: Honda 250, revving. Recorded close to exhaust                                                                                :Motorcycles:Honda 250:
    ID: 07020195.wav
    Length: 30
** Motor Cycles: Honda 250, kick start, revving                                                                                :Motorcycles:Honda 250:
    ID: 07020194.wav
    Length: 21
** Motor Cycles: Honda 250, attempted kick starts                                                                                :Motorcycles:Honda 250:
    ID: 07020193.wav
    Length: 8
** Motor Cycles: Honda 250, start, manoeuvre, switch off                                                                                :Motorcycles:Honda 250:
    ID: 07020192.wav
    Length: 48
** Motor Cycles: Honda 250 turn in road and depart                                                                                :Motor Cycles:
    ID: 07020191.wav
    Length: 25
** Motor Cycles: Honda 250 approach and pass at fast speed                                                                                :Motor Cycles:
    ID: 07020190.wav
    Length: 22
** Motor Cycles: Honda 250, medium speed pass                                                                                :Motorcycles:Honda 250:
    ID: 07020189.wav
    Length: 20
** Motor Cycles: Honda 250, passing slowly                                                                                :Motorcycles:Honda 250:
    ID: 07020188.wav
    Length: 34
** Motor Cycles: Honda 250, start, fast departure                                                                                :Motorcycles:Honda 250:
    ID: 07020187.wav
    Length: 19
** Motor Cycles: Honda 250, start, medium paced departure                                                                                :Motorcycles:Honda 250:
    ID: 07020186.wav
    Length: 23
** Motor Cycles: Honda 250, start, tickover, depart                                                                                :Motorcycles:Honda 250:
    ID: 07020185.wav
    Length: 31
** Motor Cycles: Honda 90, pass                                                                                :Motorcycles:Honda 90:
    ID: 07020184.wav
    Length: 34
** Motor Cycles: Honda 90, pass                                                                                :Motorcycles:Honda 90:
    ID: 07020183.wav
    Length: 45
** Motor Cycles: Honda 90, start, run, stops with turns, run, stop. Recorded on bike                                                                                :Motorcycles:Honda 90:
    ID: 07020182.wav
    Length: 240
** Motor Cycles: Honda 90, approach and stop                                                                                :Motorcycles:Honda 90:
    ID: 07020181.wav
    Length: 41
** Motor Cycles: Honda 90, approach and stop                                                                                :Motorcycles:Honda 90:
    ID: 07020180.wav
    Length: 25
** Motor Cycles: Honda 90, approach and stop                                                                                :Motorcycles:Honda 90:
    ID: 07020179.wav
    Length: 43
** Motor Cycles: Honda 90, start and depart                                                                                :Motorcycles:Honda 90:
    ID: 07020178.wav
    Length: 25
** Motor Cycles: Honda 90, start and depart                                                                                :Motorcycles:Honda 90:
    ID: 07020177.wav
    Length: 40
** Motor Cycles: Honda 90, False start, start, depart                                                                                :Motorcycles:Honda 90:
    ID: 07020176.wav
    Length: 44
** London Underground, Victoria Line train, interior, train slows down & stops at station, doors open.                                                                                ::
    ID: 07020175.wav
    Length: 57
** London Underground, Victoria Line train, interior, doors close, train starts, constant run.                                                                                ::
    ID: 07020174.wav
    Length: 207
** London Underground station, atmosphere on escalator. (Victoria Line.)                                                                                ::
    ID: 07020173.wav
    Length: 102
** London Underground, Finsbury Park Station, train arrives,announcement on P.A. system "Mind the doors", train departs, station atmosphere. (Victoria Line.)                                                                                ::
    ID: 07020172.wav
    Length: 392
** London Underground, Seven Sisters Station, train arrives, announcement on P.A. system "Mind the doors", train departs, station atmosphere. (Victoria Line.)                                                                                ::
    ID: 07020171.wav
    Length: 399
** London Underground, Brixton Station, announcement on P.A. system "Mind the doors", train departs, station atmosphere. (Victoria Line.)                                                                                ::
    ID: 07020170.wav
    Length: 392
** London Underground, Brixton Station, atmosphere while automatic ticket gates are being used. (Victoria Line.)                                                                                ::
    ID: 07020169.wav
    Length: 182
** London Underground, Brixton Station, commuters buying tickets & change given using decimal coinage. (Victoria Line.)                                                                                ::
    ID: 07020168.wav
    Length: 183
** London Underground, Seven Sisters Station, commuters buying tickets & change given using decimal coinage, with some speech. (Victoria Line.)                                                                                ::
    ID: 07020167.wav
    Length: 183
** London Underground, Seven Sisters Station, commuters buying tickets & change given using pre-decimal coinage, with some speech. (Victoria Line.)                                                                                ::
    ID: 07020166.wav
    Length: 179
** London Underground, Mornington Crescent Station, lift gates close, lift travels & gates opened. (Northern Line.)                                                                                ::
    ID: 07020165.wav
    Length: 27
** London Underground station, atmosphere ascending on escalator, with some speech.                                                                                ::
    ID: 07020164.wav
    Length: 90
** London Underground station, atmosphere at top of escalators..                                                                                 ::
    ID: 07020163.wav
    Length: 194
** London Underground station, atmosphere descending on escalator.                                                                                ::
    ID: 07020162.wav
    Length: 68
** London Underground station, atmosphere in suburban booking hall. (Above ground.)                                                                                ::
    ID: 07020161.wav
    Length: 305
** London Underground, Oxford Circus Station, atmosphere as automatic ticket machines are used, with voices and footsteps of passengers.                                                                                ::
    ID: 07020160.wav
    Length: 189
** London Underground, atmosphere in station passage. (Below ground.)                                                                                ::
    ID: 07020159.wav
    Length: 194
** London Underground, Charing Cross Station, atmosphere in station. (Below ground.)                                                                                ::
    ID: 07020158.wav
    Length: 376
** London Underground, Earls Court Station, atmosphere in station. (Recorded above ground.)                                                                                ::
    ID: 07020157.wav
    Length: 357
** London Underground, train passing. (Above ground.)                                                                                ::
    ID: 07020156.wav
    Length: 21
** London Underground, train passing. (Above ground.)                                                                                ::
    ID: 07020155.wav
    Length: 28
** London Underground, train passing. (Above ground.)                                                                                ::
    ID: 07020154.wav
    Length: 21
** London Underground, train passing. (Above ground.)                                                                                ::
    ID: 07020153.wav
    Length: 23
** London Underground, train passing. (In tunnel.)                                                                                ::
    ID: 07020152.wav
    Length: 59
** London Underground, train passing in station. (In tunnel.)                                                                                ::
    ID: 07020151.wav
    Length: 47
** London Underground, train passing in station. (In tunnel.)                                                                                ::
    ID: 07020150.wav
    Length: 61
** London Underground, train arrives & departs. (In tunnel.)                                                                                ::
    ID: 07020149.wav
    Length: 84
** London Underground, train arrives & departs. (In tunnel.)                                                                                ::
    ID: 07020148.wav
    Length: 93
** London Underground, train arrives & departs. (Above ground.)                                                                                ::
    ID: 07020147.wav
    Length: 53
** London Underground, train starts, run with several stops. (Above ground.)                                                                                ::
    ID: 07020146.wav
    Length: 296
** London Underground, train running above ground, start, fast run through stations, stop.                                                                                ::
    ID: 07020145.wav
    Length: 376
** London Underground, Central Line train running with intermediate stops in tunnel.                                                                                ::
    ID: 07020144.wav
    Length: 363
** Samoyed dogs playing, exterior, with atmosphere.                                                                                ::
    ID: 07020143.wav
    Length: 199
** Samoyed puppies howling, interior.                                                                                ::
    ID: 07020142.wav
    Length: 30
** Samoyed puppies playing in box, interior.                                                                                ::
    ID: 07020141.wav
    Length: 124
** Samoyed puppies playing & yelping, interior.                                                                                ::
    ID: 07020140.wav
    Length: 139
** Samoyed puppy sneezing, interior.                                                                                ::
    ID: 07020139.wav
    Length: 9
** Samoyed puppies feeding, interior.                                                                                ::
    ID: 07020138.wav
    Length: 66
** Samoyed puppies playing, interior. (28 day old puppies.)                                                                                ::
    ID: 07020137.wav
    Length: 86
** Bulldogs barking in kennels, interior.                                                                                ::
    ID: 07020136.wav
    Length: 108
** Cross-bred watchdog barking in a yard.                                                                                ::
    ID: 07020135.wav
    Length: 62
** Australian Terrier barking, exterior.                                                                                ::
    ID: 07020134.wav
    Length: 100
** Mongrel barking, exterior.                                                                                ::
    ID: 07020133.wav
    Length: 49
** Alsatian barking & running about, exterior. (3 year old Alsation.)                                                                                ::
    ID: 07020132.wav
    Length: 184
** Dog gnawing a bone, interior.                                                                                ::
    ID: 07020131.wav
    Length: 76
** Alsatian barking, interior.                                                                                ::
    ID: 07020130.wav
    Length: 81
** Pack of Malamute Alaskan Huskies, general noise, exterior. (Pack of 18 dogs.)                                                                                ::
    ID: 07020129.wav
    Length: 200
** Pack of Malamute Alaskan Huskies howling, exterior. (Pack of 18 dogs.)                                                                                ::
    ID: 07020128.wav
    Length: 200
** Malamute Alaskan Huskies screaming, into yelps, exterior.                                                                                ::
    ID: 07020127.wav
    Length: 73
** Malamute Alaskan Huskies  screaming, exterior.                                                                                ::
    ID: 07020126.wav
    Length: 69
** Malamute Alaskan Huskies barking, exterior.                                                                                ::
    ID: 07020125.wav
    Length: 79
** Malamute Alaskan Husky growling & snarling, exterior. (In foreground.)                                                                                ::
    ID: 07020124.wav
    Length: 80
** Alsatians whining & yelping, including 9-month old, exterior.                                                                                ::
    ID: 07020123.wav
    Length: 139
** Two Alsatians barking, exterior. (Distant and near)                                                                                ::
    ID: 07020122.wav
    Length: 33
** Two Alsatians barking, exterior.                                                                                ::
    ID: 07020121.wav
    Length: 43
** Alsatian barking & pushing door, interior.                                                                                ::
    ID: 07020120.wav
    Length: 54
** Alsatian barking, interior.                                                                                ::
    ID: 07020119.wav
    Length: 54
** Guard dogs barking, exterior.                                                                                ::
    ID: 07020118.wav
    Length: 75
** Deerhound growling & barking, interior.                                                                                ::
    ID: 07020117.wav
    Length: 39
** Deerhound barking, exterior.                                                                                ::
    ID: 07020116.wav
    Length: 70
** Dog growling, interior.                                                                                ::
    ID: 07020115.wav
    Length: 53
** Dog growling, interior.                                                                                ::
    ID: 07020114.wav
    Length: 92
** 5-month old puppy whining. (Species unknown.)                                                                                ::
    ID: 07020113.wav
    Length: 171
** Bull Terrier snoring, interior.                                                                                ::
    ID: 07020112.wav
    Length: 88
** Bull Terrier barking, interior.                                                                                ::
    ID: 07020111.wav
    Length: 46
** Two Terriers fighting, exterior.                                                                                ::
    ID: 07020110.wav
    Length: 34
** Terrier barking & growling, exterior.                                                                                ::
    ID: 07020109.wav
    Length: 126
** Three Alsatian guard dogs barking, exterior.                                                                                ::
    ID: 07020108.wav
    Length: 135
** Alsatian barking, interior, with other dogs joining in.                                                                                ::
    ID: 07020107.wav
    Length: 69
** Alsatian barking, interior.                                                                                ::
    ID: 07020106.wav
    Length: 23
** Two King Charles Spaniels barking & growling, exterior.                                                                                ::
    ID: 07020105.wav
    Length: 193
** Two King Charles Spaniels barking & growling, exterior.                                                                                ::
    ID: 07020104.wav
    Length: 71
** Two King Charles Spaniels barking & growling, exterior.                                                                                ::
    ID: 07020103.wav
    Length: 94
** Two King Charles Spaniels barking, exterior.                                                                                ::
    ID: 07020102.wav
    Length: 134
** King Charles Spaniel barking & snuffling, exterior.                                                                                ::
    ID: 07020101.wav
    Length: 86
** King Charles Spaniel growling & barking, exterior.                                                                                ::
    ID: 07020100.wav
    Length: 66
** Two King Charles Spaniels barking & whining in distance.                                                                                ::
    ID: 07020099.wav
    Length: 43
** Puppies in pet shop, atmosphere in shop. (Species unknown.)                                                                                ::
    ID: 07020098.wav
    Length: 65
** Dog growling, interior. (Species unknown.)                                                                                ::
    ID: 07020097.wav
    Length: 44
** Dog scratching at door, interior. (Species unknown.)                                                                                ::
    ID: 07020096.wav
    Length: 29
** Interior, one drinking.                                                                                ::
    ID: 07020095.wav
    Length: 46
** Sealyham Terrier growling with bone, interior.                                                                                ::
    ID: 07020094.wav
    Length: 102
** Sealyham Terrier snuffling, yelping & growling, interior.                                                                                ::
    ID: 07020093.wav
    Length: 65
** Sealyham Terrier yelping, interior.                                                                                ::
    ID: 07020092.wav
    Length: 101
** Sealyham Terrier yelping & barking, interior.                                                                                ::
    ID: 07020091.wav
    Length: 36
** Sealyham Terrier barking behind door, interior.                                                                                ::
    ID: 07020090.wav
    Length: 109
** Sealyham Terrier barking, exterior.                                                                                ::
    ID: 07020089.wav
    Length: 41
** Sealyham Terrier barking, exterior.                                                                                ::
    ID: 07020088.wav
    Length: 39
** Puppy on leash, exterior. (Species unknown.)                                                                                ::
    ID: 07020087.wav
    Length: 112
** Corgi barking, exterior, with other dogs in distance.                                                                                ::
    ID: 07020086.wav
    Length: 94
** Dachshund barking, interior.                                                                                ::
    ID: 07020085.wav
    Length: 102
** Dachshund barking, exterior.                                                                                ::
    ID: 07020084.wav
    Length: 73
** Mongrel terrier snarling, exterior.                                                                                ::
    ID: 07020083.wav
    Length: 45
** Dog snoring, interior. (Species unknown.)                                                                                ::
    ID: 07020082.wav
    Length: 48
** Pekinese snapping & growling, interior.                                                                                ::
    ID: 07020081.wav
    Length: 125
** Yorkshire Toy Terrier barking, interior.                                                                                ::
    ID: 07020080.wav
    Length: 69
** Yorkshire Toy Terrier yapping & whining, interior.                                                                                ::
    ID: 07020079.wav
    Length: 106
** Gordon Setter whining, interior.                                                                                ::
    ID: 07020078.wav
    Length: 163
** Gordon Setter growling & whining, interior.                                                                                ::
    ID: 07020077.wav
    Length: 102
** Gordon Setter moaning, interior.                                                                                ::
    ID: 07020076.wav
    Length: 49
** Two dogs barking in farmyard. (Species unknown.)                                                                                ::
    ID: 07020075.wav
    Length: 30
** Dog barking & growling, exterior. (Species unknown.)                                                                                ::
    ID: 07020074.wav
    Length: 31
** Two dogs barking, exterior. (Species unknown.)                                                                                ::
    ID: 07020073.wav
    Length: 125
** Sheep Dog barking, exterior.                                                                                ::
    ID: 07020072.wav
    Length: 43
** Bull Mastiff barking, exterior.                                                                                ::
    ID: 07020071.wav
    Length: 35
** Irish Wolfhound barking, exterior.                                                                                ::
    ID: 07020070.wav
    Length: 78
** Dobermann Pinscher barking, exterior.                                                                                ::
    ID: 07020069.wav
    Length: 61
** Bassett Hound playing with & chewing bone, interior.                                                                                ::
    ID: 07020068.wav
    Length: 59
** Bassett Hound growling, interior.                                                                                ::
    ID: 07020067.wav
    Length: 157
** Border Collie growling, interior.                                                                                ::
    ID: 07020066.wav
    Length: 132
** Labrador growling, exterior.                                                                                ::
    ID: 07020065.wav
    Length: 65
** Labrador panting, exterior.                                                                                ::
    ID: 07020064.wav
    Length: 49
** Labrador Puppies barking, interior. (Group of Labrador puppies.)                                                                                ::
    ID: 07020063.wav
    Length: 97
** Labrador barking, interior.                                                                                ::
    ID: 07020062.wav
    Length: 122
** Labrador barking, exterior.                                                                                ::
    ID: 07020061.wav
    Length: 137
** Cinema, chatter of children in auditorium.                                                                                ::
    ID: 07020060.wav
    Length: 216
** Cinema, footsteps & chatter while children leave film show, with sounds of occasional doors.                                                                                ::
    ID: 07020059.wav
    Length: 146
** Theatre Foyer, children in animated conversation in foyer of theatre playing a pantomime.                                                                                ::
    ID: 07020058.wav
    Length: 419
** Junior School, interior, atmosphere with 8-9 year-olds during team game with medicine ball.                                                                                ::
    ID: 07020057.wav
    Length: 126
** Junior School, interior, atmosphere with 8-9 year-olds using apparatus during free exercise.                                                                                ::
    ID: 07020056.wav
    Length: 120
** Junior school, interior, atmosphere as 8-9 year olds assemble apparatus for free exercise.                                                                                ::
    ID: 07020055.wav
    Length: 114
** Infant School, interior, atmosphere as creative activity class continues until end of period, with group of five-&-a-half year olds.                                                                                ::
    ID: 07020054.wav
    Length: 202
** Infant School, interior, atmosphere as creative activity begins with group of five-&-a-half year olds.                                                                                ::
    ID: 07020053.wav
    Length: 200
** Infant School Dining Hall, atmosphere with 6-7 year-olds clearing up after meal.                                                                                ::
    ID: 07020052.wav
    Length: 97
** Infant School Dining Hall, atmosphere with 6-7 year-olds saying grace & commencing meal.                                                                                ::
    ID: 07020051.wav
    Length: 153
** Infant School Dining Hall, atmosphere with 6-7 year-olds before commencing meal.                                                                                ::
    ID: 07020050.wav
    Length: 125
** Infant School Dining Hall, atmosphere with 5 year-olds saying grace & commencing meal.                                                                                ::
    ID: 07020049.wav
    Length: 244
** Infant School Dining Hall, atmosphere with 5 year-olds before commencing meal.                                                                                ::
    ID: 07020048.wav
    Length: 155
** Junior School Playground, bell rings & children leave playground. (8-9 year-old children.)                                                                                ::
    ID: 07020047.wav
    Length: 75
** Junior School Playground, 8-9 year-olds in playground.                                                                                ::
    ID: 07020046.wav
    Length: 314
** Infant School Playground, bell sounds & children leave playground. (Five-&-a-half year-old children.)                                                                                ::
    ID: 07020045.wav
    Length: 74
** Infant School Playground, five-&-a-half year-old children playing in playground.                                                                                ::
    ID: 07020044.wav
    Length: 301
** Nursery School, interior, 3-5 year-olds playing & awaiting collection by mothers. (Mixed nursery school.)                                                                                ::
    ID: 07020043.wav
    Length: 200
** Nursery School, interior, forty 3-5 year-olds playing in hall before roll call. (Mixed nursery school.)                                                                                ::
    ID: 07020042.wav
    Length: 201
** Nursery School, interior, 2-3 year-olds riding around on tricycles. (Mixed nursery school.)                                                                                ::
    ID: 07020041.wav
    Length: 109
** Nursery School, interior, 2-3 year-olds playing with squeakers. (Mixed nursery school.)                                                                                ::
    ID: 07020040.wav
    Length: 72
** Nursery School, interior, 2-3 year-olds trying to play singing games. (Mixed nursery school.)                                                                                ::
    ID: 07020039.wav
    Length: 196
** Nursery School, interior, 2-3 year-olds playing with squeaky wheeled toys, with teacher in background. (Mixed nursery school.)                                                                                ::
    ID: 07020038.wav
    Length: 199
** Nursery School, interior, 3-5 year-olds playing with construction sets. (Mixed nursery school.)                                                                                ::
    ID: 07020037.wav
    Length: 195
** Nursery School, interior, forty 3-5 year-olds in a mixed nursery. (Noisy background.) (Mixed nursery school.)                                                                                ::
    ID: 07020036.wav
    Length: 409
** School Classroom, six 5-year old children playing in room.                                                                                ::
    ID: 07020035.wav
    Length: 375
** Playground in London, thirty 5-11 year-olds playing with some passing traffic.                                                                                ::
    ID: 07020034.wav
    Length: 371
** Barnds Hatch, atmosphere with Formula Two cars leaving straight, entering corner, entering & leaving pits.                                                                                ::
    ID: 07020033.wav
    Length: 393
** Brands Hatch, Formula Two cars racing down the straight.                                                                                ::
    ID: 07020032.wav
    Length: 202
** Brands Hatch, Formula Two cars moving from pits to track.                                                                                ::
    ID: 07020031.wav
    Length: 199
** Silverstone, general practice atmosphere with Formula One cars. (Formula One International Trophy Race 1969.)                                                                                ::
    ID: 07020030.wav
    Length: 192
** Silverstone, saloon car racing including Mini Cooper, Chevrolet, Ford Escort, Ford Mustang & Hillman Imp.                                                                                ::
    ID: 07020029.wav
    Length: 182
** Silverstone, saloon cars on practice laps & warning horn. (Saloon Car Racing, 1969.)                                                                                ::
    ID: 07020028.wav
    Length: 128
** Silverstone, atmosphere recorded in pits, Formula One cars revving & departing for practice laps. (Formula One International Trophy Race 1969.)                                                                                ::
    ID: 07020027.wav
    Length: 152
** Silverstone, amosphere recorded in pits with Formula One cars revving & departing for practice laps. (Formula One International Trophy Race 1969.)                                                                                ::
    ID: 07020026.wav
    Length: 78
** Silverstone, Formula One International Trophy Race 1969, atmosphere during three laps of track with P.A. announcements. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020025.wav
    Length: 256
** Silverstone, Formula One International Trophy Race 1969, cars leaving Copse Corner & accelerating away. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020024.wav
    Length: 32
** Silverstone, Formula One International Trophy Race 1969, cars entering & leaving Copse Corner. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020023.wav
    Length: 65
** Silverstone, Formula One International Trophy Race 1969, cars passing. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020022.wav
    Length: 34
** Silverstone, Formula One International Trophy Race 1969, cars passing. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020021.wav
    Length: 27
** Silverstone, Formula One International Trophy Race 1969, start of race, with chatter, P.A. announcements & crowd atmosphere. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020020.wav
    Length: 91
** Silverstone, Formula One International Trophy Race 1969, atmosphere before race. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020019.wav
    Length: 98
** Silverstone, Formula One International Trophy Race 1969, McClaren Ford, start up & move away to starting position. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020018.wav
    Length: 28
** Silverstone, Formula One International Trophy Race 1969, warning hooter sounds. (Formula One, 1.3 litre.)                                                                                ::
    ID: 07020017.wav
    Length: 32
** Silverstone, production cars practising, with some tyre squeals.                                                                                ::
    ID: 07020016.wav
    Length: 190
** Silverstone, Grand Prix cars practising.                                                                                ::
    ID: 07020015.wav
    Length: 198
** Silverstone, Formula One International Trophy Race 1962, cars passing stands.                                                                                ::
    ID: 07020014.wav
    Length: 103
** Silverstone, Formula One International Trophy Race 1962, cars passing Becketts Corner.                                                                                ::
    ID: 07020013.wav
    Length: 259
** Silverstone, Formula One International Trophy Race 1962, cars passing Copse Corner.                                                                                ::
    ID: 07020012.wav
    Length: 265
** Silverstone, Formula One International Trophy Race 1962, start of race, warning hooter at 20".                                                                                ::
    ID: 07020011.wav
    Length: 104
** Silverstone, atmosphere as cars warm up before race.                                                                                ::
    ID: 07020010.wav
    Length: 393
** Stock Car Racing, general atmosphere at races with occasional P.A. announcements.                                                                                ::
    ID: 07020009.wav
    Length: 383
** Stock Car Racing, general atmosphere at races without P.A. announcements.                                                                                ::
    ID: 07020008.wav
    Length: 342
** Le Mans, end of race with applause & cheers from spectators.                                                                                ::
    ID: 07020007.wav
    Length: 251
** Le Mans, cars leaving Mulsanne Corner.                                                                                ::
    ID: 07020006.wav
    Length: 112
** Le Mans, cars entering Mulsanne Corner.                                                                                ::
    ID: 07020005.wav
    Length: 126
** Le Mans, activity in pits with cars passing.                                                                                ::
    ID: 07020004.wav
    Length: 243
** Le Mans, cars passing during race with occasional P.A. announcements. (Recorded from grandstand.)                                                                                ::
    ID: 07020003.wav
    Length: 308
** Le Mans, start of race.                                                                                ::
    ID: 07020002.wav
    Length: 62
** Le Mans, atmosphere as cars warm up before race.                                                                                ::
    ID: 07020001.wav
    Length: 373
** Bristol Britannia, exterior, taxi-ing in, engines switched off. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019189.wav
    Length: 189
** Bristol Britannia, exterior, landing. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019188.wav
    Length: 19
** Bristol Britannia, exterior, passing overhead. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019187.wav
    Length: 39
** Bristol Britannia, exterior, take off. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019186.wav
    Length: 36
** Bristol Britannia, exterior, taxi-ing to take off. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019185.wav
    Length: 154
** Bristol Britannia, exterior, start up. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019184.wav
    Length: 151
** Bristol Britannia, exterior, passing low overhead. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019183.wav
    Length: 25
** Bristol Britannia, exterior, take off. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019182.wav
    Length: 42
** Bristol Britannia, exterior, taxi away. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019181.wav
    Length: 93
** Bristol Britannia, exterior, engines running, in foreground. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019180.wav
    Length: 153
** Bristol Britannia, interior, taxi to stop & switch off. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019179.wav
    Length: 80
** Bristol Britannia, interior, touch down & taxi. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019178.wav
    Length: 128
** Bristol Britannia, interior, descent. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019177.wav
    Length: 147
** Bristol Britannia, interior, constant flight. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019176.wav
    Length: 421
** Bristol Britannia, interior, take off into constant flight. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019175.wav
    Length: 78
** Bristol Britannia, interior, start & run up engines, taxi. (Long/medium range airliner, four turboprop jet engines.)                                                                                ::
    ID: 07019174.wav
    Length: 302
** Period Gunfire, fairly concentrated in foreground. (Suggested use period battles.)                                                                                ::
    ID: 07019173.wav
    Length: 341
** Baker Rifle, single shot fired. (In use c. 1800-40.)                                                                                ::
    ID: 07019172.wav
    Length: 9
** Brown Bess Flintlock, single shot fired, hits metal target. (Manufactured 1757.)                                                                                ::
    ID: 07019171.wav
    Length: 6
** Brown Bess Flintlock, single shot fired. (Manufactured 1757.)                                                                                ::
    ID: 07019170.wav
    Length: 8
** Wheel-Lock Gun, single shot fired. (Manufactured 1590.)                                                                                ::
    ID: 07019169.wav
    Length: 6
** Elizabethan Matchlock Gun, single shot fired.                                                                                ::
    ID: 07019168.wav
    Length: 7
** Three-Pounder Bronze Cannon, fired six times. (Manufactured 1790.)                                                                                ::
    ID: 07019167.wav
    Length: 46
** Double Barrel Muzzle-Loading Percussion Shotgun, three double shots fired.                                                                                ::
    ID: 07019166.wav
    Length: 31
** Double Barrel Muzzle-Loading Percussion Shotgun, three double shots fired.                                                                                ::
    ID: 07019165.wav
    Length: 24
** Flintlock Duelling Pistol, five shots fired, fifth hits metal target. (Manufactured 1790.)                                                                                ::
    ID: 07019164.wav
    Length: 44
** Eighteenth Century Naval Cannon, constant bombardment                                                                                ::
    ID: 07019163.wav
    Length: 271
** Eighteenth Century Naval Cannon, fires quadruple shot.                                                                                ::
    ID: 07019162.wav
    Length: 9
** Eighteenth Century Naval Cannon, fires triple shot.                                                                                ::
    ID: 07019161.wav
    Length: 8
** Eighteenth Century Naval Cannon, fires double shot.                                                                                ::
    ID: 07019160.wav
    Length: 7
** Eighteenth Century Naval Cannon, fires single shot.                                                                                ::
    ID: 07019159.wav
    Length: 6
** Eighteenth Century Naval Battle, general battle atmosphere.                                                                                ::
    ID: 07019158.wav
    Length: 395
** Battle Crowd, men shouting angrily. (Suggested use, period battle)                                                                                ::
    ID: 07019157.wav
    Length: 426
** Battle Crowd, mixed angry crowd shouting rises to crescendo and dies down. (Suitable background to a period battle)                                                                                ::
    ID: 07019156.wav
    Length: 32
** Battle Crowd, mixed angry crowd, shouting rises to crescendo and dies down. (Suitable background to a period battle)                                                                                ::
    ID: 07019155.wav
    Length: 19
** Battle Crowd, murmuring crowd of men with occasional clink of swords. (Suggested use, period battle)                                                                                ::
    ID: 07019154.wav
    Length: 299
** Eleventh Century Battle, twelve men fighting with swords and axes.                                                                                 ::
    ID: 07019153.wav
    Length: 118
** Eleventh Century Battle, general battle atmosphere.                                                                                 ::
    ID: 07019152.wav
    Length: 272
** Eleventh Century Battle, large army fighting with swords & axes.                                                                                 ::
    ID: 07019151.wav
    Length: 50
** Battle Crowd, with men taunting & jeering.                                                                                ::
    ID: 07019150.wav
    Length: 405
** Battle Ccrowd, with men shouting. (No gunfire.)                                                                                ::
    ID: 07019149.wav
    Length: 432
** Period Battle, shouting men, horses galloping & whinnying, etc                                                                                ::
    ID: 07019148.wav
    Length: 411
** Period Battle, shouting men, musket shots, horses, etc.                                                                                ::
    ID: 07019147.wav
    Length: 398
** Ski-ing, nursery slope atmosphere with childrens voices & slight hum of ski drag lift.                                                                                ::
    ID: 07019146.wav
    Length: 125
** Ski-ing, atmosphere in ski cafe where French is being spoken.                                                                                ::
    ID: 07019145.wav
    Length: 161
** Ski-ing, atmosphere in ski cafe where English is being spoken.                                                                                ::
    ID: 07019144.wav
    Length: 89
** Curling, atmosphere on curling rink with speech in English & French.                                                                                ::
    ID: 07019143.wav
    Length: 265
** Curling, stone approaches with sweeping & strike.                                                                                ::
    ID: 07019142.wav
    Length: 17
** Curling, stone approaches with caller & sweeping.                                                                                ::
    ID: 07019141.wav
    Length: 22
** Curling, stone approaches, strikes another twice & hits edge.                                                                                ::
    ID: 07019140.wav
    Length: 18
** Curling, stone approaches & strikes another.                                                                                ::
    ID: 07019139.wav
    Length: 22
** Curling, stone passing.                                                                                ::
    ID: 07019138.wav
    Length: 14
** Ski-ing, skiers passing.                                                                                ::
    ID: 07019137.wav
    Length: 25
** Ski-ing, skiers passing on slalom course with spectators on side.                                                                                ::
    ID: 07019136.wav
    Length: 111
** Ski-ing, atmosphere in ski lift shed.                                                                                ::
    ID: 07019135.wav
    Length: 73
** Ski-ing, atmosphere at queue for drag lift.                                                                                ::
    ID: 07019134.wav
    Length: 117
** Ski-ing, atmosphere at departure point of ski drag lift.                                                                                ::
    ID: 07019133.wav
    Length: 51
** Ski-ing, atmosphere with ski instructor & small class, speaking in English.                                                                                ::
    ID: 07019132.wav
    Length: 135
** Ski-ing, atmosphere at ski drag lift release point, with French voices at beginning.                                                                                ::
    ID: 07019131.wav
    Length: 131
** Ski-ing, atmosphere at roadway above ski drag lift.                                                                                ::
    ID: 07019130.wav
    Length: 107
** Indoor Ice Rink, interior, atmosphere at rink side with children.                                                                                ::
    ID: 07019129.wav
    Length: 186
** Indoor Ice Rink, interior, atmosphere in ice rink with children. (Recorded from balcony.)                                                                                ::
    ID: 07019128.wav
    Length: 186
** Indoor Ice Rink, interior, atmosphere at side of ice rink with adults.                                                                                ::
    ID: 07019127.wav
    Length: 7
** Indoor Ice Rink, interior, single skater. (Close perspective recording.)                                                                                ::
    ID: 07019126.wav
    Length: 129
** Factory Fire, electrical components work, atmosphere & activity at scene.                                                                                ::
    ID: 07019125.wav
    Length: 394
** Fire hoses playing, general atmosphere & activity.                                                                                ::
    ID: 07019124.wav
    Length: 399
** Plymouth Fire 1941, atmosphere at scene of fire caused by German bombing raid, with flames crackling, masonry falling & activity of fire services.                                                                                ::
    ID: 07019123.wav
    Length: 422
** Fire, heavy flames crackling.                                                                                ::
    ID: 07019122.wav
    Length: 424
** Bonfire atmosphere, with children & adults chatting nearby.                                                                                ::
    ID: 07019121.wav
    Length: 214
** Bonfire atmosphere, with small children chatting & laughing nearby.                                                                                ::
    ID: 07019120.wav
    Length: 156
** General firework display. (Fireworks.)                                                                                ::
    ID: 07019119.wav
    Length: 283
** Firework set piece. (Fireworks.)                                                                                ::
    ID: 07019118.wav
    Length: 79
** Noisy firework display. (Fireworks.)                                                                                ::
    ID: 07019117.wav
    Length: 148
** Firework set piece. (Fireworks.)                                                                                ::
    ID: 07019116.wav
    Length: 33
** Rockets, with crowd reaction. (Fireworks.)                                                                                ::
    ID: 07019115.wav
    Length: 29
** Rockets. (Ends with explosion)                                                                                ::
    ID: 07019114.wav
    Length: 16
** Four cannons. (Fireworks.)                                                                                ::
    ID: 07019113.wav
    Length: 13
** Cannon. (Fireworks.)                                                                                ::
    ID: 07019112.wav
    Length: 7
** Firework set piece. (Fireworks.)                                                                                ::
    ID: 07019111.wav
    Length: 67
** Catherine wheels and squibs. (Fireworks.)                                                                                ::
    ID: 07019110.wav
    Length: 61
** Catherine wheel. (Fireworks.)                                                                                ::
    ID: 07019109.wav
    Length: 45
** Squibs. (Fireworks.)                                                                                ::
    ID: 07019108.wav
    Length: 17
** Explosion and cascade. (Fireworks.)                                                                                ::
    ID: 07019107.wav
    Length: 16
** Rocket exploding. (Fireworks.)                                                                                ::
    ID: 07019106.wav
    Length: 7
** Blacksmith, shoeing a horse. (Close perspective, no speech.)                                                                                ::
    ID: 07019105.wav
    Length: 359
** Blacksmith, trimming, sharpening & tempering picks. (Close perspective, no speech.)                                                                                ::
    ID: 07019104.wav
    Length: 187
** Blacksmith, making horseshoe. (Close perspective, no speech.)                                                                                ::
    ID: 07019103.wav
    Length: 185
** Atmosphere in a busy bank with occasional speech & footsteps, cashiers busy stamping documents.                                                                                ::
    ID: 07019102.wav
    Length: 371
** Atmosphere in a quiet bank with occasional speech, footsteps & cashiers stamping documents.                                                                                ::
    ID: 07019101.wav
    Length: 376
** Farnborough Air Show 1961, crowd atmosphere in a large marquee.                                                                                ::
    ID: 07019100.wav
    Length: 184
** Earls Court Motor Show 1955, general crowd atmosphere.                                                                                ::
    ID: 07019099.wav
    Length: 184
** Earls Court Boat Show 1966, atmosphere as people enter hall through turnstiles.                                                                                ::
    ID: 07019098.wav
    Length: 184
** Earls Court Boat Show 1966, atmosphere in entrance hall.                                                                                ::
    ID: 07019097.wav
    Length: 183
** Crufts Dog Show, atmosphere at dog show with large dogs barking.                                                                                ::
    ID: 07019096.wav
    Length: 369
** Crufts Dog Show, atmosphere at dog show with small dogs barking.                                                                                ::
    ID: 07019095.wav
    Length: 374
** Toilet, old-fashioned toliet, pause, 1960s toilet.                                                                                ::
    ID: 07019094.wav
    Length: 18
** Bath, using back brush.                                                                                ::
    ID: 07019093.wav
    Length: 115
** Shower, person under shower.                                                                                ::
    ID: 07019092.wav
    Length: 51
** Shower running.                                                                                ::
    ID: 07019091.wav
    Length: 56
** Shower, shower bath curtains.                                                                                ::
    ID: 07019090.wav
    Length: 58
** Bathroom, washing body, swilling down basin, water runs away.                                                                                ::
    ID: 07019089.wav
    Length: 265
** Hand basin, water running out of hand basin.                                                                                ::
    ID: 07019088.wav
    Length: 37
** Hand basin, rinsing hands in bathroom.                                                                                ::
    ID: 07019087.wav
    Length: 32
** Hand basin, scrubbing nails in a bathroom.                                                                                ::
    ID: 07019086.wav
    Length: 101
** Hand basin, washing hands in bathroom.                                                                                ::
    ID: 07019085.wav
    Length: 114
** Hand basin, filling hand basin in bathroom.                                                                                ::
    ID: 07019084.wav
    Length: 29
** Gas water heater turned on.                                                                                ::
    ID: 07019083.wav
    Length: 5
** Toilet, 1960s toilet flushing.                                                                                ::
    ID: 07019082.wav
    Length: 11
** Bath, water running into bath. (Mid-perspective recording.)                                                                                ::
    ID: 07019081.wav
    Length: 32
** Bath, washing bath out.                                                                                ::
    ID: 07019080.wav
    Length: 29
** Bath, splashing in bath.                                                                                ::
    ID: 07019079.wav
    Length: 33
** Bath, plug removed & water running out of bath.                                                                                ::
    ID: 07019078.wav
    Length: 24
** Bath, water running into bath.                                                                                ::
    ID: 07019077.wav
    Length: 38
** Canteen Kitchen, atmosphere in kitchen with some indistinct speech.                                                                                ::
    ID: 07019076.wav
    Length: 378
** Council Home Kitchen, atmosphere in kitchen with some indistinct speech, generally quieter than restaurant kitchen.                                                                                ::
    ID: 07019075.wav
    Length: 375
** Chinese Restaurant Kitchen, atmosphere of kitchen in busy restaurant with sounds of utensils & some indistinct speech.                                                                                ::
    ID: 07019074.wav
    Length: 360
** French Restaurant Kitchen, atmosphere of kitchen in busy restaurant with sounds of utensils & some indistinct speech.                                                                                ::
    ID: 07019073.wav
    Length: 358
** Nine month old baby girl at mealtime.                                                                                ::
    ID: 07019072.wav
    Length: 200
** Nine month old baby girl crying.                                                                                ::
    ID: 07019071.wav
    Length: 161
** Nine month old baby girl, laughing & playing, with mouth noises at end.                                                                                ::
    ID: 07019070.wav
    Length: 199
** Nine month old baby girl, restless in cot, early morning.                                                                                ::
    ID: 07019069.wav
    Length: 12
** Ten week old baby boy, waking up sounds with distant birdsong. (Weight 6.0 kg.)                                                                                ::
    ID: 07019068.wav
    Length: 109
** Ten week old baby boy, waking up sounds with distant birdsong. (Weight 6.0 kg.)                                                                                ::
    ID: 07019067.wav
    Length: 135
** Ten week old baby boy, waking up sounds with distant birdsong. (Weight 6.0 kg.)                                                                                ::
    ID: 07019066.wav
    Length: 31
** Ten week old baby boy, waking up sounds. (Weight 6.0 kg.)                                                                                ::
    ID: 07019065.wav
    Length: 82
** Ten week old baby boy, waking up sounds. (Weight 6.0 kg.)                                                                                ::
    ID: 07019064.wav
    Length: 49
** Ten week old baby boy, waking up sounds. (Weight 6.0 kg.)                                                                                ::
    ID: 07019063.wav
    Length: 130
** Ten week old baby boy, waking up sounds. (Weight 6.0 kg.)                                                                                ::
    ID: 07019062.wav
    Length: 25
** Five week old baby boy crying, tired and hungry. (Weight 5.0 kg.)                                                                                ::
    ID: 07019061.wav
    Length: 389
** Six week old baby boy crying.( Weight 5.3 kg.)                                                                                ::
    ID: 07019060.wav
    Length: 93
** Two week old baby boy crying, with some hiccoughs & snuffles. (Weight 4.1 kg.)                                                                                ::
    ID: 07019059.wav
    Length: 121
** Two hour old baby boy crying, first signs of hunger. (Weight 4.0kg.)                                                                                ::
    ID: 07019058.wav
    Length: 61
** Newly born baby boy crying, delivery room atmosphere. (Weight 4.0 kg.)                                                                                ::
    ID: 07019057.wav
    Length: 106
** Four rats eating. (Technical note: for use at low level.)                                                                                :Animals:Rats:
    ID: 07019056.wav
    Length: 92
** Rat squeaking. (Technical note: for use at low level.)                                                                                :Animals:Rats:
    ID: 07019055.wav
    Length: 115
** Agitated rat squeaking. (Technical note: for use at low level.)                                                                                :Animals:Rat:
    ID: 07019054.wav
    Length: 31
** Four rats in cardboard box, jumping. (Technical note: for use at low level.)                                                                                :Animals:Rats:
    ID: 07019053.wav
    Length: 30
** Fifty mice in box, eating, squeaking & general activity. (Technical note: for use at low level.)                                                                                :Animals:Mice:
    ID: 07019052.wav
    Length: 327
** Mouse snuffling & squeaking. (Technical note: for use at low level.)                                                                                :Animals:Mice:
    ID: 07019051.wav
    Length: 72
** Newcastle Tram, interior, tram running with stops & starts. (Recorded on bottom deck.) (Tram built 1903.)                                                                                ::
    ID: 07019050.wav
    Length: 209
** Newcastle Tram, interior, start, run, stop. (Recorded on bottom deck.) (Tram built 1903.)                                                                                ::
    ID: 07019049.wav
    Length: 110
** Newcastle Tram, interior, leaving depot. (Recorded on bottom deck.) (Tram built 1903.)                                                                                ::
    ID: 07019048.wav
    Length: 59
** Newcastle Tram, exterior, run with trolley noise on wire. (Recorded on top deck.) (Tram built 1903.)                                                                                ::
    ID: 07019047.wav
    Length: 94
** Newcastle Tram, exterior, run with trolley noise on wire. (Recorded on top deck.) (Tram built 1903.)                                                                                ::
    ID: 07019046.wav
    Length: 154
** Newcastle Tram, exterior, departing. (Tram built 1903.)                                                                                ::
    ID: 07019045.wav
    Length: 41
** Newcastle Tram, exterior, approaching & stop. (Tram built 1903.)                                                                                ::
    ID: 07019044.wav
    Length: 37
** Sheffield Tram No. 189, run in crowded lower saloon.                                                                                ::
    ID: 07019043.wav
    Length: 128
** Sheffield Tram No. 189, passengers alight at terminus, with compressor.                                                                                ::
    ID: 07019042.wav
    Length: 79
** Sheffield Tram No. 189, interior, run in crowded upper saloon.                                                                                ::
    ID: 07019041.wav
    Length: 169
** Sheffield Tram No. 189, depart, with compressor shut down at start.                                                                                ::
    ID: 07019040.wav
    Length: 15
** Sheffield Tram No. 189, depart with compressor at start.                                                                                ::
    ID: 07019039.wav
    Length: 37
** Sheffield Tram No. 189, depart.                                                                                ::
    ID: 07019038.wav
    Length: 35
** Sheffield Tram No. 189, approach & stop.                                                                                ::
    ID: 07019037.wav
    Length: 27
** Sheffield Tram No. 189, approach & stop.                                                                                ::
    ID: 07019036.wav
    Length: 37
** Sheffield Tram No. 189, approach & stop.                                                                                ::
    ID: 07019035.wav
    Length: 28
** AEC Regent Bus, interior, start, drive in town with stops & starts, switch off. (Model c. 1950s.)                                                                                ::
    ID: 07019034.wav
    Length: 394
** AEC Regent Bus, exterior, doors open & close. (Model c. 1950s.)                                                                                ::
    ID: 07019033.wav
    Length: 8
** AEC Regent Bus, exterior, approach, stop & depart in traffic. (Model c. 1950s.)                                                                                ::
    ID: 07019032.wav
    Length: 33
** AEC Regent Bus, exterior, start & depart. (Model c. 1950s.)                                                                                ::
    ID: 07019031.wav
    Length: 31
** AEC Regent Bus, exterior, start & depart. (Model c. 1950s.)                                                                                ::
    ID: 07019030.wav
    Length: 28
** AEC Regent Bus, exterior, approach & stop. (Model c. 1950s.)                                                                                ::
    ID: 07019029.wav
    Length: 19
** AEC Regent Bus, exterior, approach & stop. (Model c. 1950s.)                                                                                ::
    ID: 07019028.wav
    Length: 19
** Dennis Open-Top Bus, run with occasional gear changes, stops & starts. (Recorded on bottom deck.) (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019027.wav
    Length: 381
** Dennis Open-Top Bus, run with occasional gear changes, stops & starts. (Recorded on top deck.) (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019026.wav
    Length: 366
** Dennis Open-Top Bus, run with occasional gear changes, stops & starts. (Recorded from driver's position.) (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019025.wav
    Length: 410
** Dennis Open-Top Bus, exterior, ticking over. (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019024.wav
    Length: 33
** Dennis Open-Top Bus, start in garage. (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019023.wav
    Length: 21
** Dennis Open-Top Bus, exterior, passes. (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019022.wav
    Length: 26
** Dennis Open-Top Bus, exterior, manoeuvring. (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019021.wav
    Length: 48
** Dennis Open-Top Bus, exterior, depart. (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019020.wav
    Length: 29
** Dennis Open-Top Bus, exterior, approach & stop. (Vintage open-top bus c. 1925, 4 cylinder petrol engine.)                                                                                ::
    ID: 07019019.wav
    Length: 24
** Metro Scania Bus, interior, run in town with starts & stops, bell rung occasionally. (Diesel bus.)                                                                                ::
    ID: 07019018.wav
    Length: 306
** Metro Scania Bus, approach, stop & tickover, depart. (Diesel bus.)                                                                                ::
    ID: 07019017.wav
    Length: 31
** AEC Routemaster Bus, interior, run in town with stops & starts, bell rung several times. (Diesel bus.)                                                                                ::
    ID: 07019016.wav
    Length: 270
** AEC Routemaster Bus, passes.                                                                                ::
    ID: 07019015.wav
    Length: 12
** AEC Routemaster Bus, approach, stop & tickover, depart. (Diesel bus.)                                                                                ::
    ID: 07019014.wav
    Length: 32
** AEC Routemaster Bus, approach, stop & tickover, depart. (Diesel bus.)                                                                                ::
    ID: 07019013.wav
    Length: 32
** Sixteenth Century Battle, charge. (Re-enactment, recorded at Rose Bruford School.)                                                                                ::
    ID: 07019012.wav
    Length: 111
** Sixteenth Century Army encampment. (Recreation, recorded at Rose Bruford School.)                                                                                ::
    ID: 07019011.wav
    Length: 117
** Volley of muskets. (Eighteenth Century muskets recorded at Stanmer Park, East Sussex.)                                                                                ::
    ID: 07019010.wav
    Length: 6
** Cannon fired. (Eighteenth century cannon recorded at Stanmer Park, East Sussex.)                                                                                ::
    ID: 07019009.wav
    Length: 6
** Napoleonic Battle Re-enactment, with fighting, cannon, muskets, distant bagpipes & drums. (18th Century battle re-enactment recorded in East Sussex.)                                                                                ::
    ID: 07019008.wav
    Length: 99
** Napoleonic Battle Re-enactment, armies on battlefield led by bands, with cannon & musket fire. (18th Century battle re-enactment recorded in East Sussex.)                                                                                ::
    ID: 07019007.wav
    Length: 311
** Volley of musket fire. (Seventeenth Century muskets.)                                                                                ::
    ID: 07019006.wav
    Length: 7
** Volley of cannon fire. (Seventeenth Century cannons.)                                                                                ::
    ID: 07019005.wav
    Length: 8
** Three cannons firing. (Seventeenth Century cannons.)                                                                                ::
    ID: 07019004.wav
    Length: 8
** Cannon firing. (Seventeenth Century cannon.)                                                                                ::
    ID: 07019003.wav
    Length: 6
** Seventeenth Century Battle, with intensive muskets & cannons.                                                                                ::
    ID: 07019002.wav
    Length: 113
** Seventeenth Century Battle, with cannons, muskets, shouting & hand-to-hand fighting.                                                                                ::
    ID: 07019001.wav
    Length: 385
** Soldiers digging in wet muddy ground.                                                                                ::
    ID: 07018168.wav
    Length: 199
** Soldiers digging in stony ground.                                                                                ::
    ID: 07018167.wav
    Length: 201
** Soldiers hammering in wooden stakes with a mallet.                                                                                ::
    ID: 07018166.wav
    Length: 102
** Soldiers hammering in iron stakes.                                                                                ::
    ID: 07018165.wav
    Length: 97
** Army Drill, company fall in, open order marching, soldiers drilling with rifles on the march & at the halt. (Troops wearing studded boots.)                                                                                ::
    ID: 07018164.wav
    Length: 158
** Soldiers, constant marching on soft surface. (Troops wearing studded boots.)                                                                                ::
    ID: 07018163.wav
    Length: 97
** Soldiers marching past at 160 paces per minute. (Troops wearing studded boots.)                                                                                ::
    ID: 07018162.wav
    Length: 111
** Soldiers marching past on gravel. (Ragged marching, troops wearing studded boots.)                                                                                ::
    ID: 07018161.wav
    Length: 178
** Soldiers, ragged marching on gravel. (Troops wearing studded boots.)                                                                                ::
    ID: 07018160.wav
    Length: 168
** Soldiers shambling on gravel. (Troops wearing studded boots.)                                                                                ::
    ID: 07018159.wav
    Length: 183
** Soldier walking in flooded trench.                                                                                ::
    ID: 07018158.wav
    Length: 96
** Six Army Horses crossing stream.                                                                                ::
    ID: 07018157.wav
    Length: 122
** Army Horses trotting in pairs over wooden bridge.                                                                                ::
    ID: 07018156.wav
    Length: 72
** Army Horses walking in pairs over wooden bridge.                                                                                ::
    ID: 07018155.wav
    Length: 67
** Horsedrawn Gun Carriage starts, runs & stops, turns, stops. (Recorded on board.)                                                                                ::
    ID: 07018154.wav
    Length: 215
** Horsedrawn Gun Carriage approaches & stops, panting of horse, moves off.                                                                                ::
    ID: 07018153.wav
    Length: 49
** Horsedrawn Gun Carriage passing slowly.                                                                                ::
    ID: 07018152.wav
    Length: 35
** Horsedrawn Gun Carriage passing.                                                                                ::
    ID: 07018151.wav
    Length: 40
** World War I Army Drill, troops moving through mud. (No orders.)                                                                                ::
    ID: 07018150.wav
    Length: 173
** World War I Army Drill, slow marching. (No orders.)                                                                                ::
    ID: 07018149.wav
    Length: 118
** Army Firing Squad, preparing to fire & firing, with orders shouted.                                                                                ::
    ID: 07018148.wav
    Length: 41
** World War I Army Drill, Company 'D' approach & halt, stand easy, with orders shouted.                                                                                ::
    ID: 07018147.wav
    Length: 80
** World War I Army Drill, Company 'B' dismiss & ragged march off, with orders shouted.                                                                                ::
    ID: 07018146.wav
    Length: 26
** World War I Army Drill, Company 'A' dismiss & march off, with orders shouted.                                                                                ::
    ID: 07018145.wav
    Length: 27
** World War I Army Drill, four companies march off, with orders shouted.                                                                                ::
    ID: 07018144.wav
    Length: 119
** World War I Army Drill, four companies approach & halt, with orders shouted.                                                                                ::
    ID: 07018143.wav
    Length: 101
** Light Infantry Arms Drill on the march, with orders shouted.                                                                                ::
    ID: 07018142.wav
    Length: 203
** Light Infantry Arms Drill at the halt, with orders shouted.                                                                                ::
    ID: 07018141.wav
    Length: 197
** Light Infantry Arms Drill on the march, with orders shouted.                                                                                ::
    ID: 07018140.wav
    Length: 190
** Light Infantry Arms Drill at the halt, with orders shouted.                                                                                ::
    ID: 07018139.wav
    Length: 168
** Soldiers moving through undergrowth.                                                                                ::
    ID: 07018138.wav
    Length: 239
** Army Drill, marching at 160 paces per minute, with start & halt.                                                                                ::
    ID: 07018137.wav
    Length: 128
** Army Drill, marching in broken step.                                                                                ::
    ID: 07018136.wav
    Length: 244
** Army Drill, marching at 120 paces per minute, with start & halt.                                                                                ::
    ID: 07018135.wav
    Length: 128
** Army Catering, atmosphere in men's cookhouse with some speech & sounds of utensils being used.                                                                                ::
    ID: 07018134.wav
    Length: 396
** Army Catering, atmosphere in Sergeants' Mess with some speech & sounds of utensils being used.                                                                                ::
    ID: 07018133.wav
    Length: 211
** Army Catering, atmosphere in men's cookhouse with some speech & sounds of utensils being used.                                                                                ::
    ID: 07018132.wav
    Length: 224
** Boat Drill, ship's siren, seven short blasts, one long, pause one long blast. (Last blast signals end of drill.)                                                                                ::
    ID: 07018131.wav
    Length: 15
** R.M.S. Queen Elizabeth II, ship's siren, seven blasts as ship leaves port, close perspective.                                                                                ::
    ID: 07018130.wav
    Length: 15
** R.M.S. Queen Elizabeth II, ship's siren, three long blasts in distance as ship leaves port.                                                                                ::
    ID: 07018129.wav
    Length: 15
** R.M.S. Queen Elizabeth II, ship's siren, four long blasts as ship leaves port, close perspective, with other ships at end.                                                                                ::
    ID: 07018128.wav
    Length: 41
** Unidentified liner, ship's siren, sounded twice.                                                                                ::
    ID: 07018127.wav
    Length: 33
** Unidentified liner, ship's siren, sounded once.                                                                                ::
    ID: 07018126.wav
    Length: 23
** Drifter's siren, one long blast.                                                                                ::
    ID: 07018125.wav
    Length: 15
** Drifters's siren, sounded four times. (Astern.)                                                                                ::
    ID: 07018124.wav
    Length: 10
** P&O liner Strathaird, ship's siren, several long blasts.                                                                                ::
    ID: 07018123.wav
    Length: 16
** Battleship's siren, sounded three times approximately.                                                                                ::
    ID: 07018122.wav
    Length: 17
** Cruiser's siren, sounded approximately six times.                                                                                ::
    ID: 07018121.wav
    Length: 18
** Destroyer's siren, sounded three times, pause, sounded three times, pause, sounded three times.                                                                                ::
    ID: 07018120.wav
    Length: 16
** Ships' whistles & sirens sounded together.                                                                                ::
    ID: 07018119.wav
    Length: 93
** Tug's siren sounded approximately eight times.                                                                                ::
    ID: 07018118.wav
    Length: 19
** Tug's siren sounded four times.                                                                                ::
    ID: 07018117.wav
    Length: 14
** Tug's siren sounded three times.                                                                                ::
    ID: 07018116.wav
    Length: 10
** Ship's siren sounds & is answered by tug.                                                                                ::
    ID: 07018115.wav
    Length: 15
** Southampton foghorn, two blasts. (Period between signals should be 1m00s.)                                                                                ::
    ID: 07018114.wav
    Length: 22
** Tug's siren sounds & is answered by ship.                                                                                ::
    ID: 07018113.wav
    Length: 17
** French barge's siren sounded several times.                                                                                ::
    ID: 07018112.wav
    Length: 22
** 'Cock-a-doodle-doo' ships' sirens sounded.                                                                                ::
    ID: 07018111.wav
    Length: 27
** R.M.S. Queen Elizabeth, ship's siren, sounded once.                                                                                ::
    ID: 07018110.wav
    Length: 10
** Duke of Rothesay, ship's horn, sounded several times.                                                                                ::
    ID: 07018109.wav
    Length: 18
** R.M.S. Aquitania, ship's horn, sounded several times.                                                                                ::
    ID: 07018108.wav
    Length: 46
** Tug's siren.                                                                                ::
    ID: 07018107.wav
    Length: 13
** Tug's siren.                                                                                ::
    ID: 07018106.wav
    Length: 15
** Tug's siren.                                                                                ::
    ID: 07018105.wav
    Length: 10
** Trawler's siren.                                                                                ::
    ID: 07018104.wav
    Length: 32
** Trawler's siren.                                                                                ::
    ID: 07018103.wav
    Length: 20
** Ships' and tugs' hooters sounded on River Elbe.                                                                                ::
    ID: 07018102.wav
    Length: 76
** R.M.S. Queen Mary ship's siren, three horn blasts, signalling fog warning.                                                                                ::
    ID: 07018101.wav
    Length: 30
** R.M.S. Queen Mary ship's siren, three horn blasts, siganalling 'farewell'.                                                                                 ::
    ID: 07018100.wav
    Length: 41
** R.M.S. Queen Mary ship's siren, one horn blast, signalling ship stoppping.                                                                                ::
    ID: 07018099.wav
    Length: 11
** R.M.S. Queen Mary ship's siren, three horn blasts, siganalling ship reversing.                                                                                ::
    ID: 07018098.wav
    Length: 17
** R.M.S. Queen Mary ship's siren, two horn blasts, signalling ship turning to port.                                                                                ::
    ID: 07018097.wav
    Length: 12
** R.M.S. Queen Mary ship's siren, one horn blast, signalling ship turning to starboard.                                                                                ::
    ID: 07018096.wav
    Length: 8
** Pool of London, wash under piers and barges. (Some birdsong, no speech.)                                                                                ::
    ID: 07018095.wav
    Length: 220
** Pool of London, dockside atmosphere with sirens & ships passing.                                                                                ::
    ID: 07018094.wav
    Length: 220
** Pool of London, atmosphere as vessel berths with sirens & some speech.                                                                                ::
    ID: 07018093.wav
    Length: 264
** Two ships' sirens sounding long blasts. (Recorded at Pool of London.)                                                                                ::
    ID: 07018092.wav
    Length: 32
** Two ships' sirens sounding long blasts. (Recorded at Pool of London.)                                                                                ::
    ID: 07018091.wav
    Length: 23
** Ships' sirens sounding short blasts. (Recorded at Pool of London.)                                                                                ::
    ID: 07018090.wav
    Length: 14
** Ships' sirens sounding short blasts. (Recorded at Pool of London.)                                                                                ::
    ID: 07018089.wav
    Length: 24
** Pool of London, cargo boat being unloaded. (Cargo of sugar.)                                                                                ::
    ID: 07018088.wav
    Length: 216
** Pool of London, barges passing at dockside.                                                                                ::
    ID: 07018087.wav
    Length: 220
** Pool of London, general atmosphere with occasional sirens & passing ships.                                                                                ::
    ID: 07018086.wav
    Length: 380
** Lock water rushing at St. Lawrence Seaway, Canada.                                                                                ::
    ID: 07018085.wav
    Length: 122
** Lock gates opening at St. Lawrence Seaway, Canada.                                                                                ::
    ID: 07018084.wav
    Length: 63
** Container Ship, exterior, winches & horn.                                                                                ::
    ID: 07018083.wav
    Length: 34
** Container Ship, exterior, control & acceleration.                                                                                ::
    ID: 07018082.wav
    Length: 51
** Container Ship, exterior, horn blast & answer.                                                                                ::
    ID: 07018081.wav
    Length: 7
** Container Ship, exterior, single horn blast from container ship.                                                                                ::
    ID: 07018080.wav
    Length: 7
** Container Ship, interior, recording of atmosphere in engine room, no speech.                                                                                ::
    ID: 07018079.wav
    Length: 181
** Container Ship, interior, recording of atmosphere in wheel house, with some engine noise, no speech.                                                                                ::
    ID: 07018078.wav
    Length: 181
** Container Ship, exterior, engines running in rough weather.                                                                                ::
    ID: 07018077.wav
    Length: 183
** Container Ship, exterior, engines running at slow speed.                                                                                ::
    ID: 07018076.wav
    Length: 185
** Container Ship, exterior, engines running at medium speed.                                                                                ::
    ID: 07018075.wav
    Length: 393
** Trawler engine running, close perspective recording. (Diesel engine, possibly recorded in engine room.)                                                                                ::
    ID: 07018074.wav
    Length: 432
** Dredger operating, close perspective recording.                                                                                ::
    ID: 07018073.wav
    Length: 420
** Ship docking at Dover, with hawser creaks & cars being landed. (Some indistinct speech.)                                                                                ::
    ID: 07018072.wav
    Length: 386
** Customs shed at Dover Ferry Port, general atmosphere with some indistinct speech & sounds of cars being driven.                                                                                ::
    ID: 07018071.wav
    Length: 377
** Harbour background, quiet atmosphere with gulls, sirens & water lapping. (Some engine noise at end of band.)                                                                                ::
    ID: 07018070.wav
    Length: 375
** Cross-Channel car ferry, interior, rough sea recorded in anchor chain locker of ferry.                                                                                ::
    ID: 07018069.wav
    Length: 372
** Cross-Channel car ferry, exterior, rough sea recorded from bows of  ferry.                                                                                ::
    ID: 07018068.wav
    Length: 370
** Cross-Channel car ferry, exterior, wind & rough sea recorded from ferry.                                                                                ::
    ID: 07018067.wav
    Length: 372
** Cross-Channel car ferry, exterior, close perspective recording of engines on cross-channel ferry running at 18 knots.                                                                                ::
    ID: 07018066.wav
    Length: 371
** Cross-Channel car ferry, exterior, seawash at stern of cross-channel ferry.                                                                                ::
    ID: 07018065.wav
    Length: 370
** Cross-Channel car ferry, interior, atmosphere on garage deck of cross-channel ferry upon arrival at port. (Occasional speech & cars driving off.)                                                                                ::
    ID: 07018064.wav
    Length: 166
** Cross-Channel car ferry, interior, atmosphere on garage deck of cross-channel ferry prior to departure.                                                                                ::
    ID: 07018063.wav
    Length: 166
** Dover Port, exterior, departure of cross-channel ferry. (Siren at 1m00s, moves off at 3,00s.)                                                                                ::
    ID: 07018062.wav
    Length: 368
** Calais Port, exterior, departure of cross-channel ferry from Calais. (With siren and clatter.)                                                                                ::
    ID: 07018061.wav
    Length: 374
** Calais Port, exterior, general activity prior to departure of cross- channel ferry.                                                                                ::
    ID: 07018060.wav
    Length: 376
** Chatter, Victorian gentry, fifteen men in conversation.                                                                                ::
    ID: 07018059.wav
    Length: 375
** Chatter, Victorian gentry, 25 people in polite conversation. (Victorian gentry)                                                                                ::
    ID: 07018058.wav
    Length: 392
** People dispersing after a meeting, some distant speech, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018057.wav
    Length: 206
** Six bursts of laughter from group of 20-30 year-olds. (4 seconds between each burst)                                                                                ::
    ID: 07018056.wav
    Length: 84
** Hearty laughter, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018055.wav
    Length: 10
** Hearty laughter, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018054.wav
    Length: 14
** Slow hand-clap into fast rhythm, 20-30 year olds. (Interior.)                                                                                ::
    ID: 07018053.wav
    Length: 19
** Applause, 50 people, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018052.wav
    Length: 15
** Applause, 50 people, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018051.wav
    Length: 12
** 'Hip hip hooray', 50 people, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018050.wav
    Length: 9
** Cheering, 50 people, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018049.wav
    Length: 16
** Jeering & booing, 50 people, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018048.wav
    Length: 44
** Gasp, 36 people, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018047.wav
    Length: 6
** Gasp, 36 people, 20-30 years old. (Interior.)                                                                                ::
    ID: 07018046.wav
    Length: 6
** Continuous chatter, ten men and women aged 20-25 years old. (Continuous background chatter.)                                                                                ::
    ID: 07018045.wav
    Length: 411
** Homely chatter between two women and three teenagers.                                                                                ::
    ID: 07018044.wav
    Length: 192
** Cheerful chatter from seven men aged 20-25 years.                                                                                ::
    ID: 07018043.wav
    Length: 186
** Three men & three women speaking. (Close perspective recording.)                                                                                ::
    ID: 07018042.wav
    Length: 393
** Animated speech from twelve men aged 20-25 years.                                                                                ::
    ID: 07018041.wav
    Length: 364
** Party chatter, fifteen gushing women. (Farcical.)                                                                                ::
    ID: 07018040.wav
    Length: 94
** Closing time in public house, twelve youths, laughter with some distinct speech. (Farcical.)                                                                                ::
    ID: 07018039.wav
    Length: 77
** Spirited party chatter, 30 men & women. (Farcical.)                                                                                ::
    ID: 07018038.wav
    Length: 92
** Victorian party chatter, 24 men & women. (Farcical.)                                                                                 ::
    ID: 07018037.wav
    Length: 94
** Six women booing. (Farcical.)                                                                                ::
    ID: 07018036.wav
    Length: 9
** Twelve men booing. (Farcical.)                                                                                ::
    ID: 07018035.wav
    Length: 12
** Fifteen men and women booing. (Farcical.)                                                                                ::
    ID: 07018034.wav
    Length: 11
** Twelve women saying 'No, no'. (Fracical.)                                                                                ::
    ID: 07018033.wav
    Length: 8
** Fifteen men saying 'No, no'. (Farcical.)                                                                                ::
    ID: 07018032.wav
    Length: 8
** Fifteen men and women saying 'No, no'. (Farcical.)                                                                                ::
    ID: 07018031.wav
    Length: 8
** Ten women saying 'Aye, aye'. (Farcical.)                                                                                ::
    ID: 07018030.wav
    Length: 7
** Twelve men saying 'Aye, aye'. (Farcical.)                                                                                ::
    ID: 07018029.wav
    Length: 7
** Twelve men and women saying  'Aye, aye'. (Farcical.)                                                                                ::
    ID: 07018028.wav
    Length: 6
** Ten women saying  'Hear, hear'. (Farcical.)                                                                                ::
    ID: 07018027.wav
    Length: 8
** Ten men saying  'Hear, hear'. (Farcical.)                                                                                ::
    ID: 07018026.wav
    Length: 8
** Nine men and women saying 'Hear, hear'. (Farcical.)                                                                                ::
    ID: 07018025.wav
    Length: 7
** Six men cheering. (Farcical.)                                                                                ::
    ID: 07018024.wav
    Length: 10
** 50 men and women cheering. (Farcical.)                                                                                ::
    ID: 07018023.wav
    Length: 16
** 24 men and women cheering. (Farcical.)                                                                                ::
    ID: 07018022.wav
    Length: 9
** Six women cheering. (Farcical.)                                                                                ::
    ID: 07018021.wav
    Length: 13
** Fifteen Victorian ladies in spirited indoor conversation with some laughter. (Farcical.)                                                                                ::
    ID: 07018020.wav
    Length: 144
** Twelve Victorian ladies in polite indoor conversation. (Farcical.)                                                                                ::
    ID: 07018019.wav
    Length: 138
** Crowd of 40-50 men & women in a hall, loud & angry shouting with occasional pauses.                                                                                ::
    ID: 07018018.wav
    Length: 421
** Crowd of 40-50 men & women in a hall, angry shouting with occasional pauses.                                                                                ::
    ID: 07018017.wav
    Length: 421
** Crowd of 60 people, mainly men, continuous indistinct speech after meeting in hall.                                                                                ::
    ID: 07018016.wav
    Length: 477
** Crowd of 40-50 men & women in hall, continuous serious indistinct speech.                                                                                ::
    ID: 07018015.wav
    Length: 422
** Meeting with 50 men, rise & disperse after meeting.                                                                                ::
    ID: 07018014.wav
    Length: 420
** Luncheon party with 50 men, general atmosphere with speech & occasional cutlery & crockery sounds.                                                                                ::
    ID: 07018013.wav
    Length: 423
** Animated party chatter, with occasional laughter & clink of glasses.                                                                                ::
    ID: 07018012.wav
    Length: 400
** Excited  chatter in large room, women.                                                                                ::
    ID: 07018011.wav
    Length: 101
** Conversational chatter in large room, 20 people mixed.                                                                                ::
    ID: 07018010.wav
    Length: 282
** Small crowd, mainly women, exclamation during conversation.                                                                                ::
    ID: 07018009.wav
    Length: 10
** Small crowd, mainly women, quiet continuous conversation with occassional rattle of teacups.                                                                                ::
    ID: 07018008.wav
    Length: 362
** Small crowd, mainly women, general atmosphere with speech & some pauses.                                                                                ::
    ID: 07018007.wav
    Length: 439
** Crowd of 40 women, in a hall, with some children. (Close perspective recording.)                                                                                ::
    ID: 07018006.wav
    Length: 421
** Crowd of 100 women, in a hall, with footsteps & indistinct speech.                                                                                ::
    ID: 07018005.wav
    Length: 422
** Crowd of 36 women, in a hall, with footsteps & indistinct speech.                                                                                ::
    ID: 07018004.wav
    Length: 423
** Large Crowd, mainly women, in a hall, with footsteps & indistinct speech.                                                                                ::
    ID: 07018003.wav
    Length: 424
** Cocktail Party, general atmosphere, fairly animated. (20 people, mixed.)                                                                                ::
    ID: 07018002.wav
    Length: 376
** Cocktail Party, general atmosphere. (20 people, mixed.)                                                                                ::
    ID: 07018001.wav
    Length: 376
** Traffic near Berlin Zoo.                                                                                ::
    ID: 07017186.wav
    Length: 386
** Berlin U-bahn, atmosphere in underground station, with trains passing, arriving & departing, doors, announcements over P.A. & indistinct speech of passengers.                                                                                ::
    ID: 07017185.wav
    Length: 160
** Heavy traffic in Hamburg.                                                                                ::
    ID: 07017184.wav
    Length: 233
** German crowd, exterior, large angry crowd. (Some shouting.)                                                                                ::
    ID: 07017183.wav
    Length: 417
** German crowd, exterior, mixed angry crowd. (Some shouting.)                                                                                ::
    ID: 07017182.wav
    Length: 421
** German crowd in large department store with sounds of tills being used.                                                                                ::
    ID: 07017181.wav
    Length: 407
** Small German crowd, with mixed indoor chatter. (Some distinct speech.)                                                                                ::
    ID: 07017180.wav
    Length: 409
** Bowling alley in German gasthof being used. (No speech.)                                                                                ::
    ID: 07017179.wav
    Length: 212
** Mechanical glass washing machine operating in German gasthof. (Some indistinct speech.)                                                                                ::
    ID: 07017178.wav
    Length: 124
** German Gasthof, atmosphere in busy gasthof with conversation, footsteps & clinking of glasses.                                                                                ::
    ID: 07017177.wav
    Length: 367
** Supermarine Seafire, exterior, aerobatics with two planes. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017176.wav
    Length: 101
** Supermarine Seafire, exterior, aerobatics with one plane. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017175.wav
    Length: 283
** Supermarine Seafire, exterior, taxi up & switch off. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017174.wav
    Length: 80
** Supermarine Seafire, exterior, landing. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017173.wav
    Length: 31
** Supermarine Seafire, exterior, passing overhead, cuts engine. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017172.wav
    Length: 59
** Supermarine Seafire, exterior, gathering speed to take-off. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017171.wav
    Length: 48
** Supermarine Seafire, exterior, start, tickover, taxi away. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017170.wav
    Length: 125
** Supermarine Seafire, exterior, false start. ( World War II fighter, Spitfire adapted for Royal Navy, one Griffon piston engine.)                                                                                ::
    ID: 07017169.wav
    Length: 9
** Supermarine Spitfire, exterior, diving with gunfire. (World War II fighter, one piston engine.)                                                                                ::
    ID: 07017168.wav
    Length: 21
** Supermarine Spitfire, exterior, landing, taxi to close-up. (World War II fighter, one piston engine.)                                                                                ::
    ID: 07017167.wav
    Length: 70
** Supermarine Spitfire, exterior, circling and diving. (World War II fighter, one piston engine.)                                                                                ::
    ID: 07017166.wav
    Length: 221
** Supermarine Spitfire, exterior, mid-distance take off. (World War II fighter, one piston engine.)                                                                                ::
    ID: 07017165.wav
    Length: 49
** Supermarine Spitfire, exterior, take off. ( World War II fighter, one piston engine.)                                                                                ::
    ID: 07017164.wav
    Length: 32
** Supermarine Spitfire, exterior, start, run up, misfire, rev up, tickover, taxi away. (World War II fighter, one piston engine.)                                                                                ::
    ID: 07017163.wav
    Length: 179
** Supermarine Spitfire, exterior, false starts. (World War II fighter, one piston engine.)                                                                                ::
    ID: 07017162.wav
    Length: 26
** Gentlemen's hairdressing saloon. (Recorded in close perspective.)                                                                                ::
    ID: 07017161.wav
    Length: 375
** Gentlemen's hairdressing saloon. (Recorded in general perspective.)                                                                                ::
    ID: 07017160.wav
    Length: 367
** St James's Park, general park atmosphere with birds, distant traffic & occasional speech.                                                                                ::
    ID: 07017159.wav
    Length: 401
** St James's Park, atmosphere at lakeside with birds, wildfowl, lapping water & footsteps.                                                                                ::
    ID: 07017158.wav
    Length: 404
** Land Rover, exterior, passing slowly over rough ground.                                                                                ::
    ID: 07017157.wav
    Length: 45
** Land Rover, exterior, passing over rough ground.                                                                                ::
    ID: 07017156.wav
    Length: 24
** Land Rover, exterior, passing at speed.                                                                                ::
    ID: 07017155.wav
    Length: 14
** Land Rover, exterior, start, reverse away.                                                                                ::
    ID: 07017154.wav
    Length: 22
** Land Rover, exterior, approach and stop.                                                                                ::
    ID: 07017153.wav
    Length: 19
** Land Rover, exterior, start, depart.                                                                                ::
    ID: 07017152.wav
    Length: 20
** Land Rover, interior, start, run over rough ground.                                                                                ::
    ID: 07017151.wav
    Length: 70
** Land Rover, interior, start, revving.                                                                                ::
    ID: 07017150.wav
    Length: 127
** Land Rover, interior, start, tickover.                                                                                ::
    ID: 07017149.wav
    Length: 62
** Land Rover starts.                                                                                 ::
    ID: 07017148.wav
    Length: 11
** Land Rover, two doors open and close.                                                                                ::
    ID: 07017147.wav
    Length: 9
** Land Rover, one door open and close.                                                                                ::
    ID: 07017146.wav
    Length: 7
** Land Rover, interior, horn sounded.                                                                                ::
    ID: 07017145.wav
    Length: 6
** Land Rover, interior, start, fast run, stops.                                                                                ::
    ID: 07017144.wav
    Length: 346
** Land Rover, interior, start, medium fast run, stops.                                                                                ::
    ID: 07017143.wav
    Length: 377
** Land Rover, interior, start, reverses, stops.                                                                                ::
    ID: 07017142.wav
    Length: 48
** Land Rover, interior, start, runs over rough ground, stops. (Some squeaks and rattles.)                                                                                ::
    ID: 07017141.wav
    Length: 307
** Land Rover, interior, start, runs over rough ground, stops.                                                                                ::
    ID: 07017140.wav
    Length: 367
** Two horses on various surfaces, walking, then stop.                                                                                ::
    ID: 07017139.wav
    Length: 63
** Two horses on grass turf, trotting, then stop. (Actuality)                                                                                ::
    ID: 07017138.wav
    Length: 60
** Two horses on grass turf, cantering, then stop. (Actuality)                                                                                ::
    ID: 07017137.wav
    Length: 42
** Two horses on grass turf, trotting, then stop. (Actuality)                                                                                ::
    ID: 07017136.wav
    Length: 79
** Two horses on grass turf. (Actuality)                                                                                ::
    ID: 07017135.wav
    Length: 62
** Two horses on grass turf, with occasional snorts. (Actuality)                                                                                ::
    ID: 07017134.wav
    Length: 75
** Two horses stopping on soft surface. (Actuality)                                                                                ::
    ID: 07017133.wav
    Length: 15
** Two horses on soft surface. (Actuality)                                                                                ::
    ID: 07017132.wav
    Length: 206
** Pony gallops away on hard surface and returns. (Actuality, with birdsong)                                                                                ::
    ID: 07017131.wav
    Length: 46
** Pony gallops up on hard surface, breathing heavily. (Actuality)                                                                                ::
    ID: 07017130.wav
    Length: 36
** Pony gallops away on hard surface. (Actuality)                                                                                ::
    ID: 07017129.wav
    Length: 14
** Horse mounted and canters away. (Actuality)                                                                                ::
    ID: 07017128.wav
    Length: 23
** Horse chewing in stable. (Actuality)                                                                                ::
    ID: 07017127.wav
    Length: 89
** Two horses led out of stable at run, repeated. (Actuality)                                                                                ::
    ID: 07017126.wav
    Length: 35
** Horse trots away, door closed. (Actuality)                                                                                ::
    ID: 07017125.wav
    Length: 13
** Horse mounted and canters away. (Actuality, recorded from inside building)                                                                                ::
    ID: 07017124.wav
    Length: 16
** Horse approaches and stops. (Actuality, recorded from inside building)                                                                                ::
    ID: 07017123.wav
    Length: 16
** Horse approaches, canter to stop, is dismounted and led away. (Actuality)                                                                                ::
    ID: 07017122.wav
    Length: 24
** Horse approaches on turf, canters to stop in yard and is dismounted. (Actuality)                                                                                ::
    ID: 07017121.wav
    Length: 17
** Horse eating straw in stable. (Actuality)                                                                                ::
    ID: 07017120.wav
    Length: 97
** Horse mounted and dismounted twice, saddle removed. (Actuality)                                                                                ::
    ID: 07017119.wav
    Length: 50
** Horse dismounted and taken into stable. (Actuality)                                                                                ::
    ID: 07017118.wav
    Length: 21
** Horse led out of stable and mounted. (Actuality)                                                                                ::
    ID: 07017117.wav
    Length: 20
** Ruritanian state occasion with horses, cheers, shouts & excited chatter.                                                                                ::
    ID: 07017116.wav
    Length: 184
** Procession passing with horses, chatter & some orders.                                                                                ::
    ID: 07017115.wav
    Length: 195
** Cavalry & transport passing.                                                                                ::
    ID: 07017114.wav
    Length: 67
** Cavalry troop passing through town.                                                                                ::
    ID: 07017113.wav
    Length: 66
** Cavalry troop coming to stop.                                                                                ::
    ID: 07017112.wav
    Length: 25
** Cavalry troop passing through town on hard surface.                                                                                ::
    ID: 07017111.wav
    Length: 189
** String of frightened ponies whinnying and stamping.                                                                                ::
    ID: 07017110.wav
    Length: 43
** Pony snorting.                                                                                ::
    ID: 07017109.wav
    Length: 6
** Pony whinnying.                                                                                ::
    ID: 07017108.wav
    Length: 6
** Pony whinnying.                                                                                ::
    ID: 07017107.wav
    Length: 6
** Pony whinnying.                                                                                ::
    ID: 07017106.wav
    Length: 6
** One pony munching. (Indoors)                                                                                ::
    ID: 07017105.wav
    Length: 108
** One pony munching. (Outdoors)                                                                                ::
    ID: 07017104.wav
    Length: 117
** String of ponies leaving water and on to dry land.                                                                                ::
    ID: 07017103.wav
    Length: 58
** String of ponies splashing through river.                                                                                ::
    ID: 07017102.wav
    Length: 199
** String of ponies standing. (Restless)                                                                                ::
    ID: 07017101.wav
    Length: 261
** Pony walking in very wet mud.                                                                                ::
    ID: 07017100.wav
    Length: 117
** Two ponies standing.                                                                                ::
    ID: 07017099.wav
    Length: 92
** String of ponies walking down hill and stopping.                                                                                ::
    ID: 07017098.wav
    Length: 143
** String of ponies walking over rough surface.                                                                                ::
    ID: 07017097.wav
    Length: 149
** String of ponies stop.                                                                                ::
    ID: 07017096.wav
    Length: 22
** String of ponies start, walk and stop.                                                                                ::
    ID: 07017095.wav
    Length: 154
** Two ponies stop and stand.                                                                                ::
    ID: 07017094.wav
    Length: 35
** Two ponies start, walk and stop.                                                                                ::
    ID: 07017093.wav
    Length: 147
** Single pony trots past.                                                                                ::
    ID: 07017092.wav
    Length: 20
** Single pony trots past.                                                                                ::
    ID: 07017091.wav
    Length: 20
** Single pony trots up and stops.                                                                                ::
    ID: 07017090.wav
    Length: 14
** Single pony trots up, stops and stands.                                                                                ::
    ID: 07017089.wav
    Length: 34
** Single pony canters away.                                                                                ::
    ID: 07017088.wav
    Length: 12
** Single pony snorts and walks away.                                                                                ::
    ID: 07017087.wav
    Length: 11
** Twelve horses on hard surface, milling in yard. (Actuality)                                                                                ::
    ID: 07017086.wav
    Length: 281
** Six horses on hard surface, leaving yard. (Actuality)                                                                                ::
    ID: 07017085.wav
    Length: 29
** Restless horse on hard surface, approaches and departs. (Actuality)                                                                                ::
    ID: 07017084.wav
    Length: 35
** Twelve horses on hard surface, departing at trot. (Actuality)                                                                                ::
    ID: 07017083.wav
    Length: 32
** Twelve horses on hard surface, passing at trot. (Actuality)                                                                                ::
    ID: 07017082.wav
    Length: 43
** Twelve horses on hard surface, approach at trot, stop, milling in yard. (Actuality)                                                                                ::
    ID: 07017081.wav
    Length: 48
** Twelve horses on hard surface, leaving yard. (Actuality)                                                                                ::
    ID: 07017080.wav
    Length: 56
** Twelve horses on hard surface, passing. (Actuality)                                                                                ::
    ID: 07017079.wav
    Length: 29
** Twelve horses on hard surface, approach and stop. (Actuality)                                                                                ::
    ID: 07017078.wav
    Length: 38
** Horses or cattle moving on broken surface.                                                                                ::
    ID: 07017077.wav
    Length: 363
** Horses or cattle on grass moving fairly fast.                                                                                ::
    ID: 07017076.wav
    Length: 365
** Atmosphere at RAF Station airfield, with general jet aircraft activity.                                                                                ::
    ID: 07017075.wav
    Length: 374
** RAF V-bomber, exterior, taxi past. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017074.wav
    Length: 116
** RAF V-bomber, exterior, passing overhead. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017073.wav
    Length: 38
** RAF V-bomber, exterior, landing. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017072.wav
    Length: 56
** RAF V-bomber, exterior, taxi into position at marshalling point. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017071.wav
    Length: 202
** RAF V-bomber, exterior, taxi to close up, switch off. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017070.wav
    Length: 370
** RAF V-bomber, exterior, approach and overshoot. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017069.wav
    Length: 93
** RAF V-bomber, exterior, take-off. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017068.wav
    Length: 86
** RAF V-bomber, exterior, rev up and taxi away. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017067.wav
    Length: 133
** RAF V-bomber, exterior, emergency start-up with combustor, taxi away. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017066.wav
    Length: 369
** RAF V-bomber, exterior, normal start-up procedure, generator running, run up engines. (Long-range bomber, 4 jet engines.)                                                                                ::
    ID: 07017065.wav
    Length: 374
** Luton Airport Air Traffic Control, approach control.                                                                                ::
    ID: 07017064.wav
    Length: 375
** Luton Airport Air Traffic Control, aerodrome control.                                                                                ::
    ID: 07017063.wav
    Length: 389
** Heathrow Airport Air Traffic Control, approach control.                                                                                ::
    ID: 07017062.wav
    Length: 388
** Heathrow Airport Air Traffic Control, aerodrome control.                                                                                ::
    ID: 07017061.wav
    Length: 393
** Heathrow Airport viewing base, general atmosphere with sound of aircraft.                                                                                ::
    ID: 07017060.wav
    Length: 374
** Heathrow Airport transcontinental flights terminal building, general atmosphere in departure lounge. (No P.A.)                                                                                ::
    ID: 07017059.wav
    Length: 368
** Heathrow Airport transcontinental flights terminal building, general atmosphere on concourse, with continuous P.A. announcements.                                                                                ::
    ID: 07017058.wav
    Length: 69
** Heathrow Airport transcontinental flights terminal building, general atmosphere on concourse. (No P.A.)                                                                                ::
    ID: 07017057.wav
    Length: 305
** Heathrow Airport, general atmosphere in European and domestic flights terminal building, with continuous P.A. announcements.                                                                                ::
    ID: 07017056.wav
    Length: 173
** Heathrow Airport, general atmosphere in transcontinental flights terminal building, with continuous P.A. announcements.                                                                                ::
    ID: 07017055.wav
    Length: 159
** Heathrow Airport, general atmosphere in European and domestic flights terminal building. (No P.A.)                                                                                ::
    ID: 07017054.wav
    Length: 373
** Heathrow Airport, general atmosphere in transcontinental flights terminal building. (No P.A.)                                                                                ::
    ID: 07017053.wav
    Length: 373
** Generator running on airport apron. (Unknown airport.)                                                                                ::
    ID: 07017052.wav
    Length: 209
** Boeing 707 passenger jet taxis in, recorded on apron. (Unknown airport.)                                                                                ::
    ID: 07017051.wav
    Length: 107
** Atmosphere in airport terminal building. (Unknown airport.)                                                                                ::
    ID: 07017050.wav
    Length: 372
** Small group arguing. (Some identifiable speech.)                                                                                ::
    ID: 07017049.wav
    Length: 123
** Small group, mixed cheerful chatter.                                                                                ::
    ID: 07017048.wav
    Length: 254
** Large cosmopolitan crowd with speech & footsteps.                                                                                ::
    ID: 07017047.wav
    Length: 366
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017046.wav
    Length: 36
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017045.wav
    Length: 27
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017044.wav
    Length: 17
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017043.wav
    Length: 16
** Cheers, applause and whistles at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017042.wav
    Length: 29
** Cheers, applause and whistles at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017041.wav
    Length: 23
** Cheers, applause and whistles at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017040.wav
    Length: 27
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017039.wav
    Length: 13
** Chatter at close of protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017038.wav
    Length: 96
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017037.wav
    Length: 17
** Cheers and applause at protest meeting. (6000 people, recorded outdoors in England.)                                                                                ::
    ID: 07017036.wav
    Length: 18
