** Men's singles match at Wimbledon. (Scores and players' names distinct)                                                                                ::
    ID: 07012114.wav
    Length: 363
** Women's singles match at Wimbledon. (Scores and players' names distinct)                                                                                ::
    ID: 07012113.wav
    Length: 362
** Electronic alarm signal.                                                                                ::
    ID: 07012112.wav
    Length: 57
** Electronic alarm signal.                                                                                ::
    ID: 07012111.wav
    Length: 62
** Electronic alarm signal.                                                                                ::
    ID: 07012110.wav
    Length: 30
** Electronic alarm signal.                                                                                ::
    ID: 07012109.wav
    Length: 52
** Electronic alarm signal.                                                                                ::
    ID: 07012108.wav
    Length: 35
** Electronic alarm signal.                                                                                ::
    ID: 07012107.wav
    Length: 24
** Electronic alarm signal.                                                                                ::
    ID: 07012106.wav
    Length: 51
** Electronic alarm signal.                                                                                ::
    ID: 07012105.wav
    Length: 62
** Electronic alarm signal.                                                                                ::
    ID: 07012104.wav
    Length: 47
** Electronic alarm signal.                                                                                ::
    ID: 07012103.wav
    Length: 47
** Electronic alarm signal.                                                                                ::
    ID: 07012102.wav
    Length: 35
** Electronic alarm signal.                                                                                ::
    ID: 07012101.wav
    Length: 35
** Many bicycle bells ringing.                                                                                ::
    ID: 07012100.wav
    Length: 55
** Bicycle bell, single, double and frantic ringing.                                                                                ::
    ID: 07012099.wav
    Length: 25
** Bicycle bell, single, double and frantic ringing.                                                                                ::
    ID: 07012098.wav
    Length: 28
** Twelve bells ringing. (No animal sounds)                                                                                ::
    ID: 07012097.wav
    Length: 81
** Single cow bell ringing. (No animal sounds)                                                                                ::
    ID: 07012096.wav
    Length: 71
** Sleigh bells ringing.                                                                                ::
    ID: 07012095.wav
    Length: 69
** Sleigh bells ringing.                                                                                ::
    ID: 07012094.wav
    Length: 73
** Sleigh bells ringing.                                                                                ::
    ID: 07012093.wav
    Length: 75
** Sleigh bells ringing.                                                                                ::
    ID: 07012092.wav
    Length: 68
** Sleigh bells ringing.                                                                                ::
    ID: 07012091.wav
    Length: 70
** Harness jingling. (No animal sounds)                                                                                ::
    ID: 07012090.wav
    Length: 151
** Camel bells ringing.                                                                                ::
    ID: 07012089.wav
    Length: 129
** Small bell, short and frantic ringing.                                                                                ::
    ID: 07012088.wav
    Length: 19
** Desk bell ringing.                                                                                ::
    ID: 07012087.wav
    Length: 21
** Bell ringing on old-fashioned bus ticket machine.                                                                                ::
    ID: 07012086.wav
    Length: 13
** Continuous ringing of glass wind bells.                                                                                ::
    ID: 07012085.wav
    Length: 393
** Continuous ringing of electric alarm. (Medium tone)                                                                                ::
    ID: 07012084.wav
    Length: 159
** Continuous ringing of electric alarm. (Deep tone)                                                                                ::
    ID: 07012083.wav
    Length: 155
** Mechanical twist-action door bell ringing.                                                                                ::
    ID: 07012082.wav
    Length: 35
** Calling buzzer on intercom sounded at long and short intervals.                                                                                ::
    ID: 07012081.wav
    Length: 29
** Calling buzzer on intercom sounded at long and short intervals.                                                                                ::
    ID: 07012080.wav
    Length: 28
** Electric buzzer sounded at long and short intervals.                                                                                ::
    ID: 07012079.wav
    Length: 34
** Electric buzzer sounded at long and short intervals.                                                                                ::
    ID: 07012078.wav
    Length: 33
** Electric buzzer sounded at long and short intervals.                                                                                ::
    ID: 07012077.wav
    Length: 31
** Electric buzzer sounded at long and short intervals.                                                                                ::
    ID: 07012076.wav
    Length: 31
** Electric door chimes rung at intervals. (Ding-dong note)                                                                                ::
    ID: 07012075.wav
    Length: 48
** Electric door bell rung at long and short intervals. (High note)                                                                                ::
    ID: 07012074.wav
    Length: 48
** Electric door bell rung at long and short intervals. (High note)                                                                                ::
    ID: 07012073.wav
    Length: 58
** Electric door bell rung at long and short intervals. (Medium note)                                                                                ::
    ID: 07012072.wav
    Length: 50
** Hand bell ringing. (High note)                                                                                ::
    ID: 07012071.wav
    Length: 35
** Hand bell ringing. (Medium note)                                                                                ::
    ID: 07012070.wav
    Length: 39
** Hand bell ringing. (High note)                                                                                ::
    ID: 07012069.wav
    Length: 38
** Old-fashioned door bell ringing. (High note)                                                                                ::
    ID: 07012068.wav
    Length: 48
** Old-fashioned door bell ringing. (Medium note)                                                                                ::
    ID: 07012067.wav
    Length: 47
** Old-fashioned door bell ringing. (Deep note)                                                                                ::
    ID: 07012066.wav
    Length: 39
** Exterior, passing at medium-fast speed. (Bedford light van.)                                                                                ::
    ID: 07012065.wav
    Length: 35
** Exterior, passing at medium speed. (Bedford light van.)                                                                                ::
    ID: 07012064.wav
    Length: 29
** Exterior, start, three-point turn, depart. (Bedford light van.)                                                                                ::
    ID: 07012063.wav
    Length: 39
** Exterior, approach, stop, depart on gravel. (Bedford light van.)                                                                                ::
    ID: 07012062.wav
    Length: 37
** Exterior, approach and stop. (Bedford light van.)                                                                                ::
    ID: 07012061.wav
    Length: 23
** Exterior, start, depart. (Bedford light van.)                                                                                ::
    ID: 07012060.wav
    Length: 25
** Exterior, start, depart. (Bedford light van.)                                                                                ::
    ID: 07012059.wav
    Length: 26
** Exterior, start, tickover, switch off. (Bedford light van.)                                                                                ::
    ID: 07012058.wav
    Length: 158
** Exterior, start, revving, ends with tickover and switch off. (Bedford light van.)                                                                                ::
    ID: 07012057.wav
    Length: 73
** Exterior, three false starts, (Bedford light van.)                                                                                ::
    ID: 07012056.wav
    Length: 24
** Exterior, two doors opened and closed. (Bedford light van.)                                                                                ::
    ID: 07012055.wav
    Length: 11
** Exterior, one door opened and closed. (Bedford light van.)                                                                                ::
    ID: 07012054.wav
    Length: 9
** Interior, slow down, stop, switch off. (Bedford light van.)                                                                                ::
    ID: 07012053.wav
    Length: 39
** Interior, start into constant run. (Bedford light van.)                                                                                ::
    ID: 07012052.wav
    Length: 335
** Interior, start, run with gear changes, stop. (Bedford light van.)                                                                                ::
    ID: 07012051.wav
    Length: 217
** Interior, false start, start, revving and manoeuvring, switch off. (Bedford light van.)                                                                                ::
    ID: 07012050.wav
    Length: 165
** Interior, start, tickover, switch off. (Bedford light van.)                                                                                ::
    ID: 07012049.wav
    Length: 104
** Interior, two false starts. (Bedford light van.)                                                                                ::
    ID: 07012048.wav
    Length: 19
** Interior, heater boost motor. (Bedford light van.)                                                                                ::
    ID: 07012047.wav
    Length: 153
** Interior, indicators, winker type. (Bedford light van.)                                                                                ::
    ID: 07012046.wav
    Length: 31
** Interior, horn. (Bedford light van.)                                                                                ::
    ID: 07012045.wav
    Length: 44
** Interior, windscreen wipers. (Bedford light van.)                                                                                ::
    ID: 07012044.wav
    Length: 219
** Interior, hand brake on and off. (Bedford light van.)                                                                                ::
    ID: 07012043.wav
    Length: 11
** Interior, window lowered and raised. (Bedford light van.)                                                                                ::
    ID: 07012042.wav
    Length: 12
** Interior, rear door opened and closed. (Bedford light van.)                                                                                ::
    ID: 07012041.wav
    Length: 18
** Interior, two doors opened and closed. (Bedford light van.)                                                                                ::
    ID: 07012040.wav
    Length: 6
** Interior, door opened and closed. (Bedford light van.)                                                                                ::
    ID: 07012039.wav
    Length: 9
** Atmosphere, lorries and talking, in large garage.                                                                                ::
    ID: 07012038.wav
    Length: 360
** Large, quiet, vehicle repair shop.                                                                                ::
    ID: 07012037.wav
    Length: 150
** Large, busy, vehicle repair shop.                                                                                ::
    ID: 07012036.wav
    Length: 150
** Exterior, arrive and stop. (15 cwt. diesel truck)                                                                                ::
    ID: 07012035.wav
    Length: 32
** Exterior, passing. (15 cwt. diesel truck)                                                                                ::
    ID: 07012034.wav
    Length: 34
** Exterior, start, depart. (15 cwt. diesel truck)                                                                                ::
    ID: 07012033.wav
    Length: 33
** Interior, start, tickover, switch off. (15 cwt. diesel truck)                                                                                ::
    ID: 07012032.wav
    Length: 105
** Interior, two doors open and close. (15 cwt. diesel truck)                                                                                ::
    ID: 07012031.wav
    Length: 6
** Interior, door open and close. (15 cwt. diesel truck)                                                                                ::
    ID: 07012030.wav
    Length: 6
** Interior, start, revving, switch off. (15 cwt. diesel truck)                                                                                ::
    ID: 07012029.wav
    Length: 30
** Interior, travelling over rough ground, stops. (15 cwt. diesel truck)                                                                                ::
    ID: 07012028.wav
    Length: 269
** Interior, reversing and stopping. (15 cwt. diesel truck)                                                                                ::
    ID: 07012027.wav
    Length: 52
** Interior, start, depart, run on trunk road, stop, switch off. (15 cwt. diesel truck)                                                                                ::
    ID: 07012026.wav
    Length: 367
** Interior, start, depart, run through town, stop, switch off. (15 cwt. diesel truck)                                                                                ::
    ID: 07012025.wav
    Length: 379
** Exterior, passing. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012024.wav
    Length: 20
** Exterior, slow approach and stop, gear change, depart. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012023.wav
    Length: 62
** Exterior, start, depart. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012022.wav
    Length: 23
** Exterior, approach and stop. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012021.wav
    Length: 13
** Exterior, start, tickover, stop. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012020.wav
    Length: 138
** Interior, start, reversing, stop. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012019.wav
    Length: 70
** Interior, start, tickover, switch off. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012018.wav
    Length: 123
** Interior, three false starts. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012017.wav
    Length: 19
** Interior, sliding door closed. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012016.wav
    Length: 6
** Interior, sliding door opened. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012015.wav
    Length: 6
** Interior, hill climb. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012014.wav
    Length: 209
** Interior, slow-speed run. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012013.wav
    Length: 179
** Interior, stopping. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012012.wav
    Length: 23
** Interior, start, constant run, stop. (2 ton diesel truck, make not known)                                                                                ::
    ID: 07012011.wav
    Length: 362
** Exterior, approach and stop. (5 ton diesel truck)                                                                                ::
    ID: 07012010.wav
    Length: 30
** Exterior, passing. (5 ton diesel truck)                                                                                ::
    ID: 07012009.wav
    Length: 38
** Exterior, start up, depart. (5 ton diesel truck)                                                                                ::
    ID: 07012008.wav
    Length: 28
** Interior, start, tickover, switch off. (5 ton diesel truck)                                                                                ::
    ID: 07012007.wav
    Length: 112
** Interior, 2 doors open and close. (5 ton diesel truck)                                                                                ::
    ID: 07012006.wav
    Length: 7
** Interior, 1 door open and close. (5 ton diesel truck)                                                                                ::
    ID: 07012005.wav
    Length: 6
** Interior, travelling over rough track in low gear. (5 ton diesel truck)                                                                                ::
    ID: 07012004.wav
    Length: 337
** Interior, reversing. (5 ton diesel truck)                                                                                ::
    ID: 07012003.wav
    Length: 50
** Interior, start, move off into steady run on trunk road, slow down, stop, (5 ton diesel truck)                                                                                ::
    ID: 07012002.wav
    Length: 373
** Interior, start, move off into medium fast run with frequent use of gears, slow down, stop, (5 ton diesel truck)                                                                                ::
    ID: 07012001.wav
    Length: 366
** General atmosphere at a county cricket match without highlights.                                                                                ::
    ID: 07011362.wav
    Length: 404
** County cricket match in Kent. 1 stroke of bat.                                                                                ::
    ID: 07011361.wav
    Length: 7
** County cricket match in Kent. Mild applause for resumption of play.                                                                                ::
    ID: 07011360.wav
    Length: 32
** County cricket match in Kent. Good shot & applause.                                                                                ::
    ID: 07011359.wav
    Length: 23
** County cricket match in Kent. Good stroke & applause.                                                                                ::
    ID: 07011358.wav
    Length: 25
** County cricket match in Kent. Stroke & mild applause.                                                                                ::
    ID: 07011357.wav
    Length: 14
** County cricket match in Kent. Stroke and applause.                                                                                 ::
    ID: 07011356.wav
    Length: 15
** Golf club bar, evening.                                                                                ::
    ID: 07011355.wav
    Length: 194
** Golf club bar, lunch time.                                                                                ::
    ID: 07011354.wav
    Length: 194
** Small group of people in a tea room.                                                                                ::
    ID: 07011353.wav
    Length: 393
** Light chatter with crockery. Outdoor resturant.                                                                                ::
    ID: 07011352.wav
    Length: 205
** General atmosphere with birdsong, speech crockery and cutlery clatter. Outdoor resturant.                                                                                ::
    ID: 07011351.wav
    Length: 187
** Large busy restaurant serving New Years Eve meal.                                                                                ::
    ID: 07011350.wav
    Length: 198
** Busy dining area in large night club.                                                                                ::
    ID: 07011349.wav
    Length: 197
** Busy atmosphere in a cafe with teenagers talking. (Indistinct clatter of cutlery and crockery in background)                                                                                ::
    ID: 07011348.wav
    Length: 395
** Atmosphere in medium-sized cafe. (15 tables)                                                                                ::
    ID: 07011347.wav
    Length: 268
** Espresso coffee machine, person preparing coffee. (Some traffic in background)                                                                                ::
    ID: 07011346.wav
    Length: 136
** Conversation, frying food and traffic noise in fish & chip shop.                                                                                ::
    ID: 07011345.wav
    Length: 370
** Quiet atmosphere in cheap restaurant with clatter of crockery and cutlery.                                                                                ::
    ID: 07011344.wav
    Length: 371
** Quiet conversation and clatter in cheap restaurant.                                                                                ::
    ID: 07011343.wav
    Length: 372
** Noisy French resturant, in London with English speech.                                                                                ::
    ID: 07011342.wav
    Length: 362
** Light chatter and movement. Lunch/dinner time.                                                                                ::
    ID: 07011341.wav
    Length: 362
** Light chatter at coffee-time.                                                                                ::
    ID: 07011340.wav
    Length: 361
** General atmosphere in public bar, London area.                                                                                ::
    ID: 07011339.wav
    Length: 902
** Atmosphere in workmens cafe. London area.                                                                                ::
    ID: 07011338.wav
    Length: 904
** Interior, self starter; tickover; switch off (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011337.wav
    Length: 95
** Interior, Slow down; stop; switch off (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011336.wav
    Length: 26
** Interior, self starter; run in traffic; stop; switch off (Ami 6, 1968 model, 602cc)                                                                                ::
    ID: 07011335.wav
    Length: 258
** Interior, Slow down; stop; switch off (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011334.wav
    Length: 34
** Interior, self starter; into fast constant run (Ami 6, 1968 model, 602cc)                                                                                  ::
    ID: 07011333.wav
    Length: 333
** Interior, stop, switch off. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011332.wav
    Length: 22
** Interior, start, hill climb. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011331.wav
    Length: 167
** Interior, start, reversing, switch off. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011330.wav
    Length: 130
** Interior, hand brake on and off. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011329.wav
    Length: 8
** Interior, door closed. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011328.wav
    Length: 6
** Interior, door opened on a Citroen                                                                                :Cars:Citroen:
    ID: 07011327.wav
    Length: 6
** Interior, self starter, tickover; switch off (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011326.wav
    Length: 215
** Interior, self starter; revving (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011325.wav
    Length: 68
** Interior, four false starts (Ami 6, 1968 model, 602cc Citroen)                                                                                ::
    ID: 07011324.wav
    Length: 26
** Exterior, fast approach and pass with horn. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011323.wav
    Length: 17
** Exterior, fast approach and pass. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011322.wav
    Length: 16
** Exterior, approach and pass at medium speed. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011321.wav
    Length: 38
** Exterior, approach, stop, switch off. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011320.wav
    Length: 40
** Exterior, approach, stop, switch off. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011319.wav
    Length: 25
** Exterior, start, depart very fast. (AM 1.6, 1968 model, 620cc)                                                                                ::
    ID: 07011318.wav
    Length: 24
** Exterior, self starter; depart fast (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011317.wav
    Length: 32
** Exterior, self starter; depart at medium speed (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011316.wav
    Length: 32
** Exterior, start, revving, switch off. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011315.wav
    Length: 69
** Exterior, start, tickover, switch off. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011314.wav
    Length: 168
** Exterior, door closed. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011313.wav
    Length: 6
** Exterior, door opened. (Ami 6, 1968 model, 602cc: Citroen)                                                                                :Cars:Citroen:
    ID: 07011312.wav
    Length: 6
** Interior, stop, switch off. (1953 model, 14 h.p.: Citroen)                                                                                :Cars:Citroen:
    ID: 07011311.wav
    Length: 21
** Interior, start, tickover into medium-speed run. (1953 model, 14 h.p.: Citroen)                                                                                :Cars:Citroen:
    ID: 07011310.wav
    Length: 103
** Interior, start, tickover into fast run, stop, switch off. (1953 model, 14 h.p. Citroen)                                                                                ::
    ID: 07011309.wav
    Length: 133
** Exterior, approach and pass at speed. (1953 model, 14 h.p.)                                                                                ::
    ID: 07011308.wav
    Length: 29
** Exterior, approach and pass. (1953 model, 14 h.p.)                                                                                ::
    ID: 07011307.wav
    Length: 28
** Exterior, approach, stop, skid. (1953 model, 14 h.p.: Citroen)                                                                                :Cars:Citroen:
    ID: 07011306.wav
    Length: 21
** Exterior, approach, stop, switch off. (1953 model, 14 h.p.: Citroen)                                                                                :Cars:Citroen:
    ID: 07011305.wav
    Length: 23
** Exterior, start, depart. (1953 model, 14 h.p.)                                                                                ::
    ID: 07011304.wav
    Length: 30
** Exterior, start several times, tickover, switch off. (1953 model, 14 h.p.: Citroen)                                                                                :Cars:Citroen:
    ID: 07011303.wav
    Length: 80
** Exterior, door closed. (1953 model, 14 h.p.: Citroen)                                                                                :Cars:Citroen:
    ID: 07011302.wav
    Length: 6
** Exterior, door opened. (1953 model, 14 h.p.: Citroen)                                                                                :Cars:Citroen:
    ID: 07011301.wav
    Length: 6
** Two footpumps operated, with pause between each. Footpump 'A' for 43", pause, footpump 'B' for 58". (Car accessory)                                                                                ::
    ID: 07011300.wav
    Length: 109
** Tyre let down slowly.                                                                                ::
    ID: 07011299.wav
    Length: 25
** Tyre let down, fast.                                                                                ::
    ID: 07011298.wav
    Length: 24
** Replacing hub cap.                                                                                ::
    ID: 07011297.wav
    Length: 9
** Replacing wheel and nuts.                                                                                ::
    ID: 07011296.wav
    Length: 80
** Replacing hub cap and four wheel nuts, nuts placed in cap.                                                                                ::
    ID: 07011295.wav
    Length: 45
** Three spanners dropped, six spanners dropped. (Car accessories)                                                                                ::
    ID: 07011294.wav
    Length: 13
** Large spanner dropped twice. (Car accessory)                                                                                ::
    ID: 07011293.wav
    Length: 9
** Three spanners dropped. (Car accessories)                                                                                ::
    ID: 07011292.wav
    Length: 8
** A medium spanner dropped. (Car accessory)                                                                                ::
    ID: 07011291.wav
    Length: 9
** A pair of pliers dropped. (Car accessory)                                                                                ::
    ID: 07011290.wav
    Length: 8
** A small spanner dropped. (Car accessory)                                                                                ::
    ID: 07011289.wav
    Length: 8
** Two doors opened, three second pause, closed.                                                                                ::
    ID: 07011288.wav
    Length: 10
** Door opened, three second pause, closed. (Heavy car door)                                                                                ::
    ID: 07011287.wav
    Length: 10
** Car door opened, three second pause, closed. (Light car door)                                                                                ::
    ID: 07011286.wav
    Length: 8
** A windscreen wiper operating.                                                                                ::
    ID: 07011285.wav
    Length: 142
** A heater blower operating.                                                                                ::
    ID: 07011284.wav
    Length: 41
** Flasher unit operating.                                                                                ::
    ID: 07011283.wav
    Length: 27
** Indicator operating.                                                                                ::
    ID: 07011282.wav
    Length: 20
** Sliding window closed, opened and closed twice. (Three second pauses between)                                                                                ::
    ID: 07011281.wav
    Length: 20
** Bonnet opened, three second pause, closed.                                                                                ::
    ID: 07011280.wav
    Length: 11
** Bonnet closed three times, heavy and light.                                                                                ::
    ID: 07011279.wav
    Length: 18
** Bonnet opened three times.                                                                                ::
    ID: 07011278.wav
    Length: 21
** A hand brake operated, slow, fast, faster. (With three second pauses)                                                                                ::
    ID: 07011277.wav
    Length: 14
** Interior, slow down and stop. (1960 Ford Anglia)                                                                                ::
    ID: 07011276.wav
    Length: 17
** Interior, self starter, fast start into constant run, recorded near exhaust. (1960 Ford Anglia)                                                                                ::
    ID: 07011275.wav
    Length: 363
** Interior, slow down, stop, switch off. (1960 Ford Anglia)                                                                                ::
    ID: 07011274.wav
    Length: 12
** Interior, self starter, constant run recorded near exhaust. (1960 Ford Anglia)                                                                                ::
    ID: 07011273.wav
    Length: 363
** Interior, 5 false starts. (1960 Ford Anglia)                                                                                ::
    ID: 07011272.wav
    Length: 16
** Interior, travelling with difficulty over rough ground, switch off. (1960 Ford Anglia)                                                                                ::
    ID: 07011271.wav
    Length: 138
** Interior, self starter, slow run over wet road, switch off. (1960 Ford Anglia)                                                                                ::
    ID: 07011270.wav
    Length: 159
** Interior, traversing flooded unmade road. (1960 Ford Anglia)                                                                                ::
    ID: 07011269.wav
    Length: 188
** Interior, stuck in mud, stalls and restarts several times. (1960 Ford Anglia)                                                                                ::
    ID: 07011268.wav
    Length: 58
** Interior, self starter, stuck in mud, partially frees itself, switch off. (1960 Ford Anglia)                                                                                ::
    ID: 07011267.wav
    Length: 106
** Interior, self starter, stuck in mud, wheel spin, switch off. (Ford Anglia)                                                                                ::
    ID: 07011266.wav
    Length: 102
** Interior, self starter, stuck in mud, switch off. (1960 Ford Anglia)                                                                                ::
    ID: 07011265.wav
    Length: 119
** Exterior, passing at 40 mph. (1960 Ford Anglia)                                                                                ::
    ID: 07011264.wav
    Length: 40
** Exterior, approach and stop with brake squeal. (1960 Ford Anglia)                                                                                ::
    ID: 07011263.wav
    Length: 26
** Exterior, approach and stop. (1960 Ford Anglia)                                                                                ::
    ID: 07011262.wav
    Length: 21
** Exterior, self starter, depart fast. (1960 Ford Anglia)                                                                                ::
    ID: 07011261.wav
    Length: 26
** Exterior, self starter, depart at medium speed. (1960 Ford Anglia)                                                                                ::
    ID: 07011260.wav
    Length: 26
** Exterior, self starter, tickover, revving. (1960 Ford Anglia)                                                                                ::
    ID: 07011259.wav
    Length: 51
** Exterior, 7 false starts. (1960 Ford Anglia)                                                                                ::
    ID: 07011258.wav
    Length: 29
** Exterior, 1 door closing. (1960 Ford Anglia)                                                                                ::
    ID: 07011257.wav
    Length: 7
** Exterior, 1 door opening. (1960 Ford Anglia)                                                                                ::
    ID: 07011256.wav
    Length: 8
** Drum rolls. Long roll.                                                                                ::
    ID: 07011255.wav
    Length: 43
** Drum rolls. 2 long rolls. (5 secs between)                                                                                ::
    ID: 07011254.wav
    Length: 29
** Drum rolls. Long rolls on two drums.                                                                                ::
    ID: 07011253.wav
    Length: 56
** Drum rolls. 3 rolls. (3 secs between)                                                                                ::
    ID: 07011252.wav
    Length: 40
** Drum rolls. 3 rolls. (5 secs between)                                                                                ::
    ID: 07011251.wav
    Length: 32
** Drum rolls. Roll.                                                                                 ::
    ID: 07011250.wav
    Length: 88
** Tattoo on drums.                                                                                ::
    ID: 07011249.wav
    Length: 100
** Tattoo on drums.                                                                                ::
    ID: 07011248.wav
    Length: 94
** Tattoo on drums.                                                                                ::
    ID: 07011247.wav
    Length: 103
** March tempo on drum. (120 paces per minute)                                                                                ::
    ID: 07011246.wav
    Length: 99
** March tempo on drum. (120 paces per minute)                                                                                ::
    ID: 07011245.wav
    Length: 121
** March tempo on drum. (120 paces per minute)                                                                                ::
    ID: 07011244.wav
    Length: 109
** Long drum roll and cymbal crash.                                                                                ::
    ID: 07011243.wav
    Length: 16
** March tempo on drum. (120 paces per minute)                                                                                ::
    ID: 07011242.wav
    Length: 99
** March tempo on drum. (120 paces per minute)                                                                                ::
    ID: 07011241.wav
    Length: 131
** March tempo on drum. (120 paces per minute)                                                                                ::
    ID: 07011240.wav
    Length: 75
** A gong roll and cymbal clash.                                                                                ::
    ID: 07011239.wav
    Length: 18
** A gong roll and cymbal clash.                                                                                ::
    ID: 07011238.wav
    Length: 16
** A gong roll and cymbal clash.                                                                                ::
    ID: 07011237.wav
    Length: 21
** 1 stroke on cymbals.                                                                                ::
    ID: 07011236.wav
    Length: 10
** 1 stroke on cymbals.                                                                                ::
    ID: 07011235.wav
    Length: 9
** 3 cymbal taps.                                                                                ::
    ID: 07011234.wav
    Length: 18
** 1 strokes on a medium gong.                                                                                ::
    ID: 07011233.wav
    Length: 19
** 5 strokes on a large gong.                                                                                ::
    ID: 07011232.wav
    Length: 52
** Gong rolls.                                                                                ::
    ID: 07011231.wav
    Length: 23
** Gong rolls.                                                                                ::
    ID: 07011230.wav
    Length: 21
** Gong rolls.                                                                                ::
    ID: 07011229.wav
    Length: 17
** Gong rolls.                                                                                ::
    ID: 07011228.wav
    Length: 20
** Foetal heartbeats as heard from region of umbilical cord. (38 weeks)                                                                                ::
    ID: 07011227.wav
    Length: 72
** Direct contact recording of foetal heartbeats. (38 weeks)                                                                                ::
    ID: 07011226.wav
    Length: 91
** Four week-old baby boy, breastfeeding, with sucking, gurgling noises and hiccoughs. (To be used at low level)                                                                                ::
    ID: 07011225.wav
    Length: 147
** Four week-old baby boy, cries, whimpers, screams, stops.                                                                                ::
    ID: 07011224.wav
    Length: 99
** Baby boy, cries loudly, whimpers, stops. (2 weeks old)                                                                                ::
    ID: 07011223.wav
    Length: 264
** Baby boy, whimpers, sniffles, cries gently, quietens, stops. (2 weeks old)                                                                                ::
    ID: 07011222.wav
    Length: 160
** 5 month old baby girl, contented.                                                                                ::
    ID: 07011221.wav
    Length: 124
** 4 month old baby girl, laughing.                                                                                ::
    ID: 07011220.wav
    Length: 69
** A new-born baby girl, slight ward atmosphere.                                                                                ::
    ID: 07011219.wav
    Length: 179
** 3 month old baby girl, irritable.                                                                                ::
    ID: 07011218.wav
    Length: 97
** A new-born baby girl.                                                                                ::
    ID: 07011217.wav
    Length: 251
** A 2 1/2 year old boy and two girls, aged 2 1/4 and 1 1/2 years old, playing with toys.                                                                                ::
    ID: 07011216.wav
    Length: 389
** A 3 year old boy and 2 year old girl playing 'going shopping'                                                                                ::
    ID: 07011215.wav
    Length: 245
** Two small children playing and laughing, ends with crying.                                                                                ::
    ID: 07011214.wav
    Length: 142
** 14 month old; Playing contentedly (baby boy)                                                                                ::
    ID: 07011213.wav
    Length: 138
** 14 month old; Chatting to himself (baby boy)                                                                                ::
    ID: 07011212.wav
    Length: 116
** 14 month old: crying (baby boy)                                                                                :Babies:14 Month Old:
    ID: 07011211.wav
    Length: 123
** 12 months old; laughing & trying to talk (baby boy)                                                                                ::
    ID: 07011210.wav
    Length: 204
** 9 month old, laughing and squealing. (baby boy)                                                                                ::
    ID: 07011209.wav
    Length: 165
** Cat snoring.                                                                                 ::
    ID: 07011208.wav
    Length: 148
** A cat (outdoor background)                                                                                ::
    ID: 07011207.wav
    Length: 232
** A cat mewing and purring (indoors with background)                                                                                ::
    ID: 07011206.wav
    Length: 222
** A Siamese cat.                                                                                ::
    ID: 07011205.wav
    Length: 83
** A Siamese cat mewing.                                                                                ::
    ID: 07011204.wav
    Length: 283
** Two Siamese cats, one coughing occasionally.                                                                                ::
    ID: 07011203.wav
    Length: 76
** A Siamese cat mewing.                                                                                ::
    ID: 07011202.wav
    Length: 42
** Two cats growling, spitting and howling.                                                                                ::
    ID: 07011201.wav
    Length: 252
** Two cats growling, spitting and howling.                                                                                ::
    ID: 07011200.wav
    Length: 36
** A Siamese cat 'crying'                                                                                ::
    ID: 07011199.wav
    Length: 55
** A Siamese cat 'talking'                                                                                ::
    ID: 07011198.wav
    Length: 109
** A cat eating.                                                                                ::
    ID: 07011197.wav
    Length: 115
** A tom cat miaowing.                                                                                ::
    ID: 07011196.wav
    Length: 126
** A kitten purring.                                                                                ::
    ID: 07011195.wav
    Length: 65
** A kitten.                                                                                ::
    ID: 07011194.wav
    Length: 53
** A cat miaowing and purring.                                                                                ::
    ID: 07011193.wav
    Length: 52
** A cat with kittens.                                                                                ::
    ID: 07011192.wav
    Length: 57
** A cat miaowing.                                                                                ::
    ID: 07011191.wav
    Length: 120
** Exterior, piston-engined aircraft dive and crash.                                                                                ::
    ID: 07011190.wav
    Length: 22
** Exterior, jet aircraft dive and crash.                                                                                ::
    ID: 07011189.wav
    Length: 41
** Interior, jet aircraft in constant flight. (Wind sound only)                                                                                ::
    ID: 07011188.wav
    Length: 306
** Aircraft: Gliders                                                                                :Glider:
    ID: 07011187.wav
    Length: 18
** Glider: Interior: Launch into constant flight.                                                                                 :Aircraft:Gliders:
    ID: 07011186.wav
    Length: 368
** Interior, slow down, stop, switch off. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011185.wav
    Length: 22
** Interior, start, constant run. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011184.wav
    Length: 243
** Exterior, approach and pass. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011183.wav
    Length: 16
** Exterior, approach and stop. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011182.wav
    Length: 23
** Exterior, depart. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011181.wav
    Length: 24
** Exterior, start, revving, tickover, switch off recorded near engine. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011180.wav
    Length: 124
** Exterior, start, revving, tickover, switch off recorded near exhaust. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011179.wav
    Length: 203
** Exterior, door closed. (4.5 litre, 1929 model Bentley)                                                                                ::
    ID: 07011178.wav
    Length: 6
** Exterior, door opened. (4.5 litre, 1929 Bentley)                                                                                ::
    ID: 07011177.wav
    Length: 6
** Interior, stop, Ford Model 'T' (1914)                                                                                ::
    ID: 07011176.wav
    Length: 19
** Interior, start, constant run. Ford Model 'T' (1914)                                                                                ::
    ID: 07011175.wav
    Length: 298
** Interior, two false starts. Ford Model 'T' (1914)                                                                                ::
    ID: 07011174.wav
    Length: 11
** Exterior, approach and stop. Ford Model 'T' (1914)                                                                                ::
    ID: 07011173.wav
    Length: 19
** Exterior, start, tickover, depart. Ford Model 'T' (1914)                                                                                ::
    ID: 07011172.wav
    Length: 64
** Exterior, hand cranking five times and backfire, hand cranking four times, fire, tickover, stop. Ford Model 'T' (1914)                                                                                ::
    ID: 07011171.wav
    Length: 51
** Exterior, hand cranking twice and fire, tickover, stop. Ford Model 'T' (1914)                                                                                ::
    ID: 07011170.wav
    Length: 86
** Exterior, hand cranking. Ford Model 'T' (1914)                                                                                ::
    ID: 07011169.wav
    Length: 17
** Exterior, door closed, Ford Model 'T' (1914)                                                                                ::
    ID: 07011168.wav
    Length: 6
** Exterior, door opened, Ford Model 'T'. (1914)                                                                                ::
    ID: 07011167.wav
    Length: 6
** Exterior, start, tickover, switch off (exhaust end). (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011166.wav
    Length: 116
** Interior, slow down, brake squeal & stop, revving. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011165.wav
    Length: 19
** Interior, start, continuous running with gear changes. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011164.wav
    Length: 242
** Interior; slow down and stop (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose)                                                                                ::
    ID: 07011163.wav
    Length: 21
** Interior, start, running in traffic with several stops (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011162.wav
    Length: 350
** Exterior, cranking, carburetter sucking, backfire. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011161.wav
    Length: 44
** Exterior, approach & pass. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011160.wav
    Length: 18
** Exterior, reverse to mic, brake squeal, tickover, switch off. (11.9 hp side valcve Hotchkiss engine, 1922 Morris                                                                                 ::
    ID: 07011159.wav
    Length: 42
** Exterior, approach, pass to mid-distance, stop with brake squeal. (11.9 hp sioevalve Hotchkiss engine, 1922 Morris                                                                                 ::
    ID: 07011158.wav
    Length: 18
** Exterior, approach, slow down, drive off. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011157.wav
    Length: 26
** Exterior, approach, revving, switch off. (11.9 hp side valve Hotchkiss engine. 1922 Morris Bullnose.)                                                                                ::
    ID: 07011156.wav
    Length: 19
** Exterior, start & depart fast. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011155.wav
    Length: 20
** Exterior, start & depart. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011154.wav
    Length: 17
** Exterior, start, tickover, switch off. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011153.wav
    Length: 251
** Exterior, door closed. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011152.wav
    Length: 6
** Exterior, door opened. (11.9 hp side valve Hotchkiss engine, 1922 Morris Bullnose.)                                                                                ::
    ID: 07011151.wav
    Length: 6
** A fire hose playing on fire.                                                                                ::
    ID: 07011150.wav
    Length: 180
** Steam pump with start and stop, whistle at 1'15". (1860-1890)                                                                                ::
    ID: 07011149.wav
    Length: 88
** Manual pump with water, operated by 4 men. (1860-1890)                                                                                ::
    ID: 07011148.wav
    Length: 99
** Firefighting Pumps (1860-1890) Manual pump with water, operated by 6 men                                                                                ::
    ID: 07011147.wav
    Length: 124
** Firefighting Pumps (1860-1890) Manual pump (no water) operated by 4 men                                                                                ::
    ID: 07011146.wav
    Length: 127
** Firefighting Pumps (1860-1890) 1860 manual pump, no water, operated by six men.                                                                                 ::
    ID: 07011145.wav
    Length: 118
** Sawing diamond.                                                                                ::
    ID: 07011144.wav
    Length: 54
** Sharpening diamond.                                                                                ::
    ID: 07011143.wav
    Length: 61
** Polishing gem stones on lapidary's wheel.                                                                                ::
    ID: 07011142.wav
    Length: 57
** Chasing gold rings.                                                                                ::
    ID: 07011141.wav
    Length: 55
** Rolling gold into sheets.                                                                                ::
    ID: 07011140.wav
    Length: 58
** Hammering gold leaf.                                                                                ::
    ID: 07011139.wav
    Length: 57
** Pouring fine-grain gold.                                                                                ::
    ID: 07011138.wav
    Length: 60
** Shaking pan to dry fine-grain gold.                                                                                ::
    ID: 07011137.wav
    Length: 42
** Fine-grain gold taken out and rinsed.                                                                                ::
    ID: 07011136.wav
    Length: 66
** Molten gold poured into water.                                                                                ::
    ID: 07011135.wav
    Length: 97
** A hot crucible lifted with block and tackle.                                                                                ::
    ID: 07011134.wav
    Length: 32
** A gold furnace.                                                                                ::
    ID: 07011133.wav
    Length: 64
** Modern cell doors. Cell door closed.                                                                                ::
    ID: 07011132.wav
    Length: 15
** Modern cell doors. Cell door closed.                                                                                ::
    ID: 07011131.wav
    Length: 12
** Modern cell doors. Cell door in passage opened.                                                                                ::
    ID: 07011130.wav
    Length: 11
** Modern cell doors. Cell door in passage closed.                                                                                ::
    ID: 07011129.wav
    Length: 12
** Modern cell doors. Cell door closed.                                                                                ::
    ID: 07011128.wav
    Length: 25
** Modern cell doors. Cell door opened.                                                                                 ::
    ID: 07011127.wav
    Length: 18
** Period cell doors. Cell door opened.                                                                                ::
    ID: 07011126.wav
    Length: 17
** Period cell doors. Cell door closed.                                                                                ::
    ID: 07011125.wav
    Length: 32
** Period cell doors. Cell door closed with keys, bolts, etc.                                                                                ::
    ID: 07011124.wav
    Length: 31
** Period cell doors. Cell door opened with keys, etc.                                                                                ::
    ID: 07011123.wav
    Length: 25
** Period cell doors. Grill door in corridor closed.                                                                                ::
    ID: 07011122.wav
    Length: 9
** Period cell doors. Grill door in corridor opened.                                                                                ::
    ID: 07011121.wav
    Length: 9
** A metal venetian blind opened and closed twice.                                                                                ::
    ID: 07011120.wav
    Length: 22
** Old sash window opened and closed twice.                                                                                ::
    ID: 07011119.wav
    Length: 18
** Old sash window opened and closed.                                                                                ::
    ID: 07011118.wav
    Length: 10
** Old sash window opened and closed twice.                                                                                ::
    ID: 07011117.wav
    Length: 19
** Sliding canvas curtain opened and closed twice.                                                                                ::
    ID: 07011116.wav
    Length: 20
** A large curtain on metal runners.                                                                                ::
    ID: 07011115.wav
    Length: 17
** Curtains being pulled. Wooden rings on wooden rod.                                                                                ::
    ID: 07011114.wav
    Length: 11
** Curtains being pulled. Brass rings on wooden rod.                                                                                ::
    ID: 07011113.wav
    Length: 17
** Curtains being pulled. Small rings on wire.                                                                                ::
    ID: 07011112.wav
    Length: 16
** Curtains being pulled. Large brass rings on brass rod.                                                                                ::
    ID: 07011111.wav
    Length: 19
** Curtains being pulled. Metal runners.                                                                                ::
    ID: 07011110.wav
    Length: 21
** Curtains being pulled. Wooden rings on wooden rod.                                                                                 ::
    ID: 07011109.wav
    Length: 10
** Old-fashioned inner and outer metal lift gates closed. (Reverberation)                                                                                ::
    ID: 07011108.wav
    Length: 8
** Old-fashioned inner and outer metal lift gates opened. (Reverberation)                                                                                ::
    ID: 07011107.wav
    Length: 8
** Inner and outer metal lift gates closed. (Reverberation)                                                                                ::
    ID: 07011106.wav
    Length: 8
** Inner and outer metal lift gates opened. (Reverberation)                                                                                ::
    ID: 07011105.wav
    Length: 9
** Large spring door with squeak, three times.                                                                                ::
    ID: 07011104.wav
    Length: 21
** Continuous sound of a revolving door.                                                                                ::
    ID: 07011103.wav
    Length: 27
** Two small doors together.                                                                                ::
    ID: 07011102.wav
    Length: 7
** A small swing door used normally, pause, violent entry.                                                                                ::
    ID: 07011101.wav
    Length: 16
** Two large swing doors.                                                                                ::
    ID: 07011100.wav
    Length: 9
** A large swing door.                                                                                ::
    ID: 07011099.wav
    Length: 9
** Wooden French windows opened and closed with sound of bolts.                                                                                ::
    ID: 07011098.wav
    Length: 49
** A wooden sash window opened and closed three times.                                                                                ::
    ID: 07011097.wav
    Length: 35
** Wooden barn door. Heavy door closed (interior)                                                                                ::
    ID: 07011096.wav
    Length: 6
** Wooden barn door. Heavy latch.                                                                                ::
    ID: 07011095.wav
    Length: 6
** Wooden barn door. Small sliding door closed.                                                                                ::
    ID: 07011094.wav
    Length: 6
** Wooden barn door. Old door closed. (heavy)                                                                                ::
    ID: 07011093.wav
    Length: 6
** Wooden barn door. Old door closed.                                                                                ::
    ID: 07011092.wav
    Length: 6
** Wooden barn doors. Heavy latch.                                                                                 ::
    ID: 07011091.wav
    Length: 6
** Sliding wooden barn door. Closed indoor.                                                                                ::
    ID: 07011090.wav
    Length: 13
** Sliding wooden barn door. Bolted indoor.                                                                                ::
    ID: 07011089.wav
    Length: 7
** Sliding wooden barn door. Closed indoor.                                                                                ::
    ID: 07011088.wav
    Length: 10
** Sliding wooden barn door. Opened indoor.                                                                                ::
    ID: 07011087.wav
    Length: 8
** Sliding wooden barn door. Closed outdoor.                                                                                ::
    ID: 07011086.wav
    Length: 7
** Sliding wooden barn doors. Opened outdoor.                                                                                ::
    ID: 07011085.wav
    Length: 8
** Person banging on door several times.                                                                                ::
    ID: 07011084.wav
    Length: 48
** Person tapping on door.                                                                                ::
    ID: 07011083.wav
    Length: 20
** A door knocker as heard from indoors.                                                                                ::
    ID: 07011082.wav
    Length: 43
** A door knocker, various rhythms as heard from outside.                                                                                ::
    ID: 07011081.wav
    Length: 25
** A door knocker, various rhythms as heard from outside.                                                                                ::
    ID: 07011080.wav
    Length: 22
** A door lock with key.                                                                                ::
    ID: 07011079.wav
    Length: 26
** Several newspapers pushed through letterbox.                                                                                ::
    ID: 07011078.wav
    Length: 19
** A chain bolt.                                                                                ::
    ID: 07011077.wav
    Length: 15
** A small bolt drawn shut.                                                                                ::
    ID: 07011076.wav
    Length: 12
** A small bolt drawn open.                                                                                ::
    ID: 07011075.wav
    Length: 11
** A large sliding bolt drawn shut several times.                                                                                ::
    ID: 07011074.wav
    Length: 47
** A large sliding bolt drawn open several times.                                                                                ::
    ID: 07011073.wav
    Length: 42
** A roll-top desk opened and closed.                                                                                ::
    ID: 07011072.wav
    Length: 9
** A wooden chest of drawers opened and closed.                                                                                ::
    ID: 07011071.wav
    Length: 16
** A light kitchen drawer opened and closed.                                                                                ::
    ID: 07011070.wav
    Length: 9
** A heavy kitchen drawer opened and closed.                                                                                ::
    ID: 07011069.wav
    Length: 7
** A wardrobe door opened and closed with squeak.                                                                                ::
    ID: 07011068.wav
    Length: 12
** A metal cabinet opened and closed.                                                                                ::
    ID: 07011067.wav
    Length: 7
** A sliding glass door.                                                                                ::
    ID: 07011066.wav
    Length: 7
** A light cupboard door with ball catch.                                                                                ::
    ID: 07011065.wav
    Length: 6
** A heavy cupboard door with ball catch.                                                                                ::
    ID: 07011064.wav
    Length: 7
** A heavy sliding door.                                                                                ::
    ID: 07011063.wav
    Length: 6
** Large cupboard door opened and closed.                                                                                ::
    ID: 07011062.wav
    Length: 7
** Small cupboard opened and closed.                                                                                ::
    ID: 07011061.wav
    Length: 8
** Sliding cupboard door.                                                                                ::
    ID: 07011060.wav
    Length: 7
** Sliding cupboard door.                                                                                ::
    ID: 07011059.wav
    Length: 6
** A refrigerator door opened and closed.                                                                                ::
    ID: 07011058.wav
    Length: 9
** A refrigerator door opened and closed.                                                                                ::
    ID: 07011057.wav
    Length: 8
** A refrigerator door closed.                                                                                ::
    ID: 07011056.wav
    Length: 6
** A refrigerator door opened.                                                                                ::
    ID: 07011055.wav
    Length: 7
** Oven door. Opened and closed.                                                                                ::
    ID: 07011054.wav
    Length: 7
** Oven door. Opened and closed.                                                                                ::
    ID: 07011053.wav
    Length: 6
** Oven door. Closed.                                                                                ::
    ID: 07011052.wav
    Length: 6
** Oven door. Opened and closed.                                                                                ::
    ID: 07011051.wav
    Length: 11
** Oven door. Closed.                                                                                ::
    ID: 07011050.wav
    Length: 6
** Oven door. Opened.                                                                                ::
    ID: 07011049.wav
    Length: 6
** Door closed.                                                                                ::
    ID: 07011048.wav
    Length: 8
** Door unlocked and opened.                                                                                ::
    ID: 07011047.wav
    Length: 8
** Door closed with squeak.                                                                                ::
    ID: 07011046.wav
    Length: 9
** Door closed.                                                                                ::
    ID: 07011045.wav
    Length: 7
** Heavy door closed with echo.                                                                                ::
    ID: 07011044.wav
    Length: 8
** Heavy door closed with squeak and echo.                                                                                ::
    ID: 07011043.wav
    Length: 18
** Very heavy door opened and closed with squeak.                                                                                ::
    ID: 07011042.wav
    Length: 21
** Heavy door closed with squeak.                                                                                ::
    ID: 07011041.wav
    Length: 9
** Heavy sliding door opened and closed.                                                                                ::
    ID: 07011040.wav
    Length: 8
** Heavy sliding door opened and closed.                                                                                ::
    ID: 07011039.wav
    Length: 14
** Heavy sliding door opened.                                                                                ::
    ID: 07011038.wav
    Length: 7
** Heavy sliding door opened and closed.                                                                                ::
    ID: 07011037.wav
    Length: 14
** A latched church door opened and closed.                                                                                ::
    ID: 07011036.wav
    Length: 7
** A stable door closed.                                                                                ::
    ID: 07011035.wav
    Length: 6
** A latched stable door opened.                                                                                ::
    ID: 07011034.wav
    Length: 8
** A stable door closed.                                                                                ::
    ID: 07011033.wav
    Length: 6
** A stable door closed.                                                                                ::
    ID: 07011032.wav
    Length: 6
** A latched stable door opened.                                                                                ::
    ID: 07011031.wav
    Length: 6
** Wooden door opened and closed with echo.                                                                                ::
    ID: 07011030.wav
    Length: 11
** A large wooden door opened and closed with echo.                                                                                ::
    ID: 07011029.wav
    Length: 12
** A large wooden door closed with echo.                                                                                ::
    ID: 07011028.wav
    Length: 6
** Sound of hanger doors being closed.                                                                                ::
    ID: 07011027.wav
    Length: 13
** Sound of hangar doors being closed.                                                                                ::
    ID: 07011026.wav
    Length: 15
** Sound of hangar doors being closed with warning hooter.                                                                                ::
    ID: 07011025.wav
    Length: 58
** Modern interior doors. Fairly heavy close.                                                                                ::
    ID: 07011024.wav
    Length: 6
** Modern interior doors. Open.                                                                                ::
    ID: 07011023.wav
    Length: 6
** Modern interior doors. Close.                                                                                ::
    ID: 07011022.wav
    Length: 6
** Modern interior doors. Heavy open.                                                                                ::
    ID: 07011021.wav
    Length: 6
** Modern interior doors. Close.                                                                                 ::
    ID: 07011020.wav
    Length: 6
** Modern interior doors. Open gently                                                                                ::
    ID: 07011019.wav
    Length: 6
** Modern interior doors. Heavier close.                                                                                ::
    ID: 07011018.wav
    Length: 6
** Modern interior doors. Open with slight squeak.                                                                                 ::
    ID: 07011017.wav
    Length: 6
** Modern interior doors. Heavy close.                                                                                ::
    ID: 07011016.wav
    Length: 6
** Modern interior doors. Open with squeak.                                                                                ::
    ID: 07011015.wav
    Length: 6
** Modern interior doors. Close.                                                                                 ::
    ID: 07011014.wav
    Length: 6
** Modern interior doors. Open with slight squeak.                                                                                 ::
    ID: 07011013.wav
    Length: 6
** Interior, wooden door closed with light echo.                                                                                ::
    ID: 07011012.wav
    Length: 6
** Interior, wooden door opened with light echo.                                                                                ::
    ID: 07011011.wav
    Length: 6
** Interior, wooden door closed with heavy echo.                                                                                ::
    ID: 07011010.wav
    Length: 6
** Interior, wooden door opened with heavy echo.                                                                                ::
    ID: 07011009.wav
    Length: 6
** Interior, wooden door closed with heavy echo.                                                                                ::
    ID: 07011008.wav
    Length: 6
** Interior, wooden door opened.                                                                                ::
    ID: 07011007.wav
    Length: 6
** Interior, wooden door closed.                                                                                ::
    ID: 07011006.wav
    Length: 6
** Interior, wooden door opened.                                                                                ::
    ID: 07011005.wav
    Length: 7
** Interior, wooden door closed.                                                                                ::
    ID: 07011004.wav
    Length: 6
** Interior, wooden door opened.                                                                                ::
    ID: 07011003.wav
    Length: 6
** Interior, wooden door closed.                                                                                ::
    ID: 07011002.wav
    Length: 6
** Interior, wooden door opened.                                                                                ::
    ID: 07011001.wav
    Length: 6
** Morning atmosphere in a timber yard, work begins with lorries in background, band saws start up, general activity.                                                                                ::
    ID: 07010205.wav
    Length: 390
** A large Circular saw cutting 12-foot planks.                                                                                ::
    ID: 07010204.wav
    Length: 168
** A hooter operating, yard shuts down and ends with sliding doors.                                                                                ::
    ID: 07010203.wav
    Length: 114
** A sawdust extractor starting up in a timber yard                                                                                ::
    ID: 07010202.wav
    Length: 78
** A circular saw operating.                                                                                ::
    ID: 07010201.wav
    Length: 252
** A portable 5-inch circular saw cutting against the grain.                                                                                ::
    ID: 07010200.wav
    Length: 94
** A 14-inch circular saw operating in a timber yard.                                                                                ::
    ID: 07010199.wav
    Length: 217
** A portable 5-inch circular saw cutting with grain.                                                                                ::
    ID: 07010198.wav
    Length: 156
** A planing machine, starts, works, slows down at 2'45", switches off. (In an open air timber yard)                                                                                ::
    ID: 07010197.wav
    Length: 199
** A moulding machine Starts, works, slows down at 2m50s, switches off.(In an open air timber yard)                                                                                ::
    ID: 07010196.wav
    Length: 195
** A large bandsaw operating, starts, cuts, switches off. (In an open-air timber yard, machine slows down at 4'10")                                                                                ::
    ID: 07010195.wav
    Length: 400
** A band saw operating.                                                                                ::
    ID: 07010194.wav
    Length: 213
** A planing machine operating.                                                                                ::
    ID: 07010193.wav
    Length: 175
** Overhead shafting for belt-driven machinery, start, continuous run, stop.                                                                                ::
    ID: 07010192.wav
    Length: 193
** An electric routing machine operating.                                                                                ::
    ID: 07010191.wav
    Length: 205
** A 10" tenon saw in soft wood.                                                                                ::
    ID: 07010190.wav
    Length: 26
** A 10" tenon saw operating across grain of hard wood.                                                                                ::
    ID: 07010189.wav
    Length: 41
** A cross-cut saw operating across grain of hard wood.                                                                                ::
    ID: 07010188.wav
    Length: 84
** A rip saw operating along grain of hard wood.                                                                                ::
    ID: 07010187.wav
    Length: 58
** A steel plane on soft wood.                                                                                ::
    ID: 07010186.wav
    Length: 53
** A steel plane on hard wood.                                                                                ::
    ID: 07010185.wav
    Length: 42
** Vertical paring with chisel on wood.                                                                                ::
    ID: 07010184.wav
    Length: 71
** Jack plane boring hole in 3" soft wood with 1" twist bit in ratchet brace.                                                                                ::
    ID: 07010183.wav
    Length: 50
** A jack plane operating on hard wood.                                                                                ::
    ID: 07010182.wav
    Length: 48
** A jack plane operating on soft wood.                                                                                ::
    ID: 07010181.wav
    Length: 53
** A jack plane operating, knocking apart, sharpening, reassembling and setting.                                                                                ::
    ID: 07010180.wav
    Length: 99
** A sharpening gouge.                                                                                ::
    ID: 07010179.wav
    Length: 26
** Cutting mortice in soft wood with sash mortice chisel.                                                                                ::
    ID: 07010178.wav
    Length: 90
** A flat-faced spokeshave on semi-hard wood.                                                                                ::
    ID: 07010177.wav
    Length: 72
** Sanding on a wood lathe.                                                                                ::
    ID: 07010176.wav
    Length: 105
** Sanding on a wood lathe.                                                                                ::
    ID: 07010175.wav
    Length: 63
** Wood lathes turning soft wood, 2,250 rpm.                                                                                ::
    ID: 07010174.wav
    Length: 200
** Wood lathes turning hard wood, 1,330 rpm.                                                                                ::
    ID: 07010173.wav
    Length: 205
** Rasping wood.                                                                                ::
    ID: 07010172.wav
    Length: 70
** Sound of planing wood.                                                                                ::
    ID: 07010171.wav
    Length: 41
** A ratchet screwdriver operating.                                                                                ::
    ID: 07010170.wav
    Length: 65
** Hand-drilling in wood, countersinking from 43"                                                                                ::
    ID: 07010169.wav
    Length: 86
** Hammering tacks.                                                                                ::
    ID: 07010168.wav
    Length: 40
** Hammering a nail into wood.                                                                                ::
    ID: 07010167.wav
    Length: 61
** Sound of morticing.                                                                                ::
    ID: 07010166.wav
    Length: 74
** Sound of chiselling wood.                                                                                ::
    ID: 07010165.wav
    Length: 74
** A keyhole cutter operating.                                                                                ::
    ID: 07010164.wav
    Length: 54
** A cross-cut saw operating.                                                                                ::
    ID: 07010163.wav
    Length: 64
** A tenon saw operating.                                                                                ::
    ID: 07010162.wav
    Length: 60
** Sawing by hand.                                                                                ::
    ID: 07010161.wav
    Length: 174
** A band saw operating with switch on and off.                                                                                ::
    ID: 07010160.wav
    Length: 192
** General workshop atmosphere.                                                                                ::
    ID: 07010159.wav
    Length: 289
** A router operating with switch on and off.                                                                                ::
    ID: 07010158.wav
    Length: 83
** A spindle mould cutter operating with switch on and off.                                                                                ::
    ID: 07010157.wav
    Length: 91
** A belt sander operating with switch on and off.                                                                                ::
    ID: 07010156.wav
    Length: 103
** A rip saw operating with switch on and off.                                                                                ::
    ID: 07010155.wav
    Length: 137
** A cross-cut saw operating with switch on and off.                                                                                ::
    ID: 07010154.wav
    Length: 99
** A thicknesser plane operating with switch on and off.                                                                                ::
    ID: 07010153.wav
    Length: 151
** An over end plane operating with switch on and off.                                                                                ::
    ID: 07010152.wav
    Length: 96
** 175mm gun fires issue of bearings.                                                                                ::
    ID: 07010151.wav
    Length: 22
** 175mm gun fires, with orders.                                                                                ::
    ID: 07010150.wav
    Length: 8
** 175mm gun fires.                                                                                ::
    ID: 07010149.wav
    Length: 7
** Eight inch gun fires after issue of bearings.                                                                                ::
    ID: 07010148.wav
    Length: 48
** Eight inch gun fires, with orders.                                                                                ::
    ID: 07010147.wav
    Length: 8
** Eight inch gun fires.                                                                                ::
    ID: 07010146.wav
    Length: 8
** Gun engine run to firing position.                                                                                ::
    ID: 07010145.wav
    Length: 42
** GI's unloading 8 inch shells from lorry, down ramp into bunker. (some conversation)                                                                                ::
    ID: 07010144.wav
    Length: 67
** GI's on patrol, burning jungle, occasional helicopter in background.                                                                                ::
    ID: 07010143.wav
    Length: 140
** GI's on patrol in jungle.                                                                                ::
    ID: 07010142.wav
    Length: 138
** Air strike, Hue                                                                                ::
    ID: 07010141.wav
    Length: 240
** Sound of tanks on the move. Cambodia border.                                                                                ::
    ID: 07010140.wav
    Length: 127
** Sound of tanks on the move with automatic rifle fire. Cambodia border.                                                                                ::
    ID: 07010139.wav
    Length: 149
** Street fighting: Hue                                                                                :Street fighting:
    ID: 07010138.wav
    Length: 210
** Naval bombardment of North Vietnam. Heavy barrage.                                                                                 ::
    ID: 07010137.wav
    Length: 165
** Naval bombardment of North Vietnam. Barrage.                                                                                ::
    ID: 07010136.wav
    Length: 156
** Street battle in Saigon. Heavy fire.                                                                                ::
    ID: 07010135.wav
    Length: 137
** Street battle in Saigon. Light and medium fire.                                                                                 ::
    ID: 07010134.wav
    Length: 235
** Automatic rifle firing in bursts.                                                                                ::
    ID: 07010133.wav
    Length: 31
** Automatic rifle firing in bursts.                                                                                ::
    ID: 07010132.wav
    Length: 42
** Automatic rifle firing in bursts.                                                                                ::
    ID: 07010131.wav
    Length: 53
** Automatic rifle, single burst.                                                                                ::
    ID: 07010130.wav
    Length: 7
** Light machine gun, several bursts.                                                                                ::
    ID: 07010129.wav
    Length: 28
** Light machine gun, single burst.                                                                                ::
    ID: 07010128.wav
    Length: 8
** Mid-distant shots from several rifles.                                                                                ::
    ID: 07010127.wav
    Length: 28
** Mid-distant shot from single rifle.                                                                                ::
    ID: 07010126.wav
    Length: 6
** Fairly close shots from several rifles.                                                                                ::
    ID: 07010125.wav
    Length: 76
** Fairly close shot from single rifle.                                                                                ::
    ID: 07010124.wav
    Length: 6
** Close shots from several rifles.                                                                                ::
    ID: 07010123.wav
    Length: 42
** Close shot from single rifle.                                                                                ::
    ID: 07010122.wav
    Length: 6
** Lifeboat. From slipway, boat hauled up slipway. (Twin diesel engines)                                                                                ::
    ID: 07010121.wav
    Length: 242
** Lifeboat. From slipway, fixing shackles prior to hauling boat up slipway, winch engines and general atmosphere. (Twin diesel                                                                                 ::
    ID: 07010120.wav
    Length: 50
** Lifeboat. From slipway, boat launched down slipway with general atmosphere. (Twin diesel engines)                                                                                ::
    ID: 07010119.wav
    Length: 86
** Lifeboat. On board, boat hauled up slipway, sound of winch engine, some orders. (Twin diesel engines)                                                                                ::
    ID: 07010118.wav
    Length: 209
** Lifeboat. On board, tickover, manoeuvring into slipway position with some voices. (Twin diesel engines)                                                                                ::
    ID: 07010117.wav
    Length: 137
** Lifeboat. On board, constant run into neutral prior to hauling up slipway. (Twin diesel engines)                                                                                ::
    ID: 07010116.wav
    Length: 24
** Lifeboat. On board, start engines, into constant run. (Twin diesel engines)                                                                                ::
    ID: 07010115.wav
    Length: 245
** Lifeboat. On board, constant run, stop engines. (Twin diesel engines)                                                                                ::
    ID: 07010114.wav
    Length: 50
** Lifeboat. On board, shackles released, boat descends slipway into water, constant run. (Twin diesel engines)                                                                                ::
    ID: 07010113.wav
    Length: 313
** Lifeboat. On board, crew boarding with orders, engines started. (Twin diesel (Twin diesel engines)                                                                                ::
    ID: 07010112.wav
    Length: 64
** 16 foot, 40 h.p. engine - passing at speed. (Exterior)                                                                                ::
    ID: 07010111.wav
    Length: 30
** 16 foot, 40 h.p. engine - departing. (Exterior)                                                                                ::
    ID: 07010110.wav
    Length: 35
** 16 foot, 40 h.p. engine - tickover.                                                                                ::
    ID: 07010109.wav
    Length: 123
** 16 foot, 40 h.p. engine - pull up to stop. (Forward position)                                                                                ::
    ID: 07010108.wav
    Length: 36
** 16 foot, 40 h.p. engine, constant run with bow wave. (Forward position)                                                                                ::
    ID: 07010107.wav
    Length: 399
** 16 foot, 40 h.p. engine - passing.                                                                                ::
    ID: 07010106.wav
    Length: 46
** 16 foot, 40 h.p. engine - departing. (Exterior)                                                                                ::
    ID: 07010105.wav
    Length: 38
** 16 foot, 40 h.p. engine - tickover.                                                                                ::
    ID: 07010104.wav
    Length: 184
** 16 foot, 40 h.p. engine - pull up to stop. (Exterior or interior)                                                                                ::
    ID: 07010103.wav
    Length: 40
** 16 foot, 40 h.p. engine - constant run.                                                                                ::
    ID: 07010102.wav
    Length: 396
** Departing. (Stern of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010101.wav
    Length: 39
** Start up, revving, manoeuvring. (Stern of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010100.wav
    Length: 64
** Tickover. (Stern of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010099.wav
    Length: 159
** Slow down, stop. (Stern of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010098.wav
    Length: 46
** Start up, into constant run, slow down, stop. (Stern of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010097.wav
    Length: 394
** Start up, depart. (Exterior recording of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010096.wav
    Length: 40
** Approach and stop. (Exterior recording of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010095.wav
    Length: 46
** Constant run. (In cockpit of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010094.wav
    Length: 63
** Tickover. (In cockpit of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010093.wav
    Length: 180
** Slow down, stop, switch off. (In cockpit of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010092.wav
    Length: 22
** Start up, into constant run. (In cockpit of 19 foot motor boat, 12 h.p. petrol engine)                                                                                ::
    ID: 07010091.wav
    Length: 392
** Boat 2 1/4 h.p. engine, stop.                                                                                ::
    ID: 07010090.wav
    Length: 12
** Boat 2 1/4 h.p. engine, start, constant run.                                                                                ::
    ID: 07010089.wav
    Length: 308
** Boat.2 1/4 h.p. engine, false start.                                                                                ::
    ID: 07010088.wav
    Length: 13
** Boat. Stop. (7 h.p. twin-cylinder diesel engine)                                                                                ::
    ID: 07010087.wav
    Length: 12
** Boat. Slow down to tickover. (7 h.p. twin-cylinder diesel engine)                                                                                ::
    ID: 07010086.wav
    Length: 30
** Boat. Continuous run. (7 h.p. twin-cylinder diesel engine)                                                                                ::
    ID: 07010085.wav
    Length: 213
** Boat. Tickover. (7 h.p. twin-cylinder diesel engine)                                                                                ::
    ID: 07010084.wav
    Length: 123
** Boat. Start, tickover. (7 h.p. twin-cylinder diesel engine)                                                                                ::
    ID: 07010083.wav
    Length: 10
** Boat 4 h.p. engine, stop.                                                                                ::
    ID: 07010082.wav
    Length: 9
** Boat 4 h.p. engine, start, constant run against tide.                                                                                ::
    ID: 07010081.wav
    Length: 271
** Boat 4 h.p. engine, false start.                                                                                ::
    ID: 07010080.wav
    Length: 6
** Boat 4 h.p. engine, false start.                                                                                ::
    ID: 07010079.wav
    Length: 6
** Boat 4 h.p. engine, stop.                                                                                ::
    ID: 07010078.wav
    Length: 9
** Boat 4 h.p. engine, continuous run.                                                                                ::
    ID: 07010077.wav
    Length: 324
** Boat 4 h.p. engine, start.                                                                                :Boats:Outboard:
    ID: 07010076.wav
    Length: 10
** Boat 4 h.p. engine, false start.                                                                                ::
    ID: 07010075.wav
    Length: 13
** Motor launch. Starts, cruise with wash, stops. (On deck)                                                                                ::
    ID: 07010074.wav
    Length: 363
** Motor launch. Starts, reverses, high speed runs with wash, stops. (In cabin)                                                                                ::
    ID: 07010073.wav
    Length: 239
** Motor launch. Starts, reversing and manoeuvring with wash, stops. (On deck)                                                                                ::
    ID: 07010072.wav
    Length: 98
** Motor launch. Starts, constant run with wash, stops. (On deck)                                                                                ::
    ID: 07010071.wav
    Length: 368
** Motor launch. Start, fast run with wash, stops. (On deck)                                                                                ::
    ID: 07010070.wav
    Length: 132
** Motor launch. Starts, slow run with wash, stops. (On deck)                                                                                ::
    ID: 07010069.wav
    Length: 64
** Motor launch. Starts, tickover, stops with wash. (On deck)                                                                                 ::
    ID: 07010068.wav
    Length: 136
** Factory. Mixed staff clocking off in main hall.                                                                                ::
    ID: 07010067.wav
    Length: 421
** Factory. Staff descending stairs, busy atmosphere.                                                                                ::
    ID: 07010066.wav
    Length: 125
** Factory. 15 people, mostly female, general noise prior to clocking off.                                                                                ::
    ID: 07010065.wav
    Length: 258
** Exterior, 30 children playing in a field with birds and traffic.                                                                                ::
    ID: 07010064.wav
    Length: 421
** Exterior, 6 children playing in a London street, distant traffic and birds.                                                                                ::
    ID: 07010063.wav
    Length: 398
** Three people in a hall with speech and chatter, busy. Slight traffic.                                                                                ::
    ID: 07010062.wav
    Length: 351
** Three people in a hall with speech and chatter, fairly quiet with no traffic.                                                                                 ::
    ID: 07010061.wav
    Length: 337
** 700 people in a large hall. (Recorded in House of Lords during the opening of Parliament)                                                                                ::
    ID: 07010060.wav
    Length: 392
** Three people in a hall with chatter & clatter, traffic in background.                                                                                ::
    ID: 07010059.wav
    Length: 370
** Moving cases and objects in a warehouse with distant conversation and occasional whistling.                                                                                ::
    ID: 07010058.wav
    Length: 396
** Moving cases in a warehouse, fairly noisy without speech.                                                                                ::
    ID: 07010057.wav
    Length: 396
** Atmosphere in a club boatyard with general movement and some distinct speech.                                                                                ::
    ID: 07010056.wav
    Length: 393
** General background of men mixing and laying ballast with distant conversation.                                                                                ::
    ID: 07010055.wav
    Length: 400
** Interior, slow down, stop, switch off. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010054.wav
    Length: 35
** Interior, self starter, into constant run in traffic with intermediate starts & stops. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010053.wav
    Length: 344
** Interior, slow down, stop, switch off. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010052.wav
    Length: 30
** Interior, self starter, manoeuvring with tickover, into constant run. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010051.wav
    Length: 347
** Exterior, self starter, 3-point turn, departs. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010050.wav
    Length: 45
** Exterior, approach, skid to stop, tickover, depart. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010049.wav
    Length: 41
** Exterior, approach, stop, tickover, depart. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010048.wav
    Length: 54
** Exterior, fast pass. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010047.wav
    Length: 38
** Exterior, 40" passing at medium speed. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010046.wav
    Length: 33
** Exterior, passing slowly. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010045.wav
    Length: 46
** Exterior, approach, skid to stop, engine cuts out. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010044.wav
    Length: 17
** Exterior, approach, skid to stop, tickover, switch off. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010043.wav
    Length: 24
** Exterior, approach, stop, tickover, switch off. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010042.wav
    Length: 35
** Exterior, self starter, departs. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010041.wav
    Length: 36
** Exterior, self starter, slight skid, departs. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010040.wav
    Length: 28
** Exterior, self starter, (twice), departs. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010039.wav
    Length: 36
** Exterior, self starter, tickover, switch off. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010038.wav
    Length: 142
** Exterior, self starter, revving, switch off. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010037.wav
    Length: 86
** Exterior, self starter, revving until 50", tickover, switch off. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010036.wav
    Length: 116
** Exterior, 2 doors opened & closed. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010035.wav
    Length: 14
** Exterior, 1 door opened & closed. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010034.wav
    Length: 9
** Exterior, 2-tone into single-tone horn. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010033.wav
    Length: 39
** Exterior, spring-loaded petrol filler cap opened & closed. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010032.wav
    Length: 70
** Exterior, bonnet opened & closed. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010031.wav
    Length: 15
** Exterior, luggage boot opened & closed. (TR6 Sports Car, 1971 model)                                                                                ::
    ID: 07010030.wav
    Length: 13
** Interior, slow down, stop, switch off. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010029.wav
    Length: 16
** Interior, false start, self starter into constant run, fast for 1'46" then slower in traffic. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010028.wav
    Length: 316
** Interior, self starter, travelling over rough unmade road. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010027.wav
    Length: 222
** Exterior, approach, slow down, depart fast. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010026.wav
    Length: 29
** Exterior, approach & pass at speed with horn. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010025.wav
    Length: 22
** Exterior, approach & pass at speed. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010024.wav
    Length: 28
** Exterior, approach & pass at speed. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010023.wav
    Length: 21
** Exterior, approach, stop, reverse, depart fast. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010022.wav
    Length: 33
** Exterior, approach, stop, revving, switch off. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010021.wav
    Length: 21
** Exterior, approach, stop, revving, switch off. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010020.wav
    Length: 28
** Exterior, start, revving, fast depart. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010019.wav
    Length: 19
** Exterior, start, revving, depart at medium speed. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010018.wav
    Length: 22
** Exterior, false start, self starter, revving, depart fast, with wheel screech (TR3 Sports Car. 1957 model)                                                                                ::
    ID: 07010017.wav
    Length: 27
** Exterior, self starter, tickover, switch off. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010016.wav
    Length: 246
** Exterior, door closed. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010015.wav
    Length: 6
** Exterior, door opened. (TR3 Sports Car, 1957 model)                                                                                ::
    ID: 07010014.wav
    Length: 6
** Bow wave (Recorded at front of moving tug)                                                                                ::
    ID: 07010013.wav
    Length: 370
** Tug Whistles                                                                                 ::
    ID: 07010012.wav
    Length: 12
** Tug Whistles                                                                                 ::
    ID: 07010011.wav
    Length: 11
** Tug Whistles                                                                                 ::
    ID: 07010010.wav
    Length: 8
** Tug Whistles - Going astern (3 blasts)                                                                                ::
    ID: 07010009.wav
    Length: 12
** Tug Whistles - Turning to starboard (2 blasts)                                                                                ::
    ID: 07010008.wav
    Length: 9
** Tug Whistles - turning to port (one blast)                                                                                ::
    ID: 07010007.wav
    Length: 6
** Tug. 180 h.p. engines, constant run.                                                                                ::
    ID: 07010006.wav
    Length: 357
** Tug. 180 h.p. engines, starts, tickover, runs, stops.                                                                                ::
    ID: 07010005.wav
    Length: 297
** Tug. 180 h.p. engines, starts, tickover, revving, stops.                                                                                ::
    ID: 07010004.wav
    Length: 59
** Tug. 450 h.p. engines, constant run.                                                                                ::
    ID: 07010003.wav
    Length: 368
** Tug. 450 h.p. engines starting and running. (Some manoeuvring)                                                                                ::
    ID: 07010002.wav
    Length: 229
** Tug. 450 h.p. engines running and stopping.                                                                                ::
    ID: 07010001.wav
    Length: 122
** Calcutta, gardens in central Calcutta, general atmosphere.                                                                                ::
    ID: 07009159.wav
    Length: 156
** Ajmer main street. (Recorded at noon.)                                                                                ::
    ID: 07009158.wav
    Length: 105
** Pushkar skyline. (Recorded at Dawn.)                                                                                ::
    ID: 07009157.wav
    Length: 113
** Nomadic encampment with camels. (Recorded in India, exact location unknown.)                                                                                ::
    ID: 07009156.wav
    Length: 120
** Pushkar bazaar, general atmosphere.                                                                                 ::
    ID: 07009155.wav
    Length: 78
** Pushkar market place, general atmosphere. (Recorded at noon.)                                                                                ::
    ID: 07009154.wav
    Length: 107
** Madurai Grand Temple, interior. general atmosphere.                                                                                ::
    ID: 07009153.wav
    Length: 91
** Madurai city skyline.                                                                                ::
    ID: 07009152.wav
    Length: 279
** Kerala State Game Reserve, general atmosphere. (Recorded at night-time.)                                                                                ::
    ID: 07009151.wav
    Length: 158
** Nagpur Junction railway station, general atmosphere. (Recorded in the evening.)                                                                                ::
    ID: 07009150.wav
    Length: 206
** Marine Bugle Call, 'Officers dinner call'.                                                                                ::
    ID: 07009149.wav
    Length: 20
** Marine Bugle Call, 'Officers dress for dinner'.                                                                                ::
    ID: 07009148.wav
    Length: 8
** Marine Bugle Call, 'Divisions'.                                                                                ::
    ID: 07009147.wav
    Length: 15
** Marine Bugle Call, 'Last post'.                                                                                ::
    ID: 07009146.wav
    Length: 66
** Marine Bugle Call, 'Alert', 'General salute', 'Carry on'.                                                                                ::
    ID: 07009145.wav
    Length: 24
** Marine Bugle Call, 'Alert', 'Sunset', 'Carry on'.                                                                                ::
    ID: 07009144.wav
    Length: 52
** Marine Bugle Call, 'Reveille'.                                                                                ::
    ID: 07009143.wav
    Length: 30
** Marine Bugle Call, 'Flying stations'.                                                                                ::
    ID: 07009142.wav
    Length: 10
** Marine Bugle Call, 'Alarm to arms'.                                                                                ::
    ID: 07009141.wav
    Length: 9
** Marine Bugle Call, 'Action'.                                                                                ::
    ID: 07009140.wav
    Length: 10
** Marine Bugle Call, 'Carry on'.                                                                                ::
    ID: 07009139.wav
    Length: 6
** Marine Bugle Call, 'Alert'.                                                                                ::
    ID: 07009138.wav
    Length: 7
** Schoolchildren in classroom, noisy infants in class.                                                                                ::
    ID: 07009137.wav
    Length: 390
** Schoolchildren playing in urban Infant School playground.                                                                                 ::
    ID: 07009136.wav
    Length: 210
** Schoolchildren in Junior School gymnasium.                                                                                ::
    ID: 07009135.wav
    Length: 210
** Schoolchildren playing in urban Junior School playground. (Mid distance with footsteps)                                                                                ::
    ID: 07009134.wav
    Length: 390
** Schoolchildren in classroom, 5 to 7 year-olds in class.                                                                                ::
    ID: 07009133.wav
    Length: 390
** Schoolchildren in classroom, subdued classroom atmosphere with 10 to 13 year old pupils reading. (Recorded in London, 1980.)                                                                                ::
    ID: 07009132.wav
    Length: 120
** School bell rings, mixed 10 to 13 year old schoolchildren leave classroom. (Recorded in London, 1980.)                                                                                ::
    ID: 07009131.wav
    Length: 50
** Mixed 10 to 13 year old schoolchildren gradually settling down in classroom. (Recorded in London, 1980.)                                                                                ::
    ID: 07009130.wav
    Length: 150
** Mixed 10 to 13 year old schoolchildren entering classroom. (Recorded in London, 1980.)                                                                                ::
    ID: 07009129.wav
    Length: 90
** Electric school bell rings. (Recorded in London, 1980.)                                                                                ::
    ID: 07009128.wav
    Length: 10
** Schoolchildren in classroom, mixed 10 to 13 year old pupils, groans of incredulity. (Recorded in London, 1980.)                                                                                 ::
    ID: 07009127.wav
    Length: 12
** Schoolchildren in classroom, mixed 10 to 13 year old pupils, groans of disappointment. (Recorded in London, 1980.)                                                                                ::
    ID: 07009126.wav
    Length: 18
** Schoolchildren in classroom, mixed 10 to 13 year old pupils giggling. (Recorded in London, 1980.)                                                                                ::
    ID: 07009125.wav
    Length: 4
** Schoolchildren in classroom, mixed 10 to 13 year old pupils laughing. (Recorded in London, 1980.)                                                                                ::
    ID: 07009124.wav
    Length: 3
** Schoolchildren in classroom, mixed 10 to 13 year old pupils laughing. (Recorded in London, 1980)                                                                                ::
    ID: 07009123.wav
    Length: 7
** Schoolchildren, exterior, singing 'Looby Loo'.                                                                                ::
    ID: 07009122.wav
    Length: 84
** Schoolchildren, interior, singing 'Looby Loo'.                                                                                ::
    ID: 07009121.wav
    Length: 87
** Schoolchildren, exterior, singing 'London's Burning'.                                                                                ::
    ID: 07009120.wav
    Length: 46
** Schoolchildren, interior, singing 'London's Burning'.                                                                                ::
    ID: 07009119.wav
    Length: 47
** Schoolchildren, exterior, singing 'London Bridge'.                                                                                ::
    ID: 07009118.wav
    Length: 83
** Schoolchildren, interior, singing 'London Bridge'.                                                                                ::
    ID: 07009117.wav
    Length: 83
** School Playground, 5-10 year old pupils in urban playground with shouts, footsteps, swings & distant traffic.                                                                                ::
    ID: 07009116.wav
    Length: 423
** French Schoolchildren, mixed group playing in playground. (Mid-distant recording, Paris.)                                                                                ::
    ID: 07009115.wav
    Length: 158
** Group of mixed children singing 'Cat's got the Measles'                                                                                ::
    ID: 07009114.wav
    Length: 27
** Group of mixed children singing 'Farmer's in his den'                                                                                ::
    ID: 07009113.wav
    Length: 77
** Group of mixed children singing 'Poor Jenny is a-weeping'                                                                                ::
    ID: 07009112.wav
    Length: 28
** School Playground, mixed group of mixed 5 to 11 year old pupils in enclosed playground. (Close perspective.)                                                                                ::
    ID: 07009111.wav
    Length: 394
** Girls' Secondary School playground, atmosphere of girls playing recorded between buildings. (Occasional distinct speech and scream.)                                                                                ::
    ID: 07009110.wav
    Length: 245
** Girls' Secondary School playing field, with shouting, laughter & footsteps. (Occasional distinct speech.)                                                                                ::
    ID: 07009109.wav
    Length: 127
** Girls' Secondary School dining room, busy lunchtime atmosphere with speech & crockery clatter.                                                                                ::
    ID: 07009108.wav
    Length: 244
** Girls' Secondary School classroom, speech and clatter prior to lesson, ends with 'shshsh'. (Occasional desk scraped on floor.)                                                                                ::
    ID: 07009107.wav
    Length: 122
** Girls' Secondary School hall, conversation quietens.                                                                                ::
    ID: 07009106.wav
    Length: 15
** Girls' Secondary School hall, noisy conversation.                                                                                ::
    ID: 07009105.wav
    Length: 306
** Girls' Secondary School corridor, footsteps and voices during break.                                                                                ::
    ID: 07009104.wav
    Length: 186
** Girls' Secondary School classroom, loud chatter at end of lesson.                                                                                ::
    ID: 07009103.wav
    Length: 180
** Three to six year old children playing outdoors.                                                                                ::
    ID: 07009102.wav
    Length: 368
** Three to six year old children playing indoors.                                                                                ::
    ID: 07009101.wav
    Length: 382
** Boys' Comprehensive School classroom, junior boys in noisy classroom.                                                                                ::
    ID: 07009100.wav
    Length: 57
** Boys' Comprehensive School classroom, boys entering classroom.                                                                                ::
    ID: 07009099.wav
    Length: 28
** Boys' Comprehensive School classroom, boys leaving classroom.                                                                                ::
    ID: 07009098.wav
    Length: 17
** Boys' Comprehensive School classroom, abusive remarks thrown at teacher.                                                                                ::
    ID: 07009097.wav
    Length: 24
** Boys' Comprehensive School classroom, argumentative atmosphere.                                                                                ::
    ID: 07009096.wav
    Length: 62
** Boys' Comprehensive School classroom, sudden change from rowdy to silent atmosphere.                                                                                ::
    ID: 07009095.wav
    Length: 13
** Boys' Comprehensive School classroom, boys not under control.                                                                                ::
    ID: 07009094.wav
    Length: 196
** Boys' Comprehensive School classroom, boys supposed to be working.                                                                                ::
    ID: 07009093.wav
    Length: 198
** Boys' Secondary School, boys playing during break time.                                                                                ::
    ID: 07009092.wav
    Length: 185
** Boys' Secondary School, boys playing in outdoor swimming pool with younger mixed children also audible.                                                                                ::
    ID: 07009091.wav
    Length: 192
** Boys' Secondary School, Grace said & atmosphere during meal.                                                                                ::
    ID: 07009090.wav
    Length: 220
** Boys' Secondary School, boys enter dining hall & atmosphere before start of meal.                                                                                ::
    ID: 07009089.wav
    Length: 207
** Schoolchildren playing in school playground in the South of England.                                                                                ::
    ID: 07009088.wav
    Length: 517
** Schoolchildren playing in a school playground in the Midlands.                                                                                ::
    ID: 07009087.wav
    Length: 412
** Boeing 707, interior, constant flight, starts to descend at 4'30". (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009086.wav
    Length: 377
** Boeing 707, interior, taxi to take-off, climb. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009085.wav
    Length: 393
** Boeing 707, interior, taxi to runway for take-off. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009084.wav
    Length: 392
** Boeing 707, interior, start and run up engines. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009083.wav
    Length: 392
** Boeing 707, interior, descent, lands at 3'50", taxis. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009082.wav
    Length: 341
** Boeing 707, exterior, passing overhead, with Vickers VC10 landing. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009081.wav
    Length: 55
** Boeing 707, exterior, passing overhead. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009080.wav
    Length: 110
** Boeing 707, exterior, passing overhead. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009079.wav
    Length: 99
** Boeing 707, exterior, landing. (Long-range airliner, 4 jet engines.) (Recorded 1958.)                                                                                ::
    ID: 07009078.wav
    Length: 62
** Boeing 707, exterior, landing. (Long-range airliner, 4 jet engines.) (Recorded 1970.)                                                                                ::
    ID: 07009077.wav
    Length: 65
** Boeing 707, exterior, landing. (Long-range airliner, 4 jet engines.) (Recorded 1970.)                                                                                ::
    ID: 07009076.wav
    Length: 79
** Boeing 707, exterior, landing. (Long-range airliner, 4 jet engines.) (Recorded 1970.)                                                                                ::
    ID: 07009075.wav
    Length: 61
** Boeing 707, exterior, take off with skylarks at end. (Long-range airliner, 4 jet engines.) (Recorded 1958.)                                                                                ::
    ID: 07009074.wav
    Length: 111
** Boeing 707, exterior, take off. (Long-range airliner, 4 jet engines.) (Recorded 1958.)                                                                                ::
    ID: 07009073.wav
    Length: 102
** Boeing 707, exterior, take off. (Long-range airliner, 4 jet engines.) (Recorded 1970.)                                                                                ::
    ID: 07009072.wav
    Length: 113
** Boeing 747 'Jumbo Jet', interior, descent, touch down at 5'20", taxi. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009071.wav
    Length: 393
** Boeing 747 'Jumbo Jet', interior, flaps up, quiet constant flight. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009070.wav
    Length: 399
** Boeing 747 'Jumbo Jet', interior, short taxi and take-off, undercarriage raised at 1'45", climb into constant flight at 5000 feet. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009069.wav
    Length: 384
** Boeing 747 'Jumbo Jet', interior, taxi to take-off, undercarriage raised at 2'50", indicator board gong, aircraft climbs. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009068.wav
    Length: 412
** Boeing 747 'Jumbo Jet', exterior, passing overhead. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009067.wav
    Length: 91
** Boeing 747 'Jumbo Jet', exterior, passing overhead. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009066.wav
    Length: 104
** Boeing 747 'Jumbo Jet', exterior, landing. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009065.wav
    Length: 102
** Boeing 747 'Jumbo Jet', exterior, landing. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009064.wav
    Length: 69
** Boeing 747 'Jumbo Jet', exterior, taxi past and take off. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009063.wav
    Length: 171
** Boeing 747 'Jumbo Jet', exterior, taxi off. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009062.wav
    Length: 113
** Boeing 747 'Jumbo Jet', exterior, taxi past. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009061.wav
    Length: 91
** BAC 1-11, exterior, passing overhead at 1000 feet. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009060.wav
    Length: 43
** BAC 1-11, exterior, passing overhead at 300 feet. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009059.wav
    Length: 51
** BAC 1-11, exterior, taxi to foreground. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009058.wav
    Length: 65
** BAC 1-11, exterior, landing. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009057.wav
    Length: 62
** BAC 1-11, exterior, take off. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009056.wav
    Length: 81
** BAC 1-11, exterior, taxi past. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009055.wav
    Length: 72
** BAC 1-11, exterior, taxi away. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009054.wav
    Length: 38
** BAC 1-11, exterior, start up main engines. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009053.wav
    Length: 154
** BAC 1-11, exterior, start and run up auxiliary power unit. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009052.wav
    Length: 139
** BAC 1-11, interior, switch off, sounds of movement from passengers. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009051.wav
    Length: 93
** BAC 1-11, interior, landing and taxi-ing. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009050.wav
    Length: 154
** BAC 1-11, interior, descent. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009049.wav
    Length: 127
** BAC 1-11, interior, constant flight. (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009048.wav
    Length: 406
** BAC 1-11, interior, constant flight. (Recorded in pilots' cabin.) (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009047.wav
    Length: 402
** BAC 1-11, interior, take off into level flight. (Recorded in pilots' cabin.) (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009046.wav
    Length: 135
** BAC 1-11, interior, taxi-ing. (Recorded in pilots' cabin.) (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009045.wav
    Length: 104
** BAC 1-11, interior, start and run up engines. (Recorded in pilots' cabin.) (Short-range airliner, 2 jet engines.)                                                                                ::
    ID: 07009044.wav
    Length: 123
** Airport activity with Hawker-Siddeley Tridents. (Exterior, short/medium-range airliners, 3 jet engines.)                                                                                ::
    ID: 07009043.wav
    Length: 152
** Hawker-Siddeley Trident, exterior, landing and taxi to close-up. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009042.wav
    Length: 92
** Hawker-Siddeley Trident, exterior, taxi up and past. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009041.wav
    Length: 60
** Hawker-Siddeley Trident, exterior, landing and taxi to mid-distance. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009040.wav
    Length: 57
** Hawker-Siddeley Trident, exterior, passing overhead. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009039.wav
    Length: 59
** Hawker-Siddeley Trident, exterior, take off. (Short/medium-range airliner, 3 jet engines)                                                                                ::
    ID: 07009038.wav
    Length: 66
** Hawker-Siddeley Trident, exterior, revving for take-off. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009037.wav
    Length: 48
** Hawker-Siddeley Trident, exterior, start and run up engines, taxi. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009036.wav
    Length: 167
** Hawker-Siddeley Trident, interior, high speed constant flight. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009035.wav
    Length: 421
** Hawker-Siddeley Trident, interior, landing, taxi, switch off. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009034.wav
    Length: 184
** Hawker-Siddeley Trident, interior, descent. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009033.wav
    Length: 197
** Hawker-Siddeley Trident, interior, constant flight. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009032.wav
    Length: 420
** Hawker-Siddeley Trident, interior, take off and climb to cruising height. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009031.wav
    Length: 57
** Hawker-Siddeley Trident, interior, start, run up engines, taxi. (Short/medium-range airliner, 3 jet engines.)                                                                                ::
    ID: 07009030.wav
    Length: 227
** De Havilland Comet IV, exterior, taxi past into distance. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009029.wav
    Length: 133
** De Havilland Comet IV, exterior, taxi past. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009028.wav
    Length: 97
** De Havilland Comet IV, exterior, taxi in and switch off. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009027.wav
    Length: 123
** De Havilland Comet IV, exterior, passing overhead. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009026.wav
    Length: 39
** De Havilland Comet IV, exterior, take off. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009025.wav
    Length: 86
** De Havilland Comet IV, exterior, start and run up engines, taxi. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009024.wav
    Length: 154
** De Havilland Comet IV, interior, taxi-ing to stop, switch off. (Medium/long range airliner, 4 jet engines.)                                                                                ::
    ID: 07009023.wav
    Length: 44
** De Havilland Comet IV, interior, landing, reverse engines for breaking, taxi-ing. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009022.wav
    Length: 139
** De Havilland Comet IV, interior, descent. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009021.wav
    Length: 199
** De Havilland Comet IV, interior, take off into constant flight. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009020.wav
    Length: 275
** De Havilland Comet IV, interior, start and run up engines, taxi to take-off point. (Medium/long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009019.wav
    Length: 146
** Vickers VC10, exterior, warm up, taxis away. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009018.wav
    Length: 352
** Vickers VC10, interior, taxis to terminal, slow down, stop, switch off. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009017.wav
    Length: 184
** Vickers VC10, interior, descends, lands and taxis. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009016.wav
    Length: 96
** Vickers VC10, exterior, landing. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009015.wav
    Length: 36
** Vickers VC10, interior, descent. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009014.wav
    Length: 299
** Vickers VC10, interior, constant flight. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009013.wav
    Length: 364
** Vickers VC10, exterior, taxis into mid-distance. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009012.wav
    Length: 211
** Vickers VC10, exterior, landing. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009011.wav
    Length: 71
** Vickers VC10, exterior, taxi into close-up, switch off. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009010.wav
    Length: 100
** Vickers VC10, interior, climb into level flight. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009009.wav
    Length: 243
** Vickers VC10, exterior, passing overhead. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009008.wav
    Length: 53
** Vickers VC10, exterior, take off. (Long range-airliner, 4 jet engines.)                                                                                ::
    ID: 07009007.wav
    Length: 64
** Vickers VC10, exterior, taxis away from position. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009006.wav
    Length: 151
** Vickers VC10, interior, taxis into take off. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009005.wav
    Length: 147
** Vickers VC10, interior, taxis to runway. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009004.wav
    Length: 152
** Vickers VC10, exterior, start up procedure, run up engines. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009003.wav
    Length: 370
** Vickers VC10, interior, commences to taxi. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009002.wav
    Length: 92
** Vickers VC10, interior, start engines, warm up. (Long-range airliner, 4 jet engines.)                                                                                ::
    ID: 07009001.wav
    Length: 233
** Interior, slow down, stop, switch off. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008230.wav
    Length: 30
** Interior, start into constant run. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008229.wav
    Length: 355
** Interior, start into slow run with gear changes. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008228.wav
    Length: 217
** Interior, start, reversing, stop. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008227.wav
    Length: 61
** Interior, start, tickover, switch off. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008226.wav
    Length: 98
** Exterior, three-point turn, depart. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008225.wav
    Length: 60
** Exterior, approach, stop, tickover, depart with brake squeal. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008224.wav
    Length: 54
** Exterior, approach, stop, switch off. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008223.wav
    Length: 22
** Exterior, approach with brake squeal, tickover, switch off. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008222.wav
    Length: 32
** Exterior, passing at 40 m.p.h. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008221.wav
    Length: 22
** Exterior, passing at 30 m.p.h. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008220.wav
    Length: 37
** Exterior, passing at 15 m.p.h. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008219.wav
    Length: 36
** Exterior, start, depart. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008218.wav
    Length: 22
** Exterior, start, depart. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008217.wav
    Length: 32
** Exterior, start, tickover, switch off. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008216.wav
    Length: 109
** Exterior, 2 doors opened and closed. (Badly worn Sunbeam Rapier, 1962 model)                                                                                ::
    ID: 07008215.wav
    Length: 6
** Exterior, door opened and closed. (Badly worn Sunbean Rapier, 1962 model)                                                                                ::
    ID: 07008214.wav
    Length: 6
** Interior, start, running fast in low gears, stop, switch off. (1940 period car)                                                                                ::
    ID: 07008213.wav
    Length: 163
** Interior, start, bad driving and gear changes, stop. (1940 period car)                                                                                ::
    ID: 07008212.wav
    Length: 180
** Interior, start, jerking along badly, stop, switch off. (1940 period car)                                                                                ::
    ID: 07008211.wav
    Length: 132
** Interior, false start, start crawl along with bad gear changes, stop, switch off. (1940 period car)                                                                                ::
    ID: 07008210.wav
    Length: 165
** Exterior, start, revving, stop. (1940 period car)                                                                                ::
    ID: 07008209.wav
    Length: 72
** Exterior, approach and pass. (1940 period car)                                                                                ::
    ID: 07008208.wav
    Length: 25
** Exterior, approach, stop, switch off. (1940 period car)                                                                                ::
    ID: 07008207.wav
    Length: 23
** Exterior, approach, stop, switch off. (1940 period car)                                                                                ::
    ID: 07008206.wav
    Length: 16
** Exterior, start and depart. (1940 period car)                                                                                ::
    ID: 07008205.wav
    Length: 18
** Exterior, start, tickover. (Recorded near exhaust of 1940 period car)                                                                                ::
    ID: 07008204.wav
    Length: 90
** Exterior, start, tickover. (Recorded near engine of 1940 period car)                                                                                ::
    ID: 07008203.wav
    Length: 76
** Exterior, starts, heavy backfiring, stop. (1940 period car)                                                                                ::
    ID: 07008202.wav
    Length: 114
** Exterior, attempted starts, backfiring, stop. (1940 period car)                                                                                ::
    ID: 07008201.wav
    Length: 45
** Exterior, start, running badly, revving, stop. (1940 period car)                                                                                ::
    ID: 07008200.wav
    Length: 46
** Exterior, reluctant start, runs badly. (1940 period car)                                                                                ::
    ID: 07008199.wav
    Length: 18
** Exterior, door closed. (1940 period car)                                                                                ::
    ID: 07008198.wav
    Length: 6
** Exterior, door opened. (1940 period car)                                                                                ::
    ID: 07008197.wav
    Length: 6
** Interior, slow down to stop. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008196.wav
    Length: 20
** Interior, start, constant run. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008195.wav
    Length: 262
** Interior, start, tickover, switch off. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008194.wav
    Length: 39
** Exterior, klaxon sounded twice. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008193.wav
    Length: 7
** Exterior, klaxon sounded once. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008192.wav
    Length: 6
** Exterior, approach and stop with skid, drive away. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008191.wav
    Length: 33
** Exterior, approach to foreground, drive away. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008190.wav
    Length: 30
** Exterior, fast approach and pass with klaxon. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008189.wav
    Length: 17
** Exterior, fast approach and pass. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008188.wav
    Length: 22
** Exterior, approach, medium speed pass. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008187.wav
    Length: 18
** Exterior, start, reverse, switch off. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008186.wav
    Length: 45
** Exterior, approach, stop, tickover, switch off. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008185.wav
    Length: 21
** Exterior, approach, stop, tickover, switch off. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008184.wav
    Length: 25
** Exterior, start, fast depart. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008183.wav
    Length: 26
** Exterior, start, depart at medium speed. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008182.wav
    Length: 41
** Exterior, start, revving, switch off. (Recorded near exhaust of Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008181.wav
    Length: 89
** Exterior, start, revving, switch off. (Recorded near engine of Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008180.wav
    Length: 97
** Exterior, start, tickover. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008179.wav
    Length: 99
** Exterior, two false starts. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008178.wav
    Length: 7
** Exterior, door closed. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008177.wav
    Length: 6
** Exterior, door opened. (Riley 9 h.p. saloon, 1929 model)                                                                                ::
    ID: 07008176.wav
    Length: 6
** Interior, slow to stop, tickover. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008175.wav
    Length: 12
** Interior, start, run in low gear over rough track. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008174.wav
    Length: 348
** Interior, slow down to stop. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008173.wav
    Length: 15
** Interior, start, fast constant run. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008172.wav
    Length: 358
** Interior, runaway car, no engine, skid to stop. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008171.wav
    Length: 43
** Interior, slow down to stop. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008170.wav
    Length: 16
** Interior, start, constant run at medium speed. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008169.wav
    Length: 292
** Interior, slow down to stop. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008168.wav
    Length: 19
** Interior, start, hard-driven hill climb. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008167.wav
    Length: 187
** Exterior, start, reverse to stop. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008166.wav
    Length: 30
** Exterior, approach & pass at speed. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008165.wav
    Length: 15
** Exterior, approach, medium speed pass. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008164.wav
    Length: 21
** Exterior, approach & stop, brake squeal, tickover. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008163.wav
    Length: 12
** Exterior, approach & stop, brake squeal, tickover. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008162.wav
    Length: 18
** Exterior, self-starter, slow depart. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008161.wav
    Length: 22
** Exterior, self-starter, fast depart. (1.5 litre, 1959, worn engine.                                                                                ::
    ID: 07008160.wav
    Length: 20
** Exterior, self-starter, revving, switch off. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008159.wav
    Length: 71
** Exterior, self-starter, revving, tickover. (1.5 litre, 1959, worn engine)                                                                                ::
    ID: 07008158.wav
    Length: 254
** Exterior, 2 doors closed. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008157.wav
    Length: 6
** Exterior, door closed. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008156.wav
    Length: 6
** Exterior, door opened. (1.5 litre, 1959, worn engine, Riley)                                                                                ::
    ID: 07008155.wav
    Length: 6
** Small rowing boat on a lake. Erratic rowing.                                                                                ::
    ID: 07008154.wav
    Length: 350
** Small rowing boat on a lake. Beaching boat on pebbles.                                                                                ::
    ID: 07008153.wav
    Length: 41
** Small rowing boat on a lake. Beaching boat on mud & gravel. (Distant birds)                                                                                ::
    ID: 07008152.wav
    Length: 99
** Small rowing boat on a lake. Boarding & moving gear. (Distant birds)                                                                                ::
    ID: 07008151.wav
    Length: 124
** Small rowing boat on a lake. Boarding. (Distant birds)                                                                                ::
    ID: 07008150.wav
    Length: 44
** First century slave galley, rowing as heard from amidships.                                                                                ::
    ID: 07008149.wav
    Length: 193
** First century slave galley, rowing as heard from aft. (Specially created)                                                                                ::
    ID: 07008148.wav
    Length: 162
** First century slave galley, rowing with start and stop in close perspective. (Specially created)                                                                                ::
    ID: 07008147.wav
    Length: 155
** Sound of rowing with 1 pair of oars. (With squeak)                                                                                ::
    ID: 07008146.wav
    Length: 206
** Sea Scouts whaler, rowing with six pairs of oars, shipping oars at end.                                                                                ::
    ID: 07008145.wav
    Length: 201
** Sea Scouts whaler, fairly fast rowing with 3 pairs of oars.                                                                                ::
    ID: 07008144.wav
    Length: 185
** Sea Scouts whaler, fairly slow muffled rowing with one pair of oars.                                                                                ::
    ID: 07008143.wav
    Length: 392
** Sea Scouts whaler, fairly slow rowing with one pair of oars. (With start and stop)                                                                                ::
    ID: 07008142.wav
    Length: 391
** Sea Scouts whaler, rowing with 2 pairs of oars. (With start and stop)                                                                                ::
    ID: 07008141.wav
    Length: 179
** Sea Scouts whaler, fairly fast rowing with single oars. (With start and stop)                                                                                ::
    ID: 07008140.wav
    Length: 190
** One man, rowing on park lake with heavy rowlock sound.                                                                                ::
    ID: 07008139.wav
    Length: 395
** One man, heavy rowing on park lake.                                                                                ::
    ID: 07008138.wav
    Length: 362
** Exterior, fast train passes through station.                                                                                ::
    ID: 07008137.wav
    Length: 34
** Exterior, train passes through station.                                                                                ::
    ID: 07008136.wav
    Length: 35
** Exterior, train arrives at station.                                                                                ::
    ID: 07008135.wav
    Length: 27
** Exterior, whistle, train departs.                                                                                ::
    ID: 07008134.wav
    Length: 31
** Interior, doors open and close.                                                                                ::
    ID: 07008133.wav
    Length: 23
** Interior, doors close.                                                                                ::
    ID: 07008132.wav
    Length: 11
** Interior, constant run over welded track.                                                                                ::
    ID: 07008131.wav
    Length: 205
** Interior, siren, constant run in tunnel.                                                                                ::
    ID: 07008130.wav
    Length: 71
** Interior, constant run in tunnel.                                                                                ::
    ID: 07008129.wav
    Length: 46
** Interior, very quiet station background heard from inside train.                                                                                ::
    ID: 07008128.wav
    Length: 56
** Interior, constant run gathering speed.                                                                                ::
    ID: 07008127.wav
    Length: 389
** Interior, stops at signals.                                                                                ::
    ID: 07008126.wav
    Length: 104
** Interior, stops at station.                                                                                ::
    ID: 07008125.wav
    Length: 61
** Interior, doors slam, moves off and gathers speed.                                                                                ::
    ID: 07008124.wav
    Length: 93
** Interior, guard's whistle, moves off and gathers speed.                                                                                ::
    ID: 07008123.wav
    Length: 100
** East Croyden Station: General atmosphere with occasional P.A.                                                                                :Trains:Stations:East Croyden:
    ID: 07008122.wav
    Length: 403
** Clapham Junction: General atmosphere with P.A. at start.                                                                                :Clapham Junction:General atmosphere with P:
    ID: 07008121.wav
    Length: 397
** Brighton Station: General atmosphere with P.A. at start.                                                                                :Trains:Stations:Brighton:
    ID: 07008120.wav
    Length: 467
** Victoria Station: General atmosphere with P.A. at start.                                                                                :Trains:Stations:Victoria:
    ID: 07008119.wav
    Length: 396
** Barrage, with soft shell whistles, World War II. (From (78 r.p.m. disc)                                                                                ::
    ID: 07008118.wav
    Length: 102
** Battle actuality. Enemy shells landing. World War II. (From 73 r.p.m. disc)                                                                                ::
    ID: 07008117.wav
    Length: 100
** Enemy shell, mortar fire, MG 42 (nickname Spandau) machine gunfire in background. World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07008116.wav
    Length: 134
** Rifle and machine gunfire, World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07008115.wav
    Length: 117
** River Maas, Heavy artillery and shell whines, World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07008114.wav
    Length: 63
** Battle of Arnhem. Infantry with 2" mortar, rifle, Bren and tommy gunfire advance, 25 pounder barrage, World War II.                                                                                 ::
    ID: 07008113.wav
    Length: 190
** Enemy mortar fire (400 yds) Nebelwerfer (6 barrelled mortar) from enemy lines. World War II. (From 78 r.p.m. disc).                                                                                ::
    ID: 07008112.wav
    Length: 66
** Enemy mortar fire (400 yds). World War II. (From 78 r.p.m. disc).                                                                                ::
    ID: 07008111.wav
    Length: 117
** Machine gun and small arms fire, Bessa guns, enemy shells landing (some in canal) World War II. (From 78 r.p.m. disc).                                                                                ::
    ID: 07008110.wav
    Length: 123
** Allied 3" mortars, burst of machine gun fire, World War II. (From 78 r.p.m. disc).                                                                                ::
    ID: 07008109.wav
    Length: 59
** Street fighting, tanks, Priest self propelled guns, enemy shells landing, World War II. (From 78 r.p.m. disc)                                                                                ::
    ID: 07008108.wav
    Length: 187
** MG 42 (nickname Spandau) machine-gun, Bren gun, small arms fire, Bofor gunfire. World War II. (From 78 r.p.m. disc).                                                                                ::
    ID: 07008107.wav
    Length: 183
** Heavy constant barrage. (Recorded during the Rhine Crossing. From 78 rpm record)                                                                                ::
    ID: 07008106.wav
    Length: 150
** Heavy barrage with tanks and flail tanks moving up. (Recorded during attack on the Siegfried Line, Reischwald Forest.                                                                                 ::
    ID: 07008105.wav
    Length: 159
** Heavy barrage. (World War II, recorded during attack on the Siegfried Line, Reischwald Forest. From 78 rpm recorded)                                                                                ::
    ID: 07008104.wav
    Length: 114
** Heavy barrage with occasional faint bagpipes. (World War II, recorded during attack on the Siegfried Line, Reichswald                                                                                 ::
    ID: 07008103.wav
    Length: 206
** Tank procession with crowds cheering. World War II. (From 78 rpm record)                                                                                ::
    ID: 07008102.wav
    Length: 80
** German Tiger tank starting, ticking over, shutting off. Exterior, World War II. (From 78 rpm record)                                                                                ::
    ID: 07008101.wav
    Length: 101
** German Tiger tank starting, running, shutting off, Interior. World War II. (From 78 rpm record)                                                                                ::
    ID: 07008100.wav
    Length: 103
** German Tiger tank starting, revving, ticking over, shutting off. (From 78 rpm record)                                                                                ::
    ID: 07008099.wav
    Length: 133
** Churchill tank over rough country, World War II. (From 78 rpm record)                                                                                ::
    ID: 07008098.wav
    Length: 168
** Cromwell tank starting, moving over rough country and stopping, World War II. (From 78 rpm record)                                                                                ::
    ID: 07008097.wav
    Length: 86
** Churchill tank starting, revving, stopping, World War II. (From 78 rpm record)                                                                                ::
    ID: 07008096.wav
    Length: 60
** German Tiger tank passing, World War II. (From 78 rpm record)                                                                                ::
    ID: 07008095.wav
    Length: 42
** Large German crowd cheering and shouting slogan. (From 78 rpm record)                                                                                ::
    ID: 07008094.wav
    Length: 68
** Large German crowd cheering. (From 78 rpm record)                                                                                ::
    ID: 07008093.wav
    Length: 60
** Large German crowd shouting "Sieg Heil". (From 78rpm record)                                                                                ::
    ID: 07008092.wav
    Length: 40
** Large German crowd shouting "Sieg heil". (From 78 rpm record)                                                                                ::
    ID: 07008091.wav
    Length: 73
** Goosestep marching, with orders in German. (From 78 rmp record)                                                                                ::
    ID: 07008090.wav
    Length: 20
** Goosestep marching, with orders in German. (From 78 rpm record)                                                                                ::
    ID: 07008089.wav
    Length: 41
** Large German crowd cheering and shouting "Sieg Heil". (From 78rpm record)                                                                                ::
    ID: 07008088.wav
    Length: 180
** Large German crowd cheering. (From 78rpm record)                                                                                ::
    ID: 07008087.wav
    Length: 63
** Artillery: British (World War II actuality)                                                                                :Guns:Gunfire:Artillery:British:
    ID: 07008086.wav
    Length: 170
** Artillery: Enemy (World War II actuality)                                                                                :Guns:Gunfire:Artillery:Enemy:
    ID: 07008085.wav
    Length: 178
** Sound of a tank battle. (World War II actuality)                                                                                ::
    ID: 07008084.wav
    Length: 212
** Sound of artillery with machine gun fire.                                                                                ::
    ID: 07008083.wav
    Length: 181
** Actuality recorded during air raids. Air raid.                                                                                ::
    ID: 07008082.wav
    Length: 208
** Actuality recorded during air raids. Air raids, bombs falling.                                                                                ::
    ID: 07008081.wav
    Length: 77
** Actuality recorded during air raids. Rocket guns. Air raids, bombs falling. Air raid on London.                                                                                ::
    ID: 07008080.wav
    Length: 43
** Air raids on London at night.                                                                                ::
    ID: 07008079.wav
    Length: 180
** Air raids on London at night.                                                                                ::
    ID: 07008078.wav
    Length: 195
** Air raids on London at night. Anti-aircraft barrage                                                                                ::
    ID: 07008077.wav
    Length: 178
** Air raid actuality. Intensive air raid, anti-aircraft fire, bombs falling and bursting, fire engine, bells.                                                                                 ::
    ID: 07008076.wav
    Length: 182
** Air raids on London at night. Night raid, drone of planes                                                                                ::
    ID: 07008075.wav
    Length: 191
** Air raids on London at night. Night alert, faint droning of planes, siren.                                                                                 ::
    ID: 07008074.wav
    Length: 194
** Actuality of Dover raid during the Battle of Britain, Messerschmitts attack on balloon barrage driven off by A/A fire                                                                                ::
    ID: 07008073.wav
    Length: 131
** Massed formation of German bombers in steady flight.                                                                                ::
    ID: 07008072.wav
    Length: 173
** Battle of Britain actuality, air battles.                                                                                ::
    ID: 07008071.wav
    Length: 166
** Battle of Britain actuality, air battles.                                                                                ::
    ID: 07008070.wav
    Length: 140
