** Two-stroke petrol engine driving small elevator, start, run, stop.                                                                                :Engines:Petrol:
    ID: 07076051.wav
    Length: 194
** Single-cylinder Petter engine, start, run stop. (1 1/2 h.p.)                                                                                :Engines:Diesel:
    ID: 07076050.wav
    Length: 194
** Start, constant run with engine driving small compressor, stop. (2 1/4 h.p. 4-stroke)                                                                                :Engines:Petrol:
    ID: 07076049.wav
    Length: 200
** Two false starts, constant run, stop. (2 1/4 h.p. 4-stroke)                                                                                :Engines:Petrol:
    ID: 07076048.wav
    Length: 195
** An 8 mm projector running at 24 f.p.s.                                                                                :Cine Projectors:
    ID: 07076047.wav
    Length: 117
** Automatic threading on 8 mm projector running at 16 f.p.s.                                                                                :Cine Projectors:
    ID: 07076046.wav
    Length: 126
** Film running out on 16 mm projector. (24 f.p.s.)                                                                                :Cine Projectors:
    ID: 07076045.wav
    Length: 17
** A 16 mm projector running at 24 f.p.s.                                                                                :Cine Projectors:
    ID: 07076044.wav
    Length: 124
** Multiple shutter click with wind-on of 6 by 6 cm SLR Hasselblad camera.                                                                                :Photography:Cameras:
    ID: 07076043.wav
    Length: 11
** Single shutter click with wind-on of 6 by 6 cm SLR Hasselblad camera.                                                                                :Photography:Cameras:
    ID: 07076042.wav
    Length: 6
** Three single shutter clicks of 35 mm SLR camera.                                                                                :Photography:Cameras:
    ID: 07076041.wav
    Length: 8
** Short burst of shutter clicks with motor drive of 35 mm SLR camera.                                                                                :Photography:Cameras:
    ID: 07076040.wav
    Length: 6
** Long burst of shutter clicks with motor drive of 35 mm SLR camera.                                                                                :Photography:Cameras:
    ID: 07076039.wav
    Length: 8
** Shutter click and manual wind-on of 35 mm SLR camera.                                                                                :Photography:Cameras:
    ID: 07076038.wav
    Length: 11
** Triple-expansion, constant run, slow down and speed up at 3'45". (Marine-type steam engine, 1911)                                                                                :Engines:Steam:
    ID: 07076037.wav
    Length: 423
** Triple-expansion, start by donkey engine. (Marine-type steam engine, 1911)                                                                                :Engines:Steam:
    ID: 07076036.wav
    Length: 398
** A milling machine switched on, operates with occasional pauses.                                                                                :Industry:Light:
    ID: 07076035.wav
    Length: 156
** Machining and tapping machinery operating.                                                                                :Industry:Light:
    ID: 07076034.wav
    Length: 207
** Shaft orientation machine operating.                                                                                :Industry:Light:
    ID: 07076033.wav
    Length: 159
** Drilling and reaming machine operating, with occasional pauses.                                                                                :Industry:Light:
    ID: 07076032.wav
    Length: 173
** General atmosphere in a busy machine shop with some indistinct speech.                                                                                :Industry:Light:
    ID: 07076031.wav
    Length: 393
** A drilling and milling machine operates with occasional pauses.                                                                                :Industry:Light:
    ID: 07076030.wav
    Length: 289
** Milling machine operating. (Close perspective)                                                                                :Industry:Light:
    ID: 07076029.wav
    Length: 83
** Tropical forest, West Africa at night.                                                                                :Africa:Forest:
    ID: 07076028.wav
    Length: 502
** Tropical Forest, West Africa at dawn.                                                                                :Africa:Forest:
    ID: 07076027.wav
    Length: 510
** Background static to echoes from the moon.                                                                                :Radio:Interference:
    ID: 07076026.wav
    Length: 216
** Keying an Aldis lamp.                                                                                :Morse Code:Aldis lamps:
    ID: 07076025.wav
    Length: 63
** Keyed morse. (No tone, sound of key being operated)                                                                                :Morse Code:
    ID: 07076024.wav
    Length: 67
** Low-pitched buzzer                                                                                :Morse Code:
    ID: 07076023.wav
    Length: 63
** Medium-pitched buzzer                                                                                :Morse Code:
    ID: 07076022.wav
    Length: 64
** Low-pitched oscillator                                                                                :Morse Code:
    ID: 07076021.wav
    Length: 64
** Medium-pitched oscillator                                                                                :Morse Code:
    ID: 07076020.wav
    Length: 63
** High-pitched oscillator                                                                                :Morse Code:
    ID: 07076019.wav
    Length: 65
** Electronic monotony                                                                                :Electronic Sounds:Monotony:
    ID: 07076018.wav
    Length: 191
** Electronic monotony                                                                                :Electronic Sounds:Monotony:
    ID: 07076017.wav
    Length: 195
** Electronic monotony.                                                                                :Electronic Sounds:Monotony:
    ID: 07076016.wav
    Length: 204
** Sound of radar echoes from the Moon.                                                                                :Radar:
    ID: 07076015.wav
    Length: 200
** Creed tape-printing telegraph operating. (c.1928-1952)                                                                                ::
    ID: 07076014.wav
    Length: 119
** Creed transmitter, perforator and receiver operating together.                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076013.wav
    Length: 83
** Creed receiver operating. (c.1925)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076012.wav
    Length: 154
** Creed morse printer operating. (c.1925-1930)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076011.wav
    Length: 71
** Creed transmitter operating. (c.1925)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076010.wav
    Length: 148
** Creed keyboard perforator operating. (c.1925)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076009.wav
    Length: 131
** Hughes printer, with piano type keyboard, operating. (c.1867-1939)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076008.wav
    Length: 100
** Wheatstone reciever operating. (c.1870)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076007.wav
    Length: 86
** Wheatstone transmitter operating. (c.1870)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076006.wav
    Length: 74
** Morse perforator and punches operating, used with Wheatstone transmitter and receiver. (c.1870)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076005.wav
    Length: 88
** Burgett ABC receiver operating. (c.1850)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076004.wav
    Length: 88
** Morse key, transmitting end. (c.1839)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076003.wav
    Length: 80
** Sounder used with morse key, receiving end. (c.1839)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076002.wav
    Length: 134
** Cooke's portable 2-needle telegraph operating. (c.1838)                                                                                :Telegraph Equipment:Morse Code:
    ID: 07076001.wav
    Length: 40
** Tipping coal from hopper in a coal mine.                                                                                :Coal Mining:
    ID: 07075071.wav
    Length: 31
** A pit locomotive operating with constant run in a coal mine.                                                                                :Coal Mining:
    ID: 07075070.wav
    Length: 126
** Lift, gates close, cage descends and gates open.                                                                                :Coal Mining:
    ID: 07075069.wav
    Length: 55
** Lamp room atmosphere in a coal mine.                                                                                :Coal Mining:
    ID: 07075068.wav
    Length: 57
** An agitator belt operating in constant run in a coal mine.                                                                                :Coal Mining:
    ID: 07075067.wav
    Length: 63
** Coal falling down a shute in a coal mine.                                                                                :Coal Mining:
    ID: 07075066.wav
    Length: 118
** Pneumatic coal drill operating in a coal mine. (Distant perspective)                                                                                :Coal Mining:
    ID: 07075065.wav
    Length: 52
** Pneumatic coal drill operating in a coal mine. (Close perspective)                                                                                :Coal Mining:
    ID: 07075064.wav
    Length: 65
** Miners chatting in pit baths.                                                                                :Coal Mining:
    ID: 07075063.wav
    Length: 91
** Tubs crashing together in a coal mine with occasional pit cage bells.                                                                                :Coal Mining:
    ID: 07075062.wav
    Length: 91
** Tubs being coupled in a coal mine. (Steam locomotive passes at end)                                                                                :Coal Mining:
    ID: 07075061.wav
    Length: 124
** Wet shovelling in a coal mine.                                                                                :Coal Mining:
    ID: 07075060.wav
    Length: 131
** Coal falling into a hopper.                                                                                :Coal Mining:
    ID: 07075059.wav
    Length: 55
** Shovelling and distant drilling in a coal mine.                                                                                :Coal Mining:
    ID: 07075058.wav
    Length: 120
** Miners assembling at pit bottom with occasional pit cage gates and bells.                                                                                :Coal Mining:
    ID: 07075057.wav
    Length: 145
** Bell, end of round, quiet speech at a wrestling match.                                                                                :Wrestling:
    ID: 07075056.wav
    Length: 14
** Applause for throw at a wrestling match.                                                                                :Wrestling:
    ID: 07075055.wav
    Length: 12
** Shouts of encouragement at a wrestling match.                                                                                :Wrestling:
    ID: 07075054.wav
    Length: 26
** Announcement, bell, wrestling bout begins.                                                                                :Wrestling:
    ID: 07075053.wav
    Length: 156
** Public address announcement and crowd reaction at a wrestling match.                                                                                :Wrestling:
    ID: 07075052.wav
    Length: 37
** General atmosphere with spectators arriving before a wrestling match.                                                                                :Wrestling:
    ID: 07075051.wav
    Length: 390
** Corliss steam engine, stopping. (Built in 1889, 91 h.p.)                                                                                :Engines:Steam:
    ID: 07075050.wav
    Length: 80
** Corliss steam engine, start up. (Built in 1889, 91 h.p.)                                                                                :Engines:Steam:
    ID: 07075049.wav
    Length: 98
** Corliss steam engine, running. (Built in 1889, 91 h.p.)                                                                                :Engines:Steam:
    ID: 07075048.wav
    Length: 184
** Gear wheels running, driven by steam engine. (No engine noise)                                                                                :Engines:Steam:
    ID: 07075047.wav
    Length: 185
** Single cylinder horizontal steam engine, start, run, stop. (Built in 1851 for the Great Exhibition)                                                                                :Engines:Steam:
    ID: 07075046.wav
    Length: 185
** Large gas/diesel generators, constant run. (Sewage machinery suitable for general use)                                                                                :Engines:Diesel:Gas:
    ID: 07075045.wav
    Length: 184
** One with start, run, stop. (Sewage machinery suitable for general use)                                                                                :Engines:
    ID: 07075044.wav
    Length: 185
** One with start, run, stop. (Sewage machinery suitable for general use)                                                                                :Engines:
    ID: 07075043.wav
    Length: 184
** Several operating, continuous run. (Sewage machinery suitable for general use)                                                                                :Engines:
    ID: 07075042.wav
    Length: 184
** Operating, constant run. (Refuse machinery suitable for general use)                                                                                :Engines:
    ID: 07075041.wav
    Length: 185
** Motor powering a conveyor belt, constant run. (Refuse machinery suitable for general purpose use)                                                                                :Engines:Conveyor:
    ID: 07075040.wav
    Length: 183
** One operating, constant run. (Refuse machinery suitable for general use)                                                                                :Pumps:Diesel:
    ID: 07075039.wav
    Length: 185
** Dust filtration plant operating, constant run. (Refuse machinery suitable for general use)                                                                                :Engines:Filtration plants:
    ID: 07075038.wav
    Length: 184
** Heavy line noise on transatlantic circuit. (Static)                                                                                :Radio:Interference:
    ID: 07075037.wav
    Length: 396
** Static. (Continuous background)                                                                                :Radio:Interference:
    ID: 07075036.wav
    Length: 395
** Tag match: PA annct with crowd reaction, bell; bout begins.                                                                                :Wrestling:
    ID: 07075035.wav
    Length: 332
** Laughter and applause after throw at a wrestling match.                                                                                :Wrestling:
    ID: 07075034.wav
    Length: 33
** Animated crowd reaction at a wrestling match.                                                                                :Wrestling:
    ID: 07075033.wav
    Length: 302
** Good throw and applause, bell into PA and chatter                                                                                :Wrestling:
    ID: 07075032.wav
    Length: 53
** Tuning a communications receiver on the medium-wave band.                                                                                :Radio:Receivers:
    ID: 07075031.wav
    Length: 216
** VHF receiver with aerial disconnected. (Unintelligible speech and heavy distortion)                                                                                :Radio:Receivers:
    ID: 07075030.wav
    Length: 58
** Tuning VHF receiver.                                                                                :Radio:Receivers:
    ID: 07075029.wav
    Length: 50
** Severe mains hum and static.                                                                                :Radio:Interference:
    ID: 07075028.wav
    Length: 62
** Radio interference from electric fence.                                                                                :Radio:Interference:
    ID: 07075027.wav
    Length: 64
** Tuning small medium-wave receiver.                                                                                :Radio:Receivers:
    ID: 07075026.wav
    Length: 185
** An electric centrifugal pump operating with start and stop. (Sewage pump)                                                                                :Pumps:Electric:
    ID: 07075025.wav
    Length: 143
** Ingersoil Rand compressor pump operating with start and stop. (Sewage pump, 1896, with belt-drive)                                                                                :Pumps:Engines:Compressors:
    ID: 07075024.wav
    Length: 140
** Single cylinder compressor pump operating with start and stop. (Sewage pump with belt drive)                                                                                :Pumps:Engines:Compressors:
    ID: 07075023.wav
    Length: 154
** Single five inch pump operating with start and stop. (Sewage pump)                                                                                :Pumps:Engines:
    ID: 07075022.wav
    Length: 129
** Three fourteen inch diesel pumps operating with start and stop. (Sewage pumps)                                                                                :Pumps:Engines:
    ID: 07075021.wav
    Length: 126
** Single 14 inch diesel pump operating with start and stop. (Sewage pump)                                                                                :Pumps:Engines:
    ID: 07075020.wav
    Length: 136
** Ingersoil Rand air compressor, slow down and stop. (1900)                                                                                :Pumps:Engines:Compressors:
    ID: 07075019.wav
    Length: 12
** Ingersoil Rand air compressor, start and run. (1900)                                                                                :Pumps:Engines:Compressors:
    ID: 07075018.wav
    Length: 148
** Ruston Hornsey YEX 6 pumping engines, slow down and stop.                                                                                :Pumps:Diesel:
    ID: 07075017.wav
    Length: 19
** Ruston Hornsey YEX 6 pumping engines, start and run                                                                                :Pumps:Diesel:
    ID: 07075016.wav
    Length: 135
** Ruston Hornsey YEX 6 pumping engine, slow down and stop.                                                                                :Pumps:Diesel:
    ID: 07075015.wav
    Length: 18
** Ruston Hornsey YEX 6 pumping engine, start and run.                                                                                :Pumps:Diesel:
    ID: 07075014.wav
    Length: 120
** Worthington Simpson pumping engine, constant run. (1929)                                                                                :Pumps:Diesel:
    ID: 07075013.wav
    Length: 193
** Lathe shop atmosphere                                                                                :Industry:Lathes:Metal:
    ID: 07075012.wav
    Length: 247
** Lathe switched on, Grinding Tool, slows down, stops.                                                                                :Industry:Lathes:Metal:
    ID: 07075011.wav
    Length: 129
** Lathe switched on, turns steel, slows down, stops.                                                                                :Industry:Lathes:Metal:
    ID: 07075010.wav
    Length: 161
** Lathe switched on, turns aluminium with occasional pauses.                                                                                :Industry:Lathes:Metal:
    ID: 07075009.wav
    Length: 148
** Lathe switched on, turns brass, slows down, stops.                                                                                :Industry:Lathes:Metal:
    ID: 07075008.wav
    Length: 93
** Applause and whistles.                                                                                :Sports:Boxing:Professional:
    ID: 07075007.wav
    Length: 25
** Announcement for retirement, applause.                                                                                :Sports:Boxing:Professional:
    ID: 07075006.wav
    Length: 43
** Medium applause into atmosphere at a boxing match.                                                                                :Sports:Boxing:Professional:
    ID: 07075005.wav
    Length: 32
** Seconds out announcement, round five, bell, atmosphere into next round.                                                                                :Sports:Boxing:Professional:
    ID: 07075004.wav
    Length: 179
** End of round, bell and applause.                                                                                :Sports:Boxing:Professional:
    ID: 07075003.wav
    Length: 19
** Rowdy crowd at boxing match with occasional booing.                                                                                :Sports:Boxing:Professional:
    ID: 07075002.wav
    Length: 184
** Last round of a big fight.                                                                                :Sports:Boxing:Professional:
    ID: 07075001.wav
    Length: 202
** Electronic - bleeps and printer on cash register (background voices - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074235.wav
    Length: 21
** Electronic - light-pen scanner on cash register - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074234.wav
    Length: 8
** Electronic - bleeps on cash register - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074233.wav
    Length: 24
** Electronic - printing and bleeps on cash register - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074232.wav
    Length: 33
** Electronic NCR - addition, empty drawer opened and closed - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074231.wav
    Length: 8
** Electronic NCR - addition, drawer open, money removed - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074230.wav
    Length: 14
** Electronic NCR - bleeps without printer - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074229.wav
    Length: 7
** Electronic NCR - change calculation - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074228.wav
    Length: 5
** Electronic NCR - entry error - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074227.wav
    Length: 4
** Electronic NCR - drawer closed - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074226.wav
    Length: 2
** Electronic NCR - adding in mixed amounts - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074225.wav
    Length: 21
** Electronic NCR - adding in amounts of less than one pound - 1982 (2R1,reprocessed)                                                                                :Cash Registers:
    ID: 07074224.wav
    Length: 15
** Monroe-Sweda - keyboard operated, ticket produced, drawer opens, change given, drawer opens (twice) - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074223.wav
    Length: 53
** Class Fifty One Machine - keyboard operated, drawer opens, bell, change given, drawer closes, in betting office - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074222.wav
    Length: 12
** Class Three Machine (supermarket) - resetting machine - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074221.wav
    Length: 8
** Class Three Machine (supermarket) - keyboard operated, ticket produced, drawer opens, bell, change given, drawer closes (three times) - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074220.wav
    Length: 56
** Itemizing Machine - resetting machine - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074219.wav
    Length: 10
** Itemizing Machine - keyboard operated, drawer opens, bell, change given, drawer closes (three times) - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074218.wav
    Length: 51
** Type Ninety-Six Five - keyboard operated, ticket produced, drawer opens, bell, change given, coins put in drawer and closed - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074217.wav
    Length: 24
** Type Ninety-Six One - keyboard operated, ticket produced, drawer closed (totting up) - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074216.wav
    Length: 15
** Type Ninety-Six One - keyboard operated, ticket produced, drawer opens, bell, change given, coins put in drawer and closed - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074215.wav
    Length: 21
** Class One Hundred - opened, keyboard operated, closed - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074214.wav
    Length: 14
** Class One Hundred - keyboard operated, bell, change given, coins put in drawer, drawer closed (three times) - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074213.wav
    Length: 36
** Class One Hundred - opened, bell, change given, coins put in drawer, drawer closed (six times) - 1969 (23Z,reprocessed)                                                                                :Cash Registers:
    ID: 07074212.wav
    Length: 54
** Manual - bell, change given and coins put in drawer, drawer closed (three times) - 1966 (9A,reprocessed)                                                                                :Cash Registers:
    ID: 07074211.wav
    Length: 27
** Manual - bell, change given and coins put in drawer, drawer closed (twice) - 1966 (9A,reprocessed)                                                                                :Cash Registers:
    ID: 07074210.wav
    Length: 17
** Manual - bell, keyboard, change given and coins put in drawer, drawer closed - 1966 (9A,reprocessed)                                                                                :Cash Registers:
    ID: 07074209.wav
    Length: 13
** Manual - bell, change given and coins put in drawer, drawer closed - 1966 (9A,reprocessed)                                                                                :Cash Registers:
    ID: 07074208.wav
    Length: 12
** Atmosphere in store with distinct speech (pre-decimal coinage) - Sept '1967 (23F,reprocessed)                                                                                :Atmospheres:Villages:
    ID: 07074207.wav
    Length: 253
** Checkout, cash registers and sounds of wrapping - 1981 (1C26,reprocessed)                                                                                :Cash Registers:
    ID: 07074206.wav
    Length: 61
** General atmosphere, occasional trolley and bell - 1981 (1C26,reprocessed)                                                                                :Shops:Supermarkets:
    ID: 07074205.wav
    Length: 269
** Atmosphere in a quiet urban post office with footsteps, voices and distant traffic - Jan '1980 (1C21,reprocessed) (technical note - for use at low level)                                                                                :Post Offices:
    ID: 07074204.wav
    Length: 304
** Petrol station shop, with occasional voices and distant traffic - 1985 (4P1,reprocessed)                                                                                :Petrol Stations:
    ID: 07074203.wav
    Length: 181
** Thirty budgerigars in shed (rec. Petersfield, Hants) - 1986 (1B19,reprocessed)                                                                                :Birds:
    ID: 07074202.wav
    Length: 119
** Agitated birds and cockatiel screeching (rec. Petersfield, Hants) - 1986 (1B19,reprocessed)                                                                                :Birds:
    ID: 07074201.wav
    Length: 15
** Agitated birds and cockatiel screeching (rec. Petersfield, Hants) - 1986 (1B19,reprocessed)                                                                                :Birds:
    ID: 07074200.wav
    Length: 10
** Birds flapping wings with faint calls (rec. Petersfield, Hants) - 1986 (1B19,reprocessed)                                                                                :Birds:
    ID: 07074199.wav
    Length: 13
** A cockatiel calling (rec. Petersfield, Hants) - 1986 (1B19,reprocessed)                                                                                :Birds:
    ID: 07074198.wav
    Length: 9
** Atmosphere in a small shop with caged birds (recorded in a pet shop but suitable for an aviary (rec. Petersfield, Hants) - 1986 (1B19,reprocessed)                                                                                :Birds:
    ID: 07074197.wav
    Length: 64
** Aquarium, close perspective - 1986 (1B19,reprocessed)                                                                                :Aquaria:
    ID: 07074196.wav
    Length: 66
** Atmosphere in a large shop, with aquaria and mixed birds (rec. Stubbington, Hants) - 1986 (1B19,reprocessed)                                                                                :Aquaria:
    ID: 07074195.wav
    Length: 359
** Atmosphere with cash conveyor, some distinct speech - April 1967 (23D,reprocessed)                                                                                :Shops:Drapers:
    ID: 07074194.wav
    Length: 263
** Atmosphere recorded in a London department store - John Lewis - 1973 (1C3,reprocessed)                                                                                :Shops:Department Stores:
    ID: 07074193.wav
    Length: 325
** Atmosphere recorded in a London chain store - British Home Stores - 1973 (1C3,reprocessed)                                                                                :Shops:Chain Stores:
    ID: 07074192.wav
    Length: 287
** Crowds and manual cash registers - Woolworths - 1975 (1C26,reprocessed)                                                                                :Cash Registers:
    ID: 07074191.wav
    Length: 306
** Quiet atmosphere in a bank, traffic noise increases when door opens - 1981 (1C12,reprocesses)                                                                                :Banks:
    ID: 07074190.wav
    Length: 297
** Atmosphere in a large indoor shopping arcade - 1974 (recorded in Holland, no distinct speech) (1C14,reprocessed)                                                                                :Shops:Holland:
    ID: 07074189.wav
    Length: 301
** Group in foreground running to stop - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074188.wav
    Length: 21
** Two people run to distance and double splash - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074187.wav
    Length: 14
** Run to distance and splash - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074186.wav
    Length: 10
** Run to distance and return - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074185.wav
    Length: 21
** One pair of feet approach and stop - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074184.wav
    Length: 6
** One pair of feet approach and explosion - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074183.wav
    Length: 11
** Squeaky feet, door open and close with squeak - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074182.wav
    Length: 18
** Strolling through ovens, oven door open and close - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074181.wav
    Length: 33
** One pair of feet overhead and removing boots - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074180.wav
    Length: 39
** One pair of feet approach to door, door open and close, feet depart - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074179.wav
    Length: 6
** Feet overhead on wood - 1968 (7G, reprocessed)                                                                                :Footsteps:Comedy:
    ID: 07074178.wav
    Length: 27
** Tap turned on, fizzy liquid gurgles out - 1967 (7B, reprocessed)                                                                                :Fizzy Liquids:Comedy:
    ID: 07074177.wav
    Length: 44
** 36 people brawling - 1968 (170A, reprocessed)                                                                                :Fights:Comic:
    ID: 07074176.wav
    Length: 53
** 6 people brawling - 1968 (170A, reprocessed)                                                                                :Fights:Comic:
    ID: 07074175.wav
    Length: 116
** 3 people brawling - 1968 (170A, reprocessed)                                                                                :Fights:Comic:
    ID: 07074174.wav
    Length: 117
** Continuous body falls - continuous heavy movement (170A)                                                                                :Comedy:Fights:
    ID: 07074173.wav
    Length: 32
** Two body falls - 1968 (170A, reprocessed)                                                                                :Fights:Comic:
    ID: 07074172.wav
    Length: 32
** Punches, 3 backhanders - 1968 (170A, reprocessed)                                                                                :Fights:Comic:
    ID: 07074171.wav
    Length: 6
** 4 stomach punches - 1968 (170A, reprocessed)                                                                                :Fights:Comic:
    ID: 07074170.wav
    Length: 10
** Tum punch - 1967 (7A, reprocessed)                                                                                :Fights:Comic:
    ID: 07074169.wav
    Length: 3
** Cod indoor fight - 1967 (7C, reprocessed)                                                                                :Fights:Comic:
    ID: 07074168.wav
    Length: 25
** Scuffle with twangs - 1967 (7E, reprocessed)                                                                                :Fights:Comic:
    ID: 07074167.wav
    Length: 28
** Saloon bar brawl - 1967 (7E, reprocessed)                                                                                :Fights:Comic:
    ID: 07074166.wav
    Length: 116
** Swordfight with shots and groans - 1967 (7E, reprocessed)                                                                                :Fights:Comic:
    ID: 07074165.wav
    Length: 32
** Musical explosion - 1967 (7F, reprocessed)                                                                                :Explosions:Comedy:
    ID: 07074164.wav
    Length: 9
** Execution being carried out with a block and large axe - 1974 (199A, reprocessed)                                                                                :Executions:Comedy:
    ID: 07074163.wav
    Length: 11
** Execution being carried out with a block and axe - 1974 (199A, reprocessed)                                                                                :Executions:Comedy:
    ID: 07074162.wav
    Length: 8
** Execution being carried out with a block and sword - 1971 (199A, reprocessed)                                                                                :Executions:Comedy:
    ID: 07074161.wav
    Length: 8
** Guillotine being used at an execution - 1971 (199A, reprocessed)                                                                                :Executions:Comedy:
    ID: 07074160.wav
    Length: 4
** Masticating apple - 1967 (7C, reprocessed)                                                                                :Eating:Comedy:
    ID: 07074159.wav
    Length: 29
** Man drinking bucket of cold cocoa - 1967 (7F, reprocessed)                                                                                :Drinking:Comedy:
    ID: 07074158.wav
    Length: 18
** One drawbridge opening sideways - 1972 (7K, reprocessed)                                                                                :Drawbridges:Comedy:
    ID: 07074157.wav
    Length: 10
** Breaking down door - 1968 (7H, reprocessed)                                                                                :Cymbals:Comedy:
    ID: 07074156.wav
    Length: 36
** Knocking with doors opening and closing - 1968 (7G, reprocessed)                                                                                :Cymbals:Comedy:
    ID: 07074155.wav
    Length: 22
** Cymbals clang and drop - 1967 (7B, reprocessed)                                                                                :Cymbals:Comedy:
    ID: 07074154.wav
    Length: 6
** Small crowd gasps - 1969 (169C, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074153.wav
    Length: 8
** Busy English market - 1967 (7E, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074152.wav
    Length: 69
** Crowd panics - 1968 (7H, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074151.wav
    Length: 19
** Crowd panic and rush for exits - 1967 (7E, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074150.wav
    Length: 18
** English club chatter - 1967 (7E, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074149.wav
    Length: 51
** Mixed group booing and bleating - 1967 (7E, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074147.wav
    Length: 56
** Small group, half-hearted hurrahs - 1967 (7E, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074146.wav
    Length: 17
** Small group cheering - 1972 (7K, reprocessed)                                                                                :Crowds:Comedy:
    ID: 07074145.wav
    Length: 17
** 3 furniture crashes - 1968 (170A, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074144.wav
    Length: 13
** Comic metal crash - 1971 (84F, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074143.wav
    Length: 7
** Metal crash - 1972 (7M, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074142.wav
    Length: 10
** Girders clanging - 1967 (7B, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074141.wav
    Length: 7
** Shovelling tins - 1967 (7B, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074140.wav
    Length: 37
** Gas stove dropped - 1967 (7C, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074139.wav
    Length: 6
** Things falling and clanging - 1967 (7C, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074138.wav
    Length: 13
** Long, drawn out crash - 1972 (7K, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074137.wav
    Length: 27
** Frantic banging and clanging - 1967 (7B, reprocessed)                                                                                :Crashes:Comedy:
    ID: 07074136.wav
    Length: 32
** Single cork pop and heavy guzzling - 1967 (7C, reprocessed)                                                                                :Cork Pops:Comedy:
    ID: 07074135.wav
    Length: 8
** Martian computer - 1972 (7K, reprocessed)                                                                                :Computers:Comic:
    ID: 07074134.wav
    Length: 100
** Chemical computer - 1970 (7J, reprocessed)                                                                                :Computers:Comic:
    ID: 07074133.wav
    Length: 97
** Cuckoo clock tester - 1970 (7J, reprocessed)                                                                                :Clocks:Comic:
    ID: 07074132.wav
    Length: 82
** Clock cartoon - 1970 (7J, reprocessed)                                                                                :Clocks:Comic:
    ID: 07074131.wav
    Length: 11
** Clockwork mechanism - 1968 (7H, reprocessed)                                                                                :Clocks:Comic:
    ID: 07074130.wav
    Length: 26
** Atmos. in a clock shop, with ticking and chimes - 1967 (7F, reprocessed)                                                                                :Clocks:Comic:
    ID: 07074129.wav
    Length: 65
** Clock nightmare - 1967 (7D, reprocessed)                                                                                :Clocks:Comic:
    ID: 07074128.wav
    Length: 25
** Slow walk with chains - 1969 (89E, reprocessed)                                                                                :Chains:Comedy:
    ID: 07074127.wav
    Length: 61
** Running chains - 1969 (89E, reprocessed)                                                                                :Chains:Comedy:
    ID: 07074126.wav
    Length: 61
** Chains shaken - 1969 (89E, reprocessed)                                                                                :Chains:Comedy:
    ID: 07074125.wav
    Length: 61
** Chains rattling - 1969 (89E, reprocessed)                                                                                :Chains:Comedy:
    ID: 07074124.wav
    Length: 61
** Puncture - air escaping from tyre - 1972 (7M, reprocessed)                                                                                :Comedy:Cars:
    ID: 07074123.wav
    Length: 7
** Single car running comically - 1967 (7F, reprocessed)                                                                                :Comedy:Cars:
    ID: 07074122.wav
    Length: 69
** Continuous bubbling sound - 1972 (7M, reprocessed)                                                                                :Bubbles:Comedy:
    ID: 07074121.wav
    Length: 12
** Milk bottles breaking - 1968 (7H, reprocessed)                                                                                :Comedy:Bottles:
    ID: 07074120.wav
    Length: 1
** Glass bottles tipped onto floor - 1967 (7B, reprocessed)                                                                                :Comedy:Bottles:
    ID: 07074119.wav
    Length: 21
** One bluebottle circling at 7 ft - 1972 (7L, reprocessed)                                                                                :Insects:Bluebottles:Comedy:
    ID: 07074118.wav
    Length: 31
** Single woodpecker practising - 1972 (7K, reprocessed)                                                                                :Birds:Comic:
    ID: 07074117.wav
    Length: 43
** Mother owl hooting - 1972 (7K, reprocessed)                                                                                :Birds:Comic:
    ID: 07074116.wav
    Length: 4
** Father owl hooting - 1972 (7K, reprocessed)                                                                                :Birds:Comic:
    ID: 07074115.wav
    Length: 7
** Irish nightingale - 1972 (7L, reprocessed)                                                                                :Birds:Comic:
    ID: 07074114.wav
    Length: 59
** Smoked herring gull - 1972 (7L, reprocessed)                                                                                :Birds:Comic:
    ID: 07074113.wav
    Length: 5
** One goose gobbling - 1972 (7M, reprocessed)                                                                                :Birds:Comic:
    ID: 07074112.wav
    Length: 17
** Bristle-backed duck - 1972 (7L, reprocessed)                                                                                :Birds:Comic:
    ID: 07074111.wav
    Length: 39
** Indisposed chicken - 1972 (7L, reprocessed)                                                                                :Birds:Comic:
    ID: 07074110.wav
    Length: 7
** More-or-less normal chicken - 1972 (7L, reprocessed)                                                                                :Birds:Comic:
    ID: 07074109.wav
    Length: 23
** Large bird taking off, three attempts - 1972 (7M, reprocessed)                                                                                :Birds:Comic:
    ID: 07074108.wav
    Length: 28
** Birds taking off - 1967 (7C, reprocessed)                                                                                :Birds:Comic:
    ID: 07074107.wav
    Length: 4
** A country idyll, countryside atmos. - 1972 (7L, reprocessed)                                                                                :Birds:Comic:
    ID: 07074106.wav
    Length: 18
** 4 batter puddings thrown - 1967 (7A, reprocessed)                                                                                :Comedy:Batter Puddings:
    ID: 07074105.wav
    Length: 4
** Mighty balloon bursts - 1967 (7D, reprocessed)                                                                                :Balloons:Comedy:
    ID: 07074104.wav
    Length: 9
** Arrow landing - 1972 (7M, reprocessed)                                                                                :Sports:Archery:Comedy:
    ID: 07074103.wav
    Length: 4
** Flight of arrows - 1972 (7M, reprocessed)                                                                                :Sports:Archery:Comedy:
    ID: 07074102.wav
    Length: 27
** Feeble applause - 1967 (7E, reprocessed)                                                                                :Applause:Comedy:
    ID: 07074101.wav
    Length: 19
** Half a dozen werewolves - 1972 (7L, reprocessed)                                                                                :Animals:Comedy:
    ID: 07074100.wav
    Length: 19
** Assorted sheep bleating - 1972 (7M, reprocessed)                                                                                :Animals:Comedy:
    ID: 07074099.wav
    Length: 37
** Mother and child sheep bleating - 1972 (7M, reprocessed)                                                                                :Animals:Comedy:
    ID: 07074098.wav
    Length: 36
** Trio of horse neighs - 1972 (7L, reprocessed)                                                                                :Animals:Comedy:
    ID: 07074097.wav
    Length: 23
** Mating cry young donkey - 1972 (7L, reprocessed)                                                                                :Animals:Comedy:
    ID: 07074096.wav
    Length: 23
** One donkey donkeying - 1972 (7L, reprocessed)                                                                                :Animals:Comedy:
    ID: 07074095.wav
    Length: 20
** Wild boars having tea - 1972 (7L, reprocessed)                                                                                :Animals:Comedy:
    ID: 07074094.wav
    Length: 26
** One angel in flight - 1967 (7F, reprocessed)                                                                                :Angels:Comedy:
    ID: 07074093.wav
    Length: 42
** Buffing sheet metal parts.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074092.wav
    Length: 180
** Scurfing sheet metal parts.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074091.wav
    Length: 177
** 750-ton press stamping out metal parts.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074090.wav
    Length: 182
** High-pressure air pipes singing.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074089.wav
    Length: 180
** Atmosphere in high-pressure spray plant.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074088.wav
    Length: 180
** Spot welding of car bodies.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074087.wav
    Length: 139
** Tightening nuts mechanically.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074086.wav
    Length: 56
** Body building shop atmosphere.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074085.wav
    Length: 180
** General atmosphere in motor car works.                                                                                :Industry:Motor Car Manufacture:
    ID: 07074084.wav
    Length: 180
** Sawing diamond.                                                                                :Industry:Gold And Gems:
    ID: 07074083.wav
    Length: 49
** Sharpening diamond.                                                                                :Industry:Gold And Gems:
    ID: 07074082.wav
    Length: 57
** Polishing gem stone on lapidary's wheel.                                                                                :Industry:Gold And Gems:
    ID: 07074081.wav
    Length: 54
** Chasing gold rings.                                                                                :Industry:Gold And Gems:
    ID: 07074080.wav
    Length: 50
** Rolling gold into sheets.                                                                                :Industry:Gold And Gems:
    ID: 07074079.wav
    Length: 52
** Hammering gold leaf.                                                                                :Industry:Gold And Gems:
    ID: 07074078.wav
    Length: 53
** Pouring fine-grain gold.                                                                                :Industry:Gold And Gems:
    ID: 07074077.wav
    Length: 57
** Shaking pan to dry fine-grain gold.                                                                                :Industry:Gold And Gems:
    ID: 07074076.wav
    Length: 37
** Fine-grain gold taken out & rinsed.                                                                                :Industry:Gold And Gems:
    ID: 07074075.wav
    Length: 57
** Molten gold poured into water.                                                                                :Industry:Gold And Gems:
    ID: 07074074.wav
    Length: 92
** Hot crucible lifted with block and tackle.                                                                                :Industry:Gold And Gems:
    ID: 07074073.wav
    Length: 28
** Gold furnace.                                                                                :Industry:Gold And Gems:
    ID: 07074072.wav
    Length: 59
** Tyre bead-making machine.                                                                                :Industry:Tyre Manufacture:
    ID: 07074071.wav
    Length: 94
** Weathering tyres.                                                                                :Industry:Tyre Manufacture:
    ID: 07074070.wav
    Length: 144
** Mixing raw rubber.                                                                                :Industry:Tyre Manufacture:
    ID: 07074069.wav
    Length: 180
** Heavy steam hisses - tyre factory.                                                                                :Industry:Tyre Manufacture:
    ID: 07074068.wav
    Length: 80
** Mill room atmosphere.                                                                                :Industry:Tyre Manufacture:
    ID: 07074067.wav
    Length: 180
** Debagging tyres.                                                                                :Industry:Tyre Manufacture:
    ID: 07074066.wav
    Length: 180
** Assembly shop atmosphere ("D").                                                                                :Industry:Light:
    ID: 07074065.wav
    Length: 180
** Machine shop atmosphere.                                                                                :Industry:Light:
    ID: 07074064.wav
    Length: 180
** Injection moulding shop atmosphere.                                                                                :Industry:Light:
    ID: 07074063.wav
    Length: 180
** Assembly shop atmosphere ("C").                                                                                :Industry:Light:
    ID: 07074062.wav
    Length: 180
** Weingarten hydraulic press operating.                                                                                :Industry:Light:
    ID: 07074061.wav
    Length: 183
** Wire cutting machine operating.                                                                                :Industry:Light:
    ID: 07074060.wav
    Length: 113
** Braiding machine operating.                                                                                :Industry:Light:
    ID: 07074059.wav
    Length: 139
** Moulding crusher operating.                                                                                :Industry:Light:
    ID: 07074058.wav
    Length: 42
** Betting shop - Atmosphere - P.A. with voices, busy.                                                                                :Shops:Betting Shops:
    ID: 07074057.wav
    Length: 191
** Betting shop - Atmosphere - P.A. with voices.                                                                                :Shops:Betting Shops:
    ID: 07074056.wav
    Length: 207
** Betting shop - Atmosphere with P.A.                                                                                :Shops:Betting Shops:
    ID: 07074055.wav
    Length: 201
** Betting shop - General atmosphere.                                                                                :Shops:Betting Shops:
    ID: 07074054.wav
    Length: 185
** Village store - general atmosphere.                                                                                :Shops:Village Stores:
    ID: 07074053.wav
    Length: 300
** Greengrocers' shop - open fronted.                                                                                :Shops:Greengrocers:
    ID: 07074052.wav
    Length: 300
** Newsagent/confectioner's shop - fairly quiet atmosphere.                                                                                :Shops:Newsagents/Confectioners:
    ID: 07074051.wav
    Length: 314
** Confectioners' shop - busy, with children.                                                                                :Shops:Confectioners:
    ID: 07074050.wav
    Length: 301
** Butchers' shop - general atmosphere.                                                                                :Shops:Butchers:
    ID: 07074049.wav
    Length: 300
** Drapers' shop - general atmosphere with cash railway.                                                                                :Shops:Drapers:
    ID: 07074048.wav
    Length: 313
** Shopping precinct - Chatter, footsteps, etc - wide perspective, Stevenage, April 1970.                                                                                :Shops:Shopping Precincts:
    ID: 07074047.wav
    Length: 300
** Shopping precinct - Chatter, footsteps, etc - close perspective, Stevenage, April 1970.                                                                                :Shops:Shopping Precincts:
    ID: 07074046.wav
    Length: 300
** Supermarket - At checkout positions, quieter than track 4.                                                                                :Shops:Supermarkets:
    ID: 07074045.wav
    Length: 141
** Supermarket - At checkout positions.                                                                                :Shops:Supermarkets:
    ID: 07074044.wav
    Length: 146
** Supermarket - General atmosphere.                                                                                :Shops:Supermarkets:
    ID: 07074043.wav
    Length: 165
** Atmosphere in Bentalls.                                                                                :Shops:Department Stores:
    ID: 07074042.wav
    Length: 291
** Atmosphere in Harrods.                                                                                :Shops:Department Stores:
    ID: 07074041.wav
    Length: 291
** General atmosphere in canteen kitchen.                                                                                :Restaurants:Canteens:
    ID: 07074040.wav
    Length: 337
** Kitchen of London Council home.                                                                                :Kitchens:
    ID: 07074039.wav
    Length: 332
** Kitchen of busy Chinese restaurant, London.                                                                                :Kitchens:
    ID: 07074038.wav
    Length: 287
** Kitchen of busy French restaurant, London.                                                                                :Kitchens:
    ID: 07074037.wav
    Length: 312
** American chatter; large mixed crowd in dining hall of US Air Force base.                                                                                :Crowds:Interior:
    ID: 07074036.wav
    Length: 320
** American chatter; medium-sized crowd in dining hall of US Air Force base.                                                                                :Crowds:Interior:
    ID: 07074035.wav
    Length: 320
** Large restaurant Holland.                                                                                :Restaurants:Holland:
    ID: 07074034.wav
    Length: 204
** British Museum - atmosphere in tea room.                                                                                :Museums:British Museum:
    ID: 07074033.wav
    Length: 316
** Fish and chip shop.                                                                                :Restaurants:
    ID: 07074032.wav
    Length: 318
** Cheap restaurant - very quiet.                                                                                :Restaurants:
    ID: 07074031.wav
    Length: 270
** Cheap restaurant - quiet conversation and chatter.                                                                                :Restaurants:
    ID: 07074030.wav
    Length: 301
** Noisy French restaurant, London.                                                                                :London:
    ID: 07074029.wav
    Length: 307
** Restaurant - lunch/dinner time.                                                                                :Restaurants:
    ID: 07074028.wav
    Length: 322
** Restaurant - tea/coffee time.                                                                                :Restaurants:
    ID: 07074027.wav
    Length: 300
** Sheep shearing machine - starts, runs, stops. Rec. at the New Zealand Agrodome, Rotorua.                                                                                :New Zealand:
    ID: 07074026.wav
    Length: 47
** Claybird shooting - several shotgun shots preceded by noise of claybird (aka clay pigeon) firing mechanism, with comments from instructor just audible. Rec. at Agrodome, Rotorua, New Zealand.                                                                                :Guns:Shotguns:
    ID: 07074025.wav
    Length: 51
** Cars passing on open road - tranquil cicadas and distant birds disturbed by occasional cars passing at speed.                                                                                :Birds:
    ID: 07074024.wav
    Length: 186
** Street scene, Christchurch - outside arts centre (afternoon), horse-drawn carriage passes, tram approaches, stops, then departs with honks, clanks and hiss of steam.                                                                                :Animals:Horses:Carriages:
    ID: 07074023.wav
    Length: 145
** Shopping mall cafe, Auckland - distant clatter of crockery and cutlery with lively conversation in eating area surrounded by food counters.                                                                                :New Zealand:
    ID: 07074022.wav
    Length: 202
** Quiet back street, Auckland - distant cars revving and accelerating, hum of air conditioning, sparrows, rustle of wind-blown paper.                                                                                :Traffic:Motor:Side Streets:
    ID: 07074021.wav
    Length: 143
** Queen Street, Auckland - cars and buses passing and waiting at busy crossroads, distant myna birds, laughter, conversation and pedestrian crossing signals.                                                                                :Traffic:Motor:Towns:
    ID: 07074020.wav
    Length: 226
** Busy street scene, Wellington - traffic footsteps, rattle of overhead wires and pantographs as electric buses pass, pedestrian crossings.                                                                                :Streets:
    ID: 07074019.wav
    Length: 255
** Lorikeets at dawn, Manly beach, Australia - raccous dawn chorus of Rainbow Lorikeets in tall trees against a background of Tasman sea surf.                                                                                :Australia:
    ID: 07074018.wav
    Length: 141
** Budgerigars and doves, Warratah Park, Australia - occasional wind in dry leaves and crow calling.                                                                                :Australia:
    ID: 07074017.wav
    Length: 186
** Bellbirds on farm land - recorded at Kurrajong Heights in the Blue Mountains region, Australia (some cars and chain-saw audible in background).                                                                                :Australia:
    ID: 07074016.wav
    Length: 126
** Suburban bush at dawn, Cherry brook - lively bush atmosphere on the Callicoma Trail, including whipbirds, cockatoos, parrots ( distant light plane heard occasionally in background).                                                                                :Australia:
    ID: 07074015.wav
    Length: 167
** Ferry arrives at Circular Quay Sydney, Australia - distant horns, water churning as large ferry arrives, indistinct speech and calls from passengers, warning alarms, clank of metal gates and ramps; passengers disembark.                                                                                :Australia:
    ID: 07074014.wav
    Length: 268
** Monorail train passing, Darling Harbour - city atmosphere with footsteps, some distinct speech. Monorail train passes overhead (ID point at 1'22" for train approach).                                                                                :Trains:Sydney:
    ID: 07074013.wav
    Length: 124
** Sydney Harbourlink Monorail - train arrives in station and departs with general atmosphere, tourists and click of turnstiles.                                                                                :Trains:Stations:Australia:
    ID: 07074012.wav
    Length: 139
** Suburban trains, Circular Quay Station - trains arrive and depart with station announcements, whistles, hooters and passengers waiting.                                                                                :Trains:Stations:
    ID: 07074011.wav
    Length: 188
** Cicada and trash - lone cicada sings as bags of cans and bottles are thrown away. Urban atmosphere; recorded Sydney, Australia.                                                                                :Australia:
    ID: 07074010.wav
    Length: 170
** Building site - Manly, Australia. Large site as heard from above with natural reverberation, hammering, electric saws, drilling, metal sheeting and wood dropped, very distant background surf and some myna birds.                                                                                :Australia:
    ID: 07074009.wav
    Length: 172
** Pedestrian crossings, Manly, Australia. Vibrating crossing signals, with passing traffic, footsteps and some distant voices.                                                                                :Australia:
    ID: 07074008.wav
    Length: 233
** Station foyer, Circular Quay - general foyer atmosphere with ticket machines, entry gates and some distant traffic.                                                                                :Trains:Stations:Australia:
    ID: 07074007.wav
    Length: 98
** Street scene, outside Circular Quay - buses stopping with air brakes, taxi rank, occasional passing traffic.                                                                                :Australia:
    ID: 07074006.wav
    Length: 157
** Harbour skyline, Sydney cove - overlooking Circular quay, The Rocks and Sydney Harbour Bridge, water lapping againt jetty, ferry horns, distant trains arriving and leaving (evening).                                                                                :Atmospheres:Quayside:
    ID: 07074005.wav
    Length: 251
** Small creek, Charles Darwin walk - bush walk in the Blue Mountains region, some bird calls in background.                                                                                :Australia:
    ID: 07074004.wav
    Length: 139
** Lapping water with bird song, Pittwater - early morning, with distant bird calls including whipbirds, laughing kookaburra, parrots and cockatoos.                                                                                :Australia:
    ID: 07074003.wav
    Length: 176
** Heavy surf - Manly beach.                                                                                :Australia:
    ID: 07074002.wav
    Length: 157
** Surf - Bondi beach.                                                                                :Australia:
    ID: 07074001.wav
    Length: 143
** Tag match - PA announcement with crowd reaction, bell, bout begins                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073026.wav
    Length: 314
** Laughter & applause after throw                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073025.wav
    Length: 31
** Animated crowd reaction                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073024.wav
    Length: 284
** Good throw & applause - bell into PA & chatter                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073023.wav
    Length: 51
** Bell - end of round, into quiet chatter                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073022.wav
    Length: 10
** Applause for throw                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073021.wav
    Length: 7
** Shouts of encouragement                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073020.wav
    Length: 22
** Announcement - bell, bout begins                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073019.wav
    Length: 152
** PA announcement. & crowd reaction                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073018.wav
    Length: 33
** General atmosphere - spectators arriving                                                                                 :Sports:Wrestling:Indoor:
    ID: 07073017.wav
    Length: 374
** Applause & whistles                                                                                 :Sports:Boxing:Professional:
    ID: 07073016.wav
    Length: 21
** Announcement for retirement - applause                                                                                 :Sports:Boxing:Professional:
    ID: 07073015.wav
    Length: 36
** Medium applause into atmosphere                                                                                 :Sports:Boxing:Professional:
    ID: 07073014.wav
    Length: 29
** Announcement - seconds out, round 5, bell, into round                                                                                 :Sports:Boxing:Professional:
    ID: 07073013.wav
    Length: 169
** End of round, bell & applause                                                                                 :Sports:Boxing:Professional:
    ID: 07073012.wav
    Length: 15
** Rowdy crowd with booing, etc.                                                                                 :Sports:Boxing:Professional:
    ID: 07073011.wav
    Length: 175
** Last round of big fight                                                                                 :Sports:Boxing:Professional:
    ID: 07073010.wav
    Length: 192
** Announcement into 1st round - bell at end of round into atmosphere, seconds out, bell, into 2nd round - fairly quiet contest                                                                                 :Sports:Boxing:Professional:
    ID: 07073009.wav
    Length: 374
** General atmosphere before contest                                                                                 :Sports:Boxing:Professional:
    ID: 07073008.wav
    Length: 352
** Skipping                                                                                 :Sports:Boxing:
    ID: 07073007.wav
    Length: 117
** Practising with punch bell - distant conversation                                                                                 :Sports:Boxing:
    ID: 07073006.wav
    Length: 171
** 2 heavy weights in gymnasium - bell at end                                                                                 :Sports:Boxing:
    ID: 07073005.wav
    Length: 180
** 1 round of hard boxing - no audience                                                                                 :Sports:Boxing:
    ID: 07073004.wav
    Length: 170
** 3rd round - enthusiastic, starts with bell                                                                                 :Sports:Boxing:Amateur:
    ID: 07073003.wav
    Length: 199
** 1st round - fairly quiet, starts with bell                                                                                 :Sports:Boxing:Amateur:
    ID: 07073002.wav
    Length: 188
** Crowd assembling                                                                                 :Sports:Boxing:Amateur:
    ID: 07073001.wav
    Length: 374
** Activity with clowns, act in progress with indistinguishable music, drum rolls and children shouting - Nov '1979 (1C20,reprocessed)                                                                                :Children:Playing:
    ID: 07072179.wav
    Length: 73
** Expectant drum roll, with speech and atmosphere, cymbal crash, applause (indistinguishable music in background) - Nov '1979 (1C20,reprocessed)                                                                                :Circuses:
    ID: 07072178.wav
    Length: 44
** Cymbal crash, applause (indistinguishable music in background) - Nov '1979 (1C20,reprocessed)                                                                                :Circuses:
    ID: 07072177.wav
    Length: 10
** Children and clowns shout 'hello' (indistinguishable music in background) - Nov '1979 (1C20,reprocessed)                                                                                :Children:Playing:
    ID: 07072176.wav
    Length: 10
** Performing dogs with whistles, barks and whipcracks (indistinguishable music in background) - Nov '1979 (1C20,reprocessed)                                                                                :Circuses:
    ID: 07072175.wav
    Length: 71
** Atmosphere, drum roll and applause (indistinguishable music in background) - Nov '1979 (1C20,reprocessed)                                                                                :Circuses:
    ID: 07072174.wav
    Length: 30
** Big top crowd atmosphere, mainly indistinct speech with generator in background - Nov '1979 (1C20,reprocessed)                                                                                :Circuses:
    ID: 07072173.wav
    Length: 300
** Giant powered swingboat - May '1985 (rec West Midlands Safari Park) (5F4,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072172.wav
    Length: 102
** The Satellite - machine operates, screams with occasional indistinct PA - July '1966 (38C,reprocessed)                                                                                :Crowds:Exterior:Screams:
    ID: 07072171.wav
    Length: 154
** Children's roundabout with occasional bell - July '1966 (38C,reprocessed)                                                                                :Children:Playing:
    ID: 07072170.wav
    Length: 160
** Atmosphere at children's roundabout - May '1985 (rec West Midlands Safari Park) (5F4,reprocessed)                                                                                :Children:Playing:
    ID: 07072169.wav
    Length: 68
** Roundabouts with fairground atmosphere - Nov '1980 (rec Battersea Funfair) (5F1,reprocessed)                                                                                :Fairgrounds:Roundabouts:
    ID: 07072168.wav
    Length: 283
** People shouting and screaming in the Rotor as the machine operates - July '1966 (38C,reprocessed)                                                                                :Crowds:Exterior:Shouting:
    ID: 07072167.wav
    Length: 145
** Cobra rollercoaster - from side of track - May '1985 (recorded West Midlands Safari Park) (5F4,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072166.wav
    Length: 151
** Cobra rollercoaster - from underneath track - May '1985 (recorded West Midlands Safari Park) (5F4,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072165.wav
    Length: 99
** A ride on the Cobra rollercoaster - May '1985 (recorded West Midlands Safari Park) (5F4,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072164.wav
    Length: 94
** Atmosphere recorded near rifle range and darts, with indistinct music and inaudible PA announcements - June '1989(digitally mastered but copied to analogue for dubbing purposes)                                                                                :Fairgrounds:Rifle Ranges:
    ID: 07072163.wav
    Length: 194
** Atmosphere in air-rifle range at fairground - Jan '1980 (5F2,reprocessed)                                                                                :Fairgrounds:Rifle Ranges:
    ID: 07072162.wav
    Length: 180
** A ghost train ride - May '1985 (rec West Midlands Safari Park) (5F4,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072161.wav
    Length: 75
** A ghost train ride with sirens and bells - Jan '1980 (5F2,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072160.wav
    Length: 180
** Ride in a dodgem car with bell at end of ride - Jan '1980 (5F2,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072159.wav
    Length: 181
** Atmosphere from edge of dodgem area with some indistinct music - Jan '1980 (5F2,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072158.wav
    Length: 180
** Caterpillar - machine operates, screams with indistinct PA - July '1966 (38C,reprocessed)                                                                                :Fairgrounds:Rides:
    ID: 07072157.wav
    Length: 151
** Amusement arcade atmosphere - Nov '1980 (recorded Battersea Funfair) (5F1,reprocessed) (tecnical note - to be used at low level)                                                                                :Crowds:Interior:
    ID: 07072156.wav
    Length: 227
** Atmosphere in an amusement arcade at a fairground with background fairground atmosphere - Jan '1980 (5F3,reprocessed)                                                                                :Crowds:Interior:
    ID: 07072155.wav
    Length: 276
** Crowd atmosphere with steam roundabouts and indistinct music from steam organ - Aug '1966 (38A,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07072154.wav
    Length: 242
** Quiet safari park fairground atmos., with birdsong and some ducks quacking at start - May '1985 (recorded West Midlands Safari Park) (5F4,reprocessed) (tecnical note - to be used at low level)                                                                                :Birds:
    ID: 07072153.wav
    Length: 146
** Crowd atmosphere with indistinct band in background - Jan '1980 (5F3,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07072152.wav
    Length: 300
** General fairground atmosphere - Nov. '1980 (recorded Battersea Funfair) (5F1,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07072151.wav
    Length: 185
** In playground, atmosphere of girls playing recorded between buildings (occasional distinct speech and scream)  - 1979 (3C6, reprocessed)                                                                                :Children:Playing:
    ID: 07072150.wav
    Length: 242
** In open playing field, shouting and laughter with footsteps (occasional distinct speech)  - 1979 (3C6, reprocessed)                                                                                :Girls:
    ID: 07072149.wav
    Length: 120
** In dining room at lunchtime, busy atmosphere with speech and crockery clatter - 1979 (3C6, reprocessed)                                                                                :Girls:
    ID: 07072148.wav
    Length: 224
** In class, speech and clatter prior to lesson, ends with "shshsh" (occasional desk scraped on floor, reprocessed) - 1979 (3C6, reprocessed)                                                                                :Girls:
    ID: 07072147.wav
    Length: 119
** In hall, conversation quietens  - 1979 (3C5, reprocessed)                                                                                :Girls:
    ID: 07072146.wav
    Length: 13
** In hall, noisy conversation - 1979 (3C5, reprocessed)                                                                                :Girls:
    ID: 07072145.wav
    Length: 303
** In corridor, footsteps and voices during break - 1979 (3C5, reprocessed)                                                                                :Girls:
    ID: 07072144.wav
    Length: 184
** In class, loud chatter and movement at end of lesson - 1979 (3C5, reprocessed)                                                                                :Girls:
    ID: 07072143.wav
    Length: 168
** Chatter in laboratory during free period (no distinct speech) - 1968 (68D, reprocessed)                                                                                :Girls:
    ID: 07072142.wav
    Length: 193
** Girls filing into hall (footsteps and indistinct chatter) - 1968 (68C, reprocessed)                                                                                :Girls:
    ID: 07072141.wav
    Length: 172
** Chairs being set up in hall with some quiet periods and chatter (no distinct speech - wide perspective) - 1968 (68c, reprocessed)                                                                                :Girls:
    ID: 07072140.wav
    Length: 195
** Girls entering school building (footsteps and chatter, no distinct speech) - 1968 (68B, reprocessed)                                                                                :Girls:
    ID: 07072139.wav
    Length: 188
** Junior boys in noisy classroom - 1981 (3C3, reprocessed)                                                                                :Boys:
    ID: 07072138.wav
    Length: 55
** Boys entering classroom - 1981 (3C3, reprocessed)                                                                                :Boys:
    ID: 07072137.wav
    Length: 26
** Boys leaving classroom - 1981 (3C3, reprocessed)                                                                                :Boys:
    ID: 07072136.wav
    Length: 15
** Abusive remarks thrown at teacher in classroom - 1981 (3C3, reprocessed)                                                                                :Schools:
    ID: 07072135.wav
    Length: 22
** Argumentative atmosphere in classroom - 1981 (3C3, reprocessed)                                                                                :Schools:
    ID: 07072134.wav
    Length: 59
** Sudden change from rowdy to silent atmosphere in classroom - 1981 (3C3, reprocessed)                                                                                :Schools:
    ID: 07072133.wav
    Length: 12
** Boys not under control in classroom - 1981 (3C3, reprocessed)                                                                                :Boys:
    ID: 07072132.wav
    Length: 194
** Boys supposed to be working in classroom - 1981 (3C3, reprocessed)                                                                                :Boys:
    ID: 07072131.wav
    Length: 190
** Boys in showers, with indistinct speech in foreground (wide perspective, reprocessed) - 1968 (68J, reprocessed)                                                                                :Boys:
    ID: 07072130.wav
    Length: 126
** Boys playing during break time  - 1981 (3C2, reprocessed)                                                                                :Boys:
    ID: 07072129.wav
    Length: 183
** Boys playing in outdoor swimming pool with younger mixed children also audible - 1981 (3C2, reprocessed)                                                                                :Boys:
    ID: 07072128.wav
    Length: 191
** Grace said, atmosphere during meal - 1981 (3C2, reprocessed)                                                                                :Boys:
    ID: 07072127.wav
    Length: 216
** Boys enter dining hall and atmosphere before start of meal (occasional voice of young child, reprocessed)  - 1981 (3C2, reprocessed)                                                                                :Boys:
    ID: 07072126.wav
    Length: 206
** Electric school bell  - 1980 (3C9, reprocessed)                                                                                :Schools:Bells:
    ID: 07072125.wav
    Length: 11
** Sounds of groans of incredulity in classroom (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072124.wav
    Length: 12
** Sounds of groans of disappointment in class (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072123.wav
    Length: 18
** Children giggling in classroom (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072122.wav
    Length: 4
** Children laughing in classroom (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072121.wav
    Length: 4
** Children laughing in classroom (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072120.wav
    Length: 7
** Subdued classroom atmosphere with children reading (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072119.wav
    Length: 202
** Bell rings, children leave classroom (rec. London, reprocessed) - 1980 (3C9, reprocessed)                                                                                :Schools:Bells:
    ID: 07072118.wav
    Length: 50
** Children gradually settle down in classroom (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072117.wav
    Length: 149
** Children entering classroom (rec. London) - 1980 (3C9, reprocessed)                                                                                :Schools:Middle Schools:
    ID: 07072116.wav
    Length: 91
** Single cylinder steam engine (1860), belt drive to overhead shafting - slow and stop.                                                                                :Engines:Nineteenth Century:
    ID: 07072115.wav
    Length: 55
** Single cylinder steam engine (1860), belt drive to overhead shafting - start and run.                                                                                :Engines:Nineteenth Century:
    ID: 07072114.wav
    Length: 181
** Tangye single-cylinder engine (1860).                                                                                :Engines:Nineteenth Century:
    ID: 07072113.wav
    Length: 79
** Hydraulic pump (1870).                                                                                :Engines:Nineteenth Century:
    ID: 07072112.wav
    Length: 86
** General factory atmosphere.                                                                                :Factories:Nineteenth Century:
    ID: 07072111.wav
    Length: 159
** Large type vertical triple expansion steam engine, constant run.                                                                                :Engines:Steam:
    ID: 07072110.wav
    Length: 211
** Single cylinder horizontal uniform flow (1925, 583WHP, 130rpm)- start, constant run, stop.                                                                                :Engines:Steam:
    ID: 07072109.wav
    Length: 132
** Single cylinder horizontal uniform flow (1925, 583WHP, 130rpm)- start and run.                                                                                :Engines:Steam:
    ID: 07072108.wav
    Length: 34
** W.H.Allen steam generator.                                                                                :Engines:Steam:
    ID: 07072107.wav
    Length: 248
** Compound rotative horizontal beam steam engine: start, constant run, stop - occaisional voices in background.                                                                                :Engines:Steam:
    ID: 07072106.wav
    Length: 262
** Triple-expansion marine-type steam engine (1911) - constant run with slow down and speed up.                                                                                :Engines:Steam:
    ID: 07072105.wav
    Length: 125
** Triple-expansion marine-type steam engine (1911) - start by donkey engine.                                                                                :Engines:Steam:
    ID: 07072104.wav
    Length: 300
** Ingersoll Rand air compressor - slow down and stop.                                                                                :Engines:Compressors:
    ID: 07072103.wav
    Length: 8
** Ingersoll Rand air compressor - start and run.                                                                                :Engines:Compressors:
    ID: 07072102.wav
    Length: 142
** 3 Ruston Hornsey YEX 6 pumping engines - slow and stop.                                                                                :Pumps:Diesel:
    ID: 07072101.wav
    Length: 13
** 3 Ruston Hornsey YEX 6 pumping engines - start and run.                                                                                :Pumps:Diesel:
    ID: 07072100.wav
    Length: 126
** Ruston Hornsey YEX 6 pumping engines - slow down and stop.                                                                                :Pumps:Diesel:
    ID: 07072099.wav
    Length: 10
** Ruston Hornsey YEX 6 pumping engines - start and run.                                                                                :Pumps:Diesel:
    ID: 07072098.wav
    Length: 115
** Worthington Simpson pumping engine (1929) - constant run.                                                                                :Pumps:Diesel:
    ID: 07072097.wav
    Length: 183
** 2-stroke petrol engine driving small elavator - starts, runs, stops.                                                                                :Engines:Petrol:
    ID: 07072096.wav
    Length: 170
** 2 and a quarter h.p. 4-stroke petrol engine, starts, constant run, driving small compressor.                                                                                :Engines:Petrol:
    ID: 07072095.wav
    Length: 199
** 2 and a quarter h.p. 4-stroke petrol engine, constant run.                                                                                :Engines:Petrol:
    ID: 07072094.wav
    Length: 162
** Steam pumping machine, slow run, slow down and stop with final puffs.                                                                                :Pumps:Steam:
    ID: 07072093.wav
    Length: 72
** Steam pumping machine, start and slow run with puffing steam.                                                                                :Pumps:Steam:
    ID: 07072092.wav
    Length: 40
** Steam pumping machine, slow down and stop.                                                                                :Pumps:Steam:
    ID: 07072091.wav
    Length: 53
** Steam pumping machine, start and run occaisional voices.                                                                                :Pumps:Steam:
    ID: 07072090.wav
    Length: 164
** Old gear-driven electric pug mill engine - constant run.                                                                                :Engines:Electric:
    ID: 07072089.wav
    Length: 146
** Gas engine (1920) 35h.p. - start and run.                                                                                :Engines:Gas:
    ID: 07072088.wav
    Length: 131
** Ingersoll Rand compressor (1896) - belt drive, start and stop.                                                                                :Engines:Compressors:
    ID: 07072087.wav
    Length: 132
** Single cylinder compressor - belt drive, start and stop.                                                                                :Engines:Compressors:
    ID: 07072086.wav
    Length: 148
** Single 5" sewage pump, start and stop.                                                                                :Pumps:Diesel:
    ID: 07072085.wav
    Length: 124
** 3 14" diesel sewage pumps, start and stop.                                                                                :Pumps:Diesel:
    ID: 07072084.wav
    Length: 119
** General interior atmosphere on rig (some voices). 1970.                                                                                :Gas:North Sea:
    ID: 07072083.wav
    Length: 237
** Mud filter. 1970.                                                                                :Gas:North Sea:
    ID: 07072082.wav
    Length: 46
** Drilling floor. 1970.                                                                                :Gas:North Sea:
    ID: 07072081.wav
    Length: 242
** Rig background. 1970.                                                                                :Gas:North Sea:
    ID: 07072080.wav
    Length: 53
** Pipe-laying machinery. 1970.                                                                                :Gas:North Sea:
    ID: 07072079.wav
    Length: 107
** Trench excavator working. 1970.                                                                                :Gas:North Sea:
    ID: 07072078.wav
    Length: 55
** Pipes rotating on rollers. 1970.                                                                                :Gas:North Sea:
    ID: 07072077.wav
    Length: 28
** Shop floor crane lifting finished pipes. 1970.                                                                                :Gas:North Sea:
    ID: 07072076.wav
    Length: 114
** Final coating. 1970.                                                                                :Gas:North Sea:
    ID: 07072075.wav
    Length: 90
** Shot blasting. 1970.                                                                                :Gas:North Sea:
    ID: 07072074.wav
    Length: 71
** Coating interior of pipes. 1970.                                                                                :Gas:North Sea:
    ID: 07072073.wav
    Length: 85
** Paintshop - coating pipes. 1970.                                                                                :Gas:North Sea:
    ID: 07072072.wav
    Length: 59
** Box purifier. 1971.                                                                                :Gasworks:
    ID: 07072071.wav
    Length: 185
** Steam hammer. 1971.                                                                                :Hammers:Steam:
    ID: 07072070.wav
    Length: 147
** Exhauster. 1971.                                                                                :Gasworks:
    ID: 07072069.wav
    Length: 154
** Loading coke on to lorries. 1971.                                                                                :Lorries:Loading:
    ID: 07072068.wav
    Length: 146
** Fan booster switched off.                                                                                :Gasworks:
    ID: 07072067.wav
    Length: 189
** Retort house. 1971.                                                                                :Gasworks:
    ID: 07072066.wav
    Length: 189
** Retort house. 1971.                                                                                :Gasworks:
    ID: 07072065.wav
    Length: 169
** Coke grader. 1971.                                                                                :Gasworks:
    ID: 07072064.wav
    Length: 287
** Crane moving on caterpillar tracks. 1971.                                                                                :Cranes:
    ID: 07072063.wav
    Length: 133
** Cranes re-piling coke. 1971.                                                                                :Cranes:
    ID: 07072062.wav
    Length: 137
** 2 lorries crossing weighbridge. 1971.                                                                                :Lorries:Weighbridges:
    ID: 07072061.wav
    Length: 88
** Shunting empty trucks. 1971.                                                                                :Gasworks:
    ID: 07072060.wav
    Length: 97
** Conveying coke to hoppers. 1971.                                                                                :Gasworks:
    ID: 07072059.wav
    Length: 186
** Filling sacks with coke. 1971.                                                                                :Gasworks:
    ID: 07072058.wav
    Length: 141
** Boiler alarm blowing off. 1971.                                                                                :Alarms:
    ID: 07072057.wav
    Length: 15
** Cleaning a producer fire. 1971.                                                                                :Gasworks:
    ID: 07072056.wav
    Length: 146
** Filling retort with coal from hoppers. 1971.                                                                                :Gasworks:
    ID: 07072055.wav
    Length: 79
** Governor house (later) - machinery starts up. 1971.                                                                                :Gasworks:
    ID: 07072054.wav
    Length: 193
** Governor house (early morning) - general atmosphere. 1971.                                                                                :Gasworks:
    ID: 07072053.wav
    Length: 163
** 4 men walking in single file along small passage.                                                                                :Caves:Caving:
    ID: 07072052.wav
    Length: 221
** 4 men walking slowly in dry passage, wearing nailed boots.                                                                                :Caves:Caving:
    ID: 07072051.wav
    Length: 120
** 4 men walking in dry passage (constant)                                                                                :Caves:Caving:
    ID: 07072050.wav
    Length: 118
** Man in 30ft drainpipe crawling away, in steel toe caps. Faster                                                                                :Caves:Caving:
    ID: 07072049.wav
    Length: 71
** Man in 30ft drainpipe crawling away from microphone.                                                                                :Caves:Caving:
    ID: 07072048.wav
    Length: 128
** 2 men on 30ft drainpipe moving fast (some mic bumps in keeping with sound).                                                                                :Caves:Caving:
    ID: 07072047.wav
    Length: 111
** Man in 50ft drainpipe approaching microphone.                                                                                :Caves:Caving:
    ID: 07072046.wav
    Length: 130
** Boulders falling into 70ft cavern (5 takes).                                                                                :Caves:Caving:
    ID: 07072045.wav
    Length: 43
** Small boulders falling and rolling (6 takes).                                                                                :Caves:Caving:
    ID: 07072044.wav
    Length: 55
** Stones falling down 60ft pot hole (6 takes).                                                                                :Caves:Caving:
    ID: 07072043.wav
    Length: 43
** Man descending ladder.                                                                                :Caves:Caving:
    ID: 07072042.wav
    Length: 110
** Man climbing ladder faster.                                                                                :Caves:Caving:
    ID: 07072041.wav
    Length: 94
** Man climbing ladder (rubber boots).                                                                                :Caves:Caving:
    ID: 07072040.wav
    Length: 99
** Signal sequence, whistles: one blast means stop, two means pull up, three means let down.                                                                                :Caves:Caving:
    ID: 07072039.wav
    Length: 12
** Single stone falling.                                                                                :Caves:Caving:
    ID: 07072038.wav
    Length: 3
** Single rock falling.                                                                                :Caves:Caving:
    ID: 07072037.wav
    Length: 3
** Single stone falling.                                                                                :Caves:Caving:
    ID: 07072036.wav
    Length: 3
** 1 man climbing and slipping.                                                                                :Caves:Caving:
    ID: 07072035.wav
    Length: 15
** 1 man climbing rock face.                                                                                :Caves:Caving:
    ID: 07072034.wav
    Length: 36
** 1 man climbing with start and stop.                                                                                :Caves:Caving:
    ID: 07072033.wav
    Length: 13
** Woman climbing with start and stop.                                                                                :Caves:Caving:
    ID: 07072032.wav
    Length: 28
** 1 man walking (tired with start and stop).                                                                                :Caves:Caving:
    ID: 07072031.wav
    Length: 40
** 2 men walking (tired with start and stop).                                                                                :Caves:Caving:
    ID: 07072030.wav
    Length: 39
** 2 men constant walking up sharp incline of loose stone.                                                                                :Caves:Caving:
    ID: 07072029.wav
    Length: 37
** 1 man constant walking up sharp incline of loose stone.                                                                                :Caves:Caving:
    ID: 07072028.wav
    Length: 57
** 2 men crawling along small passage.                                                                                :Caves:Caving:
    ID: 07072027.wav
    Length: 110
** 1 man crawling along small passage (approach and pass).                                                                                :Caves:Caving:
    ID: 07072026.wav
    Length: 41
** Group walking through large chamber.                                                                                :Caves:Caving:
    ID: 07072025.wav
    Length: 67
** Group walking through small chamber (with stop and start).                                                                                :Caves:Caving:
    ID: 07072024.wav
    Length: 99
** Water running in cavern, close perspective.                                                                                :Caves:Caving:
    ID: 07072023.wav
    Length: 33
** Water dripping in cavern, distant perspective.                                                                                :Caves:Caving:
    ID: 07072022.wav
    Length: 40
** Water running in cavern, close perspective.                                                                                :Caves:Caving:
    ID: 07072021.wav
    Length: 54
** Water running in cavern, medium perspective.                                                                                :Caves:Caving:
    ID: 07072020.wav
    Length: 59
** Man climbing ladder with rubber boots and steel toe caps.                                                                                :Caves:Caving:
    ID: 07072019.wav
    Length: 70
** Hauling ladder up, medium perspective.                                                                                :Caves:Caving:
    ID: 07072018.wav
    Length: 73
** Hauling ladder up, close perspective.                                                                                :Caves:Caving:
    ID: 07072017.wav
    Length: 86
** Ladder thrown down pitch, medium perspective.                                                                                :Caves:Caving:
    ID: 07072016.wav
    Length: 5
** Ladder thrown down pitch, close perspective.                                                                                :Caves:Caving:
    ID: 07072015.wav
    Length: 6
** Unrolling wire ladder at top of 60ft pitch.                                                                                :Caves:Caving:
    ID: 07072014.wav
    Length: 66
** Stream trickling through small cavern, close perspective.                                                                                :Caves:Caving:
    ID: 07072013.wav
    Length: 107
** Water running into underground lake.                                                                                :Caves:Caving:
    ID: 07072012.wav
    Length: 118
** 20ft waterfall, microphone at bottom.                                                                                :Caves:Caving:
    ID: 07072011.wav
    Length: 111
** 20ft waterfall, microphone at top.                                                                                :Caves:Caving:
    ID: 07072010.wav
    Length: 115
** 40ft waterfall, microphone at top.                                                                                :Caves:Caving:
    ID: 07072009.wav
    Length: 90
** 40ft waterfall (use at low level).                                                                                :Caves:Caving:
    ID: 07072008.wav
    Length: 119
** Stream, microphone in cave (use at low level).                                                                                :Caves:Caving:
    ID: 07072007.wav
    Length: 118
** Stream entering cave (slight wind noise on microphone).                                                                                :Caves:Caving:
    ID: 07072006.wav
    Length: 115
** Small stream running through field.                                                                                :Caves:Caving:
    ID: 07072005.wav
    Length: 180
** Water gurgling down drain.                                                                                :Caves:Caving:
    ID: 07072004.wav
    Length: 36
** Water running and stopping in cavern.                                                                                :Caves:Caving:
    ID: 07072003.wav
    Length: 168
** Water running into large drain.                                                                                :Caves:Caving:
    ID: 07072002.wav
    Length: 150
** Water surging into cave.                                                                                :Caves:Caving:
    ID: 07072001.wav
    Length: 120
** Shunting in a steam railway goods yard.                                                                                :Trains:Goods Yards:
    ID: 07071161.wav
    Length: 299
** Coupling trucks - use at low level, in a steam railway goods yard.                                                                                :Trains:Goods Yards:
    ID: 07071160.wav
    Length: 65
** Shutting side of steel truck in steam railway goods yard.                                                                                :Trains:Goods Yards:
    ID: 07071159.wav
    Length: 3
** Dropping side of steel truck in steam railway goods yard.                                                                                :Trains:Goods Yards:
    ID: 07071158.wav
    Length: 10
** Shutting side of wooden truck in steam railway goods yard.                                                                                :Trains:Goods Yards:
    ID: 07071157.wav
    Length: 6
** Dropping side of wooden truck in steam railway goods yard.                                                                                :Trains:Goods Yards:
    ID: 07071156.wav
    Length: 17
** Shunting with diesel electric locomotive.                                                                                :Trains:Diesel Electric:
    ID: 07071155.wav
    Length: 199
** Diesel train passing over level crossing.                                                                                :Trains:Diesel:
    ID: 07071154.wav
    Length: 26
** Diesel freight train passing over level crossing.                                                                                :Trains:Diesel:
    ID: 07071153.wav
    Length: 47
** Pedestrians' gate opened & closed several times.                                                                                :Trains:Level Crossings:
    ID: 07071152.wav
    Length: 20
** Level crossing gates closed mechanically from signal box - as heard from box.                                                                                :Trains:Level Crossings:
    ID: 07071151.wav
    Length: 20
** Level crossing gates opened mechanically from signal box - as heard from box.                                                                                :Trains:Level Crossings:
    ID: 07071150.wav
    Length: 22
** Train passes - level crossing gates opened by hand, traffic resumes.                                                                                :Trains:Level Crossings:
    ID: 07071149.wav
    Length: 63
** Diesel trains shunting.                                                                                :Trains:Diesel:
    ID: 07071148.wav
    Length: 266
** Sound of platelayers' trolley - approaching.                                                                                :Trains:Goods Yards:
    ID: 07071147.wav
    Length: 19
** Sound of platelayers' trolley - departing.                                                                                :Trains:Goods Yards:
    ID: 07071146.wav
    Length: 29
** Sound of platelayers' trolley - constant run.                                                                                :Trains:Goods Yards:
    ID: 07071145.wav
    Length: 86
** Wheel tapping in progress, testing wheels for defects - with brakes on.                                                                                :Trains:Steam:
    ID: 07071144.wav
    Length: 93
** Wheel tapping in progress, testing wheels for defects - with brakes off.                                                                                :Trains:Steam:
    ID: 07071143.wav
    Length: 119
** Railway breakdown crane operating.                                                                                :Trains:Goods Yards:
    ID: 07071142.wav
    Length: 197
** Atmosphere in manual signal box.                                                                                :Trains:Signal Boxes:
    ID: 07071141.wav
    Length: 179
** Raking coal in hopper.                                                                                :Trains:Goods Yards:
    ID: 07071140.wav
    Length: 104
** Approach of light engine, signals received and acknowledged.                                                                                :Trains:Signal Boxes:
    ID: 07071139.wav
    Length: 26
** Approach of express freight train with signal received and acknowledged .                                                                                :Trains:Signal Boxes:
    ID: 07071138.wav
    Length: 34
** Approach of passenger train, signal received and acknowledged.                                                                                :Trains:Signal Boxes:
    ID: 07071137.wav
    Length: 33
** Signal box closing down, with signal received and acknowledged.                                                                                :Trains:Signal Boxes:
    ID: 07071136.wav
    Length: 13
** Signal box opening with signal received and acknowledged.                                                                                :Trains:Signal Boxes:
    ID: 07071135.wav
    Length: 12
** Continental-type level crossing. Car crosses, bell, train passes, traffic resumes.                                                                                :Trains:Diesel:
    ID: 07071134.wav
    Length: 64
** Continental-type level crossing - bell, train crosses.                                                                                :Trains:Diesel:
    ID: 07071133.wav
    Length: 82
** Siren sounded 3 times, train stationary.                                                                                :Trains:Diesel:
    ID: 07071132.wav
    Length: 15
** Siren sounded 3 times, train stationary.                                                                                :Trains:Diesel:
    ID: 07071131.wav
    Length: 15
** Siren sounded once (multiple), train stationary.                                                                                :Trains:Diesel:
    ID: 07071130.wav
    Length: 17
** Siren sounded 2 times, train stationary.                                                                                :Trains:Diesel:
    ID: 07071129.wav
    Length: 13
** Siren sounded 3 times, train stationary.                                                                                :Trains:Diesel:
    ID: 07071128.wav
    Length: 13
** Siren sounded 2 times, train stationary.                                                                                :Trains:Diesel:
    ID: 07071127.wav
    Length: 14
** Exterior - passes with siren.                                                                                :Trains:Diesel Electric:
    ID: 07071126.wav
    Length: 44
** Exterior - departs from station.                                                                                :Trains:Diesel Electric:
    ID: 07071125.wav
    Length: 76
** Exterior - tickover.                                                                                :Trains:Diesel Electric:
    ID: 07071124.wav
    Length: 176
** Exterior - slow down and stop.                                                                                :Trains:Diesel Electric:
    ID: 07071123.wav
    Length: 87
** Exterior - arrives in station, tickover.                                                                                :Trains:Diesel Electric:
    ID: 07071122.wav
    Length: 77
** Exterior - fast constant run.                                                                                :Trains:Diesel Electric:
    ID: 07071121.wav
    Length: 224
** Interior - tickover, depart from station, gathering speed.                                                                                :Trains:Diesel Electric:
    ID: 07071120.wav
    Length: 267
** Exterior - doors, tickover, guards whistle, departs, multiple unit diesel train.                                                                                :Trains:Diesel:
    ID: 07071119.wav
    Length: 147
** Interior - tickover into constant run with carriage creaks, multiple unit diesel train.                                                                                :Trains:Diesel:
    ID: 07071118.wav
    Length: 300
** Interior - move off into constant run with marked rhythm, multiple unit diesel train.                                                                                :Trains:Diesel:
    ID: 07071117.wav
    Length: 210
** Brighton station - general atmosphere.                                                                                :Trains:Stations:
    ID: 07071116.wav
    Length: 234
** Several teleprinters receiving, 1968.                                                                                :Offices:Teleprinters:
    ID: 07071115.wav
    Length: 180
** Single teleprinter receiving, 1968.                                                                                :Offices:Teleprinters:
    ID: 07071114.wav
    Length: 186
** Single teleprinter sending, 1968.                                                                                :Offices:Teleprinters:
    ID: 07071113.wav
    Length: 186
** 6 typewriters, 1968.                                                                                :Offices:Typewriters:
    ID: 07071112.wav
    Length: 180
** Single typewriter, 1968.                                                                                :Offices:Typewriters:
    ID: 07071111.wav
    Length: 190
** General computer room atmosphere with printer in foreground.                                                                                :Computers:
    ID: 07071110.wav
    Length: 204
** Card reader, 1968.                                                                                :Computers:
    ID: 07071109.wav
    Length: 86
** ICT sorter, 1968.                                                                                :Computers:
    ID: 07071108.wav
    Length: 115
** ICT collator, 1968.                                                                                :Computers:
    ID: 07071107.wav
    Length: 150
** General atmosphere in an office printing unit with equipment operating, 1968.                                                                                :Offices:Printers:
    ID: 07071106.wav
    Length: 180
** General post room atmosphere.                                                                                :Offices:Post Rooms:
    ID: 07071105.wav
    Length: 180
** Photo-direct camera processor (photographic reproducer), 1968.                                                                                :Offices:Reproducers:
    ID: 07071104.wav
    Length: 107
** Gordon gotch collating machine (stacks printed sheets), 1968.                                                                                :Offices:Printers:
    ID: 07071103.wav
    Length: 118
** Roneo duplicator - several short runs & stops, 1968.                                                                                :Offices:Duplicators:
    ID: 07071102.wav
    Length: 109
** Roneo duplicator - long run & stops, 1968.                                                                                :Offices:Duplicators:
    ID: 07071101.wav
    Length: 109
** Multilith 1250 printing machine, 1968.                                                                                :Offices:Printers:
    ID: 07071100.wav
    Length: 102
** Multilith 85 printing machine, 1968.                                                                                :Offices:Printers:
    ID: 07071099.wav
    Length: 114
** Rotoprint machine, 1966.                                                                                :Offices:Printers:
    ID: 07071098.wav
    Length: 180
** One adding machine, 1966.                                                                                :Offices:Adding Machines:
    ID: 07071097.wav
    Length: 161
** Two key punches, 1966.                                                                                :Offices:Punches:
    ID: 07071096.wav
    Length: 152
** Auto key punch, 1966.                                                                                :Offices:Punches:
    ID: 07071095.wav
    Length: 158
** Reproducer, 1966.                                                                                :Offices:Reproducers:
    ID: 07071094.wav
    Length: 164
** Card sorter, 1966.                                                                                :Offices:Card Sorters:
    ID: 07071093.wav
    Length: 158
** Interpolator, 1966.                                                                                :Offices:Interpolators:
    ID: 07071092.wav
    Length: 130
** Interpreter, 1966.                                                                                :Offices:Interpreters:
    ID: 07071091.wav
    Length: 201
** Electronic punch, 1966.                                                                                :Offices:Punches:
    ID: 07071090.wav
    Length: 162
** Tabulator, 1966.                                                                                :Offices:Tabulators:
    ID: 07071089.wav
    Length: 155
** Referees whistle: short, double, long, longer 1", 1" 1", 2" - 1968 (169A, reprocessed)                                                                                :Whistles:Comedy:
    ID: 07071088.wav
    Length: 10
** Police whistle: single, double, treble 1", 2", 4" - 1968 (169A, reprocessed)                                                                                :Whistles:Comedy:
    ID: 07071087.wav
    Length: 13
** Tuneless whistling - 1968 (169A, reprocessed)                                                                                :Whistles:Comedy:
    ID: 07071086.wav
    Length: 136
** Five finger whistles - 1968 (169A, reprocessed)                                                                                :Whistles:Comedy:
    ID: 07071085.wav
    Length: 13
** Wolf whistles - 1968 (169A, reprocessed)                                                                                :Whistles:Comedy:
    ID: 07071084.wav
    Length: 10
** Slow whipping, interior - 1974 (199A, reprocessed)                                                                                :Whiplashes:Comedy:
    ID: 07071083.wav
    Length: 70
** Fast whipping, interior - 1974 (199A, reprocessed)                                                                                :Whiplashes:Comedy:
    ID: 07071082.wav
    Length: 13
** Busy workshop atmosphere - 1972 (7M, reprocessed)                                                                                :Workshops:Comedy:
    ID: 07071081.wav
    Length: 19
** Oriental workshop - 1967 (7E, reprocessed)                                                                                :Workshops:Comedy:
    ID: 07071080.wav
    Length: 32
** One whoosh, two whooshes 1", 1" - 1967 (7D, reprocessed)                                                                                :Whooshes:Comedy:
    ID: 07071079.wav
    Length: 5
** Three whooshes with ripping fabric - 1967 (7B, reprocessed)                                                                                :Whooshes:Comedy:
    ID: 07071078.wav
    Length: 18
** Pouring liquid - 1968 (7H, reprocessed)                                                                                :Water:Comic:
    ID: 07071077.wav
    Length: 34
** Water dripping (with echo, reprocessed)  - 1967 (7F, reprocessed)                                                                                :Water:Comic:
    ID: 07071076.wav
    Length: 66
** Lava bubbling - 1967 (7B, reprocessed)                                                                                :Volcanoes:Comedy:
    ID: 07071075.wav
    Length: 68
** Typing with three hands - 1972 (7K, reprocessed)                                                                                :Typewriters:Comedy:
    ID: 07071074.wav
    Length: 91
** Jews harp sequence - 1970 (7J, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071073.wav
    Length: 20
** Twangs made using wooden ruler - 1970 (7J, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071072.wav
    Length: 21
** Sounding like twangs on a metal ruler - 1967 (7F, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071071.wav
    Length: 16
** Squeaky trolley bumped along - 1967 (7B, reprocessed)                                                                                :Trolleys:Comedy:
    ID: 07071070.wav
    Length: 49
** Squeaky trolley - 1967 (7B)                                                                                :Trolleys:Comedy:
    ID: 07071069.wav
    Length: 45
** One tree sagging and crashing into water - 1972 (7K, reprocessed)                                                                                :Trees:Comedy:
    ID: 07071068.wav
    Length: 12
** Sawing tree and crash - 1967 (7C, reprocessed)                                                                                :Trees:Comedy:
    ID: 07071067.wav
    Length: 17
** Train crash - 1967 (7B, reprocessed)                                                                                :Trains:Comic:
    ID: 07071066.wav
    Length: 9
** Traffic jam with moving traffic - 1968 (7H, reprocessed)                                                                                :Traffic:Comedy:
    ID: 07071065.wav
    Length: 23
** Traffic jam - 1968 (7H, reprocessed)                                                                                :Traffic:Comedy:
    ID: 07071064.wav
    Length: 16
** Colliding traffic with horns - 1967 (7C, reprocessed)                                                                                :Traffic:Comedy:
    ID: 07071063.wav
    Length: 34
** High speed telephone gibberish - 1967 (7E, reprocessed)                                                                                :Telephones:Comedy:
    ID: 07071062.wav
    Length: 2
** Paddle steamer rhythm - 1967 (7F, reprocessed)                                                                                :Boats:Comic:
    ID: 07071061.wav
    Length: 41
** One ship colliding - 1967 (7D, reprocessed)                                                                                :Boats:Comic:
    ID: 07071060.wav
    Length: 16
** Sawing stale bread - 1967 (7C, reprocessed)                                                                                :Saws:Comedy:
    ID: 07071059.wav
    Length: 20
** Rocket ship landing - 1967 (7D, reprocessed)                                                                                :Rocket Ships:Comedy:
    ID: 07071058.wav
    Length: 31
** Rocket ship flying - 1967 (7D, reprocessed)                                                                                :Rocket Ships:Comedy:
    ID: 07071057.wav
    Length: 21
** Rocket ship takes off - 1967 (7D, reprocessed)                                                                                :Rocket Ships:Comedy:
    ID: 07071056.wav
    Length: 47
** Rocket ship exploding - 1967 (7D, reprocessed)                                                                                :Rocket Ships:Comedy:
    ID: 07071055.wav
    Length: 10
** Radiophionic stomach - sequence of sounds including explosion, whoosh, bubbling and belch - 1972 (7K, reprocessed)                                                                                :Comedy:Radiophonic Stomach:
    ID: 07071054.wav
    Length: 11
** Single projectile approach and richochet - 1967 (7C, reprocessed)                                                                                :Projectiles:Comedy:
    ID: 07071053.wav
    Length: 24
** Portcullis closing - 1972 (7M, reprocessed)                                                                                :Portcullis:Comedy:
    ID: 07071052.wav
    Length: 5
** Crash of piano - 1968 (7H, reprocessed)                                                                                :Pianos:Comedy:
    ID: 07071051.wav
    Length: 11
** Man dragged out of piano - 1967 (7C, reprocessed)                                                                                :Pianos:Comedy:
    ID: 07071050.wav
    Length: 10
** One piano dragged along - 1967 (7B, reprocessed)                                                                                :Pianos:Comedy:
    ID: 07071049.wav
    Length: 73
** One penny dropped - 1968 (7H, reprocessed)                                                                                :Pennies:Comedy:
    ID: 07071048.wav
    Length: 6
** Falling pennies - 1967 (7D, reprocessed)                                                                                :Pennies:Comedy:
    ID: 07071047.wav
    Length: 35
** Standard orgy with smashing glass, screams, footsteps and whipping sounds - 1972 (7K, reprocessed)                                                                                :Orgies:Comedy:
    ID: 07071046.wav
    Length: 26
** Tank riveter - 1970 (7J, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071045.wav
    Length: 64
** Hand operated sewing machine - 1970 (7J, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071044.wav
    Length: 68
** Sausage counter - 1970 (7J, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071043.wav
    Length: 63
** Coconut milk extractor - 1970 (7J, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071042.wav
    Length: 52
** Coathanger bender - 1970 (7J, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071041.wav
    Length: 42
** Clockwork airship inflator - 1970 (7J, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071040.wav
    Length: 43
** Bottle top tester - 1970 (7J, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071039.wav
    Length: 57
** Cod machinery - 1967 (7D, reprocessed)                                                                                :Machines:Comedy:
    ID: 07071038.wav
    Length: 28
** Experimental laboratory - 1967 (7D, reprocessed)                                                                                :Laboratories:Comedy:
    ID: 07071037.wav
    Length: 37
** Busy jungle atmosphere - 1967 (7D, reprocessed)                                                                                :Jungles:Comedy:
    ID: 07071036.wav
    Length: 55
** Studio Indians whooping - 1967 (7C, reprocessed)                                                                                :Indians:Comedy:
    ID: 07071035.wav
    Length: 35
** Razz, nazz, bang, jangle - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071034.wav
    Length: 3
** Wallop, clang, jangle - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071033.wav
    Length: 3
** Whizz, clong - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071032.wav
    Length: 3
** Razz rhythm clang - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071031.wav
    Length: 6
** Bong, doying: jews harp - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071030.wav
    Length: 8
** Doying, pop, cloying - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071029.wav
    Length: 4
** Whoosh, bing, bang, doying - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071028.wav
    Length: 3
** Clong bong doying - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071027.wav
    Length: 2
** Jangle flong - 1967 (7A, reprocessed)                                                                                :Impact Rhythms:Comedy:
    ID: 07071026.wav
    Length: 2
** Ice creaking and cracking - 1972 (7K, reprocessed)                                                                                :Ice:Comedy:
    ID: 07071025.wav
    Length: 10
** Maniacal laughter (male and female, reprocessed)  - 1969 (169C, reprocessed)                                                                                :Comedy:Laughs:
    ID: 07071024.wav
    Length: 40
** One woman, uncontrolled sobbing - 1968 (169A, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071023.wav
    Length: 59
** One woman snoring - 1980 (169B, reprocessed)                                                                                :Comedy:Snores:
    ID: 07071022.wav
    Length: 91
** One woman, two burlesque screams 7", 7" - 1968 (169A, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071021.wav
    Length: 15
** One woman, two screams at apparition 14", 5" - 1968 (169A, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071020.wav
    Length: 20
** One woman, two long screams 8", 9" - 1968 (169A, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071019.wav
    Length: 18
** One woman, three fairly short screams - 1968 (169A, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071018.wav
    Length: 10
** One woman hysterical crying - 1968 (169A, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071017.wav
    Length: 55
** Heavy female breathing - 1980 (169B, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071016.wav
    Length: 75
** Several men snoring less hilariously - 1967 (7F, reprocessed)                                                                                :Comedy:Snores:
    ID: 07071015.wav
    Length: 63
** Several men snoring hilariously - 1967 (7F, reprocessed)                                                                                :Comedy:Snores:
    ID: 07071014.wav
    Length: 66
** Several men snoring - 1967 (7F, reprocessed)                                                                                :Comedy:Snores:
    ID: 07071013.wav
    Length: 35
** One man continuous snoring - 1972 (7M, reprocessed)                                                                                :Comedy:Snores:
    ID: 07071012.wav
    Length: 14
** One man snoring - 1980 (169B, reprocessed)                                                                                :Comedy:Snores:
    ID: 07071011.wav
    Length: 73
** One man snoring - 1967 (7F, reprocessed)                                                                                :Comedy:Snores:
    ID: 07071010.wav
    Length: 22
** One man screaming 3"; one man screaming twice 7"- 1980 (169B, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071009.wav
    Length: 13
** Six men groaning -1969 (169C, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071008.wav
    Length: 41
** One man groaning - 1969 (169C, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071007.wav
    Length: 26
** Several men coughing -1980 (7H, reprocessed)                                                                                :Comedy:Coughing and Spitting:
    ID: 07071006.wav
    Length: 15
** One male coughing - 1980 (169B, reprocessed)                                                                                :Comedy:Coughing and Spitting:
    ID: 07071005.wav
    Length: 61
** Heavy male breathing - 1980 (169B, reprocessed)                                                                                :Human Effects:Comic:
    ID: 07071004.wav
    Length: 55
** Six belches 1",1",1",2",2",2" - 1980 (169B, reprocessed)                                                                                :Comedy:Burps:
    ID: 07071003.wav
    Length: 18
** Single Belch - 1967 (7A, reprocessed)                                                                                :Comedy:Burps:
    ID: 07071002.wav
    Length: 3
** Hammer testing - 1968 (7H, reprocessed)                                                                                :Hammers:Comic:
    ID: 07071001.wav
    Length: 21
** New York - Police sirens, continuous burble.                                                                                :Police:Cars:
    ID: 07070229.wav
    Length: 123
** New York - Times Square, busy traffic.                                                                                :New York:
    ID: 07070228.wav
    Length: 188
** Lapping water in marshes, St Simon's Island, Georgia.                                                                                :Marshes:
    ID: 07070227.wav
    Length: 120
** Mockingbirds at coastguard station, St Simon's Island, Georgia.                                                                                :Birds:Mocking Birds:
    ID: 07070226.wav
    Length: 135
** Birds near sea - St Simons Island, Georgia.                                                                                :Birds:
    ID: 07070225.wav
    Length: 222
** Night - cicadas in Boca Raton, Florida.                                                                                :America:Florida:
    ID: 07070224.wav
    Length: 262
** Freeway (nr Fort Lauderdale, Florida)                                                                                :America:Florida:
    ID: 07070223.wav
    Length: 141
** Distant train siren.                                                                                :Trains:America:
    ID: 07070222.wav
    Length: 13
** Long passenger train passes with siren (Folkston, Georgia)                                                                                :Trains:America:
    ID: 07070221.wav
    Length: 120
** Long freight train passes (Folkston, Georgia)                                                                                :Trains:America:
    ID: 07070220.wav
    Length: 107
** Birds by courthouse (Folkston, Georgia)                                                                                :Birds:
    ID: 07070219.wav
    Length: 152
** Quiet roadside (Folkston, Georgia)                                                                                :Roadsides:
    ID: 07070218.wav
    Length: 126
** Restaurant (Folkston, Georgia)                                                                                :Restaurants:North America:
    ID: 07070217.wav
    Length: 205
** Cafe (Folkston, Georgia)                                                                                :Cafes:America:
    ID: 07070216.wav
    Length: 197
** Evangelical church congregation - restless (Georgia)                                                                                :Churches:America:
    ID: 07070215.wav
    Length: 275
** Steam boat journey with paddle wash (Mississippi)                                                                                :Mississippi River:
    ID: 07070214.wav
    Length: 206
** Steam boat departure with hooters & announcements (Mississippi)                                                                                :Boats:Hooters:
    ID: 07070213.wav
    Length: 123
** Steam boat hooter (Mississippi)                                                                                :Boats:Hooters:
    ID: 07070212.wav
    Length: 8
** By the Mississippi river.                                                                                :Rivers:
    ID: 07070211.wav
    Length: 210
** Street car - doors close, interior run, alight (New Orleans)                                                                                :Trams:
    ID: 07070210.wav
    Length: 199
** French market (New Orleans)                                                                                :New Orleans:
    ID: 07070209.wav
    Length: 199
** Crowded street (New Orleans)                                                                                :New Orleans:
    ID: 07070208.wav
    Length: 217
** Noisy street with youths chanting & calling.                                                                                :New Orleans:
    ID: 07070207.wav
    Length: 202
** Quiet side street (New Orleans)                                                                                :New Orleans:
    ID: 07070206.wav
    Length: 149
** Restaurant Kitchen atmosphere, with cooks chatting, food prepartion & cooking sounds, extractor fan & parking attendant blowing whistle outside.                                                                                :Kitchens:
    ID: 07070205.wav
    Length: 196
** Don Muang International Airport, atmopshere on departures concourse with voices, footsteps, P.A. system, flight indicator board & trolleys.                                                                                :Airports:
    ID: 07070204.wav
    Length: 198
** Thai Diesel Express Train, interior, atmosphere in third class carriage, constant run with open windows & on board vendors, slow & stop with squeaking brakes, station atmosphere with P.A., bell & train horn, train starts into run.                                                                                :Trains:Diesel:
    ID: 07070203.wav
    Length: 205
** Tropical Storm, rain & heavy thunder recorded from aprtment balcony.                                                                                :Weather:Thunder And Rain:
    ID: 07070202.wav
    Length: 190
** Bangkok Riverside atmosphere, with sounds of various small boats passing , waves against banks & tubular chimes.                                                                                :Rivers:
    ID: 07070201.wav
    Length: 159
** Thai Steel Warehouse, interior, atmosphere with workers talking & calling, machinery including cranes, truck & steel being moved.                                                                                :Industry:Steel Works:
    ID: 07070200.wav
    Length: 122
** Hua Lamphong Railway Station (Bangkok's main station), interior, atmosphere with P.A. system announcements. (Recorded in early afternoon.)                                                                                :Trains:Stations:
    ID: 07070199.wav
    Length: 178
** Bangkok Skytrain System, platform atmosphere, train arrives, passengers board train, train interior, start into constant run, passenger chatter & on-board announcements.                                                                                :Trains:Electric:
    ID: 07070198.wav
    Length: 157
** Bangkok Rush Hour Atmosphere, with motor cycles, cars, buses & Skytrain system. (Recorded in centre of city.)                                                                                :Traffic:Motor:City:
    ID: 07070197.wav
    Length: 187
** Girls' Primary School, interior, children leaving classrooms.                                                                                :Schools:
    ID: 07070196.wav
    Length: 187
** Coffee Shop, interior, busy shop atmosphere with teenagers' chatter.                                                                                ::
    ID: 07070195.wav
    Length: 186
** 3rd Class Single Deck Bus, run through traffic with starts & stops, with ticket machine.                                                                                ::
    ID: 07070194.wav
    Length: 169
** Tuk Tuk travelling through Bangkok at night, run with starts & stops, quite breezy. (Three wheeled taxi.)                                                                                ::
    ID: 07070193.wav
    Length: 133
** Khao Yai National Park, monkeys in forest canopy (late morning).                                                                                :Animals:Monkeys:
    ID: 07070192.wav
    Length: 204
** Khao Yai National Park, morning insects' chorus.                                                                                :Insects:
    ID: 07070191.wav
    Length: 169
** Khao Yai National Park, nightime insects' chorus.                                                                                :Insects:
    ID: 07070190.wav
    Length: 169
** Khao Yai National Park, nightime forest atmosphere under deep canopy, very still with insects.                                                                                :Insects:
    ID: 07070189.wav
    Length: 198
** Khao Yai National Park, nightime forest atmosphere near pond with night frog chorus, insects & Park Ranger's jeep.                                                                                :Animals:Frogs:
    ID: 07070188.wav
    Length: 188
** Khao Yai National Park, with sound of insects, creek, slight breeze & swaying trees. (Recorded on edge of Khao Yai National Park.)                                                                                :Insects:
    ID: 07070187.wav
    Length: 181
** Seafood Restaurant, interior, chatter & cutlery sounds.                                                                                :Restaurants:
    ID: 07070186.wav
    Length: 180
** Chinese Buddhist Temple, exterior, atmosphere with gongs, visitors walking in grounds & tapping wishing bells.                                                                                ::
    ID: 07070185.wav
    Length: 153
** Bangkok Riverside Market, small stalls, chatter & vendors' voices.                                                                                ::
    ID: 07070184.wav
    Length: 184
** Bangkok suburban nightime skyline, with insects, distant scooters, cars & dogs.                                                                                :Skyline:
    ID: 07070183.wav
    Length: 135
** Thai Buddhist Temple, interior, approx 20 Buddhist Monks praying & chanting, with slight breeze passing through temple. (Recorded in Thailand.)                                                                                ::
    ID: 07070182.wav
    Length: 198
** Thai Boxing Match, interior, large crowd watching whole round of boxing. (Recorded at the Lumpini Stadium, Bangkok.)                                                                                :Sports:Boxing:
    ID: 07070181.wav
    Length: 198
** Martinskirken bell (Copenhagen) - call to mid-morning service                                                                                :Copenhagen:
    ID: 07070180.wav
    Length: 94
** Copenhagen City Hall - 1/4 hour                                                                                :Copenhagen:
    ID: 07070179.wav
    Length: 9
** Copenhagen City Hall - 1/2 hour                                                                                :Copenhagen:
    ID: 07070178.wav
    Length: 11
** Copenhagen City Hall - bell strikes 12                                                                                :Copenhagen:
    ID: 07070177.wav
    Length: 65
** Swiss Centre, Leicester Square - bell strikes 6 into carrillion of traditional tunes (some voices in background)                                                                                :London:Leicester Square:
    ID: 07070176.wav
    Length: 311
** St.Michael's Church, St.Albans - bell strikes 9                                                                                :Bells:Churches:
    ID: 07070175.wav
    Length: 33
** St.Albans Catherdral - 1/4 hour                                                                                :Bells:Cathedrals:
    ID: 07070174.wav
    Length: 17
** St.Albans Catherdral - bell strikes 8                                                                                :Bells:Cathedrals:
    ID: 07070173.wav
    Length: 52
** Carfax Tower, Oxford (interior perspective) - 1/2 hour                                                                                :Clocks:Striking:
    ID: 07070172.wav
    Length: 24
** Carfax Tower, Oxford (interior perspective) - 1/4 hour                                                                                :Clocks:Striking:
    ID: 07070171.wav
    Length: 17
** Carfax Tower, Oxford (interior perspective) - strikes 12                                                                                :Clocks:Striking:
    ID: 07070170.wav
    Length: 64
** Magdalen College, Oxford - 1/4 hour                                                                                :Clocks:Striking:
    ID: 07070169.wav
    Length: 13
** Magdalen College, Oxford - bell strikes 12                                                                                :Clocks:Striking:
    ID: 07070168.wav
    Length: 49
** Merton College, Oxford - 1/4 hour                                                                                :Clocks:Striking:
    ID: 07070167.wav
    Length: 28
** Merton College, Oxford - 1/2 hour                                                                                :Clocks:Striking:
    ID: 07070166.wav
    Length: 25
** Merton College, Oxford (some voices and birdsong) - bell strikes 12                                                                                :Clocks:Striking:
    ID: 07070165.wav
    Length: 75
** Tom, Christ Church, Oxford - strikes 12 (interior perspective)                                                                                :Clocks:Striking:
    ID: 07070164.wav
    Length: 78
** Car clock ticking                                                                                :Clocks:Ticking:
    ID: 07070163.wav
    Length: 156
** Digital watch alarm                                                                                :Alarms:Watches:
    ID: 07070162.wav
    Length: 20
** Portable electric alarm clock                                                                                :Clocks:Alarm:
    ID: 07070161.wav
    Length: 37
** Room full of ticking clocks                                                                                :Clocks:Ticking:
    ID: 07070160.wav
    Length: 88
** English clock (1715) - strikes 12 across halway                                                                                :Clocks:Striking:
    ID: 07070159.wav
    Length: 23
** French clock (late 19th Century) - strikes 12                                                                                :Clocks:Striking:
    ID: 07070158.wav
    Length: 18
** English Walnut clock (1700) - wound up                                                                                :Clocks:Winding Up:
    ID: 07070157.wav
    Length: 26
** English Walnut clock (1700) - strikes 12                                                                                :Clocks:Striking:
    ID: 07070156.wav
    Length: 16
** Cuckoo clock (1820) - ticking                                                                                :Clocks:Cuckoo:
    ID: 07070155.wav
    Length: 215
** Cuckoo clock (1820) - strikes 12                                                                                :Clocks:Cuckoo:
    ID: 07070154.wav
    Length: 34
** Bracket clock (1740) with gong - strikes 12                                                                                :Clocks:Gong:
    ID: 07070153.wav
    Length: 23
** Bracket with St.Michael's chimes - 3/4 hour                                                                                :Clocks:Chiming:
    ID: 07070152.wav
    Length: 10
** Bracket with St.Michael's chimes - 1/2 hour                                                                                :Clocks:Chiming:
    ID: 07070151.wav
    Length: 9
** Bracket with St.Michael's chimes - 1/4 hour                                                                                :Clocks:Chiming:
    ID: 07070150.wav
    Length: 6
** Bracket with St.Michael's chimes - strikes 12                                                                                :Clocks:Chiming:
    ID: 07070149.wav
    Length: 24
** Bracket clock (1920) with Westminster chimes - strikes 12                                                                                :Clocks:Chiming:
    ID: 07070148.wav
    Length: 59
** Grandfather clock (1680) - ticking                                                                                :Clocks:Grandfather:
    ID: 07070147.wav
    Length: 243
** Grandfather clock (1850) - strikes 12 (rapid)                                                                                :Clocks:Grandfather:
    ID: 07070146.wav
    Length: 18
** Grandfather clock (1750) - strikes 12                                                                                :Clocks:Grandfather:
    ID: 07070145.wav
    Length: 40
** Grandfather clock (1710) - strikes 12                                                                                :Clocks:Grandfather:
    ID: 07070144.wav
    Length: 28
** Mason - sanding a statue with a spinner.                                                                                :Cottage Industries:
    ID: 07070143.wav
    Length: 200
** Mason - airtool chisel.                                                                                :Cottage Industries:
    ID: 07070142.wav
    Length: 200
** Mason - malet & chisel to make statue.                                                                                :Cottage Industries:
    ID: 07070141.wav
    Length: 200
** Shoe maker - Heavy stitching.                                                                                :Cottage Industries:
    ID: 07070140.wav
    Length: 200
** Shoe maker - Light stitching.                                                                                :Cottage Industries:
    ID: 07070139.wav
    Length: 200
** Shoe maker - Skiving, cutting the leather to allow stitching.                                                                                :Cottage Industries:
    ID: 07070138.wav
    Length: 200
** Shoe maker - buffing machine.                                                                                :Cottage Industries:
    ID: 07070137.wav
    Length: 200
** Seamstress - sewing on treadle machine.                                                                                :Sewing Machines:Domestic:
    ID: 07070136.wav
    Length: 200
** Glassworks - hand blown glass.                                                                                :Glassworks:
    ID: 07070135.wav
    Length: 200
** Baker - baking.                                                                                :Cottage Industries:
    ID: 07070134.wav
    Length: 200
** Potter - making clay pots.                                                                                :Cottage Industries:
    ID: 07070133.wav
    Length: 200
** Cooper - making a barrel.                                                                                :Cottage Industries:
    ID: 07070132.wav
    Length: 200
** Grinding - sharpening tools.                                                                                :Workshops:Carpenters:
    ID: 07070131.wav
    Length: 100
** Sawing with circular saw.                                                                                :Workshops:Carpenters:
    ID: 07070130.wav
    Length: 100
** Wood turning on lathe, being polished & worked with sandpaper.                                                                                :Workshops:Carpenters:
    ID: 07070129.wav
    Length: 200
** Woodturning - pole lathe.                                                                                :Workshops:Carpenters:
    ID: 07070128.wav
    Length: 200
** Forge - blacksmith working metal.                                                                                :Blacksmith:
    ID: 07070127.wav
    Length: 200
** Flour milling - grinding.                                                                                :Cottage Industries:
    ID: 07070126.wav
    Length: 200
** Flour milling - separating machine.                                                                                :Cottage Industries:
    ID: 07070125.wav
    Length: 200
** Weaving - Hand loom                                                                                :Weaving:
    ID: 07070124.wav
    Length: 200
** Weaving - Spinning jack                                                                                :Weaving:
    ID: 07070123.wav
    Length: 200
** Weaving - Carding.                                                                                :Weaving:
    ID: 07070122.wav
    Length: 200
** Stromberg-Carlson - 6 rings, pick up.                                                                                :Telephones:Period:Stromberg-Carlson:
    ID: 07070121.wav
    Length: 26
** Stromberg-Carlson - phone down.                                                                                :Telephones:Period:Stromberg-Carlson:
    ID: 07070120.wav
    Length: 1
** Stromberg-Carlson (USA 1978) - pick up.                                                                                :Telephones:America:
    ID: 07070119.wav
    Length: 13
** Trimphone (1979) - 7 rings, pick up.                                                                                :Telephones:Period:Trimphone:
    ID: 07070118.wav
    Length: 18
** GPO 700 Series - European: 5 rings pick up.                                                                                :Telephones:Ringing Tone:International:
    ID: 07070117.wav
    Length: 19
** GPO 700 Series - Exchange rings 3 times.                                                                                :Telephones:Period:GPO 700 Series:
    ID: 07070116.wav
    Length: 13
** GPO 700 Series - 10 rings, pick up.                                                                                :Telephones:Period:GPO 700 Series:
    ID: 07070115.wav
    Length: 29
** GPO 700 Series - phone down.                                                                                :Telephones:Period:GPO 700 Series:
    ID: 07070114.wav
    Length: 1
** GPO 700 Series (1960 onwards) pick up, dial 7 digit number.                                                                                :Telephones:Period:GPO 700 Series:
    ID: 07070113.wav
    Length: 10
** Red Kiosk Neophone - 5 rings, pick up.                                                                                :Telephones:Period:Red Kiosk:Neophone:
    ID: 07070112.wav
    Length: 20
** Red Kiosk Neophone - button B pressed.                                                                                :Telephones:Period:Red Kiosk:Neophone:
    ID: 07070111.wav
    Length: 9
** Red Kiosk Neophone - button A pressed.                                                                                :Telephones:Period:Red Kiosk:Neophone:
    ID: 07070110.wav
    Length: 1
** Red Kiosk Neophone - pick up, dial 7 digit number.                                                                                :Telephones:Period:Red Kiosk:Neophone:
    ID: 07070109.wav
    Length: 13
** Wallphone (1910 onwards) - earpiece onto hook.                                                                                :Telephones:Period:Wallphone:
    ID: 07070108.wav
    Length: 1
** Wallphone (1910 onwards) - 2 short rings, one long ring.                                                                                :Telephones:Period:Wallphone:
    ID: 07070107.wav
    Length: 21
** Wallphone (1910 onwards) - earpiece lifted, handle turned with bell jingling.                                                                                :Telephones:Period:Wallphone:
    ID: 07070106.wav
    Length: 23
** GEC Neophone (1930 onwards) - 5 rings, pick up on 6th.                                                                                :Telephones:Period:GEC Neophone:
    ID: 07070105.wav
    Length: 18
** GEC Neophone (1930 onwards) - phone down.                                                                                :Telephones:Period:GEC Neophone:
    ID: 07070104.wav
    Length: 1
** GEC Neophone (1930 onwards) - dial 7 digit number.                                                                                :Telephones:Period:GEC Neophone:
    ID: 07070103.wav
    Length: 14
** Bakelite 200 series - 5 rings, pick up on 6th.                                                                                :Telephones:Period:Bakerlite 200 Series:
    ID: 07070102.wav
    Length: 26
** Bakelite 200 series - phone down.                                                                                :Telephones:Period:Bakerlite 200 Series:
    ID: 07070101.wav
    Length: 1
** Bakelite 200 series (1930 onwards) - dial 7 digit number.                                                                                :Telephones:Period:Bakerlite 200 Series:
    ID: 07070100.wav
    Length: 12
** Dialling out on Chinese phone - dialling tone, dialling 6 digit number, engaged tone, hang up (recorded China 1960)                                                                                :China:
    ID: 07070099.wav
    Length: 28
** Computerised PABX with voices & keyboards.                                                                                :Telephone Exchanges:
    ID: 07070098.wav
    Length: 290
** Dialing out through modem.                                                                                :Computers:
    ID: 07070097.wav
    Length: 16
** Apartment entry phone (ends with exterior door closing)                                                                                :Doors:
    ID: 07070096.wav
    Length: 18
** Fax phone (Samsung SF40) - dial 11 digit number, access ring, send fax                                                                                :Fax Recivers:Samsung SF40:
    ID: 07070095.wav
    Length: 87
** Fax phone (Samsung SF40) - rings, detects fax & receives it.                                                                                :Fax Recivers:Samsung SF40:
    ID: 07070094.wav
    Length: 50
** Answering machine engaging.                                                                                :Telephones:Answering Machines:
    ID: 07070093.wav
    Length: 11
** Mode change button tone.                                                                                :Telephones:Answering Machines:
    ID: 07070092.wav
    Length: 1
** Answering machine (BT) - playback terminates.                                                                                :Telephones:Answering Machines:
    ID: 07070091.wav
    Length: 2
** Answering machine (BT) - playback with clicks, spooling tones then 28" noise for message placement.                                                                                :Telephones:Answering Machines:
    ID: 07070090.wav
    Length: 35
** Ringing tone (Hong Kong, Australia, NZ) - 5 rings, answer machine                                                                                :Telephones:Answering Machines:
    ID: 07070089.wav
    Length: 20
** Notification of change of number message (USA)                                                                                :Telephones:America:
    ID: 07070088.wav
    Length: 21
** Engaged tone (USA)                                                                                :Telephones:America:
    ID: 07070087.wav
    Length: 20
** Ringing tone (USA) - 4 rings, answer on 5th.                                                                                :Telephones:America:
    ID: 07070086.wav
    Length: 24
** Ringing tone (France, Spain, Russia) - 8 rings to answer.                                                                                :Telephones:Ringing Tone:International:
    ID: 07070085.wav
    Length: 37
** Ringing tone (Benelux, Scandinavia, Germany) - 7 rings to answer.                                                                                :Telephones:Ringing Tone:International:
    ID: 07070084.wav
    Length: 30
** Motorola car phone - switch off, replace in holster.                                                                                :Telephones:Mobile Phones:
    ID: 07070083.wav
    Length: 10
** Motorola car phone - 4 rings, pick up.                                                                                :Telephones:Mobile Phones:
    ID: 07070082.wav
    Length: 10
** Motorola car phone - off holster - switch on, dial 11 digits.                                                                                :Telephones:Mobile Phones:
    ID: 07070081.wav
    Length: 9
** Call to Vodaphone mobile: no response message (repeated twice) hang up on third                                                                                :Telephones:Mobile Phones:
    ID: 07070080.wav
    Length: 14
** Ringing tone - 6 rings calling to Cellnet mobile (repeated twice)                                                                                :Telephones:Mobile Phones:
    ID: 07070079.wav
    Length: 14
** Sony mobile (Vodaphone) - 5 rings.                                                                                :Telephones:Mobile Phones:
    ID: 07070078.wav
    Length: 17
** Sony mobile (Vodaphone) - switched on.                                                                                :Telephones:Mobile Phones:
    ID: 07070077.wav
    Length: 1
** Sony mobile (Vodaphone) - switched on, dial 10 digit number.                                                                                :Telephones:Mobile Phones:
    ID: 07070076.wav
    Length: 7
** Call to Cellnet mobile: no response message (repeated twice)                                                                                :Telephones:Mobile Phones:
    ID: 07070075.wav
    Length: 12
** BT mobile (Cellnet) - switched on, dial 10 digit number.                                                                                :Telephones:Mobile Phones:
    ID: 07070074.wav
    Length: 13
** BT mobile (Cellnet) - switched on.                                                                                :Telephones:Mobile Phones:
    ID: 07070073.wav
    Length: 1
** BT mobile (Cellnet) - 3 rings, answered.                                                                                :Telephones:Mobile Phones:
    ID: 07070072.wav
    Length: 7
** Kiosk - phone down, phonecard ejected.                                                                                :Telephones:Kiosks:Dialling:
    ID: 07070071.wav
    Length: 2
** Kiosk - pick up, BT phonecard inserted, dial 11 digit number.                                                                                :Telephones:Kiosks:Dialling:
    ID: 07070070.wav
    Length: 13
** Phone ringing - 10 rings, pick up.                                                                                :Telephones:Pushbutton:Vanguard:
    ID: 07070069.wav
    Length: 29
** Phone ringing - 6 rings pick up                                                                                :Telephones:Pushbutton:Ericsson:
    ID: 07070068.wav
    Length: 20
** Phone slammed down.                                                                                :Telephones:Pushbutton:
    ID: 07070067.wav
    Length: 1
** Pick-up, dial 10 digits.                                                                                :Telephones:Pushbutton:Diallatron Debate:
    ID: 07070066.wav
    Length: 8
** Phone down.                                                                                :Telephones:Pushbutton:
    ID: 07070065.wav
    Length: 1
** Pick-up dial out - 7 digits.                                                                                :Telephones:Pushbutton:Betacom Vogue:
    ID: 07070064.wav
    Length: 5
** Pick-up dial out - 7 digits.                                                                                :Telephones:Pushbutton:Vanguard:
    ID: 07070063.wav
    Length: 6
** Pick-up dial out - 11 digits.                                                                                :Telephones:Pushbutton:Ericsson:
    ID: 07070062.wav
    Length: 11
** Engaged tone.                                                                                :Telephones:Pushbutton:
    ID: 07070061.wav
    Length: 20
** Dialling pulses (push button phone)                                                                                :Telephones:Touch Tone:
    ID: 07070060.wav
    Length: 8
** Ringing tone - 6 rings, answered.                                                                                :Telephones:Touch Tone:
    ID: 07070059.wav
    Length: 18
** Touch tone phone - 2 rings, silent pick on 2nd                                                                                :Telephones:Touch Tone:
    ID: 07070058.wav
    Length: 5
** Touch tone phone - quick dial 7 digits.                                                                                :Telephones:Touch Tone:
    ID: 07070057.wav
    Length: 4
** Touch tone phone - 12 rings, audible hang-up                                                                                :Telephones:Digital:
    ID: 07070056.wav
    Length: 34
** Pick-up, dial 10 digits on Touch tone phone.                                                                                :Telephones:Touch Tone:
    ID: 07070055.wav
    Length: 9
** Hang up with the termination tone                                                                                :Telephones:Digital:
    ID: 07070054.wav
    Length: 8
** Hang up - [callled party]                                                                                :Telephones:Digital:
    ID: 07070053.wav
    Length: 1
** Lift journey - up five floors                                                                                :Lifts:
    ID: 07070052.wav
    Length: 97
** Mainframe computer control room (DEC Datasystems rec. 1983)                                                                                :Computers:
    ID: 07070051.wav
    Length: 153
** Heathrow Air Traffic - visual control tower                                                                                :Airports:Heathrow:Air Traffic Control:
    ID: 07070050.wav
    Length: 265
** Heathrow Air Traffic - approach radar room                                                                                :Radar:
    ID: 07070049.wav
    Length: 258
** RAC Motor Control Centre - incoming calls area                                                                                :Control Rooms:
    ID: 07070048.wav
    Length: 268
** RAC Motor Control Centre - rescue despatch                                                                                :Control Rooms:
    ID: 07070047.wav
    Length: 243
** Operations room - behind operators' desks                                                                                :Control Rooms:
    ID: 07070046.wav
    Length: 257
** Telex area (Force Operations)                                                                                :Offices:Telex Machines:
    ID: 07070045.wav
    Length: 143
** Police operations room - behind sergeant's desk                                                                                :Control Rooms:
    ID: 07070044.wav
    Length: 242
** London Sugar Futures Market - reception hall                                                                                :Entrance Halls:
    ID: 07070043.wav
    Length: 269
** London Sugar Futures Market (rec. 1985)                                                                                :Exchange Markets:
    ID: 07070042.wav
    Length: 113
** International Petroleum Market (rec. 1985)                                                                                :Exchange Markets:
    ID: 07070041.wav
    Length: 113
** London Metal Exchange (rec. 1985)                                                                                :Exchange Markets:
    ID: 07070040.wav
    Length: 123
** London International Financial Futures Exchange (rec.1985)                                                                                :Exchange Markets:
    ID: 07070039.wav
    Length: 122
** Newspaper copy typists room (rec. 1986)                                                                                :Newspapers:
    ID: 07070038.wav
    Length: 153
** City bank computer & teleprinter room (rec. 1986)                                                                                :Banks:
    ID: 07070037.wav
    Length: 182
** Thomas Cook World Travel Centre                                                                                :Travel Centres:
    ID: 07070036.wav
    Length: 255
** Cash dispenser operating                                                                                :Cash Dispensers:
    ID: 07070035.wav
    Length: 31
** Microfiche reader, slide placed, print out, slide removed                                                                                :Offices:Microfiche Readers:
    ID: 07070034.wav
    Length: 39
** Computer printer (Hewlett Packard Laserjet) - prints                                                                                :Computers:Printers:
    ID: 07070033.wav
    Length: 53
** Photo copier (Konica UB1X250Z) - 4 originals copied                                                                                :Offices:Photocopiers:
    ID: 07070032.wav
    Length: 88
** Telex machine (Transtel) - receiving                                                                                :Offices:Telex Machines:
    ID: 07070031.wav
    Length: 47
** Fax machine (Pitney Bowes 8000) - dial out, line engaged                                                                                :Offices:Fax Machines:
    ID: 07070030.wav
    Length: 52
** Fax machine (Pitney Bowes 8000) - receive                                                                                :Offices:Fax Machines:
    ID: 07070029.wav
    Length: 45
** Fax machine (Pitney Bowes 8000) - dial out, send                                                                                :Offices:Fax Machines:
    ID: 07070028.wav
    Length: 79
** Hospital trolley passes in corridor.                                                                                :Hospitals:Corridors:
    ID: 07070027.wav
    Length: 19
** Hospital Lift, doors open, journey, stops at six floors (lift doors close, lift doors jammed open).                                                                                :Lifts:Doors:
    ID: 07070026.wav
    Length: 127
** Hospital corridor atmosphere.                                                                                :Hospitals:Corridors:
    ID: 07070025.wav
    Length: 179
** Cafe in hospital foyer.                                                                                :Foyers:
    ID: 07070024.wav
    Length: 253
** Hospital entrance lobby, near lifts.                                                                                :Hospitals:Corridors:
    ID: 07070023.wav
    Length: 230
** Hospital research laboratory atmosphere.                                                                                :Laboratories:
    ID: 07070022.wav
    Length: 152
** Chemical centrifugal analyzer.                                                                                :Hospitals:Chemical Centrifugal Analyzer:
    ID: 07070021.wav
    Length: 106
** Hospital pathology laboratory atmosphere, some indistinct speech.                                                                                :Hospitals:Pathological Laboratories:
    ID: 07070020.wav
    Length: 79
** Autoclave sterilisers operating.                                                                                :Hospitals:Autoclave Sterilisers:
    ID: 07070019.wav
    Length: 65
** Foetal heart beat, as heard from region of umbilical cord.                                                                                :Heartbeats:
    ID: 07070018.wav
    Length: 71
** Foetal heartbeat, direct contact recording at 38 weeks.                                                                                :Babies:Foetal Heartbeats:
    ID: 07070017.wav
    Length: 89
** Human heartbeat, 58 bpm (average for fit young person).                                                                                :Heartbeats:
    ID: 07070016.wav
    Length: 214
** Pulse monitor, erratic pulse, slow down, continuous pulse.                                                                                :Hospitals:Pulse Monitors:
    ID: 07070015.wav
    Length: 90
** Pulse monitor, normal rate.                                                                                :Hospitals:Pulse Monitors:
    ID: 07070014.wav
    Length: 246
** Hydraulic bed raised.                                                                                :Hospitals:Men's Wards:
    ID: 07070013.wav
    Length: 15
** Ventilator, busy period in intensive care unit. (Recorded at patient's end.)                                                                                :Hospitals:Intensive Care Unit:
    ID: 07070012.wav
    Length: 64
** Ventilator. (Recorded at machine end.)                                                                                :Hospitals:Intensive Care Unit:
    ID: 07070011.wav
    Length: 130
** Intensive Care Unit atmosphere.                                                                                :Hospitals:Intensive Care Unit:
    ID: 07070010.wav
    Length: 156
** Operating Theatre atmosphere, during later stages of surgery. (General perspective recording.)                                                                                :Hospitals:Operating Theatres:
    ID: 07070009.wav
    Length: 177
** Operating Theatre atmosphere, during abdominal surgery. (Close perspective recording.)                                                                                :Hospitals:Operating Theatres:
    ID: 07070008.wav
    Length: 207
** Hospital pharmacy atmosphere.                                                                                :Hospitals:Pharmacies:
    ID: 07070007.wav
    Length: 145
** Hospital pharmacy waiting area atmosphere.                                                                                :Hospitals:Pharmacies:
    ID: 07070006.wav
    Length: 76
** Outpatients clinic atmosphere.                                                                                :Hospitals:Outpatients:
    ID: 07070005.wav
    Length: 145
** Childrens' ward atmosphere.                                                                                :Hospitals:Children's Wards:
    ID: 07070004.wav
    Length: 211
** Maternity ward atmosphere.                                                                                :Hospitals:Maternity Wards:
    ID: 07070003.wav
    Length: 253
** Mens' ward atmosphere.                                                                                :Hospitals:Men's Wards:
    ID: 07070002.wav
    Length: 242
** Womens' ward atmosphere.                                                                                :Hospitals:Women's Wards:
    ID: 07070001.wav
    Length: 240
** Tuning communications receiver - medium wave band.                                                                                :Radio:Receivers:
    ID: 07069069.wav
    Length: 208
** VHF receiver with aerial disconnected. Speech, heavily distorted.                                                                                :Radio:Interference:
    ID: 07069068.wav
    Length: 52
** Severe mains hum & static.                                                                                :Radio:Interference:
    ID: 07069067.wav
    Length: 57
** General purpose electrical radiation                                                                                :Electronic Sounds:Radiation:
    ID: 07069066.wav
    Length: 48
** Wimhurst machine.                                                                                :Electronic Sounds:Wimshurst Machines:
    ID: 07069065.wav
    Length: 44
** Radion interference.                                                                                :Electronic Sounds:Radiation:
    ID: 07069064.wav
    Length: 77
** Amplifier noise.                                                                                :Geiger Counters:
    ID: 07069063.wav
    Length: 78
** Amplifier crackles.                                                                                :Geiger Counters:
    ID: 07069062.wav
    Length: 55
** Geiger counter.                                                                                :Electronic Sounds:Radiation:
    ID: 07069061.wav
    Length: 175
** Static - heavy line noise on transatlantic circuit.                                                                                :Static:
    ID: 07069060.wav
    Length: 180
** Static.                                                                                :Static:
    ID: 07069059.wav
    Length: 180
** Electronic monotony.                                                                                :Electronic Sounds:
    ID: 07069058.wav
    Length: 198
** Electronic monotony.                                                                                :Electronic Sounds:
    ID: 07069057.wav
    Length: 190
** Electronic monotony.                                                                                :Electronic Sounds:
    ID: 07069056.wav
    Length: 183
** Radar echoes from the Moon.                                                                                :Radar:
    ID: 07069055.wav
    Length: 179
** Background static to echoes from the moon.                                                                                :Electronic Sounds:
    ID: 07069054.wav
    Length: 211
** Keying Aldis lamp.                                                                                :Morse Code:
    ID: 07069053.wav
    Length: 60
** Keyed morse - no tone.                                                                                :Morse Code:
    ID: 07069052.wav
    Length: 63
** Low-pitched buzzer.                                                                                :Morse Code:
    ID: 07069051.wav
    Length: 59
** Medium-pitched buzzer.                                                                                :Morse Code:
    ID: 07069050.wav
    Length: 60
** Low-pitched oscillator.                                                                                :Morse Code:
    ID: 07069049.wav
    Length: 60
** Medium-pitched oscillator.                                                                                :Morse Code:
    ID: 07069048.wav
    Length: 60
** High-pitched oscillator.                                                                                :Morse Code:
    ID: 07069047.wav
    Length: 60
** Creed tape-printing telegraph, 1928-1952.                                                                                :Telegraph Equipment:
    ID: 07069046.wav
    Length: 116
** Creed transmitter, perforator & receiver working together.                                                                                :Telegraph Equipment:
    ID: 07069045.wav
    Length: 80
** Creed receiver, 1925.                                                                                :Telegraph Equipment:
    ID: 07069044.wav
    Length: 152
** Creed morse printer, 1925- 1930.                                                                                :Telegraph Equipment:
    ID: 07069043.wav
    Length: 69
** Creed transmitter, 1925.                                                                                :Telegraph Equipment:
    ID: 07069042.wav
    Length: 146
** Creed keyboard perforator, 1925.                                                                                :Telegraph Equipment:
    ID: 07069041.wav
    Length: 128
** Hughes printer - piano-type keyboard, 1867                                                                                :Telegraph Equipment:
    ID: 07069040.wav
    Length: 80
** Wheatstone receiver, 1870.                                                                                :Telegraph Equipment:
    ID: 07069039.wav
    Length: 80
** Wheatstone transmitter, 1870.                                                                                :Telegraph Equipment:
    ID: 07069038.wav
    Length: 70
** Morse perforator & punches - used with Wheatstone transmitter & receiver, 1870.                                                                                :Morse Code:
    ID: 07069037.wav
    Length: 85
** Burgett ABC receiver, 1850.                                                                                :Telegraph Equipment:
    ID: 07069036.wav
    Length: 85
** Morse key - transmitting end, 1839.                                                                                :Morse Code:
    ID: 07069035.wav
    Length: 77
** Sounder used with morse key - receiving end, 1839.                                                                                :Morse Code:
    ID: 07069034.wav
    Length: 131
** Cooke's portable 2-needle telegraph, 1838.                                                                                :Telegraph Equipment:
    ID: 07069033.wav
    Length: 63
** Airport activity with Tridents.                                                                                :Aircraft:Trident:
    ID: 07069032.wav
    Length: 147
** Exterior. Landing & taxi to close-up.                                                                                :Aircraft:Trident:
    ID: 07069031.wav
    Length: 92
** Exterior. Taxi up & past.                                                                                :Aircraft:Trident:
    ID: 07069030.wav
    Length: 58
** Passing overhead.                                                                                :Aircraft:Trident:
    ID: 07069029.wav
    Length: 55
** Exterior. Take off.                                                                                :Aircraft:Trident:
    ID: 07069028.wav
    Length: 64
** Exterior. Revving for take off.                                                                                :Aircraft:Trident:
    ID: 07069027.wav
    Length: 44
** Exterior. Start & run up engines - taxi.                                                                                :Aircraft:Trident:
    ID: 07069026.wav
    Length: 162
** Interior. Taxi - switch off.                                                                                :Aircraft:Trident:
    ID: 07069025.wav
    Length: 118
** Interior. Landing - taxi.                                                                                :Aircraft:Trident:
    ID: 07069024.wav
    Length: 58
** Interior. Descent.                                                                                :Aircraft:Trident:
    ID: 07069023.wav
    Length: 90
** Interior. Constant flight.                                                                                :Aircraft:Trident:
    ID: 07069022.wav
    Length: 180
** Interior. Take off & climb to cruising height.                                                                                :Aircraft:Trident:
    ID: 07069021.wav
    Length: 52
** Interior. Start & run up engines - taxi.                                                                                :Aircraft:Trident:
    ID: 07069020.wav
    Length: 181
