** Battle of Britain actuality, air battle.                                                                                ::
    ID: 07008069.wav
    Length: 133
** Bombers overhead, anti-aircraft fire, bombs fall.                                                                                ::
    ID: 07008068.wav
    Length: 195
** Night raid on London, stick of bombs, anti-aircraft fire-close, wardens voices.                                                                                ::
    ID: 07008067.wav
    Length: 256
** Night raid on London. Anti-aircraft fire over London streets                                                                                ::
    ID: 07008066.wav
    Length: 161
** Night raid on London. Stick of bombs falling, distant anti-aircraft fire.                                                                                 ::
    ID: 07008065.wav
    Length: 125
** Night raid on London, bombs fall, anti-aircraft fire, A.R.P. warden's patrol.                                                                                ::
    ID: 07008064.wav
    Length: 135
** Night raid on London, distant anti-aircraft fire, bomb falls, drone of plane.                                                                                ::
    ID: 07008063.wav
    Length: 87
** Night raid on London, one bomb falls-close.                                                                                ::
    ID: 07008062.wav
    Length: 31
** Night raid on London, two bombs fall-close.                                                                                ::
    ID: 07008061.wav
    Length: 27
** German night bombers in constant flight. Desynchronised engines                                                                                ::
    ID: 07008060.wav
    Length: 383
** German night bombers in constant flight. Synchronised engines.                                                                                ::
    ID: 07008059.wav
    Length: 373
** Massed formations of German Bombers attacked by British Fighters.                                                                                 ::
    ID: 07008058.wav
    Length: 165
** A dive bomber attack with pom pom guns, bombs and machine guns.                                                                                ::
    ID: 07008057.wav
    Length: 201
** Stuka dive bombers. (World War II German Bombers)                                                                                ::
    ID: 07008056.wav
    Length: 282
** Stuka dive bombers. (World War II German Bombers)                                                                                ::
    ID: 07008055.wav
    Length: 53
** Actuality of an air battle, planes diving and zooming, gunfire. (German film)                                                                                ::
    ID: 07008054.wav
    Length: 167
** A Messerschmitt 110, land and taxi away. (World War II German Aircraft)                                                                                ::
    ID: 07008053.wav
    Length: 80
** A Messerschmitt 110, taxi and take off. (World War II German Aircraft)                                                                                ::
    ID: 07008052.wav
    Length: 74
** Messerschmitt 110. In flight with engines desynchronised (World War II German Aircraft)                                                                                ::
    ID: 07008051.wav
    Length: 56
** Messerschmitt 110. Circling overhead, with one dive at 700 feet.                                                                                 ::
    ID: 07008050.wav
    Length: 244
** Messerschmitt 110. Taxi and take off. (World War II German Aircraft)                                                                                ::
    ID: 07008049.wav
    Length: 93
** Messerschmitt 110. Taxi past.  (World War II German Aircraft)                                                                                ::
    ID: 07008048.wav
    Length: 99
** Messerschmitt 110. Start, warm up, switch off. . (World War II                                                                                 ::
    ID: 07008047.wav
    Length: 133
** Junkers 88 circling overhead, several dives. (World War II German Aircraft)                                                                                ::
    ID: 07008046.wav
    Length: 391
** Junkers 88. Low level attack.  (World War II German Aircraft)                                                                                ::
    ID: 07008045.wav
    Length: 40
** Junkers 88. Land and taxi away.  (World War II German Aircraft)                                                                                ::
    ID: 07008044.wav
    Length: 57
** Junkers 88. Land and taxi away.  (World War II German Aircraft)                                                                                ::
    ID: 07008043.wav
    Length: 78
** Junkers 88. Take off (World War II German Aircraft)                                                                                ::
    ID: 07008042.wav
    Length: 60
** Junkers 88. Take off. (World War II German Aircraft)                                                                                ::
    ID: 07008041.wav
    Length: 73
** Junkers 88. Taxi past. (World War II German Aircraft)                                                                                ::
    ID: 07008040.wav
    Length: 102
** Junkers 88. Start, warm up and switch off. (World War II German Aircraft)                                                                                ::
    ID: 07008039.wav
    Length: 179
** Heinkel 115, exterior recording. Flying against wind at 3,000ft                                                                                ::
    ID: 07008038.wav
    Length: 162
** Heinkel 115, exterior recording. Flying against wind at 3,000ft                                                                                ::
    ID: 07008037.wav
    Length: 191
** Heinkel 115, exterior recording. Flying with wind at 3,000ft                                                                                ::
    ID: 07008036.wav
    Length: 168
** Heinkel 115, exterior recording. Flying with wind at 3,000 feet.                                                                                ::
    ID: 07008035.wav
    Length: 119
** Heinkel III, interior recordings. Taxi, take off, climbing                                                                                ::
    ID: 07008034.wav
    Length: 326
** Heinkel III, interior recordings. Constant flight                                                                                ::
    ID: 07008033.wav
    Length: 139
** Heinkel III, interior recordings. Start up, revving and taxi.                                                                                 ::
    ID: 07008032.wav
    Length: 136
** Heinkel III, interior recordings. Landing, taxiiing                                                                                ::
    ID: 07008031.wav
    Length: 114
** Heinkel III, exterior recordings. Low level approach                                                                                ::
    ID: 07008030.wav
    Length: 46
** Heinkel III, exterior recordings. Constant flight 1,000                                                                                ::
    ID: 07008029.wav
    Length: 49
** Heinkel III, exterior recordings. Low level approach                                                                                ::
    ID: 07008028.wav
    Length: 27
** Heinkel III, exterior recordings. Landing.                                                                                 ::
    ID: 07008027.wav
    Length: 26
** Heinkel III, exterior recordings. Take off                                                                                ::
    ID: 07008026.wav
    Length: 37
** Exterior, Heinkel III, starting with inertia starter, revving and stopping. (World War II German Bomber)                                                                                ::
    ID: 07008025.wav
    Length: 104
** Exterior, Focke-Wulf 190, circling overhead, climbs and dives. (World War II German Bomber)                                                                                ::
    ID: 07008024.wav
    Length: 250
** Focke-Wulf 190, exterior recordings. Low level attack                                                                                ::
    ID: 07008023.wav
    Length: 38
** Focke-Wulf 190, exterior recordings. Shallow dive                                                                                ::
    ID: 07008022.wav
    Length: 59
** Focke-Wulf 190, exterior recordings. Land and taxi away                                                                                ::
    ID: 07008021.wav
    Length: 57
** Focke-Wulf 190, exterior recordings. Take off                                                                                ::
    ID: 07008020.wav
    Length: 74
** Focke-Wulf 190, exterior recordings. Take off.                                                                                ::
    ID: 07008019.wav
    Length: 61
** Focke-Wulf 190, exterior recordings. Start, warm up and taxi past. (World War II)                                                                                ::
    ID: 07008018.wav
    Length: 107
** Focke-Wulf 190, exterior recordings. Start, warm up and switch off. (World War II)                                                                                ::
    ID: 07008017.wav
    Length: 178
** V2 rocket, launching                                                                                ::
    ID: 07008016.wav
    Length: 44
** V2 rocket, double explosion                                                                                ::
    ID: 07008015.wav
    Length: 18
** V2, Explosion, rumble                                                                                ::
    ID: 07008014.wav
    Length: 19
** V2 rocket, Explosion, rumble                                                                                ::
    ID: 07008013.wav
    Length: 19
** V2 rocket, Explosion, train whistle and cock crow                                                                                ::
    ID: 07008012.wav
    Length: 22
** V2 rocket, double explosion.                                                                                 ::
    ID: 07008011.wav
    Length: 16
** V2 rocket, explosion and train whistle.                                                                                ::
    ID: 07008010.wav
    Length: 15
** V2 rocket, double explosion.                                                                                ::
    ID: 07008009.wav
    Length: 15
** V2 rocket, explosion and rumble.                                                                                ::
    ID: 07008008.wav
    Length: 23
** V2 rocket, heavy rumble, taxi drives off. (Recorded Marble Arch)                                                                                ::
    ID: 07008007.wav
    Length: 41
** V1 flying bomb, doodle bug, explosion.                                                                                ::
    ID: 07008006.wav
    Length: 9
** V1 flying bomb, doodle bug, passing over and anti-aircraft fire.                                                                                ::
    ID: 07008005.wav
    Length: 69
** V1 - Flying Bomb (Doodle Bug) Approach, engine cut out, expolosion                                                                                ::
    ID: 07008004.wav
    Length: 46
** V1 - Flying Bomb (Doodle Bug) Approach, engine cut out, expolosion                                                                                ::
    ID: 07008003.wav
    Length: 41
** V1 - Flying Bomb (Doodle Bug) seven in quick succession approach                                                                                ::
    ID: 07008002.wav
    Length: 256
** A German Zeppelin airship in constant flight, recorded in air. (World War II Airship)                                                                                ::
    ID: 07008001.wav
    Length: 393
** Fairground machine "The Rotor" operates, people shouting and screaming.                                                                                ::
    ID: 07007148.wav
    Length: 223
** Children's fairground roundabout operating with occasional bell.                                                                                ::
    ID: 07007147.wav
    Length: 169
** Fairground machine "The Caterpillar" operates, screams with occasional indistinct public address except at end when operator attracts new custom.                                                                                ::
    ID: 07007146.wav
    Length: 189
** Fairground machine "The Satellite" operates, screams with occasional indistinct public address.                                                                                ::
    ID: 07007145.wav
    Length: 162
** Fairground atmosphere with indistinct sound of barkers in background attracting custom.                                                                                ::
    ID: 07007144.wav
    Length: 372
** Prize-winning tickets announced by woman over public address system. (Fairground atmosphere in distance.)                                                                                ::
    ID: 07007143.wav
    Length: 159
** Man calling Bingo over public address system, game ends, caller attracts custom. (Fairground atmosphere in distance.)                                                                                ::
    ID: 07007142.wav
    Length: 152
** Fairground atmosphere with steam roundabouts and occasional indistinct music.                                                                                ::
    ID: 07007141.wav
    Length: 372
** Fairground atmosphere with dodgems and occasional indistinct music.                                                                                ::
    ID: 07007140.wav
    Length: 373
** 2 3/4 year old baby girl. Reciting nonsense nursery rhymes; ends with farewells                                                                                ::
    ID: 07007139.wav
    Length: 374
** 2 3/4 year old baby girl. Talking nonsense, looking at picture book                                                                                ::
    ID: 07007138.wav
    Length: 337
** 2 3/4 year old baby girl. Talking nonsense, playing with toys                                                                                ::
    ID: 07007137.wav
    Length: 325
** 2 3/4 year old baby girl. Saying 'please' and 'thank you'                                                                                ::
    ID: 07007136.wav
    Length: 8
** 2 1/4 year old baby girl, talking nonsense and asking questions.                                                                                ::
    ID: 07007135.wav
    Length: 399
** 2 year old baby girl. Chattering                                                                                ::
    ID: 07007134.wav
    Length: 117
** 2 year old baby girl. Giggling                                                                                ::
    ID: 07007133.wav
    Length: 121
** 2 year old baby girl. Crying                                                                                ::
    ID: 07007132.wav
    Length: 124
** 2 year old baby girl. Looking at picture book, pages turned                                                                                ::
    ID: 07007131.wav
    Length: 236
** 2 year old baby girl. Talking and crying.                                                                                 ::
    ID: 07007130.wav
    Length: 162
** 18 month old baby girl. Protesting at having face washed                                                                                ::
    ID: 07007129.wav
    Length: 255
** 18 month old baby girl. Crying                                                                                ::
    ID: 07007128.wav
    Length: 113
** 18 month old baby girl. Crying                                                                                ::
    ID: 07007127.wav
    Length: 179
** 18 month old baby girl. Looking at picture book.                                                                                 ::
    ID: 07007126.wav
    Length: 182
** 15 month old baby girl. Crying                                                                                ::
    ID: 07007125.wav
    Length: 132
** 15 month old baby girl. Squeals of delight                                                                                ::
    ID: 07007124.wav
    Length: 52
** 15 month old baby girl. Saying 'beh-beh'                                                                                ::
    ID: 07007123.wav
    Length: 59
** 15 month old baby girl. Singing and playing with toys.                                                                                 ::
    ID: 07007122.wav
    Length: 100
** 22 week old baby girl. Trying to talk.                                                                                ::
    ID: 07007121.wav
    Length: 128
** 22 week old baby girl. Tantrums when toys are taken                                                                                 ::
    ID: 07007120.wav
    Length: 119
** 22 week old baby girl. Trying to talk and playing with toys.                                                                                 ::
    ID: 07007119.wav
    Length: 122
** 58 week old baby girl, playing with Teddy bear with sneeze and hiccoughs.                                                                                ::
    ID: 07007118.wav
    Length: 165
** 56 week old baby girl, playing in bath.                                                                                ::
    ID: 07007117.wav
    Length: 209
** 54 week old baby girl, trying to talk.                                                                                ::
    ID: 07007116.wav
    Length: 210
** 48 week old baby girl, in temper.                                                                                ::
    ID: 07007115.wav
    Length: 145
** 46 week old baby girl, playing                                                                                ::
    ID: 07007114.wav
    Length: 118
** 45 week old baby girl, playing                                                                                ::
    ID: 07007113.wav
    Length: 119
** 44 weeks old baby girl, playing                                                                                ::
    ID: 07007112.wav
    Length: 128
** 43 week old baby girl, playing.                                                                                ::
    ID: 07007111.wav
    Length: 78
** 40 week old baby girl, fretful.                                                                                ::
    ID: 07007110.wav
    Length: 71
** 40 week old baby girl, hiccoughs, becoming irritable.                                                                                ::
    ID: 07007109.wav
    Length: 93
** 40 week old baby girl, playing and shouting.                                                                                ::
    ID: 07007108.wav
    Length: 97
** 35 week old baby girl, playing and trying to talk. (Saying 'mum-mum-mum')                                                                                ::
    ID: 07007107.wav
    Length: 199
** 34 week old baby girl, playing and trying to talk.                                                                                ::
    ID: 07007106.wav
    Length: 192
** 36 week old baby girl, gurgling and hiccoughing.                                                                                ::
    ID: 07007105.wav
    Length: 177
** 36 week old baby girl, crying at bedtime.                                                                                ::
    ID: 07007104.wav
    Length: 95
** 34 week old baby girl, uncertain gurgling.                                                                                ::
    ID: 07007103.wav
    Length: 44
** 34 week old baby girl saying 'da-da-da'                                                                                ::
    ID: 07007102.wav
    Length: 208
** 32 week old baby girl, saying 'ba-ba-ba'                                                                                ::
    ID: 07007101.wav
    Length: 155
** 30 week old baby girl, sitting, playing quietly, blowing bubbles.                                                                                ::
    ID: 07007100.wav
    Length: 182
** 29 week old baby girl, teething.                                                                                ::
    ID: 07007099.wav
    Length: 135
** 28 week old baby girl, gurgling and blowing bubbles                                                                                ::
    ID: 07007098.wav
    Length: 149
** 26 week old baby girl, gurgling, laughing and hiccoughing.                                                                                ::
    ID: 07007097.wav
    Length: 105
** 26 week old baby girl, distressed crying.                                                                                ::
    ID: 07007096.wav
    Length: 105
** 22 week old baby girl. Crying in temper.                                                                                ::
    ID: 07007095.wav
    Length: 185
** 22 week old baby girl, Cooing, laughing and sucking thumb.                                                                                 ::
    ID: 07007094.wav
    Length: 188
** 20 week old baby girl. Tired and irritable crying.                                                                                ::
    ID: 07007093.wav
    Length: 245
** 20 week old baby girl. Very irritable crying.                                                                                 ::
    ID: 07007092.wav
    Length: 136
** 18 week old baby girl, gurgling becoming irritable.                                                                                ::
    ID: 07007091.wav
    Length: 106
** 18 week old baby girl, cooing and gurgling.                                                                                ::
    ID: 07007090.wav
    Length: 136
** 16 week old baby girl, cooing, gurgling etc.                                                                                ::
    ID: 07007089.wav
    Length: 122
** 14 week-old baby girl, grizzles and cries whilst trying to sleep.                                                                                ::
    ID: 07007088.wav
    Length: 126
** 14 week-old baby girl, gurgles and coos.                                                                                ::
    ID: 07007087.wav
    Length: 67
** 12 week-old baby girl, gurgles with cough at end.                                                                                ::
    ID: 07007086.wav
    Length: 118
** 12 week-old baby girl, fretful cries.                                                                                ::
    ID: 07007085.wav
    Length: 65
** 9 week old baby girl. Cries and hiccoughs.                                                                                ::
    ID: 07007084.wav
    Length: 124
** 9 week old baby girl. Hiccoughs                                                                                ::
    ID: 07007083.wav
    Length: 120
** 9 week old baby girl. Hunger cries                                                                                ::
    ID: 07007082.wav
    Length: 120
** Baby girl crying. 17 day-old girl, weight 71b.                                                                                ::
    ID: 07007081.wav
    Length: 399
** Baby girl crying. 6 day-old, weight 5 3/41b.                                                                                 ::
    ID: 07007080.wav
    Length: 405
** Twin-tower type cement mixer loading lorries.                                                                                ::
    ID: 07007079.wav
    Length: 183
** Concrete vibrator machine operating.                                                                                ::
    ID: 07007078.wav
    Length: 182
** Arrival and manoeuvring of lorries on motorway construction site. (No speech)                                                                                ::
    ID: 07007077.wav
    Length: 182
** Several Caterpillar type tractors manoeuvring during construction of motorway. (Squeaks and engine noise)                                                                                ::
    ID: 07007076.wav
    Length: 184
** Levelling machines operating.                                                                                ::
    ID: 07007075.wav
    Length: 184
** Grab excavator operating during motorway construction. (Suitable for building use)                                                                                ::
    ID: 07007074.wav
    Length: 184
** Titon road making machine laying road. (Some speech)                                                                                ::
    ID: 07007073.wav
    Length: 183
** Supplying cement from silo. (Some speech)                                                                                ::
    ID: 07007072.wav
    Length: 183
** Ready-mixed cement lorry manoeuvres into position and discharges cement. (Some voices)                                                                                ::
    ID: 07007071.wav
    Length: 241
** Warning klaxon sounds, charging on stationary ready-mixed cement lorry stops.                                                                                ::
    ID: 07007070.wav
    Length: 141
** Stationary ready-mixed cement lorry charged with sand, gravel, cement and water. (Some speech)                                                                                ::
    ID: 07007069.wav
    Length: 387
** Hammering stakes into ground. (Exterior)                                                                                ::
    ID: 07007068.wav
    Length: 65
** Hammering heavy stakes into ground. (Exterior)                                                                                ::
    ID: 07007067.wav
    Length: 64
** Hammering fence post into ground. (Exterior)                                                                                ::
    ID: 07007066.wav
    Length: 56
** Hammering fence post into ground. (Exterior)                                                                                ::
    ID: 07007065.wav
    Length: 43
** Hammering iron fence into ground. (Exterior)                                                                                ::
    ID: 07007064.wav
    Length: 37
** Hammering fence post into ground. (Exterior)                                                                                ::
    ID: 07007063.wav
    Length: 54
** Hammering light stake into ground. (Exterior)                                                                                ::
    ID: 07007062.wav
    Length: 34
** Loosening iron stake from ground. (Exterior)                                                                                ::
    ID: 07007061.wav
    Length: 21
** Hammering iron stake into ground. (Exterior)                                                                                ::
    ID: 07007060.wav
    Length: 30
** Loosening stake. (Exterior)                                                                                ::
    ID: 07007059.wav
    Length: 36
** Hammering stake into ground. (Exterior)                                                                                ::
    ID: 07007058.wav
    Length: 23
** Hammering fence posts into ground. (Exterior)                                                                                ::
    ID: 07007057.wav
    Length: 36
** Driving piles into river bed with pile hammers. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007056.wav
    Length: 83
** Torque hammer operating, some speech. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007055.wav
    Length: 38
** Close perspective recording of girders being welded. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007054.wav
    Length: 21
** Mobile cranes and general atmosphere. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007053.wav
    Length: 108
** General atmosphere of steel erection and welding with some voices. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007052.wav
    Length: 75
** Tipping mud from shaft on to conveyor belt, some speech. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007051.wav
    Length: 39
** Continuous engine noise as mud is carried to barge on conveyor belt. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007050.wav
    Length: 82
** General atmosphere, drilling, hammering with some voices. (Construction of London Bridge, 1969)                                                                                ::
    ID: 07007049.wav
    Length: 256
** One bulldozer demolishing house in preparation for motorway construction.                                                                                ::
    ID: 07007048.wav
    Length: 351
** Wide perspective recording of tracked vehicles working on motorway.                                                                                ::
    ID: 07007047.wav
    Length: 189
** Wide perspective recording of construction work on motorway.                                                                                ::
    ID: 07007046.wav
    Length: 188
** Four-wheel drive vibrating roller operating.                                                                                ::
    ID: 07007045.wav
    Length: 189
** JCB type excavator levelling and excavating motorway. (Also suitable for building use)                                                                                ::
    ID: 07007044.wav
    Length: 191
** Tracked Hi-Mac type excavator dumping excavated soil.                                                                                ::
    ID: 07007043.wav
    Length: 180
** Tracked Hi-Mac type excavator in operation. (Medium perspective recording)                                                                                ::
    ID: 07007042.wav
    Length: 190
** Ball and chain demolition in progress with crane manoeuvring.                                                                                ::
    ID: 07007041.wav
    Length: 183
** Pile driver, slowly driving piles into river bed.                                                                                ::
    ID: 07007040.wav
    Length: 182
** Pile driver, mechanically driving piles into ground.                                                                                ::
    ID: 07007039.wav
    Length: 199
** Pile driver, three ton drop hammer in operation.                                                                                ::
    ID: 07007038.wav
    Length: 184
** Four ton pile hammer working.                                                                                ::
    ID: 07007037.wav
    Length: 186
** One pile hammer, pressure piling.                                                                                ::
    ID: 07007036.wav
    Length: 188
** Atmosphere on large building site with engines running and miscellaneous bustle.                                                                                ::
    ID: 07007035.wav
    Length: 393
** Mixing mortar, general atmosphere on building site. (Some speech)                                                                                ::
    ID: 07007034.wav
    Length: 190
** Halving bricks, general atmosphere on building site. (Some speech)                                                                                ::
    ID: 07007033.wav
    Length: 199
** Mechanical sand sifting machine in operation.                                                                                ::
    ID: 07007032.wav
    Length: 203
** Mechanical hopper operating.                                                                                ::
    ID: 07007031.wav
    Length: 204
** One gravel suction pump operating. (On building site)                                                                                ::
    ID: 07007030.wav
    Length: 196
** One mechanical excavator start up, run, stop.                                                                                ::
    ID: 07007029.wav
    Length: 209
** One bulldozer approaches, stops, switches off.                                                                                ::
    ID: 07007028.wav
    Length: 43
** One bulldozer starts up, clears top soil, stops.                                                                                ::
    ID: 07007027.wav
    Length: 344
** Hammer and chisel on brick. (Close perspective)                                                                                ::
    ID: 07007026.wav
    Length: 184
** Roar of falling debris.                                                                                ::
    ID: 07007025.wav
    Length: 52
** Falling stones. (Light crash)                                                                                ::
    ID: 07007024.wav
    Length: 17
** Falling stones. (Heavy crash)                                                                                ::
    ID: 07007023.wav
    Length: 17
** One wall collapsing.                                                                                ::
    ID: 07007022.wav
    Length: 15
** Interior recording of a crash of bricks.                                                                                ::
    ID: 07007021.wav
    Length: 11
** Hard shovelling, gravel soil.                                                                                ::
    ID: 07007020.wav
    Length: 186
** Hard pickaxing, gravel soil.                                                                                ::
    ID: 07007019.wav
    Length: 188
** Roar of sliding debris. (Some mechanical noise in background)                                                                                ::
    ID: 07007018.wav
    Length: 98
** Shovelling and digging debris on a demolition site. (Exterior.)                                                                                ::
    ID: 07007017.wav
    Length: 276
** Hammering brick wall, falling debris.                                                                                ::
    ID: 07007016.wav
    Length: 184
** Cutting brick and stone with metal hand tools. (Interior)                                                                                ::
    ID: 07007015.wav
    Length: 184
** Atmosphere recording of work inside a semi-completed building, various sounds of drills, banging, etc.                                                                                ::
    ID: 07007014.wav
    Length: 454
** Compressor switched on, drilling, compressor switch off.                                                                                ::
    ID: 07007013.wav
    Length: 454
** Single 'Jumping Jenny' (road leveller) with starts and stops.                                                                                ::
    ID: 07007012.wav
    Length: 452
** Single pneumatic drill with starts and stops.                                                                                ::
    ID: 07007011.wav
    Length: 453
** Pneumatic drills, continuous drilling. (Several drills)                                                                                ::
    ID: 07007010.wav
    Length: 192
** Mechanical excavator loading spoil into trucks.                                                                                ::
    ID: 07007009.wav
    Length: 192
** Mechanically fed cement mixer operating on building site                                                                                ::
    ID: 07007008.wav
    Length: 183
** Dumper truck on a building site carrying cement.                                                                                ::
    ID: 07007007.wav
    Length: 192
** Large cement mixer starts, empties and stops.                                                                                ::
    ID: 07007006.wav
    Length: 367
** Small cement mixer runs and empties                                                                                ::
    ID: 07007005.wav
    Length: 383
** Interior of heavy engineering works, with machinery, distant speech and occasional hammering. (Wide perspective)                                                                                ::
    ID: 07007004.wav
    Length: 215
** Industrial atmosphere, wide perspective recording of industrial sounds suitable for general purpose background.                                                                                ::
    ID: 07007003.wav
    Length: 125
** Building site, wide perspective recording of building being constructed.                                                                                ::
    ID: 07007002.wav
    Length: 145
** Construction site, clearing a building site using bulldozers and other machinery.                                                                                ::
    ID: 07007001.wav
    Length: 230
** Parish Church wedding, congregation leaving church, bells in background.                                                                                ::
    ID: 07006143.wav
    Length: 181
** Parish Church wedding, congregation standing.                                                                                ::
    ID: 07006142.wav
    Length: 28
** Parish Church wedding, church atmosphere during the signing of register.                                                                                ::
    ID: 07006141.wav
    Length: 139
** Parish Church wedding, congregation assembling before ceremony, with bells.                                                                                  ::
    ID: 07006140.wav
    Length: 93
** Parish Church wedding, congregation assembling before ceremony, with distant bells.                                                                                  ::
    ID: 07006139.wav
    Length: 249
** End of church service, speech and footsteps as congregation leaves church.                                                                                ::
    ID: 07006138.wav
    Length: 273
** Church congregation sitting down.                                                                                ::
    ID: 07006137.wav
    Length: 30
** Church congregation assembling before service with bells in background.                                                                                ::
    ID: 07006136.wav
    Length: 386
** Large crowd murmuring in a large room with echo.                                                                                ::
    ID: 07006135.wav
    Length: 204
** Birmingham Stock Exchange, atmosphere on floor during trading.                                                                                ::
    ID: 07006134.wav
    Length: 162
** London Stock Exchange, atmosphere on floor during trading.                                                                                ::
    ID: 07006133.wav
    Length: 389
** Lloyd's of London underwriting rooms, general atmosphere with speech & other indistinct noises.                                                                                ::
    ID: 07006132.wav
    Length: 393
** Lloyd's of London underwriting rooms, general atmosphere with speech & other indistinct noises.                                                                                ::
    ID: 07006131.wav
    Length: 394
** Coventry Cathedral, general atmosphere with footsteps and speech. (Echo)                                                                                ::
    ID: 07006130.wav
    Length: 394
** Lincoln Cathedral, general atmosphere with footsteps and occasional speech. (Echo)                                                                                ::
    ID: 07006129.wav
    Length: 401
** British Museum, atmosphere in reading room with occasional speech & telephone bell.                                                                                ::
    ID: 07006128.wav
    Length: 393
** British Museum, atmosphere in Dead Sea Scrolls gallery with occasional indistinct speech & footsteps.                                                                                ::
    ID: 07006127.wav
    Length: 397
** British Museum, atmosphere in entrance hall, footsteps & indistinct speech with echo.                                                                                ::
    ID: 07006126.wav
    Length: 395
** British Museum, atmosphere in tea room.                                                                                ::
    ID: 07006125.wav
    Length: 390
** Tate Gallery, general gallery atmosphere with speech and footsteps.                                                                                ::
    ID: 07006124.wav
    Length: 363
** Tate Gallery, atmosphere in entrance hall with speech and footsteps.                                                                                ::
    ID: 07006123.wav
    Length: 362
** Villa Borghese Museum, general atmosphere with footsteps voices & echo. (Rome, Italy.)                                                                                ::
    ID: 07006122.wav
    Length: 363
** Courtroom atmosphere, with constant background of indistinct speech & occasional footsteps.                                                                                ::
    ID: 07006121.wav
    Length: 363
** Kings Cross Station suburban line platforms, atmosphere with engine letting off steam.                                                                                ::
    ID: 07006120.wav
    Length: 408
** Kings Cross Station suburban line platforms, general atmosphere.                                                                                ::
    ID: 07006119.wav
    Length: 407
** Local train approach and stop in station, station background, depart. (Eastern Region steam train.)                                                                                ::
    ID: 07006118.wav
    Length: 103
** Local train approach and stop in station, station background, depart. (Eastern Region steam train.)                                                                                ::
    ID: 07006117.wav
    Length: 96
** Local train approach and stop in station, station background, depart. (Eastern Region steam train.)                                                                                ::
    ID: 07006116.wav
    Length: 108
** Local train approach and stop in station, station background, depart. (Eastern Region steam train.)                                                                                ::
    ID: 07006115.wav
    Length: 95
** Local train whistle and depart. (London Midland Region steam train.)                                                                                ::
    ID: 07006114.wav
    Length: 56
** Local train approach and stop, station background with steam. (London Midland Region steam train.)                                                                                ::
    ID: 07006113.wav
    Length: 144
** Local train approach and stop, station background, whistle, depart. (London Midland Region steam train.)                                                                                ::
    ID: 07006112.wav
    Length: 160
** A4 Streamline express passing with siren. (London Midland Region steam train.)                                                                                ::
    ID: 07006111.wav
    Length: 25
** Local train passing. (Western Region steam train.)                                                                                ::
    ID: 07006110.wav
    Length: 48
** Local train passing with whistle. (Western Region steam train.)                                                                                ::
    ID: 07006109.wav
    Length: 57
** Local train passing at speed with whistle. (Western Region steam train.)                                                                                ::
    ID: 07006108.wav
    Length: 36
** Local train passing. (Western Region steam train.)                                                                                ::
    ID: 07006107.wav
    Length: 51
** Distant whistle from local train which leaves tunnel at speed. (Southern Region steam train.)                                                                                ::
    ID: 07006106.wav
    Length: 47
** Local train enters tunnel with whistle. (Southern Region steam train.)                                                                                ::
    ID: 07006105.wav
    Length: 41
** Local train arrives in station, steam, departs. (Southern Region steam train.)                                                                                ::
    ID: 07006104.wav
    Length: 128
** Doors close, local train leaves station. (Southern Region steam train.)                                                                                ::
    ID: 07006103.wav
    Length: 63
** Local train leaves station with whistle. (Southern Region steam train.)                                                                                ::
    ID: 07006102.wav
    Length: 69
** Local train leaves station, whistles. (Southern Region steam train.)                                                                                ::
    ID: 07006101.wav
    Length: 56
** Local train leaves station with whistle, passes under bridge, signal drops. (Southern Region steam train.)                                                                                ::
    ID: 07006100.wav
    Length: 51
** Shunting in a steam railway goods yard.                                                                                ::
    ID: 07006099.wav
    Length: 409
** Shunting in a steam railway goods yard.                                                                                ::
    ID: 07006098.wav
    Length: 111
** Coupling trucks in a steam railway goods yard.                                                                                ::
    ID: 07006097.wav
    Length: 72
** Shutting side of steel truck in a steam railway goods yard.                                                                                ::
    ID: 07006096.wav
    Length: 7
** Dropping side of steel truck in a steam railway goods yard.                                                                                ::
    ID: 07006095.wav
    Length: 16
** Shutting side of wooden truck in a steam railway goods yard.                                                                                ::
    ID: 07006094.wav
    Length: 11
** Dropping side of a wooden truck in a steam railway goods yard.                                                                                ::
    ID: 07006093.wav
    Length: 20
** Express train followed by goods train passing. (Steam train.)                                                                                ::
    ID: 07006092.wav
    Length: 76
** Brake van passing. (Steam train.)                                                                                ::
    ID: 07006091.wav
    Length: 35
** Light engine passing. (Steam train.)                                                                                ::
    ID: 07006090.wav
    Length: 46
** Goods train shunting. (Steam train.)                                                                                ::
    ID: 07006089.wav
    Length: 54
** Goods train with express train passing. (Steam train.)                                                                                ::
    ID: 07006088.wav
    Length: 108
** Long goods train entering tunnel. (Steam train.)                                                                                ::
    ID: 07006087.wav
    Length: 64
** Fast goods train passing. (Steam train.)                                                                                ::
    ID: 07006086.wav
    Length: 69
** Slow goods train passing with siren. (Steam train.)                                                                                ::
    ID: 07006085.wav
    Length: 90
** Slow goods train passing. (Steam train.)                                                                                ::
    ID: 07006084.wav
    Length: 72
** Goods train passing. (Steam train.)                                                                                ::
    ID: 07006083.wav
    Length: 59
** Express train passing without siren. (Western Region steam train.)                                                                                ::
    ID: 07006082.wav
    Length: 56
** Express train passing without siren. (Western Region steam train.)                                                                                ::
    ID: 07006081.wav
    Length: 44
** Express train passing without siren. (Western Region steam train.)                                                                                ::
    ID: 07006080.wav
    Length: 45
** Farnborough express train passing without siren. (Southern Region steam train.)                                                                                ::
    ID: 07006079.wav
    Length: 26
** Bournemouth Belle train passing without siren. (Southern Region steam train.)                                                                                ::
    ID: 07006078.wav
    Length: 27
** West Country express train passing without siren. (Southern Region steam train.)                                                                                ::
    ID: 07006077.wav
    Length: 46
** Western Region express train passing with siren. (Southern Region steam train.)                                                                                ::
    ID: 07006076.wav
    Length: 38
** Weymouth express train passing with siren. (Southern Region steam train.)                                                                                ::
    ID: 07006075.wav
    Length: 50
** Basingstoke express train passing with siren. (Southern Region steam train.)                                                                                ::
    ID: 07006074.wav
    Length: 52
** West of England express train passing with siren. (Southern Region steam train.)                                                                                ::
    ID: 07006073.wav
    Length: 47
** Bournemouth express train passing with siren. (Southern Region steam train.)                                                                                ::
    ID: 07006072.wav
    Length: 47
** Golden Arrow train passing with siren. (Southern Region steam train.)                                                                                ::
    ID: 07006071.wav
    Length: 50
** Southern Region express steam train, interior, medium-speed into fast constant run.                                                                                ::
    ID: 07006070.wav
    Length: 389
** Southern Region express steam train, interior, constant run, slow down to stop in station.                                                                                ::
    ID: 07006069.wav
    Length: 124
** Southern Region express steam train, interior, guard's whistle, move off into constant run.                                                                                ::
    ID: 07006068.wav
    Length: 278
** Exterior, Stroudley 0-6-0 tank locomotive whistle. (Southern Region train.)                                                                                ::
    ID: 07006067.wav
    Length: 11
** Exterior, train hauled by Stroudley 0-6-0 tank locomotive approach and pass with whistle. (Southern Region train.)                                                                                ::
    ID: 07006066.wav
    Length: 57
** Exterior, whistle, train hauled by Stroudley 0-6-0 tank locomotive departs from country station. (Southern Region train.)                                                                                ::
    ID: 07006065.wav
    Length: 49
** Exterior, whistle, local train hauled by Stroudley 0-6-0 tank locomotive departs. (Southern Region train.)                                                                                ::
    ID: 07006064.wav
    Length: 31
** Exterior, local train hauled by Stroudley 0-6-0 tank locomotive arrives in station, doors slam. (Southern Region train.)                                                                                ::
    ID: 07006063.wav
    Length: 61
** Stroudley 0-6-0 tank locomotive, slow down and stop in station, whistle, departs. (Southern region train.) (Recorded on footplate.)                                                                                ::
    ID: 07006062.wav
    Length: 102
** Stroudley 0-6-0 tank locomotive, steam, whistle, gathering speed. (Southern region train.) (Recorded on footplate.)                                                                                ::
    ID: 07006061.wav
    Length: 95
** Stroudley 0-6-0 tank locomotive, whistle into constant run, stops. (Southern Region train.) (Recorded on footplate.)                                                                                ::
    ID: 07006060.wav
    Length: 254
** Stroudley 0-6-0 tank locomotive running with one intermediate stop, with whistle. (Southern Region train.) (Recorded on footplate.)                                                                                ::
    ID: 07006059.wav
    Length: 371
** Stroudley 0-6-0 tank locomotive running in and out of local stations, with whistles. (Southern Region train.) (Recorded on footplate.)                                                                                ::
    ID: 07006058.wav
    Length: 364
** House-to-house milk delivery, early morning.                                                                                ::
    ID: 07006057.wav
    Length: 203
** Milk float stops. (Recorded on float)                                                                                ::
    ID: 07006056.wav
    Length: 34
** Milk float starts, moves into constant run. (Recorded on float)                                                                                ::
    ID: 07006055.wav
    Length: 155
** Milk float leaves depot, runs and stops in traffic. (Recorded on float)                                                                                ::
    ID: 07006054.wav
    Length: 210
** Loaded milk floats leave the depot.                                                                                ::
    ID: 07006053.wav
    Length: 127
** Carrier leaves filled with empty milk bottles.                                                                                ::
    ID: 07006052.wav
    Length: 53
** Atmosphere of milk floats being loaded using Slingsby trucks.                                                                                ::
    ID: 07006051.wav
    Length: 201
** Trailer loaded with empty bottles using a fork lift truck.                                                                                ::
    ID: 07006050.wav
    Length: 199
** Milk carrier arrives at dairy, full bottles unloaded using fork lift trucks.                                                                                ::
    ID: 07006049.wav
    Length: 217
** Milk tanker arrives at dairy, stops, milk transferred to milk holders.                                                                                ::
    ID: 07006048.wav
    Length: 191
** Bottle filling machine starts and operates, bell sounds, machine fades at end.                                                                                ::
    ID: 07006047.wav
    Length: 200
** Bottle washing machine starts, operates and fades at end.                                                                                ::
    ID: 07006046.wav
    Length: 198
** Electrical hum of milk churn refrigerator operating and sound of running liquid.                                                                                ::
    ID: 07006045.wav
    Length: 196
** Milk lorry departs.                                                                                ::
    ID: 07006044.wav
    Length: 61
** Milk lorry arrives, churns loaded and unloaded.                                                                                ::
    ID: 07006043.wav
    Length: 104
** Milking operation with teats fitted incorrectly to cow. (No animal sounds)                                                                                ::
    ID: 07006042.wav
    Length: 96
** Milking equipment being cleaned.                                                                                ::
    ID: 07006041.wav
    Length: 103
** Atmosphere of cows being prepared for milking, with footsteps, buckets being moved and machinery sounds in background.                                                                                ::
    ID: 07006040.wav
    Length: 166
** Electric line pump for mechanical milker starts and runs.                                                                                ::
    ID: 07006039.wav
    Length: 111
** Twelve-stall milking machine starts and runs. (No animal sounds)                                                                                ::
    ID: 07006038.wav
    Length: 269
** Six-stall milking machine starts, runs and stops. (No animal sounds)                                                                                ::
    ID: 07006037.wav
    Length: 379
** Cow being milked by hand, milk flows into churn, occasional 'moo' from animal being milked.                                                                                ::
    ID: 07006036.wav
    Length: 359
** Continuation and end of milking operation with electric milking unit.                                                                                ::
    ID: 07006035.wav
    Length: 305
** Preparations and start of milking operation with electric milking unit.                                                                                ::
    ID: 07006034.wav
    Length: 330
** Several teleprinters receiving messages.                                                                                ::
    ID: 07006033.wav
    Length: 378
** One teleprinter receiving a message.                                                                                ::
    ID: 07006032.wav
    Length: 191
** One teleprinter sending a message.                                                                                ::
    ID: 07006031.wav
    Length: 192
** Six typewriters being used.                                                                                ::
    ID: 07006030.wav
    Length: 220
** Two typewriters being used.                                                                                ::
    ID: 07006029.wav
    Length: 187
** One typewriter being used.                                                                                ::
    ID: 07006028.wav
    Length: 194
** One typewriter being used.                                                                                ::
    ID: 07006027.wav
    Length: 187
** General computer room atmosphere with printer in foreground.                                                                                ::
    ID: 07006026.wav
    Length: 369
** Card reader operating.                                                                                ::
    ID: 07006025.wav
    Length: 92
** ICT sorter, on, runs, off.                                                                                ::
    ID: 07006024.wav
    Length: 120
** ICT collator, on, runs, off.                                                                                ::
    ID: 07006023.wav
    Length: 156
** General atmosphere in an office printing unit with equipment operating.                                                                                ::
    ID: 07006022.wav
    Length: 409
** General atmosphere in post room, conversation as staff sort and frank mail.                                                                                ::
    ID: 07006021.wav
    Length: 275
** Photo-direct camera processor operating.                                                                                ::
    ID: 07006020.wav
    Length: 118
** Gordon Gotch collating machine, constant run. (Stacks printed sheets.)                                                                                ::
    ID: 07006019.wav
    Length: 123
** Roneo duplicator, several short runs and stops.                                                                                ::
    ID: 07006018.wav
    Length: 138
** Roneo duplicator, start, long run and stop.                                                                                ::
    ID: 07006017.wav
    Length: 113
** Multilith 1250 printing machine, constant run.                                                                                ::
    ID: 07006016.wav
    Length: 108
** Multilith 85 printing machine, constant run.                                                                                ::
    ID: 07006015.wav
    Length: 122
** Xerox photocopying machine, constant run.                                                                                ::
    ID: 07006014.wav
    Length: 122
** Rotoprint machine, constant run.                                                                                ::
    ID: 07006013.wav
    Length: 361
** One machine being used in an office.                                                                                ::
    ID: 07006012.wav
    Length: 165
** Two machines being used in an office.                                                                                ::
    ID: 07006011.wav
    Length: 162
** Two auto-key punches operating, occasional pause                                                                                ::
    ID: 07006010.wav
    Length: 164
** One auto-key punch operating, occasional pause.                                                                                ::
    ID: 07006009.wav
    Length: 163
** Reproducer operating, occasional pause.                                                                                ::
    ID: 07006008.wav
    Length: 168
** Card sorter operating, occasional pause.                                                                                ::
    ID: 07006007.wav
    Length: 161
** Three machines being used in an office, no speech.                                                                                ::
    ID: 07006006.wav
    Length: 301
** Seven machines being used in an office, no speech.                                                                                ::
    ID: 07006005.wav
    Length: 302
** Interpolator operating. (Punch card calcualtion machine.)                                                                                ::
    ID: 07006004.wav
    Length: 136
** Interpreter operating. (Punch card reader/printer.)                                                                                ::
    ID: 07006003.wav
    Length: 206
** Electronic multiplying punch operating.                                                                                ::
    ID: 07006002.wav
    Length: 165
** Tabulator operating, occasional pause.                                                                                ::
    ID: 07006001.wav
    Length: 163
** Storm recorded on Solomon Islands.                                                                                ::
    ID: 07005240.wav
    Length: 378
** Wind & rain, recorded inside a hut.                                                                                ::
    ID: 07005239.wav
    Length: 409
** Claps of thunder with rain. (Specially created)                                                                                ::
    ID: 07005238.wav
    Length: 37
** Claps of thunder with rain. (Specially created)                                                                                ::
    ID: 07005237.wav
    Length: 37
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005236.wav
    Length: 13
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005235.wav
    Length: 19
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005234.wav
    Length: 19
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005233.wav
    Length: 18
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005232.wav
    Length: 17
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005231.wav
    Length: 19
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005230.wav
    Length: 10
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005229.wav
    Length: 12
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005228.wav
    Length: 17
** Clap of thunder. (Specially created)                                                                                ::
    ID: 07005227.wav
    Length: 20
** Clap of thunder.                                                                                ::
    ID: 07005226.wav
    Length: 15
** Clap of thunder.                                                                                ::
    ID: 07005225.wav
    Length: 12
** Clap of thunder.                                                                                ::
    ID: 07005224.wav
    Length: 12
** Clap of thunder.                                                                                ::
    ID: 07005223.wav
    Length: 12
** Clap of thunder.                                                                                ::
    ID: 07005222.wav
    Length: 13
** Clap of thunder.                                                                                ::
    ID: 07005221.wav
    Length: 20
** Roll of thunder.                                                                                ::
    ID: 07005220.wav
    Length: 17
** Roll of thunder.                                                                                ::
    ID: 07005219.wav
    Length: 11
** Roll of thunder.                                                                                ::
    ID: 07005218.wav
    Length: 14
** Roll of thunder.                                                                                ::
    ID: 07005217.wav
    Length: 12
** Roll of thunder.                                                                                ::
    ID: 07005216.wav
    Length: 12
** Roll of thunder.                                                                                ::
    ID: 07005215.wav
    Length: 18
** Thunderstorm with light rain.                                                                                ::
    ID: 07005214.wav
    Length: 378
** Wind & rain against windows. (Interior recording.)                                                                                ::
    ID: 07005213.wav
    Length: 195
** Wind & rain in street.                                                                                ::
    ID: 07005212.wav
    Length: 185
** Heavy rain.                                                                                ::
    ID: 07005211.wav
    Length: 370
** Heavy rain, on turf and trees.                                                                                ::
    ID: 07005210.wav
    Length: 369
** Hail on window. (Interior recording.)                                                                                ::
    ID: 07005209.wav
    Length: 900
** Heavy rain, torrential.                                                                                ::
    ID: 07005208.wav
    Length: 905
** Low-pitched wind.                                                                                ::
    ID: 07005207.wav
    Length: 397
** High-pitched wind.                                                                                ::
    ID: 07005206.wav
    Length: 416
** Wind in trees.                                                                                ::
    ID: 07005205.wav
    Length: 357
** Arctic wind.                                                                                ::
    ID: 07005204.wav
    Length: 188
** Wind whistling through a crack.                                                                                ::
    ID: 07005203.wav
    Length: 185
** Strong, gusty wind.                                                                                ::
    ID: 07005202.wav
    Length: 371
** A blizzard.                                                                                ::
    ID: 07005201.wav
    Length: 373
** Sinister, deep-toned wind.                                                                                ::
    ID: 07005200.wav
    Length: 892
** Polar wind, very strong & gusty.                                                                                ::
    ID: 07005199.wav
    Length: 906
** Busy country pub.                                                                                ::
    ID: 07005198.wav
    Length: 366
** Quiet conversation in country pub.                                                                                ::
    ID: 07005197.wav
    Length: 369
** Women's darts match in London pub.                                                                                ::
    ID: 07005196.wav
    Length: 368
** Conversation in pub with fruit machines.                                                                                ::
    ID: 07005195.wav
    Length: 363
** A game of skittles being played in a suburban pub.                                                                                ::
    ID: 07005194.wav
    Length: 370
** A game of skittles being played in a pub.                                                                                ::
    ID: 07005193.wav
    Length: 369
** A game of bar billiards being played in a town saloon bar.                                                                                ::
    ID: 07005192.wav
    Length: 369
** A game of bar billiards being played in a town public bar.                                                                                ::
    ID: 07005191.wav
    Length: 371
** A game of darts being played in a town pub.                                                                                ::
    ID: 07005190.wav
    Length: 367
** A game of darts being played in a country pub.                                                                                ::
    ID: 07005189.wav
    Length: 367
** A game of dominoes being played in a town pub.                                                                                ::
    ID: 07005188.wav
    Length: 370
** A game of dominoes being played in a country pub.                                                                                ::
    ID: 07005187.wav
    Length: 369
** Sports Club Bar, lively chatter, sixty to seventy people.                                                                                ::
    ID: 07005186.wav
    Length: 367
** Sports Club Bar, lively chatter, twenty to thirty people.                                                                                ::
    ID: 07005185.wav
    Length: 368
** Medium-sized crowd in London suburban pub.                                                                                ::
    ID: 07005184.wav
    Length: 364
** Small crowd in London suburban pub.                                                                                ::
    ID: 07005183.wav
    Length: 356
** Chatter in Lincoln pub.                                                                                ::
    ID: 07005182.wav
    Length: 370
** Cash register, bell, change given and coins put in drawer, closed. (Three times)                                                                                ::
    ID: 07005181.wav
    Length: 27
** Cash register, bell, change given and coins put in drawer, closed. (Twice)                                                                                ::
    ID: 07005180.wav
    Length: 18
** Cash register, bell, keyboard, change given and coins put in drawer, closed.                                                                                ::
    ID: 07005179.wav
    Length: 14
** Cash register, bell, change given and coins put in drawer, closed                                                                                ::
    ID: 07005178.wav
    Length: 11
** Beer engine, half a pint of beer pulled.                                                                                ::
    ID: 07005177.wav
    Length: 7
** Beer engine, one pint of beer pulled.                                                                                ::
    ID: 07005176.wav
    Length: 11
** Large bird taking off, three attempts. (Specially created effect)                                                                                ::
    ID: 07005175.wav
    Length: 29
** One. (Specially created effect)                                                                                ::
    ID: 07005174.wav
    Length: 11
** Arrow landing. (Specially created effect)                                                                                ::
    ID: 07005173.wav
    Length: 6
** Busy workshop atmosphere. (Specially created effect)                                                                                ::
    ID: 07005172.wav
    Length: 21
** Flights of arrows. (Specially created effect)                                                                                ::
    ID: 07005171.wav
    Length: 27
** Portcullis closing. (Specially created effect)                                                                                ::
    ID: 07005170.wav
    Length: 6
** Snoring. (Specially created effect)                                                                                ::
    ID: 07005169.wav
    Length: 16
** Bubbling sound. (Specially created effect)                                                                                ::
    ID: 07005168.wav
    Length: 14
** Air escaping from punctured tyre. (Specially created effect)                                                                                ::
    ID: 07005167.wav
    Length: 9
** One goose gobbling. (Specially created effect)                                                                                ::
    ID: 07005166.wav
    Length: 19
** Assorted sheep bleating. (Specially created effect)                                                                                ::
    ID: 07005165.wav
    Length: 40
** Ewe and lamb bleating. (Specially created effect)                                                                                ::
    ID: 07005164.wav
    Length: 40
** One bluebottle circling at seven foot. (Specially created effect)                                                                                ::
    ID: 07005163.wav
    Length: 34
** Trio of horse neighs. (Specially created effect)                                                                                ::
    ID: 07005162.wav
    Length: 26
** One donkey donkeying. (Specially created effect)                                                                                ::
    ID: 07005161.wav
    Length: 23
** Wild boars having tea. (Specially created effect)                                                                                ::
    ID: 07005160.wav
    Length: 28
** Half a dozen werewolves. (Specially created effect)                                                                                ::
    ID: 07005159.wav
    Length: 21
** Bristle-backed duck. (Specially created effect)                                                                                ::
    ID: 07005158.wav
    Length: 40
** Mating cry of young donkey. (Specially created effect)                                                                                ::
    ID: 07005157.wav
    Length: 24
** Indisposed chicken, (Specially created effect)                                                                                ::
    ID: 07005156.wav
    Length: 10
** More-or-less normal chicken. (Specially created effect)                                                                                ::
    ID: 07005155.wav
    Length: 25
** Smoked herring gull. (Specially created effect)                                                                                ::
    ID: 07005154.wav
    Length: 7
** Irish nightingale. (Specially created effect)                                                                                ::
    ID: 07005153.wav
    Length: 61
** A country idyll, countryside atmosphere. (Specially created effect)                                                                                ::
    ID: 07005152.wav
    Length: 20
** Mother owl hooting. (Specially created effect)                                                                                ::
    ID: 07005151.wav
    Length: 6
** Father owl hooting. (Specially created effect)                                                                                ::
    ID: 07005150.wav
    Length: 9
** Small group cheering. (Specially created effect)                                                                                ::
    ID: 07005149.wav
    Length: 20
** Standard orgy, with smashing glass, screams, footsteps and whipping sounds. (Specially created effect)                                                                                ::
    ID: 07005148.wav
    Length: 29
** Radiophonic stomach, including explosion, whoosh, bubbling and belch. (Specially created effect)                                                                                ::
    ID: 07005147.wav
    Length: 14
** Ice creaking and cracking. (Specially created effect)                                                                                ::
    ID: 07005146.wav
    Length: 12
** One drawbridge opening sideways. (Specially created effect)                                                                                ::
    ID: 07005145.wav
    Length: 12
** Martian computer. (Specially created effect)                                                                                ::
    ID: 07005144.wav
    Length: 105
** Typing with three hands. (Specially created effect)                                                                                ::
    ID: 07005143.wav
    Length: 92
** Single woodpecker practising. (Specially created effect)                                                                                ::
    ID: 07005142.wav
    Length: 44
** Long, drawn out crash. (Specially created effect)                                                                                ::
    ID: 07005141.wav
    Length: 30
** One tree sagging and crashing. (Specially created effect)                                                                                ::
    ID: 07005140.wav
    Length: 14
** Cuckoo clock tester. (Specially created effect)                                                                                ::
    ID: 07005139.wav
    Length: 82
** Clock cartoon. (Specially created effect)                                                                                ::
    ID: 07005138.wav
    Length: 13
** Twangs made using wooden ruler. (Specially created effect)                                                                                ::
    ID: 07005137.wav
    Length: 22
** Sequence played on Jews' harp. (Specially created effect)                                                                                ::
    ID: 07005136.wav
    Length: 22
** Chemical computer. (Specially created effect)                                                                                ::
    ID: 07005135.wav
    Length: 99
** Tank riveter. (Specially created effect)                                                                                ::
    ID: 07005134.wav
    Length: 68
** Coconut milk extractor. (Specially created effect)                                                                                ::
    ID: 07005133.wav
    Length: 53
** Coathanger bender. (Specially created effect)                                                                                ::
    ID: 07005132.wav
    Length: 44
** Sausage counter. (Specially created effect)                                                                                ::
    ID: 07005131.wav
    Length: 66
** Bottle-top tester. (Specially created effect)                                                                                ::
    ID: 07005130.wav
    Length: 59
** Clockwork airship inflator. (Specially created effect)                                                                                ::
    ID: 07005129.wav
    Length: 44
** Hand operated sewing machine. (Specially created effect)                                                                                ::
    ID: 07005128.wav
    Length: 71
** Traffic jam, pause, jam with moving traffic. (Specially created effect)                                                                                ::
    ID: 07005127.wav
    Length: 46
** Three impact crashes. (Specially created effect)                                                                                ::
    ID: 07005126.wav
    Length: 13
** Milk bottle breaking. (Specially created effect)                                                                                ::
    ID: 07005125.wav
    Length: 5
** Crash of piano. (Specially created effect)                                                                                ::
    ID: 07005124.wav
    Length: 12
** Crowd panic. (Specially created effect)                                                                                ::
    ID: 07005123.wav
    Length: 21
** Pouring liquid. (Specially created effect)                                                                                ::
    ID: 07005122.wav
    Length: 42
** Breaking down door. (Specially created effect)                                                                                ::
    ID: 07005121.wav
    Length: 39
** Hammer testing. (Specially created effect)                                                                                ::
    ID: 07005120.wav
    Length: 22
** Several men coughing. (Specially created effect)                                                                                ::
    ID: 07005119.wav
    Length: 18
** One penny dropped. (Specially created effect)                                                                                ::
    ID: 07005118.wav
    Length: 6
** One penny dropped. (Specially created effect)                                                                                ::
    ID: 07005117.wav
    Length: 8
** Clockwork mechanism. (Specially created effect)                                                                                ::
    ID: 07005116.wav
    Length: 27
** Knocking with doors opening and closing. (Specially created effect)                                                                                ::
    ID: 07005115.wav
    Length: 23
** Squeaky feet, door open and close with squeak. (Specially created effect)                                                                                ::
    ID: 07005114.wav
    Length: 20
** Strolling through ovens, oven door open and close. (Specially created effect)                                                                                ::
    ID: 07005113.wav
    Length: 34
** One pair of feet overhead and removing boots. (Specially created effect)                                                                                ::
    ID: 07005112.wav
    Length: 40
** One pair of feet approach to door, door open and close, feet depart. (Specially created effect)                                                                                ::
    ID: 07005111.wav
    Length: 8
** Feet overhead on wood. (Specially created effect)                                                                                ::
    ID: 07005110.wav
    Length: 29
** Group in foreground running to stop. (Specially created effect)                                                                                ::
    ID: 07005109.wav
    Length: 23
** Two people run to distance and double splash. (Specially created effect)                                                                                ::
    ID: 07005108.wav
    Length: 15
** Run to distance and splash. (Specially created effect)                                                                                ::
    ID: 07005107.wav
    Length: 12
** Run to distance and return. (Specially created effect)                                                                                ::
    ID: 07005106.wav
    Length: 22
** One pair of feet approach and stop. (Specially created effect)                                                                                ::
    ID: 07005105.wav
    Length: 7
** One pair of feet approach and explosion. (Specially created effect)                                                                                ::
    ID: 07005104.wav
    Length: 12
** One angel in flight. (Specially created effect)                                                                                ::
    ID: 07005103.wav
    Length: 62
** Atmosphere in a clock shop, with ticking and chimes. (Specially created effect)                                                                                ::
    ID: 07005102.wav
    Length: 67
** Single car running comically. (Specially created effect)                                                                                ::
    ID: 07005101.wav
    Length: 72
** Water dripping. (Specially created effect)                                                                                ::
    ID: 07005100.wav
    Length: 74
** Musical explosion. (Specially created effect)                                                                                ::
    ID: 07005099.wav
    Length: 11
** Twangs made using metal ruler. (Specially created effect)                                                                                ::
    ID: 07005098.wav
    Length: 17
** Paddle steamer rhythm. (Specially created effect)                                                                                ::
    ID: 07005097.wav
    Length: 43
** Man drinking bucket of cold cocoa. (Specially created effect)                                                                                ::
    ID: 07005096.wav
    Length: 20
** Several men snoring, less hilariously. (Specially created effect)                                                                                ::
    ID: 07005095.wav
    Length: 65
** Several men snoring hilariously. (Specially created effect)                                                                                ::
    ID: 07005094.wav
    Length: 74
** Several men snoring. (Specially created effect)                                                                                ::
    ID: 07005093.wav
    Length: 38
** Man snoring. (Specially created effect)                                                                                ::
    ID: 07005092.wav
    Length: 25
** High-speed telephone gibberish. (Specially created effect)                                                                                ::
    ID: 07005091.wav
    Length: 64
** Swordfight with shots and groans. (Specially created effect)                                                                                ::
    ID: 07005090.wav
    Length: 35
** Saloon bar brawl. (Specially created effect)                                                                                ::
    ID: 07005089.wav
    Length: 117
** Scuffle with twangs. (Specially created effect)                                                                                ::
    ID: 07005088.wav
    Length: 29
** Busy English market. (Specially created effect)                                                                                ::
    ID: 07005087.wav
    Length: 74
** Crowd panic and rush for exits. (Specially created effect)                                                                                ::
    ID: 07005086.wav
    Length: 21
** English club chatter. (Specially created effect)                                                                                ::
    ID: 07005085.wav
    Length: 54
** Oriental workshop. (Specially created effect)                                                                                ::
    ID: 07005083.wav
    Length: 34
** Half-hearted hurrahs and cheers. (Specially created effect)                                                                                ::
    ID: 07005082.wav
    Length: 19
** Feeble applause. (Specially created effect)                                                                                ::
    ID: 07005081.wav
    Length: 22
** Booing and bleating. (Specially created effect)                                                                                ::
    ID: 07005080.wav
    Length: 58
** Mighty balloon bursts. (Specially created effect)                                                                                ::
    ID: 07005079.wav
    Length: 10
** Rocket ship landing. (Specially created effect)                                                                                ::
    ID: 07005078.wav
    Length: 33
** Rocket ship antics. (Specially created effect)                                                                                ::
    ID: 07005077.wav
    Length: 24
** Rocket ship takes off. (Specially created effect)                                                                                ::
    ID: 07005076.wav
    Length: 50
** Rocket ship explodes. (Specially created effect)                                                                                ::
    ID: 07005075.wav
    Length: 13
** One whoosh, two whooshes. (Specially created effect)                                                                                ::
    ID: 07005074.wav
    Length: 7
** Experimental laboratory. (Specially created effect)                                                                                ::
    ID: 07005073.wav
    Length: 41
** Falling pennies. (Specially created effect)                                                                                ::
    ID: 07005072.wav
    Length: 37
** Clock nightmare. (Specially created effect)                                                                                ::
    ID: 07005071.wav
    Length: 28
** Cod machinery operating. (Specially created effect)                                                                                ::
    ID: 07005070.wav
    Length: 31
** Busy atmosphere. (Specially created effect)                                                                                ::
    ID: 07005069.wav
    Length: 57
** One ship colliding. (Specially created effect)                                                                                ::
    ID: 07005068.wav
    Length: 18
** Cod indoor fight. (Specially created effect)                                                                                ::
    ID: 07005067.wav
    Length: 27
** Single projectile approach and ricochet. (Specially created effect)                                                                                ::
    ID: 07005066.wav
    Length: 26
** Colliding traffic with horns. (Specially created effect)                                                                                ::
    ID: 07005065.wav
    Length: 37
** Man dragged out of piano. (Specially created effect)                                                                                ::
    ID: 07005064.wav
    Length: 12
** Birds taking off. (Specially created effect)                                                                                ::
    ID: 07005063.wav
    Length: 4
** Things falling and clanging. (Specially created effect)                                                                                ::
    ID: 07005062.wav
    Length: 15
** Single cork pop and heavy guzzling. (Specially created effect)                                                                                ::
    ID: 07005061.wav
    Length: 10
** Sawing stale bread. (Specially created effect)                                                                                ::
    ID: 07005060.wav
    Length: 24
** Masticating apple. (Specially created effect)                                                                                ::
    ID: 07005059.wav
    Length: 30
** Sawing tree and crash. (Specially created effect)                                                                                ::
    ID: 07005058.wav
    Length: 19
** Stove dropped. (Specially created effect)                                                                                ::
    ID: 07005057.wav
    Length: 8
** Studio Native Americans whooping. (Specially created effect)                                                                                ::
    ID: 07005056.wav
    Length: 37
** Three whooshes with ripping fabric. (Specially created effect)                                                                                ::
    ID: 07005055.wav
    Length: 20
** Clang and drop of cymbals. (Specially created effect)                                                                                ::
    ID: 07005054.wav
    Length: 8
** Squeaky trolley bumped along. (Specially created effect)                                                                                ::
    ID: 07005053.wav
    Length: 53
** Squeaky trolley. (Specially created effect)                                                                                ::
    ID: 07005052.wav
    Length: 48
** Frantic banging and clanging. (Specially created effect)                                                                                ::
    ID: 07005051.wav
    Length: 34
** Train crash. (Specially created effect)                                                                                ::
    ID: 07005050.wav
    Length: 11
** Lava bubbling. (Specially created effect)                                                                                ::
    ID: 07005049.wav
    Length: 71
** Tap turned on, fizzy liquid gurgles out. (Specially created effect)                                                                                ::
    ID: 07005048.wav
    Length: 47
** Glass bottles tipped on to floor. (Specially created effect)                                                                                ::
    ID: 07005047.wav
    Length: 22
** Clanging. (Specially created effect)                                                                                ::
    ID: 07005046.wav
    Length: 9
** Shovelling tins. (Specially created effect)                                                                                ::
    ID: 07005045.wav
    Length: 40
** One piano dragged along. (Specially created effect)                                                                                ::
    ID: 07005044.wav
    Length: 75
** Bong doying, Jews' harp. (Specially created effect)                                                                                ::
    ID: 07005043.wav
    Length: 9
** Doying pop doying. (Specially created effect)                                                                                ::
    ID: 07005042.wav
    Length: 7
** Single belch. (Specially created effect)                                                                                ::
    ID: 07005041.wav
    Length: 6
** Whoosh bing bang doying. (Specially created effect)                                                                                ::
    ID: 07005040.wav
    Length: 5
** Clong bong doying. (Specially created effect)                                                                                ::
    ID: 07005039.wav
    Length: 6
** Jangle flong. (Specially created effect)                                                                                ::
    ID: 07005038.wav
    Length: 6
** Razz razz bang jangle. (Specially created effect)                                                                                ::
    ID: 07005037.wav
    Length: 6
** Wallop clang jangle. (Specially created effect)                                                                                ::
    ID: 07005036.wav
    Length: 6
** Whizz clong. (Specially created effect)                                                                                ::
    ID: 07005035.wav
    Length: 6
** Razz rhythm clang. (Specially created effect)                                                                                ::
    ID: 07005034.wav
    Length: 9
** Tum punch. (Specially created effect)                                                                                ::
    ID: 07005033.wav
    Length: 5
** Four batter puddings thrown. (Specially created effect)                                                                                ::
    ID: 07005032.wav
    Length: 7
** Hunt ball chatter, without music. (Quorn Hunt.)                                                                                ::
    ID: 07005031.wav
    Length: 362
** Hounds at freedom, yelping and howling. (Quorn Hunt.)                                                                                ::
    ID: 07005030.wav
    Length: 177
** The kill, shouts, hunting horn and chatter. (Quorn Hunt.)                                                                                ::
    ID: 07005029.wav
    Length: 145
** Horse driven into box. (Quorn Hunt.)                                                                                ::
    ID: 07005028.wav
    Length: 19
** Whipping in, hunting horn and atmosphere. (Quorn Hunt.)                                                                                ::
    ID: 07005027.wav
    Length: 208
** Whipping in, whips and atmosphere. (Quorn Hunt.)                                                                                ::
    ID: 07005026.wav
    Length: 128
** Hunting horn call, calling hounds when on the move.  (Quorn Hunt.)                                                                                ::
    ID: 07005025.wav
    Length: 11
** Hunting horn call, the kill.  (Quorn Hunt.)                                                                                ::
    ID: 07005024.wav
    Length: 11
** Hunting horn call, going home.  (Quorn Hunt.)                                                                                ::
    ID: 07005023.wav
    Length: 12
** Hunting horn call, calling hounds out of cover.  (Quorn Hunt.)                                                                                ::
    ID: 07005022.wav
    Length: 11
** Hunting horn call, For'ard away.  (Quorn Hunt.)                                                                                ::
    ID: 07005021.wav
    Length: 13
** Hunting horn call, drawing the cover. (Quorn Hunt.)                                                                                ::
    ID: 07005020.wav
    Length: 10
** In cover, hounds yelping and moving about. (Quorn Hunt.)                                                                                ::
    ID: 07005019.wav
    Length: 118
** In cover, hunting horn, shouts and whistles, whips. (Quorn Hunt.)                                                                                ::
    ID: 07005018.wav
    Length: 134
** Hounds into cover, hunting horn and cries. (Quorn Hunt.)                                                                                ::
    ID: 07005017.wav
    Length: 60
** Huntsman cries three times. (Quorn Hunt.)                                                                                ::
    ID: 07005016.wav
    Length: 33
** Horses gallop past on soft surface. (Quorn Hunt.)                                                                                ::
    ID: 07005015.wav
    Length: 103
** Horses canter past singly on muddy track. (Quorn Hunt.)                                                                                ::
    ID: 07005014.wav
    Length: 107
** Horses canter past on soft surface, hounds in full cry. (Quorn Hunt.)                                                                                ::
    ID: 07005013.wav
    Length: 58
** Horses canter past on soft surface, hounds and hunting horn. (Quorn Hunt.)                                                                                ::
    ID: 07005012.wav
    Length: 43
** Horses canter past, hunting horn. (Quorn Hunt.)                                                                                ::
    ID: 07005011.wav
    Length: 112
** Horses canter past on road. (Quorn Hunt.)                                                                                ::
    ID: 07005010.wav
    Length: 106
** Horses jumping hedge singly. (Quorn Hunt.)                                                                                ::
    ID: 07005009.wav
    Length: 43
** Horses canter through undergrowth. (Quorn Hunt.)                                                                                ::
    ID: 07005008.wav
    Length: 55
** At the meet, general atmosphere. (Quorn Hunt.)                                                                                ::
    ID: 07005007.wav
    Length: 213
** Horses canter past. (Quorn Hunt.)                                                                                ::
    ID: 07005006.wav
    Length: 68
** Horse canters past, hunting horn, many horses canter past. (Quorn Hunt.)                                                                                ::
    ID: 07005005.wav
    Length: 64
** Fox located. (Whaddon Chase Hunt.)                                                                                ::
    ID: 07005004.wav
    Length: 109
** Beating for fox. (Whaddon Chase Hunt.)                                                                                ::
    ID: 07005003.wav
    Length: 120
** Hunt moves off. (Whaddon Chase Hunt.)                                                                                ::
    ID: 07005002.wav
    Length: 115
** At the meet, general atmosphere. (Whaddon Chase Hunt.)                                                                                ::
    ID: 07005001.wav
    Length: 394
** Interior, start, move off fast into constant run. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004335.wav
    Length: 21
** Interior, start, move off fast into constant run. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004334.wav
    Length: 35
** Interior, slow down, stop. (Sports car, 1967 model)                                                                                ::
    ID: 07004333.wav
    Length: 31
** Interior, start, constant run with transmission effect. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004332.wav
    Length: 260
** Interior, slow down, stop. (Sports car, 1967 model)                                                                                ::
    ID: 07004331.wav
    Length: 24
** Interior, start, constant run at medium speed. (Sports car, 1967 model)                                                                                ::
    ID: 07004330.wav
    Length: 385
** Interior, close start, tickover, switch off. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004329.wav
    Length: 89
** Interior, start, tickover, switch off. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004328.wav
    Length: 189
** Interior, two doors close. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004327.wav
    Length: 7
** Interior, two doors open. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004326.wav
    Length: 8
** Interior, one door close. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004325.wav
    Length: 7
** Interior, one door open. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004324.wav
    Length: 8
** Exterior, reverse to microphone, tickover, switch off. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004323.wav
    Length: 36
** Exterior, reverse to microphone, tickover, switch off. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004322.wav
    Length: 23
** Exterior, fast approach and pass. (Sports car, 1967 model)                                                                                ::
    ID: 07004321.wav
    Length: 42
** Exterior, fairly fast approach and pass. (Sports car, 1967 model)                                                                                ::
    ID: 07004320.wav
    Length: 55
** Exterior, slow approach and pass. (Sports car, 1967 model)                                                                                ::
    ID: 07004319.wav
    Length: 35
** Exterior, approach, stop, tickover, switch off. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004318.wav
    Length: 22
** Exterior, approach, stop, tickover, switch off. (Sports car 1967 model M.G. Midget)                                                                                ::
    ID: 07004317.wav
    Length: 28
** Exterior, distant start and depart. (Sports car, 1967 model)                                                                                ::
    ID: 07004316.wav
    Length: 35
** Exterior, close start and depart. (Sports car, 1967 model)                                                                                ::
    ID: 07004315.wav
    Length: 33
** Exterior, start, revving. (Sports car, 1967 M.G. Midget)                                                                                ::
    ID: 07004314.wav
    Length: 190
** Exterior, start, tickover, switch off. (Sports car, 1967 M.G. Midget)                                                                                ::
    ID: 07004313.wav
    Length: 257
** Exterior, two doors close. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004312.wav
    Length: 7
** Exterior, two doors open. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004311.wav
    Length: 7
** Exterior, one door close. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004310.wav
    Length: 7
** Exterior, one door open. (Sports car, 1967 model M.G. Midget)                                                                                ::
    ID: 07004309.wav
    Length: 8
** Exterior, fast approach and pass. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004308.wav
    Length: 36
** Exterior, long approach and pass. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004307.wav
    Length: 55
** Exterior, approach, stop, tickover, depart. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004306.wav
    Length: 69
** Exterior, approach, stop, tickover, switch off. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004305.wav
    Length: 36
** Exterior, self starter, depart. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004304.wav
    Length: 42
** Exterior, self starter, tickover. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004303.wav
    Length: 156
** Interior, self starter, tickover, move off into constant run, with wind. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004302.wav
    Length: 387
** Interior, self starter, move off into constant run, slow down, stop, switch off. (1966 1798cc MGB open sports car) Cars:                                                                                 :Cars:MGB:
    ID: 07004301.wav
    Length: 358
** Interior, self starter, reversing. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004300.wav
    Length: 54
** Interior, 1 door closing. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004299.wav
    Length: 8
** Interior, 1 door opening. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004298.wav
    Length: 7
** Interior, self starter, tickover. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004297.wav
    Length: 141
** Interior, self starter, engine starts with difficulty, tickover. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004296.wav
    Length: 62
** Interior, self starter. (1966 1798cc MGB open sports car)                                                                                ::
    ID: 07004295.wav
    Length: 9
** Interior, slow down and stop, with fast traffic. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004294.wav
    Length: 34
** Interior, move off into constant run on motorway. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004293.wav
    Length: 383
** Interior, slow down, stop, switch off. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004292.wav
    Length: 24
** Interior, start into constant run at 50 m.p.h. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004291.wav
    Length: 385
** Interior, slow down and stop. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004290.wav
    Length: 23
** Interior, start, into medium-speed constant run in traffic. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004289.wav
    Length: 390
** Interior, false start, revving, with traffic. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004288.wav
    Length: 96
** Interior, start, reversing. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004287.wav
    Length: 172
** Interior, 2 doors close. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004286.wav
    Length: 6
** Interior, 1 door close. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004285.wav
    Length: 6
** Interior, 1 door open. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004284.wav
    Length: 8
** Interior, start, tickover, switch off. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004283.wav
    Length: 216
** Interior, start, tickover, revving, switch off. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004282.wav
    Length: 84
** Interior, false start. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004281.wav
    Length: 11
** Exterior, start, three-point turn, stop. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004280.wav
    Length: 25
** Exterior, start, three-point turn, depart. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004279.wav
    Length: 55
** Exterior, passing at speed with horn. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004278.wav
    Length: 34
** Exterior, approach and pass at 70 m.p.h. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004277.wav
    Length: 20
** Exterior, approach and pass at 60 m.p.h. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004276.wav
    Length: 28
** Exterior, approach and pass at medium speed. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004275.wav
    Length: 38
** Exterior, approach and stop, tickover, switch off. (Wolseley sixteen-sixty car)                                                                                ::
    ID: 07004274.wav
    Length: 42
** Exterior, approach and stop, tickover. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004273.wav
    Length: 29
** Exterior, start, fast depart. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004272.wav
    Length: 28
** Exterior, start, depart. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004271.wav
    Length: 46
** Exterior, starts, revving. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004270.wav
    Length: 188
** Exterior, start, tickover. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004269.wav
    Length: 260
** Exterior, 2 doors close. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004268.wav
    Length: 7
** Exterior, 1 door close. (wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004267.wav
    Length: 6
** Exterior, 1 door open. (Wolseley sixteen-sixty car, 1967)                                                                                ::
    ID: 07004266.wav
    Length: 6
** Filling glass vase with water.                                                                                ::
    ID: 07004265.wav
    Length: 21
** 3 small splashes.                                                                                ::
    ID: 07004264.wav
    Length: 10
** 2 small splashes.                                                                                ::
    ID: 07004263.wav
    Length: 10
** Small splash.                                                                                ::
    ID: 07004262.wav
    Length: 6
** Emptying bucket of water.                                                                                ::
    ID: 07004261.wav
    Length: 8
** 200 year old village pump filling bucket with water.                                                                                ::
    ID: 07004260.wav
    Length: 33
** Emptying metal bucket of water into sink.                                                                                ::
    ID: 07004259.wav
    Length: 24
** Filling metal bucket with water.                                                                                ::
    ID: 07004258.wav
    Length: 50
** Emptying plastic water holder into sink.                                                                                ::
    ID: 07004257.wav
    Length: 20
** Filling plastic water holder.                                                                                ::
    ID: 07004256.wav
    Length: 19
** Emptying plastic bucket of water into sink.                                                                                ::
    ID: 07004255.wav
    Length: 18
** Filling plastic bucket with water.                                                                                ::
    ID: 07004254.wav
    Length: 44
** Lid off, 2 pint-pan filled with water and emptied into sink.                                                                                ::
    ID: 07004253.wav
    Length: 43
** Lid off, large saucepan filled with water, lid on.                                                                                ::
    ID: 07004252.wav
    Length: 37
** Lid off, small saucepan filled with water, lid on.                                                                                ::
    ID: 07004251.wav
    Length: 21
** Emptying metal basin full of water.                                                                                ::
    ID: 07004250.wav
    Length: 13
** Filling metal basin with water.                                                                                ::
    ID: 07004249.wav
    Length: 22
** Pouring basin full of water into sink.                                                                                ::
    ID: 07004248.wav
    Length: 12
** Filling large basin with water.                                                                                ::
    ID: 07004247.wav
    Length: 30
** Emptying tin sink.                                                                                ::
    ID: 07004246.wav
    Length: 20
** Filling tin sink with water.                                                                                ::
    ID: 07004245.wav
    Length: 47
** Emptying stone sink.                                                                                ::
    ID: 07004244.wav
    Length: 16
** Filling stone sink with water.                                                                                ::
    ID: 07004243.wav
    Length: 55
** Emptying metal sink.                                                                                ::
    ID: 07004242.wav
    Length: 19
** Filling metal sink with water.                                                                                ::
    ID: 07004241.wav
    Length: 37
** Emptying sink.                                                                                ::
    ID: 07004240.wav
    Length: 20
** Filling enamel sink with water. (Stopper in)                                                                                ::
    ID: 07004239.wav
    Length: 57
** Filling enamel sink with water. (No stopper)                                                                                ::
    ID: 07004238.wav
    Length: 51
** Old village pump filling bucket with water.                                                                                ::
    ID: 07004237.wav
    Length: 32
** Old village pump filling bucket with water.                                                                                ::
    ID: 07004236.wav
    Length: 25
** Bucket dropped 3 times.                                                                                ::
    ID: 07004235.wav
    Length: 34
** Hoisting bucket.                                                                                ::
    ID: 07004234.wav
    Length: 90
** Bucket clipped to rope, free run down well.                                                                                ::
    ID: 07004233.wav
    Length: 69
** Hoisting bucket with windlass, uncoupled, lid closed.                                                                                ::
    ID: 07004232.wav
    Length: 94
** Bucket on a short run down a well, ends with a splash.                                                                                ::
    ID: 07004231.wav
    Length: 11
** Bucket clipped to rope, lid opened, fast run down well.                                                                                ::
    ID: 07004230.wav
    Length: 39
** Washing hands in bucket.                                                                                ::
    ID: 07004229.wav
    Length: 76
** Knocking in pipes. (Water pipes)                                                                                ::
    ID: 07004228.wav
    Length: 70
** Water thrown from plastic bucket. (3 times)                                                                                ::
    ID: 07004227.wav
    Length: 11
** Water thrown from metal bucket on to concrete.                                                                                ::
    ID: 07004226.wav
    Length: 8
** Filling metal bucket from pond and pouring water on to grass.                                                                                ::
    ID: 07004225.wav
    Length: 19
** Filling plastic bucket from pond and pouring water on to concrete. (3 times)                                                                                ::
    ID: 07004224.wav
    Length: 35
** Filling metal bucket from pond and pouring water on to concrete. (Twice)                                                                                ::
    ID: 07004223.wav
    Length: 30
** Pouring bucket of water down drain.                                                                                ::
    ID: 07004222.wav
    Length: 14
** Hand pump being used.                                                                                ::
    ID: 07004221.wav
    Length: 52
** Hand pump being used.                                                                                ::
    ID: 07004220.wav
    Length: 53
** Hand pump being used.                                                                                ::
    ID: 07004219.wav
    Length: 38
** Hand pump being used.                                                                                ::
    ID: 07004218.wav
    Length: 50
** Animated home movie viewer/editor, splicing film.                                                                                ::
    ID: 07004217.wav
    Length: 39
** Animated home movie/editor, removing spools, lid closed.                                                                                ::
    ID: 07004216.wav
    Length: 21
** Animated home movie viewer/editor, winding film in reverse.                                                                                ::
    ID: 07004215.wav
    Length: 40
** Animated home movie viewer/editor, winding film forwards.                                                                                ::
    ID: 07004214.wav
    Length: 53
** Animated home movie viewer/editor, putting on spools                                                                                ::
    ID: 07004213.wav
    Length: 32
** An 8mm cine projector, threading film and power rewind. (Make of projector not known)                                                                                ::
    ID: 07004212.wav
    Length: 41
** Euming 8mm cine projector. Start; run in reverse; stop                                                                                ::
    ID: 07004211.wav
    Length: 102
** Eumig 8mm cine projector. Start; run; stop                                                                                ::
    ID: 07004210.wav
    Length: 217
** Eumig 8mm cine projector. Threading film and short test run.                                                                                 ::
    ID: 07004209.wav
    Length: 43
** 16mm RCA cine projector. Running badly (machine faulty)                                                                                ::
    ID: 07004208.wav
    Length: 49
** 16mm RCA cine projector. Running without spools.                                                                                 ::
    ID: 07004207.wav
    Length: 90
** 16mm RCA cine projector. Power rewind.                                                                                ::
    ID: 07004206.wav
    Length: 98
** 16mm RCA cine projector. Hand rewind.                                                                                 ::
    ID: 07004205.wav
    Length: 64
** 16mm RCA cine projector. Start, run, stop.                                                                                ::
    ID: 07004204.wav
    Length: 351
** 16mm RCA cine projector. Threading film and short test run.                                                                                ::
    ID: 07004203.wav
    Length: 58
** Modern 35mm cine projector. Start, run, stop                                                                                 ::
    ID: 07004202.wav
    Length: 121
** Modern 35mm cine projector. Start run and stop (without sound).                                                                                ::
    ID: 07004201.wav
    Length: 137
** Modern 35mm cine projector. Threading film.                                                                                 ::
    ID: 07004200.wav
    Length: 52
** A 1938 Ross GC sound projector, start, run, stop. (35mm)                                                                                ::
    ID: 07004199.wav
    Length: 192
** A 1927 Kalee 7, start, run stop. (35mm)                                                                                ::
    ID: 07004198.wav
    Length: 192
** Metal scrap yard. Heavy background with machinery                                                                                ::
    ID: 07004197.wav
    Length: 257
** Metal scrap yard. Light background with hammering.                                                                                ::
    ID: 07004196.wav
    Length: 174
** An auto presser operating. (In a metal scrap yard)                                                                                ::
    ID: 07004195.wav
    Length: 144
** A crane moves in to position. (In a metal scrab yard)                                                                                ::
    ID: 07004194.wav
    Length: 150
** A lorry arrives, tips, departs. (In a metal scrap yard)                                                                                ::
    ID: 07004193.wav
    Length: 94
** Gyros operating, each with start and stop. 6 gyros, independently switched                                                                                 ::
    ID: 07004192.wav
    Length: 154
** Gyros operating, each with start and stop. 3-phase A.C gyro.                                                                                ::
    ID: 07004191.wav
    Length: 264
** D.C. rotary converter, constant run.                                                                                ::
    ID: 07004190.wav
    Length: 57
** D.C. rotary converter operating in short bursts.                                                                                ::
    ID: 07004189.wav
    Length: 36
** A varying electrical hum.                                                                                ::
    ID: 07004188.wav
    Length: 136
** A varying electric hum.                                                                                ::
    ID: 07004187.wav
    Length: 81
** RGD tape machine operating with start and stop.                                                                                ::
    ID: 07004186.wav
    Length: 75
** Entrance hall, footsteps on stone with traffic and swing doors in background.                                                                                ::
    ID: 07004185.wav
    Length: 283
** 2 people in ski boots walking up snow slope.                                                                                ::
    ID: 07004184.wav
    Length: 106
** 2 people in ski boots walking down snow slope.                                                                                ::
    ID: 07004183.wav
    Length: 88
** 2 people clambering over loose debris.                                                                                ::
    ID: 07004182.wav
    Length: 106
** 1 person clambering over loose debris.                                                                                ::
    ID: 07004181.wav
    Length: 92
** Running, 2 people in shallow water.                                                                                ::
    ID: 07004180.wav
    Length: 98
** Running, 1 man in shallow water.                                                                                ::
    ID: 07004179.wav
    Length: 97
** Walking, 2 men in shallow water                                                                                ::
    ID: 07004178.wav
    Length: 95
** Walking, 1 man in shallow water.                                                                                ::
    ID: 07004177.wav
    Length: 98
** Running, 1 man in mud.                                                                                ::
    ID: 07004176.wav
    Length: 78
** Walking, 2 people in mud.                                                                                ::
    ID: 07004175.wav
    Length: 99
** Walking, 1 person in mud                                                                                ::
    ID: 07004174.wav
    Length: 94
** Running, 2 people in wet sand. (With start and stop)                                                                                ::
    ID: 07004173.wav
    Length: 97
** Running, 1 person in wet sand.                                                                                ::
    ID: 07004172.wav
    Length: 80
** Walking, 2 men in wet sand.                                                                                ::
    ID: 07004171.wav
    Length: 95
** Walking, 1 man in wet sand. (Medium tempo)                                                                                ::
    ID: 07004170.wav
    Length: 99
** Footsteps down stone stairs, 1 woman departing.                                                                                ::
    ID: 07004169.wav
    Length: 16
** Footsteps down stone stairs, 1 woman. (With approach and stop)                                                                                ::
    ID: 07004168.wav
    Length: 13
** Footsteps down stone stairs, 1 woman. (With start and stop)                                                                                ::
    ID: 07004167.wav
    Length: 60
** Footsteps down stone stairs, 2 men departing.                                                                                ::
    ID: 07004166.wav
    Length: 15
** Footsteps down stone stairs, 2 men. (With approach and stop)                                                                                ::
    ID: 07004165.wav
    Length: 15
** Footsteps down stone stairs, 2 men. (With start and stop)                                                                                ::
    ID: 07004164.wav
    Length: 66
** Footsteps down stone stairs, 1 man departing.                                                                                ::
    ID: 07004163.wav
    Length: 18
** Footsteps down stone stairs, 1 man. (With approach and stop)                                                                                ::
    ID: 07004162.wav
    Length: 14
** Footsteps down stone stairs, 1 man. (With start and stop)                                                                                ::
    ID: 07004161.wav
    Length: 86
** Fast footsteps down stone stairs, 2 women departing.                                                                                ::
    ID: 07004160.wav
    Length: 10
** Fast footsteps down stone stairs, 2 women. (With approach and stop)                                                                                ::
    ID: 07004159.wav
    Length: 11
** Fast footsteps down stone stairs, 1 woman. (With start and stop)                                                                                ::
    ID: 07004158.wav
    Length: 37
** Fast footsteps down stone stairs, 1 woman departing.                                                                                ::
    ID: 07004157.wav
    Length: 11
** Fast footsteps down stone stairs, 1 woman. (With approach and stop)                                                                                ::
    ID: 07004156.wav
    Length: 11
** Fast footsteps down stone stairs, 1 woman. (With start and stop)                                                                                ::
    ID: 07004155.wav
    Length: 36
** Fast footsteps down stone stairs, 2 men departing.                                                                                ::
    ID: 07004154.wav
    Length: 12
** Fast footsteps down stone stairs, 2 men. (With approach and stop)                                                                                ::
    ID: 07004153.wav
    Length: 12
** Fast footsteps down stone stairs, 2 men. (With start and stop)                                                                                ::
    ID: 07004152.wav
    Length: 41
** Fast footsteps down stone stairs, 1 man departing.                                                                                ::
    ID: 07004151.wav
    Length: 10
** Fast footsteps down stone stairs, 1 man. (With approach and stop)                                                                                ::
    ID: 07004150.wav
    Length: 11
** Fast footsteps down stone stairs, 1 man. (With start and stop)                                                                                ::
    ID: 07004149.wav
    Length: 38
** Medium tempo footsteps down stone stairs, 2 women departing.                                                                                ::
    ID: 07004148.wav
    Length: 11
** Medium tempo footsteps down stone stairs, 2 women. (With approach and stop)                                                                                ::
    ID: 07004147.wav
    Length: 11
** Medium tempo footsteps down stone stairs, 2 women. (With start and stop)                                                                                ::
    ID: 07004146.wav
    Length: 43
** Medium tempo footsteps down stone stairs, 1 woman departing.                                                                                ::
    ID: 07004145.wav
    Length: 13
** Medium tempo footsteps down stone stairs, 1 woman. (With approach and stop)                                                                                ::
    ID: 07004144.wav
    Length: 11
** Medium tempo footsteps down stone stairs, 1 woman. (With start and stop)                                                                                ::
    ID: 07004143.wav
    Length: 51
** Medium tempo footsteps down stone stairs, 2 men departing.                                                                                ::
    ID: 07004142.wav
    Length: 13
** Medium tempo footsteps down stone stairs, 2 men. (With approach and stop)                                                                                ::
    ID: 07004141.wav
    Length: 13
** Medium tempo footsteps down stone stairs, 2 men. (With start and stop)                                                                                ::
    ID: 07004140.wav
    Length: 38
** Medium tempo footsteps down stone stairs, 1 man departing.                                                                                ::
    ID: 07004139.wav
    Length: 15
** Medium tempo footsteps down stone stairs, 1 man. (With approach and stop)                                                                                ::
    ID: 07004138.wav
    Length: 12
** Medium tempo footsteps down stone stairs, 1 man. (With start and stop)                                                                                ::
    ID: 07004137.wav
    Length: 40
** Fast footsteps up stone stairs, 2 women departing, slight echo.                                                                                ::
    ID: 07004136.wav
    Length: 16
** Fast footsteps up stone stairs, 2 women. (With approach and stop, slight echo)                                                                                ::
    ID: 07004135.wav
    Length: 18
** Fast footsteps up stone stairs, 2 women. (With start and stop, slight echo)                                                                                ::
    ID: 07004134.wav
    Length: 27
** Fast footsteps up stone stairs, 1 woman departing. (Slight echo)                                                                                ::
    ID: 07004133.wav
    Length: 17
** Fast footsteps up stone stairs, 1 woman. (With approach and stop, slight echo)                                                                                ::
    ID: 07004132.wav
    Length: 17
** Fast footsteps up stone stairs, 1 woman. (With start and stop, slight echo)                                                                                ::
    ID: 07004131.wav
    Length: 21
** Fast footsteps up stone stairs, 2 men departing. (Slight echo)                                                                                ::
    ID: 07004130.wav
    Length: 15
** Fast footsteps up stone stairs, 2 men. (With approach and stop, slight echo)                                                                                ::
    ID: 07004129.wav
    Length: 16
** Fast footsteps up stone stairs, 2 men. (With start and stop, slight echo)                                                                                ::
    ID: 07004128.wav
    Length: 29
** Fast footsteps up stone stairs, 1 man departing. (Slight echo)                                                                                ::
    ID: 07004127.wav
    Length: 14
** Fast footsteps up stone stairs, 1 man. (With approach and stop, slight echo)                                                                                ::
    ID: 07004126.wav
    Length: 15
** Fast footsteps up stone stairs, 1 man. (With start and stop, slight echo)                                                                                ::
    ID: 07004125.wav
    Length: 30
** Footsteps up stone stairs, 2 women departing, slight echo.                                                                                ::
    ID: 07004124.wav
    Length: 18
** Footsteps up stone stairs, 2 women. (With approach and stop, slight echo)                                                                                ::
    ID: 07004123.wav
    Length: 18
** Footsteps up stone stairs, 2 women. (With start and stop, slight echo)                                                                                ::
    ID: 07004122.wav
    Length: 33
** Footsteps up stone stairs, 1 woman departing. (Slight echo)                                                                                ::
    ID: 07004121.wav
    Length: 14
** Footsteps up stone stairs, 1 woman. (With approach and stop, slight echo)                                                                                ::
    ID: 07004120.wav
    Length: 17
** Footsteps up stone stairs, 1 woman. (With start and stop, slight echo)                                                                                ::
    ID: 07004119.wav
    Length: 38
** Footsteps up stone stairs, 2 men departing, slight echo.                                                                                ::
    ID: 07004118.wav
    Length: 16
** Footsteps up stone stairs, 2 men. (With approach and stop, slight echo)                                                                                ::
    ID: 07004117.wav
    Length: 13
** Footsteps up stone stairs, 2 men. (With start and stop, slight echo)                                                                                ::
    ID: 07004116.wav
    Length: 30
** Footsteps up stone stairs, 1 man departing. (slight echo)                                                                                ::
    ID: 07004115.wav
    Length: 13
** Footsteps up stone stairs, 1 man. (With approach and stop, slight echo)                                                                                ::
    ID: 07004114.wav
    Length: 14
** Footsteps up stone stairs, 1 man. (With start and stop, slight echo)                                                                                ::
    ID: 07004113.wav
    Length: 28
** Running, 1 woman on stone, departing.                                                                                ::
    ID: 07004112.wav
    Length: 17
** Running, 1 woman on stone. (With approach and stop)                                                                                ::
    ID: 07004111.wav
    Length: 13
** Running, 1 woman on stone. (With start and stop)                                                                                ::
    ID: 07004110.wav
    Length: 64
** Running, 3 men on stone departing.                                                                                ::
    ID: 07004109.wav
    Length: 17
** Running, 3 men on stone. (With approach and stop)                                                                                ::
    ID: 07004108.wav
    Length: 16
** Running, 3 men on stone. (With start and stop)                                                                                ::
    ID: 07004107.wav
    Length: 66
** Running, 2 men on stone, departing.                                                                                ::
    ID: 07004106.wav
    Length: 16
** Running, 2 men on stone. (With approach and stop)                                                                                ::
    ID: 07004105.wav
    Length: 14
** Running, 2 men on stone. (With start and stop)                                                                                ::
    ID: 07004104.wav
    Length: 65
** Running, 1 man on stone, departing.                                                                                ::
    ID: 07004103.wav
    Length: 18
** Running, 1 man on stone. (With approach and stop)                                                                                ::
    ID: 07004102.wav
    Length: 14
** Running, 1 man on stone. (With start and stop)                                                                                ::
    ID: 07004101.wav
    Length: 64
** Walking, 2 men and women on stone departing. (Slight echo)                                                                                ::
    ID: 07004100.wav
    Length: 17
** Walking, 2 men and women on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004099.wav
    Length: 17
** Walking, 2 men and women on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004098.wav
    Length: 66
** Walking, 2 men and 1 woman on stone departing. (Slight echo)                                                                                ::
    ID: 07004097.wav
    Length: 18
** Walking, 2 men and 1 woman on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004096.wav
    Length: 16
** Walking, 2 men and 1 woman on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004095.wav
    Length: 66
** Walking, 1 man and woman on stone departing. (Slight echo)                                                                                ::
    ID: 07004094.wav
    Length: 18
** Walking, 1 man and woman on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004093.wav
    Length: 17
** Walking, 1 man and woman on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004092.wav
    Length: 65
** Walking, 2 women on stone, departing. (Slight echo)                                                                                ::
    ID: 07004091.wav
    Length: 16
** Walking, 2 women on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004090.wav
    Length: 16
** Walking, 2 women on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004089.wav
    Length: 68
** Walking, 1 woman on stone departing. (Slight echo)                                                                                ::
    ID: 07004088.wav
    Length: 16
** Walking, 1 woman on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004087.wav
    Length: 16
** Walking, 1 woman on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004086.wav
    Length: 68
** Walking, 3 men on stone departing, slight echo.                                                                                ::
    ID: 07004085.wav
    Length: 19
** Walking, 3 men on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004084.wav
    Length: 18
** Walking, 3 men on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004083.wav
    Length: 67
** Walking, 2 men on stone departing. (Slight echo)                                                                                ::
    ID: 07004082.wav
    Length: 19
** Walking, 2 men on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004081.wav
    Length: 17
** Walking, 2 men on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004080.wav
    Length: 66
** Walking, 1 man on stone departing. (Slight echo)                                                                                ::
    ID: 07004079.wav
    Length: 16
** Walking, 1 man on stone. (With approach and stop, slight echo)                                                                                ::
    ID: 07004078.wav
    Length: 16
** Walking, 1 man on stone. (With start and stop, slight echo)                                                                                ::
    ID: 07004077.wav
    Length: 65
** Walking, 1 man on loose shingle. (With start and stop)                                                                                ::
    ID: 07004076.wav
    Length: 91
** Footsteps on stones and shingle, one man and woman. (With start and stop)                                                                                ::
    ID: 07004075.wav
    Length: 74
** Running, 1 man passing on stones and shingle.                                                                                ::
    ID: 07004074.wav
    Length: 12
** Footsteps on stones and shingle, 1 man. (With start, run and stop)                                                                                ::
    ID: 07004073.wav
    Length: 40
** Footsteps on stones and shingle, 1 man departing.                                                                                ::
    ID: 07004072.wav
    Length: 16
** Footsteps on stones and shingle, 1 man. (With start and stop)                                                                                ::
    ID: 07004071.wav
    Length: 137
** Footsteps on shingle, 2 men departing.                                                                                ::
    ID: 07004070.wav
    Length: 31
** Footsteps on shingle, 2 men. (With approach and stop)                                                                                ::
    ID: 07004069.wav
    Length: 35
** Footsteps on shingle, 2 men. (With start and stop)                                                                                ::
    ID: 07004068.wav
    Length: 130
** Footsteps on shingle, 1 man departing.                                                                                ::
    ID: 07004067.wav
    Length: 29
** Footsteps on shingle, 1 man. (With approach and stop)                                                                                ::
    ID: 07004066.wav
    Length: 30
** Footsteps on shingle, 1 man. (With start and stop)                                                                                ::
    ID: 07004065.wav
    Length: 125
** Footsteps in snow, 4 men departing.                                                                                ::
    ID: 07004064.wav
    Length: 29
** Footsteps in snow, 4 men. (With approach and stop)                                                                                ::
    ID: 07004063.wav
    Length: 36
** Footsteps in snow, 4 men. (With start and stop)                                                                                ::
    ID: 07004062.wav
    Length: 126
** Footsteps in snow, 3 men departing.                                                                                ::
    ID: 07004061.wav
    Length: 31
** Footsteps in snow, 3 men. (With approach and stop)                                                                                ::
    ID: 07004060.wav
    Length: 33
** Footsteps in snow, 3 men. (With start and stop)                                                                                ::
    ID: 07004059.wav
    Length: 96
** Footsteps in snow, 2 men departing.                                                                                ::
    ID: 07004058.wav
    Length: 28
** Footsteps in snow, 2 men. (With approach and stop)                                                                                ::
    ID: 07004057.wav
    Length: 34
** Footsteps in snow, 2 men. (With start and stop)                                                                                ::
    ID: 07004056.wav
    Length: 123
** Footsteps in snow, 1 man departing.                                                                                ::
    ID: 07004055.wav
    Length: 31
** Footsteps in snow, 1 man. (With approach and stop)                                                                                ::
    ID: 07004054.wav
    Length: 33
** Footsteps in snow, 1 man. (With start and stop)                                                                                ::
    ID: 07004053.wav
    Length: 93
** Running, 2 men departing.                                                                                ::
    ID: 07004052.wav
    Length: 27
** Running, 2 men. (With approach and stop)                                                                                ::
    ID: 07004051.wav
    Length: 28
** Running, 2 men. (With start and stop)                                                                                ::
    ID: 07004050.wav
    Length: 65
** Running, 1 man departing.                                                                                ::
    ID: 07004049.wav
    Length: 24
** Running, 1 man. (With approach and stop)                                                                                ::
    ID: 07004048.wav
    Length: 24
** Running, 1 man. (With start and stop)                                                                                ::
    ID: 07004047.wav
    Length: 64
** Walking, 2 men departing.                                                                                ::
    ID: 07004046.wav
    Length: 27
** Walking, 2 men. (With approach and stop)                                                                                ::
    ID: 07004045.wav
    Length: 30
** Walking, 2 men. (With start and stop)                                                                                ::
    ID: 07004044.wav
    Length: 71
** Walking, 1 man departing.                                                                                ::
    ID: 07004043.wav
    Length: 28
** Walking, 1 man. (With approach and stop)                                                                                ::
    ID: 07004042.wav
    Length: 24
** Walking, 1 man. (With start and stop)                                                                                ::
    ID: 07004041.wav
    Length: 68
** Interior complete sequence - Part 4 (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                :Trains:Diesel Electric:
    ID: 07004040.wav
    Length: 287
** Interior complete sequence - Part 3 (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                :Trains:Diesel Electric:
    ID: 07004039.wav
    Length: 300
** Interior complete sequence - Part 2 (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                :Trains:Diesel Electric:
    ID: 07004038.wav
    Length: 300
** Interior complete sequence - Part 1 (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                :Trains:Diesel Electric:
    ID: 07004037.wav
    Length: 301
** Rail terminus, no steam trains, general atmosphere.                                                                                ::
    ID: 07004036.wav
    Length: 853
** Interior, fast constant run on welded track. (Recorded in restaurant car)                                                                                ::
    ID: 07004035.wav
    Length: 850
** Interior, fast constant run on welded track. (Recorded in passenger compartment)                                                                                ::
    ID: 07004034.wav
    Length: 913
** Interior, fast constant run on welded track. (Recorded in corridor)                                                                                ::
    ID: 07004033.wav
    Length: 901
** Exterior, sounds siren and passes at medium speed, sounding siren again. (English Electric Vulcan Locomotive. 2000                                                                                 ::
    ID: 07004032.wav
    Length: 48
** Exterior, leaves station passing microphone. (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                ::
    ID: 07004031.wav
    Length: 88
** Exterior, arrives in station and stops, tickover.(English Electri c Vulcan Locomotive, 2000 b.h.p.)                                                                                ::
    ID: 07004030.wav
    Length: 67
** Exterior, tickover in quiet station. (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                ::
    ID: 07004029.wav
    Length: 183
** Interior, slow down and stop at station, passengers alight. (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                ::
    ID: 07004028.wav
    Length: 91
** Exterior, sounds siren and passes at speed. (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                ::
    ID: 07004027.wav
    Length: 35
** Exterior, tickover, sounds siren, leaves station passing microphone. (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                ::
    ID: 07004026.wav
    Length: 96
** Exterior, arrives at station, tickover, unintelligible public address announcement, doors. (English Electric Vulcan                                                                                 ::
    ID: 07004025.wav
    Length: 111
** Fast constant run (English Electric Vulcan Locomotive, 2000 b.h.p.)                                                                                ::
    ID: 07004024.wav
    Length: 303
** Interior, tickover, depart from station gathering speed over mostly welded track. (English Electric Vulcan Locomotive,                                                                                 ::
    ID: 07004023.wav
    Length: 302
** Interior, tickover, depart from station gathering speed over jointed and welded track. (English Electric Vulcan                                                                                 ::
    ID: 07004022.wav
    Length: 303
** Exterior, approach and pass. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004021.wav
    Length: 27
** Exterior, approach and pass. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004020.wav
    Length: 28
** Exterior, approach and stop, tickover, switch off. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004019.wav
    Length: 35
** Exterior, approach and stop, tickover, switch off. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004018.wav
    Length: 38
** Exterior, self starter, fast depart. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004017.wav
    Length: 35
** Exterior, self starter, depart. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004016.wav
    Length: 45
** Exterior, 1 door closing. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004015.wav
    Length: 6
** Exterior, 1 door opening. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004014.wav
    Length: 6
** Exterior, self starter, revving, switch off. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004013.wav
    Length: 75
** Exterior, self starter, tickover, switch off. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004012.wav
    Length: 211
** Interior, self starter, high speed constant run, slow down, stop. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004011.wav
    Length: 182
** Interior, self starter, run in low gear, stop. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004010.wav
    Length: 204
** Interior, constant run, slow down, stop. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004009.wav
    Length: 16
** Interior, self starter, into constant run partly through traffic. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004008.wav
    Length: 339
** Interior, constant, run, slow down, stop, tickover with revving, switch off. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004007.wav
    Length: 38
** Interior, self starter, move off into constant run. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004006.wav
    Length: 296
** Interior, 1 door opening and closing. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004005.wav
    Length: 8
** Interior, 1 door closing. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004004.wav
    Length: 6
** Interior, 1 door opening. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004003.wav
    Length: 6
** Interior, self starter, tickover. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004002.wav
    Length: 184
** Interior, self starter, revving, switch off. (1966 848cc BMC Mini car)                                                                                ::
    ID: 07004001.wav
    Length: 49
** Playhouse Theatre: English & French audience chatter                                                                                :Playhouse Theatre:
    ID: 07003112.wav
    Length: 392
** Playhouse Theatre: Applause.                                                                                :Playhouse Theatre:Applause:
    ID: 07003111.wav
    Length: 9
** Playhouse Theatre: Applause.                                                                                :Playhouse Theatre:Applause:
    ID: 07003110.wav
    Length: 10
** Playhouse Theatre: Laughter and applause.                                                                                :Playhouse Theatre:Laughter and applause:
    ID: 07003109.wav
    Length: 13
** Playhouse Theatre: Laughter.                                                                                :Playhouse Theatre:Laughter:
    ID: 07003108.wav
    Length: 8
** Playhouse Theatre: Laughter and applause.                                                                                :Playhouse Theatre:Laughter and applause:
    ID: 07003107.wav
    Length: 10
** Playhouse Theatre: Applause.                                                                                :Playhouse Theatre:Applause:
    ID: 07003106.wav
    Length: 10
** Large hall with jumble sale.                                                                                ::
    ID: 07003105.wav
    Length: 383
** Large exhibition hall with occasional indistinct music and P.A.                                                                                ::
    ID: 07003104.wav
    Length: 371
** Crowds in large entrance hall, with turnstiles at close perspective.                                                                                ::
    ID: 07003103.wav
    Length: 412
** Crowds in large entrance hall with turnstiles.                                                                                ::
    ID: 07003102.wav
    Length: 446
** Political Party Conference: Applause                                                                                :Political Party Conference:
    ID: 07003101.wav
    Length: 19
** Political Party Conference: Applause                                                                                :Political Party Conference:
    ID: 07003100.wav
    Length: 17
** Political Party Conference: Applause                                                                                :Political Party Conference:
    ID: 07003099.wav
    Length: 13
** Political Party Conference: Applause                                                                                :Political Party Conference:
    ID: 07003098.wav
    Length: 12
** Political Party Conference: Applause                                                                                :Political Party Conference:
    ID: 07003097.wav
    Length: 10
** Political Party Conference: Applause                                                                                :Political Party Conference:
    ID: 07003096.wav
    Length: 16
** Mixed crowd in hotel foyer.                                                                                ::
    ID: 07003095.wav
    Length: 393
** Subdued crowd in abbey.                                                                                ::
    ID: 07003094.wav
    Length: 394
** Crowd in hamburger fast food store.                                                                                ::
    ID: 07003093.wav
    Length: 394
** Woolworths: Crowds and manual cash registers,                                                                                 :Shops:Woolworths:
    ID: 07003092.wav
    Length: 395
** Shops: Check out, cash registers and sounds of wrapping.                                                                                :Shops:Check out, cash registers and sounds of wrapping:
    ID: 07003091.wav
    Length: 64
** Shops: General atmosphere, occasional trolley and bell.                                                                                :Shops:General atmosphere, occasional trolley and bell:
    ID: 07003090.wav
    Length: 274
** Clubs & Bars: Busy mixed chatter at mealtime. (Mid-distance perspective)                                                                                :Clubs & Bars:Busy mixed chatter at mealtime:
    ID: 07003089.wav
    Length: 394
** Clubs & Bars: Busy mixed chatter. (Close perspective)                                                                                :Clubs & Bars:Busy mixed chatter:
    ID: 07003088.wav
    Length: 393
** Atmosphere in working men's club with children, fruit machines and dominoes being played in background.                                                                                ::
    ID: 07003087.wav
    Length: 393
** Crowd arrives for meeting in hall.                                                                                ::
    ID: 07003086.wav
    Length: 392
** Atmosphere in a reception hall with footsteps, occasional indistinct voices and very distant traffic. (Technical note: for use at low level)                                                                                :Atmospheres:Reception Hall:
    ID: 07003085.wav
    Length: 393
** Atmosphere in crowded tea marquee. (Technical note, for use at low level)                                                                                ::
    ID: 07003084.wav
    Length: 394
** Quiet hotel foyer atmosphere, traffic and indistinct speech.                                                                                ::
    ID: 07003083.wav
    Length: 393
** Busy hotel foyer atmosphere.                                                                                ::
    ID: 07003082.wav
    Length: 392
** Main exhibition hall atmosphere at Science Museum, London. (Technical note, for use at low level)                                                                                ::
    ID: 07003081.wav
    Length: 397
** Atmosphere in a quiet urban post office with footsteps, voices and distant traffic. (Technical note, for use at low level)                                                                                ::
    ID: 07003080.wav
    Length: 365
** Activity with clowns, act in progress with indistinguishable music, drum rolls and children shouting.                                                                                ::
    ID: 07003079.wav
    Length: 75
** Expectant drum roll, with speech and atmosphere, cymbal crash, applause. (Indistinguishable music in background)                                                                                ::
    ID: 07003078.wav
    Length: 45
** Cymbal crash, applause. (Indistinguishable music in background)                                                                                ::
    ID: 07003077.wav
    Length: 11
** Children and clowns shout 'hello'. (Indistinguishable music in background)                                                                                ::
    ID: 07003076.wav
    Length: 11
** Performing dogs with whistles, barks and whip cracks. (Indistinguishable music in background)                                                                                ::
    ID: 07003075.wav
    Length: 72
** Atmosphere, drum roll and applause. (Indistinguishable music in background)                                                                                ::
    ID: 07003074.wav
    Length: 31
** Big top crowd atmosphere, mainly indistinct speech with generator in background.                                                                                ::
    ID: 07003073.wav
    Length: 393
** Atmosphere at a jumble sale.                                                                                ::
    ID: 07003072.wav
    Length: 382
** Sports club bar, atmosphere and mixed chatter.                                                                                ::
    ID: 07003071.wav
    Length: 384
** Crowd atmosphere in an exhibition hall.                                                                                ::
    ID: 07003070.wav
    Length: 372
** Crowd atmosphere in a busy museum.                                                                                ::
    ID: 07003069.wav
    Length: 381
** Atmosphere in reptile house at London Zoo. Children                                                                                ::
    ID: 07003068.wav
    Length: 365
** Atmosphere in a large cafeteria at London Zoo. Mixed crowd & children                                                                                ::
    ID: 07003067.wav
    Length: 368
** Playhouse Theatre: Audience chatter (French & English)                                                                                :Playhouse Theatre:Audience chatter:
    ID: 07003066.wav
    Length: 312
** Playhouse Theatre: Applause                                                                                :Playhouse Theatre:
    ID: 07003065.wav
    Length: 10
** Playhouse Theatre: Applause                                                                                :Playhouse Theatre:
    ID: 07003064.wav
    Length: 11
** Playhouse Theatre: Laughter & applause                                                                                :Playhouse Theatre:
    ID: 07003063.wav
    Length: 13
** Playhouse Theatre: Laughter                                                                                :Playhouse Theatre:
    ID: 07003062.wav
    Length: 9
** Playhouse Theatre: Laughter & applause                                                                                :Playhouse Theatre:
    ID: 07003061.wav
    Length: 10
** Playhouse Theatre: Applause                                                                                :Playhouse Theatre:
    ID: 07003060.wav
    Length: 12
** Audience murmur (Recorded in Broadcasting House Concert Hall, London)                                                                                ::
    ID: 07003059.wav
    Length: 386
** Sound of audience leaving auditorium. (Recorded in Broadcasting House Concert Hall, London)                                                                                ::
    ID: 07003058.wav
    Length: 197
** Laughter & applause. (Recorded in Broadcasting House Concert Hall, London)                                                                                ::
    ID: 07003057.wav
    Length: 28
** Laughter. (Recorded in Broadcasting House Concert Hall, London)                                                                                ::
    ID: 07003056.wav
    Length: 6
** Little laughter. (Recorded in Broadcasting House Concert Hall, London)                                                                                ::
    ID: 07003055.wav
    Length: 6
** Laughter and applause. (Recorded in Broadcasting House Concert Hall, London)                                                                                ::
    ID: 07003054.wav
    Length: 25
** Laughter and applause. (Recorded in Broadcasting House Concert Hall, London)                                                                                ::
    ID: 07003053.wav
    Length: 12
** Atmosphere in a large indoor shopping arcade.                                                                                ::
    ID: 07003052.wav
    Length: 400
** Atmosphere in main hall of a flower auction.                                                                                ::
    ID: 07003051.wav
    Length: 390
** Old Vic: Final applause, audience leave theatre.                                                                                :Theatres:Old Vic:
    ID: 07003050.wav
    Length: 282
** Old Vic: Audience laughter in a theatre.                                                                                :Theatres:Old Vic:
    ID: 07003049.wav
    Length: 6
** Old Vic: Audience laughter in a theatre.                                                                                :Theatres:Old Vic:
    ID: 07003048.wav
    Length: 6
** Old Vic: Audience laughter in a theatre.                                                                                :Theatres:Old Vic:
    ID: 07003047.wav
    Length: 6
** Old Vic: Audience laughter in a theatre.                                                                                :Theatres:Old Vic:
    ID: 07003046.wav
    Length: 6
