** Steam Engine whistle (London, Midland & Scottish Railway).                                                                                ::
    ID: 07045047.wav
    Length: 2
** Steam Engine whistle (Great Western Railways).                                                                                ::
    ID: 07045046.wav
    Length: 1
** Steam Engine whistle (Great Western Railways).                                                                                ::
    ID: 07045045.wav
    Length: 4
** Railway Points change.                                                                                ::
    ID: 07045044.wav
    Length: 4
** Railway Signalling Equipment, signal falls.                                                                                ::
    ID: 07045043.wav
    Length: 1
** Railway Signalling Equipment, bell for train entering sector, acknowledgement, token prepared, signal levers thrown.                                                                                ::
    ID: 07045042.wav
    Length: 32
** Railway Signalling Equipment, advance warning of train & return acknowledgement.                                                                                ::
    ID: 07045041.wav
    Length: 19
** Steam Crane, starts into constant run, stops (whistle blown frequently).                                                                                ::
    ID: 07045040.wav
    Length: 205
** Steam Crane shunts coal trucks with squealing rails.                                                                                ::
    ID: 07045039.wav
    Length: 34
** Steam Crane, passes right to left & coupled to coal trucks.                                                                                ::
    ID: 07045038.wav
    Length: 78
** Static Steam Engine, run venting single cylinder to clear water.                                                                                ::
    ID: 07045037.wav
    Length: 70
** Steam Water Pump, topping-up cold water tank.                                                                                ::
    ID: 07045036.wav
    Length: 56
** Traction Engine sawing logs to make planks.                                                                                ::
    ID: 07045035.wav
    Length: 124
** Traction Engine driving farm machinery with belt.                                                                                ::
    ID: 07045034.wav
    Length: 72
** Traction Engine blows hooter.                                                                                ::
    ID: 07045033.wav
    Length: 9
** Traction Engines blowing hooters.                                                                                ::
    ID: 07045032.wav
    Length: 37
** Traction Engines manoeuvring.                                                                                ::
    ID: 07045031.wav
    Length: 107
** Long tailed tit, group feeding calls, with blackbird, blackcap, chaffinch and cuckoo in distance.                                                                                ::
    ID: 07045030.wav
    Length: 152
** Great tit, teacher song.                                                                                ::
    ID: 07045029.wav
    Length: 73
** Blue tit, awareness calls, with blackbird, willow warbler, chaffinch, song thrush and robin in distance.                                                                                ::
    ID: 07045028.wav
    Length: 116
** Song thrush, with goldfinch, woodpigeon, pheasant, chaffinch and green woodpecker in distance.                                                                                ::
    ID: 07045027.wav
    Length: 119
** Mistle thrush, with song thrush and skylark in distance.                                                                                ::
    ID: 07045026.wav
    Length: 177
** Whooper swan, trumpeting calls from several while feeding on water, occasional calls from mute swans and barnacle                                                                                 ::
    ID: 07045025.wav
    Length: 126
** Mute swan, calls wings whistling in flight, landing on water, whooper swans and wigeon in background.                                                                                ::
    ID: 07045024.wav
    Length: 135
** Swallow, song, with farmyard background.                                                                                ::
    ID: 07045023.wav
    Length: 89
** Sparrowhawk, alarm calls from a pair, female more prominent, chaffinch in background.                                                                                ::
    ID: 07045022.wav
    Length: 111
** Morning Chorus of house sparrow.                                                                                ::
    ID: 07045021.wav
    Length: 259
** House sparrows, two adults singing and chirruping.                                                                                ::
    ID: 07045020.wav
    Length: 140
** House sparrow, several birds calling with feral pigeon.                                                                                ::
    ID: 07045019.wav
    Length: 162
** Rook, adult calling.                                                                                ::
    ID: 07045018.wav
    Length: 72
** Robin, spring, summer song, with willow warbler, chiffchaff, another robin, cuckoo, nuthatch and woodpigeon.                                                                                ::
    ID: 07045017.wav
    Length: 303
** Nuthatch, calls, with chiffchaff, blackbird, wren, blue tit and chaffinch in distance.                                                                                ::
    ID: 07045016.wav
    Length: 95
** Nightingale, night calls.                                                                                ::
    ID: 07045015.wav
    Length: 312
** Jackdaw, adults and fledgelings in quarry, begging and feeding calls from chicks.                                                                                ::
    ID: 07045014.wav
    Length: 274
** Greenfinch, with mistle thrush, collared dove, house sparrows, and skhlark in background.                                                                                ::
    ID: 07045013.wav
    Length: 98
** Goldcrest, with blackbird, woodpigeon, wren and blue tit in background.                                                                                ::
    ID: 07045012.wav
    Length: 76
** Falcon, peregrine, close annoyance and chirrup calls.                                                                                ::
    ID: 07045011.wav
    Length: 76
** Falcon, peregrine, male and female flight alarm calls.                                                                                ::
    ID: 07045010.wav
    Length: 176
** Dunnock, with skylark and mistle thrush, gusty wind in background.                                                                                ::
    ID: 07045009.wav
    Length: 68
** Ducks, wigeon, flock of 1000 grazing at pool.                                                                                ::
    ID: 07045008.wav
    Length: 168
** Ducks, wigeon, large flock at pool.                                                                                ::
    ID: 07045007.wav
    Length: 191
** Ducks, mallard, close female, males and females in distance.                                                                                ::
    ID: 07045006.wav
    Length: 78
** Ducks, mallard, males and females.                                                                                ::
    ID: 07045005.wav
    Length: 153
** Rock Dove, coos and calls from several in old barn, wing flaps, chaffinch, jackdaws, wren and other birds in distance.                                                                                ::
    ID: 07045004.wav
    Length: 135
** Chiffchaff, with wren, other chiffchaffs and song thrush in distance.                                                                                ::
    ID: 07045003.wav
    Length: 146
** Buzzard, two adults calling, song thrush, woodpigeon, wren and jackdaw in background.                                                                                ::
    ID: 07045002.wav
    Length: 92
** Blackbird, with dawn woodland atmosphere of song thrush, woodpigeon and jackdaw in background.                                                                                ::
    ID: 07045001.wav
    Length: 187
** Lake in late Spring, night atmosphere with Oystercatcher & Artic Terns. (Some wind.)                                                                                ::
    ID: 07044132.wav
    Length: 241
** Low lying marshy pasture in Winter, early morning atmosphere with lapping water & distant Curlews. (Some wind.)                                                                                ::
    ID: 07044131.wav
    Length: 308
** Lake in early Spring,early morning atmosphere with Mallard, Coot, Canada Goose & incipient dawn chorus, with Mallards rising at 1m38s & 4m08s.                                                                                ::
    ID: 07044130.wav
    Length: 259
** Heather moorland in late Spring, evening atmosphere with Snipe & Oystercatchers. (Some wind.)                                                                                ::
    ID: 07044129.wav
    Length: 362
** Heather moorland in late Spring, early morning atmosphere with Golden Plover, Skylark, Curlew & distant sheep. (Some wind.)                                                                                ::
    ID: 07044128.wav
    Length: 312
** Coniferous woodland in late Spring, midday atmosphere with Black Kite, Tree Sparrows, Corn Bunting, Chaffinch, field crickets, bees, flies & distant Hoopoe.                                                                                ::
    ID: 07044127.wav
    Length: 308
** Mixed woodland in early Spring, early morning atmosphere, rather neutral with distant Hooded Crows, Buzzard & Great Tit.                                                                                ::
    ID: 07044126.wav
    Length: 260
** Broad-leaved woodland in late Spring, early morning atmosphere with Nightingale, flies, Cuckoo, Whitethroat, Bonelli's Warbler & field crickets. (Mediterranean region only.)                                                                                ::
    ID: 07044125.wav
    Length: 238
** Broad-leaved woodland in late Spring, early morning dawn chorus with Cuckoos, Garden Warbler & Nightingale.                                                                                ::
    ID: 07044124.wav
    Length: 405
** Farmstead in Summer, evening atmosphere with Barn Owls, distant Tawny Owls & distant dog.                                                                                ::
    ID: 07044123.wav
    Length: 250
** Cultivated land (semi-arid) in late Spring, midday atmosphere with Woodlark, Booted Eagle, Corn Bunting, Hoopoe, Azure-Winged Magpie, Spotless Starling, grasshoppers & flies, with very distant traffic.                                                                                ::
    ID: 07044122.wav
    Length: 262
** Cultivated land (warm temperate) in late Spring, midday atmosphere with Bee-Eaters, Spotless Starlings, Turtle Dove, Blue Tit, Azure-Winged Magpie, Crested Lark & cattle.                                                                                ::
    ID: 07044121.wav
    Length: 254
** Farmstead in Summer, early morning atmosphere with Blackbird, Wren, Robin, Rooks, Woodpigeon, feral Pigeon, Chaffinch, House Sparrow, distant Peacock & sheep.                                                                                ::
    ID: 07044120.wav
    Length: 248
** Village in late Spring, early morning atmosphere with Blackbird, Wren, Rooks, Chaffinch, Woodpigeon & distant dog.                                                                                ::
    ID: 07044119.wav
    Length: 205
** Farmstead in late Spring, early morning atmosphere with Wren, Robin, Pheasant, Cuckoo, Chaffinch, House Sparrows, Goldfinch, Peacock, feral Pigeon & Peacock, with distant sheep & cattle.                                                                                ::
    ID: 07044118.wav
    Length: 502
** Small waterfall.                                                                                ::
    ID: 07044117.wav
    Length: 121
** Fish Farm, breeding room.                                                                                ::
    ID: 07044116.wav
    Length: 137
** Hail falling on umbrella.                                                                                ::
    ID: 07044115.wav
    Length: 241
** Hose pipe, with start & stop.                                                                                ::
    ID: 07044114.wav
    Length: 58
** Water flowing down drain, with start & stop.                                                                                ::
    ID: 07044113.wav
    Length: 94
** Car Wash. (Recorded inside car).                                                                                ::
    ID: 07044112.wav
    Length: 107
** Person thrashing in water.                                                                                ::
    ID: 07044111.wav
    Length: 57
** Small splash.                                                                                ::
    ID: 07044110.wav
    Length: 7
** Large splash.                                                                                ::
    ID: 07044109.wav
    Length: 7
** Cave, interior. (Recorded at Witches Kitchen, Wookey Hole.)                                                                                ::
    ID: 07044108.wav
    Length: 126
** Sea from cliff top.                                                                                ::
    ID: 07044107.wav
    Length: 306
** Seawash, rising tide on rocks.                                                                                ::
    ID: 07044106.wav
    Length: 364
** Lock gates on River Thames.                                                                                ::
    ID: 07044105.wav
    Length: 14
** River lock filling on River Thames.                                                                                ::
    ID: 07044104.wav
    Length: 103
** Stream flowing down drain.                                                                                ::
    ID: 07044103.wav
    Length: 242
** Weir on River Thames.                                                                                ::
    ID: 07044102.wav
    Length: 302
** Waterfall.                                                                                ::
    ID: 07044101.wav
    Length: 302
** Small stream.                                                                                ::
    ID: 07044100.wav
    Length: 301
** River rapids.                                                                                ::
    ID: 07044099.wav
    Length: 305
** Brook flowing.                                                                                ::
    ID: 07044098.wav
    Length: 305
** Ring-Tailed Lemur, with insects in background.                                                                                ::
    ID: 07044097.wav
    Length: 34
** Willow Warbler singing.                                                                                ::
    ID: 07044096.wav
    Length: 67
** Iberian Marsh Frog, adult male croaking with Woodlark and Great Grey Shrikes.                                                                                ::
    ID: 07044095.wav
    Length: 54
** Red-Throated Diver, wailing with Curlew and Great Skua.                                                                                ::
    ID: 07044094.wav
    Length: 75
** Tropical Dawn Chorus. (Recorded in Sri Lanka.)                                                                                ::
    ID: 07044093.wav
    Length: 190
** Tennis Game, with services, points won & crowd reaction. (See CD SFX catalogue for details.)                                                                                ::
    ID: 07044092.wav
    Length: 100
** Hawker Harrier Jump Jet, taking off vertically.                                                                                ::
    ID: 07044091.wav
    Length: 41
** Cafe Royal, Edinburgh. very busy Saturday night atmosphere.                                                                                ::
    ID: 07044090.wav
    Length: 82
** Television sets crushed at refuse depot plant. (Pre-1976 TV sets.)                                                                                ::
    ID: 07044089.wav
    Length: 97
** Electric power station being demolished.                                                                                ::
    ID: 07044088.wav
    Length: 11
** Factory chimney demolition.                                                                                ::
    ID: 07044087.wav
    Length: 12
** Brick wall demolition.                                                                                ::
    ID: 07044086.wav
    Length: 43
** Wooden door smashed.                                                                                ::
    ID: 07044085.wav
    Length: 23
** Very small window smashed.                                                                                ::
    ID: 07044084.wav
    Length: 4
** Teapot smashed.                                                                                ::
    ID: 07044083.wav
    Length: 4
** Mug smashed.                                                                                ::
    ID: 07044082.wav
    Length: 4
** Plate smashed.                                                                                ::
    ID: 07044081.wav
    Length: 4
** Dentist's Surgery, mouthwash.                                                                                ::
    ID: 07044080.wav
    Length: 10
** Dentist's Surgery, dental suction tube.                                                                                ::
    ID: 07044079.wav
    Length: 15
** Dentist's Surgery, working on a filling.                                                                                ::
    ID: 07044078.wav
    Length: 19
** Dentist's Surgery, low speed drilling.                                                                                ::
    ID: 07044077.wav
    Length: 16
** Dentist's Surgery, high speed drilling.                                                                                ::
    ID: 07044076.wav
    Length: 19
** Dentist's Surgery, polishing teeth.                                                                                ::
    ID: 07044075.wav
    Length: 14
** Television screen smashed by cricket ball.                                                                                ::
    ID: 07044074.wav
    Length: 4
** Karate class, gradually approaching with shouts and rustling.                                                                                ::
    ID: 07044073.wav
    Length: 65
** Karate shout or kai. (Recorded at 10 metres in large hall.)                                                                                ::
    ID: 07044072.wav
    Length: 5
** Market place, walking through.                                                                                ::
    ID: 07044071.wav
    Length: 78
** Happy Baby. (12 week old baby boy weighing 6. 1kg.)                                                                                ::
    ID: 07044070.wav
    Length: 30
** Sneezing Baby, sneezes at 2s, 3s & 6s. Baby. (12 week old baby boy weighing 6. 1kg.)                                                                                ::
    ID: 07044069.wav
    Length: 10
** Crying Baby. (12 week old baby boy weighing 6. 1kg.)                                                                                ::
    ID: 07044068.wav
    Length: 28
** Bicycle, 1936 Raleigh sports model, crashing into fence.                                                                                ::
    ID: 07044067.wav
    Length: 8
** Bicycle, 1936 Raleigh sports model, approach & skid.                                                                                ::
    ID: 07044066.wav
    Length: 10
** Bicycle, 1936 Raleigh sports model, passing with bell from right to left.                                                                                ::
    ID: 07044065.wav
    Length: 14
** Bicycle, 1936 Raleigh sports model, passing with bell from left to right.                                                                                ::
    ID: 07044064.wav
    Length: 12
** Bicycle, 1936 Raleigh sports model, passes from right to left.                                                                                ::
    ID: 07044063.wav
    Length: 15
** Bicycle, 1936 Raleigh sports model, passes from left to right.                                                                                ::
    ID: 07044062.wav
    Length: 8
** Bicycle, 1936 Raleigh sports model, continuous run on road with traffic passing. (Recorded on bicycle.)                                                                                ::
    ID: 07044061.wav
    Length: 211
** Bicycle, 1936 Raleigh sports model, fast continuous run on gravel. (Recorded on bicycle.)                                                                                ::
    ID: 07044060.wav
    Length: 108
** Bicycle, 1936 Raleigh sports model, slow continuous run on gravel. (Recorded on bicycle.)                                                                                ::
    ID: 07044059.wav
    Length: 105
** Yamaha RD 350 motor cycle, rider runs up & cycle departs on gravel.                                                                                ::
    ID: 07044058.wav
    Length: 40
** Yamaha RD 350 motor cycle, approach on gravel & rider dismounts.                                                                                ::
    ID: 07044057.wav
    Length: 30
** Automatic car wash, wash phase inside Renault 5.                                                                                ::
    ID: 07044056.wav
    Length: 52
** High street with traffic, footsteps and pedestrian crossing signal.                                                                                ::
    ID: 07044055.wav
    Length: 302
** Busy city skyline.                                                                                ::
    ID: 07044054.wav
    Length: 586
** Wood fire, inside stove.                                                                                ::
    ID: 07044053.wav
    Length: 307
** River, small.                                                                                ::
    ID: 07044052.wav
    Length: 128
** Seawash, choppy.                                                                                ::
    ID: 07044051.wav
    Length: 245
** Seawash, calm.                                                                                ::
    ID: 07044050.wav
    Length: 242
** Public Foyer with voices & footsteps on stone stairs. (Recorded at the National Gallery.)                                                                                ::
    ID: 07044049.wav
    Length: 260
** Teleprinter Room atmosphere, with telex machines, tearing of paper, distant typewriters & telephones. (Recorded at The Times.)                                                                                ::
    ID: 07044048.wav
    Length: 123
** Bank atmosphere, with footsteps, voices, escalators, document-stamping & coins being weighted (at 2m59s).                                                                                ::
    ID: 07044047.wav
    Length: 234
** Underground Station Ticket Hall with footsteps, ticket machines & distant voices. (Ticket machine close on at 1m57s.)                                                                                ::
    ID: 07044046.wav
    Length: 126
** Public Bar atmosphere, quiet crowd in public house with glasses, occasional fruit machine & distant traffic. (Win on fruit machine at 2m46s.)                                                                                ::
    ID: 07044045.wav
    Length: 235
** Self-Service Restaurant atmosphere, with voices, crockery, cutlery, footsteps & dishes being cleared.                                                                                ::
    ID: 07044044.wav
    Length: 255
** Amusement Arcade atmosphere, with electronic games, fruit machines & musical jingles.                                                                                ::
    ID: 07044043.wav
    Length: 247
** Theatre Audience, mixed animated chatter before performance.                                                                                ::
    ID: 07044042.wav
    Length: 244
** Supermarket atmosphere, with check-out bell (at 58s), footsteps, trolleys, voices & baskets being stacked.                                                                                ::
    ID: 07044041.wav
    Length: 251
** Shopping Centre atmosphere with footsteps, voices & distant unidentifiable music. (Recorded at Brent Cross Shopping Centre, London.)                                                                                ::
    ID: 07044040.wav
    Length: 247
** National Newspaper Newsroom atmosphere, with voices, typewriters & telephones. (Recorded at The Times.)                                                                                ::
    ID: 07044039.wav
    Length: 237
** Public Library with voices, footsteps, trolleys & a telephone (at 20s).                                                                                ::
    ID: 07044038.wav
    Length: 212
** Art Gallery atmosphere with footsteps & indistinct voices. (Recorded at the National Gallery.)                                                                                ::
    ID: 07044037.wav
    Length: 241
** Cathedral atmosphere with movement from visitors & distant traffic. (Recorded at St. Paul's Cathedral.)                                                                                ::
    ID: 07044036.wav
    Length: 235
** Airport Terminal Building, with footsteps, voices, suitcase conveyors & P.A. announcements (at 1m33s & 3m01s).                                                                                ::
    ID: 07044035.wav
    Length: 249
** Main Line Railway Station, with footsteps, voices, trolleys, destination indicators & P.A. announcements (at 2m45s).                                                                                 ::
    ID: 07044034.wav
    Length: 251
** Austria: Schwedenplatz underground station platform.                                                                                :Trains:Austria:Schwedenplatz:
    ID: 07044033.wav
    Length: 154
** France: Pedestrian precinct.                                                                                :France:Pedestrian precinct:
    ID: 07044032.wav
    Length: 207
** Italy: Large square, distant perspective.                                                                                :Italy:Large square, distant perspective:
    ID: 07044031.wav
    Length: 208
** Italy: Water-bus arrives at stop, passengers disembark, gate slid shut, bus departs.                                                                                :Italy:Water-bus arrives at stop, passengers disembark, gate sli:
    ID: 07044030.wav
    Length: 100
** Italy: Busy canal with footsteps & speech (recorded at 8am).                                                                                :Italy:Busy canal with footsteps & speech (recorded at 8am):
    ID: 07044029.wav
    Length: 243
** Italy: School corridor with mxed teenage chatter.                                                                                :Italy:School corridor with mxed teenage chatter:
    ID: 07044028.wav
    Length: 171
** Italy: Roadside station, train passes through, small passenger train stops & reverses out with hooter sounding at 1m58s.                                                                                :Italy:Roadside station, train passes through, small passenger t:
    ID: 07044027.wav
    Length: 198
** Switzerland: Small cowbells.                                                                                :Switzerland:Small cowbells:
    ID: 07044026.wav
    Length: 240
** Switzerland: Large cowbells.                                                                                :Switzerland:Large cowbells:
    ID: 07044025.wav
    Length: 240
** Switzerland: Tram journey.                                                                                :Switzerland:Tram journey:
    ID: 07044024.wav
    Length: 195
** Germany: Bus journey.                                                                                :Germany:
    ID: 07044023.wav
    Length: 217
** Germany: Railway journey on S - Bahn overground.                                                                                :Germany:Railway journey on S - Bahn overground:
    ID: 07044022.wav
    Length: 197
** Germany: Pedestrian precinct.                                                                                :Germany:Pedestrian precinct:
    ID: 07044021.wav
    Length: 201
** Germany: Station with trains departing & arriving, train approaches & stops with squeal of brakes at 2m10s, train stops quietly at 3m20s, train stops at 4m12.                                                                                :Germany:Station with trains departing & arriving, train approac:
    ID: 07044020.wav
    Length: 414
** Holland: Busy market with carillon.                                                                                :Holland:Busy market with carillon:
    ID: 07044019.wav
    Length: 224
** Holland: Fast train at level crossing.                                                                                :Holland:Fast train at level crossing:
    ID: 07044018.wav
    Length: 35
** Belgium: Quiet shop atmosphere (interior, no cash register).                                                                                :Belgium:
    ID: 07044017.wav
    Length: 239
** Belgium: Fifty junior school pupils in playground.                                                                                :Belgium:
    ID: 07044016.wav
    Length: 239
** Welsh Hillside with occasional creaking trees, birds & distant sheepdog.                                                                                ::
    ID: 07044015.wav
    Length: 182
** School Playground, with 7-11 year old children playing games.                                                                                ::
    ID: 07044014.wav
    Length: 257
** Blustery Wind on a Beach, with drifting sand. (No seawash.)                                                                                ::
    ID: 07044013.wav
    Length: 254
** Mixed Deciduous Woodland atmosphere on a windy day, with occasional flying insects.                                                                                ::
    ID: 07044012.wav
    Length: 259
** Large Airport, general exterior atmosphere. (Recorded in roof-garden observation area.)                                                                                ::
    ID: 07044011.wav
    Length: 254
** Main Railway Station, with indiscernible P.A. announcement & arriving train.                                                                                ::
    ID: 07044010.wav
    Length: 254
** City Skyline.                                                                                ::
    ID: 07044009.wav
    Length: 360
** City Traffic.                                                                                ::
    ID: 07044008.wav
    Length: 240
** Main Road in the country. (Recorded on a bend on the A44 near Leominster.                                                                                ::
    ID: 07044007.wav
    Length: 255
** High Street in a small town, with traffic and footsteps.                                                                                ::
    ID: 07044006.wav
    Length: 246
** Town Traffic on a wet road in a one-way system.                                                                                ::
    ID: 07044005.wav
    Length: 261
** City Park on a breezy day, near a pond with ducks, moorhens and geese.                                                                                ::
    ID: 07044004.wav
    Length: 258
** Seawash, gentle, with occasional seagulls.                                                                                ::
    ID: 07044003.wav
    Length: 242
** Mountain Stream.                                                                                ::
    ID: 07044002.wav
    Length: 211
** Open Air Swimming Pool, with children splashing & shouting. (Recorded near London.)                                                                                ::
    ID: 07044001.wav
    Length: 243
** Flamborough Head Lighthouse's Foghorn sounding. (Nautophone  horn, c.1960s.) (Distant perspective.)                                                                                ::
    ID: 07043406.wav
    Length: 12
** Flamborough Head Lighthouse's Foghorn sounding. (Nautophone  horn, c.1960s.) (Close perspective.)                                                                                ::
    ID: 07043405.wav
    Length: 10
** Whitby Lighthouse's Foghorn sounding. (Elliptical horn, c.1950s.) (Distant perspective.)                                                                                ::
    ID: 07043404.wav
    Length: 27
** Whitby Lighthouse's Foghorn sounding. (Elliptical horn, c.1950s.) (Close perspective.)                                                                                ::
    ID: 07043403.wav
    Length: 22
** Frankenstein's Castle-style thunder, etc.                                                                                ::
    ID: 07043402.wav
    Length: 120
** Severe thunder storm with light rain.                                                                                ::
    ID: 07043401.wav
    Length: 147
** Thunder storm, with light rain.                                                                                ::
    ID: 07043400.wav
    Length: 212
** Lightning strike with thunder crash.                                                                                ::
    ID: 07043399.wav
    Length: 6
** Lightning strike with thunder crash.                                                                                ::
    ID: 07043398.wav
    Length: 11
** Simulated lightning strike, left to right.                                                                                ::
    ID: 07043397.wav
    Length: 3
** Simulated lightning strike, right to left.                                                                                ::
    ID: 07043396.wav
    Length: 3
** Thunder roll  (with rain).                                                                                ::
    ID: 07043395.wav
    Length: 35
** Thunder roll  (with rain).                                                                                ::
    ID: 07043394.wav
    Length: 41
** Thunder roll  (with rain).                                                                                ::
    ID: 07043393.wav
    Length: 39
** Thunder roll  (with rain).                                                                                ::
    ID: 07043392.wav
    Length: 32
** Thunder roll (with rain).                                                                                ::
    ID: 07043391.wav
    Length: 23
** Thunder crash.                                                                                ::
    ID: 07043390.wav
    Length: 10
** Thunder crash.                                                                                ::
    ID: 07043389.wav
    Length: 11
** Thunder crash.                                                                                ::
    ID: 07043388.wav
    Length: 12
** Thunder crash.                                                                                ::
    ID: 07043387.wav
    Length: 7
** Thunder crash.                                                                                ::
    ID: 07043386.wav
    Length: 9
** Thunder crash.                                                                                ::
    ID: 07043385.wav
    Length: 14
** Gale force wind & rain on yacht. (Recorded in cabin.)                                                                                ::
    ID: 07043384.wav
    Length: 210
** Gale force wind & rain on yacht. (Recorded in cockpit.)                                                                                ::
    ID: 07043383.wav
    Length: 178
** Rain on tent. (Interior acoustic.)                                                                                ::
    ID: 07043382.wav
    Length: 309
** Rain on corrugated iron shed roof.                                                                                ::
    ID: 07043381.wav
    Length: 157
** Rain on perspex shed roof.                                                                                ::
    ID: 07043380.wav
    Length: 394
** Hail on window. (Interior acoustic.)                                                                                ::
    ID: 07043379.wav
    Length: 120
** Heavy rain on car roof. (Interior acoustic.)                                                                                ::
    ID: 07043378.wav
    Length: 270
** Rain on window, with water dripping off roof. (Interior acoustic.)                                                                                ::
    ID: 07043377.wav
    Length: 231
** Driving rain on window. (Interior acoustic.)                                                                                ::
    ID: 07043376.wav
    Length: 290
** Rain on water. (Close perspective.)                                                                                ::
    ID: 07043375.wav
    Length: 270
** Rain on foliage.                                                                                ::
    ID: 07043374.wav
    Length: 330
** Heavy rain in yard (with gully noise).                                                                                ::
    ID: 07043373.wav
    Length: 173
** Lifeboat, winching boat up launching ramp into boathouse. (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043372.wav
    Length: 49
** Lifeboat, bow-wave. (Recorded on deck.) (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043371.wav
    Length: 93
** Lifeboat, engines in constant run. (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043370.wav
    Length: 141
** Lifeboat., atmosphere in wheelhouse, with some indistinct speech & R/T. (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043369.wav
    Length: 121
** Lifeboat, start, constant run, stop. (Recorded on deck.) (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043368.wav
    Length: 229
** Lifeboat, deck pick-up by Whirlwind Helicopter. (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043367.wav
    Length: 79
** Lifeboat, radar scanner revolving. (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043366.wav
    Length: 60
** Lifeboat, single maroon fired. (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043365.wav
    Length: 3
** Lifeboat, launch. (Recorded on board.) (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043364.wav
    Length: 55
** Lifeboat, launch. (Recorded on shore.) (48ft 6in Oakley class self-righting boat, RNLB 'Charles Henry'.)                                                                                ::
    ID: 07043363.wav
    Length: 20
** Thames sailing barge, atmosphere below deck under auxiliary engine. (Kelvin 3 cylinder engine, 66 h.p.) (Recorded on board S.B. Pudge.)                                                                                ::
    ID: 07043362.wav
    Length: 185
** Thames sailing barge, atmosphere below deck under sail, with creaking wood. (Recorded on board S.B. Pudge.)                                                                                ::
    ID: 07043361.wav
    Length: 184
** Thames sailing barge, hoisting topsial. (Recorded on board S.B. Pudge.)                                                                                ::
    ID: 07043360.wav
    Length: 32
** Thames sailing barge, going about, lee board raised & other lowered. (Recorded on board. S.B. Pudge.)                                                                                ::
    ID: 07043359.wav
    Length: 79
** Thames sailing barge, bow-wave sailing in force 5 wind, some spray. (Recorded on board S.B. Pudge.)                                                                                ::
    ID: 07043358.wav
    Length: 143
** Beam Fishing Trawler, general atmosphere on deck whilst trawling.                                                                                ::
    ID: 07043357.wav
    Length: 119
** Beam Fishing Trawler, washing fish on deck with hose.                                                                                ::
    ID: 07043356.wav
    Length: 47
** Beam Fishing Trawler, collecting fish from deck.                                                                                ::
    ID: 07043355.wav
    Length: 61
** Beam Fishing Trawler, catch hauled aboard.                                                                                ::
    ID: 07043354.wav
    Length: 112
** Beam Fishing Trawler, trawl gear lowered into water.                                                                                ::
    ID: 07043353.wav
    Length: 217
** Beam Fishing Trawler, atmosphere in wheelhouse with indistinct R/T.                                                                                ::
    ID: 07043352.wav
    Length: 139
** Beam Fishing Trawler, atmosphere at sea. (Recorded on deck.)                                                                                ::
    ID: 07043351.wav
    Length: 194
** German U-Boat, cruising on surface with Diesel engines. (Exterior acoustic.)                                                                                ::
    ID: 07043350.wav
    Length: 149
** German U-Boat surfacing.                                                                                ::
    ID: 07043349.wav
    Length: 39
** German U-Boat, blowing ballast.                                                                                ::
    ID: 07043348.wav
    Length: 11
** German U-Boat, electric motors, constant run submerged.                                                                                ::
    ID: 07043347.wav
    Length: 150
** German U-Boat, Diesel engines start, cruise underwater with snorkel.                                                                                ::
    ID: 07043346.wav
    Length: 180
** German U-Boat, torpedo room atmosphere.                                                                                ::
    ID: 07043345.wav
    Length: 147
** German U-Boat, torpedo passes left to right. (Recorded underwater.)                                                                                ::
    ID: 07043344.wav
    Length: 47
** German U-Boat, two torpedos fired. (Recorded in torpedo room.)                                                                                ::
    ID: 07043343.wav
    Length: 21
** German U-Boat, one torpedo fired. (Recorded in torpedo room.)                                                                                ::
    ID: 07043342.wav
    Length: 18
** Paddle Steamer, paddles thrashing in constant run.                                                                                ::
    ID: 07043341.wav
    Length: 97
** Paddle Steamer engines, constant run.                                                                                ::
    ID: 07043340.wav
    Length: 138
** Paddle Steamer, engines slow then stop, with telegraph.                                                                                ::
    ID: 07043339.wav
    Length: 111
** Paddle Steamer, engine room telegraph, engine start.                                                                                ::
    ID: 07043338.wav
    Length: 123
** Paddle Steamer, stoking boiler.                                                                                ::
    ID: 07043337.wav
    Length: 112
** Paddle Steamer, coaling ship.                                                                                ::
    ID: 07043336.wav
    Length: 60
** Paddle Steamer, hooter sounded.                                                                                ::
    ID: 07043335.wav
    Length: 6
** Paddle Steamer arriving at dock & berthing.                                                                                ::
    ID: 07043334.wav
    Length: 64
** Paddle Steamer departing from dock, with hooter.                                                                                ::
    ID: 07043333.wav
    Length: 69
** Synthesised crickets. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043332.wav
    Length: 60
** Pulsating pink noise. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043331.wav
    Length: 72
** Simulated jet engine, (run up, run down)                                                                                ::
    ID: 07043330.wav
    Length: 54
** Particle beaming device, run up, fades. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043329.wav
    Length: 23
** Particle beaming device, idle, run up, run down, idle. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043328.wav
    Length: 55
** Particle beaming device (constant background). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043327.wav
    Length: 152
** Machine hum with heartbeat. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043326.wav
    Length: 73
** Electronic machine buzz. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043325.wav
    Length: 144
** Electronic machine buzz. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043324.wav
    Length: 96
** Electronic warble. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043323.wav
    Length: 64
** High pitch machinery. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043322.wav
    Length: 62
** Electronic multiple motors.  (Futuristic Spot Effect.)                                                                                ::
    ID: 07043321.wav
    Length: 193
** Electronic multiple motors (high pitch). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043320.wav
    Length: 153
** Electronic multiple motors. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043319.wav
    Length: 154
** Motor starts into constant run. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043318.wav
    Length: 117
** Electronic motor hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043317.wav
    Length: 152
** Electronic motor hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043316.wav
    Length: 150
** Electronic motor hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043315.wav
    Length: 154
** Generator hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043314.wav
    Length: 97
** High pitch pulsating hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043313.wav
    Length: 153
** Variable pitch harmonic hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043312.wav
    Length: 87
** Digital hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043311.wav
    Length: 99
** Threatening robotic hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043310.wav
    Length: 112
** Pulsing harmonic bass hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043309.wav
    Length: 142
** Mid pitch pulsing hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043308.wav
    Length: 154
** High power phaser weapon, bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043307.wav
    Length: 12
** High power phaser weapon, four single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043306.wav
    Length: 6
** High power phaser weapon., single shot. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043305.wav
    Length: 1
** Hand phaser weapon, bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043304.wav
    Length: 17
** Hand phaser weapon, six single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043303.wav
    Length: 8
** Hand phaser weapon, single shot. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043302.wav
    Length: 1
** Stun gun, prolonged burst. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043301.wav
    Length: 9
** Stun gun, series of bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043300.wav
    Length: 23
** Stun gun, single burst. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043299.wav
    Length: 2
** Stun gun, rapid single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043298.wav
    Length: 9
** Stun gun, three single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043297.wav
    Length: 7
** Stun gun, single shot. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043296.wav
    Length: 1
** Variable velocity gun, series of bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043295.wav
    Length: 13
** Variable velocity gun, short bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043294.wav
    Length: 1
** Variable velocity gun, six single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043293.wav
    Length: 13
** Variable velocity gun, single shot. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043292.wav
    Length: 1
** Inverse gun, bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043291.wav
    Length: 11
** Inverse gun, six single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043290.wav
    Length: 4
** Inverse gun, single shot. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043289.wav
    Length: 1
** Pump action rifle, short bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043288.wav
    Length: 17
** Pump action rifle, six single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043287.wav
    Length: 11
** Pump action rifle, single shot. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043286.wav
    Length: 1
** Compressed gas gun, mixed bursts & single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043285.wav
    Length: 8
** Compressed gas gun, single burst. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043284.wav
    Length: 3
** Compressed gas gun, six single shots. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043283.wav
    Length: 12
** Compressed gas gun, single shot. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043282.wav
    Length: 1
** Machine gun rhythm, rapid prolonged bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043281.wav
    Length: 20
** Machine gun rhythm, rapid series of bursts. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043280.wav
    Length: 32
** Machine gun rhythm, short rapid burst. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043279.wav
    Length: 3
** Machine gun rhythm, slow. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043278.wav
    Length: 11
** Sliding door, slow, no hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043277.wav
    Length: 1
** Sliding door, rapid, no hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043276.wav
    Length: 1
** Sliding door, medium, no hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043275.wav
    Length: 1
** Sliding door, slow, no hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043274.wav
    Length: 1
** Sliding door, medium, with mechanism hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043273.wav
    Length: 1
** Sliding door, rapid, with mechanism hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043272.wav
    Length: 1
** Sliding door, rapid, with mechanism hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043271.wav
    Length: 1
** Sliding door, slow, with mechanism hum. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043270.wav
    Length: 1
** Eerie electronic noise (various different pitches). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043269.wav
    Length: 24
** Eerie electronic noise. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043268.wav
    Length: 7
** Missile ricochets right to left (high pitch). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043267.wav
    Length: 3
** Missile ricochets right to left (high pitch). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043266.wav
    Length: 3
** Missile ricochets left to right. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043265.wav
    Length: 3
** Electronic Bubbles, rising pitch. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043264.wav
    Length: 8
** Electronic Pipes dropped. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043263.wav
    Length: 4
** Space craft lands. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043262.wav
    Length: 16
** Descending projectile passes left to right (low pitch). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043261.wav
    Length: 4
** Descending projectile passes left to right. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043260.wav
    Length: 4
** Descending projectile passes from right to left. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043259.wav
    Length: 3
** Descending Crash. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043258.wav
    Length: 6
** Severe Crash. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043257.wav
    Length: 3
** Double Crash. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043256.wav
    Length: 7
** Single Crash. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043255.wav
    Length: 6
** Buzzing Computer with constant tone background. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043254.wav
    Length: 37
** Rapid Chattering Computer (descending pitch). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043253.wav
    Length: 26
** Talking Computer (mid pitch with warble). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043252.wav
    Length: 45
** Talking Computer (mid pitch, digital). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043251.wav
    Length: 71
** Talking Computer (low pitch, harmonic). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043250.wav
    Length: 48
** Talking Computer (mid pitch, harmonic). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043249.wav
    Length: 63
** 4 Minute Warning alert, massed sirens. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043248.wav
    Length: 28
** 4 Minute Warning alert, two cycles, (High pitch.) (Futuristic Spot Effect.)                                                                                ::
    ID: 07043247.wav
    Length: 8
** 4 Minute Warning alert, two cycles. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043246.wav
    Length: 8
** Electronic alarm bell. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043245.wav
    Length: 32
** Descending siren. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043244.wav
    Length: 35
** Emergency alarm (with slight phasing). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043243.wav
    Length: 26
** Emergency alarm (with slight phasing). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043242.wav
    Length: 32
** Rapid cyclical alarm. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043241.wav
    Length: 21
** Slow cyclical alarm. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043240.wav
    Length: 41
** Synthesised air raid alarm. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043239.wav
    Length: 43
** Rapid warble alarm (high pitch). (Futuristic Spot Effect.)                                                                                ::
    ID: 07043238.wav
    Length: 31
** Rapid warble alarm. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043237.wav
    Length: 34
** Mewing kitten alarm (high pitch.) (Futuristic Spot Effect.)                                                                                ::
    ID: 07043236.wav
    Length: 16
** Mewing kitten alarm. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043235.wav
    Length: 32
** Repeating cat alarm. (Futuristic Spot Effect.)                                                                                ::
    ID: 07043234.wav
    Length: 46
** Land Rover, exterior, approach & stop.                                                                                ::
    ID: 07043233.wav
    Length: 26
** Land Rover, exterior, passes right to left.                                                                                ::
    ID: 07043232.wav
    Length: 12
** Land Rover, exterior, switch on & depart.                                                                                ::
    ID: 07043231.wav
    Length: 17
** Landrover, interior, switch on continuous run, switch off in mud.                                                                                ::
    ID: 07043230.wav
    Length: 136
** Standing tanks & soldiers, general atmosphere, with one vehicle passing.                                                                                ::
    ID: 07043229.wav
    Length: 71
** Tanks approaching & manoevering in mud.                                                                                ::
    ID: 07043228.wav
    Length: 177
** Chieftain Tank, interior atmosphere (mainly the noise of air conditioning for on board computer).                                                                                ::
    ID: 07043227.wav
    Length: 82
** Armoured Personnel Carrier, interior, start, engine idles, continuous run, stop.                                                                                ::
    ID: 07043226.wav
    Length: 98
** Armoured Personnel Carrier, exterior, approaches, engine idles, departs.                                                                                ::
    ID: 07043225.wav
    Length: 48
** Armoured Personnel Carrier, exterior, passes right to left in mud.                                                                                ::
    ID: 07043224.wav
    Length: 25
** USAF Fairchild A-10 Thunderbolt, two fly overhead firing cannon (some tank engine noise in foreground).                                                                                ::
    ID: 07043223.wav
    Length: 22
** USAF Fairchild A-10 Thunderbolt, four fly overhead (some tank engine noise in foreground).                                                                                ::
    ID: 07043222.wav
    Length: 54
** RAF Hawker Siddeley Harrier, three fly overhead firing cannon (some tank engine noise in foreground).                                                                                ::
    ID: 07043221.wav
    Length: 33
** RAF Hawker Siddeley Harrier, three fly overhead firing rockets (some tank engine noise in foreground).                                                                                ::
    ID: 07043220.wav
    Length: 31
** RAF Hawker Siddeley Harrier, three fly overhead (some tank engine noise in foreground).                                                                                ::
    ID: 07043219.wav
    Length: 33
** Battlefield atmosphere, distant perspective with some close explosions.                                                                                ::
    ID: 07043218.wav
    Length: 152
** Battlefield atmosphere, middle-distant perspective with close mortars firing.                                                                                ::
    ID: 07043217.wav
    Length: 162
** Battlefield atmosphere. (Close perspective.)                                                                                ::
    ID: 07043216.wav
    Length: 125
** Scorpion Armored Vehicle, firing three High Explosive Squash Head (HESH) rounds. (Distant perspective.)                                                                                ::
    ID: 07043215.wav
    Length: 41
** Scorpion Armored Vehicle, firing High Explosive Squash Head (HESH) round.                                                                                ::
    ID: 07043214.wav
    Length: 7
** Chieftain Tank, firing machine guns & shells while moving. (Distant perspective.)                                                                                ::
    ID: 07043213.wav
    Length: 40
** Chieftain Tank, firing machine guns & shells while moving. (Close perspective.)                                                                                ::
    ID: 07043212.wav
    Length: 74
** Chieftain Tank, firing three High Explosive Squash Head (HESH) rounds. (Distant perspective.)                                                                                ::
    ID: 07043211.wav
    Length: 28
** Chieftain Tank, firing four High Explosive Squash Head (HESH) rounds. (Close perspective.)                                                                                ::
    ID: 07043210.wav
    Length: 53
** Chieftain Tank, firing armour piercing round. (Recorded close to recieving end.)                                                                                ::
    ID: 07043209.wav
    Length: 8
** Chieftain Tank, firing armour piercing round. (Close perspective.)                                                                                ::
    ID: 07043208.wav
    Length: 10
** Chieftain Tank, firing two rounds of 105mm shells. (Middle-distant perspective.)                                                                                ::
    ID: 07043207.wav
    Length: 6
** Chieftain Tank, firing two rounds of 105mm shells.                                                                                ::
    ID: 07043206.wav
    Length: 8
** Scimitar Armoured Vehicle, firing on automatic. (Distant perspective.)                                                                                ::
    ID: 07043205.wav
    Length: 10
** Scimitar Armoured Vehicle, three shots fired. (Distant perspective.)                                                                                ::
    ID: 07043204.wav
    Length: 15
** Scimitar Armoured Vehicle, firing on automatic. (Close perspective.)                                                                                ::
    ID: 07043203.wav
    Length: 11
** Scimitar Armoured Vehicle, three shots fired. (Close perspective.)                                                                                ::
    ID: 07043202.wav
    Length: 17
** 81mm medium mortar, firing multiple high explosive & smoke charges, explosions after 0m22s. (Recorded close to firing end.)                                                                                 ::
    ID: 07043201.wav
    Length: 39
** 81mm medium mortar, firing multiple high explosive & smoke charges, explosions after 0m21s. (Distant perspective.)                                                                                ::
    ID: 07043200.wav
    Length: 38
** 81mm medium mortar, firing multiple high explosive charges, explosions after 0m19s. (Recorded close to firing end.)                                                                                ::
    ID: 07043199.wav
    Length: 29
** 66mm light anti tank weapon fired. (Middle-distant perpective.)                                                                                ::
    ID: 07043198.wav
    Length: 6
** 84mm medium anti tank weapon fired. (Distant perpective.)                                                                                ::
    ID: 07043197.wav
    Length: 6
** 84mm medium anti tank weapon, two rounds of high explosive fired. (Close perspective.)                                                                                ::
    ID: 07043196.wav
    Length: 5
** Rapid gunfire. (Distant perpective.)                                                                                ::
    ID: 07043195.wav
    Length: 6
** General purpose machine gun surface fire. (Distant perspective.)                                                                                ::
    ID: 07043194.wav
    Length: 6
** Rapid fire in air defence.                                                                                ::
    ID: 07043193.wav
    Length: 8
** General purpose machine gun pimple & turret mounted firing in turn.                                                                                ::
    ID: 07043192.wav
    Length: 12
** General purpose machine gun firing from behind & above.                                                                                ::
    ID: 07043191.wav
    Length: 15
** General purpose machine gun firing from in front & close left.                                                                                ::
    ID: 07043190.wav
    Length: 29
** General purpose machine gun, distant.                                                                                ::
    ID: 07043189.wav
    Length: 11
** General purpose machine gun, surface fire from close left.                                                                                ::
    ID: 07043188.wav
    Length: 14
** Machine guns firing from all sides. (Close perpective.)                                                                                ::
    ID: 07043187.wav
    Length: 20
** 5.6mm light support weapon firing. (Distant perspective.)                                                                                ::
    ID: 07043186.wav
    Length: 9
** 5.6mm light support weapon firing. (Close perspective.)                                                                                ::
    ID: 07043185.wav
    Length: 7
** 5.6mm gas operated rifle, platoon fires 200 rounds on automatic radio. (Distant perspective.)                                                                                ::
    ID: 07043184.wav
    Length: 9
** 5.6mm gas operated rifle, platoon fires 200 rounds on automatic. (Close perspective.)                                                                                ::
    ID: 07043183.wav
    Length: 9
** 5.6mm gas operated rifle, a section firing single shots. (Distant perspective.)                                                                                ::
    ID: 07043182.wav
    Length: 10
** 5.6mm gas operated rifle, a section firing single shots. (Close perspective.)                                                                                ::
    ID: 07043181.wav
    Length: 9
** 5.6mm gas operated rifle, six single shots on targets. (Distant perspective.)                                                                                ::
    ID: 07043180.wav
    Length: 8
** 5.6mm gas operated rifle, six single shots on targets. (Close perspective.)                                                                                ::
    ID: 07043179.wav
    Length: 9
** Sniper, single shot fired from position 10 feet away.                                                                                ::
    ID: 07043178.wav
    Length: 5
** Burglar Alarm, bell.                                                                                ::
    ID: 07043177.wav
    Length: 34
** Burglar Alarm, electronic spin.                                                                                ::
    ID: 07043176.wav
    Length: 15
** Car alarm.                                                                                ::
    ID: 07043175.wav
    Length: 15
** Electronic Alarm, rapid pips.                                                                                ::
    ID: 07043174.wav
    Length: 18
** Electronic Alarm, wail with wobble on top.                                                                                ::
    ID: 07043173.wav
    Length: 31
** Electronic Alarm, gun shots.                                                                                ::
    ID: 07043172.wav
    Length: 22
** Electronic Alarm, urgent.                                                                                ::
    ID: 07043171.wav
    Length: 86
** Quarrying, road drill with compressor.                                                                                ::
    ID: 07043170.wav
    Length: 126
** Quarrying, rock crusher, lorry unloads & crusher operates.                                                                                ::
    ID: 07043169.wav
    Length: 110
** Quarrying, dumper trucks, three start up & depart.                                                                                ::
    ID: 07043168.wav
    Length: 68
** Quarrying, single explosion in hardstone quarry.                                                                                ::
    ID: 07043167.wav
    Length: 21
** Quarrying, three siren blasts. (Short World War II siren.)                                                                                ::
    ID: 07043166.wav
    Length: 30
** Gelignite, three 8oz sticks explode at 20 feet.                                                                                ::
    ID: 07043165.wav
    Length: 3
** Gelignite, two 8oz sticks explode at 20 feet.                                                                                ::
    ID: 07043164.wav
    Length: 3
** Bag of bottles break.                                                                                ::
    ID: 07043163.wav
    Length: 2
** Beer bottle breaks, with fizz.                                                                                ::
    ID: 07043162.wav
    Length: 6
** Wine bottle breaks.                                                                                ::
    ID: 07043161.wav
    Length: 2
** Firework Night, atmosphere in suburban England with some traffic.                                                                                ::
    ID: 07043160.wav
    Length: 270
** Fireworks, Catherine Wheel with indistinct speech.                                                                                ::
    ID: 07043159.wav
    Length: 17
** Fireworks, Ground Mine.                                                                                ::
    ID: 07043158.wav
    Length: 4
** Fireworks, Chinese Fire Cracker.                                                                                ::
    ID: 07043157.wav
    Length: 11
** Fireworks, Screamer.                                                                                ::
    ID: 07043156.wav
    Length: 4
** Fireworks, Rocket.                                                                                ::
    ID: 07043155.wav
    Length: 2
** Fireworks, Thunderflash.                                                                                ::
    ID: 07043154.wav
    Length: 2
** Fireworks, Roman Candle.                                                                                ::
    ID: 07043153.wav
    Length: 27
** Fireworks, Mine of Serpents.                                                                                ::
    ID: 07043152.wav
    Length: 9
** Fireworks, Crackerjack Fountain.                                                                                ::
    ID: 07043151.wav
    Length: 28
** Fireworks, Retrojet Fountain.                                                                                ::
    ID: 07043150.wav
    Length: 44
** Fireworks, Chrysanthemum Fountain.                                                                                ::
    ID: 07043149.wav
    Length: 27
** Jaguar Sovereign, exterior, fast pass left to right. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043148.wav
    Length: 28
** Jaguar Sovereign, exterior, pass right to left. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043147.wav
    Length: 24
** Jaguar Sovereign, exterior, approach from right, skid, switch off. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043146.wav
    Length: 24
** Jaguar Sovereign, exterior, approach from right, idle, switch off. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043145.wav
    Length: 27
** Jaguar Sovereign, exterior, switch on, fast depart. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043144.wav
    Length: 27
** Jaguar Sovereign, exterior, switch on, depart. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043143.wav
    Length: 24
** Jaguar Sovereign, exterior, switch on, idle, switch off. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043142.wav
    Length: 143
** Jaguar Sovereign, exterior, two false starts. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043141.wav
    Length: 10
** Jaguar Sovereign, interior, approach motorway, constant run on motorway, leave motorway. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043140.wav
    Length: 308
** Jaguar Sovereign, interior, skid to stop. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043139.wav
    Length: 6
** Jaguar Sovereign, interior, switch on, constant run. (3.6 litre, 1986/7 model.)                                                                                ::
    ID: 07043138.wav
    Length: 453
** Peugeot 309, exterior, slow pass right to left. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043137.wav
    Length: 28
** Peugeot 309, exterior, approach from right, skid to stop & reverse, switch off. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043136.wav
    Length: 29
** Peugeot 309, exterior, approach from left, skid, idle, switch off. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043135.wav
    Length: 28
** Peugeot 309, exterior, approach from right, idle, switch off. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043134.wav
    Length: 23
** Peugeot 309, exterior, switch on, fast depart with squeal. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043133.wav
    Length: 23
** Peugeot 309, exterior, switch on, depart. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043132.wav
    Length: 23
** Peugeot 309, exterior, switch on, idle, switch off. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043131.wav
    Length: 159
** Peugeot 309, interior, constant run, skids to a stop. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043130.wav
    Length: 22
** Peugeot 309, interior, constant run. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043129.wav
    Length: 370
** Peugeot 309, interior, switch on, idle, switch off. (1.9 litre Diesel engine, 1986/7 model.)                                                                                ::
    ID: 07043128.wav
    Length: 64
** Vauxhall Carlton, exterior, medium speed pass right to left. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043127.wav
    Length: 14
** Vauxhall Carlton, exterior, slow pass left to right. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043126.wav
    Length: 21
** Vauxhall Carlton, exterior, approach from right & stop, switch off. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043125.wav
    Length: 18
** Vauxhall Carlton, exterior, switch on, depart. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043124.wav
    Length: 20
** Vauxhall Carlton, exterior, switch on, rev cold engine, engine fails. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043123.wav
    Length: 59
** Vauxhall Carlton, exterior, switch on, idle, switch off. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043122.wav
    Length: 63
** Vauhall Carlton, interior, switch on, constant run, switch off. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043121.wav
    Length: 308
** Vauxhall Carlton, interior, switch on, idle, switch off. (1.8 litre saloon, 1986 model.)                                                                                ::
    ID: 07043120.wav
    Length: 48
** Ford Fiesta, exterior, fast pass right to left. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043119.wav
    Length: 37
** Ford Fiesta, exterior, slow pass right to left. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043118.wav
    Length: 24
** Ford Fiesta, exterior, approach from left & stop, switch off. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043117.wav
    Length: 23
** Ford Fiesta, exterior, switch on, depart. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043116.wav
    Length: 17
** Ford Fiesta, exterior, switch on, idle, switch off. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043115.wav
    Length: 94
** Ford Fiesta, interior, switch on, constant run, switch off. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043114.wav
    Length: 330
** Ford Fiesta, interior, switch on, reverse, switch off. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043113.wav
    Length: 21
** Ford Fiesta, interior, switch on, idle, switch off. (1.1 litre hatchback, 1986/7 model.)                                                                                ::
    ID: 07043112.wav
    Length: 64
** Car, interior, heating fan.                                                                                ::
    ID: 07043111.wav
    Length: 103
** Car, interior, windscreen wipers, fast.                                                                                ::
    ID: 07043110.wav
    Length: 43
** Car, interior, windscreen wipers, slow.                                                                                ::
    ID: 07043109.wav
    Length: 130
** Car, exterior, horn, six blasts.                                                                                ::
    ID: 07043108.wav
    Length: 10
** Car, interior, horn, four blasts.                                                                                ::
    ID: 07043107.wav
    Length: 14
** Car, interior, indicators operating.                                                                                ::
    ID: 07043106.wav
    Length: 63
** Car, interior, handbrake released.                                                                                ::
    ID: 07043105.wav
    Length: 3
** Car, interior, handbrake applied.                                                                                ::
    ID: 07043104.wav
    Length: 2
** Car, interior, seatbelt released.                                                                                ::
    ID: 07043103.wav
    Length: 4
** Car, interior, seatbelt fastened.                                                                                ::
    ID: 07043102.wav
    Length: 5
** Car, interior, window wound down & up (with squeak).                                                                                ::
    ID: 07043101.wav
    Length: 19
** Car, exterior, window wound down & up.                                                                                ::
    ID: 07043100.wav
    Length: 13
** Car, interior, tin door opens & shuts.                                                                                ::
    ID: 07043099.wav
    Length: 8
** Car, interior, opens & shuts.                                                                                ::
    ID: 07043098.wav
    Length: 6
** Car, exterior, hatch shuts.                                                                                ::
    ID: 07043097.wav
    Length: 4
** Car, exterior, hatch opens.                                                                                ::
    ID: 07043096.wav
    Length: 5
** Car, exterior, tin door opens & shuts.                                                                                ::
    ID: 07043095.wav
    Length: 5
** Car, exterior, door opens & shuts.                                                                                ::
    ID: 07043094.wav
    Length: 5
** Group of young people walking in park, with some voices.                                                                                ::
    ID: 07043093.wav
    Length: 41
** Twenty men walking in broken step.                                                                                ::
    ID: 07043092.wav
    Length: 92
** Footsteps on shingle, with distant seawash.                                                                                ::
    ID: 07043091.wav
    Length: 63
** Footsteps in snow.                                                                                ::
    ID: 07043090.wav
    Length: 61
** Two men walking on pavement.                                                                                ::
    ID: 07043089.wav
    Length: 53
** One man walking on pavement.                                                                                ::
    ID: 07043088.wav
    Length: 60
** Crowd at Buckingham Palace, cheers for Queen.                                                                                ::
    ID: 07043087.wav
    Length: 40
** Large Crowd at Royal occasion.                                                                                ::
    ID: 07043086.wav
    Length: 135
** Industrial Dispute, cheers, clapping & booing.                                                                                ::
    ID: 07043085.wav
    Length: 47
** Industrial Dispute, chanting among marchers.                                                                                ::
    ID: 07043084.wav
    Length: 85
** Industrial Dispute, jeers & calls.                                                                                ::
    ID: 07043083.wav
    Length: 51
** London Marathon, cheers & applause.                                                                                ::
    ID: 07043082.wav
    Length: 111
** London Marathon, atmosphere near start.                                                                                ::
    ID: 07043081.wav
    Length: 140
** County Cricket Match, general atmopshere. (Recorded during Hertfordshire v. Somerset.)                                                                                ::
    ID: 07043080.wav
    Length: 189
** Football Crowd reaction to goal in Second Division Match. (Recorded during Portsmouth v. Carlisle, 6th May 1985.)                                                                                ::
    ID: 07043079.wav
    Length: 80
** Football Crowd reaction to near miss during Second Division Match. (Recorded during Portsmouth v. Carlisle, 6th May 1985.)                                                                                ::
    ID: 07043078.wav
    Length: 20
** Football Crowd during Second Division Match. (Recorded during Portsmouth v. Carlisle, 6th May 1985.)                                                                                ::
    ID: 07043077.wav
    Length: 151
** Two thousand children outside.                                                                                ::
    ID: 07043076.wav
    Length: 124
** Forty children outside on wet gravel.                                                                                ::
    ID: 07043075.wav
    Length: 128
** Children fidgeting quitely.                                                                                ::
    ID: 07043074.wav
    Length: 116
** Children chattering quietly.                                                                                ::
    ID: 07043073.wav
    Length: 95
** Children booing & hissing.                                                                                ::
    ID: 07043072.wav
    Length: 26
** Children cheering.                                                                                ::
    ID: 07043071.wav
    Length: 7
** Noisy Children in class, with banging.                                                                                ::
    ID: 07043070.wav
    Length: 79
** Hysterical Children in class, quietens at end.                                                                                ::
    ID: 07043069.wav
    Length: 19
** Two & a quarter year old baby talking nonsense.                                                                                ::
    ID: 07043068.wav
    Length: 238
** Two & a quarter year old baby crying.                                                                                ::
    ID: 07043067.wav
    Length: 122
** Press Reception atmosphere. (Useful also for party atmosphere.)                                                                                ::
    ID: 07043066.wav
    Length: 106
** Department Store atmosphere.                                                                                ::
    ID: 07043065.wav
    Length: 130
** Concert Audience, applause, cheers & stamping after piece, into stamping & slow hand clapping.                                                                                ::
    ID: 07043064.wav
    Length: 240
** Concert Audience, applause between movements.                                                                                ::
    ID: 07043063.wav
    Length: 21
** Concert Audience, applause & tuning before piece, applause for Orchestra Leader, tuning, applause for Conductor.                                                                                ::
    ID: 07043062.wav
    Length: 133
** Theatre Audience, laughter & applause into interval.                                                                                ::
    ID: 07043061.wav
    Length: 180
** Theatre Audince, continuous laughter.                                                                                ::
    ID: 07043060.wav
    Length: 10
** Theatre Audience in foyer during interval.                                                                                ::
    ID: 07043059.wav
    Length: 121
** Light Entertainment Audience, continuous applause.                                                                                ::
    ID: 07043058.wav
    Length: 25
** Light Entertainment Audience, cheer into applause.                                                                                ::
    ID: 07043057.wav
    Length: 14
** Light Entertainment Audience, laugh into applause.                                                                                ::
    ID: 07043056.wav
    Length: 8
** Light Entertainment Audience, continuous laughing.                                                                                ::
    ID: 07043055.wav
    Length: 7
** Light Entertainment Audience, loud laugh with clapping.                                                                                ::
    ID: 07043054.wav
    Length: 6
** Light Entertainment Audience, hearty laughter.                                                                                ::
    ID: 07043053.wav
    Length: 3
** Light Entertainment Audience, light laughter.                                                                                ::
    ID: 07043052.wav
    Length: 2
** Light Entertainment Audience, crowds laughing.                                                                                ::
    ID: 07043051.wav
    Length: 3
** Light Entertainment Audience, sympathetic "Aaahs"                                                                                ::
    ID: 07043050.wav
    Length: 4
** Light Entertainment Audience, boos and hisses.                                                                                ::
    ID: 07043049.wav
    Length: 16
** Light Entertainment Audience, continuous cheering & applause.                                                                                ::
    ID: 07043048.wav
    Length: 17
** Light Entertainment Audience, crowd cheering.                                                                                ::
    ID: 07043047.wav
    Length: 4
** Light Entertainment Audience, quiet expectant audience with some laughter.                                                                                ::
    ID: 07043046.wav
    Length: 56
** Car Ferry, atmosphere in rest lounge in public area, with childrens' voices. (Car Ferry "St. Nicholas", 17,400 tons, built 1980.)                                                                                ::
    ID: 07043045.wav
    Length: 110
** Car Ferry, watertight door open  & close, bell warns of closing. (Car Ferry "St. Nicholas", 17,400 tons, built 1980.)                                                                                ::
    ID: 07043044.wav
    Length: 22
** Car Ferry, atmosphere in engine room. (Car Ferry "St. Nicholas", 17,400 tons, built 1980.)                                                                                ::
    ID: 07043043.wav
    Length: 120
** Car Ferry Bridge, with morse code, RT & intercoms security announcement (at 1m33s). (Car Ferry "St. Nicholas", 17,400 tons, built 1980.)                                                                                ::
    ID: 07043042.wav
    Length: 121
** Car Ferry, siren at Harwich berth. (Car Ferry "St. Nicholas", 17,400 tons, built 1980.)                                                                                ::
    ID: 07043041.wav
    Length: 12
** Car Ferry, bow wave at port side. (Car Ferry "St. Nicholas", 17,400 tons, built 1980.)                                                                                ::
    ID: 07043040.wav
    Length: 119
** Car Ferry, seawash at stern. (Car Ferry "St. Nicholas", 17,400 tons, built 1980.)                                                                                ::
    ID: 07043039.wav
    Length: 182
** Hughes 500E Helicopter, exterior, approach, land, switch off.                                                                                :Aircraft:Helicopters:
    ID: 07043038.wav
    Length: 212
** Bell Jetranger Executive Helicopter, interior, engine failure warning siren.                                                                                :Aircraft:Helicopters:
    ID: 07043037.wav
    Length: 12
** Bell Jetranger Executive Helicopter, interior, descent, land, switch off.                                                                                :Aircraft:Helicopters:
    ID: 07043036.wav
    Length: 145
** Bell Jetranger Executive Helicopter, interior, start, run up engines, take-off.                                                                                :Aircraft:Helicopters:
    ID: 07043035.wav
    Length: 302
** Shorts 360 Commuter Transporter, interior, land, taxi to halt. (2 turboprop engines.)                                                                                ::
    ID: 07043034.wav
    Length: 202
** Shorts 360 Commuter Transporter, interior, take-off into constant flight. (2 turboprop engines.)                                                                                ::
    ID: 07043033.wav
    Length: 113
** Shorts 360 Commuter Transporter, interior, run-up engines, taxi. (2 turboprop engines)                                                                                ::
    ID: 07043032.wav
    Length: 131
** Electric Train, exterior, as Diesel Express 125 passes under bridge from right to left. (Class 317, built 1983.)                                                                                ::
    ID: 07043031.wav
    Length: 22
** Electric Train, exterior, pass through station from left to right. (Class 317, built 1983.)                                                                                ::
    ID: 07043030.wav
    Length: 24
** Electric Train, exterior, doors close, horn sounds, departs. (Class 317, built 1983.)                                                                                ::
    ID: 07043029.wav
    Length: 27
** Electric Train, exterior, arrives in station, doors open. (Class 317, built 1983.)                                                                                ::
    ID: 07043028.wav
    Length: 26
** Electric Train, interior, sliding doors close, run, stop in station. (Class 317, built 1983.)                                                                                ::
    ID: 07043027.wav
    Length: 216
** Regents Park Underground Station, atmosphere on platform, train arrives & departs.                                                                                ::
    ID: 07043026.wav
    Length: 74
** London Underground Train, interior, doors close, run, doors open. (Recorded on the Victoria Line.)                                                                                ::
    ID: 07043025.wav
    Length: 93
** Amsterdam Tram, exterior, pass from right to left. (8-axle articulated tram, built 1980.)                                                                                ::
    ID: 07043024.wav
    Length: 23
** Amsterdam Tram, exterior, doors close with bell, departs. (8-axle articulated tram, built 1980.)                                                                                ::
    ID: 07043023.wav
    Length: 12
** Amsterdam Tram, exterior, approach, doors open & passengers alight. (8-axle articulated tram, built 1980.)                                                                                ::
    ID: 07043022.wav
    Length: 21
** Amsterdam Tram, interior, run with several stops & some Dutch voices.(8-axle articulated tram, built 1980.)                                                                                ::
    ID: 07043021.wav
    Length: 320
** Bicycle, 1936 Raleigh sports model, passing with bell from left to right.                                                                                ::
    ID: 07043020.wav
    Length: 9
** Bicycle, 1936 Raleigh sports model, continuous run on road with traffic passing. (Recorded on bicycle.)                                                                                ::
    ID: 07043019.wav
    Length: 180
** Rolls Royce Silver Spirit, exterior, door opened & closed. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043018.wav
    Length: 7
** Rolls Royce Silver Spirit, exterior, horn sounded. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043017.wav
    Length: 7
** Rolls Royce Silver Spirit, exterior, approach & stop. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043016.wav
    Length: 12
** Rolls Royce Silver Spirit, exterior, pass from left to right. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043015.wav
    Length: 8
** Rolls Royce Silver Spirit, exterior, start up & drive off. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043014.wav
    Length: 11
** Rolls Royce Silver Spirit, interior, electrically operated seat adjustment. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043013.wav
    Length: 15
** Rolls Royce Silver Spirit, interior, electrical window open & close. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043012.wav
    Length: 13
** Rolls Royce Silver Spirit, interior, emergency stop. (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043011.wav
    Length: 11
** Rolls Royce Silver Spirit, interior, start up, constant run, stop. (Horn sounded at 1m39s.) (6.75 litres, 1986 model.)                                                                                ::
    ID: 07043010.wav
    Length: 376
** BMW Motor Cycle, hooter sounded. (980cc, 2 cylinders, 1982 model.)                                                                                ::
    ID: 07043009.wav
    Length: 4
** BMW Motor Cycle, approach & stop, onto stand. (980cc, 2 cylinders, 1982 model.)                                                                                ::
    ID: 07043008.wav
    Length: 19
** BMW Motor Cycle, pass from right to left. (980cc, 2 cylinders, 1982 model.)                                                                                ::
    ID: 07043007.wav
    Length: 10
** BMW Motor Cycle, off stand, false start, drive off. (980cc, 2 cylinders, 1982 model.)                                                                                ::
    ID: 07043006.wav
    Length: 24
** BMW Motor Cycle, start up, constant run, stop. (Recorded on bike.) (980cc, 2 cylinders, 1982 model.)                                                                                ::
    ID: 07043005.wav
    Length: 157
** Bedford Truck, exterior, approach, stop & switch off. (10 ton Diesel truck, 6 cylinders, 1984 model.)                                                                                ::
    ID: 07043004.wav
    Length: 13
** Bedford Truck, exterior, pass from left to right. (10 ton Diesel truck, 6 cylinders, 1984 model.)                                                                                ::
    ID: 07043003.wav
    Length: 18
** Bedford Truck, exterior, start up & drive off. (10 ton Diesel truck, 6 cylinders, 1984 model.)                                                                                ::
    ID: 07043002.wav
    Length: 17
** Bedford Truck, interior, start up, constant run, stop. (10 ton Diesel truck, 6 cylinders, 1984 model.)                                                                                ::
    ID: 07043001.wav
    Length: 230
** City dealing room, large crowded electronic office.                                                                                ::
    ID: 07042307.wav
    Length: 383
** London, early morning atmosphere with seagulls & distant street cleaning.                                                                                ::
    ID: 07042306.wav
    Length: 170
** Soho atmosphere, mainly pedestrian street with international voices.                                                                                ::
    ID: 07042305.wav
    Length: 248
** Leicester Square, evening atmosphere with roosting starlings and some voices.                                                                                ::
    ID: 07042304.wav
    Length: 241
** Pigeons rising.                                                                                ::
    ID: 07042303.wav
    Length: 6
** Pigeons feeding with distant traffic.                                                                                ::
    ID: 07042302.wav
    Length: 67
** London Zoo, interior of bird house with children.                                                                                ::
    ID: 07042301.wav
    Length: 267
** Westminster Cathedral atmosphere, with large tourist groups.                                                                                ::
    ID: 07042300.wav
    Length: 245
** Harrods Food Hall, with voices, cash tills & occasional meat slicer.                                                                                ::
    ID: 07042299.wav
    Length: 247
** Billingsgate Fish Market atmosphere.                                                                                ::
    ID: 07042298.wav
    Length: 262
** Thameside atmosphere, with lapping water & distant industry, river boat passing until 2m22s.                                                                                ::
    ID: 07042297.wav
    Length: 298
** Docklands Light Railway train, exterior, arrives, doors open & shuts, departs.                                                                                ::
    ID: 07042296.wav
    Length: 66
** Docklands Light Railway train, interior, constant run with station stops at 0m52s and 2m13s.                                                                                ::
    ID: 07042295.wav
    Length: 197
** Routemaster Double-Decker Bus, interior, buzzer rung once.                                                                                ::
    ID: 07042294.wav
    Length: 3
** Routemaster Double-Decker Bus, interior, bell rung twice.                                                                                ::
    ID: 07042293.wav
    Length: 3
** Routemaster Double-Decker Bus, interior, constant run on upper deck, buzzer pressed at 0m39s.                                                                                ::
    ID: 07042292.wav
    Length: 180
** Routemaster Double-Decker Bus, interior, constant run on lower deck, with bell rung once at 0m23s & twice at 1m47s.                                                                                ::
    ID: 07042291.wav
    Length: 145
** Routemaster Double-Decker Bus, exterior, arrives & departs.                                                                                ::
    ID: 07042290.wav
    Length: 37
** Austin Taxi, interior, constant run. (Austin Diesel Taxi Cab.)                                                                                ::
    ID: 07042289.wav
    Length: 219
** Austin Taxi, interior, tickover, door opens & shuts. (Austin Diesel Taxi Cab.)                                                                                ::
    ID: 07042288.wav
    Length: 27
** Austin Taxi, exterior, tickover. (Austin Diesel Taxi Cab.)                                                                                ::
    ID: 07042287.wav
    Length: 54
** Austin Taxi, exterior, arrives, door opens & shuts, departs. (Austin Diesel Taxi Cab.)                                                                                ::
    ID: 07042286.wav
    Length: 44
** Lloyds of London, Lutine bell rung once (for a total wreck).                                                                                ::
    ID: 07042285.wav
    Length: 9
** Lloyds of London, Lutine bell, rung twice (for an overdue ship).                                                                                ::
    ID: 07042284.wav
    Length: 12
** Big Ben ticking.                                                                                ::
    ID: 07042283.wav
    Length: 62
** Big Ben chiming & striking 1 o'clock.                                                                                ::
    ID: 07042282.wav
    Length: 37
** Big Ben chiming quarter to the hour.                                                                                ::
    ID: 07042281.wav
    Length: 24
** Big Ben chiming half past the hour.                                                                                ::
    ID: 07042280.wav
    Length: 20
** Big Ben chiming quarter past the hour.                                                                                ::
    ID: 07042279.wav
    Length: 21
** Big Ben chiming & striking 12 o'clock.                                                                                ::
    ID: 07042278.wav
    Length: 84
** Electric Sanding Machine operating.                                                                                ::
    ID: 07042277.wav
    Length: 49
** Electric Circular Saw operating.                                                                                ::
    ID: 07042276.wav
    Length: 12
** Electric Jigsaw operating.                                                                                ::
    ID: 07042275.wav
    Length: 29
** Hand Saw, sawing a piece of plywood.                                                                                ::
    ID: 07042274.wav
    Length: 36
** Electric Drill, series of holes drilled in quick succession.                                                                                ::
    ID: 07042273.wav
    Length: 20
** Electric Drill, single hole drilled.                                                                                ::
    ID: 07042272.wav
    Length: 10
** Hair dryer, starts, runs & stops.                                                                                ::
    ID: 07042271.wav
    Length: 90
** Bath emptied.                                                                                ::
    ID: 07042270.wav
    Length: 77
** Bath, someone having a bath.                                                                                ::
    ID: 07042269.wav
    Length: 208
** Bath filled.                                                                                ::
    ID: 07042268.wav
    Length: 177
** Wash-hand basin, running tap with plug not inserted.                                                                                ::
    ID: 07042267.wav
    Length: 93
** Wash-hand basin filled, hands washed & basin emptied.                                                                                ::
    ID: 07042266.wav
    Length: 78
** Toilet flushing.                                                                                ::
    ID: 07042265.wav
    Length: 87
** Vacuum cleaner.                                                                                ::
    ID: 07042264.wav
    Length: 85
** Microwave oven loaded, operated & emptied.                                                                                ::
    ID: 07042263.wav
    Length: 153
** Coffee grinder filled & operated.                                                                                ::
    ID: 07042262.wav
    Length: 43
** Three slices of wholemeal bread being sliced.                                                                                ::
    ID: 07042261.wav
    Length: 20
** Frying an egg.                                                                                ::
    ID: 07042260.wav
    Length: 77
** Can Opener, tin opened & contents emptied into a saucepan.                                                                                ::
    ID: 07042259.wav
    Length: 37
** Teapot filled with boiling water.                                                                                ::
    ID: 07042258.wav
    Length: 28
** Whistling kettle coming to the boil.                                                                                ::
    ID: 07042257.wav
    Length: 39
** Gas Stove, one ring lit, burns, turned off.                                                                                ::
    ID: 07042256.wav
    Length: 138
** Match being struck.                                                                                ::
    ID: 07042255.wav
    Length: 9
** Kettle filled with water.                                                                                ::
    ID: 07042254.wav
    Length: 17
** Tap dripping.                                                                                ::
    ID: 07042253.wav
    Length: 182
** Washing Up.                                                                                ::
    ID: 07042252.wav
    Length: 270
** Automatic Washing Machine, drain & spin (at 1m20s).                                                                                ::
    ID: 07042251.wav
    Length: 133
** Automatic Washing Machine, load, fill & wash.                                                                                ::
    ID: 07042250.wav
    Length: 240
** Refrigerator hum.                                                                                ::
    ID: 07042249.wav
    Length: 241
** Telephone, handset lifted & 9 digits keyed. (Push button telephone.)                                                                                ::
    ID: 07042248.wav
    Length: 9
** Telephone, handset lifted & 7 digits keyed. (Push button telephone.)                                                                                ::
    ID: 07042247.wav
    Length: 8
** Telephone, handset lifted & replaced. (Push button telephone.)                                                                                ::
    ID: 07042246.wav
    Length: 9
** Telephone, ring & handset lifted. (Push button telephone.)                                                                                ::
    ID: 07042245.wav
    Length: 11
** Telephone, constant ring. (Push button telephone.)                                                                                ::
    ID: 07042244.wav
    Length: 32
** Back door, interior, open & close.                                                                                ::
    ID: 07042243.wav
    Length: 15
** Front Door, interior, Yale lock unlocked, door open & close.                                                                                ::
    ID: 07042242.wav
    Length: 15
** Doorbell with Multi electric chimes rung. (Ding-dong note.)                                                                                ::
    ID: 07042241.wav
    Length: 10
** Doorbell with electric chime rung. (Ding-dong note.)                                                                                ::
    ID: 07042240.wav
    Length: 8
** Domestic alarm clock ticking.                                                                                ::
    ID: 07042239.wav
    Length: 286
** Domestic chiming clock ticking.                                                                                ::
    ID: 07042238.wav
    Length: 242
** Domestic chiming clock striking 6 o'clock.                                                                                ::
    ID: 07042237.wav
    Length: 47
** Domestic chiming clock striking 3 o'clock.                                                                                ::
    ID: 07042236.wav
    Length: 44
** Domestic chiming clock striking 1 o'clock.                                                                                ::
    ID: 07042235.wav
    Length: 39
** Domestic chiming clock striking 12 o'clock.                                                                                ::
    ID: 07042234.wav
    Length: 53
** Domestic chiming clock striking quarter to the hour.                                                                                ::
    ID: 07042233.wav
    Length: 34
** Domestic chiming clock striking half past the hour.                                                                                ::
    ID: 07042232.wav
    Length: 30
** Domestic chiming clock striking quarter past the hour.                                                                                ::
    ID: 07042231.wav
    Length: 30
** The End. (Legends Spot Effect.)                                                                                ::
    ID: 07042230.wav
    Length: 36
** Little people. (Legends Spot Effect.)                                                                                ::
    ID: 07042229.wav
    Length: 35
** Dragon burns its fingers. (Legends Spot Effect.)                                                                                ::
    ID: 07042228.wav
    Length: 61
** Winged monster flies away. (Legends Spot Effect.)                                                                                ::
    ID: 07042227.wav
    Length: 11
** Unicorn. (Legends Spot Effect.)                                                                                ::
    ID: 07042226.wav
    Length: 15
** Thunderbolt and thunderclap. (Legends Spot Effect.)                                                                                ::
    ID: 07042225.wav
    Length: 7
** Pendulum torture machine. (Horror Spot Effect.)                                                                                ::
    ID: 07042224.wav
    Length: 50
** Cackling hag. (Horror Spot Effect.)                                                                                ::
    ID: 07042223.wav
    Length: 44
** Whiplashes, four times. (Horror Spot Effect.)                                                                                ::
    ID: 07042222.wav
    Length: 8
** Branding iron. (Horror Spot Effect.)                                                                                ::
    ID: 07042221.wav
    Length: 33
** Streched on the rack. (Horror Spot Effect.)                                                                                ::
    ID: 07042220.wav
    Length: 38
** Space battle. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042219.wav
    Length: 97
** Cedric the CD Robot. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042218.wav
    Length: 50
** Beaming down. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042217.wav
    Length: 17
** Disintegrator machine strikes. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042216.wav
    Length: 6
** Laser gun. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042215.wav
    Length: 5
** Meteor passes. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042214.wav
    Length: 3
** Alien pods lands, sprouts four legs, walks off. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042213.wav
    Length: 47
** Alien pods land in swamp. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042212.wav
    Length: 49
** Flying saucer takes off. (Space Fantasy Spot Effect.)                                                                                ::
    ID: 07042211.wav
    Length: 13
** Jungle atmosphere. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042210.wav
    Length: 118
** Owl screech. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042209.wav
    Length: 15
** Owl hooting. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042208.wav
    Length: 16
** Duck. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042207.wav
    Length: 22
** Cat. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042206.wav
    Length: 17
** Cow. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042205.wav
    Length: 26
** Pig. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042204.wav
    Length: 37
** Sheep and lambs bleating. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042203.wav
    Length: 50
** Single lamb bleating. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042202.wav
    Length: 27
** Many horses trotting. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042201.wav
    Length: 61
** Person thrown from a horse. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042200.wav
    Length: 11
** Horse on cobbles. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042199.wav
    Length: 66
** Laughing horse. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042198.wav
    Length: 6
** Seychelles tortoises mating. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042197.wav
    Length: 27
** Footsteps in mud. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042196.wav
    Length: 122
** Exploding music machine. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042195.wav
    Length: 20
** Orgy. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042194.wav
    Length: 64
** Colliding ships. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042192.wav
    Length: 36
** Old jalopy. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042191.wav
    Length: 200
** Gibberish phone call. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042190.wav
    Length: 58
** Church organist. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042189.wav
    Length: 39
** Woman laughing. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042188.wav
    Length: 27
** Man laughing. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042187.wav
    Length: 19
** Dripping taps (musical). (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042186.wav
    Length: 61
** Wound up clock. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042185.wav
    Length: 39
** Bed bouncer. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042184.wav
    Length: 33
** Eating a fly. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042183.wav
    Length: 43
** Kettle blowing its top. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042182.wav
    Length: 66
** Cork twist & pop. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042181.wav
    Length: 3
** Cuckoo struck dumb. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042180.wav
    Length: 14
** Bull's eye & glass smash. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042179.wav
    Length: 4
** Twang, razz, pop. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042178.wav
    Length: 4
** Boing, honk, whiz. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042177.wav
    Length: 4
** Twang, boing, whistle. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042176.wav
    Length: 4
** Zeppelin bomb-drop mechanism. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042175.wav
    Length: 8
** Tearing fabric. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042174.wav
    Length: 4
** Tum punches (four times). (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042173.wav
    Length: 8
** Drooling and eyes popping. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042172.wav
    Length: 5
** Drinking from a bucket. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042171.wav
    Length: 16
** Coughing & spitting. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042170.wav
    Length: 14
** Kiss. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042169.wav
    Length: 5
** Hiccups. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042168.wav
    Length: 37
** Person snoring. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042167.wav
    Length: 44
** Gargle. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042166.wav
    Length: 12
** Person throwing up. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042165.wav
    Length: 6
** Short raspberry. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042164.wav
    Length: 2
** Long raspberry. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042163.wav
    Length: 3
** Single burp. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042162.wav
    Length: 2
** Custard pie. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042161.wav
    Length: 2
** Slurp. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042160.wav
    Length: 3
** Plunger. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042159.wav
    Length: 2
** Wooden twangs. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042158.wav
    Length: 7
** Metallic twang, with vibrato. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042157.wav
    Length: 7
** Metallic twang. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042156.wav
    Length: 2
** Vibra slap. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042155.wav
    Length: 3
** Horn sounded three times. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042154.wav
    Length: 3
** Horn sounded twice. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042153.wav
    Length: 7
** Three party whistles. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042152.wav
    Length: 5
** Party siren, long blow. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042151.wav
    Length: 7
** Party siren on reverb. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042150.wav
    Length: 5
** Party siren, short blow. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042149.wav
    Length: 4
** Swannee whistle, high pitched ascend & descend quickly. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042148.wav
    Length: 6
** Swannee Whistle, ascend & descend quickly. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042147.wav
    Length: 4
** Swannee Whistle, slowly ascending and descending. (Comedy Spot Effect.)                                                                                :Comedy:Spot Effect:
    ID: 07042146.wav
    Length: 8
** South American Jungle morning atmosphere.                                                                                ::
    ID: 07042145.wav
    Length: 271
** Asian Jungle night-time atmosphere.                                                                                ::
    ID: 07042144.wav
    Length: 209
** African Bush after sunset.                                                                                ::
    ID: 07042143.wav
    Length: 267
** Sound of an African Scops Owl.                                                                                ::
    ID: 07042142.wav
    Length: 189
** Red-Rumped Parakeet.                                                                                ::
    ID: 07042141.wav
    Length: 106
** Dusky Lory.                                                                                ::
    ID: 07042140.wav
    Length: 25
** Roseate Cockatoos.                                                                                ::
    ID: 07042139.wav
    Length: 46
** Flamingoes.                                                                                ::
    ID: 07042138.wav
    Length: 58
** Ne'en (Hawaiian Goose).                                                                                ::
    ID: 07042137.wav
    Length: 41
** Sound of Ruddy Shelduck.                                                                                ::
    ID: 07042136.wav
    Length: 12
** Garganey.                                                                                ::
    ID: 07042135.wav
    Length: 30
** Swan Geese calls.                                                                                ::
    ID: 07042134.wav
    Length: 86
** Winter Migrant Wildfowl, including Berwick Swans, Canada Geese, Tufted Duck, Pochard & Pintail.                                                                                ::
    ID: 07042133.wav
    Length: 142
** Coot. (Recorded on early winter morning with Geese & Mallard.)                                                                                ::
    ID: 07042132.wav
    Length: 18
** Moorhen.                                                                                ::
    ID: 07042131.wav
    Length: 6
** Robin singing.                                                                                ::
    ID: 07042130.wav
    Length: 86
** Donkey braying                                                                                ::
    ID: 07042129.wav
    Length: 11
** Herd of donkeys. (Recorded amidst herd.)                                                                                ::
    ID: 07042128.wav
    Length: 51
** Thirty donkeys passing in yard.                                                                                ::
    ID: 07042127.wav
    Length: 28
** Donkeys in shed braying & eating.                                                                                ::
    ID: 07042126.wav
    Length: 61
** Horse approaches snorting four times.                                                                                ::
    ID: 07042125.wav
    Length: 9
** Horse walks on muddy track.                                                                                ::
    ID: 07042124.wav
    Length: 64
** Horse canters past on muddy forest track.                                                                                ::
    ID: 07042123.wav
    Length: 15
** Horse walks on cobble stones.                                                                                ::
    ID: 07042122.wav
    Length: 122
** Horse approaches & stops on gravel.                                                                                ::
    ID: 07042121.wav
    Length: 20
** Horse passes on gravel from left to right.                                                                                ::
    ID: 07042120.wav
    Length: 21
** Horse walks away on gravel track.                                                                                ::
    ID: 07042119.wav
    Length: 17
** Chickens in yard.                                                                                ::
    ID: 07042118.wav
    Length: 61
** Cock crows three times.                                                                                ::
    ID: 07042117.wav
    Length: 11
** Hen cackling.                                                                                ::
    ID: 07042116.wav
    Length: 11
** Hen house atmosphere.                                                                                ::
    ID: 07042115.wav
    Length: 111
** Pigs in field.                                                                                ::
    ID: 07042114.wav
    Length: 120
** Pigs in shed. (with distant birds.)                                                                                ::
    ID: 07042113.wav
    Length: 121
** Three rams bleating in shed.                                                                                ::
    ID: 07042112.wav
    Length: 46
** Restless sheep in shed. (With distant birds.)                                                                                ::
    ID: 07042111.wav
    Length: 123
** Restless cattle in shed.                                                                                ::
    ID: 07042110.wav
    Length: 132
** Beagle drinking water. (Interior.)                                                                                ::
    ID: 07042109.wav
    Length: 66
** Labrador & two sheep dogs barking. (Exterior.)                                                                                ::
    ID: 07042108.wav
    Length: 42
** Beagle barking, whining & jumping up at a door. (Interior.)                                                                                ::
    ID: 07042107.wav
    Length: 151
** Collie dog barking. (Exterior.)                                                                                ::
    ID: 07042106.wav
    Length: 57
** Domestic cat howling & spitting.                                                                                ::
    ID: 07042105.wav
    Length: 112
** Persian cat eating & purring.                                                                                ::
    ID: 07042104.wav
    Length: 68
** Three cats eating & purring.                                                                                ::
    ID: 07042103.wav
    Length: 117
** Domestic cat squealing & purring.                                                                                ::
    ID: 07042102.wav
    Length: 90
** Persian cat miaowing.                                                                                ::
    ID: 07042101.wav
    Length: 59
** Domestic cat miaowing.                                                                                ::
    ID: 07042100.wav
    Length: 105
** Greenwich  Time Signal, post January 1st 1972.                                                                                ::
    ID: 07042099.wav
    Length: 6
** Greenwich Time Signal, pre-January 1st 1972.                                                                                ::
    ID: 07042098.wav
    Length: 6
** Automatic letter sorter, start, run & stop. (1975 onward.)                                                                                ::
    ID: 07042097.wav
    Length: 134
** Doublewidth press, start, run & stop.                                                                                ::
    ID: 07042096.wav
    Length: 247
** Goss Metroliner doublewidth web-offset press, plates being adjusted. (1980 onward.)                                                                                ::
    ID: 07042095.wav
    Length: 130
** Singlewidth web-offset press run. (1960 onward.)                                                                                ::
    ID: 07042094.wav
    Length: 120
** Cosser letterpress, start, run & stop. (1935 onward.)                                                                                ::
    ID: 07042093.wav
    Length: 122
** Crosser letterpress, cutters being adjusted. (1935 onward.)                                                                                ::
    ID: 07042092.wav
    Length: 95
** Linotype hall with proofing machines & metal cutters. (1930 onward.)                                                                                ::
    ID: 07042091.wav
    Length: 122
** Linotype Machine, operator's perspective. (1930 onward.)                                                                                ::
    ID: 07042090.wav
    Length: 106
** Large Collator Copier, start, run & stop. (1975 onward.)                                                                                ::
    ID: 07042089.wav
    Length: 151
** Small Photocopier, six copies made.                                                                                ::
    ID: 07042088.wav
    Length: 18
** Rex Stencil Duplicator run electrically.                                                                                ::
    ID: 07042087.wav
    Length: 63
** Rex Stencil Duplicator run by hand. (1960 onward.)                                                                                ::
    ID: 07042086.wav
    Length: 55
** Transtel teleprinters in news area.                                                                                ::
    ID: 07042085.wav
    Length: 119
** Olivetti Praxis 35 typewriter paragraph indent & type.                                                                                ::
    ID: 07042084.wav
    Length: 82
** Olivetti Praxis 35 typewriter switch on.                                                                                ::
    ID: 07042083.wav
    Length: 3
** Juki Daisywheel Printer switch on.                                                                                ::
    ID: 07042082.wav
    Length: 77
** Epson Dot-Matrix Printer, switch on & print.                                                                                ::
    ID: 07042081.wav
    Length: 28
** Amstrad Dot-Matrix Printer printing.                                                                                ::
    ID: 07042080.wav
    Length: 100
** Computer, two keystrokes & bleeps (signifying mistaken input).                                                                                ::
    ID: 07042079.wav
    Length: 2
** Computer disc drive operating.                                                                                ::
    ID: 07042078.wav
    Length: 13
** Computer, typing text.                                                                                ::
    ID: 07042077.wav
    Length: 121
** BT Telephone operators, Jackfield switchroom with 999 alarm audible occasionally. (1925 onward.)                                                                                ::
    ID: 07042076.wav
    Length: 120
** BT Strowger electromechanical exchange. (1922 onward.)                                                                                ::
    ID: 07042075.wav
    Length: 120
** BT Strowger callmaker & line-tester running.                                                                                ::
    ID: 07042074.wav
    Length: 120
** BT Crossbar electromechanical exchange. (1960 onward.)                                                                                ::
    ID: 07042073.wav
    Length: 120
** Dialling pulses from pushbutton phone.                                                                                ::
    ID: 07042072.wav
    Length: 14
** Number unobtainable signal.                                                                                ::
    ID: 07042071.wav
    Length: 31
** Equipment (system) engaged.                                                                                ::
    ID: 07042070.wav
    Length: 22
** Telephone engaged.                                                                                ::
    ID: 07042069.wav
    Length: 37
** Caller rings off on local line, with 35s dialling tone (usable separately).                                                                                ::
    ID: 07042068.wav
    Length: 45
** Called party rings off on STD line.                                                                                ::
    ID: 07042067.wav
    Length: 2
** Four STD rings, phone answered with 'pip'.                                                                                ::
    ID: 07042066.wav
    Length: 19
** Three STD rings, phone answered with 'pip'.                                                                                ::
    ID: 07042065.wav
    Length: 19
** PABX ringing tones, phone answered.                                                                                ::
    ID: 07042064.wav
    Length: 32
** BT ringing tones.                                                                                ::
    ID: 07042063.wav
    Length: 30
** BT local line noise.                                                                                ::
    ID: 07042062.wav
    Length: 60
** STD line noise with faint crosstalk.                                                                                ::
    ID: 07042061.wav
    Length: 61
** International telephone line noise with metering pulses.                                                                                ::
    ID: 07042060.wav
    Length: 62
** BT Pushbutton Payphone, pips heard when operator dialled or telephone box called from outside.                                                                                ::
    ID: 07042059.wav
    Length: 10
** BT Dial Payphone pips.                                                                                ::
    ID: 07042058.wav
    Length: 19
** BT Pushbutton Payphone, telephone ringing in callbox.                                                                                ::
    ID: 07042057.wav
    Length: 24
** BT Pushbutton Payphone, receiver replaced & coins returned.                                                                                ::
    ID: 07042056.wav
    Length: 7
** BT Pushbutton Payphone, money inserted & call made (9 digits).                                                                                ::
    ID: 07042055.wav
    Length: 14
** BT Dial Payphone, telephone ringing in callbox.                                                                                ::
    ID: 07042054.wav
    Length: 27
** BT Dial Payphone, receiver replaced heavily.                                                                                ::
    ID: 07042053.wav
    Length: 4
** BT Dial Payphone, receiver replaced normally.                                                                                ::
    ID: 07042052.wav
    Length: 4
** BT Dial Payphone, money inserted.                                                                                ::
    ID: 07042051.wav
    Length: 4
** BT Dial Payphone, call dialled (9 digits).                                                                                ::
    ID: 07042050.wav
    Length: 21
** BT Domestic Phone, Viscount model, 12 rings & pick-up.                                                                                ::
    ID: 07042049.wav
    Length: 39
** BT Domestic Phone, Statesman model, 10 rings & pick-up.                                                                                ::
    ID: 07042048.wav
    Length: 32
** Cockerels, two cocks crowing alternately, 2nd cock from a distance.                                                                                ::
    ID: 07042047.wav
    Length: 25
** Wren singing.                                                                                ::
    ID: 07042046.wav
    Length: 61
** Lesser Whitethroat singing.                                                                                ::
    ID: 07042045.wav
    Length: 84
** Whitethroat sining, with Willow Warbler in background.                                                                                ::
    ID: 07042044.wav
    Length: 71
** Willow Warbler singing, with distant cuckoo.                                                                                ::
    ID: 07042043.wav
    Length: 185
** Wheatear singing, with Sheep, Cuckoo & Willow Warbler in background.                                                                                ::
    ID: 07042042.wav
    Length: 180
** Coal Tits, two pairs displaying to each other on territorial boundary.                                                                                ::
    ID: 07042041.wav
    Length: 115
** Stonechat, singing, with Chaffinch & Skylarks in background.                                                                                ::
    ID: 07042040.wav
    Length: 165
** Skylark, song flight with occasional gusts of wind.                                                                                ::
    ID: 07042039.wav
    Length: 147
** Sedgewarbler singing.                                                                                ::
    ID: 07042038.wav
    Length: 180
** Rookery, nests with nestlings.                                                                                ::
    ID: 07042037.wav
    Length: 182
** Robin singing, with distant Sheep.                                                                                ::
    ID: 07042036.wav
    Length: 179
** Ring Ouzel singing, with song of second bird, Red Grouse & Cuckoo in background.                                                                                ::
    ID: 07042035.wav
    Length: 178
** Reedwarbler, song of unmated male with very distant cows. (Recorded approx. 1900 hrs.)                                                                                ::
    ID: 07042034.wav
    Length: 155
** Oystercatcher calls, with Skylark & heavy sea in background.                                                                                ::
    ID: 07042033.wav
    Length: 49
** Tawny Owl, hunting calls with chorus of dark bush-crickets.                                                                                ::
    ID: 07042032.wav
    Length: 131
** Nightingale singing.                                                                                ::
    ID: 07042031.wav
    Length: 123
** Linnet singing.                                                                                ::
    ID: 07042030.wav
    Length: 179
** Lapwing, female ground anxiety call with distant aeroplane.                                                                                ::
    ID: 07042029.wav
    Length: 67
** Housemartin, female calling at nest entrance.                                                                                ::
    ID: 07042028.wav
    Length: 148
** Common Gulls, calls of 10 pairs at breeding colony with lapping water.                                                                                ::
    ID: 07042027.wav
    Length: 126
** Chiffchaff singing, with distant Bullfinch, Wren & Sheep on slightly windy day.                                                                                ::
    ID: 07042026.wav
    Length: 158
** Chaffinch calling.                                                                                ::
    ID: 07042025.wav
    Length: 79
** Blackcap singing.                                                                                ::
    ID: 07042024.wav
    Length: 192
** Blackbird singing in quiet town garden, with dawn chorus & occasional distant car.                                                                                ::
    ID: 07042023.wav
    Length: 189
** Water Mill, interior, mill operating.                                                                                ::
    ID: 07042022.wav
    Length: 183
** Water Mill, exterior, water wheel turning.                                                                                ::
    ID: 07042021.wav
    Length: 183
** Grinding, beveling on a grinding wheel.                                                                                ::
    ID: 07042020.wav
    Length: 173
** Refuse Skip, rummaging in full skip with distant traffic.                                                                                ::
    ID: 07042019.wav
    Length: 39
** Refuse Skip, skip loaded on to lorry & removed, distant birds in background.                                                                                ::
    ID: 07042018.wav
    Length: 86
** Refuse Skip, approach and delivery of skip, distant birds in background.                                                                                ::
    ID: 07042017.wav
    Length: 108
** Stainless Steel Making, electric arc-welding shop.                                                                                ::
    ID: 07042016.wav
    Length: 189
** Stainless Steel Making, hot stainless plate mill.                                                                                ::
    ID: 07042015.wav
    Length: 133
** Stainless Steel Making, hot plate mill, contactor house with occasional distant voices.                                                                                ::
    ID: 07042014.wav
    Length: 184
** Stainless Steel Making, gas fired ladle pre-heater.                                                                                ::
    ID: 07042013.wav
    Length: 235
** Stainless Steel Making, slab grinding machine.                                                                                ::
    ID: 07042012.wav
    Length: 167
** China Factory, plate making.                                                                                ::
    ID: 07042011.wav
    Length: 188
** China Factory, checking the ware for faults, with voices in background.                                                                                ::
    ID: 07042010.wav
    Length: 135
** China Factory, vibrator cleaning the ware.                                                                                ::
    ID: 07042009.wav
    Length: 157
** Hattersley warping frame.                                                                                ::
    ID: 07042008.wav
    Length: 183
** Sulzer weaving loom.                                                                                ::
    ID: 07042007.wav
    Length: 184
** Mayer circular fleece-knitting machine.                                                                                ::
    ID: 07042006.wav
    Length: 151
** Milk Bottling Plant, bottle filling, bottles filled & capped.                                                                                ::
    ID: 07042005.wav
    Length: 127
** Milk Bottling Plant, bottle cleaning with empty bottles cleaned & moved on.                                                                                ::
    ID: 07042004.wav
    Length: 125
** Brewery, tun room with vessels being scrubbed out.                                                                                ::
    ID: 07042003.wav
    Length: 182
** Brewery, grist mill.                                                                                ::
    ID: 07042002.wav
    Length: 180
** Brewery, Jacobs ladder, with occasional distant voices.                                                                                ::
    ID: 07042001.wav
    Length: 184
** Cicadas stridulating.                                                                                :Cicadas:
    ID: 07041218.wav
    Length: 320
** Liquid fuel rocket motor.                                                                                :Rockets:Motors:
    ID: 07041217.wav
    Length: 54
** Solid fuel rocket motor.                                                                                :Rockets:Motors:
    ID: 07041216.wav
    Length: 10
** Solid fuel rocket motor.                                                                                :Rockets:Motors:
    ID: 07041215.wav
    Length: 6
** V1 Flying Bomb (Doodle Bug), approach & explosion.                                                                                :World War II:Flying Bombs:
    ID: 07041214.wav
    Length: 46
** V1 Flying Bomb (Doodle Bug), approach & explosion.                                                                                :World War II:Flying Bombs:
    ID: 07041213.wav
    Length: 46
** V1 Flying Bomb (Doodle Bug), approach & explosion.                                                                                :World War II:Flying Bombs:
    ID: 07041212.wav
    Length: 45
** V1 Flying Bomb (Doodle Bug), approach, engine cuts out, pause & explosion.                                                                                :World War II:Flying Bombs:
    ID: 07041211.wav
    Length: 43
** V1 Flying Bomb (Doodle Bug), seven in succession, each approach, engine cuts out, pause & explosion.                                                                                :World War II:Flying Bombs:
    ID: 07041210.wav
    Length: 258
** Junkers Ju 88, circling with four dives. (German World War II fighter/bomber, two piston engines.)                                                                                :Aircraft:Junkers:
    ID: 07041209.wav
    Length: 270
** Junkers Ju 88, start, warm up, switch off. (German World War II fighter/bomber, two piston engines.)                                                                                :Aircraft:Junkers:
    ID: 07041208.wav
    Length: 170
** Messerschmitt 110, in flight. (German World War II fighter, single piston engine.)                                                                                :Aircraft:Messerschmitt:
    ID: 07041207.wav
    Length: 57
** Messerschmitt 110, circling at 500 to 1000 feet with one dive. (German World War II fighter, single piston engine.)                                                                                :Aircraft:Messerschmitt:
    ID: 07041206.wav
    Length: 249
** Vickers Vanguard, exterior, two aircraft taxiing & stopping. (Short/medium-range airliner, four piston engines.)                                                                                :Aircraft:Piston-Engines:
    ID: 07041205.wav
    Length: 213
** Vickers Vanguard, interior, constant flight, Captain using P.A. system. (Short/medium-range airliner, four piston engines.)                                                                                :Aircraft:Piston-Engines:
    ID: 07041204.wav
    Length: 62
** Vickers Vanguard, interior, constant flight. (Short/medium-range airliner, four piston engines.)                                                                                :Aircraft:Piston-Engines:
    ID: 07041203.wav
    Length: 310
** Vickers Vanguard, interior, constant flight (to Rome), Captain describes view over P.A. system. (Short/medium-range airliner, four piston engines.)                                                                                :Aircraft:Piston-Engines:
    ID: 07041202.wav
    Length: 111
** Bristol Britannia, engines running. (Medium-range airliner, four piston engines.)                                                                                :Aircraft:Britannia:
    ID: 07041201.wav
    Length: 179
** Bristol Britannia, take off. (Medium-range airliner, four piston engines.)                                                                                :Aircraft:Britannia:
    ID: 07041200.wav
    Length: 56
** Four-engined aircraft, heavy landing.                                                                                :Aircraft:Piston-Engines:
    ID: 07041199.wav
    Length: 34
** Four-engined aircraft, landing.                                                                                :Aircraft:Piston-Engines:
    ID: 07041198.wav
    Length: 182
** Four-engined aircraft, emergency stop on take off.                                                                                :Aircraft:Piston-Engines:
    ID: 07041197.wav
    Length: 140
** Four-engined aircraft, heavy landing.                                                                                :Aircraft:Piston-Engines:
    ID: 07041196.wav
    Length: 75
** Footsteps, walking through leaves & undergrowth.                                                                                :Footsteps:Male:Undergrowth:
    ID: 07041195.wav
    Length: 92
** Footsteps, one pair of feet running in grass.                                                                                :Footsteps:Male:Undergrowth:
    ID: 07041194.wav
    Length: 43
** Footsteps, one pair of feet walking in grass.                                                                                :Footsteps:Male:Undergrowth:
    ID: 07041193.wav
    Length: 54
** Footsteps, one pair of feet running in shallow water.                                                                                :Footsteps:Water:
    ID: 07041192.wav
    Length: 35
** Footsteps, one pair of feet walking in shallow water.                                                                                :Footsteps:Water:
    ID: 07041191.wav
    Length: 110
** Footsteps, two pairs of feet running away on gravel.                                                                                :Footsteps:Male:Gravel:
    ID: 07041190.wav
    Length: 20
** Footsteps, one pair of feet running away on gravel.                                                                                :Footsteps:Male:Gravel:
    ID: 07041189.wav
    Length: 23
** Footsteps, two pairs of feet walking on gravel.                                                                                :Footsteps:Male:Gravel:
    ID: 07041188.wav
    Length: 47
** Footsteps, two pairs of feet walking on gravel.                                                                                :Footsteps:Male:Gravel:
    ID: 07041187.wav
    Length: 26
** Footsteps, one person running in mud.                                                                                :Footsteps:Mud:
    ID: 07041186.wav
    Length: 66
** Footsteps, two people walking in mud                                                                                :Footsteps:Mud:
    ID: 07041185.wav
    Length: 85
** Footsteps, one person walking in mud.                                                                                :Footsteps:Mud:
    ID: 07041184.wav
    Length: 103
** Footsteps, one person running in water.                                                                                :Footsteps:Water:
    ID: 07041183.wav
    Length: 60
** Footsteps, two people walking in water.                                                                                :Footsteps:Water:
    ID: 07041182.wav
    Length: 110
** Footsteps, one person walking in water.                                                                                :Footsteps:Water:
    ID: 07041181.wav
    Length: 101
** General purpose electrical radiation.                                                                                :Electronic Sounds:Radiation:
    ID: 07041180.wav
    Length: 153
** Television sound interference caused by car revving engine.                                                                                :Cars:
    ID: 07041179.wav
    Length: 69
** Television sound interference caused by stationary car.                                                                                :Cars:
    ID: 07041178.wav
    Length: 63
** Television sound interference caused by vacuum cleaner.                                                                                :Electronic Sounds:
    ID: 07041177.wav
    Length: 63
** Heavy line noise on Transatlantic circuit.                                                                                :Radio:Interference:
    ID: 07041176.wav
    Length: 79
** Electronic interference.                                                                                :Radio:Interference:
    ID: 07041175.wav
    Length: 26
** Radio interference.                                                                                :Radio:Interference:
    ID: 07041174.wav
    Length: 64
** Keyed Teleprinter radio signal.                                                                                :Telegraph Equipment:
    ID: 07041173.wav
    Length: 42
** Double Current Cable Code audio signal.                                                                                :Telegraph Equipment:
    ID: 07041172.wav
    Length: 50
** Morse Undualtor recoding.                                                                                :Morse Code:
    ID: 07041171.wav
    Length: 23
** Creed Machine operating (100 wpm.)                                                                                :Telegraph Equipment:
    ID: 07041170.wav
    Length: 40
** Morse Code background interference.                                                                                :Morse Code:
    ID: 07041169.wav
    Length: 33
** High Speed Morse (65 wpm.)                                                                                :Morse Code:
    ID: 07041168.wav
    Length: 66
** Wimshurst Machine operating.                                                                                :Electronic Sounds:Radiation:
    ID: 07041167.wav
    Length: 34
** Radio Interference. (Radiation)                                                                                :Electronic Sounds:Radiation:
    ID: 07041166.wav
    Length: 47
** Amplifier Noise.                                                                                :Amplifiers:
    ID: 07041165.wav
    Length: 52
** Amplifier Crackles.                                                                                :Amplifiers:
    ID: 07041164.wav
    Length: 63
** Geiger Counter operating.                                                                                :Electronic Sounds:Geiger Counters:
    ID: 07041163.wav
    Length: 182
** Simulated Lightning. (Spot Effect.)                                                                                :Electronic Sounds:Lightning:
    ID: 07041162.wav
    Length: 6
** Simulated Lightning. (Spot Effect.)                                                                                :Electronic Sounds:Lightning:
    ID: 07041161.wav
    Length: 6
** Simulated Lightning. (Spot Effect.)                                                                                :Electronic Sounds:Lightning:
    ID: 07041160.wav
    Length: 6
** Simulated Lightning. (Spot Effect.)                                                                                :Electronic Sounds:Lightning:
    ID: 07041159.wav
    Length: 6
** Simulated Lightning. (Spot Effect.)                                                                                :Electronic Sounds:Lightning:
    ID: 07041158.wav
    Length: 6
** Short Wave radio interference.                                                                                :Radio:Interference:
    ID: 07041157.wav
    Length: 185
** Short Wave radio interference.                                                                                :Radio:Interference:
    ID: 07041156.wav
    Length: 184
** Asdic, searching for target.                                                                                :Asdic:
    ID: 07041155.wav
    Length: 169
** Asdic echo at 1400 yards, approaching target.                                                                                :Asdic:
    ID: 07041154.wav
    Length: 94
** Asdic echo at 2000 yards.                                                                                :Asdic:
    ID: 07041153.wav
    Length: 77
** Suburban Station Atmosphere, electric multiple unit trains arrive, depart & pass.                                                                                :Trains:Stations:
    ID: 07041152.wav
    Length: 222
** Euston Station Concourse, atmosphere with footstep. (No announcements.)                                                                                :Trains:Stations:Euston:
    ID: 07041151.wav
    Length: 199
** Victoria Station, rush-hour atmosphere on concourse with close footsteps, occasional indistinct voices & distant train doors. (Wide perspective recording.)                                                                                :Trains:Stations:Victoria:
    ID: 07041150.wav
    Length: 200
** Victoria Station, rush-hour outside station, taxis & buses arrive & depart.                                                                                :Trains:Stations:Victoria:
    ID: 07041149.wav
    Length: 199
** Victoria Station Concourse, busy rush-hour crowd with close footsteps, occasional indistinct voices, distant train whistles. (Recorded in crowd, no announcements.)                                                                                :Trains:Stations:Victoria:
    ID: 07041148.wav
    Length: 397
** Victoria Station Concourse, busy rush-hour crowd with footsteps, occasional indistinct voices, distant train whistles. (Recorded above concourse, no announcements.)                                                                                :Trains:Stations:Victoria:
    ID: 07041147.wav
    Length: 394
** Inter-City 125. exterior, fast pass with horn. (British Rail High Speed Train, Diesel engine.)                                                                                :Trains:Diesel:
    ID: 07041141.wav
    Length: 21
** Inter-City 125, exterior, depart. (British Rail High Speed Train, Diesel engine.)                                                                                :Trains:Diesel:
    ID: 07041140.wav
    Length: 74
** Inter-City 125, exterior, approach, stop & tick over. (British Rail High Speed Train, Diesel engine.)                                                                                :Trains:Diesel:
    ID: 07041139.wav
    Length: 63
** Diesel Multiple Unit Train, interior, train slows, stops & tick over.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041138.wav
    Length: 63
** Diesel Multiple Unit Train, interior, buzzer sounds, train starts into constant run.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041137.wav
    Length: 293
** Diesel Multiple Unit Train, interior, tick over.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041136.wav
    Length: 117
** Diesel Multiple Unit Train, exterior, train departs.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041135.wav
    Length: 50
** Diesel Multiple Unit Train, exterior, train arrives & stops, platform atmosphere.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041134.wav
    Length: 58
** Diesel Multiple Unit Train, exterior, train arrives, stops & ticks over in station.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041133.wav
    Length: 43
** Diesel Train, exterior, carriage door open & close.                                                                                :Trains:Diesel:
    ID: 07041130.wav
    Length: 7
** Diesel Train, interior, compartment door open & close.                                                                                :Trains:Diesel:
    ID: 07041129.wav
    Length: 10
** Diesel Train, interior, doors as passengers disembark & board stationary train.                                                                                :Trains:Diesel:
    ID: 07041128.wav
    Length: 40
** Diesel Train, interior, deceleration from fast run to stop on unwelded track.                                                                                :Trains:Diesel:
    ID: 07041127.wav
    Length: 66
** Diesel Train, interior, guard's whistle, train starts & gathers speed on unwelded track. (Recorded in corridor.)                                                                                :Trains:Diesel:
    ID: 07041124.wav
    Length: 58
** Diesel Train, interior, train boarded. (Recorded in corridor.)                                                                                :Trains:Diesel:
    ID: 07041123.wav
    Length: 57
** Diesel Train, exterior, arrives in station & passengers board.                                                                                :Trains:Diesel:
    ID: 07041122.wav
    Length: 32
** Blaenau Festiniog Light Railway, Steam Train slows & stops.                                                                                :Trains:Steam:
    ID: 07041121.wav
    Length: 33
** Blaenau Festiniog Light Railway, Steam Train starts & runs.                                                                                :Trains:Steam:
    ID: 07041120.wav
    Length: 301
** Blaenau Festiniog Light Railway, Steam Train passes.                                                                                :Trains:Steam:
    ID: 07041119.wav
    Length: 37
** Blaenau Festiniog Light Railway, Steam Train starts & departs. (Recorded approximately 1 mile away.)                                                                                :Trains:Steam:
    ID: 07041118.wav
    Length: 131
** Blaenau Festiniog Light Railway, Steam Train passes through woodland with whistle.                                                                                :Trains:Steam:
    ID: 07041117.wav
    Length: 61
** Blaenau Ffestiniog Light Railway, Steam Train whistle, train departs.                                                                                :Trains:Steam:
    ID: 07041116.wav
    Length: 57
** Blaenau Ffestiniog Light Railway, Steam Train arrives & stops.                                                                                :Trains:Steam:
    ID: 07041115.wav
    Length: 35
** Diesel Multiple Unit Train medium pass R-L.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041114.wav
    Length: 40
** Diesel Multiple Unit Train medium pass R-L.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041113.wav
    Length: 60
** Diesel Multiple Unit Train fast pass L-R.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041112.wav
    Length: 20
** Diesel Multiple Unit Train medium pass R-L.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041111.wav
    Length: 49
** Diesel Multiple Unit Trains, medium pass R-L, fast pass R-L, slow pass L-R, fast pass L-R.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041110.wav
    Length: 159
** Diesel Multiple Unit Train medium pass R-L, DMU slow pass L-R.                                                                                :Trains:Diesel Multiple Units:
    ID: 07041109.wav
    Length: 49
** Electric Multiple Unit Trains pass R-L & L-R.                                                                                 :Trains:Electric Multiple Units:
    ID: 07041108.wav
    Length: 54
** Electric Multiple Unit Train passes L-R.                                                                                :Trains:Electric Multiple Units:
    ID: 07041107.wav
    Length: 68
** Electric Multiple Unit Train fast pass R-L.                                                                                :Trains:Electric Multiple Units:
    ID: 07041106.wav
    Length: 45
** Steam Train slow pass R-L. (King George V Steam Locomotive.)                                                                                :Trains:Steam:
    ID: 07041105.wav
    Length: 104
** Steam Train fast pass L-R. (King George V Steam Locomotive.)                                                                                :Trains:Steam:
    ID: 07041104.wav
    Length: 59
** Steam Train fast pass L-R. (King George V Steam Locomotive.)                                                                                :Trains:Steam:
    ID: 07041103.wav
    Length: 53
** Steam engine shunting in goods yard (steam express passes at 4m50s).                                                                                :Trains:Goods Yards:
    ID: 07041102.wav
    Length: 382
** Diesel train shunting in a goods yard.                                                                                :Trains:Diesel:
    ID: 07041101.wav
    Length: 330
** Euston Station,  Train arrives, doors slam as passengers alight & embark.                                                                                :Trains:Stations:Euston:
    ID: 07041100.wav
    Length: 189
