** Warning siren sounded at space rocket site.                                                                                ::
    ID: 07038026.wav
    Length: 19
** NASA Saturn V Project, exterior, test rig atmosphere.                                                                                ::
    ID: 07038025.wav
    Length: 90
** NASA Apollo Project, interior, hangar atmosphere.                                                                                ::
    ID: 07038024.wav
    Length: 73
** NASA Space Ship Launch, verbal checking prior to launch.                                                                                ::
    ID: 07038023.wav
    Length: 112
** NASA Space Ship Launch, space ship engine running.                                                                                ::
    ID: 07038022.wav
    Length: 33
** NASA Space Ship Launch, warning signal & launch, with engine background.                                                                                ::
    ID: 07038021.wav
    Length: 83
** NASA Space Ship Launch, launch.                                                                                ::
    ID: 07038020.wav
    Length: 58
** NASA Space Ship Launch, countdown.                                                                                ::
    ID: 07038019.wav
    Length: 17
** Sonic Boom, single distant boom as English Electric Lightning passes through sound barrier. (Jet fighter, c. 1967.)                                                                                ::
    ID: 07038018.wav
    Length: 13
** Sonic Boom, single distant boom as English Electric Lightning passes through sound barrier. (Jet fighter, c. 1967.)                                                                                ::
    ID: 07038017.wav
    Length: 18
** Sonic Boom, double boom as English Electric Lightning passes through sound barrier. (Jet fighter, c. 1967.)                                                                                ::
    ID: 07038016.wav
    Length: 12
** Sonic Boom, single boom as English Electric Lightning passes through sound barrier. (Jet fighter, c. 1967.)                                                                                ::
    ID: 07038015.wav
    Length: 10
** Sonic Boom, Hawker Hunter passing through sound barrier on power drive. (Jet fighter, c. 1952.)                                                                                ::
    ID: 07038014.wav
    Length: 17
** Sonic Boom, Hawker Hunter passing through sound barrier on power drive. (Jet fighter, c. 1952.)                                                                                ::
    ID: 07038013.wav
    Length: 17
** Sputnik 1 Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038012.wav
    Length: 48
** Explorer 10 Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038011.wav
    Length: 55
** OSO Satellite, telemetry effects from satellite. (Orbiting Solar Observations satellite.)                                                                                ::
    ID: 07038010.wav
    Length: 49
** IMP Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038009.wav
    Length: 54
** Mariner 2 Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038008.wav
    Length: 47
** Explorer 12 Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038007.wav
    Length: 50
** Alouette Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038006.wav
    Length: 46
** Relay Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038005.wav
    Length: 52
** Telstar Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038004.wav
    Length: 50
** Vanguard 3 Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038003.wav
    Length: 48
** Vanguard 1 Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038002.wav
    Length: 49
** Ariel Satellite, telemetry effects from satellite.                                                                                ::
    ID: 07038001.wav
    Length: 50
** Fourteen cwt. bell ringing.                                                                                ::
    ID: 07037657.wav
    Length: 144
** Six cwt. bell ringing.                                                                                ::
    ID: 07037656.wav
    Length: 146
** Bells ringing at San Sabino, Rome.                                                                                 ::
    ID: 07037655.wav
    Length: 44
** Bells ringing at San Giovanni Church, Laterno (Rome).                                                                                 ::
    ID: 07037654.wav
    Length: 64
** Bells ringing at Santa Agnese Church, Rome.                                                                                ::
    ID: 07037653.wav
    Length: 65
** Bells ringing at San Petronio Church, Bologna.                                                                                ::
    ID: 07037652.wav
    Length: 70
** Basutoland, mission bell sounded. (Basutoland renamed Lesotho.)                                                                                ::
    ID: 07037651.wav
    Length: 81
** Goat bells ringing.                                                                                ::
    ID: 07037650.wav
    Length: 72
** Bells ringing at Lavenham Church, Suffolk.                                                                                ::
    ID: 07037649.wav
    Length: 251
** Handbells sounded.                                                                                 ::
    ID: 07037648.wav
    Length: 75
** Monastery handbell sounded.                                                                                 ::
    ID: 07037647.wav
    Length: 71
** Bells at an Indian Temple sounded.                                                                                ::
    ID: 07037646.wav
    Length: 79
** Bells ringing at St Francis Church, Valetta.                                                                                ::
    ID: 07037645.wav
    Length: 112
** Bells ringing at Nidaros Cathedral.                                                                                ::
    ID: 07037644.wav
    Length: 64
** Bells ringing at Bergen Cathedral.                                                                                ::
    ID: 07037643.wav
    Length: 50
** Steel door opened & closed.                                                                                ::
    ID: 07037642.wav
    Length: 18
** Steel door opened & closed.                                                                                ::
    ID: 07037641.wav
    Length: 18
** Steel door closed.                                                                                ::
    ID: 07037640.wav
    Length: 11
** Steel door opened.                                                                                ::
    ID: 07037639.wav
    Length: 14
** Steel door closed.                                                                                ::
    ID: 07037638.wav
    Length: 9
** Steel door closed.                                                                                ::
    ID: 07037637.wav
    Length: 11
** Steel door opened.                                                                                ::
    ID: 07037636.wav
    Length: 11
** Steel door opened & closed.                                                                                ::
    ID: 07037635.wav
    Length: 18
** Cupboard door opened & closed.                                                                                ::
    ID: 07037634.wav
    Length: 12
** Cupboard door opened & closed.                                                                                ::
    ID: 07037633.wav
    Length: 14
** Door opened & closed.                                                                                ::
    ID: 07037632.wav
    Length: 12
** Door opened & closed.                                                                                ::
    ID: 07037631.wav
    Length: 17
** Door opened & closed.                                                                                ::
    ID: 07037630.wav
    Length: 13
** Pair of swing doors.                                                                                ::
    ID: 07037629.wav
    Length: 66
** Steel door closed.                                                                                ::
    ID: 07037628.wav
    Length: 10
** Steel door opened.                                                                                ::
    ID: 07037627.wav
    Length: 10
** Steel door on ship opened & closed.                                                                                ::
    ID: 07037626.wav
    Length: 14
** Iron gate opened & closed.                                                                                ::
    ID: 07037625.wav
    Length: 14
** Iron gate opened & closed.                                                                                ::
    ID: 07037624.wav
    Length: 13
** Iron gate opened & closed.                                                                                ::
    ID: 07037623.wav
    Length: 13
** Door slams.                                                                                ::
    ID: 07037622.wav
    Length: 8
** Door slams.                                                                                ::
    ID: 07037621.wav
    Length: 10
** Door shuts with rattle.                                                                                ::
    ID: 07037620.wav
    Length: 10
** Door shuts.                                                                                ::
    ID: 07037619.wav
    Length: 11
** Door shuts.                                                                                ::
    ID: 07037618.wav
    Length: 11
** Door opens & shuts.                                                                                ::
    ID: 07037617.wav
    Length: 16
** Door opens & shuts.                                                                                ::
    ID: 07037616.wav
    Length: 16
** Door shuts.                                                                                ::
    ID: 07037615.wav
    Length: 12
** Door, latch lifted & door opens with squeak.                                                                                ::
    ID: 07037614.wav
    Length: 15
** Door shuts with squeak.                                                                                ::
    ID: 07037613.wav
    Length: 8
** Door opens with squeak.                                                                                ::
    ID: 07037612.wav
    Length: 9
** Door shuts.                                                                                ::
    ID: 07037611.wav
    Length: 7
** Door shuts with squeak.                                                                                ::
    ID: 07037610.wav
    Length: 10
** Door shuts.                                                                                ::
    ID: 07037609.wav
    Length: 10
** Heavy door shuts, with reverberation.                                                                                ::
    ID: 07037608.wav
    Length: 11
** Heavy door shuts, with reverberation.                                                                                ::
    ID: 07037607.wav
    Length: 16
** Heavy door unbolted & opened  with reverberation.                                                                                ::
    ID: 07037606.wav
    Length: 15
** Heavy door opens & shuts, with reverberation.                                                                                ::
    ID: 07037605.wav
    Length: 15
** Heavy door unbolted with reverberation.                                                                                ::
    ID: 07037604.wav
    Length: 15
** Heavy door unbolted & opened  with reverberation.                                                                                ::
    ID: 07037603.wav
    Length: 12
** Heavy door opens & shuts, with reverberation.                                                                                ::
    ID: 07037602.wav
    Length: 12
** Heavy door opens & shuts, with reverberation.                                                                                ::
    ID: 07037601.wav
    Length: 16
** Heavy door opens & shuts, with reverberation.                                                                                ::
    ID: 07037600.wav
    Length: 18
** Heavy door opens & shuts, with reverberation.                                                                                ::
    ID: 07037599.wav
    Length: 15
** Heavy door opens & shuts, with reverberation.                                                                                ::
    ID: 07037598.wav
    Length: 16
** Heavy door shuts, with reverberation.                                                                                ::
    ID: 07037597.wav
    Length: 10
** Door, interior, opened & shut with reverberation.                                                                                ::
    ID: 07037596.wav
    Length: 9
** Door, interior, opened & shut with reverberation.                                                                                ::
    ID: 07037595.wav
    Length: 14
** Door, interior, opened & shut with reverberation.                                                                                ::
    ID: 07037594.wav
    Length: 10
** Door, interior, opened & shut with reverberation.                                                                                ::
    ID: 07037593.wav
    Length: 11
** Door, interior, opened & shut with reverberation.                                                                                ::
    ID: 07037592.wav
    Length: 13
** Door, interior, opened & shut with reverberation.                                                                                ::
    ID: 07037591.wav
    Length: 18
** Door, interior, opened & shut with reverberation.                                                                                ::
    ID: 07037590.wav
    Length: 12
** Door, interior, opened & shut.                                                                                ::
    ID: 07037589.wav
    Length: 9
** Door, interior, opened & shut.                                                                                ::
    ID: 07037588.wav
    Length: 11
** Door, interior, opened & shut.                                                                                ::
    ID: 07037587.wav
    Length: 12
** Door, interior, opened & shut.                                                                                ::
    ID: 07037586.wav
    Length: 8
** Door, interior, opened & shut.                                                                                ::
    ID: 07037585.wav
    Length: 10
** Door, interior, opened & shut.                                                                                ::
    ID: 07037584.wav
    Length: 10
** Door, interior, opened & shut.                                                                                ::
    ID: 07037583.wav
    Length: 9
** Door, interior, opened & shut.                                                                                ::
    ID: 07037582.wav
    Length: 9
** Sliding door opened & shut.                                                                                ::
    ID: 07037581.wav
    Length: 13
** Sliding door shut.                                                                                ::
    ID: 07037580.wav
    Length: 9
** Sliding door opened & shut.                                                                                ::
    ID: 07037579.wav
    Length: 14
** Exterior gate slamming.                                                                                ::
    ID: 07037578.wav
    Length: 8
** Sliding door opened & shut.                                                                                ::
    ID: 07037577.wav
    Length: 12
** French telephone kiosk door opened & shut.                                                                                ::
    ID: 07037576.wav
    Length: 10
** Door, interior, opened & shut.                                                                                ::
    ID: 07037575.wav
    Length: 11
** Door, interior, opened & shut.                                                                                ::
    ID: 07037574.wav
    Length: 11
** Door, interior, shut.                                                                                ::
    ID: 07037573.wav
    Length: 8
** Door, interior, opened & shut noisily.                                                                                ::
    ID: 07037572.wav
    Length: 12
** Door, interior, opened & shut.                                                                                ::
    ID: 07037571.wav
    Length: 11
** Door, interior, opened & shut.                                                                                ::
    ID: 07037570.wav
    Length: 12
** Door, interior, opened & shut.                                                                                ::
    ID: 07037569.wav
    Length: 13
** Door, interior, shut.                                                                                ::
    ID: 07037568.wav
    Length: 10
** Ten urgent knocks on a door.                                                                                ::
    ID: 07037567.wav
    Length: 8
** Six urgent knocks on a door.                                                                                ::
    ID: 07037566.wav
    Length: 8
** Door, interior, opened & shut.                                                                                ::
    ID: 07037565.wav
    Length: 9
** Three discreet knocks on a door.                                                                                ::
    ID: 07037564.wav
    Length: 7
** Door, interior, opened & slammed.                                                                                ::
    ID: 07037563.wav
    Length: 10
** Door, interior, opened & shut.                                                                                ::
    ID: 07037562.wav
    Length: 12
** Door, interior, opened & shut.                                                                                ::
    ID: 07037561.wav
    Length: 12
** Door, interior, opened & shut.                                                                                ::
    ID: 07037560.wav
    Length: 11
** Door, interior, opened & slammed.                                                                                ::
    ID: 07037559.wav
    Length: 10
** Door, interior, opened & shut.                                                                                ::
    ID: 07037558.wav
    Length: 11
** Door creak.                                                                                ::
    ID: 07037557.wav
    Length: 7
** Door creak.                                                                                ::
    ID: 07037556.wav
    Length: 7
** Door creak.                                                                                ::
    ID: 07037555.wav
    Length: 15
** Door creak.                                                                                ::
    ID: 07037554.wav
    Length: 15
** Door creak.                                                                                ::
    ID: 07037553.wav
    Length: 9
** Door creak.                                                                                ::
    ID: 07037552.wav
    Length: 10
** Door creak.                                                                                ::
    ID: 07037551.wav
    Length: 6
** Heavy door, interior, shut. (Distant perspective recording.)                                                                                ::
    ID: 07037550.wav
    Length: 8
** Small iron gate shut.                                                                                ::
    ID: 07037549.wav
    Length: 10
** Garage doors closing.                                                                                ::
    ID: 07037548.wav
    Length: 22
** Garage doors opening.                                                                                ::
    ID: 07037547.wav
    Length: 20
** Door key in door, opened, feet wiped, door shut.                                                                                ::
    ID: 07037546.wav
    Length: 22
** Door being shut.                                                                                ::
    ID: 07037545.wav
    Length: 7
** Door being shut.                                                                                ::
    ID: 07037544.wav
    Length: 7
** Door knocker banged twice.                                                                                ::
    ID: 07037543.wav
    Length: 7
** Door being shut.                                                                                ::
    ID: 07037542.wav
    Length: 7
** Door knocked on twice.                                                                                ::
    ID: 07037541.wav
    Length: 6
** Door opened & shut.                                                                                ::
    ID: 07037540.wav
    Length: 12
** Door knocked on twice.                                                                                ::
    ID: 07037539.wav
    Length: 5
** Door knocker banged three times.                                                                                ::
    ID: 07037538.wav
    Length: 7
** Door knocked on twice.                                                                                ::
    ID: 07037537.wav
    Length: 7
** Railway carriage window lowered & raised three times.                                                                                ::
    ID: 07037536.wav
    Length: 35
** Railway carriage window lowered, door opened & shut, window raised.                                                                                ::
    ID: 07037535.wav
    Length: 20
** Railway carriage window lowered & raised four times.                                                                                ::
    ID: 07037534.wav
    Length: 36
** Dividing door in railway carriage door opened & shut.                                                                                ::
    ID: 07037533.wav
    Length: 20
** Railway carriage door opened & slammed.                                                                                ::
    ID: 07037532.wav
    Length: 13
** Railway carriage door opened & shut three times.                                                                                ::
    ID: 07037531.wav
    Length: 26
** Sliding gates into guard's van opened & shut twice.                                                                                ::
    ID: 07037530.wav
    Length: 17
** Sliding door in railway carriage opened & shut twice.                                                                                ::
    ID: 07037529.wav
    Length: 18
** Railway carriage window lowered & raised three times.                                                                                ::
    ID: 07037528.wav
    Length: 27
** Railway carriage door opened & slammed.                                                                                ::
    ID: 07037527.wav
    Length: 11
** Sliding door between compartments in railway carriage opened & shut three times.                                                                                ::
    ID: 07037526.wav
    Length: 25
** Sliding corridor door in railway carriage opened & shut three times.                                                                                ::
    ID: 07037525.wav
    Length: 30
** Door creaking.                                                                                ::
    ID: 07037524.wav
    Length: 105
** Door creaking.                                                                                ::
    ID: 07037523.wav
    Length: 61
** Door creaking.                                                                                ::
    ID: 07037522.wav
    Length: 39
** Sash window opened & shut.                                                                                ::
    ID: 07037521.wav
    Length: 36
** Sash window opened & shut.                                                                                ::
    ID: 07037520.wav
    Length: 43
** Door squeaks.                                                                                ::
    ID: 07037519.wav
    Length: 25
** Door creaks open & shut twice.                                                                                ::
    ID: 07037518.wav
    Length: 77
** Heavy door opened & shut.                                                                                ::
    ID: 07037517.wav
    Length: 21
** Heavy door with lock & bolts opened & shut.                                                                                ::
    ID: 07037516.wav
    Length: 18
** Prison doors opened & closed, with keys jangling.                                                                                ::
    ID: 07037515.wav
    Length: 52
** Creaking door closed.                                                                                ::
    ID: 07037514.wav
    Length: 21
** Creaking door closed.                                                                                ::
    ID: 07037513.wav
    Length: 16
** Metal door closed twice.                                                                                ::
    ID: 07037512.wav
    Length: 20
** Metal door closed with a clang twice.                                                                                ::
    ID: 07037511.wav
    Length: 22
** Noisy door opened & closed.                                                                                ::
    ID: 07037510.wav
    Length: 25
** Noisy door opened & closed.                                                                                ::
    ID: 07037509.wav
    Length: 18
** Door unlocked & locked.                                                                                ::
    ID: 07037508.wav
    Length: 19
** Door, key & handle turned, door opened & reverse.                                                                                ::
    ID: 07037507.wav
    Length: 27
** Creaking door.                                                                                ::
    ID: 07037506.wav
    Length: 15
** Creaking door in wind.                                                                                ::
    ID: 07037505.wav
    Length: 39
** Clatter & creak of signs.                                                                                ::
    ID: 07037504.wav
    Length: 56
** Hampshire Farm, early morning atmosphere.                                                                                ::
    ID: 07037503.wav
    Length: 230
** Motorcycle starts & departs.                                                                                ::
    ID: 07037502.wav
    Length: 23
** Pigeon, landing with flap of wings.                                                                                ::
    ID: 07037501.wav
    Length: 15
** Pigeons, flapping of wings with human whistles.                                                                                ::
    ID: 07037500.wav
    Length: 16
** Pigeons, flapping of wings with rifle shots.                                                                                ::
    ID: 07037499.wav
    Length: 20
** Pigeons, flapping of wings.                                                                                ::
    ID: 07037498.wav
    Length: 11
** World War II, unidentified aircraft swooping with gunfire.                                                                                ::
    ID: 07037497.wav
    Length: 42
** Pigeons cooing. (Close perspective recording.)                                                                                ::
    ID: 07037496.wav
    Length: 17
** Pigeon loft, door opens & closes, footsteps on wooden floor of loft.                                                                                ::
    ID: 07037495.wav
    Length: 19
** Pigeon loft, general atmosphere with wings flapping..                                                                                ::
    ID: 07037494.wav
    Length: 41
** Pigeons cooing.                                                                                ::
    ID: 07037493.wav
    Length: 49
** Pigeons actuality.                                                                                ::
    ID: 07037492.wav
    Length: 30
** Owl imitation.                                                                                ::
    ID: 07037491.wav
    Length: 58
** Dog barking.                                                                                ::
    ID: 07037490.wav
    Length: 102
** Dog barking.                                                                                ::
    ID: 07037489.wav
    Length: 32
** Cairn Terrier, yelp & howls.                                                                                ::
    ID: 07037488.wav
    Length: 10
** Cairn Terrier yelping, whining & barking.                                                                                ::
    ID: 07037487.wav
    Length: 106
** Cairn Terrier barking & yelping.                                                                                ::
    ID: 07037486.wav
    Length: 89
** Dogs, angry snarls & barks.                                                                                ::
    ID: 07037485.wav
    Length: 14
** Dog, anxious barking with whines.                                                                                ::
    ID: 07037484.wav
    Length: 79
** Springer Spaniel, distant barking, approaches.                                                                                ::
    ID: 07037483.wav
    Length: 34
** Springer Spaniel barking, growling & panting.                                                                                ::
    ID: 07037482.wav
    Length: 69
** Springer Spaniel barking & panting.                                                                                ::
    ID: 07037481.wav
    Length: 74
** Mongrel Terrier barking.                                                                                ::
    ID: 07037480.wav
    Length: 189
** Irish Wolfhound barking.                                                                                ::
    ID: 07037479.wav
    Length: 80
** Irish Wolfhound, howling, barking & whining.                                                                                ::
    ID: 07037478.wav
    Length: 180
** Knock on door, dog barks, door closed.                                                                                ::
    ID: 07037477.wav
    Length: 21
** Dog barks as door opened & closed.                                                                                ::
    ID: 07037476.wav
    Length: 15
** Dog, distant barking.                                                                                ::
    ID: 07037475.wav
    Length: 28
** Dog, distant barking.                                                                                ::
    ID: 07037474.wav
    Length: 35
** Dog, angry barking & growls.                                                                                ::
    ID: 07037473.wav
    Length: 127
** Dog, angry snapping & growls, with a few barks.                                                                                ::
    ID: 07037472.wav
    Length: 61
** Spaniel, angry snarling.                                                                                ::
    ID: 07037471.wav
    Length: 96
** Springer Spaniel, angry snarling.                                                                                ::
    ID: 07037470.wav
    Length: 90
** Golden Retriever barking & whining.                                                                                ::
    ID: 07037469.wav
    Length: 87
** Golden Retriever growling.                                                                                ::
    ID: 07037468.wav
    Length: 71
** Golden Retriever growling.                                                                                ::
    ID: 07037467.wav
    Length: 89
** Maltese Terriers, two barking in distance.                                                                                ::
    ID: 07037466.wav
    Length: 36
** Maltese Terrier barking.                                                                                ::
    ID: 07037465.wav
    Length: 10
** Maltese Terrier barking.                                                                                ::
    ID: 07037464.wav
    Length: 9
** Maltese Terriers, two yapping & fighting.                                                                                ::
    ID: 07037463.wav
    Length: 51
** Airedale barks once.                                                                                ::
    ID: 07037462.wav
    Length: 8
** Airedale barking angrily.                                                                                ::
    ID: 07037461.wav
    Length: 14
** Airedale panting excitedly.                                                                                ::
    ID: 07037460.wav
    Length: 14
** Airedale barking.                                                                                ::
    ID: 07037459.wav
    Length: 11
** Airedale barking.                                                                                ::
    ID: 07037458.wav
    Length: 13
** Huskies fighting.                                                                                ::
    ID: 07037457.wav
    Length: 35
** Huskies barking & panting.                                                                                ::
    ID: 07037456.wav
    Length: 68
** West Highland Terrier barking. (Recorded outdoors.)                                                                                ::
    ID: 07037455.wav
    Length: 69
** West Highland Terrier barking. (Recorded indoors.)                                                                                ::
    ID: 07037454.wav
    Length: 62
** Horse whinnying.                                                                                ::
    ID: 07037453.wav
    Length: 54
** Sheep, single lamb.                                                                                ::
    ID: 07037452.wav
    Length: 57
** Sheep, ewe & two lambs.                                                                                ::
    ID: 07037451.wav
    Length: 54
** Sheep, ewe & lamb.                                                                                ::
    ID: 07037450.wav
    Length: 55
** Opossum, sound made by opossum.                                                                                ::
    ID: 07037449.wav
    Length: 57
** Dogs barking. (Breed unknown.)                                                                                ::
    ID: 07037448.wav
    Length: 53
** Reindeer Ride, with bells, orders shouted & dogs barking.                                                                                ::
    ID: 07037447.wav
    Length: 111
** Rats scampering & scraping.                                                                                ::
    ID: 07037446.wav
    Length: 68
** Rats squeaking.                                                                                ::
    ID: 07037445.wav
    Length: 64
** Dragon's footsteps. (Specially created effect.)                                                                                ::
    ID: 07037444.wav
    Length: 76
** Dragon roaring. (Specially created effect.)                                                                                ::
    ID: 07037443.wav
    Length: 35
** Horses, one year old foal calling to companion.                                                                                ::
    ID: 07037442.wav
    Length: 132
** Horses, one year old foal calling to companion.                                                                                ::
    ID: 07037441.wav
    Length: 122
** Sheep, flock on Hampshire Downs.                                                                                ::
    ID: 07037440.wav
    Length: 240
** Sheep, flock on Hampshire Downs.                                                                                ::
    ID: 07037439.wav
    Length: 249
** Collie barking.                                                                                ::
    ID: 07037438.wav
    Length: 27
** Dog lapping water. (Breed unknown.)                                                                                ::
    ID: 07037437.wav
    Length: 34
** Dog fight. (Breed unknown.)                                                                                ::
    ID: 07037436.wav
    Length: 30
** Puppy whining & barking. (Breed unknown.)                                                                                ::
    ID: 07037435.wav
    Length: 28
** Bulldog barking.                                                                                ::
    ID: 07037434.wav
    Length: 48
** Sleigh running over frozen road.                                                                                ::
    ID: 07037433.wav
    Length: 164
** Bicycle, approach & fall over on gravel.                                                                                ::
    ID: 07037432.wav
    Length: 11
** Bicycle, approach & fall over on gravel.                                                                                ::
    ID: 07037431.wav
    Length: 15
** Bicycle, passing on gravel with bell.                                                                                ::
    ID: 07037430.wav
    Length: 13
** Bicycles, several passing on gravel with bells.                                                                                ::
    ID: 07037429.wav
    Length: 18
** Bicycle Bells, two bells ringing followed by several.                                                                                ::
    ID: 07037428.wav
    Length: 16
** Bicycle Bells, several ringing.                                                                                ::
    ID: 07037427.wav
    Length: 12
** Bicycle Bell ringing.                                                                                ::
    ID: 07037426.wav
    Length: 17
** Bicycle Bell ringing.                                                                                ::
    ID: 07037425.wav
    Length: 21
** Bicycle Bell ringing.                                                                                ::
    ID: 07037424.wav
    Length: 13
** Bicycle Bell ringing.                                                                                ::
    ID: 07037423.wav
    Length: 18
** Bicycle Bell ringing.                                                                                ::
    ID: 07037422.wav
    Length: 14
** Washing Line, very wet heavy washing flapping on line.                                                                                ::
    ID: 07037421.wav
    Length: 258
** Footsteps scrambling & slipping in loose dirt.                                                                                ::
    ID: 07037420.wav
    Length: 66
** Loose dirt falling.                                                                                ::
    ID: 07037419.wav
    Length: 48
** Loose dirt falling.                                                                                ::
    ID: 07037418.wav
    Length: 11
** Loose stones falling.                                                                                ::
    ID: 07037417.wav
    Length: 10
** Loose stones falling.                                                                                ::
    ID: 07037416.wav
    Length: 11
** Loose stones falling.                                                                                ::
    ID: 07037415.wav
    Length: 10
** Loose stones falling.                                                                                ::
    ID: 07037414.wav
    Length: 27
** Loose stones falling.                                                                                ::
    ID: 07037413.wav
    Length: 11
** Loose stones falling.                                                                                ::
    ID: 07037412.wav
    Length: 9
** Loose stones falling.                                                                                ::
    ID: 07037411.wav
    Length: 12
** Archery, flight of arrows.                                                                                ::
    ID: 07037410.wav
    Length: 51
** Archery, flight of arrows shot into target.                                                                                ::
    ID: 07037409.wav
    Length: 42
** Archery, arrows shot into target.                                                                                ::
    ID: 07037408.wav
    Length: 46
** Archery, single arrows shot into target.                                                                                ::
    ID: 07037407.wav
    Length: 64
** Factory Siren sounded.                                                                                ::
    ID: 07037406.wav
    Length: 42
** Airfield atmosphere.                                                                                ::
    ID: 07037405.wav
    Length: 96
** Flying Fortress, interior, engines starting. (Recorded inside cockpit.) (World War II US bomber.)                                                                                ::
    ID: 07037404.wav
    Length: 84
** Flying Fortress, ticking over. (World War II US bomber.)                                                                                ::
    ID: 07037403.wav
    Length: 38
** Archery, arrows passing.                                                                                ::
    ID: 07037402.wav
    Length: 35
** Archery, bow twangs & arrows hitting target.                                                                                ::
    ID: 07037401.wav
    Length: 9
** Archery, arrows thudding into target.                                                                                ::
    ID: 07037400.wav
    Length: 9
** Archery, six fast bow twangs.                                                                                ::
    ID: 07037399.wav
    Length: 8
** Archery, three bow twangs.                                                                                ::
    ID: 07037398.wav
    Length: 9
** Archery, bow twang.                                                                                ::
    ID: 07037397.wav
    Length: 8
** Slow whipping, interior. (Specially created effect.)                                                                                ::
    ID: 07037396.wav
    Length: 76
** Fast whipping, interior. (Specially created effect.)                                                                                ::
    ID: 07037395.wav
    Length: 16
** Execution carried out with a block & large axe. (Specially created effect.)                                                                                ::
    ID: 07037394.wav
    Length: 14
** Execution carried out with a block & axe. (Specially created effect.)                                                                                ::
    ID: 07037393.wav
    Length: 11
** Execution carried out with a block & sword. (Specially created effect.)                                                                                ::
    ID: 07037392.wav
    Length: 12
** Guillotine being used at an execution. (Specially created effect.)                                                                                ::
    ID: 07037391.wav
    Length: 7
** Bucket on a chain with crashes.                                                                                ::
    ID: 07037390.wav
    Length: 52
** Slow walk with chains.                                                                                ::
    ID: 07037389.wav
    Length: 64
** Chains running.                                                                                ::
    ID: 07037388.wav
    Length: 63
** Chains being shaken.                                                                                ::
    ID: 07037387.wav
    Length: 63
** Chains rattling.                                                                                ::
    ID: 07037386.wav
    Length: 62
** Heavy winch operated quickly with start & stop.                                                                                ::
    ID: 07037385.wav
    Length: 15
** Heavy winch operated with start and stop.                                                                                ::
    ID: 07037384.wav
    Length: 31
** Winch operated quickly with start & stop.                                                                                ::
    ID: 07037383.wav
    Length: 23
** Winch operated slowly with start & stop.                                                                                ::
    ID: 07037382.wav
    Length: 46
** Light Metal Pulley operated with start & stop.                                                                                ::
    ID: 07037381.wav
    Length: 74
** Rope Pulley operated with start & stop.                                                                                ::
    ID: 07037380.wav
    Length: 19
** Chain Pulley operated with start & stop.                                                                                ::
    ID: 07037379.wav
    Length: 55
** Metal squeak.                                                                                ::
    ID: 07037378.wav
    Length: 20
** Twin Metal squeaks.                                                                                :Metal:Squeaks:
    ID: 07037377.wav
    Length: 22
** Twin Metal squeaks.                                                                                :Metal:Squeaks:
    ID: 07037376.wav
    Length: 16
** Twin Metal squeaks.                                                                                :Metal:Squeaks:
    ID: 07037375.wav
    Length: 13
** Metal squeak.                                                                                :Metal:Squeaks:
    ID: 07037374.wav
    Length: 8
** Metal squeak.                                                                                :Metal:Squeaks:
    ID: 07037373.wav
    Length: 8
** Seven metal squeaks.                                                                                :Metal:Squeaks:
    ID: 07037372.wav
    Length: 86
** Metal squeak.                                                                                :Metal:Squeaks:
    ID: 07037371.wav
    Length: 11
** Metal squeak.                                                                                ::
    ID: 07037370.wav
    Length: 10
** Metal squeak.                                                                                ::
    ID: 07037369.wav
    Length: 9
** Metal squeak.                                                                                ::
    ID: 07037368.wav
    Length: 12
** Metal squeak.                                                                                ::
    ID: 07037367.wav
    Length: 14
** Chairs squeaking in hall.                                                                                ::
    ID: 07037366.wav
    Length: 11
** Quick Squeaks, short, double, long.                                                                                ::
    ID: 07037365.wav
    Length: 12
** Timber creaking.                                                                                ::
    ID: 07037364.wav
    Length: 126
** Wheels squeaking.                                                                                ::
    ID: 07037363.wav
    Length: 64
** Wheels squeaking.                                                                                ::
    ID: 07037362.wav
    Length: 63
** Wheels squeaking.                                                                                ::
    ID: 07037361.wav
    Length: 50
** Metal sign swinging, with some squeaks.                                                                                ::
    ID: 07037360.wav
    Length: 84
** Metal sign swinging, with some squeaks.                                                                                ::
    ID: 07037359.wav
    Length: 114
** Pair of metal gates opened four times with occasional squeaks.                                                                                ::
    ID: 07037358.wav
    Length: 21
** Sliding Wooden Latch operated four times.                                                                                ::
    ID: 07037357.wav
    Length: 14
** Metal Gate opened & closed.                                                                                ::
    ID: 07037356.wav
    Length: 8
** Wooden Window Frame rattling.                                                                                ::
    ID: 07037355.wav
    Length: 122
** Three Wooden Door Creaks with pauses between each.                                                                                ::
    ID: 07037354.wav
    Length: 29
** Wooden Door Creak.                                                                                ::
    ID: 07037353.wav
    Length: 6
** Wooden Door Creak.                                                                                ::
    ID: 07037352.wav
    Length: 10
** Wooden Door Creak.                                                                                ::
    ID: 07037351.wav
    Length: 13
** Wooden Door Creak.                                                                                ::
    ID: 07037350.wav
    Length: 8
** Wooden Door Creak.                                                                                ::
    ID: 07037349.wav
    Length: 15
** Wooden Door Creak.                                                                                ::
    ID: 07037348.wav
    Length: 10
** Wooden Door Creak.                                                                                ::
    ID: 07037347.wav
    Length: 8
** Wooden Door Creak.                                                                                ::
    ID: 07037346.wav
    Length: 11
** Six Wooden Door Creaks, with pauses between each.                                                                                ::
    ID: 07037345.wav
    Length: 45
** Wooden Door Creak.                                                                                ::
    ID: 07037344.wav
    Length: 7
** Wooden Door Creak.                                                                                ::
    ID: 07037343.wav
    Length: 9
** Wooden Creak.                                                                                ::
    ID: 07037342.wav
    Length: 15
** Wooden Creak.                                                                                ::
    ID: 07037341.wav
    Length: 8
** Long Wooden Creak.                                                                                ::
    ID: 07037340.wav
    Length: 93
** Wooden Creak.                                                                                ::
    ID: 07037339.wav
    Length: 12
** Wooden Creak.                                                                                ::
    ID: 07037338.wav
    Length: 9
** Wooden Creak.                                                                                ::
    ID: 07037337.wav
    Length: 11
** Wooden Creak.                                                                                ::
    ID: 07037336.wav
    Length: 9
** Wooden Creak.                                                                                ::
    ID: 07037335.wav
    Length: 10
** Four single Wooden Creaks.                                                                                ::
    ID: 07037334.wav
    Length: 30
** Wooden Creak.                                                                                ::
    ID: 07037333.wav
    Length: 9
** Wooden Creak.                                                                                ::
    ID: 07037332.wav
    Length: 9
** Wooden Creak.                                                                                ::
    ID: 07037331.wav
    Length: 8
** Heavy Explosion.                                                                                ::
    ID: 07037330.wav
    Length: 8
** Heavy Explosion.                                                                                ::
    ID: 07037329.wav
    Length: 20
** Heavy Explosion.                                                                                ::
    ID: 07037328.wav
    Length: 16
** Heavy Explosion.                                                                                ::
    ID: 07037327.wav
    Length: 7
** Heavy Explosion.                                                                                ::
    ID: 07037326.wav
    Length: 6
** Heavy Explosion.                                                                                ::
    ID: 07037325.wav
    Length: 6
** Heavy Explosion.                                                                                ::
    ID: 07037324.wav
    Length: 15
** Heavy Explosion.                                                                                ::
    ID: 07037323.wav
    Length: 14
** Heavy Explosion.                                                                                ::
    ID: 07037322.wav
    Length: 16
** Heavy Explosion.                                                                                ::
    ID: 07037321.wav
    Length: 8
** Heavy Explosion.                                                                                ::
    ID: 07037320.wav
    Length: 11
** Heavy Explosion.                                                                                ::
    ID: 07037319.wav
    Length: 9
** Factory Hooter sounded.                                                                                ::
    ID: 07037318.wav
    Length: 29
** Factory Hooter sounded.                                                                                ::
    ID: 07037317.wav
    Length: 31
** Factory Hooter sounded.                                                                                ::
    ID: 07037316.wav
    Length: 13
** Factory Hooter sounded.                                                                                ::
    ID: 07037315.wav
    Length: 20
** Factory Hooter sounded.                                                                                ::
    ID: 07037314.wav
    Length: 29
** Factory Hooter sounded.                                                                                ::
    ID: 07037313.wav
    Length: 30
** Factory Hooter sounded.                                                                                ::
    ID: 07037312.wav
    Length: 25
** Factory Hooter sounded.                                                                                ::
    ID: 07037311.wav
    Length: 22
** Factory Hooter sounded.                                                                                ::
    ID: 07037310.wav
    Length: 12
** Factory Hooter sounded.                                                                                ::
    ID: 07037309.wav
    Length: 15
** Factory Hooter sounded.                                                                                ::
    ID: 07037308.wav
    Length: 11
** Factory Hooter sounded.                                                                                ::
    ID: 07037307.wav
    Length: 26
** F36 British Emergency Services Horn sounded.                                                                                ::
    ID: 07037306.wav
    Length: 27
** Mixo TRBO Motor Horn sounded.                                                                                ::
    ID: 07037305.wav
    Length: 21
** Mixo Dynamic Motor Horn sounded.                                                                                ::
    ID: 07037304.wav
    Length: 18
** Mixo TR109 Motor Horn sounded.                                                                                ::
    ID: 07037303.wav
    Length: 20
** F24 Route Nationale Motor Horn sounded.                                                                                ::
    ID: 07037302.wav
    Length: 16
** F33 Musical Motor Horn sounded.                                                                                ::
    ID: 07037301.wav
    Length: 26
** American Police Siren being sounded.                                                                                ::
    ID: 07037300.wav
    Length: 155
** Swiss Post Horn, trumpets sounded as a chord.                                                                                ::
    ID: 07037299.wav
    Length: 25
** Swiss Post Horn sounded.                                                                                ::
    ID: 07037298.wav
    Length: 41
** Portoblast sounded. (Hand-held horn used on light sailing craft.)                                                                                ::
    ID: 07037297.wav
    Length: 22
** Portoblast sounded. (Hand-held horn used on light sailing craft.)                                                                                ::
    ID: 07037296.wav
    Length: 17
** F45 Marine Horn sounded.                                                                                ::
    ID: 07037295.wav
    Length: 31
** Italian Twin Motor Horn being sounded. (Electric Motor Horn.)                                                                                ::
    ID: 07037294.wav
    Length: 12
** Electric motor horn, single blast sounded.                                                                                ::
    ID: 07037293.wav
    Length: 6
** Electric Motor Horn being sounded. (c. 1951 motor horn.) (Recorded inside car.)                                                                                ::
    ID: 07037292.wav
    Length: 9
** Electric Motor Horn being sounded. (c. 1931 motor horn.)                                                                                ::
    ID: 07037291.wav
    Length: 6
** Single Tone Motor Horn sounded, long impatient blasts. (Electric motor horn.)                                                                                ::
    ID: 07037290.wav
    Length: 16
** Single Tone Motor Horn sounded, 2 blasts into impatient blasts. (Electric motor horn.)                                                                                ::
    ID: 07037289.wav
    Length: 7
** Electric Motor Horn sounded, impatient blasts.                                                                                ::
    ID: 07037288.wav
    Length: 7
** Several Electric Motor Horns sounded.                                                                                ::
    ID: 07037287.wav
    Length: 25
** Multitone Motor Horn, impatient blasts sounded. (Electric motor horn.)                                                                                ::
    ID: 07037286.wav
    Length: 7
** Multitone Motor Horn, 1 blast, then 2 short blasts sounded. (Electric motor horn.)                                                                                ::
    ID: 07037285.wav
    Length: 8
** French Single Tone Motor Horn sounded. (Electric motor horn.)                                                                                ::
    ID: 07037284.wav
    Length: 6
** Electric Motor Horn, 2 blasts sounded.                                                                                ::
    ID: 07037283.wav
    Length: 6
** Multitone Motor Horn sounded.                                                                                ::
    ID: 07037282.wav
    Length: 7
** French Multitone Motor Horn sounded.                                                                                ::
    ID: 07037281.wav
    Length: 10
** Twin Tone Motor Horn sounded.                                                                                ::
    ID: 07037280.wav
    Length: 7
** Single Tone Motor Horn sounded.                                                                                ::
    ID: 07037279.wav
    Length: 8
** Twin Electric Motor Horn sounded.                                                                                ::
    ID: 07037278.wav
    Length: 16
** Klaxon Motor Horn sounded.                                                                                ::
    ID: 07037277.wav
    Length: 27
** Bulb-type Motor Horn sounded.                                                                                ::
    ID: 07037276.wav
    Length: 15
** Bulb-type Motor Horn sounded.                                                                                ::
    ID: 07037275.wav
    Length: 12
** Bulb-type Motor Horn sounded.                                                                                ::
    ID: 07037274.wav
    Length: 13
** Bulb-type Motor Horn sounded.                                                                                ::
    ID: 07037273.wav
    Length: 8
** Bulb-type Motor Horn sounded.                                                                                ::
    ID: 07037272.wav
    Length: 11
** Bulb-type Motor Horn sounded.                                                                                ::
    ID: 07037271.wav
    Length: 11
** Service Station, car ramp operating.                                                                                ::
    ID: 07037270.wav
    Length: 39
** Service Station, grinding wheel.                                                                                ::
    ID: 07037269.wav
    Length: 44
** Service Station, high-pressure grease gun operating.                                                                                ::
    ID: 07037268.wav
    Length: 50
** Service Station, electric impulse wrench operating on wheel nuts.                                                                                ::
    ID: 07037267.wav
    Length: 48
** Service Station, air drill operating.                                                                                ::
    ID: 07037266.wav
    Length: 41
** Service Station, compressed air air line operating.                                                                                ::
    ID: 07037265.wav
    Length: 46
** Service Station, oil spray operating.                                                                                ::
    ID: 07037264.wav
    Length: 24
** Service Station, tyre being inflated.                                                                                ::
    ID: 07037263.wav
    Length: 17
** Service Station, tyre being let down.                                                                                ::
    ID: 07037262.wav
    Length: 27
** Service Station, petrol pump turned on, runs, turned off. (Recorded near main road.)                                                                                ::
    ID: 07037261.wav
    Length: 82
** Service Station, petrol pump turned on, runs, turned off. (Recorded near main road.)                                                                                ::
    ID: 07037260.wav
    Length: 54
** Service Station, petrol pump turned on, runs, turned off. (Recorded near main road.)                                                                                ::
    ID: 07037259.wav
    Length: 64
** Dutch Clothing Factory, general atmosphere.                                                                                ::
    ID: 07037258.wav
    Length: 388
** Dutch Customs Hall, general atmosphere.                                                                                ::
    ID: 07037257.wav
    Length: 148
** Dutch Airport, Manchester flight announcement.                                                                                ::
    ID: 07037256.wav
    Length: 29
** Dutch Airport, London flight announcement.                                                                                ::
    ID: 07037255.wav
    Length: 28
** Amsterdam Beurs, gong, calling, ends with bell. (Amsterdam Stock Exchange.)                                                                                ::
    ID: 07037254.wav
    Length: 144
** Dutch Street, children & adults in street.                                                                                ::
    ID: 07037253.wav
    Length: 205
** Amsterdam Market, general atmosphere.                                                                                ::
    ID: 07037252.wav
    Length: 209
** Dutch Public House, atmosphere with jolly crowd.                                                                                ::
    ID: 07037251.wav
    Length: 206
** Dutch Restaurant, atmosphere in large restaurant.                                                                                ::
    ID: 07037250.wav
    Length: 215
** New York Side Street atmosphere.                                                                                ::
    ID: 07037249.wav
    Length: 123
** New York Car Mart atmosphere.                                                                                ::
    ID: 07037248.wav
    Length: 96
** Central Park atmosphere.                                                                                ::
    ID: 07037247.wav
    Length: 121
** New York Dock Workers, begins with sound of siren.                                                                                ::
    ID: 07037246.wav
    Length: 122
** New York Dockside, general atmosphere.                                                                                ::
    ID: 07037245.wav
    Length: 250
** Large mixed crowd in a dining hall with American chatter. (Recorded at a U.S. Air Force base in England.)                                                                                ::
    ID: 07037244.wav
    Length: 426
** Medium-sized mixed crowd in a dining hall with American chatter. (Recorded at a U.S. Air Force base in England.)                                                                                ::
    ID: 07037243.wav
    Length: 431
** Large mixed party crowd with American chatter. (Recorded at a U.S. Air Force base in England.)                                                                                ::
    ID: 07037242.wav
    Length: 427
** Medium-sized mixed party crowd with American chatter. (Recorded at a U.S. Air Force base in England.)                                                                                ::
    ID: 07037241.wav
    Length: 426
** Footsteps on Wood, two men & two women running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037240.wav
    Length: 21
** Footsteps on Wood, two men & two women running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037239.wav
    Length: 21
** Footsteps on Wood, two men & two women running, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037238.wav
    Length: 69
** Footsteps on Wood, two men & one woman running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037237.wav
    Length: 17
** Footsteps on Wood, two men & one woman running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037236.wav
    Length: 18
** Footsteps on Wood, two men & one woman running, with start and stop. (Dead acoustic.)                                                                                ::
    ID: 07037235.wav
    Length: 71
** Footsteps on Wood, man & woman running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037234.wav
    Length: 21
** Footsteps on Wood, man & woman running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037233.wav
    Length: 21
** Footsteps on Wood, man & woman running, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037232.wav
    Length: 64
** Footsteps on Wood, two women running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037231.wav
    Length: 14
** Footsteps on Wood, two women running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037230.wav
    Length: 17
** Footsteps on Wood, two women running, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037229.wav
    Length: 62
** Footsteps on Wood, woman running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037228.wav
    Length: 15
** Footsteps on Wood, woman running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037227.wav
    Length: 16
** Footsteps on Wood, woman running, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037226.wav
    Length: 70
** Footsteps on Wood, three men running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037225.wav
    Length: 18
** Footsteps on Wood, three men running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037224.wav
    Length: 18
** Footsteps on Wood, three men running, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037223.wav
    Length: 67
** Footsteps on Wood, two men running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037222.wav
    Length: 18
** Footsteps on Wood, two men running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037221.wav
    Length: 18
** Footsteps on Wood, two men running, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037220.wav
    Length: 68
** Footsteps on Wood, man running, departing. (Dead acoustic.)                                                                                ::
    ID: 07037219.wav
    Length: 16
** Footsteps on Wood, man running, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037218.wav
    Length: 17
** Footsteps on Wood, man running, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037217.wav
    Length: 68
** Footsteps on Wood, two men & two women walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037216.wav
    Length: 18
** Footsteps on Wood, two men & two women walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037215.wav
    Length: 17
** Footsteps on Wood, two men & two women walking, with start and stop. (Dead acoustic.)                                                                                ::
    ID: 07037214.wav
    Length: 64
** Footsteps on Wood, two men & one woman walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037213.wav
    Length: 17
** Footsteps on Wood, two men & one woman walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037212.wav
    Length: 16
** Footsteps on Wood, two men & one woman walking, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037211.wav
    Length: 65
** Footsteps on Wood, man & woman walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037210.wav
    Length: 16
** Footsteps on Wood, man & woman walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037209.wav
    Length: 15
** Footsteps on Wood, man & woman walking, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037208.wav
    Length: 63
** Footsteps on Wood, two women walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037207.wav
    Length: 14
** Footsteps on Wood, two women walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037206.wav
    Length: 14
** Footsteps on Wood, two women walking, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037205.wav
    Length: 67
** Footsteps on Wood, woman walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037204.wav
    Length: 13
** Footsteps on Wood, woman walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037203.wav
    Length: 15
** Footsteps on Wood, woman walking, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037202.wav
    Length: 65
** Footsteps on Wood, three men walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037201.wav
    Length: 16
** Footsteps on Wood, three men walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037200.wav
    Length: 17
** Footsteps on Wood, three men walking, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037199.wav
    Length: 69
** Footsteps on Wood, two men walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037198.wav
    Length: 21
** Footsteps on Wood, two men walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037197.wav
    Length: 16
** Footsteps on Wood, two men walking, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037196.wav
    Length: 67
** Footsteps on Wood, man walking, departing. (Dead acoustic.)                                                                                ::
    ID: 07037195.wav
    Length: 16
** Footsteps on Wood, man walking, with approach & stop. (Dead acoustic.)                                                                                ::
    ID: 07037194.wav
    Length: 15
** Footsteps on Wood, man walking, with start & stop. (Dead acoustic.)                                                                                ::
    ID: 07037193.wav
    Length: 66
** Footsteps Down Metal Stairs, two men, fast, departing.                                                                                ::
    ID: 07037192.wav
    Length: 24
** Footsteps Down Metal Stairs, two men, fast, with approach & stop.                                                                                ::
    ID: 07037191.wav
    Length: 32
** Footsteps Down Metal Stairs, two men, fast, with start & stop.                                                                                ::
    ID: 07037190.wav
    Length: 47
** Footsteps Down Metal Stairs, man, fast, departing.                                                                                ::
    ID: 07037189.wav
    Length: 22
** Footsteps Down Metal Stairs, man, fast, with approach & stop.                                                                                ::
    ID: 07037188.wav
    Length: 24
** Footsteps Down Metal Stairs, man, fast, with start & stop.                                                                                ::
    ID: 07037187.wav
    Length: 39
** Footsteps Up Metal Stairs, two men, fast, departing.                                                                                ::
    ID: 07037186.wav
    Length: 27
** Footsteps Up Metal Stairs, two men, fast, with approach & stop.                                                                                ::
    ID: 07037185.wav
    Length: 28
** Footsteps Up Metal Stairs, two men, fast, with start & stop.                                                                                ::
    ID: 07037184.wav
    Length: 41
** Footsteps Up Metal Stairs, man, fast, departing.                                                                                ::
    ID: 07037183.wav
    Length: 27
** Footsteps Up Metal Stairs, man, fast, with approach & stop.                                                                                ::
    ID: 07037182.wav
    Length: 28
** Footsteps Up Metal Stairs, man, fast, with start & stop.                                                                                ::
    ID: 07037181.wav
    Length: 41
** Footsteps Down Metal Stairs, woman, slow, departing.                                                                                ::
    ID: 07037180.wav
    Length: 27
** Footsteps Down Metal Stairs, woman, slow, with approach & stop.                                                                                ::
    ID: 07037179.wav
    Length: 26
** Footsteps Down Metal Stairs, woman, slow, with start & stop.                                                                                ::
    ID: 07037178.wav
    Length: 40
** Footsteps Down Metal Stairs, three men, slow, departing.                                                                                ::
    ID: 07037177.wav
    Length: 24
** Footsteps Down Metal Stairs, three men, slow, with approach & stop.                                                                                ::
    ID: 07037176.wav
    Length: 23
** Footsteps Down Metal Stairs, three men, slow, with start & stop.                                                                                ::
    ID: 07037175.wav
    Length: 29
** Footsteps Down Metal Stairs, two men, slow, departing.                                                                                ::
    ID: 07037174.wav
    Length: 26
** Footsteps Down Metal Stairs, two men, slow, with approach & stop.                                                                                ::
    ID: 07037173.wav
    Length: 28
** Footsteps Down Metal Stairs, two men, slow, with start & stop.                                                                                ::
    ID: 07037172.wav
    Length: 40
** Footsteps Down Metal Stairs, man, slow, departing.                                                                                ::
    ID: 07037171.wav
    Length: 27
** Footsteps Down Metal Stairs, man, slow, with approach & stop.                                                                                ::
    ID: 07037170.wav
    Length: 26
** Footsteps Down Metal Stairs, man, slow, with start & stop.                                                                                ::
    ID: 07037169.wav
    Length: 39
** Footsteps Up Metal Stairs, woman, slow, departing.                                                                                ::
    ID: 07037168.wav
    Length: 21
** Footsteps Up Metal Stairs, woman, slow, with approach & stop.                                                                                ::
    ID: 07037167.wav
    Length: 32
** Footsteps Up Metal Stairs, woman, slow, with start & stop.                                                                                ::
    ID: 07037166.wav
    Length: 41
** Footsteps Up Metal Stairs, three men, slow, departing.                                                                                ::
    ID: 07037165.wav
    Length: 30
** Footsteps Up Metal Stairs, three men, slow, with approach & stop.                                                                                ::
    ID: 07037164.wav
    Length: 27
** Footsteps Up Metal Stairs, three men, slow, with start & stop.                                                                                ::
    ID: 07037163.wav
    Length: 41
** Footsteps Up Metal Stairs, two men, slow, departing.                                                                                ::
    ID: 07037162.wav
    Length: 30
** Footsteps Up Metal Stairs, two men, slow, with approach & stop.                                                                                ::
    ID: 07037161.wav
    Length: 32
** Footsteps Up Metal Stairs, two men, slow, with start & stop.                                                                                ::
    ID: 07037160.wav
    Length: 39
** Footsteps Up Metal Stairs, man, slow, departing.                                                                                ::
    ID: 07037159.wav
    Length: 33
** Footsteps Up Metal Stairs, man, slow, with approach & stop.                                                                                ::
    ID: 07037158.wav
    Length: 28
** Footsteps Up Metal Stairs, man, slow, with start & stop.                                                                                ::
    ID: 07037157.wav
    Length: 37
** Footsteps Down Wooden Stairs, two men & two women, slow, departing.                                                                                ::
    ID: 07037156.wav
    Length: 27
** Footsteps Down Wooden Stairs, two men & two women, slow, with approach & stop.                                                                                ::
    ID: 07037155.wav
    Length: 24
** Footsteps Down Wooden Stairs, two men & two women, slow, with start and stop.                                                                                ::
    ID: 07037154.wav
    Length: 19
** Footsteps Down Wooden Stairs, two men & one woman, slow, departing.                                                                                ::
    ID: 07037153.wav
    Length: 21
** Footsteps Down Wooden Stairs, two men & one woman, slow, with approach & stop.                                                                                ::
    ID: 07037152.wav
    Length: 18
** Footsteps Down Wooden Stairs, two men & one woman, slow, with start and stop.                                                                                ::
    ID: 07037151.wav
    Length: 20
** Footsteps Down Wooden Stairs, man & woman, slow, departing.                                                                                ::
    ID: 07037150.wav
    Length: 21
** Footsteps Down Wooden Stairs, man & woman, slow, with approach & stop.                                                                                ::
    ID: 07037149.wav
    Length: 19
** Footsteps Down Wooden Stairs, man & woman, slow, with start and stop.                                                                                ::
    ID: 07037148.wav
    Length: 20
** Footsteps Down Wooden Stairs, two women, slow, departing.                                                                                ::
    ID: 07037147.wav
    Length: 20
** Footsteps Down Wooden Stairs, two women, slow, with approach & stop.                                                                                ::
    ID: 07037146.wav
    Length: 19
** Footsteps Down Wooden Stairs, two women, slow, with start & stop.                                                                                ::
    ID: 07037145.wav
    Length: 21
** Footsteps Down Wooden Stairs, woman, slow, departing.                                                                                ::
    ID: 07037144.wav
    Length: 20
** Footsteps Down Wooden Stairs, woman, slow, with approach & stop.                                                                                ::
    ID: 07037143.wav
    Length: 20
** Footsteps Down Wooden Stairs, woman, slow, with start & stop.                                                                                ::
    ID: 07037142.wav
    Length: 19
** Footsteps Down Wooden Stairs, three men, slow, departing.                                                                                ::
    ID: 07037141.wav
    Length: 21
** Footsteps Down Wooden Stairs, three men, slow, with approach & stop.                                                                                ::
    ID: 07037140.wav
    Length: 21
** Footsteps Down Wooden Stairs, three men, slow, with start & stop.                                                                                ::
    ID: 07037139.wav
    Length: 21
** Footsteps Down Wooden Stairs, two men, slow, departing.                                                                                ::
    ID: 07037138.wav
    Length: 21
** Footsteps Down Wooden Stairs, two men, slow, with approach & stop.                                                                                ::
    ID: 07037137.wav
    Length: 22
** Footsteps Down Wooden Stairs, two men, slow, with start & stop.                                                                                ::
    ID: 07037136.wav
    Length: 20
** Footsteps Down Wooden Stairs, man, slow, departing.                                                                                ::
    ID: 07037135.wav
    Length: 21
** Footsteps Down Wooden Stairs, man, slow, with approach & stop.                                                                                ::
    ID: 07037134.wav
    Length: 20
** Footsteps Down Wooden Stairs, man, slow, with start & stop.                                                                                ::
    ID: 07037133.wav
    Length: 20
** Footsteps Up Wooden Stairs, woman, fast, departing.                                                                                ::
    ID: 07037132.wav
    Length: 17
** Footsteps Up Wooden Stairs, woman, fast, with approach & stop.                                                                                ::
    ID: 07037131.wav
    Length: 19
** Footsteps Up Wooden Stairs, woman, fast, with start & stop.                                                                                ::
    ID: 07037130.wav
    Length: 19
** Footsteps Up Wooden Stairs, three men, fast, departing.                                                                                ::
    ID: 07037129.wav
    Length: 19
** Footsteps Up Wooden Stairs, three men, fast, with approach & stop.                                                                                ::
    ID: 07037128.wav
    Length: 17
** Footsteps Up Wooden Stairs, three men, fast, with start & stop.                                                                                ::
    ID: 07037127.wav
    Length: 20
** Footsteps Up Wooden Stairs, two men, fast, departing.                                                                                ::
    ID: 07037126.wav
    Length: 17
** Footsteps Up Wooden Stairs, two men, fast, with approach & stop.                                                                                ::
    ID: 07037125.wav
    Length: 19
** Footsteps Up Wooden Stairs, two men, fast, with start & stop.                                                                                ::
    ID: 07037124.wav
    Length: 17
** Footsteps Up Wooden Stairs, man, fast, departing.                                                                                ::
    ID: 07037123.wav
    Length: 15
** Footsteps Up Wooden Stairs, man, fast, with approach & stop.                                                                                ::
    ID: 07037122.wav
    Length: 16
** Footsteps Up Wooden Stairs, man, fast, with start & stop.                                                                                ::
    ID: 07037121.wav
    Length: 17
** Footsteps Up Wooden Stairs, two men & two women, slow, departing.                                                                                ::
    ID: 07037120.wav
    Length: 26
** Footsteps Up Wooden Stairs, two men & two women, slow, with approach & stop.                                                                                ::
    ID: 07037119.wav
    Length: 33
** Footsteps Up Wooden Stairs, two men & two women, slow, with start & stop.                                                                                ::
    ID: 07037118.wav
    Length: 27
** Footsteps Up Wooden Stairs, two men & one woman, slow, departing.                                                                                ::
    ID: 07037117.wav
    Length: 25
** Footsteps Up Wooden Stairs, two men & one woman, slow, with approach & stop.                                                                                ::
    ID: 07037116.wav
    Length: 25
** Footsteps Up Wooden Stairs, two men & one woman, slow, with start & stop.                                                                                ::
    ID: 07037115.wav
    Length: 28
** Footsteps Up Wooden Stairs, man & woman, slow, departing.                                                                                ::
    ID: 07037114.wav
    Length: 23
** Footsteps Up Wooden Stairs, man & woman, slow, with approach & stop.                                                                                ::
    ID: 07037113.wav
    Length: 27
** Footsteps Up Wooden Stairs, man & woman, slow, with start & stop.                                                                                ::
    ID: 07037112.wav
    Length: 28
** Footsteps Up Wooden Stairs, two women, slow, departing.                                                                                ::
    ID: 07037111.wav
    Length: 23
** Footsteps Up Wooden Stairs, two women, slow, with approach & stop.                                                                                ::
    ID: 07037110.wav
    Length: 27
** Footsteps Up Wooden Stairs, two women, slow, with start & stop.                                                                                ::
    ID: 07037109.wav
    Length: 28
** Footsteps Up Wooden Stairs, woman, slow, departing.                                                                                ::
    ID: 07037108.wav
    Length: 23
** Footsteps Up Wooden Stairs, woman, slow, with approach & stop.                                                                                ::
    ID: 07037107.wav
    Length: 24
** Footsteps Up Wooden Stairs, woman, slow, with start & stop.                                                                                ::
    ID: 07037106.wav
    Length: 20
** Footsteps Up Wooden Stairs, three men, slow, departing.                                                                                ::
    ID: 07037105.wav
    Length: 25
** Footsteps Up Wooden Stairs, three men, slow, with approach & stop.                                                                                ::
    ID: 07037104.wav
    Length: 24
** Footsteps Up Wooden Stairs, three men, slow, with start & stop.                                                                                ::
    ID: 07037103.wav
    Length: 26
** Footsteps Up Wooden Stairs, two men, slow, departing.                                                                                ::
    ID: 07037102.wav
    Length: 24
** Footsteps Up Wooden Stairs, two men, slow, with approach & stop.                                                                                ::
    ID: 07037101.wav
    Length: 26
** Footsteps Up Wooden Stairs, two men, slow, with start & stop.                                                                                ::
    ID: 07037100.wav
    Length: 24
** Footsteps Up Wooden Stairs, man, slow, departing.                                                                                ::
    ID: 07037099.wav
    Length: 24
** Footsteps Up Wooden Stairs, man, slow, with approach & stop.                                                                                ::
    ID: 07037098.wav
    Length: 23
** Footsteps Up Wooden Stairs, man, slow, with start & stop.                                                                                ::
    ID: 07037097.wav
    Length: 29
** Footsteps on Country Road, two men & two women running, departing.                                                                                ::
    ID: 07037096.wav
    Length: 20
** Footsteps on Country Road, two men & two women running, with approach & stop.                                                                                ::
    ID: 07037095.wav
    Length: 20
** Footsteps on Country Road, two men & two women running, with start & stop.                                                                                ::
    ID: 07037094.wav
    Length: 71
** Footsteps on Country Road, two men & one woman running, departing.                                                                                ::
    ID: 07037093.wav
    Length: 19
** Footsteps on Country Road, two men & one woman running, with approach & stop.                                                                                ::
    ID: 07037092.wav
    Length: 18
** Footsteps on Country Road, two men & one woman running, with start & stop.                                                                                ::
    ID: 07037091.wav
    Length: 70
** Footsteps on Country Road, man & woman running, departing.                                                                                ::
    ID: 07037090.wav
    Length: 18
** Footsteps on Country Road, man & woman running, with approach & stop.                                                                                ::
    ID: 07037089.wav
    Length: 20
** Footsteps on Country Road, man & woman running, with start & stop.                                                                                ::
    ID: 07037088.wav
    Length: 63
** Footsteps on Country Road, two women running, departing.                                                                                ::
    ID: 07037087.wav
    Length: 19
** Footsteps on Country Road, two women running, with approach & stop.                                                                                ::
    ID: 07037086.wav
    Length: 19
** Footsteps on Country Road, two women running, with start & stop.                                                                                ::
    ID: 07037085.wav
    Length: 67
** Footsteps on Country Road, woman running, departing.                                                                                ::
    ID: 07037084.wav
    Length: 19
** Footsteps on Country Road, woman running, with approach & stop.                                                                                ::
    ID: 07037083.wav
    Length: 18
** Footsteps on Country Road, woman running, with start & stop.                                                                                ::
    ID: 07037082.wav
    Length: 67
** Footsteps on Country Road, three men running, departing.                                                                                ::
    ID: 07037081.wav
    Length: 17
** Footsteps on Country Road, three men running, with approach & stop.                                                                                ::
    ID: 07037080.wav
    Length: 17
** Footsteps on Country Road, three men running, with start & stop.                                                                                ::
    ID: 07037079.wav
    Length: 69
** Footsteps on Country Road, two men running, departing.                                                                                ::
    ID: 07037078.wav
    Length: 18
** Footsteps on Country Road, two men running, with approach & stop.                                                                                ::
    ID: 07037077.wav
    Length: 18
** Footsteps on Country Road, two men running, with start & stop.                                                                                ::
    ID: 07037076.wav
    Length: 69
** Footsteps on Country Road, man running, departing.                                                                                ::
    ID: 07037075.wav
    Length: 18
** Footsteps on Country Road, man running, with approach & stop.                                                                                ::
    ID: 07037074.wav
    Length: 16
** Footsteps on Country Road, man running, with start & stop.                                                                                ::
    ID: 07037073.wav
    Length: 68
** Footsteps on Country Road, two men & two women walking, departing.                                                                                ::
    ID: 07037072.wav
    Length: 16
** Footsteps on Country Road, two men & two women walking, with approach & stop.                                                                                ::
    ID: 07037071.wav
    Length: 17
** Footsteps on Country Road, two men & two women walking, with start & stop.                                                                                ::
    ID: 07037070.wav
    Length: 69
** Footsteps on Country Road, two men & one woman walking, departing.                                                                                ::
    ID: 07037069.wav
    Length: 18
** Footsteps on Country Road, two men & one woman walking, with approach & stop.                                                                                ::
    ID: 07037068.wav
    Length: 18
** Footsteps on Country Road, two men & one woman walking, with start & stop.                                                                                ::
    ID: 07037067.wav
    Length: 69
** Footsteps on Country Road, man & woman, departing.                                                                                ::
    ID: 07037066.wav
    Length: 17
** Footsteps on Country Road, man & woman, with approach & stop.                                                                                ::
    ID: 07037065.wav
    Length: 17
** Footsteps on Country Road, man & woman, with start & stop.                                                                                ::
    ID: 07037064.wav
    Length: 71
** Footsteps on Country Road, two women walking, departing.                                                                                ::
    ID: 07037063.wav
    Length: 17
** Footsteps on Country Road, two women walking, with approach & stop.                                                                                ::
    ID: 07037062.wav
    Length: 17
** Footsteps on Country Road, two women walking, with start & stop.                                                                                ::
    ID: 07037061.wav
    Length: 75
** Footsteps on Country Road, woman walking, departing.                                                                                ::
    ID: 07037060.wav
    Length: 17
** Footsteps on Country Road, woman walking, with approach & stop.                                                                                ::
    ID: 07037059.wav
    Length: 17
** Footsteps on Country Road, woman walking, with start & stop.                                                                                ::
    ID: 07037058.wav
    Length: 67
** Footsteps on Country Road, three men walking, departing.                                                                                ::
    ID: 07037057.wav
    Length: 20
** Footsteps on Country Road, three men walking, with approach & stop.                                                                                ::
    ID: 07037056.wav
    Length: 17
** Footsteps on Country Road, three men walking, with start & stop.                                                                                ::
    ID: 07037055.wav
    Length: 77
** Footsteps on Country Road, two men walking, departing.                                                                                ::
    ID: 07037054.wav
    Length: 18
** Footsteps on Country Road, two men walking, with approach & stop.                                                                                ::
    ID: 07037053.wav
    Length: 21
** Footsteps on Country Road, two men walking, with start & stop.                                                                                ::
    ID: 07037052.wav
    Length: 69
** Footsteps on Country Road, man walking, departing.                                                                                ::
    ID: 07037051.wav
    Length: 18
** Footsteps on Country Road, man walking, with approach & stop.                                                                                ::
    ID: 07037050.wav
    Length: 17
** Footsteps on Country Road, man walking, with start & stop.                                                                                ::
    ID: 07037049.wav
    Length: 67
** Footsteps on Pavement, woman running, departing.                                                                                ::
    ID: 07037048.wav
    Length: 25
** Footsteps on Pavement, woman running, with approach & stop.                                                                                ::
    ID: 07037047.wav
    Length: 17
** Footsteps on Pavement, woman running, with start & stop.                                                                                ::
    ID: 07037046.wav
    Length: 67
** Footsteps on Pavement, three men running, departing.                                                                                ::
    ID: 07037045.wav
    Length: 18
** Footsteps on Pavement, three men running, with approach & stop.                                                                                ::
    ID: 07037044.wav
    Length: 18
** Footsteps on Pavement, three men running, with start & stop.                                                                                ::
    ID: 07037043.wav
    Length: 69
** Footsteps on Pavement, two men running, departing.                                                                                ::
    ID: 07037042.wav
    Length: 19
** Footsteps on Pavement, two men running, with approach & stop.                                                                                ::
    ID: 07037041.wav
    Length: 17
** Footsteps on Pavement, two men running, with start & stop.                                                                                ::
    ID: 07037040.wav
    Length: 65
** Footsteps on Pavement, man running, departing.                                                                                ::
    ID: 07037039.wav
    Length: 18
** Footsteps on Pavement, man running, with approach & stop.                                                                                ::
    ID: 07037038.wav
    Length: 21
** Footsteps on Pavement, man running, with start & stop.                                                                                ::
    ID: 07037037.wav
    Length: 72
** Footsteps on Pavement, two men & two women running, departing.                                                                                ::
    ID: 07037036.wav
    Length: 17
** Footsteps on Pavement, two men & two women running, with approach & stop.                                                                                ::
    ID: 07037035.wav
    Length: 19
** Footsteps on Pavement, two men & two women running, with start & stop.                                                                                ::
    ID: 07037034.wav
    Length: 68
** Footsteps on Pavement, two men & one woman running, departing.                                                                                ::
    ID: 07037033.wav
    Length: 16
** Footsteps on Pavement, two men & one woman running, with approach & stop.                                                                                ::
    ID: 07037032.wav
    Length: 20
** Footsteps on Pavement, two men & one woman running, with start & stop.                                                                                ::
    ID: 07037031.wav
    Length: 67
** Footsteps on Pavement, man & woman running, departing.                                                                                ::
    ID: 07037030.wav
    Length: 14
** Footsteps on Pavement, man & woman running, with approach & stop.                                                                                ::
    ID: 07037029.wav
    Length: 15
** Footsteps on Pavement, man & woman running, with start & stop.                                                                                ::
    ID: 07037028.wav
    Length: 61
** Footsteps on Pavement, two women running, departing.                                                                                ::
    ID: 07037027.wav
    Length: 18
** Footsteps on Pavement, two women running, with approach & stop.                                                                                ::
    ID: 07037026.wav
    Length: 17
** Footsteps on Pavement, two women running, with start & stop.                                                                                ::
    ID: 07037025.wav
    Length: 67
** Footsteps on Pavement, two men & two women walking, departing.                                                                                ::
    ID: 07037024.wav
    Length: 19
** Footsteps on Pavement, two men & two women walking, with approach & stop.                                                                                ::
    ID: 07037023.wav
    Length: 17
** Footsteps on Pavement, two men & two women walking, with start & stop.                                                                                ::
    ID: 07037022.wav
    Length: 66
** Footsteps on Pavement, two men & one woman walking, departing.                                                                                ::
    ID: 07037021.wav
    Length: 20
** Footsteps on Pavement, two men & one woman walking, with approach & stop.                                                                                ::
    ID: 07037020.wav
    Length: 17
** Footsteps on Pavement, two men & one woman walking, with start & stop.                                                                                ::
    ID: 07037019.wav
    Length: 66
** Footsteps on Pavement, man & woman walking, departing.                                                                                ::
    ID: 07037018.wav
    Length: 20
** Footsteps on Pavement, man & woman walking, with approach & stop.                                                                                ::
    ID: 07037017.wav
    Length: 16
** Footsteps on Pavement, man & woman walking, with start & stop.                                                                                ::
    ID: 07037016.wav
    Length: 66
** Footsteps on Pavement, two women walking, departing.                                                                                ::
    ID: 07037015.wav
    Length: 18
** Footsteps on Pavement, two women walking, with approach & stop.                                                                                ::
    ID: 07037014.wav
    Length: 15
** Footsteps on Pavement, two women walking, with start & stop.                                                                                ::
    ID: 07037013.wav
    Length: 64
** Footsteps on Pavement, woman walking, departing.                                                                                ::
    ID: 07037012.wav
    Length: 22
** Footsteps on Pavement, woman walking, with approach & stop.                                                                                ::
    ID: 07037011.wav
    Length: 15
** Footsteps on Pavement, woman walking, with start & stop.                                                                                ::
    ID: 07037010.wav
    Length: 62
** Footsteps on Pavement, three men walking, departing.                                                                                ::
    ID: 07037009.wav
    Length: 16
** Footsteps on Pavement, three men walking, with approach & stop.                                                                                ::
    ID: 07037008.wav
    Length: 24
** Footsteps on Pavement, three men walking, with start & stop.                                                                                ::
    ID: 07037007.wav
    Length: 67
** Footsteps on Pavement, two men walking, departing.                                                                                ::
    ID: 07037006.wav
    Length: 16
** Footsteps on Pavement, two men walking, with approach & stop.                                                                                ::
    ID: 07037005.wav
    Length: 16
** Footsteps on Pavement, two men walking, with start & stop.                                                                                ::
    ID: 07037004.wav
    Length: 63
** Footsteps on Pavement, man walking, departing.                                                                                ::
    ID: 07037003.wav
    Length: 14
** Footsteps on Pavement, man walking, with approach & stop.                                                                                ::
    ID: 07037002.wav
    Length: 15
** Footsteps on Pavement, man walking, with start & stop.                                                                                ::
    ID: 07037001.wav
    Length: 65
** Grandfather Clock with St Michael's chimes, winding by chain.                                                                                ::
    ID: 07036204.wav
    Length: 40
** Grandfather Clock with St Michael's chimes, striking twelve o'clock.                                                                                ::
    ID: 07036203.wav
    Length: 66
** Grandfather Clock with St Michael's chimes, striking eleven o'clock.                                                                                ::
    ID: 07036202.wav
    Length: 61
** Grandfather Clock with St Michael's chimes, striking ten o'clock.                                                                                ::
    ID: 07036201.wav
    Length: 59
** Grandfather Clock with St Michael's chimes, striking nine o'clock.                                                                                ::
    ID: 07036200.wav
    Length: 57
** Grandfather Clock with St Michael's chimes, striking eight o'clock.                                                                                ::
    ID: 07036199.wav
    Length: 54
** Grandfather Clock with St Michael's chimes, striking seven o'clock.                                                                                ::
    ID: 07036198.wav
    Length: 50
** Grandfather Clock with St Michael's chimes, striking six o'clock.                                                                                ::
    ID: 07036197.wav
    Length: 48
** Grandfather Clock with St Michael's chimes, striking five o'clock.                                                                                ::
    ID: 07036196.wav
    Length: 45
** Grandfather Clock with St Michael's chimes, striking four o'clock.                                                                                ::
    ID: 07036195.wav
    Length: 42
** Grandfather Clock with St Michael's chimes, striking three o'clock.                                                                                ::
    ID: 07036194.wav
    Length: 39
** Grandfather Clock with St Michael's chimes, striking two o'clock.                                                                                ::
    ID: 07036193.wav
    Length: 40
** Grandfather Clock with St Michael's chimes, striking one o'clock.                                                                                ::
    ID: 07036192.wav
    Length: 34
** Grandfather Clock with St Michael's chimes, striking quarter to the hour.                                                                                ::
    ID: 07036191.wav
    Length: 30
** Grandfather Clock with St Michael's chimes, striking half past the hour.                                                                                ::
    ID: 07036190.wav
    Length: 21
** Grandfather Clock with St Michael's chimes, striking quarter past the hour.                                                                                ::
    ID: 07036189.wav
    Length: 16
** Domestic Mantle Clock striking twelve o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036188.wav
    Length: 64
** Domestic Mantle Clock striking eleven o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036187.wav
    Length: 62
** Domestic Mantle Clock striking ten o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036186.wav
    Length: 62
** Domestic Mantle Clock striking nine o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036185.wav
    Length: 58
** Domestic Mantle Clock striking eight o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036184.wav
    Length: 56
** Domestic Mantle Clock striking seven o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036183.wav
    Length: 52
** Domestic Mantle Clock striking six o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036182.wav
    Length: 54
** Domestic Mantle Clock striking five o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036181.wav
    Length: 51
** Domestic Mantle Clock striking four o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036180.wav
    Length: 47
** Domestic Mantle Clock striking three o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036179.wav
    Length: 45
** Domestic Mantle Clock striking two o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036178.wav
    Length: 45
** Domestic Mantle Clock striking one o'clock. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036177.wav
    Length: 40
** Domestic Mantle Clock striking quarter to the hour. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036176.wav
    Length: 24
** Domestic Mantle Clock striking half past the hour. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036175.wav
    Length: 21
** Domestic Mantle Clock striking quarter past the hour. (Early 19th Century clock chimes 'B', 8 bells, 1 gong.)                                                                                ::
    ID: 07036174.wav
    Length: 18
** Domestic Mantle Clock striking twelve o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036173.wav
    Length: 69
** Domestic Mantle Clock striking eleven o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036172.wav
    Length: 65
** Domestic Mantle Clock striking ten o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036171.wav
    Length: 64
** Domestic Mantle Clock striking nine o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036170.wav
    Length: 60
** Domestic Mantle Clock striking eight o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036169.wav
    Length: 56
** Domestic Mantle Clock striking seven o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036168.wav
    Length: 56
** Domestic Mantle Clock striking six o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036167.wav
    Length: 52
** Domestic Mantle Clock striking five o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036166.wav
    Length: 50
** Domestic Mantle Clock striking four o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036165.wav
    Length: 47
** Domestic Mantle Clock striking three o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036164.wav
    Length: 43
** Domestic Mantle Clock striking two o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036163.wav
    Length: 42
** Domestic Mantle Clock striking one o'clock. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036162.wav
    Length: 43
** Domestic Mantle Clock striking quarter to the hour. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036161.wav
    Length: 23
** Domestic Mantle Clock striking half past the hour. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036160.wav
    Length: 19
** Domestic Mantle Clock striking quarter past the hour. (Early 19th Century clock chimes 'A', 8 bells, 1 gong.)                                                                                ::
    ID: 07036159.wav
    Length: 16
** Hawker Harrier, exterior, manoeuvring on ground. (Harrier Jump-Jet, vertical take off & landing fighter jet.)                                                                                ::
    ID: 07036158.wav
    Length: 100
** Hawker Harrier, exterior, approach & land, switch off engines. (Harrier Jump-Jet, vertical take off & landing fighter jet.)                                                                                ::
    ID: 07036157.wav
    Length: 127
** Hawker Harrier, exterior, passing over twice. (Harrier Jump-Jet, vertical take off & landing fighter jet.)                                                                                ::
    ID: 07036156.wav
    Length: 42
** Hawker Harrier, exterior, take off & passing over. (Harrier Jump-Jet, vertical take off & landing fighter jet.)                                                                                ::
    ID: 07036155.wav
    Length: 54
** Hawker Harrier, exterior, passing over. (Harrier Jump-Jet, vertical take off & landing fighter jet.)                                                                                ::
    ID: 07036154.wav
    Length: 32
** Hawker Harrier, exterior, revving engines, taxi away. (Harrier Jump-Jet, vertical take off & landing fighter jet.)                                                                                ::
    ID: 07036153.wav
    Length: 198
** Hawker Harrier, exterior, start & run up engines. (Harrier Jump-Jet, vertical take off & landing fighter jet.)                                                                                ::
    ID: 07036152.wav
    Length: 123
** Farnborough Air Show 1968, general atmosphere with P.A. announcements, jet aircraft in foreground.                                                                                ::
    ID: 07036151.wav
    Length: 192
** Farnborough Air Show 1968, aircraft passing overhead.                                                                                ::
    ID: 07036150.wav
    Length: 193
** Farnborough Air Show 1968, general atmosphere without P.A. announcements.                                                                                 ::
    ID: 07036149.wav
    Length: 382
** Racing Track, two-car race.                                                                                ::
    ID: 07036148.wav
    Length: 47
** Racing Track, single car lapping.                                                                                ::
    ID: 07036147.wav
    Length: 74
** Humming Top, golden note top.                                                                                ::
    ID: 07036146.wav
    Length: 81
** Humming Top, choral tone top.                                                                                ::
    ID: 07036145.wav
    Length: 112
** Teddy Bear squeaker.                                                                                ::
    ID: 07036144.wav
    Length: 71
** Teddy Bear squeaker.                                                                                ::
    ID: 07036143.wav
    Length: 26
** 'Mama' doll.                                                                                ::
    ID: 07036142.wav
    Length: 60
** 'Mama' doll.                                                                                ::
    ID: 07036141.wav
    Length: 55
** 'Mama' doll.                                                                                ::
    ID: 07036140.wav
    Length: 49
** Musical workbench.                                                                                ::
    ID: 07036139.wav
    Length: 136
** Battery-powered Mechanical Batman toy operating.                                                                                ::
    ID: 07036138.wav
    Length: 117
** Battery-powered Showboat River Queen toy operating.                                                                                ::
    ID: 07036137.wav
    Length: 120
** Battery-powered toy fire engine operating.                                                                                ::
    ID: 07036136.wav
    Length: 99
** Clockwork Toy, plastic 'push-and-go' operating.                                                                                ::
    ID: 07036135.wav
    Length: 94
** Clockwork Toy, minature racer operating.                                                                                ::
    ID: 07036134.wav
    Length: 17
** Clockwork Toy, minature car operating.                                                                                ::
    ID: 07036133.wav
    Length: 20
** Clockwork Toy, Whimpsy Pal operating.                                                                                ::
    ID: 07036132.wav
    Length: 76
** Musical push-along toy.                                                                                ::
    ID: 07036131.wav
    Length: 133
** Toy Pussycat squeaker.                                                                                ::
    ID: 07036130.wav
    Length: 74
** Toy Mouse squeaker.                                                                                ::
    ID: 07036129.wav
    Length: 71
** Toy Rabbit squeaker.                                                                                ::
    ID: 07036128.wav
    Length: 69
** Rattle (normal type).                                                                                ::
    ID: 07036127.wav
    Length: 74
** Rattle, Handy Dandy.                                                                                ::
    ID: 07036126.wav
    Length: 53
** Rattle, Ring-a-Bell.                                                                                ::
    ID: 07036125.wav
    Length: 69
** Rattle, Bobby (suction cup rattle).                                                                                ::
    ID: 07036124.wav
    Length: 68
** Rattle, melody chime.                                                                                ::
    ID: 07036123.wav
    Length: 67
** Talking Story Set Record, "Tommy the Train" story. (Speech mainly unidentifiable.)                                                                                ::
    ID: 07036122.wav
    Length: 49
** Talking Story Set Record, fire story. (Speech mainly unidentifiable.)                                                                                ::
    ID: 07036121.wav
    Length: 81
** Talking Story Set Record, animal story. (Speech mainly unidentifiable.)                                                                                ::
    ID: 07036120.wav
    Length: 85
** Rosebud Pull-Out Wire Doll, various phrases.                                                                                ::
    ID: 07036119.wav
    Length: 95
** 'Suzy Sing-a-Song' Singing Doll Record, spoken phrases.                                                                                ::
    ID: 07036118.wav
    Length: 43
** 'Suzy Sing-a-Song' Singing Doll Record, tongue twister said twice.                                                                                ::
    ID: 07036117.wav
    Length: 37
** 'Suzy Sing-a-Song' Singing Doll Record, "Polly put the kettle on"/"Grand old Duke of York".                                                                                ::
    ID: 07036116.wav
    Length: 35
** 'Suzy Sing-a-Song' Singing Doll Record, "Frere Jacques".                                                                                ::
    ID: 07036115.wav
    Length: 30
** 'Suzy Sing-a-Song' Singing Doll Record, "It's raining it's pouring"/"Round and round the garden".                                                                                ::
    ID: 07036114.wav
    Length: 30
** 'Suzy Sing-a-Song' Singing Doll Record, "Oranges and Lemons".                                                                                ::
    ID: 07036113.wav
    Length: 36
** Paris Metro, platform atmosphere.                                                                                ::
    ID: 07036112.wav
    Length: 252
** Paris Metro, train arrives in station & departs.                                                                                ::
    ID: 07036111.wav
    Length: 64
** Paris Metro, platform gates opened & closed.                                                                                ::
    ID: 07036110.wav
    Length: 29
** French Steam Train, exterior, Pacific-type steam engine in station, departs with train at 001m15s.                                                                                ::
    ID: 07036109.wav
    Length: 99
** French Steam Train, interior, local train constant run on welded track, stops at 003m50s.                                                                                ::
    ID: 07036108.wav
    Length: 262
** French Steam Train, local train arrives, guard's whistle, train departs.                                                                                ::
    ID: 07036107.wav
    Length: 177
** French Steam Train, guard's whistle & local train departs.                                                                                ::
    ID: 07036106.wav
    Length: 58
** French Steam Train, local train arrives, station atmosphere.                                                                                ::
    ID: 07036105.wav
    Length: 82
** French Steam Train, local train departs quietly.                                                                                ::
    ID: 07036104.wav
    Length: 93
** French Steam Train, whistle & local train departs.                                                                                ::
    ID: 07036103.wav
    Length: 133
** French Steam Train, train & guard's whistles, train departs.                                                                                ::
    ID: 07036102.wav
    Length: 75
** French Steam Train, local passenger train passing.                                                                                ::
    ID: 07036101.wav
    Length: 59
** French Level Crossing, gates close, two steam trains pass, gates open, traffic passes.                                                                                ::
    ID: 07036100.wav
    Length: 185
** French Level Crossing, steam train over level crossing, gates opened, traffic passes.                                                                                ::
    ID: 07036099.wav
    Length: 85
** French Level Crossing, pedestrain gate on a level crossing opened & closed.                                                                                ::
    ID: 07036098.wav
    Length: 12
** French Steam Train, light steam engine passing.                                                                                ::
    ID: 07036097.wav
    Length: 30
** French Steam Train, goods train passing with whistle. (Pacific-type engine.)                                                                                ::
    ID: 07036096.wav
    Length: 92
** French Steam Train, goods train passing with whistle. (American locomotive c. 1944.)                                                                                ::
    ID: 07036095.wav
    Length: 116
** French Steam Train, goods train passing at speed.                                                                                ::
    ID: 07036094.wav
    Length: 46
** French Steam Train, interior, constant run at speed. (Slows down at 002m50s.)                                                                                ::
    ID: 07036093.wav
    Length: 189
** French Steam Train, interior, move off into constant run on welded track.                                                                                ::
    ID: 07036092.wav
    Length: 198
** French Steam Train, express train goods train passing at speed with bird song.                                                                                ::
    ID: 07036091.wav
    Length: 74
** French Steam Train, express train passing at speed with bird song.                                                                                ::
    ID: 07036090.wav
    Length: 99
** French Steam Train, express train passing at speed.                                                                                ::
    ID: 07036089.wav
    Length: 40
** French Steam Train, express train passing at speed.                                                                                ::
    ID: 07036088.wav
    Length: 87
** French Steam Train, express train with two engines passing, with slight traffic.                                                                                ::
    ID: 07036087.wav
    Length: 33
** French Steam Train, Fleche d'Or, passing at speed through station at medium speed.                                                                                ::
    ID: 07036086.wav
    Length: 47
** French Steam Train, Fleche d'Or, passing at speed.                                                                                ::
    ID: 07036085.wav
    Length: 28
** French Steam Train, Fleche d'Or, departs station (quiet).                                                                                ::
    ID: 07036084.wav
    Length: 105
** French Steam Train, Fleche d'Or, departs station.                                                                                ::
    ID: 07036083.wav
    Length: 167
** French Steam Train, Paris Express departs from station.                                                                                ::
    ID: 07036082.wav
    Length: 182
** French Steam Train, Paris Express arrives at station.                                                                                ::
    ID: 07036081.wav
    Length: 205
** Boulogne Rail Terminal atmosphere with steam trains.                                                                                ::
    ID: 07036080.wav
    Length: 409
** Gare Maritime, Boulogne, general station atmosphere with steam trains.                                                                                ::
    ID: 07036079.wav
    Length: 403
** French Traffic, atmosphere of traffic on main street.                                                                                ::
    ID: 07036078.wav
    Length: 407
** Cannes Traffic, heavy traffic on main Cannes road, with occasional whistles & atmosphere.                                                                                ::
    ID: 07036077.wav
    Length: 406
** Boulonge Traffic, atmosphere at main harbour intersection.                                                                                ::
    ID: 07036076.wav
    Length: 197
** Calais Traffic, atmosphere with scooters.                                                                                ::
    ID: 07036075.wav
    Length: 199
** Busy French Village Street, atmosphere with cars, horns, occasional quiet periods.                                                                                ::
    ID: 07036074.wav
    Length: 200
** Paris Traffic, with horns.                                                                                ::
    ID: 07036073.wav
    Length: 200
** Prisunic Department Store, general atmosphere.                                                                                ::
    ID: 07036072.wav
    Length: 379
** French Customs Hall, atmosphere in customs hall at Calais.                                                                                ::
    ID: 07036071.wav
    Length: 394
** Boulogne Vegetable Market, general atmosphere.                                                                                ::
    ID: 07036070.wav
    Length: 397
** Calais Market, atmosphere with geese and chicks.                                                                                ::
    ID: 07036069.wav
    Length: 391
** French Snack Bar, atmosphere in a busy snack bar.                                                                                ::
    ID: 07036068.wav
    Length: 392
** French Caf, atmosphere in a busy popular cafe.                                                                                ::
    ID: 07036067.wav
    Length: 413
** French Crowd, animated crowd of men in hall.                                                                                ::
    ID: 07036066.wav
    Length: 459
** French Crowd, subdued crowd of men in hall.                                                                                ::
    ID: 07036065.wav
    Length: 388
** North Sea Gas Rig, interior, mess atmosphere, serving food at hatch.                                                                                ::
    ID: 07036064.wav
    Length: 78
** North Sea Gas Rig, interior, general atmosphere with some voices.                                                                                ::
    ID: 07036063.wav
    Length: 273
** North Sea Gas Rig, mud filter.                                                                                ::
    ID: 07036062.wav
    Length: 56
** North Sea Gas Rig, drilling floor atmosphere.                                                                                ::
    ID: 07036061.wav
    Length: 259
** North Sea Gas Rig, rig background                                                                                ::
    ID: 07036060.wav
    Length: 61
** North Sea Gas Industry, pipe-laying machinery.                                                                                ::
    ID: 07036059.wav
    Length: 118
** North Sea Gas Industry, trench excavator working.                                                                                ::
    ID: 07036058.wav
    Length: 63
** North Sea Gas Industry, pipes rotating on rollers.                                                                                ::
    ID: 07036057.wav
    Length: 33
** North Sea Gas Industry, shop-floor crane lifting finished pipes.                                                                                ::
    ID: 07036056.wav
    Length: 121
** North Sea Gas Industry, final coating of pipes.                                                                                ::
    ID: 07036055.wav
    Length: 96
** North Sea Gas Industry, shot blasting pipes.                                                                                ::
    ID: 07036054.wav
    Length: 77
** North Sea Gas Industry, coating interior of pipes.                                                                                ::
    ID: 07036053.wav
    Length: 95
** North Sea Gas Industry, paintshop, coating pipes.                                                                                ::
    ID: 07036052.wav
    Length: 68
** Oil Drilling, four-wheel drive truck constant run over rough icy ground.                                                                                ::
    ID: 07036051.wav
    Length: 126
** Oil Drilling, seismic camp, truck motors running.                                                                                ::
    ID: 07036050.wav
    Length: 110
** Oil Drilling, skidoo departs.                                                                                ::
    ID: 07036049.wav
    Length: 30
** Oil Drilling, two skidoos passing.                                                                                ::
    ID: 07036048.wav
    Length: 24
** Oil Drilling, general atmosphere with 'sky cranes', helicopters, gulls, etc.                                                                                ::
    ID: 07036047.wav
    Length: 122
** Oil Drilling Rig, exterior.                                                                                ::
    ID: 07036046.wav
    Length: 100
** Oil Drilling Rig, interior.                                                                                ::
    ID: 07036045.wav
    Length: 106
** Oil Exploration, pipes unloaded from lorry. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036044.wav
    Length: 60
** Oil Exploration, large lorry backing slowly to rig. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036043.wav
    Length: 144
** Oil Exploration, atmosphere on oil rig with drill operating. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036042.wav
    Length: 123
** Oil Exploration, rumble of diesel engines, 25 yards from oil rig. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036041.wav
    Length: 56
** Oil Exploration, lorry, approach & pass, 7 second pause, constant run on bumpy road. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036040.wav
    Length: 126
** Oil Exploration, drilling lorry departs. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036039.wav
    Length: 30
** Oil Exploration, shot blast. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036038.wav
    Length: 13
** Oil Exploration, packing charges into drill holes. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036037.wav
    Length: 27
** Oil Exploration, drilling lorries changing bits, drilling starts (at 001m05s). (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036036.wav
    Length: 94
** Oil Exploration, drilling lorries. (Recorded in the Delta Region of Patagonia.)                                                                                ::
    ID: 07036035.wav
    Length: 41
** Fawley Oil Refinery, outdoor alarm signal.                                                                                ::
    ID: 07036034.wav
    Length: 32
** Fawley Oil Refinery, alarm signal sounded.                                                                                ::
    ID: 07036033.wav
    Length: 27
** Fawley Oil Refinery, air fin coolers.                                                                                ::
    ID: 07036032.wav
    Length: 270
** Fawley Oil Refinery, burning off waste gases.                                                                                ::
    ID: 07036031.wav
    Length: 185
** Fawley Oil Refinery, high pressure water pumps.                                                                                ::
    ID: 07036030.wav
    Length: 189
** Fawley Oil Refinery,  heavy duty compressors.                                                                                ::
    ID: 07036029.wav
    Length: 168
** Fawley Oil Refinery. polymerisation plant.                                                                                ::
    ID: 07036028.wav
    Length: 185
** Fawley Oil Refinery, catalytic cracking plant.                                                                                ::
    ID: 07036027.wav
    Length: 184
** Fawley Oil Refinery, principal distillation furnace.                                                                                ::
    ID: 07036026.wav
    Length: 186
** Fawley Oil Refinery, furnace.                                                                                ::
    ID: 07036025.wav
    Length: 179
** Fawley Oil Refinery, Iso-flow furnace in Phenol plant.                                                                                ::
    ID: 07036024.wav
    Length: 186
** Fawley Oil Refinery, steam cracking furnace.                                                                                ::
    ID: 07036023.wav
    Length: 184
** Fawley Oil Refinery, Iso-flow furnace.                                                                                ::
    ID: 07036022.wav
    Length: 187
** German U-Boat, firing 2 pairs of torpedoes.  (World War II German U-Boat manned by British crew.) (Recorded in Torpedo Room.)                                                                                ::
    ID: 07036021.wav
    Length: 51
** German U-Boat, firing torpedo.  (World War II German U-Boat manned by British crew.) (Recorded in Torpedo Room.)                                                                                ::
    ID: 07036020.wav
    Length: 23
** German U-Boat, firing torpedo.  (World War II German U-Boat manned by British crew.) (Recorded in Torpedo Room.)                                                                                ::
    ID: 07036019.wav
    Length: 29
** German U-Boat, general atmosphere in Torpedo Room. (World War II German U-Boat manned by British crew.) (Recorded in Torpedo Room.)                                                                                ::
    ID: 07036018.wav
    Length: 236
** German U-Boat, start diesel engines, ship's telegraph, cruising on surface. (World War II German U-Boat manned by British crew.) (Recorded from Conning Tower.)                                                                                ::
    ID: 07036017.wav
    Length: 409
** German U-Boat, submerged, blowing ballast tanks. (World War II German U-Boat manned by British crew.) (Recorded in Control Room.)                                                                                ::
    ID: 07036016.wav
    Length: 58
** German U-Boat, submerged, cruising underwater running on batteries. (World War II German U-Boat manned by British crew.) (Recorded in Control Room.)                                                                                ::
    ID: 07036015.wav
    Length: 338
** German U-Boat, diesel engines start & run on surface. (World War II German U-Boat manned by British crew.) (Recorded in Control Room.)                                                                                ::
    ID: 07036014.wav
    Length: 142
** German U-Boat, surfacing. (World War II German U-Boat manned by British crew.) (Recorded in Control Room.)                                                                                ::
    ID: 07036013.wav
    Length: 58
** German U-Boat, submerged, diesel engines start & run with snorkel raised. (World War II German U-Boat manned by British crew.) (Recorded in Control Room.)                                                                                ::
    ID: 07036012.wav
    Length: 187
** German U-Boat, cruising on surface, constant run with diesel engines & seawash. (World War II German U-Boat manned by British crew.)                                                                                ::
    ID: 07036011.wav
    Length: 395
** German U-Boat, on surface, reverse diesel engines, stop, into wash. (World War II German U-Boat manned by British crew.) (Recorded on after deck.)                                                                                ::
    ID: 07036010.wav
    Length: 181
** German U-Boat, on surface, start diesel engines, run, slow down & stop. (World War II German U-Boat manned by British crew.) (Recorded on after deck.)                                                                                ::
    ID: 07036009.wav
    Length: 181
** Submarine, control deck atmosphere while submerged, with background orders. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036008.wav
    Length: 219
** Submarine, firing torpedoes with background orders. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036007.wav
    Length: 116
** Submarine, manipulating torpedoes with background orders. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036006.wav
    Length: 52
** Submarine, cruising on surface with seawash & gale. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036005.wav
    Length: 423
** Submarine, surfacing with orders given. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036004.wav
    Length: 293
** Submarine, diving with orders given. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036003.wav
    Length: 393
** Submarine, submerged, engines running. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036002.wav
    Length: 389
** Submarine, cruising on surface, engines running & seawash. (Diesel Electric Submarine, c. 1961.)                                                                                ::
    ID: 07036001.wav
    Length: 395
** Railway Station in Raome, large local station, general atmosphere.                                                                                ::
    ID: 07035170.wav
    Length: 400
** Railway Station in Rome, large local station, electric train arrives & departs.                                                                                ::
    ID: 07035169.wav
    Length: 244
** Italian Railway Station, general atmosphere.                                                                                ::
    ID: 07035168.wav
    Length: 113
** Rome Metropolitana, platform atmosphere, train departs. (Underground railway in Rome.)                                                                                ::
    ID: 07035167.wav
    Length: 202
** Rome Metropolitana, ticket turnstiles, train arrives. (Underground railway in Rome.)                                                                                ::
    ID: 07035166.wav
    Length: 198
** Termini Railway Station, Rome, platform atmosphere.                                                                                ::
    ID: 07035165.wav
    Length: 413
** Termini Railway Station, Rome, general atmosphere.                                                                                ::
    ID: 07035164.wav
    Length: 197
** Termini Railway Station, Rome, booking hall atmosphere.                                                                                ::
    ID: 07035163.wav
    Length: 197
** Termini Railway Station, Rome, atmosphere outside station.                                                                                ::
    ID: 07035162.wav
    Length: 320
** Rome, tramcar approach, stop & depart.                                                                                ::
    ID: 07035161.wav
    Length: 64
** Rome, atmosphere at a road junction.                                                                                ::
    ID: 07035160.wav
    Length: 225
** Rome, light traffic actuality.                                                                                ::
    ID: 07035159.wav
    Length: 159
** Rome, fast traffic actuality.                                                                                ::
    ID: 07035158.wav
    Length: 198
** Via Veneto, Rome, street atmosphere.                                                                                ::
    ID: 07035157.wav
    Length: 195
** Via Appia, Rome, street atmosphere.                                                                                ::
    ID: 07035156.wav
    Length: 186
** Rome, atmosphere in public gardens with cicadas.                                                                                ::
    ID: 07035155.wav
    Length: 200
** San Paolo Basilica, Rome, atmosphere in cloisters.                                                                                ::
    ID: 07035154.wav
    Length: 195
** San Paolo Basilicia, Rome, interior, general atmosphere.                                                                                ::
    ID: 07035153.wav
    Length: 206
** Piazza Novona, Rome, exterior, mainly boys playing in piazza.                                                                                ::
    ID: 07035152.wav
    Length: 204
** Piazza Novana, Rome, exterior, mainly girls playing in piazza.                                                                                ::
    ID: 07035151.wav
    Length: 203
** Vatican, exterior, crowds disperse at end of Pope's speech with tolling bell, other bells join in.                                                                                ::
    ID: 07035150.wav
    Length: 204
** Vatican, exterior, throng of people on steps of St. Peter's Basilica.                                                                                ::
    ID: 07035149.wav
    Length: 210
** Italian crowd, exterior, murmuring crowd.                                                                                ::
    ID: 07035148.wav
    Length: 196
** Rome, fairground dodgems.                                                                                ::
    ID: 07035147.wav
    Length: 201
** Italian Crowd, exterior, very large crowd with cheers at beginning.                                                                                ::
    ID: 07035146.wav
    Length: 169
** Italian Crowd, exterior, large & very excited, with cheers, shrieks & whistles.                                                                                ::
    ID: 07035145.wav
    Length: 214
** Caracalla, interior, crowds leaving after performance.                                                                                ::
    ID: 07035144.wav
    Length: 145
** Caracalla, interior, applause & atmosphere at end of performance.                                                                                ::
    ID: 07035143.wav
    Length: 119
** Caracalla, interior, applause & atmosphere at end of act.                                                                                ::
    ID: 07035142.wav
    Length: 111
** Caracalla, interior, gong sounds, auditorium atmosphere.                                                                                ::
    ID: 07035141.wav
    Length: 204
** Caracalla, interior, crowds enter forum with programme sellers & speech of foreign tourists.                                                                                ::
    ID: 07035140.wav
    Length: 204
** Outdoor Coffee Bar, Caracella, general atmosphere.                                                                                ::
    ID: 07035139.wav
    Length: 385
** Cafe Alemagna, Rome, general atmosphere.                                                                                ::
    ID: 07035138.wav
    Length: 395
** Rome Market, general atmosphere.                                                                                ::
    ID: 07035137.wav
    Length: 399
** News Boy in an Italian market.                                                                                ::
    ID: 07035136.wav
    Length: 86
** Melon Seller in an Italian market.                                                                                ::
    ID: 07035135.wav
    Length: 68
** Fiumicio Fish Market, general atmosphere.                                                                                ::
    ID: 07035134.wav
    Length: 197
** Irvin-Bell helicopter, start, revving, hover, land. (Model unknown.)                                                                                :Aircraft:Helicopters:
    ID: 07035133.wav
    Length: 148
** Sikorsky S-55, interior, descent, hover, ascending.                                                                                ::
    ID: 07035132.wav
    Length: 127
** Sikorsky S-55, interior, descent, land, switch off.                                                                                ::
    ID: 07035131.wav
    Length: 125
** Sikorsky S-55, interior, start, warm up, take off into constant flight.                                                                                ::
    ID: 07035130.wav
    Length: 258
** Sikorsky S-51, approach, hover, land, switch off.                                                                                ::
    ID: 07035129.wav
    Length: 82
** Sikorsky S-51, revving, take off.                                                                                ::
    ID: 07035128.wav
    Length: 88
** Sikorsky S-51, start, tick over.                                                                                ::
    ID: 07035127.wav
    Length: 130
** Fairey Rotodyne, approach from distance, land, runs down jets. (Prototype helicopter with 2 Napier prop jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035126.wav
    Length: 341
** Fairey Rotodyne, passing overhead. (Prototype helicopter with 2 Napier prop jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035125.wav
    Length: 25
** Fairey Rotodyne, test rig, rotor tip impulse jet motor operating. (Prototype helicopter with 2 Napier prop jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035124.wav
    Length: 155
** Fairey Rotodyne, prop engines revving, rotor tip motors start (at 001m05s), take off (at 001m50s), depart. (Prototype helicopter with 2 Napier prop jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035123.wav
    Length: 225
** Fairey Rotodyne, approach, hover, pass overhead. (Prototype helicopter with 2 Napier prop jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035122.wav
    Length: 101
** Fairey Rotodyne, prop jet engines start, revving. (Prototype helicopter with 2 Napier prop jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035121.wav
    Length: 245
** Fairey Ultralite, exterior, start jet engine, rotor tip motor (after 001m40s), take off, hover, depart. (2-seater helicopter with jet engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035120.wav
    Length: 342
** Fairey Ultralite, exterior, approach, hover, circle, depart. (2-seater helicopter with jet engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035119.wav
    Length: 145
** Fairey Ultralite, exterior, land & switch off. (2-seater helicopter with jet engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035118.wav
    Length: 92
** Fairey Ultralite, exterior, start jet engine, rotor tip motor (after 001m00s), switch off. (Ground test of helicopter.) (2-seater helicopter with jet engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035117.wav
    Length: 98
** Westland Lynx, exterior, take off, move away, hover and fade into distance. (Anglo-French prototype helicopter with two 1800 h.p. jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035116.wav
    Length: 385
** Westland Lynx, exterior, run up engines for take off, blades rotate. (Anglo-French prototype helicopter with two 1800 h.p. jet engines.)                                                                                :Aircraft:Helicopters:
    ID: 07035115.wav
    Length: 391
** Westland Widgeon, exterior, approach, land (at 001m50s), take off, manoeuvre & land, switch off. (4-seater executive helicopter, Alvis Leonides piston engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035114.wav
    Length: 274
** Westland Widgeon, exterior, start, take off, hover, depart. (4-seater executive helicopter, Alvis Leonides piston engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035113.wav
    Length: 101
** Westland Widgeon, interior, start, take off, constant flight, land, switch off. (4-seater executive helicopter, Alvis Leonides piston engine.)                                                                                 :Aircraft:Helicopters:
    ID: 07035112.wav
    Length: 408
** Westland Whirlwind, exterior, two helicopters circling. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035111.wav
    Length: 209
** Westland Whirlwind, exterior, helicopter circling. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035110.wav
    Length: 201
** Westland Whirlwind, exterior, passing overhead. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035109.wav
    Length: 68
** Westland Whirlwind, exterior, passing overhead. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035108.wav
    Length: 42
** Westland Whirlwind, exterior, approach and land. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035107.wav
    Length: 102
** Westland Whirlwind, exterior, start, take off. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035106.wav
    Length: 116
** Westland Whirlwind, interior, constant flight. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035105.wav
    Length: 391
** Westland Whirlwind, interior, land, switch off. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035104.wav
    Length: 212
** Westland Whirlwind, interior, start, take off into constant flight. (10-seater helicopter with 1 Bristol Siddeley Gnome turbine.)                                                                                :Aircraft:Helicopters:
    ID: 07035103.wav
    Length: 213
** Westland Wessex mark 2, exterior, circling overhead. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035102.wav
    Length: 183
** Westland Wessex mark 2, exterior, circling overhead. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035101.wav
    Length: 155
** Westland Wessex mark 2, exterior, passing overhead. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035100.wav
    Length: 57
** Westland Wessex mark 2, exterior, start, run engines on ground, switch off. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035099.wav
    Length: 232
** Westland Wessex mark 2, exterior, land, switch off. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035098.wav
    Length: 120
** Westland Wessex mark 2, exterior, start, take off. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035097.wav
    Length: 90
** Westland Wessex mark 2, interior, constant flight. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035096.wav
    Length: 392
** Westland Wessex mark 2, interior, land, switch off. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035095.wav
    Length: 178
** Westland Wessex mark 2, interior, start, take off. (16-seater helicopter with 2 Bristol Siddeley Gnome turbines.)                                                                                :Aircraft:Helicopters:
    ID: 07035094.wav
    Length: 214
** Brantley 305, interior, start, take off into constant flight, land, switch off. (5-seater helicopter.)                                                                                :Aircraft:Helicopters:
    ID: 07035093.wav
    Length: 358
** Brantley 305, interior, 2 false starts. (5-seater helicopter.)                                                                                :Aircraft:Helicopters:
    ID: 07035092.wav
    Length: 34
** Brantley B2B, interior, start, take off into constant flight, land, switch off. (2-seater helicopter with 3 bladed rotor, 180 h.p. Lycoming engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035091.wav
    Length: 390
** Brantley B2B, exterior, passing overhead. (2-seater helicopter with 3 bladed rotor, 180 h.p. Lycoming engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035090.wav
    Length: 67
** Brantley B2B, exterior, passing overhead. (2-seater helicopter with 3 bladed rotor, 180 h.p. Lycoming engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035089.wav
    Length: 68
** Brantley B2B, exterior, approach, land, switch off. (2-seater helicopter with 3 bladed rotor, 180 h.p. Lycoming engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035088.wav
    Length: 78
** Brantley B2B, exterior, start, take off. (2-seater helicopter with 3 bladed rotor, 180 h.p. Lycoming engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035087.wav
    Length: 84
** Brantley B2B, exterior, approach, land, switch off. (2-seater helicopter with 3 bladed rotor, 180 h.p. Lycoming engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035086.wav
    Length: 112
** Brantley B2B, exterior, start, warm up, take off. (2-seater helicopter with 3 bladed rotor, 180 h.p. Lycoming engine.)                                                                                :Aircraft:Helicopters:
    ID: 07035085.wav
    Length: 252
** Bristol Sycamore S171, exterior, approach, hover, depart.                                                                                :Aircraft:Helicopters:
    ID: 07035084.wav
    Length: 178
** Bristol Sycamore S171, exterior, approach & pass.                                                                                :Aircraft:Helicopters:
    ID: 07035083.wav
    Length: 87
** Bristol Sycamore S171, exterior, approach & pass.                                                                                :Aircraft:Helicopters:
    ID: 07035082.wav
    Length: 93
** Bristol Sycamore S171, exterior, several helicopters circling overhead.                                                                                :Aircraft:Helicopters:
    ID: 07035081.wav
    Length: 146
** Bristol Sycamore S171, exterior, approach, land, switch off.                                                                                :Aircraft:Helicopters:
    ID: 07035080.wav
    Length: 130
** Bristol Sycamore S171, exterior, start, warm up, take off & depart.                                                                                :Aircraft:Helicopters:
    ID: 07035079.wav
    Length: 144
** Bristol Sycamore S171, exterior, approach, hover, descend, land, switch off.                                                                                :Aircraft:Helicopters:
    ID: 07035078.wav
    Length: 246
** Bristol Sycamore S171, exterior, start, warm up, take off & depart.                                                                                :Aircraft:Helicopters:
    ID: 07035077.wav
    Length: 137
** Bristol Sycamore S171, interior, start, warm up, take off into constant flight, descend, land, switch off.                                                                                :Aircraft:Helicopters:
    ID: 07035076.wav
    Length: 359
** Large crowd cheering continuously.                                                                                ::
    ID: 07035075.wav
    Length: 164
** Large crowd cheering.                                                                                ::
    ID: 07035074.wav
    Length: 38
** Large crowd cheering.                                                                                ::
    ID: 07035073.wav
    Length: 27
** 100 men, single cheer.                                                                                ::
    ID: 07035072.wav
    Length: 15
** 100 men, single cheer.                                                                                ::
    ID: 07035071.wav
    Length: 9
** 100 men, single cheer.                                                                                ::
    ID: 07035070.wav
    Length: 12
** 100 men, prolonged cheer.                                                                                ::
    ID: 07035069.wav
    Length: 15
** 100 men, prolonged cheer.                                                                                ::
    ID: 07035068.wav
    Length: 15
** 100 men, single cheer.                                                                                ::
    ID: 07035067.wav
    Length: 12
** 100 men, single cheer.                                                                                ::
    ID: 07035066.wav
    Length: 7
** Coach Horn, sounded three times.                                                                                ::
    ID: 07035065.wav
    Length: 21
** Coach Horn, sounded twice.                                                                                ::
    ID: 07035064.wav
    Length: 15
** Coach Horn, sounded three times.                                                                                ::
    ID: 07035063.wav
    Length: 31
** Coach Horn, sounded four times.                                                                                ::
    ID: 07035062.wav
    Length: 23
** Coach Horn, sounded three times.                                                                                ::
    ID: 07035061.wav
    Length: 43
** Coach Horn, sounded three times.                                                                                ::
    ID: 07035060.wav
    Length: 23
** Coach Horn, sounded three times.                                                                                ::
    ID: 07035059.wav
    Length: 23
** Coach Horn, sounded three times.                                                                                ::
    ID: 07035058.wav
    Length: 29
** Coach Horn, sounded once.                                                                                ::
    ID: 07035057.wav
    Length: 10
