** Devon hedgerow, dawn - stream, birdsong, occasional sheep, 1973 (1B5, reprocessed)                                                                                :Atmospheres:Dawn:
    ID: 07062121.wav
    Length: 361
** Dawn chorus, with distant cock crow, 1972 (1B3, reprocessed)                                                                                :Atmospheres:Dawn:
    ID: 07062120.wav
    Length: 300
** Woodland edge, summer - recorded in Wales, distant jet aircraft, 1980 (1B8, reprocessed) (technical note: to be used at low level)                                                                                :Atmospheres:Summer:
    ID: 07062119.wav
    Length: 219
** Woodland edge, June, early morning - thrushes and willow warblers predominate, occasional crow, 1979 (1B14, reprocessed)                                                                                :Atmospheres:Summer:
    ID: 07062118.wav
    Length: 303
** Woodland edge, March - with robins, great tits and jays, distant traffic, 1981 (1B15 , reprocessed) (technical note: to be used at low level)                                                                                :Atmospheres:Woodland:
    ID: 07062117.wav
    Length: 302
** Woodland, March, early morning - birdsong, raindrops on leaves, some distant traffic, 1978 (1B11, reprocessed)                                                                                :Atmospheres:Woodland:
    ID: 07062116.wav
    Length: 301
** Woodland, February, daytime - distant traffic, distant aircraft, 1981 (1B7, reprocessed) (technical note: to be used at low level)                                                                                :Atmospheres:Woodland:
    ID: 07062115.wav
    Length: 301
** Woodland, dusk wind in trees, birdsong, distant light aircraft, bee buzzing, 1972 (1B10, reprocessed)                                                                                :Atmospheres:Woodland:
    ID: 07062114.wav
    Length: 301
** Woodland, daytime -  with birdsong, 1972 (1B1, reprocessed) (technical note: to be used at low level)                                                                                :Atmospheres:Woodland:
    ID: 07062113.wav
    Length: 302
** Woodland, daytime - blustery wind in trees, birdsong, creaking tree, 1972 (1B10 ,reprocessed)                                                                                :Atmospheres:Woodland:
    ID: 07062112.wav
    Length: 300
** Atmosphere at a jumble sale - 1979 (1C19,reprocessed)                                                                                :Jumble Sales:
    ID: 07062111.wav
    Length: 285
** Jumble sale in a large hall - 1983 (1C30,reprocessed)                                                                                :Jumble Sales:
    ID: 07062110.wav
    Length: 281
** Mixed crowd in hotel foyer - 1982 (1C28)                                                                                :Foyers:
    ID: 07062109.wav
    Length: 300
** Quiet hotel foyer atmosphere, traffic and indistinctive speech - 1981 (1C22,reprocessed)                                                                                :Foyers:
    ID: 07062108.wav
    Length: 297
** Busy hotel foyer atmosphere - 1981 (1C22,reprocessed)                                                                                :Foyers:
    ID: 07062107.wav
    Length: 310
** Trolley passing in hospital corridor - 1966 (55E,reprocessed)                                                                                :Trolleys:
    ID: 07062106.wav
    Length: 23
** Trolley passing in hospital corridor - 1966 (55E,reprocessed)                                                                                :Trolleys:
    ID: 07062105.wav
    Length: 20
** Pulse monitor, speeding up, continuous - 1985 (3H4,reprocessed)                                                                                :Pulse Monitors:
    ID: 07062104.wav
    Length: 110
** Quiet male and female conversation at visiting time, approximately 30 people - 1981 (3H1,reprocessed)                                                                                :Hospitals:
    ID: 07062103.wav
    Length: 302
** Activity in a hospital corridor - 1981 (3H1,reprocessed)                                                                                :Hospitals:
    ID: 07062102.wav
    Length: 296
** Hospital outpatients reception atmosphere with adults and children - 1981 (3H3,reprocessed)                                                                                :Hospitals:
    ID: 07062101.wav
    Length: 298
** Hospital casualty reception atmosphere, with speech and occasional telephone - 1981 (3H3,reprocessed)                                                                                :Hospitals:
    ID: 07062100.wav
    Length: 315
** Constant background of indistinct speech with occasional footsteps in a courtroom - 1966 (37A,reprocessed)                                                                                :Courtrooms:
    ID: 07062099.wav
    Length: 272
** Atmosphere in a room with computer disc drives and heavy air conditioning, with steady roar of equipment and intermittent quiet bleeps - 1982 (2N1,reprocessed)                                                                                :Air Conditioning:
    ID: 07062098.wav
    Length: 300
** Atmosphere in a club boatyard with general movement and some distinct speech - 1967 (136A,reprocessed)                                                                                :Boats:Boatyards:
    ID: 07062097.wav
    Length: 238
** Atmosphere in an amusement arcade - 1985 (2N2,reprocessed)                                                                                :Fairgrounds:Amusement Arcades:
    ID: 07062096.wav
    Length: 300
** First floor lounge, Terminal III, Heathrow, atmosphere with occasional tannoy - 1972 (1C9,reprocessed))                                                                                :Airports:Heathrow:
    ID: 07062095.wav
    Length: 240
** Ground floor, Terminal III Heathrow, lively acoustic, footsteps, voices, movement and indistinct tannoy - 1972 (1C9,reprocessed))                                                                                :Airports:Heathrow:
    ID: 07062094.wav
    Length: 227
** Mule train passes (left to right)with sound of bells, hooves and shouts from minders, Himalayas, near Annapurna, Nepal                                                                                :Nepal:
    ID: 07062093.wav
    Length: 83
** Mules with bells and minders chatting and shouting, preparing animals for journey, Himalayas, near Annapurna, Nepal                                                                                :Nepal:
    ID: 07062092.wav
    Length: 201
** One tiger snarling and growling with others in background                                                                                :Nepal:
    ID: 07062091.wav
    Length: 92
** 2 Indian elephants growling and trumpeting, with some footsteps in undergrowth,chewing noises                                                                                :Animals:Elephants:
    ID: 07062090.wav
    Length: 165
** Indian elephant trumpeting, no background                                                                                :Animals:Elephants:
    ID: 07062089.wav
    Length: 35
** Indian elephant growling, no background                                                                                :Animals:Elephants:
    ID: 07062088.wav
    Length: 56
** Dry-scrub woodland, winter, late afternoon, Haleji Lake, Pakistan, with bulbuls,warblers, moorhen and other birds, insects buzzing, cicada chorus                                                                                :Atmospheres:Afternoon:
    ID: 07062087.wav
    Length: 267
** Lakeside oasis, mid-afternoon, winter, Kirtha Ra National Park, Pakistan, many frogs,some close-up, also birds, insects and wind in trees                                                                                :Atmospheres:Afternoon:
    ID: 07062086.wav
    Length: 245
** Dry deciduous woodland, midday, winter, Lal Suhanra, Pakistan, many collared dovesand insects, other birds in background                                                                                :Atmospheres:Morning:
    ID: 07062085.wav
    Length: 279
** Dry deciduous woodland, winter, early morning, Lal Suhanra, Pakistan, very busy, with some close up calls from bulbuls,crow-pheasant, mynahs, parakeets, warblers, doves and treepies                                                                                :Atmospheres:Morning:
    ID: 07062084.wav
    Length: 252
** Dry, deciduous woodland, midday, late winter, Lal Suhanra, Pakistan, many birdscalling including house-crows and ring-necked parakeets                                                                                :Atmospheres:Midday:
    ID: 07062083.wav
    Length: 284
** Dry deciduous woodland, midday, late winter, Lal Suhanra, Pakistan with insects,collared doves, bulbuls, little green bee-eaters and other birds                                                                                :Atmospheres:Midday:
    ID: 07062082.wav
    Length: 251
** Water birds, Ranganathittu Bird Sanctuary, with cormorants, asian darter and spoonbill                                                                                :Birds:
    ID: 07062081.wav
    Length: 257
** Fruit bats and painted storks, Ranganathittu Bird Sanctuary, Tamil Nadu                                                                                :Animals:Bats:
    ID: 07062080.wav
    Length: 262
** Birds, Madumbalai National Park, early morning with close-up partridge calls, warblers, crow-pheasants and house crow                                                                                :Birds:
    ID: 07062079.wav
    Length: 252
** Birds at watering hole, Madumbalai National Park, early morning with red-wattled lapwing, warblers, crow-pheasant, black kite, house-crow and cicadas                                                                                :Birds:
    ID: 07062078.wav
    Length: 248
** Birds at watering hole, Madumbalai National Park, Tamil Nadu, late afternoon with mynahs, barbets, parakeets, bulbuls and crickets                                                                                :Birds:
    ID: 07062077.wav
    Length: 231
** Dawn chorus, Madumbalai National Park, Tamil Nadu (S India)with bird song,parakeets, bulbuls and insects                                                                                :Atmospheres:Dawn:
    ID: 07062076.wav
    Length: 286
** Pioneer railway, external, tickover with chat from children and hisses from train-train departs 1'08" (indexed)                                                                                :Children:Playing:
    ID: 07062075.wav
    Length: 100
** Pioneer railway, internal, (narrow-gauge railway across Buda Hills run by school children), starts, constant run with hooter and muted chat, stops                                                                                :Trains:Hooters:
    ID: 07062074.wav
    Length: 195
** Long-distance train (Budapest to Pecs), internal, starts, constant run, stops                                                                                :Trains:Hungary:
    ID: 07062073.wav
    Length: 231
** Metro, internal, constant run (Deli Palyaudvar to Batthyany Ter with stops and starts with PA announcements and door noise, some muted speech                                                                                :Trains:Hungary:
    ID: 07062072.wav
    Length: 192
** Tram, internal, Budapest, constant run with stops and starts, doors opening and closing, some quiet speech                                                                                :Trams:Hungary:
    ID: 07062071.wav
    Length: 294
** Train station, Pecs, forecourt, with indistinct PA announcements and bells, speech,footsteps and occasional train noise                                                                                :Bells:Hungary:
    ID: 07062070.wav
    Length: 258
** Bus station, Pecs, fairly quiet, with footsteps, speech and some bus noise                                                                                :Buses:Hungary:
    ID: 07062069.wav
    Length: 228
** Metro station ticket office at Deli Palyaudvar near top of escalator, busy, with footsteps,ticket barrier noise and escalator noise                                                                                :Escalators:
    ID: 07062068.wav
    Length: 273
** Thermal baths, "Thermal Hotel", St Margarets Island, with splashes, some indistinct speech, hum from heater                                                                                :Baths:Hungary:
    ID: 07062067.wav
    Length: 252
** Open-air swimming pool, St Margarets Island (Budapest), noisy, with children splashing and playing (distinct speech),clunks of diving board, generator noise                                                                                :Swimming Pools:
    ID: 07062066.wav
    Length: 245
** Bank, Budapest, fairly busy, with distinct speech, bangs of document stamping, print-out noises, phones, and faint exterior traffic                                                                                :Banks:
    ID: 07062065.wav
    Length: 228
** Supermarket, Budapest, busy, with speech and trolley noise                                                                                :Trolleys:
    ID: 07062064.wav
    Length: 220
** Fruit and vegetable market (covered), Pecs, large and echoey, with speech, footsteps,bangs, distant traffic                                                                                :Markets:Vegetable:
    ID: 07062063.wav
    Length: 252
** Shopping arcade (covered), Budapest, echoey, with footsteps and some indistinct speech (including noisy child near end)                                                                                :Shops:Hungary:
    ID: 07062062.wav
    Length: 217
** Traffic, Moscva Ter, Budapest, with heavy traffic, including lots of trams, also footsteps and speech                                                                                :Traffic:Hungary:
    ID: 07062061.wav
    Length: 325
** Cafe, Pecs (small town in southern Hungary), loud speech, some kitchen noise                                                                                :Cafes:Hungary:
    ID: 07062060.wav
    Length: 215
** Bar, Abaliget (village in southern Hungary) with animated chat (including children) radio, clinks, some exterior traffic noise                                                                                :Bars:
    ID: 07062059.wav
    Length: 261
** Livestock Market, interior, general atmosphere in market, calf auction heard in background, with some metalic bangs & chatter.                                                                                :Auctions:Livestock:
    ID: 07062058.wav
    Length: 173
** Livestock Market, interior, cattle in pens at market with some distant conversation & lots of animal noise.                                                                                :Cattle:
    ID: 07062057.wav
    Length: 153
** Sheep Auction, interior, some animal noise, very low level vehicle noise & lots of general chatter.                                                                                :Auctions:Livestock:
    ID: 07062056.wav
    Length: 217
** Calf Auction, interior, with lots of animal noise.                                                                                :Auctions:Livestock:
    ID: 07062055.wav
    Length: 372
** Cow & Calf Auction, interior, with some distinct speech. (Recorded near ring.)                                                                                :Auctions:Livestock:
    ID: 07062054.wav
    Length: 250
** Poultry Auction, interior, with some distinct speech.                                                                                :Auctions:Livestock:
    ID: 07062053.wav
    Length: 79
** Cattle, exterior, calves out of trailer.                                                                                :Animals:Farm:Cattle:
    ID: 07062052.wav
    Length: 29
** Cattle, calves loaded/unloaded from trailer, rear tailgate opened/closed, straw spread, calves loaded, faint wind in trees.                                                                                :Animals:Farm:Cattle:
    ID: 07062051.wav
    Length: 75
** Cattle, cows walking down muddy lane, lots of moos. (Close perspective recording, ends abruptly.)                                                                                :Animals:Farm:Cattle:
    ID: 07062050.wav
    Length: 38
** Cattle, interior, young calves feeding from buckets in sheds, one sucking through teat out of bucket (close perspective), calf scampers in straw, young calf moos, older calves moo, with occasional dogs in distance.                                                                                :Buckets:
    ID: 07062049.wav
    Length: 184
** Cattle, cows mooing in yard with some birdsong, loud moo (close perspective), others move round yard.                                                                                :Animals:Farm:Cattle:
    ID: 07062048.wav
    Length: 92
** Cattle, cow startled in cattle crush, makes loud complaining moo.                                                                                :Animals:Farm:Cattle:
    ID: 07062047.wav
    Length: 5
** Cattle, TB testing in yard, with lots of mooing from cows & noise from cattle crush, with occasional gusts of wind in trees & birds singing.                                                                                :Birds:
    ID: 07062046.wav
    Length: 290
** Goats mating, with other goats bleating in background & some wind in trees. (Perspective varies as goats move around in front of microphone.)                                                                                :Animals:Goats:
    ID: 07062045.wav
    Length: 91
** Goats, exterior, billy calling to nanny. (British Saanen goat.)                                                                                :Animals:Goats:
    ID: 07062044.wav
    Length: 4
** Sheep, exterior, sheep unloaded at market, lots of animal noise. (Wide stereo image.)                                                                                :Markets:Animals:
    ID: 07062043.wav
    Length: 55
** Sheep, one sheep being sheared with some noise from sheep. (Close perspective recording, length of track equals time taken to shear one sheep.)                                                                                :Animals:Sheep:
    ID: 07062042.wav
    Length: 200
** Sheep, exterior, sheep run past on concrete, with some wind in trees.                                                                                :Animals:Sheep:
    ID: 07062041.wav
    Length: 9
** Sheep, exterior, sheep scurry past (with no animal sounds).                                                                                :Animals:Sheep:
    ID: 07062040.wav
    Length: 20
** Sheep, one lamb bleating in barn with occasional reply from ewe from outside, some birds in background. (Recorded inside barn.)                                                                                :Birds:
    ID: 07062039.wav
    Length: 94
** Sheep, 30 to 50 ewes & lambs calling in field, scattered then approach, food bucket shaken, food into troughs, one lamb bleats on own, loud bleats. (Cows & birds heard occassionally in background.)                                                                                :Animals:Sheep:
    ID: 07062038.wav
    Length: 352
** Sheep, flock of sheep run up lane with lots of wind in trees, gate opening.                                                                                :Gates:
    ID: 07062037.wav
    Length: 51
** Chickens, exterior, cockerel & hens scratching in grass for corn, with some very gentle wind in trees & aircraft briefly heard in distance. (Close perspective recording.)                                                                                :Birds:Chickens:
    ID: 07062036.wav
    Length: 104
** Chickens, interior, hens disturbed in hen-house, very close flap of wings, lots of thuds as hens move around.                                                                                :Birds:Chickens:
    ID: 07062035.wav
    Length: 56
** Chickens, loud cockerel, hens moving round hen-house, with some wind in trees & dog barking occasionally in background. (Microphone outside hen-house.)                                                                                :Birds:Chickens:
    ID: 07062034.wav
    Length: 61
** Turkeys, interior, general atmosphere of turkey hens.                                                                                :Birds:Turkeys:
    ID: 07062033.wav
    Length: 86
** Turkeys, interior, six month old turkeys general atmosphere (ends abruptly).                                                                                :Birds:Turkeys:
    ID: 07062032.wav
    Length: 25
** Turkeys, interior, six month old turkeys, mostly stags (males), startled at 0m17s.                                                                                :Birds:Turkeys:
    ID: 07062031.wav
    Length: 50
** Turkeys, interior, eight month old turkeys, mostly hens (females). (Close perspective recording.)                                                                                :Birds:Turkeys:
    ID: 07062030.wav
    Length: 120
** Chimpanzees, close up calls.                                                                                :Africa:Gambia:
    ID: 07062029.wav
    Length: 18
** Wildebeest, several grazing & grunting, with birds & insects in background.                                                                                :Africa:Kenya:
    ID: 07062028.wav
    Length: 124
** Chacma Baboons, male chasing another, with background.                                                                                :Animals:Baboons:
    ID: 07062027.wav
    Length: 16
** Chacma Baboons, juveniles screaming, with background.                                                                                :Animals:Baboons:
    ID: 07062026.wav
    Length: 36
** Chacma Baboon, juvenile screaming, with background.                                                                                :Animals:Baboons:
    ID: 07062025.wav
    Length: 18
** Chacma Baboon, adult calling.                                                                                :Animals:Baboons:
    ID: 07062024.wav
    Length: 10
** Chacma Baboons, two juveniles playing, with background.                                                                                :Animals:Baboons:
    ID: 07062023.wav
    Length: 24
** Zebra, close up calls from single animal, with background.                                                                                :South Africa:
    ID: 07062022.wav
    Length: 13
** Zebra, middle distance calling from single animal.                                                                                :South Africa:
    ID: 07062021.wav
    Length: 24
** Elephants trumpeting & breaking branches.                                                                                :Africa:Kenya:
    ID: 07062020.wav
    Length: 10
** Elephant close up, others in background. (Elephants recorded in captivity, some slight scho from walls.)                                                                                :Animals:Elephants:
    ID: 07062019.wav
    Length: 57
** Wart Hogs, close up growls & snarls from several animals.                                                                                :South Africa:
    ID: 07062018.wav
    Length: 180
** Leopards, close up, growling & breathing.                                                                                :Animals:Leopards:
    ID: 07062017.wav
    Length: 75
** Cheetahs, close up purring from several animals, with some movement sounds.                                                                                :Animals:Cheetahs:
    ID: 07062016.wav
    Length: 46
** Lions roaring, with crickets in background.                                                                                :Africa:
    ID: 07062015.wav
    Length: 44
** Male lion roaring (with clean background).                                                                                :Africa:
    ID: 07062014.wav
    Length: 98
** Lions with insect chorus, in tropical evergreen forest at dusk.                                                                                :Africa:Gambia:
    ID: 07062013.wav
    Length: 51
** Kenya: Lakes Naivasha early morning atmosphere, with birds - including hoopoe & boubou shrike.                                                                                :Africa:Kenya:
    ID: 07062012.wav
    Length: 274
** Kenya: Lakes Naivasha daytime atmosphere, with hippo grunting & snorting, coots, grebes & hoopoe in background.                                                                                :Africa:Kenya:
    ID: 07062011.wav
    Length: 205
** Kenya: Lake Nakuru morning atmosphere with flamingoes.                                                                                :Africa:Kenya:
    ID: 07062010.wav
    Length: 213
** Kenya: Amboeseli National Park early morning atmosphere, doves & Go-Away birds.                                                                                :Africa:Kenya:
    ID: 07062009.wav
    Length: 256
** Rwanda: Early evening tropical rain forest atmosphere, with marsh & tree frogs & insects.                                                                                :Africa:Rwanda:
    ID: 07062008.wav
    Length: 216
** Zaire: Late evening marshy jungle atmosphere, with tree frogs & crickets.                                                                                :Africa:Zaire:
    ID: 07062007.wav
    Length: 346
** Central African Republic: Bangui, early evening tropical rain forest atmosphere, with insects. (Recorded near Bangui.)                                                                                :Africa:Central African Republic:
    ID: 07062006.wav
    Length: 221
** Senegal: Suleti water holes on savanna (during dry season, with insects & birds (cicadas, purple starlings, distant red-beaked hornbills & doves).                                                                                :Africa:Senegal:
    ID: 07062005.wav
    Length: 302
** Cameroon: Tropical rain forest atmosphere, with turaco birds, insects & tree frogs.                                                                                :Africa:Cameroun:
    ID: 07062004.wav
    Length: 300
** Cameroon: Yaounde, mid afternoon tropical rain forest atmosphere, with crickets, tree frogs & rain on big leaves. (Just south of Yaounde.)                                                                                :Africa:Cameroun:
    ID: 07062003.wav
    Length: 205
** Cameroon: Kribi, mid morning tropical rain forest atmosphere, with birds & insects.                                                                                :Africa:Cameroun:
    ID: 07062002.wav
    Length: 232
** Cameroon: Kribi, early evening tropical rain forest atmosphere, with insects & frogs.                                                                                :Africa:Cameroun:
    ID: 07062001.wav
    Length: 172
** Slower pass through station.                                                                                :Trains:Stations:
    ID: 07061134.wav
    Length: 41
** Fast pass through station.                                                                                :Trains:High Speed:
    ID: 07061133.wav
    Length: 32
** Fast pass under bridge with hooter (Eurostar)                                                                                :Trains:Bridges:
    ID: 07061132.wav
    Length: 32
** Eurostar train arrives on distant platform.                                                                                :Trains:Stations:Waterloo International:
    ID: 07061131.wav
    Length: 91
** Eurostar train arrives.                                                                                :Trains:Stations:Waterloo International:
    ID: 07061130.wav
    Length: 130
** Doors close, Eurostar departs (train departs 0.56")                                                                                :Trains:Doors And Windows:
    ID: 07061129.wav
    Length: 176
** Eurostar train departs (close-up to train)                                                                                :Trains:Stations:Waterloo International:
    ID: 07061128.wav
    Length: 94
** Empty platform (distant Eurostar departs)                                                                                :Trains:Stations:Waterloo International:
    ID: 07061127.wav
    Length: 45
** Drivers cabin - driver's conversation on intercom (French)                                                                                :Trains:Eurostar:
    ID: 07061126.wav
    Length: 42
** Drivers cabin - train travelling at speed.                                                                                :Trains:Eurostar:
    ID: 07061125.wav
    Length: 150
** Drivers cabin - train moves off into slow run, with some French conversation.                                                                                :Trains:Eurostar:
    ID: 07061124.wav
    Length: 326
** Train entering Channel Tunnel with prior announcement (Second class compartments)                                                                                :Trains:Tunnels:
    ID: 07061123.wav
    Length: 211
** Train travelling in France (Second class compartment)                                                                                :Trains:Eurostar:
    ID: 07061122.wav
    Length: 250
** Second class compartment before departure (announcements at 0'40", door close signal at 2'14")                                                                                :Trains:Eurostar:
    ID: 07061121.wav
    Length: 189
** Gard du Nord station departure lounge.                                                                                :Trains:Stations:France:
    ID: 07061120.wav
    Length: 108
** Gard du Nord station concourse.                                                                                :Trains:Stations:France:
    ID: 07061119.wav
    Length: 108
** Train slowing & entering Gard du Nord (First class compartment)                                                                                :Trains:Eurostar:
    ID: 07061118.wav
    Length: 316
** Train travelling in France with announcements at 1'22" (First class compartment)                                                                                :Trains:Eurostar:
    ID: 07061117.wav
    Length: 161
** Toilet compartment with water & blower sounds (First class compartment)                                                                                :Trains:Toilets:
    ID: 07061116.wav
    Length: 109
** End of train corridor (First class compartment)                                                                                :Trains:Eurostar:
    ID: 07061115.wav
    Length: 311
** Train travelling in Channel Tunnel (First class compartment)                                                                                :Trains:Tunnels:
    ID: 07061114.wav
    Length: 91
** First class compartment departure announcements.                                                                                :Trains:Eurostar:
    ID: 07061113.wav
    Length: 13
** First class compartment prior to departure.                                                                                :Trains:Eurostar:
    ID: 07061112.wav
    Length: 134
** Platform with passengers prior to departure.                                                                                :Trains:Stations:Waterloo International:
    ID: 07061111.wav
    Length: 40
** Ascending escalator to platform.                                                                                :Trains:Stations:Waterloo International:
    ID: 07061110.wav
    Length: 40
** Departure lounge announcements in English & French.                                                                                :Trains:Stations:Waterloo International:
    ID: 07061109.wav
    Length: 34
** Departure lounge.                                                                                :Trains:Stations:Waterloo International:
    ID: 07061108.wav
    Length: 297
** Germany - Taxi Rank                                                                                :Germany:
    ID: 07061107.wav
    Length: 281
** Germany - Bus - interior                                                                                :Germany:Buses:
    ID: 07061106.wav
    Length: 282
** Germany - Children at bus station                                                                                :Germany:Buses:
    ID: 07061105.wav
    Length: 292
** Germany - Metro - interior                                                                                :Germany:Trains:
    ID: 07061104.wav
    Length: 281
** Germany - Metro station                                                                                :Germany:Trains:
    ID: 07061103.wav
    Length: 288
** Germany - Railway carriage - interior                                                                                :Trains:Germany:
    ID: 07061102.wav
    Length: 291
** Germany - Railway station (Munich)                                                                                :Germany:Trains:
    ID: 07061101.wav
    Length: 290
** Germany - Munich airport                                                                                :Airports:
    ID: 07061100.wav
    Length: 282
** Germany - Tourist queueing at historical site                                                                                :Germany:Crowds:
    ID: 07061099.wav
    Length: 284
** Germany - Civic centre (Munich)                                                                                :Germany:
    ID: 07061098.wav
    Length: 282
** Germany - Pedestrian town centre                                                                                :Germany:
    ID: 07061097.wav
    Length: 282
** Germany - Supermarket forecourt                                                                                :Germany:Shops:
    ID: 07061096.wav
    Length: 282
** Germany - Department store                                                                                :Germany:Department Stores:
    ID: 07061095.wav
    Length: 282
** Germany - Patisserie                                                                                :Germany:Restaurants:
    ID: 07061094.wav
    Length: 294
** Germany - Resturant                                                                                :Germany:Restaurants:
    ID: 07061093.wav
    Length: 290
** Refuse transfer station - refuse falling inside empty container & being compacted in normal cycle                                                                                :Cranes:
    ID: 07061092.wav
    Length: 195
** Cranes moving containers of compacted waste.                                                                                :Cranes:
    ID: 07061091.wav
    Length: 180
** Refuse transfer station - compactor in final boost cycle.                                                                                :Waste Disposal:
    ID: 07061090.wav
    Length: 180
** Scrap yard - lorry being loaded with metal by grab whilst acetylene torch is used to cut that metal.                                                                                :Acetylene Torches:
    ID: 07061089.wav
    Length: 180
** Scrap yard - general atmosphere with cranes & shear.                                                                                :Waste Disposal:
    ID: 07061088.wav
    Length: 128
** Scrap yard - bailer crushing copper tanks.                                                                                :Waste Disposal:
    ID: 07061087.wav
    Length: 210
** Scrap yard - light metals being picked up by grab and crushed by shear.                                                                                :Waste Disposal:
    ID: 07061086.wav
    Length: 238
** Public waste tip, busy with people with whirring compactor in first half                                                                                :Rubbish Tips:
    ID: 07061085.wav
    Length: 237
** Refuse lorry collecting rubbish in quiet street - recorded in cab of lorry.                                                                                :Council Activities:
    ID: 07061084.wav
    Length: 240
** Refuse lorry collecting rubbish in quiet street - recorded from back of lorry as rubbish is thrown in.                                                                                :Council Activities:
    ID: 07061083.wav
    Length: 240
** Refuse lorry collecting rubbish in quiet street.                                                                                :Council Activities:
    ID: 07061082.wav
    Length: 186
** Bottle bank in supermarket car park.                                                                                :Glass:Crashes:
    ID: 07061081.wav
    Length: 198
** Incinerator.                                                                                :Waste Disposal:
    ID: 07061080.wav
    Length: 240
** Municipal incinerator - Hydraulic power pack, combustion chamber, clinker conveyor.                                                                                :Conveyor Belts:
    ID: 07061079.wav
    Length: 180
** Municipal incinerator - lorry at tipping stall, opening hopper, depositing waste & leaving.                                                                                :Lorries:
    ID: 07061078.wav
    Length: 180
** Forklift truck dropping large boxes of glass into containers.                                                                                :Fork Lift Trucks:
    ID: 07061077.wav
    Length: 240
** Cans being dropped onto conveyor belt to bailing machine.                                                                                :Waste Disposal:
    ID: 07061076.wav
    Length: 240
** Forklift truck tipping boxes of cans into large container.                                                                                :Fork Lift Trucks:
    ID: 07061075.wav
    Length: 240
** Paper disposal plant - bailing machine                                                                                :Waste Disposal:
    ID: 07061074.wav
    Length: 240
** General atmos - forklift, saw cutting paper & bailing machine in background                                                                                :Fork Lift Trucks:
    ID: 07061073.wav
    Length: 240
** Conveyor belt being fed paper by tractor.                                                                                :Conveyor Belts:
    ID: 07061072.wav
    Length: 180
** Health centre reception area - squash courts in background.                                                                                :Gyms:
    ID: 07061071.wav
    Length: 180
** General gymnasium atmosphere - large, 5 people.                                                                                :Gyms:
    ID: 07061070.wav
    Length: 180
** General gymnasium atmosphere - large, 20 people.                                                                                :Gyms:
    ID: 07061069.wav
    Length: 180
** General gymnasium atmosphere - small, 6 people.                                                                                :Gyms:
    ID: 07061068.wav
    Length: 180
** Public swimming pool - 40 people lane swimming.                                                                                :Swimming Pools:
    ID: 07061067.wav
    Length: 180
** Oily massage.                                                                                :Gyms:
    ID: 07061066.wav
    Length: 180
** Thumping massage.                                                                                :Gyms:
    ID: 07061065.wav
    Length: 180
** Cupping massage.                                                                                :Gyms:
    ID: 07061064.wav
    Length: 180
** Hacking massage.                                                                                :Gyms:
    ID: 07061063.wav
    Length: 180
** Sunbed.                                                                                :Gyms:
    ID: 07061062.wav
    Length: 180
** Vibrosauna.                                                                                :Gyms:
    ID: 07061061.wav
    Length: 180
** Sauna - water poured over coals.                                                                                :Gyms:
    ID: 07061060.wav
    Length: 180
** Hamstring machine - custom body.                                                                                :Gyms:
    ID: 07061059.wav
    Length: 180
** Arm pulley machine - custom body.                                                                                :Gyms:
    ID: 07061058.wav
    Length: 180
** Weights machine.                                                                                :Gyms:
    ID: 07061057.wav
    Length: 180
** Seated chest press - pulstar.                                                                                :Gyms:
    ID: 07061056.wav
    Length: 180
** Exercise bike 3 - Monarks 814E.                                                                                :Gyms:
    ID: 07061055.wav
    Length: 180
** Exercise bike 2 - Schwiss Airdyne.                                                                                :Exercise Bicycles:Lifecycle 7500:
    ID: 07061054.wav
    Length: 180
** Exercise bike 1 - Life cycle.                                                                                :Gyms:
    ID: 07061053.wav
    Length: 180
** Step machine 2 (XT3000 Power Sport)                                                                                :Gyms:
    ID: 07061052.wav
    Length: 180
** Step machine 1 (Life step 7500)                                                                                :Gyms:
    ID: 07061051.wav
    Length: 180
** Rowing machine (Corset 2)                                                                                :Gyms:
    ID: 07061050.wav
    Length: 180
** Rowing machine (G4RO)                                                                                :Gyms:
    ID: 07061049.wav
    Length: 180
** Jogging machine (Power jog E 10)                                                                                :Gyms:
    ID: 07061048.wav
    Length: 180
** Set of rapids in a small river.                                                                                :Rivers:
    ID: 07061047.wav
    Length: 180
** Cascade of numerous small waterfalls.                                                                                :Waterfalls:
    ID: 07061046.wav
    Length: 240
** Medium size fast flowing river.                                                                                :Rivers:
    ID: 07061045.wav
    Length: 240
** Fast flowing river with numerous medium size waterfalls.                                                                                :Rivers:
    ID: 07061044.wav
    Length: 240
** Large waterfall - very high drop into fast flowing river (recorded at distance)                                                                                :Rivers:
    ID: 07061043.wav
    Length: 240
** Small waterfall - a thin waterfall in fast running stream with long drop.                                                                                :Rivers:
    ID: 07061042.wav
    Length: 240
** Sea ripples - water along shore being rippled by wind & tide.                                                                                :Weather:Wind:
    ID: 07061041.wav
    Length: 240
** Wind on dunes by palm tree - thin wind with some sand, sea & some buffering                                                                                :Weather:Wind:
    ID: 07061040.wav
    Length: 240
** Wind on tundra - cold rolling wilderness sound.                                                                                :Weather:Wind:
    ID: 07061039.wav
    Length: 240
** Light neutral wind - ideal for unintrusive backgrounds.                                                                                :Weather:Wind:
    ID: 07061038.wav
    Length: 240
** Savage wind - relentless, searing, very strong wind.                                                                                :Weather:Wind:
    ID: 07061037.wav
    Length: 240
** Desert wind - dry, hot, sandy, constant.                                                                                :Weather:Wind:
    ID: 07061036.wav
    Length: 240
** Wind on mountain - strong, gusty, cold wind.                                                                                :Mountains:
    ID: 07061035.wav
    Length: 240
** Soft sea breeze - light, wispy gentle wind                                                                                :Weather:Wind:
    ID: 07061034.wav
    Length: 240
** Aerial wind - constantly buffeting wind from birds eye view.                                                                                :Weather:Wind:
    ID: 07061033.wav
    Length: 240
** Post snow storm - soft, gentle wind after snow has settled.                                                                                :Weather:Snow:
    ID: 07061032.wav
    Length: 240
** Blizzard - height of driving snow storm.                                                                                :Weather:Snow:
    ID: 07061031.wav
    Length: 240
** Snow storm - heavy snow in swirling wind.                                                                                :Weather:Snow:
    ID: 07061030.wav
    Length: 240
** Small Lap crowd herding reindeer                                                                                :Finland:
    ID: 07061029.wav
    Length: 27
** Large reindeer herd                                                                                :Finland:
    ID: 07061028.wav
    Length: 45
** Countryside in spring, near Salo, Finland with willow warbler, chaffinch, fieldfare, great spotted woodpecker, blue tits and greenfinches                                                                                :Atmospheres:Countryside:
    ID: 07061027.wav
    Length: 190
** Helsinki suburban garden in spring with willow warbler, yellow hammer and skylark                                                                                :Atmospheres:Spring:
    ID: 07061026.wav
    Length: 146
** Metro station platform - train departs                                                                                :Finland:
    ID: 07061025.wav
    Length: 31
** Metro train journey for 1 stop                                                                                :Finland:
    ID: 07061024.wav
    Length: 81
** Metro station platform - train arrives                                                                                :Finland:
    ID: 07061023.wav
    Length: 28
** Helsinki Central Station - PA announcement near beginning                                                                                :Finland:
    ID: 07061022.wav
    Length: 183
** Forum supermarket, with musicians preparing to play                                                                                :Finland:
    ID: 07061021.wav
    Length: 117
** Tram journey, Helsinki                                                                                :Finland:
    ID: 07061020.wav
    Length: 178
** Beer garden, Helsinki                                                                                :Finland:
    ID: 07061019.wav
    Length: 120
** Harbour fountain, Helsinki                                                                                :Finland:
    ID: 07061018.wav
    Length: 126
** Quayside market, Helsinki  - changing perspective                                                                                :Finland:
    ID: 07061017.wav
    Length: 186
** Traffic by Observatory Park, Helsinki                                                                                :Finland:
    ID: 07061016.wav
    Length: 184
** Odense cathedral bells carillon                                                                                :Bells:Cathedrals:
    ID: 07061015.wav
    Length: 23
** Odense cathedral bells chime and run-down                                                                                :Bells:Cathedrals:
    ID: 07061014.wav
    Length: 101
** Copenhagen Kastrup airport concourse                                                                                :Copenhagen:
    ID: 07061013.wav
    Length: 223
** Outside hamburger restaurant                                                                                :Copenhagen:
    ID: 07061012.wav
    Length: 308
** Post Office, Copenhagen                                                                                :Post Offices:
    ID: 07061011.wav
    Length: 189
** Rosenborg Gardens, Copenhagen, Sunday morning, summer                                                                                :Atmospheres:Summer:
    ID: 07061010.wav
    Length: 210
** Market Square, Nytorv, Copenhagen                                                                                :Copenhagen:
    ID: 07061009.wav
    Length: 159
** Foyer of National Museum, Copenhagen                                                                                :Foyers:
    ID: 07061008.wav
    Length: 149
** Cafe, Copenhagen                                                                                :Copenhagen:
    ID: 07061007.wav
    Length: 287
** Holmen's Church bell chimes half-hour                                                                                :Copenhagen:
    ID: 07061006.wav
    Length: 11
** Holmen's Church bell chimes 9                                                                                :Copenhagen:
    ID: 07061005.wav
    Length: 44
** Restaurant, Copenhagen                                                                                :Copenhagen:
    ID: 07061004.wav
    Length: 335
** Light traffic in Kongens Nytorv Square, Copenhagen                                                                                :Copenhagen:
    ID: 07061003.wav
    Length: 243
** Crowds on Nyhavn Wharf, Copenhagen                                                                                :Crowds:Exterior:
    ID: 07061002.wav
    Length: 292
** Copenhagen Central Station -  PA announcement near beginning                                                                                :Copenhagen:
    ID: 07061001.wav
    Length: 169
** Exterior, bell rings (electric, reprocessed)  and children leave playground (8-9 year olds) - December 1968 (76D, reprocessed)                                                                                :Schools:Junior:
    ID: 07060111.wav
    Length: 69
** Children playing in a school playground in the south of England - 1974 (3C1, reprocessed)                                                                                :Children:Playing:
    ID: 07060110.wav
    Length: 381
** Children playing in a school playground in the Midlands (Birmingham) - 1971 (3C1, reprocessed)                                                                                :Children:Playing:
    ID: 07060109.wav
    Length: 362
** Group of mixed 5-11 year olds in enclosed playground (close perspective) - 1980 (3C7, reprocessed)                                                                                :Children:Playing:
    ID: 07060108.wav
    Length: 361
** Children at play in urban school playground (mid distance with footsteps) - 1982 (3C10, reprocessed) (technical note - to be used at low level)                                                                                :Children:Playing:
    ID: 07060107.wav
    Length: 361
** A group of junior schoolchildren in gymnasium - 1982 (3C11, reprocessed)                                                                                :Children:Playing:
    ID: 07060106.wav
    Length: 210
** 30 children playing in a field with birds and traffic - November 1970 (136E, reprocessed)                                                                                :Children:Playing:
    ID: 07060105.wav
    Length: 345
** 6 children playing in a London street, distant traffic and birds - November 1970 (136E, reprocessed)                                                                                :Children:Playing:
    ID: 07060104.wav
    Length: 389
** 5-10 year olds in urban playground with shouts, footsteps, swings, and distant traffic - 1981 (3C8, reprocessed)                                                                                :Children:Playing:
    ID: 07060103.wav
    Length: 395
** Exterior, group of children singing 'Looby Loo' - 1981 (3C8, reprocessed)                                                                                :Children:Singing:
    ID: 07060102.wav
    Length: 81
** Interior, group of children singing 'Looby Loo' - 1981 (3C8, reprocessed)                                                                                :Children:Singing:
    ID: 07060101.wav
    Length: 85
** Exterior, group of children singing 'London's Burning' - 1981 (3C8, reprocessed)                                                                                :Children:Singing:
    ID: 07060100.wav
    Length: 43
** Interior, group of children singing 'London's Burning' - 1981 (3C8, reprocessed)                                                                                :Children:Singing:
    ID: 07060099.wav
    Length: 44
** Exterior, group of children singing 'London Bridge' - 1981 (3C8, reprocessed)                                                                                :Children:Singing:
    ID: 07060098.wav
    Length: 81
** Interior, group of children singing 'London Bridge' - 1981 (3C8, reprocessed)                                                                                :Children:Singing:
    ID: 07060097.wav
    Length: 81
** Exterior, group of mixed children singing 'Cat's got the Measles', with movement and belches - 1980 (3C7, reprocessed)                                                                                :Children:Playing:
    ID: 07060096.wav
    Length: 25
** Exterior, group of mixed children singing 'Farmer's in his den', with movement - 1980 (3C7, reprocessed)                                                                                :Children:Playing:
    ID: 07060095.wav
    Length: 75
** Exterior, group of mixed children singing 'Poor Jenny is a-weeping', with movement - 1980 (3C7, reprocessed)                                                                                :Children:Playing:
    ID: 07060094.wav
    Length: 26
** Interior, 2-3 year olds trying to play singing games (mixed nursery school, reprocessed)  - November 1968 (76C, reprocessed)                                                                                :Children:Playing:
    ID: 07060093.wav
    Length: 193
** Main yard - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060092.wav
    Length: 237
** Boiler room - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060091.wav
    Length: 237
** Barrel loading - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060090.wav
    Length: 237
** Racking room - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060089.wav
    Length: 237
** Racking tank room - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060088.wav
    Length: 237
** Mash tun - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060087.wav
    Length: 237
** Lauter tun - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060086.wav
    Length: 237
** Brew house - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060085.wav
    Length: 241
** Grist room - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060084.wav
    Length: 235
** Mill room - Courage Brewery (large modern brewer)                                                                                :Brewing:
    ID: 07060083.wav
    Length: 237
** Filling casks - Smiles Brewery (small traditional brewer)                                                                                :Brewing:
    ID: 07060082.wav
    Length: 265
** Steam from boiling vessel (copper) - Smiles Brewery                                                                                :Brewing:
    ID: 07060081.wav
    Length: 210
** Mash tun - Smiles Brewery (small traditional brewer)                                                                                :Brewing:
    ID: 07060080.wav
    Length: 237
** Mill Room - Smiles Brewery (small traditional brewer)                                                                                :Brewing:
    ID: 07060079.wav
    Length: 237
** Fermenting vessels in the brew house - Smiles Brewery.                                                                                :Brewing:
    ID: 07060078.wav
    Length: 237
** Racking cellar - Smiles Brewery (small traditional brewer)                                                                                :Brewing:
    ID: 07060077.wav
    Length: 237
** Washing casks - Smiles Brewery (small traditional brewer)                                                                                :Brewing:
    ID: 07060076.wav
    Length: 237
** Malt room - Smiles Brewery (small traditional brewer)                                                                                :Brewing:
    ID: 07060075.wav
    Length: 235
** Small river flowing, mid-distant perspective - 1980 (1W10, reprocessed)                                                                                :Rivers:
    ID: 07060074.wav
    Length: 210
** Small river running over rocks - 1974 (1W6, reprocessed)                                                                                :Rivers:
    ID: 07060073.wav
    Length: 196
** River rippling over stones, close perspective - 1979 (1W8, reprocessed)                                                                                :Rivers:
    ID: 07060072.wav
    Length: 271
** Atmosphere recorded on River Mersey, with occasional hoot from boat  - 1980 (1B9, reprocessed) (technical note - for use at low level)                                                                                :Rivers:
    ID: 07060071.wav
    Length: 301
** Riverside atmosphere (Chelsea, London) - 1982 (1N2, reprocessed)                                                                                :London:
    ID: 07060070.wav
    Length: 285
** London riverside atmosphere  - 1981 (1W1, reprocessed) (technical note - for use at low level)                                                                                :London:
    ID: 07060069.wav
    Length: 280
** Water lapping on shore (Loch Bream, Ullapool)  - 1965 (22A, reprocessed)                                                                                :Seawash:
    ID: 07060068.wav
    Length: 211
** Sea lapping around legs of pier - 1980 (1W10, reprocessed)                                                                                :Piers:
    ID: 07060067.wav
    Length: 209
** Lapping river water (River Thames, London)  - 1979 (1W9, reprocessed)                                                                                :London:
    ID: 07060066.wav
    Length: 210
** Water rippling against quayside - July 1980 (1S9, reprocessed)                                                                                :Harbours:
    ID: 07060065.wav
    Length: 240
** Harbour atmosphere in summer with gulls and terns - 1981 (1S4, reprocessed) (technical note - for use at low level)                                                                                :Birds:Seagulls:
    ID: 07060064.wav
    Length: 269
** Pool of London atmosphere - siren, water lapping, birds and activity -1972 (1W3, reprocessed)                                                                                :London:
    ID: 07060063.wav
    Length: 303
** Pool of London atmosphere - siren, water lapping, birds, voices, engins - 1972 (1W3)                                                                                :London:
    ID: 07060062.wav
    Length: 287
** Large fountain, recorded close right centre with some traffic - 1972 (1W2,reprocessed)                                                                                :Fountains:
    ID: 07060061.wav
    Length: 151
** Large fountain, recorded close left centre with some traffic - 1972 (1W2,reprocessed)                                                                                :Fountains:
    ID: 07060060.wav
    Length: 152
** Large fountain - 1967 (22G, reprocessed)                                                                                :Fountains:
    ID: 07060059.wav
    Length: 121
** Fairly small fountain - 1967 (22G,reprocessed)                                                                                :Fountains:
    ID: 07060058.wav
    Length: 120
** Small fountain - 1967 (22G, reprocessed)                                                                                :Fountains:
    ID: 07060057.wav
    Length: 120
** Water running through culvert or bridge - 1979 (1W9)                                                                                :Water:Bridges:
    ID: 07060056.wav
    Length: 209
** Canal atmosphere under bridge - 1981 (1W1)                                                                                :Boats:Canals:
    ID: 07060055.wav
    Length: 271
** Veteran cars - montage of recordings from Veteran Car Run - 1984 (All vehicles 1892-1904) (4M1, reprocessed)                                                                                :Cars:Veteran:
    ID: 07060054.wav
    Length: 275
** Horsedrawn traffic - 1972 (1T4,reprocessed)                                                                                :Animals:Horses:Horsedrawn Traffic:
    ID: 07060053.wav
    Length: 272
** Car park atmosphere from inside closed car - 1981 (1T5)                                                                                :Car Parks:
    ID: 07060052.wav
    Length: 240
** Car park atmosphere with close and distant traffic - 1981(1T5, reprocessed)                                                                                :Car Parks:
    ID: 07060051.wav
    Length: 244
** Traffic from car park of Television Centre, distant traffic with occas. close vehicle and footsteps - 1981(1T8, reprocessed)                                                                                :Car Parks:
    ID: 07060050.wav
    Length: 244
** Night traffic in town - 1972 (1T2, reprocessed)                                                                                :Atmospheres:Night:
    ID: 07060049.wav
    Length: 270
** Night traffic - Trafalgar Square, London - 1972 (1T2, reprocessed)                                                                                :Atmospheres:Night:
    ID: 07060048.wav
    Length: 272
** Busy motorway, traffic passing with occasional pause (M4,Slough) -  Feb.1977 (1T11, reprocessed)                                                                                :Motorways:
    ID: 07060047.wav
    Length: 273
** Fast traffic on a trunk road - 1981(1T10, reprocessed)                                                                                :Trunk Roads:
    ID: 07060046.wav
    Length: 249
** Quiet main road during the evening - 1972 (1T3)                                                                                :Traffic:Motor:
    ID: 07060045.wav
    Length: 268
** Traffic on wet city street with dripping water - 1981(1T6, reprocessed)                                                                                :London:
    ID: 07060044.wav
    Length: 275
** Traffic on wet city street (St.Paul's, London) - 1981 (1T6, reprocessed)                                                                                :London:
    ID: 07060043.wav
    Length: 273
** Traffic from forecourt of Television Centre, distinct traffic with occas.close vehicle and footsteps - 1981(1T8, reprocessed)                                                                                :London:
    ID: 07060042.wav
    Length: 270
** Quiet city background with traffic - 1981 (1T7, reprocessed) (technical note: to be used at low level)                                                                                 :London:
    ID: 07060041.wav
    Length: 271
** Daytime city traffic background with pauses in traffic and birdsong (occas.hiss from vehicle or machine - July 1976 (1T11, reprocessed)                                                                                :London:
    ID: 07060040.wav
    Length: 271
** London, West End, side street - 1972 (1T1, reprocessed)                                                                                :London:
    ID: 07060039.wav
    Length: 270
** London, West End, Portland Place - 1972 (1T1, reprocessed)                                                                                :London:
    ID: 07060038.wav
    Length: 278
** Nightingales singing, close perspective - 1972 (1B3, reprocessed)                                                                                :Birds:Nightingales:
    ID: 07060037.wav
    Length: 242
** Rooks in the tree tops - 1972 (1B4, reprocessed)                                                                                :Trees:
    ID: 07060036.wav
    Length: 301
** Churchyard atmosphere at night  - clock strikes 12 midnight at 14", churchyard atmosphere with owls, distant dog barks at 2'50" (1B4, reprocessed)                                                                                :Birds:Owls:
    ID: 07060035.wav
    Length: 302
** Norfolk Broads - neutral night atmosphere - 1982 (1N3, reprocessed) (technical note - to be used at low level)                                                                                :Atmospheres:Night:
    ID: 07060034.wav
    Length: 299
** Norfolk Broads, daytime atmosphere - with wind through trees, creaking trees, waterfowl etc. - 1982 (1N3, reprocessed) (technical note   to be used at low level)                                                                                :Norfolk Broads:
    ID: 07060033.wav
    Length: 302
** Autumn atmosphere - sparrows, starlings and blackbirds roosting in thicket, more subdued - 1981 (1B16, reprocessed)                                                                                :Atmospheres:Autumn:
    ID: 07060032.wav
    Length: 211
** Autumn atmosphere - sparrows and starlings roosting in thicket with other birds, distant traffic - 1981 (1B16, reprocessed)                                                                                :Birds:
    ID: 07060031.wav
    Length: 211
** Quiet birds and insects with light breeze - August, 1981 (1B16, reprocessed)                                                                                :Birds:
    ID: 07060030.wav
    Length: 208
** Farm garden, July, mid-morning - with housemartins, swallows, pigeons, rooks, bees and grasshoppers - 1981 (1B17, reprocessed)                                                                                :Insects:Bees:
    ID: 07060029.wav
    Length: 267
** Garden, July, early morning - with occasional distant traffic - 1981 (1B17, reprocessed)                                                                                :Gardens:
    ID: 07060028.wav
    Length: 267
** Country scene - tractor ploughing with seabirds - 1973 (1B6, reprocessed)                                                                                :Birds:
    ID: 07060027.wav
    Length: 289
** Country scene - sheep and lambs with birdsong and stream in meadow - 1973 (1B6, reprocessed)                                                                                :Birds:
    ID: 07060026.wav
    Length: 303
** Summer atmosphere - quiet English downland during summer, a lark sings from 2'05" to 2'28", distant aircraft - 1980 (1B8, reprocessed) (technical note - to be used at low level)                                                                                :Atmospheres:Summer:
    ID: 07060025.wav
    Length: 248
** Summer atmosphere - quiet Welsh hillside during summer - distant traffic - 1980 (1B8, reprocessed) (technical note - to be used at low level)                                                                                :Atmospheres:Summer:
    ID: 07060024.wav
    Length: 175
** Summer atmosphere, June - recorded during hot weather with close buzzing of bees - 1981 (1B15, reprocessed)                                                                                :Atmospheres:Summer:
    ID: 07060023.wav
    Length: 302
** Summer atmosphere - quiet wind in trees and atmosphere just before dawn, distant aircraft - 1980 (1B8 , reprocessed) (technical note -  to be used at low level)                                                                                :Atmospheres:Dawn:
    ID: 07060022.wav
    Length: 239
** Moorland, June -  Exmoor atmosphere with chaffinch, redpolls, distant cuckoo, cattle, sheep, raindrops - 1979 (1B14 , reprocessed)                                                                                :Atmospheres:Summer:
    ID: 07060021.wav
    Length: 240
** Small town market square - footsteps, voices, street sweeping, traffic (rec. Wisbech, Cambridge) - 1979 (2C6, reprocessed) (technical note - for use at low level)                                                                                :Crowds:Exterior:
    ID: 07060020.wav
    Length: 246
** Crowd shouting, screaming, laughing - close perspective - 1972 (2C1, reprocessed)                                                                                :Crowds:Exterior:Laughter:
    ID: 07060019.wav
    Length: 132
** Angry, jeering crowd - close perspective crowd with horse-drawn vehicle - 1972 (2C1, reprocessed)                                                                                :Crowds:Exterior:Jeers:
    ID: 07060018.wav
    Length: 229
** Group of boys assembling, with speech, laughter and footsteps on gravel - 1968 (40E,reprocessed)                                                                                :Boys:
    ID: 07060017.wav
    Length: 183
** Group of 16-19 year old boys talking, occasional laughter - 1968 (40E,reprocessed)                                                                                :Boys:
    ID: 07060016.wav
    Length: 182
** Group of 16-19 year old boys talking, occasional pauses, and footsteps on gravel - 1968 (40E, reprocessed)                                                                                :Boys:
    ID: 07060015.wav
    Length: 175
** Mixed chatter and footsteps on gravel, animated ,1966 (40A,reprocessed)                                                                                :Crowds:Exterior:Chatter:
    ID: 07060014.wav
    Length: 147
** Mixed chatter and footsteps on gravel - 1966 (40A, reprocessed)                                                                                :Crowds:Exterior:Chatter:
    ID: 07060013.wav
    Length: 180
** Mixed cheerful chatter and laughter - 1966 (40A, reprocessed)                                                                                :Crowds:Exterior:Chatter:
    ID: 07060012.wav
    Length: 181
** Mixed general chatter - close perspective - 1966 (40A, reprocessed)                                                                                :Crowds:Exterior:Chatter:
    ID: 07060011.wav
    Length: 181
** Crowd with children at London Zoo, with sea lions at feeding time - 1974 (2C3, reprocessed)                                                                                :Children:Playing:
    ID: 07060010.wav
    Length: 241
** Mixed crowd with children at London Zoo (no animal sounds) - 1974 (2C3)                                                                                :Children:Playing:
    ID: 07060009.wav
    Length: 241
** Mixed outdoor crowd at fete, with children and adults - distant birdsong and traffic - 1975 (2C7, reprocessed)                                                                                :Children:Playing:
    ID: 07060008.wav
    Length: 304
** Crowds in Paternoster Square, London, with footsteps and speech - 1972 (2C1,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07060007.wav
    Length: 203
** Large moving crowd with footsteps and voices - 1982 (2C10, reprocessed)                                                                                :Crowds:Exterior:
    ID: 07060006.wav
    Length: 302
** Expectant crowd background with birdsong, footsteps on pavement and speech - 1977 (2C4, reprocessed)                                                                                :Birds:
    ID: 07060005.wav
    Length: 288
** Large expectant crowd with birdsong - wide perspective - 1977 (2C4,reprocessed)                                                                                :Birds:
    ID: 07060004.wav
    Length: 270
** Large restless crowd builds up - occasional vendors shouting wares (recorded at outdoor sports meeting, suitable for general purpose use) - 1975 (257, reprocessed)                                                                                :Crowds:Exterior:
    ID: 07060003.wav
    Length: 301
** Close good natured crowd at public demonstration - occasional distant PA - 1982 (2C10,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07060002.wav
    Length: 303
** Atmosphere before ships launch, close perspective - occas. hammering in background - 1985 (3S23)                                                                                :Crowds:Exterior:
    ID: 07060001.wav
    Length: 135
** Cicadas - large number in trees (NZ)                                                                                :Insects:Crickets:
    ID: 07059128.wav
    Length: 137
** Californian sealion 2 - older male (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059127.wav
    Length: 38
** Californian sealion 1 - young male (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059126.wav
    Length: 48
** Dolphins echo underwater (NZ)                                                                                :Animals:Dolphins:
    ID: 07059125.wav
    Length: 121
** Ducks - solo (NZ)                                                                                :Birds:Ducks:
    ID: 07059124.wav
    Length: 20
** Ducks - feeding frenzy (NZ)                                                                                :Birds:Ducks:
    ID: 07059123.wav
    Length: 149
** Peacocks - several birds calling at night.                                                                                :Birds:Peacocks:
    ID: 07059122.wav
    Length: 75
** Stitchbird - several calls.                                                                                :New Zealand:Natural World:
    ID: 07059121.wav
    Length: 26
** Kea - call, single.                                                                                :Birds:
    ID: 07059120.wav
    Length: 5
** Kea - several calls & noises in flight.                                                                                :Birds:
    ID: 07059119.wav
    Length: 52
** North Island Kaka.                                                                                :New Zealand:Natural World:
    ID: 07059118.wav
    Length: 119
** Yellow Eyed Penguins (NZ)                                                                                :Birds:Penguins:
    ID: 07059117.wav
    Length: 127
** Little Blue Penquin colony, Oamaru (NZ)                                                                                :Birds:Penguins:
    ID: 07059116.wav
    Length: 229
** Sand dunes at Omamari nr Dargaville (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059115.wav
    Length: 183
** Heavy surf, Hauraki Gulf (NZ)                                                                                :Surf:
    ID: 07059114.wav
    Length: 216
** Surf on sand, Army Bay, Whangaparoa (NZ)                                                                                :Surf:
    ID: 07059113.wav
    Length: 168
** Sea on pebble beach, Kaikoura (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059112.wav
    Length: 184
** Pacific ocean, rocky coastline north of Kaikoura.                                                                                :New Zealand:Natural World:
    ID: 07059111.wav
    Length: 273
** Water trickling over leaves at night, Opapaka Walk, Waitomo (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059110.wav
    Length: 118
** Stream 3 - waterfall gully track, Shakespeare Regional Park (NZ)                                                                                :Rivers:
    ID: 07059109.wav
    Length: 118
** Stream 2 - waterfall gully track, Shakespeare Regional Park (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059108.wav
    Length: 166
** Stream 1 - waterfall gully track, Shakespeare Regional Park (NZ)                                                                                :Rivers:
    ID: 07059107.wav
    Length: 256
** Small stream at night, farmland nr Dargaville                                                                                :Rivers:
    ID: 07059106.wav
    Length: 97
** Hot waterfall - fierce flow through gully.                                                                                :Waterfalls:
    ID: 07059105.wav
    Length: 123
** Hot water stream - fast flowing at 50 degrees.                                                                                :Rivers:
    ID: 07059104.wav
    Length: 194
** Hot steam vent - spluttering of steam (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059103.wav
    Length: 142
** Hot Spring 2- tight - Bird's Nest Terrace (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059102.wav
    Length: 142
** Hot Spring 1 - loose, Birds' Nest Terrace (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059101.wav
    Length: 133
** Hot Springs of Mother Earth (Nga Puia o te Papa) - cluster of boiling springs (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059100.wav
    Length: 126
** Boiling mud - nightime, Rotorua (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059099.wav
    Length: 227
** Boiling mud - daytime, Waiotapu (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059098.wav
    Length: 130
** Artist's Palette, Waiotapu Thermal Reserve (NZ)                                                                                :New Zealand:Natural World:
    ID: 07059097.wav
    Length: 107
** Electronic metal detector.                                                                                :Metal Detectors:
    ID: 07059096.wav
    Length: 68
** Blowlamp turned off.                                                                                :Blowlamps:
    ID: 07059095.wav
    Length: 9
** Blowlamp re-lit and runs (pumping after 19").                                                                                :Blowlamps:
    ID: 07059094.wav
    Length: 134
** Pumping a blowlamp.                                                                                :Blowlamps:
    ID: 07059093.wav
    Length: 23
** Failed attempt to start.                                                                                :Blowlamps:
    ID: 07059092.wav
    Length: 37
** Several fairly long runs (hand-operated sewing machine).                                                                                :Sewing Machines:Domestic:
    ID: 07059091.wav
    Length: 344
** Several short runs (hand-operated sewing machine).                                                                                :Sewing Machines:Domestic:
    ID: 07059090.wav
    Length: 156
** Foot lifted & lowered - 3 times (hand-operated sewing machine).                                                                                :Sewing Machines:Domestic:
    ID: 07059089.wav
    Length: 23
** Winding cotton on to shuttle (hand-operated sewing machine).                                                                                :Sewing Machines:Domestic:
    ID: 07059088.wav
    Length: 24
** Taking out machine & setting up (hand-operated sewing machine).                                                                                :Sewing Machines:Domestic:
    ID: 07059087.wav
    Length: 22
** Putting machine away (hand-operated sewing machine).                                                                                :Sewing Machines:Domestic:
    ID: 07059086.wav
    Length: 24
** Venetian blind (metal) opened & closed twice.                                                                                :Blinds:
    ID: 07059085.wav
    Length: 14
** Old sash window opened & closed.                                                                                :Windows:
    ID: 07059084.wav
    Length: 8
** Sliding canvas curtains open & closed.                                                                                :Curtains:
    ID: 07059083.wav
    Length: 17
** Large curtain on metal runners.                                                                                :Curtains:
    ID: 07059082.wav
    Length: 15
** Curtains being pulled - wooden rings on wooden rod.                                                                                :Curtains:
    ID: 07059081.wav
    Length: 8
** Curtains being pulled - brass rings on wooden rod.                                                                                :Curtains:
    ID: 07059080.wav
    Length: 14
** Curtains being pulled - small rings on wire.                                                                                :Curtains:
    ID: 07059079.wav
    Length: 13
** Curtains being pulled - large brass rings on brass rod.                                                                                :Curtains:
    ID: 07059078.wav
    Length: 17
** Curtains being pulled - metal runners.                                                                                :Curtains:
    ID: 07059077.wav
    Length: 15
** Curtains being pulled - wooden rings on wooden rod.                                                                                :Curtains:
    ID: 07059076.wav
    Length: 7
** Refrigerator hum - switch on & off.                                                                                :Electronic Sounds:Hums:
    ID: 07059075.wav
    Length: 115
** Refrigerator hum - switch on & off.                                                                                :Electronic Sounds:Hums:
    ID: 07059074.wav
    Length: 126
** Deep-freeze motor hum.                                                                                :Electronic Sounds:Hums:
    ID: 07059073.wav
    Length: 119
** Refrigerator hum - switch off.                                                                                :Electronic Sounds:Hums:
    ID: 07059072.wav
    Length: 102
** Refrigerator hum - switch off.                                                                                :Electronic Sounds:Hums:
    ID: 07059071.wav
    Length: 118
** Strip lighting hum.                                                                                :Electronic Sounds:Hums:
    ID: 07059070.wav
    Length: 92
** Several light switches operated.                                                                                :Household:Lights:
    ID: 07059069.wav
    Length: 38
** Gas meter - 1 two-silling piece inserted.                                                                                :Household:Meters:
    ID: 07059068.wav
    Length: 7
** Electricity meter - 2 two-silling pieces inserted.                                                                                :Household:Meters:
    ID: 07059067.wav
    Length: 9
** Electricity meter - 2 one-silling pieces inserted.                                                                                :Household:Meters:
    ID: 07059066.wav
    Length: 13
** Gas meter - 2 one-shilling pieces inserted.                                                                                :Household:Meters:
    ID: 07059065.wav
    Length: 17
** Gas water heater turned on.                                                                                :Household:Gas:
    ID: 07059064.wav
    Length: 31
** Gas water boiler lit & burns.                                                                                :Household:Gas:
    ID: 07059063.wav
    Length: 40
** Gas stove burner roar (natural gas).                                                                                :Household:Gas:
    ID: 07059062.wav
    Length: 57
** Match struck - gas mantle lit & burns.                                                                                :Household:Gas:
    ID: 07059061.wav
    Length: 126
** Grill lit & burns.                                                                                :Household:Gas:
    ID: 07059060.wav
    Length: 56
** Gas fire lit (ignites twice).                                                                                :Household:Gas:
    ID: 07059059.wav
    Length: 4
** Gas poker lit & burns.                                                                                :Household:Gas:
    ID: 07059058.wav
    Length: 72
** Poking open coal fire and adding fire.                                                                                :Fires:Household:
    ID: 07059057.wav
    Length: 37
** Riddling a boiler fire.                                                                                :Fires:Household:
    ID: 07059056.wav
    Length: 29
** Open coal fire, shovelling coal into rubber hod.                                                                                :Fires:Household:
    ID: 07059055.wav
    Length: 32
** Open coal fire, shovelling coal into metal hod.                                                                                :Fires:Household:
    ID: 07059054.wav
    Length: 21
** Emptying hod of coal into grate.                                                                                :Fires:Household:
    ID: 07059053.wav
    Length: 10
** Filling plastic coal hod.                                                                                :Fires:Household:
    ID: 07059052.wav
    Length: 26
** Filling plastic coal hod.                                                                                :Fires:Household:
    ID: 07059051.wav
    Length: 32
** Open fire burning.                                                                                :Fires:Household:
    ID: 07059050.wav
    Length: 176
** Match struck - open fire lit, crackle of flame.                                                                                :Fires:Household:
    ID: 07059049.wav
    Length: 165
** Laying fire in open fireplace.                                                                                :Fires:Household:
    ID: 07059048.wav
    Length: 27
** Shovelling out cinders in open fireplace.                                                                                :Fires:Household:
    ID: 07059047.wav
    Length: 27
** Brushing out open fireplace.                                                                                :Fires:Household:
    ID: 07059046.wav
    Length: 26
** Raking out open fireplace.                                                                                :Fires:Household:
    ID: 07059045.wav
    Length: 32
** Chopping firewood.                                                                                :Fires:Household:
    ID: 07059044.wav
    Length: 59
** Beating a carpet.                                                                                :Household:Carpets:
    ID: 07059043.wav
    Length: 60
** Vacuum cleaner (cylinder type) - in use, stops.                                                                                :Household:Vacuum Cleaners:
    ID: 07059042.wav
    Length: 7
** Vacuum cleaner (cylinder type) - in use (distant).                                                                                :Household:Vacuum Cleaners:
    ID: 07059041.wav
    Length: 159
** Vacuum cleaner (cylinder type) - start, constant run on carpet, stop.                                                                                :Household:Vacuum Cleaners:
    ID: 07059040.wav
    Length: 131
** Vacuum cleaner (cylinder type) - start, constant run on lino.                                                                                :Household:Vacuum Cleaners:
    ID: 07059039.wav
    Length: 144
** Old fashioned mangle operated with washing in rollers with squeak.                                                                                :Household:Mangles:
    ID: 07059038.wav
    Length: 91
** Old fashioned mangle operated with washing in rollers.                                                                                :Household:Mangles:
    ID: 07059037.wav
    Length: 112
** Old fashioned mangle operated without washing.                                                                                :Household:Mangles:
    ID: 07059036.wav
    Length: 35
** Old fashioned mangle, tin bath moved in preparation for drying clothes.                                                                                :Household:Mangles:
    ID: 07059035.wav
    Length: 16
** Old fashioned mangle moved on stone floor.                                                                                :Household:Mangles:
    ID: 07059034.wav
    Length: 21
** Washing on dolly board.                                                                                :Household:Washing:
    ID: 07059033.wav
    Length: 140
** Knocking in pipes.                                                                                :Household:Plumbing:
    ID: 07059032.wav
    Length: 66
** Open city skyline - specially created.                                                                                :City Skyline:
    ID: 07059031.wav
    Length: 167
** Countryside in summer - use at low level.                                                                                :Atmospheres:Countryside:
    ID: 07059030.wav
    Length: 270
** Sharpening lawn mower blades.                                                                                :Grinders:
    ID: 07059029.wav
    Length: 145
** Sickle being sharpened.                                                                                :Grinders:
    ID: 07059028.wav
    Length: 134
** Scythe being sharpened.                                                                                :Grinders:
    ID: 07059027.wav
    Length: 117
** Chopper being sharpened.                                                                                :Grinders:
    ID: 07059026.wav
    Length: 76
** Sickle with Fagin hook being used.                                                                                :Gardening:
    ID: 07059025.wav
    Length: 122
** Sweeping on concrete.                                                                                :Brooms:
    ID: 07059024.wav
    Length: 117
** Sweeping earth & stones.                                                                                :Brooms:
    ID: 07059023.wav
    Length: 120
** Raking grass.                                                                                :Gardening:
    ID: 07059022.wav
    Length: 115
** Raking stony ground.                                                                                :Gardening:
    ID: 07059021.wav
    Length: 197
** Hedge clipping.                                                                                :Gardening:
    ID: 07059020.wav
    Length: 193
** Garden hose turned on & runs.                                                                                :Gardening:
    ID: 07059019.wav
    Length: 194
** Hoeing in a garden.                                                                                :Gardening:
    ID: 07059018.wav
    Length: 184
** Digging gravel with a spade.                                                                                :Gardening:
    ID: 07059017.wav
    Length: 181
** Digging with a spade.                                                                                :Gardening:
    ID: 07059016.wav
    Length: 185
** A scythe being used.                                                                                :Gardening:
    ID: 07059015.wav
    Length: 190
** Trimming grass with shears.                                                                                :Gardening:
    ID: 07059014.wav
    Length: 89
** Electric mower - various cutting patterns.                                                                                :Gardening:Lawn Mowing:
    ID: 07059013.wav
    Length: 166
** 4-stroke rotary lawn mower stopping.                                                                                :Gardening:Lawn Mowing:
    ID: 07059012.wav
    Length: 10
** Start up, continuous run - approaching & receding of 4-stroke rotary lawn mower.                                                                                :Gardening:Lawn Mowing:
    ID: 07059011.wav
    Length: 244
** 4-stroke rotary lawn mower stopping.                                                                                :Gardening:Lawn Mowing:
    ID: 07059010.wav
    Length: 9
** Start up, tickover of 4-stroke rotary lawn mower.                                                                                :Gardening:Lawn Mowing:
    ID: 07059009.wav
    Length: 56
** False starts of 4-stroke rotary lawn mower.                                                                                :Gardening:Lawn Mowing:
    ID: 07059008.wav
    Length: 32
** Rotary mower - start, mowing medium-sized lawn, stop.                                                                                :Gardening:Lawn Mowing:
    ID: 07059007.wav
    Length: 265
** Rotary mower - starts, revving, stops.                                                                                :Gardening:Lawn Mowing:
    ID: 07059006.wav
    Length: 56
** Rotary mower - false starts.                                                                                :Gardening:Lawn Mowing:
    ID: 07059005.wav
    Length: 30
** Continuous mowing with turns using roller-type lawn mower.                                                                                :Lawn Mowers:Roller:
    ID: 07059004.wav
    Length: 107
** Fast, short pushes of roller-type lawn mower.                                                                                :Lawn Mowers:Roller:
    ID: 07059003.wav
    Length: 52
** Medium pushes of roller mower.                                                                                :Lawn Mowers:Roller:
    ID: 07059002.wav
    Length: 94
** Slow pushes of roller-type mower.                                                                                :Lawn Mowers:Roller:
    ID: 07059001.wav
    Length: 99
** Exterior, 5 bells rung in the style used from the Reformation until about the 17th Century - rounds and call changes recorded outside church (St. Mary and St. Andrew's Church, Whittlesford, Cambs.) - 1982 (2B8, reprocessed )                                                                                :Bells:Churches:Sixteenth Century:
    ID: 07058199.wav
    Length: 331
** Interior, 5 bells rung in the style used from the Reformation until about the 17th Century - rounds and call changes from interior of church (St. Mary and St. Andrew's Church, Whittlesford, Cambs.) - 1982 (2B8, reprocessed )                                                                                :Bells:Churches:Sixteenth Century:
    ID: 07058198.wav
    Length: 329
** Exterior, 3 bells rung at random in Pre-Reformation style, with birdsong (St. Andrew's Church, Toft, Cambs.) - 1982 (2B7, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058197.wav
    Length: 206
** Interior, 3 bells rung at random in Pre-Reformation style, from interior of church, with some noise of feet and rope (St. Andrew's Church, Toft, Cambs.) - 1982 (2B7, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058196.wav
    Length: 205
** Exterior, 5 bells rung at random in Pre-Reformation style (St. Mary and St. Andrew's Church, Whittlesford, Cambs.) - 1982 (2B7, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058195.wav
    Length: 205
** Interior, 5 bells rung at random in Pre-Reformation style (St. Mary and St. Andrew's Church, Whittlesford, Cambs.) - 1982 (2B7, reprocessed )                                                                                :Bells:Churches:Pre-Reformation:
    ID: 07058194.wav
    Length: 207
** Interior, peal of 8 bells, ringing ends (St. Chad's Parish Church, Rochdale) - 1974 (2B3, reprocessed )                                                                                :Bells:Churches:
    ID: 07058193.wav
    Length: 181
** Peal of 8 bells from inside parch (St. Chad's Parish Church, Rochdale) - 1974 (2B3, reprocessed )                                                                                :Bells:Churches:
    ID: 07058192.wav
    Length: 178
** Exterior, single bell telling, with distant traffic and birdsong (St. Chad's Parish Church, Rochdale) - 1974 (2B3, reprocessed )                                                                                :Bells:Churches:
    ID: 07058191.wav
    Length: 78
** Exterior, peal of 8 bells, ringing ends, with birdsong (St. Chad's Parish Church, Rochdale) - 1974 (2B3, reprocessed )                                                                                :Bells:Churches:
    ID: 07058190.wav
    Length: 104
** Exterior, 1 bell rung, with birdsong (St. Michael's Parish Church, Mytholmroyd.)- 1981 (2B6, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058189.wav
    Length: 53
** Exterior, 7 bells poorly rung, ringing ends, with birdsong and occasional traffic (St. Michael's Parish Church, Mytholmroyd) - 1981(2B6, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058188.wav
    Length: 53
** St. Sepulchre's Church, High Holborn, known as 'bells of Old Bailey', exterior, incomplete Cambridge Surprise Maximus - 1985 (2B9, reprocessed )                                                                                :Bells:Churches:London:
    ID: 07058187.wav
    Length: 186
** St. Sepulchre's Church, High Holborn, known as 'bells of Old Bailey', exterior, aborted Cambridge Surprise maximus, ends - 1985 (2B9, reprocessed )                                                                                :Bells:Churches:London:
    ID: 07058186.wav
    Length: 70
** St. Sepulchre's Church, High Holborn, exterior, tenor bell rung, ends, background traffic (This was the bell rung at public executions and rung here in an authentic manner - opposite The old Bailey, formerly site of Newgate Prison) - 1985 (2B9)                                                                                :Bells:Churches:London:
    ID: 07058185.wav
    Length: 30
** St. Sepulchre's Church, High Holborn, exterior, tenor bell rung, with background traffic (This was the bell rung at public executions and rung here in an authentic manner - opposite The Old Bailey, formerly site of Newgate Prison) - 1985 (2B9)                                                                                :Bells:Churches:London:
    ID: 07058184.wav
    Length: 110
** St. Mary-Le-Bow, interior, incomplete Bristol Maximus from interior of church, with distant traffic - July 1976 (2B4, reprocessed )                                                                                :Bells:Churches:London:
    ID: 07058183.wav
    Length: 167
** St. Mary-Le-Bow, exterior, incomplete Maximus from churchyard with distant traffic - July 1976 (2B4, reprocessed )                                                                                :Atmospheres:Churchyards:
    ID: 07058182.wav
    Length: 166
** St. Mary-Le-Bow, exterior, Stedman Cinques finish, with traffic and birdsong - July 1976 (2B4, reprocessed )                                                                                :Bells:Churches:London:
    ID: 07058181.wav
    Length: 30
** St. Mary-Le-Bow, exterior start, incomplete Stedman Cinques rung, with heavy traffic and birdsong - July 1976 (2B4, reprocessed )                                                                                :Bells:Churches:London:
    ID: 07058180.wav
    Length: 184
** Village church, single bell ringing up then telling (Christ Church, Kilndown, Kent) - November 1966 (91B, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058179.wav
    Length: 87
** Village church, peal of 6 bells, ringing stops (Christ Church, Kilndown, Kent) - November 1966 (91B, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058178.wav
    Length: 26
** Village church, peal of 6 bells (Christ Church, Kilndown, Kent) - November 1966 (91B, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058177.wav
    Length: 171
** Village church, single bell tolling, ringing ends (St.Margaret's, Horsmonden, Kent) - November 1966 (91C, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058176.wav
    Length: 61
** Village church, single bell ringing, ringing ends (St.Margaret's Horsmonden, Kent) - November 1966 (91C, reprocessed )                                                                                :Atmospheres:Villages:
    ID: 07058175.wav
    Length: 89
** Angelus, with outdoor atmosphere - 1966 (91D, reprocessed )                                                                                :Bells:Churches:
    ID: 07058174.wav
    Length: 59
** Canterbury Cathedral bells, exterior, ringing starts, rounds, Grandsire Cinques, rounds, ringing stops (recorded from top of 'Bell Harry' tower) - 1981 (2B5, reprocessed )                                                                                :Bells:Cathedrals:
    ID: 07058173.wav
    Length: 388
** Canterbury Cathedral bells, interior, ringing starts, rounds, Grandsire Cinques, rounds, ringing stops (recorded in roof void above nave) - 1981 (2B5, reprocessed )                                                                                :Bells:Cathedrals:
    ID: 07058172.wav
    Length: 347
** Canned drink opened                                                                                :Cans:
    ID: 07058171.wav
    Length: 4
** Stylus jerked off vinyl record, record scratch                                                                                :Scratches:Records:
    ID: 07058170.wav
    Length: 1
** 4-6-2 Pacific model locomotive only, slow run round track and stop                                                                                :Trains:Model:
    ID: 07058169.wav
    Length: 26
** 4-6-2 Pacific model locomotive only, run round track                                                                                :Trains:Model:
    ID: 07058168.wav
    Length: 103
** 4-6-2 Pacific model locomotive, fast run round track (rec. centre of track)                                                                                :Trains:Model:
    ID: 07058167.wav
    Length: 73
** 4-6-2 Pacific model locomotive, with 3 Mark 1 coaches, run round track                                                                                :Trains:Model:
    ID: 07058166.wav
    Length: 109
** Slower dialling on Cellnet portable telephone (8 digits)                                                                                :Telephones:Mobile Phones:
    ID: 07058165.wav
    Length: 4
** Dialling on Cellnet portable telephone (7 digits)                                                                                :Telephones:Mobile Phones:
    ID: 07058164.wav
    Length: 3
** Slow tuning  across 9 Mhz, with static and heavy interference                                                                                :Radio:Receivers:
    ID: 07058163.wav
    Length: 95
** Slow tuning between 8-9 Mhz, with morse teletype atmosphere                                                                                :Morse Code:
    ID: 07058162.wav
    Length: 91
** Quick tuning across 49 metre band                                                                                :Radio:Receivers:
    ID: 07058161.wav
    Length: 39
** Slow tuning across 31 metre band (Short Wave Communications Receiver)                                                                                :Radio:Receivers:
    ID: 07058160.wav
    Length: 109
** MRI (Magnetic Resonance Inducer) body scanner                                                                                :Body Scanners:
    ID: 07058159.wav
    Length: 231
** Heavy front door opens, exterior sounds, door closes (heard outside)                                                                                :Doors:House:
    ID: 07058158.wav
    Length: 6
** Front door opens, person enters, door closes                                                                                :Doors:House:
    ID: 07058157.wav
    Length: 5
** Key in lock, door opens and closes (reverberent corridor)                                                                                :Doors:House:
    ID: 07058156.wav
    Length: 7
** Tannoy signal with interior carriage background (single note)                                                                                :Tannoys:
    ID: 07058155.wav
    Length: 4
** Tannoy signal - untreated, no background (2 notes)                                                                                :Tannoys:
    ID: 07058154.wav
    Length: 6
** Tannoy signal with airport background (2 notes)                                                                                :Airports:
    ID: 07058153.wav
    Length: 4
** Tannoy signal with station background (4 notes)                                                                                :Trains:Stations:
    ID: 07058152.wav
    Length: 7
** Air horn - 5 short blasts                                                                                :Horns:
    ID: 07058151.wav
    Length: 5
** Air horn - long blast                                                                                :Horns:
    ID: 07058150.wav
    Length: 9
** Police car - fast pass with siren (Copenhagen)                                                                                :Police:Cars:
    ID: 07058149.wav
    Length: 13
** Numerous police sirens, with hooters and traffic (New York, night-time)                                                                                :Hooters:
    ID: 07058148.wav
    Length: 112
** New York police sirens - distant (night-time)                                                                                :Police:Cars:
    ID: 07058147.wav
    Length: 41
** New York traffic skyline at night                                                                                :City Skyline:
    ID: 07058146.wav
    Length: 325
** Nazi Germany - large German crowd cheering and shouting slogans (500T, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07058145.wav
    Length: 64
** Nazi Germany - large German crowd cheering (500T, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07058144.wav
    Length: 55
** Nazi Germany - large German crowd shouting 'Sieg Heil' (500T, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07058143.wav
    Length: 68
** Nazi Germany - large German crowd cheering and shouting 'Sieg Heil' (500T, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07058142.wav
    Length: 174
** Nazi Germany - large German crowd cheering (500T, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07058141.wav
    Length: 58
** Riot in Belfast - more subdued                                                                                :Crowds:Exterior:Rioting:
    ID: 07058140.wav
    Length: 150
** Riot in Belfast - with breaking glass, rubber bullets, distant cries and chants                                                                                :Crowds:Exterior:Rioting:
    ID: 07058139.wav
    Length: 103
** Close crowds at running event                                                                                :Crowds:Exterior:
    ID: 07058138.wav
    Length: 127
** Small crowd laughing at puppet show (Denmark)                                                                                :Crowds:Exterior:
    ID: 07058137.wav
    Length: 12
** Outdoor rock concert - Cheer, chants, hooters and whistling                                                                                :Cheers:Exterior:
    ID: 07058136.wav
    Length: 74
** Outdoor rock concert - Derisory cries, whistles and cheers                                                                                :Cheers:Exterior:
    ID: 07058135.wav
    Length: 53
** Outdoor rock concert - cheers, applause and calls of 'more'                                                                                :Applause:Exterior:
    ID: 07058134.wav
    Length: 118
** Outdoor classical concert - Applause at end of concert and audience dispersing                                                                                :Applause:Exterior:
    ID: 07058133.wav
    Length: 116
** Outdoor classical concert - Applause, cheers and whistles after item and audience dispersing                                                                                :Applause:Exterior:
    ID: 07058132.wav
    Length: 139
** Outdoor classical concert - Applause after movement                                                                                :Applause:Exterior:
    ID: 07058131.wav
    Length: 21
** Outdoor classical concert - crowd presence before performance (2 bursts of applause for performers)                                                                                :Applause:Exterior:
    ID: 07058130.wav
    Length: 96
** Large tree falling                                                                                :Tree Felling:
    ID: 07058129.wav
    Length: 12
** Three trees falling (index point for each fall)                                                                                :Tree Felling:
    ID: 07058128.wav
    Length: 16
** Tree being chopped down                                                                                :Tree Felling:
    ID: 07058127.wav
    Length: 85
** Water lapping on shore (Loch Lomond)                                                                                :Atmospheres:Lakes:
    ID: 07058126.wav
    Length: 296
** Lions eating carcass (inside cage)                                                                                :Animals:Lions:
    ID: 07058125.wav
    Length: 56
** Lions eating carcass (exterior)                                                                                :Animals:Lions:
    ID: 07058124.wav
    Length: 166
** Lion roaring (inside cage)                                                                                :Animals:Lions:
    ID: 07058123.wav
    Length: 37
** Two dogs fighting                                                                                :Animals:Dogs:
    ID: 07058122.wav
    Length: 60
** Small town, children in playground - distant traffic.                                                                                :Children:Playing:
    ID: 07058121.wav
    Length: 76
** Small town, children - some taffic.                                                                                :Children:Playing:
    ID: 07058120.wav
    Length: 303
** Small country town, general atmosphere with birds and occasional lorries.                                                                                :Traffic:Motor:Country Towns:
    ID: 07058119.wav
    Length: 278
** Small country town, high street.                                                                                :Traffic:Motor:Country Towns:
    ID: 07058118.wav
    Length: 266
** Provincial town traffic, light and heavy - no footsteps or chatter.                                                                                :Traffic:Towns:
    ID: 07058117.wav
    Length: 199
** Provincial town, some footsteps and chatter.                                                                                :Traffic:Motor:With Pedestrians:
    ID: 07058116.wav
    Length: 211
** Small town, main street - few footsteps.                                                                                :Traffic:Motor:Towns:
    ID: 07058115.wav
    Length: 99
** Daytime with birds.                                                                                :Birds:
    ID: 07058114.wav
    Length: 256
** Traffic on main wet road.                                                                                :Traffic:London:
    ID: 07058113.wav
    Length: 191
** Traffic in fog.                                                                                :Traffic:Motor:Fog:
    ID: 07058112.wav
    Length: 269
** In a city street.                                                                                :Traffic:Motor:City:
    ID: 07058111.wav
    Length: 229
** Traffic on trunk road.                                                                                :Traffic:Motor:Trunk Roads:
    ID: 07058110.wav
    Length: 105
** Fairly heavy traffic on wet road, with pedestrians - few horns.                                                                                :Traffic:Motor:With Pedestrians:
    ID: 07058109.wav
    Length: 260
** Fairly heavy traffic on wet road - no pedestrians.                                                                                :Traffic:London:
    ID: 07058108.wav
    Length: 289
** Oxford Circus with pedestrians.                                                                                :Traffic:Motor:With Pedestrians:
    ID: 07058107.wav
    Length: 292
** Main road Shepherd's Bush - occasionally heavy.                                                                                :Traffic:Motor:City:
    ID: 07058106.wav
    Length: 290
** Knightsbridge.                                                                                :Traffic:Motor:City:
    ID: 07058105.wav
    Length: 179
** Westminster Bridge.                                                                                :Traffic:Motor:City:
    ID: 07058104.wav
    Length: 187
** Trafalgar Square with fountains playing.                                                                                :Fountains:
    ID: 07058103.wav
    Length: 190
** Starting in pairs - Junior TT 350cc machines, Isle of Man Tourist trophy race 1967.                                                                                :Motorcycles:Racing:
    ID: 07058102.wav
    Length: 62
** Atmosphere in pits before start - Junior TT 350cc machines, Isle of Man Tourist trophy race 1967.                                                                                :Motorcycles:Racing:
    ID: 07058101.wav
    Length: 75
** Starting in pairs at 10 sec. intervals - 125cc machines, Isle of Man Tourist trophy race 1967.                                                                                :Motorcycles:Racing:
    ID: 07058100.wav
    Length: 110
** Atmosphere in pits before start - 125cc machines, Isle of Man Tourist trophy race 1967.                                                                                :Motorcycles:Racing:
    ID: 07058099.wav
    Length: 119
** Heavy wheeled tractor, passing slowly.                                                                                :Tractors:
    ID: 07058098.wav
    Length: 134
** Tractor, passing slowly.                                                                                :Tractors:
    ID: 07058097.wav
    Length: 20
** Caterpillar road tractor towing, passing slowly.                                                                                :Tractors:Caterpillar:
    ID: 07058096.wav
    Length: 135
** 1 lorry passing slowly.                                                                                :Lorries:Passing:
    ID: 07058095.wav
    Length: 55
** 1 lorry passing slowly.                                                                                :Lorries:Passing:
    ID: 07058094.wav
    Length: 34
** 1 lorry passing slowly.                                                                                :Lorries:Passing:
    ID: 07058093.wav
    Length: 34
** 2 lorries passing slowly.                                                                                :Lorries:Passing:
    ID: 07058092.wav
    Length: 45
** 1 lorry passing slowly.                                                                                :Lorries:Passing:
    ID: 07058091.wav
    Length: 27
** 1 lorry passing slowly.                                                                                :Lorries:Passing:
    ID: 07058090.wav
    Length: 28
** 1 lorry passing slowly.                                                                                :Lorries:Passing:
    ID: 07058089.wav
    Length: 21
** Motor traffic at bust crossroads - traffic lights with filter lane.                                                                                :Traffic:Motor:Crossroads:
    ID: 07058088.wav
    Length: 366
** Motor traffic entering roundabout.                                                                                :Traffic:Motor:Roundabouts:
    ID: 07058087.wav
    Length: 192
** Motor traffic leaving roundabout.                                                                                :Traffic:Motor:Roundabouts:
    ID: 07058086.wav
    Length: 189
** Traffic entering & leaving, London Airport road tunnel 1958.                                                                                :Traffic:Motor:Tunnels:
    ID: 07058085.wav
    Length: 175
** General traffic atmosphere, London Airport road tunnel 1958.                                                                                :Traffic:Motor:Tunnels:
    ID: 07058084.wav
    Length: 174
** Traffic entering & leaving, Dartford Tunnel 1968.                                                                                :Traffic:Motor:Tunnels:
    ID: 07058083.wav
    Length: 172
** General traffic atmosphere, Dartford Tunnel 1968.                                                                                :Traffic:Motor:Tunnels:
    ID: 07058082.wav
    Length: 170
** Single horn - car stationary, Dartford Tunnel 1968.                                                                                :Cars:Horns:
    ID: 07058081.wav
    Length: 9
** Car approach - with horn, stop, depart. Dartford Tunnel, 1968.                                                                                :Cars:Horns:
    ID: 07058080.wav
    Length: 59
** Car approach & pass with horn. Dartford tunnel, 1968.                                                                                :Cars:Horns:
    ID: 07058079.wav
    Length: 35
** Victor 2000 entering - passing vehicles, Dartford tunnel, 1968.                                                                                :Traffic:Motor:Tunnels:
    ID: 07058078.wav
    Length: 133
** Traffic on the M1, 1969 - mid perspective, use at low level.                                                                                :Traffic:Motor:Motorways:
    ID: 07058077.wav
    Length: 358
** Traffic on the M1, 1969 - close perspective.                                                                                :Traffic:Motor:Motorways:
    ID: 07058076.wav
    Length: 381
** Traffic at night - distant trains passing over bridge.                                                                                :Traffic:Motor:Night:
    ID: 07058075.wav
    Length: 330
** Children playing in London street - car doors, traffic.                                                                                :Children:Playing:
    ID: 07058074.wav
    Length: 143
** Traffic moving through snow - use at low level.                                                                                :Traffic:Motor:Snow:
    ID: 07058073.wav
    Length: 48
** Traffic moving through snow - use at low level.                                                                                :Traffic:Motor:Snow:
    ID: 07058072.wav
    Length: 32
** Traffic moving through snow - use at low level.                                                                                :Traffic:Motor:Snow:
    ID: 07058071.wav
    Length: 54
** Quiet village - birds and light traffic.                                                                                :Villages:
    ID: 07058070.wav
    Length: 179
** Starting-up procedure, exterior.                                                                                :Aircraft:Lightning:
    ID: 07058069.wav
    Length: 194
** 26 passing over, exterior.                                                                                :Aircraft:Lightning:
    ID: 07058068.wav
    Length: 37
** 1 passing over, exterior.                                                                                :Aircraft:Lightning:
    ID: 07058067.wav
    Length: 56
** Several Lightnings landing, exterior.                                                                                :Aircraft:Lightning:
    ID: 07058066.wav
    Length: 132
** Landing, exterior.                                                                                :Aircraft:Lightning:
    ID: 07058065.wav
    Length: 18
** 26 Lightnings take off, exterior.                                                                                :Aircraft:Lightning:
    ID: 07058064.wav
    Length: 129
** Taxi & take off, exterior.                                                                                :Aircraft:Lightning:
    ID: 07058063.wav
    Length: 116
** Airfield atmosphere - no jets.                                                                                :Airports:Airfields:
    ID: 07058062.wav
    Length: 172
** Descend, land, taxi, switch off (interior).                                                                                :Aircraft:De Havilland Dove:
    ID: 07058061.wav
    Length: 227
** Engines, run up, taxi, take off, climb (interior).                                                                                :Aircraft:De Havilland Dove:
    ID: 07058060.wav
    Length: 269
** Passing overhead.                                                                                :Aircraft:De Havilland Dove:
    ID: 07058059.wav
    Length: 37
** Taxi to close-up, rev, switch off (exterior).                                                                                :Aircraft:De Havilland Dove:
    ID: 07058058.wav
    Length: 93
** Landing (exterior).                                                                                :Aircraft:De Havilland Dove:
    ID: 07058057.wav
    Length: 44
** Taxi up and away - take off (exterior).                                                                                :Aircraft:De Havilland Dove:
    ID: 07058056.wav
    Length: 199
** General airfield atmosphere - aircraft revving & taking off.                                                                                :Airports:Airfields:
    ID: 07058055.wav
    Length: 269
** Passing overhead (4 piston-engined aircraft, exterior).                                                                                :Aircraft:Shackleton:
    ID: 07058054.wav
    Length: 120
** Taxi & switch off (4 piston-engined aircraft, exterior).                                                                                :Aircraft:Shackleton:
    ID: 07058053.wav
    Length: 120
** Landing to mid-distance (4 piston-engined aircraft, exterior).                                                                                :Aircraft:Shackleton:
    ID: 07058052.wav
    Length: 57
** Take off (4 piston-engined aircraft, exterior).                                                                                :Aircraft:Shackleton:
    ID: 07058051.wav
    Length: 54
** Constant flight (4 piston-engined aircraft, interior).                                                                                :Aircraft:Shackleton:
    ID: 07058050.wav
    Length: 72
** Descent & landing (4 piston-engined aircraft, interior).                                                                                :Aircraft:Shackleton:
    ID: 07058049.wav
    Length: 165
** Take off & climb (4 piston-engined aircraft, interior).                                                                                :Aircraft:Shackleton:
    ID: 07058048.wav
    Length: 180
** Commence & continues to taxi (4 piston-engined aircraft, interior).                                                                                :Aircraft:Shackleton:
    ID: 07058047.wav
    Length: 142
** Start & run up engines(4 piston-engined aircraft, interior).                                                                                :Aircraft:Shackleton:
    ID: 07058046.wav
    Length: 180
** Start engines & splutter out (4 piston-engined aircraft, interior).                                                                                :Aircraft:Shackleton:
    ID: 07058045.wav
    Length: 9
** Atmosphere at an RAF station.                                                                                :Airports:Airfields:
    ID: 07058044.wav
    Length: 262
** Passing overhead.                                                                                :Aircraft:V-Bomber:
    ID: 07058043.wav
    Length: 35
** Landing.                                                                                :Aircraft:V-Bomber:
    ID: 07058042.wav
    Length: 34
** Taxi to close-up and switch off.                                                                                :Aircraft:V-Bomber:
    ID: 07058041.wav
    Length: 205
** Take off.                                                                                :Aircraft:V-Bomber:
    ID: 07058040.wav
    Length: 84
** Emergency start-up.                                                                                :Aircraft:V-Bomber:
    ID: 07058039.wav
    Length: 210
** Start-up procedure - exterior.                                                                                :Aircraft:V-Bomber:
    ID: 07058038.wav
    Length: 270
** Single pneumatic drill with starts and stops.                                                                                :Drills:Pneumatic:
    ID: 07058037.wav
    Length: 120
** Wall collapsing.                                                                                :Demolition:
    ID: 07058036.wav
    Length: 19
** Wood crushed.                                                                                :Demolition:
    ID: 07058035.wav
    Length: 15
** Wood splintered.                                                                                :Demolition:
    ID: 07058034.wav
    Length: 63
** Wood crunched.                                                                                :Demolition:
    ID: 07058033.wav
    Length: 9
** Wood crunched.                                                                                :Demolition:
    ID: 07058032.wav
    Length: 10
** Tree falling.                                                                                :Tree Felling:
    ID: 07058031.wav
    Length: 8
** Tree falling.                                                                                :Tree Felling:
    ID: 07058030.wav
    Length: 11
** Tree falling.                                                                                :Tree Felling:
    ID: 07058029.wav
    Length: 7
** Chopping tree.                                                                                :Axes:
    ID: 07058028.wav
    Length: 60
** Wood splintering.                                                                                :Wood:Crashes:
    ID: 07058027.wav
    Length: 25
** Axe blows on door.                                                                                :Axes:
    ID: 07058026.wav
    Length: 26
** Shouldering door.                                                                                :Doors:
    ID: 07058025.wav
    Length: 30
** 4 wheel drive vibrating roller.                                                                                :Excavators:
    ID: 07058024.wav
    Length: 185
** JCB excavator levelling and excavating.                                                                                :Excavators:
    ID: 07058023.wav
    Length: 187
** Dumping material.                                                                                :Demolition:
    ID: 07058022.wav
    Length: 174
** Gravel suction pump, medium perspective.                                                                                :Pumps:
    ID: 07058021.wav
    Length: 180
** Gravel suction pump.                                                                                :Pumps:
    ID: 07058020.wav
    Length: 193
** Excavator starts up, runs, stops.                                                                                :Excavators:
    ID: 07058019.wav
    Length: 209
** Bulldozer approach, stop, switch off.                                                                                :Bulldozers:
    ID: 07058018.wav
    Length: 40
** Bulldozer starts up, clears top soil, stops.                                                                                :Bulldozers:
    ID: 07058017.wav
    Length: 330
** Bulldozer demolishing house.                                                                                :Bulldozers:
    ID: 07058016.wav
    Length: 300
** Ball and chain demolition.                                                                                :Demolition:
    ID: 07058015.wav
    Length: 179
** Pile driver (slow in river bed).                                                                                :Demolition:
    ID: 07058014.wav
    Length: 172
** Pile driver.                                                                                :Demolition:
    ID: 07058013.wav
    Length: 196
** Pile driver - 3 ton drop hammer.                                                                                :Demolition:
    ID: 07058012.wav
    Length: 178
** Hammer and chisel on brick.                                                                                :Chisels:
    ID: 07058011.wav
    Length: 169
** Roar of falling debris.                                                                                :Demolition:
    ID: 07058010.wav
    Length: 50
** Falling stones (heavier).                                                                                :Demolition:
    ID: 07058009.wav
    Length: 16
** Falling stones.                                                                                :Demolition:
    ID: 07058008.wav
    Length: 14
** Wall collapsing.                                                                                :Demolition:
    ID: 07058007.wav
    Length: 10
** Crash of bricks.                                                                                :Demolition:
    ID: 07058006.wav
    Length: 7
** Shovelling hard, gravel soil.                                                                                :Digging:
    ID: 07058005.wav
    Length: 174
** Pickaxing hard, gravel soil.                                                                                :Demolition:
    ID: 07058004.wav
    Length: 149
** Shovelling & digging (exterior).                                                                                :Digging:
    ID: 07058003.wav
    Length: 253
** Hammering brick wall - falling debris.                                                                                :Demolition:
    ID: 07058002.wav
    Length: 137
** Cutting brick & stone with metal hand tools (interior).                                                                                :Demolition:
    ID: 07058001.wav
    Length: 180
** Cinema audience during interval.                                                                                :Crowds:Interior:Halls:
    ID: 07057087.wav
    Length: 249
** Audience gathering in foyer.                                                                                :Crowds:Interior:Halls:
    ID: 07057086.wav
    Length: 101
** Applause (longer burst)                                                                                :Crowds:Interior:Applause:
    ID: 07057085.wav
    Length: 23
** Applause (short burst)                                                                                :Crowds:Interior:Applause:
    ID: 07057084.wav
    Length: 11
** Audience in auditorium of provincial theatre (before perfomance)                                                                                :Crowds:Interior:
    ID: 07057083.wav
    Length: 153
** Two pairs of footsteps up to dress circle.                                                                                :Theatres:
    ID: 07057082.wav
    Length: 20
** Two pairs of footsteps from foyer up to gallery (with traffic at beginning)                                                                                :Theatres:
    ID: 07057081.wav
    Length: 54
** Flashpot - dry.                                                                                :Theatres:Photographic Flashpots:
    ID: 07057080.wav
    Length: 1
** Flashpot - deeper note (with reverb)                                                                                :Theatres:Photographic Flashpots:
    ID: 07057079.wav
    Length: 2
** Flashpot as used in Victorian period (with reverb)                                                                                :Theatres:Photographic Flashpots:
    ID: 07057078.wav
    Length: 1
** Revolver shot (simulated)                                                                                :Theatres:Special Effects:
    ID: 07057077.wav
    Length: 2
** Gatling gun (simulated)                                                                                :Theatres:Special Effects:
    ID: 07057076.wav
    Length: 21
** Cannon fire (simulated)                                                                                :Theatres:Special Effects:
    ID: 07057075.wav
    Length: 25
** Railway simulating machine running faster.                                                                                :Theatres:Special Effects:
    ID: 07057074.wav
    Length: 33
** Railway simulating machine                                                                                :Theatres:Special Effects:
    ID: 07057073.wav
    Length: 33
** Wind machine                                                                                :Weather:Wind:
    ID: 07057072.wav
    Length: 123
** Three thunder claps simulated by rolling cannon ball (as used in Elizabethan theatre)                                                                                :Theatres:Special Effects:
    ID: 07057071.wav
    Length: 33
** Reefer curtain with rings (heard from stage)                                                                                :Theatres:Stage Mechanisms:
    ID: 07057070.wav
    Length: 17
** Electrically operated reefer curtain (heard from audience)                                                                                :Theatres:Stage Mechanisms:
    ID: 07057069.wav
    Length: 31
** Hemp flying.                                                                                :Theatres:Stage Mechanisms:
    ID: 07057068.wav
    Length: 53
** Noise on stage (heard from beneath stage)                                                                                :Theatres:Stage Mechanisms:
    ID: 07057067.wav
    Length: 53
** Bridge wound down.                                                                                :Theatres:Stage Mechanisms:
    ID: 07057066.wav
    Length: 14
** Bridge wound up.                                                                                :Theatres:Stage Mechanisms:
    ID: 07057065.wav
    Length: 15
** Trap opened all the way.                                                                                :Theatres:Stage Mechanisms:
    ID: 07057064.wav
    Length: 2
** Trap closed up.                                                                                :Theatres:Stage Mechanisms:
    ID: 07057063.wav
    Length: 2
** Trap opened (near)                                                                                :Theatres:Stage Mechanisms:
    ID: 07057062.wav
    Length: 4
** Trap opened, person emerges                                                                                :Theatres:Stage Mechanisms:
    ID: 07057061.wav
    Length: 3
** Trap door opened (for an object)                                                                                :Theatres:Stage Mechanisms:
    ID: 07057060.wav
    Length: 3
** Trap door opened (from 10 feet away).                                                                                :Theatres:Stage Mechanisms:
    ID: 07057059.wav
    Length: 3
** Sloth opened, sent up, brought back down.                                                                                :Theatres:Stage Mechanisms:
    ID: 07057058.wav
    Length: 23
** Geni trap lowered onto stage.                                                                                :Theatres:Stage Mechanisms:
    ID: 07057057.wav
    Length: 27
** Geni trap lowered                                                                                :Theatres:Stage Mechanisms:
    ID: 07057056.wav
    Length: 34
** Geni trap opening                                                                                :Theatres:Stage Mechanisms:
    ID: 07057055.wav
    Length: 23
** Devon market - 1976 (1M3, reprocessed)                                                                                :Markets:Devon:
    ID: 07057054.wav
    Length: 361
** Aylesbury market, Buckinghamshire - atmosphere with speech, traffic and footsteps - 1981 (2C2, reprocessed)                                                                                :Markets:
    ID: 07057053.wav
    Length: 362
** London street market - 1976 (1M3, reprocessed)                                                                                :London:
    ID: 07057052.wav
    Length: 362
** Covent Garden Market, London - lorries arriving, voices and movement (1M1, reprocessed)                                                                                :London:
    ID: 07057051.wav
    Length: 287
** Berwick Street Market, London - atmosphere with speech, coins and footsteps - 1981 (2C2, reprocessed)                                                                                :London:
    ID: 07057050.wav
    Length: 362
** Berwick Street Market, London -  with footsteps, chatter, coins and tills - 1972 (2C1, reprocessed)                                                                                :London:
    ID: 07057049.wav
    Length: 249
** Large crowd cheers continuously  - 1966 (94A, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057048.wav
    Length: 151
** Girls screaming in street, with traffic and horns - 1966 (63C, processed)                                                                                :Girls:
    ID: 07057047.wav
    Length: 92
** Girls screaming in street, with much movement (running feet) and general excitement - 1966 (63C, reprocessed)                                                                                :Girls:
    ID: 07057046.wav
    Length: 217
** Mixed excited chatter with laughter and occasional distinct speech, constant background  - 1967 (40C, reprocessed)                                                                                :Crowds:Exterior:Chatter:
    ID: 07057045.wav
    Length: 240
** Applause of mixed outdoor crowd with atmosphere at Henley Regatta - 1975 (2C7, reprocessed)                                                                                :Crowds:Exterior:
    ID: 07057044.wav
    Length: 26
** Mixed outdoor crowd at Henley Regatta - close perspective (occasional indistinct PA and boats) ,1975 (2C7,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07057043.wav
    Length: 298
** Large cheer with whistles - July 1981 (2C9, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057042.wav
    Length: 28
** Large cheer with whistles - July 1981 (2C9,reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057041.wav
    Length: 45
** Build up of cheering and whistling - July 1981 (2C9,reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057040.wav
    Length: 60
** Orders shouted, small cheer - July 1981 (2C9,reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057039.wav
    Length: 33
** Orders shouted, carriage procession arrives, cheers - July 1981 (2C9, reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057038.wav
    Length: 102
** Crowds outside St.Paul's Cathedral at the wedding of The Prince of Wales - orders shouted, carriage procession arrives, cheers - July 1981 (2C1,reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057037.wav
    Length: 52
** Large crowd outside St Paul's Cathedral at wedding of HRH Prince of Wales - mid-distant perspective - July 1981 (2C9,reprocessed)                                                                                :Weddings:
    ID: 07057036.wav
    Length: 357
** Chant of "We want the Queen" (rec. Silver Jubilee - June 1977) (2C8,reprocessed)                                                                                :London:Buckingham Palace:
    ID: 07057035.wav
    Length: 18
** Cheer and applause - mid-distant perspective (rec. Silver Jubilee - June 1977) (2C8,reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057034.wav
    Length: 19
** Cheers, whistles and applause - mid-distant perspective (rec. Silver Jubilee - June 1977) (2C8,reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057033.wav
    Length: 75
** Two cheers - mid-distant perspective (rec. Silver Jubilee - June 1977) (2C8,reprocessed)                                                                                :Crowds:Exterior:Cheering:
    ID: 07057032.wav
    Length: 8
** Subdued crowd - close perspective (rec. Silver Jubilee - June 1977) (2C8,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07057031.wav
    Length: 210
** Large subdued crowd - mid-distant perspective (rec. Silver Jubilee - June 1977) (2C8,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07057030.wav
    Length: 172
** Subdued crowds as horseguards pass - mid-distant perspective (rec. Silver Jubilee - June 1977) (2C8,reprocessed)                                                                                :Crowds:Exterior:
    ID: 07057029.wav
    Length: 72
** Noisy crowd, some footsteps - distant band plays National Anthem at 1'05.,mid-distant perspective (rec. Silver Jubilee - June 1977) (2C8, reprocessed)                                                                                :Crowds:Exterior:
    ID: 07057028.wav
    Length: 113
** Applause at LE show - 1981 (1C15,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057027.wav
    Length: 26
** Laughter at LE show - 1981 (1C15,reprocessed)                                                                                :Crowds:Interior:Laughter:
    ID: 07057026.wav
    Length: 4
** Laughter and applause at LE show - 1981 (1C15,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057025.wav
    Length: 23
** Laughter and applause at LE show - 1981 (1C15,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057024.wav
    Length: 9
** Audience leaving auditorium, at 2'25 doors being closed - 1981 (1C15,reprocessed)                                                                                :London:Broadcasting House:
    ID: 07057023.wav
    Length: 189
** Concert Hall - atmosphere of small audience as auditorium gradually fills - 1981 (1Cl5,reprocessed)                                                                                :London:Broadcasting House:
    ID: 07057022.wav
    Length: 335
** Atmosphere, with some quiet tuning - 1972 (1C11,reprocessed)                                                                                :Orchestras:
    ID: 07057021.wav
    Length: 213
** Applause, at 0'19" quiet - 1972 (1C11,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057020.wav
    Length: 26
** Atmosphere, at 1'00" applause, at 1'22" atmosphere, at 1'30" violin tuning to piano - 1972 (1C11,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057019.wav
    Length: 116
** Applause, at 0'26" quiet - 1972 (1C11,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057018.wav
    Length: 33
** Full orchestra tuning, at 3'04" applause for conductor - 1972 (1C11,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057017.wav
    Length: 203
** Applause, at 1'00" atmosphere - 1972 (1C11,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057016.wav
    Length: 140
** Closing applause, applause swells from time to time, 'encore', at 4'53" atmosphere - 1972 (1C10,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057015.wav
    Length: 305
** Applause, at 0'14" atmosphere, settling down, score rustles, at 0'25" quartet tuning up, quiet - 1972 (1C10,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057014.wav
    Length: 62
** Royal Festival Hall - closing applause - 1973 (1C10,reprocessed)                                                                                :Crowds:Interior:Applause:
    ID: 07057013.wav
    Length: 73
** Atmosphere, distant sound of 5 min. warning gong, people walking about before start of concert - 1973 (1C10)                                                                                :London:Royal Festival Hall:
    ID: 07057012.wav
    Length: 299
** Applause at end of item with shouts of 'more' and atmosphere with tuning - 1972 (1C7,reprocessed)                                                                                :Applause:Interior:
    ID: 07057011.wav
    Length: 133
** Final applause, some cheers and 'bravos'into atmos. - 1972 (1C7,reprocessed)                                                                                :Applause:Interior:
    ID: 07057010.wav
    Length: 208
** Applause into atmosphere - 1972 (1C7,reprocessed)                                                                                :Applause:Interior:
    ID: 07057009.wav
    Length: 54
** Atmosphere, applause into atmosphere - 1972 (1C7,reprocessed)                                                                                :Applause:Interior:
    ID: 07057008.wav
    Length: 29
** Enthusiastic applause with cheers and 'bravos'- 1972 (1C7,reprocessed)                                                                                :Applause:Interior:
    ID: 07057007.wav
    Length: 59
** Chamber orchestra tuning with fountain and chatter - 1972 (1C7,reprocessed)                                                                                :Fountains:
    ID: 07057006.wav
    Length: 124
** Symphony orchestra tuning, at 2'50" applause for leader, at 3'38", applause and cheers for conductor, then quiet atmos. - 1972 (1C7,reprocessed)                                                                                :Applause:Interior:
    ID: 07057005.wav
    Length: 247
** Applause, at 0'51" tuning strings, at 1'23" applause - 1972 (1C6,reprocessed)                                                                                :Applause:Interior:
    ID: 07057004.wav
    Length: 116
** Atmosphere with fountain and programme seller - 1972 (1C6,reprocessed)                                                                                :Fountains:
    ID: 07057003.wav
    Length: 300
** Atmosphere before concert with tuning (symphony orchestra), at 1'08" applause for leader, at 1'26" applause for conductor, at 1'48" quiet atmosphere to end - 1972 (1C6,reprocessed)                                                                                :Applause:Interior:
    ID: 07057002.wav
    Length: 118
** Atmosphere before concert - 1972 (1C6,reprocessed)                                                                                :London:Royal Albert Hall:
    ID: 07057001.wav
    Length: 299
** Grocer shop.                                                                                :Shops:Greengrocers:
    ID: 07056116.wav
    Length: 252
** Butcher shop.                                                                                :Shops:Butchers:
    ID: 07056115.wav
    Length: 252
** Fish & chip shop.                                                                                :Restaurants:
    ID: 07056114.wav
    Length: 244
** Supermarket food area.                                                                                :Shops:Supermarkets:
    ID: 07056113.wav
    Length: 252
** Supermarket till area.                                                                                :Cash Registers:
    ID: 07056112.wav
    Length: 252
** Large motorway service station.                                                                                :Cafes:
    ID: 07056111.wav
    Length: 252
** Small motorway service station.                                                                                :Cafes:
    ID: 07056110.wav
    Length: 218
** Cellar wine bar - crowded at lunchtime.                                                                                :Public Houses:Crowds:
    ID: 07056109.wav
    Length: 252
** Large restaurant - 100 people.                                                                                :Restaurants:
    ID: 07056108.wav
    Length: 252
** Small restaurant - 10 people.                                                                                :Restaurants:
    ID: 07056107.wav
    Length: 252
** Large hotel kitchen - food collection area.                                                                                :Hotels:
    ID: 07056106.wav
    Length: 246
** Large hotel kitchen - food preparation area.                                                                                :Hotels:
    ID: 07056105.wav
    Length: 252
** Large restaurant kitchen.                                                                                :Restaurants:
    ID: 07056104.wav
    Length: 252
** Small restaurant kitchen.                                                                                :Restaurants:
    ID: 07056103.wav
    Length: 252
** Canteen kitchen.                                                                                :Canteens:
    ID: 07056102.wav
    Length: 229
** Large domestic kitchen.                                                                                :Kitchens:
    ID: 07056101.wav
    Length: 252
** Small domestic kitchen.                                                                                :Kitchens:
    ID: 07056100.wav
    Length: 252
** General atmosphere at printers rec. near the path rollers at a large printing company.                                                                                :Industry:Printing:
    ID: 07056099.wav
    Length: 197
** A binding machine (Muller Martini) for assembling magazines, recorded at a large printing company.                                                                                :Industry:Printing:
    ID: 07056098.wav
    Length: 253
** Newspaper folding machine, large printing company (rec. 1998).                                                                                :Industry:Printing:
    ID: 07056097.wav
    Length: 231
** Pulp breaker; slow down and switch off, 1970.                                                                                :Papermaking:
    ID: 07056096.wav
    Length: 72
** Pulp breaker, 1970.                                                                                :Papermaking:
    ID: 07056095.wav
    Length: 89
** Pulp breaker; switch on and run, 1970.                                                                                :Papermaking:
    ID: 07056094.wav
    Length: 183
** Vat house, 1970.                                                                                :Papermaking:
    ID: 07056093.wav
    Length: 183
** Pressing room, 1970.                                                                                :Industry:Papermaking:
    ID: 07056092.wav
    Length: 187
** Pulp grinding, 1970.                                                                                :Industry:Papermaking:
    ID: 07056091.wav
    Length: 120
** Boiler rotated, 1970.                                                                                :Industry:Papermaking:
    ID: 07056090.wav
    Length: 122
** Boiler lid fitted, 1970.                                                                                :Industry:Papermaking:
    ID: 07056089.wav
    Length: 170
** Rag cutting: start; run; stop.                                                                                :Industry:Papermaking:
    ID: 07056088.wav
    Length: 202
** Wohlenberg Flying Carpet guillotine, 1970.                                                                                :Industry:Papermaking:
    ID: 07056087.wav
    Length: 184
** Air knife coater, 1970.                                                                                :Industry:Papermaking:
    ID: 07056086.wav
    Length: 190
** Atmosphere in yard, 1970.                                                                                :Industry:Papermaking:
    ID: 07056085.wav
    Length: 191
** Hand sorting; rejecting imperfect sheets, 1970.                                                                                :Industry:Papermaking:
    ID: 07056084.wav
    Length: 185
** Changing reel centre, 1970.                                                                                :Industry:Papermaking:
    ID: 07056083.wav
    Length: 145
** Dry end of realer, 1970.                                                                                :Industry:Papermaking:
    ID: 07056082.wav
    Length: 134
** Sludge pump with start and stop, 1970.                                                                                :Industry:Papermaking:
    ID: 07056081.wav
    Length: 88
** Machine house, 1970.                                                                                :Industry:Papermaking:
    ID: 07056080.wav
    Length: 241
** Machine house, 1970.                                                                                :Industry:Papermaking:
    ID: 07056079.wav
    Length: 140
** Shaft room, 1970.                                                                                :Industry:Papermaking:
    ID: 07056078.wav
    Length: 119
** Clay storage chest, 1970.                                                                                :Industry:Papermaking:
    ID: 07056077.wav
    Length: 119
** Clay slurry ram pump, 1970.                                                                                :Industry:Papermaking:
    ID: 07056076.wav
    Length: 119
** Pulp machine, 1970.                                                                                :Industry:Papermaking:
    ID: 07056075.wav
    Length: 118
** Several potchers, 1970.                                                                                :Industry:Papermaking:
    ID: 07056074.wav
    Length: 119
** Potcher (pulp maker), 1970.                                                                                :Industry:Papermaking:
    ID: 07056073.wav
    Length: 115
** Airport waiting lounge (Cape Town International Airport) - 100 persons waiting for flight with light jet engine sound in background.                                                                                :Africa:South Africa:
    ID: 07056072.wav
    Length: 270
** Botanical Gardens (Cape Town) - with quiet strolling pedestrians.                                                                                :Parks:
    ID: 07056071.wav
    Length: 242
** Open air flea market (Cape Town) - busy bustling market with sellers crying out.                                                                                :Africa:South Africa:
    ID: 07056070.wav
    Length: 270
** Cape Town - wide perspective, cicadas, gulls and traffic (night time).                                                                                :Atmospheres:Night:
    ID: 07056069.wav
    Length: 277
** Cape Town (the Waterfront developmet) - noisy pedestrians enjoying themselves (daytime).                                                                                :Crowds:Exterior:
    ID: 07056068.wav
    Length: 262
** Delicatessen fridge noise plus cuctomers and diners chatting and buying.                                                                                :Africa:South Africa:
    ID: 07056067.wav
    Length: 263
** Small town in the countryside (Bredasdorph) - light traffic, pedestrians and whistling wind.                                                                                :Traffic:Motor:Country Towns:
    ID: 07056066.wav
    Length: 270
** Indian ocean surf - recorded close to the Cape of Good Hope.                                                                                :Surf:
    ID: 07056065.wav
    Length: 258
** Campsite (Naukluft Mountains) - light wind in trees, 7am, sound of birds with occaisional people.                                                                                :Africa:Namibia:
    ID: 07056064.wav
    Length: 270
** Swimming pool atmosphere - several people enjoying a pool in Etosha Game Reserve, Namibia.                                                                                :Swimming Pools:
    ID: 07056063.wav
    Length: 270
** Skeleton coast surf (Atlantic Ocean).                                                                                :Surf:
    ID: 07056062.wav
    Length: 230
** Quiet street corner (Swakopmund) - traffic, children, pedestrians and distant ocean surf.                                                                                :Africa:Namibia:
    ID: 07056061.wav
    Length: 270
** Light construction in pedestrian centre (Swakopmund) - six workers and passing pedestrians.                                                                                :Building Construction:
    ID: 07056060.wav
    Length: 268
** Large supermarket, crowded, with the sound of tills.                                                                                :Shops:Supermarkets:
    ID: 07056059.wav
    Length: 270
** The First National Bank main customer area.                                                                                :Banks:
    ID: 07056058.wav
    Length: 270
** Windhoek (capital city) - street with traffic and pedestrians.                                                                                :Atmospheres:Cities:
    ID: 07056057.wav
    Length: 270
** Inside Billingsgate fish market.                                                                                :Markets:Fish:
    ID: 07056056.wav
    Length: 170
** General atmosphere in indoor shopping centre, Birmingham.                                                                                :Shops:Shopping Precincts:
    ID: 07056055.wav
    Length: 132
** Outdoor rag market (with "action" at end for use if showing a film crew).                                                                                :Markets:Birmingham:
    ID: 07056054.wav
    Length: 204
** Outdoor market, general atmosphere with preacher.                                                                                :Markets:Birmingham:
    ID: 07056053.wav
    Length: 217
** China shop outside Bullring market.                                                                                :Markets:Birmingham:
    ID: 07056052.wav
    Length: 217
** China shop at Bullring market.                                                                                :Markets:Birmingham:
    ID: 07056051.wav
    Length: 174
** General wares sold at Bullring market (use at low level due to hiss).                                                                                :Markets:Birmingham:
    ID: 07056050.wav
    Length: 203
** Fish, meat and poultry at Bullring market.                                                                                :Markets:Birmingham:
    ID: 07056049.wav
    Length: 200
** Auctioning pigs at country market, Winslow, Bucks.                                                                                :Animals:Farm:Pigs:
    ID: 07056048.wav
    Length: 316
** Auctioning beef cattle at country market, Winslow, Bucks.                                                                                :Animals:Farm:Cattle:
    ID: 07056047.wav
    Length: 262
** General atmosphere.                                                                                :Markets:Pontypridd, Wales:
    ID: 07056046.wav
    Length: 303
** General atmosphere.                                                                                :Markets:Maidstone:
    ID: 07056045.wav
    Length: 213
** Plant stalls.                                                                                :Markets:Aylesbury:
    ID: 07056044.wav
    Length: 161
** General atmosphere.                                                                                :Markets:Aylesbury:
    ID: 07056043.wav
    Length: 231
** Lorries parking and unloading.                                                                                :Lorries:
    ID: 07056042.wav
    Length: 192
** General atmosphere with trolleys.                                                                                :Markets:London:
    ID: 07056041.wav
    Length: 189
** Flower hall.                                                                                :Markets:London:
    ID: 07056040.wav
    Length: 193
** Early morning porters and trolleys.                                                                                :Markets:London:
    ID: 07056039.wav
    Length: 373
** Farmland at night - Maropiu (NZ)                                                                                :Atmospheres:Night:
    ID: 07056038.wav
    Length: 210
** Small brook - Opapaka Bush Walk, Waitomo (NZ)                                                                                :Atmospheres:Night:
    ID: 07056037.wav
    Length: 283
** Duck pond - mixed farmland, Dannevirke (NZ)                                                                                :Birds:
    ID: 07056036.wav
    Length: 279
** Woodland gully, Shakespeare Regional Park, nr Aukland (NZ)                                                                                :Atmospheres:Woodland:
    ID: 07056035.wav
    Length: 128
** Small holiday park, Upper Hutt, nr Wellington (NZ)                                                                                :New Zealand:Natural World:
    ID: 07056034.wav
    Length: 248
** Rural graden, Maropiu, nr Dargaville (NZ)                                                                                :New Zealand:Natural World:
    ID: 07056033.wav
    Length: 147
** Wind in wattle trees - wattle track, Tiritiri Matangi Island (NZ)                                                                                :Weather:Wind:
    ID: 07056032.wav
    Length: 211
** Light rain in woodland Nga Manu Sanctuary (NZ)                                                                                :Atmospheres:Woodland:
    ID: 07056031.wav
    Length: 269
** Marble terrace, Waimangu Volcanic Valley (NZ)                                                                                :New Zealand:Natural World:
    ID: 07056030.wav
    Length: 125
** Woodland - summer afternoon, Waimangu Volcanic Valley                                                                                :Atmospheres:Woodland:
    ID: 07056029.wav
    Length: 125
** Tui & bell birds feeding in rata trees, Kapiti Island.                                                                                :Birds:
    ID: 07056028.wav
    Length: 168
** Bush atmosphere, Kapiti Island, NZ (motorboat in distance)                                                                                :Boats:Motor:
    ID: 07056027.wav
    Length: 251
** Tui & Weka in bush, Kapiti Island, NZ.                                                                                :New Zealand:Natural World:
    ID: 07056026.wav
    Length: 251
** Thunderstorm passing - forest clearing, Mapara reserve, NZ.                                                                                :Atmospheres:Forests:
    ID: 07056025.wav
    Length: 480
** Dawn atmosphere, cocks crowing, hens clucking, peacocks - Aviary, Dannevirke                                                                                :Atmospheres:Dawn:
    ID: 07056024.wav
    Length: 216
** Holiday park near farmland, Dannevirke, NZ.                                                                                :Atmospheres:Dawn:
    ID: 07056023.wav
    Length: 258
** Woodland - roadside, Waitomo, New Zealand.                                                                                :Atmospheres:Dawn:
    ID: 07056022.wav
    Length: 216
** Dawn chorus - open farmland surrounded by trees, Waitomo, New Zealand.                                                                                :Atmospheres:Dawn:
    ID: 07056021.wav
    Length: 232
** Dawn chorus - Tiritiri Matangi Island, New Zealand.                                                                                :Atmospheres:Dawn:
    ID: 07056020.wav
    Length: 220
** Light sea as heard from Halliards (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056019.wav
    Length: 263
** Average sea as heard from inside sail locker (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056018.wav
    Length: 280
** Head sails flapping with wash (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056017.wav
    Length: 269
** Light ripples as heard from deck (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056016.wav
    Length: 271
** Wash as heard from Lee Scuppers (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056015.wav
    Length: 221
** Tacking (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056014.wav
    Length: 45
** Tackles clanking (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056013.wav
    Length: 47
** Sails flapping (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056012.wav
    Length: 52
** Average sea as heard from Lee Halliards (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056011.wav
    Length: 369
** Creaking and flapping boom in calm weather (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056010.wav
    Length: 209
** Average sea with wind whistling on Lee Rail (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056009.wav
    Length: 191
** Average sea as heard from Bowsprit, with sails flapping.                                                                                :Ships:Sailing:
    ID: 07056008.wav
    Length: 263
** Bow wave (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056007.wav
    Length: 240
** Bow wave as heard from lee quarter (STS Malcolm Miller).                                                                                :Ships:Sailing:
    ID: 07056006.wav
    Length: 265
** 'Trade winds', a Clipper sailing with wind and sea.                                                                                :Ships:Sailing:
    ID: 07056005.wav
    Length: 358
** 'Roaring forties', a Clipper sailing with wind and sea.                                                                                :Ships:Sailing:
    ID: 07056004.wav
    Length: 318
** Atmosphere in cabin (19ft cabin sloop).                                                                                :Ships:Sailing:
    ID: 07056003.wav
    Length: 287
** Lee no!" shouted in wind (19ft cabin sloop).                                                                                :Ships:Sailing:
    ID: 07056002.wav
    Length: 16
** Sailing against the wind (19ft cabin sloop).                                                                                :Ships:Sailing:
    ID: 07056001.wav
    Length: 240
** Mid-race with PA & passes at intervals (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055254.wav
    Length: 1607
** One car passes noisily (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055253.wav
    Length: 6
** Three cars pass (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055252.wav
    Length: 16
** Two cars pass (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055251.wav
    Length: 11
** One car passes (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055250.wav
    Length: 15
** Distant approach into many cars passing (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055249.wav
    Length: 114
** Cars revving engines, manouevreing into position, race begins. (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055248.wav
    Length: 62
** Many cars start up, continuous revving (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055247.wav
    Length: 62
** Cars returning to start position after false start, revving then switching off (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055246.wav
    Length: 119
** Many cars start up, drive off (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055245.wav
    Length: 101
** One car starts up. switches off (1994 Silverstone Grand Prix)                                                                                :Motor Racing:Formula 1:
    ID: 07055244.wav
    Length: 17
** exterior - start and reverse, stop and switch off (rec. near exhaust)                                                                                :Cars:Tyres on Gravel:Peugeot 208:
    ID: 07055243.wav
    Length: 26
** exterior - slow freewheeling in close perspective                                                                                :Cars:Tyres on Gravel:Peugeot 207:
    ID: 07055242.wav
    Length: 26
** exterior - freewheeling in close perspective                                                                                :Cars:Tyres on Gravel:Peugeot 206:
    ID: 07055241.wav
    Length: 27
** exterior - approach , stop and switch oft                                                                                :Cars:Tyres on Gravel:Peugeot 205:
    ID: 07055240.wav
    Length: 16
** interior - severe brake and skid, tickover to fade                                                                                :Cars:Skids, scrapes and stalls:Peugot 212:
    ID: 07055239.wav
    Length: 10
** interior - severe brake and skid, stalling engine                                                                                :Cars:Skids, scrapes and stalls:Peugot 211:
    ID: 07055238.wav
    Length: 6
** exterior - two attempts to start engine with stalls                                                                                :Cars:Skids, scrapes and stalls:Peugot 210:
    ID: 07055237.wav
    Length: 8
** exterior - start and stall engine                                                                                :Cars:Skids, scrapes and stalls:Peugot 209:
    ID: 07055236.wav
    Length: 6
** interior - start and stall engine                                                                                :Cars:Skids, scrapes and stalls:Peugot 208:
    ID: 07055235.wav
    Length: 5
** interior - start, series of tailed attempts to engage gear, with heavy revving                                                                                :Cars:Skids, scrapes and stalls:Peugot 207:
    ID: 07055234.wav
    Length: 25
** exterior - start and series of failed attempts to engage gear                                                                                :Cars:Skids, scrapes and stalls:Peugot 206:
    ID: 07055233.wav
    Length: 24
** exterior - fast approach and skid to stop, tickover to fade                                                                                :Cars:Skids, scrapes and stalls:Peugot 205:
    ID: 07055232.wav
    Length: 10
** exterior - slow pass right to left through puddle                                                                                :Cars:Wet weather driving:Peugeot 216:
    ID: 07055231.wav
    Length: 17
** interior - start into medium fast drive on wet road with lots of puddles, slow, stop, switch off                                                                                :Cars:Wet weather driving:Peugeot 215:
    ID: 07055230.wav
    Length: 90
** exterior - fast pass right to left through puddles                                                                                :Cars:Wet weather driving:Peugeot 214:
    ID: 07055229.wav
    Length: 10
** exterior - medium approach from right, splash through several puddles, stop, switch off                                                                                :Cars:Wet weather driving:Peugeot 213:
    ID: 07055228.wav
    Length: 14
** exterior - start and medium depart to left on wet road                                                                                :Cars:Wet weather driving:Peugeot 212:
    ID: 07055227.wav
    Length: 20
** exterior - medium approach from right, splash through puddle, stop, switch off                                                                                :Cars:Wet weather driving:Peugeot 211:
    ID: 07055226.wav
    Length: 12
** exterior - heavy continuous rain on roof of stationary car, heavy traffic passing                                                                                :Cars:Wet weather driving:Peugeot 210:
    ID: 07055225.wav
    Length: 90
** exterior - start, gear crunch, reverse towards mic, misfiring and depart to left                                                                                :Cars:Manoeuvres:Peugeot 226:
    ID: 07055224.wav
    Length: 32
** exterior - start and slow depart to right                                                                                :Cars:Manoeuvres:Peugeot 225:
    ID: 07055223.wav
    Length: 17
** exterior - medium speed pass left to right on cobbles                                                                                :Cars:Manoeuvres:Peugeot 224:
    ID: 07055222.wav
    Length: 24
** exterior - medium pass from right to left                                                                                :Cars:Manoeuvres:Peugeot 223:
    ID: 07055221.wav
    Length: 14
** exterior pass from left to right, sounding horn with doppler effect                                                                                :Cars:Manoeuvres:Peugeot 222:
    ID: 07055220.wav
    Length: 13
** exterior - medium approach from left, stop and switch off                                                                                :Cars:Manoeuvres:Peugeot 221:
    ID: 07055219.wav
    Length: 15
** exterior - fast approach from left, skid to stop, switch off                                                                                :Cars:Manoeuvres:Peugeot 220:
    ID: 07055218.wav
    Length: 14
** exterior - switch on, fast skidding departure to left                                                                                :Cars:Manoeuvres:Peugeot 219:
    ID: 07055217.wav
    Length: 16
** exterior - switch on and depart to right                                                                                :Cars:Manoeuvres:Peugeot 218:
    ID: 07055216.wav
    Length: 14
** interior - switch on and fast pull away, drive fast, slow and switch off                                                                                :Cars:Manoeuvres:Peugeot 217:
    ID: 07055215.wav
    Length: 37
** exterior - reverse pass left to right                                                                                :Cars:Manoeuvres:Peugeot 216:
    ID: 07055214.wav
    Length: 22
** exterior - reverse approach and switch off                                                                                :Cars:Manoeuvres:Peugeot 215:
    ID: 07055213.wav
    Length: 15
** interior - start, gear crunch, handbrake and slow reverse, tickover, switch off                                                                                :Cars:Manoeuvres:Peugeot 214:
    ID: 07055212.wav
    Length: 60
** interior - start, drive on cobbles in medium traffic, stop, switch off                                                                                :Cars:Manoeuvres:Peugeot 213:
    ID: 07055211.wav
    Length: 162
** interior - start, drive in busy town, occasional puddles, stop, switch off                                                                                :Cars:Manoeuvres:Peugeot 212:
    ID: 07055210.wav
    Length: 268
** interior - start, drive at medium speed on country road, occasional puddles, stop, switch off                                                                                :Cars:Manoeuvres:Peugeot 211:
    ID: 07055209.wav
    Length: 152
** interior - start, drive on wet, muddy in first and second gears, slow, switch off                                                                                :Cars:Manoeuvres:Peugeot 210:
    ID: 07055208.wav
    Length: 233
** interior - start, attempts to power out of muddy ditch, wheelspin, switch off                                                                                :Cars:Freewheeling and stuck:Peugeot 216:
    ID: 07055207.wav
    Length: 16
** exterior - start, attempts to power out of muddy ditch, wheelspin then drive away                                                                                :Cars:Freewheeling and stuck:Peugeot 215:
    ID: 07055206.wav
    Length: 37
** exterior - start, attempts to power out of muddy ditch with wheel spin, switch off                                                                                :Cars:Freewheeling and stuck:Peugeot 214:
    ID: 07055205.wav
    Length: 19
** interior - reversing and manoeuvring on muddy ground                                                                                :Cars:Freewheeling and stuck:Peugeot 213:
    ID: 07055204.wav
    Length: 54
** interior - downhill freewheel over rough ground and through puddles                                                                                :Cars:Freewheeling and stuck:Peugeot 212:
    ID: 07055203.wav
    Length: 98
** interior - slower freewheeling downhill                                                                                :Cars:Freewheeling and stuck:Peugeot 211:
    ID: 07055202.wav
    Length: 62
** interior - freewheeling downhill with brake squeal at end                                                                                :Cars:Freewheeling and stuck:Peugeot 210:
    ID: 07055201.wav
    Length: 46
** interior - attempts to start with very flat battery                                                                                :Cars:Flat Battery:Peugeot 210:
    ID: 07055200.wav
    Length: 27
** exterior - attempts to start with very flat battery; birdsong in background                                                                                :Cars:Flat Battery:Peugeot 209:
    ID: 07055199.wav
    Length: 17
** interior - single attempt to start engine                                                                                :Cars:Flat Battery:Peugeot 208:
    ID: 07055198.wav
    Length: 4
** interior - two attempts to start engine                                                                                :Cars:Flat Battery:Peugeot 207:
    ID: 07055197.wav
    Length: 9
** exterior - single attempt to start engine                                                                                :Cars:Flat Battery:Peugeot 206:
    ID: 07055196.wav
    Length: 3
** exterior - four attempts to start engine                                                                                :Cars:Flat Battery:Peugeot 205:
    ID: 07055195.wav
    Length: 14
** interior - switch on, squeaky continuous operation, switch off                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 215:
    ID: 07055194.wav
    Length: 60
** interior - gear stick jiggled in neutral                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 214:
    ID: 07055193.wav
    Length: 2
** exterior - nine short, angry blasts                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 213:
    ID: 07055192.wav
    Length: 4
** exterior - two horn blasts                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 212:
    ID: 07055191.wav
    Length: 1
** exterior - single short blast                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 211:
    ID: 07055190.wav
    Length: 1
** interior - twelve short, angry blasts                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 210:
    ID: 07055189.wav
    Length: 6
** interior - eight short, angry blasts                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 209:
    ID: 07055188.wav
    Length: 5
** interior - single horn blast                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 208:
    ID: 07055187.wav
    Length: 2
** interior - two short blasts                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 207:
    ID: 07055186.wav
    Length: 1
** interior - four short, angry blasts                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 206:
    ID: 07055185.wav
    Length: 3
** interior - five short, angry horn blasts                                                                                :Cars:Horns, Gearsticks and Wipers:Peugeot 205:
    ID: 07055184.wav
    Length: 3
** exterior - start, fierce revving and switch off                                                                                :Cars:Peugeot 205:Tickover:
    ID: 07055183.wav
    Length: 46
** exterior - start, tickover with misfires and poor running, switch off near exhaust)                                                                                :Cars:Peugeot 205:Tickover:
    ID: 07055182.wav
    Length: 73
** exterior - start with warm engine, steady tickover and switch off (rec. near exhaust)                                                                                :Cars:Peugeot 205:Tickover:
    ID: 07055181.wav
    Length: 69
** exterior - start with very cold engine, steady tickover and switch off (rec. near exhaust)                                                                                :Cars:Peugeot 205:Tickover:
    ID: 07055180.wav
    Length: 76
** interior - start, fierce revving and switch off                                                                                :Cars:Peugeot 205:Tickover:
    ID: 07055179.wav
    Length: 70
** interior - start, steady tickover and switch off                                                                                :Cars:Peugeot 205:Tickover:
    ID: 07055178.wav
    Length: 65
** interior - manual sunroof wound shut                                                                                :Cars:Doors, bonnets and windows:Peugeot 218:
    ID: 07055177.wav
    Length: 7
** interior - manual sunroof wound open                                                                                :Cars:Doors, bonnets and windows:Peugeot 217:
    ID: 07055176.wav
    Length: 7
** interior - manual sunroof shutter closed                                                                                :Cars:Doors, bonnets and windows:Peugeot 216:
    ID: 07055175.wav
    Length: 2
** interior - manual sunroof shutter opened                                                                                :Cars:Doors, bonnets and windows:Peugeot 215:
    ID: 07055174.wav
    Length: 3
** exterior - electric window, wound up                                                                                :Cars:Doors, bonnets and windows:Peugeot 214:
    ID: 07055173.wav
    Length: 5
** exterior - electric window, wound down                                                                                :Cars:Doors, bonnets and windows:Peugeot 213:
    ID: 07055172.wav
    Length: 4
** interior - electric window, wound up                                                                                :Cars:Doors, bonnets and windows:Peugeot 212:
    ID: 07055171.wav
    Length: 6
** interior - electric window, wound down                                                                                :Cars:Doors, bonnets and windows:Peugeot 211:
    ID: 07055170.wav
    Length: 4
** interior - manual window wound up                                                                                :Cars:Doors, bonnets and windows:Peugeot 210:
    ID: 07055169.wav
    Length: 3
** interior - manual window wound down                                                                                :Cars:Doors, bonnets and windows:Peugeot 209:
    ID: 07055168.wav
    Length: 5
** exterior - bonnet closed                                                                                :Cars:Doors, bonnets and windows:Peugeot 208:
    ID: 07055167.wav
    Length: 3
** exterior - bonnet opened with a creak                                                                                :Cars:Doors, bonnets and windows:Peugeot 207:
    ID: 07055166.wav
    Length: 4
** interior - bonnet closed, recorded inside car                                                                                :Cars:Doors, bonnets and windows:Peugeot 206:
    ID: 07055165.wav
    Length: 2
** interior - bonnet release activated from inside car                                                                                :Cars:Doors, bonnets and windows:Peugeot 205:
    ID: 07055164.wav
    Length: 2
** interior - seat belt taker off                                                                                :Cars:Entrances and exits:Peugeot 212:
    ID: 07055163.wav
    Length: 3
** interior - seat belt put on                                                                                :Cars:Entrances and exits:Peugeot 211:
    ID: 07055162.wav
    Length: 6
** exterior - two people exit car                                                                                :Cars:Entrances and exits:Peugeot 210:
    ID: 07055161.wav
    Length: 5
** exterior - two people enter car                                                                                :Cars:Entrances and exits:Peugeot 209:
    ID: 07055160.wav
    Length: 6
** exterior - one person exits car                                                                                :Cars:Entrances and exits:Peugeot 208:
    ID: 07055159.wav
    Length: 5
** exterior - one person enters car                                                                                :Cars:Entrances and exits:Peugeot 207:
    ID: 07055158.wav
    Length: 4
** interior - one person enters car                                                                                :Cars:Entrances and exits:Peugeot 206:
    ID: 07055157.wav
    Length: 6
** interior - one person exits from car                                                                                :Cars:Entrances and exits:Peugeot 205:
    ID: 07055156.wav
    Length: 6
** exterior - continuous alarm from mid distant perspective                                                                                :Cars:Alarms:Peugeot 208:
    ID: 07055155.wav
    Length: 63
** exterior - continuous alarm sounding, close perspective                                                                                :Cars:Alarms:Peugeot 207:
    ID: 07055154.wav
    Length: 64
** exterior - two bleeps from close perspective, as for disarming                                                                                :Cars:Alarms:Peugeot 206:
    ID: 07055153.wav
    Length: 2
** exterior - single bleep rec. from close perspective, as for arming                                                                                :Cars:Alarms:Peugeot 205:
    ID: 07055152.wav
    Length: 1
** General atmosphere (buttoner, seam pressers, finishers) in trouser factory.                                                                                :Industry:Clothing Manufacture:
    ID: 07055151.wav
    Length: 58
** Two overlocking machines, trouser facctory.                                                                                :Industry:Clothing Manufacture:
    ID: 07055150.wav
    Length: 49
